### ISSUE TITLE
When using @Multipart with a default Gson converter and sending a Date object, quotes are added to the value sent

### ISSUE THREAD

**Issue by jmickela** [square/retrofit#1000]
I create my Gson converter like this:

    Gson gson = new GsonBuilder()
                .setDateFormat("yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'SSS'Z'")
                .create();

The output of:
    String date = gson.toJson(new Date());

Will look like this (with the quotes included):

    "2015-08-06T19:37:14.000Z"

It appears that the value from Gson is accepted and just passed on when dates are encoded, which is what you want when sending JSON, since the date will need to be in quotes, but when sending Multipart data the extra quotes will be interpreted as part of the value, which will cause the date to fail validation on the remote end unless special case validators are written to handle this.

**Comment by swankjesse** [comment]
In your words: there's a difference between a date literal: `2015-08-06T19:37:14.000Z` and a JSON string literal that contains a date: `"2015-08-06T19:37:14.000Z"`. Seems like you don't want JSON for your Multipart value. You should configure your application that way.

**Comment by jmickela** [comment]
Then it would seem that this is an extension of this issue: https://github.com/square/retrofit/issues/763
Since I don't see a way to tell Retrofit to send a date literal instead of sending JSON.

**Comment by JakeWharton** [comment]
Pass it as a string.

**Comment by ramesh586** [comment]
I am passing as a string only still i am getting same issue will you please give an example ..
