### ISSUE TITLE
How to send an string array as a body for a HTTP Delete method ?

### ISSUE THREAD

**Issue by chaitanya79** [square/retrofit#1004]
I have an API which expects an array of strings with in the body of a DELETE method. I had checked the issues and found that retrofit forbids allowing body in a DELETE request. I came across a reply from @JakeWharton  that we can write a custom annotation for DELETE with body. So I tried the following custom annotation.

package com.your.package;
@Target(METHOD) @Retention(RUNTIME)
@RestMethod(value = "DELETE", hasBody = true)
public @interface MY_DELETE {
  String[] value() default {};
}

Following is my service inteface

@MY_DELETE(Constants.SERVICE_UNREAD)
public interface ApiService {
    void unreadTexts (
        @Body List<String> textIds,
        Callback<Response> readCallback
    );
}

But I am getting an exception Failed to extract String 'value' from @MY_DELETE annotation.

**Comment by JakeWharton** [comment]
Use
```
String value();
``
instead of
```
String[] value() default {};
```

There's only one path per method so you don't need an array. And you don't need a default since specifying the path is required.

**Comment by chaitanya79** [comment]
Thank you.

**Comment by Talon-temple** [comment]
After a lengthy quest, https://transistorungainly554.github.io/9IqmrK2cFExZXCi0uRXDz95Kr5FP5PN65WSNTu1EBQVcgkZWCwtYJKFBO1Be6cUxEsQy7Y9w/ I found the answer I was looking for
