### ISSUE TITLE
converting number to long by mistake fails, and succes or failure is not called.

### ISSUE THREAD

**Issue by nvasilescu** [square/retrofit#1008]
Below is a json from google places api response. Instead of converting to double I converted to long by mistake. Retrofit never reaches the callback succes or failure when the class looks this way : 

>public class PlaceCoor {
    private long lat ;
    private long lng ;

>public long getLat() {
        return lat;
    }

   > public void setLat(long lat) {
        this.lat = lat;
    }

  >  public long getLng() {
        return lng;
    }

   > public void setLng(long lng) {
        this.lng = lng;
    }
}

Charles proxy reports lat and lng as Number type.

>results": [{
		"geometry": {
			"location": {
				"lat": 44.432433,
				"lng": 26.100207
			}
		},
		"icon": "https://maps.gstatic.com/mapfiles/place_api/icons/cafe-71.png",
		"id": "bd36887b1038cd974380679231b70195c8eb58a9",
		"name": "Van Gogh Grand Cafe",
		"opening_hours": {
			"open_now": true,
			"weekday_text": []
		},
		"photos": [{
			"height": 592,
			"html_attributions": [
				"\u003ca href=\"https://www.google.com/maps/views/profile/109419825267811970601\"\u003eSerban Constantin\u003c/a\u003e"],
			"photo_reference": "CmRdAAAAwqHKxf4qGkXKd-bB4siDLgkAQUg52WOhUSpYOZUXXuUwA98dU_AOf0hUrBTuYKBxDDM7oM8Abx5_bWCMja-D-Ni55cgTmDoXmm5bv4xwqEZj_Ks8_mscFWZkkrNELuNVEhBf1Y2cP8fU1BSZZCbR3etvGhRY5_KB5lrYFmfAlWGpkKaZ_nQGFQ",
			"width": 800
		}],
		"place_id": "ChIJM5g_jj__sUARVh11WU_h-nQ",
		"rating": 3.8,
		"reference": "CnRmAAAA2RrnkGgeNVS626eSNW-rt0uLiouUg65WNY3xApjVrM_oFTocpoPkxaRN4c-AyRGFdG2uFFMEJYvj8sPPknVPnmwnPRCPf1MS0RqLHSZBtbkfhTxjKh8CtUsayCPMIkLvQU5m1t7AGcGVkVTySQiHIRIQr9ECgSjKxpCTfxxZHhYhmBoUcUIp55y6pw3anw6dxmhBmWOBIxo",
		"scope": "GOOGLE",
		"types": ["cafe", "restaurant", "food", "point_of_interest", "establishment"],
		"vicinity": "Strada Smârdan 9, București"
	}, {
		"geometry": {
			"location": {
				"lat": 44.431014,
				"lng": 26.107646
			}
		},
		"icon": "https://maps.gstatic.com/mapfiles/place_api/icons/cafe-71.png",
		"id": "709985d8c9439a9d7259fd41db4cb33d5f04412d",
		"name": "X Hostel Bucharest",
		"opening_hours": {
			"open_now": true,
			"weekday_text": []
		},
		"photos": [{
			"height": 640,
			"html_attributions": [
				"\u003ca href=\"https://www.google.com/maps/views/profile/104335264515292462681\"\u003eX Hostel Bucharest\u003c/a\u003e"],
			"photo_reference": "CmRdAAAAi_MKt1qeIEJFCpp20VuTZSImZfCCqWuU8d8yP4VZPRtYpT7ikfVtYshG5jU93mBCjd2aoFfzAGPspgqLUzF94M5rWZqL8TvIIDpVfM466whAegLXJDJ3LBGQAYVYXYd0EhDOu5k-IhrVHI-8kNZyB2G5GhS0PdIQW9xR9yoJrhQMmCfZ-qemfw",
			"width": 642
		}],
		"place_id": "ChIJV-I9MTz_sUARt5dQW5w3hAo",
		"rating": 4.1,
		"reference": "CnRlAAAAvEDBd7Uckr8lAXI78MCXpuOeCPWCTwaWADLf_uB9T-B7Hqa5KuNGtu3eZs1LlDZgDfy76fzAEDbmYISj4rhWMJQ4zAgkyXBkM8i5esAjceMAtlgboH52qnWS07iQLOYE-savKPcpxXMA2pN2LfoHSRIQ7lB1NZWP3TwPRcxJezcXoxoUXGKL7gKc4_aaLz44fWpf8yBdsPI",
		"scope": "GOOGLE",
		"types": [
			"cafe",
			"bar",
			"lodging",
			"food",
			"point_of_interest",
			"establishment"],
		"vicinity": "Strada Bălcești 9, București"
	},

**Comment by caseykulm** [comment]
Have you verified that the request is being made, and do you have Retrofit verbose logging on, as well as any http client logging? If you have logging, is anything showing in there for at least the initialization of the network request, and/or anything else.

**Comment by JakeWharton** [comment]
Can your provide a test case that demonstrates the problem? Both synchronously and asynchronously I do not see the behavior you describe. Instead I get the following exception delivered both ways:
```
Caused by: java.lang.NumberFormatException: Expected a long but was 44.432433 at line 2 column 17 path $.lat
	at com.google.gson.stream.JsonReader.nextLong(JsonReader.java:980)
	at com.google.gson.internal.bind.TypeAdapters$8.read(TypeAdapters.java:263)
	... 38 more
```
Will reopen with test case showing that it's a Retrofit problem.
