### ISSUE TITLE
Incorrect RetrofitError for 401

### ISSUE THREAD

**Issue by tseglevskiy** [square/retrofit#1012]
Retrofit does not recognize unexpected IOException from connection.getResponseCode();
There are lots of info about this issue in android, for example:
http://stackoverflow.com/a/15973063/1263771

So I can not get RetrofitError with code 401 (because Retrofit does not catch IOException itself) and has not access to others HTTP headers.

**Comment by caseykulm** [comment]
Using [OkHttp](https://github.com/square/okhttp) instead of HttpURLConnection fixes this. It doesn't seem that unexpected Exceptions thrown by an HTTP client library are Retrofits job to handle, but the users.

**Comment by JakeWharton** [comment]
Wow this is horrible behavior!

For the past few months all of my efforts have been towards Retrofit 2 in trying to ship it before the new year. It's unlikely that we'll ship another 1.x version and even if we did it wouldn't be for months. My suggestion would be to use OkHttp! But if you can't do that, you can [copy the `UrlConnectionClient` from 1.9][1] and modify it with the fix suggested in StackOverflow. Pass an instance of that modified instance to the `RestAdapter.Builder`'s `setClient` method and you'll be good to go.

Sorry for not replying sooner. Hope you were able to work around the problem.

 [1]: https://github.com/square/retrofit/blob/parent-1.9.0/retrofit/src/main/java/retrofit/client/UrlConnectionClient.java
