### ISSUE TITLE
Gson Serializer never gets called, deserializer works fine

### ISSUE THREAD

**Issue by kokeroulis** [square/retrofit#1016]
Hello,

In the example below the JsonSerializer never gets called but the deserializer works fine.
According to the gson docs both of them should work (Serializer and deserializer).
You can find the full code here https://github.com/kokeroulis/retrofit_bug.

    public class Github implements JsonSerializer<Github>, JsonDeserializer<Github> {
        public int id;
        public String name;
        public Owner owner;
        public String url;
        public int size;
        public Organization organization;
        public String foo;

    @Override
    public JsonElement serialize(Github src, Type typeOfSrc, JsonSerializationContext context) {
        // it never calls this one....
        src.foo = "this is foo";
        return context.serialize(src);
    }

    @Override
    public Github deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {
        // this one gets called.
        Github github = new Gson().fromJson(json, Github.class);
        Log.i("info", "test that the deserializer works!");
        return github;
    }
}

   public interface RetrofitServiceExample {

    @GET("/square/retrofit")
    void getRetrofit(Callback<Github> callback);

     public static class Implementation {
        public static RetrofitServiceExample get() {
            return getBuilder()
                    .build()
                    .create(RetrofitServiceExample.class);
        }

        static RestAdapter.Builder getBuilder() {
            return new RestAdapter.Builder()
                    .setConverter(new GsonConverter(getGson()))
                    .setClient(new OkClient(new OkHttpClient()))
                    .setEndpoint("https://api.github.com/repos");
        }

        private static Gson getGson() {
            return new GsonBuilder()
                    .registerTypeAdapter(Github.class, new Github())
                    .create();
        }
    }
}

**Comment by JakeWharton** [comment]
You are not sending any instances of `GitHub` anywhere so there's no reason for the serializer to be called. On the other hand, you are receiving an instance of `GitHub` from the remote server which is why the deserializer is called. If you `@POST` with `@Body GitHub` you will see the serializer used.
