### ISSUE TITLE
About cached request

### ISSUE THREAD

**Issue by mdtuyen** [square/retrofit#1022]
I need a document or example clearly about cache for request
1. only using okhttp
2. using okhttp and retrofit
3. if header setting is private no-cache, no-store, must-revalidate
Now i see that document about this topic is difficult to understand. I have just begin first project using retrofit, okhttp. Please help me.

**Comment by mdtuyen** [comment]
I make a example follow stackoverflow:
```
    @Override
    protected T doInBackground(Void... params) {
        Gson gson = new GsonBuilder().create();
        File httpCacheDirectory = new File(context.getCacheDir(), UUID.randomUUID().toString());

        Cache cache = new Cache(httpCacheDirectory, 10 * 1024 * 1024);

        OkHttpClient okHttpClient = new OkHttpClient();
        if (cache != null) {
            okHttpClient.setCache(cache);
        }
        retrofit.RestAdapter restAdapter = new retrofit.RestAdapter.Builder()
                .setRequestInterceptor(new RequestInterceptor() {
                    @Override
                    public void intercept(RequestFacade request) {
                        request.addHeader("Accept", "application/json;versions=1");
                        if (new ConnectionDetector(context).isConnectingToInternet()) {
                            int maxAge = 60; // read from cache for 1 minute
                            request.addHeader("Cache-Control", "public, max-age=" + maxAge);
                        } else {
                            int maxStale = 60 * 60 * 24 * 28; // tolerate 4-weeks stale
                            request.addHeader("Cache-Control",
                                    "public, only-if-cached, max-stale=" + maxStale);
                        }
                    }
                })
                .setEndpoint(service_url)
                .setClient(new OkClient(okHttpClient))
                .setConverter(new GsonConverter(gson))
                .build();

        GetAllAPI service = restAdapter.create(GetAllAPI.class);
        
        return (T) service.getCountries();
    }
```
It can be cached but if the first after install i disconect network => force close

**Comment by JakeWharton** [comment]
Retrofit plays no part in caching, that's entirely contained in the underlying HTTP client. I would have pointed you at StackOverflow, but you've already asked [the question there](http://stackoverflow.com/q/32155082/132047) (although with entirely too little information). Caching headers can be complicated and it's a topic that there's a lot of good information one. Some examples:
 * https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching
 * http://www.mobify.com/blog/beginners-guide-to-http-cache-headers/
