### ISSUE TITLE
Retrofit Async /CallBack Methods Not executing on Jdk 1.8

### ISSUE THREAD

**Issue by gp2you** [square/retrofit#1025]
Hi ...I am using Retrofit to call some rest api (on Java 1.8 running on server not android ) ....but async version doesn't even executes ( in call back objects success or failure methods are never called )...does Retrofit Async version only works on android ?? Some threading needed on when running on standard JDK ??As per logs Async has no network activity either

*************************************CODE Snippet ***************************************

        RestAdapter restAdapter = new RestAdapter.Builder()
                .setEndpoint(CONFIG.END_PONT).setLogLevel(RestAdapter.LogLevel.FULL)
                .build();
        TrackingService service = restAdapter.create(TrackingService.class);
        _.debug("Start Testing ............");
        // Always Executes   
       _.debug("Calling Sync Version ............which excu"+ service.addTrackDataSync(trackData).descprition);

        try{
            service.addTrackingData(trackData, new Callback<TrackSummary>() {
                public void success(TrackSummary trackSummary, Response response) {
                    //NEVER EXECUTES 
                    System.out.println("Track summary data ->>>>>>" + trackSummary.descprition);
                }

                public void failure(RetrofitError retrofitError) {
                    //NEVER EXECUTES 
                    System.out.println("Error data ->>>>>>" + retrofitError.getMessage());
                }
            });

            service.addTrackingData(trackData,callback);
        } catch (Exception e){
            _.error("Error ............" + e.getMessage());
        } finally {
            _.error("serverResponse wtf:");
        }

**Comment by JakeWharton** [comment]
Retrofit uses daemon threads which will not keep the JVM alive if the above is the only thing in your main method. If you need non-daemon threads you'll have to supply your own background executor to `RestAdapter.Builder` which has a thread factory that does not create daemon threads. Other than that, Retrofit works fine on the JVM in both sync and async fashion.

I'm going to close assuming the issue it with the daemon threads, please comment if otherwise.

**Comment by gp2you** [comment]
can you please give me example on how to achieve , I was not able to find any documentation ...best would be add in documentation

**Comment by gp2you** [comment]
Tried with executor also nothing seems to work ......does anyone has working sample ?


//  Executor executor = Executors.newSingleThreadExecutor();
        Executor executor = Executors.newCachedThreadPool();
        OkHttpClient okHttpClient = new OkHttpClient();
        RestAdapter restAdapter = new RestAdapter.Builder()
                .setEndpoint(CONFIG.END_PONT).setLogLevel(RestAdapter.LogLevel.FULL)
                .setExecutors(executor, executor) .setClient(new OkClient(okHttpClient))
                .build();
        TrackingService service = restAdapter.create(TrackingService.class);
        _.debug("Start Testing ............");
        // Always Executes
    //   _.debug("Calling Sync Version ............which excu"+ service.addTrackDataSync(trackData).descprition);

        try{
            service.addTrackingData(trackData, new Callback<TrackSummary>() {
                public void success(TrackSummary trackSummary, Response response) {
                    //NEVER EXECUTES
                    System.out.println("Track summary data ->>>>>>" + trackSummary.descprition);
                }

                public void failure(RetrofitError retrofitError) {
                    //NEVER EXECUTES
                    System.out.println("Error data ->>>>>>" + retrofitError.getMessage());
                }
            });
