### ISSUE TITLE
How to avoid waiting on main thread when adding headers to requests using retrofit?

### ISSUE THREAD

**Issue by mori-honest** [square/retrofit#1026]
I already made the [stackoverflow question here] (http://stackoverflow.com/questions/32175717/how-to-avoid-waiting-on-main-thread-when-adding-headers-to-requests-using-retrof). I appreciate if you take a look at this. Thank you.

**Comment by JakeWharton** [comment]
We are subscribed to StackOverflow questions on the 'retrofit' tag. No need to post here.
