### ISSUE TITLE
retrofit 1.9.0 stuck while trying to write SSL in offline mode on Samsung Galaxy S6

### ISSUE THREAD

**Issue by SooperCode** [square/retrofit#1028]
Retrofit appears to get stuck at this point when the Phone is offline, and then the process needs to be killed manually. Could only be reproduced on a Samsung Galaxy S6, Android 5.1.1 so far (never happened on Samsung Galaxy S5, Android 5.0 & LG G4, Android 5.1).
<img width="864" alt="screen shot 2015-08-24 at 3 32 54 pm" src="https://cloud.githubusercontent.com/assets/9916929/9442068/ff2cae48-4a79-11e5-94c5-39cd7a3449c4.png">

**Comment by JakeWharton** [comment]
Retrofit interacts with underlying HTTP clients in a synchronous way so it will never be Retrofit that is the problem when a connection is stalled. You are using OkHttp as the underlying client so at the very least it might be the problem, but the actual stall is in native code in the Android platform itself, so OkHttp is likely not the cause either. Not really sure how to help you move forward, but it's definitely not Retrofit which is at fault here.

**Comment by SooperCode** [comment]
Ok, that's good to know though - thanks a lot Jake!
