### ISSUE TITLE
Response content type was not a proto: application/json

### ISSUE THREAD

**Issue by williamrussellajb** [square/retrofit#1030]
Hello, 

I'm not quite sure why I'm getting this error.

@Headers({"Accept: application/json", "Content-Type: application/x-protobuf"})
	@POST("/dashboard/mobile")
	MobileDashboardResponse getQuotaGroupsByPublisher(@Body MobileDashboardRequest mobileDashboardRequest);

I want to use the protobuf generated models we have to send/receive requests from our API. 
However, when I execute the test.. I see the response sent to the server... and I see a JSON response.

I Cannot get it to map back into the MobileDashboardResponse? 
I tried playing around with the headers... but I'm not quite sure where the error is at. 

My adapter is using .setConverter(new ProtoConverter()).

**Comment by caseykulm** [comment]
"I see a JSON response" <-- That's the problem.

The server is sending you a JSON response, and you are trying to parse the JSON as proto, hence "Response content type was not a proto: application/json".

**Comment by JakeWharton** [comment]
Yep, what he said! Retrofit 2.0.0-beta1 supports multiple converters allowing proto on the way up and JSON on the way down. Just be sure to add the proto converter first.
