### ISSUE TITLE
More costomize RequestInterceptor

### ISSUE THREAD

**Issue by closerZhang** [square/retrofit#1036]
In my project,Header Authorization is encrypt by HttpMethod and Host and Url and some other value in Context,I want to use RequestInterceptor to set my Header Authorization,but the RequestInterceptor do not support me to access RestMethodInfo and Host.can you give me some suggestion.

**Comment by JakeWharton** [comment]
You'll need to use an [OkHttp interceptor][1] which has access to all the request metadata and full body.

 [1]: https://github.com/square/okhttp/wiki/Interceptors

**Comment by closerZhang** [comment]
@JakeWharton I follow your suggestion,and it is a good idea,thank you very much
