### ISSUE TITLE
Can't seem to get the examples to work at all

### ISSUE THREAD

**Issue by fjfish** [square/retrofit#1040]
Hi guys

I pulled the service example into my android code and changed the main() method to be one called load.

It blows up in my face with Unable to create converter (as in MethodHandler line 61)

I went to the website URL (http://square.github.io/retrofit/) and it refers to a class called RestAdapter that has a different syntax from Call - but that class does not appear to be in the JAR file and I'm very confused now.

Is there something missing in the documentation, or am I missing a dependency somewhere?

Thanks

**Comment by fjfish** [comment]
Update: RestAdapter is in 1.9.0 - so it looks like the syntax on the website works with that version of the jar, I will carry on.

**Comment by JakeWharton** [comment]
2.0 beta 1 was just published on Friday. Docs are in the process of being updated. The website now reflects 2.0, but there's still a lot to do to make them comprehensive.

**Comment by fjfish** [comment]
Thanks - it's really useful and has saved me a ton of work.
