### ISSUE TITLE
Url malformation depending on trailing

### ISSUE THREAD

**Issue by FranciscoE-Reuters** [square/retrofit#1041]
For 2.0.0-beta1

If your enpoint doesn't end with / like https:///www.do.com/root and you define @GET("/thing") the final url is https://do.com/thing

```
new Retrofit.Builder().baseUrl("https://garrylachman-detect-nudity-v1.p.mashape.com/nude").build()

public interface CheckerApi {
    @GET("url")
    @Headers("Accept: application/json")
    Observable<CheckerResult> getResult(@Header("X-Mashape-Key") String mashapeKey,
            @Query("url") String url);
}
```

**Comment by jdreesen** [comment]
Well, that's actually the correct behaviour. Maybe you should read this article: https://cdivilly.wordpress.com/2014/03/11/why-trailing-slashes-on-uris-are-important/ ;)

**Comment by FranciscoE-Reuters** [comment]
The example in Jake's slides from 3 days ago shows it the way I implemented, hence the confusion: https://speakerdeck.com/jakewharton/simple-http-with-retrofit-2-droidcon-nyc-2015

**Comment by JakeWharton** [comment]
The subsequent slides go on to show you how a base URL with a path behaves. Long story short: a leading slash on the method is an absolute path and no-leading slash is a relative URL. It works exactly like `<a href="">`.

**Comment by FranciscoE-Reuters** [comment]
I'll need the video for that, but it's understood now.
