### ISSUE TITLE
Potential new Converter API

### ISSUE THREAD

**Issue by JakeWharton** [square/retrofit#1044]
Copy/paste of conversation:

> i'm a bit concerned about the Converter/Factory interfaces now that there's multiple

> if you want to add a thing that lets you encode enum's to text/plain strings by calling .name() you also have to implement the deserialize method

> tempted to make:
> ```java
> interface Converter<F, T> {
>   T convert(F value);
> 
>   interface Factory {
>     Converter<ResponseBody, ?> fromBody(Type type, Annotation[] annotations);
>     Converter<?, RequestBody> toBody(Type type, Annotation[] annotations);
>   }
> }
> ```
> 
> actually would probably do an abstract class for `Factory`
> 
> what's interesting is that there's a potential for using that same interface for parameters then
> 
> ```java
> Converter<String, ?> forParam(Type type, Annotation[] annotations);
> ```
> or something...
> 
> to handle the date formatting, enum .name() calling, etc. path/query/header handling

**Comment by tadfisher** [comment]
Unification of RequestBody/ResponseBody, Query, and Path conversion would be a win in my book.

**Comment by JakeWharton** [comment]
Definitely. It's a lot easier said than done. I have a form of this new API working for the existing hookups., but as to the query/path/part/field/header hookup things get complicated very quickly.
