### ISSUE TITLE
Improper encoding of path segment

### ISSUE THREAD

**Issue by tadfisher** [square/retrofit#1045]
Here's a test case:

https://android.api.simple.com/atm-api/nearest/45.529801,-122.683633 (works)

Retrofit encodes as:

https://android.api.simple.com/atm-api/nearest/45.529801%2C-122.683633 (doesn't work)

According to [this guide](http://blog.lunatech.com/2009/02/03/what-every-web-developer-must-know-about-url-encoding) the `,` (comma) character should be allowed unencoded in the path.

Easily worked around with `encoded=true`.

**Comment by JakeWharton** [comment]
I'm assuming you are using something like `/nearest/{location}` and specifying the location as a parameter?

**Comment by tadfisher** [comment]
Yep, sorry. Here's the endpoint definition:

```java
    @GET("/atm-api/nearest/{coordinate}")
    Call<AtmLocation> getNearestAtmLocation(@Path(value = "coordinate", encoded = true) Coordinate coordinate);
```

`Coordinate` is a converted using this `toString` implementation:

```java
return String.format("%.6f,%.6f", latitude, longitude)
```

**Comment by swankjesse** [comment]
Try with OkHttp 2.5 ?

**Comment by tadfisher** [comment]
@swankjesse Yep this is with `-beta1`

**Comment by JakeWharton** [comment]
This is because path encoding happens in Retrofit, not OkHttp's HttpUrl class.

```java
        String encodedValue = URLEncoder.encode(String.valueOf(value), "UTF-8");
        // URLEncoder encodes for use as a query parameter. Path encoding uses %20 to
        // encode spaces rather than +. Query encoding difference specified in HTML spec.
        // Any remaining plus signs represent spaces as already URLEncoded.
        encodedValue = encodedValue.replace("+", "%20");
        relativeUrl = relativeUrl.replace("{" + name + "}", encodedValue);
      } else {
        relativeUrl = relativeUrl.replace("{" + name + "}", String.valueOf(value));
      }
```
