### ISSUE TITLE
retrofit-converters jar missing from maven central

### ISSUE THREAD

**Issue by kaiwaldron** [square/retrofit#1048]
Not quite sure why this jar is missing now, I'm trying to get 1.9.0 but other versions seem to be missing as well:

https://repo1.maven.org/maven2/com/squareup/retrofit/retrofit-converters/1.9.0/

**Comment by JakeWharton** [comment]
It has never been there because it's just a parent project. Depend on a specific converter instead: http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.squareup.retrofit%22%20AND%20v%3A%221.9.0%22%20AND%20p%3A%22jar%22
