### ISSUE TITLE
Force trailing slash on base URL

### ISSUE THREAD

**Issue by JakeWharton** [square/retrofit#1049]
You never want http://example.com/foo but rather http://example.com/foo/ to ensure the relative URL is resolved as a child rather than as a sibling of that path.

**Comment by joepetrakovich** [comment]
For some reason my base URL trailing paths are truncated, is this related?

For example, with base URL "https://www.hello.com/api/v1" 
and Retrofit call @GET("/user") 

The onResponse is showing an error with the URL as "https://www.hello.com/user"

**Comment by JakeWharton** [comment]
Add a trailing slash on the base url, remove leading slash on annotation.

**Comment by joepetrakovich** [comment]
I actually had deleted my comment before your response because I found your answer on StackOverflow and doubly after watching the video of your talk!  Thanks again, Jake.

**Comment by JakeWharton** [comment]
Ah, ok. Great. I'm triaging a ton of email and not looking on the website.
Documentation around this is coming!
