### ISSUE TITLE
Convert errorBody just like body

### ISSUE THREAD

**Issue by heyarne** [square/retrofit#1053]
I have a JSON API that returns a non-20x Status Code.The response body looks similar to this:
```
{ "error": "Device limit exceeded" }
```
The behaviour of Retrofit currently seems to be to always return a `ResponseBody` for the `errorBody` ([see here](https://github.com/square/retrofit/blob/9cd5dfa0e0c66704ab035835259fde2721511237/retrofit/src/main/java/retrofit/Response.java#L69)).
Am I missing something? Should the errorBody not be parsed like the regular body?

**Comment by JakeWharton** [comment]
> Should the errorBody not be parsed like the regular body?

Definitely no. The format of the responses in non-200 codes is not guaranteed. I can offer up plenty of examples which return HTML or simply JSON of a completely different format. Furthermore, the error might be returned from another hop in the route to the server (such as a load balancer) that has no awareness of the response format.

**Comment by tadfisher** [comment]
It would be interesting to see an `@Error(Type)` with an additional set of error-body converters. Not sure how you'd handle it when the error body is completely broken (i.e. proxy error, etc).

**Comment by JakeWharton** [comment]
That also wouldn't allow representing a complex type like Map<String,
String>, but you're unlikely to want that anyway.

**Comment by tadfisher** [comment]
Yeah, it's tough to avoid polluting the API. I was thinking `Request<MyType, MyErrorType>` and associated `Call` and `Result` signatures would also suffice, but you'd be forcing this everywhere.

**Comment by JakeWharton** [comment]
Maybe Request<T> can extend something lower level like HttpRequest<T,
ResponseBody>.
