### ISSUE TITLE
URL Parameter Encoding fails

### ISSUE THREAD

**Issue by jjoe64** [square/retrofit#1058]
Hi I'm trying to do a simple http get query via `Retrofit`.

My parameter has some special characters and it seems that the url encoding fails.

Original:

    data=[out:json];node["name"~"Karlsruhe"]["place"~"city|village|town"];out body;

correct encoding should look like this:

    data=%5Bout%3Ajson%5D%3Bnode%5B%22name%22~%22Karlsruhe%22%5D%5B%22place%22~%22city%7Cvillage%7Ctown%22%5D%3Bout%20body%3B

but Retrofit creates this:

    data=[out:json];node[%22name%22~%22Karlsruhe%22][%22place%22~%22city|village|town%22];out%20body;

and this will fail with:

> java.lang.IllegalStateException: not valid as a java.net.URI:
> http://overpass.osm.rambler.ru/cgi/interpreter?data=[out:json];node[%22name%22~%22Karlsruhe%22][%22place%22~%22city|village|town%22];out%20body;
> 	at com.squareup.okhttp.HttpUrl.uri(HttpUrl.java:336) 	at
> com.squareup.okhttp.internal.http.RouteSelector.resetNextProxy(RouteSelector.java:135)
> 	at
> com.squareup.okhttp.internal.http.RouteSelector.<init>(RouteSelector.java:71)
> 	at
> com.squareup.okhttp.internal.http.RouteSelector.get(RouteSelector.java:76)
> 	at
> com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:321)
> 	at
> com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:245)
> 	at com.squareup.okhttp.Call.getResponse(Call.java:267) 	at
> com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224)
> 	at
> com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
> 	at com.squareup.okhttp.Call.execute(Call.java:79) 	at
> retrofit.OkHttpCall.execute(OkHttpCall.java:112)

What can be done here to fix this encoding issue?
Thanks

**Comment by JakeWharton** [comment]
I don't think your OkHttp change was enough. On its latest `master`:
```java
HttpUrl url = new Builder() //
    .scheme("http")
    .host("example.com")
    .addPathSegment("data=[out:json];node[\"name\"~\"Karlsruhe\"][\"place\"~\"city|village|town\"];out body;")
    .build();
System.out.println(url);
System.out.println(url.uri());
```
yields:
```
http://example.com/data=[out:json];node[%22name%22~%22Karlsruhe%22][%22place%22~%22city%7Cvillage%7Ctown%22];out%20body;
Exception in thread "main" java.lang.IllegalStateException: not valid as a java.net.URI: http://example.com/data=[out:json];node[%22name%22~%22Karlsruhe%22][%22place%22~%22city%7Cvillage%7Ctown%22];out%20body;
```

**Comment by JakeWharton** [comment]
Moved to https://github.com/square/okhttp/issues/1872
