### ISSUE TITLE
abstract class implementation Call<T>

### ISSUE THREAD

**Issue by gintechsystems** [square/retrofit#1059]
This is more of a question because I may be doing this wrong, but I have created a custom class because I wanted to add a few methods that are not part of Call (such as a tag so I can cancel the request from anywhere in my apps). Maybe there is a better approach to this, but my code follows and I receive the following error:

Error:(1822, 10) error: clone() in Object cannot implement clone() in Call
attempting to assign weaker access privileges; was public
where T is a type-variable:
T extends Object declared in interface Call

abstract class RemoteJSONServiceCall<T> implements Call<T> {
    AMFParameters amfParameters = null;
}

private RemoteJSONServiceCall<JsonObject> createRetrofitCall(final AMFParameters params) {
        if (Connectivity.isConnected(visnetawrap)) {
            RemoteJSONServiceCall<JsonObject> newCall = amfService.amfcall(params);
            newCall.amfParameters = params;
            callsList.add(newCall);
            return amfService.amfcall(params);
        }
        return null;
    }

**Comment by JakeWharton** [comment]
You need to add a `clone()` method which returns a new instance.

**Comment by JakeWharton** [comment]
Here's an example:
```java
public final class AppCall<T> implements Call<T> {
  private final Call<T> delegate;
​
  public AppCall(Call<T> delegate) {
    this.delegate = delegate;
  }
​
  private void handleResponseBody(T body) {
​    // TODO whatever
  }
​
  @Override public Response<T> execute() throws IOException {
    Response<T> response = delegate.execute();
    if (response.isSuccess()) {
      handleResponseBody(response.body());
    }
    return response;
  }
​
  @Override public void enqueue(final Callback<T> callback) {
    delegate.enqueue(new Callback<T>() {
      @Override public void onResponse(Response<T> response) {
        if (response.isSuccess()) {
          handleResponseBody(response.body());
        }
        callback.onResponse(response);
      }
​
      @Override public void onFailure(Throwable t) {
        callback.onFailure(t);
      }
    });
  }
​
  @Override public void cancel() {
    delegate.cancel();
  }
​
  @Override public Call<T> clone() {
    return new AppCall<>(delegate.clone());
  }
}
```
Note the clone method and the fact that it also clones the `delegate`.

**Comment by gintechsystems** [comment]
Thank you!

**Comment by marconealberto** [comment]
I tried to do the same thing, but I get this error:

> Could not locate call adapter for .....


and then 

> Unable to create call adapter for .....


this is a piece of my code

```
            Retrofit client = new Retrofit.Builder()
                    .baseUrl(baseUrl)
                    .client(okClient)
                    .addConverterFactory(GsonConverterFactory.create())
                    .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                    .build();
```

what am I doing wrong?
