### ISSUE TITLE
Request Headers Bug?

### ISSUE THREAD

**Issue by gintechsystems** [square/retrofit#1060]
I have tried 2 different ways to add headers but they never show in the request or response.

Can anyone else reproduce this issue or am I doing something wrong?

Call<JsonObject> amfcall(@Header("Content-Type") String contentType, @Header("UserSession") String userSession, @Body AMFParameters info);

defaultClient.interceptors().add(new Interceptor() {
            @Override
            public Response intercept(Chain chain) throws IOException {
                Request.Builder newRequest = chain.request().newBuilder();
                newRequest.header("Content-Type", "application/json");

                if (visnetawrap.visnetaUser != null) {
                    if (visnetawrap.visnetaUser.getUserIdString() != null) {
                        newRequest.addHeader("UserSession", "id=" + visnetawrap.visnetaUser.getUserIdString());
                    }
                    if (visnetawrap.visnetaUser.userToken != null) {
                        newRequest.addHeader("UserSession", "token=" + visnetawrap.visnetaUser.userToken);
                    }
                }
                newRequest.addHeader("UserSession", "source=Android-" + AppUtils.getDeviceUUID(visnetawrap));

                return chain.proceed(newRequest.build());
            }
        });

**Comment by JakeWharton** [comment]
How do you know they do not show up?

**Comment by gintechsystems** [comment]
Logcat, want me to post?

**Comment by JakeWharton** [comment]
Logcat how? Retrofit has no logging.

**Comment by gintechsystems** [comment]
The headers from okhttp request. This is my retrofit builder.

Retrofit retrofit = new Retrofit.Builder().addConverterFactory(GsonConverterFactory.create(visnetawrap.gsonClient)).baseUrl(BASE_URL).client(defaultClient).build();

**Comment by gintechsystems** [comment]
Should I revert back to 1.9 for now? I only need the ability to cancel in 2.0, only reason I switched. I was doing it in 1.9 but had to create my own class for that.

**Comment by zeeshanaslam78** [comment]
@JakeWharton I want to use Headers ["Authorization", "Basic MykeyHere"] 
Please please provide code How can I call in Retrofit 2.0.0-beta1. I tried different ways but I am getting this in response when I log "Response{protocol=http/1.1, code=404, message=Not Found, url=https://mysiteurl.com/api/v1/oauth2/token}"

**Comment by JakeWharton** [comment]
Please create a representative test or example that demonstrates the problem. I can't reproduce such behavior.

**Comment by alekaizer** [comment]
Actually I have the same problem

-Override Headers
    @Headers("content-type:application/json")
    @POST("/login")
    Call<User> logUser(@Body Credential user);
-----------------------------------------------------------------------
    @POST("/login")
    Call<User> logUser(@Body Credential user, @Header("Content-Type") String contentType);

- Use Interceptors

        client.interceptors().add(new Interceptor() {
            @Override
            public com.squareup.okhttp.Response intercept(Chain chain) throws IOException {
                Request original = chain.request();

                Request request = original.newBuilder()
                        .addHeader("Cache-Type", "application/json")
                        .method(original.method(), original.body())
                        .build();

                return chain.proceed(request);
            }
        });


When I check the headers on logcat I get this

11-13 22:47:59.966 17299-18016/fr.packageName D/OkHttp: --> POST /login HTTP/1.1
11-13 22:47:59.966 17299-18016/fr.upackageName D/OkHttp: --> END POST

But when I try the same stuffs with others headers it works.

11-13 22:51:23.764 23279-23749/fr.packageName D/OkHttp: --> POST /login HTTP/1.1
11-13 22:51:23.764 23279-23749/fr.packageName D/OkHttp: Cache-control: max-age=1500
11-13 22:51:23.764 23279-23749/fr.packageName D/OkHttp: --> END POST

**Comment by gintechsystems** [comment]
Jake I will get back to you with a test as soon as I can, been pretty busy. Thank you Alek for posting your results.

**Comment by JakeWharton** [comment]
How are you logging?

**Comment by abhaysood** [comment]
Hey, I have the same problem. 

**Interceptor**

        public Response intercept(Chain chain) throws IOException {

            Request request = chain.request();
            final Request.Builder builder = request.newBuilder();
            builder.addHeader(APP_VERSION, "version");
            builder.addHeader(USER_TOKEN, "sometoken");
            builder.build();
            return chain.proceed(request);
            }

**Logging**
I am logging using the [okhttp-logging-interceptor](https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor)

However the headers are not being sent to the server as I get a response saying "token not present"
also it is not present in the logs

**Comment by JakeWharton** [comment]
You are not using the Request returned from calling .build(), but rather
the original one.

**Comment by abhaysood** [comment]
Ahh! Thanks Jake :+1:

**Comment by alekaizer** [comment]
@JakeWharton using OkHttp-logging-interceptor for logging. 
Got it work by modifying my classes and not setting any headers.

is it a choice from you guys to not being able to set the Content-type headers ?

**Comment by JakeWharton** [comment]
Content-Type is part of the body, as is the length.

**Comment by JakeWharton** [comment]
The content type and length are part of the body, not headers, when using an application interceptor. It's only when the request is going to the network do the headers get actually added. You'll need to use a network interceptor if you want to see these values logged.

**Comment by sirawitit** [comment]
@gintechsystems  @alekaizer 
pls try.    `    httpClient.addInterceptor(interceptor); `After AddHeader .
Below code is sample Log can show able.

```
  OkHttpClient.Builder httpClient = new OkHttpClient.Builder();
        httpClient.connectTimeout(10, TimeUnit.SECONDS);
        httpClient.writeTimeout(10, TimeUnit.SECONDS);
        httpClient.readTimeout(20, TimeUnit.SECONDS);
        httpClient.addInterceptor(chain -> {
            Request original = chain.request();
            Request request = original.newBuilder()
                    .addHeader("AccessToken", AccessDonutToken.getInstance().getAccessToken())
                    .addHeader("Accept", "application/json")
                    .method(original.method(), original.body()).build();
            return chain.proceed(request);
        });
        httpClient.addInterceptor(interceptor);
```

**Comment by alekaizer** [comment]
thanks @sirawitit will let you know

**Comment by miladcoder** [comment]
i have same problem
`public static ApiInterface initInterface() {
        OkHttpClient.Builder httpClient = new OkHttpClient.Builder();
        httpClient.addInterceptor(new Interceptor() {
            @Override
            public Response intercept(Chain chain) throws IOException {
                Request original = chain.request();
                Request request = original.newBuilder()
                        .removeHeader("Authorization")
                        .removeHeader("Content-type")
                        .addHeader("Accept", "*/*")
                        .addHeader("Content-type", "application/x-www-form-urlencoded; charset=UTF-8")
                        .addHeader("Cookie2", "$Version=1")
                        .addHeader("Accept-Language", "en-US")
                        .addHeader("User-Agent", ApiConfig.userAgent)
                        .method(original.method(), original.body())
                        .build();
                return chain.proceed(request);
            }
        });

        OkHttpClient client = httpClient.build();

        if (apiInterface == null) {
            Retrofit retrofit = new Retrofit.Builder()
                    .baseUrl(ApiConfig.baseUrl)
                    .addConverterFactory(GsonConverterFactory.create())
                    .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                    .client(client)
                    .build();
            apiInterface = retrofit.create(ApiInterface.class);
        }
        return apiInterface;
    }`

**Comment by gintechsystems** [comment]
It has been a long time since I looked at this issue, but I do remember switching from OkHttp to the default HttpClient to resolve this issue, but I know I also ended up switching to Volley to for other needs. Hope this gives direction.
