### ISSUE TITLE
What's missing in Retrofit 2.0 documentation

### ISSUE THREAD

**Issue by Cartman34** [square/retrofit#1061]
First, thank you for this great library !

I think this is really missing in new documentation
- a BIG red blinking warning message at top for "Note: This site is still in the process of being expanded for the new 2.0 APIs."
- A link to 1.9.0 documentation
- A way to upgrade asynchronous callback, i use it on my android app and i don't understand documentation about that.
- Download section is below Configuration section... what the *<3*...

I have an encoding trouble with 1.9.0 and list in objects, so... i would upgrade retrofit to test if this is working with the new version.

Please, users, feel free to add your own reports.

**Comment by thinger-io** [comment]
I agree. It is necessary more documentation for this new version.

I have been able to make async calls working, but I cannot send custom body string skipping the default serializer. TypedString is not defined anymore?

**Comment by kimkr** [comment]
I agree. 
Will TypedString and TypedFile be supported by 2.0? 
If not, please let me know how to handle Multipart request.

**Comment by JakeWharton** [comment]
Use RequestBody

**Comment by KyleDBoyd** [comment]
+1

**Comment by silva96** [comment]
Can't believe the 1.9 documentation is gone!, please give us a link to it.

I was trying to understand why Calbacks are not documented on 2.0, whats this Call and enqueue all about? I used to do it like this:
The API class:
```
@POST("/somepath/{param1}/")
        void myRequest(
                @Path("param1") String param1,
                Callback<MyObject> cb);
```

```
API.getService(this).myRequest(param1, new Callback<MyObject>() {
                @Override
                public void success(MyObject obj, Response response) {
                   //do something
                }

                @Override
                public void failure(RetrofitError error) {
                    //do something else
                }
            });

```

How should this be done now?

**Comment by vrstest** [comment]
Well as for Retrofit 2.0 "OkHttp is now Required". Call is a part of OkHttp Library and enqueue means Asynchronously.

Example :

-> Service

interface GithubService{
     @GET("Your Url")
     Call<List<Contributor>> repoContrib(......);
} 

- Synchronous 
Call<List<Contributor>> call  = gitHubService.repoContrib(.....);
call.execute();

Note : Be aware this will throw IlligelstateException or Network on Main Thread.

- Asynchronous 

Call<List<Contributor>> call  = gitHubService.repoContrib(.....);

call.enqueue(new Callback<List<Contributor>>{
    @Override
    onResponse(....);
    
   @Override
   onFailure(.....);
});

For more information on retrofit 2.0  please look at here https://speakerdeck.com/jakewharton/simple-http-with-retrofit-2-droidcon-nyc-2015

**Comment by Swisyn** [comment]
What about setLogging method? or similar?

**Comment by artem-zinnatullin** [comment]
@Swisyn logging is now not a part of Retrofit, you can do it via OkHttp Interceptors API, see https://github.com/square/okhttp/pull/1874

**Comment by aercanozcan** [comment]
I agree with @Cartman34. Specially the "A link to 1.9.0 documentation" part touched my hearth.

**Comment by jamesone** [comment]
Im wanting to use retrofit but there is no documentation for it, can someone help?

**Comment by JakeWharton** [comment]
There's a whole website and some simple samples in the repo. There's also
some good articles you can Google.

**Comment by JakeWharton** [comment]
> a BIG red blinking warning message at top for "Note: This site is still in the process of being expanded for the new 2.0 APIs."

There's has always been a warning. Big, red, and blinking is unnecessary.

> A link to 1.9.0 documentation

The website, samples, and tests are in the git repo under the 1.9.0 release: https://github.com/square/retrofit/tree/parent-1.9.0. We're not hosting the old site, but the latest 1.x documentation will always be at http://square.github.io/retrofit/1.x/retrofit/

> A way to upgrade asynchronous callback

Use `enqueue` on a `Call` object.

> Download section is below Configuration section

This doesn't bother me. I'd rather show the features of the library than how to get it first. There's quick links on the side and in the header.

Technically the version is first as it's in the header.

> I have an encoding trouble with 1.9.0 and list in objects

If you can create a failing test case or runnable code demonstrating the failure you can file an issue. Otherwise usage questions are best pointed at StackOverflow with the 'retrofit' tag.

> Please, users, feel free to add your own reports.

Please, users, don't! Issues where everyone piles on things are not useful. Specific issues can be tracked, updated, and resolved individually and by multiple people across multiple releases.

**Comment by JakeWharton** [comment]
Documentation is always being worked on, as we find time.
