### ISSUE TITLE
Send an array list to Backend server using Retrofit

### ISSUE THREAD

**Issue by hdkcomm** [square/retrofit#1064]
@FormUrlEncoded
    @POST("/users/search")
    void search(@Field("value") String value, Callback<List<userItem>> users);

I want to change value to array list which contains like

value["name"] = "foo@bar.com"
user["phone"] = "123456" 
value["name"] = "foo@bar.com"
user["phone"] = "123456" 
value["name"] = "foo@bar.com"
user["phone"] = "123456" 

and so on.

**Comment by NightlyNexus** [comment]
I'm not sure I understand what this looks like.
Can you give an example url with the relative path and query parameters and values?

**Comment by JakeWharton** [comment]
There's no easy way to do this. You'll want to create something nice in your application layer to map to what Retrofit needs. You can also just create a `FormEncodedTypedInput` and build the key/value pairs yourself.
```java
@FormUrlEncoded
@POST("/users/search")
void search(
    @Field("value[\"name\"]") List<String> values,
    @Field("user[\"name\"]") List<String> phones,
    Callback> users);
```
