### ISSUE TITLE
[2.0] Is RequestInterceptor gone, or is it in OkHttp now?

### ISSUE THREAD

**Issue by cgollner** [square/retrofit#1065]

**Comment by JakeWharton** [comment]
Use an OkHttp interceptor instead.

**Comment by cgollner** [comment]
Thanks! Wasn't sure if this would be implemented, or we should just go and use OkHttp interceptors.

**Comment by JakeWharton** [comment]
Retrofits interceptors pre-date OkHttps so it's nice to push more of that
into the actual HTTP client where they're even more powerful.
