### ISSUE TITLE
What return type should I declare?

### ISSUE THREAD

**Issue by NeoLSN** [square/retrofit#1066]
Old design:
```java
public interface someRestfulInterface {
    Response aCallWithNoResponseBody();
    void aCallWithNoResponseBody(Callback<Response>);
}
```
In Retrofit 2.0, what return type should I declare on the interface?
```java
public interface someRestfulInterface {
    Response aCallWithNoResponseBody();
    // or
    Call<Response> aCallWithNoResponseBody();
    // or something else?
}
```

**Comment by JakeWharton** [comment]
The latter. Some examples are here: https://github.com/square/retrofit/blob/848f330230e827475baea5bfeadd0f16f8feb476/retrofit/src/test/java/retrofit/CallTest.java#L52-L57, there's also samples in the repo and the website has been updated with this information.

Documentation will be worked on eventually, but finishing the library is of the utmost importance right now.

**Comment by NeoLSN** [comment]
Thanks!! It is very helpful.
