### ISSUE TITLE
Requests queue

### ISSUE THREAD

**Issue by phiphuc89** [square/retrofit#1070]
I have an array of urls. I want to make requests one-by-one (or some-by-some). One (or some) request won't be called unless previous request(s) finished or canceled. Can you give me an example for my case?

Thank you.

**Comment by jbaginski** [comment]
you can use Call object to cancel the query. you can easily mix it with any type of Queue.

**Comment by JakeWharton** [comment]
You can use a single-threaded `Executor` and any queue of your choosing.

In general, GitHub issues are not a good place for support. Please use StackOverflow with the 'retrofit' tag where there are many more people who will see the question as well as being a place that's a much better archive for questions.

**Comment by shobhitpuri** [comment]
@phiphuc89 Do you mind mentioning how did you end up solving this or a link to the stackoverflow question that you might have created? Thanks.
