### ISSUE TITLE
Syncronous request fails when proguard is on

### ISSUE THREAD

**Issue by aviranfdna** [square/retrofit#1074]
Hello,

I'm using retrofit 1.9.0 in an android app, everything works fine on the debug version which does not include proguard obfuscation.

When I build my release version with proguard obfuscation, the following API calls returns null for all the fields.

@GET("/access/database-versions")
DatabasesInfo getDatabasesVersions();

public class DatabasesInfo {
    public String version1;
    public String version2;
}

{"version1":"e2eeb18d8a60e6b0fe40125c8d2d1eab","version2":"0d1d83adbf30d95a867297a5e981a7ef"}

Any idea what could go wrong here? I can't debug in release mode, I see that the response from the server is good, and I get a DatabaseInfo object from the call, but all the fields are null.

heres my dependencies and my proguard conf

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.2.1'
    compile 'com.android.support:design:22.2.1'
    compile 'com.android.support:cardview-v7:22.2.1'
    compile 'com.android.support:recyclerview-v7:22.2.1'
    compile 'com.squareup.retrofit:retrofit:1.9.0*
    compile 'com.squareup.okhttp:okhttp:2.5.0'
    compile('com.crashlytics.sdk.android:crashlytics:2.5.1@aar') {
        transitive = true;
    }
    compile 'de.hdodenhof:circleimageview:1.3.0'
    compile 'com.google.android.gms:play-services-analytics:7.3.0'
    compile 'com.pusher:pusher-java-client:0.3.3'
}

====

proguard.conf

-keepclassmembers class fqcn.of.javascript.interface.for.webview {
   public *;
}

-dontwarn android.support.design.**
-keep class android.support.design.** { *; }
-keep interface android.support.design.** { *; }
-keep public class android.support.design.R$* { *; }

-dontwarn retrofit.**
-keep class retrofit.** { *; }

-dontwarn okio.**
-keep class okio.** { *; }

-dontwarn org.slf4j.**
-keep class org.slf4j.** { *; }

-keepattributes Signature
-keepattributes Exceptions

**Comment by aviranfdna** [comment]
most of the API calls does not return values, nothing really works.

**Comment by sohayb** [comment]
You should include your model classes (in your case DatabaseInfo class) in your proguard configuration to avoid obfuscation, like this:
````
-keep class com.exampleapp.model.** { *; }
````
In general, GitHub issues are not a good place for support. Please use StackOverflow with the 'retrofit' tag where there are many more people who will see the question as well as being a place that's a much better archive for questions.

**Comment by aviranfdna** [comment]
Thanks a lot, sorry about the confusion in the future I will post on SO.

**Comment by tvhieuit** [comment]
How to fix this issue. It's appear when proguard and run application:
 Caused by: java.lang.IllegalArgumentException: RequestServerAPI.getConfiguration: Last parameter must be of type Callback<X> or Callback<? super X>.
