### ISSUE TITLE
RequestInterceptor in retrofit 2 ?

### ISSUE THREAD

**Issue by grevolution** [square/retrofit#1082]
i was not able to find `RequestInterceptor`. is there some other way to achieve the same functionality of what RequestInterceptor was made for? or is it totally scraped?

**Comment by JakeWharton** [comment]
You can use an [OkHttp interceptor][1] instead. It's 100x more powerful as well.

 [1]: https://github.com/square/okhttp/wiki/Interceptors

**Comment by grevolution** [comment]
yes, figured that out :+1: thanks

**Comment by tachang** [comment]
@grevolution Any chance you could post an example?

**Comment by Rainer-Lang** [comment]
An example would be nice.

**Comment by drdavidpier** [comment]
+1 for an example

**Comment by jtuchek** [comment]
Follow Jake's link above, there's at least 2 examples right in the docs
