### ISSUE TITLE
How to centralize some attribute across Calls?

### ISSUE THREAD

**Issue by b95505017** [square/retrofit#1084]
For example, I want to set same user-agent for all my Calls to our server, but I don't want to write lots of duplicate annotations or parameters for request header. Using Interceptor may one of the workaround but may too ugly.
Thanks.

**Comment by JakeWharton** [comment]
An interceptor isn't a workaround, it's the way that this is accomplished. The same thing existed in v1 except it was a Retrofit RequestInterceptor instead of an OkHttp Interceptor.
```java
okHttpClient.interceptors().add(new Interceptor() {
  @Override public Response intercept(Chain chain) throws IOException {
    return chain.proceed(chain.request().newBuilder()
        .addHeader("User-Agent", "Whatever")
        .build());
  }
});
```
