### ISSUE TITLE
android.os.NetworkOnMainThreadException thrown for Call.cancel()

### ISSUE THREAD

**Issue by lawloretienne** [square/retrofit#1085]
I tried to call the method `cancel()` on a `Call` object but it throws a `android.os.NetworkOnMainThreadException`.  I thought this could be called on the main thread?

**Comment by JakeWharton** [comment]
Probably a dupe of https://github.com/square/retrofit/issues/1069, and technically not Retrofit's problem. That's just the tracking issue. The problem is in OkHttp and there's an issue tracking it there as well.

**Comment by lawloretienne** [comment]
Where is the OkHttp issue, so that I can follow it?  Do you have a link?

**Comment by JakeWharton** [comment]
https://github.com/square/okhttp/issues/1592

**Comment by lawloretienne** [comment]
Thanks.
