### ISSUE TITLE
why don't have cancel reuqest

### ISSUE THREAD

**Issue by vihuela** [square/retrofit#1087]
i use retrofit return obServable，not found how cancel this request

<code>

           ApiUtils.getObservable(ApiUtils.createApi().getAllCity())
                .map((CityResponse cityBean) -> cityBean.data)
                .flatMapIterable((List<CityResponse.DataEntity> dataEntities) -> dataEntities)
                .map((CityResponse.DataEntity dataEntity) -> {
                    CitySelectBean selectBean = new CitySelectBean();
                    selectBean.name = dataEntity.name;
                    return selectBean;
                })
                .toList()
                .subscribe(new ApiUtils.SubscriberWrapper<List<CitySelectBean>>(mTag) {
                    @Override
                    public void onNexts(List<CitySelectBean> citySelectBeans) {
                        if (citySelectBeans.size() == 0)
                            presenter.onEmpty("木有数据");
                        else
                            presenter.onRefreshSuccess(citySelectBeans);
                    }

                    @Override
                    public void onError(RetrofitError error) {
                        switch (error.getKind()) {
                            case NETWORK:
                                presenter.onNetWorkException();
                                break;
                            case CONVERSION:
                                presenter.onRefreshException("CONVERSION Error");
                                break;
                            case HTTP:
                                presenter.onRefreshException("HTTP Error");
                                break;
                            case UNEXPECTED:
                                presenter.onRefreshException("UNEXPECTED Error");
                                break;
                        }
                    }
                })
        ;
</code>

**Comment by JakeWharton** [comment]
You can `unsubscribe()` from the returned `Subscription` which will cancel the request. This is plugged in even more deeply in v2.0.
