### ISSUE TITLE
may I ask how to retrofit multi-file upload? 

### ISSUE THREAD

**Issue by Vence** [square/retrofit#1089]
excuse me, may I ask how to retrofit multi-file upload? Whether to support it

```
@Multipart
	@POST("/...")
	public String upload(@Path("sessionid")String sessionID, @Part("file")TypedFile file);
```

this is only Single File Upload method , all right?

**Comment by Vence** [comment]
and  i use retrofit-1.9.0 jar

**Comment by JakeWharton** [comment]
You can add multiple `TypedFile` / `TypedInput` parameters, each of which will get included in the single multi-part request.

**Comment by TangMonk** [comment]
@JakeWharton 

Hi, I have same question

If server require upload multiple image using array like params, like following:

```
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images_attributes[][image]"; filename="CgQI01U6IiGAXPlDAAIUofCNaYA71600.jpg"
Content-Type: image/jpeg


----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images_attributes[][image]"; filename="20131030095302192.jpg"
Content-Type: image/jpeg


----WebKitFormBoundary7MA4YWxkTrZu0gW
```

notice above `images_attributes[][image]` paramters

Can I upload those image with :

```
@Multipart
@POST("/...")
public String upload(@Path("sessionid")String sessionID, @Part("files[][file]")TypedFile[] file);
```

In 2.0.0 beta
