### ISSUE TITLE
[Retrofit 2.0.0-beta1] Handling no content with a 201 response

### ISSUE THREAD

**Issue by LGordon2** [square/retrofit#1090]
Hi,

I've been having an issue using Retrofit with an endpoint that returns a 201 on a POST, but with no content.  My intuition is that Retrofit is expecting some content and trying to parse it, but because there is no content it is throwing an error.  From what I've seen in the code, if the endpoint returned 204 or 205 (or a redirection) I'd be better off and wouldn't have this issue.  However, it doesn't seem trivial to change the behavior call's execute.  Hopefully I'm just missing something obvious, but I'd love an elegant solution to this issue.

Thanks!

FWIW I'm also using Retrofit's SimpleXML converter.

**Comment by JakeWharton** [comment]
You can use Call<Void> using the latest snapshot. This will skip trying to
process the body. It will be included in beta2 this week or next.

**Comment by LGordon2** [comment]
Worked well, thanks!
