### ISSUE TITLE
Synchronous Error Handling

### ISSUE THREAD

**Issue by KyleDBoyd** [square/retrofit#1095]
In retrofit, I'm able to handle a network error in the ```onFailure(Throwable t)``` method of the ```Callback```. What if I was already on the correct thread and I wanted to handle a response/network error in a catch block?

Is this possible in Retrofit 1.9? What about 2.0?

**Comment by f2prateek** [comment]
Synchronous execution in Retrofit 1would throw a `RetrofitError` (or whatever you've adapted with a custom `ErrorHandler`).

```
try {
  T foo = service.foo(...);
} catch (RetrofitError e) {
  // Either the network responded with a code < 200 or >= 300 or some other error occurred.
}
```

The same code in v2 would look like this:
```
try {
  Response<T> response = service.foo(...);
  if (!response.isSuccess()) {
    // Network responded with a code < 200 or >= 300.
  }
} catch (IOException e) {
  // Some other error occurred.
}
```

**Comment by JakeWharton** [comment]
The question is really vague. Synchronous methods throw exceptions both on v1 and v2. You can use ErrorHandler on v1 to customize the error thrown.

If you have follow-ups, please ask on StackOverflow with the 'retrofit' tag as GitHub issues aren't the greatest place for that discussion.
