### ISSUE TITLE
2.0-beta1, Manually creating and encoding a RequestBody causes Content-Length to always be '2'

### ISSUE THREAD

**Issue by stoyicker** [square/retrofit#1097]
Migrated from https://github.com/square/okhttp/issues/1864

Creating a request body does not seem to properly understand its size. 
See http://stackoverflow.com/questions/32647760/okhttp-requestbody-returning-wrong-content-length/32664465#32664465 for context.

MNWE: https://github.com/stoyicker/okHttpContentLength2Bug - Run the unit test.

**Comment by JakeWharton** [comment]
This has already been fixed on `master` and will be in the next beta. We incorrectly send the type to the converter instead of using it directly.

**Comment by JakeWharton** [comment]
You can verify using the latest SNAPSHOT that it's fixed.

**Comment by kristjanmik** [comment]
Still getting the same results with build 67(compile group: 'com.squareup.retrofit', name: 'retrofit', version: '2.0.0-SNAPSHOT-67')

`````java
RequestBody filebody = RequestBody.create(MediaType.parse(mimeType), file);
filebody.contentLength(); //is 699534
filebody.contentType(); //is image/jpeg
``````
When it hits the log interceptor/server it has content-length of 2

**Comment by kristjanmik** [comment]
Confirmed to be working in com.squareup.retrofit:retrofit:2.0.0-beta2
