### ISSUE TITLE
Where are the snapshots located?

### ISSUE THREAD

**Issue by kristjanmik** [square/retrofit#1103]
It is listed in the Readme that the location of the snapshot repo is in [Sonatype's snapshots repository](https://oss.sonatype.org/content/repositories/snapshots/), however I'm not able to find them there. Where are they supposed to be located?

**Comment by felipecsl** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/squareup/retrofit/retrofit/2.0.0-SNAPSHOT/

**Comment by JakeWharton** [comment]
The link is to the repository which you can add to your build system so that depending on the SNAPSHOT version works.

e.g., for gradle,
```groovy
repositories {
  maven {
    url 'https://oss.sonatype.org/content/repositories/snapshots/'
  }
}
```

And as @felipecsl linked, the artifacts are available in there under the path of the groupId, artifactId, and snapshot version.
