### ISSUE TITLE
Does RxJava adapted requests observe on main thread?

### ISSUE THREAD

**Issue by xingrz** [square/retrofit#1104]
I just configured Retrofit 2 with RxJava adapter as below

```java
retrofit = new Retrofit.Builder()
        .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
        /* ... */
```

and my service interface:

```java
public interface FeedApi {

    @GET("v1/feed/timeline/")
    Observable<FeedEnvelope> timeline(@Query("max_id") String maxId);

}
```

Then I make a request in my Activity and populate the result into a RecyclerView adapter like below:

```java
feedApi.timeline(null)
        .subscribe(envelope -> myRecyclerAdapter.setItems(envelope.items));
```

That RecyclerView didn't render the result until I manually scroll it.

But code below works:

```java
feedApi.timeline(null)
        .observeOn(AndroidSchedulers.mainThread())
        .subscribeOn(Schedulers.io())
        .subscribe(envelope -> myRecyclerAdapter.setItems(envelope.items));
```

**Comment by JakeWharton** [comment]
No. It calls back on a background thread. You need to observe it on the
main thread. You do not need to provide a subscription scheduler, it's
always on a background thread.
