### ISSUE TITLE
[Retrofit 2] Proguard causes IllegalArgumentException

### ISSUE THREAD

**Issue by fredpedersen** [square/retrofit#1106]
Enabling proguard with the recommended rules:

-dontwarn retrofit.**
-keep class retrofit.** { *; }
-keepattributes Signature
-keepattributes Exceptions

Causes an IllegalArgumentException: Last parameter must be of type Callback<X> or Callback<? super X>.

Interface:
public interface Weather {
    @GET("/api2/index.php")
    Call<WeatherResponse> getWeather(@Query("latitude") double latitude, @Query("longitude") double longitude, @Query("units") String units);
}

Request:
public Call<WeatherResponse> getForecast(double latitude,double longitude,String units){
        Weather mWeather = getRetrofit().create(Weather.class);
        return mWeather.getWeather(latitude, longitude, units);
}

**Comment by JakeWharton** [comment]
You are not using Retrofit 2 as that exception and the Callback type do not
exist anymore. If you want to use v2, make sure it is correctly referenced
in your build.
