### ISSUE TITLE
How to use Headers in Retrofit 2.0?

### ISSUE THREAD

**Issue by zeeshanaslam78** [square/retrofit#1107]
I am having difficulty in using Headers
Can you please give me best solution on this issue
http://stackoverflow.com/questions/32706354/how-to-get-simple-json-object-in-retrofit-2-0-0-beta-1

I want to get JSON response in my POJO

**Comment by JakeWharton** [comment]
StackOverflow is the right place for this question, and it will be answered there when we get the time (or someone else gets to it first). GitHub issues are for bugs and feature requests only.

**Comment by zeeshanaslam78** [comment]
oops wrong window
