### ISSUE TITLE
How to set listener for downloading progress?

### ISSUE THREAD

**Issue by devsoulwolf** [square/retrofit#1110]
I can't find API to call get progress function when download a file by retrofit ,How can i implement this function?

**Comment by JakeWharton** [comment]
Here's an OkHttp recipe showing how to do it in an interceptor: https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/com/squareup/okhttp/recipes/Progress.java. If you want to do it for a single call you'd need to use `ResponseBody` as your response type and then immediately wrap it with the `ProgressResponseBody` from that code snippet before you read.

**Comment by devsoulwolf** [comment]
Very glad that you can reply to me, for that matter, I have the answer, thanks!

**Comment by iamshajeer** [comment]
@JakeWharton the link you posted shows 404, can you recheck it please ?

**Comment by caiolopes** [comment]
Where exactly should I wrap with the `ProgressResponseBody`?

**Comment by julioromano** [comment]
@JakeWharton Is this at all possible without an interceptor? How to get ResponseBody from a Call<ResponseBody> object before calling execute() or enqueue() ?

**Comment by ehdtkqorl123** [comment]
@JakeWharton For Progress for RequestBody, how should writeTo() be implemented - if this is the one to modify from the recipe?

**Comment by g707175425** [comment]
@JakeWharton Is this at all possible without an interceptor? How to get ResponseBody from a Call object before calling execute() or enqueue() ?
