### ISSUE TITLE
How to unsubscribe from Observable but let the Observable run to completion

### ISSUE THREAD

**Issue by kaciula** [square/retrofit#1111]
I am using Retrofit 1.9.0.

If I unsubscribe from an in-progress Observable, I get thread interrupted but I would like the Observable to run to completion instead. If I do not unsubscribe at all then the activity (the observer) is kept in memory until the Observable finishes (which may take a lot of time).

Is there a solution for this? Am I using Observables in an improper way?

**Comment by JakeWharton** [comment]
This is a general RxJava question, not a Retrofit question.

Shooting from the hip:
```
Observable<Foo> foo = service.someApi().share();
foo.subscribe();
Subscription s = foo.subscribe(yourSubscriber());
s.unsubscribe();
```

**Comment by vedant1811** [comment]
@kaciula I am curious to why would you want to do that: Are you not at all interested in the response of the server? AFAIK, there is no way to get the response once you have unsubscribed. If you subscribe again, another request will be generated and will still take a *long* time to complete.

**Comment by JakeWharton** [comment]
If there's an HTTP response cache then it will be stored there for
subsequent requests.
