### ISSUE TITLE
@PUT file without use @Multipart

### ISSUE THREAD

**Issue by andersonacs** [square/retrofit#1112]
I'm trying to port my code from 1.9.0 to version 2, my current request:

```Java
Bitmap bm = BitmapFactory.decodeFile(mCurrentPhotoPath);
ByteArrayOutputStream baos = new ByteArrayOutputStream(); bm.compress(Bitmap.CompressFormat.JPEG, 100, baos); //bm is the bitmap object
byte[] b = baos.toByteArray();

TypedInput body = new TypedByteArray("image/jpg", b);
```
```Java
@PUT("/{Key}")
void upload(@Path("Key") String Key,
            @Header("Content-Length") long length,
            @Header("Host") String host,
            @Header("Date") String date,
            @Header("Content-type") String contentType,
            @Header("Authorization") String authorization,
            @Body TypedInput body, Callback<String> mCallback);
``` 

Some sample code equivalent to the code above using Retrofit 2?

**Stackoverflow question**: [aws-s3-rest-api-with-android-retrofit-v2-library-uploaded-image-is-damaged](http://stackoverflow.com/questions/32663281/aws-s3-rest-api-with-android-retrofit-v2-library-uploaded-image-is-damaged)

I tried use this :

`RequestBody body = RequestBody.create(MediaType.parse("image/jpeg"), file);`

but **RequestBody** required `@Multipart` annotation, 

My project using 1.9.0 version work fine:

[AmazonS3-Example](https://github.com/andersonacs/AmazonS3-Example)

thanks;

**Comment by JakeWharton** [comment]
> but RequestBody required @Multipart 

This is not true. What made you believe this is the case?

**Comment by andersonacs** [comment]
Sorry, my mistake, "but RequestBody required @Multipart", I do not believe that's the problem in fact.

But when I use 

But in this case I need send my content like Retrofit 1.9.0, using `TypedByteArray` and `@Body` this is working currently.

what would be the equivalent way RequestBody?

**Comment by JakeWharton** [comment]
`RequestBody.create` takes a `byte[]` and also a `MediaType` which is the content type of the file. For this you would pass `MediaType.create("image/jpeg")` (or whatever the appropriate content type of the file is).

**Comment by andersonacs** [comment]
OK, I'll verify this approach!

thanks!

**Comment by andersonacs** [comment]
Hi @JakeWharton, Sorry me for my confusion, actually `@Part` requires `@Multpart` and not `RequestBody`, by the way what I need is send the image using Base64 serialization like that [android-retrofit-base64-body](http://stackoverflow.com/questions/22787585/android-retrofit-base64-body)

I'm using Paw rest client for Mac to validation my request, and works fine, right now am trying make the same request using Restrofit.

thanks again.
