### ISSUE TITLE
Annotate entire service with path

### ISSUE THREAD

**Issue by YuriHeupa** [square/retrofit#1113]
Is there any way to annotate my entire service with a url path, which will be appended to all methods?

i.e. change the following:

    Retrofit retrofit = new Retrofit.Builder()
            .baseUrl("http://example.com")
            .build();

    public interface ApiService {

        @GET("/v1/api/admin")
        Call<Object> login();
        @POST("/v1/api/admin")
        Call<Object> logout();

    }

To: 

    Retrofit retrofit = new Retrofit.Builder()
            .baseUrl("http://example.com/v1")
            .build();

    @ServicePath("/api")
    public interface ApiService {

        @GET("/admin")
        Call<Object> login();
        @POST("/admin")
        Call<Object> logout();

    }

In the expected example i added the path /v1 to the base url, which i'm trying to use actually, but the retrofit seems to ignore the path.

PS. I'm using the latest version.

**Comment by JakeWharton** [comment]
Add a trailing slash to the base URL, remove the leading slash from the relative URL. These work like `<a href="">`.

**Comment by YuriHeupa** [comment]
Ok, the base url is working now, but the main question is, how can i add a base path to entire service?

**Comment by JakeWharton** [comment]
Sorry, I meant add a trailing slash after the "v1" in your second example.

If I resolve "foo/bar/" on "http://example.com/v1" I get "http://example.com/foo/bar" because "v1" and "foo" are siblings.
If I resolve "foo/bar/" on "http://example.com/v1/" I get "http://example.com/v1/foo/bar" because "foo/bar" is a child of "v1/".

**Comment by JakeWharton** [comment]
Documentation on this, with example is coming. There's a lot going on right now and just haven't gotten to it yet!

**Comment by JimmyRojas** [comment]
Hi I have this scenario..
String baseUrl = "https://example1.com/serviceAddress/";
        retrofit = new Retrofit.Builder()
                .baseUrl(baseUrl)
                .addConverterFactory(GsonConverterFactory.create())
                .build();
I need to resolve for v1/authentication/login

but I'm getting a "java.net.SocketTimeoutException: timeout" error message

any idea...?

**Comment by tomkoptel** [comment]
"It means the specific destination is unable to connect / unable to read" (Jayachandran K)[[1]](http://www.coderanch.com/t/602741/java/java/Explain-java-net-SocketTimeoutException-Read)

It looks like either your server down or you have issues with network connectivity.

**Comment by JimmyRojas** [comment]
Thank you sir, I could solve my issue... BTW I found great samples to understand the scenario here
http://inthecheesefactory.com/blog/retrofit-2.0/en
