### ISSUE TITLE
Retrofit 2.0 @Part converting even Strings

### ISSUE THREAD

**Issue by gnumilanix** [square/retrofit#1116]
Here is my retrofit interface which I use to upload file to the server. This was working fine with Retrofit **1.9**:

    public interface FileUploadApi {
    @Multipart
    @POST("/api/{actionPath}")
    Call<FileUpload> upload(
		    @Path("actionPath") String actionPath,
            @Part("os") String os,
            @PartMap Map<String, ?> photo);
    }

The javadoc in the Retrofit 2.0 says:

 > The parameter type on which this annotation exists will be processed in one of three ways:
> - If the type is {@link String} the value will also be used directly with a {@code text/plain} content type. 
> - Other object types will be converted to an appropriate representation by using {@linkplain Converter a converter} 
> - Values may be {@code null} which will omit them from the request body.

I have also tried adding os like this:
> final MediaType formDataType = MediaType.parse("multipart/form-data");
> final HashMap<String, RequestBody> params = new HashMap<>();
> params.put("os", RequestBody.create(formDataType, image.getKey()));

Here's my gradle imports:
> compile 'com.squareup.retrofit:retrofit:2.0.0-beta1'
> compile 'com.squareup.retrofit:converter-gson:2.0.0-beta1'

With retrofit 2 I have added a GSON converter but, now I get an exception:

> Caused by: java.lang.IllegalStateException: JSON must start with an array or an object.
com.google.gson.stream.JsonWriter.beforeValue(JsonWriter.java:609)
com.google.gson.stream.JsonWriter.nullValue(JsonWriter.java:437)
com.google.gson.internal.Excluder\$1.write(Excluder.java:134)
com.google.gson.TypeAdapter.toJson(TypeAdapter.java:142)
retrofit.GsonConverter.toBody(GsonConverter.java:55)
retrofit.RequestBuilderAction\$PartMap.perform(RequestBuilderAction.java:239)
retrofit.RequestFactory.create(RequestFactory.java:62)
retrofit.OkHttpCall.createRawCall(OkHttpCall.java:116)
retrofit.OkHttpCall.execute(OkHttpCall.java:106)
retrofit.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:59)

**Comment by gnumilanix** [comment]
Issue should be closed, tested with snapshot and it's fine:

> compile 'com.squareup.retrofit:retrofit:2.0.0-SNAPSHOT'
> compile 'com.squareup.retrofit:converter-gson:2.0.0-SNAPSHOT'

**Comment by Bajranghudda1** [comment]
See this link it might help you...
https://github.com/square/retrofit/issues/811
