### ISSUE TITLE
error: package retrofit.client does not exist

### ISSUE THREAD

**Issue by IgorGanapolsky** [square/retrofit#1124]
Hello,
I tried to use `compile 'com.squareup.retrofit:retrofit:2.0.0-beta1'`, but then I get a compilation error:
> Error:(9, 23) error: package retrofit.client does not exist

Please advise.

**Comment by JakeWharton** [comment]
Retrofit no longer includes a client abstraction and depends directly on OkHttp instead.

**Comment by IgorGanapolsky** [comment]
Then why can't I `import retrofit.RetrofitError

**Comment by JakeWharton** [comment]
Because it was deleted

**Comment by IgorGanapolsky** [comment]
Can you please advise what I should use instead of it?

**Comment by JakeWharton** [comment]
There is no equivalent in V2. It was a poor design that has been corrected
in the new version.

See either http://square.github.io/retrofit/ or
https://realm.io/news/droidcon-jake-wharton-simple-http-retrofit-2/ for
more information.

**Comment by IgorGanapolsky** [comment]
Ok, thanks for your efforts.  @JakeWharton @changetip $1

**Comment by changetip** [comment]
Hi @jakewharton, @IgorGanapolsky sent you a tip worth 4,225 bits ($1.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/899577)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**
