### ISSUE TITLE
Any plan to support MessagePack

### ISSUE THREAD

**Issue by kamoljan** [square/retrofit#1128]
Hi guys!

Do you have any plan to support [MessagePack](http://msgpack.org/index.html)?

**Comment by f2prateek** [comment]
You can easily write your own [`Converter`](https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit/Converter.java) implementation wrapping the MessagePack Java library. It doesn't need to be in the core library. There are plenty of examples to see in the [`converters` module](https://github.com/square/retrofit/tree/master/retrofit-converters).

**Comment by kamoljan** [comment]
@f2prateek Clear! Thank you very much!

**Comment by chintan-mishra** [comment]
Request to reopen this issue. I have made a converter for MessagePack and I plan on opening a pull request. I have tried to adhere to the code pattern as used in converter for Jackson.

**Comment by JakeWharton** [comment]
We are not accepting any new first-party converters at this time. Please
publish it as a separate library. There is a wiki page which lists all of
the third-party converters.
