### ISSUE TITLE
Use more sophisticated path replacement leveraging HttpUrl's native encoding

### ISSUE THREAD

**Issue by JakeWharton** [square/retrofit#1129]
And delete all the custom path encoding introduced in #1123.

As we discussed. Just creating this as a tracking issue.

**Comment by NightlyNexus** [comment]
May I ask what thoughts were here?
Copy HttpUrl's `canonicalize` implementation?
Refactor the usage of `relativeUrl`?

**Comment by JakeWharton** [comment]
The implementation is already copied, that's what I'm trying to delete. The idea is that we `resolve()` the relative URL immediately on `RequestBuilder` creation and then when doing path replacement we read the segment string, replace the value, and set that segment back on the builder. This pushes all encoding responsibility into `HttpUrl`.

**Comment by JakeWharton** [comment]
We have determined that, for the time being, there's no feasible way to work this into OkHttp's API. Some details are at https://github.com/square/okhttp/issues/2171. The encoding rules will remain duplicated into Retrofit.
