### ISSUE TITLE
How to properly upload a File (multipart/form-data) using Retrofit 2.0-beta2 

### ISSUE THREAD

**Issue by vivekkiran** [square/retrofit#1137]
This is in connection with https://github.com/square/retrofit/issues/1063, I need a sample code uploading file as multipart/form-data, in Retrofit 2.0-beta2, there is no much documentation and examples anywhere on properly uploading a file using retrofit 2.0-beta2, I have followed the recipe given in OkHttp's wiki for posting a multipart request and its working fine, but I would like have an example for retrofit 2.0-beta2.

**Comment by ayon115** [comment]
I have posted sample code in #1063 , It will help hopefully.

**Comment by JakeWharton** [comment]
Rolling this into #1140 as they're the same thing.

**Comment by vivekkiran** [comment]
Thanks, @ayon115 your sample code helped a lot :).
