### ISSUE TITLE
Add a way to set filename on multipart requests

### ISSUE THREAD

**Issue by lukaciko** [square/retrofit#1140]
This has already been discussed in #1063 #1092 #1096 and #1130, but I thought I'd open a separate issue to track this specifically.

[RFC2388](https://www.ietf.org/rfc/rfc2388.txt) describes the `filename` header parameter of `multipart/form-data` requests that Retrofit now uses. This parameter is required on some backend configurations. More details and examples can be found [here](http://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.2).

We need a way of figuring out what the filename is. The problem with `RequestBody` (which is a part of OkHttp) is that it doesn't expose the filename when created with a `File`.

**Comment by erikdcch** [comment]
Hi @lukaciko I had the same problem but finally I found the solution of this bug. I just had to add the name of the field in @Part() RequestBody.

This is an example: 
Call<Object> postMethod(@Part("picture\"; filename=\"1.jpg\" ") RequestBody file);

picture - is the name of the parameter and after put the "filename" parameter with any name.

Note: Do not forget scape quotation marks  :)

**Comment by wKovacs64** [comment]
That may work, but it seems a bit hacky. Inherent support would seem more natural.

Should this be an OkHttp issue rather than a Retrofit one? Maybe the `File` overload of the `RequestBody.create()` could automatically include the `filename` header parameter obtained via `File#getName()` or something.

**Comment by lukaciko** [comment]
Injecting the filename can be used as a workaround, but it's not exactly pretty. It'd be better if it could be defined with an optional annotation parameter (i.e. `@Part(value="picture", filename="cool_cat.jpg")` but this still has the bigger issue - form field name is known in advanced and is thus a part of the interface, but filenames are dynamic.

@JakeWharton you've advocated using `RequestBody` directly when creating requests. Any ideas how we could change the API to accommodate this?

**Comment by JakeWharton** [comment]
Sorry I haven't been too involved here. There is a lot going on in this
library, others, and internally, so I can only focus on so many things at
once.

Most of what you describe has nothing to do with Retrofit, but OkHttp.
RequestBody is an OkHttp type and internally we use OkHttp's multipart
builder. The filename property of TypedInput always felt out-of-place, so I
don't think we're likely to add it to RequestBody (which is the analogous
to TypedInput now).

I would encourage you to experiment with it and see possible ways forward
if you can. Otherwise I will take a look before v2.0, but I can't promise
when that will be just yet.

**Comment by BugsBunnyBR** [comment]
I have looked at the source of Retrofit and OkHttp and without changing RequestBody implementation/usage it seems a good way to go is to add some annotation as @PartFile("file") with a File object, retrofit could use it to set the "filename" header and to create the RequestBody object.

**Comment by JakeWharton** [comment]
@BugsBunnyBR Yeah, that seems reasonable. I'll start thinking about this. It will be resolved with a sample before 2.0 is released.

**Comment by wKovacs64** [comment]
@JakeWharton Bugs and I made an attempt in #1188 if that's of any value.

**Comment by AtanL** [comment]
It's a possible way to support file name rather than (@Part("picture\"; filename=\"1.jpg\" ") ? I look not such pretty but error-prone.

**Comment by wKovacs64** [comment]
@AtanL That's what #1188 does. It would look something like this:

```java
File file = /* ... */;
TypedFile image = new TypedFile("image/png", file);

// ...

@PartFile("image") TypedFile image
```

The file name would default to the result of `File#getName()` but you could override it when creating a new `TypedFile` if desired. I'm not sure if this is the way the project wants to go yet, but it's out there.

**Comment by newmanw** [comment]
Not sure what the 

Using beta.2

```java
    public interface UploadService {
        @Multipart
        @PUT("/somepath/upload")
        Call<ResponseBody> upload(@Part("uploadFile") RequestBody upload);
    }

    UploadService service = retrofit.create(UploadService.class);

    File file = new File(filePath);
    RequestBody requestBody = RequestBody.create(MediaType.parse(mimeType), file);
    Response<ResponseBody> response = service.upload(requestBody).execute();
```

I would expect headers to look something like this:

```text
Content-Disposition: form-data; name="fileUpload"; filename="somefile.jpg"
Content-Type: image/jpeg
```

Attached a log interceptor to OkHttp and am only seeing these headers:

```text
 D/OkHttp: --> PUT /somepath/upload HTTP/1.1
 D/OkHttp: Authorization: Bearer 12345
 D/OkHttp: Accept-Encoding: gzip
 D/OkHttp: --> END POST
1```

Is multipart file upload still broken?

**Comment by newmanw** [comment]
@erikdcch 

Call postMethod(@Part("picture\"; filename=\"1.jpg\" ") RequestBody file);

Does indeed work.  However, from what I can tell there is no way to set a dynamic filename.  IE I don't want to filename to be the same for every upload.

When removing the 'filename' portion the upload does not work.

**Comment by newmanw** [comment]
Seems @ayon115 found a good workaround for dynamic filename here: https://github.com/square/retrofit/issues/1063#issuecomment-145920568

**Comment by UMFsimke** [comment]
Btw guys, even with all this solutions I have next problem.

```java
@Multipart
    @PUT("users/{id}")
    Call<JsonObject> uploadInsuranceCardImage(@Path("id") String id,
                                  @Part("profile\"; filename=\"image.jpg\"") RequestBody file);
```
When I do logging I get:
```java
Content-Disposition: form-data; name="profile"; filename="image.jpg""
D/OkHttp﹕ Content-Transfer-Encoding: binary
D/OkHttp﹕ Content-Type: image/jpeg
D/OkHttp﹕ Content-Length: 58077
```
Notice on the end of filename double quotes.
If I remove escape quote after extension everything works fine

**Comment by JakeWharton** [comment]
So the solution to this actually going to mostly live in OkHttp as a model representing both an entire multipart body and its parts (https://github.com/square/okhttp/pull/2082). This will allow a `Multipart.Part` to be passed for `@Part` which carries the required information for named files.

**Comment by TimeManx** [comment]
@JakeWharton Has this been integrated into beta3?

**Comment by JakeWharton** [comment]
No

**Comment by ArslanAli7** [comment]
Hello @JakeWharton  i am also waiting for this feature to be implemented,when can we  have this feature live with beta3,currently the upload request isn't working with hard coded file name as well,that was previously working with beta2.

**Comment by grennis** [comment]
Just want to re-iterate comment from @UMFsimke 

Many people have been repeating this workaround, but this does not work with all servers:

    @Part("profile\"; filename=\"image.jpg\"")

This is wrong; it generates an extra quote. Should be:

    @Part("profile\"; filename=\"image.jpg")

Formatted this way, the workaround does work for me.

**Comment by TimeManx** [comment]
@JakeWharton Has this been integrated into beta4?

**Comment by JakeWharton** [comment]
No

**Comment by mesterj** [comment]
It would be ever corrected? ;-)

**Comment by shakil807g** [comment]
no

**Comment by mesterj** [comment]
Really?? It is time to start learning Volley??

**Comment by grennis** [comment]
No, it's time to start contributing and helping resolve the issue if it is that much of a problem for you. There is a simple documented workaround so I don't know why it would be though. By the way, volley is more analogous to okhttp, not retrofit, so not really appropriate.

**Comment by mesterj** [comment]
I don't find workaround what is working. There are a lot bad solution here and stackoverflow. Can you show me the working version? I would be check .

**Comment by newmanw** [comment]
@mesterj Looking at the first post, there are many links to other discussions about this.  I am using this and it is working great.

https://github.com/square/retrofit/issues/1063#issuecomment-145920568

**Comment by mesterj** [comment]
It would be a very good example if I have any idea about what is  AZUtils a how do I use. This kind of "help" is useless.

**Comment by ArslanAli7** [comment]
@mesterj  Its working great for me also.[https://github.com/square/retrofit/issues/1063#issuecomment-145920568](url)

**Comment by mesterj** [comment]
Thank you. I found two workaround and I made my third which is really works. :-)

**Comment by gichamba** [comment]
@mesterj Care to share?

**Comment by mesterj** [comment]
In the API interface:

 @Multipart
 @POST("upload")
 Call<ResponseBody> uploadImage(@PartMap Map<String, RequestBody> params);

When you have the file:

Map<String, RequestBody> map = new HashMap<>();
RequestBody fileBody = RequestBody.create(MediaType.parse("image/jpg"), file);
map.put("file\"; filename=\"" + file.getName(), fileBody);

**Comment by wKovacs64** [comment]
Using a map works (and may be the best option for beta versions of Retrofit 2 before they brought in OkHttp 3), but I believe they promoted `Multipart` for exactly this scenario. The current intended way to upload a file while specifying a filename (afaict) is using `Multipart.Part`. Something like this:

Interface:
```java
@Multipart
@POST("upload")
Call<UploadResponse> uploadImage(@Part MultipartBody.Part filePart)
```

Client:
```java
RequestBody fileReqBody = RequestBody.create(mediaType, file);
MultipartBody.Part filePart =
    MultipartBody.Part.createFormData(partName, file.getName(), fileReqBody);

Call<UploadResponse> call = api.uploadImage(filePart);
```

**Comment by gwilli** [comment]
If you're using Jackson, you'll likely get the error:
`Unable to convert okhttp3.MultipartBody$Part to RequestBody`
In this case, you can use `MultipartBody.Builder()` like this:
Interface:
```
@POST("upload")
Call<UploadResponse> uploadImage(@Body RequestBody requestBody);
```
Client:
```
RequestBody requestBody = new MultipartBody.Builder()
     .setType(MultipartBody.FORM)
     .addFormDataPart(partName, file.getName(), RequestBody.create(mediaType, file))
     .build();

Call<UploadResponse> call = api.uploadImage(requestBody);
```

**Comment by JakeWharton** [comment]
MultipartBody.Part is not for @Body parameters but for @Part ones

**Comment by mesterj** [comment]
Thank you. It is much better.

**Comment by sbljayarathna** [comment]
This is my code. This works..
```
public interface FileUploadService {  
    @Multipart
    @POST("upload")
    Call<ResponseBody> upload(@PartMap Map<String, RequestBody> params);
}

 private void uploadFile() {  
        FileUploadService service =
                ServiceGenerator.createService(FileUploadService.class);

        File file = new File(selectedImagePath);
image_name = file.getName();
String fileName = "file\"; filename=\"" + image_name;
RequestBody requestBody = RequestBody.create(MediaType.parse("multipart/form-data"), file);

 RequestBody id = RequestBody.create(MediaType.parse("multipart/form-data"), observation_id);

Map<String, RequestBody> requestBodyMap = new HashMap<>();
 requestBodyMap.put("id", id);
requestBodyMap.put(fileName, requestBody);


        Call<ResponseBody> call = service.upload(requestBodyMap);
        call.enqueue(new Callback<ResponseBody>() {
            @Override
            public void onResponse(Call<ResponseBody> call,
                                   Response<ResponseBody> response) {
                Log.v("Upload", "success");
            }

            @Override
            public void onFailure(Call<ResponseBody> call, Throwable t) {
                Log.e("Upload error:", t.getMessage());
            }
        });
    }
```

**Comment by jalle007** [comment]
WTH is observation_id in your code?

**Comment by marieldee** [comment]
i am also using a PartMap, and kept getting 500 internal server error when i would add an image to the multipart request. i just tried out what @sbljayarathna did, and it worked for me, too. (thanks!)

**Comment by Harmeet2491** [comment]
I am trying to upload a pdf file but I keep getting unprocessable entity 
RequestBody requestFile =
                RequestBody.create(MediaType.parse("multipart/form-data"), file);

**Comment by yuanjunli** [comment]
@UMFsimke what does you mean"Notice on the end of filename double quotes.
If I remove escape quote after extension everything works fine"
can you just show me the code
