### ISSUE TITLE
What is the latest version of compile logging-interceptor

### ISSUE THREAD

**Issue by nvhaiwork** [square/retrofit#1141]
I got this guild in readme.md file but I don't know where to get the "(insert latest version)", can you help me to get it?
 ``` 
compile 'com.squareup.okhttp:logging-interceptor:(insert latest version)'
 ```

Thanks

**Comment by JakeWharton** [comment]
Retrofit has no project of such name. OkHttp has a logging interceptor module that was just added and has not been released yet. You'll have to use its latest snapshot or build a local jar yourself.
