### ISSUE TITLE
Add Spring Cloud NetFlix ribbon load balancer support

### ISSUE THREAD

**Issue by gregturn** [square/retrofit#1143]
Right now, if you using Spring Cloud and it's Ribbon support, Feign is VERY easy to use in scaling REST endpoints with logical URLs instead of physical ones.

For example:
```java
@FeignClient("stores")
public interface StoreClient {
    @RequestMapping(method = RequestMethod.GET, value = "/stores")
    List<Store> getStores();

    @RequestMapping(method = RequestMethod.POST, value = "/stores/{storeId}", consumes = "application/json")
    Store update(@PathVariable("storeId") Long storeId, Store store);
}
```
In this example, "stores" is defined as a logical endpoint provided by [Ribbon's load balancer](http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html#spring-cloud-feign) instead of a physical URL like http://my-rest-service.foo.com.

Adding support to Retrofit for [Spring Cloud](http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html) would be VERY nice and make me not to have to rewrite all my interfaces already defined in retrofit.

**Comment by JakeWharton** [comment]
Isn't this what our [`BaseUrl`][1] class already does? It's called once per request for the base URL on which the relative paths are assembled. This lets you use any strategy you want for changing the host to which you connect provided it can be represented as the base of the URL.

Even if that's not enough, you could use a dummy host like `http://stores/` in Retrofit but configure the underlying OkHttpClient to have [an interceptor][2] which rewrote the URL on the way out using the load balancer.

 [1]: https://github.com/square/retrofit/blob/07d1f3de5e0eb11fb537464bd14fdbacfc9e55a7/retrofit/src/main/java/retrofit/BaseUrl.java
 [2]: https://github.com/square/okhttp/wiki/Interceptors

**Comment by gregturn** [comment]
Thank. It appears one of my teammates wrote just what you suggested.

https://github.com/spencergibb/okhttp-ribbon/blob/master/README.md

**Comment by JakeWharton** [comment]
Awesome! Thanks for sharing it.
