### ISSUE TITLE
Is it possible to Make a Request Parameter optional ?

### ISSUE THREAD

**Issue by ayon115** [square/retrofit#1144]
I am making a Multipart request with Retrofit 2.0.0-beta2 , where I upload an image and some text data. File part is optional here, that means user may or may not choose an image. Is there a way to make any parameter optional in Retrofit ? Currently app crashes, when `@Part RequestBody file` is null.

**Comment by tom-bell** [comment]
The solution here would be to create another method without that parameter. The calling code would then make the distinction as to whether to pass the data, and call that method or not.

```java
@POST("/url")
public Call<Response> sendData(@Part RequestBody data, @Part RequestBody text);

@POST("/url")
public Call<Response> sendData(@Part RequestBody text);
```

**Comment by ayon115** [comment]
Thanks for your help. I have used a PartMap<String, RequestBody> instead to overcome this issue. When I don't have to send the optional parameter, I just didn't put that into the Map. That solves the problem.

**Comment by socialcodia** [comment]
@tom-bell , i was thinking the same logic. before opening google chrome. :D
