### ISSUE TITLE
Custom Delete Method with Retrofit 2.0

### ISSUE THREAD

**Issue by MichaelSchmidtt** [square/retrofit#1145]
Accoring to @JakeWharton it is possible to overwrite Rest Methods. I need a customized method (DELETE with Body) as it isn´t allowed by retrofit even if it´s allowed by rfc spec.
But this does not work anyore since the Annotation @RestMethod was removed since retrofit 2.0
So how can I send now a HTTP-DELETE with Body?

see alsow: https://github.com/square/retrofit/issues/426
and https://github.com/square/okhttp/issues/605

If I use default mechnism of retrofit 2.0 i get a stacktrace

```
@DELETE("/myurl")
    Call<String> deactivateUserPermanently(
            @Header("Authorization") String systemAuthLine,
            @Body MyBodyRequest myBodyRequest
    );
```

```java
java.lang.IllegalArgumentException: Non-body HTTP method cannot contain @Body.
    for method MyProxy.deactivateUserPermanently
	at retrofit.Utils.methodError(Utils.java:177)
	at retrofit.Utils.methodError(Utils.java:167)
	at retrofit.RequestFactoryParser.parseParameters(RequestFactoryParser.java:359)
	at retrofit.RequestFactoryParser.parse(RequestFactoryParser.java:60)
	at retrofit.MethodHandler.create(MethodHandler.java:30)
	at retrofit.Retrofit.loadMethodHandler(Retrofit.java:151)
	at retrofit.Retrofit$1.invoke(Retrofit.java:132)
	at com.sun.proxy.$Proxy7.deactivateUserPermanently(Unknown Source)
```

**Comment by MichaelSchmidtt** [comment]
https://github.com/square/retrofit/issues/426

**Comment by JakeWharton** [comment]
You can use the `@HttpMethod` annotation to create custom verbs in Retrofit 2.

**Comment by MichaelSchmidtt** [comment]
@JakeWharton  - that doesn´t work

if i use a custom annotation like 

```
import javax.ws.rs.HttpMethod;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

@Target(METHOD)
@Retention(RUNTIME)
@HttpMethod(value = HttpMethod.DELETE)
public @interface DELETE_WITH_BODY {
    String value();
}
```


and use it like this
```
@DELETE_WITH_BODY("/myurl")
    Call<String> deactivateUserPermanently(
            @Header("Authorization") String systemAuthLine,
            @Body MyBodyRequest myBodyRequest
    );
```

I get following stacktrace

```
java.lang.IllegalArgumentException: HTTP method annotation is required (e.g., @GET, @POST, etc.).
    for method MyProxy.deactivateUserPermanently
	at retrofit.Utils.methodError(Utils.java:177)
	at retrofit.Utils.methodError(Utils.java:167)
	at retrofit.RequestFactoryParser.parseMethodAnnotations(RequestFactoryParser.java:135)
	at retrofit.RequestFactoryParser.parse(RequestFactoryParser.java:59)
	at retrofit.MethodHandler.create(MethodHandler.java:30)
	at retrofit.Retrofit.loadMethodHandler(Retrofit.java:151)
	at retrofit.Retrofit$1.invoke(Retrofit.java:132)
	at com.sun.proxy.$Proxy7.deactivateUserPermanently(Unknown Source)
	at xxx.xxx.MyGateway.deactivateUserPermanently(MyGateway.java:354)
```

**Comment by Zhuinden** [comment]
Copied from the referred issue, as `@HttpMethod` is misleading.

```
interface Example {
  @HTTP(method = "CUSTOM1", path = "/foo")
  Call<ResponseBody> method();
}
```

**Comment by chinmaygit** [comment]
@Zhuinden  This is correct one.
interface Example {
@HTTP(method = "DELETE", path = "/foo, hasBody = true")
Call method();
}

**Comment by nindzyago** [comment]
Actually, the correct syntax is:
@HTTP(method = "DELETE", path = "/foo", hasBody = true)

**Comment by cleber-henriques-ilegra** [comment]
Hey folks!
What if need to send query params and body? I've tried `@http(method = "DELETE", path = "/foo", hasBody = true)` but retrofit (or OkHttp) is adding `/` to the end of path, so, i'm getting something like this: `/path/to/url/?param1=abc`.

**Comment by Santi92** [comment]
Hey guys,

If you have conflict with the serialization of the answer, this works for me

API
`  @HTTP(method = "DELETE", path ="----", hasBody = true)
    fun deleteGiftCard(
                       @Body body: ObjectRequest): Observable<okhttp3.ResponseBody>`

Response

`.subscribe(
                        { result ->

                           val response = Gson().fromJson(result.string(), GiftAddResponse::class.java)

                            (response (result != null,response.totalOrder))
                        },
                        {
                            (response (false,0))
                        }`

**Comment by Zhuinden** [comment]
@Santi92 out of curiousity, why not use `GsonConverterFactory` and receive `Observable<YourObjectResponse>` from Retrofit?

**Comment by Santi92** [comment]
@Zhuinden I got it.
But do not serialize it, in the okHttpClient-Interceptor interceptor if you show the body.
Super strange, the names of the keys is fine.

Does it work for you?
