### ISSUE TITLE
How to set log in new version retrofit?

### ISSUE THREAD

**Issue by uziassantosferreira** [square/retrofit#1147]
Hello guys, how to set log in new version beta retrofit?
as it once was:
restAdapterBuilder.setLogLevel(RestAdapter.LogLevel.FULL);

but how is now in new version ?

**Comment by ersen-osman** [comment]
You have to do it through a OK Http client using incerceptor. 

```java
 OkHttpClient okHttpClient = new OkHttpClient();

 okHttpClient.interceptors().add(new Interceptor() {
                @Override
                public Response intercept(Chain chain) throws IOException {

                  Request originalRequest = chain.request(); //Current Request

                  Response response = chain.proceed(originalRequest); //Get response of the request

                    /** DEBUG STUFF */
                    if (BuildConfig.DEBUG) {
                        //I am logging the response body in debug mode. When I do this I consume the response (OKHttp only lets you do this once) so i have re-build a new one using the cached body
                        String bodyString = response.body().string();
                        DebugUtils.Log(String.format("Sending request %s with headers %s ", originalRequest.url(), originalRequest.headers()));
                        DebugUtils.Log(String.format("Got response HTTP %s %s \n\n with body %s \n\n with headers %s ", response.code(), response.message(), bodyString, response.headers()));
                        response = response.newBuilder().body(ResponseBody.create(response.body().contentType(), bodyString)).build();
                    }

                  return response;
                  }
            });
```

And then on your retrofit instance

```java
 retrofit = new Retrofit.Builder()
 .client(okHttpClient)
 .build();
```

This line is quite important 
```java
   response = response.newBuilder().body(ResponseBody.create(response.body().contentType(), bodyString)).build();
```

You can only consume a response once, if you do it twice, you get an exception, this line basically rebuilds the response only if we are debug mode. On release its ignored.

Also Debug utils is just my helper class. its just a simple Log.e in android :)

I hope this helps.

**Comment by RichardLindhout** [comment]
Thanks @ersen-osman! But I alsno need the interceptor for my OAuth refresh token refresher.
How can I combine. Maybe rebuild it to the authenticate class or something?

**Comment by RichardLindhout** [comment]
Wait.. It seems like you can add multipli interceptors. I'll try that out :+1:

**Comment by JakeWharton** [comment]
I added a [logging interceptor][1] to OkHttp which will ship with its next version. If you want to use it now you have to build your own jar, or use the current SNAPSHOT dependency.

Retrofit might have logging of Java types, but for v1-style logging the linked interceptor is the right choice.

 [1]: https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor

**Comment by mohit-sharma-87** [comment]
Hi , 

I am not able to view header parameters of request using logging interceptor . Please find the code 

  HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
        interceptor.setLevel(HttpLoggingInterceptor.Level.BODY);
        OkHttpClient client = new OkHttpClient.Builder()
                .addNetworkInterceptor(new Interceptor() {
                    @Override
                    public Response intercept(Chain chain) throws IOException {
                        Request.Builder builder = chain.request().newBuilder();
                        Set<Map.Entry<String, String>> entrySet = requestHeaderMap.entrySet();
                        for (Map.Entry<String, String> entry : entrySet) {
                            if (entry.getValue().isEmpty())
                                builder.removeHeader(entry.getKey());
                            else
                                builder.addHeader(entry.getKey(), entry.getValue());
                        }
                        Request request = builder.build();
                        return chain.proceed(request);
                    }
                })
                .addNetworkInterceptor(interceptor)
                .build();
------------------ Retrofit Client ---------------------- 
new Retrofit.Builder()
                .baseUrl(Constants.BASE_URL)
                .client(client)
                .addConverterFactory(GsonConverterFactory.create())
                .build();
