### ISSUE TITLE
get JSON  before convert in other type

### ISSUE THREAD

**Issue by enieber** [square/retrofit#1148]
Is there any way to get JSON before being converted to the required type?

**Comment by JakeWharton** [comment]
You can use an [OkHttp interceptor][1] which has full access to read/replace the response body. You could also implement a `Converter.Factory` which wraps another (such as one that does JSON) and use it to read/rewrite request and response bodies as well.

 [1]: https://github.com/square/okhttp/wiki/Interceptors

**Comment by enieber** [comment]
thanks....
