### ISSUE TITLE
Custom Annotations in Retrofit 2.0

### ISSUE THREAD

**Issue by MichaelSchmidtt** [square/retrofit#1150]
According to @JakeWharton in issue https://github.com/square/retrofit/issues/1145 it should be possible to use custom annotations

if i use a custom annotation like 

```
import javax.ws.rs.HttpMethod;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

@Target(METHOD)
@Retention(RUNTIME)
@HttpMethod(value = HttpMethod.DELETE)
public @interface DELETE_WITH_BODY {
    String value();
}
```

and use it like this
```
@DELETE_WITH_BODY("/myurl")
    Call<String> deactivateUserPermanently(
            @Header("Authorization") String systemAuthLine,
            @Body MyBodyRequest myBodyRequest
    );
```

I get following stacktrace

```
java.lang.IllegalArgumentException: HTTP method annotation is required (e.g., @GET, @POST, etc.).
    for method MyProxy.deactivateUserPermanently
	at retrofit.Utils.methodError(Utils.java:177)
	at retrofit.Utils.methodError(Utils.java:167)
	at retrofit.RequestFactoryParser.parseMethodAnnotations(RequestFactoryParser.java:135)
	at retrofit.RequestFactoryParser.parse(RequestFactoryParser.java:59)
	at retrofit.MethodHandler.create(MethodHandler.java:30)
	at retrofit.Retrofit.loadMethodHandler(Retrofit.java:151)
	at retrofit.Retrofit$1.invoke(Retrofit.java:132)
	at com.sun.proxy.$Proxy7.deactivateUserPermanently(Unknown Source)
	at xxx.xxx.MyGateway.deactivateUserPermanently(MyGateway.java:354)
```

maybe I have an error, but i think that should work though

Using Retrofit 1.9 and that annotation, I can use a HTTP DELETE with body:
```
package working.with.retrofit.1_9.like.that;

import retrofit.http.RestMethod;

import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

@Target(METHOD)
@Retention(RUNTIME)
@RestMethod(value = "DELETE", hasBody = true)
public @interface DELETE_WITH_BODY {
    String value();
}

```

**Comment by JakeWharton** [comment]
`@HttpMethod` is a JAX-RS annotation, not a Retrofit one. You should be using the [`@HTTP` annotation][1] and directly on the service method. Here's [an example][2]:

```java
interface Example {
  @HTTP(method = "CUSTOM1", path = "/foo")
  Call<ResponseBody> method();
}
```

I'll add the example to the `@HTTP` annotation's Javadoc.

 [1]: http://square.github.io/retrofit/javadoc/index.html?retrofit/http/HTTP.html
 [2]: https://github.com/square/retrofit/blob/07d1f3de5e0eb11fb537464bd14fdbacfc9e55a7/retrofit/src/test/java/retrofit/RequestBuilderTest.java#L52-L64

**Comment by chinmaygit** [comment]
To be precise....
interface Example {
  @HTTP(method = "DELETE", path = "/foo, hasBody = true")
  Call<ResponseBody> method();
}

**Comment by donUA** [comment]
Ensure all imports are retrofit2:
import retrofit2.http.POST;
import retrofit2.Call;
import retrofit2.http.Field;
import retrofit2.http.FormUrlEncoded;

or whatever version you are using
