### ISSUE TITLE
GsonConverterFactory can not handle String Response

### ISSUE THREAD

**Issue by renierdbruyn** [square/retrofit#1151]
I have the following retrofit code:

```Java
Retrofit retrofit = new Retrofit.Builder()
//                .baseUrl("http://10.0.2.2:6543/") // On AVD
                .baseUrl("http://192.168.0.106:6543") // On device
                .addConverterFactory(GsonConverterFactory.create())
                .build();

            EnrollmentRequest = retrofit.create(EnrollmentApiInterface.class);
```

That makes a POST request:

```Java
@Headers({
            "Accept: application/json",
            "Content-Type: application/json"
        })
        @POST("auth/enroll")
        Call<String> RequestEnrollment(@Body EnrollmentRequest EnrollmentDetails);
```

and is used like:

```Java
EnrollmentRequest request = new EnrollmentRequest();
        request.setMsisdn(MsisdnTxt.getText().toString());
        request.setId_number(IdNumberTxt.getText().toString());
        EnrollmentApiClient.EnrollmentApiInterface service = EnrollmentApiClient.getApiClient();
        Log.i(TAG, "REQUEST:   " + request.toJson());
        Call<String> call = service.RequestEnrollment(request);
        call.enqueue(new Callback<String>() {
            @Override
            public void onResponse(Response<String> response) {
                // Create object of SharedPreferences.
                SharedPreferences sharedPref = PreferenceManager.getDefaultSharedPreferences(that);
                //now get Editor
                SharedPreferences.Editor editor = sharedPref.edit();
                //put your value
                editor.putString("IDnumber", IdNumberTxt.getText().toString());
                editor.putString("Msisdn", MsisdnTxt.getText().toString());

                //commits your edits
                editor.commit();
                Log.i(TAG, "onClick-AFTER");
                Intent intent = new Intent(getApplicationContext(), AuthoriseActivity.class);
                startActivity(intent);

            }

            @Override
            public void onFailure(Throwable t) {
                // Always get in here
                Log.i(TAG, "NOTHERE", t);
                Log.d("CallBack", " Throwable is " + t.toString());

                Toast.makeText(EnrollActivity.this, "Request Failed", Toast.LENGTH_LONG).show();
            }
```

The request is sent, but on response I expect a String, but for some odd reason I get the following exception:

```
 com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 2 path $
            at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1573)
            at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1423)
            at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:575)
            at com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
            at com.google.gson.internal.bind.TypeAdapters$13.read(TypeAdapters.java:349)
            at com.google.gson.internal.bind.TypeAdapters$13.read(TypeAdapters.java:346)
            at com.google.gson.TypeAdapter.fromJson(TypeAdapter.java:256)
            at retrofit.GsonConverter.fromBody(GsonConverter.java:42)
            at retrofit.OkHttpCall.parseResponse(OkHttpCall.java:144)
            at retrofit.OkHttpCall.access$000(OkHttpCall.java:25)
            at retrofit.OkHttpCall$1.onResponse(OkHttpCall.java:90)
            at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:168)
            at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
```

I have tested Converting The string to Json, using Gson:

```Java
Gson gson = new GsonBuilder()
                .setDateFormat("yyyy-MM-dd'T'HH:mm:ssZ")
                .create();

            String blah = gson.fromJson("\"600\"", String.class);
            Log.w(TAG, blah);
```

I suspect that this might be a bug in `GsonConverterFactory` causing this, or am I doing something horribly wrong?

**Comment by ayon115** [comment]
You'll need your own Custom Converter Class to get response as String.

**Comment by renierdbruyn** [comment]
I have also tried that:
```Java
public final class ToStringConverter implements Converter<String> {

    @Override
    public String fromBody(ResponseBody body) throws IOException {
        return body.string();
    }

    @Override
    public RequestBody toBody(String value) {
        return RequestBody.create(MediaType.parse("text/plain"), value);
    }
}
```

and then I implemented it like:
```Java
            Retrofit retrofit = new Retrofit.Builder()
                .baseUrl("http://10.0.2.2:6543/") // On AVD
                .addConverter(String.class, new ToStringConverter())
                .addConverterFactory(GsonConverterFactory.create())
                .build();
```

But it still gives me the same error

**Comment by JakeWharton** [comment]
We use a string converter in all the tests so I can assure you it works. However, it looks like you are using some outdated version of Retrofit 2 as the `addConverter` API no longer exists. That version might have no behaved correctly with this case, and I would encourage you to use 'beta2' or the latest SNAPSHOT instead.

Here's a link to the [`ToStringConverterFactory`][1] and [an example of it being used][2].

 [1]: https://github.com/square/retrofit/blob/07d1f3de5e0eb11fb537464bd14fdbacfc9e55a7/retrofit/src/test/java/retrofit/ToStringConverterFactory.java
 [2]: https://github.com/square/retrofit/blob/07d1f3de5e0eb11fb537464bd14fdbacfc9e55a7/retrofit/src/test/java/retrofit/CallTest.java#L59-L71

**Comment by kamilwlf** [comment]
I have:
ava.lang.IllegalArgumentException: Could not locate ResponseBody converter for class java.lang.String. Tried:
.addConverterFactory(ScalarsConverterFactory.create())

compile 'com.squareup.retrofit2:retrofit:2.0.0-beta3'
    compile 'com.squareup.retrofit2:converter-gson:2.0.0-beta3'
    compile 'com.squareup.retrofit2:converter-scalars:2.0.0-beta3'

    compile 'com.squareup.okhttp3:okhttp:3.0.0-RC1'
    compile 'com.squareup.okhttp3:logging-interceptor:3.0.0-RC1'

**Comment by lber19535** [comment]
Hi @kamilwlf , I found the method which you Override of Converter.Factory have already changed, the new methods are fromResponseBody and toRequestBody, so when I changed the method, they all works!

**Comment by cbornet** [comment]
For information, with retrofit 2.0.0-beta3, this issue is worked-around with:
```java
adapterBuilder = new Retrofit .Builder()
               .addConverterFactory(ScalarsConverterFactory.create())
               .addConverterFactory(GsonConverterFactory.create());
```
I still think that GsonConverterFactory should be able to ser/deser primitive types though...

**Comment by JakeWharton** [comment]
It has nothing to do with GsonConverterFactory and all with Gson itself. I
updated Gson to RFC 7159 which supports primitives as top-level types so if
you use version 2.6.1 or newer it will work.

**Comment by avtarsingh1122** [comment]
trsrg

**Comment by cbornet** [comment]
@JakeWharton good to know ! Is it safe to use gson-2.6.1 with the beta4 ?

**Comment by JakeWharton** [comment]
Yes

**Comment by cbornet** [comment]
I tried using gson-2.6.1 with the beta4 and I still get the MalformedJsonException.

**Comment by JakeWharton** [comment]
If the response is an unquoted string (aka not actually valid JSON) then you'll need to set Gson to be lenient. If it is an unquoted string, you really should just be using the scalars converter, though.

**Comment by cbornet** [comment]
Obviously, end of week, I'm tired... So, I will use scalar converter as you suggest since it works like a charm. Thanks for your support.
Note : maybe the multi-converter capability of retrofit2 could be outlined in the doc.

**Comment by iballan** [comment]
I used the latest Gson Version and it works now:

`compile 'com.google.code.gson:gson:2.6.1'`

then set the GsonConverterFactory this way:

```
Retrofit retrofit = new Retrofit.Builder()
                    .baseUrl(Constants.SERVICE_URL)
                    .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                    .addConverterFactory(GsonConverterFactory.create(new Gson()))
                    .client(client)
                    .build();
```
so the solution was in this line 

`.addConverterFactory(GsonConverterFactory.create(new Gson()))`

 I imported `Gson` from the library imported above. Make sure it is not imported from Retrofit or the GsonConvertorFactory.

**Comment by valdesekamdem** [comment]
**@iballan** thank's it salves my issue
But you are obligate to import another library **Gson**. That's growing the size of your, application.
Is there any another  flexible solution ?

**Comment by shivapriya** [comment]
@iballan doesnt work for me
@cbornet have you found a solution?

**Comment by nAkhmedov** [comment]
How to use the latest version of Gson?
![image](https://cloud.githubusercontent.com/assets/8067423/15207036/c1d72258-183c-11e6-875e-4aff089e2148.png)

**Comment by shivapriya** [comment]
i believe for the latest retrofit2, they are no longer supporting gson as
part of their release...
so if you wish to use the latest gson release:
add this to gradle: compile 'com.google.code.gson:gson:2.6.1'

else if you are still using gson as part of retrofit2:
you can use: compile 'com.squareup.retrofit2:converter-gson:2.0.1'

hope it helps

~Shiva

**Comment by cjhandroid** [comment]
I  still get  the MalformedJsonException.

**Comment by iacky** [comment]
@JakeWharton I am confused,when i request like this `public interface API {
        @FormUrlEncoded
        @POST("login.do?os=" + ConstantValue.OS + "&version=" + ConstantValue.VERSION)
        Observable<LoginInfo> login(@Field("cmd") String params);
    }`,the method of my custom Converter stringConverter do not work..

**Comment by waelalameen** [comment]
`ApiInterface apiInterface = ApiClient.getApiClient().create(ApiInterface.class);
                Call<List<Contact>> call = apiInterface.getContacts();

                call.enqueue(new Callback<List<Contact>>() {
                    @Override
                    public void onResponse(Call<List<Contact>> call, Response<List<Contact>> response) {
                        contactList = response.body();
                        adapter = new MyAdapter(MainActivity.this, contactList);
                        recyclerView.setAdapter(adapter);
                    }

                    @Override
                    public void onFailure(Call<List<Contact>> call, Throwable t) {
                        Toast.makeText(MainActivity.this, t.getMessage(), Toast.LENGTH_SHORT).show();
                    }
                });`
I'm trying to fetch information from three fields in the database but i get only the last field, how to solve this ??

**Comment by gleison** [comment]
try this:

`
Gson gson = new GsonBuilder()
        .setLenient()
        .create();
Retrofit retrofit = new Retrofit.Builder()
        .baseUrl(BASE_URL)
        .client(client)
        .addConverterFactory(GsonConverterFactory.create(gson))
        .build();
`

that's worked for me.

**Comment by tianxia--** [comment]
My application now makes the following errors frequently, but not every time. All of the above approaches are used, but there is no guarantee that the error will not occur. The Retrift object is set when it is created
"AddConverterFactory (GsonConverterFactory. Create (new Gson ()))", why there will be empty. Ask for help!!!!

`java.lang.NullPointerException: Attempt to invoke virtual method 'retrofit2.Converter retrofit2.Converter$Factory.stringConverter(java.lang.reflect.Type, java.lang.annotation.Annotation[], retrofit2.Retrofit)' on a null object reference
    at retrofit2.Retrofit.stringConverter(Retrofit.java:364)
    at retrofit2.ServiceMethod$Builder.parseParameterAnnotation(ServiceMethod.java:430)
    at retrofit2.ServiceMethod$Builder.parseParameter(ServiceMethod.java:336)
    at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:204)
    at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:170)
    at retrofit2.Retrofit$1.invoke(Retrofit.java:147)
    at java.lang.reflect.Proxy.invoke(Proxy.java:913)`

**Comment by manvinderr21** [comment]
> try this:
> 
> `Gson gson = new GsonBuilder() .setLenient() .create(); Retrofit retrofit = new Retrofit.Builder() .baseUrl(BASE_URL) .client(client) .addConverterFactory(GsonConverterFactory.create(gson)) .build();`
> 
> that's worked for me.
Thanks @gleison 
Worked for me also.
