### ISSUE TITLE
How to prevent @FormDataEncoded for single value

### ISSUE THREAD

**Issue by maan-smith** [square/retrofit#1155]
Hi,
I have this sample request code,
I just want to prevent @Field("SearchToken") String SearchToken, parameter from encoding how can I do that?

@FormUrlEncoded
@POST(AppWebServices.URL)
void create(@Field("SearchToken") String SearchToken,
                   @Field("SearchTokenDisplay") String SearchTokenDisplay,
                   @Field("UserType") int UserType,
                   Callback<Object> callback);

**Comment by JakeWharton** [comment]
Use `encoded = true` on the `@Field` annotation to inform Retrofit that the value is already encoded appropriately.

**Comment by maan-smith** [comment]
@FormUrlEncoded
@POST(AppWebServices.URL)
void create(@Field("SearchToken") String SearchToken,
@Field("SearchTokenDisplay") String SearchTokenDisplay,
@Field("UserType") int UserType,
Callback callback);

Can you please add on this?
