### ISSUE TITLE
Retrofit Error

### ISSUE THREAD

**Issue by stelian008** [square/retrofit#1157]
Hello, Everybody!

I am using Retrofit engine to make the request of POST/GET.

I have one problem.

In one activity, i have coded to use several of ApiClient object as below:

private ApiClient mApiClient;

mApiClient = new RestAdapter.Builder()
                .setEndpoint("http://192.168.0.120/restapi")
                .build()
                .create(ApiClient.class);

--- First Use --
mApiClient.getClientToken(new Callback<ClientToken>() {
                    @Override
                    public void success(ClientToken clientToken, Response response) {
                           // Do Something
                    }

                    @Override
                    public void failure(RetrofitError error) {
                         // Do Something
                    }
                });

In this case, i checked the api runs successfully, it calls "success" callback.

But, i try to call another method by using mApiClient, and then it cause failure.

mApiClient.createMessage("This is second test", new Callback<ClientToken>() {
                    @Override
                    public void success(ClientToken clientToken, Response response) {
                           // Do Something
                    }

                    @Override
                    public void failure(RetrofitError error) {
                         // Do Something
                   }
                });

In this case, RetrofitError's content is same as "java.io.EOFException", kind is "NETWORK".

I don't know why this error happened.

Help me!

**Comment by JakeWharton** [comment]
This isn't really a great support forum (as evidenced by the fact this is two weeks old). Do you have a stacktrace? Anything subclassing IOException is thrown in the HTTP client so it's unlikely to have anything to do with Retrofit.
