### ISSUE TITLE
Could not find method com.squareup.wire.Wire.<init>, referenced from method retrofit.WireConverterFactory.create

### ISSUE THREAD

**Issue by Gilb007** [square/retrofit#1158]
Hi everyone!

I caught problem.

I use  in gradle:
    compile 'com.squareup.retrofit:retrofit:2.0.0-beta1'
    compile 'com.squareup.wire:wire-runtime:2.0.0-BETA7'
    compile 'com.squareup.okhttp:okhttp:2.5.0'
    compile 'com.squareup.retrofit:adapter-rxjava:2.0.0-beta1'
    compile 'com.squareup.retrofit:converter-gson:2.0.0-beta1'
    compile 'com.squareup.retrofit:converter-wire:2.0.0-beta2'
    compile 'io.reactivex:rxandroid:1.0.1'

Make things in code:
1)
public interface RetrofitService {
    @Headers({"Cookie: bankId=*****************", "Content-Type: application/x-protobuf"})
    @POST("")
    Observable<BaseModelResponseProtobufDTO> baseRequest(@Body BaseModelRequestProtobufDTO baseModelRequestProtobufDTO);
}
2)
Retrofit retrofit = new Retrofit.Builder()
            .baseUrl(Constants.apiURL)
            .addConverterFactory(WireConverterFactory.create())
            .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
            .build();

When method .addConverterFactory try access Wire(), it doesn't see Wire()!
Bacause Wire() in wire-runtime-2.0.0-BETA7 has private constructor.

Is it correct?

![image](https://cloud.githubusercontent.com/assets/7489129/10246262/4e270748-6918-11e5-9aaa-08d4c76266a4.png)

**Comment by JakeWharton** [comment]
The current Wire converter only works with Wire 1.x. See #1120 for tracking the update to version 2. It shouldn't be too hard to write your own in the mean time. Look up the `ProtoAdapter` in the factory method and then use its methods for reading and writing the value.

**Comment by aaakinshin** [comment]
I've worked on weekend, but it's doesn't work. 
I will waiting for update.
tnx

**Comment by Gilb007** [comment]
I've worked on weekend, but it's doesn't work. 
I will waiting for update.
tnx

**Comment by gauravdott** [comment]
Any update on this?

I am trying to use wire 2.0.2 with retrofit 2.0.0-beta2 and wire-converter 2.0.0 beta2 to extend enum values options.

Any help is appreciated!

**Comment by Gilb007** [comment]
I've used compile 'com.squareup.wire:wire-runtime:1.8.0' and compile 'com.squareup.retrofit:converter-wire:2.0.0-beta2' and it works perfect. But I'm not use enum. Be more specific?
