### ISSUE TITLE
Send array in POST request

### ISSUE THREAD

**Issue by Ne1c** [square/retrofit#1161]
How to send array at POST request, example sending body(param->value):
`{"chat":["560e8befef36415027432170", "560e8bfabd0a2d2427189eab"]}`

I tried make with this method, but not successful:

`
@FormUrlEncoded
@POST("/v1/rooms/{roomId}")

void readMessages(@Path("roomId") String roomId, @Field("chat") String[] ids, Callback<Response> callback);

How I make it on Retrofit 1.9.0?
`

**Comment by jinqibu** [comment]
how to send a array data,try 
>@Query("chat[]") String[] ids

**Comment by JakeWharton** [comment]
The format you define is JSON, not form encoding. For this you would create an object with that format like:
```java
class Foo {
  List<String> chat;
}
```
paired with the `@Body` annotation on a single parameter.

**Comment by BambangHeriSetiawan** [comment]
thanks this is work for me
