### ISSUE TITLE
Solution to #1004 still producing same error

### ISSUE THREAD

**Issue by gudatcomputers** [square/retrofit#1167]
Hi!

We are getting "Failed to extract String 'value' from @BULK_DELETE annotation." We defined the following custom annotation:

@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
@RestMethod(value = "DELETE", hasBody = true)
@interface BULK_DELETE {
    String value();
}

and used it here:

    public interface DeleteMedicineApiInterface {
        @BULK_DELETE("/api/medicines")
        Response hitEndpoint(
            @Body BulkDeleteMedicinesApiRequest bulkDeleteMedicinesApiRequest
        );
    }

any idea what could be wrong? We understand that this is addressed in #1004 but we are applying the recommended solution from there and still getting the same error.

**Comment by JakeWharton** [comment]
Are you using proguard to obfuscate?

**Comment by gudatcomputers** [comment]
Hi!

We have proguard here in our app build.gradle:

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

this is to get over the DEX limit. Does Proguard sometimes cause a problem with this?

**Comment by JakeWharton** [comment]
Yep. It will rename the `value` method on the annotation which prevents the library from looking it up. Add an entry to your ProGuard configuration to ensure it's name it kept and not obfuscated.

**Comment by shahwaiz90** [comment]
A bit late to the party, can you show how to add its entry in the proguard of BULK_DELETE?
