### ISSUE TITLE
SocketTimeoutException on Android 5

### ISSUE THREAD

**Issue by ber4444** [square/retrofit#1177]
With the exact same code I'm getting good results on Android 6 (api 23) but SocketTimeoutException on Android 5.1 (api 22). My server is NOT down!
This is with    compile 'com.squareup.retrofit:retrofit:2.0.0-beta2'
using:
Call<RegistrationResponse> call = service.register(registrationRequestBundle);
      call.enqueue(new Callback<RegistrationResponse>() {
            // ...
      });

**Comment by JakeWharton** [comment]
There's not enough information here to be actionable. But even if there were, Retrofit is not going to be the cause of something like this as it plays no part in the actual communication with the server. Socket timeouts would be set by the HTTP client which in this case is OkHttp.

**Comment by ber4444** [comment]
ok, it was my vpn, sorry for the false report
