### ISSUE TITLE
Make @Part supporting filename property

### ISSUE THREAD

**Issue by jeaking** [square/retrofit#1179]
I am using Retrofit 2 in my application, it is great and very easy to learn. But I still met some issues when I tried to uploading files using Retrofit 2, the biggest one is that I didn't know how to specify the filename of uploading file. I finally got a solution by googling, it looks like this:

    @POST("client/resources/upload/image")
    @Multipart
    Call<ResponseBody> upload(@Part("myFile\"; filename=\"myFile.png") RequestBody myFile); 

It work for me, but in my opinion this looks more like a work around, I think there should be another solution which is more elegant and straightforward.

I suggest to add a new property named "filename" to @Part as following:

@Documented
@Target(PARAMETER)
@Retention(RUNTIME)
public @interface Part {
  String value();
  String filename() default "";
  /** The {@code Content-Transfer-Encoding} of this part. */
  String encoding() default "binary";
}

Is this acceptable？Or any comments on this？

Thanks！

**Comment by JakeWharton** [comment]
This prevents the filename from being set dynamically which will make the feature not useful to most users. Please contribute discussion on #1140.
