### ISSUE TITLE
Question/Suggestion if possible for having two types of objects that retrofit could parse

### ISSUE THREAD

**Issue by rubinbasha** [square/retrofit#1180]
I have worked with some webservices that deliver two types of JSON in case of response code 200. I have also seen many cases where this is the approach from the people developing the WS. 
There are cases when I receive a response like this : {success: 1, (the data like ID , name, etc)} and there are some cases when i receive a response like this {success: 0, error:smth, redirect: smthelse, etc}.

What I would ask or suggest would be if it is possible to supply alternate result objects in case of response 200(not just non 200). I would ponder if it is possible to do it like you have done with addConverterFactory, meaning that we could supply extra types and than we could work with instanceof operator. Right now in my case I will just get the response as a JsonObject and than use Gson manually to convert it to a concrete object that i need , or the other one, based on the contents of the Json. In some cases where I can influence the result json I can also ask to get always a Json which has both object types but only one is non-null so I can parse the response directly with retrofit into a wrapper object and than substract the non null field from that wrapper.

**Comment by JakeWharton** [comment]
This is a type modeling problem with your serialization format and library. There's no way for Retrofit to do anything here in both a type and serialization format-agnostic way.

There's plenty of tricks to getting this to work. Your success model objects can extend a base class which offers the `success` boolean available on every type. Or if you're using Gson or Jackson you can create a wrapper type `Foo<ActualType>` and register a special deserializer (in Gson they're called TypeAdapters) which encapsulates both success and failure into a single type.

I've run across a few StackOverflow answers related to this topic if you want to go searching. You can also post to Gson's mailing list (if you're using Gson. presumably Jackson has a mailing list as well) asking how to handle this case. They'll be able to offer more specifics on how to actually create the necessary machinery in the serialization library such that this is completely transparent to Retrofit.
