### ISSUE TITLE
PROTOCOL_ERROR on Android >KitKat

### ISSUE THREAD

**Issue by hamen** [square/retrofit#1181]
Hi all
I'm suddenly having a weird error when I try to fetch data from

> https://public-api.wordpress.com/rest/v1/freshly-pressed?number=30

using retrofit + okhttp. I found a couple of related issues:
https://github.com/square/okhttp/issues/1844
https://github.com/square/okhttp/issues/1897#issuecomment-146445729
Any suggestion?
Thank you

**Comment by JakeWharton** [comment]
Retrofit has nothing to do with problems in the HTTP client like this. The interaction with the HTTP client is way too high level to have any effect here. You already linked the relevant issues which are in the right place, the HTTP client.

**Comment by hamen** [comment]
Thank you, Jake. I appreciate your feedback. I switched the project to **retrofit** 2, tuning a few things here and there. It's working fine now. I'll post my current configuration in the proper thread.
