### ISSUE TITLE
Android GET not request with query firstly

### ISSUE THREAD

**Issue by AndwareSsj** [square/retrofit#1185]
service like this:
@Get("http://182.92.155.55:3005/api/v1/user/sms")
Call<Boolean> getSms ( @Query ("user_phone") String phone );
request like this:
Call< Boolean > smsCall = userService.getSms ( phone );
smsCall.enqueue (//callback);

first open(init) activity not request to web server.

**Comment by JakeWharton** [comment]
There is far too little information here to diagnose or reproduce any problem you are experiencing. If you can phrase your problem in the form of a failing test case or provide more details in the form of the stacktrace of the problem and more of the code you are using then perhaps we can figure it out. But without that, there's not really anything we can help with.
