### ISSUE TITLE
Retrofit - removing escaped characters from json acquired from C#

### ISSUE THREAD

**Issue by paragones** [square/retrofit#1186]
I have this json string(?) that I got from calling a C# Api

    "{\"PublicApiToken\":\"M6RVJcCyiVODapF0wOR/Pg==\",\"ErrorList\":[]}"

This is returning an error of :

    retrofit.RetrofitError: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 2 path $

Is there any this can be converted/cleaned? I've tried researching and the closest I got was this link : http://stackoverflow.com/questions/26290267/retrofit-removing-some-invalid-characters-from-response-body-before-parsing-it

but unfortunately it still doesn't work on my problem at all. 

Have you guys solved this problem? 

My Method Call :

    @Headers("Content-Type: application/json")
    @POST("/authorize/AcquirePublicApiToken")
    void attemptLoginToMCCServer(@Header("Content-Type") String contentType, @Header("Authorization") String authorization, @Body Authorization authorizationKey, Callback<SuccessLoginCallback> successLoginCallback);

My Pojo :

    public class Authorization {
    
        private String consumerName;
        private String username;
        private String consumerKey;
        private String password;
        private String nonce;
        private String timeStamp;
    
        public String getConsumerName() {
            return consumerName;
        }
    
        public void setConsumerName(String consumerName) {
            this.consumerName = consumerName;
        }
    
        public String getUsername() {
            return username;
        }
    
        public void setUsername(String username) {
            this.username = username;
        }
    
        public String getConsumerKey() {
            return consumerKey;
        }
    
        public void setConsumerKey(String consumerKey) {
            this.consumerKey = consumerKey;
        }
    
        public String getPassword() {
            return password;
        }
    
        public void setPassword(String password) {
            this.password = password;
        }
    
        public String getNonce() {
            return nonce;
        }
    
        public void setNonce(String nonce) {
            this.nonce = nonce;
        }
    
        public String getTimeStamp() {
            return timeStamp;
        }
    
        public void setTimeStamp(String timeStamp) {
            this.timeStamp = timeStamp;
        }
    
        @Override
        public String toString() {
            StringBuffer sb = new StringBuffer();
            sb.append("amx ");
            sb.append(getConsumerName());
            sb.append("-");
            sb.append(getUsername());
            sb.append(":");
            sb.append(getConsumerKey());
            sb.append("-");
            sb.append(getPassword());
            sb.append(":");
            sb.append(getNonce());
            sb.append(":");
            sb.append(getTimeStamp());
    
    
    
            return sb.toString();
        }
    }

**Comment by JakeWharton** [comment]
This was also [posted to StackOverflow][1], presumably by you, which is the correct place for this type of question. It's neither a bug report nor a feature request, but just a usage problem with a particular behavior of a remote API. SO is also so much better for archiving, searching, and incentivizing answers to these problems. Going to close this issue on it, and anyone interested in responding should do so on SO.

 [1]: http://stackoverflow.com/q/33043211/132047
