### ISSUE TITLE
How could I add multi part with same name

### ISSUE THREAD

**Issue by tuandigital** [square/retrofit#1190]
In our project, I need to upload multiple files in multipart form data, I mark all files with the name is "file". It's much more convenience for Backend to get file list. I tried to create Multipart RequestBody from MultipartBuilder but the server only recognises single file. Could you please let me know how to resolve it? Thanks

**Comment by JakeWharton** [comment]
You can re-use the name in the `@Part` annotation. Multipart lets you put whatever you want (including files) in each part. If the server only recognizes only one file then you likely are not creating the request in a way that it recognizes. You might have to append `[]` to each part name for it to view it as multiple files, or something. It really depends on the server.

For support of iterable part values all with the same name you can subscribe to https://github.com/square/retrofit/issues/685.

I'm fairly certain this is just an interaction problem between you and your server. If it's truly a Retrofit problem, the best way to showcase that is with some kind of failing test case or sample project showing the erroneous behavior.
