### ISSUE TITLE
Jackson converter breaks polymorphism

### ISSUE THREAD

**Issue by jianghaolu** [square/retrofit#1192]
in https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit/RequestFactoryParser.java#L299: 
```java
converter = retrofit.requestConverter(methodParameterType, methodParameterAnnotations);
```
The method parameter type was directly passed into the creation of the `ObjectWriter` in Jackson converter.

In the case of
```java
public interface MyService {
    @PUT("/url")
    Call<ResponseBody> getMyClass(@Body BaseClass obj);
}
```
An object of `SubClass` will be written as `BaseClass` by the `ObjectWriter` with `_rootType=BaseClass`.

**Comment by swankjesse** [comment]
As a rule, all serialization breaks polymorphism. You might be able to work around this by configuring the `ObjectMapper` that you pass to `JacksonConverterFactory.create()`. Retrofit isn’t really involved here, it’s just asking Jackson to do its thing.

**Comment by jianghaolu** [comment]
Thanks for the reply @swankjesse.

I did create my own `ObjectMapper` and pass it in. `Retrofit.converterFactories` contains a `JacksonConverterFactory` that wraps my `ObjectMapper`.

Instead, the error happens at `Converter.toReuqestBody(type, annotations)` which for Jackson converter it's calling creating an `ObjectWriter` from `mapper.writerWithType()`. This is redundant and wrong - because Jackson will trust you are providing the type instead of reflecting and looking at the [annotations](http://wiki.fasterxml.com/JacksonPolymorphicDeserialization) itself.

By changing that to `mapper.wrtier()` will solve the issue - Jackson will then have to decide the type on its own, which actually works in this case.

It's a one-line fix - I'll send a pull request.

**Comment by JakeWharton** [comment]
@jianghaolu that is not the desired behavior. The whole point is caching the work that is done to create the mapper for a type.

**Comment by jianghaolu** [comment]
> Retrofit isn’t really involved here, it’s just asking Jackson to do its thing.

"Caching the work to create the mapper"? I think I'm providing the mapper myself.

**Comment by JakeWharton** [comment]
The writer. Whatever jackson calls the thing that does the work and is expensive to create. In Gson and Moshi it's called an adapter.

**Comment by jianghaolu** [comment]
Can you point me to where it's cached? I'm only seeing it being passed into `JacksonRequestBodyConverter` but no other instantiations.

Also, I mean, polymorphism is broken here. If you have no plans to fix this, at least a workaround?

**Comment by JakeWharton** [comment]
The converter is created once when the method is first parsed and re-used for subsequent calls. This avoids looking up the writer for the same type over and over every time you call the method.

> at least a workaround?

Write your own Converter.Factory which creates Converter instances that doesn't cache a configured writer.

**Comment by jianghaolu** [comment]
Okay, I see what you are doing here. Surprised that this would cause a performance surge that let you made this decision.

Anyway, thanks for following up. Will work around this for now.
