### ISSUE TITLE
Retrofit Upload data from form-input

### ISSUE THREAD

**Issue by griajobag** [square/retrofit#1193]
I being learning about android (Retrofit). please suggest me a link that have a tutorials about retrofit (send data from form like register form).

**Comment by JakeWharton** [comment]
https://futurestud.io/blog/retrofit-how-to-upload-files/ is a good resource for multipart form data. If you want just form url-encoded then there's a myriad of examples on stackoverflow. The `@Multipart` and `@FormUrlEncoded` annotations also contain simple examples.

**Comment by griajobag** [comment]
thank you! i have created as same as your example but in difference model. my case : the apps  will used for register account. so it need button register activity and register response.
