### ISSUE TITLE
HEAD method does not like ResponseBody return type

### ISSUE THREAD

**Issue by jianghaolu** [square/retrofit#1195]
"HEAD method must use Void as response type" thrown even if return type is ResponseBody.
```java
interface MyService {
        @HEAD("/url")
        Call<ResponseBody> headOp();
}
```
I would want to know the metadata in the response for a HEAD method.

**Comment by JakeWharton** [comment]
HEAD requests have no response body so that type makes no sense for it. Both `execute()` and `enqueue()` give you a `Request` object with the response code, message, and the headers for your inspection, which is the entirety of what the HTTP RFC allows in a HEAD response.

**Comment by itsPR** [comment]
When I am using  @HEAD("/url"),  the headers in response ( response.headers(); ) are different from actual headers. is response.headers(); is right way to get hearerd when using @HEAD method. ?
