### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by arafeh94** [square/retrofit#1196]
Guys any help I spent 3 hour searching for a way to show the response body in the new version because I got a some parse exception

and guys I know how hard you work to help us but I think this update is a fail no one remove old  ways and methods, just mark it as deprecate, don't think anyone will be happy to change all his projects  structure to use this updated

**Comment by felipecsl** [comment]
this might help you: https://gist.github.com/felipecsl/fd03e771e3058f2b2bd6

**Comment by artem-zinnatullin** [comment]
1. Nobody forces you to upgrade :) 1.9 still works, 2.0 is in development.
2. Jake had recently added Logging Interceptor to the OkHttp, take a look https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor

**Comment by arafeh94** [comment]
unluckily there is lots of new important functionality i want to use it 
for your solution is appear that Platform.get().log(message); do not exist at line 100 replace by logW
and there is not logging also this is my code



OkHttpClient client = new OkHttpClient();
        HttpLoggingInterceptor logging = new HttpLoggingInterceptor();
        logging.setLevel(Level.BASIC);
        client.interceptors().add(logging);
        
        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl("http://localhost/projectlu/")
                .client(client)
                .build();
        
        Server server = retrofit.create(Server.class);
        
        server.getUser("3", "q@q", "q").enqueue(new Callback<List<User>>() { //this line give exception

            @Override
            public void onResponse(retrofit.Response<List<User>> rspns, Retrofit rtrft) {
                
                System.out.println(rspns.toString());
            }

            @Override
            public void onFailure(Throwable thrwbl) {
                System.out.println("fail");
            }
        });

note: I use java connected to localhost on my pc first to create my server than use it in android

**Comment by artem-zinnatullin** [comment]
StackOverflow is ~~probably~~ a better place for that, but please post exception stacktrace.

Looks like you've not set any converter for the responses, use `addConverterFactory` on the `Retrofit.Builder`, here is the example https://github.com/square/retrofit/blob/master/samples/src/main/java/com/example/retrofit/SimpleService.java, Gson is not a default converter any more.

**Comment by artem-zinnatullin** [comment]
@arafeh94, I'd suggest you to watch Jake's talk about Retrofit 2 for a better understanding of its new architecture! https://www.youtube.com/watch?v=KIAoQbAu3eA

**Comment by JakeWharton** [comment]
Use the linked OkHttp logging interceptor for Retrofit 1.x-like format or add your own interceptor that logs in whatever format you want following its lead. Since it's not released you'll have to use 2.6.0-SNAPSHOT.

And as noted, you're missing a converter.

Read inthecheesefactory.com/blog/retrofit-2.0 and read/watch https://realm.io/news/droidcon-jake-wharton-simple-http-retrofit-2/ for now until we get more documentation. Post usage problems to StackOverflow with the 'retrofit' tag (we all get emails for these) and create GitHub issues for reproducible bugs or feature requests that don't already have issues.

Native logging is covered by #378.
