### ISSUE TITLE
Using @QueryMap(encoded = true) will still encode values

### ISSUE THREAD

**Issue by raniejade** [square/retrofit#1199]
I'm using `QueryMap` like this:

```java
interface ProjectApi {
    @GET("projects/")
    Observable<Project> getProjects(@QueryMap(encoded = true) Map<String, String> params);
}
```

```java
final ProjectApi api = ...;
final Map<String, String> params = new HashMap<>();

params.put("owner", 1234);
params.put("statuses[]", "ACCEPTED&statuses[]=IN_PROGRESS");

api.getProjects(params)
```

I assume that when setting `encoded` to true, values will not be encoded anymore. However this is not the case, `ACCEPTED&statuses[]=IN_PROGRESS` gets encoded to `ACCEPTED%26statuses%5B%5D%3DIN_PROGRESS`

I'm using 2.0.0-beta2.

**Comment by JakeWharton** [comment]
For what it's worth, we're just calling OkHttp's [`addEncodedQueryParam`][1] method and specifying `true` as the last argument. So the behavior you are seeing is from OkHttp.

What you're really looking for is iterable values for these annotations so that you can just pass a list of values with a single name declaration instead of the map hack...

 [1]: http://square.github.io/okhttp/javadoc/com/squareup/okhttp/HttpUrl.Builder.html#addEncodedQueryParameter-java.lang.String-java.lang.String-

**Comment by JakeWharton** [comment]
Iterable map-based params is covered under #685.

**Comment by robertoestivill** [comment]
I'm experiencing the same incorrect behaviour with `@Query` annotated parameters

Interface declaration
@Query(value="start_date", encoded=true) String start,
@Query(value="end_date", encoded=true) String end,

In Java, already encoded
String start_date = "2015-11-19+11%3A32%3A22.824-0300"
String end_date = "2015-11-23+11%3A32%3A22.824-0300"

In the wire, encoded twice
start_date=2015-11-19%2B11%253A32%253A22.824-0300
end_date=2015-11-23%2B11%253A32%253A22.824-0300

Retrofit 2.0.0-beta2
OkHttp 2.6.0

Can the root cause be the same?

**Comment by edu11** [comment]
Sorry @JakeWharton I'm not sure if it's related but I'm also having the same behaviour with @Field annotated parameters.

I need to provide a token so I'm using **@Field**(value ="userData" , encoded = true) for declaring the interface
The actual token is something like 
{"response_status":"JSONOBJECT","userID":"36569","surname":"e,"lastname":"d","sessionID":"xxxxxxxx"}

but using logging-interceptor library I could see that OkHttp uses﹕ userData=%7Bresponse_status%3DJSONOBJECT%2C%20userID%3D36569%2C%20surname%3De%2C%20lastname%3Dd%2C%20sessionID%3Dxxxxxxxx%7D

Any idea how to solve it? I'm also using Retrofit 2.0.0-beta2

**Comment by ownwell** [comment]
me too
```Java
@GET(Constants.LIVE_CHAT_ROOM_INFO)
    Observable<RoomInfo> requestChatRoomInfo(@QueryMap(encoded = true) Map data);
```
but result is:
```java
http://data.chat.126.net/route_room?avatar=http://imgm.ph.126.net/ObtaShfyoAJr160qkBnlFw%3D%3D/6631275573400909981.png&userid=ZhQic0pQy41ku3mzYK9Iiw%3D%3D&nickname=cyning&topicid=75053
```

**Comment by ownwell** [comment]
the issule is not Ok!

**Comment by sergii-frost** [comment]
Hi, I am facing issue with encoding as well: 
I need to send redirect_url parameter and is it not encoded when I pass it as parameter to the interface method: 

```
    @POST("token/?grant_type=authorization_code")
    Call<AccessToken> getAccessTokenWithCode(
            @Query("code") String code,
            @Query("client_id") String clientId,
            @Query("client_secret") String clientSecret,
            @Query("redirect_uri") String redirectUri
    );
```

In actual request url `redirect_uri` value is not encoded:  
`https://.../token?grant_type=authorization_code&code=myCode&redirect_uri=https://my_redirect_url/token`

While I am expecting it to be encoded by Retrofit/OkHttp.

I have tried setting `encoded` value to `false` (which is default value) and still it does not help: 
`@Query(value = "redirect_uri", encoded = false) String redirectUri`

**Comment by evgenizero** [comment]
Is this resolved? I am having the same problem here.

**Comment by JoaoManaroulas** [comment]
Same problem;

**Comment by JoaoManaroulas** [comment]
@JakeWharton anything that could do the trick here?

**Comment by swankjesse** [comment]
@sergii-frost which character do you expect to be encoded?

@evgenizero, @JoaoManaroulas I suspect this is a problem with OkHttp’s HttpUrl. 

Could you each please provide an executable test case like this one that demonstrates the differences between your expectations and our behavior?

```
  @Test public void composeQueryWithEncodedComponents() throws Exception {
    HttpUrl base = HttpUrl.parse("http://host/");
    HttpUrl url = base.newBuilder().addEncodedQueryParameter("a+=& b", "c+=& d").build();
    assertEquals("http://host/?a+%3D%26%20b=c+%3D%26%20d", url.toString());
    assertEquals("c =& d", url.queryParameter("a =& b"));
  }
```

**Comment by sergii-frost** [comment]
@swankjesse I am expecting "://" symbols to be encoded in the url. 

I was able to that working as expected when using `@FormUrlEncoded` and `@Field` instead of `@Query` - in this case all the fields work as expected.

**Comment by digitalbuddha** [comment]
hi @swankjesse I am having same problem when encoding an '='  .  The field is a token that has an equal sign at the end. I am trying to send it over as 
`@Query(value = "authSignature",encoded = true) String authSignature`

I am using retrofit 2.0.0-beta3. What I ended up needing to do is something like this in interceptor:
`request.url(originalRequest.url().toString().replace("%3D","="));`

**Comment by Alisunov** [comment]
Hi all! I've looked into okhttp source and found the problem.
`addEncodedQueryParameter()` **does encode** keys and values of the url, but **does not re-encode** "%" symbol.

So, one of the solutions is to use `@Query("fieldName") List<String> values`

**Comment by Tamicer** [comment]
@JakeWharton  I can't find  ：OkHttp's addEncodedQueryParam

**Comment by YaroslavHavrylovych** [comment]
HI all. Had the same problem and I've been searching for a fast solution. For me it was to use [dynamic urls](https://futurestud.io/tutorials/retrofit-2-how-to-use-dynamic-urls-for-requests). I have manually converted [values in a Map to get params](http://stackoverflow.com/questions/2809877/how-to-convert-map-to-url-query-string), checked that they are not encoded and that's it.

**Comment by rafaelanastacioalves** [comment]
Just to be sure,
we could assure that it could be a problem to Firebase REST API too, is that right? Specially to those queries that need values between double quotes.

**Comment by darekdeo** [comment]
I think writing custom interceptor is one way to solve this issue, I think it is not pefect but it works for now. Add custom interceptor to OkHttp with intercept method like below:
`@Override
    Response intercept(Interceptor.Chain chain) throws IOException {
        Request request = chain.request()
        def string = request.url().toString()
        string = string.replace("%26", "&")
        string = string.replace("%3D", "=")

        Request newRequest = new Request.Builder()
                .url(string)
                .build()

        return chain.proceed(newRequest)
    }`
Above code is just simple example, it is lacking headers, etc.

**Comment by NLUZYA15** [comment]
really works)

**Comment by franquicidad** [comment]
fun getClient(codeForActionOrComedy:Int): MovieDbInterfaceToGetMovies {

        val requestToApiInterceptor=Interceptor { chain ->

            val url =chain.request()
                .url()
                .newBuilder()
                .addQueryParameter("api_key",ALONE_API)
                    .addQueryParameter("with_genres","$codeForActionOrComedy")
                .build()

            val request =chain.request()
                .newBuilder()
                .url(url.toString().replace("%3D","="))
                .build()
            return@Interceptor chain.proceed(request)
        }
        val okHttpClient= OkHttpClient.Builder()
            .addInterceptor(requestToApiInterceptor)
            .connectTimeout(60, TimeUnit.SECONDS)
            .build()

        val httpUrl = Retrofit.Builder()
            .client(okHttpClient)
            .baseUrl(BASE_URL)
            .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
            .addConverterFactory(GsonConverterFactory.create())
            .build()
            .create(MovieDbInterfaceToGetMovies::class.java)

        return httpUrl

**Comment by franquicidad** [comment]
```
fun getClient(codeForActionOrComedy:Int): MovieDbInterfaceToGetMovies {

        val requestToApiInterceptor=Interceptor { chain ->

            val url =chain.request()
                .url()
                .newBuilder()
                .addQueryParameter("api_key",ALONE_API)
                    .addQueryParameter("with_genres","$codeForActionOrComedy")
                .build()

            val request =chain.request()
                .newBuilder()
                .url(url.toString().replace("%3D","="))
                .build()
            return@Interceptor chain.proceed(request)
        }
        val okHttpClient= OkHttpClient.Builder()
            .addInterceptor(requestToApiInterceptor)
            .connectTimeout(60, TimeUnit.SECONDS)
            .build()

        val httpUrl = Retrofit.Builder()
            .client(okHttpClient)
            .baseUrl(BASE_URL)
            .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
            .addConverterFactory(GsonConverterFactory.create())
            .build()
            .create(MovieDbInterfaceToGetMovies::class.java)

        return httpUrl
```

**Comment by bludnis** [comment]
API:
` fun get(@QueryName(encoded=true) vararg options: String): Call<Page<Project>>`
Calling like so:
`projectApi.get("sort=description,asc", "sort=title,desc")`
Request looks like so:
api/v1/projects?sort%3Ddescription,asc&sort%3Dtitle,desc 

I Am expecting :
api/v1/projects?sort=description,asc&sort=title,desc 

Am I doing something wrong or (encoded=true) is not effecting "=" ?

**Comment by mohammadkashifkhan** [comment]
Same issue, tried with custom interceptor, tried individual @Query params, tried @QueryMap, tried (encoded=true/false). Still no luck.
Retrofit version = 2.9.0

Anyone knows how to fix this?

**Comment by knobk3** [comment]
Solved this problem using code snipped from https://github.com/square/retrofit/issues/1324

```
class ProxyRetrofitQueryMap(m: Map<String?, List<String?>>) : HashMap<String, Any>(m) {
    override val entries: MutableSet<MutableMap.MutableEntry<String, Any>>
        get() {
            val originSet: Set<Map.Entry<String?, Any?>> = super.entries
            val newSet: MutableSet<MutableMap.MutableEntry<String, Any>> = HashSet()
            for ((key, entryValue) in originSet) {
                val entryKey = key ?: throw IllegalArgumentException("Query map contained null key.")
                // Skip null values
                requireNotNull(entryValue) { "Query map contained null value for key '$entryKey'." }
                if (entryValue is List<*>) {
                    for (arrayValue in entryValue) {
                        if (arrayValue != null) { // Skip null values
                            val newEntry: MutableMap.MutableEntry<String, Any> =
                                SimpleEntry(entryKey, arrayValue)
                            newSet.add(newEntry)
                        }
                    }
                } else {
                    val newEntry: MutableMap.MutableEntry<String, Any> = SimpleEntry(entryKey, entryValue)
                    newSet.add(newEntry)
                }
            }
            return newSet
        }
}
```

**Comment by mohammadkashifkhan** [comment]
Thanks for the update. Still need some more info. How are you using the aforementioned class when expecting a Map with values given as **List<String?>>**. Can you please show how you are using the above class?

**Comment by Faltenreich** [comment]
We are experiencing the same issue with `@QueryName` using Retrofit 3.0.0. 
The query string is encoding no matter what we set for `encoded`.

```
@GET(value = "/api")
suspend fun search(
    @QueryName(encoded = true) query: String,
)

// results in "/api?query%3Dparam"
search("query=param")
```

**Comment by JakeWharton** [comment]
Working as intended, as that is otherwise an invalid name. Please also see above about this behavior being from OkHttp.

**Comment by Faltenreich** [comment]
Sounds like we are using `@QueryName` for something it is not intended for.

Could you point us to the direction of how to append a whole query string to a URL?
The query string comes from an external source, contains multiple query parameters including dividers (ampersands), and should simply be appended to a static URL.

We have tried `@Path`
```
@GET(value = "/api?{query}")
suspend fun search(
    @Path("query") query: String,
)
``` 
which results in an IllegalArgumentException: `URL query string "{query}" must not have replace block. For dynamic query parameters use @Query.`

We have also tried `@Query`
```
@GET(value = "/api")
suspend fun search(
    @Query("") query: String,
)
``` 
which results in a (understandably) scrambled URL: `/api?=<param>`.
 
Our current solution uses `@Url` where we put together the whole URL including host and path
```
@GET
suspend fun search(
    @Url url: String, // passing "<host>/api?<param>"
)
```
but there might be a leaner way to do this.

Sorry for hijacking this issue!

**Comment by JakeWharton** [comment]
There is no mechanism to do exactly what you describe. The URL annotation seems the best approach. You don't need to specify the host, a relative URL should work fine (like an `<a href=…>`). You also could drop down to using OkHttp directly.
