### ISSUE TITLE
Retrofit 2 + Groovy + Android =  java.lang.StackOverflowError 

### ISSUE THREAD

**Issue by jhavatar** [square/retrofit#1202]
Hi
Compilation of my Andorid app written in Groovy using Retrofit 2 (2.0.0-beta2) fails with error "java.lang.StackOverflowError (no error message)".  It compiles and works fine with Retrofit 1 (1.9).

Error in compiling log: 

17:17:44.950 [QUIET] [system.out] 17:17:44.950 [DEBUG] [org.gradle.process.internal.child.ActionExecutionWorker] Starting Gradle Compiler Daemon 1.
17:17:45.100 [QUIET] [system.out] 17:17:45.100 [INFO] [org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonServer] Executing org.gradle.api.internal.tasks.compile.ApiGroovyCompiler@6ff3cb0e in compiler daemon.
17:17:54.729 [QUIET] [system.out] 17:17:54.729 [INFO] [org.gradle.api.internal.tasks.compile.JdkJavaCompiler] Compiling with JDK Java compiler API.
17:18:08.646 [QUIET] [system.out] 17:18:08.646 [INFO] [org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonServer] Exception executing org.gradle.api.internal.tasks.compile.ApiGroovyCompiler@6ff3cb0e in compiler daemon: java.lang.StackOverflowError.
17:18:08.764 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':app:compileDevDebugGroovyWithGroovyc'
17:18:08.764 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :app:compileDevDebugGroovyWithGroovyc FAILED
17:18:08.766 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :app:compileDevDebugGroovyWithGroovyc (Thread[Task worker Thread 3,5,main]) completed. Took 24.66 secs.
17:18:08.766 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Daemon worker,5,main]] finished, busy: 3.524 secs, idle: 28.186 secs
17:18:08.766 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Task worker Thread 2,5,main]] finished, busy: 0.868 secs, idle: 30.843 secs
17:18:08.766 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Task worker,5,main]] finished, busy: 2.506 secs, idle: 29.205 secs
17:18:08.766 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Task worker Thread 3,5,main]] finished, busy: 25.246 secs, idle: 6.463 secs
17:18:08.777 [ERROR] [org.gradle.BuildExceptionReporter] 
17:18:08.778 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
17:18:08.779 [ERROR] [org.gradle.BuildExceptionReporter] 
17:18:08.779 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
17:18:08.780 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':app:compileDevDebugGroovyWithGroovyc'.
17:18:08.780 [ERROR] [org.gradle.BuildExceptionReporter] > java.lang.StackOverflowError (no error message)

**Comment by JakeWharton** [comment]
Please provide a minimal sample that demonstrates this is caused by Retrofit.

**Comment by jhavatar** [comment]
Yup, not retrofit directly -- reason was groovy does not like the default version of rxjava that comes with rxandroid and adapter-rxjava.

If I am not the only person with this issue -- I solved it with the following build.gradle dependencies:

```
// after rxandroid v0.24 the default rxjava lib does not compile
compile files('libs/rxjava-1.1.0-SNAPSHOT.jar')

compile ('io.reactivex:rxandroid:1.+') {
    exclude module: 'rxjava'
}

compile 'com.squareup.okhttp:okhttp:2.6.0'
compile 'com.squareup.retrofit:retrofit:2.0.0-beta2'
compile 'com.squareup.retrofit:converter-gson:2.0.0-beta2'
compile ('com.squareup.retrofit:adapter-rxjava:2.0.0-beta2') {
    exclude module: 'rxjava'
}
```
