### ISSUE TITLE
Wait for 2 async REST calls to result in success or error

### ISSUE THREAD

**Issue by krunalsshah** [square/retrofit#1203]
@JakeWharton 

Hey Jake, We have an use case where we need to wait for 2 async REST calls to result in either success or failure & based on outcome launch an Activity with dynamic UI labels. We use retrofit as our networking library.

Please let me know if Retrofit has an in built support the use case above? What are the alternatives?

Thanks

**Comment by JakeWharton** [comment]
With Retrofit 1 or 2?

**Comment by artem-zinnatullin** [comment]
RxJava is perfect for such tasks! And Retrofit has integration with it.

On Fri, Oct 16, 2015, 23:31 krunalsshah <notifications@github.com> wrote:

> @JakeWharton <https://github.com/JakeWharton>
>
> Hey Jake, We have an use case where we need to wait for 2 async REST calls
> to result in either success or failure & based on outcome launch an
> Activity with dynamic UI labels. We use retrofit as our networking library.
>
> Please let me know if Retrofit has an in built support the use case above?
> What are the alternatives?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/square/retrofit/issues/1203>.
>
-- 

@artem_zin

**Comment by krunalsshah** [comment]
Currently using :      compile 'com.squareup.retrofit:retrofit:1.9.0'

Open for suggestions Thanks

**Comment by krunalsshah** [comment]
Specific Methods in RX Java? Please note this is not a chain operation.
These are async REST calls & I have to wait for the 2 calls to succeed or
fail, before launching my activity & alter the labels accordingly

Code snippet would help

Thanks.
Krunal

On Fri, Oct 16, 2015 at 1:57 PM, Artem Zinnatullin <notifications@github.com
> wrote:

> RxJava is perfect for such tasks! And Retrofit has integration with it.
>

**Comment by JakeWharton** [comment]
The easiest way is to just have an `AtomicInteger` in the activity and call `decrementAndGet()` when you receive the success or failure callback. When the return value is 0, you can call a method to finalize the data received.

Something like 
```java
api.firstCall(new Callback<Whatever>() {
  @Override success(..) {
    // TODO store result
    if (count.decrementAndGet()) {
      finalizeApiCalls();
    }
    // TODO failure
});
api.secondCall(new Callback<Whatever>() {
  @Override success(..) {
    // TODO store result
    if (count.decrementAndGet()) {
      finalizeApiCalls();
    }
    // TODO failure
});
```

**Comment by JakeWharton** [comment]
There are no plans to offer something like this in the library. There's far too many requirements on how people want to combine results and failures and also the behavior they want when all fail, some fail, or all succeed to encapsulate in a single, re-usable solution. It's not that it would be impossible to do, just that it's better left to application code or other libraries like RxJava as mentioned.

**Comment by artem-zinnatullin** [comment]
@krunalsshah I'll just show you how to do it with RxJava, but if you'll go that road you should know that Rx requires some time to understand.

```java
Observable
  .zip(api.call1(), api.call2(), (result1, result2) -> new Pair(result1, result2))
  .observeOn(mainThread())
  .subscribe(
    result -> {
      // start required Activity
    },
    error -> {
      // handle error
    });
```

I think you can Google some articles/videos about applying RxJava to Android project, pretty sure that Retrofit is used as an example in many of them.
