### ISSUE TITLE
Retrofit 2.0's retrofit.Callback results in more boilerplate overall

### ISSUE THREAD

**Issue by amitav13** [square/retrofit#1205]
Coming from 1.x's success() and failure() blocks, onResponse and onFailure() require more boilerplate to achieve the same effect.

1.x:
```
success(T responseObj, Response response) { //success code }
failure(RetrofitError error) {//failure code}
```
This was concise and clear. However, with 2.0:
```
onResponse(Response<T> response, Retrofit retrofit) {
if (response.isSuccess()) {//success code} 
else { //failure code }
}

onFailure(Throwable t) { //more failure code }
 ```

Seems to be a more roundabout way of achieving the same result. Especially since the failure handling in the onResponse might require the same handling as the onFailure, like displaying a generic error message.

Is there some clear advantage that I am missing out on in using 2.0's callbacks? This change will also require a very sizeable amount of refactoring when updating from 1.x to 2.0.

**Comment by JakeWharton** [comment]
The advantage is that we don't conflate transport or serialization failures
with non-200 responses. This was done in poor taste in v1, and we are
correcting the error.

**Comment by JakeWharton** [comment]
It's also trivial to write your own callback with the same semantics as v1
and use it everywhere. You must have to come up with your own choice of
type to mash exceptions with non-200 response bodies.

**Comment by JakeWharton** [comment]
And as to the refactoring, that's the cost of 2.0. I would have made this
change over a year ago if I didn't care about maintaining API
compatibility. It quickly became apparent we made a mistake here in 1.0.

**Comment by amitav13** [comment]
I guess in a lot of my use cases, I didn't care what the response body was in non-success responses - they were handled the same from the user's perspective, so I didn't treat them any different either. But yes, its a good point about the conflation of the serialization, I've had cases where jackson barfed trying to parse a 400 response. 
Unfortunately, the refactoring issue remains. I probably won't be switching over to 2.0 on existing projects, but will make the switch on new ones. Thanks.
