### ISSUE TITLE
How to make my own Logger in retrofit 2.0.0-beta2 ?

### ISSUE THREAD

**Issue by ivanvigoss** [square/retrofit#1207]
Is there anyway to custom my logger to log http request and response or even time cost information ?
Now, I'm using ```AsyncTask``` to wrap ```Call``` , I'd like to know is there anyway more convenient ,or a build-in logger?
```java
public abstract class HttpAsyncTask<T> extends AsyncTask<Call<T>, Void, Response<T>> {
    private final static String TAG = "HttpAsyncTask";

    @Override
    protected void onPreExecute() {
        super.onPreExecute();
        //todo
    }

    @SafeVarargs
    @Override
    protected final Response<T> doInBackground(Call<T>... params) {
        try {
            if (params != null && params.length > 0) {
                Call<T> call = params[0];
                return call.execute();
            }
        } catch (IOException | ClassCastException e) {
            e.printStackTrace();
            onFailed(ResponseBody.create(MediaType.parse("text/plain; charset=utf-8"), e.getMessage()));
        }
        return null;
    }

    @Override
    protected void onPostExecute(Response<T> response) {
        super.onPostExecute(response);
        Log.d(TAG, response.raw().toString());
        if (response.isSuccess()) {
            onSuccess(response.body());
        } else {
            onFailed(response.errorBody());
        }

    }


    protected abstract void onSuccess(T body);

    protected abstract void onFailed(ResponseBody body);

}
```

**Comment by JakeWharton** [comment]
You can use a custom [OkHttp interceptor][1]. There's also [a logging interceptor][2] that I added to OkHttp which will be released in its next version which you can use out-of-the-box.

 [1]: https://github.com/square/okhttp/wiki/Interceptors
 [2]: https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor

**Comment by JakeWharton** [comment]
See also, #378.

**Comment by ivanvigoss** [comment]
Awesome.

**Comment by xmbb** [comment]
logging-interceptor-3.0.0-RC1 ， okhttp-3.0.0-RC and retrofit-2.0.0-beta3
custom logger then show me  runtime error :
java.lang.UnsupportedOperationException.

code:
    HttpLoggingInterceptor logging = new HttpLoggingInterceptor();
    logging.setLevel(HttpLoggingInterceptor.Level.BODY);
    OkHttpClient httpClient = new OkHttpClient();
    httpClient.interceptors().add(logging);  
    retrofit = new Retrofit.Builder()
                .baseUrl(BASE_HOST)
                .addConverterFactory(GsonConverterFactory.create())
                .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                .client(httpClient)
                .build();

**Comment by baoti** [comment]
okhttp-3 ```httpClient.interceptors()``` is unmodified, you can use ```OkHttpClient.Builder``` instead.
