### ISSUE TITLE
Getting Call details after creation

### ISSUE THREAD

**Issue by gnardini** [square/retrofit#1208]
Hi!

Just for context, what I'm trying to do is an Util class that receives a call but makes it only if there isn't one with the exact same target url and parameters on it's way. In that case, it waits for the response and returns to both Callbacks. This is to avoid making two identical calls at the same time.

So, I looked at this in two different ways. The first one was to receive the name of the method as a String and call it via reflection. This works but isn't very elegant and I just don't like it very much, I'd much rather not use reflection and not have to use a String for the method name to call it, since any method renaming has potential to bring bugs (also, it's a bit slower). The benfit of this is that, since I receive all of the parameters, I can easily check weather the call has already being made or not.

The other idea I came up with was to recieve a Call object and do the same as above. My problem with this is that I don't know how to compare calls. Is there any way to get the call details, such as the resource being queried or the raw data, or anything that can univocally identify it? I tried reading the source code but couldn't find anything useful and also had no luck searching on Google and SO about this.

Any help is greatly appreciated.

**Comment by JakeWharton** [comment]
Does that mean implementing `equals` and `hashCode` on `Call` would be enough? It would take into account both the information from the endpoint as well as the arguments supplied.

**Comment by gnardini** [comment]
I'd think so yes. That's the information I'm taking into account on my reflection implementation anyway, and it seems to be working, so I think that would be enough.

**Comment by JakeWharton** [comment]
Ok I'll try to look into that soon. At worst we could also expose a way to get at the underlying `Request` object of a call. I'm more hesitant about that approach, though.

**Comment by artem-zinnatullin** [comment]
@gnardini I think you can achieve the same result via `OkHttp` Interceptors API!

It seems clearer way to do it, `Request` is immutable in `OkHttp` which automatically makes it a better candidate for equality check, though it does not implement `equals()` and `hashCode()` at the moment…

From the point of performance and resources usage — both ways look equal since `Call` in `Retrofit` does not cache parsed response (and this is correct behavior because result entity may be mutable).

Personally, if I'd need to do such thing I'll go with `OkHttp` Interceptor simply because it does not require passing `Call`s around (I guess you have some wrapper over `Retrofit` for this) and it's applicable to any call adapter: RxJava, etc. `Retrofit` now in close relationships with `OkHttp` so it looks like a good solution :) 

@swankjesse, @JakeWharton  :+1: :-1: ?

**Comment by gnardini** [comment]
@artem-zinnatullin 
Hi! Thanks for your suggestion. I hadn't though about using an Interceptor. I just looked into how I'd do it and I guess I could do it that way, but the other one seems easier and more intuitive to me.

**Comment by imminent** [comment]
We have an approach that uses the `CallAdapter.Factory` to keep track of `Call`s that are active, from there we can cancel a call when a new call of the same type is requested. As it is now, it only grabs the relativeURI off the Method Annotation (such as `GET` or `POST`). But that approach could possibly work for constructing a `CompositeCallback` that chains the callbacks.
 
Also, I ran into an issue not having any access to the underlying `Request` object ([question](http://stackoverflow.com/q/33793570/910718)), so having that exposed might be beneficial.

Here's some code:
```java
public class TagCancellableCallAdapterFactory implements CallAdapter.Factory {
    private final ArrayMap<String, Call> mQueuedCalls;
    private final ArrayMap<Call, Callback> mQueuedCallbacks;

    private TagCancellableCallAdapterFactory() {
        mQueuedCalls = new ArrayMap<>(2);
        mQueuedCallbacks = new ArrayMap<>(2);
    }

    public static TagCancellableCallAdapterFactory create() {
        return new TagCancellableCallAdapterFactory();
    }

    @Override
    public CallAdapter<?> get(final Type returnType, Annotation[] annotations, Retrofit retrofit) {
        boolean hasTagAnnotation = false;
        String value = StringUtils.EMPTY;
        for (Annotation annotation : annotations) {
            if (annotation instanceof Tag) {
                hasTagAnnotation = true;
            } else if (annotation instanceof DELETE) {
                value = ((DELETE) annotation).value();
            } else if (annotation instanceof GET) {
                value = ((GET) annotation).value();
            } else if (annotation instanceof HEAD) {
                value = ((HEAD) annotation).value();
            } else if (annotation instanceof PATCH) {
                value = ((PATCH) annotation).value();
            } else if (annotation instanceof POST) {
                value = ((POST) annotation).value();
            } else if (annotation instanceof PUT) {
                value = ((PUT) annotation).value();
            }
        }
        final boolean isTagged = hasTagAnnotation;
        final String tag = value;
        final CallAdapter<?> delegate = retrofit.nextCallAdapter(this, returnType, annotations);
        final ExecutorService executor = retrofit.client().getDispatcher().getExecutorService();
        return new CallAdapter<Object>() {
            @Override
            public Type responseType() {
                return delegate.responseType();
            }

            @Override
            public <R> Object adapt(Call<R> call) {
                return delegate.adapt(isTagged ? new TaggedCall<>(call, tag, mQueuedCalls, mQueuedCallbacks, executor) : call);
            }
        };
    }

    static final class TaggedCall<T> implements Call<T> {
        private final Call<T> mDelegate;
        private final String mTag;
        private final ArrayMap<String, Call> mQueuedCalls;
        private final ArrayMap<Call, Callback> mQueuedCallbacks;
        private final ExecutorService mExecutor;

        TaggedCall(Call<T> delegate, String tag, ArrayMap<String, Call> queuedCalls, ArrayMap<Call, Callback> queuedCallbacks, ExecutorService executor) {
            mQueuedCalls = queuedCalls;
            mQueuedCallbacks = queuedCallbacks;
            mTag = tag;
            mDelegate = delegate;
            mExecutor = executor;
        }

        @Override
        public Response<T> execute() throws IOException {
            return mDelegate.execute();
        }

        @Override
        public void enqueue(Callback<T> callback) {
            synchronized (mQueuedCalls) {
                // Cancel enqueued call for the same tag
                if (mQueuedCalls.containsKey(mTag)) {
                    final Call queuedCall = mQueuedCalls.get(mTag);
                    if (queuedCall != null) {
                        // WORKAROUND: https://github.com/square/okhttp/issues/1592 Call.cancel() is triggering StrictMode
                        mExecutor.execute(new Runnable() {
                            @Override
                            public void run() {
                                queuedCall.cancel();
                            }
                        });
                    }
                    mQueuedCalls.remove(mTag);

                    final Callback queuedCallback = mQueuedCallbacks.get(queuedCall);
                    if (queuedCallback != null) {
                        //noinspection unchecked
                        callback = new CompositeCallback<>(queuedCallback);
                    }
                }
                // Add call to enqueued calls
                mQueuedCalls.put(mTag, mDelegate);
                mQueuedCallbacks.put(mDelegate, callback);
            }
            mDelegate.enqueue(callback);
        }

        @Override
        public void cancel() {
            mDelegate.cancel();
        }

        @SuppressWarnings("CloneDoesntCallSuperClone" /* Performing deep clone */)
        @Override
        public Call<T> clone() {
            return new TaggedCall<>(mDelegate.clone(), mTag, mQueuedCalls, mQueuedCallbacks, mExecutor);
        }
    }

    static final class CompositeCallback<T> implements Callback<T> {
        private final List<Callback<T>> mChainedCallbacks;

        CompositeCallback(Callback<T> callback) {
            if (callback instanceof CompositeCallback) {
                mChainedCallbacks = ((CompositeCallback<T>) callback).mChainedCallbacks;
            } else {
                mChainedCallbacks = new LinkedList<>();
                mChainedCallbacks.add(callback);
            }
        }

        @Override
        public void onResponse(Response<T> response, Retrofit retrofit) {
            for (Callback<T> callback : mChainedCallbacks) {
                callback.onResponse(response, retrofit);
            }
        }

        @Override
        public void onFailure(Throwable t) {
            for (Callback<T> callback : mChainedCallbacks) {
                callback.onFailure(t);
            }
        }
    }
}
```

**Comment by JakeWharton** [comment]
You can probably do this with a `Call.Factory` now. It has access to the `Request` and can return a custom `Call` that reads from a cache or joins to an in-flight `Call`.

**Comment by gnardini** [comment]
Sounds good, I'll give that a try!

**Comment by imminent** [comment]
What `Call.Factory` are you referencing? @JakeWharton

**Comment by JakeWharton** [comment]
It was removed, replaced with OkHttp's `Call.Factory` instead.

**Comment by JakeWharton** [comment]
#1484 fulfilled the requirements of the original issue description here by providing the ability to eagerly create and return `Request` object for a `Call`.

**Comment by petrnohejl** [comment]
@JakeWharton Any idea how to get an encapsulated `Call` object or `Request` object from RxJava 2 `Observable` (when using `RxJava2CallAdapterFactory`)?
