### ISSUE TITLE
In my android project the php service return json is Not  specification, some times return key is data , some times return key  like r_tf what ever,so if I want return json-string and I parser json in onResponse()，what should I do?

### ISSUE THREAD

**Issue by xiaomeixw** [square/retrofit#1211]
RT...in 2.0 beta,If the service return json is Not  specification,how can I  get json-string ,I want to parser json on my own way?

**Comment by JakeWharton** [comment]
You can use `ResponseBody` as the type and then call `.string()` in the `onResponse` callback.

**Comment by ayon115** [comment]
You need to use a StringConverter in your Retrofit Builder configuration, it will return the Response as String which you'll get by calling `response.body()`. Then you can parse it any way you like.

**Comment by xiaomeixw** [comment]
@JakeWharton  & @ayon115  Great , it worked well ....Thanks for your REST-library....
