### ISSUE TITLE
HTTP/1.1 400 BAD_REQUEST through  Retrofit  onHttp GET ,while getting data through calling same api using POSTMAN 

### ISSUE THREAD

**Issue by MacSimmy** [square/retrofit#1215]
Hi I found a  strange behavior of Retrofit client in my android application which uses a retrofit Rest Api library. Some of my  HTTP GET api calls result to error HTTP/1.1 400 BAD_REQUEST, while hitting the same  api URi using some other rest client like Postman get the response correctly. Please provide some  guide where I am missing the critical thing using retrofit. Calling agin same api sometimes get the correct  response. Retrofit logs are as follows:

10-21 00:30:42.103 28391-28444/com.retail D/Retrofit: <--- HTTP 400 https://api.parse.com/1/classes/Product?where={"primaryCategory":"kids","secondaryCategory":"kids_baby_boys_clothes","$or":[{"brand":"Beebay"},{"brand":"612 League"}],"priceRegular":{"$gte":100,"$lte":10000}}&limit=15&skip=0&count=true&order= (272ms)
10-21 00:30:42.103 28391-28444/com.retail D/Retrofit: : HTTP/1.1 400 BAD_REQUEST
10-21 00:30:42.103 28391-28444/com.retail D/Retrofit: Connection: Close
10-21 00:30:42.103 28391-28444/com.retail D/Retrofit: Content-Length: 0
10-21 00:30:42.104 28391-28444/com.retail D/Retrofit: X-Android-Received-Millis: 1445401842103
10-21 00:30:42.104 28391-28444/com.retail D/Retrofit: X-Android-Response-Source: NETWORK 400
10-21 00:30:42.104 28391-28444/com.retail D/Retrofit: X-Android-Sent-Millis: 1445401841832
10-21 00:30:42.104 28391-28444/com.retail D/Retrofit: <--- END HTTP (0-byte body)
10-21 00:30:42.106 28391-28391/com.retail D/RetailCommand: GetPMPDataCmd::notifyError() - fire event to: com.retail.ui.activity.PMPActivity$11@11b368a4

**Comment by Sutirth** [comment]
I am facing the same issue while using retrofit I get error code as 400 have used the deserialized error body example as well. But errorBody gives null always whereas on postman It shows data.

**Comment by JakeWharton** [comment]
A 400 response means that the server didn't like your request, but that the request was created, sent, and a response was parsed. The latter 3 things are Retrofit's job, and constructing a well-formed request is your job.

If there's clear evidence (like a test case) that Retrofit was the cause of the malformed request we can look at the issue, but otherwise this is likely just you doing something that the server can't understand and that is entirely dependent on your code and what the server expects.

**Comment by Sutirth** [comment]
I agree with you Jake but in my scenario my request generated is pretty simple for e.g
{
  "appStatusCode": 100,
  "data": "NOTFOUND_TEAM"
}

and for success

{
  "appStatusCode": 0,
  "data": "TEAM_FOUND"
} 

but still during fetching errorBody it gives me null and http response code as 400. Can you give any inputs on this

**Comment by liorzam** [comment]
The solution to that is it that in postman you send your 'where' object as a parameter .l recommend that you change in api instead of @Body to @Query

Let me know if this is solve your issue

**Comment by Sutirth** [comment]
I am Using it as a GET itself and sending it as query to server

**Comment by MacSimmy** [comment]
Hi liorzam,
I am also using GET with @Query annotation for where  clause. I am not  able to create a fixed test case in which it is failing always. But It fails most of time and get the response correctly very few  times. I am not able  to track from where it is breaking my rest call i.e. from my server or Retrofit?

**Comment by liorzam** [comment]
Send me your code and i will try to help you with this issue 
email: liorzam@gmail.com
