### ISSUE TITLE
How can I cancel the request with Rxjava

### ISSUE THREAD

**Issue by shj00007** [square/retrofit#1216]

**Comment by artem-zinnatullin** [comment]
If you are using Retrofit 2 - unsubscribe from the Observable/Single.

On Wed, Oct 21, 2015, 09:40 shj00007 <notifications@github.com> wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/square/retrofit/issues/1216>.
>
-- 

@artem_zin

**Comment by shj00007** [comment]
@artem-zinnatullin but the request has been in running until the request finish, how can I stop the request?

**Comment by artem-zinnatullin** [comment]
Retrofit will try to cancel request https://github.com/square/retrofit/blob/8162cefddc3af8dc213183795429de68224c5323/retrofit-adapters/rxjava/src/main/java/retrofit/RxJavaCallAdapterFactory.java#L102

**Comment by JakeWharton** [comment]
The `Call` type has a `cancel()` method and `Observable` unsubscription will also call that method.

**Comment by shj00007** [comment]
@artem-zinnatullin thanks!!

**Comment by hegazy** [comment]
@JakeWharton Can we just unsubscribe without canceling when using RxJava?
