### ISSUE TITLE
Retrofit + RxJava, how to obtain the responses' error body in case 4XX errors

### ISSUE THREAD

**Issue by ranadeep47** [square/retrofit#1218]
I am using `retrofit:2.0.0-beta2` with RxJava and i cannot access the response body in the onError method of my subscriber. 
```
        Retrofit retrofit = new Retrofit
                .Builder()
                .baseUrl(ViatoService.baseUrl)
                .client(client)
                .validateEagerly()
                .addConverterFactory(new ToStringConverterFactory())
                .addConverterFactory(MoshiConverterFactory.create())
                .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                .build();
```

**Comment by artem-zinnatullin** [comment]
In case of  response `code < 200 || code >= 300` (OkHttp handles redirects and so on) `RxJavaCallAdapter` will emit `onError()` with [`HttpException`](https://github.com/square/retrofit/blob/master/retrofit-adapters/rxjava/src/main/java/retrofit/HttpException.java), [`HttpException`](https://github.com/square/retrofit/blob/master/retrofit-adapters/rxjava/src/main/java/retrofit/HttpException.java) contains response with body and other info.

**Comment by JakeWharton** [comment]
There are three ways to construct your observable: `Observable<BodyType>`, `Observable<Response<BodyType>>`, or `Observable<Result<BodyType>>`. For the first version, there's nowhere to hang non-200 response information so it is included in the exception passed to `onError`. For the latter two, the data is encapsulated in the `Response` object and can be accessed by calling `errorBody()`.

**Comment by alejantab** [comment]
Hello.

I know that this post is old, but i Have a little problem, when I am getting the answer if I use ((HttpException) throwable).response().errorBody().string() and later I try to use the line again or assign to another variable, the second value is empty, anybody has been in the same situation?.

Thanks for your help.

**Comment by jcholin** [comment]
@alejantab Once you consume the `response body`, you can't reuse it anymore. It's a normal behavior. Then store your response body (`response().errorBody().string()`) in a variable first, then reuse this variable.

**Comment by GuoZhaoHui628** [comment]
```
    public void onError(Throwable e){
        HttpException error = (HttpException)e;
        String errorBody = error.response().errorBody().string();
       // now,you can do what you want to do ,like parse ....
 }
```
Hope to help you!

**Comment by fanjavaid** [comment]
If you want to separate Response Error and Exception, use `Response<BaseResponse<String>>`
So you can fetch your non 200 response with body in `onNext`, and exception in `onError`

**Comment by RadoVidjenGost** [comment]
Hi guys, i have very similar problem, can you check this question on stackoverflow: [](https://stackoverflow.com/questions/50945672/retrofit-response-codes-with-rxjava2)

**Comment by chintan-mishra** [comment]
@fanjavaid can you please elaborate your version of the solution?

**Comment by apexkid** [comment]
Will love to have a snippet for this. I still couldn't understand how will i manage to get my response body from API in case of an error as onError method only takes in a Throwable.

My server sends custom response in case of error such as
```
{
	"status": "Success",
	"httpcode": 400,
	"devMessage": "APICallSuccess",
	"userMessage": "Problems with your input",
	"data": {...}
}
```

I want to show the userMessage to the user while using Retrofit + RxJava.

**Comment by amaury-mv** [comment]
> Will love to have a snippet for this. I still couldn't understand how will i manage to get my response body from API in case of an error as onError method only takes in a Throwable.
> 
> My server sends custom response in case of error such as
> 
> ```
> {
> 	"status": "Failed",
> 	"httpcode": 400,
> 	"devMessage": "APICallSuccess",
> 	"userMessage": "Problems with your input",
> 	"data": {...}
> }
> ```
> 
> I want to show the userMessage to the user while using Retrofit + RxJava.

I want the same but i dont know how to catch response body in java

**Comment by bernatdelgado87** [comment]
Sample:

Exception Class

`public class ExcepcionApi {

    private int estado;
    private String mensaje;
    private int codigo;

    public ExcepcionApi(int estado, String mensaje, int codigo){
        this.estado = estado;
        this.mensaje = mensaje;
        this.codigo = codigo;
    }
.......`

UserBean

`public class UsuarioBean {

    @SerializedName("estado")
    @Expose
    private Integer estado;
    @SerializedName("usuario")
    @Expose
    private Usuario usuario;`

........

The observer

`public DisposableObserver<Response<UsuarioBean>> getObserver(){
        return new DisposableObserver<Response<UsuarioBean>>() {

            @Override               
            public void onNext(@NonNull Response loginResponse) {

//HERE is SAVED THE ERROR RESPONSE. 
ExcepcionApi excepcionApi = ExcepcionApi.fromResponseBody(loginResponse.errorBody());
Log.d("presenter", excepcionApi.getMensaje());`

**Comment by ashboomla** [comment]
> There are three ways to construct your observable: `Observable<BodyType>`, `Observable<Response<BodyType>>`, or `Observable<Result<BodyType>>`. For the first version, there's nowhere to hang non-200 response information so it is included in the exception passed to `onError`. For the latter two, the data is encapsulated in the `Response` object and can be accessed by calling `errorBody()`.

How would one go about calling the errorBody(). Conceptually I understand but Its not clear on how to implement, I only have a throwable in the `onError` block which doesn't seem capable of accessing the Response. Can someone please go more in depth on this.
