### ISSUE TITLE
version 1.9 class RequestBuilder didn't not use added function

### ISSUE THREAD

**Issue by yunair** [square/retrofit#1221]
In `RequestBuilder` class, there are two implementions of  `addQueryParam()` function, 
- private void addQueryParam(String name, Object value, boolean encodeName, boolean encodeValue) 
- private void addQueryParam(String name, String value, boolean encodeName, boolean encodeValue)

but in `addQueryParamMap()` function, there using the second implements instead of the first.

In the queryMap, they can not putting List or Array In it, So I think it's useful to use the first implements replace the second.

before I change

```java
private void addQueryParamMap(int parameterNumber, Map<?, ?> map, boolean encodeNames,
                                  boolean encodeValues) {
        for (Map.Entry<?, ?> entry : map.entrySet()) {
            Object entryKey = entry.getKey();
            if (entryKey == null) {
                throw new IllegalArgumentException(
                        "Parameter #" + (parameterNumber + 1) + " query map contained null key.");
            }
            Object entryValue = entry.getValue();
            if (entryValue != null) { // Skip null values.
                addQueryParam(entryKey.toString(), entryValue.toString(), encodeNames, encodeValues);
            }
        }
    }
```

after I change

```java
private void addQueryParamMap(int parameterNumber, Map<?, ?> map, boolean encodeNames,
                                  boolean encodeValues) {
        for (Map.Entry<?, ?> entry : map.entrySet()) {
            Object entryKey = entry.getKey();
            if (entryKey == null) {
                throw new IllegalArgumentException(
                        "Parameter #" + (parameterNumber + 1) + " query map contained null key.");
            }
            Object entryValue = entry.getValue();
            if (entryValue != null) { // Skip null values.
                addQueryParam(entryKey.toString(), entryValue, encodeNames, encodeValues);
            }
        }
    }
```

**Comment by JakeWharton** [comment]
This done explicitly as iterable values are not supported in 1.x. Issue #626 and even #685 to some degree are tracking the feature to add support for this case (and others like the use of Multimap from Gauva).

**Comment by yunair** [comment]
But in 1.x, users can use `@Query` annotation to use there feature, why does not be supported at `@QueryMap` annotation?
