### ISSUE TITLE
Support for GWT RPC Servlets

### ISSUE THREAD

**Issue by poseidonjm** [square/retrofit#1225]
GWT is a compiler from Java to Javascript and is used to build Single Page Applications. You write your client code (javascript compatible) in java then it is compiled to javascript. While there a javascript client there is no java client for GWT RPC Servlets.

Although there is a java client for GWT RequestFactory Servlets. It can be used with Android and GWT with the exact same code.

From 
http://stackoverflow.com/questions/4119867/when-should-i-use-requestfactory-vs-gwt-rpc
The big difference between GWT RPC and RequestFactory is that the RPC system is "RPC-by-concrete-type" while RequestFactory is "RPC-by-interface".

From 
http://www.gwtproject.org/doc/latest/tutorial/RPC.html
The GWT RPC framework exchange Java objects over HTTP on your web application. The server-side code that gets invoked from the client is often referred to as a service. The implementation of a GWT RPC service is based on the well-known Java servlet architecture. Within the client code, you’ll use an automatically-generated proxy class to make calls to the service. GWT will handle serialization of the Java objects passing back and forth—the arguments in the method calls and the return value.

GWT RPC services are not the same as web services based on SOAP or REST. They are simply as a lightweight method for transferring data between your server and the GWT application on the client

**Comment by JakeWharton** [comment]
What does this entail?

**Comment by JakeWharton** [comment]
Also, why?

**Comment by JakeWharton** [comment]
With no compelling reason, and no large group of people wanting this support, I see no reason to add it. Retrofit focuses on the HTTP RFC's defined behaviors.

**Comment by poseidonjm** [comment]
Sorry for open an un unnecessary issue. GWT will remove support for GWT RPC Servlets and RequestFactory Servlets according to this webinar https://www.brighttalk.com/webcast/11505/201545/the-state-of-gxt-and-gwt
The suggestion for GWT developers is to move from GWT RPC to resty-gwt
