### ISSUE TITLE
Request with several Query parameter having same key

### ISSUE THREAD

**Issue by ayon115** [square/retrofit#1226]
I need to make a GET request where there are several Query parameters but their keys are same. For example : 

`http://api.example.com?filter=name&filter=age&filter=occupation`

So, if I use a QueryMap (HashMap of String) , It does not work because as key is same for every parameter, so only last Parameter will hit the API. And as there are many parameters like this, so writing a method with so many separate Query parameter does not seem to be good to me. Can anyone please help me on this ? 

Thanks in advance.

**Comment by JakeWharton** [comment]
You can use `@Query("filter") List<String> filters`, `@Query("filter") String[] filters`, or if it's the last parameter on the method `@Query("filter") String... filters`. One key/value pair will be added for each entry in the list or array.

Here's some examples in the test cases: https://github.com/square/retrofit/blob/parent-1.9.0/retrofit/src/test/java/retrofit/RequestBuilderTest.java#L1092-L1138

**Comment by manishpatelgt** [comment]
Hi @JakeWharton but if the @Query parameter is in between then we can us it? URL like https://api.stackexchange.com/2.2/me?key=gQJsL7krOvbXkJ0NEI((&site=stackoverflow&order=desc&sort=reputation&access_token=HM*22z8nkaaoyjA8PD))&filter=default
