### ISSUE TITLE
The Data of @Part RequestBody in Arguments in 2.0.0-beta2.

### ISSUE THREAD

**Issue by simpleton** [square/retrofit#1229]
Does the 2.0.0-beta2 version retrofit put the @Part data in arguments? 
```
    @Multipart
    @POST("/v1/user/avatar")
    Observable<Map<String, String>> updateAvatar(@Part("avatar") RequestBody photo);
```
I create photo with below code:
```
RequestBody image = RequestBody.create(MediaType.parse("image/*"), imageFileName);
```

The server will get the data from arguments, not in files. 
Is that right?

**Comment by ayon115** [comment]
See #1063

**Comment by enginebai** [comment]
@simpleton What's your requirement?? Or you may check #1217.

**Comment by simpleton** [comment]
@enginebai thanks for your reply. ayon115 had gave me the workaround. 
Close now.
