### ISSUE TITLE
NoSuchMethodError after calling Retrofit creating static method

### ISSUE THREAD

**Issue by petrLorenc** [square/retrofit#1232]
I have this problem with creating Retrofit service (if the code below write to method directly everything is OK)

     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime: FATAL EXCEPTION: main
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime: Process: cz.united121.rxandroid, PID: 9472
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime: java.lang.NoSuchMethodError: No static method createNetworkService(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/Object; in class Lcz/united121/rxandroid/model/network/NetworkService; or its super classes (declaration of 'cz.united121.rxandroid.model.network.NetworkService' appears in /data/app/cz.united121.rxandroid-1/base.apk)
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime:     at cz.united121.rxandroid.model.recyclerModel.RecyclerModel.updateDataToDatabase(RecyclerModel.java:35)
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime:     at cz.united121.rxandroid.presenter.recyclerPresenter.RecyclerPresenter.updateRecyclerViewClick(RecyclerPresenter.java:64)
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime:     at cz.united121.rxandroid.view.recyclerView.RecyclerFragment.onClickupdateRecyclerView(RecyclerFragment.java:74)
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime:     at cz.united121.rxandroid.view.recyclerView.RecyclerFragment$$ViewBinder$1.doClick(RecyclerFragment$$ViewBinder.java:22)
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime:     at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime:     at android.view.View.performClick(View.java:4785)
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:19884)
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5343)
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

the line where a call createNetworkService

    	NetworkService networkService = NetworkService.createNetworkService(NetworkService.class, NetworkService.TEST_ENDPOINT);

and function looks like this 

    public interface NetworkService {
	static <T> T createNetworkService(final Class<T> tClass, final String endPoint) {
		Retrofit retrofit = new Retrofit.Builder()
				.addCallAdapterFactory(RxJavaCallAdapterFactory.create())
				.addConverterFactory(GsonConverterFactory.create())
				.baseUrl(endPoint)
				.build();
		T service = retrofit.create(tClass);
		return service;
	}
    ....
It looks like the error from here https://github.com/square/okhttp/issues/967 (I write my post even there too)

**Comment by JakeWharton** [comment]
This error is in your code and how it's being built and has nothing to do
with Retrofit itself. It also has nothing to do with OkHttp or Okio.

Since you're showing a static method on an interface and yet showing logcat
I'd wager it's a Retrolamda problem.
