### ISSUE TITLE
Beta2 @Path not replacing values

### ISSUE THREAD

**Issue by cooperkong** [square/retrofit#1234]
Hi,
I have been using this great library for a while but recently I have discovered that in one of the legacy project I'm working on that uses multidex in androud studio, @Path is not been replaced somehow. This is the log I received from server side.

Request [/group/%7Bid%7D/users] received

I have created a sample project and it works fine, when I run the same code in that big project, it failed to replace {id} with the actual value. I have tried to disable proguard and multidex by removing several classes. But still no luck.

The sample project is very basic, just the samples from http://square.github.io/retrofit/, so there is no special customizations.

**Comment by JakeWharton** [comment]
Code? Link to sample? You didn't include any information here.

**Comment by cooperkong** [comment]
Hi Jake
The sample is very basic.It is literally the Github interface from http://square.github.io/retrofit/ with no customisations rather than change the baseurl to "http://mylocalhost:1234".

Normal @GET without @Path works fine, only below doesn't work
@GET("/group/{id}/users")
List<User> groupList(@Path("id") int groupId);

{id} is logged as %7Bid%7D on the server side.

**Comment by JakeWharton** [comment]
I do not see the same behavior. Please provide a test case.

Here was mine:
```java
public final class Test {
  interface Service {
    @GET("/group/{id}/users") //
    Call<ResponseBody> groupList(@Path("id") int groupId);
  }

  public static void main(String... args) throws IOException {
    OkHttpClient client = new OkHttpClient();
    client.interceptors().add(new Interceptor() {
      @Override public Response intercept(Chain chain) throws IOException {
        Request request = chain.request();
        System.out.println("URL: " + request.urlString());
        return chain.proceed(request);
      }
    });

    Retrofit retrofit = new Retrofit.Builder()
        .baseUrl("http://mylocalhost:1234")
        .addConverterFactory(GsonConverterFactory.create())
        .client(client)
        .build();
    Service service = retrofit.create(Service.class);

    service.groupList(12).execute();
  }
}
```
```
URL: http://mylocalhost:1234/group/12/users
Exception in thread "main" java.net.UnknownHostException: mylocalhost: unknown error
```

**Comment by cooperkong** [comment]
Yeah, it is working in my sample as well. After disable multidex, I was able to debug through retrofit.
in parseParameters method in RequestFactoryParser at line 199

```
    Annotation[][] methodParameterAnnotationArrays = method.getParameterAnnotations();
...
   int count = methodParameterAnnotationArrays.length
```
count is returned as 0, however the method definition has @Path as parameter

**Comment by JakeWharton** [comment]
Are you using ProGuard?

**Comment by cooperkong** [comment]
Yeah, I have below exclusions.
```

-keep class com.squareup.okhttp.** { *; }
-keep class retrofit.** { *; }
-keep interface com.squareup.okhttp.** { *; }
-keep interface com.mysample.retrofit.* //the retrofit interface
```
And it still doesn't work.

**Comment by cooperkong** [comment]
I was suspecting that as well. Looks like I need to -keep the retrofit interface .

All good now ! Thanks.

**Comment by JakeWharton** [comment]
Great!
