### ISSUE TITLE
Post method but server receives GET

### ISSUE THREAD

**Issue by ArcaneWater** [square/retrofit#1236]
I tryed to switch to 2.0 Retrofit and here is my interface class:

```
public interface ApiService {

    @POST("login/")
    Call<User> login(@Body User user);
}
```

And then in class i call

```
 Retrofit retrofit = new Retrofit.Builder()
                .baseUrl("http://myapi.com/api/")
                .addConverterFactory(GsonConverterFactory.create())
                .build();

 ApiService service = retrofit.create(ApiService.class);
```
And at the end a normal execute call with 
```
            User postUser = new User(mEmail, mPassword, "1234556789");

            Call<User> call = service.login(postUser);
            call.enqueue(new Callback<User>() {.....
```

And server always receives GET instead of POST, bug or i'm doing something wrong?

**Comment by ayon115** [comment]
Your code seems to be fine except one thing. Can you please re-check the API endpoint "login/", may be "/" at the end is sending the request to another Endpoint. It seems to be API specific issue, but It's my guess only.

**Comment by JakeWharton** [comment]
If the server replies with a 302 or 303 to force the connection onto https then the POST will be changed to a GET per RFC 2616. Can you check if this is happening?

**Comment by ArcaneWater** [comment]
Thanks that was the issue yes, it was forcing https.

**Comment by Murat88** [comment]
I have same problem ,but server side returns 400 (Bad request) because it calls get methot instead of post.
Also I have lunched my post request on an online http request site to check if the server web api works fine or not ,And it is OK.But retrofit still calls GET . i'm doing something wrong?

**Comment by Murat88** [comment]
I found the solution : I noticed that i forgot "www" in BaseUrl base url should be http://www.blabla.com.
Never forget www !!!
