### ISSUE TITLE
Is it possible to support FastJson for addConverterFactory?

### ISSUE THREAD

**Issue by aliang5820** [square/retrofit#1237]
my project used FastJson:https://github.com/alibaba/fastjson

**Comment by JakeWharton** [comment]
We will not be adding any more first-party converters. The API supports
creating your own, and there's a wiki page which lists available
third-party ones. You can look at the implementations of the ones included
in Retrofit for guidance.

**Comment by SeanCode** [comment]
You can use my [lib](https://github.com/SeanCode/retrofit-converters-fastjson) which could help you。

**Comment by aliang5820** [comment]
@SeanCode  thx a lot

**Comment by syhily** [comment]
@SeanCode Tks. Needs little change.

**Comment by spysoos** [comment]
@syhily Could you tell me HOW you do that?
