### ISSUE TITLE
Proposition : use Jackson-jr

### ISSUE THREAD

**Issue by Grodzickir** [square/retrofit#1241]
Wouldn't it fit more the mobile environment to use Jackson-jr ? https://github.com/FasterXML/jackson-jr

Accordingly to this project description, it speeds up application start up.

**Comment by JakeWharton** [comment]
Looks like it has a completely different API. We won't be adding any more
first-party converters for the foreseeable future. There's a wiki page
which lists third-party converters for use with Retrofit 2, and I would
encourage someone to create a version for this library if it is useful.
