### ISSUE TITLE
Callback not executed due to JVM exit even when using non daemon threads

### ISSUE THREAD

**Issue by alexamster** [square/retrofit#1243]
Running tests and the JVM is exiting before my callback ever gets invoked. I have attempted to use a custom executor with non daemon threads:

    ExecutorService exec = Executors.newSingleThreadExecutor(new ThreadFactory() {
            @Override
            public Thread newThread(Runnable runnable) {
                Thread thread = new Thread(runnable);
                thread.setDaemon(false);
                thread.setPriority(Thread.MAX_PRIORITY);
                return thread;
            }
        });

    new Retrofit.Builder()
                .baseUrl(baseUrl)
                .addConverterFactory(GsonConverterFactory.create(SpGson.getGson()))
                .client(getclient())
                .callbackExecutor(exec)
                .build();

If I add some code to keep the JVM alive such as:

        for (int i = 0; i < 1000000; i++) {
            System.out.print("");
        }

the test executes properly and my callback gets invoked. From reading other issues I thought setDaemon(false) would solve the problem, but that is not the case. Am I missing something here? :(

**Comment by JakeWharton** [comment]
I don't see this behavior, and it shouldn't happen. OkHttp uses non-daemon threads for its worker threads which keeps the JVM alive and by default it uses a callback executor that runs on those same threads.

I made the following change to test:
```diff
--- a/samples/src/main/java/com/example/retrofit/SimpleService.java
+++ b/samples/src/main/java/com/example/retrofit/SimpleService.java
@@ -18,7 +18,9 @@ package com.example.retrofit;
 import java.io.IOException;
 import java.util.List;
 import retrofit.Call;
+import retrofit.Callback;
 import retrofit.GsonConverterFactory;
+import retrofit.Response;
 import retrofit.Retrofit;
 import retrofit.http.GET;
 import retrofit.http.Path;
@@ -57,9 +59,16 @@ public final class SimpleService {
     Call<List<Contributor>> call = github.contributors("square", "retrofit");

     // Fetch and print a list of the contributors to the library.
-    List<Contributor> contributors = call.execute().body();
-    for (Contributor contributor : contributors) {
-      System.out.println(contributor.login + " (" + contributor.contributions + ")");
-    }
+    call.enqueue(new Callback<List<Contributor>>() {
+      @Override public void onResponse(Response<List<Contributor>> response, Retrofit retrofit) {
+        for (Contributor contributor : response.body()) {
+          System.out.println(contributor.login + " (" + contributor.contributions + ")");
+        }
+      }
+
+      @Override public void onFailure(Throwable t) {
+        t.printStackTrace();
+      }
+    });
   }
 }
```
and the JVM stayed alive for 60 seconds after the completion of the request.

Please provide an executable test case that demonstrates the bug. It's usually easiest to modify an existing test or sample.

**Comment by alexamster** [comment]
Here is the whole test:

    public void testCallback() throws Exception {
        MockWebServer server = new MockWebServer();
        server.enqueue(new MockResponse());
        server.start();
        String baseUrl = server.url("/api/v1/").toString();

        final SpAccountAnonymousSignupRequest signupReq =
                new SpAccountAnonymousSignupRequest("testid", "testsecret");

        ExecutorService exec = Executors.newSingleThreadExecutor(new ThreadFactory() {
            @Override
            public Thread newThread(Runnable runnable) {
                Thread thread = new Thread(runnable);
                thread.setDaemon(true);
                thread.setPriority(Thread.MAX_PRIORITY);
                return thread;
            }
        });

        AccountService accountService = new Retrofit.Builder()
                .baseUrl(baseUrl)
                .addConverterFactory(GsonConverterFactory.create(SpGson.getGson()))
                .client(new OkHttpClient())
                .callbackExecutor(exec)
                .build().create(AccountService.class);

        accountService.createAnonUser(signupReq).enqueue(new Callback<SpAccountTokenResponse>() {
             @Override
             public void onResponse(Response<SpAccountTokenResponse> response, Retrofit retrofit) {
                 System.out.println("onResponse");
             }

             @Override
             public void onFailure(Throwable t) {
                 System.out.println("onFailure");
             }
         });
    }

Running it (JUnit3) will result in the following logs:

    Nov 05, 2015 5:39:55 PM com.squareup.okhttp.mockwebserver.MockWebServer$3 execute
    INFO: MockWebServer[49788] starting to accept connections

    Process finished with exit code 0

I then added this code to keep the VM alive (at the very end of the test):

    Nov 05, 2015 5:45:10 PM com.squareup.okhttp.mockwebserver.MockWebServer$3 execute
    INFO: MockWebServer[49807] starting to accept connections
    Nov 05, 2015 5:45:10 PM com.squareup.okhttp.mockwebserver.MockWebServer$4 processOneRequest
    INFO: MockWebServer[49807] received request: POST /api/v1/signup HTTP/1.1 and responded: HTTP/1.1 200 OK
    onResponse

    Process finished with exit code 0

Although after some reading I now realize JUnit only supports assertions on the main thread, so I'm not sure what the best strategy would be for testing callbacks. Is there any recommended pattern for this?

**Comment by JakeWharton** [comment]
This is not due to the JVM exiting before the response, but rather the test method exiting before the response is received. The JVM will wait because of the non-daemon thread, but JUnit will not.

One way to enforce the waiting is to use a `CountDownLatch` that waits at the end of the method and which is counted down in each of the two callbacks from `Callback`. This will block the test thread until one of the callbacks are executed, and doesn't actually need you to create your own executor.

```java
final CountDownLatch latch = new CountDownLatch(1);
accountService.createAnonUser(signupReq).enqueue(new Callback<SpAccountTokenResponse>() {
  @Override
  public void onResponse(Response<SpAccountTokenResponse> response, Retrofit retrofit) {
    System.out.println("onResponse");
    latch.countDown();
  }

  @Override
  public void onFailure(Throwable t) {
    t.printStackTrace(System.out);
    latch.countDown();
  }
});
    
assertTrue(latch.await(5, SECONDS));
```

**Comment by alexamster** [comment]
Ah, that makes sense. Thanks for the info!
