### ISSUE TITLE
Retrofit 2 does not allow Call without type and is not able to map empty body with Jackson

### ISSUE THREAD

**Issue by stefanli** [square/retrofit#1245]
If I understand it correctly Retrofit does not allow using Call without types i.e.: 

```
@DELETE(PATH_COLLECTION_CARD)
Call deleteCard(@Path("id") String collectionId, @Path("card") String cardId);
```

This results in: Caused by: java.lang.IllegalArgumentException: Call return type must be parameterized as Call<Foo> or Call<? extends Foo>

The rationale for this being "All HTTP calls have a response therefore we force you to acknowledge it in your method signature." according to @JakeWharton in [this issue](https://github.com/square/retrofit/issues/603).

I'm encountering APIs that returns an empty body but I would still like to use Call for the other features it provides ( execute vs enqueue etc..). My workaround was to declare an EmptyData object like so:

```
@DELETE(PATH_COLLECTION_CARD)
Call<EmptyData> deleteCard(@Path("id") String collectionId, @Path("card") String cardId);
```

However, because the body is completely empty Jackson now throws this exception:
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input

Wouldn't it make sense to allow Calls without types in this case?

**Comment by iagreen** [comment]
Did you try --

```@DELETE(PATH_COLLECTION_CARD)
Call<Void> deleteCard(@Path("id") String collectionId, @Path("card") String cardId);```

Top of the beta2 change list -- https://github.com/square/retrofit/blob/master/CHANGELOG.md

**Comment by stefanli** [comment]
That was exactly what I was looking for. My google-fu failed me in this instance. Thanks. )
