### ISSUE TITLE
could not find GsonConverterFactory in 2.0.0-beta

### ISSUE THREAD

**Issue by shivakumars** [square/retrofit#1246]
I am trying to migrate to 2.0.0 beta 2 and the studio could not find 'GsonConverterFactory ' class in package. can anyone help?

**Comment by shivakumars** [comment]
Never mind. Just learned that i have to import another dependency for it

> compile 'com.squareup.retrofit:converter-gson:2.0.0-beta2'

thanks.

**Comment by Zapnologica** [comment]
Thanks, I also had this issue. I appreciate the followup response.
