### ISSUE TITLE
How do i add custom error handler in retrofit 2.0.0 beta

### ISSUE THREAD

**Issue by shivakumars** [square/retrofit#1247]
I had a custom error handler(deserializer), how do i implement that in 2.0.0?

**Comment by iagreen** [comment]
There is a sample here - 

https://github.com/square/retrofit/blob/master/samples/src/main/java/com/example/retrofit/DeserializeErrorBody.java

**Comment by JakeWharton** [comment]
Dupe of #1102. The concept of ErrorHandler isn't really needed because we killed the awful RetrofitError type.
