### ISSUE TITLE
How do I get the full Url in logcat By Retrofit2 ?

### ISSUE THREAD

**Issue by xiaomeixw** [square/retrofit#1248]
If I want to see my full Url address in logcat ,like this :http://www.xxxxx.com/v2/myhome/getUser?page=1&md5=837482739DFGEHT877&id=372759.  What should I do?

**Comment by ayon115** [comment]
You can use the HTTPLoggingInterceptor from the latest snapshot build of Okhttp and Retrofit. Set the log level to BODY, you'll see the Url and all necessary logs of your request.

Sample code
```
HttpLoggingInterceptor logging = new HttpLoggingInterceptor();
        logging.setLevel(HttpLoggingInterceptor.Level.BODY);
        okHttpClient.interceptors().add(logging);

```

**Comment by xiaomeixw** [comment]
Perfect,with the okhttp‘s HttpLoggingInterceptor ,I see every information in my logcat,@ayon115 Thanks for your Generous help.

**Comment by xiaomeixw** [comment]
Close the issue.it Has been resolved,Thanks....
