### ISSUE TITLE
Image Uploading with retrofit:2.0.0-beta2

### ISSUE THREAD

**Issue by HariKvana** [square/retrofit#1249]
I am new to retrofit, getting error while uploading image.Please help me.. 

 trying to upload Image to true vault - https://console.truevault.com/login

API to upload image : https://docs.truevault.com/BLOBs#create-a-blob

Should include a boundary parameter as specified in the RFC http://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.2

My code Repo : https://github.com/HariKvana/TrueVault-BLOB

Request : 
@Multipart
@Headers({"Content-Type:multipart/form-data; boundary=AaB03x",
            "Content-Length :524,288,000"})
@POST("/v1/vaults/{vaultKey}/blobs")
Call<String> createBlob(@Header("Authorization") String authorization, @Path("vaultKey") String voltKey, @Part("file") RequestBody file);

Response: 
Response{protocol=http/1.1, code=400, message=BAD REQUEST, url=https://api.truevault.com/v1/vaults/9cce4add-11e1-4102-9cde-8dd55ce18c01/blobs}
<img width="1305" alt="blob" src="https://cloud.githubusercontent.com/assets/10043265/10861871/3d263fee-7fb7-11e5-93a9-4165a211823b.png">

**Comment by raniejade** [comment]
I never tried to set the Content-Type header when doing a multipart request, I think retrofit does it for you automatically? Have you tried to remove the `@Headers(...)` annotation?

**Comment by HariKvana** [comment]
@raniejade, Thanks for response

Do you mean like this..

@Multipart
@POST("/v1/vaults/{vaultKey}/blobs")
Call<String> createBlob(@Header("Authorization") String authorization, @Path("vaultKey") String voltKey, @Part("file") RequestBody file);

Respons:
Response{protocol=http/1.1, code=400, message=BAD REQUEST, url=https://api.truevault.com/v1/vaults/9cce4add-11e1-4102-9cde-8dd55ce18c01/blobs}

Getting success response with content type application/octet-stream and request as below.. 

@Headers({"Content-Type:application/octet-stream; boundary=AaB03x",
            "Content-Length :524,288,000"})
@POST("/v1/vaults/{vaultKey}/blobs")
Call<String> createBlob(@Header("Authorization") String authorization, @Body("vaultKey") String voltKey, @Body String file);

But it is uploading image string not image..

picasso unable to load the image which uploade with below request..

**Comment by raniejade** [comment]
Ahhh

```java
    String filePath;

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (resultCode == RESULT_OK) {
            if (requestCode == Constants.REQUEST_CODE_GALLERY) {
                filePath = ImageUtils.getFilePath(this, data.getData());
                Bitmap bitmap = ImageUtils.createBitMap(filePath);
                showProgressDialog();
                RequestBody file = RequestBody.create(MediaType.parse("image/*"), filePath);

                RetrofitHandler.getInstance().getCreateBlob("Basic " + Util.stringToBase64(Constants.ADMIN + ":"), Constants.VAULT, file).enqueue(createBlobCallBack);
            } else
                showToast("Something went wrong.");

        }
    }
```

What you are actually uploading is not a file but the path to that file. `filePath` is a String, you need to pass an instance of a `File`. `RequestBody.create` has an overloaded method that accepts a `File` as its second parameter.

**Comment by HariKvana** [comment]
@raniejade 

Thanks you so much .. It uploaded successfully..(downloading successfully from TrueVault website).

@Headers({"Content-Type:application/octet-stream; boundary=AaB03x",
            "Content-Length :524,288,000"})
@POST("/v1/vaults/{vaultKey}/blobs")
Call<String> createBlob(@Header("Authorization") String authorization, @Path("vaultKey") String voltKey, @Body RequestBody file);

 @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (resultCode == RESULT_OK) {
            if (requestCode == Constants.REQUEST_CODE_GALLERY) {
                filePath = ImageUtils.getFilePath(this, data.getData());
                Bitmap bitmap = ImageUtils.createBitMap(filePath);
                showProgressDialog();
                RequestBody file = RequestBody.create(MediaType.parse("image/*"), new File(filePath));

                RetrofitHandler.getInstance().getCreateBlob("Basic " + Util.stringToBase64(Constants.ADMIN + ":"), Constants.VAULT, file).enqueue(createBlobCallBack);
            } else
                showToast("Something went wrong.");

        }
    }

But true vault people saying they only supports  @Headers({"Content-Type:multipart/form-data; boundary=AaB03x" but getting 400 response I use Content-Type:multipart/form-data, same 400 response with out any content-Type Headers.

Picasso unable to load this is this issue because of content-Type?

Again Thanks for giving time..

**Comment by raniejade** [comment]
Hey, sorry not familiar with true vault. Since it's not a retrofit issue I don't think this is the right place to discuss it, please close this issue.

**Comment by HariKvana** [comment]
Ok Thank you so much..

**Comment by JakeWharton** [comment]
Sounds like you got the Retrofit problem sorted out but now are only having problems with the service so I'll close. You can ask general usage questions on StackOverflow using the 'retrofit' tag.
