### ISSUE TITLE
Unable to convert my Request to RequestBody

### ISSUE THREAD

**Issue by youranshul** [square/retrofit#1250]
I am trying to upgrade my retrofit1.9 to retroit2.0. I have followed the tutorial from this link. But i am getting below error when i try to make a request though it was working fine with retrofit1.9.

java.lang.RuntimeException: Unable to convert requestData.LoginRequestModel@427cde88 to RequestBody
10-31 02:58:30.785  32100-32100/.com W/System.err﹕ at retrofit.RequestBuilderAction$Body.perform(RequestBuilderAction.java:276)
10-31 02:58:30.786  32100-32100/.com W/System.err﹕ at retrofit.RequestFactory.create(RequestFactory.java:62)
10-31 02:58:30.786  32100-32100/.com W/System.err﹕ at retrofit.OkHttpCall.createRawCall(OkHttpCall.java:120)
10-31 02:58:30.786  32100-32100/.com W/System.err﹕ at retrofit.OkHttpCall.enqueue(OkHttpCall.java:60)
10-31 02:58:30.786  32100-32100/.com W/System.err﹕ at retrofit.ExecutorCallAdapterFactory$ExecutorCallbackCall.enqueue(ExecutorCallAdapterFactory.java:57)

http://stackoverflow.com/questions/33445315/unable-to-convert-my-request-to-requestbody

I know Jake told me not to duplicate the post but i don't know why my question was down voted there and i am stuck now with this error .So i apologize for that.But please help me with it.

**Comment by raniejade** [comment]
Jackson probably can't convert `LoginRequestModel`.

Exception thrown by the converter factory is silently ignored, see https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit/RequestBuilderAction.java#L276

**Comment by youranshul** [comment]
But i don't know what is the problem with my LoginRequestModel though things were fine with retrofit 1.9

**Comment by raniejade** [comment]
If I remember correctly pre 2.0 retrofit does not have a built-in Jackson converter. Are you using custom one before?

**Comment by youranshul** [comment]
Yes

**Comment by raniejade** [comment]
You probably configured the `ObjectMapper` differently before (jackson auto detect functionality is turned on?). `JacksonConverterFactory.create` has an overloaded method that accepts an `ObjectMapper` as its first parameter.

**Comment by youranshul** [comment]
Yes . I had an ObjectMapper  with Jackson auto turned on.Let me check with passing the same ObjectMapper .

**Comment by youranshul** [comment]
Awesome .Thanks raniejade, it worked with my custom ObjectMapper. But don't know what is the problem with the ObjectMapper configured with JacksonConverterFactory.

**Comment by raniejade** [comment]
No worries. `JacksonConverterFactory.create()` just instantiates a new `ObjectMapper` if you don't pass one.

**Comment by youranshul** [comment]
I can happily close this issue now.
