### ISSUE TITLE
POST request with Body and Query

### ISSUE THREAD

**Issue by TurhanOz** [square/retrofit#1253]
Hi, 

using retrofit:2.0.0-beta2 & okhttp 2.5.0

Among all my API calls from the same retrotit client (using same endpoint), one is failing with the following message : 
```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.squareup.okhttp.HttpUrl$Builder com.squareup.okhttp.HttpUrl.newBuilder()' on a null object reference
```

The only specificity of this POST call is to have a Body as well as a Query .

```
public interface BeaconInfoService {
    @POST("beaconinfo:getforobserved")
    Observable<ListBeaconsInfo> getForObserved(@Query("key") String key, @Body ListObservations listObservations);
}
```

Any idea ? Thx

**Comment by TurhanOz** [comment]
The colon character seems to be the reason of this bug...
Is there any restriction for using colon character in url (in this precise configuration) ? 
A magic fix for now (yet haven't explored the root cause)
```
@POST("beaconinfo\\:getforobserved")
```
Thanks

**Comment by JakeWharton** [comment]
Minimum test case:
```java
HttpUrl base = HttpUrl.parse("http://example.com");
System.out.println("BASE: " + base);
HttpUrl resolved = base.resolve("beaconinfo:getforobserved");
System.out.println("RESOLVED: " + resolved);
```
```
BASE: http://example.com/
RESOLVED: null
```

@swankjesse What do you think about this? I'm guessing the colon causes it to see this as a user/password combo with no host which then becomes invalid.

**Comment by JakeWharton** [comment]
Ping @swankjesse

**Comment by iagreen** [comment]
It is interpreting the `beaconinfo:` as a scheme and okhttp is rejecting it as unknown.  This seems generally inline with how browsers resolve the same issue.  Given a base url and an href with "beaconinfo:getforobserved", both firefox and chrome will fail to build the desired url and attempt to find a "beaconinfo" protocol.  A workaround for both browsers and okhttp/retrofit is to prepend a path element, even if it is just a leading `/`.

`@POST("/beaconinfo:getforobserved")`

or

`HttpUrl resolved = base.resolve("/beaconinfo:getforobserved");`

**Comment by JakeWharton** [comment]
Ah, yeah. Good call.

Unfortunately the leading slash makes the path absolute instead of
relative. This won't work if your base URL has path segments itself (
http://example.com/api/ resolving /a:b will result in
http://example.com/a:b not
http://example.com/api/a:b) but would if you had none.

**Comment by iagreen** [comment]
Unfortunately so. In your example you could resolve, http://example.com/ with api/a:b to get the correct result because any leading path element with stop it from being recognized as a scheme. It is dissatisfying to make the user special case their url construction, but users can construct their base + path segments to account for all possibilities.  

One option to get resolve to handle it would be to treat the segment as relative if it causes an unknown scheme error.  That would resolve the original case, but would also have resolve do things like 

http://example.com/ + mailto:test@example.com --> http://example.com/mailto:test@example.com

**Comment by JakeWharton** [comment]
@swankjesse thoughts here?

**Comment by swankjesse** [comment]
Try `./beaconinfo:getforobserved`

**Comment by JakeWharton** [comment]
Neat trick! Confirming it works:
```java
HttpUrl base = HttpUrl.parse("http://example.com/path/");
System.out.println("BASE: " + base);
HttpUrl resolved = base.resolve("./beaconinfo:getforobserved");
System.out.println("RESOLVED: " + resolved);
```
```
BASE: http://example.com/path/
RESOLVED: http://example.com/path/beaconinfo:getforobserved
```

**Comment by swankjesse** [comment]
Yeah. Colons in paths are generally a bad idea ’cause they can be confused with schemes.
