### ISSUE TITLE
Support for array query parameters

### ISSUE THREAD

**Issue by BoldijarPaul** [square/retrofit#1255]
Hello.
I have an url such as:

www.adress.com/api/people?ages=10,20,25&something=123

I want to query for people that are 10, 20 or 25 years old.
If I set the Query parameter to a int array, I will get an url such as

www.adress.com/api/people?ages=10&ages=20&ages=25

Will ever be a fix for this?
Thanks.

**Comment by JakeWharton** [comment]
This isn't broken, but working as intended. If you need to join a series of
values that is an application level concern. Do it before calling Retrofit
as we have no way of knowing how to join those items.

See also #626 which would let you handle this yourself.

**Comment by bartoszbanczerowski** [comment]
The simplest way:
If You want to have only one query for age, You can make a dictionary for mobile and server side.

Example age dictionary:
1 - only 10
2 - only 15
3 - only 25
4 - 10 and 15
5 - 10 and 25
6 - 15 and 25

**Comment by JakeWharton** [comment]
You can also just do Joiner.on('.').join(items) in the call to Retrofit. If
you're using Java 8, you can use a default method that calls the real
implementation that only takes a String value.
