### ISSUE TITLE
Empty JSONObject even though logging was OK

### ISSUE THREAD

**Issue by brucardoso2** [square/retrofit#1256]
Hi everyone, 

```
compile 'com.squareup.retrofit:retrofit:2.0.0-beta2'
compile 'com.squareup.retrofit:converter-gson:2.0.0-beta2'
compile 'com.squareup.okhttp:logging-interceptor:2.6.0-SNAPSHOT'
```

Here is my Retrofit initialization (enabling OkHttp logging)
```java
OkHttpClient client = new OkHttpClient();
HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
interceptor.setLevel(HttpLoggingInterceptor.Level.BODY);
client.interceptors().add(interceptor);

// Initialize Retrofit
Retrofit retrofit = new Retrofit.Builder()
        .baseUrl("http://myendpoint.com")
        .client(client)
        .addConverterFactory(GsonConverterFactory.create())
        .build();
```

After executing this command of my API (which works fine on Postman)
```java
@GET("data")
Call<JSONObject> getData();
```

The `Response<JSONObject> reponse` has an empty JSONObject on its `response.body`, which makes no sense even though OkHttp logging Interceptor was able to print the body data correctly.

**Comment by JakeWharton** [comment]
The `JSONObject` type is from `org.json.*` not Gson. You want `JsonObject` from `com.google.gson.*` or to bind to your own model class.

**Comment by luffynas** [comment]
@JakeWharton Thank you very much :D
