### ISSUE TITLE
How to set httpExecutor in Retrofit 2?

### ISSUE THREAD

**Issue by dmarusic35** [square/retrofit#1259]
Retrofit 1 has ```RestAdapter.Builder().setExecutors``` method which sets both httpExecutor and callbackExecutor while Retrofit 2 allows only to set callbackExecutor. Is there any way to set httpExecutor in Retrofit 2?

**Comment by JakeWharton** [comment]
Retrofit 2 uses OkHttp's async API (assuming you use `Call.enqueue`) which has manages its own threads per host for execution. OkHttp allows [setting a `Dispatcher`][1] which is the object the owns the threading, and [can be created with an `ExecutorService`][2]. if you just want to monitor the background execution, you can ask the `OkHttpClient` for its `Dispatcher` and then ask that instance for its `ExecutorService`.

 [1]: http://square.github.io/okhttp/2.x/okhttp/com/squareup/okhttp/OkHttpClient.html#setDispatcher-com.squareup.okhttp.Dispatcher-
 [2]: http://square.github.io/okhttp/2.x/okhttp/com/squareup/okhttp/Dispatcher.html#Dispatcher-java.util.concurrent.ExecutorService-

**Comment by dmarusic35** [comment]
Thanks for quick reply

**Comment by JakeWharton** [comment]
Our of curiosity, are you just trying to monitor the background threads or
do you need to supply your own due some reason?

**Comment by dmarusic35** [comment]
I needed to supply my own Executor because when I run tests using Robolectric I want calls to be executed synchronously, on main thread. Manage to do it now by setting up Dispatcher, which is created by my implementation of ExecutorService, as you suggested.

**Comment by JakeWharton** [comment]
Ah, OK. Great!

**Comment by pkhivesara** [comment]
@dmarusic35  Can you provide a snippet of how to go about creating the dispatcher and setting it up on the rest client?

**Comment by dmarusic35** [comment]
@pkhivesara I provide `Dispatcher` using Dagger. For app, I use default implementation:
```java
@Provides
@Singleton
public Dispatcher provideDispatcher() {
    return new Dispatcher();
}
```

On the other hand, for tests, I use `Dispatcher` with my own implementation of `ExecutorService` (method `execute(Runnable command)` is where magic happens):
```java
@Provides
@Singleton
public Dispatcher provideDispatcher() {
    // this dispatcher will ensure networking is done on the main thread
    return new Dispatcher(new SynchronousExecutorService());
}

private class SynchronousExecutorService implements ExecutorService {

    @Override
    public void shutdown() {

    }

    @NonNull
    @Override
    public List<Runnable> shutdownNow() {
        return null;
    }

    @Override
    public boolean isShutdown() {
        return false;
    }

    @Override
    public boolean isTerminated() {
        return false;
    }

    @Override
    public boolean awaitTermination(long timeout, TimeUnit unit) throws InterruptedException {
        return false;
    }

    @NonNull
    @Override
    public <T> Future<T> submit(Callable<T> task) {
        return null;
    }

    @NonNull
    @Override
    public <T> Future<T> submit(Runnable task, T result) {
        return null;
    }

    @NonNull
    @Override
    public Future<?> submit(Runnable task) {
        return null;
    }

    @NonNull
    @Override
    public <T> List<Future<T>> invokeAll(Collection<? extends Callable<T>> tasks) throws InterruptedException {
        return null;
    }

    @NonNull
    @Override
    public <T> List<Future<T>> invokeAll(Collection<? extends Callable<T>> tasks, long timeout, TimeUnit unit)
            throws InterruptedException {
        return null;
    }

    @NonNull
    @Override
    public <T> T invokeAny(Collection<? extends Callable<T>> tasks) throws InterruptedException, ExecutionException {
        return null;
    }

    @Override
    public <T> T invokeAny(Collection<? extends Callable<T>> tasks, long timeout, TimeUnit unit)
            throws InterruptedException, ExecutionException, TimeoutException {
        return null;
    }

    @Override
    public void execute(Runnable command) {
        command.run();
    }
}
```

And I just set provided dispatcher to OkHttpClient:
```java
OkHttpClient.Builder okHttpClientBuilder = new OkHttpClient.Builder();
okHttpClientBuilder.dispatcher(dispatcher);
...
```
