### ISSUE TITLE
Can't intercept request and add parameters as previously could

### ISSUE THREAD

**Issue by ncapdevi** [square/retrofit#1261]
In previous retrofit versions it was possible to add an interceptor and use that to add query parameters that were globally needed for example:

 .setRequestInterceptor(new RequestInterceptor() {
                    @Override
                    public void intercept(RequestFacade requestFacade) {
                        requestFacade.addQueryParam("platform", "android");
                        requestFacade.addQueryParam("app_version", com.package.BuildConfig.VERSION_NAME);

                    }
                })

With the new implementation, it's required that you use OkHttpClient.interceptors.  With this new approach, how would one append parameters without removing the original parameters?

**Comment by JakeWharton** [comment]
http://stackoverflow.com/q/33558352/132047
