### ISSUE TITLE
Http2 Support

### ISSUE THREAD

**Issue by pranaysharma** [square/retrofit#1265]
Hi,
My server www.parkzap.com supports Http2.
To what I understand Retrofit is based on Okhttp.
Below is the code I used to fix the Protocol type in okhttp and pass it to Retrofit. But in the debug log it still shows to use only HTTP1.1.(i.e D/Retrofit: OkHttp-Selected-Protocol: http/1.1) 
Kindly advice if this feature is available.
Pranay

Code:

        List<Protocol> proto_list = new ArrayList<Protocol>();
        proto_list.add(Protocol.HTTP_2);
        proto_list.add(Protocol.HTTP_1_1);
        proto_list.add(Protocol.SPDY_3);
        http_client.setProtocols(proto_list);

        http_client.setReadTimeout(okhttp_timeout, TimeUnit.SECONDS);     // connect timeout
        http_client.setConnectTimeout(okhttp_timeout, TimeUnit.SECONDS);  // socket timeout

        RestAdapter.Builder builder = new RestAdapter.Builder()
                .setEndpoint(baseUrl)
                .setClient(new OkClient(http_client));

**Comment by JakeWharton** [comment]
OkHttp supports HTTP/2, yes, but Retrofit has nothing to do with that. There's nothing for Retrofit to do here. Try with OkHttp directly and ensure that the HTTP/2 can be negotiated and once that's working use the same configuration on the client you pass to Retrofit.

**Comment by pranaysharma** [comment]
Thanks a lot for the reply. 
You are correct this is not a Retrofit issue. Further it seems that after Andorid 5.0 only Http2 is supported.
Thanks for great tools you are building at Square.
