### ISSUE TITLE
[Proposal] Add isExecuted API to Call interface

### ISSUE THREAD

**Issue by philipgiuliani** [square/retrofit#1267]
What do you think about adding a
```java
boolean isExecuted();
```
API to the Call interface?

Would  be helpful in some situations. Of course i could handle it by myself by setting executed true in the onResponse and onFailure handling, but would still be nice to have it in retrofit.

I would also be open to add it via a PR if you are interested.

**Comment by JakeWharton** [comment]
For what purpose? When would you not know if a call had been executed?

**Comment by philipgiuliani** [comment]
In my app i have the following, simple, usecase:
I am loading some unimportant data in the background which i need when the users clicks on a button. Now if the data is not loaded yet the user should get a message that it's still loading. In this case its not possible to disable the button (Leanback has no option for this...)

**Comment by JakeWharton** [comment]
@swankjesse have opinions here? Right now Retrofit's Call mirrors OkHttp's, so if we expose this, ideally OkHttp would expose it as well.

**Comment by eneim** [comment]
It seems to be close to ```tag``` object in OkHttp call. For now, OkHttp allows user to build ```Request``` with ```tag```, and OkHttpClient could ```cancel``` request for those tags. So IMO it would be nice if we could have more convenient method for ```tags``` like ```OkHttpClient#isExecuted(Object tag)```.

**Comment by JakeWharton** [comment]
That would require keeping far too much state and it provides no way of
dealing with both executed and unexecuted calls of the same tag.

**Comment by swankjesse** [comment]
In OkHttp: https://github.com/square/okhttp/pull/2022
