### ISSUE TITLE
when onFailure method called in enqueue(new Callback)?

### ISSUE THREAD

**Issue by yuandaimadeshijie** [square/retrofit#1268]
OnResponse method could be called every times? 
    Even 400,404,or 500? 
    If there are no return value ,I need try this way : Call<Response> ? 
    What different about com.squareup.okhttp.Response and retrofit.Response,
    Which object should i import?

----------------------------------------------------------------------------------------------
MyApplication.api.login(user).enqueue(new Callback() {
            @Override
            public void onResponse(Response response, Retrofit retrofit) {
                if (response.code()==200){
                    showDialogContent(user.getUsername(), "登录成功", "");
                }
            }
            @Override
            public void onFailure(Throwable t) {
                showErrorLogin("登录失败", "您输入的密码有误，请重新登录");
            }
        });
@POST("user/login")
    Call<Response>  login(@Body User user);

**Comment by tomkoptel** [comment]
Hello @yuandaimadeshijie !

You can find answer on your question in following issue [#1260](https://github.com/square/retrofit/issues/1260).

**Comment by JakeWharton** [comment]
Indeed. See the linked issue.
