### ISSUE TITLE
add spring custom tag support

### ISSUE THREAD

**Issue by yuankui** [square/retrofit#1270]
I was very excited when I come across with this project.
It make my http request invocation logic very clear,like mybatis for SQL

But when I want to use it In my spring project, I found that I must create `Retrofit` manually and 'compile'(`retrofit.create(GitHubService.class)`) every interface manually.

so I was looking for a mybatis-styled spring config,which config Retrofit as expected, and scan specific package and compile the interfaces. But I didn't find it.

so I am wondering if this will be a great feature,for spring projects intergration. And I am pleased to contribute.

**Comment by raniejade** [comment]
You can use a factory bean (https://spring.io/blog/2011/08/09/what-s-a-factorybean).

**Comment by JakeWharton** [comment]
We don't really have much interest in maintaining a Spring integration since we don't use it for anything and are unlikely to use it any time soon. Can this be done as a sibling project?

**Comment by yuankui** [comment]
okay, I will start a sibling project myself..

**Comment by JakeWharton** [comment]
Closing this out since there's no action to take on our side. In general, moving forward we're are trying to minimize the number of first-party modules maintained in the repo.
