### ISSUE TITLE
support etcd restful style, path containing charactor '/'

### ISSUE THREAD

**Issue by yuankui** [square/retrofit#1272]
When I use retrofit to implement a interface for etcd
https://coreos.com/etcd/docs/latest/api.html#setting-the-value-of-a-key

`curl http://127.0.0.1:2379/v2/keys/message -XPUT -d value="Hello world"`

where I declaire a method like
```
@PUT("/v2/keys/{key}")
    @FormUrlEncoded
    Call<Result> set(@Path(value = "key", encoded = true) String key, @Field("value")String value, @Field("ttl") int ttl);
```

when i invoke `etcdService.set("/test/key", "testValue")`, It still urlencoded my key although I declaired with `@Path(value = "key", encoded = true)`

I checked the source code and found It has a `PATH_SEGMENT_ENCODE_SET = " \"<>^`{}|/\\?#"` in which chars are always encoded.

But In the case I cannot do it with the `/` char encode.

So I propose to remove `/` from the PATH_SEGMENT_ENCODE_SET.

**Comment by yuankui** [comment]
https://github.com/square/retrofit/pull/1273

**Comment by swankjesse** [comment]
Would this work?

```
@PUT("/v2/keys/{key1}/{key2}")
    @FormUrlEncoded
    Call<Result> set(
        @Path(value = "key1") String key1,
        @Path(value = "key2") String key2,
        @Field("value")String value, @Field("ttl") int ttl);

```
etcdService.set("test", "key", "testValue")
```

The `@Path` annotation matches a single path segment.

**Comment by JakeWharton** [comment]
There's also @Url which lets you specify an entire relative (or absolute)
URL as a parameter to the method.

**Comment by JakeWharton** [comment]
```java
@PUT
@FormUrlEncoded
Call<Result> set(
    @Url String url,
    @Field("value") String value,
    @Field("ttl") int ttl);
```
```java
String value = "/test/key";
service.set("keys/" + value, "some", "value");
```

**Comment by yuankui** [comment]
@swankjesse that will not cover /test/it/that, and /test/it/and/this, ie, the path deep is not always the same.

@JakeWharton that may be a solution. But I have two concat the prefix& key like `/v2/keys/$key` in every  when ever I invoke this service, That's not elegant, I think.

for me, I would prefer applying the the patch above, and will wait for your reconstruction.

**Comment by JakeWharton** [comment]
It will not be applied. As I said in the PR, the code is temporary and will eventually be removed in favor of OkHttp's path encoding (per #1129). You're basically describing HATEOAS with a prefix, which is exactly what `@Url` parameters were meant for. We could maybe look at allowing a fixed prefix here, but the complexity might not be justified.
