### ISSUE TITLE
Getting exception after adding Proguard

### ISSUE THREAD

**Issue by HariKvana** [square/retrofit#1279]
My Request : 

@FormUrlEncoded
    @POST("/v1/auth/login")
    Call<String> loginUser(@Field("username") String username, @Field("password") String password, @Field("account_id") String accountId);

My Proguard:

-dontobfuscate
-optimizations !field/removal/writeonly,!field/marking/private,!class/merging/*,!code/allocation/variable
-dontwarn retrofit.**
-keep class retrofit.** { *; }
-keepattributes Signature
-keepattributes Exceptions

Exception : 
E: android.view.InflateException: Binary XML file line #76: Binary XML file line #33: Error inflating class Button
D: Shutting down VM
E: FATAL EXCEPTION: main
E: Process: com.sikkasoft.humos2_doctor, PID: 5668
E: java.lang.IllegalArgumentException: Form-encoded method must contain at least one @Field.
E:     for method TrueVaultApiService.loginUser$226b3f16
E:     at retrofit.Utils.methodError(Utils.java:177)
E:     at retrofit.RequestFactoryParser.parse(RequestFactoryParser.java:11167)
E:     at retrofit.MethodHandler.create(MethodHandler.java:30)
E:     at retrofit.Retrofit.loadMethodHandler(Retrofit.java:151)
E:     at retrofit.Retrofit$1.invoke(Retrofit.java:132)
E:     at java.lang.reflect.Proxy.invoke(Proxy.java:393)
E:     at com.sikkasoft.humos2.network.$Proxy1.loginUser$226b3f16(Unknown Source)
E:     at com.sikkasoft.humos2.network.RetrofitHandler.loginUser(RetrofitHandler.java:53)
E:     at com.sikkasoft.humos2_doctor.fragment.LoginFragment$1.onClick(LoginFragment.java:88)
E:     at android.view.View.performClick(View.java:5198)
E:     at android.view.View$PerformClick.run(View.java:21147)
E:     at android.os.Handler.handleCallback(Handler.java:739)
E:     at android.os.Handler.dispatchMessage(Handler.java:95)
E:     at android.os.Looper.loop(Looper.java:148)
E:     at android.app.ActivityThread.main(ActivityThread.java:5417)
E:     at java.lang.reflect.Method.invoke(Native Method)
E:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by JakeWharton** [comment]
The exception indicates that the annotations are being stripped from the method parameters. I'm not a proguard expert, and this isn't the right place to figure out how to use that tool. There's bound to be some configuration option which retains annotations.

You should try on StackOverflow with the 'retrofit' and 'proguard' tags, as it's a much better place for usage questions. This tracker is for bug reports and feature requests, and since proguard is a third-party tool the audience for getting help on it here is severely limited.
