### ISSUE TITLE
Retrofit post request won't trigger on first time with multiple fields that are form URL encoded.

### ISSUE THREAD

**Issue by ArslanAli7** [square/retrofit#1280]
Hi jake, I am working with retrofit 2.0 beta version in my Android application,whenever I run my  app on some new device, the post request that I am executing using call.enque won't enter the callback i.e  on Response,onFailure part,I have to execute the request once more to obtain the results,also afterwards it work just fine,untill I open the app after some idle time,maybe I am doing mistake somewhere while creating the rrquest, in addition to retrofit beta version library I am using okhttp library as a request interceptor, I can share my code of rest client if you want me to.Best regards.

**Comment by JakeWharton** [comment]
Need to see code. Otherwise we have no idea what's going on.

**Comment by ArslanAli7** [comment]
Basically its an OAuth request in which i have to sent client_secret,client_id,username,password etc. on response of which i receive an access token,i am using rest client for chrome to double check if there is some other issue,but the request execute just fine every time i use the rest client,does we need to add some more information to the request in order to retrofit know its an oauth request,also i am using call.eneque() on the main thread without using  any async task on the main UI thread,i have change everything related to the code,firstly i was creating the Retrofit object in the class name restclient,after some time i decided to move the retrofit builder functionality to the button that is actually triggering the request, but no success after this as well,i have spent too much time on it,if you just highlight a general mechanism to execute the Post request that is form url encoded of oauth type i would be really thankful,i have my api methods in a separate interface.

**Comment by JakeWharton** [comment]
Still need to see code or a representative sample that reproduces the
issue. We have no way of knowing what's happening here without it and we're
not going to guess at what you're doing.

**Comment by ArslanAli7** [comment]
Here is the code:
RestWebApiInterface :

 public interface RestWebApiInterface {

        //Api Method to Receive the Access token Details
        @FormUrlEncoded
        @POST("/xyz/abc")
        Call<Login> getUserDetails(@Field("grant_type") String grantType,
                                   @Field("username") String userName,
                                   @Field("password") String passWord,
                                   @Field("client_id") String clientId,
                                   @Field("client_secret") String clientSecret);

}

LoginActivity.java:
Sign in button click part:
 OkHttpClient okClient = new OkHttpClient();
        okClient.interceptors().add(new Interceptor() {
            @Override
            public com.squareup.okhttp.Response intercept(Chain chain) throws IOException {
                com.squareup.okhttp.Response response = chain.proceed(chain.request());
                return response;
            }
        });

        Retrofit client = new Retrofit.Builder()
                .baseUrl("https://www.xyz.com")
                .client(okClient)
                .addConverterFactory(GsonConverterFactory.create())
                .build();
         restWebApiInterface = client.create(RestWebApiInterface.class);
        Call<Login> call = restWebApiInterface.getUserDetails( getResources().getString(R.string.grant_type), email, password, getResources().getString(R.string.client_id), getResources().getString(R.string.client_secret));
 call.enqueue(this);

    }
i have onResponse and onFailure implementation below inside the class and i have implemented the Callback<Login> on LoginActivity

**Comment by ArslanAli7** [comment]
Hi jake ,hoping  you are doing great,i have increased the timeout of the request now it seems to work awesome,thanks for your help,i am in love with  retrofit 2.0,thanks a lot for your time.

**Comment by JakeWharton** [comment]
Great. Glad you figured it out.
