### ISSUE TITLE
Skip Retrofit API calls to server if there is no active internet connection

### ISSUE THREAD

**Issue by punitshah89** [square/retrofit#1281]
I am using Retrofit 1.9.0 and OkHttp 2.5.0.

Is there a way to skip server call and get OkClient request object to maintain RequestQueue when device is offline ?

Such as retrofit is trying to hit the server even though there is no connectivity to network. I want to prevent hitting server by checking internet connection. Want to access request parameter without performing retrofit server call. basically want to prevent call to invoke(Object proxy, Method method, final Object[] args) method in retrofit.RestAdapter class and want to use below request object to maintain RequestQueue.
```java
 @Override
    public Response execute(Request request) throws IOException {
       
        return response;
    }﻿
```

**Comment by JakeWharton** [comment]
No. Retrofit only concerns itself with the construction of the HTTP request from high-level interface declarations, submitting that request to the underlying HTTP client, and parsing the response into a high-level response object.

Something like a request queue is an application-level concern and should be implemented on top of Retrofit (such as queueing `Call` instances) checking whatever indication of network connectivity the target platform has.

We have no plans for anything like this.
