### ISSUE TITLE
How to upload a video using Retrofit 2-beta

### ISSUE THREAD

**Issue by mkamrani** [square/retrofit#1285]
Hi everybody,
I want to upload a video using Retrofit 2-beta (chosen from gallery) to a server. Would you please show me a working sample. I especially doubt about the RequestBody and the annotation. I really haven't found any proper documentation for this so far. This is what I have done almost blindly.

	public interface UploadApiService 
	{
		@Multipart
		@PUT("api/upload.php")
		Call<ResponseBody> uploadVideo(
				@Part("description") String description, 
				@Part(("videos\"; filename=\"a.mp4\" ")) RequestBody video);
	}

----

	public class MainActivity extends Activity 
	{
	    private static int RESULT_LOAD_VIDEO = 1;
	    String decodableString;
	    @Override
	    protected void onCreate(Bundle savedInstanceState) 
	    {
	        super.onCreate(savedInstanceState);
	        setContentView(R.layout.activity_main);
	        final Button btn_load = (Button) findViewById(R.id.buttonLoadVideo);
	        btn_load.setOnClickListener(new OnClickListener() {
	
	            @Override
	            public void onClick(View v) {
	                // TODO Auto-generated method stub
	               loadVideoFromGallery(btn_load);
	            }
	        });
	    }
	    /*
	     * PICK THE VIDEO AND EXTRACT ITS ADDRESS
	     */
	    public void loadVideoFromGallery(View view) 
	    {
	        Intent galleryIntent = new Intent(Intent.ACTION_PICK,
	                android.provider.MediaStore.Video.Media.EXTERNAL_CONTENT_URI);
	        startActivityForResult(galleryIntent, RESULT_LOAD_VIDEO);
	    }
	    @Override
	    protected void onActivityResult(int requestCode, int resultCode, Intent data) 
	    {
	        super.onActivityResult(requestCode, resultCode, data);
	        try {
	            // When a video is picked
	            if (requestCode == RESULT_LOAD_VIDEO && resultCode == RESULT_OK
	                    && null != data) 
	            {
	                // Get the video from data
	                Uri selectedVideo = data.getData();
	                String[] filePathColumn = { MediaStore.Video.Media.DATA };
	                Cursor cursor = getContentResolver().query(selectedVideo,
	                        filePathColumn, null, null, null);
	                cursor.moveToFirst();
	                int columnIndex = cursor.getColumnIndex(filePathColumn[0]);
	                decodableString = cursor.getString(columnIndex);
	                cursor.close();
	                File file = new File(decodableString);
	                Log.i("mok","done");
	                upload(file);
	            } else 
	            {
	                Toast.makeText(this, "You haven't picked any video",
	                        Toast.LENGTH_LONG).show();
	            }
	        } catch (Exception e) 
	        {
	        	e.printStackTrace();
	            Toast.makeText(this, "Something went wrong", Toast.LENGTH_LONG)
		                    .show();
		        }
		    }
	    
	    /*
	     * UPLOAD THE SELECTED VIDEO TO THE SRVER
	     */
	    
	    public void upload(File file)
		{
			final String BASE_URL = "http://192.168.1.7/";
			Retrofit retrofit = new Builder()
			.baseUrl(BASE_URL)
			.addConverterFactory(GsonConverterFactory.create())
			.build();
			
			UploadApiService service = retrofit.create(UploadApiService.class);
			MediaType MEDIA_TYPE = MediaType.parse("video/mp4");
			Log.i("mok",MEDIA_TYPE.toString());
			RequestBody requestBody = RequestBody.create(MEDIA_TYPE, file);
			Call<ResponseBody> call = service.uploadVideo("desc", requestBody);
			call.enqueue(new Callback<ResponseBody>(){
				@Override
				public void onResponse(Response<ResponseBody> response, Retrofit retrofit) 
				{
					// TODO Auto-generated method stub
					if (response.isSuccess())
					{
						Log.i("mok","S");
						
						ResponseBody rb = response.body();
					}
					else
					{
						Log.i("mok","F");
						com.squareup.okhttp.ResponseBody rb = response.errorBody();
					}
				}
				@Override
				public void onFailure(Throwable t) 
				{
					t.printStackTrace();
					Log.i("mok",t.getCause()+"");
					Log.i("mok","T");
					finish();
				}
			});
		}
	}

**Comment by JakeWharton** [comment]
The code looks fine. What's the problem?

**Comment by mkamrani** [comment]
@JakeWharton Thank you for your really fast response. Indeed the response.isSuccess is true but no file is returned. login.php is as follows: (I have added some temporary operations just to track the results fastly)

	<?php
	ob_start();
	var_dump($_FILES);
	$result = ob_get_clean();
	$file = fopen("test.html","w");
	echo fwrite($file,$result);
	fclose($file);

	$uploaddir = '../uploads/';
	$uploadfile = $_FILES['userfile']['name'];
	$response = array();
	if (move_uploaded_file($_FILES['userfile']['tmp_name'], $uploaddir.$uploadfile)) 
	{
		$file = fopen("test1.txt","w");
		echo fwrite($file,"Hello World. Testing!");
		fclose($file);
		$response["username"] = $username;
		$response["result"] = "1";
		echo json_encode($response);
	} else 
	{
		$file = fopen("test2.txt","w");
		echo fwrite($file,"Hello World. Testing!");
		fclose($file);
		$response["result"] = "-1";
		echo json_encode($response);
	}
	?>

**Comment by JakeWharton** [comment]
Are you saying this is a bug in Retrofit? I can't see how the file would not be uploaded. You can add [OkHttp's logging interceptor][1] or use a proxy like [Charles][2] to inspect the request and ensure the file is being uploaded. Beyond that, this isn't a forum for help with configuring your server-side code for handling the upload. I would ask on StackOverflow, which it [looks like you already have done][3] (although you'll want to provide a ton more information). These issues are for tracking bugs and feature requests.

 [1]: https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor
 [2]: http://www.charlesproxy.com/
 [3]: http://stackoverflow.com/q/33723001/132047

**Comment by mkamrani** [comment]
@JackDanger I'm sorry if I have misused anything unintentionally. I really thought my code has some problem, so as you said I asked on SO too. I just saw another issue that asked for uploading images and the others helped. If you say my code is right, I'll look for other reasons.

**Comment by teohirs** [comment]
Hi, is there anyone who can help me  short terme with image upload using Retrofit 2. I looked probably every single content available on google related to that topic, but I'm still having troubles with image upload. If there is someone, I will write more details.

**Comment by Nbi007** [comment]
How do you receive it on server side using java servlets ? A link or source code will be highly appreciated.

**Comment by Nbi007** [comment]
@JakeWharton  Off topic, Hi sir i am new to programming and android developments ,been 6 months.
I heard allot about you and i see you as an inspiration to work hard. I would like to ask you to give me some tips on how to be a good developer and develop your mental logics and sharpen the brain. Your scripts are gems.
Thanks allot
nbidrees@hotmail.com

**Comment by bahintege** [comment]
How do you receive it on server side using java servlets ? A link or source code will be highly appreciated.

**Comment by swankjesse** [comment]
Please use StackOverflow for questions.

**Comment by bahintege** [comment]
How to upload a video using Retrofit 2?

**Comment by sachinletsgo** [comment]
@JakeWharton  I am not able to upload the audio file more than 6mb? Less than 6Mb is working fine. 
retrofit have size constraints?

**Comment by swankjesse** [comment]
There are no size constraints. You'll want to stream the request using RequestBody.

**Comment by sachinletsgo** [comment]
@swankjesse, Already using RequestBody. But not working for more than 6Mb file 
Please check and give me the suggestion 

    ```
HttpLoggingInterceptor logging = new HttpLoggingInterceptor();
    logging.setLevel(HttpLoggingInterceptor.Level.BASIC);
    //The logging interceptor will be added to the http client
    OkHttpClient.Builder httpClient = new OkHttpClient.Builder();
    httpClient.connectTimeout(60, TimeUnit.SECONDS);
    httpClient.readTimeout(60, TimeUnit.MINUTES);
    httpClient.writeTimeout(60, TimeUnit.MINUTES);

    httpClient.addInterceptor(logging);

    //The Retrofit builder will have the client attached, in order to get connection logs
    Retrofit retrofit = new Retrofit.Builder()
            .client(httpClient.build())
            .addConverterFactory(GsonConverterFactory.create())
            .baseUrl(appURL)
            .build();

    Interface service = retrofit.create(Interface.class);

    // use the FileUtils to get the actual file by uri
    File file = new File(path.toString());//

    // create RequestBody instance from file
    RequestBody requestFile = RequestBody
            .create(MediaType.parse("application/octet-stream"), file);

    // MultipartBody.Part is used to send also the actual file name
    MultipartBody.Part body =
            MultipartBody.Part.createFormData("voice", file.getName(), requestFile);

    // add another part within the multipart request
    RequestBody description =
            RequestBody.create(
                    MediaType.parse("application/json"),
                    jsonValue);

    // finally, execute the request
    Call<ServerResponse> call = service.upload(description, body);
```

**Comment by artem-zinnatullin** [comment]
There might be a limit on max body size on server side.

**Comment by sachinletsgo** [comment]
@artem-zinnatullin server is able to receive 50 Mb file

**Comment by swankjesse** [comment]
@sachinletsgo executable test case please.

**Comment by sachinletsgo** [comment]
@swankjesse, any 6Mb .mp3 file

**Comment by swankjesse** [comment]
Couldn't reproduce independently.

**Comment by sachinletsgo** [comment]
@JakeWharton.. I mailed you about this. need your guidance. 
Do you need parameter and API?
