### ISSUE TITLE
retrofit.RetrofitError: 401 Unauthorized access

### ISSUE THREAD

**Issue by paragones** [square/retrofit#1290]
I don't know this problem is only existing in Android because when I have tried to use the API calls using [Postman][1], it is working. Is there a reason why this isn't working in Retrofit?

My RestAdapter

     private static OkHttpClient getClient() {
        OkHttpClient client = new OkHttpClient();
        client.setConnectTimeout(3, TimeUnit.MINUTES);
        client.setReadTimeout(3, TimeUnit.MINUTES);
        return client;
    }

    public static AccountServiceMethods getWebServiceMethods() {

        final OkHttpClient okHttpClient = getClient();

        if (webServiceMethods == null){

            mExecutorService = Executors.newCachedThreadPool();

            RestAdapter restAdapter = new RestAdapter.Builder()
                    .setEndpoint(BASE_URL)
                    .setClient(new OkClient(okHttpClient))
                    .setLogLevel(RestAdapter.LogLevel.FULL)
                    .setLog(new RestAdapter.Log() {
                        @Override
                        public void log(String msg) {
                            Log.e("RestAdapter", msg);
                        }
                    })
                    .build();

            webServiceMethods = restAdapter.create(AccountServiceMethods.class);
        }

        return webServiceMethods;
    }

My Interface Methods

   

    public interface AccountServiceMethods {

    @Headers("Content-Type: application/json")
    @POST("/authorize/AcquirePublicApiToken")
    void acquirePublicApiToken(@Header("Content-Type") String contentType, @Header("Authorization") String authorization, @Body Username userName, Callback<PublicApiTokenResponse> publicApiTokenResponse);
    
    }

My Web Manager

        public void attemptLogin(String contentType, String authorizationKey, final Authorization authorization) {
        Log.e(LOG_TAG, "&&& acquirePublicApiToken &&&");
        final EventBus eventBus = EventBus.getDefault();
        final LoginChecker loginChecker = new LoginChecker();

        Username username = new Username();

        username.setUsername(authorization.getUsername());

        accountServiceMethods.acquirePublicApiToken(contentType, authorizationKey, username, new Callback<PublicApiTokenResponse>() {
            @Override
            public void success(PublicApiTokenResponse publicApiTokenResponse, Response response) {
                Log.e(LOG_TAG, "acquirePublicApiToken success");

                if (publicApiTokenResponse.getErrorList().isEmpty()) {
                    PrimeTicketRequest primeTicketRequest = new PrimeTicketRequest();
                    primeTicketRequest.setUsername(authorization.getUsername());

                    primeTicketRequest.setEncryptedToken(publicApiTokenResponse.getPublicApiToken());

                    loginChecker.setLoginStatus(LoginChecker.LoginStatus.CREDENTIALS_VERIFIED);
                    eventBus.postSticky(loginChecker);

                    acquirePrimeTicket(primeTicketRequest);
                } else {
                    loginChecker.setLoginStatus(LoginChecker.LoginStatus.MCC_FAILURE);
                    loginChecker.setErrorList(publicApiTokenResponse.getErrorList());
                    Log.e(LOG_TAG, "Code : Error 101");
                    eventBus.postSticky(loginChecker);
                }
            }

            @Override
            public void failure(RetrofitError error) {
                Log.e(LOG_TAG, "acquirePublicApiToken failure");
                Log.e(LOG_TAG, " Error : ", error);
                Log.e(LOG_TAG, " Error Response: " + error.getResponse());
                Log.e(LOG_TAG, " Error Response: " + error.getMessage());
                Log.e(LOG_TAG, " Error Status: " + error.getResponse().getStatus());
                Log.e(LOG_TAG, " Error Cause: " + error.getCause());
                loginChecker.setLoginStatus(LoginChecker.LoginStatus.SERVER_FAILURE);
                Log.e(LOG_TAG, "Code : Error 201");
                eventBus.postSticky(loginChecker);
            }
        });

    }

Here's the error message. 

    11-17 20:05:20.583    8227-8227/com.pw.mccdealsapp E/AccountWebManager﹕ Error :
    retrofit.RetrofitError: 401 Unauthorized access
            at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
            at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
            at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
            at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
            at retrofit.Platform$Android$2$1.run(Platform.java:142)
            at java.lang.Thread.run(Thread.java:856)

I hope you can help me. Thanks. 

  [1]: https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop?hl=en

**Comment by JakeWharton** [comment]
Seeing a 401 response means that the request was successfully executed and the server returned that status code. This is not a problem with Retrofit, but in whatever authentication information you are including in the request that the server expects. If it works in Postman, then somehow you are misconfiguring Retrofit or not sending the same data.

**Comment by ujwalv** [comment]
I am having the same issue @JakeWharton , header authentication and params are all correct, works in postman and other devices, except while using retrofit 2

**Comment by Longalei** [comment]
i meet the problem like you .the reason is the url is wrong. maybe you should check the url and parameter first. hope you can solve it.
没想到我遇到这个问题是url多加了一个“/”，日了狗了。

**Comment by a1018875550** [comment]
fuck dog? interesting
