### ISSUE TITLE
Custom gson adapter doesn't work

### ISSUE THREAD

**Issue by ductranit** [square/retrofit#1291]
I want to customize gson adapter with retrofit 2.0 beta 2 like this:

```javascript
Gson gson = new GsonBuilder().registerTypeAdapter( MyData.class, new MyDataDeserializer() ).create();
        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(Config.SERVER_URL)
                .addConverterFactory(GsonConverterFactory.create(gson))
                .build();
```

but the `deserialize` method isn't called:

```javascript
public class MyDataDeserializer implements JsonDeserializer<MyData> {
    @Override
    public MyData deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {
      // NOT CALLED
        JsonObject ja = json.getAsJsonObject();
        MyData data = new Gson().fromJson(ja,MyData.class);


        return data;
    }
}
```

Is there something wrong?

**Comment by JakeWharton** [comment]
Are you using `MyData` in your request or response type?

**Comment by ductranit** [comment]
MyData is a base class of all response types

**Comment by JakeWharton** [comment]
That won't work with Gson. You can try a [`TypeAdapterFactory`][1] and see if `MyData` is a parent class and return an instance of a `TypeAdapter` (a more efficient version of `JsonDeserializer`). The scope of doing this is beyond this issue and it's not even Retrofit related. I would suggest posting to StackOverflow with the 'retrofit' and 'gson' tags.

 [1]: https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/TypeAdapterFactory.html
