### ISSUE TITLE
Using a backslash in a Url or Path

### ISSUE THREAD

**Issue by alliecurry** [square/retrofit#1295]
I need to make a request to a URL with an unencoded backslash:

```GET /api/\(123)```

I've been trying to accomplish this via the ```@Url``` annotation with no luck. Every time the call is made, my "\" is replaced with a "/". For example:

````
@GET
Call<JsonObject> getAllTheThings(@Url String url);
...
String url = "/api/\\(123)";
myService.getAllTheThings(url).enqueue(...);
````

When printed to the logs, the request looks like:
```--> GET /api//(123)```

Any help would be appreciated! Thanks!

**Comment by swankjesse** [comment]
OkHttp's behavior is consistent with Chrome and Safari, and with the WHATWG’s specification.
https://github.com/w3c/web-platform-tests/blob/master/url/urltestdata.txt#L156

If you really need `\`, use `%5C`.
