### ISSUE TITLE
when i get bad request , can i get response?

### ISSUE THREAD

**Issue by DuanTzXavier** [square/retrofit#1296]
@POST("/login")
    Observable<Response> signIn(@Body SignInModel signInModel);

Retrofit mAdapter = new Retrofit.Builder()
                .client(client)
                .baseUrl(Api.BASE_URL)
                .addConverterFactory(GsonConverterFactory.create())
                .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                .build();

mApi = mAdapter.create(Api.class);

mSubscription = mApi.signIn(signInModel)
.subscribeOn(Schedulers.newThread())
                .observeOn(AndroidSchedulers.mainThread())
.subscribe(
                response -> onReceivedResponse(response),
                throwable -> manageError(throwable)
        );

I get a throwable, but I can't get message from server . how could I get Observable<Response>? help me please

**Comment by tomkoptel** [comment]
Hi @DuanTzXavier !

From yours question it is not clear what are you trying to achieve.
```java
@POST("/login")
Observable signIn(@Body SignInModel signInModel);
```
If you configure Observable to wrap your java object. For instance
```java
@POST("/login")
Observable<MyUser> signIn(@Body SignInModel signInModel);
```
Then you should process both `HttpException` and `IOException`:
```java
void manageError(Throwable error) {
 if (error instanceOf HttpException) {
  HttpException httpError = (HttpException) error;
  Response response = error.response();
  // grab data from response instance
 }
}
```
Otherwise you can have 
```java
@POST("/login")
Observable<Response<MyUser>> signIn(@Body SignInModel signInModel);
```
This nottation will pass response object to the `onNext()` callback of your Subscription.
```java
void onReceivedResponse(Response response) {
 if (response.isSuccess()) {
  // success!
 } else {
  int code = response.code();
  ResponseBody errorResponeBody = response.errorBody();
 }
}
void manageError(Throwable error) {
  // in particular case HttpException will not be passed in onError of subscription 
  if (error instanceOf IOException) {
   // network connectivity issues  
  }
}
```

**Comment by JakeWharton** [comment]
If an `Observable<Response<Foo>>` calls `onError` then there was no response from the server. The exception will either be an `IOException` indicating network problems or just a `RuntimeException` subclass indicating problems converting the request body or response body.

When the server responds successfully but with an error code (e.g., 404 Not Found), your `onNext` will be called with `isSuccess() == false` and you can check `code()`, `message()`, and `errorBody()` for information on the failure.
