### ISSUE TITLE
Problems using get method

### ISSUE THREAD

**Issue by diorslau** [square/retrofit#1297]
In the use of the get method, the default query parameters in the%22 parameters of the replacement, there is no way to replace it?
Just like this  {"isrec":true}   {%22isrec%22:true}

**Comment by JakeWharton** [comment]
Please show code demonstrating your problem. I don't understand the question.

**Comment by diorslau** [comment]
retrofit Default to use urlencode encoding, how to modify the encoding way

**Comment by JakeWharton** [comment]
Specify encoded=true on @Path or whatever annotation you are using.
