### ISSUE TITLE
How to add RequestInterceptor in Retrofit 2.0?

### ISSUE THREAD

**Issue by shehabic** [square/retrofit#1299]
How can I add request interceptor in Retrofit 2.0, I looked at OKHttp but I found that to add request interceptor I have to actually create the request myself and if I create the request and set it in OkHttp how can this be used with Retrofit?

For logging I did that:
```Java
OkHttpClient client = new OkHttpClient();
HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
interceptor.setLevel(HttpLoggingInterceptor.Level.BODY);
client.interceptors().add(interceptor);
retrofit = new Retrofit.Builder()
    .baseUrl(baseUrl)
    .addConverterFactory(GsonConverterFactory.create())
    .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
    .client(client)
    .build();
 ```
But I'm not sure how can I achieve this for the Request in order to add custom headers,

Another question (may be there's a better architecture), I have an API with 5 end-points and I have 1 abstract class where the client is built, then there are 5 different classes each one is based on 1 end-point, and they're all extending the abstract class where the client is constructed, in my old code with Retrofit 1, the abstract class had a request interceptor and is aware of the app's context, and populates the headers dynamically (which includes a checksum for the request, based on the parameters) how can I achieve this without request interceptor? and without have to repeat the headers for each end-point ?

I already looked at this: 
https://github.com/square/okhttp/wiki/Interceptors
But I don't get how can add this interceptor without creating the request, and If I created the request myself, how can I pass this to Retrofit? or what's the use of retrofit then?

**Comment by shehabic** [comment]
After a lot of trials, one thing solved my problem I didn't deep into the code, but what I add HttpLoggingInterceptor before my custom Interceptor, the custom is ignored completely, so I had to flip them, does this make any sense?

**Comment by JakeWharton** [comment]
Yes. Interceptors are ordered. An earlier one cannot see what a later one
does.

**Comment by shehabic** [comment]
ok, this makes sense then.
so the headers were being sent but it's just that the logger didn't see this?
could be also useful if you could add this hint at any point in the docs, I know it's mainly about OKHttp now, but I believe that many people using retrofit will add at least the logging Interceptor. and if it's not the last, they'd go round in circles like me.
