### ISSUE TITLE
Optional in response's errorBody

### ISSUE THREAD

**Issue by carek** [square/retrofit#1304]
Hey!

I was wondering whether it is possible for you guys to change api of response a bit so errorBody() method returns Optional<ResponseBody> instead ResponseBody. Is it doable? If you would like to have more info why I am asking about it - please look here:
http://stackoverflow.com/questions/33125190/retrofit-errorbody-should-return-optional

**Comment by swankjesse** [comment]
Optional is not available on Android. Also, optional is actually worse on Kotlin.

**Comment by carek** [comment]
eh I was afraid of it... Thanks for an answer.
