### ISSUE TITLE
Retrofit(2.0 beta2) Multipart file upload doesn't work

### ISSUE THREAD

**Issue by longtq-setacinq** [square/retrofit#1307]
please help me

**Comment by ayon115** [comment]
See #1063

**Comment by longtq-setacinq** [comment]
Hi Ayon115 i have tried like comments in pull #1063, howerver i couldn't upload file. Iam using method PUT, can you please give me another example?............It's very sad but I didn't manage to get it to work. I have rolled back to Retrofit 1.9.0 and continued to use it.

**Comment by ayon115** [comment]
Well, I haven't tried file upload with PUT request. I would suggest to use snapshot build with Logging interceptor. If you see request/response details from log and post log here, we can probably sort that out.

**Comment by longtq-setacinq** [comment]
Retrofit(2.0 beta2) seen to work as not as stable like Retrofit 1.9. Why did you delete class TypedFile?
I don't understand why, because I see that when using TypedFile  in version 1.9, it work very well? Please explain me what happened with  Retrofit(2.0 beta2).

**Comment by JakeWharton** [comment]
`TypedFile` was replaced by OkHttp's `RequestBody`. There's not only not enough information to know what you are doing to help, but this also isn't the best place to get help as it's not a support forum. Please post to StackOverflow with the 'retrofit' tag and _a lot_ more information about your interface, the calling code, what you are observing, and what you expect.

Also #1140 tracks file name inclusion on multipart part uploads.
