### ISSUE TITLE
Base url not recognized when is in directory and I don't add slash at the end

### ISSUE THREAD

**Issue by marcel-paduch** [square/retrofit#1310]
Hey,
If you cannot understand the title, here's what I mean:
```
public final class Constants {
	public static final String URL = "http://xxx.xx.xx.xx/public";
	public static final String API_DIRECTORY = "/api/";
}
```
When I use URL as argument for Retrofit's Base Url it ommits public, but when I do
```
public final class Constants {
	public static final String URL = "http://xxx.xx.xx.xx/public/";
	public static final String API_DIRECTORY = "api/";
}
```
It works just fine.

**Comment by JakeWharton** [comment]
The first example is an absolute path as it starts with a slash. It will replace "public".

The second is a relative path so it will resolve under of the "public" path segment. Also if you omit the trailing slash in this example "api" becomes a sibling of "public" and will replace it. 

So the second example is correct as-is. See the documentation on `Retrofit.Builder#baseUrl` where this behavior is described.
