### ISSUE TITLE
Call Default Type

### ISSUE THREAD

**Issue by jpshelley** [square/retrofit#1311]
Why does Call now need a type? In Retro 1.x I could easily just use the standard `Response` object. For example with API's that I don't care about converting into POJO's. It was easy and lazy.

Sorry if this was clear somewhere else, tried searching around for it to no avail. Great work so far on 2.0 to everyone thats contributing.

**Comment by JakeWharton** [comment]
You can use `ResponseBody` as that type if just want the raw contents of the response.

**Comment by jpshelley** [comment]
Thanks!
