### ISSUE TITLE
Not getting server response with Retrofit 1.9.0 in release mode .

### ISSUE THREAD

**Issue by yakubpashask** [square/retrofit#1314]
Hello,

I am trying to figure out with the issue that i am facing to get the data from the server .
My application is working good in debug mode but not in release and always get null from the server.
I don't understand what i made wrong here.

i was able to make this work once but suddenly it stopped working.

before i was not getting any warnings but i did see this today.
Warning:can't write resource [META-INF/maven/com.squareup.retrofit/retrofit/pom.properties] (Duplicate zip entry [META-INF/maven/com.squareup.retrofit/retrofit/pom.properties])
Warning:can't write resource [META-INF/maven/com.squareup.retrofit/retrofit/pom.xml] (Duplicate zip entry [META-INF/maven/com.squareup.retrofit/retrofit/pom.xml])

below is my progaurd file:

-keepattributes Exceptions,InnerClasses,Signature,Deprecated,SourceFile,LineNumberTable,*Annotation*,EnclosingMethod

-dontwarn com.google.android.gms.**
-keep class org.apache.http.** { *; }
-dontwarn org.apache.http.**
-keep class android.net.http.** { *; }
-dontwarn android.net.http.**
-dontwarn retrofit.client.OkClient
-dontwarn rx.**
-dontwarn com.github.siyamed.shapeimageview.*
-dontwarn com.parse.*
-dontwarn okio.**

-dontwarn com.squareup.okhttp.**
-keep class com.squareup.okhttp.** { *; }
-keep interface com.squareup.okhttp.** { *; }
-dontwarn org.kxml2.io.KXmlParser
-dontwarn retrofit.**
-dontwarn retrofit.appengine.UrlFetchClient
-dontwarn com.github.siyamed.shapeimageview.path.parser.SvgToPath
-keep class retrofit.** { *; }
-keepclasseswithmembers class * {
    @retrofit.http.* <methods>;
}
-keep class android.support.v4.app.** { *; }
-keep interface android.support.v4.app.** { *; }
-keep class android.support.v7.app.** { *; }
-keep interface android.support.v7.app.** { *; }
-keep class android.support.v13.app.** { *; }
-keep interface android.support.v13.app.** { *; }

Please help me.!!!

**Comment by yakubpashask** [comment]
Just an update.. I was able to get the data (enabled the log level to full ) there are 5000 key value pairs in my response and the framework struck at 259th object..
This is weird that the something is working in debug mode but not in Release but WHY?

**Comment by JakeWharton** [comment]
You haven't provided any information for anyone to be able to understand what is going on let alone to try and help in some way. Furthermore, this isn't a good forum for support. We use GitHub issues to track bugs and feature requests whereas a place like StackOverflow with the 'retrofit' tag is a much more appropriate place for asking usage questions. Please create a question there with much more detail about your usage.

Some things that would help your question get answered:
 * The interface method declaration you are calling and its annotations.
 * The configuration of the `RestAdapter`
 * An example of the data that's being sent back.
 * What shows up in logging, if anything (and perhaps try turning Retrofit's logging on).
