### ISSUE TITLE
Support for chunked transfer encoding

### ISSUE THREAD

**Issue by baev** [square/retrofit#1315]
I guess there is no way to use chunked transfer encoding. My service looks like this:

```java
public interface UploadService {

    @PUT("/upload/{id}")
    Response upload(@Path("id") long id, @Body TypedFile file);

}
```

**Comment by JakeWharton** [comment]
I think you can add `@Headers("Transfer-Encoding: chunked")` to the method and OkHttp will automatically honor the request for a chunked transfer.

**Comment by baev** [comment]
@JakeWharton thanks for the answer. But it seems it doesn't work.

I simply replace the 

```java
try (CloseableHttpClient client = HttpClients.createDefault();
     InputStream in = Files.newInputStream(file)) {
    HttpPut put = new HttpPut(ENDPOINT + "/upload/" + id);
    InputStreamEntity reqEntity = new InputStreamEntity(in);
    reqEntity.setChunked(true);
    put.setEntity(reqEntity);

    try (CloseableHttpResponse response = client.execute(put)) {
        //process response
    }
} 
```

with

```java
public interface UploadService {

    @PUT("/upload/{id}")
    @Headers({"Transfer-Encoding: chunked"})
    Response upload(@Path("id") long id, @Body TypedFile file);

}

...

UploadService service = new RestAdapter.Builder()
                .setEndpoint(ENDPOINT)
                .build()
                .create(UploadService.class);
service.upload(id, new TypedFile("application/octet-stream", file.toFile()));
```

and its fail with the following error:

`retrofit.RetrofitError: java.io.IOException: Error writing request body to server`

**Comment by JakeWharton** [comment]
What's the whole trace?

**Comment by baev** [comment]
```
Caused by: java.io.IOException: Error writing request body to server
	at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.checkError(HttpURLConnection.java:3478)
	at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.write(HttpURLConnection.java:3461)
	at retrofit.mime.TypedFile.writeTo(TypedFile.java:78)
	at retrofit.client.UrlConnectionClient.prepareRequest(UrlConnectionClient.java:66)
	at retrofit.client.UrlConnectionClient.execute(UrlConnectionClient.java:37)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:322)
	... 32 more
```

**Comment by JakeWharton** [comment]
Oh, sorry. You are using Retrofit 1.x and there's no way to do chunked that works across all of the possible HTTP clients (`HttpURLConnection` in this case).

If you add OkHttp to your app (which Retrofit 1.x will automatically pick up and use) or you migrate to the Retrofit 2 beta (which forces using OkHttp) this should work.

**Comment by baev** [comment]
@JakeWharton thanks, I'll try

**Comment by swankjesse** [comment]
It'll use chunked encoding if the file’s length is unknown when the upload starts. Otherwise it'll use content-length.

**Comment by baev** [comment]
@JakeWharton @swankjesse thanks, it works!

One more question: as far as I can see there is no way to force use chunked transfer encoding, so I need to implement my own RequestBody without content size:

```java
public static RequestBody create(final MediaType contentType, final File file) {
    if (file == null) throw new NullPointerException("content == null");

    return new RequestBody() {
        @Override
        public MediaType contentType() {
            return contentType;
        }

        @Override
        public void writeTo(BufferedSink sink) throws IOException {
            Source source = null;
            try {
                source = Okio.source(file);
                sink.writeAll(source);
            } finally {
                Util.closeQuietly(source);
            }
        }
    };
}
```

Maybe we should support chunks more obviously?

**Comment by swankjesse** [comment]
@baev why would you want to force chunked transfer encoding? It's strictly less efficient if you know the content length.

**Comment by baev** [comment]
@swankjesse in my case the server supports only chunked transfer encoding for upload method

**Comment by swankjesse** [comment]
Got it. That's a server bug. You should

**Comment by ViramP** [comment]
Hello,
For chunk,how can i specify size for chunks ?

**Comment by indradutt** [comment]
Hey Guys, I am using retrofit2 + okhttp3 3.2.0 in my android project.

I was using a delete API:

@DELETE("{id}")
Call<Void> remove(@Path(value = "id", encoded = true) String id, @Header("Authorization") String token);

I was getting 400 while I could see response received 200 using curl command. Difference b/w pass/failed request was Transfer-Encoding chunked. I am sending no body, so content-length was 0.

I just upgraded the okhttp3 to 3.8.0 and API is working just fine and req doesn't have transfer-encoding in it. 

My question

1. How to remove transfer-encoding when using retrofit2/OKHttp3
2. Was it a default value in retrofit 3.2.0?

**Comment by swankjesse** [comment]
@indradutt please ask your question on StackOverflow.
