### ISSUE TITLE
How retrofit 2.0 logger work?

### ISSUE THREAD

**Issue by Joy-Whale** [square/retrofit#1320]
In retrofit I can though RestAdapter.setLogger to log in logcat, bug  retrofit 2.0 i can't find the method, what should I do?

**Comment by Joy-Whale** [comment]
I found it

**Comment by strombringer** [comment]
In case anyone else is looking for the answer, it's now done through an OkHttp Interceptor: 
> compile 'com.squareup.okhttp:logging-interceptor:2.6.0'

http://stackoverflow.com/a/33256827/29694
