### ISSUE TITLE
Converting response.errorBody()

### ISSUE THREAD

**Issue by jemshit** [square/retrofit#1321]
Can somebody provide example of converting `response.errorBody()` to some Error class or String or JSON ? I've tried [this kind of converter](http://stackoverflow.com/q/32997062/3736955) and [this approach](http://stackoverflow.com/q/33646197/3736955), but i always get `null` ?

In my case server responds with 
```json
"Message": "Authorization has been denied for this request."
```

**Comment by jemshit** [comment]
I have found this solution, i am not sure if it good solution. It converts `errorBody` to String:
```java
BufferedReader reader = null;
StringBuilder sb = new StringBuilder();
try {
    reader = new BufferedReader(new InputStreamReader(response.errorBody().byteStream()));
    String line;
    try {
        while ((line = reader.readLine()) != null) {
            sb.append(line);
        }
    } catch (IOException e) {
        e.printStackTrace();
    }
 } catch (IOException e) {
       e.printStackTrace();
 }

String finallyError = sb.toString();
```

**Comment by jemshit** [comment]
I've managed to do this with also `Converter` now. This is error returned from server:
```json
"Message": "Authorization has been denied for this request."
```
I  have this class for modeling this error:
```java
public class ModelError {
    private String Message;

    public String getMessage() {
        return Message;
    }
    public void setMessage(String Message) {
        this.Message = Message;
    }
}
```

And this is code for getting error message from `response.errorBody()`:
```java
@Override
public void onResponse(Response<MyCustomModel> response, Retrofit retrofit) {
    if (response.errorBody() != null ) {                            
        Converter<ResponseBody, ModelError> errorConverter =
        retrofit.responseConverter(ModelError.class, new Annotation[0]);
        try {
            ModelError error = errorConverter.convert(response.errorBody());
        } catch (IOException e) {
            e.printStackTrace();
        }
        // Now use error.getMessage()
    }
    ...
}
```

**Comment by philipgiuliani** [comment]
Is there a new solution for this? The current retrofit2 snapshot does not provide `Retrofit retrofit` in the `onResponse` Callback anymore :(

**Comment by JakeWharton** [comment]
You need to pass around the Retrofit or the Converter instance yourself.

**Comment by azizbekian** [comment]
@JakeWharton , is it possible to covert to List<ErrorResponse>? I can't manage.

**Comment by JakeWharton** [comment]
```
Type listOfString = new TypeToken<List<String>>() {}.getType();
```

**Comment by meetmkjangid** [comment]
I found a better way to convert errorbody to JSONObject if you dont have time for creating ResponseError classes. Just do 
`JSONObject  jObjError = new JSONObject (response.errorBody().string())`

**Comment by mhkubaid** [comment]
How about if errorBody contains only a string?

**Comment by JakeWharton** [comment]
Just call `.string()` on it then

**Comment by rajeefmk** [comment]
@meetmkjangid Strangely, if you call `response.errorBody().string()` twice, (one inside log and one for parsing the data), the second time it returns empty.

**Comment by JakeWharton** [comment]
That's not strange, that's how a ResponseBody works. It's a resource you
read.

**Comment by rajeefmk** [comment]
Thanks @JakeWharton . My understanding was that it could be read any number of times. I guess that's not possible.

**Comment by trinadhkoya** [comment]
@philipgiuliani should i create ErrorResponse class as a POJO or POJO with Gson Annotations .

**Comment by msangel** [comment]
I am migrating from retrofit1 and missing RetrofitError is like a nightmare. 
How do I rewrite this code? 

    public static Optional <JsonObject> getErrorMessage(Throwable e){
        if(RetrofitError.class.isInstance(e)){
            RetrofitError err = RetrofitError.class.cast(e);
            Object responce = err.getBody();
            if(JsonObject.class.isInstance(responce)){
                JsonObject res = JsonObject.class.cast(responce);
                return Optional.of(res);
            } else {
                return Optional.absent();
            }
        } else {
            return Optional.absent();
        }
    }

The error API of 1st version was great.....

**Comment by maheshsuthar93** [comment]
Any one help me to how to handle this type error in retrofit??
[
  {
    "error": {
      "field": "data.first_name",
      "message": "must be first_name format"
    },
    "message": "Alphabet characters are allowed in  name."
  },
  {
    "error": {
      "field": "data.first_name",
      "message": "must be first_name format"
    },
    "message": "Alphabet characters are allowed in  name."
  }
]

**Comment by mhkubaid** [comment]
Convert `response.errorBody().string()` to an **array** of your custom model. Use Gson or any other (de)serialization library for the conversion.

Share the StackOverflow link, I will provide the sample code.

**Comment by zhchzs** [comment]
Why Call<Entity> does not work when code is 400 or more?

**Comment by zhchzs** [comment]
Why Call\<Entity\> does not work when code is 400 or more?

**Comment by zhchzs** [comment]
Why Call\<Entity\> does not work when code is non-20x?

**Comment by xenogew** [comment]
Claps for @mkjangid answer, `.string()` is make life easier.

Why don't you ask yourself, we use library to make dev life easier, but why it's not be implemented from the start or just need to **create stupid converter** to see the plain text we want in its whole context.

**Comment by mochadwi** [comment]
sometimes the server doesn't returns anything, and the `errorBody()` null or just empty, if you did this

> `JSONObject jObjError = new JSONObject (response.errorBody().string())`

it will throws: `JSONException: Value of type java.lang.String cannot be converted to JSONObject`

see answer:
1. TL;DR answer here: https://stackoverflow.com/a/10268019/3763032
2. wrap your strings with, e.g: `new JSONObject("{your string}")`

**Comment by ali0399** [comment]
> 

what is mApp?

**Comment by Juliet-Olieng** [comment]
help solve an error in this code
class LoginViewModel:ViewModel() {
    val logRepo= LoginRepository()
    val logLiveData=MutableLiveData<LoginResponse>()
    val errLiveData=MutableLiveData<String?>()

    fun loginUser(loginRequest: LoginRequest) {
        viewModelScope.launch {
            val response = logRepo.login(loginRequest)
            if (response.isSuccessful) {

            } else {
                val errorBody = response.errorBody()?.string() ?: "Unknown error" // Get the error message from the error response or use a default message if null
                errLiveData.postValue(errorBody)
            }
        }
    }


}
