### ISSUE TITLE
Multipart requests must contain at least one part

### ISSUE THREAD

**Issue by Vence** [square/retrofit#1322]
In the process of dynamic publication, the file can be attached or not, you need to upload files, then you need to add @Multipart, the case if you use the @Multipart but do not need to upload a file, how to set? set @Part ("file")  null ? this will error: Multipart requests must contain at least one part

Please take a moment to tell me , very grateful

Your fans Vence

**Comment by JakeWharton** [comment]
If the file is `null` you can skip making the API call altogether. Is that suitable?

**Comment by JakeWharton** [comment]
From RFC 1341:

> The body must then contain one or more "body parts,"

The exception you get for a zero part request comes from OkHttp anyway, so no action to take.

**Comment by oky2abbas** [comment]
+1
