### ISSUE TITLE
Issues with Image upload In Beta 2.0.0beta2

### ISSUE THREAD

**Issue by jainsanchits** [square/retrofit#1323]
Trying to upload Image File Using retrofit but Couldnt do it so i found Some work around 

For retro fit Call
@Multipart
   @POST("END_POINT OF API")
    Call<APINAME>uploadFile(@Part("xyz(Filename)\";filename=\"image.*(type of file)\" ") RequestBody xyz);

when You Call it using in your App
 RequestBody requestBody = RequestBody.create(MediaType.parse("multipart/form-data"),new FILE("path to your file"));

            Call<APINAME> fileUploadCall = App.getRestClient(context.this).getApiService().uploadfile(requestBody);
            imageUploadCall.enqueue(new Callback<APINAME>() {
                @Override
                public void onResponse(Response<APINAME> response, Retrofit retrofit) {
                    if(response.body().getSuccess())
                    {
                    }

                }

                @Override
                public void onFailure(Throwable t) {
                    try {
                        Log.e("Upload","false");
                        throw t;
                    } catch (Throwable throwable) {
                        throwable.printStackTrace();
                    }
                }
            });

**Comment by JakeWharton** [comment]
Dupe #1140
