### ISSUE TITLE
Dynamic Endpoints with Retrofit

### ISSUE THREAD

**Issue by xiaomeixw** [square/retrofit#1327]
If I have some second level domain  like this : 
http://shopping.mlm.com    
http://mei.mlm.com         
http://center.mlm.com ;

In my android project some Api'Endpoint begin with http://shopping.mlm.com ,some Api'Endpoint begin with “ http://mei.mlm.com ”. How Can I do in the application or in my interface APIService?Dynamic Endpoints with Retrofit2?

**Comment by eneim** [comment]
Create another API Adapter(s)?

**Comment by xiaomeixw** [comment]
@eneim I don't think it's a good idea.If I have 1000 API that means I need 1000  RestAdapter(Retrofit.build)...

**Comment by eneim** [comment]
Well, assume that you are using ```Retrofit 2.0```, you could create a common/shared ```Retrofit.Builder``` instance, with all shared setting accept for the ```Retrofit.Builder#baseUrl(String url)```. Then, for each endpoint, you will need to build that Builder with new baseUrl, calling ```mySharedBuilder.baseUrl(myAnotherEndpoint).build()```. This way looks like a dynamic way to do what you want. I just don't know if it's safe. But the fact that, you need to create a bunch of Retrofit objects (as many as your number of Endpoints).

**Comment by xiaomeixw** [comment]
@eneim  I have a idea ,I think like this is the best way,but need to Modify retrofit source code: 

Use @GET for example:

1.add a new params in @GET

	@Documented
	@Target(METHOD)
	@Retention(RUNTIME)
	public @interface GET {
	  //new
	  int Endpoints () default 1;   (or use enum)

	  String value() default "";
	}

2.Define three baseUrl in Retrofit.Builder

	Retrofit retrofit = new Retrofit.Builder()
	        .baseUrl("http://shopping.mlm.com") 
			.baseUrl("http://mei.mlm.com") 
			.baseUrl("http://center.mlm.com")        
	        .build();
	  
	service = retrofit.create(APIService.class);

That's means ：

http://shopping.mlm.com   this Endpoints =1 in @GET
http://mei.mlm.com this Endpoints =2 in @GET
http://center.mlm.com Endpoints =2 in @GET

(the "http://shopping.mlm.com" is the default base url.)

3.now use it in annotation APIService:

	public interface APIService {
	
		//Situation 1
		@GET("/list")
	    void loadRepo(Callback<Repo> cb);
			  
		//Situation 2
	    @GET(2,"/list")
	    void loadRepo(Callback<Repo> cb);
	
		//Situation 2
	    @GET(1,"/list")
	    void loadRepo(Callback<Repo> cb);
	  
	}


Situation 1 not has param  "int Endpoints()", so means use default url：http://shopping.mlm.com

Situation 2 has param "int Endpoints()" , so means ues Endpoints2 : http://mei.mlm.com

the Situation 3 is same with Situation 1.

That means if your want use Dynamic Endpoints ,you only add a param in @GET.It can solve the problem of create 1000 Retrofit objects.And it will  not affect the old project use Retrofit and write code easy.

**Comment by eneim** [comment]
Unfortunately your interface definition is opposed to Java's rules of method's structure: you have three methods with exactly same structure which is prohibited. You could not be able to compile your source code. So the idea of having different annotation is not usable here.

**Comment by xiaomeixw** [comment]
@eneim it just a Pseudo code , not a Real code , I just say a thinking to solve the problem of  create 1000 Retrofit objects.

**Comment by eneim** [comment]
First: You then will need to add the same thing to all other Methods which is a pain. And you will need to maintain that array of endpoints (yes, one Integer matches exactly one endpoint, and suppose you have 1000 of them). On the other hand, instead of writing redundant Retrofit creation code (which you don't want to), you need to write 1000 more methods in your interface. I don't think this is a nice trade off.

Second: you need to re-write ```Retrofit.Builder#baseUrl``` which is another pain though. Take a look at that method and see if you want to.

**Comment by xiaomeixw** [comment]
@eneim  I think my English is not good , so you mistake my word.I am sorry...

my little thought will not affect the old project use Retrofit, It just need to  add a Defined body in @GET. If your project not need Dynamic Endpoints, you not need to modify any code;

If I need Dynamic Endpoints , The thought  think you just do easy like this:

My old Project:

APIService:

	public interface APIService {
		Retrofit retrofit = new Retrofit.Builder()
	        .baseUrl("http://www.mlm.com")
	        .build();
	
		APIService service = retrofit.create(APIService.class);
	
		@POST("/list")
	    Call<Repo> loadRepo();
	}

now my project need three second level domain replace  http://www.mlm.com.

So my though just modify like this：

	public interface APIService {

		Retrofit retrofit = new Retrofit.Builder()
	        .baseUrl("http://shopping.mlm.com") 
			.baseUrl("http://mei.mlm.com") 
			.baseUrl("http://center.mlm.com")   
	        .build();
	
		APIService service = retrofit.create(APIService.class);
	
		@GET("/list")
	    Call<Repo> loadRepo();

		@GET(2,"/list")
	    Call<Repo> loadRepo();

	}

So,If you want use http://mei.mlm.com you just add a Defined body "int Endpoints ()".

	@GET(2,"/list")

and if I do not want to use "int Endpoints ()" that means I use http://shopping.mlm.com.

	@GET("/list")

I know your Worried， but I think I know which api use which url, And I must to CREATE AND MANAGE 1000 Request method in APIService and to know which API use which url。
	

	public interface APIService {

		Retrofit retrofit = new Retrofit.Builder()
	        .baseUrl("http://shopping.mlm.com") 
			.baseUrl("http://mei.mlm.com") 
			.baseUrl("http://center.mlm.com")   
	        .build();
	
		APIService service = retrofit.create(APIService.class);
	
		//http://shopping.mlm.com/register
		@GET("/register")
	    Call<Repo> register();

		//URL：http://mei.mlm.com/login
		@GET(2,"/login")
	    Call<Repo> login();

		//URL：http://mei.mlm.com/userinfo
		@GET(2,"/userinfo")
	    Call<Repo> getUserInfo();

		//URL：http://center.mlm.com/age
		@GET(3,"/age")
	    Call<Repo> setAge();

		//URL：http://shopping.mlm.com/image
		@GET("/image")
	    Call<Repo> uploadImage();


		....1000 Request method.....

	}

**Comment by xiaomeixw** [comment]
THANKS to @eneim. I know There are a lot of worries about my thought, So I think Square   maybe have a best way or thought to solve the problem.
@JakeWharton  If you see this issue  Can you help me to solve the problem......

**Comment by eneim** [comment]
I think I didn't misunderstand you. For instance, how you would do if you want to ```POST``` something?

**Comment by xiaomeixw** [comment]
If @POST it should be like this

1.the retrofit source code @POST like this:

	@Documented
	@Target(METHOD)
	@Retention(RUNTIME)
	public @interface POST {
	  //new 
	  int Endpoints () default 1;
	  
	  String value() default "";
	}


2.Modify retrofit source code to support @POST'S int Endpoints ().


3.Use it ：


	public interface APIService {
	
	
		Retrofit retrofit = new Retrofit.Builder()
		        .baseUrl("http://shopping.mlm.com") 
				.baseUrl("http://mei.mlm.com") 
				.baseUrl("http://center.mlm.com")   
		        .build();
		
		APIService service = retrofit.create(APIService.class);
	  
		//means url is : http://mei.mlm.com/list
	    @POST(2,"/list")
	    Call<Users> loadSpecialUsers();
	  
	}

**Comment by eneim** [comment]
> 1.the retrofit source code **@POST** like this ...

That's why I'm saying this
> You then will need to add the same thing to all other Methods which is a pain.

Thinking like a **library creator**, you might need to support for others thousands of people. So just modify one class doesn't make sense.

I create a Gist which adapt your requirement, I think it would help. It based on how many Base Urls you have, not how many **methods** you have. So in case you have to deal with 1000 Urls, instead of writing 1000 methods like

```
@GET(999, "/get_something")
Call<SomeThing> getSomething()
```

you just need to write another interface for your new Url.

The gist is here: ```https://gist.github.com/eneim/bfe81b4bfa87e1699077```

**Comment by xiaomeixw** [comment]
@eneim 
I see your code， and Really  understand your words, and I think your thought is a good another way to Analyse problem and give a new thinking about to solve the problem.

Thanks for your Generous thoughts and code.


But your hava one point misunderstand my words.

	@GET(999, "/get_something")
	Call<SomeThing> getSomething()

there are only there value for this :
just 1 ,2,3

the value "1" means the url is http://shopping.mlm.com

	@GET(1, "/get_something")
	Call<SomeThing> getSomething()

the value 2 means the url is http://mei.mlm.com

	@GET(2, "/get_something")
	Call<SomeThing> getSomething()
the value 3 means the url is http://center.mlm.com

	@GET(3, "/get_something")
	Call<SomeThing> getSomething()

not 4,5,6......999


the number's value is base on baseUrl's size.


 	Retrofit retrofit = new Retrofit.Builder()
            .baseUrl("http://shopping.mlm.com") 
            .baseUrl("http://mei.mlm.com") 
            .baseUrl("http://center.mlm.com")   
            .build();


there are three baseUrl,so only have 3 value and it one to one.

maybe "Endpoints ()" use "int" type Misleading your.

	public @interface GET {
	  //new
	  int Endpoints () default 1;   (or use Enum)
	
	  String value() default "";
	}


but No matter how , you give me a new thought to Analyse problem. thanks very much.

**Comment by eneim** [comment]
Oh yeah my bad. Actually I didn't mean that number ```999```. But glad you get the point.

**Comment by WesleyWu** [comment]
@xiaomeixw 
你可以给每一个 api 方法，写一个 header ，来指定用哪一个 endpoint
例如

    //http://shopping.mlm.com/register
    @GET("/register")
    Call<Repo> register();

    //URL：http://mei.mlm.com/login
    @GET("/login")
    @Headers("Endpoint-index: 2")
    Call<Repo> login();

    //URL：http://mei.mlm.com/userinfo
    @GET("/userinfo")
    @Headers("Endpoint-index: 2")
    Call<Repo> getUserInfo();

    //URL：http://center.mlm.com/age
    @GET("/age")
    @Headers("Endpoint-index: 3")
    Call<Repo> setAge();

    //URL：http://shopping.mlm.com/image
    @GET("/image")
    Call<Repo> uploadImage();

然后，写一个 OkHttp 的 Interceptor 

    import com.squareup.okhttp.Interceptor;
    import com.squareup.okhttp.Request;
    import com.squareup.okhttp.Response;
    import org.apache.commons.lang3.StringUtils;
    public class EndpointInterceptor implements Interceptor {
		@Override
		public Response intercept(Chain chain) throws IOException {
			Request request = chain.request();
			String endpointIndexHeader = request.header("Endpoint-index");
			int endpointIndex = 1;
			try {
				endpointIndex = Integer.parseInt(StringUtils.trimToEmpty(endpointIndexHeader));
			} catch (NumberFormatException e) {
				// ignore
			}
			// todo 根据 endpointIndex 拿到新的 endpoint
			String newEndpoint = "http://my.new.endpoint";
			String url = request.url().toString();
			// todo 换掉 url 中的 protocol://host:port 部分，假设这个部分长 23 个字符
			String newUrl = newEndpoint + url.substring(23);
	
			Request newRequest = request.newBuilder()
			                            .url(newUrl)
			                            .removeHeader("Endpoint-index")
			                            .build();
	
			return chain.proceed(newRequest);
		}
	}

最后要使用这个 Interceptor， 需要在 build retrofit 之前传一个加过这个 Interceptor 的 Client 进去：

	    OkHttpClient client = new OkHttpClient();
	    client.interceptors().add(new EndpointInterceptor());
	    retrofit = new Retrofit.Builder()
			    .client(client)
			    .baseUrl("http://blahblah")
			    .build();

齐活。

**Comment by xiaomeixw** [comment]
@WesleyWu I can understand chinese but I think the Foreign developers can not understand . So would you translate into English...please.Thanks.
@WesleyWu your code is  thinking use Interceptor  to solve the problem , a good idea,But every api need @Header and writer code so complexity,maybe have some performance problem.

**Comment by WesleyWu** [comment]
@xiaomeixw 我知道你是中国人在上海做美丽美app所以写中文嘛，你能懂就行。本来就是hack，用 header 的方式是目前我能想到最优雅的，你说需要 writer code 是啥意思？每个api加一个header比起去修改 GET POST 要好多了吧，也比每个 endpoint 都要写一个不同的 interface 要好多了吧，除了这个 header 不需要写其他的业务代码了，其他都是底层代码呀。

这个怎么会有性能问题呢，每次请求多干点事，20几行代码，没有干任何跟网络、数据库相关的事，纯粹查询map拼接字符串，这个绝对没有任何性能问题。

**Comment by eneim** [comment]
I think @xiaomeixw means that If you want to contribute not to only one man but to all community, please use English.

**Comment by xiaomeixw** [comment]
@WesleyWu I am sorry I was working overtime and just go home,So Reply late.
 
I understand your thought with okhttp's Interceptor to solve the problem.I said "maybe have some performance problem" is means the Retrofit is a RUNTIME ANNOTATION not a Compile ANNOTATION PROCESSING(not like ButterKnife) It use reflection and proxy TO parser ANNOTATION. 

	 public <T> T create(final Class<T> service) {
	    Utils.validateServiceInterface(service);
	    return (T) Proxy.newProxyInstance(service.getClassLoader(), new Class<?>[] { service },new InvocationHandler() {};
	  }


use two Annotations @Header and @GET it will cost a lot of time to parser ANNOTATION than one Annotation @GET.I was Worried about reflection performance.

	for (Annotation annotation : method.getAnnotations()) {
		  if (annotation instanceof GET) {
	        parseHttpMethodAndPath("GET", ((GET) annotation).value(), false);
	      } else if (annotation instanceof POST) {
	        parseHttpMethodAndPath("POST", ((POST) annotation).value(), true);
	      } else if (annotation instanceof PUT) {
	        parseHttpMethodAndPath("PUT", ((PUT) annotation).value(), true);
	      } else if (annotation instanceof Headers) {
	        String[] headersToParse = ((Headers) annotation).value();
	        if (headersToParse.length == 0) {
	          throw methodError(method, "@Headers annotation is empty.");
	        }
	        headers = parseHeaders(headersToParse);
	      } else if (annotation instanceof Multipart) {
	        if (isFormEncoded) {
	          throw methodError(method, "Only one encoding annotation is allowed.");
	        }
	        isMultipart = true;
	      } else if (annotation instanceof FormUrlEncoded) {
	        if (isMultipart) {
	          throw methodError(method, "Only one encoding annotation is allowed.");
	        }
	        isFormEncoded = true;
	      }
	}

If I have 1000 API and all use @GET method to request  ,
I only use @GET(num,"/url") that means I should run

	parseHttpMethodAndPath("GET", ((GET) annotation).value(), false);

1000 times.

But if I use two Annotations @Header and @GET that means I should run

	parseHttpMethodAndPath("GET", ((GET) annotation).value(), false);

And

	headers = parseHeaders(headersToParse);


	private com.squareup.okhttp.Headers parseHeaders(String[] headers) {
	    Headers.Builder builder = new Headers.Builder();
	    for (String header : headers) {
	      int colon = header.indexOf(':');
	      String headerName = header.substring(0, colon);
	      String headerValue = header.substring(colon + 1).trim();
	      if ("Content-Type".equalsIgnoreCase(headerName)) {
	        contentType = MediaType.parse(headerValue);
	      } else {
	        builder.add(headerName, headerValue);
	      }
	    }
	    return builder.build();
  	}

each Annotation (parser @Header and @GET )1000 times.

That was I said ： "maybe have some performance problem";

But I agree with your thoughts.In Retrofit 1.9 the retrofit use retrofit'LogLevel to get Log info.

		new RestAdapter.Builder().setLogLevel(RestAdapter.LogLevel.FULL).build()

But in Retrofit2  use okhttp's RequestInterceptor to get Log info. So I think the  Interceptor is a good idea.

	OkHttpClient client = new OkHttpClient();
	HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
	interceptor.setLevel(HttpLoggingInterceptor.Level.BODY);
	client.interceptors().add(interceptor);
	retrofit = new Retrofit.Builder()
	    .baseUrl(baseUrl)
	    .addConverterFactory(GsonConverterFactory.create())
	    .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
	    .client(client)
	    .build();

@eneim ，you and me ,just Inquiry to solve the problem by a Beautiful way.The way find Balance between simple and stability.

@eneim & @WesleyWu , I found another two ways to solve the problem： Dynamic Endpoints with Retrofit.

Option One: Use Full URL

	public interface APIService {

		@POST("http://api.nuuneoi.com/special/user/list")
	    Call<Users> loadSpecialUsers();

	    @GET("http://shopping.mlm.com/register")
	    Call<Repo> register();
	

	    @GET("http://mei.mlm.com/login")
	    Call<Repo> login();
	

	    @GET("http://mei.mlm.com/userinfo")
	    Call<Repo> getUserInfo();
	

	    @GET("http://center.mlm.com/age")
	    Call<Repo> setAge();
	
	    @GET("http://shopping.mlm.com/image")
	    Call<Repo> uploadImage();
	  
	  	.......1000 API WITH FULL URL.......
	}

BUT this way need 1000 API all Full Url ,I  think the code will  Not beautiful， because The code style smell not good；


Option Two: see this blog 

[https://medium.com/@kevintcoughlin/dynamic-endpoints-with-retrofit-a1f4229f4a8d](https://medium.com/@kevintcoughlin/dynamic-endpoints-with-retrofit-a1f4229f4a8d)

 The League of Legends API is as follows：

	public final class RiotEndpoint implements Endpoint {
	    private static final String PROTOCOL = “https://”;
	    private static final String BASE = “.api.pvp.net”;
	    private String url;
	    private String mRegion;
	    public void setRegion(String region) {
	        mRegion = region;
	        url = PROTOCOL + mRegion + BASE;
	    }
	    @Override
	    public String getName() {
	        return mRegion;
	    }
	    @Override
	    public String getUrl() {
	        if (url == null) {
	            throw new IllegalStateException(“Illegal URL.”);
	        }
	        return url;
	    }
	}


And here’s the relevant lines from my RiotClient Class：


	private static RiotEndpoint mEndpoint = new RiotEndpoint();
	...
	public static RiotService getClient(String region) {
	    mEndpoint.setRegion(region);
	    RestAdapter restAdapter = new RestAdapter.Builder()
	        .setEndpoint(mEndpoint)
	        .build();
	    return restAdapter.create(RiotService.class);
	}

This allows the caller to pass in a region string that is used to construct the correct URL prior to calling the API:

	RiotClient.getClient(region)
               .listSummonersByNames(region, name, this);



@eneim & @WesleyWu What do you think about another two Options?

**Comment by baoti** [comment]
Just split those to a few service interfaces.

```
interface MeiService {
  @GET("...")
  Call<...> listMei();
  @POST("...")
  Call<...> createMei();
  // ...
}

interface CenterService {
  @GET("...")
  Call<...> one();
  @POST("...")
  Call<...> two();
  // ...
}

interface ShoppingService {
  @GET("...")
  Call<...> one();
  @POST("...")
  Call<...> two();
  // ...
}

OkClient client = new OkClient();
MeiService meiApi = buildRetrofit(client, "http://mei.mlm.com")
    .create(MeiService.class);
CenterService centerApi = buildRetrofit(client, "http://center.mlm.com")
    .create(CenterService.class);
ShoppingService shoppingApi = buildRetrofit(client, "http://shopping.mlm.com")
    .create(ShoppingService.class);

```

**Comment by xiaomeixw** [comment]
@baoti  your had the same idea as eneim had , he is agree with split service interfaces too.

this is his code:

	 /**
	   * You have 3 base urls, so we create 3 API interface
	   */
	  private interface ShoppingApiService {
	
	    @GET("/register") Call<Object> register();
	  }
	
	  private interface MeiApiService {
	
	    @GET("/login")
	    Call<Object> login();
	  }
	
	  private interface CenterApiService {
	
	    @GET("/age")
	    Call<Object> setAge();
	  }


you can see his gist : https://gist.github.com/eneim/bfe81b4bfa87e1699077
@baoti Thanks for your  Generous thought.

**Comment by eneim** [comment]
Well this is more like a StackOverFlow question. Pardon us creators and contributors.

Well, so you mean that you prefer a way to have 10 (number of URLs) x 10 (suppose each URLs has 10 method) = 100 method definitions in ONE SINGLE Service? That will be a pain for ME to maintain instead.

In my opinion, split API services by number of URL you have is rather a good way for you to manage your code. **WHY**? By doing so, you would know where you need to modify your code if you have new method call or have problem. Otherwise, you will need to add it in to your only Big service with hundreds of lines? Numbering 10+ URLs by number will give you a bad way to control your source code --> or you need to name the indexes or else use **enum** which is not a good way bacause you can avoid it, and you should avoid using it. 

Thinking like a base activity (which is generally a not bad practice for big application): if you add a lot of code to it, make it available to do a lot of things, **after a while** you would not know what it could do totally, and you may misuse some of them. Then if you want to fix it, you don't know where to start from. Same thing here: in case your API are all set, nothing need to fix then i would be fine. But it is normal that your API would change a little bit in the future, then the pain is coming: finding your correct method in a Single 500 lines service file ... Well . On the other hand, separate your API Service to smaller ones give you a more clear vision of what is going on. I'm writing a project with only ONE Base Url, with 5 different repositories (/api/repo1, /api/repo2, etc ...), and each of them provides about 10 more methods (/api/repo1/method1 ...). I create ONE services for each repo (so 5 in total) so it's really clear to me where I need to look at if I have some problems. It works for me. Hope this help you too.

**Comment by WesleyWu** [comment]
@xiaomeixw As a 20 years java developer, I have not being worried about reflection performance since JDK5. I think reflection performance is totally a false proposition. Anyone concerns about the problem might go to do some benchmark about reflection including runtime annotation processing.

Latency of such operations should cost ~ 0.0x ms, thus should not have any impacts to your application.

**Comment by JakeWharton** [comment]
So is there any action to take here? We've covered at least two ways that Retrofit already supports your use case (separate interfaces vs. full URLs on endpoints). Unless there's a clear suggestion for a third option I don't think there's anything for us to do.

**Comment by JakeWharton** [comment]
No action to take.

**Comment by mohitfreshmenu** [comment]
which retrofit version has this change
