### ISSUE TITLE
NetworkOnMainThreadException when unsubscribing during network call

### ISSUE THREAD

**Issue by pbryn** [square/retrofit#1328]
Stack trace:

    Caused by: android.os.NetworkOnMainThreadException
    at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1273)
    at com.android.org.conscrypt.OpenSSLSocketImpl.shutdownAndFreeSslNative(OpenSSLSocketImpl.java:1126)
    at com.android.org.conscrypt.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:1121)
    at com.squareup.okhttp.Connection.closeIfOwnedBy(Connection.java:148)
    at com.squareup.okhttp.OkHttpClient$1.closeIfOwnedBy(OkHttpClient.java:75)
    at com.squareup.okhttp.internal.http.HttpConnection.closeIfOwnedBy(HttpConnection.java:137)
    at com.squareup.okhttp.internal.http.HttpTransport.disconnect(HttpTransport.java:135)
    at com.squareup.okhttp.internal.http.HttpEngine.disconnect(HttpEngine.java:573)
    at com.squareup.okhttp.Call.cancel(Call.java:122)
    at retrofit.OkHttpCall.cancel(OkHttpCall.java:162)
    at retrofit.RxJavaCallAdapterFactory$CallOnSubscribe$1.call(RxJavaCallAdapterFactory.java:102)
    at rx.subscriptions.BooleanSubscription.unsubscribe(BooleanSubscription.java:72)
    at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
    at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
    at rx.Subscriber.unsubscribe(Subscriber.java:98)
    at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
    at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
    at rx.Subscriber.unsubscribe(Subscriber.java:98)
    at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
    at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
    at rx.Subscriber.unsubscribe(Subscriber.java:98)
    at MainActivity.onCreate(MainActivity.java:63)

Code

    OkHttpClient okHttpClient = new OkHttpClient();
    if(BuildConfig.DEBUG) {
        okHttpClient.interceptors().add(new LoggingInterceptor());
    }
    okHttpClient.setSslSocketFactory(sslSocketFactory);
    okHttpClient.setReadTimeout(20000, TimeUnit.MILLISECONDS);
    okHttpClient.setConnectTimeout(20000, TimeUnit.MILLISECONDS);
    Retrofit retrofit = new Retrofit.Builder()
                           .client(client)
                           .baseUrl(httpsUrl)
                           .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                           .addConverterFactory(GsonConverterFactory.create())
                           .build(); 
    Api api = retrofit.create(Api.class);
    Subscription subscription = api.getPoiInfo("en").subscribeOn(Schedulers.io()).observeOn(AndroidSchedulers.mainThread()).subscribe(new Action1<PoiInfo[]>() {
        @Override
        public void call(PoiInfo[] poiInfos) {
       }
    });
    try{
        Thread.sleep(200);
    }catch (Exception e){
    subscription.unsubscribe();

Dependencies:

    compile 'com.squareup.okhttp:okhttp:2.5.0'
    compile 'com.squareup.retrofit:retrofit:2.0.0-beta2'
    compile 'com.squareup.retrofit:adapter-rxjava:2.0.0-beta2'
    compile 'com.squareup.retrofit:converter-gson:2.0.0-beta2'
    compile 'com.google.code.gson:gson:2.4'
    compile 'io.reactivex:rxjava:1.0.14'
    compile 'io.reactivex:rxandroid:1.0.1'

**Comment by liorzam** [comment]
Its look like that the 'STRICT MODE' is the problem...
please write which flags you turn on for StrictMode

**Comment by wKovacs64** [comment]
This is an OkHttp thing. See https://github.com/square/okhttp/issues/869 and https://github.com/square/okhttp/issues/1592. For now, use `.unsubscribeOn(Schedulers.io())` (or `Schedulers.computation()` or something).

**Comment by liorzam** [comment]
'''if(BuildConfig.DEBUG) {
    okHttpClient.interceptors().add(new LoggingInterceptor());
} 
'''

btw i still think its all about which flags you turned on
look here for 
consider to change it to 
'''
Retrofit retrofit = new Retrofit.Builder()
                       .client(client) 
                       .baseUrl(httpsUrl) 
                       .setLogLevel(LogLevel.FULL)
                       .addCallAdapterFactory(RxJavaCallAdapterFactory.create()) 
                       .addConverterFactory(GsonConverterFactory.create()) 
                       .build();  
'''

btw try to change you strict mode to:
'''
if (android.os.Build.VERSION.SDK_INT > 9) {
StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder().permitAll().build();
StrictMode.setThreadPolicy(policy); 
} 
'''

**Comment by liorzam** [comment]
Before a few days ago in 'Google Summit' discussed about security and SSL Connection,
maybe you might find that this information is essential for you:

https://www.youtube.com/watch?v=YYin_N6xXxQ
2:57:30 Keep it Secret, Keep it Safe

**Comment by JakeWharton** [comment]
This will be fixed in OkHttp 2.7. Retrofit 2 will not be released until OkHttp 2.7 is out. Tracked by #1069.

**Comment by ajdevy** [comment]
still not fixed

**Comment by ajdevy** [comment]
10-10 14:32:04.564 6843-7071/me.mint.debug D/MintFunctions: android.os.NetworkOnMainThreadException
10-10 14:32:04.564 6843-7071/me.mint.debug D/MintFunctions:     at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1273)
10-10 14:32:04.564 6843-7071/me.mint.debug D/MintFunctions:     at com.android.org.conscrypt.OpenSSLSocketImpl.shutdownAndFreeSslNative(OpenSSLSocketImpl.java:1237)
10-10 14:32:04.564 6843-7071/me.mint.debug D/MintFunctions:     at com.android.org.conscrypt.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:1232)
10-10 14:32:04.564 6843-7071/me.mint.debug D/MintFunctions:     at okhttp3.internal.Util.closeQuietly(Util.java:103)
10-10 14:32:04.564 6843-7071/me.mint.debug D/MintFunctions:     at okhttp3.internal.connection.StreamAllocation.deallocate(StreamAllocation.java:265)
10-10 14:32:04.564 6843-7071/me.mint.debug D/MintFunctions:     at okhttp3.internal.connection.StreamAllocation.streamFailed(StreamAllocation.java:312)
10-10 14:32:04.564 6843-7071/me.mint.debug D/MintFunctions:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:139)
10-10 14:32:04.564 6843-7071/me.mint.debug D/MintFunctions:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
10-10 14:32:04.564 6843-7071/me.mint.debug D/MintFunctions:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
10-10 14:32:04.564 6843-7071/me.mint.debug D/MintFunctions:     at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
10-10 14:32:04.564 6843-7071/me.mint.debug D/MintFunctions:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
10-10 14:32:04.564 6843-7071/me.mint.debug D/MintFunctions:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)

**Comment by JakeWharton** [comment]
That's not a Retrofit or OkHttp problem.

**Comment by vinisauter** [comment]
Just use RxJavaCallAdapterFactory.createAsync() which creates asynchronous observables.

```
Retrofit retrofit = new Retrofit.Builder()
                       .client(client) 
                       .baseUrl(httpsUrl) 
                       .setLogLevel(LogLevel.FULL)
                       .addCallAdapterFactory(RxJavaCallAdapterFactory.createAsync()) 
                       .addConverterFactory(GsonConverterFactory.create()) 
                       .build();  
```
