### ISSUE TITLE
Could not find class 'retrofit.RestAdapter$Builder'

### ISSUE THREAD

**Issue by sohambannerjee8** [square/retrofit#1329]
I am using Retrofit com.squareup.retrofit:retrofit:1.9.0 .It is giving me the below error
Could not find class 'retrofit.RestAdapter$Builder', referenced from RestClient.setupRestClient
11-27 03:30:50.138: E/AndroidRuntime(2926):     at .RestClient.setupRestClient(RestClient.java:32)
11-27 03:30:50.138: E/AndroidRuntime(2926):     at.RestClient.<clinit>(RestClient.java:21)

My build.gradle file

dependencies {
    compile 'com.android.support:appcompat-v7:22.2.1'
    compile files('libs/YouTubeAndroidPlayerApi.jar')
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.squareup.okhttp:okhttp:2.5.0'
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    apt 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.5.0'
    compile 'org.projectlombok:lombok:1.16.6'
    compile 'com.google.android.gms:play-services:8.1.0'
    compile 'com.android.support:cardview-v7:22.1.0'
    compile 'com.android.support:recyclerview-v7:22.1.0'
    compile files('libs/volley.jar')
    compile 'com.github.rahatarmanahmed:circularprogressview:2.4.0'
}

My Error method
private static void setupRestClient() {
  OkHttpClient OKHTTPCLIENT = new OkHttpClient();
  OKHTTPCLIENT.setReadTimeout(30 * 1000, TimeUnit.SECONDS);
  REST_CLIENT = new RestAdapter.Builder()
            .setLogLevel(RestAdapter.LogLevel.FULL)
            .setEndpoint(ROOT)
            .setClient(new OkClient(OKHTTPCLIENT)).setRequestInterceptor(new SessionRequestInterceptor())
            .setConverter(new GsonConverter(new Gson()))
            .build().create(Restapi.class);
}

Here is the stackoverflow question

http://stackoverflow.com/questions/33953353/could-not-find-class-retrofit-restadapterbuilder-retrofit

**Comment by JakeWharton** [comment]
From the SO questions it's clear you are using ProGuard and this is likely what's causing the class to be removed. Since this is a ProGuard usage question and not a Retrofit bug or feature, I'll defer to the SO answerers.

**Comment by sohambannerjee8** [comment]
@JakeWharton  I have commented there,that it's default ProGuard  file is written there.Anyway I have removed that ,and that doesn't make any changes.Still getting the same errors.

**Comment by dasdebodip07** [comment]
From the SO questions it's clear you are using ProGuard and this is likely what's causing the class to be removed. Since this is a ProGuard usage question and not a Retrofit bug or feature, I'll defer to the SO answerers.

**Comment by zhangwenshuan** [comment]
my god,on my a part of phone ,it is appear,some phone don't have the question
