### ISSUE TITLE
Using Retrofit 2 with Robospice

### ISSUE THREAD

**Issue by RezaOruji** [square/retrofit#1333]
i have used Robospice retrofit module in my projects ( retrofit 1.6.1 ) .
https://github.com/stephanenicolas/robospice/tree/release/extensions/robospice-retrofit-parent
with the new version of retrofit ( retrofit 2 )  does it make sense to use retrofit 2 with Robospice ?

**Comment by JakeWharton** [comment]
I have no idea what Robospice is or does. This seems like a question that should be asked on their issue tracker or perhaps on StackOverflow instead.
