### ISSUE TITLE
How can I get the original response returned by the server?

### ISSUE THREAD

**Issue by Calamus-Cajan** [square/retrofit#1335]
Retrofit rely OkHttp, but get less than the full ResponseBody (or a JSON data server response).
In addition, in some part of the request parameters you can not pass, but not now want to pass a: "" or Null.
These are the two problems I encountered when using Retrofit.
Please help me. thank you very much.

**Comment by JakeWharton** [comment]
The full response information is available. The `Response` type includes the status code, message, and the headers, along with the converted response body. You can also call `raw()` to get the OkHttp `Response` type which has this information (and more, such as the cache response).

I'm not sure what you asking about passing the empty string or null. Can you provide a failing test case?

**Comment by Calamus-Cajan** [comment]
Thank you.
I refer https://github.com/square/retrofit/blob/master/retrofit/src/test/java/retrofit/ToStringConverterFactory.java, customize a ConverterFactory, to solve the first problem. 
As for your second question, I have found a solution, this is not Retrofit of failure.

I kinda do not understand is why you want to re-create a NoContentResponseBody in parseResponse method OkHttpCall class, rather than a direct return rawResponse.

**Comment by JakeWharton** [comment]
Because the response body is processed by the converter. The raw response
is exhausted.

**Comment by Calamus-Cajan** [comment]
Thank you. I think I understand.
