### ISSUE TITLE
send Object of array with POST (Retrofit 2)

### ISSUE THREAD

**Issue by jemshit** [square/retrofit#1336]
Hello, a web service accepts this kind of requests below:
```
[
      {
        "BarcodeNo": "5435435",
        "ReceiverName": "Test1" 
      },
      {
        "BarcodeNo": "353534534",
        "ReceiverName": "Test2"
      }
]
```
This is POST service which requires 3 headers which is token, handshake, content-type. I can make this work with Postman on desktop, but  not with retrofit. Currently i am doing this:

```java
    @POST(MyUrl)
    Call<MyModelResponse> operationTransfer(@Header("Authorization") String token,
                                          @Header("Handshake") String handshake,
                                          @Header("Content-Type") String contentType,
                                          @Body MyModel[] requestList);
```

Above does not work, what am i doing wrong?

**Comment by jemshit** [comment]
@JakeWharton

**Comment by JakeWharton** [comment]
> Above does not work

This tells us nothing. What isn't working?

**Comment by JakeWharton** [comment]
Can you phrase your problem in the form of a failing test case?

**Comment by jemshit** [comment]
Server returns  "400 bad request".

**Comment by JakeWharton** [comment]
That's a disagreement between your configuration of Retrofit and your server's expectations. It's not a bug in Retrofit.

**Comment by jemshit** [comment]
Yes, server expects some body data like above shown, and how i tried to
implement it with retrofit. İ am asking what is wrong with my
implementation code? Can we send Object to web service with retrofit ?

**Comment by JakeWharton** [comment]
You haven't shown the implementation of `MyModel`, what serialization library is being used, or what the body that Retrofit actually sends actually looks like.

**Comment by jemshit** [comment]
MyModel:
```java
public class MyModel extends RealmObject {   
    @Expose @PrimaryKey
    private String BarcodeNo;   

    @Expose @Required
    private String ReceiverName;
}
```

Because it extends `RealmObject` i use `Converter` below:
```java
Retrofit.Builder()
                .baseUrl(ConstantsWebService.OPERATION_SERVICES_BASE_TEST)
                .client(client)
                .addConverterFactory(GsonConverterFactory.create(gson))
                .build();
```
Gson is:

```java
Gson provideGson() {
        return new GsonBuilder().setExclusionStrategies(new ExclusionStrategy() {
            @Override
            public boolean shouldSkipField(FieldAttributes f) {
                return f.getDeclaringClass().equals(RealmObject.class);
            }

            @Override
            public boolean shouldSkipClass(Class<?> clazz) {
                return false;
            }
        }).create();
    }
```

**Comment by jemshit** [comment]
How do i check *"what the body that Retrofit actually sends"* ?

**Comment by JakeWharton** [comment]
Charles Proxy, WireShark, OkHttp's logging-inteceptor, server logs, etc.
Anything that shows the raw body.

**Comment by jemshit** [comment]
```json
[
  {
    "columnInfo": {
      "BarcodeNoIndex": 0,
      "ReceiverNameIndex": 1,
      "indicesMap": {
        "BarcodeNo": 0,
        "ReceiverName": 1
      }
    }
  }
]
```

**Comment by jemshit** [comment]
I can make it work with writing another Model class without extending `RealmObject`:
```java
public class Model2 {
    @Expose
    private String BarcodeNo;
    @Expose
    private String ReceiverName;
}
```

So i think `GsonConverterFactory.create(gson)` above did not save me this time.

**Comment by JakeWharton** [comment]
Yep. Looks like a problem with Realm interacting with Gson. I'm not a Realm user, but you probably need to find a TypeAdapterFactory which adapts their object into the JSON which it logically represents.

**Comment by JakeWharton** [comment]
Maybe https://gist.github.com/cmelchior/ddac8efd018123a1e53a via https://realm.io/docs/java/latest/#gson

**Comment by baoti** [comment]
`gsonBuilder.excludeFieldsWithoutExposeAnnotation().create()` may help you.

**Comment by jemshit** [comment]
@baoti it didn't work for above request, it sends empty [{}]. 

Writing separate Model class works fine **or**  writing `Serializer` for Model seems to work too:
```java
public class MyModelSerializer implements JsonSerializer<MyModel> {
    @Override
    public JsonElement serialize(MyModelsrc, Type typeOfSrc, JsonSerializationContext context) {
        final JsonObject jsonObject = new JsonObject();
        jsonObject.addProperty("BarcodeNo", src.getBarcodeNo());
        jsonObject.addProperty("ReceiverName", src.getReceiverName());
        return jsonObject;
    }
}
```
...

```java
    Gson provideGson() {
            return new GsonBuilder().setExclusionStrategies(new ExclusionStrategy() {
                @Override
                public boolean shouldSkipField(FieldAttributes f) {
                    return f.getDeclaringClass().equals(RealmObject.class);
                }
                @Override
                public boolean shouldSkipClass(Class<?> clazz) {
                    return false;
                }
            })
            .registerTypeAdapter(MyModel.class, new MyModelSerializer())
             // OR 
             //registerTypeAdapter(Class.forName("io.realm.MyModelRealmProxy"), new MyModelSerializer())
             .create();


    }
```
