### ISSUE TITLE
How do we create ErrorHandler in retrofit 2.0.0-beta?

### ISSUE THREAD

**Issue by chonamdoo** [square/retrofit#1337]
rxjava + retrofit 1.9  
         new Action1<Throwable>() {
            @Override
            public void call(Throwable throwable) {
        
                if (throwable instanceof RetrofitError) {
                    RetrofitError e = (RetrofitError) throwable;
                    Response response = null;
                    int code = 0;
                    try {
                        response = e.getResponse();
                        code = response.getStatus();
                        LogUtils.log(new Exception(), TAG, "code:" + code);

                    } catch (Exception e1) {
                    }
                    if (response != null && response.getUrl().contains("/auth/check")) {
                        AnalyticsUtils.getInstance().sendResisterFailed(throwable.getMessage(), code);
                    }
                    if (e.getKind() == RetrofitError.Kind.NETWORK) {
                        Message msg = new Message();
                        msg.what = Constants.MSG_NETWORK_FAIL;
                        if (throwable.getCause() instanceof UnknownHostException || throwable.getCause() instanceof SSLHandshakeException) {
                            LogUtils.v("DEBUG108", "e : " + e.getUrl());
                            if (!TextUtils.isEmpty(e.getUrl())) {
                                if(Utils.isNetworkConnected(getApplication())) {
                                    AnalyticsUtils.getInstance().sendNoAddress(e.getUrl(), throwable);
                                }
                                if (e.getUrl().contains("/auth/check")) {
                                    msg.what = Constants.MSG_SERVER_UNAVAILABLE;
                                    msg.obj = dismissListener;
                                    weakHandler.sendMessage(msg);
                                }
                            }
                        } else {
                            msg.obj = dismissListener;
                            weakHandler.sendMessage(msg);
                        }
                    } else if (code != HttpStatus.HTTP_RESPONSE_UNREGIST) {
                        Message msg = new Message();
                        msg.what = Constants.MSG_SERVER_UNAVAILABLE;
                        msg.obj = dismissListener;
                        msg.arg1 = code;
                        weakHandler.sendMessage(msg);
                    }

                }
    
            }
        };
      update retrofit 2.0.0 beta  how create error handle

**Comment by Diego-Franco** [comment]
in the documentation say you can get the error from the Response object like

```
reponse.errorBody.string();
```

you can try with that, and see how works

**Comment by JakeWharton** [comment]
You can use basically the same exact code but deal with HttpException instead of the (awful) RetrofitError class from 1.x.

In general, usage questions like this should be directed to StackOverflow where general knowledge can be kept and questions can be searched for and answers improved upon over time.
