### ISSUE TITLE
Retrofit 2.0 upload pictures and string (Multipart)

### ISSUE THREAD

**Issue by Diego-Franco** [square/retrofit#1338]
Hi, i trying to make the post request with retrofit 2.0 but i can't solve

my server require this 3 variables
name (String)
picture1 (File)
picture2 (File)

i have my method for retrofit like this
```
@Multipart
@POST("users/{id}/profile.json")
Call<InfoUser> sendInfo(
@Path("id") int id, 
@Part("file\"; filename=\"image_1.jpg\" " ) RequestBody picture1, 
@Part("file\"; filename=\"image_2.jpg\" ") RequestBody picture2, 
@Part("name" ) RequestBody name, 
@Query("version") String api_version, 
@Query("token") String token);
```

and i making my RequestBody like this

```
RequestBody name = new MultipartBuilder()
                        .type(MultipartBuilder.FORM)
                        .addPart(Headers.of("Content-Disposition", "form-data; name=\"name\""), RequestBody.create(MediaType.parse("plain/text"), name))
                        .build();
RequestBody pic1 = new MultipartBuilder()
                        .type(MultipartBuilder.FORM)
                        .addPart(Headers.of("Content-Disposition", "form-data; name=\"image_1.jpg\""), RequestBody.create(MediaType.parse("image/*"), new File(pic1.filePath)))
                        .build();
RequestBody pic2 = new MultipartBuilder()
                                .type(MultipartBuilder.FORM)
                                .addPart(Headers.of("Content-Disposition", "form-data; name=\"image_2.jpg\""), RequestBody.create(MediaType.parse("image/*"), new File(pic2.filePath)))
                                .build();
```

but when i sent the request, every time i got a 500 error code from server, is a problem with the RequestBody or is for the Multipart issue with retrofit and the request?

**Comment by JakeWharton** [comment]
500 is a response from the server which means the request and response transmission were successful but the server failed in processing it. This almost always means it's a configuration problem in your setup vs. what the server expects and not a bug or problem with Retrofit itself. Consult your server team for what's going wrong, or compare the request that's sent over the wire (with a proxy like Charles or OkHttp's logging-interceptor) with one that doesn't return a 500.
