### ISSUE TITLE
Should HttpException extend RuntimeException?

### ISSUE THREAD

**Issue by kkovach** [square/retrofit#1341]
I'm currently moving from 1.9.0 to 2.0.0-beta2. I have a couple of calls that return Observables and in some spots I call toBlocking().first() on them. In 1.9.0 I was able to wrap these calls in a try and catch RettrofitError(s) to handle any HTTP errors.

Now that I've moved to 2.0.0-beta2 it appears that HttpException does not extend RuntimeException as RetrofitError did. Is there a better/different way I should be handling these errors in 2.0.0 or should HttpException extend RuntimeException rather than just Exception? Thanks.

- Kevin

**Comment by kkovach** [comment]
After some more digging this appears to be related more specifically to a 401 rather than HTTP errors in general. It appears that 401s are now handled differently than 403, 404, etc?

That said, I guess this is no longer a question about HttpException extending RuntimeException but rather why a 401 would not be resulting in a RuntimeException being thrown when .first() is called. Still digging so not sure if this has become a usage question rather than a possible issue.

**Comment by JakeWharton** [comment]
Check `isSuccess()` of the `Response` object to determine if it was a 200 or not. A 401 is a response from the server so it is encapsulated in that object. Exceptions are thrown for transport or serialization problems only.
