### ISSUE TITLE
multipart/form-data upload extra double quote and space

### ISSUE THREAD

**Issue by DeveloperXY** [square/retrofit#1344]
During my struggle to send a photo from my Android client to a PHP web server. I noticed this: 

My Upload client code:

    public interface FileUploadService {
        @Multipart
        @POST("/upload_image.php")
        Call<String> upload(
                @Part("myfile\"; filename=\"image.jpg\" ") RequestBody file,
                @Part("description") String description
        );
    }

When I retrieve the file sent on the server side, the file couldn't be saved. I debugged, found out that:

    $_FILES['myfile']['name'] == image.jpg"  + space (note the extra quote)

After changing 

    @Part("myfile\"; filename=\"image.jpg\" ")

to

    @Part("myfile\"; filename=\"image.jpg")

I was able to retrieve the correct file name.

**Comment by JakeWharton** [comment]
No action to take here. User error.

**Comment by Pranav-Mtl** [comment]
@Multipart
  @POST(ApiURL)
  ApiCallback.MyCall<BaseResponse> editOfferImage(@Part MultipartBody.Part imageFile,@Part("id") RequestBody id);

--------------------------------------------------------------

 File file = new File(imagePath);
        RequestBody requestBody = RequestBody.create(MediaType.parse("multipart/form-data"), file);
        MultipartBody.Part imageFileBody = MultipartBody.Part.createFormData("media", file.getName(), requestBody);
        RequestBody id = RequestBody.create(MediaType.parse("text/plain"),addOfferRequest.getCar_id());
        ApiCallback.MyCall<BaseResponse> myCall = apiRequest.editOfferImage(imageFileBody,id);
