### ISSUE TITLE
retrofit 2.0.0 RequestBody is not working 

### ISSUE THREAD

**Issue by chonamdoo** [square/retrofit#1345]
retrofit 1.9 working
    @POST("/v1/log")
    Observable<NewBaseData> postStatisticsData(@Body TypedString statistics_data);

      Global.getRequsetStatServer()
                        .postStatisticsData(new TypedString(requestData))
                        .subscribeOn(Schedulers.io())
                        .observeOn(Schedulers.immediate())
                        .retryWhen(new RetryWithDelay(2, 1500))
                        .subscribe(new Action1<NewBaseData>() {
                            @Override
                            public void call(NewBaseData newBaseData) {
                            }
                        }, new Action1<Throwable>() {
                            @Override
                            public void call(Throwable throwable) {
                            }
                        });

    but retrofit 2.0.0  use RequestBody 
       @POST("/v1/log")
    Observable<NewBaseData> postStatisticsData(@Body RequestBody statistics_data);
     Global.getRequsetStatServer()
                        .postStatisticsData(RequestBody.create(MediaType.parse("text/plain"),requestData))
                        .subscribeOn(Schedulers.io())
                        .observeOn(Schedulers.immediate())
                        .retryWhen(new RetryWithDelay(1, 1500))
                        .subscribe(new Action1<NewBaseData>() {
                            @Override
                            public void call(NewBaseData newBaseData) {
                               
                            }
                        }, new Action1<Throwable>() {
                            @Override
                            public void call(Throwable throwable) {
                            }
                        });
    
           404 not found error

**Comment by JakeWharton** [comment]
A 404 indicates that the URL the client is hitting is different from what the server expects and thus is a configuration problem. Ensure you have read the Javadoc of `baseUrl` and are specifying the base URL and relative URLs of the endpoints correctly.

**Comment by chonamdoo** [comment]
@JakeWharton  ok thx
