### ISSUE TITLE
Request caching and/or classes visibility and extensibility

### ISSUE THREAD

**Issue by dimitrovskif** [square/retrofit#1346]
My current requirement for my project is:
* Store cache in memory and disk
* All GET requests are served from cache immediately, and a subsequent network call is tried (if it's successful, update the app, if not - the cache is enough)

In order to achieve that I tried:
* `OkHttpClient.setCache()`
   * This approach waits for the request to fail before returning the cache
   * Offers no memory cache

* Writing a custom `Interceptor`
   * can be implemented like `internetConnected ? chain.proceed(networkReq) : chain.proceed(forcedCacheReq)` - **not** a complete solution: cannot predict the network request, won't work if server is down, etc
   * Impossible to return two responses for a single request (which is required, since you want to serve cache-based response immediately and *then* try and return a network-based response).
 
* Writing a custom `CallAdapter.Factory`
   * Requires code duplication (since `ExecutorCallAdapterFactory` is `private` and the `Utils` are too)
   * This class has a single responsibility - working with types and callbacks and doesn't (and shouldn't) offer a way to work with network

* Extending Retrofit
  * Impossible because the majority of classes are `final` and most constructors and utils are `private`

Am I missing some approach or my requirements are completely impossible to fulfill?  

It is very possible that I am wrong and overlooked a way of doing it (since caching should be performed at network layer, this may be considered an OkHttp issue), but in case I am correct, Retrofit will need to offer extendable classes and more public code (which shouldn't break encapsulation and single responsibility pattern) as well as better caching support.

**Comment by dimitrovskif** [comment]
After a careful inspection of the lifecycle of Retrofit and OkHttp, I saw that trivially implementing my requirements is impossible.

What I am doing now is really hacky but works:

```java
public class CachedClient extends OkHttpClient {
    @Override
    public Call newCall(Request request) {
        return new CachedCall(this, request);
    }

    static class CachedCall extends Call {
        OkHttpClient client;

        public CachedCall(OkHttpClient client, Request originalRequest){
            super(client, originalRequest);
            this.client = client;
        }

        @Override
        void enqueue(Callback responseCallback, boolean forWebSocket) {
            super.enqueue(responseCallback, forWebSocket);
            Request immediateReq = originalRequest.newBuilder().cacheControl(CacheControl.FORCE_CACHE).build();
            Call immediateCall = new Call(client, newReq);
            immediateCall.enqueue(responseCallback);
        }
    }
}
```

This always returns a cached response before the networked one (unless the cache is empty). However, I don't think the issue is ready to be closed because this is not the ideal solution.

**Comment by JakeWharton** [comment]
Your requirements seem to be that of an application, not an HTTP client, and thus should probably be implemented at the application layer. Both Retrofit and OkHttp are a means of making HTTP requests, and your description of requirements indicates multiple HTTP requests (to the cache and to the network) and delivering multiple responses (which neither library supports at present, see also https://github.com/square/okhttp/issues/1083).

I think this just requires you to implement something on top of Retrofit rather than inside of it.

**Comment by dimitrovskif** [comment]
@JakeWharton My problem is that once a Service is created, all the details are hidden and implementing cache is impossible.

A caching system requires getting the URL endpoints, getting the converter factory (to serialize <T> into a file for saving, and viseversa for reading). None of this is possible with the Call<T> methods generated from `Retrofit.create()`

**Comment by dimitrovskif** [comment]
@JakeWharton In addition, type erasure means I can't get `Type(T)` out of `Call<T>`. Even if I was to use reflection, I could get the `ExecutorCallbackCall` which has no type info.
