### ISSUE TITLE
how to pass image name dynamically 

### ISSUE THREAD

**Issue by HariKvana** [square/retrofit#1349]
Hi please help me out..

@Multipart
@POST("/v1/vaults/{vaultId}/blobs")
Call<String> createBlob(@Header("Authorization") String authorization, @Path("vaultId") String voltKey, @Part("file\"; filename=\"image.png\" ") RequestBody requestBody);

In this I am passing filename as image.png, But how to pass it dynamically?

**Comment by NikoYuwono** [comment]
Refer to this one [#1063]((comment) https://github.com/square/retrofit/issues/1063#issuecomment-145920568)

**Comment by JakeWharton** [comment]
Dupe of #1140.
