### ISSUE TITLE
How to send MultipartRequest with parameters with the same keys?

### ISSUE THREAD

**Issue by OleksiyDundar** [square/retrofit#1355]
I need to send a multipart request using the retrofit 2.0 with image and some key-value parameters: "key1" - "parameter1" , "key2" - "parameter2" etc. But there are parameters with the same key: "somepar[]" - "text1" , "somepar[]" - "text2" ... And i cant use @PartMap in this structure:

@Multipart
@POST(myUrlPart)
Call<ClassEntity> myRequest(@Header("Authorization") String authHeader,
                                                @Part("image\"; filename=\"image.png\"") RequestBody image,
                                                @PartMap Map<String, RequestBody> params); 
because Map<> cant store multiple values with the same key. And i cant use

@Part("somepar[]") List<String> mylist  
or
@Part("somepar[]") String[] myArray  
because it will send key-value
 "somepar[]" - "{"1","2","3"}",    not the "somepar[]" = "1" , "somepar[]" = "2" , "somepar[]" = "3".

**Comment by JakeWharton** [comment]
Fixed by #1326 which added list and array support to `@Part`.
