### ISSUE TITLE
HttpException's response().errorBody().contentLength() returns 0 incorrectly if okhttp interceptor returns recreated okhttp response.

### ISSUE THREAD

**Issue by jhavatar** [square/retrofit#1357]
My app has an okhttp application interceptor that inspects the body on a failed response to see if it includes a force update request from the server. My interceptor then returns a recreated response since the original response has been consumed. This recreated failed response is then later retrieved in Retrofit1 from a RetrofitError object to retrieve the server's error message from json.

This same flow does not work on Retrofit2. When I attempt to retrieve the response-json from the HttpException object (that replaces RetrofitError object) with httpExceptionObject.response().errorBody().string() I get the following exception: "java.io.IOException: Content-Length and stream length disagree". 

Did some investigation and found that a manual conversion of the HttpException's ResponseBody instance to String works fine -- the issue is that for some reason the ResponseBody instance's contentLength() method returns 0 incorrectly which triggers an exception in code
```
if (contentLength != -1 && contentLength != bytes.length) {
  throw new IOException("Content-Length and stream length disagree");
}
```

Any ideas why this is happening?

**Comment by JakeWharton** [comment]
How are you replacing the body? This type of bug is best expressed in the form of a failing test case or runnable piece of code.

**Comment by JakeWharton** [comment]
Since this is a usage question, lacks a test case, and is actually an OkHttp problem not a Retrofit one, I'm going to close. Feel free to comment with a test case or more info. You should also consider StackOverflow as it has a much more active community for usage questions and serves as a better place for archiving questions for future users searching for help.

If I had a guess: you're doing this work in an interceptor added to `networkInterceptors()` and not changing the `Content-Length` header value but changing the body length. You need to change both.

**Comment by jhavatar** [comment]
I created a small app to reproduce the issue and found that the culprit is actually NewRelic. Everything works fine when I remove NewRelic form the app, . 

I agree with closing this issue. I logged it with them https://discuss.newrelic.com/t/newrelic-5-3-3-cause-problems-reading-response-body-of-httpexception-from-retrofit-2-0/32359.

btw, issue occurs when I add an interceptor as basic as:
```
        client.interceptors().add(new Interceptor() {

            @Override
            public Response intercept(Chain chain) throws IOException {

                Request request = chain.request();
                Response origResponse = chain.proceed(request);

                String responseStringOrig = origResponse.body().string();
                Response response = origResponse
                        .newBuilder()
                        .body(ResponseBody.create(origResponse.body().contentType(), responseStringOrig))
                        .build();

                return response;
            }
        });
```
