### ISSUE TITLE
How to upload image

### ISSUE THREAD

**Issue by kazixma** [square/retrofit#1358]
How to upload images when image have parameter Example

@Part("img) Requestbody file

**Comment by JakeWharton** [comment]
There is not enough information here to figure out what you are asking. But, in general, usage questions should be taken to StackOverflow with the 'retrofit' tag. There are more people watching and engaging in solving usage problems there, and it also serves for a much better archive of questions for others to search and find in the future.

Make sure you provide more information about what you expect and what you are currently doing.

**Comment by kazixma** [comment]
Thankyou Sir
