### ISSUE TITLE
hope retrofit can support optional @Query parameters etc

### ISSUE THREAD

**Issue by JackCho** [square/retrofit#1360]
When I come across a request, it may ask a bunch of parameters, and some is optional. Now I must write two or more methods for request, and that's really upseting me

**Comment by raniejade** [comment]
You can use `@QueryMap`, but it currently does not support multi-values (#1324).

**Comment by JakeWharton** [comment]
Pass null and the query name and value will be omitted.

**Comment by JakeWharton** [comment]
Or use @QueryMap for a fully dynamic control over what's added.

**Comment by JackCho** [comment]
thanks, Got it.
