### ISSUE TITLE
Retrofit Json Respnse

### ISSUE THREAD

**Issue by venkatsys** [square/retrofit#1363]
Hi All,

I am getting the below json response {"data":{"date":1449750694,"home":[{"secId":"43","homePriority":"1",etc... For this above response how shall i create a model class... please help.

**Comment by JakeWharton** [comment]
Try using http://www.jsonschema2pojo.org/. Also this is a usage question for Gson and not Retrofit. In the future please direct usage questions to StackOverflow with the 'retrofit' tag (or 'gson' in this case). The community there has many more people helping answer questions and it serves as a better archive for people searching in the future.
