### ISSUE TITLE
Multi segment path replacement 

### ISSUE THREAD

**Issue by iwo** [square/retrofit#1364]
Looking at [StackOverflow](http://stackoverflow.com/questions/23833290/retrofit-path-replacements-replacement-over-whole-path-including) questions and other issues here (#1156), there is clearly a need for multi segment path replacement. The workaround used to be marking `@Path` as encoded and passing `/` inside a path argument but this is no longer supported. Using  `@Url` requires building whole url in the calling code which is a dirty workaround as well.

I see two elegant solutions to this problem:
* Add `multiSegment` param to the `@Path` annotation which will turn off the encoding of `/`
```
@GET(„/tree/element/{path}”)
Call<TreeElement> getTreeElement(@Path(„path”, multiSegment = true) String path)
```
* Accept `String` array argument for path segments and join them with `/` when constructing the final path
```
@GET(„/tree/element/{path}”)
Call<TreeElement> getTreeElement(@Path(„path”) String[] pathElements)
```

Personally I prefer the `String[] pathElements` variant.
Let me know what you think about this approach and I may submit a pull request.

**Comment by JakeWharton** [comment]
While the latter seems more correct in terms of modeling, my guess as to when people will encounter this case is in receiving a hypermedia-like string and not want to parse it themselves which lends to the former (although, one could simply call `.split("/")` for an array). Definitely needs thought. Presumably you could also pass a `List<String>` for the latter case.

> there is clearly a need

There is a _desire_ for a lot of cases that we simply cannot support in Retrofit while maintaining a small, sane, and focused API. So it's less about the fact that someone needs to use this and more about how high-leverage a feature like this would be in the API. Does it hold its weight in term so of usage and complexity to implement?

I'm not convinced that it is as this time, so this won't be in 2.0. I'll leave the issue open for post-2.0 consideration.

**Comment by jakeswenson** [comment]
I think to add to the discussion on how to make multisegment parameters easier in retrofit, i'm not a fan of the suggested solutions. 

What if instead you combine the suggestions so that it would look something like `@Path(multiSegment = true) Iterable<T> pathSegments`

This way you explicitly designate that each value you should be encoded an then joined together with `/`

Either that or using an interface to have a `pathSegments()` method so you could have a custom type, though i feel the former is more inline with the rest of retrofit.

**Comment by iwo** [comment]
@jakeswenson  what would `@Path(multiSegment = false) Iterable<T> pathSegments` mean in your solution? And which `multiSegment` parameter value would be default? Repeating `@Query` parameter doesn’t require setting additional annotation parameters.

**Comment by JakeWharton** [comment]
Fixed by 01d6fb1a133cea6fac18f2ef1ecab1cbee86b569

**Comment by a1018875550** [comment]
this issues also in version2.1;
` @Streaming
    @GET("{apkUrl}")
    Observable<ResponseBody> download(@Path(value = "apkUrl", encoded = false) String url);`

this is my code;but it's not work

**Comment by JakeWharton** [comment]
This is working as expected. Use @Url instead.
