### ISSUE TITLE
Passing Array of Objects as FormUrlEncoded Fields 

### ISSUE THREAD

**Issue by micsha123** [square/retrofit#1366]
images[0][url]=link&images[0][height]=425&images[1][url]=link&images[1][height]=425

But how we can get the same in Retrofit 2.0?

**Comment by JakeWharton** [comment]
None of those pairs have the same key so an array will not work (it re-uses the same key). You need to use a `@FieldMap` to specify those key/value pairs.

See the example here: https://github.com/square/retrofit/blob/54c011ace378429306f2cac3a24ba9212efbff93/retrofit/src/test/java/retrofit2/RequestBuilderTest.java#L1572-L1588

**Comment by micsha123** [comment]
I've made Map<String, Object> manually

    private Map<String, Object> getProducts(){
        List<CartContentDMC> products = new Select().from(CartContentDMC.class).execute();
        Map<String, Object> productMap = new LinkedHashMap<>();
        for(int j = 0; j < products.size(); j++){
            productMap.put("products[" + Integer.toString(j) + "][code]", Integer.toString(products.get(j).id));
            productMap.put("products[" + Integer.toString(j) + "][amount]", products.get(j).amount);
            productMap.put("products[" + Integer.toString(j) + "][price]", Integer.toString(products.get(j).price));
        }
        return productMap;
    }

, but in my request:

    @FormUrlEncoded
    @POST("orders.json/createOrder?")
    Call<Response> sendOrder(@Query("client_id") String id, @Query("access_token") String access_token,
                             @Query("order_id") int order_id, @Query("buyer_name") String buyer_name,
                             @Query("buyer_phone") String buyer_phone, @Query("buyer_address") String buyer_address,
                             @FieldMap Map<String, Object> products, @Query("delivery_price") int delivery_price,
                             @Query("website") String website);

and FieldMap always empty in requests.

What I'm doin' wrong?
