### ISSUE TITLE
Provide new method to get the original request from Retrofit Call proxies

### ISSUE THREAD

**Issue by vpasquier** [square/retrofit#1367]
Hi,

When using Retrofit Call proxies, it's not possible to be aware of the original request through those objects. When implementing a custom response cache (not depending on response cache of okhttp), generating a cache key with the request is necessary. However we cannot access to this original request, headers, params through Call objects (okhttpcall being final as well).

Would be nice to provide in the interface Call the method CreateRawCall already implemented in private.

**Comment by JakeWharton** [comment]
Why expose the `Call` instead of the `Request`?

**Comment by vpasquier** [comment]
To access to the original request. But dummy from my side, the original request is not public as well.

Hum. which solution would be the best? I can pull request as well okhttp. Thank you a lot for your help.

**Comment by vpasquier** [comment]
In general it would be great to have an access from the proxies to the client.

**Comment by JakeWharton** [comment]
> which solution would be the best?

I would prefer exposing the `Request` given the choice between the two, but I need to think more about the implications of exposing this.

> In general it would be great to have an access from the proxies to the client.

You can access the client by calling `client()` on the `Retrofit` instance. The same client is shared by all created proxies.

**Comment by vpasquier** [comment]
Thank you very much for your help and your response!

**Comment by JakeWharton** [comment]
The largest detractor against something like what this issue proposes is when test code (be it unit, functional, integration, or whatever) creates a fake `Call` instance. This is currently done via the `Calls` class for successful and failing responses.

What `Request` objects would be returned from these method if this proposal was accepted? We can synthesize a good portion of them. In fact, we already do so, depending on what is provided.

**Comment by dimitrovskif** [comment]
Oh, god we really need this. At the moment I am working on a caching library for Retrofit2 and unfortunately this is how I build a new Request: https://github.com/dimitrovskif/Retrofit-SmartCache/blob/master/retrofit-smartcache/src/main/java/dimitrovskif/smartcache/SmartCallFactory.java#L94

**Comment by dimitrovskif** [comment]
Still nothing?
