### ISSUE TITLE
API response as JSON

### ISSUE THREAD

**Issue by krishnameena** [square/retrofit#1368]
How  can I get API response as json object?

**Comment by JakeWharton** [comment]
Depends on the serializer you are using. Gson has `JsonObject`, Jackson has `ObjectNode`, and for Moshi you just use `Map<String, Object>`.

**Comment by JakeWharton** [comment]
In general, usage questions should be directed at StackOverflow with the 'retrofit' tag. This tracker is for bugs and feature requests. SO has a much larger community answering questions and also serves as an archive for future users searching for help.
