### ISSUE TITLE
Detect if onFailure was called because of a cancel?

### ISSUE THREAD

**Issue by philipgiuliani** [square/retrofit#1375]
In all my Fragments & Activities i do `call.cancel()` inside the `onStop` callback.
In case i modify something in the view like changing a viewFlipper or something similar, the app crashes in the `onFailure` method because the activity has been already destroyed.

So how do i detect the reason for calling `onFailure`?. Shouldn't onFailure only be called if its a real failure, like no network ect.? Are there some good examples how to structure my code with this two handlers?

**Comment by JakeWharton** [comment]
Check if `Call.isCanceled()` is true!

> Shouldn't onFailure only be called if its a real failure, like no network ect.? 

No. Always calling a callback allows resolving any in-progress UI state (like a progress dialog).

**Comment by Jayvd** [comment]
```

        call.enqueue(new Callback<APIResults>() {

            @Override
            public void onResponse(retrofit.Response<APIResults> response, Retrofit retrofit) {
                System.out.println("SUCCESS RESPONSE " + response.raw());
                }

                finished = true;
            }

            @Override
            public void onFailure(Throwable t) {
                System.out.println("******************************BAD RESPONSE******************************");
        
                if(call.isCanceled()) { //THIS LINE IS NOT RECOGNIZED BY THE COMPILER
                }
            }
        });
```

**Comment by 1f7** [comment]
> Any ideas?

of course. in beta 4:
`public void onResponse(Call<APIResults> call, Response<APIResults> response)`

`public void onFailure(Call<APIResults> call, Throwable t)`
