### ISSUE TITLE
Retrofit2 support for alternative HTTP clients?

### ISSUE THREAD

**Issue by johnrengelman** [square/retrofit#1377]
I see that v2 couples very tightly to `OkHttp`. Specifically, `Retrofit.Builder.client(OkHttpClient)` only takes an implementation of `OkHttpClient` instead of an abstract interface.

I was looking to integrate v2 support in to Ratpack and I can make it work with the `CallAdapter` except that the implementation continues to use OkHttpClient behind the scenes. While functional, I was wondering if there is a way that I could replace the underlying HTTP client with Ratpack's Netty based Http client.

Is there a way to do this (even if hacky)? Is this a feature that you would be interested in supporting?

**Comment by swankjesse** [comment]
The hacky way to do this is with an OkHttp interceptor that calls into your HttpClient instead of calling chain.proceed().

**Comment by johnrengelman** [comment]
hmmm, clever :)

**Comment by johnrengelman** [comment]
The only downside here is you still can't use this to adapt to an ansync HttpClient because the `Interceptor` interface requires a synchronous return value: `Response intercept(Chain)`

I think the place that it needs to be done is in `MethodHandler.invoke`. It currently explicitly creates a `OkHttpCall`, but if that was sometime of provider interface that I could provide my own implementation, then I can plugin in my client...

```
interface CallProvider {
  <T> Call<T> provide(Retrofit, RequestFactory, Converter<ResponseBody, T>, Object...)
}
```

Then `MethodHandler.invoke()` would be:
```
Object invoke(Object... args) {
  return callAdapter.adapt(callProvider.provide(retrofit, requestFactory, responseConverter, args));
}
```

And we'd just need a way to pass the `CallProvider` that far down.

**Comment by johnrengelman** [comment]
That or allow a `CallAdapter` to get a handle on the original Request, so it could adapt the call by doing it's own actions.

**Comment by JakeWharton** [comment]
Hmm, I probably wouldn't make this hypothetical type aware of the mechanism for creating a `Request`. Something like:
```
interface Call.Factory {
  <T> Call<T> create(Request request, Converter<ResponseBody, T> converter);
}
```

**Comment by johnrengelman** [comment]
@JakeWharton are you thinking this interface would go into the `withClient()` method in `Retrofit`?
I'd be happy to code up a PR with some direction.

**Comment by JakeWharton** [comment]
Give me a day or two to think about it? We explicitly chose not to support multiple HTTP clients, but re-using OkHttp's value types as a model for abstracting different HTTP clients is an interesting one. I need to re-frame some things in my head.

**Comment by johnrengelman** [comment]
Sure thing. I'll wait to hear back from you on here. Like I said, I don't mind doing the leg work and if you want to provide an initial path and I can code it up and we can re-work that as much as you want.

**Comment by JakeWharton** [comment]
Ok I'm thinking:
```java
abstract class Client {
  abstract <T> Call<T> newCall(Request request, Converter<ResponseBody, T> converter);
}
```
along with special treatment in the public API for taking in an `OkHttpClient` and wrapping it internally.

The abstract class buys us the ability to add a method in the future for creating a hypothetical `WebSocketCall<T>` (#924) which can default to `throw new UnsupportedOperationException();`.

**Comment by johnrengelman** [comment]
@JakeWharton in case you're curious, I finally got around to implementing this in Ratpack - https://ratpack.io/manual/1.4.0/retrofit.html#retrofit_type_safe_clients
