### ISSUE TITLE
Altering server path on runtime

### ISSUE THREAD

**Issue by AutomatedPlayground** [square/retrofit#1382]
Hello,
I'm using retrofit2. I want to alter my call path in runtime, but before initialization of library.
So, ie. we got API server:  myserver.com/api/version - so we got myserver.com/api/1 and myserver.com/api/2 . I want to be able to switch beetwen API v1 and v2 basing on some parameters.
 I tried those:
1. Extending url in retrofit builder:
```java
Retrofit mRetrofit = new Retrofit.Builder()
                .baseUrl("myserver.com/api/1")
                .client(client)
                .build();
```
This makes all requests to "myserver.com" ignoring all other parts of path.

2. Adding interceptor to okHttpClient to alter path of each request:
```java
client.interceptors().add(new Interceptor() {
            @Override
            public com.squareup.okhttp.Response intercept(@NonNull Chain chain) throws IOException {
                Request currentRequest = chain.request();
                Request.Builder builder = currentRequest.newBuilder().url(currentRequest.httpUrl().toString() + "API_VERSION");
                return chain.proceed(builder.build());
            }
        });
```
And this is causing to do calls directly to paths declared in API interface (so ie. instead of myserver.com/api/1/users it tries to call /users)

Isn't this a bug from library? Or there is other way to achieve url altering? I haven't found any information about this in docs.

Best,
Adrian

**Comment by EddieRingle** [comment]
Why not just create a new Retrofit instance?

**Comment by AutomatedPlayground** [comment]
Look at point 1 - I tried to change path to more complex but retrofit is still calling "base url" without sub dirs. Or am I doing something wrong in point 1?

**Comment by EddieRingle** [comment]
@AutomatedPlayground Ah, sorry, I misread.

Two things:
1. The URL you pass in to `baseUrl()` should end in a trailing `/`.
2. What do your service routes look like? If they contain a leading `/`, Retrofit will just use the host of the base URL and trim off any path segments you have set. Example:
```Java
// baseUrl("www.example.com/api/v1/")

@GET("foo/bar")
Call<Void> getBar();

@GET("/foo/bar")
Call<Void> getOtherBar();
```

`getBar()` will make a request to `www.example.com/api/v2/foo/bar`, while `getOtherBar()` will make a request to `www.example.com/foo/bar`.

**Comment by JakeWharton** [comment]
> I want to be able to switch beetwen API v1 and v2 basing on some parameters.

What parameters? Are you doing this for geographic proximity or maybe a simple round robin?

You can implement the `BaseUrl` interface and pass that instance to `Builder#baseUrl`. The `url()` method will be called for every request allowing different values to be specified.

> This makes all requests to "myserver.com" ignoring all other parts of path.

See the [Javadoc on `Builder#baseUrl`][1] or @EddieRingle's reply.

 [1]: https://github.com/square/retrofit/blob/b8d6b0089122769cc254f626f78fadeece968e4d/retrofit/src/main/java/retrofit2/Retrofit.java#L380-L429

**Comment by AutomatedPlayground** [comment]
@EddieRingle this was the case, thanks for your help!:)

Best,
