### ISSUE TITLE
Provide raw response from Retrofit Call proxies

### ISSUE THREAD

**Issue by vpasquier** [square/retrofit#1385]
Hello,

As I mentioned in this feature request (https://github.com/square/retrofit/issues/1367), I'm implementing a custom cache for my java client, and wanted at the end:

- The original raw request (https://github.com/square/retrofit/issues/1367)
- The raw response (pure json payload)

Because for now, the only mean I have is to caching the ResponseBody inside my custom converter registered in Retrofit client. Which is not the super best.

So if we could have those both elements, that would be the perfect proxies I've never seen:)

I'm available to do a PR. What do you think?

**Comment by JakeWharton** [comment]
> The raw response (pure json payload)

This requires buffering the entire payload in memory _before_ sending a copy of it to the converter which is an unacceptable trade-off.

**Comment by JakeWharton** [comment]
Or at the very least duplicating the buffers as they're streamed to the converter. It's hard to see how this fits into the pipeline as almost no one needs this behavior except for an extremely specific use-case.

**Comment by vpasquier** [comment]
I understand on this way but is there not another way to keep the JSON payload?

And this is not just for this specific use-case. How about debugging response?

The only way to debug the response (if for instance Jackson is not throwing an explicit exception) would be to consume ResponseBody.string() to see the JSON payload?

Thank you very much for your reactive response and help

**Comment by dimitrovskif** [comment]
Had the same problem while making a cache lib, now I am reconverting the typed response into a raw one by iterating converter factories, supplying them `T` and getting raw bytes using okio.

Here is the lib, I'm still working on the build script so you can't fetch it from any repo (and the code is still buggy)

https://github.com/dimitrovskif/SmartCache 

The first release will be probably in 2 weeks

**Comment by JakeWharton** [comment]
That depends on what debugging means here. You can install OkHttp's [logging-interceptor][1] for debug logs of the data flowing across the wire (or write your own interceptor). Otherwise you should be able to debug the data flowing through the converter using normal breakpoints and inspection of what is being parsed.

 [1]: https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor

**Comment by JakeWharton** [comment]
So you might be able to do this with a `Call.Factory` now. I don't have time to experiment, but you get access to the full `Request` and you have the ability to wrap the built-in `Call` (with a slight hoop). We can look at making this easier before 2.0 final.

**Comment by JakeWharton** [comment]
`Call.Factory` was removed and pushed down into OkHttp instead, FYI.

**Comment by vpasquier** [comment]
Thank you all of you for those informations. do you have an approximate release date for the 2.0? In all cases I will close the ticket once I could test it

**Comment by JakeWharton** [comment]
We don't have a release date, but it will be #soon. Closing since the needs seem to have been addressed. Please file a specific issue if something is lacking.
