### ISSUE TITLE
Interfaces Callbacks.

### ISSUE THREAD

**Issue by Grozny** [square/retrofit#1387]
Does retrofit support SparseArray(Android) callbacks?

**Comment by JakeWharton** [comment]
In what sense?

**Comment by NightlyNexus** [comment]
@Grozny
Is your server really returning a SparseArray structure in JSON?
Assuming you are using Gson, I don't think Gson will deserialize a `SparseArray` correctly, but you could always write a custom `TypeAdapter`.

**Comment by JakeWharton** [comment]
SparseArray is just a map with indexes whose keys are numbers. As @NightlyNexus said, you need to configure your serializer to understand the `SparseArray` type.

If you are unsure how to do this, ask a question on StackOverflow with the 'retrofit' tag and the tag of the serialization library you are using.
