### ISSUE TITLE
failure : retrofit.RetrofitError: 307 Temporary Redirect

### ISSUE THREAD

**Issue by lotfi10** [square/retrofit#1389]
I have used retrofit for networking in my project in android.I have got this Error when I make a POST request:
failure : retrofit.RetrofitError: 307 Temporary Redirect

I add to line in gradle like that:

compile 'com.squareup.retrofit:retrofit:1.9.0'
compile 'com.squareup.okhttp:okhttp:2.4.0'

How to resolve it ? I need your Help

**Comment by JakeWharton** [comment]
Dupe of https://github.com/square/okhttp/issues/2131, answered there.
