### ISSUE TITLE
`Retrofit#create()` performance

### ISSUE THREAD

**Issue by lwasylkowski** [square/retrofit#1401]
What's the performance of the `create` method? Often I see people creating service for every API call they have, or every time an activity/fragment starts. Apart from building costs (providing converter factories, adapters and so on), is there any meaningful overhead when calling `Retrofit#create(Class<T>)` so that it should be manually cached?

**Comment by JakeWharton** [comment]
The performance is fast but the expense is large. Do not create service interfaces each time you need to use them. Create them one and re-use them for the lifetime of the app. Yell at anyone who is not doing this!

**Comment by dimitrovskif** [comment]
I'd disagree that you should re-use them for the lifetime of the app (especially since any non-trivial service is going to use `Context`-dependent interceptors & factories), but definitely not more than one per Activity.

**Comment by JakeWharton** [comment]
`Application` is a `Context` and lives for the entire lifetime of the app. Use that. If you are creating instances you are wasting memory and reducing performance.

**Comment by dimitrovskif** [comment]
@JakeWharton Even the most basic app wants to close the current activity and show login when `401 Unauthorized` is returned. In those cases, having one service per activity is quite reasonable.

**Comment by JakeWharton** [comment]
That is orthogonal to your ability to re-use a service implementation.

**Comment by lwasylkowski** [comment]
@JakeWharton Thanks for the answer, the issue can be closed closed as far as I'm concerned
