### ISSUE TITLE
Change the baseUrl at runtime.

### ISSUE THREAD

**Issue by julioromano** [square/retrofit#1404]
I have a use case in which the baseUrl of the application depdends on a user setting that can be changed at runtime.

I build retrofit with:

Retrofit retrofit = Retrofit.Builder().baseUrl(baseUrl).build();
MyApi myApi = retrofit.create(MyApi.class);

Is it possible to change the baseUrl setting after this initialization without having to rebuild (and thus repropagate to all my objects) all instances of the retrofit objects?

Thanks,
Bye,
Marco

**Comment by JakeWharton** [comment]
Implement `BaseUrl` and pass that instead of a fixed URL. It will be asked for the URL for each request, allowing it to change over time.

**Comment by maoruibin** [comment]
thanks J.W, it's very useful ~  ^_^

**Comment by Zhuinden** [comment]
Has it been changed to `HttpUrl`?

**Comment by swankjesse** [comment]
Unfortunately I removed this because it’s not safe.
https://github.com/square/retrofit/pull/1652

You can workaround with this:
https://gist.github.com/swankjesse/8571a8207a5815cca1fb

**Comment by gobera** [comment]
@swankjesse Your link https://gist.github.com/swankjesse/8571a8207a5815cca1fb just contains the class HostSelectionInterceptor.java. How do i wire it up with Dagger 2, Retrofit, okHttp and Gson to make API calls to 3 different urls, with each call done in a class of it's own where i have injected a Retrofit dependecy? Please, just began using Dagger2.

**Comment by swankjesse** [comment]
I think you might make your `HostSelectionInterceptor` a singleton (`@Singleton`) and use it as an argument to your`@Provides` method when you build your `OkHttpClient`:

```
  @Provides public OkHttpClient provideOkHttpClient(
      HostSelectionInterceptor hostSelectionInterceptor) {
    return new OkHttpClient.Builder()
        .addInterceptor(hostSelectionInterceptor)
        .build();
```

**Comment by JessYanCoding** [comment]
[Let Retrofit support multiple baseUrl and can be change the baseUrl at runtime](https://github.com/JessYanCoding/RetrofitUrlManager)
