### ISSUE TITLE
Could not find method com.squareup.wire.Wire.<init>, referenced from method retrofit.WireConverterFactory.create

### ISSUE THREAD

**Issue by gauravdott** [square/retrofit#1408]
I am trying to use wire 2.0.2 with retrofit 2.0.0-beta2 and wire-converter 2.0.0 beta2 to extend enum values options.

Any help is appreciated!

**Comment by JakeWharton** [comment]
The Wire converter was upgraded to Wire 2.0 after the latest beta was released. Copy/paste the latest from `master` into your project until the next release.

**Comment by gauravdott** [comment]
Thanks @JakeWharton, I will give it a try!
