### ISSUE TITLE
Cannot find Mock classes

### ISSUE THREAD

**Issue by danielchristopher1** [square/retrofit#1411]
I added

compile 'com.squareup.retrofit:retrofit:2.0.0-beta2'

to my build.gradle and everything is working fine. However, I am not able to find any of the classes from the retrofit-mock project. How can I get those classes into my project?
Thanks.

**Comment by JakeWharton** [comment]
Add
```
compile 'com.squareup.retrofit:retrofit-mock:2.0.0-beta2'
```
