### ISSUE TITLE
Getting wrong response body while trying to download file

### ISSUE THREAD

**Issue by iAlex97** [square/retrofit#1415]
I'm using Retrofit 2.0.0-beta2 and I need to download some files from my PHP server. My first approach which worked was to directly use the GET method from its relative server path and I was getting the correct bytes.

Now I've tried something more secure that delivers the file to me based on some checks. It automatically fetches the file path from the DB and checks if the user session is correct. This works in browser tests, both Chrome PC and Chrome from Android correctly download some photos.

I'm serving the file using the X-Sendfile header like so:

header("X-Sendfile: $file_name");
header("Content-type: image/jpeg");
header('Content-Disposition: attachment; filename="' . basename($file_name) . '"');

The Android-side call looks like this:

@Streaming
@GET("/card/download")
Call<ResponseBody> getCard(@Query("filename") String filename);

**Comment by JakeWharton** [comment]
Are you sure the server is sending the right bytes? Retrofit doesn't really participate in anything that could affect this, and is unlikely to be a problem. Can you write a test case that demonstrates the problem with Retrofit?

**Comment by iAlex97** [comment]
I've fixed it a few days ago by updating the okhttp and reinstalling the mod on the server.
