### ISSUE TITLE
Url annotation and parameter type

### ISSUE THREAD

**Issue by ming13** [square/retrofit#1416]
Currently the `@Url` annotation in the second Retrofit generation only supports `String` parameters. What about `Uri` and `URI`? Even better, why not to try to call `Object#toString`?

**Comment by JakeWharton** [comment]
`String` is enforced because that's what OkHttp's `HttpUrl.resolve` method accepts. It's not clear what value supporting `Uri` or `URI` would have.

Is there any real argument for their use beyond the fact that those types exist? I'm not opposed to adding support, but I need a reason beyond just the fact that they exist.

> Even better, why not to try to call `Object#toString`?

Because people will inevitably use the wrong type and get broken behavior. Again, I would need a compelling reason to support this.

**Comment by ming13** [comment]
Well, I’m working with the API similar to GitHub API which provides URLs for access to API resources — [sample](https://developer.github.com/v3/repos/). Eventually I pass these URLs to Retrofit to fetch these resources. In the process sometimes I need to modify these URLs to change hosts, authority, that kind of thing. That’s why I have `Uri` in my models instead of traditional `String`. At this point Retrofit requires `String` as a `@Url` argument, so my every call to Retrofit-managed `*Api` instances has something like `resourceUri.toString()`.

I understand this argument is shaky and maybe not even an argument, but anyway. Actually `Uri` most likely will require Android framework dependency to be able to compile. Maybe there is some way I can avoid this kind of thing extending something? I mean infinite `resourceUri.toString()` calls.

**Comment by JakeWharton** [comment]
Makes sense. I don't think `Uri` and `URI` are unreasonable to support. Give me the day to think about it a bit and make sure I've thought through any potential problems. I'll make a PR tomorrow or later in the week, or if you or someone else wants to (with tests) feel free!

**Comment by ming13** [comment]
If it will give you headache with optional Android dependency—feel free to drop it!

Totally forgot—Picasso allows both `String` and `Uri` as resource paths. Not the same thing of course, but wanted to mention.
