### ISSUE TITLE
How to Upload Image and String together on Rails Server

### ISSUE THREAD

**Issue by avinash8989** [square/retrofit#1417]
How to Upload Image and String to Rails Server. I tried Everything. Image can be uploaded by PostMan but it was unable to upload by Httpurlconnection and Retrofit. As HttpPost is officially Deprecated by Google. I don't Want to Use. 

I Tried @Multipart with @Part but it give Unprocessable Entity 422.  I even try to upload just String with the Help of @part but the error was same. 

@Query and @QueryMap was working for me.

**Comment by JakeWharton** [comment]
Unless there's a clear problem with how Retrofit builds the request, this is a usage question and is best asked on StackOverflow with the 'retrofit' tag. There are many more active contributors on StackOverflow and it serves as a much better place for archiving questions for future search.
