### ISSUE TITLE
Need to handle HTTP response code using Rx

### ISSUE THREAD

**Issue by umesh0492** [square/retrofit#1420]
Using RxJavaCallAdapterFactory,  need to do something when server through HTTP codes between 300 - 500, individually for every possible  HTTP code. Do i have to Customize RxJavaCallAdapterFactory class or there is other way round. Looking  for docs to do so. Have to handle for every HTTP request.

**Comment by tomkoptel** [comment]
Hello, @umesh0492 !

Retrofit passes errors related to 300-500 codes inside `onNext(Response)`. You need manually check out for error within response object passed to subscription. Though, you should ought to consider case when IOException thrown, this one will be emitted to `onError(Throwable)` action.

Idea behind this approach is that all calls that received response are status agnostic, while any other exception treated as "something really bad happened in chain", so interrupt execution.

Cheers!

**Comment by umesh0492** [comment]
Hello, @tomkoptel, thanks for your response, but i am looking for a single place to handle all http response and do something in background (Like on receiving 412, clear all data over the app and move user to first screen). Rather than handling on every request's onNext.

**Comment by tomkoptel** [comment]
@umesh0492 I would consider to use okhttp interceptor for this case. So inside call chain you can capture 412 code and respond on it by muttating state of application(e.g. write to shared preference), while your UI listens to change of state and provide all necessary clean up.

As soon as ,you are in reactive approach it is common to have your UI stuff listen for changes of different sources and react on them correspondingly.

I hope it will give you a clue.

Best regards!

**Comment by umesh0492** [comment]
@tomkoptel it works , thanks for your time.
