### ISSUE TITLE
AES 256 hash become unicode after call retrofit webservice

### ISSUE THREAD

**Issue by stefanlam88** [square/retrofit#1421]
Hi guys,

Did anyone experience after POST to server API using retrofit. "==" become unicode which cause error in my logic.

Suppose: I convert gson into json string then I pass to server

Call<User> call = apiEndPoint.loginAPI(Const.SERVER_API_KEY, TimeConversion.GetUTCdatetimeAsString(), data);
        call.enqueue(new Callback<User>() {
            @Override
            public void onResponse(Response<User> response, Retrofit retrofit) {

            }

            @Override
            public void onFailure(Throwable t) {
                listener.onFailure();
            }
        });

**Comment by JakeWharton** [comment]
Equals signs are represented the same way in both ASCII and UTF-8, so I have no idea what you mean by "becomes unicode". Please provide a test case or example that demonstrates the problem.

**Comment by stefanlam88** [comment]
hi i manage to fix d. thanks.
