### ISSUE TITLE
converter-scalars is missing from central maven repository

### ISSUE THREAD

**Issue by Adrien-Martins** [square/retrofit#1438]
It seems that the scalars converter is missing from central maven repository:
http://search.maven.org/#search|ga|1|g%3A%22com.squareup.retrofit%22%20AND%20v%3A%222.0.0-beta2%22%20AND%20p%3A%22jar%22

Can you add it ?

**Comment by JakeWharton** [comment]
It was added after the last release and will be included in the next one.

**Comment by JakeWharton** [comment]
And 2.0.0-beta3 was _just_ released. Coincidental timing.
