### ISSUE TITLE
Question about custom json tag in response

### ISSUE THREAD

**Issue by stefanlam88** [square/retrofit#1441]
Hi there,

Is there anywhere I can refer or tutorial on custom response message?
Let say response might could have two types.

messsage:"" or message:{}

how do I handle in the class?

**Comment by flavienbert** [comment]
Hi,

You should wirite a custom response converter to handle both cases. 
Check this useful link: https://futurestud.io/blog/retrofit-replace-the-integrated-json-converter

**Comment by JakeWharton** [comment]
Retrofit takes no part in the deserialization of a response so if you need to handle something dynamically like that you need to look up how to do it for whatever serialization library you are using (Gson, Jackson, etc.). The above link is a good start.
