### ISSUE TITLE
Question about multi converters

### ISSUE THREAD

**Issue by CyberLiang** [square/retrofit#1444]
Hi,
I add the converters like this.
```
Retrofit client = new Retrofit.Builder()
           .baseUrl(BASE_URL)
           .client(okClient)
           .addConverterFactory(SimpleXmlConverterFactory.create())
           .addConverterFactory(GsonConverterFactory.create())
           .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
           .build();
```
But, the simplexml will parse the data first and throws a XmlPullParserException when i request a JSON data. The GsonConverter doesn't work.

**Comment by eneim** [comment]
You added the Xml Converter *Before* Gson Converter, that's why it takes the action beforehand. Swap the order and try again.

**Comment by JakeWharton** [comment]
That won't fix it. It will just behave the opposite with JSON used for
everything.

I will address this soon.

**Comment by raniejade** [comment]
You can create a converter (contains several converter) that checks for the *Content-Type*, then delegate to the proper converter.

**Comment by JakeWharton** [comment]
The converter the one who is responsible for creating the content type so
that won't work. You're on the right track, though, but you have to use
annotations on the method to chose to which you delegate.

**Comment by raniejade** [comment]
It would work for `Converter<ResponseBody, T>`, but yeah using annotations is the right direction to go.

**Comment by JakeWharton** [comment]
Oh, true! I was thinking of outgoing serialization (for the request)

**Comment by black-snow** [comment]
This is an issue for me, too. The scalar converter are pretty useless for now :(
