### ISSUE TITLE
Couldn't upload big size file in Retrofit V-1.9...

### ISSUE THREAD

**Issue by zakirhusain** [square/retrofit#1447]
Please help me, I couldn't upload more than 25 MB. Here is the exception from logcat 
W/GAv4: syncDispatchLocalHits timed out: java.util.concurrent.TimeoutException

**Comment by JakeWharton** [comment]
You need to configure the HTTP client to have larger timeouts. Retrofit sets a default of 15s.

* If you are using OkHttp you create an `OkHttpClient` which has methods to set the read, write, and connect timeout and then wrap it in an `OkClient` instance.
* If you are using `HttpURLConnection` you need to subclass `UrlConnectionClient`, override the `openConnection` method, and set your timeouts there on the `HttpURLConnection` instance.

You can then pass either the `OkClient` or the `UrlConnectionClient` to the `RestAdpater.Builder`'s `setClient` method.

**Comment by zakirhusain** [comment]
Here is my code below

private static RestAdapter.Builder builder = new RestAdapter.Builder()
            .setEndpoint(API_BASE_URL);

    public static <S> S createService(Class<S> serviceClass) {
        final OkHttpClient okHttpClient = new OkHttpClient();
        okHttpClient.setReadTimeout(1, TimeUnit.MINUTES);
        okHttpClient.setConnectTimeout(1, TimeUnit.MINUTES);
        builder.setClient(new OkClient(okHttpClient));
        RestAdapter adapter = builder.build();
        return adapter.create(serviceClass);
    }
