### ISSUE TITLE
client.interceptors Unmodifiable

### ISSUE THREAD

**Issue by killcortez** [square/retrofit#1450]
In beta2 I used client.interceptors to plug in logging to Retrofit.Builder. Since retrofit2 beta3 the list of interceptors is unmodifiable. I could work around this problem with the OkHttpClient(Builder) constructor - but this one is private. What is the preferred way to configure httpclient logging?

**Comment by JakeWharton** [comment]
You can call `newBuilder()` on `OkHttpClient`.

**Comment by killcortez** [comment]
thank you for your fast answer. It works. But the way I use it now looks not too nice - use a new client to get a builder with modifiable interceptors to build a even newer client:
``` java
OkHttpClient client = new OkHttpClient();
Builder builder = client.newBuilder;
builder.interceptors().add(logging);
OkHttpClient newClient = builder.build();
```
Do I miss something or is this the way it is supposed to be used?

**Comment by JakeWharton** [comment]
OkHttpClient client = new OkHttpClient.Builder()
    .addInterceptor(..)
    .build();
