### ISSUE TITLE
retrofit2 not on maven repo

### ISSUE THREAD

**Issue by sogwiz** [square/retrofit#1452]
Hi,

Are you sure the retrofit2 project is up on maven ?

```
<dependency>
  <groupId>com.squareup.retrofit2</groupId>
  <artifactId>retrofit</artifactId>
  <version>2.0.0-beta3</version>
</dependency>
```

Using the retrofit2 and beta3 triggers a dependency not found error

**Comment by 0xbaadf00d** [comment]
Library is online : http://mvnrepository.com/artifact/com.squareup.retrofit2/retrofit/2.0.0-beta3

**Comment by sogwiz** [comment]
you're right. sorry about this
