### ISSUE TITLE
How to get downloading progress while streaming?

### ISSUE THREAD

**Issue by geniusnut** [square/retrofit#1453]
Hi, all:
I'm a developer access retrofit about several days.
I know you should use (@Streaming) annotation to avoid OOM while downloading a file.
At the same time you hope you could get the downloading progress, I achieve that by using the ProgressResponseBody. 
The problem is when you use (@Streaming), you will not Buffer the entire body and thus my question is 
How to get the downloading progress when you use (@Streaming) at the same time.

Best Wishes.

**Comment by JakeWharton** [comment]
You can see a full working example at https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/Progress.java. Basically: count the bytes by wrapping the `Source` (or `InputStream`).

**Comment by yubaokang** [comment]
How to ensure that only initialize a OkHttpClient object?

**Comment by bbincybbaby** [comment]
can explain it ?

**Comment by g707175425** [comment]
How to ensure that only initialize a OkHttpClient object?
