### ISSUE TITLE
Deserialize Error Body

### ISSUE THREAD

**Issue by Sutirth** [square/retrofit#1454]
say for example we get {appStatusCode:118} and response code as 400 can we deserialize  to get appStatusCode as separate entity. I know error 400 means as bad request and broken. But is it possible to get something like this.

**Comment by JakeWharton** [comment]
There is a sample for this use case showing how you can lookup a converter for the desired error type and convert the error body to a Java object: https://github.com/square/retrofit/blob/be51f1d82264db1cf3ab739e91d366e5930b35fb/samples/src/main/java/com/example/retrofit/DeserializeErrorBody.java#L60-L69

**Comment by guiwro** [comment]
But in an asynchroneus call, the Retrofit instance is not exposed in the onResponse method, so how would you do it?

**Comment by JakeWharton** [comment]
The same way but with your application code passing the Retrofit instance
into the enclosing scope so that it can be referenced.

**Comment by guiwro** [comment]
Thanks.
