### ISSUE TITLE
(2.0.0-beta3) Multipart File upload doesn't work

### ISSUE THREAD

**Issue by mwojt** [square/retrofit#1455]
I am getting an issue with this code below. When uploading a file to my webservice, their body always contains two characters: `{}`. I use a gson converter. Retrofit v2.0.0-beta2 works properly.
```
@Multipart
@POST("/upload")
Call<AttachmentDto> uploadAttachment(
        @PartMap() Map<String, RequestBody> partMap,
        @Header("X-Auth-Token") String token
);
```
```
RequestBody requestBody = RequestBody.create(mediaType, file);
Map partMap = ImmutableMap.of("file\"; filename=\"" + file.getName(), requestBody);

Response<AttachmentDto> attachmentDto = webApi.uploadAttachment(partMap, token).execute();

```

**Comment by Ctrl-Space** [comment]
I also encountered this problem when I update beta2 to beta3..

    @Multipart
    @POST("AddBuyCard?" + AppConfig.SYSTEM_PARAMS)
    Call<BaseModel> addBuyCard(
            @Query("Token") String token,
            @Query("State") int State,
            @Query("Qty") int count,
            @Query("uid") String uid,
            @Query("deliver") String deliver,
            @Part("content") RequestBody body
    );   
     

    Log.e("content==>", content);
        RequestBody body = RequestBody.create(MediaType.parse("application/json"), content);
        final Call<BaseModel> call = ApiServiceFactory.getUserActionService()
                .addBuyCard(token, State, count, uid, deliver, body);

Log `content`   is all right
why webservice get the `content` is `{}`   
it work properly in beta2..

**Comment by Ctrl-Space** [comment]
oh..I find the problem
its my mistake..

I was used `com.squareup.okhttp.RequestBody`   
the correct is `okhttp3.RequestBody`   
so careless - -

**Comment by JakeWharton** [comment]
@mwojt Are you using `import okhttp3.ResponseBody`?

**Comment by mwojt** [comment]
@JakeWharton 
Like @Ctrl-Space I have used okhttp.ResponseBody instead of okhttp3.ResponseBody, so the solution is to import correct class.
Problem solved.
