### ISSUE TITLE
Add converter for scalars to response body

### ISSUE THREAD

**Issue by suren1525** [square/retrofit#1459]

**Comment by JakeWharton** [comment]
I'm not sure there's enough of a use case to warrant doing this. Why do you want it?

**Comment by connorMathews** [comment]
I made a scalar response body converter to deal with a legacy API that mixes application/json and text/plain. I'm happy to make a pull request if this is a common use case.

**Comment by suren1525** [comment]
I have exactly the same case described by @connorMathews. Also it will make the library "converter-scalars" more general. Thanks.

**Comment by JakeWharton** [comment]
You can use ResponseBody and call .string().

**Comment by suren1525** [comment]
I have also GsonConverterFactory for application/json responses:
        Retrofit.Builder builder = new Retrofit.Builder()
                .baseUrl(sServiceUrl)
                .callFactory(getOkHttpClient())
                .addConverterFactory(ScalarsConverterFactory.create())
                .addConverterFactory(GsonConverterFactory.create(gson));
And when I get a text/plain response it gets MalformedJsonException.

**Comment by JakeWharton** [comment]
Use ResponseBody for those.

**Comment by connorMathews** [comment]
Yep, a converter just moves the .string() call out of the calling code. In my case, I have endpoints that return integer item ids and others that return strings. I wanted to make the distinction explicitly in the service interface definition.

**Comment by JakeWharton** [comment]
I'm fine with the change. Feel free to make a PR, otherwise I'll get to it before 2.0 final.

**Comment by JakeWharton** [comment]
This was merged in.
