### ISSUE TITLE
Creating Login Using Retrofit 1.0

### ISSUE THREAD

**Issue by kevinjam** [square/retrofit#1460]
Hey Everyone
I m creating a login using retrofit but i can't get username and password from the database ; the backend is in php and it working fine ;
Here us My Interface Class
public interface LoginApi {

@FormUrlEncoded
    @POST("/zaala/retrofitlogin.php")
    public void getlogin(
       @Field("username") String username,
        @Field("password")String password,
        Callback<String> response

);
}
My MainActivity Class
 buttonlogin.setOnClickListener(this);

        restAdapter = new RestAdapter.Builder().setEndpoint(ROOT_LOGIN).build();
        restAdapter.setLogLevel(RestAdapter.LogLevel.FULL);
        loginApi = restAdapter.create(LoginApi.class);

    }

    @Override
    public void onClick(View v) {

   loginApi.getlogin(editTextUsername.getText().toString(), editTextPassword.getText().toString(), new Callback<String>() {
       @Override
       public void success(String s, Response response) {
           Toast.makeText(LoginActivity.this,"Logged in",Toast.LENGTH_LONG).show();
       }
       @Override
       public void failure(RetrofitError error) {
           Toast.makeText(LoginActivity.this,"Logged Failed",Toast.LENGTH_LONG).show();
//           Log.e("---Errrrorrr----", "", error);

What am i doing wrong here ???
I want if the Username and password is correct to Toast message to say "Logged In" else  "Logged Failed"

**Comment by JakeWharton** [comment]
It's unclear what you are doing wrong because there is not enough information to determine the cause of your problems. If you can write a test case that shows that this is a bug in Retrofit we can have a look, but this looks to be a usage question which mostly involves the PHP script which we don't see, but as something that doesn't have anything to do with Retrofit itself. You might want to try StackOverflow instead with the 'retrofit' tag and include more information like the request bodies and response bodies being transmitted.

**Comment by kevinjam** [comment]
Thanks ...i roger that ....i included it so
I have tried but still failing man 
What do u mean ?I just don't understand if i m doing something wrong or not .

 buttonlogin.setOnClickListener(this);
        restAdapter = new RestAdapter.Builder().setEndpoint(ROOT_LOGIN).build();
        restAdapter.setLogLevel(RestAdapter.LogLevel.FULL);
        loginApi = restAdapter.create(LoginApi.class);
    }
    @Override
    public void onClick(View v) {
   loginApi.getlogin(editTextUsername.getText().toString(), editTextPassword.getText().toString(), new Callback<String>() {
       @Override
       public void success(String s, Response response) {
           Toast.makeText(LoginActivity.this,"Logged in",Toast.LENGTH_LONG).show();
       }
       @Override
       public void failure(RetrofitError error) {
           Toast.makeText(LoginActivity.this,"Logged Failed",Toast.LENGTH_LONG).show();
       }
  Thanks
