### ISSUE TITLE
QueryMap ignores encoded = false

### ISSUE THREAD

**Issue by kevinbojarski** [square/retrofit#1461]
Using Retrofit2 beta3 and OkHttp3 RC1

`Call<Foo> getFoo(@QueryMap(encoded = false) Map<String, String> options);`
...
`Map<String, String> params = new HashMap<>();`
`params.put("bar","123+456");`
`getFoo(params);`

Expected URL: http://example.com?bar=123+456
Actual URL: http://example.com?bar=123%2B456

**Comment by NikoYuwono** [comment]
I think that is expected result when you are passing false into encoded.

Maybe you misunderstand the concept of encoded parameter, but take a look at the [code](https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit2/http/QueryMap.java). The documentation says that the encoded parameter is to tell that the QueryMap that you are passing is **already encoded or not**, not to tell that QueryMap **need to be encoded or not**.   
So if you are passing false RequestBuilder will think it's not yet encoded so it will encode the parameter.

**Comment by kevinbojarski** [comment]
Looks like I misread the documentation, and assumed it worked the same as the encodeValues() in pre-2.0 retrofit.
