### ISSUE TITLE
Class does exist

### ISSUE THREAD

**Issue by zhupengGitHub** [square/retrofit#1462]
![qq 20160112131419](https://cloud.githubusercontent.com/assets/11845222/12256929/bef8dbda-b93c-11e5-96ce-7536bd70b9e7.png)

**Comment by JakeWharton** [comment]
There is not enough information here to provide useful support. Please create StackOverlow question with the 'retrofit' tag and more information about how you are consuming the dependency, building the app, whether you are using ProGuard or other tools, etc.
