### ISSUE TITLE
Cannot connect to server when use WiFi

### ISSUE THREAD

**Issue by MycroftWong** [square/retrofit#1466]
retrofit 2.0 beta2, always throw exception: 500 server internal error, but it's ok. retrofit 2.0 beta3, sometimes can't connect to server when use WiFi (times out).  When I switch it to 4g, it becomes ok.

**Comment by JakeWharton** [comment]
Connections (and connection problems) like this are waaaay below Retrofit in the network stack and Retrofit has no control over it. Unless you can somehow boil this down into a reproducible test case demonstrating that Retrofit is the problem (or at least a ton of more information), I don't see any action to take here.
