### ISSUE TITLE
GsonConverterFactory error

### ISSUE THREAD

**Issue by SoroushDMA** [square/retrofit#1468]
I'm using Retrofit 2.0 beta 3 version and here is what I have in my gradle:

    compile 'com.squareup.retrofit2:retrofit:2.0.0-beta3'
    compile 'com.squareup.retrofit:converter-gson:2.0.0-beta2'

But I'm getting this error: 
"Error:(37, 65) error: incompatible types: GsonConverterFactory cannot be converted to Factory"
when working with RetrofitBuilder

P.S.     compile 'com.squareup.retrofit:converter-gson:2.0.0-beta3' doesn't work.

**Comment by AndrazP** [comment]
Try with:
```
compile 'com.squareup.retrofit2:retrofit:2.0.0-beta3'
compile 'com.squareup.retrofit2:converter-gson:2.0.0-beta3'
```

**Comment by SoroushDMA** [comment]
Cool, worked for me.
