### ISSUE TITLE
multiple file upload does not work

### ISSUE THREAD

**Issue by psyopussy** [square/retrofit#1469]
if i follow the docs: http://square.github.io/retrofit/2.x/retrofit/retrofit2/http/PartMap.html

it does not work,
i get a lot of gibberish on the server side and also it seems like it is only trying to upload the last image of the list of images.

if i try it like this only the last  image in the map is uploaded:

---

HashMap<String, RequestBody> partMap = new HashMap<String, RequestBody>();
partMap.put("file\"; filename=\"" + file.getName(), requestBody);
partMap.put("file\"; filename=\"" + file2.getName(), requestBody);
Call<ResponseBody> call = service.upload(partMap);

---

@Multipart
@POST("/upload")
Call<ResponseBody> upload(
    @PartMap() Map&lt;String, RequestBody&gt; partMap
);

---

**Comment by raniejade** [comment]
This might help http://stackoverflow.com/a/33477879/1425525. Not an issue, ask questions on stackoverflow with the retrofit tag.

**Comment by psyopussy** [comment]
Thank you, but that example is an example for a single image upload,
i am trying to upload multiple images at once like it is documented here:
http://square.github.io/retrofit/2.x/retrofit/retrofit2/http/PartMap.html


if that is incorrect method can you please point me to the correct documentation for uploading multiple files?

thank you very very much.

i already asked on stackexchanged but my question is stil unanswered:
http://stackoverflow.com/questions/34778224/android-retrofit-2-multiple-file-upload-howto

**Comment by rohnstock** [comment]
@psyopussy 
The solution on your link works fine!
Thank you.

**Comment by JakeWharton** [comment]
Since it's working and #1140 is tracking normal filename-based part uploading I'm closing.
