### ISSUE TITLE
Retrofit-2 adds '&' to first query parameter in GET request.

### ISSUE THREAD

**Issue by post2shyam** [square/retrofit#1470]
Retrofit-2 adds '&' to first query parameter in GET request.
eg: 
 final String BASEURL = "http://api.openweathermap.org/data/2.5/";

@GET("weather?")
getTodayWeatherByCity(@Query("q") String cityWithCountry

Following is the retrofit log generated.
GET http://api.openweathermap.org/data/2.5/weather?&q=London.

**Comment by JakeWharton** [comment]
Remove the question mark from the relative path:
```java
@GET("weather")
```

**Comment by PabiMoloi** [comment]
Removing the question mark does not help. Also stuck with the same issue.

**Comment by swankjesse** [comment]
@PabiMoloi executable test case?

**Comment by PabiMoloi** [comment]
@swankjesse Actually, I realized that having the question mark in the url still returns results. I guess my error was parsing the response correctly. The URL is `http://api.openweathermap.org/data/2.5/weather?&q=Melrose,Johannesburg&appid=APIKEY&units=metric` .
