### ISSUE TITLE
multipart partmap adds quotes to values

### ISSUE THREAD

**Issue by psyopussy** [square/retrofit#1476]
There is something really weird going on which makes my endpoint fail in beta2 AND beta 3

when using PartMap and multipart it seems that the values are quoted which causes endpoints to barf.

e.g.:

                Map<String, String> fields = new HashMap<String, String>();
                Set<String> formfieldskeys = formfields.keySet();
                for (String fkey : formfieldskeys) {
                    fields.put(fkey, formfields.get(fkey).getText().toString());
                }

    @Multipart
    @POST("/upload")
    Call<ResponseBody> upload(
            @PartMap() Map<String, String> fields

wrong received data:
    [key] => "value"

correct should look like this:
    [key] => value

is this a bug or the way retrofit works?

is there a work around?

**Comment by JakeWharton** [comment]
It's going through your JSON converter. Add the scalars converter module and add it to your `Retrofit.Builder` before the JSON conveter.

**Comment by psyopussy** [comment]
i feel a bit silly asking this but i cant find the package:

compile 'com.squareup.retrofit:converter-scalars:2.0.0-beta3'

how can i find this?

thx.

**Comment by psyopussy** [comment]
@JakeWharton 
is converter-scalars even supposed to be a retrofit package?

**Comment by JakeWharton** [comment]
The groupId is "com.squareup.retrofit3" for it (and all others)

**Comment by psyopussy** [comment]
@JakeWharton 
that does not seem to exist:
https://repo1.maven.org/maven2/com/squareup/retrofit3/retrofit-converters/2.0.0-beta3/

however, these do exist: 
https://repo1.maven.org/maven2/com/squareup/retrofit/retrofit-converters/2.0.0-beta3/
https://repo1.maven.org/maven2/com/squareup/retrofit2/retrofit-converters/2.0.0-beta3/

but i have no cue what the difference is between those.

**Comment by JakeWharton** [comment]
http://repo1.maven.org/maven2/com/squareup/retrofit2/converter-scalars/2.0.0-beta3/

**Comment by psyopussy** [comment]
@JakeWharton 
forgive my ignorance but i am quit new to android and retrofit,

your remark made me aware of something,
i was under the impression that i was actually using retrofit 2 but it seems in my gradle file i have a few discrepanties:

    compile 'com.squareup.retrofit:retrofit:2.0.0-beta2'
    compile 'com.squareup.retrofit2:retrofit:2.0.0-beta2'

what is the difference between those versions? 
they both say 2.0.0-beta2 but somehow they are not.

if i change my import from 
import retrofit.Retrofit;
to
import retrofit2.Retrofit;

everything seems to break?
