### ISSUE TITLE
Call<String> with @Body

### ISSUE THREAD

**Issue by rudsonlive** [square/retrofit#1477]
I created my load interface as a post and pass as parameter oneBody object.
To work well I added the .addConverterFactory (GsonConverterFactory.create ()).
But I want my call to be a String as JSON api returns that was not very well structured.
How can I do that?
Thanks,

My interface
    public interface LoadMapeamento{
        @Headers("Content-Type: application/json")
        @POST("/vs3/mobile/" + Constants.URL_API_METHOD_MAPEAMENTO)
        Call<String> mapeamento(@Body BeneBody beneBody);
    }

**Comment by JakeWharton** [comment]
Use `Call<ResponseBody>` and call `.string()`. There's already an issue for adding response body support to the scalars converter which will support the `Call<String>` use case. See #1459.

**Comment by rudsonlive** [comment]
Excellent, works 100%
Thank you so much.
