### ISSUE TITLE
Is there an EncodedQuery annotation equivalent in retrofit 2?

### ISSUE THREAD

**Issue by tc** [square/retrofit#1479]
In retrofit 1.9, there was an EncodedQuery which lets you do:

```
        @EncodedQuery("foo[]") List<String> foos
```
to
```
foo[]=x,foo[]=y
```

see https://github.com/square/retrofit/issues/472

I no longer see EncodedQuery in the 2.0 beta codebase.

**Comment by JakeWharton** [comment]
You can use `@Query(encoded = true)`

**Comment by dawidhyzy** [comment]
I'm trying to do the same with @QueryMap:
@QueryMap(encoded = true) Map<String, List<String>> foo,
but result is:
foo[]=[x,%20y]
any clue?
