### ISSUE TITLE
Parallel HTTP requests

### ISSUE THREAD

**Issue by Grozny** [square/retrofit#1480]
I have multiple http request. How can i handler when all request was finished? 
There is any way to retrofit handle it?

**Comment by JakeWharton** [comment]
Retrofit does not offer anything like this.

You can do this yourself by keeping a counter of in-flight requests and decrementing it when one of the `Callback` methods are invoked (I'm assuming you are using asynchronous requests). If you are using RxJava it has operators like `zip` for waiting for responses from multiple observables.
