### ISSUE TITLE
Regarding Multiple request

### ISSUE THREAD

**Issue by antoniomerlin** [square/retrofit#1481]
Hey there,
I want to send multiple request is their any way to retrofit for handling this on different thread and also i want to know if is their any way i can get raw JSON from response.

**Comment by JakeWharton** [comment]
> handling this on different thread

Use `Call.enqueue` which runs the request asynchronously on a background thread pool.

> raw JSON from response

Declare the method result as `Call<ResponseBody>`. You can then call `.string()` or `.bytes()` or `.byteStream()` to read the raw JSON.

**Comment by antoniomerlin** [comment]
thanks it solved my issue.
