### ISSUE TITLE
How to diffrenciate between calls in interceptor

### ISSUE THREAD

**Issue by danvinokour** [square/retrofit#1496]
I have a logging interceptor in which i want to print the request and response bodies of certain calls.
is it possible to add access to call annotations so i could give certain request custom "PrintBody" annotation?

Maybe there is another good way to diffrenciate between requests?

**Comment by danh32** [comment]
Jesse Wilson just wrote a post on a nifty way to do something like this: https://publicobject.com/2016/01/17/sneaking-data-into-an-okhttp-interceptor/

You could add a "print-body" header to the requests that you want. Check for that header in your interceptor and print your body accordingly.

**Comment by JakeWharton** [comment]
Beat me to that comment and link!

That said, I'm going to consider something that lets you modify the raw `Request` and `OkHttpClient` based on annotations on the method in the coming week or two. No promises though. The synthetic header is the solution for now.

```java
@Headers("Logging: print-body")
@GET("/")
...
```

**Comment by danvinokour** [comment]
Thnx danh32 and Jake, I kind of hoped there would be another solution since messing with headers for this purposes seems kind of hard to track. 

Jake,  maybe there is a place for "RetrofitInterceptor"  along with OkHttp interceptors and there we could access annotations like in the converter factory..

**Comment by JakeWharton** [comment]
Yep! That's the (potential) idea.
