### ISSUE TITLE
Dependency resolution issue when using Retrofit 2.0.0-beta3 with logging-interceptor 3.0.1

### ISSUE THREAD

**Issue by tkirshboim** [square/retrofit#1498]
When trying to use `com.squareup.retrofit2:retrofit:2.0.0-beta3` with `com.squareup.okhttp3:logging-interceptor:3.0.1` my app crashes with the following exception:

```
E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
  Process: com.kirshboim.depepencyissue, PID: 11732
  java.lang.AbstractMethodError: abstract method not implemented
    at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:33)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)
```

Please have a look at the repository I created that shows an example of this crash:
https://github.com/tkirshboim/retrofit-and-interceptor-issue

I'm guessing it's a (perhaps gradle related) dependency resolution issue because the workaround I used in the end was to use version `3.0.0-RC1` of the logging-interceptor library.

These are the dependencies gradle reports with the broken configuration:

```
./gradlew -q app:dependencies --configuration compile

------------------------------------------------------------
Project :app
------------------------------------------------------------

compile - Classpath for compiling the main sources.
+--- com.squareup.retrofit2:retrofit:2.0.0-beta3
|    \--- com.squareup.okhttp3:okhttp:3.0.0-RC1 -> 3.0.1
|         \--- com.squareup.okio:okio:1.6.0
\--- com.squareup.okhttp3:logging-interceptor:3.0.1
     \--- com.squareup.okhttp3:okhttp:3.0.1 (*)

(*) - dependencies omitted (listed previously)
```

And this is with the workaround:

```
./gradlew -q app:dependencies --configuration compile

------------------------------------------------------------
Project :app
------------------------------------------------------------

compile - Classpath for compiling the main sources.
+--- com.squareup.retrofit2:retrofit:2.0.0-beta3
|    \--- com.squareup.okhttp3:okhttp:3.0.0-RC1
|         \--- com.squareup.okio:okio:1.6.0
\--- com.squareup.okhttp3:logging-interceptor:3.0.0-RC1
     \--- com.squareup.okhttp3:okhttp:3.0.0-RC1 (*)

```

I thought I'd report this in case this happens to others.

**Comment by JakeWharton** [comment]
Those versions are not compatible and this has already been fixed. You need to use 2.0.0-SNAPSHOT for now. More info: https://github.com/square/retrofit/issues/1475#issuecomment-172241798

**Comment by JakeWharton** [comment]
Er, I see you figured that out. But yes, we're aware and it's unfortunate. Either a new beta or the final release will happen soon enough, though.

**Comment by tkirshboim** [comment]
Oh.. Sorry for the double posting then and thanks for the quick response.
