### ISSUE TITLE
Question about custom annotations

### ISSUE THREAD

**Issue by b22n** [square/retrofit#1500]
I want to do something like this.

```
public interface RestService {
   @Secure
   @GET("somthing")
   Call<..> getSomthing();
}

@Target(METHOD)
@Retention(RUNTIME)
public @interface Secure {}
```

There is no way for referencing my custom annotations from intercepted Request object now maybe
Could it be supported?

**Comment by danvinokour** [comment]
There might be solution according to Jack.
https://github.com/square/retrofit/issues/1496

**Comment by b22n** [comment]
Yes that may be a tricky idea but not the solution that I exactly want to

**Comment by andretietz** [comment]
would my pull request do the job?

**Comment by andretietz** [comment]
Not the nicest solution, but it fits my needs
https://medium.com/@andretietz/custom-annotations-with-retrofit-2-8701ca7ce102#.6y800r5rm

**Comment by swankjesse** [comment]
No action to take on this.
