### ISSUE TITLE
getting wrong body in retrofit

### ISSUE THREAD

**Issue by Aravind-Rajendran** [square/retrofit#1504]
i use viewpager with 3 tabs. All the tabs are call the same url . and Response type also same.Only body will change.

    In second fragment

       InboxInput inboxInput = new InboxInput(10,offset,"second");
        Log.d(TAG,"action type for input"+inboxInput.getActionType());

        call= RetrofitApi.getApi().fetchInboxforHired(inboxInput);
        call.enqueue(new Callback<InboxResponse>() {
            @Override
            public void onResponse(Response<InboxResponse> response) {
               // //Getting the response for third tab.
               
            }
        });

in ThirdFragment

         InboxInput inboxInput = new InboxInput(10,offset,"third");
        Log.d(TAG,"action type for input"+inboxInput.getActionType());
        call= RetrofitApi.getApi().fetchInboxforHired(inboxInput);
        call.enqueue(new Callback<InboxResponse>() {
            @Override
            public void onResponse(Response<InboxResponse> response) {
                
           //Getting the response for second tab.

               
            }
        });

i have checked the fragments,all are fine.not possible to identify the issue

**Comment by JakeWharton** [comment]
There's really not enough information to know what's going on here. Each call has its own request/response pair pipeline to the server and there's no place in the chain where the responses could somehow get mixed up. We also know nothing about the behavior of the server here.

Unless you can create a test case or standalone sample that reproduces the purported bug, I'm afraid there's really no action that we can take. Comment if you are able to create such a thing and we can re-open and investigate.
