### ISSUE TITLE
 abstract method not implemented at retrofit2.OkHttpCall

### ISSUE THREAD

**Issue by zhengxiaochuan** [square/retrofit#1509]
When trying to use com.squareup.retrofit2:retrofit:2.0.0-beta3 with com.squareup.okhttp3:okhttp:3.0.1 my app crashes with the following exception: E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher Process: Process: com.zhou.ontheway, PID: 18774
java.lang.AbstractMethodError: abstract method not implemented
                                                                       at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java), please tell me why. thanks

**Comment by eneim** [comment]
#1475 You should use SNAPSHOT of retrofit if you want to couple it with okhttp 3.0.1

**Comment by zhengxiaochuan** [comment]
Thanks. :)
