### ISSUE TITLE
Content-Type not changing to application/json

### ISSUE THREAD

**Issue by elod91** [square/retrofit#1524]
I'm trying to send my login params to the server, which is waiting for them in a json form. I got that working the following way:

@POST(RestConstants.USER_LOGIN)
    Call<SessionResponse> loginWithMailOrUsername(@Body User user);

But the Content-Type in the header remains text/html; charset=utf-8. I tried using the @Headers annotation, I tried to create an OkHttpClient with an interceptor and set the Content-Type header from there, but without any luck. The header stays text/html.

**Comment by JakeWharton** [comment]
What converters do you have installed? We don't ship any that would set `text/html`.

**Comment by elod91** [comment]
Gson. I need to send a JSON request. If that's possible.

**Comment by JakeWharton** [comment]
The Gson converter only uses `application/json`. Please provide an executable sample demonstrating the problem.

**Comment by zahid-mt** [comment]
I was facing similar issue today (only with proguard), spent half day and then finally, following proguard rules worked for me. @elod91 don't know you are using proguard or not.

```
-dontwarn retrofit2.**
-keep class retrofit2.** { *; }
-keep interface retrofit2.http.** { *; }
-keepclasseswithmembers class * {
    @retrofit2.http.* <methods>;
}
```

**Comment by elod91** [comment]
![contenttype](https://cloud.githubusercontent.com/assets/5939261/12575718/698e7584-c417-11e5-9a7a-b77bc130e3c0.png)
![request](https://cloud.githubusercontent.com/assets/5939261/12575726/7809ecba-c417-11e5-9a4d-d1386d83d6ce.png)

As you can see, the request param is a JSON, but the content type header is text/html... :(

**Comment by elod91** [comment]
Also, I wasn't using proguard, but I've enabled it and added the rules and still didn't work.

**Comment by elod91** [comment]
Made it work :dancer: Needed to add Accept : application/json header as well.

**Comment by Naresh-Katta** [comment]
@elod91 ,
you said needed to add Accept : application/json header as well!!
Please help me to do the same as well.
I mean please help me to make retrofit accept  application/json for Content-Type header.
I'm facing the same problem for all get requests.
I'm using the following code to set Content-Type Header
`httpClient.addInterceptor(  
                new Interceptor() {
            @Override
            public Response intercept(Chain chain) throws IOException {
                Request.Builder requestBuilder = chain.request().newBuilder();
                requestBuilder.removeHeader("Content-Type");
                requestBuilder.addHeader("Content-Type", "application/json");
                return chain.proceed(requestBuilder.build());
            }
        });`

**Comment by staroflead** [comment]
add this line 
requestBuilder.addHeader("Accept", "application/json");
