### ISSUE TITLE
Fill license placeholders

### ISSUE THREAD

**Issue by gokhanbarisaker** [square/retrofit#1526]
Current licence contains some placeholders that needs to be filled. i.e., `Copyright [yyyy] [name of copyright owner]`

https://github.com/square/retrofit/blob/c30a8b43295dee48434d8dceacb764a2c09c7af6/LICENSE.txt

**Comment by JakeWharton** [comment]
That section is part of the license, not something that should be modified. The applied license is in the source files and README.
