### ISSUE TITLE
Can't find GsonConverterFactory with snapshots

### ISSUE THREAD

**Issue by shubhamchaudhary** [square/retrofit#1534]
I am using the latest snapshot - 2.0.0-SNAPSHOT and I also have `compile 'com.squareup.retrofit2:converter-gson:2.0.0-SNAPSHOT'` in my dependencies.

```
error: cannot find symbol
import retrofit2.GsonConverterFactory;
                ^
  symbol:   class GsonConverterFactory
  location: package retrofit2
1 error
```

**Comment by JakeWharton** [comment]
It's `retrofit2.converter.gson.GsonConverterFactory` in the latest SNAPSHOTs.

**Comment by shubhamchaudhary** [comment]
And the solution for this is: `import retrofit2.converter.gson.GsonConverterFactory;`
Just wanted to add it here for anyone searching the same in future release.

**Comment by shubhamchaudhary** [comment]
You're fast :)

**Comment by JakeWharton** [comment]
There should be another (and last) beta soon, hopefully this week, which will provide more stable artifacts for OkHttp 3.0+ compatibility and these new package names.

**Comment by shubhamchaudhary** [comment]
Awesome.

**Comment by IgorGanapolsky** [comment]
I cannot import this **retrofit2.converter.gson.GsonConverterFactory**!  I get an error: `cannot resolve symbol gson`.
