### ISSUE TITLE
Using simplexml is error

### ISSUE THREAD

**Issue by chimis** [square/retrofit#1536]
I use:

compile 'com.android.support:appcompat-v7:23.1.1'
compile 'com.square.retrofit2:retrofit:2.0.0-beta3'
compile 'com.square.retrofit2:converter-simplexml:2.0-beta3'

Then:
Reading program jar [/home/chimis/Projects/CompositPublishing/app/build/intermediates/transforms/jarMerging/debug/jars/1/1f/combined.jar]
Reading library jar [/home/chimis/Software/Android/Sdk/build-tools/23.0.2/lib/shrinkedAndroid.jar]
Preparing output jar [/home/chimis/Projects/CompositPublishing/app/build/intermediates/multi-dex/debug/componentClasses.jar]
Copying resources from program jar [/home/chimis/Projects/CompositPublishing/app/build/intermediates/transforms/jarMerging/debug/jars/1/1f/combined.jar]
:app:transformClassesWithDexForDebug FAILED
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: Return code 1 for dex process

**Comment by JakeWharton** [comment]
What makes you think this is a Retrofit error? Nothing in the included logs identifies the problem, let alone Retrofit.

**Comment by JakeWharton** [comment]
Actually Simple XML has transitive dependencies which are already included in Android, apparently. You need to exclude them from the `converter-simplexml` dependency per the "Android" section here: https://github.com/square/retrofit/tree/master/retrofit-converters/simplexml#android
