### ISSUE TITLE
Retrofit2-beta3 and OkHttp 3.0.1 Error

### ISSUE THREAD

**Issue by vivekkiran** [square/retrofit#1543]
01-29 12:29:22.005: E/AndroidRuntime(18232): FATAL EXCEPTION: OkHttp Dispatcher
01-29 12:29:22.005: E/AndroidRuntime(18232): Process: in.wavelabs.starterapp, PID: 18232
01-29 12:29:22.005: E/AndroidRuntime(18232): java.lang.AbstractMethodError: abstract method not implemented
01-29 12:29:22.005: E/AndroidRuntime(18232): 	at retrofit2.OkHttpCall$1.onFailure(OkHttpCall.java)
01-29 12:29:22.005: E/AndroidRuntime(18232): 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:140)
01-29 12:29:22.005: E/AndroidRuntime(18232): 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:33)
01-29 12:29:22.005: E/AndroidRuntime(18232): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-29 12:29:22.005: E/AndroidRuntime(18232): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-29 12:29:22.005: E/AndroidRuntime(18232): 	at java.lang.Thread.run(Thread.java:841)

**Comment by eneim** [comment]
IMO, this version is under heavy development at the moment. Any crash could happen at anytime, especially when clients don't know what they are doing. So please **stay there at the point it works stably for you**, unless you know what's happening and how to solve that. You can refer the following close issue #1475
