### ISSUE TITLE
When I use Google Databinding, Retrofit 2 cannot work well

### ISSUE THREAD

**Issue by liangzhitao** [square/retrofit#1545]
I used `databinding` in demo, and then API interface with retrofit2 can't be created. The same code , and I remove `databinding` , it worked well. 

`Observable<GitHubUser> observable = GitHubApiUtils.getInstance().getGitHubApi().user(user);`  When I debug this line, it stopped to excute. And I changed `Observable` to `Call`, it remained the same.

And I asked question in [stackoverflow](http://stackoverflow.com/questions/35076118/when-i-use-google-databinding-retrofit-2-cannot-work-well). Hope to get help, thanks.

**Comment by JakeWharton** [comment]
StackOverflow is the right location for this question, thanks.
