### ISSUE TITLE
JsonArray as query parametr in GET method

### ISSUE THREAD

**Issue by Oppanke** [square/retrofit#1551]
@GET
Call<Response> getInfo(@Query("value") JsonArray jsonArray);
...
jsonArray = \[{"a": 2, "b":3}, {"a":1, "b":4}\] (for example)
How I can send JsonArray as query parameter?
When I try to use this method, I get an error "not valid as a java.net.URI: <address>/api/my?value=[{"a": 2, "b":3}, {"a":1, "b":4}]"

How fix it?

Thanks

**Comment by JakeWharton** [comment]
That error comes from an older version of OkHttp. If you use a modern version (like the latest 3.0.1) it will work.
