### ISSUE TITLE
i cannot use base url with '-' in it 

### ISSUE THREAD

**Issue by a3adel** [square/retrofit#1552]
'm trying to call an api in my application i've the following url template

test-test.domainname.com/feeds/json/v3/attribute/attribute
i'm using retrofit 2 but i get the following fatal exception

Illegal URL: test-test.domainname.com
and this is my interface

public interface Iinterface{
    @GET("feeds/json/v3/attribute/"+attribute)
    Call<ArrayList<result>>getresult();
}
can someone help me with this problem ...

**Comment by JakeWharton** [comment]
You need to prefix it with a scheme, either "http://" or "https://".
