### ISSUE TITLE
How can i "hot" change baseurl ?

### ISSUE THREAD

**Issue by nimengbo** [square/retrofit#1553]
For example the first baseurl  is "http://aa.aa.com/", Second baseurl is "http://bb.bb.com/", how can i use singleton retrofit to "hot" change base url.

**Comment by SethFeng** [comment]
I have the same problem. Hope a **request level** baseurl api.

**Comment by JakeWharton** [comment]
The base url can change over time by implementing `BaseUrl` and returning different values (such as in a round robin or based on data from response headers). You can also specify a full host name in your HTTP annotation or use the `@Url` annotation on a parameter to allow specifying a full host name dynamically.

**Comment by jianghaolu** [comment]
This has been my answer until 2.0.0. Why is `BaseUrl` removed?
Using `@Url` squashes all the path and query parameters into one, which makes it really inconvenient.

**Comment by JayNewstrom** [comment]
@jianghaolu See #1652

**Comment by JessYanCoding** [comment]
[Let Retrofit support multiple baseUrl and can be change the baseUrl at runtime](https://github.com/JessYanCoding/RetrofitUrlManager)
