### ISSUE TITLE
Handle Empty Body

### ISSUE THREAD

**Issue by roybrener** [square/retrofit#1554]
After updating to retrofit beta-3 I'm getting the Exception (Because of an empty body)

    java.io.EOFException: End of input at line 1 column 1
                                                                               at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1414)
                                                                               at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:553)
                                                                               at com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
                                                                               at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:202)
                                                                               at com.google.gson.TypeAdapter.fromJson(TypeAdapter.java:260)
                                                                               at retrofit2.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:33)
                                                                               at retrofit2.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:23)
                                                                               at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:154)
                                                                               at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:92)
                                                                               at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)

I know that It's possible to solve this issue Using `Call<Void>` but is there any other way to enforce `OkHttp` or `Gson` To accept Empty body?

Response Log:

     D/OkHttp: Date: Mon, 01 Feb 2016 08:32:10 GMT
    D/OkHttp: Server: Apache/2.4.7 (Ubuntu)
    D/OkHttp: X-Powered-By: PHP/5.5.9-1ubuntu4.13
    D/OkHttp: Expires: Thu, 19 Nov 1981 08:52:00 GMT
    D/OkHttp: Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
    D/OkHttp: Pragma: no-cache
    D/OkHttp: Access-Control-Allow-Origin: https://example.com
    D/OkHttp: Access-Control-Allow-Methods: GET,POST,OPTIONS
    D/OkHttp: Access-Control-Allow-Headers: Accept,Cache-Control,Pragma,Origin,Authorization,Content-Type,X-Requested-With,Cookie,*
    D/OkHttp: Access-Control-Allow-Credentials: true
    D/OkHttp: Content-Length: 0
    D/OkHttp: Keep-Alive: timeout=5, max=99
    D/OkHttp: Connection: Keep-Alive
    D/OkHttp: Content-Type: application/json
    D/OkHttp: OkHttp-Sent-Millis: 1454315528548
    D/OkHttp: OkHttp-Received-Millis: 1454315528725
    D/OkHttp: <-- END HTTP (0-byte body)

**Comment by FabianTerhorst** [comment]
Are you getting the same error when you don´t set a converter factory?

**Comment by roybrener** [comment]
I didn't test without the converter. I guess it will not fail because `GsonResponseBodyConverter.convert` will not run. Is there any reason why i should check without the converter?

**Comment by JakeWharton** [comment]
What behavior do you expect when the body is empty then?

You are telling Retrofit to deserialize the response as a certain object and Retrofit tells Gson to parse the stream into that type and the type is empty. This behavior already seems very reasonable to me.

**Comment by roybrener** [comment]
Just return an "empty" pojo response (Like it was until now)... all fields null? It's a real problem...for example I didn't write the server side...and usually the server side returns 200 with empty body...but there are times that the same call will return a 200 with a body message. I have nothing to do in situations like that

**Comment by JakeWharton** [comment]
An empty pojo is `{}` in JSON.

You can write a delegating converter that does this, the behavior will not be added to Retrofit by default.
```java
class NullOnEmptyConverterFactory implements Converter.Factory {
  @Override public Converter<ResponseBody, ?> responseBody(Type type, Annotation[] annotations, Retrofit retrofit) {
    final Converter<?> delegate = retrofit.nextResponseBody(type, annotations);
    return new Converter<>() {
      @Override public void convert(ResponseBody body) {
        if (body.contentLength() == 0) return null;
        return delegate.convert(body);
      }
    };
  }
}
```
```java
Retrofit retrofit = new Retrofit.Builder()
    .endpoint(..)
    .addConverterFactory(new NullOnEmptyConverterFactory())
    .addConverterFactory(GsonConverterFactory.create())
    .build();
```

**Comment by TheHal85** [comment]
I had to implement this for a requirement from my services team. Here is the updated code I used for release version of Retrofit 2.0 that seems to be working in case anyone else comes across the issue.

```Java
public class NullOnEmptyConverterFactory extends Converter.Factory {

    @Override
    public Converter<ResponseBody, ?> responseBodyConverter(Type type, Annotation[] annotations, Retrofit retrofit) {
        final Converter<ResponseBody, ?> delegate = retrofit.nextResponseBodyConverter(this, type, annotations);
            return new Converter<ResponseBody, Object>() {
                @Override
                public Object convert(ResponseBody value) throws IOException {
                    if (value.contentLength() == 0) return null;
                    return delegate.convert(value);                }
            };
    }
}
```

**Comment by nAkhmedov** [comment]
body.contentLength() always returns -1 on me. What to do?

**Comment by JakeWharton** [comment]
Just read it. That means unknown content length.

**Comment by nAkhmedov** [comment]
05-12 11:57:35.040 12039-13092/com.sms.sendsms D/OkHttp: <-- 200 OK http://www.yesplease.co.il/app/login.asp?username=zolim2&password=123456g (554ms)
05-12 11:57:35.041 12039-13092/com.sms.sendsms D/OkHttp: Cache-Control: must-revalidate,no-cache,private
05-12 11:57:35.041 12039-13092/com.sms.sendsms D/OkHttp: Content-Type: text/html; Charset=utf-8
05-12 11:57:35.041 12039-13092/com.sms.sendsms D/OkHttp: Expires: Wed, 11 May 2016 06:58:56 GMT
05-12 11:57:35.041 12039-13092/com.sms.sendsms D/OkHttp: Vary: Accept-Encoding
05-12 11:57:35.041 12039-13092/com.sms.sendsms D/OkHttp: Server: Microsoft-IIS/7.5
05-12 11:57:35.041 12039-13092/com.sms.sendsms D/OkHttp: X-Powered-By: Yes Please
05-12 11:57:35.041 12039-13092/com.sms.sendsms D/OkHttp: Server: Server
05-12 11:57:35.041 12039-13092/com.sms.sendsms D/OkHttp: Date: Thu, 12 May 2016 06:58:56 GMT
05-12 11:57:35.041 12039-13092/com.sms.sendsms D/OkHttp: Connection: Keep-Alive
05-12 11:57:35.041 12039-13092/com.sms.sendsms D/OkHttp: Set-Cookie: source=; path=/
05-12 11:57:35.041 12039-13092/com.sms.sendsms D/OkHttp: Set-Cookie: ASPSESSIONIDCSASTAQA=NCLNDGIBMFFIEGMOBHIABCEC; path=/
05-12 11:57:35.041 12039-13092/com.sms.sendsms D/OkHttp: OkHttp-Sent-Millis: 1463036254545
05-12 11:57:35.041 12039-13092/com.sms.sendsms D/OkHttp: OkHttp-Received-Millis: 1463036255040
05-12 11:57:35.041 12039-13092/com.sms.sendsms D/OkHttp: <-- END HTTP (0-byte body)
05-12 11:57:35.081 12039-12039/com.sms.sendsms W/System.err: java.io.EOFException: End of input at line 1 column 1

**Comment by nAkhmedov** [comment]
HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();//If need to logging, just uncomment
                interceptor.setLevel(HttpLoggingInterceptor.Level.BODY);
                OkHttpClient client = new OkHttpClient.Builder()
                    .addInterceptor(interceptor)
                    .build();
                Retrofit retrofit = new Retrofit.Builder()
                        .baseUrl(ContextConstants.APP_URL)
                        .addConverterFactory(new NullOnEmptyConverterFactory())
                        .addConverterFactory(GsonConverterFactory.create())
                        .client(client)
                        .build();

**Comment by AllenVork** [comment]
I add the NullOnEmptyConverterFactory to the retrofit, and still gets the error.

**Comment by jacklt** [comment]
help for Kotlin devs

```kotlin
val nullOnEmptyConverterFactory = object : Converter.Factory() {
    override fun responseBodyConverter(type: Type, annotations: Array<out Annotation>, retrofit: Retrofit) = Converter<ResponseBody, Any> {
        if (it.contentLength() != 0L) retrofit.nextResponseBodyConverter<Any>(this, type, annotations).convert(it) else null
    }
}
```

**Comment by JakeWharton** [comment]
@jacklt That is an inefficient solution. You have to look up the converter for _every_ response. Look it up once in the factory so that it can be used over and over by the returned converter.

**Comment by jacklt** [comment]
@JakeWharton Why? I create only one `Converter.Factory()`. What's wrong with that code?

**Comment by JakeWharton** [comment]
It calls `nextResponseBodyConverter` for every response.

**Comment by NightlyNexus** [comment]
@jacklt You want to cache the result of `nextResponseBodyConverter`.
something like:
```
override fun responseBodyConverter(type: Type, annotations: Array<out Annotation>, retrofit: Retrofit): Converter<ResponseBody, *>? {
  val nextResponseBodyConverter = retrofit.nextResponseBodyConverter<Any>(this, type, annotations)
  return Converter<ResponseBody, Any> {
    if (it.contentLength() != 0L) {
      nextResponseBodyConverter.convert(it)
    } else {
      null
    }
  }
}
```

**Comment by jacklt** [comment]
Ok, thanks! That's the full version

```
val nullOnEmptyConverterFactory = object : Converter.Factory() {
    fun converterFactory() = this
    override fun responseBodyConverter(type: Type, annotations: Array<out Annotation>, retrofit: Retrofit) = object : Converter<ResponseBody, Any?> {
        val nextResponseBodyConverter = retrofit.nextResponseBodyConverter<Any?>(converterFactory(), type, annotations)
        override fun convert(value: ResponseBody) = if (value.contentLength() != 0L) nextResponseBodyConverter.convert(value) else null
    }
}
```

**Comment by Piasy** [comment]
[In Gson's `fromJson` implementation](https://github.com/google/gson/blob/master/gson/src/main/java/com/google/gson/Gson.java#L891), it take care of empty JSON string, by catching the `EOFException` and returning `null`, its comment said:

> For compatibility with JSON 1.5 and earlier, we return null for empty documents instead of throwing.

So could it be possible that `GsonResponseBodyConverter` apply the same logic? 

Any way, the `NullOnEmptyConverterFactory` is a good solution.

**Comment by JakeWharton** [comment]
No, we won't be implementing that. An empty body is not valid JSON.

**Comment by SaadBilal** [comment]
@JakeWharton will it deal with empty arrays like "array":[] ?

**Comment by Piasy** [comment]
I've got a good way to handle this, just want to share with you guys :)

I create an `EmptyJsonLenientConverterFactory` to deal with empty body:

``` java
public class EmptyJsonLenientConverterFactory extends Converter.Factory {

    private final GsonConverterFactory mGsonConverterFactory;

    public EmptyJsonLenientConverterFactory(GsonConverterFactory gsonConverterFactory) {
        mGsonConverterFactory = gsonConverterFactory;
    }

    @Override
    public Converter<?, RequestBody> requestBodyConverter(Type type,
            Annotation[] parameterAnnotations, Annotation[] methodAnnotations, Retrofit retrofit) {
        return mGsonConverterFactory.requestBodyConverter(type, parameterAnnotations,
                methodAnnotations, retrofit);
    }

    @Override
    public Converter<ResponseBody, ?> responseBodyConverter(Type type, Annotation[] annotations,
            Retrofit retrofit) {
        final Converter<ResponseBody, ?> delegateConverter =
                mGsonConverterFactory.responseBodyConverter(type, annotations, retrofit);
        return value -> {
            try {
                return delegateConverter.convert(value);
            } catch (EOFException e) {
                // just return null
                return null;
            }
        };
    }
}
```

And besides, my server return api error in HTTP 200 response, so I also create a `YLApiErrorAwareConverterFactory` to catch them:

``` java
public class YLApiErrorAwareConverterFactory extends Converter.Factory {

    private final EmptyJsonLenientConverterFactory mEmptyJsonLenientConverterFactory;

    public YLApiErrorAwareConverterFactory(
            EmptyJsonLenientConverterFactory emptyJsonLenientConverterFactory) {
        mEmptyJsonLenientConverterFactory = emptyJsonLenientConverterFactory;
    }

    @Override
    public Converter<?, RequestBody> requestBodyConverter(Type type,
            Annotation[] parameterAnnotations, Annotation[] methodAnnotations, Retrofit retrofit) {
        return mEmptyJsonLenientConverterFactory.requestBodyConverter(type, parameterAnnotations,
                methodAnnotations, retrofit);
    }

    @Override
    public Converter<ResponseBody, ?> responseBodyConverter(Type type, Annotation[] annotations,
            Retrofit retrofit) {
        final Converter<ResponseBody, ?> apiErrorConverter =
                mEmptyJsonLenientConverterFactory.responseBodyConverter(YLApiError.class,
                        annotations, retrofit);
        final Converter<ResponseBody, ?> delegateConverter =
                mEmptyJsonLenientConverterFactory.responseBodyConverter(type, annotations,
                        retrofit);
        return value -> {
            ResponseBody clone = RealResponseBody.create(value.contentType(), value.contentLength(),
                    value.source().buffer().clone());
            Object apiError = apiErrorConverter.convert(clone);
            if (apiError instanceof YLApiError && ((YLApiError) apiError).isApiError()) {
                throw (YLApiError) apiError;
            }
            return delegateConverter.convert(value);
        };
    }
}
```

And to wire them up:

``` java
Retrofit retrofit = new Retrofit.Builder().client(okHttpClient)
        .baseUrl(URL)
        .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
        .addConverterFactory(new YLApiErrorAwareConverterFactory(
                new EmptyJsonLenientConverterFactory(GsonConverterFactory.create(gson))))
        .build();
```

**Comment by GJson** [comment]
package com.dooioo.core.network;

import java.io.IOException;
import java.lang.annotation.Annotation;
import java.lang.reflect.Type;

import okhttp3.ResponseBody;
import retrofit2.Converter;
import retrofit2.Retrofit;

/**
 * Created by gjson on 2016/10/17.
 * Name NullOnEmptyConverterFactory
 * Version 1.0
 */
public class NullOnEmptyConverterFactory extends Converter.Factory {

    @Override
    public Converter<ResponseBody, ?> responseBodyConverter(Type type, Annotation[] annotations, Retrofit retrofit) {
        final Converter<ResponseBody, ?> delegate = retrofit.nextResponseBodyConverter(this, type, annotations);

        return new Converter<ResponseBody, Object>() {

            @Override
            public Object convert(ResponseBody value) throws IOException {

                if (value.contentLength() == 0) return null;
                return delegate.convert(value);
            }
        };
    }
}

**Comment by Ztiany** [comment]
//ConverterFactory
      @Override
    public Converter<ResponseBody, ?> responseBodyConverter(Type type,
                                                            Annotation[] annotations,
                                                            Retrofit retrofit) {
        final Converter<ResponseBody, ?> delegateConverter =        // 3
                mGsonConverterFactory.responseBodyConverter(type,
                        annotations, retrofit);

        return new Converter<ResponseBody, Object>() {
            @Override
            public Object convert(ResponseBody value) throws IOException {
                try {
                    return delegateConverter.convert(value);            // 4
                } catch (JsonSyntaxException e) {
                    // just return null
                    Timber.e("Json covert error -->error : " + e);
                    return ApiHelper.createErrorResult();     // return a errorResult
                }
            }
        };
    }
       //crate errorResult
        public static HttpResult createErrorResult() {
              HttpResult httpResult = new HttpResult();
              httpResult.setCode(DATA_ERROR);
              return httpResult;
        }


   //hand error
          @Override
    public Observable<R> call(HttpResult<R> rHttpResult) {
        if (rHttpResult == null) {

            return Observable.error(new NetworkConnectionException());

        } else if (ApiHelper.isDataError(rHttpResult)) {

            return Observable.error(new ServerErrorException());//server data error

        } else if (!ApiHelper.isSuccess(rHttpResult)) {

            if (ApiHelper.isLoginExpired(rHttpResult)) {
                RxBus.send(new EventLoginExpired());
            }
            return Observable.error(createException(rHttpResult));

        } else {
            return Observable.just(rHttpResult.getData());
        }
    }

**Comment by grennis** [comment]
The server I am talking to (which I do not control) does not return a valid content-length so solutions that rely on it do not work for me. Furthermore I am using kotlin and using moshi. This is the only solution I could get working. I realize this has a serious error that swallows `EOFException` but I do not see any other way of doing this. Any ideas?

```java
class NullMoshiConverterFactory(val moshi: Moshi) : Converter.Factory() {
    val factory: MoshiConverterFactory

    init {
        factory = MoshiConverterFactory.create(moshi)
    }

    override fun requestBodyConverter(type: Type?, parameterAnnotations: Array<out Annotation>?, methodAnnotations: Array<out Annotation>?, retrofit: Retrofit?): Converter<*, RequestBody> {
        return factory.requestBodyConverter(type, parameterAnnotations, methodAnnotations, retrofit)
    }

    override fun responseBodyConverter(type: Type, annotations: Array<out Annotation>, retrofit: Retrofit): Converter<ResponseBody, *>? {
        return NullConverterFactory(factory.responseBodyConverter(type, annotations, retrofit))
    }

    class NullConverterFactory(val wrapped: Converter<ResponseBody, *>) : Converter<ResponseBody, Any> {
        override fun convert(value: ResponseBody?): Any? {
            try {
                return wrapped.convert(value)
            } catch (ex: EOFException) {
                return null
            }
        }
    }
}

```

**Comment by trinadhkoya** [comment]
E/UncaughtException: java.lang.IllegalArgumentException: Expected receiver of type com.zaggle.models.SuccessResponse, but got retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall

**Comment by SugerQ** [comment]
@nAkhmedov I met the same situation as you, how do you deal with it?

**Comment by nAkhmedov** [comment]
@SugerQ  i tottaly forget what was the reason. Sorry

**Comment by paulpv** [comment]
Blast from the past, but here is a fully anonymous impl:

```
Retrofit retrofit = new Retrofit.Builder()
...
//
// Prevent empty body from throwing "java.io.EOFException: End of input at line 1 column 1 path $"
// Per: https://github.com/square/retrofit/issues/1554
//
.addConverterFactory(new Factory()
{
    @Nullable
    @Override
    public Converter<ResponseBody, ?> responseBodyConverter(Type type, Annotation[] annotations, Retrofit retrofit)
    {
        final Converter<ResponseBody, Object> delegate = retrofit.nextResponseBodyConverter(this, type, annotations);
        return new Converter<ResponseBody, Object>()
        {
            @Override
            public Object convert(@NonNull ResponseBody body)
                    throws IOException
            {
                return body.contentLength() != 0 ? delegate.convert(body) : null;
            }
        };
    }
})
...
.build();        
```

**Comment by kroussevrb** [comment]
@JakeWharton someone said that "contentLength" always returns -1 for them, you replied "just read it" - if I read it in order to determine the length, then its consumed and I can't use it anymore for the actual parsing, so I get an error when I pass it to the delegate. `End of input at line 1 column 1 path $`  What to do in these cases? Tried resetting it, also tried reading it as the okhttp debugging interceptor does, but to no avail

**Comment by kcorey** [comment]
Sadly, here's another 'me too'.

I've tried each and every one of these approaches, without success.

I'm creating my builder like this:
`        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(url.toString())
                .client(client)
                .addConverterFactory(new NullOnEmptyConverterFactory())
                .addConverterFactory(converterFactory)
                .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                .build();
`

This is in a static method, so I'm creating my NullConverter like this:
`    public static class NullOnEmptyConverterFactory extends Converter.Factory {
        @Override
        public Converter<ResponseBody, ?> responseBodyConverter(Type type, Annotation[] annotations, Retrofit retrofit) {
            final Converter<ResponseBody, ?> delegate = retrofit.nextResponseBodyConverter(this, type, annotations);
            Log.d(TAG, "responseBodyConverter: creating the NULL converter");
            return new Converter<ResponseBody, Object>() {
                @Override
                public Object convert(ResponseBody body) throws IOException {
                    Log.d(TAG, "convert: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                    if (body.contentLength() == 0) {
                        Log.d(TAG, "convert: returning null");
                        return null;
                    } else {
                        Log.d(TAG, "convert: returning the delegate.convert result");
                        return delegate.convert(body);
                    }
                }
            };
        }
    }
`

Now, in every call where there's a body, I'm getting this in the log:
`convert: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
convert: returning the delegate.convert result
`
So, it would seem as if the Null Converter is at least trying to do its job.

However, on the call that is causing me difficulties (200 response, but empty body), I don't get those lines in the output.

All I can imagine is that the EOFException is being generated before the converter is getting a chance to protect us from the EOFException.  So, even though I'm getting a 200 from the server, my code is in the error handler branch.

Yes, for pedants, I understand this is not "good", "valid" or "proper" HTML, and that the server needs to change.  To that I would say that the world is not perfect.  It shouldn't be so ridiculously hard to handle such a simple situation.  

-Ken

**Comment by Shubhampatni86** [comment]
In my case I'm receiving Response body "[text={"errorCode":"username_in_use","messages":null}]" but still while converting response 

> converter.convert(responseBody) it throwing EOFException. Any suggestion !!

**Comment by jayeshpansheriya** [comment]
hello guys i face same error in retrofit with kotlin please suggest me 
use below link to see my code and give me suggestion
<br>
[https://stackoverflow.com/questions/52946537](https://stackoverflow.com/questions/52946537/java-io-eofexception-end-of-input-at-line-2-column-5)

**Comment by parcool** [comment]
> I've got a good way to handle this, just want to share with you guys :)
> 
> I create an `EmptyJsonLenientConverterFactory` to deal with empty body:
> 
> ```java
> public class EmptyJsonLenientConverterFactory extends Converter.Factory {
> 
>     private final GsonConverterFactory mGsonConverterFactory;
> 
>     public EmptyJsonLenientConverterFactory(GsonConverterFactory gsonConverterFactory) {
>         mGsonConverterFactory = gsonConverterFactory;
>     }
> 
>     @Override
>     public Converter<?, RequestBody> requestBodyConverter(Type type,
>             Annotation[] parameterAnnotations, Annotation[] methodAnnotations, Retrofit retrofit) {
>         return mGsonConverterFactory.requestBodyConverter(type, parameterAnnotations,
>                 methodAnnotations, retrofit);
>     }
> 
>     @Override
>     public Converter<ResponseBody, ?> responseBodyConverter(Type type, Annotation[] annotations,
>             Retrofit retrofit) {
>         final Converter<ResponseBody, ?> delegateConverter =
>                 mGsonConverterFactory.responseBodyConverter(type, annotations, retrofit);
>         return value -> {
>             try {
>                 return delegateConverter.convert(value);
>             } catch (EOFException e) {
>                 // just return null
>                 return null;
>             }
>         };
>     }
> }
> ```
> 
> And besides, my server return api error in HTTP 200 response, so I also create a `YLApiErrorAwareConverterFactory` to catch them:
> 
> ```java
> public class YLApiErrorAwareConverterFactory extends Converter.Factory {
> 
>     private final EmptyJsonLenientConverterFactory mEmptyJsonLenientConverterFactory;
> 
>     public YLApiErrorAwareConverterFactory(
>             EmptyJsonLenientConverterFactory emptyJsonLenientConverterFactory) {
>         mEmptyJsonLenientConverterFactory = emptyJsonLenientConverterFactory;
>     }
> 
>     @Override
>     public Converter<?, RequestBody> requestBodyConverter(Type type,
>             Annotation[] parameterAnnotations, Annotation[] methodAnnotations, Retrofit retrofit) {
>         return mEmptyJsonLenientConverterFactory.requestBodyConverter(type, parameterAnnotations,
>                 methodAnnotations, retrofit);
>     }
> 
>     @Override
>     public Converter<ResponseBody, ?> responseBodyConverter(Type type, Annotation[] annotations,
>             Retrofit retrofit) {
>         final Converter<ResponseBody, ?> apiErrorConverter =
>                 mEmptyJsonLenientConverterFactory.responseBodyConverter(YLApiError.class,
>                         annotations, retrofit);
>         final Converter<ResponseBody, ?> delegateConverter =
>                 mEmptyJsonLenientConverterFactory.responseBodyConverter(type, annotations,
>                         retrofit);
>         return value -> {
>             // read them all, then create a new ResponseBody for ApiError
>             // because the response body is wrapped, we can't clone the ResponseBody correctly
>             MediaType mediaType = value.contentType();
>             String stringBody = value.string();
>             try {
>                 Object apiError = apiErrorConverter
>                         .convert(ResponseBody.create(mediaType, stringBody));
>                 if (apiError instanceof YLApiError && ((YLApiError) apiError).isApiError()) {
>                     throw (YLApiError) apiError;
>                 }
>             } catch (JsonSyntaxException notApiError) {
>             }
>             // then create a new ResponseBody for normal body
>             return delegateConverter.convert(ResponseBody.create(mediaType, stringBody));
>         };
>     }
> }
> ```
> 
> And to wire them up:
> 
> ```java
> Retrofit retrofit = new Retrofit.Builder().client(okHttpClient)
>         .baseUrl(URL)
>         .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
>         .addConverterFactory(new YLApiErrorAwareConverterFactory(
>                 new EmptyJsonLenientConverterFactory(GsonConverterFactory.create(gson))))
>         .build();
> ```

what's your `YLApiError`?

**Comment by klaszlo8207** [comment]
Please reopen it, it is not working. When the server has no body and code is 4xx.

**Comment by BMarton** [comment]
A little help would be much appreciated here. Unfortunately I can't change the API I try to consume and one particular endpoint returns 202 - without any payload, no "{}", nothing - until the data is ready, then it'll return with a 200 and the proper payload.

When I to parse the 202 response it throws the exception. Any idea how to solve this? Is there a way to handle this - to handle the null response part and the valid payload too?

This is the converter:

```
internal val nullOnEmptyConverterFactory = object : Converter.Factory() {
    fun converterFactory() = this
    override fun responseBodyConverter(
        type: Type,
        annotations: Array<out Annotation>,
        retrofit: Retrofit
    ) = object : Converter<ResponseBody, Any?> {
        val nextResponseBodyConverter =
            retrofit.nextResponseBodyConverter<Any?>(converterFactory(), type, annotations)

        override fun convert(value: ResponseBody) =
            if (value.contentLength() != 0L) nextResponseBodyConverter.convert(value) else null
    }
}
```

```
fun provideRetrofit(factory: Gson, client: OkHttpClient): Retrofit {
        return Retrofit.Builder()
            .client(client)
            .addConverterFactory(nullOnEmptyConverterFactory)
            .addConverterFactory(ScalarsConverterFactory.create()) // used for jsonp
            .addConverterFactory(GsonConverterFactory.create(factory))
            .addCallAdapterFactory(CoroutineCallAdapterFactory())
            .baseUrl(ApiService.getBaseUrl())
            .build()
    }
```

This is the error message I get when I'm using HttpLoggingInterceptor to monitor the calls:

```
2020-11-05 10:52:42.294 1878-1878 error: java.io.EOFException
        at okio.RealBufferedSource.require(RealBufferedSource.kt:55)
        at okio.GzipSource.consumeHeader(GzipSource.kt:104)
        at okio.GzipSource.read(GzipSource.kt:62)
        at okio.RealBufferedSource.request(RealBufferedSource.kt:62)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:253)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:136)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```
And this is the error message I get when I don't use the LogginInterceptor:

```
2020-11-05 10:59:35.246 2797-2797 error: java.io.EOFException
        at okio.RealBufferedSource.require(RealBufferedSource.kt:55)
        at okio.GzipSource.consumeHeader(GzipSource.kt:104)
        at okio.GzipSource.read(GzipSource.kt:62)
        at okio.RealBufferedSource.read(RealBufferedSource.kt:41)
        at okio.ForwardingSource.read(ForwardingSource.kt:29)
        at retrofit2.OkHttpCall$ExceptionCatchingResponseBody$1.read(OkHttpCall.java:288)
        at okio.RealBufferedSource.select(RealBufferedSource.kt:93)
        at okhttp3.internal.Util.readBomAsCharset(Util.kt:256)
        at okhttp3.ResponseBody$BomAwareReader.read(ResponseBody.kt:208)
        at com.google.gson.stream.JsonReader.fillBuffer(JsonReader.java:1295)
        at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1333)
        at com.google.gson.stream.JsonReader.consumeNonExecutePrefix(JsonReader.java:1576)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:534)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:207)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:39)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
        at data.network.util.NullOnEmptyConverterFactoryKt$nullOnEmptyConverterFactory$1$responseBodyConverter$1.convert(NullOnEmptyConverterFactory.kt:29)
        at data.network.util.NullOnEmptyConverterFactoryKt$nullOnEmptyConverterFactory$1$responseBodyConverter$1.convert(NullOnEmptyConverterFactory.kt:18)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:121)
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by andrewdittmer** [comment]
Not sure if this helps, but I was able to use Response<Unit> as mentioned in here to prevent crash. https://github.com/square/retrofit/issues/3075

**Comment by BMarton** [comment]
Thanks @andrewdittmer! After a few hours of extensive digging around on SO and in github tickets I found out that my issue is caused by the backend. The API response lacks proper header data, and that's the reason I get the exception. The thread that helped me figure it out: https://github.com/square/okhttp/issues/3646

**Comment by servatti** [comment]
Just a heads up, I was facing this behaviour (null body exception) even with the solutions above. Then, I updated my API to return 200 instead of 204 (no content) and it worked.

**Comment by satyasivaprasad** [comment]
> body.contentLength() always returns -1 on me. What to do?

I am also facing the same issue. means "Empty Body" and content length is -1, so after adding NullOnEmptyConverterFactory also getting the issue.

I think we should not add contentLength != -1 condition inside NullOnEmptyConverterFactory  because https://github.com/square/okhttp/issues/3309

Is there any solution?

**Comment by elvedroid** [comment]
> > body.contentLength() always returns -1 on me. What to do?
> 
> I am also facing the same issue. means "Empty Body" and content length is -1, so after adding NullOnEmptyConverterFactory also getting the issue.
> 
> I think we should not add contentLength != -1 condition inside NullOnEmptyConverterFactory because [square/okhttp#3309](https://github.com/square/okhttp/issues/3309)
> 
> Is there any solution?

Maybe check for body.string().isEmpty() in this case?

**Comment by crisu83** [comment]
Here is my solution in Kotlin:
```kotlin
class NullOnEmptyConverterFactory @Inject constructor() : Converter.Factory() {

    override fun responseBodyConverter(
        type: Type,
        annotations: Array<out Annotation>,
        retrofit: Retrofit
    ) = Converter<ResponseBody, Any?> {
        if (it.contentLength() != 0L) retrofit.nextResponseBodyConverter<Any?>(
            this,
            type,
            annotations
        ).convert(it) else null
    }
}
```

**Comment by npwork** [comment]
Here is my solution:

```java
class NullOnEmptyConverterFactory extends Converter.Factory {
    @Override
    public Converter<ResponseBody, ?> responseBodyConverter(Type type, Annotation[] annotations, Retrofit retrofit) {
        final Converter<ResponseBody, ?> delegate = retrofit.nextResponseBodyConverter(this, type, annotations);
        return (Converter<ResponseBody, Object>) body -> {
            if (body.source().exhausted()) return null;
            return delegate.convert(body);
        };
    }
}

```

**Comment by eriknyk** [comment]
@npwork did you test it?

I've tested in retrofit v2.9.0 and contentLegth() is always -1, 
and it makes sense, since it will be set only when the response body is consumed by calling <ResponseBody instance>.bytes() or <ResponseBody instance>.byteString()

**Comment by parth-gith** [comment]
> Here is my solution:
> 
> ```java
> class NullOnEmptyConverterFactory extends Converter.Factory {
>     @Override
>     public Converter<ResponseBody, ?> responseBodyConverter(Type type, Annotation[] annotations, Retrofit retrofit) {
>         final Converter<ResponseBody, ?> delegate = retrofit.nextResponseBodyConverter(this, type, annotations);
>         return (Converter<ResponseBody, Object>) body -> {
>             if (body.source().exhausted()) return null;
>             return delegate.convert(body);
>         };
>     }
> }
> ```

Thanks! This is working..
I had issue with retrofit parsing(retrofit .enqueue() was going in infinite loop) as my api returns null with 200OK for certain condition.

**Comment by Reprheartbreaking** [comment]
@JakeWharton https://lnkr.fun/1f56aaa
