### ISSUE TITLE
Query parameter arraylist

### ISSUE THREAD

**Issue by FabianTerhorst** [square/retrofit#1555]
I want to get a url like myserver.com/items?ids =5000,50001, but when im using 
```
@GET("items")
Call<List<Item>> getItems(@Query("ids") List<Integer> ids);
```
The output url looks like this myserver.com/items?ids =5000&?ids=50001

**Comment by JakeWharton** [comment]
Iterable query params results in multiple per its documentation. If you want to join multiple pieces of data into one then you need to do that yourself.

#626 tracks pluggable handlers for parameters which would also allow you to do this.
