### ISSUE TITLE
How to cancel a request correctly?

### ISSUE THREAD

**Issue by turbof** [square/retrofit#1559]
This is my code:
`if (mCall != null) {
            mCall.cancel();
            Log.i("+++", "cancel "+mCall);
        }
        mCall = Api.search(searchKey, new Callback<SearchResult>() {
            @Override
            public void onResponse(Response<SearchResult> response) {
                Log.i("+++","correct"+response);
            }
            @Override
            public void onFailure(Throwable t) {
                Log.i("+++","fail");
            }
        });`
And there are logs:
02-02 13:44:16.935  23511-23511/? I/+++﹕ cancel retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall@431e9bc0
02-02 13:44:17.485  23511-23511/? I/+++﹕ cancel retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall@42891f98
02-02 13:44:17.495  23511-23511/? I/+++﹕ cancel retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall@42a8e648
02-02 13:44:17.505  23511-23511/? I/+++﹕ error
02-02 13:44:18.115  23511-23511/? I/+++﹕ cancel retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall@4283b408
02-02 13:44:18.655  23511-23511/? I/+++﹕ cancel retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall@431a6c30

how can I cancel the previous request correctly?

**Comment by JakeWharton** [comment]
I don't understand what you mean by correctly? What problem are you observing?

**Comment by turbof** [comment]
It run onFailure(Throwable t) method when I call cancel().I think it should not be run onFailure method.

**Comment by JakeWharton** [comment]
Cancel will always notify the callback. You can check `Call.isCanceled()` to determine whether the request has failed because of a cancel or because of an actual IO error.
