### ISSUE TITLE
retrofit + GSON doesn't serialise HashMap, GSON on his own does

### ISSUE THREAD

**Issue by qbait** [square/retrofit#1560]
My request model contains map and looks like

```
public class AddRequest {
public String url;
public String key;
public Map<String, String> attributes;

public AddProductToBasketRequest(String url, String key, Map<String, String> attributes) {
    this.url = url;
    this.key = key;
    this.attributes = attributes;
}
}
```

when I'm printing my model by

`new Gson().toJson(request)`

I've got

`{"url":"https://www.net-a-porter.com/lalala","attributes":{"size":"it34"},"key":"agtzfnNm"}`

but when I'm sending request by retrofit, I've got empty attributes in logs

`{"attributes": {}, "url": "https://www.net-a-porter.com/lalala", "key": "agtzfnNm"}   `

My RestAdapter looks like

```
public RestAdapter restAdapter = new RestAdapter.Builder()
        .setRequestInterceptor(new RequestInterceptor() {
            @Override
            public void intercept(RequestFacade request) {
                request.addHeader("Access-Token", token;
            }
        })
        .setEndpoint(url)
        .setConverter(new GsonConverter(new GsonBuilder()
                .excludeFieldsWithModifiers(Modifier.FINAL, Modifier.TRANSIENT, Modifier.STATIC)
                .serializeNulls()
                .create()))
        .build();
```

What's the problem with retrofit that can't serialise HashMap?

**Comment by ZkHaider** [comment]
possibly adding this to your converter is causing issues:

    .setConverter(new GsonConverter(new GsonBuilder()
                .excludeFieldsWithModifiers(Modifier.FINAL, Modifier.TRANSIENT, Modifier.STATIC)
                .serializeNulls()
                .create()))

Also can you list your service endpoint? And how you are declaring your params in that interface method? Example:

    @POST("http://example.com/something")
    void getSomething(@Body SomeRequest someRequest,
                                                Callback<String> callback);

**Comment by JakeWharton** [comment]
And you're certain the map is not empty?

**Comment by qbait** [comment]
Yes, it was issue with clearing HashMap!
