### ISSUE TITLE
Issue with specific request adding extra escape character

### ISSUE THREAD

**Issue by ZkHaider** [square/retrofit#1562]
I am trying to send something like this inside a request as a `@Body`:

    \/Date(13455662727)\/

When passing it through a request, I am guessing that somewhere in the `Converter` possibly `Gson` adds an extra `\` to the request, so the parameter ends up looking like the following:

    \\/Date(13455662727)\\/

The server rejects this. I'm wondering if it's possible to write a custom `RequestInterceptor` to catch this parameter **only** for this request and adjust it before its sent off to the server.

Is this achievable?

**Comment by JakeWharton** [comment]
I answered at https://github.com/google/gson/issues/781. Sounds like your server is broken (since escaping is required by JSON), or you shouldn't be using Gson as your converter to encode the body.
