### ISSUE TITLE
request parameters are adapted to concrete class, not to object's actual

### ISSUE THREAD

**Issue by emakar** [square/retrofit#1565]
RequestFactoryParser.parseParameters takes into consideration just method signature. Thus constructed Converter knows nothing of actual object type - it is constructed via requestBodyConverter(Type type, ..)

That leads to following issue with GSON Converter:
```
class A {
  @SerializedName("aField") String a;
}
class B extends A {
  @SerializedName("bField") String b;
}

@Post("http://example.com/something")
Observable<Boolean> sendData(@Body A anyData);
```
So if we use retrofitApi.sendData(new B()) constructed request won't have any "bField" in it - it would contain only registered A Type info

(retrofit1 used converter.toBody(value) directly, so that converter has actual object info and sendData(new B()) has both "aField" and "bField")

**Comment by JakeWharton** [comment]
@swankjesse Thoughts here? This keeps coming up...

**Comment by swankjesse** [comment]
It’s possible to write a converter that defers reflection until an instance is known. We could provide such a converter as a sample.

It’s unwise to implicitly subclasses in remote APIs because the types are lost on conversion. You could imagine that the remote peer doesn’t have enough information to differentiate `B` from other subclasses.

**Comment by emakar** [comment]
Ok, Thanks. It just seems to bring a little(?) more extra migration work from retrofit 1.9
And what are advantages over old technic? Is it less reflection usage? (but we still have method.getGenericParameterTypes, etc). Why not defer overall ```requestBodyConverter``` until value.getClass() could be issued (just like version 1.9 behaves) so that converter is no more constrained with its implementation (and don't require any extra configuration). That would make converter usage/implementation as easy as possible compared to 1.9 (otherwise it's just like moving difficulties to other side, isn't it?)

**Comment by emakar** [comment]
Oh, that's the point - actually remote peer differentiate descendants with synthetic 'type' field (enum, string, int, whatever). And that way it would be rather easy to customize Converter, thanks!
So I'd rather agree that would be a rare case - however worth mentioning in documentation

**Comment by JakeWharton** [comment]
> Why not defer overall requestBodyConverter until value.getClass() could be issued

Because this often comes with a lot of associated work and doing that work every time is wasteful when most people never need this behavior.

> It’s possible to write a converter that defers reflection until an instance is known.

I would welcome this as an example in the `sample/` project if anyone gets inspired.
