### ISSUE TITLE
is there any Reactive extensions decorator for Call object

### ISSUE THREAD

**Issue by osemen-remit** [square/retrofit#1568]
I'm using `rx.Observable` responses in my app. But I would like to write a tests for API that fails whenever API is changed. But I can't get raw body as my responses are `rx.Observable`s. I hoped that Retrofit2 with it's `Call` concept will help me as it does with sync and async calls.

So question is: Is there any `CallAdapterFactory` that extend `Call` with `asObservable` method beside `execute` and `enqueue` ?

For instance:

```Java
interface Api {
  @GET("/user")
  RxCall<User> getUser();
}

Api api = new Retrofit.Builder()
                .baseUrl(baseUrl)
                .addConverterFactory(GsonConverterFactory.create())
                .addCallAdapterFactory(RxCallAdapterFactory.create())
                .build().create(Api.class);
// app code
api.getUser().asObservable()
    .subscribe(
        resp -> {},
        err -> {}
    );

// test code
api.getUser().execute().raw().body.string();
```

**Comment by JakeWharton** [comment]
`raw().body()` will always return a body with no content since it's already been consumed. There is no way to have a single endpoint where you can gain access to both the deserialized object and raw body conditionally.
