### ISSUE TITLE
/system/lib/libssl.so crash in mobile app.

### ISSUE THREAD

**Issue by sorinirimies** [square/retrofit#1569]
Hi guys,

We are using the latest retrofit library in our app, and we get crashes regarding the libssl.so.
Versions used are:
okHttp 2.1.0
retrofit 1.9.0

And stack trace:

Build fingerprint: 'htc/htc_europe/htc_memul:4.4.2/KOT49H/405590.2:user/release-keys'
Revision: '0'
pid: 25052, tid: 25087, name: Thread-55425  >>> <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000000
    r0 00000000  r1 00000000  r2 68fc4045  r3 00000015
    r4 00000002  r5 68fc4046  r6 00000000  r7 ffffffff
    r8 00000001  r9 00000000  sl 00000015  fp 68fc4045
    ip 5da11b30  sp 6548d918  lr 5da060f1  pc 40adafd6  cpsr 600f0030
    d0  0000000000000000  d1  0000000000000000
    d2  0000000000000000  d3  0000000000000000
    d4  3eb4000000000000  d5  0000000800000dc7
    d6  03000008000000de  d7  4040000000000003
    d8  0000000000000000  d9  0000000000000000
    d10 0000000000000000  d11 0000000000000000
    d12 0000000000000000  d13 0000000000000000
    d14 0000000000000000  d15 0000000000000000
    d16 0000000000000000  d17 0000000000000000
    d18 0a727c8b2da65bf4  d19 664b9df9e51b2a15
    d20 c000664b9df9e51b  d21 010001ff2c000009
    d22 0023000000000000  d23 3268021500743300
    d24 0000000000000000  d25 0000000000000000
    d26 0000000000000000  d27 0000000000000000
    d28 0100010001000100  d29 0100010001000100
    d30 0000000000000000  d31 0000000000000000
    scr 68000010

backtrace:
    #00  pc 00026fd6  /system/lib/libssl.so (SSL_select_next_proto+49)
    #01  pc 000070ed  /system/lib/libjavacrypto.so
    #02  pc 0002f3a3  /system/lib/libssl.so (ssl_parse_serverhello_tlsext+434)
    #03  pc 00018129  /system/lib/libssl.so (ssl3_get_server_hello+1008)
    #04  pc 00017527  /system/lib/libssl.so (ssl3_connect+566)
    #05  pc 00026591  /system/lib/libssl.so (SSL_connect+20)
    #06  pc 0001207f  /system/lib/libssl.so (ssl23_connect+2310)
    #07  pc 00027d7b  /system/lib/libssl.so (SSL_do_handshake+50)
    #08  pc 0000b051  /system/lib/libjavacrypto.so
    #09  pc 00020a4c  /system/lib/libdvm.so (dvmPlatformInvoke+112)
    #10  pc 00057689  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+428)
    #11  pc 00029ee0  /system/lib/libdvm.so
    #12  pc 000327e4  /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
    #13  pc 0002fd00  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+232)
    #14  pc 0006d56d  /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+336)
    #15  pc 0006d591  /system/lib/libdvm.so (dvmCallMethod(Thread*, Method const*, Object*, JValue*, ...)+20)
    #16  pc 000607df  /system/lib/libdvm.so
    #17  pc 0000d300  /system/lib/libc.so (__thread_entry+72)
    #18  pc 0000d498  /system/lib/libc.so (pthread_create+240)

code around pc:
    40adafb4 d02c2b00 9f0f9701 21009102 4001f81b  
    40adafc4 0801f101 eb0bb1cf eb0b0001 90030508  
    40adafd4 f8162000 f1009000 454c0a01 eb06d109  
    40adafe4 4628010a f7e54622 4601ef3c 29002001  
    40adaff4 eb0ad00a 42b80009 eb08d3eb 9a040104  
    40adb004 42912002 e000d3da 99029e03 1c729f01  
    40adb014 7832603a b005700a 8ff0e8bd 3178f8d0  
    40adb024 2100600b bf182b00 117cf890 47706011  
    40adb034 11a4f8c0 21a8f8c0 bf004770 11acf8c0  
    40adb044 21b0f8c0 bf004770 4605b570 f8d54614  
    40adb054 460e01bc bf182800 edb2f7e5 f240480a  
    40adb064 490a6296 44014478 f7e54620 2101ed9e  
    40adb074 01bcf8c5 4631b130 f7e54622 2100edde  
    40adb084 41c0f8c5 bd704608 000139dc ffffb66d  
    40adb094 4605b570 f8d54614 460e019c bf182800  
    40adb0a4 ed8ef7e5 f240480a 490a62aa 44014478  

code around lr:
    5da060d0 46072121 f7fe4640 6a7aef86 b1646abb  
    5da060e0 000ce88d 46294630 9b084622 ef62f7fe  
    5da060f0 bf142801 20002003 b116e004 6034b10d  
    5da06100 2003702c 81fce8bd 4604b538 6a05b188  
    5da06110 f7ffb155 6829ffc3 6d9a6803 46284790  
    5da06120 ef66f7fe 62202000 20012100 616160e1  
    5da06130 bd38bd38 6803b508 47906d5a b508bd08  
    5da06140 6dda6803 bd084790 6803b508 47906fda  
    5da06150 b510bd08 f8d46804 47a04084 b40cbd10  
    5da06160 ab04b513 f8536804 f8d42b04 930140c8  
    5da06170 e8bd47a0 b002401c b40c4770 ab04b513  
    5da06180 f8536804 f8d42b04 930140f8 e8bd47a0  
    5da06190 b002401c b40c4770 ab04b513 f8536804  
    5da061a0 f8d42b04 930141cc e8bd47a0 b002401c  
    5da061b0 b5084770 f8d36803 4790229c b508bd08  
    5da061c0 f8d36803 479022ac b510bd08 f8d46804  
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---

**Comment by JakeWharton** [comment]
Retrofit has no interaction with APIs this low level. At best it would be the underlying HTTP client. Your version of OkHttp is ancient, so I would recommend trying a new version of that. If it will occurs with the latest version you can file a bug against OkHttp, but it may not even be something that OkHttp has control of.

**Comment by sorinirimies** [comment]
Thx Jake. Like always very prompt and helpful.
