### ISSUE TITLE
Exception being thrown when executing http request object. 

### ISSUE THREAD

**Issue by akash3456** [square/retrofit#1572]
I seem to be getting the following exception when i run: 

public class Connection extends AsyncTask{
        protected Object doInBackground(Object[] objects){
            try{

                PostData(R.id.fullscreen_content, 3);
               }
                    catch(IOException exception){
                        exception.printStackTrace();
                    }
                    return null;
                }
    }
cant create handler inside thread has not called looper.prepare

**Comment by JakeWharton** [comment]
The exception is missing and there's no indication of any Retrofit code. Usage questions should be directed at StackOverflow with the 'retrofit' tag. Please also include the actual stack trace and the relevant code from which the exception was thrown.
