### ISSUE TITLE
Getting error while uploading image.

### ISSUE THREAD

**Issue by santosh-imaginnovate** [square/retrofit#1574]
I am uploading an image file to server which throws the error with success response(200).

The error message I'm getting is:
Invalid file type! Only the following filetypes are allowed: bmp, csv, doc, docx, eps, flv, gif, jpeg, jpg, mkv, mov, mp3, mp4, mpeg, mpg, ogg, pdf, png, psd, rar, swf, txt, wav, wma, wmv, xls, xlsx, zip

Here is my code snippet:

        Uri imageUri = Uri.fromFile(new File(fileName));

        Map<String, RequestBody> map = new HashMap<>();
        if (imageUri != null) {
            File file = new File(imageUri.getPath());
            RequestBody fileBody = RequestBody.create(MediaType.parse("multipart/form-data"), file);
            map.put("file\"; filename=\"" + file.getName(), fileBody);
        }

        Call<UploadResponse> call = FotomateClient.getFotomateAPI().upload(authorization, map);
        call.enqueue(new Callback<UploadResponse>() {
            @Override
            public void onResponse(Response<UploadResponse> response) {
                if (response != null)
                    if (response.body() != null)
                        if (response.body().getCode() != null)
                            System.out.println(response.body().getCode());
                pd.dismiss();
                if (response.body().isSuccess()) {
                    postCart("Bearer " + fm.getAccessToken(), response.body().getCode(), qty);
                    dbHelper.deleteImage(id);

                }
            }

            @Override
            public void onFailure(Throwable t) {
                t.printStackTrace();
            }
        });
    }

I'm strucked at this point. Can any one help me out.
Thanks in advance.

**Comment by JakeWharton** [comment]
This is a usage question and not a bug or feature request of Retrofit. Please ask on StackOverflow with the 'retrofit' tag which serves as a much better location for support and for archiving questions so that future people searching can find solutions to similar problems.

**Comment by santosh-imaginnovate** [comment]
Okay thank you @JakeWharton
