### ISSUE TITLE
Passing malformed url triggers illigalArgumentException url == null

### ISSUE THREAD

**Issue by danvinokour** [square/retrofit#1575]
The url i am passing is malformed, for example it looks like gg://{url} instead of https://{url}
The exception im receiving is =IlligalArgumentException url == null.
I would expect to receive "MalformedUrlException" at least in the cause section with the right message and not "url == null" because it is not null.

Can you please make malformed url's return "MalformedUrlException" ?

**Comment by JakeWharton** [comment]
`MalformedURLException` is a checked exception and we don't want to burden the 99.999% of people who will never pass a malformed URL with a needless try/catch that they'll only end up ignoring (and their application will break at runtime) or re-throwing (and their application will crash at runtime).

For the 0.0001% of times that a malformed URL is actually passed, the unchecked exception will crash the application which is the correct behavior.

If you want to validate a URL before passing it to Retrofit's `Builder`, call `HttpUrl.parse` and verify something non-null is returned. Then you can pass that `HttpUrl` instance to `baseUrl` (which will never throw IAE).

**Comment by danvinokour** [comment]
K, will do. 
Dont you want at least change the message in the exception from url==null?   It is misleading...

**Comment by JakeWharton** [comment]
That's only thrown if you pass null. If you pass an invalid URL an IAE is thrown: https://github.com/square/retrofit/blob/b61a68ae4908016f3d838ed0659c1a698dcb0349/retrofit/src/main/java/retrofit2/Retrofit.java#L417-L419

**Comment by danvinokour** [comment]
if you take a look at RequestBuilder line 178 baseurl.resolve(relativeUrl) will return null if the url is malformed which leads to this exception to being thrown.

Maybe the problem is i forgot to mention i was talking about cases in which you use the @Url annotation and not the baseUrl.

**Comment by JakeWharton** [comment]
Got it. Will add a more useful message!
