### ISSUE TITLE
Uncustomizable order of GET parameters

### ISSUE THREAD

**Issue by artemik** [square/retrofit#1576]
How could I specify an order (even an exact place) of parameters passed to the GET annotation?
Suppose I already have some URL: .../p1=v1**&**p2=v2**&**p3=v3
What if I want to only replace the v2 and be it exactly between p1 and p3? Now I can't, because the Query annotion only appends parameters.
As a solution, I though, I could pass those p1 and p3 dynamically as well (though I don't need it). But I could not find any gurantees that Retrofit takes order of variables into account.

**Comment by JakeWharton** [comment]
You can't specify an order. Why do you need exact ordering?

**Comment by artemik** [comment]
It's required when creating the hash key (md5) of the query string and passing it as a query parameter also. Most mobile endpoints, for example, do it to protect their service from abuse of outsiders. So this is quite demanded feature.

**Comment by swankjesse** [comment]
If you need to checksum the URL, you should do that  _after_ Retrofit constructs it. You can do this with an OkHttp network interceptor.

**Comment by artemik** [comment]
I could. But I need to checksum the URL constructed Before. Because checksum depends on my own exact order. Retrofit should never restrict me from doing it anyway.

**Comment by JakeWharton** [comment]
The order is deterministic based on the parameter order, which was your second question.

**Comment by artemik** [comment]
Yes. It's working. This way I need to pass any parameters, including those that are constant, anyway it's working. I think it would be good to mention this behaviour somewhere.
Thanks
