### ISSUE TITLE
Multi Part is failing in 2.0.0-beta4

### ISSUE THREAD

**Issue by raviteja06** [square/retrofit#1579]
I tried to upload the file using retrofit 2.0.0-beta4 and OKHHTP 3.1.1. It's returning me JSON should start with an object or array. It was working fine with 2.0.0-beta2 and OKHTTP 2.7.2.

`@Multipart`
`@POST("media?format=json")`
`Call<JsonObject> uploadMedia(@Part("MediaType") String mediaType, @Part("body\"; filename=\"media.jpg\" ") RequestBody file);`

    final RequestBody requestBody =
                RequestBody.create(MediaType.parse("image/*"), new File(new Compressor(context, 1600, 1200)
                        .compressImage(projectMedia.getMediaInfo().getMediaPath(), projectMedia.getMediaInfo().getRotate())));
        Call<JsonObject> call = projectRetrofitService.uploadMedia("ProjectMedia", requestBody);
        call.enqueue(new Callback<JsonObject>() {
            @Override
            public void onResponse(Call<JsonObject> call, Response<JsonObject> response) {
              
            }

            @Override
            public void onFailure(Call<JsonObject> call, Throwable t) {
                AddProjectActivity.canGoBack = true;
                
            }
        });

Thanks in advance. This might be duplicate of multipart file upload in other versions like beta2 or 3, I tried other solution from the old versions, no luck.

**Comment by swankjesse** [comment]
This is because your Gson isn't lenient. Try configuring a lenient Gson when you set up your Retrofit.

**Comment by raviteja06** [comment]
I tried using it as responsebody also, It was still showing same. When I tried the same code using 2.0.0 beta 2 it works fine with no issues. Thanks.


----------------

Best Regards,

Ravi Gadipudi






On Mon, Feb 8, 2016 at 7:17 PM -0800, "Jesse Wilson" <notifications@github.com> wrote:












This is because your Gson isn't lenient. Try configuring a lenient Gson when you set up your Retrofit.

**Comment by AlexBlokh** [comment]
Gson 2.6.1 with set lenient works fine

**Comment by mhousser** [comment]
Can someone leave a detailed code example re: "setting Gson to lenient"? I see no obvious methods.

**Comment by AlexBlokh** [comment]
``` Java
@Provides
@ApplicationScope
Gson provideGson() {
        GsonBuilder builder = new GsonBuilder();
        builder.registerTypeAdapter(UsedCoverImages.class, new UsedCoverImagesConverter());
        builder.registerTypeAdapter(Gender.class, new GenderConverter());
        builder.registerTypeAdapter(Price.class, new PriceConverter());
        builder.registerTypeAdapter(Boolean.class, new BooleanAsIntAdapter());
        builder.registerTypeAdapter(boolean.class, new BooleanAsIntAdapter());
        builder.serializeNulls();
        builder.setLenient();
        return builder.create();
}
```

**Comment by seaguest** [comment]
@AlexBlokh , hello Alex, could you please have a look at my problem? https://github.com/square/retrofit/issues/1676
I am using 
    compile 'com.squareup.retrofit2:retrofit:2.0.0-beta4'
    compile 'com.squareup.retrofit2:converter-gson:2.0.0-beta4'

without changing the gson version, is there any easy to set the gson converter lenient?

**Comment by AlexBlokh** [comment]
you should update the son lib to v2.6.1 (or later)
`compile 'com.google.code.gson:gson:2.6.1'`
