### ISSUE TITLE
Raw json as params in Get Method

### ISSUE THREAD

**Issue by whowazit** [square/retrofit#1580]
http://blahblah/user?where={username:{startsWith:test}}

it says "not valid as a java.net.URI". I pass the where part as @Query("where) String where

and this is my dependencies:
 
    compile 'com.squareup.retrofit:retrofit:2.0.0-beta2'
    compile 'com.squareup.retrofit:converter-gson:2.0.0-beta2'

**Comment by JakeWharton** [comment]
This is thrown from OkHttp, not Retrofit, and updating OkHttp to the latest version will fix the problem. You'll also need to update to beta4 of Retrofit since older versions are incompatible with the latest OkHttp.

**Comment by whowazit** [comment]
Thank you @JakeWharton  !!!
