### ISSUE TITLE
Call.isCanceled() is not found

### ISSUE THREAD

**Issue by Jayvd** [square/retrofit#1581]
On the changelog of the beta3 

`New: isCanceled() method returns whether a Call has been canceled. Use this in onFailure to determine whether the callback was invoked from cancelation or actual transport failure.`

I am now on Beta 4 but I still do not have the isCanceled() on the Call object.

**Comment by JakeWharton** [comment]
Not sure what to tell you because it's surely there: https://github.com/square/retrofit/blob/11e708271bd46aaca939051c2eacd68a020682b8/retrofit/src/main/java/retrofit2/Call.java#L62-L63.

Are you sure you're using the correct `Call` interface? Show some more code.
