### ISSUE TITLE
@Part with list types

### ISSUE THREAD

**Issue by OleksiyDundar** [square/retrofit#1582]
I need to send request with image and some array data. And this request doesnt work:

  @Multipart
  @POST(urlStringPart)
  Call<Void> myRequest (  @Part("image\"; filename=\"image.png\"") RequestBody image,
                                          @Part("some_array[]") List<String> values);

It sends "some_array[]" like one string "["value1", "value2", "value2"]", this is not what i need.

When i use  
@Part("some_array[]") List<RequestBody> values
it sends "some_array[]" like one string "["null", "null", "null"]".

But in changelog of version Version 2.0.0-beta3 there is info:
New: @Part annotation now supports List and array types.

So, what am i doing wrong??

**Comment by JakeWharton** [comment]
These two tests show both arrays and lists working correctly: https://github.com/square/retrofit/blob/11e708271bd46aaca939051c2eacd68a020682b8/retrofit/src/test/java/retrofit2/RequestBuilderTest.java#L1317-L1376.

Can you phrase your problem in the form of a test case?

**Comment by OleksiyDundar** [comment]
It was my bad, i imported classes Retrofit, Call, GsonConverterFactory and
others from retrofit package and it had to be imported from retrofit2
package. And i wrote old gradle dependency for gson converter (not the
retrofit2:converter-gson:2.0.0-beta4). Now its okay, all requests work
correctly. Sorry for disturbing.

2016-02-09 16:38 GMT+02:00 Jake Wharton <notifications@github.com>:
