### ISSUE TITLE
RxJavaCallAfapterFactory does not recognize rx.Single after proguarding

### ISSUE THREAD

**Issue by krzysiekbielicki** [square/retrofit#1584]
After proguarding application which uses retrofit service like

```
interface Service {
  @GET("/something")
  Single<String> getSomething();
}
```

retrofit fails with

```
java.lang.IllegalArgumentException: Could not locate call adapter for e.r<java.lang.String>.
                                                   Tried:
                                                    * retrofit2.adapter.rxjava.RxJavaCallAdapterFactory
                                                    * retrofit2.ExecutorCallAdapterFactory
                                                     at retrofit2.Retrofit.nextCallAdapter(Unknown Source)
                                                     at retrofit2.Retrofit.callAdapter(Unknown Source)
```

**Comment by JakeWharton** [comment]
`Single` is `@Beta` and as such [can be broken or removed at any time][1]. Retrofit will not put its presence in the critical path for all RxJava support until it graduates to stable.

 [1]: https://github.com/ReactiveX/RxJava#beta

**Comment by JakeWharton** [comment]
You can tell ProGuard to not obfuscate this class for now.

**Comment by david-perez** [comment]
Having this issue. `Single` is no longer `@Beta`.

**Comment by JakeWharton** [comment]
And it's already been adjusted on `master` accordingly.

**Comment by david-perez** [comment]
I'm sorry, was using `2.0.0-beta4`. I can't use latest version. How do I tell ProGuard not to obfuscate the class then?

```
-keep class retrofit2.adapter.rxjava.RxJavaCallAdapterFactory { *; }
```

does not seem to do the trick. Code still goes through [this execution path](https://github.com/square/retrofit/blob/2613d174be2e6f31f4f742e040412aee308849cf/retrofit-adapters/rxjava/src/main/java/retrofit2/adapter/rxjava/RxJavaCallAdapterFactory.java#L51) with the above configuration.

**Comment by JakeWharton** [comment]
-keepnames class rx.Single
