### ISSUE TITLE
RxJavaCallAdapter has wrong package name

### ISSUE THREAD

**Issue by JMieczkowski** [square/retrofit#1586]
When trying to add the RxJavaCallDapterFactory to Retrofit, the compiler is telling me the .addCallAdapter expects a retrofit2.CallAdapter.Factory and I'm passing in retrofit.RxJavaCallAdapterFactory

It looks like someone forgot to update the packname

`compile 'com.squareup.retrofit2:retrofit:2.0.0-beta4'`
`compile 'com.squareup.retrofit:adapter-rxjava:2.0.0-beta2'`

`Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(baseUrl)
                .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                .build();`

**Comment by JakeWharton** [comment]
Don't use different versions of Retrofit components. They are incompatible. Use the new groupId and version 2.0.0-beta4 for the adapter.
