### ISSUE TITLE
Unable to get MockRetrofit working

### ISSUE THREAD

**Issue by pmellaaho** [square/retrofit#1589]
I tried following the example from Retrofit examples (SimpleMockService.java) to be able to use MockRetrofit in a Espresso test. The error I get when executing the is: java.lang.ClassCastException: rx.internal.util.ScalarSynchronousObservable cannot be cast to java.util.List 

The code is available here: [MainActivityTest](https://github.com/pmellaaho/RxApp/blob/MockRetrofit/app/src/androidTest/java/net/pmellaaho/rxapp/MainActivityTest.java)

There are two branches in my example app. Master which uses Mockito in test and is working and MockRetrofit.

**Comment by JakeWharton** [comment]
Use
```
mDelegate.returningResponse(tstList).contributors(owner, repo);
```
Basically: don't worry about wrapping your actual response data when you call the delegate.
