### ISSUE TITLE
MoshiConverterFactory should have a lenient option

### ISSUE THREAD

**Issue by swankjesse** [square/retrofit#1592]
https://github.com/square/moshi/issues/132

**Comment by NightlyNexus** [comment]
What are thoughts here?
Should all adapters be lenient or not lenient?
I suppose if you want only certain adapters to be lenient, you can easily make your own factory.

**Comment by JakeWharton** [comment]
Definitely not be default

**Comment by JakeWharton** [comment]
I think I'd do an asLenient() that returned a new lenient factory from an
existing one.

**Comment by NightlyNexus** [comment]
Right, not by default, but it will be a factory that makes all adapters lenient. I'm not sure if that's truly useful, but perhaps.

**Comment by JakeWharton** [comment]
fb94144db40f8d403ba57799b61e9547cb349b34
