### ISSUE TITLE
Upgrade OkHttp to 3.1.2, 3.1.1 has Certificate pinning vulnerability

### ISSUE THREAD

**Issue by kozmic** [square/retrofit#1593]
OkHttp 3.1.1 has a vulnerability related to its certificate pinning functionality. This is fixed in 3.1.2, so it would be nice if Retrofit would pull in a safe version of OkHttp.

Details: https://publicobject.com/2016/02/11/okhttp-certificate-pinning-vulnerability/

**Comment by JakeWharton** [comment]
We're the same people who work on OkHttp, so we're aware. We wouldn't ship
without updating to the latest.

**Comment by swankjesse** [comment]
The cert pinning vulnerability is fixed in 3.1.0, but that had its own issues with Robolectric etc.
