### ISSUE TITLE
Possibility to use @POST without url and @Url prameter

### ISSUE THREAD

**Issue by lsuski** [square/retrofit#1595]
Hi,
I have following configuration
`builder.baseUrl("https://example.com/test/")`

and service
`@POST(" ")
	Call<TestResult> test(@Body TestRequest request);`

All requests in all services have same url which is equal to baseUrl

Above configuration works because of space in `@POST` annotation. 
Another workaround is:
`@POST
	Call<TestResult> test(@Url emptyUrl,@Body TestRequest request);`

I think that below configuration should also work but it is not. Is there any reason for that?
`@POST
	Call<TestResult> test(@Body TestRequest request);`

In Retrofit 1.9 this configuration worked:
`@POST("/")
	Call<TestResult> test(@Body TestRequest request);`

**Comment by JakeWharton** [comment]
You can use `./` instead of a space which makes it very explicit that you want the base URL as-is and isn't a workaround. I responded with a little more detail on #1567, but we don't feel it's worth the special case for something which is not common.

**Comment by lsuski** [comment]
Ok, thanks for the answer
