### ISSUE TITLE
GET request with response code 100 will timeout on android 4.4.4

### ISSUE THREAD

**Issue by suau** [square/retrofit#1597]
retrofit: 2.0.0-beta4
okhttp3 logging-interceptor: 3.1.2

My server responds to a GET request with status code 100 and empty body, if the client version has a newer timestamp.
This works fine on android 6.0.1, but times out on android 4.4.4.
I'm not sure if it's retrofit,okhttp or okio causing the issue.

here is the logcat:
`02-13 15:33:13.923 26491-1232/com.mypackage:sync D/OkHttp: --> GET https://server.url/api/user?m=1455348793829 http/1.1
02-13 15:33:13.923 26491-1232/com.mypackage:sync D/OkHttp: Authorization: Bearer token
02-13 15:33:13.923 26491-1232/com.mypackage:sync D/OkHttp: --> END GET
02-13 15:33:34.638 26491-1232/com.mypackage:sync W/System.err: java.net.SocketTimeoutException: timeout
02-13 15:33:34.643 26491-1232/com.mypackage:sync W/System.err:     at okio.Okio$3.newTimeoutException(Okio.java:207)
02-13 15:33:34.643 26491-1232/com.mypackage:sync W/System.err:     at okio.AsyncTimeout.exit(AsyncTimeout.java:250)
02-13 15:33:34.648 26491-1232/com.mypackage:sync W/System.err:     at okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
02-13 15:33:34.648 26491-1232/com.mypackage:sync W/System.err:     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
02-13 15:33:34.648 26491-1232/com.mypackage:sync W/System.err:     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
02-13 15:33:34.653 26491-1232/com.mypackage:sync W/System.err:     at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
02-13 15:33:34.653 26491-1232/com.mypackage:sync W/System.err:     at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)
02-13 15:33:34.653 26491-1232/com.mypackage:sync W/System.err:     at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125)
02-13 15:33:34.653 26491-1232/com.mypackage:sync W/System.err:     at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:723)
02-13 15:33:34.653 26491-1232/com.mypackage:sync W/System.err:     at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:81)
02-13 15:33:34.658 26491-1232/com.mypackage:sync W/System.err:     at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:708)
02-13 15:33:34.658 26491-1232/com.mypackage:sync W/System.err:     at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:563)
02-13 15:33:34.658 26491-1232/com.mypackage:sync W/System.err:     at okhttp3.RealCall.getResponse(RealCall.java:241)
02-13 15:33:34.658 26491-1232/com.mypackage:sync W/System.err:     at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
02-13 15:33:34.658 26491-1232/com.mypackage:sync W/System.err:     at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:203)
02-13 15:33:34.658 26491-1232/com.mypackage:sync W/System.err:     at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
02-13 15:33:34.658 26491-1232/com.mypackage:sync W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
02-13 15:33:34.658 26491-1232/com.mypackage:sync W/System.err:     at okhttp3.RealCall.execute(RealCall.java:57)
02-13 15:33:34.658 26491-1232/com.mypackage:sync W/System.err:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:177)
02-13 15:33:34.658 26491-1232/com.mypackage:sync W/System.err:     at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:87)
02-13 15:33:34.658 26491-1232/com.mypackage:sync W/System.err:     at com.mypackage.SyncAdapter.syncAppUser(SyncAdapter.java:101)
02-13 15:33:34.658 26491-1232/com.mypackage:sync W/System.err:     at com.mypackage.SyncAdapter.onPerformSync(SyncAdapter.java:83)
02-13 15:33:34.658 26491-1232/com.mypackage:sync W/System.err:     at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
02-13 15:33:34.663 26491-1232/com.mypackage:sync D/SyncAdapter: IOException: java.net.SocketTimeoutException: timeout`

**Comment by JakeWharton** [comment]
> My server responds to a GET request with status code 100 and empty body, if the client version has a newer timestamp.

Any reason it doesn't use a 302 which is much more standard?

> This works fine on android 6.0.1, but times out on android 4.4.4.

There should be no difference between these two versions since the OkHttp is the same. The exception indicates a timeout, which is what I would expect if a server returned a 100 and then nothing else.

Are you sure it works on 6.0?

**Comment by suau** [comment]
> Any reason it doesn't use a 302 which is much more standard?
I wasn't really sure which status code to use, I've switched to 409 for now. Wouldn't 302 suggest a redirect ?

> Are you sure it works on 6.0?
I'll create a minimal example and try it again, as soon as I have a little more time.

**Comment by tramonex-james** [comment]
I saw this too, I am testing against responses from external service with HTTP status codes of 1XX **Continue,** 3XX **Multieple Choices,** 4XX **Bad Request**, and 5XX **Internal Server Error**.

Only 100 **Continue** status caused a timeout.

**Comment by knowncolor** [comment]
I saw this too, I am testing against responses from external service with HTTP status codes of 1XX **Continue,** 3XX **Multieple Choices,** 4XX **Bad Request**, and 5XX **Internal Server Error**.

Only 100 **Continue** status caused a timeout.

**Comment by swankjesse** [comment]
Fixed on current versions of OkHttp.
