### ISSUE TITLE
retrofit multipart JSON must start with an array or an object (multipart post)

### ISSUE THREAD

**Issue by jkwiecien** [square/retrofit#1598]
I know this was a known issue, but I don't think it's resolved. Actually the mechanism stopped working for me while upgraded to one of retrofit2 beta versions (probably from beta2 to beta3);    

This was method declaration I used:
```@Multipart
    @POST("media/savePhoto")
    Observable<Photo> uploadPicture(@Part("file\"; filename=\"image.jpg") RequestBody photo, @Part("order") Integer order);```

I'm getting ```retrofit multipart JSON must start with an array or an object``` while trying to execute it and it appears that the reason is the second param ```@Part("order") Integer order``` because there is no exception when I'm removing it.  Unfortunately I need to pass that param in the same request.

**Comment by AlexBlokh** [comment]
are there any solutions on that?

**Comment by mhousser** [comment]
Same here. Went from beta2 to beta4, and image uploading is one of the last pieces that I just can't get working. Upgrading Retrofit is always the lib I dread updating the most. :(

**Comment by mhousser** [comment]
"JSON must start with an array or an object."

```
    @Multipart
    @POST("images")
    Call<ImageResponse> createImage(
            @Part("image\"; filename=\"image.jpg\" ") RequestBody image,
            @Part("lat") double lat,
            @Part("lng") double lng,
            @Part("type") ImageType type,
            @Part("description") String description,
            @Part("prize_id") Integer prizeId);
```

**Comment by Allsimon** [comment]
See #1443

**Comment by JakeWharton** [comment]
See the issue @Allsimon linked for this.

**Comment by amansingh005** [comment]
I'm also getting same error **JSON must start with an array or an object**.  Any leads ???   Please help me

@Multipart
    @POST("/upload/savePics")
    Call<PODResponse> postFile(
            @Part("empsno") String empsno,
            @Part("storesno") String storesno,
            @Part("lrSno") String lrSno,
            @Part("recQty") String recQty,
            @Part("recVol") String recVol,
            @Part("recWgt") String recWgt,
            @Part("damageQty") String damageQty,
            @Part("looseQty") String looseQty,
            @Part("deliveryDate") String deliveryDate,
            @Part("deliveryTime") String deliveryTime,
//            @Part("uploadFile") RequestBody file,
            @Part("uploadFile\"; filename=\"audex.jpg\" ") RequestBody part,
            @Part("remarks") String remarks,
            @Part("receivedBy") String receivedBy,
            @Part("ipAddress") String ipAddress
    );

   compile 'com.squareup.retrofit2:retrofit-converters:2.0.0-beta3'
    compile 'com.squareup.retrofit2:converter-gson:2.0.0-beta3'
    compile 'com.squareup.retrofit2:retrofit:2.0.0-beta3'

  private void uploadFile(Uri fileUri) {


        File file = new File(fileUri.getPath());
        if (file.exists()) {
            Retrofit retrofit = new Retrofit.Builder()
                    .baseUrl(BASE_URL)
                    .addConverterFactory(GsonConverterFactory.create())
                    .build();

            MediaType MEDIA_TYPE_PNG = MediaType.parse("multipart/form-data");

            AudexInterface service = retrofit.create(AudexInterface.class);

            RequestBody requestFile = RequestBody.create(MEDIA_TYPE_PNG, file);
            Log.e(TAG, "uploadUri: " + strEmpsno + " " + strStoreSno + "  " + strLrno + "  " + strRecqty + "  " + strDeliverydate + " " + strDeliverytime);
            Call<PODResponse> call = service.postFile(strEmpsno, strStoreSno, strLrno, strRecqty, strRecvol,
                    strRecwgt, strDamageqty, strLooseqty, strDeliverydate
                    , strDeliverytime, requestFile, strRemarks, strReceivedby,
                    strIpaddress);
         call.enqueue(new Callback<PODResponse>() {
             @Override
             public void onResponse(Response<PODResponse> response) {
                 Log.e(TAG, "onResponse:uploadUri "+response.isSuccess() );
                 if (response.isSuccess()){
                     Log.e(TAG, "uploadUri: " +response.body().getResult());
                 }
             }

             @Override
             public void onFailure(Throwable t) {
                 Log.e(TAG, "onFailure:uploadUri "+t.getLocalizedMessage() );
             }
         });
        }
       
    }

**Comment by Allsimon** [comment]
This is literally answered just above... :pensive: 

Your code should be
```
    if (file.exists()) {
        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(BASE_URL)
                .addConverterFactory(ScalarsConverterFactory.create())
                .addConverterFactory(GsonConverterFactory.create())
                .build();```

**Comment by amansingh005** [comment]
@Allsimon thanks for your reply. Can you please tell me which version of ScalarsConverterFactory i should use to achieve this? because when I run this code, server is replying like "insert you image". All data is inserting correctly except image

**Comment by Allsimon** [comment]
Same version of your other converters (2.0.0-beta3)...
You might want to double check with a proxy like Charles to see if your image isn't sent to server, but I doubt it

Your issue now seems to come from the server here (is the part's name really `uploadFile` ?)
You will receive more meaningful answers on StackOverflow or on the server logs

**Comment by amansingh005** [comment]
Yes , uploadFile is right. I'm able to post is using Rest(Chrome Extensiion). but when trying by using retrofit2, its asking for "insert image"
