### ISSUE TITLE
setting encoded=true on @Query still encodes the value

### ISSUE THREAD

**Issue by kudanai** [square/retrofit#1599]
I've seen some similar issues around regarding @Path annotations. I'm having issues with (example below)

    @Get("urlpath")
    Call<SomeClass> getSomething(@Query(value="v",encoded=true) String valueForV)

and passing in a `valueForV` such as `content/list/2?count=300`. Which yeilds 

    http://api.someservice.com/urlpath/?v=content/list/2?count%3D300

instead of

    http://api.someservice.com/urlpath/?v=content/list/2?count=300

So the value is still obviously being encoded. Is this expected behaviour or is there another way to do this?

It's a bit silly, I know, but it's a proxy URL which passes down the parameter to another system after some validation.

using `retrofit2.0.0-beta4`

**Comment by JakeWharton** [comment]
Query encoding is handled by OkHttp's [`HttpUrl`][1] class (specifically, `addEncodedQueryParam`), not Retrofit. It is the mechanism through which Retrofit assembles URLs. If you have an issue with its behavior then you'll need to file an issue on its project: https://github.com/square/okhttp/issues.

 [1]: https://square.github.io/okhttp/3.x/okhttp/okhttp3/HttpUrl.html
