### ISSUE TITLE
Submit Iterable/array types to the registered converter factories

### ISSUE THREAD

**Issue by michael-andre** [square/retrofit#1602]
If the type of a `@Query` or a `@Header` parameter is an Iterable or an array, this type is actually not submitted at all to the registered converter factories. Instead, for a `@Query`, only the converter for the parameterized type is resolved and the query is built with "`param=item1&param=item2&...`".

It would be nice to allow a factory to override that behavior in `stringConverter`, e.g. to switch to `param=item1,item2,...` or `param=[item1,item2,...]` or anything else.
That would imply, in the `RequestFactoryParser`, to first submit the `parameterType` to the factories, then to fallback to the current behavior if no converter was provided.

**Comment by JakeWharton** [comment]
We're going to this with #626. A converter shouldn't have to care about the packaging of the objects it's converting (be it array, iterable, multimap, or anything else) and it would greatly complicate things. Instead we're going to make the internal mechanism for figuring out what to do with a parameter pluggable.
