### ISSUE TITLE
@Delete with @Field is not working

### ISSUE THREAD

**Issue by sanjay4one** [square/retrofit#1606]
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
@RestMethod(value = "DELETE", hasBody = true)
public @interface BODY_DELETE {
    String value();
}

@Documented
@Target(ElementType.ANNOTATION_TYPE)
@Retention(RetentionPolicy.RUNTIME)
public @interface RestMethod {
    String value();
    boolean hasBody() default false;
}

@FormUrlEncoded
@BODY_DELETE("abc/v1/albums/{album_id}/images")
Call<ApiResponse> deleteAlbumImages(@Path("album_id") String albumId,@Field("ids") String jsonIds,@Header("Authorization") String apiKey);

I am trying send delete request by using above code. But still it's not working.
Help me on this.

**Comment by JakeWharton** [comment]
> not working

how?

**Comment by sanjay4one** [comment]
When I am calling delete request with @Field then nothing happens. Even it doesn't throw any exception.I am trying to call Delete request where I am sending a string field to my server.

**Comment by JakeWharton** [comment]
Turn on full logging. What gets logged?
