### ISSUE TITLE
Custom Http Request without Annotation 

### ISSUE THREAD

**Issue by Abdelsattar** [square/retrofit#1607]
i'm trying to make the request more dynamically and don't annotate with @Get or @POST and make dynamically from the code 
how it can be done here With retrofit?

**Comment by JakeWharton** [comment]
There is no way to do this and we have no plans to support it at this time. For starters, only one of those methods requires an HTTP body while the other does not. The most dynamism you can hope to achieve with Retrofit is having two methods for each HTTP method and conditionally calling the right one.

When you get to that level of dynamism the benefits of using Retrofit start to diminish and you might want to just use OkHttp for doing HTTP directly.
