### ISSUE TITLE
How to implement TypeAdapterFactory in Retrofit 2?

### ISSUE THREAD

**Issue by mobDevKz** [square/retrofit#1611]
I am working with an API that always responds in two ways:
1) Success:

{
status : "ok"
response : {
...
}
}

2) Failure

{
status : "error"
runtimeError : {...}
}

I don’t want to create an object for the entire JSON, but only for the content, so I implemented TypeAdapterFactory. The snippet of code is the following, where I register it : 

private static Gson gson = new GsonBuilder()
            .registerTypeAdapterFactory(new ItemTypeAdapterFactory())
            .create();

private static Retrofit.Builder builder =
            new Retrofit.Builder()
                    .baseUrl(Consts.URL_BASE)
                    .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                    .addConverterFactory(GsonConverterFactory.create(gson));

Implementation of TypeAdapterFactory is the following:

public <T> TypeAdapter<T> create(Gson gson, final TypeToken<T> type) {

        Log.e("@ItemTypeAdapterFactory", "create");

        final TypeAdapter<T> delegate = gson.getDelegateAdapter(this, type);
        final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);

        return new TypeAdapter<T>() {

            public void write(JsonWriter out, T value) throws IOException {
                delegate.write(out, value);
            }

            public T read(JsonReader in) throws IOException {

                JsonElement jsonElement = elementAdapter.read(in);
                if (jsonElement.isJsonObject()) {
                    JsonObject jsonObject = jsonElement.getAsJsonObject();

                    if (jsonObject.has("status")) {

                        String status = jsonObject.get("status").getAsString();

                        if (status != null && status.equalsIgnoreCase("ok")) {
                            if (jsonObject.has("response") && jsonObject.get("response").isJsonObject()) {
                                jsonElement = jsonObject.get("response");
                            }
                        } else { //status.equalsIgnoreCase(Consts.STATUS_ERROR)
                            if (jsonObject.has("runtimeError") && jsonObject.get("runtimeError").isJsonObject()) {
                                jsonElement = jsonObject.get("runtimeError");
                            }
                        }
                    }
                }

                return delegate.fromJsonTree(jsonElement);
            }
        }.nullSafe();
    }

But it does not work. Could you please help me? What am I doing wrong?

**Comment by a284628487** [comment]
I have the same needs，here is my solution
```
    public class Result<T, E> {
        public String status;
        public T response;
        public E runtimeError;
    }
```

**Comment by JakeWharton** [comment]
There's an example of enveloping here: https://github.com/segmentio/retrofit-jsonrpc/blob/master/jsonrpc/src/main/java/com/segment/jsonrpc/JsonRPCConverterFactory.java. You're better off doing it at the `Converter` level not as a `TypeAdapter`.

We're going to pull a version of that project into the `samples` eventually. Adding a simple enveloping example (which isn't JSON-RPC) is probably a good idea too.

**Comment by mobDevKz** [comment]
a284628487, JakeWharton thank you very much for your answers. I still don't understand how to resolve this problem using your approaches. I would be grateful if you provide examples. For now I made the following, but don't know whether this is a good approach or not. I parse result in interceptor

public class StatusInterceptor implements Interceptor {

    @Override
    public Response intercept(Chain chain) throws IOException {
        Request original = chain.request();

        Response response = chain.proceed(original);
        String responseBodyString = response.body().string();

        if (response.isSuccessful()) {

            try {
                JSONObject jsonObject = new JSONObject(responseBodyString);

                if (jsonObject != null) {

                    if (Utils.isElementOk(jsonObject, Consts.STATUS)) {

                        if (jsonObject.getString(Consts.STATUS).equalsIgnoreCase(Consts.STATUS_OK)) {

                            if (Utils.isElementOk(jsonObject, Consts.RESPONSE)
                                    && jsonObject.getString(Consts.RESPONSE) != null) {
                                responseBodyString = jsonObject.getString(Consts.RESPONSE);
                            }
                        }
                    }
                }

            } catch (JSONException e) {
                e.printStackTrace();
            }
        } else {

            try {
                JSONObject jsonObject = new JSONObject(responseBodyString);

                if (jsonObject != null) {

                    if (Utils.isElementOk(jsonObject, Consts.STATUS)) {

                        if (jsonObject.getString(Consts.STATUS).equalsIgnoreCase(Consts.STATUS_ERROR)) {

                            if (Utils.isElementOk(jsonObject, Consts.RUNTIME_ERROR)
                                    && jsonObject.getString(Consts.RUNTIME_ERROR) != null) {
                                responseBodyString = jsonObject.getString(Consts.RUNTIME_ERROR);
                            }
                        }
                    }
                }

            } catch (JSONException e) {
                e.printStackTrace();
            }
        }

        Log.e("StatusInterceptor", "" + responseBodyString);

        // Customize or return the response
        return response.newBuilder()
                .body(ResponseBody.create(response.body().contentType(), responseBodyString))
                .build();
    }
}

**Comment by JakeWharton** [comment]
I wouldn't do it as an interceptor since then you have to parse JSON. It's much better to happen inside a `Converter` where you can deal with the Java object representation.

**Comment by JCarlosR** [comment]
Retrofit is really good when the JSON format is defined (I have used a lot of webservices), but now I am trying to interact with the server, and the response is different in some cases.
Please give us a simple way to do it (the JsonRPCConverterFactory example seems complicated for me).

**Comment by JakeWharton** [comment]
Retrofit has nothing to do with (de)serializing the response from the server. If it's dynamic then that's between you, the type system, and the serialization library that you are using.

Since the original question was answered, closing.
