### ISSUE TITLE
MockRetrofit: Simplify building a call with HTTP headers.

### ISSUE THREAD

**Issue by hastebrot** [square/retrofit#1614]
Does it make sense to add a convenience method to `retrofit2.Response`, that allows passing custom HTTP headers? There are some cases where I need to modify them, for instance the GitHub API uses a `"Link"` in header to return next and previous URLs of pagination.

I currently reuse the code from `Response.success(body)` where `okhttp3.Response.Builder()` is used and additionally call `addHeader()`. There could be the static method `Response.success(body, headers)`, where headers is of type `okhttp3.Headers`.

Should I create a PR?

**Comment by JakeWharton** [comment]
Sure, that's fine. Please include a test.

**Comment by JakeWharton** [comment]
Merged as 85186ec1b5232263fe0ecbda790f4911215658f6
