### ISSUE TITLE
Why using retrofit post request, server get the parameter is inputstream?

### ISSUE THREAD

**Issue by blindfate** [square/retrofit#1617]
I use retrofit 2.0 post form request, but the server get the parameter is inputstream, but server want not the parameter is inputstream.

Some code like this:
```
    @FormUrlEncoded
    @POST(Api.SEARCH_CONTACTS)
    public Call<ResultModel<PageModel<Contacts>>> searchContacts(@Field("parameter") String searchText, @Field("switchs") int mode, @Field("page") int page, @Field("size") int size);
```

Server code:

```
@RequestMapping(value="user/list", method=RequestMethod.POST)
 	public void getUsersList(HttpServletRequest request,HttpServletResponse response){
		try{ 
			String input = inputSteamToString(getRequeset().getInputStream());
                      //System.out.println(input);
		}catch (Exception e) {
			//do nothing
 		}
 	}
```

getRequeset().getInputStream() is not empty.

Help me, tks!

**Comment by JakeWharton** [comment]
I don't really understand what you're asking, but this seems to have nothing to do with Retrofit since you're asking about whatever server framework is in use. This type of question is far better suited for StackOverflow since it's a usage question of whatever that server library is.
