### ISSUE TITLE
Can't sign APK when using ProGuard.

### ISSUE THREAD

**Issue by yanaperhun** [square/retrofit#1618]
I use com.squareup.retrofit2:retrofit:2.0.0-beta4 Retrofit version. Gradle version - 2.8. Without Retrofit library in project i can create Signed APK. 
I created empty project in AndroidStudio for testing this bug. I added only 
`compile 'com.squareup.retrofit2:retrofit:2.0.0-beta4' ` string  in app.gradle and added in proguard-rules.pro this code:

`-dontwarn retrofit2.**
-keep class retrofit2.** { *; }
-keepattributes Signature
-keepattributes Exceptions`

When I try to generate Signed APK with ProGuard, Gradle Build Running process doesn't end I waited a long time. And i see in Gradle Console this message:

`...

:app:compileReleaseJavaWithJavac
:app:compileReleaseNdk UP-TO-DATE
:app:compileReleaseSources
:app:processReleaseJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForRelease
:app:transformClassesAndResourcesWithProguardForRelease`

And later this error:

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> java.io.IOException: Please correct the above warnings first.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED`

What's the problem? Can you help me, please, because i can't release app.

**Comment by JakeWharton** [comment]
This is a usage problem with ProGuard, not a problem with Retrofit. We aren't ProGuard users so aren't able to help. Your best bet is to ask on StackOverflow with the 'proguard' and 'retrofit' tags. You might also want to include the info output as the above log doesn't really give any indication of what failed.
