### ISSUE TITLE
Error Long value parsing - Numeric value (1456027500000) out of range of int

### ISSUE THREAD

**Issue by dekrandroid** [square/retrofit#1620]
Retrofit + JacksonConverter failed to parse the json file in attach ( file fermate.json). It looks JacksonConverter makes wrong decision to convert int instead of long value.
[ParsingIntToLongException.zip](https://github.com/square/retrofit/files/139569/ParsingIntToLongException.zip)

**Comment by JakeWharton** [comment]
Retrofit takes no part in deserialization. This is a problem with the Jackson library and should be reported there.
