### ISSUE TITLE
@Query can't disable URL encoding for query value name. Retrofit 2.0 beta 4

### ISSUE THREAD

**Issue by gmjgh** [square/retrofit#1622]
@GET("/{cur_list}")
        Call<List<Currency>> makeRequest(@Path(value = "cur_list") String url, @Query(value = "json&exchange&coursid", encoded = true) int coursid);

it works the same way with encoded = false for @Query. 
I think one of those must disable URL encoding for the value of @Query - but those two(encoded = false  and encoded = true for @Query) work the same.

I guess it is a bug. Retrofit 2.0 beta 4

**Comment by JakeWharton** [comment]
Ampersand is an invalid value in an encoded query key as it is also a separator between key/value pairs so it is automatically corrected to the proper encoded form. Additionally, the `encoded` setting only applies to the value, not the key.

Retrofit has no control over this behavior. It comes from using OkHttp's `HttpUrl` class (`addEncodedQueryParameter` method) to build the URL.

**Comment by gmjgh** [comment]
Thanks. But there are cases with bad, not fixable API from server, when this restrictions can be pretty difficult to workaround. Retrofit 1.9 was more flexible in similar cases. Anyway, I've understood. Thanks again. Your and Square libs are pretty awesome.)
