### ISSUE TITLE
Cutting off part of base URL Retrofit 2.0 beta 4

### ISSUE THREAD

**Issue by gmjgh** [square/retrofit#1623]
When using @GET, @POST etc. requests if you put @GET("/{cur_list}") slash before value Retrofit cuts of a part of base URL - in my case https://api.privatbank.ua/p24api/ becomes https://api.privatbank.ua/ .
When slash is removed all works fine. Retrofit 2.0 beta 4

**Comment by JakeWharton** [comment]
A leading slash indicates an absolute path on the host. Without the leading slash the path is relative to the base URL.

This is [documented on `baseUrl`][1] on the `Retrofit.Builder`.

 [1]: http://square.github.io/retrofit/2.x/retrofit/retrofit2/Retrofit.Builder.html#baseUrl-okhttp3.HttpUrl-

**Comment by gmjgh** [comment]
Thanks. But this behavioral diversity in alike methods... it's a bit confusing.

**Comment by MostafaEbrahimi** [comment]
Yes!A bit confusing! After 3 hours of debugging I found that `baseurl` has been cut after `/` .
Please add this notice in your document for developers :)
Thanks for your beauty Lib :)

**Comment by JakeWharton** [comment]
It's already documented on baseUrl.

**Comment by MostafaEbrahimi** [comment]
Thanks :D
