### ISSUE TITLE
Multiple Image Upload Requests Using PartMap failing

### ISSUE THREAD

**Issue by embydextrous** [square/retrofit#1626]
I am trying to upload multiple images using Retrofit 2-beta 4. I am using PartMap for it.

The APIService method looks like:

```
 @Multipart
    @POST("/feedback/add")
    Call<ApiResponse> sendFeedbackWithImage(
            @Part("token") RequestBody token,
            @Part("subject") RequestBody subject,
            @Part("message") RequestBody message,
            @PartMap() Map<String, RequestBody> images);

```

In the code I am setting map values like:
```
map.put(images\";filename=\"image"+i+"\" ", imageFile);

```

I am not getting error on my test device but I am not able to identify if the
 image is sent to the server or if it has been sent than in what format.

02-24 16:25:57.961 9918-14402/com.listup.android D/OkHttp: Content-Type: multipart/form-data; boundary=ca30d2f6-1415-4437-89ae-71acd0a0a7cd

02-24 16:25:57.966 9918-14402/com.listup.android D/OkHttp: ������JFIF����������������C��: %# , #&')*)-0-(0%()(����C
(((((((((((((((((((((((((((((((((((((((((((((((((((����0d"�������������������������    02-24 16:25:57.966 9918-14402/com.listup.android D/OkHttp: �����������}��!1AQa"q2���#B��R��$3br�   

I know the solution in retrofit 1 but I want to use retrofit 2. 

What I actually want is that I have to send an array of images and number of images can be variable.

**Comment by embydextrous** [comment]
I don't know if I am doing something wrong or the information is insufficient. Help me Jake!!

**Comment by shakil807g** [comment]
Many people have been repeating this workaround, but this does not work with all servers:

@Part("profile\"; filename=\"image.jpg\"")
This is wrong; it generates an extra quote. Should be:

@Part("profile\"; filename=\"image.jpg")
Formatted this way, the workaround does work for me.

**Comment by JakeWharton** [comment]
It looks like valid JPEG bytes (which you really shouldn't be logging the body of, not that it will hurt).

> I am not able to identify if the image is sent to the server or if it has been sent than in what format.

We're not going to be able to help here any more than you since we can't know which server, how it's processing, and what it expects.

Without a sample or test case that somehow demonstrates a problem with Retrofit, there's not really anything we can do to help here.

**Comment by zoricacareva** [comment]
If you want to send multiple files with Retrofit 2, I implemented a workaround 
`@Part("image\"; filename=\"image.jpg\" ") List<RequestBody> files`
My issue was with a .NET web api running on IIS.

**Comment by JakeWharton** [comment]
You don't need a workaround, as List<MultipartBody.Part> works.

**Comment by zoricacareva** [comment]
In my case it doesn't work. It works only if I have one item in the list.

**Comment by JakeWharton** [comment]
File a bug with a failing test case then!
