### ISSUE TITLE
ErrorHandlingCallAdapter callback is running on Okhttp thread not main thread

### ISSUE THREAD

**Issue by xperad** [square/retrofit#1627]
Hello~
I used ErrorHandlingCallAdapter class to customize default retrofit Callback.

src/main/java/com/example/retrofit/ErrorHandlingCallAdapter.java

below is my source.
```
call.enqueue(new MyCallback<MyModel>() {
    @Override
    public void success(Call<MyModel> call, Response<MyModel> response) {
        >> this is Okhttp thread not main thread!
    }
    @Override
    public void unauthenticated(Call<MyModel> call, Response<?> response) {
        >> this is Okhttp thread not main thread!
    }
    ...
}
```

I can't do like showing android dialog. because callback was not on main thread.
I'm using retrofit-2.0.0-beta4.jar library.
What is wrong?

**Comment by JakeWharton** [comment]
#1639 made the default callback `Executor` exposed via `retrofit.callbackExecutor()`. I'll add another "TODO" to the sample, but I don't want to clutter it with the extra code required to implement this for the callback. It's a good bit of code that distracts from the sample.
