### ISSUE TITLE
can't intercept response headers before maybeCache()

### ISSUE THREAD

**Issue by morder** [square/retrofit#1629]
I have added an interceptor

``` java
Response originalResponse = chain.proceed(chain.request());
            Response responseCached = originalResponse.newBuilder()
                    .removeHeader("Pragma")
                    .header("Cache-Control", String.format("max-age=%d", 60))
                    .addHeader("Cache-Control", String.format("max-stale=%d", 60))
                    .build();
```
but retrofit calls maybeCache() from HttpEngine before my code
and cache is not working if server returns 
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache

I want to overwrite it, before cache choise

**Comment by JakeWharton** [comment]
You need to add your interceptor to OkHttp using `.addNetworkInterceptor` not `.addInterceptor`. This will put its logic between the Socket and OkHttp instead of between your calling code and OkHttp and allow changing the behavior of OkHttp's internals.
