### ISSUE TITLE
Custom response body converters on per-method basis

### ISSUE THREAD

**Issue by mikaelstaldal** [square/retrofit#1630]
It would be useful to be able to specify a custom Converter to be used on the response body on specific method only.

Something like:

```
@Target(METHOD)
@Retention(RUNTIME)
public @interface ResponseConverter {
    Class<?> value();
}
```

```
public class MyConverter implements Converter<ResponseBody, RichItem> {
    @Override
    public RichItem convert(ResponseBody value) throws IOException {
        // ...
    }
}
```

```
public interface SomeService {
    @GET("foo/bar")
    @ResponseConverter(MyConverter.class)
    Call<RichItem> fetchItem();
}
```

**Comment by JakeWharton** [comment]
You can build this yourself with a `Converter.Factory` that looks at the annotation and creates an instance of that type. The [`JsonAndXmlConverters`][1] example shows how to look at annotations on the method to determine what converter to use. It should be straightforward to adapt this to actually pull the converter class from your annotation (when present) and return it instead.

 [1]: https://github.com/square/retrofit/blob/120b55c18857e4e7390d1f6f74411e4d3b2f70b2/samples/src/main/java/com/example/retrofit/JsonAndXmlConverters.java

**Comment by JakeWharton** [comment]
We're considering a first-party API for linked sample on `Retrofit.Builder` post-2.0.
