### ISSUE TITLE
Single Abstract Method callback interfaces

### ISSUE THREAD

**Issue by mikaelstaldal** [square/retrofit#1631]
It would be nice if the `retrofit2.Callback` interface could be broken down into two Single Abstract Method interfaces to make it possible to use lambda expressions and method references in Java 8 and Android with [RetroLambda](https://github.com/orfjackal/retrolambda).

(I don't think that retrofit-adapters/java8 would work on Android.)

```
public interface SuccessCallback<T> {
  void onResponse(Response<T> response);
}
```

```
public interface FailureCallback {
  void onFailure(Throwable t);
}
```

```
public interface Call<T> extends Cloneable {
  // current stuff
  void enqueue(SuccessCallback<T> successCallback, FailureCallback failureCallback);
}
```

**Comment by JakeWharton** [comment]
This is too drastic of a change to make this late in developer for far too little benefit (no benefit, in my opinion). Thankfully, we have a mechanism where you can create this yourself using a custom `CallAdapter.Factory`. See the [`ErrorHandlingCallAdapter`][1] example to get you started.

 [1]: https://github.com/square/retrofit/blob/120b55c18857e4e7390d1f6f74411e4d3b2f70b2/samples/src/main/java/com/example/retrofit/ErrorHandlingCallAdapter.java

**Comment by mikaelstaldal** [comment]
I would say it is a huge benefit to be able to use Java 8 style lambda expressions and method references for callbacks on Android (with RetroLambda).

You could support both this and the current `Callback` by overloading the `enqueue` method in `Call`, then it will be backwards compatible.

**Comment by JakeWharton** [comment]
An HTTP call is a single unit of work and it delivers a single result (either a response or failure). As such, we actually value the coupling afforded by the dual-method callback.

**Comment by mikaelstaldal** [comment]
I just want to be able to code like this:

```
call.enqueue(
    response -> doStuffWith(response),
    failure -> handle(failure)
    );       
```

**Comment by swankjesse** [comment]
@mikaelstaldal you can build your class to bridge this yourself.
```
class LambdaCallback {
  public static LambdaCallback(SuccessCallback sucess, FailureCallback failure);
}

call.enqueue(new LambdaCallback(
    response -> doStuffWith(response),
    failure -> handle(failure)));
```

**Comment by nindzyago** [comment]
@swankjesse can you explain your code with Retrofit callbacks? it doesn't work for me
