### ISSUE TITLE
Platform callback executor not propagated to Retrofit instance.

### ISSUE THREAD

**Issue by mikaelstaldal** [square/retrofit#1632]
It would be nice if a custom `CallAdapter.Factory` could have access to the same callbackExecutor that the default `ExecutorCallAdapterFactory` has (with logic to use proper thread for Android and non-Android).

**Comment by JakeWharton** [comment]
It does. Call `callbackExecutor()` on the supplied `Retrofit` instance.

**Comment by mikaelstaldal** [comment]
It doesn't work, `Retrofit.callbackExecutor()` return null.
