### ISSUE TITLE
How to add public params?

### ISSUE THREAD

**Issue by HakuLess** [square/retrofit#1634]
I want to add a public para in all request, while i didn't find a way to do this.
I used Interceptor but can just add header para, how to add para for get/post param?

**Comment by renyedi** [comment]
Do you want to add a parameter to all calls? If so, you can write an interceptor for that: https://github.com/square/retrofit/blob/3c195a0cc0c95b82b59bf3f88f6eabed3eeb3621/retrofit/src/test/java/retrofit2/CallTest.java#L286

**Comment by JakeWharton** [comment]
What @renyedi said! Something like:
```java
Request request = chain.request();
request = request.newBuilder()
    .url(request.url().newBuilder().addQueryParam("foo", "bar").build())
    .build();
return chain.proceed(request);
```
