### ISSUE TITLE
Callback.onFailure() with Exception and don't catch Throwable

### ISSUE THREAD

**Issue by mikaelstaldal** [square/retrofit#1637]
Why does `retrofit2.Callback.onFailure()` have Throwable as parameter, and why does `retrofit2.OkHttpCall` catch Throwable?

Wouldn't it make more sense to have Exception given that it's usually not a good idea to catch something like OutOfMemoryError?

**Comment by JakeWharton** [comment]
The code is run on an `Executor` which at best logs the exception and at worst just silently swallows it. In both cases you get a crashed thread which is automatically replaced the next time one is needed.

Non-`IOException` instances of the `Throwable` passed to `onFailure()` indicate a cause worth of spectacular failure that should be propagated.
