### ISSUE TITLE
Retrofit Post method

### ISSUE THREAD

**Issue by sushildlh** [square/retrofit#1638]
What kind of issue is this?

 - [x] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by sushildlh** [comment]
Please any one please help .
This is My API mathod
 @POST("/user/new.json")
        Call<User> createUser(@Body User user);



this is call 
 Retrofit retrofit=new Retrofit.Builder().baseUrl("https://XXXXXX.firebaseio.com").addConverterFactory(GsonConverterFactory.create()).build();

        Api api=retrofit.create(Api.class);

        User user=new User(1,"Sam");

        Call<User> call=api.createUser(user);
        call.enqueue(new Callback<User>() {
            @Override
            public void onResponse(Call<User> call, Response<User> response) {
                Log.d("sam","run");
            }

            @Override
            public void onFailure(Call<User> call, Throwable t) {
                Log.d("sam","error");
            }
        });


Output is coming like that :-"user" : {
    "new" : {
      "-KBgcQTomo8xGpnv5raM" : {
        "id" : 1,
        "name" : "Sam"
      }

but i want output like that :- "user" : {
    "new"  : {
        "id" : 1,
        "name" : "Sam"
      }

**Comment by swankjesse** [comment]
If you want to ask how to do
something, or to understand why something isn't working the way you expect it to, use Stack
Overflow. https://stackoverflow.com/questions/tagged/retrofit
