### ISSUE TITLE
With Socket IO

### ISSUE THREAD

**Issue by whowazit** [square/retrofit#1642]
I'm using "compile 'com.github.nkzawa:socket.io-client:0.6.0'" and I also have retrofit for some API request. But when I use this code "mSocket.connect() (for the socket IO)", there is a FATAL error in OkHttp. This is the error.

03-02 17:48:16.575 25125-25508/com.shima.thebizgames E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
03-02 17:48:16.575 25125-25508/com.shima.thebizgames E/AndroidRuntime: java.lang.NoSuchMethodError: com.squareup.okhttp.internal.Internal.callEngineGetConnection
03-02 17:48:16.575 25125-25508/com.shima.thebizgames E/AndroidRuntime:     at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:154)
03-02 17:48:16.575 25125-25508/com.shima.thebizgames E/AndroidRuntime:     at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:42)
03-02 17:48:16.575 25125-25508/com.shima.thebizgames E/AndroidRuntime:     at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:102)
03-02 17:48:16.575 25125-25508/com.shima.thebizgames E/AndroidRuntime:     at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
03-02 17:48:16.575 25125-25508/com.shima.thebizgames E/AndroidRuntime:     at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
03-02 17:48:16.575 25125-25508/com.shima.thebizgames E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
03-02 17:48:16.575 25125-25508/com.shima.thebizgames E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
03-02 17:48:16.575 25125-25508/com.shima.thebizgames E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:856)

**Comment by JakeWharton** [comment]
This is a problem with Socket IO and how it interacts with OkHttp, not Retrofit.

**Comment by keyuraashra** [comment]
@JakeWharton Any suggestion to resolve this with any workaround? I am also facing the same problem in my application where I am using socket.io for chat.

**Comment by JakeWharton** [comment]
Consult Socket.io or the library for support. This has nothing to do with Retrofit.

**Comment by eneim** [comment]
In short: Update it to latest version.

Long ver: go to the lib's repo for quicker/proper place for support.

**Comment by ognev-zair** [comment]
I face the same problem with com.squareup.okhttp3:okhttp:3.3.0, socket.io can't open connect to socket
