### ISSUE TITLE
Allow null on @Path parameters

### ISSUE THREAD

**Issue by smeegoan** [square/retrofit#1651]
Hi,

When trying to use retrofit to call OData functions that support null values I am forced to create overloads for every possible combination of null values that the server function supports.

So for instance a function with the following signature: (A, C and D are nullable)

http:/host/odata/Fact/.SearchByName(A=null,B={b},C=null,D=null,E={e},F={f})
http:/host/odata/Fact/.SearchByName(A={a},B={b},C=null,D=null,E={e},F={f})
http:/host/odata/Fact/.SearchByName(A={a},B={b},C={c},D=null,E={e},F={f})
http:/host/odata/Fact/.SearchByName(A={a},B={b},C=null,D={d},E={e},F={f})
[...]

I can only put the null values on the Method value and not as a @Path parameter.

If I could somehow tell retrofit to allow null parameters on @Path that would make the client code much cleaner.

Regards

**Comment by JakeWharton** [comment]
So you're saying when you pass null you want the literal "null" string to
be put in as the replacement?

**Comment by smeegoan** [comment]
Yes!

**Comment by JakeWharton** [comment]
As a workaround you can use a wrapper object whose toString either
delegates to the real value or returns "null"

**Comment by smeegoan** [comment]
I followed your instructions and everything works as intended. Thanks.

Maybe you could consider adding @NullablePath annotation or something similar in the future.

**Comment by stewemetal** [comment]
IMHO calling this same function with optional parameters to basically reach multiple endpoints is kind of an antipattern. It can also lead to ambiguous usage in you upper architectural layers.

A better approach would be to define multiple methods in the API class corresponding to each kind of endpoint you have to call, for example:

```dart
@Get(path: "topic/{topicId}/{category}/{searchQuery}")
Future<Response<TopicContent>> searchTopicContent({
    @required @Path() int topicId,
    @required @Path() String category,
    @required @Path() String searchQuery,
});

@Get(path: "topic/{topicId}/{category}")
Future<Response<TopicContent>> searchTopicByCategory({
    @required @Path() int topicId,
    @required @Path() String category
});

@Get(path: "topic/{topicId}")
Future<Response<TopicContent>> getTopic({
    @required @Path() int topicId
});
```

On top of that, in Retrofit, `@Path` parameters may not be `null` at all. Passing `null` to a path parameter results in an `IllegalArgumentException`. This behavior should be introduced into chopper as well.

While we have the named optional parameter list syntax in Dart, it doesn't mean we have to use the parameters as optional. This will be more clear when nullable types will be introduced into stable Dart. When that happens, these parameters should never be allowed to be null in the first place and the code generator should fail to generate when path parameters are of nullable types. But until this utopian state of the language, we have to think a bit more on how we implement things with it. 😄
