### ISSUE TITLE
POST Request Automatcially Convertes in GET

### ISSUE THREAD

**Issue by zubyf09** [square/retrofit#1655]
I am Doing Post request using following Code
    
` @Headers("Content-Type: application/json")
    @POST("classes")
    Call<Playlist> addToPlaylist(@Body PlaylistParm parm);
`
But when request execute it show's GET in LOG.This api's works fine on POSTMAN and in IOS app as well.

![screen shot 2016-03-07 at 11 33 52 am](https://cloud.githubusercontent.com/assets/1938171/13562674/ac9c4f76-e45c-11e5-943a-de6526c37905.png)

**Comment by zubyf09** [comment]
Had same issue with PUT Request as well it is treating all request with GET ONLY

**Comment by JakeWharton** [comment]
Retrofit isn't an HTTP client so the behavior you are seeing is not from Retrofit. That said, you're likely getting an [HTTP 302][1] response which OkHttp is changing to GET in a the follow-up request per the behavior of all modern browsers. If you want the request to be retried with the same HTTP method then a 307 is the proper response code. You can use an OkHttp network interceptor to change 302 responses into 307 if you can't update the server.

 [1]: https://en.wikipedia.org/wiki/HTTP_302

**Comment by zubyf09** [comment]
@JakeWharton  my issue is resolved i just changed the Interface Like this sending header as param
` @Headers("Content-Type: application/json")
    @POST("user/classes")
    Call<Playlist> addToPlaylist(@Header("Authorization") String auth ,@Body PlaylistParm parm);
`
and it is working fine now.Before that i was adding header through code.I still don't know how it is working for me.It will be great if you can look my existing code which is mentioned below.
`public  <S> S creatServiceForGym(Class<S> serviceClass, String token,String tokentype) {

		HttpLoggingInterceptor logging = new HttpLoggingInterceptor();
		OkHttpClient.Builder httpClient = new OkHttpClient.Builder();

		logging.setLevel(HttpLoggingInterceptor.Level.BODY);

		if (token != null && tokentype != null) {
			String credentials = token + ":" + tokentype;
			final String basic =
					"Basic " + Base64.encodeToString(credentials.getBytes(), Base64.NO_WRAP);

			httpClient.addInterceptor(new Interceptor() {
				@Override
				public okhttp3.Response intercept(Interceptor.Chain chain) throws IOException {
					Request original = chain.request();

					Request.Builder requestBuilder = original.newBuilder()
							.header("Authorization", basic).method(original.method(), original.body());

					Log.i("", "TOken  "+requestBuilder.get().toString());
					Request request = requestBuilder.build();
					return chain.proceed(request);
				}

			}).addInterceptor(logging);
		}
		OkHttpClient client = httpClient.build();
		//httpClient.addInterceptor(logging);
		Retrofit.Builder builder =new Retrofit.Builder()
				.baseUrl(C.API_ROOT_URL)
				.addConverterFactory(GsonConverterFactory.create());

		Retrofit retrofit = builder.client(client).build();
		return retrofit.create(serviceClass);
	}
`
