### ISSUE TITLE
ObjectMapper.convertValue(Object, CustomClass.class) causes infinite loop

### ISSUE THREAD

**Issue by SanderVH** [square/retrofit#1656]
In a nutshell: 
Jackson's ObjectMapper().convertValue() method causes an infinite loop when trying to convert a generic Object (in this case, a LinkedHashmap) to my own POJO class.

Here's a code snippet of my case:

```
@JsonDeserialize(converter = CustomConverter.class)
public class CustomClass {
	@JsonProperty("prop1")
	public String firstProperty;
	
	@JsonProperty("prop2")
	@JsonDeserialize(converter = OtherObjectConverter.class)
	public OtherObject secondProperty;
	
	public CustomClass() { }
}

public class CustomConverter extends StdConverter<Object, CustomClass> {
	
	@Override
    public CustomClass convert(Object value) {
		//Object is of type LinkedHashmap
		//Try to convert it to our CustomClass class
		ObjectMapper mapper = new ObjectMapper();
		
		//This is where the code loops. The statement is executed over and over again without exiting.
		//Debugging 
		CustomClass cc = mapper.convertValue(value, CustomClass.class);
		
		//Other code here
		// ...
		
		return cc;
	}
}
```

What I'm trying to achieve:
I have several RetroFit HTTP methods set up that each receive different kinds of JSON. However, all Retrofit methods return the same kind of Java object, CustomClass.
The Converter is used to map the different JSON responses / Java POJOs to this single CustomClass.

Here's a more elaborate version of the CustomConverter:

```
public class CustomConverter extends StdConverter<Object, CustomClass> {
	@Override
    public CustomClass convert(Object value) {
		CustomClass cc = null;
	
		//Object is of type LinkedHashmap
		//Try to convert it to our CustomClass class
		ObjectMapper mapper = new ObjectMapper();
		
		//This is where the code loops. The statement is executed over and over again without executing.
		try {
			cc = mapper.convertValue(value, CustomClass.class);
		} catch(Exception ex) {
			cc = null;
		}
		
		if(cc == null) {
			//Mapping failed, so the 'value' is of another type
			OtherCustomClass occ = mapper.convertValue(value, OtherCustomClass.class);
			
			cc = new CustomClass();
			
			//Do mapping of OtherCustomClass to CustomClass here
		}
		
		//Other code here
		// ...
		
		return cc;
	}
}
```

Tested with:
com.squareup.retrofit2:retrofit:2.0.0-beta4
com.squareup.retrofit2:converter-jackson:2.0.0-beta4

and

com.squareup.retrofit:retrofit:2.0.0-beta2
com.squareup.retrofit:converter-jackson:2.0.0-beta2

**Comment by JakeWharton** [comment]
This doesn't really have anything to do with Retrofit. I would isolate the failure into a test case or sample that only uses the Jackson code and report it as a bug on the Jackson project or StackOverflow. Retrofit doesn't play any part in serialization other than calling the converter for each request and response.
