### ISSUE TITLE
Path encoding fails with =

### ISSUE THREAD

**Issue by PaulWoitaschek** [square/retrofit#1657]
When I RetroFit with a path that has to be encoded with a path that ends with a slash, i.e: `d29pdGFzY2hla0BnbWFpbC5jb20=`
```
    @GET("sendVerifyRegistrationEmail/{base64email}")
    Observable<Void> sendVerifyRegistrationEmail(@Path("base64email") String base64email);
````

It ends up not being encoded properly

`https://(...)sendVerifyRegistrationEmail/d29pdGFzY2hla0BnbWFpbC5jb20=`

Instead of the `=` it should properly encode as `%3D`

A hotfix is to set encoded = true on the annotation and use UrlEncoder.encode manually.

**Comment by swankjesse** [comment]
The `=` character does not need to be escaped in paths. If your webserver requires that, it is broken.

**Comment by PaulWoitaschek** [comment]
Thanks!
