### ISSUE TITLE
Disable URL encoding

### ISSUE THREAD

**Issue by LinkOut** [square/retrofit#1658]
@GET("/myUrl")
    void myGetExample(
            @Query("fields") String fields,
            Callback<List<MyObjects>> myObjects
    );
fields is : [a,b,c,d,e,f,g] but this is URL encoded, i do not want this.

How to prevent this behaviour?

**Comment by JakeWharton** [comment]
Specify `encoded = true` on the annotation.

Please direct future usage questions to StackOverflow.
