### ISSUE TITLE
@Url Annotation and HttpUrl

### ISSUE THREAD

**Issue by BraisGabin** [square/retrofit#1660]
Related with #1416. Why don't `@Url` annotation support `HttpUrl` parameters? `HttpUrl` is a very handy class to build urls and it's in the core of OkHttp.

**Comment by swankjesse** [comment]
It’s a limitation of Java annotations. Only a small number of types are available to ’em.

**Comment by veyndan** [comment]
For documentation purposes, since version [2.0.1](https://github.com/square/retrofit/blob/master/CHANGELOG.md#version-201-2016-03-30) this behaviour is supported.
