### ISSUE TITLE
Single Observable with Multiple Subscribers

### ISSUE THREAD

**Issue by pavlospt** [square/retrofit#1667]
What kind of issue is this?
Hello. 
I have an `Observable<<List<Foo>> getFoo()` that is created from a Retrofit Service and after calling the
`.getFoo()` method, I need to share it with Multiple Subscribers. Calling the `.share()` method though, it causes the Network Call to be re-executed. Replay Operator does not work either. I know that a potential solution might be `.cache()`, but I do not know why this behaviour is caused. 

```
Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(API_URL)
                .addConverterFactory(GsonConverterFactory.create())
                .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                .build();

        // Create an instance of our GitHub API interface.

        // Create a call instance for looking up Retrofit contributors.

        Observable<List<Contributor>> testObservable = retrofit
                .create(GitHub.class)
                .contributors("square", "retrofit")
                .share();


        Subscription subscription1 = testObservable
        .subscribe(new Subscriber<List<Contributor>>() {
            @Override
            public void onCompleted() {

            }

            @Override
            public void onError(Throwable throwable) {

            }

            @Override
            public void onNext(List<Contributor> contributors) {
                System.out.println(contributors);
            }
        });

        Subscription subscription2 = testObservable
                .subscribe(new Subscriber<List<Contributor>>() {
                    @Override
                    public void onCompleted() {

                    }

                    @Override
                    public void onError(Throwable throwable) {

                    }

                    @Override
                    public void onNext(List<Contributor> contributors) {
                        System.out.println(contributors + " -> 2");
                    }
                });

        subscription1.unsubscribe();
        subscription2.unsubscribe();
```

The code above can reproduce the aforementioned behaviour. You can debug it and see that the Lists received belong to a different MemoryAddress. 

I have also looked at ConnectableObservables as a potential solution, but this requires me carrying the original observable around, and calling `.connect()` each time I want to add a new Subscriber.

**Comment by JakeWharton** [comment]
Can you ask this question on StackOverflow with the 'retrofit' and 'rxjava' tags? The question actually has nothing to do with Retrofit since it just provides the observable. It's really a question about the usage of RxJava and we prefer it be in a place where others having the same problem with the library (RxJava, in this case) can find it in the future.

**Comment by pavlospt** [comment]
Actually the same behaviour was fine for Retrofit 1.9 and the `.share()` operator was working fine. So I guess this is more of a Retrofit question but I will also ask it on StackOverflow if someone else can provide more info on the issue.

**Comment by JakeWharton** [comment]
Both R1 and R2 use cold observables that make a request per subscriber so
it's unlikely to be a Retrofit bug. If you can write a test case that shows
it's an actual Retrofit bug I'm happy to have a look.

**Comment by pavlospt** [comment]
Will try to make a test case and reply back early next week. Thank you for your replies. :)
