### ISSUE TITLE
Performance regression due to proxy creation from Retrofit 1.9.0 to 2.0.0

### ISSUE THREAD

**Issue by venator85** [square/retrofit#1670]
Hi, I'm migrating my app from Retrofit 1.9.0 to Retrofit 2.0.0, and I'm experiencing a performance regression due to proxy creation the first time I invoke the service.
Traceview shows that the following line:
`java.lang.reflect.Proxy.invoke (Ljava/lang/reflect/Proxy;Ljava/lang/reflect/Method;[Ljava/lang/Object;)Ljava/lang/Object;`
took ~240 ms on Retrofit 1.9.0, and since Retrofit 2.0.0 it takes ~1800 ms. I ran these tests on a Nexus 6, Android 6.0.1, targetSdkVersion 23.
I'm using the Jackson converter (version 2.0.0, Jackson 2.7.2).

Here you can find my service interface:
- for Retrofit 1.9.0: https://gist.github.com/venator85/b94c7c0fe5b0cae3eb1f
- for Retrofit 2.0.0: https://gist.github.com/venator85/67ddf3f7552ccd067a6e

Here: [retrofit2_performance_regression.zip](https://github.com/square/retrofit/files/883459/retrofit2_performance_regression.zip) you can find the original Traceview logs for both 1.9.0 and 2.0.0.

Don't hesitate to ask for more details if needed.
Thanks for your help.

**Comment by swankjesse** [comment]
Thanks for the helpful report.

Retrofit spent 1650ms in `JacksonConverterFactory.responseBodyConverter()`. The problem might be that we moved this reflection from the background thread to the foreground thread? That’s my guess, and it’s something we could fix at a risk of deferring error detection.

**Comment by swankjesse** [comment]
I took a quick attempt at this, but it turns out there’s one catch that’s pretty awkward to overcome.
https://github.com/square/retrofit/compare/master...jwilson_0313_sigh_async?expand=1#files_bucket

The issues is that we still want to create the okhttp3.Call instance on the UI thread, so we can call `OkHttpClient.newCall()` on the UI thread. Sigh.

**Comment by venator85** [comment]
@swankjesse @JakeWharton  any news on this?
Thanks ;)
