### ISSUE TITLE
Incomplete proguard configuration on website when using Call<Model>

### ISSUE THREAD

**Issue by mattijsf** [square/retrofit#1671]
The proguard configuration on the website is missing some critical information when using the Callback response handler.

For example when using the following resource:
`Call<com.example.model.proto.RegistrationResponse> register(@Body com.example.model.proto.RegistrationRequest);`

Retrofit's `createCallAdapter` that uses `Method.getGenericReturnType()` will return `java.lang.Object` even though I set proguard to use `-keepattributes Signature`

In order to fix this I need to add this to the proguard configuration:
`-keep class com.example.model.proto.** { *; }`

Error when above -keep rule is omitted:
```
java.lang.IllegalArgumentException: Unable to create converter for class java.lang.Object
  for method Registration.register
  at retrofit2.Utils.methodError(Utils.java:154)
  at retrofit2.MethodHandler.createResponseConverter(MethodHandler.java:62)
  at retrofit2.MethodHandler.create(MethodHandler.java:33)
  at retrofit2.Retrofit.loadMethodHandler(Retrofit.java:164)
  at retrofit2.Retrofit$1.invoke(Retrofit.java:145)
  at java.lang.reflect.Proxy.invoke(Proxy.java:393)
```

This is currently my (working) proguard configuration:
```
# retrofit
-dontwarn retrofit2.**
-keep class retrofit2.** { *; }
-keepattributes Signature
-keepattributes Exceptions
# line below is required when using Call<com.example.model.proto.*> with retrofit
-keep class com.example.model.proto.** { *; } 
```

**Comment by JakeWharton** [comment]
Care to make a PR? We're not Proguard users nor advocators.
