### ISSUE TITLE
java.net.UnknownHostException in Old Android Phones - API Level 14.1.2  to 19

### ISSUE THREAD

**Issue by techswappy** [square/retrofit#1674]
Library seems to throw the above Exception in different Phone versions randomly.

 - [ ] Question. I'm successfully using the library and have tested it on various devices. But, randomly in some devices the library throws "java.net.UnknownHostException" exception stating Unable to resolve host but, the host is very much available through the same phone's browser.

**Comment by JakeWharton** [comment]
This has nothing to do with Retrofit. This exception is thrown by the host OS when the DNS of a host name cannot be resolved. This usually happens when the phone is switching networks or simply has no connectivity.
