### ISSUE TITLE
Upgrade OkHttp to 3.2.0

### ISSUE THREAD

**Issue by hangduykhiem** [square/retrofit#1675]
We have stuck on 3.1.2 since #1600, is it possible to upgrade to 3.2.0? Is there any issues that hinder the upgrade process?

**Comment by eneim** [comment]
Due to [this](https://github.com/square/retrofit/blob/master/pom.xml#L52), It is safe I suppose.

**Comment by hangduykhiem** [comment]
My bad, should have check the source code. Thanks.
