### ISSUE TITLE
Question: Javadoc vs. implementation QueryMap on empty value

### ISSUE THREAD

**Issue by panzerdev** [square/retrofit#1677]
In the QueryMap doc it say

https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit2/http/QueryMap.java#L29
`Values are URL encoded and {@code null} will not include the query parameter in the URL.`

And in the Code 
https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit2/ParameterHandler.java#L133

```
T entryValue = entry.getValue();
        if (entryValue == null) {
          throw new IllegalArgumentException(
              "Query map contained null value for key '" + entryKey + "'.");
        }
```

an exception is thrown. 

Is the doc wrong or the exception?

**Comment by JakeWharton** [comment]
Null is forbidden.
