### ISSUE TITLE
[ Retrofit2 ]: NoClassDefFoundError on Android 4.1.2 / 4.2

### ISSUE THREAD

**Issue by speciosus** [square/retrofit#1678]
Hi everubody. 

Today I tested Retrofit2's new version. I added the following dependencies:

<code>
    compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
        exclude group: 'com.android.support'
        transitive = true;
    }

    // -- Better Picker
    compile('com.code-troopers.betterpickers:library:2.0.3') {
        exclude group: 'com.android.support', module: 'support-v4'
    }

    // -- Parsing HTML Web Page
    compile files('src/main/java/com/vwgroup/audiservice/libs/ksoap2-android-assembly-3.4.0-jar-with-dependencies.jar')

    compile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.2.1'
    compile 'com.android.support:recyclerview-v7:23.2.1'
    compile 'com.android.support:gridlayout-v7:23.2.1'

    compile 'com.android.support:design:23.2.1'

    compile 'com.j256.ormlite:ormlite-core:4.48'
    compile 'com.j256.ormlite:ormlite-android:4.48'
    compile 'info.hoang8f:android-segmented:1.0.5'

    compile('com.squareup.picasso:picasso:2.5.2') {
        exclude group: 'com.android.support'
    }
    compile ('com.mcxiaoke.volley:library:1.0.19'){
//            exclude group: 'com.squareup.retrofit2'
    }

    compile ('com.google.maps.android:android-maps-utils:0.4'){
    }

    compile ('org.jsoup:jsoup:1.8.3'){
    }

    compile ('com.kbeanie:image-chooser-library:1.5.7@aar'){
    }

    compile ('ly.count.android:sdk:15.06'){
//        exclude group: 'com.squareup.retrofit2'
    }
    // -- Network with retrofit
    compile('com.squareup.retrofit2:retrofit:2.0.0') {
        exclude group: 'com.android.support'
    }
    compile('com.squareup.retrofit2:converter-gson:2.0.0') {
        exclude group: 'com.android.support'
    }
    compile('com.squareup.retrofit2:converter-simplexml:2.0.0') {
        exclude module: 'xpp3'
        exclude module: 'stax'
        exclude module: 'stax-api'
        exclude group: 'com.android.support'
    }

    compile ('com.squareup.okhttp:okhttp:2.7.4'){
    }
    // -- Parse bolts
    compile 'com.parse.bolts:bolts-android:1.2.1'
    compile('com.google.android.gms:play-services-gcm:8.3.0') {
        exclude module: 'bolts-android'
        exclude module: 'support-v4'
    }

    compile('com.google.android.gms:play-services-maps:8.3.0') {
        exclude module: 'bolts-android'
        exclude module: 'support-v4'
    }

    compile('com.google.android.gms:play-services-location:8.3.0') {
        exclude module: 'bolts-android'
        exclude module: 'support-v4'
    }
    // -- Push woosh integration
    compile('com.pushwoosh:pushwoosh:+') {
    }
</code>

error :

<code>
Could not find class 'retrofit2.Retrofit$Builder'
</code>

Code :

<code>
Retrofit retrofit = new Retrofit.Builder()
    .baseUrl("http://myserver.com")
    .addConverterFactory(GsonConverterFactory.create())
    build();
</code>

I used <b>NO multidex </b>. Any suggestion?

**Comment by JakeWharton** [comment]
Maybe ProGuard?

Your best bet is to ask on StackOverflow with more information about your build, the exception, and anything else that might help. This isn't a problem with Retrofit, it's a problem with your build system, its configuration, or other libraries in use at runtime (like multidex).

**Comment by speciosus** [comment]
I've found the issue and it deals with this dependency

<code>
androidTestCompile ('com.squareup.spoon:spoon-client:1.3.2')
</code>

After I removed it, it worked fine. But I don't have any idea about what caused the problem
