### ISSUE TITLE
Allow to disable network failure for NetworkBehavior

### ISSUE THREAD

**Issue by rakeshcusat** [square/retrofit#1679]
I am using MockRetrofit in my automation and unit test cases. MockRetrofit needs NetworkBehavior object. This NetworkBehavior introduces network error based on the configuration. But there is no way to disable the network error. This causes flakiness in the test case. If we have feature to disable the network that would be really great to use the MockRetrofit for the unit and automation test. I already tried to look in to the source code and asked question on the [stackoverflow](http://stackoverflow.com/questions/35853617/mockretrofit-doesnt-allow-to-avoid-network-error) but I haven't found a solution.

**Comment by JakeWharton** [comment]
Set the error percentage to 0.
