### ISSUE TITLE
How to get OkhttpClient Object in retrofit

### ISSUE THREAD

**Issue by SXZZWeir** [square/retrofit#1683]
How to get OkhttpClient Object in retrofit  just like 
OkHttpClient okHttpClient =  retrofit.client()  
in  beta2

**Comment by egor-n** [comment]
It's [`Retrofit.callFactory()`](https://github.com/square/retrofit/blob/6b2bb3ad958e003488b8308df7927555a2b1008b/retrofit/src/main/java/retrofit2/Retrofit.java#L177) now.

**Comment by JakeWharton** [comment]
What @egor-n said!

**Comment by joaosardinha** [comment]
This doesn't seem to be the case anymore.

**Comment by Strife91** [comment]
Would love an update on this.
