### ISSUE TITLE
"import retrofit2.Result" is not resolved since 2.0.0-beta4

### ISSUE THREAD

**Issue by n0mer** [square/retrofit#1685]
Hi,

https://github.com/square/retrofit/blob/master/CHANGELOG.md entry for 2.0.0-beta4 do not mention package name changes regarding 

```java
import retrofit2.Result
```

in 2.0.0-beta3 this resolves correctly, but starting 2.0.0-beta4 (and 2.0.0) this import statement is not resolved.

**Comment by JakeWharton** [comment]
It's now `retrofit2.adapter.rxjava.Result`.

The change log line is:

> Each converter has been moved to its own package under `retrofit2.converter.<name>`. This prevents type collisions when many converters are simultaneously in use.

which forgot to call out adapters as well.

**Comment by n0mer** [comment]
@JakeWharton thank you for explanation!
