### ISSUE TITLE
get string result error

### ISSUE THREAD

**Issue by cxbiao** [square/retrofit#1686]
this is my code.
```
  @GET("user")
    Call<String> getUser(@Query("id") int uid, @Query("token") String token);

```
But retrofit meets an error for json malformed. 
How can I solve the problem?

**Comment by lubeast** [comment]
You'd better search your question in stackoverflow and here is a [question]((http://stackoverflow.com/questions/32861849/how-to-get-malformed-json-in-retrofit-2)) similar with yours. I think you should check your network response first.
