### ISSUE TITLE
Multipart PATCH request

### ISSUE THREAD

**Issue by thekalpit** [square/retrofit#1688]
I'm using retrofit 2.0.0-beta4. I can't get Multipart PATCH requests to work. PATCH request with HttpRequester works perfectly. So yeah, there's no issue at the server end.

**Comment by JakeWharton** [comment]
You have not provided enough information for this bug report to be actionable. Please supply a failing test case or specifically how the request body is malformed by Retrofit itself and not as a result of simply a malformed request based on your configuration.

I will re-open when such information is provided.
