### ISSUE TITLE
com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class modals.MMiscellaneous$Miscellaneous]: can not instantiate from JSON object

### ISSUE THREAD

**Issue by TheGreat0004** [square/retrofit#1692]
This is my link of question on Stackoverflow,
http://stackoverflow.com/questions/36152061/jackson-jsonmappingexception-cannot-instantinate/36158466#36158466

If i do the parsing with retrofit 1.9.0 it works well without adding any constructor or static to class but when i do the same with retrofit 2, it gives me the above mentioned error..

PLease look into this

**Comment by JakeWharton** [comment]
We're not Jackson users and since it's not a Retrofit problem StackOverflow is the right place for this question.
