### ISSUE TITLE
Enqueue callback not called

### ISSUE THREAD

**Issue by shilch** [square/retrofit#1693]
Hi,

I am using retrofit2 and recognized that sometimes the callback for Call.enqueue is not called.
e.g.
```java
mService.getItem("myID").enqueue(new retrofit2.Callback<Item>() {
    @Override
    public void onResponse(Call<Item> call, Response<Item> response) {
        Log.d(TAG, "onResponse()");
    }

    @Override
    public void onFailure(Call<Item> call, Throwable t) {
        Log.d(TAG, "onFailure()", t);
    }
});
```
I do not get a message in the log and also no timeout error.
Any ideas why this happens?

Thank you in advance!

**Comment by swankjesse** [comment]
Are you sure you see `Log.d()` logs?

**Comment by JakeWharton** [comment]
Also, add the OkHttp logging interceptor and see what the HTTP client is
actually doing.

**Comment by shilch** [comment]
Yes, I see logs. This is what I do:
```java
private static final String TAG = Fooclass.class.getSimpleName();

public void execute(){
    Log.d(TAG, "execute()");
    mService.getItem("123").enqueue(new Callback<Item>() {
        @Override
        public void onResponse(Call<Item> call, Response<Item> response) {
            Log.d(TAG, "onResponse()");
        }

        @Override
        public void onFailure(Call<Item> call, Throwable t) {
            Log.d(TAG, "onFailure()", t);
        }
    });
}
```
```java
OkHttpClient client = new OkHttpClient.Builder()
        // this is my interceptor to set the authorization header
        .addInterceptor(new Interceptor() {
            @Override
            public Response intercept(Chain chain) throws IOException {
                Request request = chain.request()
                        .newBuilder()
                        .addHeader("Accept", "application/json")
                        .addHeader("Authorization", token.getType() + " " + token.getToken())
                        .build();
                return chain.proceed(request);
            }
        })
        .addInterceptor(new HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.BASIC))
        .protocols(Arrays.asList(/*Protocol.HTTP_2, */Protocol.HTTP_1_1))
        .build();
builder.client(client);
```
And in the Logcat I type `Fooclass|OkHttp`:
```
D/Fooclass: execute()
D/OkHttp: --> GET https://example.com/api/v1/items/123 http/1.1
200 OK https://example.com/api/v1/items/123 (131ms, 153-byte body)
```
No Log from Callback is called, no timeout.

**Comment by shilch** [comment]
Using
```java
com.squareup.retrofit2:retrofit:2.0.0-beta4
```
instead of
```java
com.squareup.retrofit2:retrofit:2.0.0
```
makes no difference.
When using
```java
com.squareup.retrofit2:converter-gson:2.0.0-beta4
```
instead of
```java
com.squareup.retrofit2:converter-gson:2.0.0
```
I get
```java
com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at ...
```

**Comment by trramsiq** [comment]
2.0.0 is the latest release.
It sounds like your "Item" object does not have the correct structure compared with the JSON object you are receiving.

**Comment by shilch** [comment]
The item has the right structure, when using JacksonConverter instead of GsonGonverter, it works. But the callback is still not called.

**Comment by shilch** [comment]
Solved. Used `synchronize` where there should not be one

**Comment by FranPR9** [comment]
@shilch could you be more specific please, i'am having the same problem.

**Comment by shilch** [comment]
@FranPR9 Sorry, this issue is 5 month ago and I forgot it already. Be sure that there is no synchronize that can block you requests.

**Comment by tejasuplenchwar** [comment]
on retrofit POST method my callbacks are not working any one have solution for this

**Comment by tejasuplenchwar** [comment]
I am using Retrofit2
If  i am using post to send data to server can not able to get response from server
means my onResponse and onFailure not call

**Comment by LunaticMeta** [comment]
i have a same problem too :(

**Comment by guilmarc** [comment]
Same problem here, no solution on this forum, dam !

**Comment by joelc1225** [comment]
same problem here. any help would be appreciated. I'm trying to use enqueue method inside a non-activity class using repository pattern. Repository calls the NetworkDatasource class which contains the Retrofit api call. When debugging, the code skips over the enqueue callbacks.

**Comment by udayanem** [comment]
I am also having the same problem. I have log statements for both onResoponse() and onFailute() methods, but nothing executed. Control moves just after the enque() method. Why nobody is looking into this issue, as many people are still stuck with this issue. Is there something we all are missing?

**Comment by joelc1225** [comment]
What solved it for me was observing the result of the call in my activity using LiveData. 

So after enqueue gets called on a background thread, that call may take a few seconds to return. So the code that runs after enqueue was trying to already access the data before the data had returned from the API. 

So I removed all log statements outside of the enqueue method, so I'm not trying to access any null data before it returned from the API, and instead I'm observing the result of the call in my activity class using the LiveData 'observe' method. My enqueue call is in the 'NetworkDataSource' class of my 'AndroidHub' project, if you wanna check it out.

**Comment by TheLe0** [comment]
I had the same problem these days, i solved inserting this line on my  `AndroidManifest.xml>`

`<uses-permission android:name="android.permission.INTERNET" />`

In case somebody else still needs...

**Comment by Namida2** [comment]
I replaced enqueue with execute and it worked for me
