### ISSUE TITLE
Unable to log retrofit response using okhttp3.logging.HttpLoggingInterceptor 

### ISSUE THREAD

**Issue by ArslanAli7** [square/retrofit#1695]
Everything was working fine but suddenly i am not seeing response getting logged under my logcat i am using the following piece of code to add the logging interceptor to the okhttp object.

 ` Cache cache=null;
            HttpLoggingInterceptor logging = new HttpLoggingInterceptor();
            logging.setLevel(HttpLoggingInterceptor.Level.BODY);
            try {
                File httpCacheDirectory = new File(Global.getAppContext().getCacheDir(), "responses");
                cache = new Cache(httpCacheDirectory, 10 * 1024 * 1024);
            } catch (Exception e) {
                Log.e("OKHttp", "Could not create http cache", e);
            }`
`  okClient = new OkHttpClient()
                    .newBuilder()
                    .addInterceptor(logging)`

**Comment by forvicky** [comment]
how to solve？？

**Comment by ArslanAli7** [comment]
import okhttp3.logging.HttpLoggingInterceptor;
import okhttp3.OkHttpClient;

HttpLoggingInterceptor logging = new HttpLoggingInterceptor();
 logging.setLevel(HttpLoggingInterceptor.Level.BODY);
 okClient = new OkHttpClient()
                    .newBuilder()
                    .addInterceptor(logging)
