### ISSUE TITLE
Can't change title activity in response ?

### ISSUE THREAD

**Issue by AizeLeOuf** [square/retrofit#1696]
In an Activity, this don't works : 

        Call<ConfigItem> call = service.getConfigItemDetails(idItem);
        call.enqueue(new Callback<ConfigItem>() {
            @Override
            public void onResponse(Call<ConfigItem> call, Response<ConfigItem> response) {
                   setTitle("HELLO WORLD !"));
            }
        });

this one works : 

        setTitle("HELLO WORLD !"));
        Call<ConfigItem> call = service.getConfigItemDetails(idItem);
        call.enqueue(new Callback<ConfigItem>() {
            @Override
            public void onResponse(Call<ConfigItem> call, Response<ConfigItem> response) {
                   
            }
        });

No way to change Activity label/title in Response ?

Regards,

**Comment by JakeWharton** [comment]
Callbacks happen on the main thread so changing the title should work fine. Please provide the full exception.

**Comment by AizeLeOuf** [comment]
No stacktrace, no crash, nothing.. Just the title not changed. Maybe the callback must refresh/redraw layout or something.

**Comment by JakeWharton** [comment]
Is the callback being called?

**Comment by AizeLeOuf** [comment]
yes

**Comment by JakeWharton** [comment]
Then the problem lies between your callback and Android, not Retrofit. There's not a whole lot of information here to even guess what the problem is. I would recommend taking your question to StackOverflow since it is not specific to Retrofit.
