### ISSUE TITLE
Response Code 204

### ISSUE THREAD

**Issue by giorizzotti** [square/retrofit#1697]
What kind of issue is this?

Hello, I just updated Retrofit library from 2.0.0-beta4 to 2.0.0. The project was perfectly working, but now, when I generate the release apk (I use proguard with the rules specified in the instructions), some requests return 204 code even if they are perfect executed and them return the 200 code (tried with some utilities). What's the problem?

**Comment by JakeWharton** [comment]
These response codes are coming from your server. Maybe it's your misconfiguration of Retrofit, a problem with the serialized body, a bug in the server... who knows.

Without a test case, sample, or example that demonstrates that it is something caused by Retrofit then I'm afraid we aren't going to be of much help.

**Comment by giorizzotti** [comment]
Hello Jake, as I said, the server is OK. I tested the result code with PostMan and Advanced Rest Client for Chrome and the Result is 200. Moreover, until yesterday, before I update from 2.0.0-beta4 to  2.0.0, the application was perfeclty working.
PS the problem is only with rhe release version of the app, with the debug there are no problem!
Here are my proguard rules about Retrofit:

`#Retrofit
-keep class com.squareup.okhttp3.** { *; }
-keep interface com.squareup.okhttp3.** { *; }
-dontwarn com.squareup.okhttp3.**
-keep class retrofit2.** { *; }
-dontwarn okio.**
-dontwarn retrofit2.**
-dontwarn rx.**
-keepclasseswithmembers class * {
    @retrofit.http.* <methods>;
}
-keepattributes Exceptions
-keepattributes Signature
-keep class com.my.package.models.** {*;}
-keep class com.my.package.receiver.** {*;}`

**Comment by JakeWharton** [comment]
I don't use ProGuard so I'm not really going to be able to help if that's
the problem. You should try on a ProGuard forum or StackOverflow if that's
the case.
