### ISSUE TITLE
send request with image & strings

### ISSUE THREAD

**Issue by dimmitriy** [square/retrofit#1698]
help me please to send POST  Request (Retrofit 2.0.0) with String fields and one file field. 
I try to use TypedFile & TypedString but it cannot resolve.
Because of it I use RequestBody for all fields and get from back end: 

no body  
rawResponce message - "bad request" 

MediaType MEDIA_TYPE_JPG = MediaType.parse("image/jpeg");
        File file = new File("/storage/emulated/0/Pictures/LiveWallpapersHD/788149_1454579654.jpeg");
        RequestBody requestBody = RequestBody.create(MEDIA_TYPE_JPG, file);

        RequestBody req_family_status = RequestBody.create(MediaType.parse("text/plain"), family_status);
        RequestBody req_name = RequestBody.create(MediaType.parse("text/plain"), name);
        RequestBody req_last_name = RequestBody.create(MediaType.parse("text/plain"), last_name);
        RequestBody req_phone = RequestBody.create(MediaType.parse("text/plain"), phone);
        RequestBody req_gender = RequestBody.create(MediaType.parse("text/plain"), gender);
        RequestBody req_birthday = RequestBody.create(MediaType.parse("text/plain"), birthday);
        RequestBody req_work_place = RequestBody.create(MediaType.parse("text/plain"), work_place);
        RequestBody req_work_position = RequestBody.create(MediaType.parse("text/plain"), work_position);
        RequestBody req_about_me = RequestBody.create(MediaType.parse("text/plain"), about_me);
        RequestBody req_favourite = RequestBody.create(MediaType.parse("text/plain"), favourite);
        RequestBody req_education = RequestBody.create(MediaType.parse("text/plain"), education);
        RequestBody req_school = RequestBody.create(MediaType.parse("text/plain"), school);
        RequestBody req_hometown = RequestBody.create(MediaType.parse("text/plain"), hometown);

        sm.editProfile(req_family_status, req_name, req_last_name,
                req_phone, req_gender, req_birthday,
                req_work_place, req_work_position,
                req_about_me, req_favourite, req_education,
                req_school, req_hometown, requestBody, new Callback<ProfileResponce>() {
                    @Override
                    public void onResponse(Call<ProfileResponce> call, retrofit2.Response<ProfileResponce> response) {
                        if (response != null) {
                            ProfileResponce profile = response.body();
                            if (profile != null) {
                                Toast.makeText(getApplicationContext(), profile.toString(), Toast.LENGTH_LONG).show();
                                String result = profile.getResult();
                            } else {
                                // Response error
                                // Parse error response body
                                EditProfileResponce err = ServiceGenerator.parseResponseBody(
                                        EditProfileResponce.class, response.errorBody());
                                if (err != null) {
                                    proceedEditProfileErrors(err.getError());
                                    if (mProgress != null)
                                        mProgress.dismiss();
                                }
                            }
                        }
                    }

                    @Override
                    public void onFailure(Call<ProfileResponce> call, Throwable t) {
                        Toast.makeText(getApplicationContext(), "edit profile information failure", Toast.LENGTH_SHORT).show();
                    }
                });

@Multipart
    @POST("user")
    Call<ProfileResponce> editProfile(
            @Part("family_status") RequestBody family_status,
            @Part("name") RequestBody name,
            @Part("last_name") RequestBody last_name,
            @Part("phone") RequestBody phone,
            @Part("gender") RequestBody gender,
            @Part("birthday") RequestBody birthday,
            @Part("work_place") RequestBody work_place,
            @Part("work_position") RequestBody work_position,
            @Part("about_me") RequestBody about_me,
            @Part("favourite") RequestBody favourite,
            @Part("education") RequestBody education,
            @Part("school") RequestBody school,
            @Part("hometown") RequestBody hometown,
            @Part("avatar") RequestBody requestBody
    );

any propositions???

**Comment by WesleyWu** [comment]
Replace param @Part("avatar") RequestBody requestBody to @Part MultipartBody.Part requestBody.

MultipartBody.Part requestBody = MultipartBody.Part.createFormData("avatar", "your_avatar_file_name", the_original_requestBody);

pass the new requestBody as the last param should do the job.

**Comment by JakeWharton** [comment]
If you add the `ScalarsConverterFactory` you can just use `String` instead of `RequestBody` for the `text/plain` parts.

Other than that you can use `okhttp3.MultipartBody.Part` for the file since it allows specifying the filename whereas `RequestBody` does not.
