### ISSUE TITLE
Allow `POST("")` to post to the `baseUrl`, instead of throwing an exception

### ISSUE THREAD

**Issue by ZakTaccardi** [square/retrofit#1701]
**Use Case**
I want to `@POST` directly to my `baseUrl`, without appending anything to it. Below is my desired API.

    @POST("")
    Observable<SignInResponse> signIn(@Body SignInRequest signInRequest);

Unfortunately, this throws an error `java.lang.IllegalArgumentException: Missing either @POST URL or @Url parameter`

Here's the clunky workaround:

    @POST
    Observable<SignInResponse> signIn(@Body SignInRequest signInRequest, @Url String url);

Calling this clunky workaround currently looks like:

    service.signIn(request, "")

Note, I would prefer `@POST` over `@POST("")` (less object creation)

**Comment by ZakTaccardi** [comment]
`@POST("./")` addresses this use case.

see https://github.com/square/retrofit/issues/1567#issuecomment-180115150

**Comment by danielesegato** [comment]
Actually
```
@POST(".")
```

the `"./"` add a / if there wasn't in the base url

so if your base URL is `https://whatever/service` and doesn't answer to `https://whatever/service/` you need to use only the dot.
