### ISSUE TITLE
SocketTimeoutException causes OnErrorNotImplementedException

### ISSUE THREAD

**Issue by localhostEU** [square/retrofit#1704]
Using Retrofit 2, Okhttp 3.2.0. 
**SocketTimeoutException** doesn't go through overloaded subscribe of retrofit call and causing app crash. In Retrofit 1.9 it was working. Any workaround for this except Interceptor with try/catch block for **SocketTimeoutException**?

Original answer with complete stacktrace is [here](https://github.com/square/okhttp/issues/2415), asked in wrong place.

**Comment by JakeWharton** [comment]
As I outlined in that issue, you are not handling errors in your stream by using the `subscribe(Action1)` method. Use `subscribe(Action1, Action1)` or `subscribe(Observer)` which will allow errors to propagate to your application code to be handled or ignored.

**Comment by artem-zinnatullin** [comment]
@localhostEU btw you can try [rxlint](http://www.littlerobots.nl/blog/RxLint-a-lint-rule-for-RxJava/)  to find places without error handling!

I've suggested @localhostEU to write a test with MockWebServer to reproduce the problem, if he won't succeed I'll try to do that too.

Btw, PR #1191 may help investigate such problems.
