### ISSUE TITLE
[Feature Request] Allow hard coded method header on a service method

### ISSUE THREAD

**Issue by ZakTaccardi** [square/retrofit#1705]
Any reason the below mock `@Header` isn't part of the API? It would add a bit of flexibility.

    @POST("./")
    @Header("x-api-version", "3")
    Callback<SignInResponse> signIn(@Body SignInRequest request);

Note, I am aware we can use OkHttp's interceptors to add a header to every request, but I would like to add a header to _some_ requests, while not having to specify it every time as a method parameter.

**Comment by JakeWharton** [comment]
You can use [`@Headers`][1].

 [1]: http://square.github.io/retrofit/2.x/retrofit/retrofit2/http/Headers.html

**Comment by ZakTaccardi** [comment]
That was painfully obvious, thanks!
