### ISSUE TITLE
Release 2.0.1 version of retrofit-converter-gson and RxJava adapters

### ISSUE THREAD

**Issue by kungfoo** [square/retrofit#1707]
Can you release a non-beta version of those libs. I'm trying to pin all retrofit stuff to the same version in our build...

**Comment by gabrielittner** [comment]
They are released https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.squareup.retrofit2%22

**Comment by kungfoo** [comment]
Excuse my ignorance. They are indeed released. I could not find them on a cached maven repo.
