### ISSUE TITLE
Protobuf extension registry issue

### ISSUE THREAD

**Issue by vganin** [square/retrofit#1710]
Hi, I'm trying to get protobuf object  deserialized with Retrofit and `ProtoConverterFactory`. The issue is that my message B is extension of another message A like this:

A.proto
```
message A {
  ...
}
```

B.proto
```
import "A.proto"

message B {
  ...
}

extends A {
  optional B b = 111;
}
```

As it is known, to get extension, I have to register it first and then parse the stream like this:
```java
ExtensionRegistry reg = RextensionRegistry.newInstance();
registry.add(BProtos.b);
AProtos.A.parseFrom(stream, reg);
```

But as I can see from source code, converter only calls `parseFrom(stream)` and there are no hooks to attach `ExtensionRegistry` instance in the process.

Am I missing something?

My issue is very similar to this one http://stackoverflow.com/questions/21747336/protobuf-extension-registry-issue

**Comment by JakeWharton** [comment]
I'll have a look! We can probably provide a create method overload which
takes a registry.
