### ISSUE TITLE
onFailure Throwable returns April 1st 2016 date

### ISSUE THREAD

**Issue by Ganitzsh** [square/retrofit#1712]
Hi,

I just updated to the latest version of retrofit (2.0.1) on my Android Application.
Everything worked fine until today, one of my requests produces an `onFailure` callback.
The `getMessage()` method from the attached `Throwable` returns the following string: `4/1/2016 5:13:02 AM +08:00`

I didn't change anything and my WebService returns the correct content with a `200` status code.

**Comment by JakeWharton** [comment]
Paste the full stack trace.

**Comment by Ganitzsh** [comment]
My bad... I forgot there was a `StackTrace` object on the `Throwable`.

I managed to debug it. Sorry for the useless issue.
