### ISSUE TITLE
Retrofit2 + Path parameter + Proguard

### ISSUE THREAD

**Issue by Kiran89kumar** [square/retrofit#1717]
Hi. I just update com.squareup.retrofit:retrofit:1.0.9 to com.squareup.retrofit2:retrofit:2.0.1
Everything fine except the proguard version.

For Proguard version of the app, the path is not getting replaced.

Eg: 
PATH: "http://10.0.0.1:8080/api/users/1/devices/{deviceid"}/channels
Expected URl: "http://10.0.0.1:8080/api/users/1/devices/1234/channels"
Actual URI: "http://10.0.0.1:8080/api/users/1/devices/%deviceid%7D /channels"

**Comment by swankjesse** [comment]
Seems like a ProGuard bug. Disable that?

**Comment by Kiran89kumar** [comment]
Ya its proguard big, how do I fix it.

**Comment by JakeWharton** [comment]
We're not ProGuard users so you'll have to consult other ProGuard users
somewhere like StackOverflow. Ensure you ProGuard configuration is
up-to-date with the latest from the website.
