### ISSUE TITLE
Multiple request on single button click

### ISSUE THREAD

**Issue by aminalzanki** [square/retrofit#1724]
Hi,

I have an issue where multiple requests been called on single button click. It supposed to make only request on single button click. What are possible causes for mentioned issue? I really need  your feedback since it affected our server. 

Thanks, with love.

**Comment by rdhdia** [comment]
I guess that depends on how you implemented your onClick() on your app? Would be best if you could point to your source code, that would help a lot

**Comment by JakeWharton** [comment]
There's not enough information here to make the bug report actionable. Can you provide a test case that demonstrates this is a Retrofit problem?

**Comment by aminalzanki** [comment]
1. On button click, will call this method.
`Service.getInstance().signIn(param1, param2)`

2. This is the `getInstance()` implementation:

// create instance
`public static final Service INSTANCE = new Service();`

// getInstance()
`public static synchronized Service getInstance() {
        String token = Storage.getInstance().getAuthToken();
        mService = createService(ServiceInterface.class, "Token token=" + token);
        return Service.INSTANCE;
    }`

// create service
``private static Gson mGson = new GsonBuilder()
            .setFieldNamingPolicy(FieldNamingPolicy.LOWER_CASE_WITH_UNDERSCORES)
            .setDateFormat(DATE_FORMAT)
            .setExclusionStrategies(new ExclusionStrategy() {                
             @Override
                public boolean shouldSkipField(FieldAttributes f) {
                    return f.getDeclaringClass().equals(RealmObject.class);
                }

                @Override
                public boolean shouldSkipClass(Class<?> clazz) {
                    return false;
                }
            })
            .create();

    private static Retrofit.Builder mBuilder = new Retrofit.Builder()
              .baseUrl(BuildConfig.HOST)
              .addConverterFactory(GsonConverterFactory.create(mGson));
 
    public static <S> S createService(Class<S> serviceClass, final String authToken) {
        HttpLoggingInterceptor logging = new HttpLoggingInterceptor();
        logging.setLevel(HttpLoggingInterceptor.Level.BODY);

        mHttpClient.addInterceptor(new Interceptor() {
            @Override
            public okhttp3.Response intercept(Chain chain) throws IOException {

                Request.Builder requestBuilder;
                Request original = chain.request();

                if (authToken != null) {
                    requestBuilder = original.newBuilder()
                            .header("Authorization", authToken)
                            .header("Accept", "application/json")
                            .header("Content-Type", "application/json")
                            .method(original.method(), original.body());
                } else {
                    requestBuilder = original.newBuilder()
                            .header("Accept", "application/json")
                            .header("Content-Type", "application/json")
                            .method(original.method(), original.body());
                }

                Request request = requestBuilder.build();
                return chain.proceed(request);
            }
        });

        mHttpClient.addInterceptor(logging);
        OkHttpClient client = mHttpClient.build();
        mRetrofit = mBuilder.client(client).build();
        return mRetrofit.create(serviceClass);
    }`

**Comment by 0kai** [comment]
@aminalzanki 
hi, I call one request, and only get one result.
but the router to intercept about two or more request.

did we has same issue?

**Comment by JakeWharton** [comment]
What makes you think multiple requests are happening and that it's Retrofit's fault though?

Can you write an isolated test case that demonstrates Retrofit is making the two requests and not your code?

**Comment by 0kai** [comment]
@JakeWharton hello,
I had add okhttp client to retrofit, and it will happened multiple requests.
If I remove the ".client()", it will be ok
(okhttp:3.2, retrofit:2.0.1)

my code as follow:
`public class RestHelper {
    private static Retrofit retrofit;

    public static void init(Context context) {
        HttpLoggingInterceptor logging = new HttpLoggingInterceptor();
        logging.setLevel(HttpLoggingInterceptor.Level.BODY);

        File cacheDir = new File(context.getCacheDir(), HttpConfig.RESPONSE_CACHE);
        OkHttpClient sOkHttpClient = new OkHttpClient.Builder()
                .cache(new Cache(cacheDir, HttpConfig.RESPONSE_CACHE_SIZE))
                .connectTimeout(HttpConfig.HTTP_CONNECT_TIMEOUT, TimeUnit.MILLISECONDS)
                .readTimeout(HttpConfig.HTTP_READ_TIMEOUT, TimeUnit.MILLISECONDS)
                .writeTimeout(HttpConfig.HTTP_WRITE_TIMEOUT, TimeUnit.MILLISECONDS)
                .addInterceptor(logging)
                .build();

        retrofit = new Retrofit.Builder()
                .baseUrl(HttpConfig.BASE_URL)
                .addConverterFactory(GsonConverterFactory.create())
                .client(sOkHttpClient)
                .build();
    }

    public static <T> T createApi(Class<T> clazz) {
        return retrofit.create(clazz);
    }
}`

multiple request capture:
![py ckd ce5r 25jm wijx](https://cloud.githubusercontent.com/assets/1498653/14378405/52d5780a-fda7-11e5-9579-071843985b52.png)

**Comment by JakeWharton** [comment]
I cannot reproduce this. Unless someone provides an executable sample which demonstrates the problem there's nothing I can really do here.

**Comment by andacaydin** [comment]
I have exactly the same issue.
Using also OkHttpClient 3.2.0 & Retrofit 2.0.0

`public static <T> T getAdapter(Class<T> intf) {
        if (adapter == null) {

            OkHttpClient.Builder client = new OkHttpClient.Builder();
            client.addInterceptor(new Interceptor() {
                @Override
                public Response intercept(Chain chain) throws IOException {
                    Request request = chain.request();
                    request.newBuilder()
                            .header("Accept", "application/json;")
                            .header("Content-Type", "application/json;");
                    Response response = chain.proceed(request);
                    return response;
                }

            });

            //JACKSON START
            ObjectMapper objectMapper = new ObjectMapper();
            SimpleModule localDateModule = new SimpleModule("localDateModule", new Version(1, 0, 0, null))
                         .addDeserializer(LocalDate.class, new LocalDateDeserializer())
                         .addSerializer(LocalDate.class, new LocalDateSerializer());
            objectMapper.registerModule(localDateModule);
            SimpleModule moneyModule = new SimpleModule("moneyModule", new Version(1, 0, 0, null))
                    .addDeserializer(Money.class, new MoneyDeserializer())
                    .addSerializer(Money.class, new MoneySerializer());
            objectMapper.registerModule(moneyModule);
            //JACKSON END

            adapter = new Retrofit.Builder()
                    .baseUrl(Constants.BACKEND_API)
                    .addConverterFactory(JacksonConverterFactory.create(objectMapper))
                    .client(client.build())
                    .build();
        }
        T t = adapter.create(intf);

        return t;
    }`

and following code to start the process:

`ServerAdapter.getAdapter(ReservationService.class).createReservation(ServerAdapter.getUserAuthorization(getContext()), createReservationRQ).enqueue(new Callback<CreateReservationResult>() {`
etc...

I removed the interceptor & the OkHttpClient: same issue.

**Comment by andacaydin** [comment]
ok I found out: It has something to do with not-responding backends. So in case backend is not responding and the request runs into a timeout, it retries the request.

**Comment by 0kai** [comment]
@andacaydin 
I also create Retrofit every time, it doesn't has this issue.

Did you do something to reslove this issue?

**Comment by andacaydin** [comment]
yes, having the backend NOT timeout helped. So obviously there is a automatic retry mechanism which resends same request in case response has not been given in time

**Comment by aminalzanki** [comment]
I made a changes on my code and the repetition issue is gone. It's because of the static instance keep on recreating `OkHttpClient`. 

`public class MyService {

    private static final String TAG = MyService.class.getSimpleName();
    private static final String DATE_FORMAT = "yyyy-MM-dd'T'HH:mm:ss.SSSZ";

    private static final String ACTION_EDIT = "edit";
    private static final String ACTION_DUPLICATE = "duplicate";
    private static final String ACTION_AUTO_ASSIGN = "auto_assign";

    private static MyService sInstance = null;
    private static OkHttpClient.Builder mHttpClient = null;
    private static MyServiceInterface mService = null;

    private static Retrofit mRetrofit = null;
    private Realm mRealm;
    private EventBus mEventBus = EventBus.getDefault();

    public MyService() {
        // Enforce Singleton
    }

    public static synchronized MyService getInstance() {
        if (sInstance == null) {
            synchronized ((MyService.class)) {
                if (sInstance == null) {
                    sInstance = new MyService();
                }
            }
        }

        String token = MyStorage.getInstance().getAuthToken();
        mService = createService(MyServiceInterface.class, "Token token=" + token);
        return sInstance;
    }

    public static synchronized MyService getInstance(final String token) {
        if (sInstance == null) {
            synchronized ((MyService.class)) {
                if (sInstance == null) {
                    sInstance = new MyService();
                }
            }
        }
        mService = createService(MyServiceInterface.class, "Token token=" + token);
        return sInstance;
    }

    private static Gson mGson = new GsonBuilder()
            .setFieldNamingPolicy(FieldNamingPolicy.LOWER_CASE_WITH_UNDERSCORES)
            .setDateFormat(DATE_FORMAT)
            .setExclusionStrategies(new ExclusionStrategy() {
                @Override
                public boolean shouldSkipField(FieldAttributes f) {
                    return f.getDeclaringClass().equals(RealmObject.class);
                }

                @Override
                public boolean shouldSkipClass(Class<?> clazz) {
                    return false;
                }
            })
            .create();

    private static Retrofit.Builder mBuilder = new Retrofit.Builder()
            .baseUrl(BuildConfig.HOST)
            .addConverterFactory(GsonConverterFactory.create(mGson));

    public static <S> S createService(Class<S> serviceClass, final String authToken) {
        HttpLoggingInterceptor logging = new HttpLoggingInterceptor();
        logging.setLevel(HttpLoggingInterceptor.Level.BODY);

        // here I checked if okhttpclient is null, create new. otherwise, use existing.
        if (mHttpClient == null) {
            mHttpClient = new OkHttpClient.Builder();
        }

        mHttpClient.addInterceptor(new Interceptor() {
            @Override
            public okhttp3.Response intercept(Chain chain) throws IOException {

                Request.Builder requestBuilder;
                Request original = chain.request();

                if (authToken != null) {
                    requestBuilder = original.newBuilder()
                            .header("Authorization", authToken)
                            .header("Accept", "application/json")
                            .header("Content-Type", "application/json")
                            .method(original.method(), original.body());
                } else {
                    requestBuilder = original.newBuilder()
                            .header("Accept", "application/json")
                            .header("Content-Type", "application/json")
                            .method(original.method(), original.body());
                }

                Request request = requestBuilder.build();
                return chain.proceed(request);
            }
        });

        mHttpClient.addInterceptor(logging);
        OkHttpClient client = mHttpClient.build();

        // here I checked if retrofit is null, create new. otherwise, use existing.
        if (mRetrofit == null) {
            mRetrofit = mBuilder.client(client).build();
        }
        return mRetrofit.create(serviceClass);
    }

    public Retrofit getRetrofit() {
        return mRetrofit;
    }`

This solve my issue

**Comment by JakeWharton** [comment]
Sounds like the problem was you were creating multiple instances. Glad it got sorted out.

**Comment by navczydev** [comment]
@JakeWharton I recently got this issue, I try to understand why it needs to be a single instance? It's causing issues only when custom OkHttpCleint is added to the retrofit instance.
Thanks
