### ISSUE TITLE
Retrofit 2.0 : onResponse called with null when HTTP Code is 404

### ISSUE THREAD

**Issue by prasad767** [square/retrofit#1725]
When REST Api returns 404, onResponse called with NULL Response.  We have user search api and if the user is not found on the server our REST api returns 404 with error response in body with more details.

As Retrofit 2.0 returns a null response body, it's hard for us to show the correct error to the user. 

Do we have an alternate solution to get a response during 404?

Thanks

**Comment by JakeWharton** [comment]
We have a test which asserts that is not true: https://github.com/square/retrofit/blob/9de61e0672ab0468d42bceb536db55007821769d/retrofit/src/test/java/retrofit2/CallTest.java#L120-L147. Can you provide a test case which demonstrates the problem?

**Comment by prasad767** [comment]
Thanks for providing the hint... I was trying to get error response as same as success response.
response.errorBody().string() works.
