### ISSUE TITLE
Slashes and question marks issue in retrofit.

### ISSUE THREAD

**Issue by lectricas** [square/retrofit#1727]
Hey guys. I've asked a quesiton on stackoverflow but noone answered so far, so I have to ask here because I have a little time. 
http://stackoverflow.com/questions/36419184/3f-insted-of-question-mark-in-my-retrofit-url

The problem is that I have some params which are:

_height=1184
_target=android/2 (here is a slash in my param) I don't know if it acts like a regular slash.
_width=768
_user_id=5984

I want to replace my URL with cusom url which has slashes and question marks.
What is the perfect way to do that without irritating replacement? 
I tried to build my url with Field annotation and and have no result. Also, building with field is very hard in my case.

```
@FormUrlEncoded
    @POST("/{url}")
    Observable<ActiveParkEndpointListResponse> downloadParks(
            @Header("x-device-id") String deviceId,
            //@Field(ParkApiUrl.PARAM_HEIGHT) String height, no effect
            //@FieldMap Map<String, String> params,   no effect
            @Path(value = "url", encoded = true) String  method
    );
```

Thanks a lot.

**Comment by lectricas** [comment]
Does this project dead or something?

**Comment by swankjesse** [comment]
This is not a Q&A service.
