### ISSUE TITLE
ClassNotFoundException java.util.Optional in RoboVM for iOS

### ISSUE THREAD

**Issue by egnition** [square/retrofit#1729]
Using retrofit2 2.0.1 with RoboVM 1.14.0 leads to a ClassNotFoundException because `Class.forName("java.util.Optional");` is called before `Class.forName("org.robovm.apple.foundation.NSObject");`. Since RoboVM is based on Java 1.7  there is no `java.util.Optional`. So in class `Platform.java`

```java
    try {
        Class.forName("java.util.Optional");
        return new Java8();
    } catch (ClassNotFoundException ignored) {
    }
    try {
      Class.forName("org.robovm.apple.foundation.NSObject");
      return new IOS();
    } catch (ClassNotFoundException ignored) {
    }
```

should be 

```java
    try {
      Class.forName("org.robovm.apple.foundation.NSObject");
      return new IOS();
    } catch (ClassNotFoundException ignored) {
    }
    try {
        Class.forName("java.util.Optional");
        return new Java8();
    } catch (ClassNotFoundException ignored) {
    }
```

**Comment by JakeWharton** [comment]
That switch makes no sense. If CNFE is thrown from looking up `Optional` the method continues looking for `NSObject`.

**Comment by egnition** [comment]
Ah, yes, sorry. It's not a CNFE, it's the following warning in RoboVM
```
WARN java.lang.Class: Class.forName() failed to load 'java.util.Optional'.
Use the -forcelinkclasses command line option or add 
<forceLinkClasses><pattern>java.util.Optional</pattern></forceLinkClasses>
to your robovm.xml file to link it in.
```
which is not displayed when I first check for RoboVM and then for Java8.

**Comment by JakeWharton** [comment]
Isn't the same warning emitted for `android.os.Build` which is attempted right before that?
