### ISSUE TITLE
Query params not encoded correctly

### ISSUE THREAD

**Issue by silva96** [square/retrofit#1730]
Bug Report:

I have a query parameter called authenticity_token, I pass the token to the call and the token is a string like this

String authenticity_token = "S8Rp93ES/FZ3kyltGi0cPA22RSu34DIMUy8vZVUnVe4=";

When the Call is executed this parameter should be Url encoded, but it's being encoded partially

here is how it looks partially encoded:

authenticity_token=S8Rp93ES/FZ3kyltGi0cPA22RSu34DIMUy8vZVUnVe4%3D

As you can see, the / are not being encoded as %2F

**Comment by JakeWharton** [comment]
`/` doesn't need to be encoded after `?`.

The behavior you are seeing comes from [OkHttp][1], not Retrofit so any issues you have with how URLs are encoded will need to be filed on that project.

```java
System.out.println(HttpUrl.parse("http://example.com").newBuilder()
    .addQueryParameter("authenticity_token", "S8Rp93ES/FZ3kyltGi0cPA22RSu34DIMUy8vZVUnVe4=")
    .build());
```
```
http://example.com/?authenticity_token=S8Rp93ES/FZ3kyltGi0cPA22RSu34DIMUy8vZVUnVe4%3D
```

 [1]: https://github.com/square/okhttp

**Comment by silva96** [comment]
thanks for such a quick and accurate response @JakeWharton
