### ISSUE TITLE
Allow Retrofit level intercepter? - Feature Request

### ISSUE THREAD

**Issue by manijshrestha** [square/retrofit#1732]
In scenarios where multiple Retrofit Adapters share same instance of OkHttp client and one needs to do something at the adapter level, it would be nice to have interceptor at retrofit adapter level.
One example I could think of, is having multiple endpoint with different header requirements. Say, one endpoint needs headers to have API key, another API needs some token in header for each request. Instead of having to define `@Header` in each method, it would be ideal to have it defined in adapter level so all request going through that adapter would have those headers appended automatically for each request. As okhttp client is shared, one wouldn't want to append headers for all the API's for each request.

Note: Ref https://github.com/square/retrofit/issues/1082

**Comment by swankjesse** [comment]
You can make a copy of your OkHttpClient, put the interceptors on that copy, and then use that for Retrofit?

**Comment by manijshrestha** [comment]
Thanks @swankjesse, thats a good idea. Do you see any issue if there are shared interceptors though? Like if I have logging interceptors that could be used by all instances of okhttpclient?

**Comment by manijshrestha** [comment]
Just curious if there is any reason we would not want to have interceptors at Retrofit level?

**Comment by bluehallu** [comment]
@manijshrestha JakeWharton has expressed in the past it is a design decision to offload interceptors to whatever http client is being used.

**Comment by manijshrestha** [comment]
Thanks @bluehallu. I do see the reasoning behind using okhttp interceptor for header. In my use case, I am using same okhttp client which is being used across multiple service, hence, my request.

**Comment by bluehallu** [comment]
@manijshrestha you can use @header to have headers set on each endpoint. If you want to have headers set globally, then you have to resort to either an http interceptor or have a wrapper class that pre-curries all the calls setting the header using @header.

**Comment by manjunathc23** [comment]
+1

**Comment by dherges** [comment]
You can also make your Interceptor aware of the ``Host:`` header in the request and make decisions based on the remote end you're connecting to. You could also delegate authentication to another class. I mean, that's like a web browser that stores cookie per domain. Short sample:

```java
public class MyAuthInterceptor interface Interceptor {
  private Map<String, MyAuth> auths = new HashMap<>();
  /*
  auths.put("foo.com", new MyAuth("bar"));
  auths.put("example.com", new MyAuth("x-magic-value"));
  */

  public Response intercept(Chain chain) throws IOException {
    Request request = chain.request();

    String host = request.header("Host");
    MyAuth myAuth = auths.get(host);
    if (myAuth != null) {
      request = myAuth.authenticate(request);
    }

    return chain.proceed(request)
  }
}
```

```java
public class MyAuth {
  private String authValue;

  public MyAuth(String authValue) {
    this.authValue = authValue;
  }

  public Request authenticate(Request request) {
    return request.newBuilder()
      .header("X-Magic-Auth", authValue)
      .build();
  }
}
```

**Comment by swankjesse** [comment]
No action to take on this.
