### ISSUE TITLE
retrofit unable to create converter for byte[]

### ISSUE THREAD

**Issue by kizure** [square/retrofit#1733]
I use retrofit in my project.i wanna take a file from my server,that is a verification code.At first,everything is ok,but when i open the project again,it has a error.and i rebuild my project times but it doesn't fix.

**Comment by JakeWharton** [comment]
Built-in support for a `byte[]` is done by specifying `ResponseBody` as your type and calling `body.source().readByteArray()`. If you want to return `byte[]` directly then you'll need to make your own converter which does that for you.
