### ISSUE TITLE
How to make @Url and @FieldMap use together?

### ISSUE THREAD

**Issue by brucetoo** [square/retrofit#1737]
I just want to add dynamic url with some params,and the following is test code.
```java    
        @FormUrlEncoded
        @POST 
        Call<JsonElement> testUrl(@Url String url,@FieldMap Map<String,String> map);
```
But when i intercept the url and print it, and only original url shows without any FiedlMap params.

And the question is **How i make Url and FieldMap annotation together?**, Thank you.

**Comment by JakeWharton** [comment]
Sounds like you're looking for QueryMap, not FieldMap. QueryMap adds query
parameters to the URL whereas FieldMap adds form fields to the body.
