### ISSUE TITLE
3.x: Proposal: Either<Result, Error>

### ISSUE THREAD

**Issue by artem-zinnatullin** [square/retrofit#1739]
This is probably for 3.x because idea is to make it mandatory for all execution models (retrofit-adapters), but I think it worth it.

Concept: do not throw exceptions but instead return `Either<Result, Error>`.

Like this:

```java
interface Service {

  @GET("/user/{id}")
  Call<Either<User, Error>> user(@Path("id") String id);

  @GET("/payment/{id}")
  Single<Either<Payment, Error>> payment(@Path("id") String id);

  @GET("/settings")
  Observable<Either<Settings, Error>> settings();
}

class example {

  void example() {
    Either<User, Error> either = service.user("artem_zin").execute();
    
    if (either.isResult()) { // better than (either instanceof Either.Left) and casting.
      User user   = either.result(); // safe.
      Error error = either.error();  // will throw something like IllegalStateException.
    } else if (either.isError()) {
      Error error = either.error();  // safe.
      User user   = either.result(); // will throw something like IllegalStateException.
    }
  }
}
```

---

* Requires 2 additional classes: `Either` and `Error`.
* Unifies error handling for all execution models. 
* Makes Service interface completely self-explanatory and obvious for any reader.
* `Call` callback will have only one method and could be turned into a lambda.
* `Either` could include `Response` functionality inside itself (or it's ~ok to have `Either<Response<T>, Error>`).
* Adds hipster points :shipit: to the library because `Either` related to FP.
* ???
* Profit

// Not sure how to deal with `rx.Completable` though.

**Comment by JakeWharton** [comment]
This is already present for RxJava as Result<T>.

As to Call, we intentionally mirror OkHttp here. You can make your own
version of a Call with an Either type via CallAdapter.Factory so I'm not
sure we need to ship something like this.

**Comment by artem-zinnatullin** [comment]
Yeah, I know that RxJava adapter has similar class, but this looks like a nice unified solution for whole Retrofit. Anyway, it's up to you and community, just suggested the idea.

**Comment by swankjesse** [comment]
No action to take here. Call adapters mean you can implement this yourself if you need it.
