### ISSUE TITLE
Retrofit cannot parse xml response

### ISSUE THREAD

**Issue by rajkumar1979** [square/retrofit#1746]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by rajkumar1979** [comment]
Hi I am trying to use retrofit to write a simple rest client , I am trying to call a REST API GET that returns an xml response, however retrofit is not able to parse the xml.

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<offer xmlns="http://schema.intuit.com/platform/webs/catalog/internal/offers/v3">
    <offerID>20000798</offerID>
    <name>QBOA + QBO Plus + QBOP Enhanced CA CAD for Accountants</name>
    <description>QBOA + QBO Plus + QBOP Enhanced CA CAD for Accountants</description>
    <effectiveStartDate>2015-12-13T00:00:00-0800</effectiveStartDate>
    <currency>CAD</currency>
    <region>CA</region>
    <country>CA</country>
    <offerType>Free</offerType>
    <offerLevel>BASE</offerLevel>
    <customerSegment>ACCOUNTANT</customerSegment>
    <extendedCustomerSegment>REGULAR</extendedCustomerSegment>
    <salesChannel>DIRECT</salesChannel>
    <isListPriceOffer>true</isListPriceOffer>
    <product>
        <productID>22000220</productID>
        <packageId>21001070</packageId>
        <code>QBOA</code>
        <name>QuickBooks Online Accountant</name>
        <description>QuickBooks Online Accountant</description>
        <grantOfferingType>Intuit.smallbusiness.qba.web</grantOfferingType>
        <billingServiceType>/service/intuit/qboa</billingServiceType>
        <featureSet>
            <featureSetID>25001595</featureSetID>
            <code>QBOA_STANDARD</code>
            <name>QBO Accountant Standard</name>
            <status>Active</status>
            <description>QuickBooks Online Accountant Standard</description>
            <feature>
                <code>STANDARD</code>
                <name>Standard</name>
                <type>Feature Set</type>
            </feature>
        </featureSet>
        <charge>
            <chargeID>23001499</chargeID>
            <name>QuickBooks Online Accountant Standard</name>
            <description>QuickBooks Online Accountant Standard CA CAD Monthly Free</description>
            <type>Recurring</type>
        </charge>
    </product>
    <product>
        <productID>22000000</productID>
        <packageId>21001071</packageId>
        <code>QBO</code>
        <name>QuickBooks Online</name>
        <description>QuickBooks Online</description>
        <grantOfferingType>Intuit.sbe.salsa.default</grantOfferingType>
        <billingServiceType>/service/intuit/qbo</billingServiceType>
        <featureSet>
            <featureSetID>25000000</featureSetID>
            <code>QBO_PLUS</code>
            <name>QBO_PLUS</name>
            <status>Active</status>
            <description>QuickBooks Online Plus</description>
            <feature>
                <code>PLUS</code>
                <name>Plus</name>
                <type>Feature Set</type>
            </feature>
        </featureSet>
        <charge>
            <chargeID>23001500</chargeID>
            <name>QuickBooks Online Plus</name>
            <description>QuickBooks Online Plus Accountant CA CAD Monthly Free</description>
            <type>Recurring</type>
        </charge>
    </product>
    <product>
        <productID>22000154</productID>
        <dependentOnProductId>22000000</dependentOnProductId>
        <dependentOnProductCode>QBO</dependentOnProductCode>
        <packageId>21001323</packageId>
        <code>QBOP</code>
        <name>QuickBooks Online Payroll</name>
        <description>QuickBooks Online Payroll</description>
        <grantOfferingType>Intuit.ems.iop</grantOfferingType>
        <billingServiceType>/service/intuit/qbo/qbop</billingServiceType>
        <featureSet>
            <featureSetID>25000537</featureSetID>
            <code>ENHANCED</code>
            <name>ENHANCED</name>
            <status>Active</status>
            <description>ENHANCED</description>
            <feature>
                <code>ENHANCED</code>
                <name>Enhanced</name>
                <type>Feature Set</type>
            </feature>
        </featureSet>
        <charge>
            <chargeID>23001868</chargeID>
            <name>QuickBooks Online Payroll Enhanced</name>
            <description>QuickBooks Online Payroll Enhanced CA CAD Monthly Free</description>
            <type>Recurring</type>
        </charge>
        <charge>
            <chargeID>23001964</chargeID>
            <name>QuickBooks Online Payroll Enhanced Usage</name>
            <description>QuickBooks Online Payroll Enhanced Accountant CA CAD Usage Free</description>
            <type>Usage</type>
        </charge>
    </product>
    <transition>
        <transitionType>Resubscribe</transitionType>
        <fromOfferID>20000798</fromOfferID>
        <toOfferID>20000798</toOfferID>
    </transition>
</offer>

**Comment by rajkumar1979** [comment]
[OfferResponse.txt](https://github.com/square/retrofit/files/222178/OfferResponse.txt)

**Comment by JakeWharton** [comment]
This is a problem between your XML and the Simple library. Please consult a support forum (such as StackOverflow) which is appropriate for seeking help with that library.

**Comment by rajkumar1979** [comment]
Hi Jake,

I am sure this is not an issue with the Xml as when I use Jersey it can marshall the xml document correctly and send me the response, but the Simple Library in retrofit seems to have some issues.

Thanks

Raj

**Comment by JakeWharton** [comment]
Retrofit has nothing to do with the Simple library behavior. We just supply
a converter for it.

**Comment by rajkumar1979** [comment]
Can you please let me know whats the right forum or team that owns the simple library so that I can open an issue.

Thanks

Raj

**Comment by JakeWharton** [comment]
I have no idea. I think the library is hosted on sourceforge. StackOverflow
is also always an appropriate place.

**Comment by rajkumar1979** [comment]
Hi Jake,

When you say you simply provide a converter, do you mean to support if there are any issues with the converter.

I am using the retrofit converter com.squareup.retrofit2:converter-simplexml to un-marshall the xml document to a java object, I am trying to understand how can I move forward on this.

Appreciate your guidance.

Thanks

Raj.

**Comment by suvDev** [comment]
still this problem is there...
