### ISSUE TITLE
How to leave the @Post() empty ?

### ISSUE THREAD

**Issue by IskuhiSargsyan** [square/retrofit#1747]
I implemented via  volley ,and it worked as expected, now I want to use retrofit
The request is "post" and I send string data as requestBody. 
 @Post() I don't have anything to mention inside  the @Post() ,
as on the  backend side  from the content of the requestBody , knows what the request is it,
the  baseUrl = "....WebService/gateway.php";
when I leave empty the () it throws exception that is why I use to change the
 baseUrl = "...WebService/"; 
and @Post(gateway.php) ,I receive statusCode 200
with empty response 
what is the wrong my code?
 I would like to mention
that responseBodyConverter() never calls, while requestBodyConverter() -calls

----------------------------
 @Headers({
            "appType: 1"
    })
    @POST("gateway.php")
    Call<ResponseBody> update(@Body String requestBody);

------------------------------------
     Retrofit retrofit = new Retrofit.Builder().baseUrl("..../WebService/").
     addConverterFactory(new ToStringConverterFactory()).build();
     Service retrofitService = retrofit.create(Service.class);

        String strRequestBody = "req=<...></...>";
        Call<ResponseBody> call = retrofitService.update(strRequestBody);
        call.enqueue(new Callback<ResponseBody>() {
            @Override
            public void onResponse(Call<ResponseBody> call, Response<ResponseBody> response) {
              
                if (response.isSuccessful()) {
                    String strResponseBody = response.body().toString();
                }
            }

            @Override
            public void onFailure(Call<ResponseBody> call, Throwable t) {
            }
        });

-------------------------------

    public final class ToStringConverterFactory extends Converter.Factory {
        @Override
        public Converter<ResponseBody, ?> responseBodyConverter(Type type, Annotation[] annotations, Retrofit retrofit) {
            //noinspection EqualsBetweenInconvertibleTypes
            if (String.class.equals(type)) {
                return new Converter<ResponseBody, Object>() {

                    @Override
                    public Object convert(ResponseBody responseBody) throws IOException {
                        return responseBody.string();
                    }
                };
            }

            return null;
        }

        @Override
        public Converter<?, RequestBody> requestBodyConverter(Type type, Annotation[] parameterAnnotations, Annotation[] methodAnnotations, Retrofit retrofit) {
            if (String.class.equals(type)) {
                return new Converter<String, RequestBody>() {

                    @Override
                    public RequestBody convert(String value) throws IOException {
                        return RequestBody.create(MediaType.parse("text/plain"), value);
                    }
                };
            }

            return null;
        }

    }`

**Comment by arindamxd** [comment]
Solution?
