### ISSUE TITLE
Getting the request from HttpException

### ISSUE THREAD

**Issue by fen4o** [square/retrofit#1748]
I'm trying to get the request from a HttpException, but right now it only provides data for the response

``` java
someService.getData().subscribe(data -> handleData(data), e -> {
  if (e instanceof HttpException) { 
    HttpException exc = (HttpException) e;
    Response resp = exc.response(); // ok
    Request req = exc.request(); // not defined
    // handle req + resp
  }
});
```
Other than modifying the RxJavaCallAdapterFactory to enable this functionality is there another solution I can use?

**Comment by JakeWharton** [comment]
Use `resp.raw().request()`

**Comment by fen4o** [comment]
Great. Thanks.
