### ISSUE TITLE
Interface - Method Signature allow not annotated variables

### ISSUE THREAD

**Issue by SeameX** [square/retrofit#1754]
Hi,

this is a feature request and im not sure if i should post it here or @okhttp because the main features will be in the okhttp interceptor ;) But thats a good point to make your own!

**My Situation / Problem:**
We got a nice REST like API where we can create users in our system. To create a user you need to have already a user with the permission to create a user. A user consits of three main attributes userid, orgid and tenantid. We have a pojo that holds these three variables. Its called context. 

To Call our api you have to put these attributes to three single header fields like this:
Call<User> create(@Header("userid") UUID a, @Header("orgid") UUID b, @Header("tenantid") UUID b, , @Body User user)

For me as developer that is annoying because i have to split the context on every implementation and the method signature in my client is bloating up.

**How the Interface should look like (when you ask me):**
Call<User> create(Context context , @Body User user)
or
Call<User> create(@Header("context") Context context , @Body User user)

**Solutions:**

1. Make it possbile that i can define variables without annotations in the interface and make it that i can retrieve them via the interceptor. that would be the cleanest solution i can think of so far.

2. Another solution will be that i can pass Variables as Headers and retrieve these Variables in an interceptor. I know that this is possible already ;) The only problem ist that i just can retrieve strings from headers in the interceptor. I dont want to Parse the string back to my object. Remove this limitation and im happy :)

It would be awesome to see this in retrofit!

Best regards

Stefan

**Comment by JakeWharton** [comment]
This is going to be handled by #626 where you can define a handler for your hypothetical `Context` type, potentially with a custom annotation.

To your specific points though:

> Make it possbile that i can define variables without annotations in the interface and make it that i can retrieve them via the interceptor

Interceptors are an OkHttp concept which know nothing about your Retrofit interfaces or types beyond those it provides for making HTTP requests. We might add a Retrofit interceptor at some point but its goals probably won't align with this use case.

> The only problem ist that i just can retrieve strings from headers in the interceptor. I dont want to Parse the string back to my object. Remove this limitation and im happy :)

It's not really a limitation. Headers are strings because that's what a header is.

**Comment by swankjesse** [comment]
There's also the tag on the request, which you might be able to use here if you like.
