### ISSUE TITLE
Retrofit 2: Object Attributes null, Using GsonConverterFactory, StatusCode 200

### ISSUE THREAD

**Issue by VtheunforgivenV** [square/retrofit#1757]
Hi, 
today is started using Retrofit 2 (up from 1.6.1).
I want to request a User Object from Server. Via Retrofit i getting an User Object with all Attributes wich are null and StatusCode 200. Also when i using an intercepter the error occurs.
can you help me or say what is the error with this?

### build.gradle imports
```

    compile 'com.squareup.retrofit2:retrofit:2.0.2'
    compile 'com.squareup.retrofit2:converter-gson:2.0.2'
```
### Service:
```
@GET(Urls.LOGIN_URL)
Call<RetrofitUser> getUserDataAsUserObject(@Query("loginname") String userName, @Query("password") String password);
```

### Retrofit initialization
```
    private static String JSON_DATE_FORMAT = "yyyy-MM-dd'T'HH:mm:ssZ";

    public static RetrofitService getUserService() {
        RetrofitService service;
        synchronized (RetrofitClientProvider.class) {
            Retrofit retrofit = new Retrofit.Builder()
                    .baseUrl(Urls.BASE_URL)
                    .addConverterFactory(GsonConverterFactory.create(getGsonViaBuilder()))
                    .build();
            service = retrofit.create(RetrofitService.class);
        }
        return service;
    }

    private static Gson getGsonViaBuilder() {
        return new GsonBuilder().setDateFormat(JSON_DATE_FORMAT).create();
    }

```
### UserObject

```

public class RetrofitUser  {

    @SerializedName("firstname")
    private String firstname;
    @SerializedName("lastname")
    private String lastname;
    @SerializedName("email")
    private String email;
    @SerializedName("username")
    private String username;
    @SerializedName("uid")
    private Integer uid;
    @SerializedName("picture")
    private String pictureUrl;
    @SerializedName("usertoken")
    private String usertoken;

    /**
     * @return The firstname
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * @return The lastname
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * @return The email
     */
    public String getEmail() {
        return email;
    }

    /**
     * @return The username
     */
    public String getUsername() {
        return username;
    }

    /**
     * @return The uid
     */
    public Integer getUid() {
        return uid;
    }

    public String getPicture() {
        return pictureUrl;
    }

    /**
     * @return The usertoken
     */
    public String getUsertoken() {
        return usertoken;
    }


    @Override
    public String toString() {
        return "Firstname: " + getFirstname() + " - Lastname: " + getLastname() + " - Username: " + getUsername() + " - E_Mail: " + getEmail();
    }
}
```

### Fragment, which Requests the Data

```
public class RetrofitFragment extends Fragment{

    private static final String TAG = RetrofitFragment.class.getSimpleName();

    @Bind(R.id.fragment_retrofit_2_requested_username)
    TextView requestedUsername;

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_retrofit_2, container, false);
        ButterKnife.bind(this, view);
        return view;

    }

    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
    }


    @OnClick(R.id.fragment_retrofit_2_requestButton)
    protected void requestData() {
        RetrofitService service = RetrofitClientProvider.getUserService();
        Call<RetrofitUser> call = service.getUserDataAsUserObject("Mr_T", "test");
        call.enqueue(new Callback<RetrofitUser>() {
            @Override
            public void onResponse(Call<RetrofitUser> call, Response<RetrofitUser> response) {
                  response.body() <<--Attributes are null
            }

            @Override
            public void onFailure(Call<RetrofitUser> call, Throwable t) {

            }
        });
    }
```

### Json

```
{
  "user": {
    "uid": 11,
    "firstname": "Mr",
    "lastname": "T-Est",
    "email": "Mr_T@Test.com",
    "username": "Mr_T",
    "picture": null,
    "usertoken": "3dca80822788210d4ab96220ffe5c3068ab0422cf7c702c0115d88a28e25c51fcf6f10ce"
  }
}
```

**Comment by Orbyt** [comment]
response.body() returns a RetrofitUser in your case. Grab that and then access the needed fields.

**Comment by VtheunforgivenV** [comment]
the Problem is, that all field return null if i access them ...

**Comment by JakeWharton** [comment]
The fields you need to bind to are within the `"user"` key of the JSON not at the root. Create an object whose `user` field is a `RetrofitUser` so that the Java model matches the JSON model.

**Comment by Run-zan** [comment]
{
  "access_token": "-4hcKbuY_2C0x73kHk2P1d555cyUlPe0oR-fzYyvvEuGrY_hGYcMEabLUcYhi5VPPt7sWTEuwnZorLMTm4Q4IwA1y7Grzhrsukm_7_A8Qjxh2Qro9notDPOnWdPRrbPZOmn9Mlj0pzIMTY7S_w_SYR_gIgCmNDBfc8oo_rZNjcazFfpqD0hnCNoR1D6Ky7wonzyrXMiORRDq2hrVhtXiqVE9KZdGuk97M-GZ8fxLt9ZJeRV7j5Oa8Ghve-5En6bZ1fopVtIvY0a2AONxuc7Emk7RJHqx-XcS5Rt00-JBLoY",
  "token_type": "bearer",
  "expires_in": 1209599,
  ".issued": "Mon, 24 Apr 2017 10:14:36 GMT",
  ".expires": "Mon, 08 May 2017 10:14:36 GMT",
  "account": "{\"IsDefaultProfileImage\":true,\"IsDefaultCoverImage\":true,\"ProfileImage\":null,\"CoverImage\":null,\"Id\":22,\"LanguageId\":1,\"FirstName\":\"ranjan\",\"LastName\":\"Sharma\",\"DisplayName\":null,\"Email\":\"ranjan@gmail.com\",\"ContactEmail\":null,\"Tel\":null,\"Address\":null,\"Password\":\"$H$9pI1AoA1Brg7G1m7oXMPkvi7pZans./\",\"ActivationCode\":\"302d1b53-4bac-45bb-954a-f7a90f4cc8ff\",\"FacebookId\":null,\"FacebookToken\":null,\"TwitterToken\":null,\"TwitterTokenSecret\":null,\"IsAdmin\":false,\"IsActive\":true,\"IsDeleted\":false,\"CreatedDate\":\"2017-04-11T00:00:00\",\"UpdatedDate\":\"2017-04-11T00:00:00\",\"LastAccessDate\":null,\"UniqueName\":\"ranjan\",\"DefaultPageEnum\":0,\"DefaultShopEntityEnum\":0,\"DefaultCityId\":0,\"SignupSiteEnum\":0,\"SignupSite\":null,\"DefaultWallShopEntityIdFilter\":null,\"DefaultWallPublicFilter\":false,\"DefaultWallLocationEnumFilter\":0,\"DefaultWallIsDisplayOwnContentFilter\":false,\"DefaultSearchShopEntityIdFilter\":null,\"WallViewFavOnly\":null,\"Languages\":{\"Id\":1,\"Name\":\"English\",\"IsActive\":true}}"
}




how to wrok with this response using retrofit can anyone help please

**Comment by omurburuk** [comment]
Hi! I have a problem . So it,
I have a Object Ex : 
Order
class Order{
 @SerializedName("o_id")
    int ID;
    @SerializedName("o_name")
    String o_name="";
@SerializedName("videos")
    List<Video> videoList;
}
class Video{
@SerializedName("v_id")
    int ID;
@SerializedName("v_path")
    String vPath="";
}
Rest Controller Response Ex: 
{"video":{"v_id":"1","v_path":"asdsa","v_point":"21","v_accept_stateCastD":"1","v_accept_stateDirec":"0","v_update":"2017-05-01 13:12:53","u_id":"3","o_id":"1"},"order":{"o_id":"1","o_header":"Video Ay","o_scenario":"Video AyVideo AyVideo AyVideo Ay Video Ay","o_videopath":"","o_state":"1","o_createdate":"2017-05-12 00:00:00","o_lastdate":"2017-05-26 00:00:00","u_id":"3","o_di_id":"12"}}

I'm not getting  object data in object. Please help me

**Comment by NightlyNexus** [comment]
@omurburuk People can help on StackOverflow. Use the Gson tag there.

**Comment by novodimaporo** [comment]
Hello, got problem using retrofit. a compilation error saying cannot access javax.annotation.Nullable.
I spend the whole afternoon fixing this one.
