### ISSUE TITLE
Custom error handling

### ISSUE THREAD

**Issue by Yazon2006** [square/retrofit#1760]
Why there are no custom error handler in retrofit 2.0? It's very easy in retrofit 1.9. Why we should write crutches for handling errors for retrofit 2.0?! WTF?

**Comment by Yazon2006** [comment]
@JakeWharton

**Comment by swankjesse** [comment]
This issue tracker is not for design review.

**Comment by Yazon2006** [comment]
@swankjesse Ok, so you saying that shitty design it's not an issue?

**Comment by JakeWharton** [comment]
Use a CallAdapter. And maybe some class.

**Comment by Yazon2006** [comment]
@JakeWharton I'm using rxJava, CallAdapter not acceptable.

**Comment by JakeWharton** [comment]
CallAdapter works fine for RxJava seeing as that's how RxJava support is
implemented.
