### ISSUE TITLE
Deserialize DateTime Object ISO 8601 Time Zone

### ISSUE THREAD

**Issue by wcoc** [square/retrofit#1761]
Expecting a return JSON with an attribute containing a date in the format "2016-04-26T16:35:02.349-03:00" and format "yyyy-MM-dd'T'HH:mm:ss.SSS" But when performing deserialize only returns me null

I am using the following libs:
```
compile 'com.google.code.gson: Gson: 2.6.2'
compile 'com.squareup.retrofit2: convert Gson: 2.0.2'
compile 'com.squareup.retrofit2: Retrofit: 2.0.2'
compile 'com.squareup.okhttp3: logging-interceptor: 3.2.0'
```

Setting for request: http://pastebin.com/gc360C50
The Webservice is returning me: http://pastebin.com/ZHUfY0wi
My local object: http://pastebin.com/HdyieFMw

I made tests with the same dates and formats directly with SimpleDateFormat and functioned normally, but when I apply the Builder in retrofit it apparently does not accept the Builder, and does not convert the dates.

**Comment by JakeWharton** [comment]
You need to configure a `Gson` instance for the date format and pass that to `GsonConverterFactory.create()`. This will let Retrofit use the instance of Gson that knows about your date format when de/serializing request and response bodies. Retrofit isn't involved at all here in the actual date processing.

**Comment by wcoc** [comment]
As I sent on pastern

instance of Gson
```
Gson gson = new GsonBuilder()
                .setDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS")
                .create();
```

and set in retrofit instance
```
Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(URL_BASE)
                .addConverterFactory(GsonConverterFactory.create(gson))
                .client(client)
                .build();
```

I tested this same instance of Gson with a separate class to see if it is doing deserialize, and it worked properly. http://pastebin.com/9P3cn0Ks

```
String jsonString = "{\"dataAtualizacao\":\"2016-04-26T16:07:11.275-03:00\"}";
Gson gson = new GsonBuilder()
                .setDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS")
                .create();
DataTeste dTeste = gson.fromJson(jsonString, DataTeste.class);
 
Log.i("DataTeste", "-> " + dTeste.getDataAtualizacao().toString()); // ok here.
 
public class DataTeste {
 
    private Date dataAtualizacao;
 
    public Date getDataAtualizacao() {
        return dataAtualizacao;
    }
 
    public void setDataAtualizacao(Date dataAtualizacao) {
        this.dataAtualizacao = dataAtualizacao;
    }
}
```

**Comment by JakeWharton** [comment]
And if you use the web service response with that `Gson` instance and your real model object does it work?

**Comment by wcoc** [comment]
Yes, working! Look at the console.
![captura de tela 2016-04-26 as 17 10 55](https://cloud.githubusercontent.com/assets/7528360/14832714/fb5a7c68-0bd1-11e6-8de2-8310c4e7dba0.png)

**Comment by wcoc** [comment]
Sorry, I found the error, the Retrofit works well the error was mine!
