### ISSUE TITLE
405 Request method 'GET' not supported on POST request

### ISSUE THREAD

**Issue by serdarbuyukkanli** [square/retrofit#1762]
Im using Retrofit 1.9.0 to send this POST request:

@POST("/misc/set-push-token")
@FormUrlEncoded
void sendPushToken(@Field("platform") Integer platform, @Field("pushToken") String pushToken, Callback<Response> responseCallback);

and getting this error:

retrofit Error 405 Request method 'GET' not supported

Im sending POST request but it says me that 'GET not supported'.
Server side is working well. I tried it on Advanced Rest Client and it works.
How could it be possible?

**Comment by JakeWharton** [comment]
Your HTTP client is changing the POST to GET as a result of a 302 redirect.
Either change the server to return 307 or you'll need to switch to OkHttp
and write a custom network interceptor for manually following 302 redirects
and keeping the HTTP method.

Neither of these things are Retrofit-specific, so if you need assistance
the best place to seek help is on StackOverflow for those things.

**Comment by serdarbuyukkanli** [comment]
Thank you!

**Comment by osrl** [comment]
A question about the issue: I had the same issue and I've tried Volley to see if I was doing something wrong on the client side. There is a redirect issue but it worked well with Volley. Is this a design decision?
