### ISSUE TITLE
How to convert "?type=japanese,chinese" using Retrofit?

### ISSUE THREAD

**Issue by b95505017** [square/retrofit#1763]
http://blog.octo.com/en/design-a-rest-api/#filters
I am not able to use @Query to achieve this, using `String...` will cause `type=xx&type=yy`.

**Comment by JakeWharton** [comment]
You need to join the strings together yourself or use an object whose `toString()` joins them. We are not going to be adding support for custom joining inside of Retrofit since that's an application-layer concern.
