### ISSUE TITLE
Dynamically named top level json object

### ISSUE THREAD

**Issue by Orbyt** [square/retrofit#1764]
I am using Retrofit to make an api call. The top level object is named depending on the query parameters of the request. For example, a request like this:

`api.somewebsite.com/1.0/mix_info?mix_id=69`

returns a response like this:

    {"69":{
        "mix_id":"69",
        "mix_title":"A Title",
        "mix_file":"https:example.com/mp3",
        "mix_genres":"House,Pop",
        "mix_dj_id":"57",
        "number_votes":"390",
        "station":"1" 
        }
    }

Heres a screenie as well that kinda shows the format:
http://prnt.sc/axltcd

Basically, depending on the number passed into the url `mix_id=` query becomes the name of the top level json object returned in the response.

I was able to hack together something that kinda works:

I have a model Response class which has a member variable that is the top level object, and I use Retrofit's @SerializedName("69") to explicity set the name. This, of course, will only work for a request with the id of 69, otherwise the response returns null object.

It looks like this:

    public class Response {
        
         @SerializedName("69")
         private _69 _69;
    }

Is there a built in feature in Retrofit to handle these cases?

**Comment by JakeWharton** [comment]
StackOverflow is the right place for this question ([which you already posted on][1]) as it has nothing to do with Retrofit but Gson.

 [1]: http://stackoverflow.com/q/36898971/132047

**Comment by Orbyt** [comment]
Issue Template-

> - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
>        already exists! Don’t send pull requests to implement new features without first getting our
>        support. Sometimes we leave features out on purpose to keep the project small.

My last sentence: 

> Is there a built in feature in Retrofit to handle these cases?

Was checking if there was a built in solution to this issue. Thanks anyways.

**Comment by JakeWharton** [comment]
Retrofit doesn't take part in any serialization or deserialization. It just
hands the raw data to a converter. Retrofit doesn't know if you're speaking
JSON, Protobuf, or cat pictures over HTTP, all it knows is the HTTP part.

**Comment by Orbyt** [comment]
Ah, was under the impression `@SerializedName` was from Retrofit, it instead is from Gson. Thanks regardless.
