### ISSUE TITLE
POST form encoded with form field params not working

### ISSUE THREAD

**Issue by moonandroid** [square/retrofit#1766]
Can you please give any code snippet which work for  
@FormUrlEncoded
@POST("/abc") with @Field.

I have google at lots of places at all places they gives example for GET only.

**Comment by JakeWharton** [comment]
Here are some example from our tests: https://github.com/square/retrofit/blob/da766e8be9f8f61d5ddcf2fd0640c9bb8ff6f127/retrofit/src/test/java/retrofit2/RequestBuilderTest.java#L2088-L2199
