### ISSUE TITLE
Why Retrofit 2 document is so bad for beginners﻿?

### ISSUE THREAD

**Issue by 1c7** [square/retrofit#1769]
Hello, Retrofit community, I am beginner on android develop.
**I can't find any good tutorial & document about Retrofit 2 on Google**
Can you guys write more tutorial on Retrofit 2 ?
or recommend some tutorial & document ?
Thank you very much!

(English is not my native language, if I got grammar error, please point out help me improve, Thank you)

**Comment by swankjesse** [comment]
https://futurestud.io/blog/retrofit-2-upgrade-guide-from-1-9
