### ISSUE TITLE
Connection with PHP Rest API

### ISSUE THREAD

**Issue by WojciechCz** [square/retrofit#1771]
Today I was trying to connect with API written in php. Base url looks like this:

http://example.pl/path/api/?/test/

I want to do simple `GET` request with `@Path` replacement. So my request looks like this:

```
@GET("path/{X1}/{X2}")
Observable<Response<Beacon>> getBeacon(@Path("X1") String first, @Path("X2") int second);
```

When I code that I make request and I got exception, which surprise me. It appears that retrofit delete question mark from baseUrl. I google for that issue but can't find solution for that.

Using Retrofit 2.0 version 2.0.2

**Comment by JakeWharton** [comment]
Retrofit's combination of the method path and base URL works just like an `<a href="">` link, not just simple concatenation. This is what causes the `?/test/` part of your URL to appear to be deleted–query parameters are not retained across link resolution.

There's a few ways to accomplish what you want.

The easiest is just to prefix each relative path with the query prefix:
```java
@GET("?/test/path/{X1}/{X2}")
```

Beyond that you could do something like use an OkHttp interceptor to modify the request URL to change the normal path into a query param.

But in the current configuration, Retrofit (actually this behavior is from OkHttp) is behaving as expected.
