### ISSUE TITLE
Make error message more meaningful when converter factory for serialization is not defined

### ISSUE THREAD

**Issue by farmazon3000** [square/retrofit#1774]
Feature Request: can error message be more meaningful?

If one forget about this line
`.addConverterFactory(GsonConverterFactory.create())`
then he get's an error like so (I got one) http://stackoverflow.com/questions/34315499/unable-to-create-converter-for-java-util-list-retrofit-2-0-0-beta2

It may be useful to inform us in better way what exactly is wrong because it's easy to forget about this detail.

**Comment by JakeWharton** [comment]
The full message is
```
Unable to create converter for class java.lang.String
    for method CallMethod.disallowed
```
with a cause message of
```
Could not locate ResponseBody converter for class java.lang.String.
  Tried:
   * retrofit2.BuiltInConverters
```

What are you suggesting be added to make it clear? And remember, we can't know whether or not you're missing a converter, configured one incorrectly, or just used the wrong type on the interface.

**Comment by farmazon3000** [comment]
You are right - googling the solution took about 5 minutes so there may be nothing to change here.
