### ISSUE TITLE
Chinese confusion code when use simplexml converters(simplexml converter中文乱码)

### ISSUE THREAD

**Issue by ToDou** [square/retrofit#1775]
There is one problem that I get Chinese confusion code when the result contains Chinese.

The Post:
url:  http://mobitest.95522.cn/fcb/ReceiveXmlServlet
fields: 
reqXml=jix38dgQ7NydmcrakkLDlBimzmwbu06j2%2F0KQ%2BfWUoCqKtjt%2FzsexjOA1Ar96UGlrLarq124YIXZ%0A5OJw%2BeC6C6xx%2Bt6XCTqeCOZNqQHvp7stYTpdDC%2B5b1FOIUzmIRAy%2FTiKUiTs9YVCm7OrWNKbJ4gs%0A7LBjl8JmkzzOu57RYDCgqlU%2BFy7Wv3nUxjy0nIPmcCmQRi%2BWwwi5Xcils4Aj4%2Ba17o%2BsOjgu84DM%0AxUATT7POy58n2X%2BCd7AwECMc2Nt4O1MBvhLKTw4xZbqIjLlfiAqCT9UYsAq5%0A

The string result get from stream in log:
```
<?xml version="1.0" encoding="UTF-8"?><response><type>N</type><desc>您本人已经申领或您的家人帮您进行了申领</desc></response>
````

The Model:
```
@Root(name = "response")
public class XMLResponse {

    @Element(name = "type")
    String type;

    @Element(name = "desc")
    String desc;

    @Element(name = "policyNo", required = false)
    String policyNo;

    @Override
    public String toString() {
        return "XMLResponse{" +
                "type='" + type + '\'' +
                ", desc='" + desc + '\'' +
                ", policyNo='" + policyNo + '\'' +
                '}';
    }
}
```
The error result:
```
XMLResponse{type='N', desc='�����Ѿ��������ļ��˰������������', policyNo='null'}
```

I have translate result use utf-8 or others. But not working. I use ResponseBody.string() get the right result.
So at last, I change this in SimpleXmlResponseBodyConverter.class.in method "convert":
`      T read = serializer.read(cls, value.byteStream(), strict);
`
to 
`      T read = serializer.read(cls, value.string(), strict);
`
I have read the source in simple xml, but get no result about this problem. I prefer use responsebod.string(). I want to know this is one bug in simple-xml or not? Are there others solutions?

**Comment by JakeWharton** [comment]
Are you saying when you switch to `byteStream()` it correctly parses the Chinese characters?

**Comment by JakeWharton** [comment]
I wrote a test to mimic the behavior you said but it passes even with `byteStream()`:
```java
  @Test public void honorsCharacterEncoding() throws IOException {
    server.enqueue(new MockResponse().setBody(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?><response><type>N</type><desc>您本人已经申领或您的家人帮您进行了申领</desc></response>"));

    Call<XMLResponse> call = service.get2();
    Response<XMLResponse> response = call.execute();
    XMLResponse body = response.body();
    assertThat(body.desc).isEqualTo("您本人已经申领或您的家人帮您进行了申领");
    assertThat(body.type).isEqualTo("N");
  }
```
Do you know the `Content-Type` header value of the response?

**Comment by ToDou** [comment]
Oh,I got it. The response content-type is 'text/xml;charset=GBK'.

**Comment by JakeWharton** [comment]
Yep, thanks. I did get a test case working and will have a PR with a fix
shortly.

**Comment by ToDou** [comment]
I have saw the source in simple-xml, when parse the xml **PullProvider.provide** `When reading from an input stream the character encoding should be taken from the XML prolog or it should default to the UTF-8 character encoding`. But in the xml, the encode is utf-8. May this cause that result. And by using `string()` would get charset from content type from header. So use string get the right result from the server.

**Comment by JakeWharton** [comment]
That would buffer the entire response which is not what we want.

**Comment by pantos27** [comment]
Getting the same issue with Hebrew
Is there anything I should add to the SimpleXML converter to handle **Windows-1255** encoding?
example feed
http://www.ynet.co.il/Integration/StoryRss1854.xml

**Comment by shabarishbk** [comment]
<eTag>01#20170523121142615#fbb:b-6062e3097b214132b199adf5f264dd3c-4007682250-e4baf567-45a0-43ff-872e-a6faf18126c2</eTag>

I am getting exception : Caused by: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:184 in okhttp3.ResponseBody$BomAwareReader@fafd8f8) when the response xml has element like above, if i remove the # character from the element then it parses succesfully, can anyone please suggest how to deal with this issue, we cannot change the response xml to fix this problem.

**Comment by Shmulik-Danan** [comment]
@pantos27 
did you figure it out?
