### ISSUE TITLE
POST Request with JSON-Converters

### ISSUE THREAD

**Issue by dbaudach** [square/retrofit#1786]
I have an application that has a connection to a server. 
The server responds with JSON , I would like to convert into Java objects.

Interface looks like:
```
 @Headers({
            "Authorization: Basic YWRtaW46YWRtaW4=",
            "Content-Type: application/x-www-form-urlencoded",
            "Accept: application/sparql-results+json"
    })
    @POST("/annex/LichtScene/sparql/query")
    Observable<ScenesResponse> getScenes(@Body String userRequest);
```

When I call a POST with:

```
Retrofit retro = new Retrofit.Builder().baseUrl("http://10.0.3.2:5820/")
                .addConverterFactory(GsonConverterFactory.create())
                .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                .build();
        stardog = retro.create(Stardog.class);

        String body = "query=SELECT+%3FIDScene+WHERE+%7B+%3FIDScene+%3AhatPOI+%3FPOI+%7D";
        stardog.getScenes(body).subscribeOn(Schedulers.io()).observeOn(AndroidSchedulers.mainThread()).subscribe(new Observer<ScenesResponse>() {
            @Override
            public void onCompleted() {
            }

            @Override
            public void onError(Throwable e) {
                Timber.e(e.getMessage());
            }

            @Override
            public void onNext(ScenesResponse scenesResponse) {
            }
        });
```

I have the following problem: The request to the server is assembled incorrectly.
Wireshark output:
```
Form item: ""query" = "SELECT ?IDScene WHERE { ?IDScene :hatPOI ?POI }""
    Key: "query
    Value: SELECT ?IDScene WHERE { ?IDScene :hatPOI ?POI }"
```
There are inserted too many apostrophes.

If the return type is set to String and the converter to Scalar it works fine.
Wireshark output:
```
Form item: "query" = "SELECT ?IDScene WHERE { ?IDScene :hatPOI ?POI }"
    Key: query
    Value: SELECT ?IDScene WHERE { ?IDScene :hatPOI ?POI }
```
No extra apostrophes here.

**Comment by iagreen** [comment]
You are trying to serialize a single string as JSON, which is not going to be valid JSON.  The version of gson you are using is punting and just quoting it even though it isn't valid.  If you upgrade gson to the latest (2.6.2), you will get an `IllegalStateException` to alert you of the issue (unless you explicitly set it to `lenient == true`).  The solution is to add two converter factories, one for scalars to handle the `String` and gson to handle the other objects.  Add `ScalarsConverterFactory` before `GsonConverterFactory`.

```
Retrofit retro = new Retrofit.Builder().baseUrl("http://10.0.3.2:5820/")
                .addConverterFactory(ScalarsConverterFactory.create())
                .addConverterFactory(GsonConverterFactory.create())
                .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                .build();
```

**Comment by JakeWharton** [comment]
The scalar converter will work. You also can use `@FormUrlEncoded` and `@Field("query") String query`  (or `@FieldMap` if it's dynamic) to achieve the same result and to avoid having to do the encoding yourself.

```java
@Headers({
    "Authorization: Basic YWRtaW46YWRtaW4=",
    "Accept: application/sparql-results+json"
})
@FormUrlEncoded
@POST("/annex/LichtScene/sparql/query")
Observable<ScenesResponse> getScenes(@Field("query") String query);
```
and use like:
```java
service.getScenes("SELECT blah blah");
```

**Comment by JakeWharton** [comment]
And note that it sets the `Content-Type` header for you automatically.
