### ISSUE TITLE
CallbackRunnable: v1.9.0 

### ISSUE THREAD

**Issue by wviana** [square/retrofit#1792]
Hello,

I was getting error on class CallbackRunnable<T> when it try to dispatch a error into callback.
I better described it in here:
[FATAL EXCEPTION: Retrofit-Idle in Retrofit 1.9.0 before call `failure` callback in @FormUrlEncoded api method](http://stackoverflow.com/questions/37054106/fatal-exception-retrofit-idle-in-retrofit-1-9-0-before-call-failure-callback)

As you can see on my SOF question, I kind solve it by stoping using asynchronous request in that particular pice of code.

Right now I'm getting similar error in a different part of my code. When debugging I got into the same place of Retrofit.

```
@SuppressWarnings("unchecked")
  @Override public final void run() {
    try {
      final ResponseWrapper wrapper = obtainResponse();
      callbackExecutor.execute(new Runnable() {
        @Override public void run() {
          callback.success((T) wrapper.responseBody, wrapper.response);
        }
      });
    } catch (RetrofitError e) {
      Throwable cause = errorHandler.handleError(e);
      final RetrofitError handled = cause == e ? e : unexpectedError(e.getUrl(), cause);
      callbackExecutor.execute(new Runnable() {
        @Override public void run() {
          callback.failure(handled);
        }
      });
    }
  }
```

The line in above file (CallbackRunnable)  where is the code `final RetrofitError handled = cause == e ? e : unexpectedError(e.getUrl(), cause);`

I think it may be some bug.

**Comment by JakeWharton** [comment]
This exception can only occur when an `ErrorHandler` returns `null` and that simply isn't possible with the default one: https://github.com/square/retrofit/blob/parent-1.9.0/retrofit/src/main/java/retrofit/ErrorHandler.java#L52.

So you either have a custom `ErrorHandler` that causes `null` to be returned or you are using something like ProGuard which is breaking Retrofit's behavior.

All that said, there will be no updates to 1.9 anyway so I would strongly recommend migrating to 2.0 where `ErrorHandler` is eliminated in favor of the much more capable `CallAdapter` functionality.
