### ISSUE TITLE
retrofit 1.9 dependencies update request.

### ISSUE THREAD

**Issue by jjhesk** [square/retrofit#1793]
are there any updates for retrofit 1.9.0? the gson has new updates and its now 2.6.2. 
Are there any chances that 1.9 can be updated. [see this](http://mvnrepository.com/artifact/com.squareup.retrofit/retrofit/1.9.0). we have large amount of  the http request that is still based on 1.9.0 in production. Many thanks.

**Comment by jjhesk** [comment]
right now i just had to do it manually.. 
```gradle

    compile('com.squareup.retrofit:retrofit:1.9.0') {
        exclude group: 'com.google.code.gson', module: 'gson'
    }
    compile 'com.google.code.gson:gson:2.6.2'

```

**Comment by JakeWharton** [comment]
You don't need the exclude, just adding the explicit gson dependency is enough.

And we don't make releases just to track dependency updates. Adding the peer dependency is always recommended to ensure you get the version you expect.
