### ISSUE TITLE
Build a not REST API

### ISSUE THREAD

**Issue by BoBoMEe** [square/retrofit#1794]
Excuse me，My API is like this ：

http://xxx:8888/server/interfaceController.do?phoneStartPage&version=3&tap=1

and i don`t konw how to use ,thanks for your reply!!!

**Comment by JakeWharton** [comment]
```java
@GET("server/interfaceController.do?phoneStartPage") //
Call<SomeResponseType> doSomething(@Query("version") int version, @Query("tap") int tap);
```
