### ISSUE TITLE
Retrofit 2 Gradle Task to Build APK quits. ClassCastException

### ISSUE THREAD

**Issue by pparreno** [square/retrofit#1797]
Good Day Everyone!

I have just updated my Android Project to use the latest version of Retrovid (v2.0.2). The previous version I was using was v2.0.0-beta ('com.squareup.retrofit:retrofit:2.0.0-beta1').

Compiling and building the project is fine but when I try to test on the device and allowing Gradle to run the necessary tasks, it suddenly fails with this error:

```
Error:Execution failed for task ':app:compileProductionDebugJavaWithJavac'.
java.lang.ClassCastException: com.sun.tools.javac.code.Type cannot be cast to javax.lang.model.type.DeclaredType ndency cache may be corrupt (this sometimes occurs after a network connection timeout.) Re-download dependencies and sync project (requires network)

The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem. Stop Gradle build processes (requires restart)
Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.
In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
I need to use the latest version as there are bugs on the BETA version when generating an APK for Marshmallow devices.
```

It's been almost a week now and I can't seem to resolve this issue. I hope some of you can guide me at least to fix this. I've been hitting roadblocks here and there.

Stackoverflow [link](https://stackoverflow.com/questions/37253532/retrofit-2-gradle-task-to-build-apk-quits-classcastexception)

**Comment by JakeWharton** [comment]
What makes you think that this is a Retrofit issue? This looks like a general build system problem.

**Comment by embydextrous** [comment]
I think this can be solved by deleting .gradle folder and rebuilding again. Similar thing happened to me and I did that and it is working fine now.

**Comment by JakeWharton** [comment]
:+1:

**Comment by pparreno** [comment]
Thanks i fixed it by doing what embydextrous suggested as well as fixing some imports.
