### ISSUE TITLE
How to get json directly  without converter?

### ISSUE THREAD

**Issue by hozur** [square/retrofit#1799]
I am need to get the json string ,don`t need to convert to a java bean? How do the retrofit2 help me?Thanks!

**Comment by JakeWharton** [comment]
Use okhttp3.ResponseBody as the type.

**Comment by hozur** [comment]
it does work well, but needs to be wrapped with try-cath ! Thanks!  

 @Override
            public void onResponse(Call<ResponseBody> call, Response<ResponseBody> response) {
                try {
                    textView.setText(response.body().string());
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }

            @Override
            public void onFailure(Call<ResponseBody> call, Throwable t) {

            }
