### ISSUE TITLE
Use Jackson to convert Java Object to RequestBody.

### ISSUE THREAD

**Issue by andrew-buksha** [square/retrofit#1800]
Hello. I searched for a long time already, but couldn't find any example, that can help me understand how can I (and can I at all) use Jackson as default serializer.
Because of standard Gson converter was changing the order of my Object's properties (made them alphabetically ordered) I tried to use Jackson. But I think I missed something, because it gives me an error "Unable to convert RequestObject to RequestBody".
This code I used to change default retrofit converter:

```
ObjectMapper objectMapper = new ObjectMapper();
        JacksonConverterFactory jacksonConverterFactory = JacksonConverterFactory.create(objectMapper);
HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
interceptor.setLevel(HttpLoggingInterceptor.Level.BODY);
OkHttpClient client = new OkHttpClient.Builder().addInterceptor(interceptor).build();
Retrofit retrofit = new Retrofit.Builder()
        .baseUrl(BASE_URL)
        .addConverterFactory(jacksonConverterFactory)
        .client(client)
        .build();
return retrofit.create(ApiInterface.class);
```

And this is how I convert it (this code is exact same I used with Gson):

```
ApiInterface apiInterface = requestManager.getInterfaceService();
Call<ResponseObj> mService = apiInterface.postJson(new RequestObject("foo","bar","biz","baz"));
```

**Comment by JakeWharton** [comment]
Please paste the full stacktrace of the exception.

**Comment by vipinbpkyr** [comment]
RequestObject need getter property or make variables public

**Comment by 8codehub** [comment]
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
Add to your RequestObject
