### ISSUE TITLE
How to post both Object and File

### ISSUE THREAD

**Issue by ngochuu90** [square/retrofit#1803]
I must post: both Object and File

I'm using Retrofit 2.0.2

For example: 

@Multipart
@POST(Constants.FUNCTION_POST)
    Call<Result> postFile(
            @Part("message") Bmessage message, // Bmessage is Object
            @Part MultipartBody.Part file);
}

**Comment by amitshekhariitbhu** [comment]
You can use this library . This library supports this
[Android Networking](https://github.com/amitshekhariitbhu/AndroidNetworking)

**Comment by JakeWharton** [comment]
This is a usage question. Can you please ask on StackOverflow with the 'retrofit' tag?
