### ISSUE TITLE
Kotlin & @Body

### ISSUE THREAD

**Issue by dmitrikudrenko** [square/retrofit#1805]
I have a query
```
@PUT("/api/v3/{storeId}/categories/{categoryId}")
fun update(@Path("storeId") storeId: Int, @Path("categoryId") categoryId: Int?, @Query("token") token: String, @Body category: Map<String, Any>): Observable<OperationResultUpdated>
```
When I call it by
```
update(storeId, category.id, token, mapOf("name" to category2))
```
I receive an error 
```
java.lang.IllegalArgumentException: Parameter type must not include a type variable or wildcard: java.util.Map<java.lang.String, ?> (parameter #4)
```
How can I solve that problem?

**Comment by pedronveloso** [comment]
```@Body category: RequestBody```

**Comment by JakeWharton** [comment]
Just use `Object` for the value type?

**Comment by deviant-studio** [comment]
i forced to roll back retrofit interface back to java. ```Object``` didn't help

**Comment by tpom6oh** [comment]
I think it's happening because the `Map` declaration is `public interface Map<K, out V>` and the out word makes the value type generic. You can try to use `MutableMap` or `HashMap` instead.

**Comment by hzsweers** [comment]
You can still use Map, just suppress its wildcardness

```java
@PUT("/api/v3/{storeId}/categories/{categoryId}")
fun update(@Path("storeId") storeId: Int, @Path("categoryId") categoryId: Int?, @Query("token") token: String, @Body category: Map<String, @JvmSuppressWildcards Any>): Observable<OperationResultUpdated>
```

**Comment by PhanPirang** [comment]
I use @Body in @POST method with kotlin, my app always crash, however it work well with other method like @GET, @DELETE ...

**Comment by Alexander0024** [comment]
@hzsweers tks a lot, solve my problem.

**Comment by charchit28** [comment]
Hi @PhanPirang Use  @FormUrlEncoded for Post method. I think your problem will get solve

**Comment by charchit28** [comment]
Thanks @hzsweers. You save my Day :). I struggled  a lot to Resolve this problem. Thanks Buddy

**Comment by vpratfr** [comment]
I had a `List<Map<String, String>>`

That became: `@Field("exercises[]") exercises: List<@JvmSuppressWildcards Map<String, @JvmSuppressWildcards String>>`

Ugly but works :/ Thanks a lot @hzsweers

**Comment by GilbertoHdz** [comment]
@hzsweers   Thanks Buddy

**Comment by sergicastellsague** [comment]
This code works:
`    fun getSomethings(@Body body: HashMap<String, Any>): Observable<List<Something>>
`
This code does not work:
`    fun getSomethings(@Body body: Map<String, Any>): Observable<List<Something>>
`

**Comment by vibinr** [comment]
I went with this:
```kotlin
typealias StringAnyMap = Map<String, @JvmSuppressWildcards Any>
```

**Comment by ChineseBoyLY** [comment]
update Map to MutableMap

**Comment by cortinico** [comment]
(FYI @vpratfr)

Annotating the whole interface works as well:

```
@JvmSuppressWildcards
interface MyRetrofitApi {
    ...
}
```

And will avoid having parameters type like: `List<@JvmSuppressWildcards Map<String, @JvmSuppressWildcards String>>`
