### ISSUE TITLE
Question about Call<T>

### ISSUE THREAD

**Issue by Coine** [square/retrofit#1806]
What kind of issue is this?

 - [ ] Question. How can I set a Generic Response in APIService?
        I'm going to make a general List<T> request,but I don't know the type of List,

        public interface ApiService{
               @POST
               Call<List<T>> loadList(@Body HashMap<String, Object> bodyMap);
        }

        Just like above.

**Comment by JakeWharton** [comment]
Generic types cannot be supported since that type information is missing at runtime and thus cannot be used to deserialize the response.
