### ISSUE TITLE
StackOverflowError 

### ISSUE THREAD

**Issue by woody0518** [square/retrofit#1807]
Now I receive a Error as Follow , Any body can help me ? 

java.lang.StackOverflowError
java.lang.ThreadLocal.get(ThreadLocal.java:53)
dalvik.system.BlockGuard.getThreadPolicy(BlockGuard.java:140)
libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:163)
libcore.io.IoBridge.recvfrom(IoBridge.java:506)
java.net.PlainSocketImpl.read(PlainSocketImpl.java:489)
java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:241)
okio.Okio$2.read(Okio.java:139)
okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:906)
com.squareup.okhttp.internal.http.HttpEngine.access$300(HttpEngine.java:92)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:891)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.wbaiju.mall.retrofit.ApiServer$1.intercept(ApiServer.java:53)
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:868)
com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:749)
com.squareup.okhttp.Call.getResponse(Call.java:268)
com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224)
com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
com.squareup.okhttp.Call.access$100(Call.java:34)
com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162)
com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
java.lang.Thread.run(Thread.java:841)

**Comment by swankjesse** [comment]
You're adding the same interceptor multiple times. You should only add it once.
