### ISSUE TITLE
Erratically retrofit provides no response for an API call

### ISSUE THREAD

**Issue by jaisontj** [square/retrofit#1816]
Sometimes (always on app start) when I make an API call using retrofit 2, I get no response of any sort (success or error). As in, there is complete radio silence on the Android monitor. I am sure the Call is being made as the logs shows so (as shown below). 

I usually refrain from raising issues without proper research into the problem. But I am lost in this case. Any help would be appreciated.

The following is the log of me trying app start 3 times

### 05-24 18:00:20.383 15737-15737/com.slickup.android W/art: Failed to find OatDexFile for DexFile /data/data/com.slickup.android/files/instant-run/dex/slice-slice_7-classes.dex ( canonical path /data/data/com.slickup.android/files/instant-run/dex/slice-slice_7-classes.dex) with checksum 0x698b6e67 in OatFile /data/data/com.slickup.android/cache/slice-slice_7-classes.dex
05-24 18:00:22.235 15737-16081/com.slickup.android I/GMPM: App measurement is starting up
05-24 18:00:22.455 15737-15737/com.slickup.android I/CrashlyticsCore: Initializing Crashlytics 2.3.8.97
05-24 18:00:22.706 15737-16089/com.slickup.android D/libc: [NET] android_getaddrinfofornet+,hn 24(0x73657474696e67),sn(),hints(known),family 0,flags 4
05-24 18:00:22.706 15737-16089/com.slickup.android D/libc: [NET] android_getaddrinfofornet-, err=8
05-24 18:00:22.706 15737-16089/com.slickup.android D/libc: [NET] android_getaddrinfofornet+,hn 24(0x73657474696e67),sn(),hints(known),family 0,flags 1024
05-24 18:00:22.706 15737-16089/com.slickup.android D/libc: [NET] android_getaddrinfofornet-, pass to proxy
05-24 18:00:22.706 15737-16089/com.slickup.android D/libc: [NET] android_getaddrinfo_proxy+
05-24 18:00:22.706 15737-16089/com.slickup.android D/libc: [NET] android_getaddrinfo_proxy get netid:0
05-24 18:00:22.706 15737-16089/com.slickup.android D/libc: [NET] android_getaddrinfo_proxy-, success
05-24 18:00:22.866 15737-15737/com.slickup.android W/Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
05-24 18:00:23.426 15737-15737/com.slickup.android W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=4 r=0x7f0d00ac}
05-24 18:00:23.436 15737-15737/com.slickup.android W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=4 r=0x7f0d00ad}
05-24 18:00:23.486 15737-15737/com.slickup.android W/Resources: Converting to string: TypedValue{t=0x1d/d=0xff19b795 a=4 r=0x7f0c001b}
05-24 18:00:23.486 15737-15737/com.slickup.android W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=4 r=0x7f0d019c}
05-24 18:00:23.486 15737-15737/com.slickup.android W/Resources: Converting to string: TypedValue{t=0x5/d=0x1001 a=4 r=0x7f0800e6}
05-24 18:00:23.627 15737-15737/com.slickup.android W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=4 r=0x7f0d019d}
05-24 18:00:23.737 15737-16217/com.slickup.android D/OkHttp: --> GET https://slickup.herokuapp.com/authorize_user?authentication_token=yqYwzRR3mofaT_xJzc47 http/1.1
05-24 18:00:23.737 15737-16217/com.slickup.android D/OkHttp: --> END GET
05-24 18:00:23.767 15737-15737/com.slickup.android D/Atlas: Validating map...
05-24 18:00:23.777 15737-16217/com.slickup.android D/libc: [NET] android_getaddrinfofornet+,hn 21(0x736c69636b7570),sn(),hints(known),family 0,flags 4
05-24 18:00:23.777 15737-16217/com.slickup.android D/libc: [NET] android_getaddrinfofornet-, err=8
05-24 18:00:23.777 15737-16217/com.slickup.android D/libc: [NET] android_getaddrinfofornet+,hn 21(0x736c69636b7570),sn(),hints(known),family 0,flags 1024
05-24 18:00:23.777 15737-16217/com.slickup.android D/libc: [NET] android_getaddrinfofornet-, pass to proxy
05-24 18:00:23.777 15737-16217/com.slickup.android D/libc: [NET] android_getaddrinfo_proxy+
05-24 18:00:23.777 15737-16217/com.slickup.android D/libc: [NET] android_getaddrinfo_proxy get netid:0
05-24 18:00:23.797 15737-15737/com.slickup.android D/FindExtension: FindExtension: before mHardwareRenderer.initialize, mSurface.isValid() = true
05-24 18:00:23.797 15737-16221/com.slickup.android I/Adreno-EGL: <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.AF.1.1_RB1.05.00.02.006.020 - CR771817 ()
                                                                 OpenGL ES Shader Compiler Version: E031.25.03.06
                                                                 Build Date: 03/04/15 Wed
                                                                 Local Branch: 
                                                                 Remote Branch: refs/tags/AU_LINUX_ANDROID_LA.AF.1.1_RB1.05.00.02.006.020
                                                                 Local Patches: NONE
                                                                 Reconstruct Branch: NOTHING
05-24 18:00:23.827 15737-16217/com.slickup.android D/libc: [NET] android_getaddrinfo_proxy-, success
05-24 18:01:45.764 17599-17631/com.slickup.android I/GMPM: App measurement is starting up
05-24 18:01:45.944 17599-17634/com.slickup.android D/libc: [NET] android_getaddrinfofornet+,hn 24(0x73657474696e67),sn(),hints(known),family 0,flags 4
05-24 18:01:45.944 17599-17634/com.slickup.android D/libc: [NET] android_getaddrinfofornet-, err=8
05-24 18:01:45.944 17599-17634/com.slickup.android D/libc: [NET] android_getaddrinfofornet+,hn 24(0x73657474696e67),sn(),hints(known),family 0,flags 1024
05-24 18:01:45.944 17599-17634/com.slickup.android D/libc: [NET] android_getaddrinfofornet-, pass to proxy
05-24 18:01:45.944 17599-17634/com.slickup.android D/libc: [NET] android_getaddrinfo_proxy+
05-24 18:01:45.944 17599-17634/com.slickup.android D/libc: [NET] android_getaddrinfo_proxy get netid:0
05-24 18:01:45.964 17599-17599/com.slickup.android I/CrashlyticsCore: Initializing Crashlytics 2.3.8.97
05-24 18:01:45.974 17599-17634/com.slickup.android D/libc: [NET] android_getaddrinfo_proxy-, success
05-24 18:01:46.034 17599-17616/com.slickup.android I/art: Background sticky concurrent mark sweep GC freed 20248(1793KB) AllocSpace objects, 40(675KB) LOS objects, 55% free, 1890KB/4MB, paused 5.646ms total 33.999ms
05-24 18:01:46.185 17599-17599/com.slickup.android W/Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
05-24 18:01:46.435 17599-17599/com.slickup.android W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=4 r=0x7f0d00ac}
05-24 18:01:46.435 17599-17599/com.slickup.android W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=4 r=0x7f0d00ad}
05-24 18:01:46.475 17599-17599/com.slickup.android W/Resources: Converting to string: TypedValue{t=0x1d/d=0xff19b795 a=4 r=0x7f0c001b}
05-24 18:01:46.485 17599-17599/com.slickup.android W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=4 r=0x7f0d019c}
05-24 18:01:46.485 17599-17599/com.slickup.android W/Resources: Converting to string: TypedValue{t=0x5/d=0x1001 a=4 r=0x7f0800e6}
05-24 18:01:46.505 17599-17609/com.slickup.android W/art: Suspending all threads took: 5.829ms
05-24 18:01:46.595 17599-17599/com.slickup.android W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=4 r=0x7f0d019d}
05-24 18:01:46.695 17599-17672/com.slickup.android D/OkHttp: --> GET https://slickup.herokuapp.com/authorize_user?authentication_token=yqYwzRR3mofaT_xJzc47 http/1.1
05-24 18:01:46.695 17599-17672/com.slickup.android D/OkHttp: --> END GET
05-24 18:01:46.715 17599-17599/com.slickup.android D/Atlas: Validating map...
05-24 18:01:46.725 17599-17672/com.slickup.android D/libc: [NET] android_getaddrinfofornet+,hn 21(0x736c69636b7570),sn(),hints(known),family 0,flags 4
05-24 18:01:46.725 17599-17672/com.slickup.android D/libc: [NET] android_getaddrinfofornet-, err=8
05-24 18:01:46.725 17599-17672/com.slickup.android D/libc: [NET] android_getaddrinfofornet+,hn 21(0x736c69636b7570),sn(),hints(known),family 0,flags 1024
05-24 18:01:46.725 17599-17672/com.slickup.android D/libc: [NET] android_getaddrinfofornet-, pass to proxy
05-24 18:01:46.725 17599-17672/com.slickup.android D/libc: [NET] android_getaddrinfo_proxy+
05-24 18:01:46.725 17599-17672/com.slickup.android D/libc: [NET] android_getaddrinfo_proxy get netid:0
05-24 18:01:46.765 17599-17599/com.slickup.android D/FindExtension: FindExtension: before mHardwareRenderer.initialize, mSurface.isValid() = true
05-24 18:01:46.765 17599-17673/com.slickup.android I/Adreno-EGL: <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.AF.1.1_RB1.05.00.02.006.020 - CR771817 ()
                                                                 OpenGL ES Shader Compiler Version: E031.25.03.06
                                                                 Build Date: 03/04/15 Wed
                                                                 Local Branch: 
                                                                 Remote Branch: refs/tags/AU_LINUX_ANDROID_LA.AF.1.1_RB1.05.00.02.006.020
                                                                 Local Patches: NONE
                                                                 Reconstruct Branch: NOTHING
05-24 18:01:46.775 17599-17672/com.slickup.android D/libc: [NET] android_getaddrinfo_proxy-, success
05-24 18:03:35.701 19203-19233/com.slickup.android I/GMPM: App measurement is starting up
05-24 18:03:35.892 19203-19236/com.slickup.android D/libc: [NET] android_getaddrinfofornet+,hn 24(0x73657474696e67),sn(),hints(known),family 0,flags 4
05-24 18:03:35.892 19203-19236/com.slickup.android D/libc: [NET] android_getaddrinfofornet-, err=8
05-24 18:03:35.892 19203-19236/com.slickup.android D/libc: [NET] android_getaddrinfofornet+,hn 24(0x73657474696e67),sn(),hints(known),family 0,flags 1024
05-24 18:03:35.892 19203-19236/com.slickup.android D/libc: [NET] android_getaddrinfofornet-, pass to proxy
05-24 18:03:35.892 19203-19236/com.slickup.android D/libc: [NET] android_getaddrinfo_proxy+
05-24 18:03:35.892 19203-19236/com.slickup.android D/libc: [NET] android_getaddrinfo_proxy get netid:0
05-24 18:03:35.892 19203-19203/com.slickup.android I/CrashlyticsCore: Initializing Crashlytics 2.3.8.97
05-24 18:03:35.902 19203-19236/com.slickup.android D/libc: [NET] android_getaddrinfo_proxy-, success
05-24 18:03:36.112 19203-19203/com.slickup.android W/Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
05-24 18:03:36.372 19203-19203/com.slickup.android W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=4 r=0x7f0d00ac}
05-24 18:03:36.382 19203-19203/com.slickup.android W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=4 r=0x7f0d00ad}
05-24 18:03:36.422 19203-19203/com.slickup.android W/Resources: Converting to string: TypedValue{t=0x1d/d=0xff19b795 a=4 r=0x7f0c001b}
05-24 18:03:36.432 19203-19203/com.slickup.android W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=4 r=0x7f0d019c}
05-24 18:03:36.432 19203-19203/com.slickup.android W/Resources: Converting to string: TypedValue{t=0x5/d=0x1001 a=4 r=0x7f0800e6}
05-24 18:03:36.542 19203-19203/com.slickup.android W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=4 r=0x7f0d019d}
05-24 18:03:36.642 19203-19274/com.slickup.android D/OkHttp: --> GET https://slickup.herokuapp.com/authorize_user?authentication_token=yqYwzRR3mofaT_xJzc47 http/1.1
05-24 18:03:36.642 19203-19274/com.slickup.android D/OkHttp: --> END GET
05-24 18:03:36.662 19203-19203/com.slickup.android D/Atlas: Validating map...
05-24 18:03:36.662 19203-19274/com.slickup.android D/libc: [NET] android_getaddrinfofornet+,hn 21(0x736c69636b7570),sn(),hints(known),family 0,flags 4
05-24 18:03:36.662 19203-19274/com.slickup.android D/libc: [NET] android_getaddrinfofornet-, err=8
05-24 18:03:36.662 19203-19274/com.slickup.android D/libc: [NET] android_getaddrinfofornet+,hn 21(0x736c69636b7570),sn(),hints(known),family 0,flags 1024
05-24 18:03:36.662 19203-19274/com.slickup.android D/libc: [NET] android_getaddrinfofornet-, pass to proxy
05-24 18:03:36.662 19203-19274/com.slickup.android D/libc: [NET] android_getaddrinfo_proxy+
05-24 18:03:36.662 19203-19274/com.slickup.android D/libc: [NET] android_getaddrinfo_proxy get netid:0
05-24 18:03:36.693 19203-19203/com.slickup.android D/FindExtension: FindExtension: before mHardwareRenderer.initialize, mSurface.isValid() = true
05-24 18:03:36.693 19203-19275/com.slickup.android I/Adreno-EGL: <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.AF.1.1_RB1.05.00.02.006.020 - CR771817 ()
                                                                 OpenGL ES Shader Compiler Version: E031.25.03.06
                                                                 Build Date: 03/04/15 Wed
                                                                 Local Branch: 
                                                                 Remote Branch: refs/tags/AU_LINUX_ANDROID_LA.AF.1.1_RB1.05.00.02.006.020
                                                                 Local Patches: NONE
                                                                 Reconstruct Branch: NOTHING
05-24 18:03:36.743 19203-19274/com.slickup.android D/libc: [NET] android_getaddrinfo_proxy-, success

**Comment by JakeWharton** [comment]
Are you sure a network error isn't being thrown? Try OkHttp 3.3.0 which added logging when the connection fails.

**Comment by jaisontj** [comment]
Hi Jake. Thank you for the reply. And yeah, you're right. The problem is not with retrofit but with something i'm doing which returns a network error on app start(sometimes :/). No idea why though.Anywho, Thanks again.
