### ISSUE TITLE
@Path param ignores registered TypeAdapter

### ISSUE THREAD

**Issue by jkwiecien** [square/retrofit#1817]
I'm having a custom object object as a part of path:```@GET("api/{date}/something")
    Observable<Void> logFood(@Path("date") DateTime date)``` 

Registered `TypeAdapter` registered with `GsonBuilder`: 
```new GsonBuilder()
                .registerTypeAdapter(DateTime.class, new DateTimeTypeAdapter())```

However, url is built with `2016-05-24T14:47:57.475+02:00` which is not formatted as desired and is probably just `toString()` of `DateTime`

Is it known issue? Do I have to refrain from putting final class objects in the path? If it wasn't final I could overwrite `toString()`

Let me know if there is a sample project or failing test necessary.

**Comment by JakeWharton** [comment]
`@Path` does not use Gson because it is not JSON, it merely wants a String. You can register a Converter.Factory which handles `DateTime` in its `stringConverter` method and perform any necessary conversion.
