### ISSUE TITLE
POST method occur Bad Request

### ISSUE THREAD

**Issue by wuhaiyang** [square/retrofit#1819]
compile 'com.squareup.okhttp3:okhttp:3.3.0'
  compile 'com.squareup.retrofit2:retrofit:2.0.2'
    compile 'com.squareup.retrofit2:converter-gson:2.0.2'
    compile 'com.squareup.retrofit2:adapter-rxjava:2.0.2'

 @POST("http://hostip/api/user/{id}/friends/{to}")
    Call<ResponseBody> addFriend(@Path("id") int myId, @Path("to") int target,@Body String emptyString);
 Call<ResponseBody> addFriend = RetrofitManager.newInstance().getApi().addFriend(18, 14,"");
Response{protocol=http/1.1, code=400, message=Bad Request, url=.....}

what can i do ?

**Comment by JakeWharton** [comment]
Bad Request is a disagreement between your request and the server. So we have no way of knowing what the server expects or what you're doing wrong. Consult your server team or API documentation and compare it with the request you are making. You can use OkHttp's logging interceptor to log the raw request and compare it with what the server expects.

**Comment by wuhaiyang** [comment]
Thank you very much, I has now been solved,My solution is  extends RequestBody rewrite contentLength method.just like this:RetrofitManager.newInstance().getApi().addFriend(18, 14, EmptyOutput.INSTANCE);

**Comment by Henrryagc** [comment]
This code worked for me to watch bodyError message
 AndroidStudio Kotlin
Retrofit and Coroutines
if (response.code() == 400) {
                response.errorBody()?.let { Log.e("error", it.string()) }             
            }
