### ISSUE TITLE
Support protobuf 3.0 when released.

### ISSUE THREAD

**Issue by brilliance-boy** [square/retrofit#1821]
@JakeWharton 
Hi Wharton，
Retrofit is really a delightful networking framework for android. But we have recently found “ProtoConverterFactory” is not support ProtoBuf 3.0. So we want to know when you can update the ProtoConverter.

Thank you very much.

**Comment by JakeWharton** [comment]
We've been waiting for the API to stabilize since we don't support
pre-release versions.

**Comment by fabriciointerama** [comment]
Yes, please. I'm waiting for it too.

@brilliance-boy 
Meanwhile, I'm using this workaround. I just copied the `ProtoConverterFactory` class code for a own class (I couldn't extend it because it is `final` and private :cry:) and I added the following:

```
Field field = c.getDeclaredField("PARSER"); // find this line
field.setAccessible(true);                  // insert this line
```

Or just get [this gist code](https://gist.github.com/fabriciointerama/22178fe28528bd2919a02f171680ca13).

**Comment by echavda** [comment]
@fabriciointerama @brilliance-boy 

Hello Both, 

can you please give me some example how we can use protobuf in retrofit - i tried but its failed with some error , let me give you sample of my implementation on that.

i hope you guys will help me. 


ApiInterface.java
```
public interface ApiInterface {
    @GET
    Call<CommonProto.Country> makeGetRequest(@Url String url);
}
```

ApiClient.java
```
public class ApiClient {

    public static final String BASE_URL = "**************************";

    private static Retrofit retrofit = null;


    public static Retrofit getClient() {
        if (retrofit==null) {
            retrofit = new Retrofit.Builder()
                    .baseUrl(BASE_URL)
                    .addConverterFactory(Proto3ConverterFactory.create())
                    .build();
        }
        return retrofit;
    }

}

```

MainActivity.java
```
ApiInterface apiService =
                ApiClient.getClient().create(ApiInterface.class);

Call<CommonProto.Country> call = apiService.makeGetRequest("Services/CountryServices/GetAllCountry");

        call.enqueue(new Callback<CommonProto.Country>() {
                         @Override
                         public void onResponse(Call<CommonProto.Country> call, Response<CommonProto.Country> response) {
                             String bodyString = null;
                             try {
                                 Log.e("RETROFIT  ::::::: ", String.valueOf(response.body())+"TEST");
                             } catch (Exception e) {
                                 Log.e("RETROFIT ERROR  ::::::: ", e.getMessage()+"TEST");
                                 e.printStackTrace();
                             }

                         }

                         @Override
                         public void onFailure(Call<CommonProto.Country> call, Throwable t) {
                             // Log error here since request failed
                             Log.e(TAG, t.toString());
                         }
                     }

        ); 
```

when i run this way i got the error 
java.lang.RuntimeException: com.google.protobuf.InvalidProtocolBufferException: Protocol message tag had invalid wire type.

I have attached the Proto File with this message please find the attachment.

[CommonProto.java.zip](https://github.com/square/retrofit/files/390594/CommonProto.java.zip)
[CommonProto.proto.zip](https://github.com/square/retrofit/files/390593/CommonProto.proto.zip)

Please let me know how to do this GET Req and also i was Struggling with POST Req.

Thanks In advance , 
Madhav

**Comment by JakeWharton** [comment]
I'd be interested to hear how the current protobuf converter wasn't working with 3.0, because in all my tests it works fine. In any case, we've updated it.
