### ISSUE TITLE
Is there a way to save session after user is logged in?

### ISSUE THREAD

**Issue by IskuhiSargsyan** [square/retrofit#1822]
I need to save session ,after user logged in and receive Set-Cookie (it could be more than 1) in headers as response , it should be saved and be sent in headers with  others requests and it should be reset when user logged out.
It could be done automatically or we need to implement it ,if yes how?

I was using volley and it handles only unique headers ,
headers are HashMap I receive only one Set-Cookie, it cause some problems, that is why I'll use Retrofit, while need to know is there a way to implement saving session.

**Comment by JakeWharton** [comment]
You can set a `CookieJar` on an `OkHttpClient` implementation which will automatically persist and send cookies: http://square.github.io/okhttp/3.x/okhttp/okhttp3/CookieJar.html. Retrofit has no built-in mechanism for this though.

**Comment by IskuhiSargsyan** [comment]
Could you provide a sample?

**Comment by JakeWharton** [comment]
I don't have time to write samples for everything, sorry. If someone else
wants to do so they're welcome.
