### ISSUE TITLE
How to set "noNamespaceSchemaLocation" in retrofit2:converter-simplexml?

### ISSUE THREAD

**Issue by 7odri9o** [square/retrofit#1825]
I ned to use a xml webservice that has "noNamespaceSchemaLocation" with a *.xsd value. When consuming it on android application with retrofit and converter-simplexml content is not recognized.

`<?xml version = '1.0' encoding='UTF-8'?>
<ListaParlamentarEmExercicio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://legis.senado.leg.br/dadosabertos/dados/ListaParlamentarEmExerciciov4.xsd">`

What kind of issue is this?

 - [x] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by JakeWharton** [comment]
You'll have to consult the documentation for the Simple XML library or ask on StackOverflow using an appropriate tag for the library. This isn't a problem (or question) about Retrofit itself.

**Comment by 7odri9o** [comment]
Ok Jake! I asked here because I was talk about "com.squareup.retrofit2:converter-simplexml" that is a plugin to do a funcionality that retrofit don't have.

**Comment by JakeWharton** [comment]
That is just a shim for the Simple library. We have never used it so we
have no knowledge of how to configure it.
