### ISSUE TITLE
Getting callback in espresso tests in RetroFit

### ISSUE THREAD

**Issue by wingoku** [square/retrofit#1827]
How can I get a callback from retrofit in the espresso test?

**Comment by JakeWharton** [comment]
I don't understand the question. You want to get the actual responses in your test? Or you just want your test to wait for the responses before moving on?

**Comment by wingoku** [comment]
I want my test to wait for the response before I start executing the rest of the tests. Although I have found a workaround but it's not elegant at all. The problem with my workaround is, I have added a callback from the fragment class to the test class (which is neither good nor a sane solution, however it works for me at the moment). The callback runs on a separate thread and that thread can't be used to run the espresso tests. 

I have written a detailed article [here](https://medium.com/@wingoku/the-incongruity-of-retrofit-network-calls-and-espresso-46ff6e1199a#.7ainvknro) along the code.

**Comment by JakeWharton** [comment]
Retrofit doesn't do anything with threads for async, that's all delegated down to other libraries.

You'll need to create an idling resource around an `Executor` that you then pass to an `OkHttpClient`'s `Dispatcher`. Then you would use that `OkHttpClient` when creating the `Retrofit` instance. You'll have to do this manually as Espresso doesn't have factories for wrapping `Executor`s / `ExecutorService`s [yet](http://b.android.com/187510).

**Comment by wingoku** [comment]
You are correct that Retrofit doesn't do anything with the threads. What I tried to say was the thread on which the app is executed and the thread on which espresso tests are executed are separate ones, or at least that's what I have learned during my testing.

I'll try to write the code like you have describe. I am sure that will fix the problem.

**Comment by JakeWharton** [comment]
Yeah by default tests execute on a background thread and not the main
thread. You can use the `@MainThread` annotation if you want to force the
test onto the main thread, although this has a potential to dead lock
Espresso (because it assumes it can block the current thread).

A sample showing how to setup OkHttp+Retrofit with Espresso would be useful
for us to point people to if you want to make it public or write another
article about it. It's just too far out of scope for inclusion here and we
don't really have to time to create it.

**Comment by wingoku** [comment]
Exactly.

Sure. Understandable. I'll write one and let you know here.

**Comment by wingoku** [comment]
Hey Jake, I made my custom ExecutorService and passed it to dispatcher however there doesn't seem to be the synchronizatoin between the libraries. So as a resort, I am setting the idleFlag = true when network call is complete or no network call has occured and false otherwise, the problem of synchronization persists here again. When I set the idleFlag = true, Espresso doesn't get notified right away, as a result, it resumes tests at a later point of time and by that the UI to test is gone.

May be I am making some mistake or missing something. However it's 3 in the morning so I guess I'll hit the bed.

**Comment by wingoku** [comment]
@JakeWharton Here are the gists. I have wrote the following code but so far nothing successful occurred . I am sure I am missing something otherwise this should have worked.

[Espresso Test method](https://gist.github.com/wingoku/3f5058dcec644e8ad6ac5e1c42cfe958)

[MyExecutor.java](https://gist.github.com/wingoku/25260987cebc37c7413e18bb09b25c88)

**Comment by JakeWharton** [comment]
FYI we're going to add support into OkHttp so that creating an IdlingResource around a Dispatcher is really easy: https://github.com/square/okhttp/issues/2600

**Comment by wingoku** [comment]
Great! I hope until then my effort will be fruitful for others.
