### ISSUE TITLE
the proguard with body entity

### ISSUE THREAD

**Issue by magenchen** [square/retrofit#1830]
when I use Retrofit2.0，I write a request entity,like this
public class LoginRequest {
    public String phone;
    public String password;
    public String signtype;
    public String adId;
    public String appId;
    public String clientId;
    public String channel;
    public String blackBox;
}

And it will be confused by proguard file,if I don't ,it will expose to somebody that decompile our company's  apk。How to fix the problem。

**Comment by artem-zinnatullin** [comment]
No matter how you obfuscate it you'll still have mapping of fields to some
string names (JSON/XML/query or form params) in the code. Also, nothing
really stops somebody from sniffing http traffic, even if you use https.

Anyway your API is probably available for anybody in the internet, I
believe obfuscation of that particular part of the app is not something you
should worry that much about.

**Comment by JakeWharton** [comment]
This is not a Retrofit issue so for recommendations I would advise seeking help elsewhere (such as StackOverflow).

For JSON the key will always need encoded either in field names or annotations on the field. Alternate serialization formats allow full obfuscation as they use opaque field numbers to encode keys (like protocol buffers) but the data would still be parseable.
