### ISSUE TITLE
config special interface connection timeout with okhttp?

### ISSUE THREAD

**Issue by sharyuke** [square/retrofit#1836]
how to config special interface connection timeout with okhttp?
I have some special interfaces which expect connection timeout is short e.g.  2s . and other interfaces should be long  e.g. 10s, how to config the special one with okhttp via retorfit without defind another OkHttpClient?

**Comment by JakeWharton** [comment]
Share common configuration in the builders and then customize each to suit.
```java
OkHttpClient.Builder httpBuilder = new OkHttpClient.Builder() // + common setup...
Retrofit.Builder retrofitBuilder = new Retrofit.Builder() // + common setup...

OkHttpClient shortHttpClient = httpBuilder.readTimeout(2, SECONDS)
    .writeTimeout(2, SECONDS)
    .connectTimeout(2, SECONDS)
    .build();
Retrofit shortRetrofit = retrofitBuilder.client(shortHttpClient).build();
ShortInterface short = shortRetrofit.create(ShortInterface.class);

OkHttpClient longHttpClient = httpBuilder.readTimeout(15, SECONDS)
    .writeTimeout(15, SECONDS)
    .connectTimeout(15, SECONDS)
    .build();
Retrofit longRetrofit = retrofitBuilder.client(longHttpClient).build();
LongInterface long = longRetrofit.create(LongInterface.class);
```
We'll eventually support Retrofit-level interceptors which will allow changing timeouts using things like annotations per-interface or per-endpoint ( #1732 ).

**Comment by sharyuke** [comment]
that was I did rgiht now ,but it will be have two Retrofits instance in memory.

**Comment by JakeWharton** [comment]
They aren't that expensive such that you need to worry about that. The
generated implementations of interfaces are the expensive bits that you
only want one of each.

**Comment by sharyuke** [comment]
ok got that ,thanks ,but i hope retrofit can set special connection timeout to each of interface, like @POST ,@GET @HEADERS ... annotations . by the way . I  hope retrofit can set common params to every interfaces created by ```public <T> T create(final Class<T> service) {``` ,so that i can defind less params to every method.
