### ISSUE TITLE
Retrofit with Post not working.

### ISSUE THREAD

**Issue by moonandroid** [square/retrofit#1842]
@JakeWharton 
When i used @Post with @Field then every time getting null in retrofit:2.0.2.

 public static Retrofit getLogin() {
 private static Retrofit retrofit = null;
     String MAIN_URL = "http://xxxxxxxxxxx/xxxxx/wp-content/plugins/xxxxxx/webservices/";

        HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
        interceptor.setLevel(HttpLoggingInterceptor.Level.BODY);
        OkHttpClient okHttpClient = new OkHttpClient.Builder().addInterceptor(interceptor).build();

        if (retrofit==null) {
            retrofit = new Retrofit.Builder()
                    .baseUrl(MAIN_URL)
                    .addConverterFactory(GsonConverterFactory.create())
                    .client(okHttpClient)
                    .build();
        }
        return retrofit;
    }

--------------------
 @FormUrlEncoded
    @POST("login.php")
    Call<User> loginUser(@Field("login_type") String login_type, @Field("email") String email,
                         @Field("password") String password, @Field("deviceID") String deviceID,
                         @Field("push_token") String push_token, @Field("platform") String platform);

-------------------

 ApiInterface apiService =
                ApiClient.getLogin().create(ApiInterface.class);

        Call<User> call = apiService.loginUser("Rider","test@test.com","Test123@",
                "d653106c52bcdbb2",
                "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "android");
       
        call.enqueue(new Callback<User>() {
            @Override
            public void onResponse(Call<User> call, Response<User> response) {
                int statusCode = response.code();
                Log.e("Tag","onResponse response "+response.isSuccessful());
                Log.e("Tag","onResponse" +response.body().toString());

            }

            @Override
            public void onFailure(Call<User> call, Throwable t) {
                Log.e("Tag","onResponse onFailure" );
            }
        });

Can you please give suggestion here?
In response always getting null but when i used retrofit:1.9.0 with  RestAdapter restAdapter then working properly.

**Comment by swankjesse** [comment]
Please ask usage questions on StackOverflow.

**Comment by moonandroid** [comment]
Not getting proper solution so i asked here.

**Comment by JakeWharton** [comment]
If you think it's a bug an executable test case goes a long way. We can't
know how the server behaves to try and reproduce.

**Comment by moonandroid** [comment]
When i used retrofit:1.9.0 with RestAdapter then working properly but when i updated retrofit with 2.0.2 then create issue.
So can you give any sample code in which Post method uses @Field in 2.0.2
