### ISSUE TITLE
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.

### ISSUE THREAD

**Issue by huangbao** [square/retrofit#1843]
private RetrofitWapper() {
        //手动创建一个OkHttpClient并设置超时时间
        OkHttpClient.Builder builder = new OkHttpClient.Builder();
        builder.connectTimeout(DEFAULT_TIMEOUT, TimeUnit.SECONDS);
        mRetrofit = new Retrofit.Builder()
                .client(builder.build())
                .addConverterFactory(GsonConverterFactory.create())
                .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                .baseUrl(AppConstants.SERVER_URL)
                .build();

        mYouxianService = mRetrofit.create(YouxianService.class);
    }

    public void getList(Subscriber subscriber) {
        // 对于错误这里可做统一处理 TODO
        mYouxianService.getHomeList()
                .subscribeOn(Schedulers.io())
                .unsubscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(subscriber);
    }
 @Headers({
            "Accept: application/json",
            "Content-Type: application/json"
    })
    @GET("ffrediscache/mobile/v2/index/uri/catalog.product.getHomeCategoryProducts")
    Observable<HomeEntity> getHomeList();

Can't take special characters?

**Comment by artem-zinnatullin** [comment]
What is the exception message and stacktrace?
