### ISSUE TITLE
Retrofit 2.0 url encoding encodes characters like '=' '&'

### ISSUE THREAD

**Issue by tsaha-cse** [square/retrofit#1844]
I'm using Retrofit 2.0 in one my project. While requesting a GET request I found 200 OK response but the response body coming is empty. When I log the okhttp execution I found the url is getting encoded (i.e: '=' is replaced by '\u003d' and '&' is replaced by '\u0026'). Which isn't supported by server side. I'm using following versions.

```
compile 'com.squareup.retrofit2:retrofit:2.0.0-beta4'
compile 'com.squareup.okhttp3:logging-interceptor:3.3.1'
compile 'com.squareup.retrofit2:converter-gson:2.0.2'
compile 'com.squareup.retrofit2:converter-scalars:2.0.0'
```
Request body looks like

```
@GET("ads")
Call<JSONObject> getAd( @Query("filter[q]") String queryText,
                        @Query("page[size]") int pageSize,
                        @Query("page[number]") int pageNumber);
```
In logcat the request url looks like following:

`....?filter[q]\u003dtest\u0026page[size]\u003d5\u0026page[number]\u003d1`

I tried by following solution by not worked for me.

```
@GET("ads")
Call<JSONObject> getAd( @Query(value = "filter[q]", encoded = false) String queryText, ....)
```

I've also tried the possible [solution](http://stackoverflow.com/questions/26637340/prevent-retrofit-from-encoding-my-http-request-body). But not working for Retrofit 2.0. Is there any way to avoid/change the encoding behavior ? Thanks in advance.

**Comment by tsaha-cse** [comment]
I've also tried the following solution. But didn't worked for me.
https://github.com/square/retrofit/issues/1658
https://github.com/square/retrofit/issues/1622
https://github.com/square/retrofit/issues/1786

**Comment by swankjesse** [comment]
That's surprising. \u003d is a JSON escape, not a HttpUrl escape.

**Comment by swankjesse** [comment]
How are you getting the URL to log to logcat? Are you using Gson?

**Comment by tsaha-cse** [comment]
@swankjesse  I'm getting all data flow using `LoggingInterceptor`.
`com.squareup.okhttp3:logging-interceptor:3.3.1`
I'm getting following as an important case in the log

`{"code":"ResourceNotFound","message":"//ads%3Ffilter%5Bq%5D%3Dtest%26page%5Bsize%5D%3D5%26page%5Bnumber%5D%3D1%26sort%5Blist_time%5D%3Ddesc%26filter%5Bip%5D%3D192.168.1.1%26filter%5BuserLonLat%5D%3D%5B90.412518%2C23.810332%5D does not exist"}`

yes I'm using Gson
`com.squareup.retrofit2:converter-gson:2.0.2`

**Comment by JakeWharton** [comment]
Neither Retrofit nor OkHttp is doing anything here. That data is how it appears from whatever server you are talking to which is the one which is specifying the percent-encoding for the JSON string value.

**Comment by Robbypatel1357** [comment]
Hello can any one has solution for this kind of special charater
