### ISSUE TITLE
How to convert xml getting xml object and string as well?

### ISSUE THREAD

**Issue by IskuhiSargsyan** [square/retrofit#1845]
I receive as response xml, I need to get object which is parsed xml object and raw xml string.

**Comment by JakeWharton** [comment]
The best way to do this is a custom converter. You need a type that can carry both instances (like a `Pair<T1, T2>`). Your endpoint would be defined like:
```java
@GET("whatever")
Call<Pair<User, String>> whatever();
```
and then your custom `Converter.Factory` would match on `Pair.class`, use reflection to get the first type parameter type of `User.class`, call `retrofit.nextResponseBodyConverter(firstType, annotations);`, and then return a `Converter` which read the string, delegated, and then wrapped things up in a `Pair`.
```java
Type firstType = // reflection
Converter<ResponseBody, Object> delegate = retrofit.nextResponseBodyConverter(firstType, annotations);
return new Converter<ResponseBody, Pair<Object, String>>() {
  @Override public Pair<Object, String> convert(ResponseBody body) {
    String string = body.string();
    Object object = delegate.convert(ResponseBody.create(null, string));
    return new Pair<>(object, string);
  }
};
```

**Comment by BanksA761** [comment]
@JakeWharton @IskuhiSargsyan 
I have the same task, I'm new in android, please provide me more detail code,
I could not understand how I need to use it to implement my task
where to call this part, how implement converter with pair<>

**Comment by JakeWharton** [comment]
I do not have the bandwidth to provide full working solutions for
everything, sorry.

**Comment by BanksA761** [comment]
Any link, or any more detail  advise could be useful for me.

**Comment by BanksA761** [comment]
@JakeWharton @IskuhiSargsyan 
Please give me tips

**Comment by BanksA761** [comment]
@JakeWharton 
Please give a tip .Thanks in advance.

**Comment by eneim** [comment]
Your question could be answer quicker [here](https://stackoverflow.com)

**Comment by BanksA761** [comment]
I asked but no good response.

**Comment by BanksA761** [comment]
I  know I'm asking too much ,but  @JakeWharton please give me some tips .
