### ISSUE TITLE
Order of attributes in POST request

### ISSUE THREAD

**Issue by josephlam1984** [square/retrofit#1846]
The Amazon S3 REST API requires the attributes in a POST request to be submitted in a specific order (i.e. the key field needs to go before the file field).

I understand that the official JSON specification suggests that the order of attributes should not matter in a transmission. However, given the above requirement, can retrofit support a manual, explicit ordering of attributes when putting together a POST request?

Thanks!

**Comment by JakeWharton** [comment]
Ordering is based on what you provide.

**Comment by josephlam1984** [comment]
Thanks Jake. In my code below, the file field is received first, then the key field:
```

RequestBody requestFile = RequestBody.create(MediaType.parse("image/*"), file);
RequestBody requestBody = RequestBody.create(MediaType.parse("application/json"), gson.toJson(media.getUploadInfo().getFields()));

Call<AWSS3Asset> s3Call = mAWSS3WebService.upload(
	media.getUploadInfo().getURL(),
        requestBody,
        requestFile
);
```

The interface looks like this:

```
    @Multipart
    @POST
    Call<AWSS3Asset> upload(@Url String url,
                            @Part("data") RequestBody data,
                            @Part("file") RequestBody file);
```

**Comment by JakeWharton** [comment]
I'll write up a test case soon

**Comment by matbos** [comment]
@JakeWharton
I have created a PR(#1949) with tests that ensure `@Part`s are being translated into the `Request` in proper order.

**Comment by jaredsburrows** [comment]
@josephlam1984 @JakeWharton We can close this now that @matbos's PR is in.
