### ISSUE TITLE
Check Success response 

### ISSUE THREAD

**Issue by pranaypatel512** [square/retrofit#1847]
While using Retrofit version  with `compile 'com.squareup.retrofit2:retrofit:2.0.0'` , the success response is checking by **response.isSuccess()**.
 While using Retrofit version with `compile 'com.squareup.retrofit2:retrofit:2.0.2'` , the success response is checking by **response.isSuccessful()**

Why success response is change in both version? Because of this we need to lot of code changes!

**Comment by JakeWharton** [comment]
This is not true. Both 2.0.0 and 2.0.2 use the same `isSuccessful()` method. 2.0.0-beta4 and prior used `isSuccess()`.

**Comment by pranaypatel512** [comment]
Yes, I am using `2.0.0-beta4` . I edited my content.

**Comment by JakeWharton** [comment]
The API was never stable throughout the betas. It was a means to get people
using the library to provide feedback on what to change before 2.0.0 and
this happened to be one of things.
