### ISSUE TITLE
Can Retrofit support httpclient or other client?

### ISSUE THREAD

**Issue by tianzhijiexian** [square/retrofit#1848]
Can I use retrofit without okhttp?

**Comment by JakeWharton** [comment]
Not really, no. You can implement OkHttp's `Call.Factory` which is effectively the client and then adapt OkHttp's `Request`, `Response`, `Headers`, etc. classes to whatever model your client uses.

OkHttp's model classes are our abstraction on an HTTP client while also being an HTTP client itself. If we didn't use its types we would end up just duplicating them all anyway.

**Comment by osamaessa** [comment]
> 
> 
> Not really, no. You can implement OkHttp's `Call.Factory` which is effectively the client and then adapt OkHttp's `Request`, `Response`, `Headers`, etc. classes to whatever model your client uses.
> 
> OkHttp's model classes are our abstraction on an HTTP client while also being an HTTP client itself. If we didn't use its types we would end up just duplicating them all anyway.

How??
