### ISSUE TITLE
How to dyncmiacally change converter parser (json/.xml ) but want to have minimum retrofit instacnes

### ISSUE THREAD

**Issue by IskuhiSargsyan** [square/retrofit#1849]
I need to make http request in different pages of the app,
an the response could json ,xml, customparser
At the begging I created single instacne of Retrofit object  have access from Application, but as I need to use different converters 
I want to know 
`
        Retrofit retrofit = new Retrofit
                .Builder()
                .client(client)
                .baseUrl(RFRemoteApiConnector.BASE)
                .addConverterFactory(SimpleXmlConverterFactory.create())
                .build();`

where to create as I need to have different kind of retrofit instances
is it good to have 3 kind of retrofit instances?

**Comment by swankjesse** [comment]
Please ask usage questions on StackOverflow.
