### ISSUE TITLE
Add suport for signed requests

### ISSUE THREAD

**Issue by Bersh** [square/retrofit#185]
I've recently faced with necessity of sending signed requests (for OAuth). 
I think it would be great if retrifit has support for this, using signpost, or some other library. <br/> What do you think about it?

**Comment by futurely** [comment]
One of the most popular OAuth Java libraries Scribe provides [several signature services](https://github.com/fernandezpablo85/scribe-java/tree/master/src/main/java/org/scribe/services).

**Comment by scinfu** [comment]
@JakeWharton how to use SigningClient?
