### ISSUE TITLE
Dynamic result type with retrofit ?

### ISSUE THREAD

**Issue by mdtuyen** [square/retrofit#1852]
Sorry, I think it is a question but I asked on stackoverflow but don't receivered answer.
I have a server with BASE_URL but with another parameter they return a type
I use:

```
@GET(BASE_URL)
<T>Observable<Response<ArrayList<T>>> getSport(@QueryMap Map<String, String> params);
```

It throw a exception. 
I don't want make many funtion for each param pair, becase I have many param. 
I want to a simply solution for this case. Pls help me.

Thanks,

**Comment by swankjesse** [comment]
This tracker is not for usage questions. You'll need to learn the internals yourself if StackOverflow isn't helping.
