### ISSUE TITLE
Cache Delete .. is this the right way !

### ISSUE THREAD

**Issue by deepakSP** [square/retrofit#1853]
I wanted to delete single cache from cache folder for pull to refresh .

so I ended up with

        OkHttpClient client = new OkHttpClient
                .Builder()
                .cache(cache)
                .addInterceptor(new Interceptor() {
                    @Override
                    public Response intercept(Chain chain) throws IOException {
                   //interceptor for deleting cache

                        Request request = chain.request();
                        if (delete) {
                            String reqUrl = Util.md5Hex(request.url().toString());
                            File cacheFile = new File(cacheDir.getPath(), reqUrl+".0");
                            File cacheFile2 = new File(cacheDir.getPath(), reqUrl+".1");

                            if (cacheFile.exists()){
                                cacheFile.delete();
                                cacheFile2.delete();
                            }
                        }

                        return chain.proceed(request);
                    }
                })
                .addNetworkInterceptor(new Interceptor() {
                    @Override
                    public Response intercept(Chain chain) throws IOException {
                        Request request = chain.request();
                        Response response = chain.proceed(request);
                        response = response.newBuilder()
                                .header("Cache-Control", String.format("public, max-age=%d, only-if-cached, max-stale=%d", 60 * 60 * 24 * 1, 60 * 60 * 24 * 14))
                                .build();

                        return response;
                    }
                })
                .build();

**Comment by JakeWharton** [comment]
No. You can iterate the disk cache using the `Cache.urls()` iterator and then calling `remove()` on the one that matches your URL.

**Comment by kzdeveloper12345** [comment]
Cache.urls() and remove()  how to use it.
