### ISSUE TITLE
Put json array in @Body

### ISSUE THREAD

**Issue by FanSerg2** [square/retrofit#1855]
I want to do like in this image
![image](https://cloud.githubusercontent.com/assets/18485127/16010872/c40ed0a8-318b-11e6-9293-0c37940e6a4b.png)

I have this code:
```
    @POST("/v3/batch/")
    Call<EResponseRefreshEvents> getERefreshEvents(
            @Query("token") String token,
            @Body Task2 batch
            );

```
```
    public class Task2 {
        String batch;

        public Task2(String batch) {
            this.batch = batch;
        }
    }

```
```
        Call<EResponseRefreshEvents> call = restEventbriteClient.getERefreshEvents(
                token,
                new Task2("[{\"method\":\"GET\",\"relative_url\":\"users/me\"}]")
        );
```
When I run it then I get an error :
`java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $`

How can I run request like on the image?

**Comment by JakeWharton** [comment]
This is a problem reading the response, not sending the request. You're expecting a single `EResponseRefreshEvents` object but the response is an array. All you need is to update your response type to match the data being sent by the server.
