### ISSUE TITLE
Fatal Exception: java.lang.AbstractMethodError abstract method "void retrofit.Callback.failure(retrofit.RetrofitError)"

### ISSUE THREAD

**Issue by drozd2000** [square/retrofit#1858]
crash: 	
Fatal Exception: java.lang.AbstractMethodError
abstract method "void retrofit.Callback.failure(retrofit.RetrofitError)"

android.app.Activity.onSaveInstanceState (Activity.java)
android.support.v4.app.FragmentActivity.onSaveInstanceState (FragmentActivity.java:564)
android.support.v7.app.AppCompatActivity.onSaveInstanceState (AppCompatActivity.java:502)
com.example.ui.activity.BaseMyActivity.onSaveInstanceState (BaseMyActivity.java:164)
com.example.ui.activity.MyActivity.onSaveInstanceState (MyActivity.java:894)
android.app.Activity.performSaveInstanceState (Activity.java:1388)
android.app.Instrumentation.callActivityOnSaveInstanceState (Instrumentation.java:1286)
android.app.ActivityThread.callCallActivityOnSaveInstanceState (ActivityThread.java:4643)
android.app.ActivityThread.performStopActivityInner (ActivityThread.java:4010)
android.app.ActivityThread.handleStopActivity (ActivityThread.java:4073)
android.app.ActivityThread.access$1200 (ActivityThread.java:181)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1522)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:145)
android.app.ActivityThread.main (ActivityThread.java:6220)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1399)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1194)

dependencies:
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'com.squareup.okhttp:okhttp:2.5.0'
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.5.0'

sample of method:
@GET(UrlConstants.SOCIALS)
    String[] socials(
            @Header("Authorization") String authHeader
    );
i don't use retrofit.Callback

**Comment by swankjesse** [comment]
This is likely an issue with your build, such as multidex or ProGuard. There's nothing we can do to help you here unfortunately.

**Comment by drozd2000** [comment]
Thanks for the answer.
