### ISSUE TITLE
How to pass static data using post method in my all api

### ISSUE THREAD

**Issue by ShraddhaGadesha** [square/retrofit#1859]
My list of apis are post .
all apis use api_key as a parameter and I have to pass static value in this.
all apis are using post method.
example::http://api.demo.com/getUser
parameters 
api_key="qedfk;dfkl;sdkf;lf",
user_id=1
above api is post .

**Comment by JakeWharton** [comment]
You can use an [OkHttp Interceptor][1] to modify a request in the same way for every endpoint. Retrofit currently does not offer any mechanism for modifying every request that's made.

 [1]: https://github.com/square/okhttp/wiki/Interceptors
