### ISSUE TITLE
GsonConverterFactory can`t convert json string like this --{"data":""}

### ISSUE THREAD

**Issue by supersugar** [square/retrofit#1862]
Hi, i`m a chinese developer ,i hope you can understand me...
This is my code
private static class ResponseInterceptor implements Interceptor {

        @Override
        public Response intercept(Chain chain) throws IOException {
            Request request = chain.request();
            Response response = chain.proceed(request);
            String a = "{\"Mode\":\"Service\",\"Type\":\"App0001\",\"Status\":\"0\",\"Message\":\"\",\"Key\":\"app\",\"Data\":\"\"}";
            String b = "{\"Mode\":\"Service\",\"Type\":\"App0001\",\"Status\":\"0\",\"Message\":\"\",\"Key\":\"app\",\"Data\":{}}";
            response = response.newBuilder()
                    .body(ResponseBody.create(MediaType.parse("UTF-8"), a))
                    .build();
            return response;
        }
    }

String b --> can convert
String a --> can`t convert
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 82 path

**Comment by supersugar** [comment]
But when i use Gson only ,like this 
private void a(){
        String a = "{\"Mode\":\"Service\",\"Type\":\"App0001\",\"Status\":\"0\",\"Message\":\"\",\"Key\":\"app\",\"Data\":\"\"}";
        String b = "{\"Mode\":\"Service\",\"Type\":\"App0001\",\"Status\":\"0\",\"Message\":\"\",\"Key\":\"app\",\"Data\":{}}";
        Gson gson = new Gson();
        BaseModel<BMLogin> login = null;
        login = gson.fromJson(a, BaseModel.class);
        Log.d("xx", login.getType());
        login = gson.fromJson(b, BaseModel.class);
        Log.d("xx", login.getType());
    }
Both of them can convert success

**Comment by supersugar** [comment]
And i get this
Exception thrown on Scheduler.Worker thread. Add `onError` handling

 Network.getUUApi().login(request)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .onErrorResumeNext(Observable.<BaseModel<BMLogin>>empty())
                .flatMap(new Func1<BaseModel<BMLogin>, Observable<BMLogin>>(){
                             @Override
                             public Observable<BMLogin> call(BaseModel<BMLogin> bmLoginBaseModel) {
                                 return Observable.error(new Exception());
                             }
                         }

                )
                .subscribe(new Action1<BMLogin>() {
                    @Override
                    public void call(BMLogin bmLogin) {
                        Log.d("xx", bmLogin.getSSID());
                    }
                },new Action1<Throwable>() {
                    @Override
                    public void call(Throwable throwable) {
                        throwable.printStackTrace();
                        Toast.makeText(MainActivity.this, "请求失败,请稍后重试", Toast.LENGTH_SHORT).show();
                    }
                });
please help me, i want die...pls!!

**Comment by JakeWharton** [comment]
You didn't show your model object `BaseModel` or how Gson is configured so it's not possible to understand what the problem is. That said, this isn't a problem with Retrofit but between your String data and Gson. Retrofit just acts as something which hooks them together.

Please ask your question on StackOverflow (and show your model class and Gson configuration) with the 'gson' tag. Feel free to link it here as well.
