### ISSUE TITLE
Serialize Calls

### ISSUE THREAD

**Issue by fab1an** [square/retrofit#1863]
I would like to be able to serialise and deserialise `Call`s, (without their results).

The reason being is that I have an android-application design where I store calls in progress as part of the state `onPause`. When I restart the app I want start all those calls again. Right now I need an extra class which store the parameters for the API to do that.

**Comment by swankjesse** [comment]
This is difficult to do in general, because a call is not a value. It has an OkHttpClient, which is definitely not serializable. I think that if you want to do this, you’re going to need to write your own code to do it.

**Comment by JakeWharton** [comment]
We do this with wrapper objects that encapsulate the data required for a call but are not themselves `Call`s. Like Jesse said we simply can't serialize a `Call` because it contains the entirety of what's required to execute the request–not just what data was passed.

**Comment by fab1an** [comment]
Okay, thanks for the answers.
