### ISSUE TITLE
Ability to compose RxJavaCallAdapterFactory (in order to observe on Android main thread)

### ISSUE THREAD

**Issue by tsuijten** [square/retrofit#1864]
I'd like to have all `Single`'s returned by the `RxJavaCallAdapterFactory` to have this: `.observeOn(AndroidSchedulers.mainThread())` applied to it

I think it would be nice if we could also pass a scheduler to the `RxJavaCallAdapterFactory` which allows always observing on the Android main thread.

Or even better, the ability to pass a `Transformer` to `RxJavaCallAdapterFactory` (which will use `compose`) so you can transform the Observable before it's returned. Of course when using a `Transformer` you don't want the type of a Observable to be changed...

If you feel this is a good idea I'm happy to help with a PR.

**Comment by JakeWharton** [comment]
Transformer is a good idea.

**Comment by JakeWharton** [comment]
Unfortunately Single and Completeable have different Transformer types so
there is no single way to apply functionality for all three.

As a workaround for now you can write a CallAdapter.Factory which delegates
to the real implementation for creating Observable types and then it would
apply observeOn.

**Comment by tsuijten** [comment]
I created a PR with a custom transformer which transform Observable and Completable separately. #1865

**Comment by JakeWharton** [comment]
I added a sample to show how to use CallAdapter composition to alter the created observables such as adding operators like `observeOn` in https://github.com/square/retrofit/pull/2092
