### ISSUE TITLE
 A request URL needs another request to obtain the results, how to define the @put () inside the URL parameters?

### ISSUE THREAD

**Issue by liulilei** [square/retrofit#1868]
Now I have a problem. I need to define a @put request, but the URL request of the put need me to get the results according to another request, and then in accordance with the results of the return of the URL as URL @put to use.
For example:  
  The result of this request
  @FormUrlEncoded
  @POST(NetApi.UPLOAD_FILE)
  Observable<UploadFileInfo> uploadFile(@FieldMap Map<String, String> map);
 
  @PUT(The result of the request above, return to this URL how to fill in)
   Observable<BaseMode> uploadUrl();

THANKS!

**Comment by JakeWharton** [comment]
Use `@Url String url` on the second endpoint definition. You can also use `HttpUrl` or Android's `Uri` if convenient.

**Comment by liulilei** [comment]
THANKS! GET
