### ISSUE TITLE
Post request not working

### ISSUE THREAD

**Issue by yzbzz** [square/retrofit#1869]
My url like this:
http://xxx.xx/xxx  (not end in /)

This is my RestAPI:
```
public interface RestAPI {
	@FormUrlEncoded
	@POST
	Call<String> someEndpoint(@FieldMap Map<String,String> params);
}
```
throw java.lang.IllegalArgumentException: baseUrl must end in /
How can i definition this post request, if not add / end in url?

**Comment by pasali** [comment]
actually your base url : http://xxx.xx/ and you rest api should be like this:

public interface RestAPI {
@FormUrlEncoded
@POST("xxx")
Call someEndpoint(@FieldMap Map params);
}

**Comment by JakeWharton** [comment]
What he said
