### ISSUE TITLE
Gets a HTTP 301 Moved Permanently error

### ISSUE THREAD

**Issue by jaimeat1** [square/retrofit#1870]
Hi,

Thanks in advance for your library, it's my first time with Retrofit and I'm enjoying it.

However, now I'm trying to do a POST request, but it sends the request always as a GET method, as I can see in Android Studio logs and Wireshark traces. The web service is currently working in my iOS app.

```
// My API definition, with base URL http://xxxx.xx/
@FormUrlEncoded
@POST("users")
Call<String> setUser(@FieldMap HashMap<String, String> map);

// The Retrofit call
HashMap<String, String> map = new HashMap<>();
map.put("username", username);
map.put("email", email);
Call<String> call = getRetrofitEndpoints().setUser(map);
call.enqueue(...)

// RetrofitEndpoints is the class where API is defined
private RetrofitEndpoints getRetrofitEndpoints() {
	if (mRetrofitEndpoints == null) {
		Retrofit retrofit = new Retrofit.Builder()
                    .baseUrl(mBaseUrl)
                    .addConverterFactory(GsonConverterFactory.create())
                    .build();
        mRetrofitEndpoints = retrofit.create(RetrofitEndpoints.class);
	}
	return mRetrofitEndpoints;
}
```

This results always as a GET request, with a 405 Error response. 
Is there anything wrong in this code?

Thank you,

**Comment by jaimeat1** [comment]
Diving in the Wireshark traces, I can see that a POST request is made, then the server returns a 301 Moved Permanently HTTP error, and instantly tries again with a GET request. Callback is called only once.

This POST web service is working with the iOS app and emulator. I have tried with Genymotion and Android Studio emulators, both with the same error.

Do you have any clue of what can be misconfigured in my Retrofit request?

**Comment by JakeWharton** [comment]
OkHttp is turning the POST into a GET per the HTTP spec for 301 (and 302). You either need to connect directly to the redirect URL or have the server return a 308.

Here's what [Wikipedia says about 308][1]:

> The request and all future requests should be repeated using another URI. 307 and 308 parallel the behaviours of 302 and 301, but _do not allow the HTTP method to change_. So, for example, submitting a form to a permanently redirected resource may continue smoothly.

You can use an [OkHttp network interceptor][2] to change 301 responses into 308 if you can't update the server.

[1]: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#3xx_Redirection
[2]: https://github.com/square/okhttp/wiki/Interceptors

**Comment by jaimeat1** [comment]
Thanks @JakeWharton, I will take a look.

But, do you have any clue why the server returns 301 for Android but works for the iOS app? the base URL, service name, HTTP method and params are the same.

**Comment by swankjesse** [comment]
iOS isn’t following redirects. Disable this in your OkHttpClient like so:
https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.Builder.html#followRedirects-boolean-

**Comment by bigggge** [comment]
@JakeWharton How to create an OkHttp network interceptor to change 301 responses into 308? Thanks!

**Comment by li2** [comment]
Hi @swankjesse  I added this line in OKHTTP builder, then the HTTP call changed from 405 GET (incorrect) to 200 POST (correct) , any idea why this gonna happen? thanks

    clientBuilder.followRedirects(false)

**Comment by swankjesse** [comment]
@li2 please try StackOverflow.
