### ISSUE TITLE
Append text to the end of end point after queries inserted

### ISSUE THREAD

**Issue by meNESS** [square/retrofit#1873]
I want to produce the end point like `/api/method?page=1.json` but the problem is queries will be inserted at the end just like `/api/method.json?page=1`.
```java
// from my service
@GET("method.json")
Call<Void> method(@Query("page") int page);

// building retrofit
new Retrofit.Builder()
                .baseUrl(URL)
                .client(httpClient)
                .addConverterFactory(GsonConverterFactory.create())
                .build();
```

Why I'm doing this is because of CakePHP which returns result as a JSON. Is there another solution? Is it possible to change URL before using inside of a callback?

**Comment by JakeWharton** [comment]
The only way to do this currently is with an OkHttp interceptor that
appends the value. A Retrofit-level interceptor (when we add such a
feature) will also be able to do this.

**Comment by meNESS** [comment]
Thanks. I already done that.
