### ISSUE TITLE
retrofit2.BuildInConverters$StringConverter let me confused

### ISSUE THREAD

**Issue by iacky** [square/retrofit#1876]
I am so confused,when send request like this

 public interface API {
       @FormUrlEncoded
       @POST("login.do?os=" + ConstantValue.OS + "&version=" + ConstantValue.VERSION)
       Observable<LoginInfo> login(@Field("cmd") String params);
  } 
the method of my custom Converter stringConverter method do not work.. (to encrypt request)
retrofit2.BuildInConvert$StringConverter is first before mine execute.. help~please~
retrofit version 2.1.0 @

**Comment by iacky** [comment]
i found the default BuildInConverters,its stringConverter will intercept the request which type is String.

    @Override public Converter<?, String> stringConverter(Type type, Annotation[] annotations,Retrofit retrofit) {
        if (type == String.class) {
            return StringConverter.INSTANCE;
        }
        return null;
    }
so i change the type of the parameter,like this

public interface API {
   @FormUrlEncoded
   @POST("login.do?os=" + ConstantValue.OS + "&version=" + ConstantValue.VERSION)
   Observable<LoginInfo> login(@Field("cmd") JsonObject params);
}

then my custom Converter work.

note:
i do not know weather the way I encrypt the request  is ok..   
can I change the default Converter ,not change my type to let it can use my custom converter .

**Comment by JakeWharton** [comment]
The built-in converter is added last so any user-supplied converters should always take precedence.

**Comment by JakeWharton** [comment]
Looks like we don't call the string converter when the type is already string. This is potentially problematic if you have annotations on the parameter with which you want to modify the value. Let me look at relaxing this restriction.

**Comment by iacky** [comment]
thank you very much @JakeWharton @swankjesse

**Comment by JakeWoki** [comment]
@iacky 后来你是怎么处理的呢？求解
