### ISSUE TITLE
Not able to use alternate with @SerializedName when using 'converter-gson:2.0.0-beta2'

### ISSUE THREAD

**Issue by harshitaahuja** [square/retrofit#1878]
When using converter-gson:2.0.0-beta2 with retrofit instead of 'com.google.code.gson:gson:2.7' i am not able to write alternate with @SerializedName. (eg : @SerializedName(value = "Id", alternate={"id"})

**Comment by JakeWharton** [comment]
I doubt the version of Gson which that old version of `converter-gson` depends on contains the alternate name support. If you update to the latest (2.1.0) it depends on Gson 2.7.
