### ISSUE TITLE
Android 4.4.2, API 19

### ISSUE THREAD

**Issue by liujunhongz** [square/retrofit#1880]
- [ Code ]:  OkHttpClient.Builder builder = new OkHttpClient.Builder();

 - [ Exception ]:  Could not find class 'okhttp3.Dispatcher', referenced from method okhttp3.OkHttpClient$Builder.<init>

**Comment by JakeWharton** [comment]
This is not a problem with Retrofit, but likely a misconfiguration with your build system or maybe multidex if you're using it. I would suggest posting to StackOverflow with more information about your build setup and any information on multidex.

**Comment by liujunhongz** [comment]
thk u.
