### ISSUE TITLE
[Feature Request] how to know which url gson convert fail using rxjava + retrofit 

### ISSUE THREAD

**Issue by nightbear1009** [square/retrofit#1894]
What kind of issue is this?
- [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
     already exists! Don’t send pull requests to implement new features without first getting our
     support. Sometimes we leave features out on purpose to keep the project small.

i am using rxjava + retrofit, I want to know which api request failed while parsing gson to class.

After tracing code i find out as below  

ExceptionCatchingRequestBody catchingBody = new ExceptionCatchingRequestBody(rawBody);
    try {
      T body = responseConverter.convert(catchingBody);
      return Response.success(body, rawResponse);
    } catch (RuntimeException e) {
      // If the underlying source threw an exception, propagate that rather than indicating it was
      // a runtime exception.
      catchingBody.throwIfCaught();
      throw e;
    }

the problem is "throw e"
If I can custom my exception, I can throw url with exception 
or If abstract class ResponseBody has one more method 
public abstract class ResponseBody{
 String get Url ...
}

or is there another way to fit my problem?

**Comment by kenyee** [comment]
I'd agree w/ this...the converters should, at the least, dump the body it was trying to parse.  Crashlytics errors don't give you much of a clue as to what caused it unless you log every API call which would be too much data.  Right now, you get stacks like this if the server happens to give you JSON you don't expect.  It looks like the code above is trying to do that w/ the ExceptionCatchingExceptionBody, but instead, you get stack traces like this:

> java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
>        at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350)
>        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80)
>        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
>        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:37)
>        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:25)
>        at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:117)
>        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:211)
>        at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
>        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171)
>        at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)

**Comment by JakeWharton** [comment]
@kenyee that requires buffering the entire body for every response which is something we will never do.

**Comment by kenyee** [comment]
Ugh..forgot that it's streaming.  In that case, printing the URL would be helpful.  It's too bad GSON can't dump the segment of JSON it was trying to parse...

**Comment by sddamico** [comment]
You can use an interceptor to add more metadata to the exception trace, I've found this to be useful.

```
public class IOExceptionDecorator implements Interceptor {

    @Override
    public Response intercept(final Chain chain) throws IOException {
        final Response response;

        try {
            response = chain.proceed(chain.request());
        } catch (IOException e) {
            throw new HttpIOException(chain.request(), e);
        }

        return response;
    }

    private static class HttpIOException extends IOException {

        HttpIOException(final Request request, final IOException e) {
            super(String.format(Locale.US, "IOException during http request. Request= %s", request), e);
        }
    }
}
```

You can then add this to your OkHttpClient:

`new OkHttpClient.Builder().addInterceptor(new IOExceptionDecorator()).build()`

**Comment by kenyee** [comment]
@sddamico : you rock! :-)
Probably deserves putting on the okhttp wiki.

**Comment by swankjesse** [comment]
No action to take on this.
