### ISSUE TITLE
Use @Body and  @Multipart in single call

### ISSUE THREAD

**Issue by kvanadev1gmail** [square/retrofit#1895]
Hi Please help me out..
Ry Req:
**@Multipart**
@POST("/api/v5/msg")
Call<String> createMessage(@Body MessageInput humOsMessage, @PartMap Map<String, RequestBody> requestBodyMap);

**Error:**
java.lang.IllegalArgumentException: @Body parameters cannot be used with form or multi-part encoding. (parameter #1)

**Comment by JakeWharton** [comment]
The multipart data _is_ the body so you cannot specify both. All data in a multipart request must be specified using `@Part` or `@PartMap`.

**Comment by TwinsOd** [comment]
How to send a difficult object, like { name: Dony, cars: {bmw: firstName, tesla: secondName}} ?
