### ISSUE TITLE
Unsafe implementation of X509TrustManager

### ISSUE THREAD

**Issue by Tedix** [square/retrofit#1899]
After publication our application which is using Retrofit (thank you for that) I get email from Google Play Support team about rejected application. In the email wash mentioned that our application is using unsaved implementation of the interface X509TrustManager (email is in the end of this message). This is not in our source code and probably problem could be Retrofit.
https://support.google.com/faqs/answer/6346016

I did some research and found dependency on com.squareup.okhttp3. In the source code there is used **X509TrustManager** and probably that is why application was rejected.

Could you please check it and let me know if it could be a problem.

**Thank you,
Miroslav Novosvetsky**

**Message from Google Play Support team:**

Hello Google Play Developer,

We rejected Breweries (CZ/SK), with package name cz.novosvetsky.pivovary, for violating our Malicious Behavior policy. If you submitted an update, the previous version of your app is still available on Google Play.

This app uses software that contains security vulnerabilities for users.

Below is the list of vulnerabilities and the corresponding APK versions that were detected in your recent submission. Please upgrade your app(s) as soon as possible and increment the version number of the upgraded APK.

Vulnerability - TrustManager
You can find more information about TrustManager in this Google Help Center article.
https://support.google.com/faqs/answer/6346016

To confirm you’ve upgraded correctly, submit the updated version of your app to the Developer Console and check back after five hours to make sure the warning is gone.

While these vulnerabilities may not affect every app that uses this software, it’s best to stay up to date on all security patches. Make sure to update any libraries in your app that have known security issues, even if you're not sure the issues are relevant to your app.

Apps must also comply with the Developer Distribution Agreement and Developer Program Policies.

If you feel we have made this determination in error, please reach out to our policy support team.

Best,

The Google Play Team

**Comment by JakeWharton** [comment]
> This is not in our source code and probably problem could be Retrofit.

Neither Retrofit nor its dependencies OkHttp or Okio contain an implementation of X509TrustManager. You can use a tool like [ClassyShark](https://github.com/google/android-classyshark) to poke around inside your APK to try and find the implementation.
