### ISSUE TITLE
SDK 24 Incompatibility

### ISSUE THREAD

**Issue by arammkhitaryan** [square/retrofit#1900]
This seem to be a bug.

So basically here is what happens. I have a project with retrofit2 that works fine with build tools 23, java 7 and this configuration works just fine.
But I had to upgrade to **build tools 24, jack compiler enabled, java 8**.

At this point nothing seem to work.

**Problem 1**
The standard message is saying:

java.lang.IllegalArgumentException: Unable to create call adapter for interface retrofit2.Call
                                                   for method ......
                                                   at retrofit2.ServiceMethod$Builder.methodError(Unknown)
                                                   at retrofit2.ServiceMethod$Builder.createCallAdapter(Unknown)
                                                   at retrofit2.ServiceMethod$Builder.build(Unknown)
                                                   at retrofit2.Retrofit.loadServiceMethod(Unknown)
                                                   at retrofit2.Retrofit$1.invoke(Unknown)
                                                   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
                                                   ...
                                                Caused by: java.lang.IllegalArgumentException: Call return type must be parameterized as Call<Foo> or Call<? extends Foo>
                                                   at retrofit2.Utils.getCallResponseType(Unknown)
                                                   at retrofit2.ExecutorCallAdapterFactory.get(Unknown)
                                                   at retrofit2.Retrofit.nextCallAdapter(Unknown)
                                                   at retrofit2.Retrofit.callAdapter(Unknown)
                                                   at retrofit2.ServiceMethod$Builder.createCallAdapter(Unknown) 
                                                   at retrofit2.ServiceMethod$Builder.build(Unknown) 

This seems to be because with jack/java 8 the generic type is missed, or something like that.
None of the proguard options helped. All keepattributes: signature, annotation, and many others have no effect. I keep getting the same error.

This is the cleanest version of proguard rules (I had many others also with -keepnames or -keepmembernames, etc). All versions to keep enums, support serializables, etc are also checked.

-keep class retrofit2.** { *; }
-keepattributes Signature
-keepattributes Exceptions

-keepclasseswithmembers class * {
    @retrofit2.http.* <methods>;
}

-keepattributes Signature
-keepattributes *Annotation*
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }

-keepattributes Signature
-keepattributes *Annotation*
-keep class com.squareup.okhttp.** { *; }
-keep interface com.squareup.okhttp.** { *; }

-keepattributes Signature

-keepattributes *Annotation*

-keepattributes EnclosingMethod

-keep class sun.misc.Unsafe { *; }
-keep class com.google.gson.** { *; }

**Problem 2**
There seem to be a versioning and compatibility issue with converter/gson version.
For example, I use retrofit2:2.1.0, but gson convertor 2.1.0 and gson:2.5 cause another error.

At GsonConverterFactory.create() I get an error with "type parameter or something".
As soon as I put gson version 2.0.0-beta3 to work with retrofit2:2.1.0 ... the error goes away.

It seems there is a reflection code that points to retrofit2.GsonConverterFactory, but in the new version the class is moved to retrofit2.converter.gson.GsonConverterFactory.

**Comment by JakeWharton** [comment]
Does it work with ProGuard disabled?

**Comment by arammkhitaryan** [comment]
it works even with proguard enabled but with -dontobfuscate

**Comment by arammkhitaryan** [comment]
as soon as obfuscation gets in, it fails ...

also tried with -keepnames class * { *; } but get same error

so there seem to be something more in obfuscation except for mixing names (as keepnames doesn't help) or maybe there is another issue with java 8 and/or jack?

here is another issue I filed for jack: https://code.google.com/p/android/issues/detail?id=215350

**Comment by JakeWharton** [comment]
Sounds like this is pretty clearly a bug in Jack. I can attest to Retrofit
working fine with SDK 24 without Jack both with and without ProGuard
(including the signature keeping). I'm don't think there's any action to
take on our part here. I'll star the bug and follow along.

**Comment by arammkhitaryan** [comment]
can you please provide the proguard rules and dependencies that work for you?

**Comment by arammkhitaryan** [comment]
If it works for you then it should work for my case too. And there should be nor problem with Jack.

Any example/best practice would be helpful as there is no such resource for android/gradle/proguard/jack case in retrofit examples.

**Comment by koa73** [comment]
I have the same problem as yours
In my case the problem with options of proguard
I just added some recommended options by gson

https://github.com/google/gson/blob/master/examples/android-proguard-example/proguard.cfg

**Comment by graphee-gabriel** [comment]
Hello, I have the same crash than @arammkhitaryan using Retrofit 2 and Moshi as the JSON converter. 
I tried putting the -keepattributes on the single line as suggested here: https://code.google.com/p/android/issues/detail?id=215350
But without any success...

Anything new? Did you manage to fix it on your end @arammkhitaryan ?

**Comment by jemshit** [comment]
Added these 2 lines for Retrofit 2.1.0 on top of @koa73 's link:
```
-dontwarn retrofit2.adapter.rxjava.CompletableHelper$** # https://github.com/square/retrofit/issues/2034
-dontwarn okio.**
```
