### ISSUE TITLE
when use OkHttpClient.Builder.addInterceptor to addheader it isn't effective

### ISSUE THREAD

**Issue by Zzz468005600** [square/retrofit#1901]
- [ ] Question
here is my code:
`OkHttpClient.Builder builder = new OkHttpClient.Builder();
        builder.addInterceptor(logging);
        builder.addInterceptor(new Interceptor() {
            @Override
            public okhttp3.Response intercept(Chain chain) throws IOException {
                Request request = chain.request()
                        .newBuilder()
                        .addHeader("Content-Type", "application/x-www-form-urlencoded; charset=UTF-8")
                        .addHeader("Accept-Encoding", "gzip, deflate")
                        .addHeader("Connection", "keep-alive")
                        .addHeader("Accept", "*/*")
                        .addHeader("Cookie", "add cookies here")
                        .build();
                return chain.proceed(request);
            }
        });
        mHttpClient = builder.build();
        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl("https://api.fadaojia.co/")
                .client(mHttpClient)
                .addConverterFactory(GsonConverterFactory.create())
                .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                .build();
        ILogin login = retrofit.create(ILogin.class);
        Observable<Map> observable = login.login(body, getHeaders(makeSignature_v3(path, query)));
        CompositeSubscription mCompositeSubscription = new CompositeSubscription();
        mCompositeSubscription.add(observable.subscribeOn(Schedulers.newThread())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Subscriber<Map>() {
                    @Override
                    public void onCompleted() {
                       
                    }
                    @Override
                    public void onError(Throwable e) {
                       
                    }
                    @Override
                    public void onNext(Map map) {
                        
                    }
                }));`
but from the logging i can't get my header, and my server also can't get my header.

**Comment by swankjesse** [comment]
Reorder your interceptor and the logging interceptor? Your headers aren't added yet when the logger logs.

No other action to take here.
