### ISSUE TITLE
When I use the post request method, and the parameter is null, it will "OnError: cannot be cast to okhttp3.FormBody okhttp3.RequestBody$2"

### ISSUE THREAD

**Issue by xueyaolive** [square/retrofit#1902]
What kind of issue is this?

 - [x] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by xueyaolive** [comment]
help me!

**Comment by JakeWharton** [comment]
If you think this is a bug please post a failing test case. Otherwise this sounds like a usage problem and StackOverflow is the right place to ask questions. This issue tracker is for bugs and feature requests only.
