### ISSUE TITLE
GIT With body

### ISSUE THREAD

**Issue by mmcminn** [square/retrofit#1907]
So this is related to the DELETE with body issue. I am not sure why every API developer for android assumes GIT can't have a body. As far as I know the RFC allows ALL verbs to have a body during the request. Only the HEAD response explicitly does not have a body.

What will it take to remove this restriction because I'd really rather not fork.

Within ServiceMethod.java
all calls to parseHttpMethodAndPath should be true for hasBody.

In fact the whole hasBody thing should just be removed. There is absolutely no need for it.

**Comment by JakeWharton** [comment]
99.9% of the time a GET with a body is a programmer error, not desired intent, so for that reason we optimize for that case. You can use `@HttpMethod(value = "GET", hasBody = true)` instead, although I wouldn't be surprised if OkHttp ends up throwing an exception in this case as well.
