### ISSUE TITLE
leaked with rxjava

### ISSUE THREAD

**Issue by hcadoid** [square/retrofit#1910]
com.zjcs.student.activity.SplashActivity has leaked:
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: * GC ROOT thread java.lang.Thread.<Java Local> (named 'RxIoScheduler-2')
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: * references rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.child
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: * references rx.internal.operators.OperatorMap$MapSubscriber.actual
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: * references rx.internal.operators.OperatorMerge$MergeSubscriber.child
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: * references rx.observers.SafeSubscriber.actual
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: * references rx.internal.util.ActionSubscriber.onError
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: * references com.zjcs.student.activity.SplashActivity$4.this$0 (anonymous implementation of rx.functions.Action1)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: * leaks com.zjcs.student.activity.SplashActivity instance
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: * Retaining: 7.9MB.
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: * Reference Key: 9fc5b89a-1933-4981-9da3-d271772099f7
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: * Device: HUAWEI Huawei H60-L02 H60-L02
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: * Android Version: 4.4.2 API: 19 LeakCanary: 1.4-beta2 3799172
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: * Durations: watch=5082ms, gc=157ms, heap dump=1440ms, analysis=18611ms
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: * Details:
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: * Instance of java.lang.Thread
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   static $staticOverhead = byte[144]@1096667961 (0x415dd339)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   static NORM_PRIORITY = 5
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   static defaultUncaughtHandler = com.tendcloud.tenddata.cd$a@1126581648 (0x43264590)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   static count = 455
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   static MIN_PRIORITY = 1
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   static NANOS_PER_MILLI = 1000000
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   static MAX_PRIORITY = 10
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   contextClassLoader = dalvik.system.PathClassLoader@1126456928 (0x43245e60)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   vmThread = java.lang.VMThread@1128543392 (0x434434a0)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   group = java.lang.ThreadGroup@1096727632 (0x415ebc50)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   uncaughtHandler = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   target = java.util.concurrent.ThreadPoolExecutor$Worker@1127470840 (0x4333d6f8)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   inheritableValues = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   interruptActions = java.util.ArrayList@1128543304 (0x43443448)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   localValues = java.lang.ThreadLocal$Values@1126641384 (0x43272ee8)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   name = java.lang.String@1128543272 (0x43443428)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   parkBlocker = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   id = 449
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   stackSize = 0
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   priority = 5
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   parkState = 1
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   hasBeenStarted = true
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   daemon = true
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: * Instance of rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   child = rx.internal.operators.OperatorMap$MapSubscriber@1128694536 (0x43468308)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   counter = java.util.concurrent.atomic.AtomicLong@1127546952 (0x43350048)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   requested = java.util.concurrent.atomic.AtomicLong@1127546928 (0x43350030)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   recursiveScheduler = rx.android.schedulers.LooperScheduler$HandlerWorker@1127676240 (0x4336f950)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   error = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   queue = rx.internal.util.unsafe.SpscArrayQueue@1127962152 (0x433b5628)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   on = rx.internal.operators.NotificationLite@1127016432 (0x432ce7f0)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   limit = 12
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   emitted = 0
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   finished = false
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   delayError = false
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   producer = rx.internal.operators.OperatorSubscribeOn$1$1$1@1127518728 (0x43349208)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   subscriptions = rx.internal.util.SubscriptionList@1127546904 (0x43350018)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   subscriber = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   requested = 16
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: * Instance of rx.internal.operators.OperatorMap$MapSubscriber
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   actual = rx.internal.operators.OperatorMerge$MergeSubscriber@1126862336 (0x432a8e00)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mapper = com.zjcs.student.http.RxResultHelper$1$1@1127555392 (0x43352140)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   done = false
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   producer = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   subscriptions = rx.internal.util.SubscriptionList@1128694584 (0x43468338)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   subscriber = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   requested = -9223372036854775808
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: * Instance of rx.internal.operators.OperatorMerge$MergeSubscriber
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   static $staticOverhead = byte[24]@1126897441 (0x432b1721)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   static EMPTY = rx.internal.operators.OperatorMerge$InnerSubscriber[0]@1126862312 (0x432a8de8)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   child = rx.observers.SafeSubscriber@1127051440 (0x432d70b0)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   subscriptions = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   queue = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   producer = rx.internal.operators.OperatorMerge$MergeProducer@1127674488 (0x4336f278)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   errors = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   innerGuard = java.lang.Object@1127196296 (0x432fa688)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   innerSubscribers = rx.internal.operators.OperatorMerge$InnerSubscriber[0]@1126862312 (0x432a8de8)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   nl = rx.internal.operators.NotificationLite@1127016432 (0x432ce7f0)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   uniqueId = 0
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   lastId = 0
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   missed = false
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   maxConcurrent = 2147483647
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   emitting = false
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   done = false
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   scalarEmissionCount = 0
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   scalarEmissionLimit = 2147483647
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   delayErrors = false
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   lastIndex = 0
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   producer = rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$1@1127524504 (0x4334a898)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   subscriptions = rx.internal.util.SubscriptionList@1126862456 (0x432a8e78)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   subscriber = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   requested = 9223372036854775807
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: * Instance of rx.observers.SafeSubscriber
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   actual = rx.internal.util.ActionSubscriber@1127476560 (0x4333ed50)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   done = false
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   producer = rx.internal.operators.OperatorMerge$MergeProducer@1127674488 (0x4336f278)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   subscriptions = rx.internal.util.SubscriptionList@1127402568 (0x4332cc48)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   subscriber = rx.internal.util.ActionSubscriber@1127476560 (0x4333ed50)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   requested = -9223372036854775808
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: * Instance of rx.internal.util.ActionSubscriber
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   onCompleted = rx.functions.Actions$EmptyAction@1126392456 (0x43236288)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   onError = com.zjcs.student.activity.SplashActivity$4@1127310296 (0x433163d8)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   onNext = com.zjcs.student.activity.SplashActivity$3@1126799160 (0x43299738)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   producer = rx.internal.operators.OperatorMerge$MergeProducer@1127674488 (0x4336f278)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   subscriptions = rx.internal.util.SubscriptionList@1127402568 (0x4332cc48)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   subscriber = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   requested = -9223372036854775808
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: * Instance of com.zjcs.student.activity.SplashActivity$4
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   this$0 = com.zjcs.student.activity.SplashActivity@1128698800 (0x434693b0)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: * Instance of com.zjcs.student.activity.SplashActivity
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   static EXTRA_FIRST_START = java.lang.String@1128698720 (0x43469360)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   static $staticOverhead = byte[72]@1128692057 (0x43467959)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   static SUCCESS_WHAT = 2
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   static GO_WHAT = 1
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   runnable = com.zjcs.student.activity.SplashActivity$5@1128709672 (0x4346be28)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   handler = com.zjcs.student.activity.SplashActivity$MyHandler@1128708904 (0x4346bb28)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   id = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   imageUrl = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   imageView = com.facebook.drawee.view.SimpleDraweeView@1128763320 (0x43478fb8)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mode = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   jumpOverTv = android.widget.TextView@1126872176 (0x432ab470)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   isSuccessGetData = false
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   isHasImage = false
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   isAlready = true
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   delay = 4
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   dialog = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   exitre = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mCompositeSubscription = rx.subscriptions.CompositeSubscription@1126562064 (0x4325f910)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   subscription = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mPendingFragmentActivityResults = android.support.v4.util.SparseArrayCompat@1128726640 (0x43470070)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mFragments = android.support.v4.app.FragmentController@1128708160 (0x4346b840)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mHandler = android.support.v4.app.FragmentActivity$1@1128700200 (0x43469928)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mMediaController = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mNextCandidateRequestIndex = 0
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mOptionsMenuInvalidated = false
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mCreated = true
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mReallyStopped = true
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mRequestedPermissionsFromFragment = false
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mResumed = false
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mRetaining = false
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mStartedActivityFromFragment = false
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mStopped = true
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mActionBar = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mActivityInfo = android.content.pm.ActivityInfo@1126444000 (0x43242be0)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mAllLoaderManagers = android.util.ArrayMap@1126562448 (0x4325fa90)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mApplication = com.zjcs.student.MyApp@1126464000 (0x43247a00)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mWindowManager = android.view.WindowManagerImpl@1128716208 (0x4346d7b0)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mWindow = huawei.com.android.internal.policy.impl.HwPhoneWindow@1128713592 (0x4346cd78)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mUiThread = java.lang.Thread@1096731984 (0x415ecd50)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mTranslucentCallback = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mComponent = android.content.ComponentName@1126443440 (0x432429b0)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mToken = android.os.BinderProxy@1126443904 (0x43242b80)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mContainer = android.app.Activity$1@1128699288 (0x43469598)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mCurrentConfig = android.content.res.Configuration@1128710328 (0x4346c0b8)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mDecor = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mTitle = java.lang.String@1127868112 (0x4339e6d0)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mDefaultKeySsb = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mSearchManager = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mResultData = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mEmbeddedID = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mParent = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mMenuInflater = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mFragments = android.app.FragmentManagerImpl@1128699168 (0x43469520)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mHandler = android.os.Handler@1128699456 (0x43469640)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mManagedDialogs = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mInstanceTracker = android.os.StrictMode$InstanceTracker@1128699328 (0x434695c0)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mInstrumentation = android.app.Instrumentation@1126456736 (0x43245da0)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mIntent = android.content.Intent@1126443192 (0x432428b8)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mManagedCursors = java.util.ArrayList@1128699304 (0x434695a8)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mLastNonConfigurationInstances = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mLoaderManager = null
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mMainThread = android.app.ActivityThread@1126437784 (0x43241398)
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mLoadersStarted = false
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mIsFullFlag = false
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mIdent = 1142233280
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mFinished = true
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mEnableDefaultActionBarUp = false
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mResultCode = 0
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mDoReportFullyDrawn = false
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mResumed = false
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mDestroyed = true
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mStartedActivity = false
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mStopped = true
07-12 09:40:41.120 11366-12793/com.zjcs.student D/LeakCanary: |   mTemporaryPause = false
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: |   mDefaultKeyMode = 0
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: |   mTitleColor = 0
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: |   mTitleReady = true
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: |   mConfigChangeFlags = 0
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: |   mCheckedForLoaderManager = true
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: |   mChangingConfigurations = false
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: |   mVisibleFromClient = true
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: |   mVisibleFromServer = true
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: |   mChangeCanvasToTranslucent = false
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: |   mWindowAdded = true
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: |   mCalled = true
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: |   mBase = android.app.ContextImpl@1128709688 (0x4346be38)
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: |   mInflater = com.android.internal.policy.impl.PhoneLayoutInflater@1128715024 (0x4346d310)
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: |   mOverrideConfiguration = null
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: |   mResources = com.huawei.android.content.res.ResourcesEx@1126452320 (0x43244c60)
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: |   mTheme = android.content.res.Resources$Theme@1128716232 (0x4346d7c8)
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: |   mThemeResource = 2131296517
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: |   mBase = android.app.ContextImpl@1128709688 (0x4346be38)
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: * Excluded Refs:
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Field: android.app.ActivityThread$ActivityClientRecord.nextIdle
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Field: android.widget.Editor$EasyEditSpanController.this$0
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Field: android.widget.Editor$SpanController.this$0
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Field: android.os.Message.obj
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Field: android.os.Message.next
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Field: android.os.Message.target
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Field: android.view.inputmethod.InputMethodManager.mNextServedView
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Field: android.view.inputmethod.InputMethodManager.mServedView
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Field: android.view.inputmethod.InputMethodManager.mServedInputConnection
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Field: android.view.inputmethod.InputMethodManager.mCurRootView
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Field: android.animation.LayoutTransition$1.val$parent
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Field: android.view.textservice.SpellCheckerSession$1.this$0
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Field: android.support.v7.internal.widget.ActivityChooserModel.mActivityChoserModelPolicy
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Field: android.widget.ActivityChooserModel.mActivityChoserModelPolicy
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Field: android.speech.SpeechRecognizer$InternalListener.this$0
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Field: android.accounts.AccountManager$AmsTask$Response.this$1
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Field: android.media.MediaScannerConnection.mContext
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Field: android.os.UserManager.mContext
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Field: android.appwidget.AppWidgetHost$Callbacks.this$0
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Field: android.media.AudioManager$1.this$0
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Field: android.widget.Editor$Blink.this$0
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Field: android.view.Choreographer$FrameDisplayEventReceiver.mMessageQueue (always)
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Static field: android.text.TextLine.sCached
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Thread:FinalizerWatchdogDaemon (always)
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Thread:main (always)
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Thread:LeakCanary-Heap-Dump (always)
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Class:java.lang.ref.WeakReference (always)
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Class:java.lang.ref.SoftReference (always)
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Class:java.lang.ref.PhantomReference (always)
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Class:java.lang.ref.Finalizer (always)
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Class:java.lang.ref.FinalizerReference (always)
07-12 09:40:41.125 11366-12793/com.zjcs.student D/LeakCanary: | Root Class:android.os.Binder (always)

**Comment by hcadoid** [comment]
compile 'com.squareup.retrofit2:retrofit:2.0.2'
    compile 'com.squareup.retrofit2:adapter-rxjava:2.0.2'
    compile 'com.squareup.retrofit2:converter-gson:2.0.2'
    compile 'com.squareup.okhttp3:okhttp:3.2.0'
    compile 'com.squareup.okhttp3:logging-interceptor:3.2.0'
    compile 'io.reactivex:rxandroid:1.2.0'
    compile 'io.reactivex:rxjava:1.1.5'


subscription=RetrofitManager.getApiService().splash(1)
					.subscribeOn(Schedulers.io())
					.observeOn(AndroidSchedulers.mainThread())
					.compose(RxResultHelper.<SplashInfo>handleResult())
					.subscribe(new Action1<SplashInfo>() {
						@Override
						public void call(SplashInfo splashInfo) {
							isSuccessGetData=true;
							SharePreferenceUtil.setValue(SplashActivity.this, Constant.SPLASH_DATA, new Gson().toJson(splashInfo));
							if(splashInfo.getImgUrl()!=null){
								advertisingSuccess(splashInfo.getImgUrl());
							}
						}
					}, new Action1<Throwable>() {
						@Override
						public void call(Throwable throwable) {
							isSuccessGetData=false;
						}
					});

@Override
	protected void onDestroy() {
		super.onDestroy();
		unregisterListener();
		dismissProgress();
		if(subscription!=null){
			subscription.unsubscribe();
		}
	}


   public static ApiService getApiService() {
        if(apiService==null){
            new RetrofitManager();
        }
        return apiService;
    }

    private RetrofitManager() {
        initOkHttpClient();

        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(BASE_URL)
                .client(mOkHttpClient)
                .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                .addConverterFactory(GsonConverterFactory.create())
                .build();
        apiService=retrofit.create(ApiService.class);
    }

    private static void initOkHttpClient() {
        HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
        interceptor.setLevel(HttpLoggingInterceptor.Level.BODY);
        if (mOkHttpClient == null) {
            synchronized (RetrofitManager.class) {
                if (mOkHttpClient == null) {
                    Cache cache = new Cache(new File(Environment.getExternalStorageDirectory().getAbsoluteFile(), Constant.NET_PATH),
                            1024 * 1024 * 10);
                    mOkHttpClient = new OkHttpClient.Builder()
                            .cache(cache)
//                            .sslSocketFactory(createSSLSocketFactory())
//                            .hostnameVerifier(new TrustAllHostnameVerifier())
                            .addInterceptor(mRewriteCacheControlInterceptor)
                            .addNetworkInterceptor(mRewriteCacheControlInterceptor)
                            .addInterceptor(interceptor)
                            .retryOnConnectionFailure(true)
                            .connectTimeout(12, TimeUnit.SECONDS)
                            .build();
                }
            }
        }
    }

The above is my code。

**Comment by JakeWharton** [comment]
What makes you think this is Retrofit's fault?

**Comment by JakeWharton** [comment]
This GC path indicates that this is the background thread (IO thread) keeping a reference to your subscriber chain because it's likely blocked and hasn't stopped doing work yet. This isn't a Retrofit issue.
