### ISSUE TITLE
Issue<Using Custom GSON Converters for multiple Base_API_URLs>

### ISSUE THREAD

**Issue by Sheshlok** [square/retrofit#1914]
Hi - I have searched extensively on SO and issues list here but could not find an optimal solution to the issue. Can you please help ? Here is the gist:
https://gist.github.com/Sheshlok/f8ee09a6760f6aa3b05ad9c03d6b247b

**Issue** The second API returns a malformed JSON response, specifically, one that is wrapped in "finance_charts_json_callback(.....)". I tried implementing a custom GSON converter as you can see in the gist above but keep getting the same error (`[@Observable#getStockHistory -> onError() -> 'Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $']`)

**Note:** 
1. Have checked JsonpParser with the actual API response and it works fine.
2. I can solve this problem by using OkHttp class 'onResponse' callback, and trimming the response string appropriately before parsing JSON. However, I needed to use Observables.

**Comment by JakeWharton** [comment]
You could use an [OkHttp interceptor][1] to detect this prefix and then wrap the `Source` with one that skips the prefix `finance_charts_json_callback(` and always reads one byte-ahead to detect EOF and skip the trailing `)`. This is effectively the same thing that you said, except you are doing it in the normal request pipeline and it can thus be done automatically by the client instead of at the Retrofit level.

You can certainly continue to do this in a custom converter though. It's hard to see what's wrong with it since there's no tests to prove the behavior.

I will say that the `readerToString` method can be completely eliminated by just calling `value.string()` in the `convert` method, although that's unlikely to be part of the problem.

 [1]: https://github.com/square/okhttp/wiki/Interceptors

**Comment by Sheshlok** [comment]
Thanks Jake for clarifying and simplifying the code !!! 
One point of clarification though on the custom converters - when you say "there's no tests to prove the behavior", do you mean I should write a test similar to 'GsonConverterFactoryTest' in sample to make sure its working as desired or is it something else you are referring to?

**Comment by Sheshlok** [comment]
@JakeWharton : Am including the 'LoggingInterceptor' output here. Please have a look - May be this can help to find out why the custom converter is not working.  

`07-14 01:31:19.893 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: --> GET http://chartapi.finance.yahoo.com/instrument/1.0/TWTR/chartdata;type=close;range=1m/json http/1.1
07-14 01:31:19.893 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: --> END GET
07-14 01:31:20.021 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: <-- 200 OK http://chartapi.finance.yahoo.com/instrument/1.0/TWTR/chartdata;type=close;range=1m/json (128ms)
07-14 01:31:20.021 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: Date: Wed, 13 Jul 2016 20:01:21 GMT
07-14 01:31:20.021 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: P3P: policyref="http://info.yahoo.com/w3c/p3p.xml", CP="CAO DSP COR CUR ADM DEV TAI PSA PSD IVAi IVDi CONi TELo OTPi OUR DELi SAMi OTRi UNRi PUBi IND PHY ONL UNI PUR FIN COM NAV INT DEM CNT STA POL HEA PRE LOC GOV"
07-14 01:31:20.021 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: Expires: Thu, 14 Jul 2016 00:07:57 GMT
07-14 01:31:20.021 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: Last-Modified: Wed, 13 Jul 2016 00:07:57 GMT
07-14 01:31:20.021 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: Cache-Control: public
07-14 01:31:20.021 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: Content-Type: text/javascript; charset=utf-8
07-14 01:31:20.021 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: Vary: Accept-Encoding,X-Ssl
07-14 01:31:20.021 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: Age: 0
07-14 01:31:20.021 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: Via: http/1.1 yts222.global.media.sg3.yahoo.com (ApacheTrafficServer [cMsSfW]), http/1.1 r09.ycpi.inc.yahoo.net (ApacheTrafficServer [cHs f ])
07-14 01:31:20.021 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: Server: ATS
07-14 01:31:20.021 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: Connection: keep-alive
07-14 01:31:20.021 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: Y-Trace: BAEAQAAAAABeH2o_zFkOAQAAAAAAAAAASmqbhL0XQhkAAAAAAAAAAAAFN4nZbqDiAAU3idluon4hGA0aAAAAAA--
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: finance_charts_json_callback( { "meta" :
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp:  {
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp:   "uri" :"/instrument/1.0/TWTR/chartdata;type=close;range=1m/json",
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp:   "ticker" : "twtr",
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp:   "Company-Name" : "Twitter, Inc. Common Stock",
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp:   "Exchange-Name" : "NYQ",
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp:   "unit" : "DAY",
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp:   "timestamp" : "",
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp:   "first-trade" : "20131107",
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp:   "last-trade" : "20160712",
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp:   "currency" : "USD",
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp:   "previous_close_price" : 14.0200
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp:  }
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp:  ,
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp:  "Date" : {"min" :20160613,"max" :20160712 }
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp:  ,
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp:  "labels" : [20160613,20160620,20160627,20160705,20160711 ]
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp:  ,
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp:  "ranges" : {"close" : {"min" :14.5500,"max" :18.1000 } }
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp:  ,
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp:  "series" : [
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp:  { "Date" :20160613,"close" :14.5500 } 
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: , { "Date" :20160614,"close" :15.3600 } 
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: , { "Date" :20160615,"close" :15.9600 } 
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: , { "Date" :20160616,"close" :15.8700 } 
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: , { "Date" :20160617,"close" :16.1000 } 
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: , { "Date" :20160620,"close" :16.3400 } 
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: , { "Date" :20160621,"close" :16.3200 } 
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: , { "Date" :20160622,"close" :16.1300 } 
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: , { "Date" :20160623,"close" :17.0400 } 
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: , { "Date" :20160624,"close" :16.4400 } 
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: , { "Date" :20160627,"close" :15.8400 } 
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: , { "Date" :20160628,"close" :16.4200 } 
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: , { "Date" :20160629,"close" :16.8300 } 
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: , { "Date" :20160630,"close" :16.9100 } 
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: , { "Date" :20160701,"close" :17.2800 } 
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: , { "Date" :20160705,"close" :17.1400 } 
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: , { "Date" :20160706,"close" :17.2000 } 
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: , { "Date" :20160707,"close" :17.3700 } 
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: , { "Date" :20160708,"close" :18.0800 } 
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: , { "Date" :20160711,"close" :17.7100 } 
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: , { "Date" :20160712,"close" :18.1000 } 
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: ]
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: } )
07-14 01:31:20.022 32387-1728/com.example.sam_chordas.stockhawk D/OkHttp: <-- END HTTP (1421-byte body)`

**Comment by Sheshlok** [comment]
@JakeWharton : Thanks, the 'interceptor' worked seamlessly and got the job done. As you said, It definitely is more elegant than writing custom converters. 
However, I am still intrigued by why the custom converters did not work. Anything you can suggest to troubleshoot ?
