### ISSUE TITLE
Allow colons (":") in path parameters

### ISSUE THREAD

**Issue by jianghaolu** [square/retrofit#1915]
I'm having a URL
```java
@GET("paths/array/{arrayPath:commaSeparated}")
Call<ResponseBody> arrayCsvInPath(@Path("arrayPath:commaSeparated") String arrayPath);
```

But I get
```
java.lang.IllegalArgumentException: @Path parameter name must match \{([a-zA-Z][a-zA-Z0-9_-]*)\}. Found: arrayPath:commaSeparated (parameter #1)
    for method PathsService.arrayCsvInPath
	at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:695)
	at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:686)
	at retrofit2.ServiceMethod$Builder.parameterError(ServiceMethod.java:704)
	at retrofit2.ServiceMethod$Builder.validatePathName(ServiceMethod.java:667)
	at retrofit2.ServiceMethod$Builder.parseParameterAnnotation(ServiceMethod.java:391)
	at retrofit2.ServiceMethod$Builder.parseParameter(ServiceMethod.java:328)
	at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:201)
	at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:166)
	at retrofit2.Retrofit$1.invoke(Retrofit.java:145)
	at fixtures.url.implementation.$Proxy6.arrayCsvInPath(Unknown Source)
	at fixtures.url.implementation.PathsImpl.arrayCsvInPath(PathsImpl.java:1386)
	at fixtures.url.PathsTests.arrayCsvInPath(PathsTests.java:164) <24 internal calls>
```

Any reason colons are not allowed?

**Comment by JakeWharton** [comment]
There is no reason, but I also don't see a reason why you need to use a colon either.

**Comment by jianghaolu** [comment]
The URL is from an Open API JSON spec. So it's not (completely) controlled by me.
It would save me a bunch of emails back and forth to change that if you can add that to the regex. I'll really appreciate it.

**Comment by JakeWharton** [comment]
The string in `@Path` does not end up in the URL. You can name it whatever you want.

**Comment by jianghaolu** [comment]
That's right.
However, the entire path `"paths/array/{arrayPath:commaSeparated}"` is hardcoded in the Open API JSON spec.

**Comment by JakeWharton** [comment]
Right, but you can still use `paths/array/{whatever}` and `@Path("whatever")`. It doesn't matter what you actually use because that value never ends up in the final URL.

**Comment by jianghaolu** [comment]
Yeah then I'll need to pre-process the URL. But thanks anyways.

**Comment by JakeWharton** [comment]
Pre-process how? I don't understand why you are required to use a colon.

**Comment by jianghaolu** [comment]
Oh, the tool I'm writing parses the Open API Spec and generates Java code to make REST calls. Therefore this URL was directly copied over from the JSON spec into the Retrofit interface definition.

**Comment by jianghaolu** [comment]
So I just need to add a line to remove the colon when I read the URL from the JSON.

**Comment by JakeWharton** [comment]
Ah you're generating the interfaces. That's the part I totally didn't get.

I remembered the actual reasoning: we wanted the naming rules to be the
same as a Java identifier so that in Java 8 we could use the new reflection
API to retrieve the parameter names. This would mean you'd only have to do
`@Path String foo` and it would replace `{foo}` in the URL. That hasn't
been implemented though. As far as I remember the parameter name feature is
disabled by default in Java 8, sadly.

**Comment by jianghaolu** [comment]
Yeah sorry for the confusion.
That sounds interesting. And in that case hyphens won't be legal either.

**Comment by steve78b** [comment]
Google have just created a URL with a colon in it.
Example POST    [https://fcm.googleapis.com/v1/projects/myproject-b5ae1/messages:send]( )
See [https://firebase.google.com/docs/cloud-messaging/send-message]( https://firebase.google.com/docs/cloud-messaging/send-message)  for all the details.

Can this request be re-opened?
Or should I ask Google to change?

**Comment by swankjesse** [comment]
Colons are allowed in the paths. They aren’t allowed as the names of the placeholders.

**Comment by steve78b** [comment]
Issue #2730 covers this and solves my problem.
