### ISSUE TITLE
 FATAL EXCEPTION: OkHttp Dispatcher 

### ISSUE THREAD

**Issue by prabhu-velo** [square/retrofit#1917]
FATAL EXCEPTION: OkHttp Dispatcher 
 java.lang.IllegalArgumentException: Unexpected char 0x0a at 82 in Authorization value: Basic ZXlKcFlYUWlPakUwTmpnMU1qTTRORFlzSW1WNGNDSTZNVFEzTmpJNU9UZzBOaXdpWVd4bklqb2lTRk15TlRZaWZRLmV5SjFjMlZ5Ym1GdFpTSTZJamMwTURFd05qRTRNRE1pZlEuMXR1eGhscmVKY3RXeENjenNMcGlXZ2ZKdVZNWjFsQU9zX3pEcEREMGl0azo=

**Comment by JakeWharton** [comment]
This exception isn't coming from Retrofit. Try asking your question on StackOverflow with the 'okhttp' tag.

**Comment by prabhu-velo** [comment]
same header value of Authorization is worked with Retrofit 1

**Comment by JakeWharton** [comment]
It's unlikely to have worked with the same version of OkHttp in Retrofit 1,
since the error is not from Retrofit.

**Comment by prabhu-velo** [comment]
I fix issue using #1153
thank you for support 👍
