### ISSUE TITLE
java.lang.IllegalArgumentException: baseUrl must end in /

### ISSUE THREAD

**Issue by prasanthsyzygy** [square/retrofit#1920]
Hi,
I am using GET method type while using URL there is an error mentioning "baseURL must end in /" but my class worked fine when i am using post method . 

Thanks,
Prasanth

**Comment by swankjesse** [comment]
Is this a bug report or a question? If it's a bug report please add a test case. If it's a question please use StackOverflow instead. Thanks!

**Comment by prasanthsyzygy** [comment]
ok thanks for your update
