### ISSUE TITLE
Allow Pluggable ServiceMethod

### ISSUE THREAD

**Issue by remmeier** [square/retrofit#1921]
ServiceMethod and its Builder are currently final and hard-coded into retrofit. It would be great to make this pluggable.

- ServiceMethod becomes an interface
- current implementation becomes a default implementation.
- additional ServiceMethod / Builders can be registered with Retrofit.
- each registration  has a priority, higher priority checked first.
- an accept(...) method allows to check whether a given implementation can handle a particular method

It should only be a very minor change.

One use case of this could be deeper support for Json API. There is a Java implementation with Retrofit support provided by https://github.com/jasminb/. But the interfaces/stubs could be simpler and support additional parameters like query object for sorting, filtering, paging and support to extract more information of the result (links, meta-data, etc.). There is an issue for jasminb at https://github.com/jasminb/jsonapi-converter/issues/47.

**Comment by JakeWharton** [comment]
I don't understand what exposing `ServiceMethod` would buy you here. Can you explain the advantages more directly? As far as I can tell the existing converter API is enough to support that use case already.

**Comment by remmeier** [comment]
I had a second look and decided to use OkHttp directly instead of Retrofit because requirements for a generic vs. JSON API stub look quite different.
