### ISSUE TITLE
Is the gh-pages branch still in the process of being updated to 2.0 API? [Documentation]

### ISSUE THREAD

**Issue by yegeniy** [square/retrofit#1925]
Is the gh-pages branch still in the process of being updated to 2.0 API, as per https://github.com/square/retrofit/blob/gh-pages/index.html#L67 ?

**Comment by yegeniy** [comment]
Seems up to date to me.

**Comment by JakeWharton** [comment]
Yeah that can probably be removed now. I'll try to get to it tomorrow.

**Comment by yegeniy** [comment]
Good to know. Thanks Jake.
