### ISSUE TITLE
Same service with different base url 

### ISSUE THREAD

**Issue by jaumard** [square/retrofit#1927]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I made this factory : 
```
package com.sync.fr.async.services;

import com.sync.fr.SyncSDK;
import com.sync.fr.conf.GlobalConf;
import com.sync.fr.conf.URLConf;
import com.sync.fr.models.users.UserInfos;
import com.sync.fr.retrofit.HeaderInterseptor;

import java.util.List;

import okhttp3.Interceptor;
import okhttp3.OkHttpClient;
import okhttp3.logging.HttpLoggingInterceptor;
import retrofit2.Retrofit;
import retrofit2.converter.gson.GsonConverterFactory;

public class ServiceGenerator {
    public static String API_BASE_URL = URLConf.URL_BASE;

    private static OkHttpClient.Builder httpClient = new OkHttpClient.Builder();
    private static OkHttpClient.Builder httpClientConnected = new OkHttpClient.Builder();

    private static Retrofit.Builder builder = new Retrofit.Builder().baseUrl(API_BASE_URL)
                                                                    .addConverterFactory(GsonConverterFactory.create());
    private static Retrofit.Builder builderConnected = null;

    private static Retrofit retrofit;
    private static Retrofit retrofitConnected;

    public static <S> S createService(Class<S> serviceClass) {
        UserInfos userInfos = SyncSDK.i().getUserInfos();
        return userInfos == null ? createServiceBasic(serviceClass) : createServiceConnected(serviceClass);
    }

    private static <S> S createServiceBasic(Class<S> serviceClass) {
        List<Interceptor> interceptors = httpClient.interceptors();

        if (interceptors.size() == 0) {
            /**
             * Add header to requests
             */
            httpClient.addInterceptor(new HeaderInterseptor());
            HttpLoggingInterceptor logging = new HttpLoggingInterceptor();

            // set your desired log level
            logging.setLevel(HttpLoggingInterceptor.Level.BODY);
            httpClient.addInterceptor(logging);
        }

        if (retrofit == null) {
            retrofit = builder.client(httpClient.build()).build();
        }

        return retrofit.create(serviceClass);
    }

    private static <S> S createServiceConnected(Class<S> serviceClass) {
        List<Interceptor> interceptors = httpClientConnected.interceptors();
        UserInfos userInfos = SyncSDK.i().getUserInfos();
        if (builderConnected == null) {
            builderConnected = new Retrofit.Builder().baseUrl(API_BASE_URL + userInfos.getUri())
                                                     .addConverterFactory(GsonConverterFactory.create());
        }
        if (interceptors.size() == 0) {
            /**
             * Add header to requests
             */
            httpClientConnected.addInterceptor(new HeaderInterseptor());
            HttpLoggingInterceptor logging = new HttpLoggingInterceptor();

            // set your desired log level
            logging.setLevel(HttpLoggingInterceptor.Level.BODY);
            httpClientConnected.addInterceptor(logging);
        }

        if (retrofitConnected == null) {
            retrofitConnected = builderConnected.client(httpClientConnected.build()).build();
        }

        return retrofitConnected.create(serviceClass);
    }
}
```

When I create the same service but with a different `baseUrl` the first one is keep (in my example `API_BASE_URL` is always used and `API_BASE_URL+userInfos.getUri()` never. I put some breakpoint and  `createServiceConnected` is correctly called and API base should be `API_BASE_URL+userInfos.getUri()` but it's not... 

Did I miss something or it's a bug ? I just want to have different base URL once user is connected, first I try to only recreate the builder with the new baseURL but as it failed I start to duplicate all instance to see if it work better but it doesn't...

**Comment by JakeWharton** [comment]
My guess would be that when you call it `retrofitConnected` is not null and thus a previous instance of `Retrofit` is used to create the service with the wrong base URL.

Nothing about your code indicates that this is a Retrofit bug. Your use of static state and lazily initialization makes this code very hard to reason about and is the cause of the problematic behavior.

**Comment by jaumard** [comment]
@JakeWharton here is what I'm talking about https://gist.github.com/jaumard/fe679ee7bed6f73bfe857472c724bc77 is there a way to do this ? I also try with interceptors with no luck...

In my API I have to first call `/` to have a prefix who look like `/user/123` and all my other call must look like `/user/123/mymethod` and I don't want to add `@Path  String prefix` in all my call. I was supposing that `baseUrl` could take segments but they're ignored.
