### ISSUE TITLE
please handle the reports @hackerone

### ISSUE THREAD

**Issue by OneSourceCat** [square/retrofit#1928]
please handle the reports @hackerone

**Comment by JakeWharton** [comment]
Those are not managed directly by us the authors, but I have sent a ping to the team who does manage them about it. They'll reach out through the site.

**Comment by OneSourceCat** [comment]
Oh I see. However, there is nobody checking the report either. Maybe they forgot the account at hackerone..... How can I connect them?

**Comment by JakeWharton** [comment]
I have emailed them to look, but I have no timeframe as to when they'll get
to it.
