### ISSUE TITLE
How can upload 20 image of array into server?

### ISSUE THREAD

**Issue by jalpeshsolanki** [square/retrofit#1932]
Sir How can upload 20 images in android retofit 1.9 and i pick image in multiimagepicker and found onActivityResult array of images but how can create file and store to file and pass to api in retrofit i search in retrofit create typedfile for file passing but how can pass that image?and can i possible to 20 images upload same time in android?

  @Override    
        protected void onActivityResult(int requestCode, int resultCode, Intent data) {
                 super.onActivityResult(requestCode, resultCode, data);     
            if(requestCode == REQUEST_IMAGE){
                if(resultCode == RESULT_OK){
                    // Get the result list of select image paths
                    List<String> path = data.getStringArrayListExtra(MultiImageSelectorActivity.EXTRA_RESULT);
                    // do your logic ....
                }
            }
        }

        @Background
        public void createAlbum(){
            messageUtil.showProgressDialog();
            if (Utility.checkInternetConnection(ActivityAddAlbum.this)) {
                VLogger.infoLog("CREATE ALBUM");
                RetrofitClient.getInstance().getRestOkClient().addAlbum(edtAlbumName.getText().toString(), VPreferences.getPreferanceEmail(ActivityAddAlbum.this),, loginCallBack);
            } else {
                messageUtil.showToast("No Internet!!");
            }

**Comment by JakeWharton** [comment]
This is a usage question and not a bug or feature request. Please ask on StackOverflow with the 'retrofit' tag.
