### ISSUE TITLE
Is there a retrofit snapshot with latest okhttp-3.4.1 version ?

### ISSUE THREAD

**Issue by anirudhramanan** [square/retrofit#1933]
Since, they have mentioned a major bug fix which got fixed in 3.4.1.

**From okhttp website:**
Fix an major bug in encoding HTTP headers. In 3.4.0 and 3.4.0-RC1 OkHttp had an off-by-one bug in our HPACK encoder. This bug could have caused the wrong headers to be emitted after a sequence of HTTP/2 requests! Everyone who is using OkHttp 3.4.0 or 3.4.0-RC1 should upgrade for this bug fix.

**Comment by swankjesse** [comment]
You can configure your OkHttp dependency directly in your build and Retrofit will work with it.

**Comment by JakeWharton** [comment]
What he said.

**Comment by anirudhramanan** [comment]
Yes, checked with it. Gradle resolves the okhttp version to 3.4.1 internally.
