### ISSUE TITLE
Prevent deserializing null values

### ISSUE THREAD

**Issue by robinsingh-bw** [square/retrofit#1937]
Hi,

I have a pojo like this:
public class User implements Serializable {
	@SerializedName("name")
	public String name;
	@SerializedName("favorites")
	public ArrayList<Favorite> favorites = new ArrayList<>;
}

Sometimes the server can respond with json such as: { "name": "my name", "favorites": null }

In such cases I want to keep the default initialized array instead of setting it to null. I had a similar issue with strings but I solved that by registering a custom type adapter. I dont want to keep registering custom adapters for all different objects though. Is there any way to force retrofit to just ignore 'null' values?

Regards.

**Comment by JakeWharton** [comment]
This is something that you'll need to reconcile with your serialization
library (which looks like Gson). Retrofit plays no part in serialization
other than delegating to third-party libraries.
