### ISSUE TITLE
Send form-data in method POST  ?

### ISSUE THREAD

**Issue by esantiago1** [square/retrofit#1938]
send request POSTMAN  

e:123

Response
1||20050|Hello Hello

I tried these steps but without success
http://stackoverflow.com/questions/29680158/how-to-send-multipart-form-data-with-retrofit
http://stackoverflow.com/questions/37814857/retrofit-2-with-only-form-data

how it would be implemented with retrofit?

**Comment by esantiago1** [comment]
I have managed to fix :)

**Comment by JakeWharton** [comment]
Glad you got it working.
