### ISSUE TITLE
Multipart requests now are harder than get 50000 points in FlappyBird

### ISSUE THREAD

**Issue by felipefpx** [square/retrofit#1939]
I'm really sad about Retrofit 2.0+

When I created Multipart requests with Retrofit 1.9 things were so easy, with TypedFiles and the possibility to put @Part with different objects. 

Now, I'm trying to send a request with one object and 2 images. When I sent using **@Part("data") Object** I got **500 - Bad Request**. When I tried to use **@Part("data[name]") RequestBody name** I got success in my request, but it require**d one RequestBody to each field that I have in my Object**. One of these fields is an **int array**, and that is impossible to send like **RequestBody** because **RequestBody** just work with **String parameters** and my server received like **["[1,16]"]**.

**How can I send 2 images and 1 Object in a Multipart request with Retrofit 2? Do I really need to create one RequestBody to each attribute I want to send? How can I create a RequestBody with an int array?**

Thank you,
Best Regards

**Comment by JakeWharton** [comment]
The ability to use objects hasn't changed and you can use `MultipartBody.Part` as a replacement for `TypedFile`.

Please ask general usage questions on StackOverflow with the 'retrofit' tag. This issue tracker is for bug reports and feature requests only.
