### ISSUE TITLE
okhttp3.Headers$Builder.checkNameAndValue vallue == null

### ISSUE THREAD

**Issue by Daard** [square/retrofit#1942]
This is code sample.
OkHttpClient.Builder clientBuilder = new OkHttpClient.Builder();
        clientBuilder.addInterceptor(new Interceptor() {
            @Override
            public Response intercept(Interceptor.Chain chain) throws IOException {
                Request original = chain.request();
                Request request = original.newBuilder()
                        .addHeader("Accept", "application/json")
                        .addHeader("Content-Type", "application/json; text/html; charset=UTF-8")
                        .addHeader("X-User-Api-Token", token)
                        .method(original.method(), original.body())
                        .build();
                return chain.proceed(request);
            }
        });

And stacktrace shows NPE exception in headers builder, vallue == null. How to fix this issue?

**Comment by egor-n** [comment]
Your `token` is null. OkHttp does not allow null in headers (see [this line](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/Headers.java#L316)).

**Comment by Daard** [comment]
You are right.
