### ISSUE TITLE
How to Login username, password Android by Basic Auth using Retrofit 2.0 ?

### ISSUE THREAD

**Issue by Khamphai** [square/retrofit#1947]
What kind of issue is this?

 - [x] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by JakeWharton** [comment]
Basic auth is just a header so you can use `@Header("Authorization")` on a parameter.

Please ask usage questions on StackOverflow using the 'retrofit' tag.

**Comment by Khamphai** [comment]
But, I dont Know how to use Basic Auth, When i put value in editText and
then get value from editText To use
....Please Help Me

**Comment by JakeWharton** [comment]
Sorry, but this is not a support forum for development. StackOverflow is
still more appropriate.

**Comment by Khamphai** [comment]
For Example : https://futurestud.io/blog/android-basic-authentication-with-retrofit
for this : I don't Understand
public static <S> S createService(Class<S> serviceClass) {
        return createService(serviceClass, null, null);
    }

    public static <S> S createService(Class<S> serviceClass, String username, String password) {
        if (username != null && password != null) {
            // concatenate username and password with colon for authentication
            String credentials = username + ":" + password;
            // create Base64 encodet string
            final String basic =
                    "Basic " + Base64.encodeToString(credentials.getBytes(), Base64.NO_WRAP);

            builder.setRequestInterceptor(new RequestInterceptor() {
                @Override
                public void intercept(RequestFacade request) {
                    request.addHeader("Authorization", basic);
                    request.addHeader("Accept", "application/json");
                }
            });
        }

        RestAdapter adapter = builder.build();
        return adapter.create(serviceClass);
    }
