### ISSUE TITLE
Getting onFailure with null body and response code 200

### ISSUE THREAD

**Issue by arushijain45** [square/retrofit#1950]
There are certain use cases where my api gives me 200 with null response body.

In such cases, Retrofit 2 is giving onFailure() callback instead of onResponse().
Shouldn't it go to onResponse with sucess.

**Comment by JakeWharton** [comment]
The exception will tell you the problem, which I guess is you trying to deserialize that empty body as a type. If you don't care about the response you can use `Void` as the response type.

**Comment by arushijain45** [comment]
But don't you think that if we are receiving 200 status code in api result (whatever may be the value of result, whether it is null or containing some value) it should come under onResponse instead of onFailure?

**Comment by JakeWharton** [comment]
Not if we can't deserialize the body into the type you told us to. That is
very much a failure.
