### ISSUE TITLE
Change base URL, segments ignored

### ISSUE THREAD

**Issue by jaumard** [square/retrofit#1951]
When I change a base URL from my service all segments of the new base url are ignored. 

I made a gist to show you my problem : https://gist.github.com/jaumard/fe679ee7bed6f73bfe857472c724bc77 is there a way to do this ? I also try with interceptors with no luck...

In my API I have to first call / to have a prefix who look like /user/123 and all my other call must look like /user/123/mymethod and I don't want to add @Path String prefix in all my call. I was supposing that baseUrl could take segments but they're ignored.

**Comment by JakeWharton** [comment]
They're not ignored. You are using absolute URLs instead of relative ones. Please read [the documentation on `baseUrl()`][1] for examples of how to do this.

 [1]: http://square.github.io/retrofit/2.x/retrofit/retrofit2/Retrofit.Builder.html#baseUrl-okhttp3.HttpUrl-
