### ISSUE TITLE
I can't disable encoding in POST @Field or @FieldMap

### ISSUE THREAD

**Issue by pesjak** [square/retrofit#1952]
Hi, this is my first time posting to here so please be gentle.
I'm trying to send an HashMap to the API through Retrofit, I tried converting it to String, send it and it didn't quite work. The API expects the list named meta with some values, but with that list you have to send an API key so it looks like this:
 ```
   @FormUrlEncoded
    @POST("api/read/criteria_get")
    Call<Criteria> getCriteria(@Query("apikey") String api_key,
                                  @FieldMap(encoded = true) HashMap<String,HashMap<String,String>> meta);
```
I tried even, with the @Field named meta, and sending a basic HashMap<String,String> and the result was the same. 

I'm using HttpLoggingInterceptor for looking debugging.
No matter if encoding is TRUE or FALSE the result is the same,
The request that is send:
 D/OkHttp: meta=%7Buser_id%3D401%7D

with an error from API, User ID is not set in request (POST), which makes sense, because it should be something like this: meta={user_id=401}.
I'm wondering is this a bug or am i doing something wrong?

Thanks for the response,
with regards Primož

**Comment by pesjak** [comment]
I couldn't solve it so we've changed the api, so now i send a @Body which is json, and i've got it to work.

**Comment by xueyaolive** [comment]
When you use the post mode, you should not comment @Query,Maybe you should use this comment @Field,When you use the @Body,You should get rid of the notes @FormUrlEncoded.Hope to help you！

**Comment by pesjak** [comment]
```
    @Headers("Content-Type: application/json")
    @POST("api/read/criteria_get")
    Call<Criteria> getCriteria(@Query("apikey") String api_key,
                               @Body HashMap<String,Object> body);

```
This is how i have it now, @Query is needed because the API is in GET

**Comment by JakeWharton** [comment]
So Retrofit doesn't actually control this. It comes from OkHttp's `FormBody` type which uses [this list][1] for encoding. However, your server should be percent-decoding these values to the same thing. The whole point of percent encoding is to avoid ambiguity. In theory you could percent encode every single character. That said, the current set comes from the behavior of major browsers (Chrome and Firefox) so someone posting from an HTML form would produce the same version.

 [1]: https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/HttpUrl.java#L294
