### ISSUE TITLE
Retrofit change Server Response

### ISSUE THREAD

**Issue by rohnstock** [square/retrofit#1954]
Hello,

my response of a POST request in various REST-Clients is:
HTTP Response Code: 401
`{
"code": 401
"message": "My custom error message."
}`

Retrofit says the response is:
HTTP Response Code: 401
`{
"code": 401
"message": "Unauthorized"
}`

Retrofit change the message to the current HTTP status code.

Is there a possibility to get the real server response?

**Comment by JakeWharton** [comment]
Retrofit does not modify the response from the server in error cases. If you can provide a test case that demonstrates Retrofit is at fault I will fix it, but there's no code for changing anything like this in Retrofit.

**Comment by GokhanArik** [comment]
@rohnstock Try testing your call using Postman for Chrome or some other tool and compare responses

**Comment by rohnstock** [comment]
@GokhanArik 
Postman shows me the correct body with the correct message.

I send a 401 HTTP status code not a 200 ok (from a nginx server).

**Comment by JakeWharton** [comment]
Without a test case there's no clear action to take here.

**Comment by tarunnickelfox** [comment]
Hello,

I have run into the same issue. I am using https://newsapi.org/v2/sources?apiKey=xxxxx this link. When testing with postman the server sends a proper response of what type of error we are running into.
**e.g:** if we type wrong key response is: `{"status":"error","code":"apiKeyInvalid","message":"Your API key is invalid or incorrect. Check your key, or go to https://newsapi.org to create a free API key."}` 

but Retrofit sends me following as response: 

`Response{protocol=http/1.1, code=401, message=Unauthorized, url=https://newsapi.org/v2/sources}`.

I am getting same response through Retrofit if I hit https://newsapi.org/v2/sources whereas the server sends: 

`{"status":"error","code":"apiKeyMissing","message":"Your API key is missing. Append this to the URL with the apiKey param, or use the x-api-key HTTP header."}`

I hope this is a good enough test case.

Thank you in advance for the help.
