### ISSUE TITLE
Support Brotli Compression (RFC7932) For More Performance

### ISSUE THREAD

**Issue by RehanSaeed** [square/retrofit#1957]
Feature Request

Brotli compression is the new standard compression algorithm [RFC7932](https://www.rfc-editor.org/info/rfc7932) which provides around ~20% better compression over GZIP. We have apps working in rural parts of Africa where bandwidth is a problem, it would be amazing if Retrofit added support for Brotli.

**Comment by swankjesse** [comment]
You can implement it yourself with an OkHttp interceptor. See this for inspiration.
https://github.com/square/okhttp/wiki/Interceptors#rewriting-requests
