### ISSUE TITLE
Query with dynamic key and value as list

### ISSUE THREAD

**Issue by kabindra** [square/retrofit#1960]
I want to create dynamic query for elasticsearch facet search thus require query in form
?q=t-shirt&size[]=S&size[]=L&category=men&color[]=Black&color[]=Grey

I couldn't use List<String> for Query values as query names are dynamic also I couldn't place multiple entries in Map as key has to be unique. Thus `@QueryMap(Map<String,String> map)` or `@Query(List<String> list)` or `@QueryMap(Map<String, List<String>> map)` just don't fit in.

**Comment by JakeWharton** [comment]
This has been requested multiple times and we've bucketed it under #626. That said, I think the current plan is to implement this natively for 2.2 so I'll just leave this open to track it.

**Comment by iwo** [comment]
If `@QueryMap Map<String, List<String>> map` created a separate query argument for each value in the list would that solve your problem @kabindra? If so, we could check the second parameter of `Map` type and if it's `Iterable` enable the repeating behavior just like we do for `@Query List<String> list`.

@JakeWharton do you think we can enable this behavior for all `@*Map` annotations by default or would you add some additional flag to the annotations that use request body converters?
Someone may have a custom `Converter` registered for the `List<Foo>` type in which case enabling this by default would be a breaking change.

**Comment by kabindra** [comment]
@iwo If we can put Iterable list as key-value pairs instead of key and values as a single pair, I think it will solve it.

**Comment by JakeWharton** [comment]
Tracking with #1324.
