### ISSUE TITLE
how can I use request param before execute

### ISSUE THREAD

**Issue by Witype** [square/retrofit#1965]
I want do do something before http call,because of ecah request params is different,what can I do!!!
![image](https://cloud.githubusercontent.com/assets/6899329/17511926/deffecbe-5e57-11e6-916f-f748dd332f83.png)
![image](https://cloud.githubusercontent.com/assets/6899329/17511932/e7d11f2a-5e57-11e6-8025-a28b04f063bd.png)
thanks!!!

**Comment by JakeWharton** [comment]
Please ask usage questions on StackOverflow.

You can also consider just abstracting the Retrofit interaction behind your own API which can operate on the request values before sending them to Retrofit.

**Comment by GJson** [comment]
@Witype  Did you solve this problem

**Comment by Witype** [comment]
@GJson yes,I have solve this problem,what can I help you!

**Comment by GJson** [comment]
how  do you do?  

use Interceptor  before excute, i want to get the  chain.request.body  changes it  then excute

**Comment by Witype** [comment]
this is my code,hope to help you
~~~
private Interceptor PreInterceptor = new Interceptor() {
        @Override
        public Response intercept(Chain chain) throws IOException {
            Request request = chain.request();
            RequestBody body = request.body();
            if (body instanceof FormBody) {
                FormBody formBody = (FormBody) body;
                bodyParam = new HashMap<>();
                for (int i = 0 , size = formBody.size(); i < size; i++) {
                    bodyParam.put(formBody.name(i),formBody.value(i));
                }
            }
            //TODO
            return chain.proceed(request);
        }
    }
~~~

**Comment by GJson** [comment]
if    http.get    param like  @Query   @QueryMap  ?

**Comment by Witype** [comment]
RequestBody is an abstract class, you can cast to current type.

**Comment by GJson** [comment]
@GET(CONSTAN.URL)
    Call<JsonObject> getHouseCard(@Query("key") String key,
                                  @Query("userCode") String usercode,
                                  @Query("type") int type);

like this ,finally  what type this RequestBody ?

**Comment by Witype** [comment]
you should view the source code and debug what the type of RequestBody , I just use Field annotation in my code ,so FormBody is the current implements class of RequestBody,
~~~
//debug this line in code,the current type you will see,
request.body()
~~~
