### ISSUE TITLE
 Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.internal.Platform" on path: DexPathList

### ISSUE THREAD

**Issue by xwpeng** [square/retrofit#1970]
I try add HttpLoggingInterceptor like this:

         HttpLoggingInterceptor logging = new HttpLoggingInterceptor();
         logging.setLevel(HttpLoggingInterceptor.Level.BODY);
         OkHttpClient.Builder httpClient = new OkHttpClient.Builder();
         httpClient.addInterceptor(logging);
         Retrofit.Builder builder = new Retrofit.Builder();
         builder.baseUrl(baseUrl).addCallAdapterFactory(RxJavaCallAdapterFactory.create()).client(httpClient.build());

then i run work project,carsh occur.
Exception Log:
Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.internal.Platform" on path: DexPathList.
But in simple demo , no this problem.
what should i do to solve this?

**Comment by JakeWharton** [comment]
This is caused by using different versions of OkHttp artifacts. Ensure all your dependencies from `com.squareup.okhttp3` are using the same version.

**Comment by danginirav** [comment]
Well, I am not able to use `OkHttpClient` of `com.squareup.okhttp3`. Because `OkHttpClient` has been moved from package `com.squareup.okhttp` to `okhttp3` in the last version.

I have fixed this issue by downgrading okhttp dependency to `compile 'com.squareup.okhttp3:okhttp:3.2.0'`

**Comment by arekolek** [comment]
> Ensure all your dependencies from `com.squareup.okhttp3` are using the same version.

Hint: `./gradlew -q dependencies app:dependencies | grep 'com.squareup.okhttp.*' -o | sort -u`

**Comment by telenewbie** [comment]
compile 'com.squareup.okhttp3:logging-interceptor:3.8.0'
    compile 'com.squareup.okhttp3:okhttp:3.8.0'

**Comment by mohamedebrahim96** [comment]
Unsubscribe

**Comment by uiltonjose** [comment]
> ```
> compile 'com.squareup.okhttp3:logging-interceptor:3.8.0'
> compile 'com.squareup.okhttp3:okhttp:3.8.0'
> ```

This really works for me! Thanks a lot!!

**Comment by cong-spark** [comment]
> Well, I am not able to use `OkHttpClient` of `com.squareup.okhttp3`. Because `OkHttpClient` has been moved from package `com.squareup.okhttp` to `okhttp3` in the last version.
> 
> I have fixed this issue by downgrading okhttp dependency to `compile 'com.squareup.okhttp3:okhttp:3.2.0'`

That is really work for me. Thank you
