### ISSUE TITLE
Retrofit + Observable.

### ISSUE THREAD

**Issue by RuiHelderOliveira** [square/retrofit#1971]
I used retrofit with Observable.

When i subscribe a new Subscriber, In onNext callback a print of data is currectly but a receive, in onError method, this message: "Expected receiver of type <mypackage.myType>, but got java.util.ArrayList".

I test with Call and the result is expected.

I need used Observable to zip multiple requests.

Please help me.

Thanks.

**Comment by RuiHelderOliveira** [comment]
The problem are onNext method. If i convert object to string (to save in sharedpreferences) with new Gson().toJson(object, myclass.class), this produce this stack trace.

[java.lang.reflect.Field.get(Native Method), com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.writeField(ReflectiveTypeAdapterFactory.java:136), com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:241), com.google.gson.Gson.toJson(Gson.java:669), com.google.gson.Gson.toJson(Gson.java:648), com.google.gson.Gson.toJson(Gson.java:603), app.movvo.spacesvalidation.activities.MainActivity$7$override.onNext(MainActivity.java:411), app.movvo.spacesvalidation.activities.MainActivity$7$override.access$dispatch(MainActivity.java), app.movvo.spacesvalidation.activities.MainActivity$7.onNext(MainActivity.java:0), app.movvo.spacesvalidation.activities.MainActivity$7.onNext(MainActivity.java:378), rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134), rx.internal.operators.OperatorUnsubscribeOn$1.onNext(OperatorUnsubscribeOn.java:52), rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:227), rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107), android.os.Handler.handleCallback(Handler.java:739), android.os.Handler.dispatchMessage(Handler.java:95), android.os.Looper.loop(Looper.java:148), android.app.ActivityThread.main(ActivityThread.java:5422), java.lang.reflect.Method.invoke(Native Method), com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726), com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)]

**Comment by JakeWharton** [comment]
This doesn't appear to have anything to do with Retrofit. It looks like you have a disagreement between your types and what Gson expects–potentially because of ProGuard stripping the type information.

StackOverflow is your best place to ask for this, but more information is needed because it's unclear what is actually happening.
