### ISSUE TITLE
Result of endcode between @Path and @Query!

### ISSUE THREAD

**Issue by datdn1** [square/retrofit#1972]
I have a String "@#$%&-".
When I using @Path, I had debug my url where endcode that string has result was "@%23$%25&-".
But with @Query, I had different result, it's "@%23$%25%26-"

I don't change endcode default, so I don't understand why.

**Comment by JakeWharton** [comment]
`&` is a query parameter separator and thus has to be encoded when used inside a query key or value. You can safely use it in a path, however, because it's before the start of the query parameters (`?`).
