### ISSUE TITLE
Can't support two array

### ISSUE THREAD

**Issue by gushoubang** [square/retrofit#1979]
I want to post two array at the same time

```
Observable<JsonElement> postActiveBindimg(@Header("token") String token, @Path("replyId") String replyId,@Query("img_ids[]") String... img_idsb, @Query("unbind_img_ids[]") String... img_idsu);
```

but it can't support ,and must I post the body?

**Comment by JakeWharton** [comment]
Java doesn't let you have two varargs on a single method. It can only be on the last parameter. You can use traditional arrays (`String[]`) when you need multiple.
