### ISSUE TITLE
Empty 201 response

### ISSUE THREAD

**Issue by f22labsAman** [square/retrofit#1983]
I have been trying to make request to an api endpoint, and response is showing success in the resonse logs, but with 201, though thats the server's choice. Actually i am not able to access the response, as response body is giving me null. 
In postman, i am able to see the response, though they maybe making redirects on the backend.
So i tried to make a curl request, it also showed 201 only.
` @Headers({"x-dbg-apikey: api_key",
                "x-dbg-Subscriber-ID: subscriber_id",
                "Content-Type: application/json"})`

  `  @POST("users/auth")
    Call<PaasUser> getUserToken(@Body User user, @Header("x-dbg-date") int timestamp);`
I tried creating a follow up request also, but its only giving me 201.
Hence the concerned issue is , if the server only sends 201, we will not be able to access the response body, though it is visible in the logs.

**Comment by JakeWharton** [comment]
Retrofit does nothing special or different for 201s than 200s. Can you
write a test case that demonstrates the problem?

**Comment by f22labsAman** [comment]
Ok. But the response is showing me null.
Following are the logs,
`OkHttp: follow-redirect: true
OkHttp: x-dbg-date: 1471700155
OkHttp: {"password":"pass","username":"user"}
OkHttp: --> END POST (53-byte body)
OkHttp: <-- 201 Created http://dev-admin-paasapi.us-west-2.elasticbeanstalk.com/users/auth (531ms)
OkHttp: Server: nginx/1.8.1
OkHttp: Date: Sat, 20 Aug 2016 13:36:17 GMT
OkHttp: Content-Type: application/json
OkHttp: Content-Length: 384
OkHttp: Connection: keep-alive
OkHttp: Access-Control-Allow-Headers: Content-Type, Authorization, X-dbg-Subscriber-ID, X-dbg-api-signature, X-dbg-date, X-dbg-apikey
OkHttp: Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, OPTIONS
OkHttp: Access-Control-Allow-Origin: *
OkHttp: Allow: GET, POST, PUT, PATCH, DELETE, OPTIONS
OkHttp: Cache-Control: must-revalidate
OkHttp: {"message":"success","data":{"id":"user_id","token":"token"}}
OkHttp: <-- END HTTP (384-byte body)
MainActivity: Response: null
RenderScript: 0xa1ba2000 Launching thread(s), CPUs 2`

I have just changed the token and user_id, for security sake.

The call used,
` @Override
    public void onResponse(Call<PaasUser> call, Response<PaasUser> response) {
        int code = response.code();
        if (response.isSuccessful()) {
            PaasUser user = response.body();
            Log.v(LOG_TAG, "Response: " + response.body());
            Toast.makeText(this, "Got the user: " + user.token, Toast.LENGTH_LONG).show();
        } else {
            Log.v(LOG_TAG, "Anshi Response: " + response.raw());
            Toast.makeText(this, "Did not work: " + String.valueOf(code), Toast.LENGTH_LONG).show();
        }
    }`

**Comment by JakeWharton** [comment]
When I make this change all tests still pass:
```diff
diff --git a/retrofit/src/test/java/retrofit2/CallTest.java b/retrofit/src/test/java/retrofit2/CallTest.java
index 18dd035..f098f5e 100644
--- a/retrofit/src/test/java/retrofit2/CallTest.java
+++ b/retrofit/src/test/java/retrofit2/CallTest.java
@@ -67,7 +67,7 @@ public final class CallTest {
         .build();
     Service example = retrofit.create(Service.class);

-    server.enqueue(new MockResponse().setBody("Hi"));
+    server.enqueue(new MockResponse().setResponseCode(201).setBody("Hi"));

     Response<String> response = example.getString().execute();
     assertThat(response.isSuccessful()).isTrue();
@@ -81,7 +81,7 @@ public final class CallTest {
         .build();
     Service example = retrofit.create(Service.class);

-    server.enqueue(new MockResponse().setBody("Hi"));
+    server.enqueue(new MockResponse().setResponseCode(201).setBody("Hi"));

     final AtomicReference<Response<String>> responseRef = new AtomicReference<>();
     final CountDownLatch latch = new CountDownLatch(1);
```
Without a test case to reproduce the failure, I have no way to know what the problem is that you're seeing or how to fix it.
