### ISSUE TITLE
optimize  function 'loadServiceMethod ' lock

### ISSUE THREAD

**Issue by AlexFastAll** [square/retrofit#1988]
ServiceMethod loadServiceMethod(Method method) {
    ServiceMethod result;
    synchronized (serviceMethodCache) {
      result = serviceMethodCache.get(method);
      if (result == null) {
        result = new ServiceMethod.Builder(this, method).build();
        serviceMethodCache.put(method, result);
      }
    }
    return result;
  }

Each call to the method will locked，consider double check like below

ServiceMethod loadServiceMethod(Method method) {
    ServiceMethod result = serviceMethodCache.get(method);

   if(null == result){
    synchronized (serviceMethodCache) {
      result = serviceMethodCache.get(method);
      if (result == null) {
        result = new ServiceMethod.Builder(this, method).build();
        serviceMethodCache.put(method, result);
      }
    }
}
    return result;
  }

**Comment by JakeWharton** [comment]
Care to send a PR?

**Comment by JakeWharton** [comment]
Fixed in https://github.com/square/retrofit/pull/2017
