### ISSUE TITLE
Is there any way to get the value of the annotation dynamicly?(eg.  @POST)

### ISSUE THREAD

**Issue by HenryBrightChao** [square/retrofit#1990]
thanks.

**Comment by asinel** [comment]
After getting response you can get request, which has property METHOD.
P.S. this is question for stackoverflow, not for github issues

**Comment by JakeWharton** [comment]
Yep, what he said. All request info is exposed on the `Response` object (potentially through `raw()` which is OkHttp's `Response` object)
