### ISSUE TITLE
ErrorHandlingCallAdapter Error 

### ISSUE THREAD

**Issue by MahmoudAlnouno** [square/retrofit#1991]
I'm using this class 
But i have error 
Can't create handler inside thread that has not called Looper.prepare()
```
 @Override
            public void unexpectedError(Throwable t) {
display MSG here in my fragment 
            }
```

**Comment by JakeWharton** [comment]
It's called on the HTTP thread. If you need to run an action on the main thread post a runnable to `new Handler(Looper.getMainLooper())` or change the implementation to invoke the callbacks by doing that automatically.
