### ISSUE TITLE
How Getting Unknown variable number of parameters url or unlimited parameters url variable in retrofit

### ISSUE THREAD

**Issue by andishejavan** [square/retrofit#1994]
I want getting unknown variable number of parameters URL in Retrofit .number of parameter unlimited in URL . How generate URL unlimited in retrofit and android?
For Example:
http://api.aa.net/aaa/bbb/cc/daily?q=94043&mode=json&units=metric&cnt=7,....
 number of parameter undefine. how get this in retrofit?

**Comment by JakeWharton** [comment]
You can use `@QueryMap`. Please ask future questions on StackOverflow. GitHub issues are for feature requests and bug tracking only.

**Comment by andishejavan** [comment]
url parameters each time changes and not constant. how define this in retrofit?

**Comment by JakeWharton** [comment]
That's exactly what `@QueryMap` is for. Add as few or as many parameters as you like.
