### ISSUE TITLE
Impossible to POST paramaters and body at the same time

### ISSUE THREAD

**Issue by Sumbers** [square/retrofit#1995]
Hi, 

I don't understand why but we can't do something like this with retrofit2 : 

"@FormUrlEncoded
@POST("/api/carnet/entry/setFromApp")
    Call<ResponseBody> setMissingEntries(@Field("idUser") String idUser, @Body ArrayList<EntryToSend> entries);"

Why is it not possible to put parameters in the url and at the same time put body in the request ?

**Comment by JakeWharton** [comment]
Because both are trying to dictate the format of the body with different representations. You either want `@Query` or a `@Multipart` request.
