### ISSUE TITLE
jcenter retrofit-converter missing jar

### ISSUE THREAD

**Issue by hkhamm** [square/retrofit#1998]
The version of retrofit-converters on jcenter is missing the jar. It has the pom, but when I add it to my gradle.build I can't use it because it doesn't have the jar.

https://bintray.com/bintray/jcenter/com.squareup.retrofit2%3Aretrofit-converters/2.1.0#files/com/squareup/retrofit2/retrofit-converters/2.1.0

**Comment by JakeWharton** [comment]
The converter artifact is only a pom. See https://github.com/square/retrofit/wiki/Converters for the actual dependencies of the individual converters.
