### ISSUE TITLE
In one class GsonConverterFactory is able to get response as Response<String> but the same code at other place gives error "Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path" when sending string as response from server. 

### ISSUE THREAD

**Issue by dhruvam-gupta** [square/retrofit#2007]
What kind of issue is this?

 - [x] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by dhruvam-gupta** [comment]
`package com.go.gocard.card;

import com.go.gocard.model.Card;
import com.go.gocard.model.JsonResponse;

import retrofit2.Call;
import retrofit2.http.Body;
import retrofit2.http.GET;
import retrofit2.http.POST;


public interface CardService {

    @POST("savecard")
    Call<String> sendCard(@Body Card card);

    @GET("getResponse")
    Call<JsonResponse> getCardList();
}`

`public void sendCard(Card card) {

       Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(context.getString(CardResources.BASE_URL))
                .addConverterFactory(GsonConverterFactory.create())
                .build();

        CardService service = retrofit.create(CardService.class);
        Call<String> resp = service.sendCard(card);
        resp.enqueue(new Callback<String>() {
            @Override
            public void onResponse(Call<String> call, Response<String> response) {
                Toast.makeText(context,response.body(),Toast.LENGTH_SHORT).show();
                seeOthers();
                Log.d("Success","Sa");
            }

            @Override
            public void onFailure(Call<String> call, Throwable t) {
                Toast.makeText(context,t.getLocalizedMessage(),Toast.LENGTH_SHORT).show();
                Log.d("Failure_Reason",t.getMessage());
            }
        });
    }`
This is working fine. But the below code is not working .It is giving error as: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path
`package com.go.gocard.loginAndRegister;

import retrofit2.Call;
import retrofit2.http.Field;
import retrofit2.http.FormUrlEncoded;
import retrofit2.http.POST;

/**
 * Created by dhruvam on 02/09/2016.
 */
public interface LoginService {

    @POST("registration")
    @FormUrlEncoded
    Call<String> register(@Field("email") String emailId, @Field("pass") String pass);
}
`
` public void register(View v)
    {
        if(validated())
        {
            task = "register";
           // UserLoginAndRegisterTask task = new UserLoginAndRegisterTask();
            //task.execute();
           Retrofit retrofit = new Retrofit.Builder()
                    .baseUrl(context.getResources().getString(R.string.base_url))
                    .addConverterFactory(GsonConverterFactory.create())
                    .build();

           LoginService service = retrofit.create(LoginService.class);
           Call<String> resp = service.register(email, pass);
           resp.enqueue(new Callback<String>() {
                    @Override
                    public void onResponse(Call<String> call, Response<String> response) {
                        Log.d("message",response.body());
                    }

                    @Override
                    public void onFailure(Call<String> call, Throwable t) {
                        Log.d("error",t.getMessage());
                    }
                });

        }
    }`

I am doing same thing in both the codes but in second case it is not working.
So plz help anyone .
Thanks in advance

**Comment by JakeWharton** [comment]
A JSON string has quotes. When you tell Gson to parse the response as a `String` it must looks like this: `"content"`. If the quotes are missing because it's a raw string (like `content`) or just another JSON object like a message (`{"foo":"bar"}`) or array (`[1, 2, 3]`) Gson throws the exception.

So either you need to change your server to respond with JSON strings that are quoted properly, or you should be using [the "scalars" converter][1] which handles the `String` type by reading the response as a raw string, not a JSON string. The scalars converter is a separate dependency and it must be added to the `Retrofit.Builder` before the Gson converter so that it takes precedence.

 [1]: https://github.com/square/retrofit/tree/master/retrofit-converters/scalars

**Comment by ArslanAli7** [comment]
Hello @JakeWharton  my question is not related to this thread,but i posted my question on stackoverflow and get no response, it will be really helpful if you can help me on this one. [Retrofit post parameter of primitive type](http://stackoverflow.com/questions/39278123/post-parameter-retrofit-not-formurlencoded-without-creating-a-class-with-default)

**Comment by JakeWharton** [comment]
Use RequestBody or String + scalars converter.

**Comment by dhruvam-gupta** [comment]
Yes i have seen other converters. But i don't understand the issue that in first case it is fine while the same thing in second case is not working. In both the cases server is returning the String (just one word to test the app) then why error is raised only in second case i.e. LoginService.java not in CardService.java

**Comment by JakeWharton** [comment]
You didn't include the data being deserialized in the responses so it's
impossible to know.

**Comment by dhruvam-gupta** [comment]
@JakeWharton i have posted the code in comment above.

**Comment by JakeWharton** [comment]
Right, but the response data is what's important here, not the code.

**Comment by dhruvam-gupta** [comment]
@JakeWharton response data is:

**In 1st case:**

`response.getWriter().print("true")`

this is being printed in toast in android app

but  **In 2nd case:**

`response.getWriter().print("success")`

is not received instead error is raisedin the application

**Comment by JakeWharton** [comment]
"true" is a JSON boolean literal so Gson might be interpreting it as such
and converting it to a String automatically.

**Comment by JakeWharton** [comment]
The second case is not valid JSON so Gson throwing an exception isn't
surprising. You'd have to add double quotes inside the response to make it
a JSON string literal.

**Comment by dhruvam-gupta** [comment]
ok thanks for pointing the issue. I am going to try it

**Comment by dhruvam-gupta** [comment]
@JakeWharton Thanks!!! once again...I changed "success" to "\"success\"" and it worked..

**Comment by ArslanAli7** [comment]
@JakeWharton  i have added the ScalarsConverter under my retrofit object, my service only accepts content type equals application/json if i use something like this 
`Call<ArrayList<Object>> GetABC(
            @Body int  Id);`
 i am getting response from the service as not acceptable model this is because it accepts data of the from json and i think by using scalar factory the data content type has to be text/plain is there any possibility to send the primitive data with content type application/json with scalar converter.

**Comment by JakeWharton** [comment]
You can use the Gson converter with Gson's JsonObject class or just a Map
of string to object.

**Comment by ArslanAli7** [comment]
Okay thanks a lot,i would prefer to go with the first option as creating a hash map for a single int value comes at a hefty cost.

**Comment by JakeWharton** [comment]
JsonObject just wraps a map so you're paying either way. There's also
Collections.singletonMap which is tiny.

**Comment by ArslanAli7** [comment]
Thanks a lot mate,i would surely go with the singleton Map.
