### ISSUE TITLE
Redirect not working as expected

### ISSUE THREAD

**Issue by roybrener** [square/retrofit#2009]
I'm having issues with a get request that has Redirect. I'm getting the redirect response (text/html) instead of the intended application / json content response. The request works well Using all known browsers and rest clients.

Url for example: http://denver.moovex.net/ride.asp?userid=1&from_name=John%20F.%20Kennedy%20International%20Airport&from_lat=40.641311&from_lng=-73.778139&to_name=Madison&to_lat=43.0730517&to_lng=-89.4012302&time=1472979600000

Response when using Retrofit

    D/OkHttp: --> GET http://denver.moovex.net/ride.asp?userid=1&from_name=John%20F.%20Kennedy%20International%20Airport&from_lat=40.641311&from_lng=-73.778139&to_name=Madison&to_lat=43.0730517&to_lng=-89.4012302&time=1472979600000 HTTP/1.1
    D/OkHttp: --> END GET
    D/OkHttp: <-- 200 OK http://denver.moovex.net/setshifts.asp?  action2=ordertaxi&source=produceform&focus=1&production=0&pd1=13/12/1901%2018:45:52&pd2=13/12/1901%2022:45:52 (243ms)
    D/OkHttp: Cache-Control: private
    D/OkHttp: Content-Type: text/html
    D/OkHttp: Vary: Accept-Encoding
    D/OkHttp: Server: Microsoft-IIS/8.5
    D/OkHttp: Set-Cookie: ASPSESSIONIDAASATBDB=LIOFNKOBMGLBKFPFEICHNKCG; path=/
    D/OkHttp: X-Powered-By: ASP.NET
    D/OkHttp: Date: Sun, 04 Sep 2016 08:10:46 GMT
    D/OkHttp: OkHttp-Sent-Millis: 1472976644845
    D/OkHttp: OkHttp-Received-Millis: 1472976644981
    D/OkHttp: <html dir=ltr><head>
    D/OkHttp: <title> - setshifts</title>
    D/OkHttp:   <meta http-equiv="Content-Type" content="text/html; charset=windows-1255">
    D/OkHttp:   <meta http-equiv="Content-Language" content="he"><META HTTP-EQUIV="EXPIRES"   CONTENT="0"><META HTTP-EQUIV="CACHE-CONTROL" CONTENT="NO-CACHE, NO-STORE"><meta name="robots" content="noindex"><meta http-equiv="X-UA-Compatible" content="IE=6" /><meta name="keywords" content=""><meta name="description" content=""><link rel="stylesheet" rel="text/css" href=style.css><link rel="shortcut icon" href="moovex.ico"><style>
    D/OkHttp: </style>
    D/OkHttp: </head><script language=javascript>...

Same request from the Browser
![response_chrome](https://cloud.githubusercontent.com/assets/3992182/18229985/dcd62950-7296-11e6-8a03-5027f024de42.PNG)

Using retrofit 2.1.0

**Comment by swankjesse** [comment]
If this is a bug report, could you provide a failing test? There’s an example here:
https://gist.github.com/swankjesse/6608b4713ad80988cdc9

**Comment by roybrener** [comment]
I'm not sure i can recreate the response as a test.  I think the main issue is that the response from the server is "irregular" and involve redirect which Retrofit doesn't handle well. I've added an example:

https://gist.github.com/roybrener/fd535a05672a83ac94e62730c2c2e898

Thanks

**Comment by JakeWharton** [comment]
Retrofit doesn't handle redirects at all. That's the responsibility of the
HTTP client.

**Comment by roybrener** [comment]
So should i open the same issue at okhttp issue tracker?

**Comment by roybrener** [comment]
Also i assume that this issue arises because of a redirect because the
supplied url has a redirect chain. All other calls with this specific
server are successful and do not involve redirect.  But i can't be sure
that this is the reason
Thanks

**Comment by swankjesse** [comment]
If you like, you can configure OkHttp to not follow redirects.

**Comment by roybrener** [comment]
Yeah it's the first thing i've tried but then i'm getting a "no content response" 301 with Location header:

    Location: setshifts.asp?  action2=ordertaxi&source=produceform&focus=1&production=0&pd1=13/12/1901 18:45:52&pd2=13/12/1901 22:45:52

**Comment by swankjesse** [comment]
Please create a standalone test case that demonstrates how OkHttp or Retrofit are behaving incorrectly. So far it looks like you’re just calling the API wrong.

**Comment by roybrener** [comment]
Can you please elaborate on "just calling the api wrong"?. Is the file that
i added is incorrect in some manner?

Btw the project that im currently working on has more than 20 api rest
calls..all working perfectly..this one is the only that is not working and
it's the only one with redirect

I will be more than happy to discover that im doing something wrong and
that its not a bug (:
I will create a demo project that shows the result.

**Comment by roybrener** [comment]
Project example
[https://github.com/roybrener/retrofitbadRequest](Url)
Thanks
