### ISSUE TITLE
 java.lang.IllegalArgumentException: Method return type must not include a type variable or wildcard: retrofit2.Call<model.DataModelResponse<T>>

### ISSUE THREAD

**Issue by andishejavan** [square/retrofit#2012]
how define generic T class in interface api and rest mansger ?
api this 
```
 @GET("api/customer/")
    Call<DataModelResponse<T>> getList(@Query("take") int page, @Query("skip") int step);

```
call rest manager this 

```
mManager = new ServiceGenerator();
            Call<DataModelResponse<T>> listCall = mManager.getService().getList(ClientConfigs.PAGAE_RECYCLER, skip);

```
rest manager this 
 ```
public Api  getService() {
        return Api;
    }
```

**Comment by ly1054** [comment]
"Method return type must not include a type variable or wildcard " it seems to be clear

**Comment by JakeWharton** [comment]
You cannot. Type information needs to be fully known at runtime in order for deserialization to work.

**Comment by developer--** [comment]
would be great

**Comment by lordplagus02** [comment]
So for example, a request such as: 
```Call<T[]> call = apiService.getResources(...);``` where `T extends Resource` would not be possible? (`Resource` being a class from the [moshi-jsonapi](https://github.com/kamikat/moshi-jsonapi) library, which allows you to extend a class as a `Resource`.)
Would I then need to create a different retrofit API interface for each of these `Resources`?

Sorry to bring up old issues...

**Comment by JakeWharton** [comment]
Yes. Retrofit has no idea what type to create to fulfill that contract.

**Comment by lordplagus02** [comment]
So... If I have 6 different types of resources, I'm going to create 6 different interfaces, and this is how people have been doing it the whole time? I'm sorry I'm just not sure what the alternative is here when trying to keep my code DRY.

**Comment by shahsurajk** [comment]
@lordplagus02 
How about this, define the Call so as to return a `JsonElement` as the class type, something like this, 
`Call<JsonElement> getObjectByID();` and then parse the jsonElement yourself 

`CustomObject1 customObject1 = new Gson().fromJson(response.body().getAsJsonObject().toString(), CustomObject1.class);`

`CustomObject2 customObject2 = new Gson().fromJson(response.body().getAsJsonObject().toString(), CustomObject2.class);`

So here, the parsing dependency is upon you and not retrofit. Hope it helps. 

this way you can create just one interface for all object by ID queries, alternatively you can also add query map to add additional options and set null if not required.

**Comment by LessTalk** [comment]
oh This will be very troublesome

**Comment by shahsurajk** [comment]
You can create these methods once and then you're done. A utility sort of thing

**Comment by khushbu-shah** [comment]
yes It will work but May I have some more in explanation if possible with example with 2 or more service call 
Thank you

**Comment by emanuelthedude** [comment]
I get this error because of proguard. In my interface I had a function that was not used anymore. Also the class of the return type was not used anymore in the project. I think proguard removed the return type class and made the return type of the function Call<Any> or Call<?>. The result was the same IllegalArgumentException as soon as the first http call started.

**Comment by morder** [comment]
It needs to fix proguard rules

**Comment by antonio195** [comment]
It has worked for me using Kotlin. But is this the best way to do this? Doesn't this generic form bring problems with memory leaks?

![retrofit2](https://user-images.githubusercontent.com/53958269/235799507-333af9fe-e309-4558-ba7d-7317217a0790.png)
![retrofit](https://user-images.githubusercontent.com/53958269/235800027-8df4a223-6732-4d96-941c-c90a78b8c1a8.png)
