### ISSUE TITLE
sendto failed: EPIPE (Broken pipe)

### ISSUE THREAD

**Issue by lianyuchen** [square/retrofit#2013]
when I use @Multipart @POST to upload file,the log show that:
09-07 10:41:14.388 6782-6838/com.demo.lianyuchen.retrofitstudy I/OpenGLRenderer: Initialized EGL, version 1.4
09-07 10:41:14.434 6782-6838/com.demo.lianyuchen.retrofitstudy W/MALI: glDrawArrays:714: [MALI] glDrawArrays takes more than 5ms here. Total elapse time(us): 11334
09-07 10:41:50.283 6782-6782/com.demo.lianyuchen.retrofitstudy I/Instrumentation: [AppLaunch] activity.onStart +
09-07 10:41:50.283 6782-6782/com.demo.lianyuchen.retrofitstudy I/Instrumentation: [AppLaunch] activity.onStart -
09-07 10:41:50.283 6782-6782/com.demo.lianyuchen.retrofitstudy I/Instrumentation: [AppLaunch] activity.onResume +
09-07 10:41:50.284 6782-6782/com.demo.lianyuchen.retrofitstudy I/SettingsInterface: call-query of user -3 by 0 so not updating cache
09-07 10:41:50.284 6782-6782/com.demo.lianyuchen.retrofitstudy I/Instrumentation: [AppLaunch] activity.onResume -
09-07 10:41:50.309 6782-7375/com.demo.lianyuchen.retrofitstudy I/System.out: [CDS][DNS] getAllByNameImpl netId = 0
09-07 10:41:50.316 6782-7375/com.demo.lianyuchen.retrofitstudy I/System.out: [CDS]rx timeout:10000
09-07 10:41:50.317 6782-7375/com.demo.lianyuchen.retrofitstudy I/System.out: [socket][0] connection /10.253.10.178:8080;LocalPort=48795(10000)
09-07 10:41:50.317 6782-7375/com.demo.lianyuchen.retrofitstudy I/System.out: [CDS]connect[/10.253.10.178:8080] tm:10
09-07 10:41:50.328 6782-7375/com.demo.lianyuchen.retrofitstudy I/System.out: [socket][/10.253.102.126:48795] connected
09-07 10:41:50.336 6782-7375/com.demo.lianyuchen.retrofitstudy I/System.out: [CDS]rx timeout:10000
09-07 10:41:51.812 6782-7375/com.demo.lianyuchen.retrofitstudy I/System.out: [CDS]write is:160/8192
09-07 10:41:51.812 6782-7375/com.demo.lianyuchen.retrofitstudy I/System.out: [CDS]write exceptionCount:0
09-07 10:41:51.816 6782-7375/com.demo.lianyuchen.retrofitstudy I/System.out: [CDS]close[48795]
09-07 10:41:51.820 6782-6782/com.demo.lianyuchen.retrofitstudy E/MainActivity: sendto failed: EPIPE (Broken pipe)

I want to know How to solve this?

I try it again by follow:'https://futurestud.io/blog/retrofit-2-how-to-upload-files-to-server',but it doesn't work.

**Comment by jjhesk** [comment]
I have experienced the same issue. when 6.4MB of image file performed on retrofit shocket. Now using 
RETROFIT LIBRARY=2.1.0
OKHTTP LIBRARY=3.3.1

**Comment by 237345339** [comment]
i alse have this problem ,so how can i do in retrofit2 ?

**Comment by softboy99** [comment]
i also have this problem
