### ISSUE TITLE
[Question] Retrofit exception handling with ReactiveX Java

### ISSUE THREAD

**Issue by jollyjoker992** [square/retrofit#2014]
I am using retrofit with ReactiveX Java to implement my application. As I know, Retrofit will throws exception when a network error has occurred (ex : server internal error, server not found or no internet connection...) but when server error is 502 Bad Gateway, Retrofit does not throw any exceptions. So, can you give me all network error cases that retrofit does not throw any exceptions? Thank you so much!

**Comment by JakeWharton** [comment]
> As I know, Retrofit will throws exception when a network error has occurred (ex : server internal error, server not found or no internet connection...) but when server error is 502 Bad Gateway, Retrofit does not throw any exceptions

This is not correct. All non-200 responses are treated the same as an unsuccessful response.

If you specify `Observable<Response<T>>` then all non-200 responses will be passed to `onNext` as unsuccessful responses. If you specify `Observable<T>` then all non-200 response will be passed to `onError` as `HttpException`s.

**Comment by jollyjoker992** [comment]
Yes, thank you so much. I have understood.

**Comment by jollyjoker992** [comment]
Sorry @JakeWharton because I forgot ask you how to get Exception when I specified `Observable<Response<T>>` ?? Thank you so much.

**Comment by JakeWharton** [comment]
Whenever the network fails in some way which prevents a response from being
read.
