### ISSUE TITLE
Could not find class 'retrofit2.Retrofit$Builder'

### ISSUE THREAD

**Issue by hellosad** [square/retrofit#2022]
gradle like this:
    compile 'com.squareup.retrofit2:retrofit:2.1.0'
    compile 'com.squareup.retrofit2:converter-gson:2.1.0'

  but crash by "Could not find class 'retrofit2.Retrofit$Builder'" after installed

**Comment by JakeWharton** [comment]
This is a problem with your build configuration, not Retrofit. The `Retrofit.Builder` class is definitely present inside the jar, so something in your build is causing it to be removed or not found. Best guess would be that you're using multidex but not configuring it properly.
