### ISSUE TITLE
had an error about HTTP 414.....

### ISSUE THREAD

**Issue by Microhx** [square/retrofit#2026]
` W/System.err: retrofit2.adapter.rxjava.HttpException: HTTP 414 Request-URI Too Large
 W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$SimpleCallAdapter$1.call(RxJavaCallAdapterFactory.java:163)
 W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$SimpleCallAdapter$1.call(RxJavaCallAdapterFactory.java:158)
 W/System.err:     at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
 W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:113)
 W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:92)
 W/System.err:     at rx.Observable$2.call(Observable.java:162)
 W/System.err:     at rx.Observable$2.call(Observable.java:154)
 W/System.err:     at rx.Observable$2.call(Observable.java:162)
 W/System.err:     at rx.Observable$2.call(Observable.java:154)
 W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:8098)
 W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
 W/System.err:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
 W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
 W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
 W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
 W/System.err:     at java.lang.Thread.run(Thread.java:818)`

the source :+1: 
`  @POST(Constant.BASE_ACTION)
    @Multipart
    Call<ResponseBody> uploadUserInfoTest(@QueryMap Map<String,String> options,
                                      @PartMap Map<String, RequestBody> externalFileParameters) ;`
I had used the POST method , there is no limited request length in theory, but I don't kown why .....

**Comment by JakeWharton** [comment]
This isn't a Retrofit problem. The server doesn't like the length of the URL of your request. Consult your server engineers or API documentation as to their maximum length.

**Comment by Microhx** [comment]
ohhhhhhhhhhhhhhhh, thanks.... @JakeWharton

**Comment by RushiMThakker** [comment]
But @JakeWharton  It works well with postman and simple HttpUrlConnection method

**Comment by MarcusPetri** [comment]
@JakeWharton its not a server problem, I got the same error, if I try the URI in another program, it return success...

@Microhx you found a solution?

**Comment by MarcusPetri** [comment]
@JakeWharton I configured my server side, the request stopped returning the 414 error, but now I got "stream was reset: CANCEL". If I decrease the size of the url, it works again!

Like @RushiMThakker, I can run the same request in a rest client!

Any ideas?

**Comment by gabriel-TheCode** [comment]
> But @JakeWharton It works well with postman and simple HttpUrlConnection method

I have the same problem. My server (WebLogic) already have the max size of post request.

**Comment by tribbianiwang** [comment]
Try Use @FormUrlEncoded in retrofit and @POST() and send the data using @Field("data") annotation. work for me
