### ISSUE TITLE
[Feature Request] Error message for "unable to create converter..." should explain why

### ISSUE THREAD

**Issue by ZakTaccardi** [square/retrofit#2027]
Scenario:

I have a `Branding` class, which has a field `Colors` class.  Retrofit knows how to convert every field on `Branding` except `Colors`.

Actual Error:
`Unable to create converter for class Branding`

Desired Error:
`Unable to create converter for class Branding due to Colors not being convertible`

Why?:
If you have a very complex `Branding` class, debuging which class cannot be converted within it can be time consuming. Would be nice to be pointed to the right direction right away.

Note -> I'm using the AutoValue moshi extension, not sure if that's a factor here.

**Comment by JakeWharton** [comment]
Actually Retrofit doesn't know anything about `Branding` except that it exists. It blindly asks each converter to handle that type.

The exception cause should point you in the right direction and if not then that's a feature request for whichever serialization library you are using.
