### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Could not locate call adapter for io.reactivex.Observable

### ISSUE THREAD

**Issue by raghunandankavi2010** [square/retrofit#2028]
My application was not building due to duplicates files in .apk as mentioned here

https://github.com/ReactiveX/RxJava/issues/4445

So adding this

     packagingOptions {
        exclude 'META-INF/rxjava.properties'
    }

did not cause the problem again., but a new issue cropped up

     Caused by: java.lang.IllegalArgumentException: Could not locate calladapter for 
    io.reactivex.Observable<myModelclass>.
                                    Tried:
                                     * retrofit2.adapter.rxjava.RxJavaCallAdapterFactory
                                     * retrofit2.ExecutorCallAdapterFactory
                                    ....

I do have

    @Headers({"Content-Type: application/json;charset=UTF-8"})
    @GET(Constants.FETCH_FEED)
    Observable<FeedResponse> fetch_Feed();

And then

      Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(Constants.BASE_URL)
                .addConverterFactory(GsonConverterFactory.create())
                .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                .build();
       Observable<myModelclass> response = retrofit.create(Api.class).fetch_Feed();

My build.gradle file

     compile 'com.squareup.okhttp3:okhttp:3.4.1'
     compile 'com.squareup.retrofit2:retrofit:2.1.0'
     compile 'io.reactivex.rxjava2:rxjava:2.0.0-RC3'
     compile 'io.reactivex.rxjava2:rxandroid:2.0.0-RC1'
     compile 'com.squareup.retrofit2:converter-gson:2.1.0'
     compile 'com.squareup.retrofit2:adapter-rxjava:2.1.0'

This could be related to RxJava2. This is not reproducible with version1.  In which case issue should be opened in RxJava and this issue closed.

**Comment by JakeWharton** [comment]
You need to use https://github.com/JakeWharton/retrofit2-rxjava2-adapter
for RxJava 2 not the built in adapter which only handles RxJava 1.

**Comment by raghunandankavi2010** [comment]
Thank you. I missed that.

**Comment by LongNguyen-51101909** [comment]
Thanks you

**Comment by KDisEDDY** [comment]
kiang kiang kiang

**Comment by effectivecui** [comment]
New Solution：

https://github.com/square/retrofit/tree/master/retrofit-adapters/rxjava2

**Comment by youyutongxue** [comment]
Thanks you

**Comment by fuchangle** [comment]
thanks
