### ISSUE TITLE
转换器went

### ISSUE THREAD

**Issue by passwhl** [square/retrofit#2029]
![image](https://cloud.githubusercontent.com/assets/12857123/18859256/05520adc-84a5-11e6-825f-24f18a3e942d.png)
![image](https://cloud.githubusercontent.com/assets/12857123/18859266/2bb37922-84a5-11e6-9072-5a94fcd7eac3.png)
为什么进响应转换，不进请求转换

**Comment by passwhl** [comment]
perform  responseBodyConverter function
Does not perform requestBodyConverter function，why?

**Comment by swankjesse** [comment]
Please use StackOverflow with the “retrofit” tag for usage questions.
