### ISSUE TITLE
IllegalStateException  while uploading image using multipart

### ISSUE THREAD

**Issue by dheerajgrover** [square/retrofit#2030]
I am getiing IllegalStateException   while uploading image in multipart
Following is the stacktrace:

okio.RealBufferedSink.write( RealBufferedSink.java : 44 )
okio.ForwardingSink.write( ForwardingSink.java : 35 )
CountingRequestBody $1.write( CountingRequestBody .java : 54 )
CountingRequestBody .writeTo( CountingRequestBody .java : 43 )
okio.RealBufferedSink.emitCompleteSegments( RealBufferedSink.java : 176 )
okio.RealBufferedSink.writeAll( RealBufferedSink.java : 104 )
com.squareup.okhttp.RequestBody$3.writeTo( RequestBody.java : 118 )
com.squareup.okhttp.MultipartBuilder$MultipartRequestBody.writeOrCountBytes( MultipartBuilder.java : 277 )
com.squareup.okhttp.MultipartBuilder$MultipartRequestBody.writeTo( MultipartBuilder.java : 297 )
com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed( HttpEngine.java : 887 )
com.squareup.okhttp.internal.http.HttpEngine.readResponse( HttpEngine.java : 749 )
com.squareup.okhttp.Call.getResponse( Call.java : 268 )
com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed( Call.java : 224 )
com.squareup.okhttp.Call.getResponseWithInterceptorChain( Call.java : 195 )
com.squareup.okhttp.Call.access$100( Call.java : 34 )
com.squareup.okhttp.Call$AsyncCall.execute( Call.java : 162 )
com.squareup.okhttp.internal.NamedRunnable.run( NamedRunnable.java : 33 )
java.util.concurrent.ThreadPoolExecutor.runWorker( ThreadPoolExecutor.java : 1112 )
java.util.concurrent.ThreadPoolExecutor$Worker.run( ThreadPoolExecutor.java : 587 )
java.lang.Thread.run( Thread.java : 818 )

crash report says:
App Crashed with Exception: java.lang.IllegalStateException at: class: okio.RealBufferedSink method: write file: RealBufferedSink.java line: 

We are using following  code to track progress but could not find where the stream is being closed.

public class CountingRequestBody extends RequestBody {

```
protected RequestBody delegate;
protected Listener listener;

protected CountingSink countingSink;

public CountingRequestBody(RequestBody delegate, Listener listener) {
    this.delegate = delegate;
    this.listener = listener;
}

@Override
public MediaType contentType() {
    return delegate.contentType();
}

@Override
public long contentLength() {
    return delegate.contentLength();
}

@Override
public void writeTo(BufferedSink sink) throws IOException {
    BufferedSink bufferedSink;

    countingSink = new CountingSink(sink);
    bufferedSink = Okio.buffer(countingSink);

    delegate.writeTo(bufferedSink);

    bufferedSink.flush();
}

protected final class CountingSink extends ForwardingSink {

    private long bytesWritten = 0;

    public CountingSink(Sink delegate) {
        super(delegate);
    }

    @Override
    public void write(Buffer source, long byteCount) throws IOException {
        super.write(source, byteCount);

        bytesWritten += byteCount;
        listener.onRequestProgress(bytesWritten, contentLength());
    }

}

public static interface Listener {

    public void onRequestProgress(long bytesWritten, long contentLength);

}
```

}

**Comment by JakeWharton** [comment]
You've truncated the actual message from the exception so it's hard to know the problem. Can you write a test case that demonstrates the problem?

**Comment by Suhinin** [comment]
I tried use this method to show uploading progress. But I have not file, I post file as long string. This code return always 100% progress one time. Help me please.
`    public Observable<DownloadProgress> apiUploadFile (final String sessionKey, final String profileId, final String encodedData) {
        return Observable.create(new Observable.OnSubscribe<DownloadProgress>() {
            @Override
            public void call (final Subscriber<? super DownloadProgress> subscriber) {

                FileApi fileApi = ApiFactory.createRetrofitService(FileApi.class, new ProgressListener() {
                    @Override
                    public void update (long bytesRead, long contentLength) {
                        long percent = (100 * bytesRead) / contentLength;
                        subscriber.onNext(new DownloadProgress((int) percent));
                    }
                }, false);

                RequestBody sessionKeyBody = RequestBody.create(MediaType.parse("multipart/form-data"), sessionKey);
                RequestBody profileIdBody = RequestBody.create(MediaType.parse("multipart/form-data"), profileId);
                RequestBody encodedDataBody = RequestBody.create(MediaType.parse("multipart/form-data"), encodedData);

                Map<String, RequestBody> map = new HashMap<>();
                map.put(ApiConst.SESSION_KEY, sessionKeyBody);
                map.put(ApiConst.PROFILE_ID, profileIdBody);
                map.put(ApiConst.ENCODED_DATA, encodedDataBody);

                fileApi.add(map).enqueue(new Callback<JsonObject>() {
                    @Override
                    public void onResponse (Call<JsonObject> call, Response<JsonObject> callResponse) {
                        if (callResponse.isSuccessful() == true) {
                            JsonObject jsonObject = callResponse.body();
                            boolean result = jsonObject.get(ApiConst.RESULT).getAsBoolean();
                            if (result == true) {
                                JsonObject response = jsonObject.getAsJsonObject(ApiConst.RESPONSE);

                                String url = response.get(ApiConst.URL).getAsString();
                                subscriber.onNext(new DownloadProgress(url));
                                subscriber.onCompleted();
                            } else {
                                subscriber.onError(new RuntimeException(jsonObject.get(ApiConst.RESPONSE).getAsString()));
                            }
                        } else {
                            subscriber.onError(new RuntimeException("server contact failed"));
                        }
                    }

                    @Override
                    public void onFailure (Call<JsonObject> call, Throwable throwable) {
                        subscriber.onError(throwable);
                    }
                });
            }
        });
    }`

and retrofit service:
`    @Multipart
    @POST (FILE_ADD)
    Call<JsonObject> add (@PartMap Map<String, RequestBody> params);`

and also added interceptor:
`        Interceptor uploadInterceptor = new Interceptor() {
            @Override
            public Response intercept (Chain chain) throws IOException {
                Request originalRequest = chain.request();

                if (originalRequest.body() == null) {
                    return chain.proceed(originalRequest);
                } else {
                    Request progressRequest = originalRequest.newBuilder()
                            .method(originalRequest.method(), new ProgressRequestBody(originalRequest.body(), progressListener))
                            .build();

                    return chain.proceed(progressRequest);
                }
            }
        };`

**Comment by lww2626** [comment]
i alse have this problem, it happens when  posting file  401

**Comment by JakeWharton** [comment]
My best guess is that you're writing after calling `close()` which is the only `IllegalStateException` that `RealBufferedSink` throws. Without a test case that reproduces the failure it's hard to imagine that Retrofit is the cause here, especially seeing that it's nowhere in the stacktrace of the exception.
