### ISSUE TITLE
I am trying cache offline using retrofit2 and okhttp3 , i am using interceptor when i try to put GET request the cache is working properly with no issue but when i put POST request it shows 504 unsatisfiable only-if-cached 

### ISSUE THREAD

**Issue by abumoallim** [square/retrofit#2033]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by swankjesse** [comment]
That’s working as designed. OkHttp’s cache follows HTTP caching semantics.

**Comment by abumoallim** [comment]
Can u help me how to do it ? i have tried everything but not working. i just want to know how to cache POST request in retrofit

**Comment by ikkyu0319** [comment]
I have the question too ！！help~

**Comment by litianyuan1111** [comment]
retrofit2.adapter.rxjava.HttpException: HTTP 504 Unsatisfiable Request (only-if-cached)
01-01 12:01:36.415 1598-1598/com.yuantu.inpatientdpt W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$SimpleCallAdapter$1.call(RxJavaCallAdapterFactory.java:204)
01-01 12:01:36.416 1598-1598/com.yuantu.inpatientdpt W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$SimpleCallAdapter$1.call(RxJavaCallAdapterFactory.java:199)
01-01 12:01:36.416 1598-1598/com.yuantu.inpatientdpt W/System.err:     at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
01-01 12:01:36.416 1598-1598/com.yuantu.inpatientdpt W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:146)
01-01 12:01:36.416 1598-1598/com.yuantu.inpatientdpt W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:125)
01-01 12:01:36.416 1598-1598/com.yuantu.inpatientdpt W/System.err:     at rx.Observable$2.call(Observable.java:162)
01-01 12:01:36.416 1598-1598/com.yuantu.inpatientdpt W/System.err:     at rx.Observable$2.call(Observable.java:154)
01-01 12:01:36.416 1598-1598/com.yuantu.inpatientdpt W/System.err:     at rx.Observable$2.call(Observable.java:162)
01-01 12:01:36.416 1598-1598/com.yuantu.inpatientdpt W/System.err:     at rx.Observable$2.call(Observable.java:154)
01-01 12:01:36.416 1598-1598/com.yuantu.inpatientdpt W/System.err:     at rx.Observable$2.call(Observable.java:162)
01-01 12:01:36.416 1598-1598/com.yuantu.inpatientdpt W/System.err:     at rx.Observable$2.call(Observable.java:154)
01-01 12:01:36.416 1598-1598/com.yuantu.inpatientdpt W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:8314)
01-01 12:01:36.416 1598-1598/com.yuantu.inpatientdpt W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
01-01 12:01:36.416 1598-1598/com.yuantu.inpatientdpt W/System.err:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
01-01 12:01:36.416 1598-1598/com.yuantu.inpatientdpt W/System.err:     at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:98)
01-01 12:01:36.416 1598-1598/com.yuantu.inpatientdpt W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-01 12:01:36.416 1598-1598/com.yuantu.inpatientdpt W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-01 12:01:36.416 1598-1598/com.yuantu.inpatientdpt W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by litianyuan1111** [comment]
this is my log,i don`t kown  why that question,the api have test is  ok

**Comment by sujithTSR** [comment]
ReOpen the issue. 
even I am stuck with this problem.
