### ISSUE TITLE
Support for RxJava 1.2

### ISSUE THREAD

**Issue by cosminstefanxp** [square/retrofit#2034]
Recently, RxJava 1.2.0 has been released and they've made some backward-incompatible changes related to Completables, specifically:
- `CompletableSubscriber` -> `rx.CompletableSubscriber`
- `CompletableOnSubscribe` -> `rx.Completable.OnSubscribe`

After upgrading to it, I'm getting the following gradle build issues related to Retrofit:
```
Warning:retrofit2.adapter.rxjava.CompletableHelper$CompletableCallOnSubscribe: can't find superclass or interface rx.Completable$CompletableOnSubscribe
Warning:retrofit2.adapter.rxjava.CompletableHelper$CompletableCallAdapter: can't find referenced method 'rx.Completable create(rx.Completable$CompletableOnSubscribe)' in program class rx.Completable
Warning:retrofit2.adapter.rxjava.CompletableHelper$CompletableCallAdapter: can't find referenced class rx.Completable$CompletableOnSubscribe
Warning:retrofit2.adapter.rxjava.CompletableHelper$CompletableCallOnSubscribe: can't find referenced class rx.Completable$CompletableSubscriber
Warning:retrofit2.adapter.rxjava.CompletableHelper$CompletableCallOnSubscribe: can't find referenced class rx.Completable$CompletableOnSubscribe
Warning:retrofit2.adapter.rxjava.CompletableHelper$CompletableCallOnSubscribe: can't find referenced class rx.Completable$CompletableSubscriber
Warning:retrofit2.adapter.rxjava.CompletableHelper$CompletableCallOnSubscribe$1: can't find referenced class rx.Completable$CompletableSubscriber
```

**Comment by vanniktech** [comment]
#2024

**Comment by cosminstefanxp** [comment]
Great, thanks. Any info re. when it will be included in a release?

**Comment by JakeWharton** [comment]
It will be in the next release but no there's no timeframe. "Soon" is the
best we have. You can use the snapshot for now.

**Comment by JakeWharton** [comment]
Those warnings are safe to ignore.

**Comment by cosminstefanxp** [comment]
Thanks

**Comment by Pitel** [comment]
How to ignore them? I added `-dontwarn rx.Completable.**` to my ProGuard rules, but I still get these warnings.

**Comment by JakeWharton** [comment]
Suppress the Retrofit class, not the Rx class.

**Comment by Pitel** [comment]
`-dontwarn rx.Completable**` (no dot!)

**Comment by PaulWoitaschek** [comment]
It would be great to have a release soon. My app just failed with a runtime crash because one of my dependencies updated its RxJava. So I had to spend some time figuring out how to resolve this.

```groovy
configurations.all {
    resolutionStrategy.force "io.reactivex:rxjava:$vRxJava"
}
```

**Comment by baudm** [comment]
As per Jake's comment, the ProGuard rule should be:
`-dontwarn retrofit2.adapter.rxjava.CompletableHelper$**`
