### ISSUE TITLE
Parsing XML (encoding ISO-8859-1) with Retrofit2 and SimpleXmlConverter doesn't show correct characters

### ISSUE THREAD

**Issue by JaviChaques** [square/retrofit#2041]
I am using Retrofit2 and SimpleXML converter in Android. When parsing XML file which is encoded in ISO-8859-1 (I don't have any control over server) special characters (ó, á) are not displayed correctly. Project and everything else uses UTF-8 encoding. The main Retrofit2 code looks like this (with logger and interceptor for testing)

`private static OkHttpClient.Builder httpClient = new OkHttpClient.Builder();
    private static Retrofit.Builder sBuilder = new Retrofit.Builder()
            .baseUrl(BASE_URL)
            .addConverterFactory(SimpleXmlConverterFactory.create());

```
public static <S> S createService (Class<S> serviceClass){

    HttpLoggingInterceptor logging = new HttpLoggingInterceptor();
    logging.setLevel(HttpLoggingInterceptor.Level.BODY);
    httpClient.addInterceptor(logging);


    httpClient.addInterceptor(new Interceptor() {
        @Override
        public Response intercept(Chain chain) throws IOException {
            Request request = chain.request()
                    .newBuilder()
                    .addHeader("Content-Encoding","UTF-8")
                    .build();
            return chain.proceed(request);
        }
    });

    Retrofit retrofit = sBuilder
            .client(httpClient.build())
            .build();
    return retrofit.create(serviceClass);`
```

When looking in the logs I can see that parsed XML is already with broken special characters. I have also tried to encode from ISO-8859-1 to UTF-8 like this:

```
private String changeCharsetEncoding(String curString) {
        Charset iso88591 = Charset.forName("ISO-8859-1");
        Charset utf8 = Charset.forName("UTF-8");

        CharBuffer curBuffer = iso88591.decode(ByteBuffer.wrap(curString.getBytes()));
        ByteBuffer outputBuffer = utf8.encode(curBuffer);

        return new String(outputBuffer.array(), utf8);
    }
```

But it's seems that parsed XML is already broken and there is no way how convert it to UTF-8. I have also tried to change Android Studio settings -> File Encoding to ISO-8859-1 but nothing works. How to correctly parse this XML to show special characters? Is this error because of SimpleXML parser or other reasons?

**Comment by JakeWharton** [comment]
Can you provide a test case that fails? There's ones already in the SimpleXML converter that show how to do it.

**Comment by ylfzq** [comment]
I'm afraid that your http body was not decoded by ISO-8859-1. I haven't read the source of SimpleXmlConverterFactory, but I've read GsonConverterFactory's, which will use underlying okhttp 3 to decode byte array into string. okhttp 3 will check the header (e.g. Content-Type) to infer the codec/charset name, if can't, it will use UTF-8.

code snippet in okhttp3/ResponseBody.java
```java
  /**
   * Returns the response as a string decoded with the charset of the Content-Type header. If that
   * header is either absent or lacks a charset, this will attempt to decode the response body as
   * UTF-8.
   */
  public final String string() throws IOException {
    return new String(bytes(), charset().name());
  }

  private Charset charset() {
    MediaType contentType = contentType();
    return contentType != null ? contentType.charset(UTF_8) : UTF_8;
  }
```

So, I guess your http response is lack of charset, caused to use UTF-8 as default.

**Comment by JakeWharton** [comment]
No action to take without a test case.
