### ISSUE TITLE
Problem with UTF-8 Encode in retrofit2

### ISSUE THREAD

**Issue by graymind75** [square/retrofit#2042]
Hi everybody
i have a problem with sending information to server and store in mysql database

its my interface for send information :

`@FormUrlEncoded`
`@POST("mypage.php")`
`Call<ResponseBody> sending(@Field(value = "conname",encoded=true) String contname
            , @Field(value = "connum",encoded = true) String contnum);`

so im send information and save in database like `?????`

my language is persian and support with utf-8

where is problem?what i have to do?
please help me 
thanks for great lib :X

**Comment by graymind75** [comment]
any body cant help me?

**Comment by JakeWharton** [comment]
Can you describe your problem in a failing test case? I fail to see how Retrofit is doing anything here that could be at fault.

**Comment by graymind75** [comment]
thats my send code in mainactivity

`Retrofit retrofit=new Retrofit.Builder().baseUrl("http://graber.twomini.com/")`
               ` .addConverterFactory(GsonConverterFactory.create())`
               ` .build();`
     `   SendInterface  registerInterface=retrofit.create(SendInterface.class);`
     `  Call<ResponseBody> call=registerInterface.contact(contname,contnum);`
       ` call.enqueue(new Callback<ResponseBody>() {`
         `   @Override`
          `  public void onResponse(Call<ResponseBody> call, Response<ResponseBody> `
           ` }`
        `   @Override`
       `     public void onFailure(Call<ResponseBody> call, Throwable t) {`
       `     }`
       ` });`

and thats my sendinterface

`public interface SendInterface {`
  `  @FormUrlEncoded`
   ` @POST("contact.php")`
   ` Call<ResponseBody> contact(@Field(value = "conname",encoded=true) String contname`
       `     , @Field(value = "connum",encoded = true) String `
`}`

![result](https://cloud.githubusercontent.com/assets/22690689/19319053/ef63b3c8-90b7-11e6-9252-cd021672b716.jpg)

**Comment by graymind75** [comment]
Pleeeeeeeease Help me thats very important to me! please:(

**Comment by FabianTerhorst** [comment]
Thats not related to this library.

**Comment by graymind75** [comment]
@FabianTerhorst 
so where is the problem?
please help me very important ...

**Comment by FabianTerhorst** [comment]
Your database doesn't contain the correct symbols.

**Comment by graymind75** [comment]
@FabianTerhorst 
im test in 2 server but still result ??? :(

**Comment by FabianTerhorst** [comment]
what is the http result when you just use okhttp?
