### ISSUE TITLE
how to send post request with raw string like [this](https://cloud.githubusercontent.com/assets/9336436/19213896/6fee42f6-8d7f-11e6-87e8-0ada0a4bd27f.png)

### ISSUE THREAD

**Issue by dimmitriy** [square/retrofit#2044]
how to send post request with raw string like [this](https://cloud.githubusercontent.com/assets/9336436/19213896/6fee42f6-8d7f-11e6-87e8-0ada0a4bd27f.png)

**Comment by a1018875550** [comment]
have you google first?

**Comment by dimmitriy** [comment]
What do you mean about google first?
I have already an answer - 
 MethodsService methodsService = retrofit.create(MethodsService.class);
        String strRequestBody = "{" +
                "\"imei\" : \"" + imei + "\"," +
                "\"login\" : \"" + login + "\"," +
                "\"password\" : \"" + password + "\"" +
                "}";
        RequestBody requestBody = RequestBody.create(MediaType.parse("text/plain"),strRequestBody);
        Call<LoginResponse> call = methodsService.authentication(requestBody);
        call.enqueue(callback);

**Comment by swankjesse** [comment]
Please use StackOverflow for usage questions.
