### ISSUE TITLE
multipart and other params together

### ISSUE THREAD

**Issue by pmbfish40** [square/retrofit#2047]
My API documentation required that I send data with this JSON format

{
    "title": "title",
    "file": "uploaded file instance",
    "location": {
        "lat": 48.8583,
        "lng": 2.29232,
        "place": "Eiffel Tower"
    }
}

How could create Multipart and Body or RequestBody to send data server like shown in that JSON

**Comment by swankjesse** [comment]
Please use StackOverflow for usage questions.
