### ISSUE TITLE
RxJavaCallAdapterFactory and HTTP requests cancellation

### ISSUE THREAD

**Issue by ming13** [square/retrofit#2048]
The d6666438ea50137df49957d25e62639b86b59197 commit changed `RxJavaCallAdapterFactory` internals to work with `Observable.fromCallable` instead of custom `OnSubscribe`. It greatly simplifies the implementation, but it seems like it omits such important thing as HTTP request cancellation.

The previous implementation called `retrofit2.Call.cancel` which in its turn called `okhttp3.Call.cancel` under the hood. As the `retrofit2.Call.cancel` documentation states `Cancel this call. An attempt will be made to cancel in-flight calls, and if the call has not yet been executed it never will be`. It seems like the `Observable.fromCallable` covers the second part about never executing the request if it wasn’t already, but misses the in-flight call situation. Was this change intentional? As far as I understand OkHttp reacts on `okhttp3.Call.cancel` by closing a connection socket which is actually a great thing.

**Comment by JakeWharton** [comment]
I don't recall my thought process at the time, but I thought I might have
tested that thread interrupts were going to be Good Enough™. I'm happy to
switch back until fromEmitter becomes stable API though. It's just annoying
having to use these low-level primitives where so much can go wrong because
you are responsible for so much!

**Comment by jasonsparc** [comment]
Not sure if thread interrupts are guaranteed everywhere though but I did peeked under the hood and I guess thread interrupts are guaranteed, at least to every standard implementation of `rx.Scheduler` that uses `ScheduledAction`:

https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/internal/schedulers/ScheduledAction.java#L140

Even `RxAndroid` uses `ScheduledAction`, so no problem with that.

I guess a little comment or note might have been helpful to those wandering strangers peeking under the hood ;)

However, what if someone used a custom `Scheduler`? That might be a problem but not a major thing I guess.

**Comment by ming13** [comment]
@jasonsparc Closing a socket on unsubscription is not equal to interrupting a thread. So that’s not the point Jake and I were talking about ;-)

Anyway, @JakeWharton, should I prepare a PR with `fromCallable` → `fromEmitter` migration? Or you are working on it already, maybe as part as RxJava 2 migration?

**Comment by JakeWharton** [comment]
fromEmitter isn't a stable API
