### ISSUE TITLE
RxJava onError() method called indefinite times.

### ISSUE THREAD

**Issue by shivamsingh** [square/retrofit#2053]
10-19 17:28:35.016 4372-4372/com.example.test1 W/System.err: java.net.ConnectException: Failed to connect to /52.11.239.143:80
    10-19 17:28:35.016 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:189)
    10-19 17:28:35.016 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:173)
    10-19 17:28:35.016 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
    10-19 17:28:35.016 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
    10-19 17:28:35.016 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
    10-19 17:28:35.016 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
    10-19 17:28:35.017 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
    10-19 17:28:35.017 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    10-19 17:28:35.017 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    10-19 17:28:35.017 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
    10-19 17:28:35.017 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    10-19 17:28:35.017 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    10-19 17:28:35.017 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
    10-19 17:28:35.017 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    10-19 17:28:35.017 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
    10-19 17:28:35.017 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    10-19 17:28:35.017 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    10-19 17:28:35.017 4372-4372/com.example.test1 W/System.err:     at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
    10-19 17:28:35.017 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    10-19 17:28:35.017 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    10-19 17:28:35.017 4372-4372/com.example.test1 W/System.err:     at com.example.test1.network.AuthInterceptor.intercept(AuthInterceptor.java:25)
    10-19 17:28:35.017 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    10-19 17:28:35.017 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    10-19 17:28:35.018 4372-4372/com.example.test1 W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
    10-19 17:28:35.018 4372-4372/com.example.test1 W/System.err:     at okhttp3.RealCall.execute(RealCall.java:60)
    10-19 17:28:35.018 4372-4372/com.example.test1 W/System.err:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
    10-19 17:28:35.018 4372-4372/com.example.test1 W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171)
    10-19 17:28:35.018 4372-4372/com.example.test1 W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
    10-19 17:28:35.018 4372-4372/com.example.test1 W/System.err:     at rx.Subscriber.setProducer(Subscriber.java:211)
    10-19 17:28:35.018 4372-4372/com.example.test1 W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
    10-19 17:28:35.018 4372-4372/com.example.test1 W/System.err:     at rx.Subscriber.setProducer(Subscriber.java:205)
    10-19 17:28:35.018 4372-4372/com.example.test1 W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
    10-19 17:28:35.018 4372-4372/com.example.test1 W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
    10-19 17:28:35.018 4372-4372/com.example.test1 W/System.err:     at rx.Observable$2.call(Observable.java:162)
    10-19 17:28:35.018 4372-4372/com.example.test1 W/System.err:     at rx.Observable$2.call(Observable.java:154)
    10-19 17:28:35.018 4372-4372/com.example.test1 W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:8314)
    10-19 17:28:35.018 4372-4372/com.example.test1 W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
    10-19 17:28:35.018 4372-4372/com.example.test1 W/System.err:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
    10-19 17:28:35.018 4372-4372/com.example.test1 W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
    10-19 17:28:35.019 4372-4372/com.example.test1 W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    10-19 17:28:35.019 4372-4372/com.example.test1 W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
    10-19 17:28:35.019 4372-4372/com.example.test1 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    10-19 17:28:35.019 4372-4372/com.example.test1 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    10-19 17:28:35.019 4372-4372/com.example.test1 W/System.err:     at java.lang.Thread.run(Thread.java:818)
    10-19 17:28:35.033 4372-4372/com.example.test1 D/BaseActivity: error : Failed to connect to /52.11.239.143:80
    10-19 17:28:35.033 4372-4372/com.example.test1 W/System.err: java.net.ConnectException: Failed to connect to /52.11.239.143:80
    10-19 17:28:35.033 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:189)
    10-19 17:28:35.033 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:173)
    10-19 17:28:35.033 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
    10-19 17:28:35.033 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
    10-19 17:28:35.034 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
    10-19 17:28:35.034 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
    10-19 17:28:35.034 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
    10-19 17:28:35.034 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    10-19 17:28:35.034 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    10-19 17:28:35.034 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
    10-19 17:28:35.034 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    10-19 17:28:35.035 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    10-19 17:28:35.035 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
    10-19 17:28:35.035 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    10-19 17:28:35.035 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
    10-19 17:28:35.035 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    10-19 17:28:35.035 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    10-19 17:28:35.035 4372-4372/com.example.test1 W/System.err:     at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
    10-19 17:28:35.035 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    10-19 17:28:35.035 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    10-19 17:28:35.035 4372-4372/com.example.test1 W/System.err:     at com.example.test1.network.AuthInterceptor.intercept(AuthInterceptor.java:25)
    10-19 17:28:35.035 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    10-19 17:28:35.035 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    10-19 17:28:35.035 4372-4372/com.example.test1 W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
    10-19 17:28:35.035 4372-4372/com.example.test1 W/System.err:     at okhttp3.RealCall.execute(RealCall.java:60)
    10-19 17:28:35.036 4372-4372/com.example.test1 W/System.err:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
    10-19 17:28:35.036 4372-4372/com.example.test1 W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171)
    10-19 17:28:35.036 4372-4372/com.example.test1 W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
    10-19 17:28:35.036 4372-4372/com.example.test1 W/System.err:     at rx.Subscriber.setProducer(Subscriber.java:211)
    10-19 17:28:35.036 4372-4372/com.example.test1 W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
    10-19 17:28:35.036 4372-4372/com.example.test1 W/System.err:     at rx.Subscriber.setProducer(Subscriber.java:205)
    10-19 17:28:35.036 4372-4372/com.example.test1 W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
    10-19 17:28:35.036 4372-4372/com.example.test1 W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
    10-19 17:28:35.036 4372-4372/com.example.test1 W/System.err:     at rx.Observable$2.call(Observable.java:162)
    10-19 17:28:35.036 4372-4372/com.example.test1 W/System.err:     at rx.Observable$2.call(Observable.java:154)
    10-19 17:28:35.036 4372-4372/com.example.test1 W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:8314)
    10-19 17:28:35.036 4372-4372/com.example.test1 W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
    10-19 17:28:35.036 4372-4372/com.example.test1 W/System.err:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
    10-19 17:28:35.036 4372-4372/com.example.test1 W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
    10-19 17:28:35.036 4372-4372/com.example.test1 W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    10-19 17:28:35.036 4372-4372/com.example.test1 W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
    10-19 17:28:35.037 4372-4372/com.example.test1 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    10-19 17:28:35.037 4372-4372/com.example.test1 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    10-19 17:28:35.037 4372-4372/com.example.test1 W/System.err:     at java.lang.Thread.run(Thread.java:818)
    10-19 17:28:35.052 4372-4372/com.example.test1 D/BaseActivity: error : Failed to connect to /52.11.239.143:80
    10-19 17:28:35.052 4372-4372/com.example.test1 W/System.err: java.net.ConnectException: Failed to connect to /52.11.239.143:80
    10-19 17:28:35.052 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:189)
    10-19 17:28:35.052 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:173)
    10-19 17:28:35.052 4372-4372/com.example.test1 W/System.err:     at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
    10-19 17:28:35.052 4372-4372/? W/System.err:     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
    10-19 17:28:35.052 4372-4372/? W/System.err:     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
    10-19 17:28:35.052 4372-4372/? W/System.err:     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
    10-19 17:28:35.052 4372-4372/? W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
    10-19 17:28:35.052 4372-4372/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    10-19 17:28:35.052 4372-4372/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    10-19 17:28:35.052 4372-4372/? W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
    10-19 17:28:35.052 4372-4372/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    10-19 17:28:35.052 4372-4372/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    10-19 17:28:35.052 4372-4372/? W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
    10-19 17:28:35.053 4372-4372/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    10-19 17:28:35.053 4372-4372/? W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
    10-19 17:28:35.053 4372-4372/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)

**Comment by JakeWharton** [comment]
That stacktrace indicates a single connection failure. If you believe there is a bug in Retrofit with regard to how errors are propagated please provide a failing test case or executable sample.
