### ISSUE TITLE
[Request] Add "newBuilder" to Retrofit class

### ISSUE THREAD

**Issue by jaredsburrows** [square/retrofit#2054]
Can we add `newBuilder` builder similar to Okhttp3 (see [here](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/OkHttpClient.java#L390)) to `Retrofit.Builder`?

I would like to change the URL of an already created builder.

**Comment by JakeWharton** [comment]
Why do you need it?

**Comment by jaredsburrows** [comment]
The same reason it is availble in OkHttp3.

For instance:

```
// Some Client
    OkHttpClient client = new OkHttpClient.Builder()
      .addInterceptor(new HttpLoggingInterceptor()
        .setLevel(HttpLoggingInterceptor.Level.BODY))
      .cache(cache)
      .build();
    
// Some client 2
    OkHttpClient client2 = client.newBuilder().connectTimeout(CLIENT_TIME_OUT, TimeUnit.SECONDS)
      .writeTimeout(CLIENT_TIME_OUT, TimeUnit.SECONDS)
      .readTimeout(CLIENT_TIME_OUT, TimeUnit.SECONDS)
      .build();
```

I can reuse the existing builder to create another client and change some the existing parameters. I would like to be able to do the same with Retrofit 2.

**Comment by JakeWharton** [comment]
I know what it's function is, but what specifically would you use it for?
Unlike OkHttpClient the Retrofit instance is much more dumb and
necessitates something like this much less. So actual motivations are much
more compelling than theoretical ones (which is why it's currently absent).

**Comment by jaredsburrows** [comment]
It would be nice to easily call `newBuilder` and pass in the url from the Okhttp mockserver for testing. But in general, it would be nice to change some the existing parameters.

**Comment by ly85206559** [comment]
U can hold one Retrofit.Builder instance, then you can create different Retrofit instance with this builder.
like this:
Retrofit.Builder builder = Retrofit.Builder()
                .addConverterFactory(GsonConverterFactory.create())
                .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                .client(okHttpClient);
Retrofit retrofit1 = builder
                .baseUrl("xxx")
                .build();

Retrofit retrofit2 = builder
                .baseUrl("xxxxx")
                .build();
Do you mean this?

**Comment by ly85206559** [comment]
U can hold one Retrofit.Builder instance, then you can create different Retrofit instance with this builder.
like this:
Retrofit.Builder builder = Retrofit.Builder()
                .addConverterFactory(GsonConverterFactory.create())
                .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                .client(okHttpClient);
Retrofit retrofit1 = builder
                .baseUrl("xxx")
                .build();

Retrofit retrofit2 = builder
                .baseUrl("xxxxx")
                .build();
Do you mean this?

**Comment by jaredsburrows** [comment]
@ly85206559 That is what I am doing now. I do not want to pass `Retrofit.Builder`. It would be nice to pass `Retrofit` as a parameter. With `OkHttp3`, you can call `newBuilder()` on `OkHttpClient`.
