### ISSUE TITLE
Upload file using multipart

### ISSUE THREAD

**Issue by darakt** [square/retrofit#2060]
Hi, I'm trying to upload an image to my server using multipart but I'm always getting an error 400...
I assume that there is a probleme with the http query built.

`
    @Multipart
    @POST("japronto/api/chef/dish/new")
    Call<Dish> upload(@Part("name") RequestBody name, @Part("description") RequestBody description,
                      @Part("disponibility") RequestBody disp,@Part("max") RequestBody max,
                      @Part("price") RequestBody price, @Part("ImageNameHere\"; filename=\"image.png\" ") RequestBody image);
`

`        RequestBody name = RequestBody.create( MediaType.parse("multipart/form-data"), this.name.getText().toString());

```
    RequestBody description =
            RequestBody.create(
                    MediaType.parse("multipart/form-data"), this.description.getText().toString());

    RequestBody disp =
            RequestBody.create(
                    MediaType.parse("multipart/form-data"), Integer.toString(this.TorF));

    RequestBody max =
            RequestBody.create(
                    MediaType.parse("multipart/form-data"), this.max.getText().toString());

    RequestBody price =
            RequestBody.create(
                    MediaType.parse("multipart/form-data"), this.price.getText().toString());


    File nImg = new File(folderImg, imgName);
    Log.d(TAG, "onOK: "+folderImg+imgName);

    Uri uri = Uri.fromFile(nImg);
    ImageView tmp =(ImageView)findViewById(R.id.imgTT);
    tmp.setImageURI(uri);


    RequestBody rqFile = RequestBody.create(MediaType.parse("image/png"), nImg);

    RequestBody requestFile = RequestBody.create(MediaType.parse("multipart/form-data"), nImg);

    ApiService apiService = ApiManager.createService(ApiService.class, this.chef.getPseudo(), this.chef.getPassword());
    Call<Dish> call = apiService.upload(name, description, disp, max, price, rqFile);
    call.enqueue(new Callback<Dish>() {
        @Override
        public void onResponse(Call<Dish> call, Response<Dish> response) {
            Dish d = response.body();
            Log.d(TAG, "onResponse: ");
        }

        @Override
        public void onFailure(Call<Dish> call, Throwable t) {

        }
    });
```

`

**Comment by annelorayne** [comment]
Hi, @darakt, 

I use @Body MultipartTypedOutput to upload an image to my server using multipart. See the example below: 

@POST("/japronto/api/chef/dish/new")
 Call<Dish> upload(@Body MultipartTypedOutput attachments);

To create the request param you can use: 
final MultipartTypedOutput multipartTypedOutput = new MultipartTypedOutput();
multipartTypedOutput.addPart("name", new TypedString(this.description.getText().toString())));
...
 final TypedFile imageFile = new TypedFile("image/*", nImg);
 multipartTypedOutput.addPart("images", imageFile);

I hope to be helpful @darakt.

**Comment by JakeWharton** [comment]
A 400 means your client and your server disagree on the format of the request. This isn't a problem with Retrofit. You'll need to consult your server team or the API documentation coupled with tools like OkHttp's logging interceptor to ensure you're sending the data in the format it expects.
