### ISSUE TITLE
How to expand

### ISSUE THREAD

**Issue by TruthKeeper** [square/retrofit#2061]
Excuse me，I want to do something to extend，But I have some trouble。
I can't cancel requests by target，althoughOkHttp support。

**Comment by JakeWharton** [comment]
Retrofit does not expose specifying a tag or canceling by tag (which actually isn't supported by OkHttp natively anymore). If you need behavior like this, you can keep your own multimap of tag objects to a set of call instances. This will quickly allow you to cancel all calls by a certain tag. You also can use the OkHttpClient instance to iterate the active calls that Retrofit created and cancel them using any kind of marker like URL or header. At this time we have no plans to support exposing OkHttp's tag functionality through Retrofit.
