### ISSUE TITLE
java.lang.IllegalArgumentException: Field map contained null value 

### ISSUE THREAD

**Issue by starktonys** [square/retrofit#2067]
java.lang.IllegalArgumentException: Field map contained null value

**Comment by JakeWharton** [comment]
There's no reason to have a null value in a field map. Just omit the key altogether.

**Comment by twiceyuan** [comment]
Is ignore this field better than throw a exception? Or provide a option to configure.

There are some nullable fields in our api, we must manual filter them now because this feature.

**Comment by alen252** [comment]
Is ignore this field better than throw a exception? Or provide a option to configure.

There are some nullable fields in our api, we must manual filter them now because this feature.
