### ISSUE TITLE
RxJava2 and no content with Retrofit

### ISSUE THREAD

**Issue by JoshMieczkowski** [square/retrofit#2068]
Since RxJava2 is no longer passing Void/nulls, what is the correct way of implementing a Flowable return with no content api calls?

**Comment by patloew** [comment]
Use `Completable` as return type.

**Comment by JakeWharton** [comment]
Retrofit does not have an adapter for RxJava 2 yet. The correct way is with `Completable`, however, as @patloew said. You can use https://github.com/JakeWharton/retrofit2-rxjava2-adapter until Retrofit gets native RxJava 2 support.
