### ISSUE TITLE
The use of retrofit upload pictures encountered a problem

### ISSUE THREAD

**Issue by laymanZ** [square/retrofit#2072]
Hello, I first learned to use retrofit, upload pictures encountered a little trouble, the error is as follows:
Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $

Here is my code:
1: gradle configuration

Compile 'com.squareup.retrofit2: retrofit: 2.1.0'
Compile 'com.squareup.retrofit2: converter-gson: 2.1.0'
Compile 'com.squareup.retrofit2: adapter-rxjava: 2.0.0-beta4'

2、Interface

//    http://1.qxmb.applinzi.com/picture.php

public interface PictureService
{
    @Multipart
    @POST("picture.php")
    Call<Result<String>> testPicture(@Part MultipartBody.Part part);   
}

3、Test class

` MediaType mediaType = MediaType.parse("multipart/form-data;charset=utf-8");
        MultipartBody.Part imageTest = MultipartBody.Part.createFormData("img",path,RequestBody.create(mediaType,new File(path)));
        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl("http://1.qxmb.applinzi.com/")
                .addConverterFactory(GsonConverterFactory.create())
                .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                .build();
        PictureService pictureService = retrofit.create(PictureService.class);
//        Call<User> call = pictureService.testPicture(imageTest);
        Call<Result<String>> call = pictureService.testPicture(imageTest);
        call.enqueue(new Callback<Result<String>>() {
            @Override
            public void onResponse(Call<Result<String>> call, Response<Result<String>> response)
            {
                Log.d("haha","成功");
            }

            @Override
            public void onFailure(Call<Result<String>> call, Throwable t) {
                Log.d("haha","上传失败" + t.getMessage());
            }
        });`

Test link I use okhttp upload pictures can be successfully uploaded, so the link is no problem
So far found no mistakes in which I hope to be given guidance, thank you

**Comment by FabianTerhorst** [comment]
You are getting a non-json response from your Server. You can use the ResponseBody object instead of String to fix that.

**Comment by JakeWharton** [comment]
It's really hard to know what's going on here, but it looks your server isn't returning JSON but your interface expects it to? That's something you'll have to just figure out what went wrong and correct the behavior. If you can write a test case or sample that shows somehow this is a Retrofit problem I'm happy to take a look, but it seems just like your server isn't responding in a way that you've set up the client to expect.

**Comment by laymanZ** [comment]
Thanks for the answer, I have to solve this problem, but forgot to paste the code, I am sorry, the following is my solution


```
`public interface PictureService
{
    @Multipart
    @POST("picture.php")
    Call<User> testPicture(@Part MultipartBody.Part part);


}
class User
{

}`
```

`MultipartBody.Part imageTest = MultipartBody.Part.createFormData("img",path,RequestBody.create(mediaType,new File(path)));

        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl("")
                .addConverterFactory(GsonConverterFactory.create())
                .build();
        PictureService pictureService = retrofit.create(PictureService.class);
        Call<User> call = pictureService.testPicture(imageTest);

        call.enqueue(new Callback<User>() {
            @Override
            public void onResponse(Call<User> call, Response<User> response) {
                Log.d("haha","success");

            }

            @Override
            public void onFailure(Call<User> call, Throwable t) {
                Log.d("haha","failed" + t.getMessage());
            }
        });`

**Comment by k0shk0sh** [comment]
As @FabianTerhorst __said__ your server returns `String` & not `JsonObject` you need to verify with your server regards this & if you are sure about that it returns `Json` then please post the response here.
