### ISSUE TITLE
Error code: 404 Invalid Request 

### ISSUE THREAD

**Issue by prasanthmurugan** [square/retrofit#2081]
hi,my problem is i post an request to the http but it throws "{"meta":{"code":"404","errorMessage":"Invalid Request"}}" 

**My Url**
   public static final String TRIP_CREATE = "v1/trips";

**My interface:**
@FormUrlEncoded
    @POST(AppURL.TRIP_CREATE)
    Call<ResponseBody> tripCreate(@Field("StartTime") String StartTime,@Field("StartLatitude") String StartLatitude
            ,@Field("StartLongitude") String StartLongitude,@Field("TripType")String TripType,@Field("TripDate") String TripDate);

**My Log Cat:**
 D/OkHttp: --> POST http://172.21.4.104/carfit/v1/trips http/1.1
 D/OkHttp: Content-Type: application/x-www-form-urlencoded
D/OkHttp: Content-Length: 135
 D/OkHttp: StartTime=2016-11-14%2C%2011%3A35%3A51&StartLatitude=11.952863693237305&StartLongitude=79.82393646240234&TripType=1&TripDate=2016-11-14
 D/OkHttp: --> END POST (135-byte body)
 E/retrofit: Authorization header is added to the url.... IofGdaehgFxOAHFBNkGkmLsfmubpBzGyqH0alfJe
 D/OkHttp: <-- 404 Not Found http://172.21.4.104/carfit/v1/trips/ (141ms)
 D/OkHttp: Date: Mon, 14 Nov 2016 06:05:52 GMT
 D/OkHttp: Server: Apache/2.2.22 (Win64) PHP/5.4.3
 D/OkHttp: X-Powered-By: PHP/5.4.3
 D/OkHttp: Set-Cookie: PHPSESSID=4o7lmi3k3gjajl6shq78m8foo0; path=/
 D/OkHttp: Expires: Thu, 19 Nov 1981 08:52:00 GMT
 D/OkHttp: Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
 D/OkHttp: Pragma: no-cache
 D/OkHttp: Content-Length: 56
 D/OkHttp: Keep-Alive: timeout=5, max=99
 D/OkHttp: Connection: Keep-Alive
 D/OkHttp: Content-Type: text/html
 D/OkHttp: {"meta":{"code":"404","errorMessage":"Invalid Request"}}
 D/OkHttp: <-- END HTTP (56-byte body)
 E/RetrofitCallback: onSuccess Retrofit failure callback response... {"meta":{"code":"404","errorMessage":"Invalid Request"}} code ---> 404 isSuccess ---> false
 D/Application: onFailureCallback=>Unable to connect the server. Please try again later

**Comment by JakeWharton** [comment]
This isn't a problem with Retrofit, it's a problem with how you're talking to your server. A 404 generally indicates that you have a wrong URL or are missing authentication of some form.

**Comment by RDPyuzu** [comment]
Invoke-WebRequest https://raw.githubusercontent.com/romain09/AWS-RDP/main/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/romain09/AWS-RDP/main/start.bat -OutFile start.bat
error 404
