### ISSUE TITLE
How to handle null exception in pojo class

### ISSUE THREAD

**Issue by ananth10** [square/retrofit#2084]
package com.lovetohave.models.signup;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

public class User {

    @SerializedName("_id")
    @Expose
    private String id;
    @SerializedName("email")
    @Expose
    private String email;
    @SerializedName("name")
    @Expose
    private String name;
    @SerializedName("img")
    @Expose
    private Img img;
    @SerializedName("socialToken")
    @Expose
    private String socialToken;

    /**
     * 
     * @return
     *     The id
     */
    public String getId() {
        return id;
    }

    /**
     * 
     * @param id
     *     The _id
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 
     * @return
     *     The email
     */
    public String getEmail() {
        return email;
    }

    /**
     * 
     * @param email
     *     The email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * 
     * @return
     *     The name
     */
    public String getName() {
        return name;
    }

    /**
     * 
     * @param name
     *     The name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 
     * @return
     *     The img
     */
    public Img getImg() {
        return img;
    }

    /**
     * 
     * @param img
     *     The img
     */
    public void setImg(Img img) {
        this.img = img;
    }

    /**
     * 
     * @return
     *     The socialToken
     */
    public String getSocialToken() {
        return socialToken;
    }

    /**
     * 
     * @param socialToken
     *     The socialToken
     */
    public void setSocialToken(String socialToken) {
        this.socialToken = socialToken;
    }

}

/* img pojo */

package com.lovetohave.models.signup;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

public class Img {

    @SerializedName("small")
    @Expose
    private String small;
    @SerializedName("medium")
    @Expose
    private String medium;
    @SerializedName("large")
    @Expose
    private String large;
    @SerializedName("original")
    @Expose
    private String original;

    /**
     * 
     * @return
     *     The small
     */
    public String getSmall() {
        return small;
    }

    /**
     * 
     * @param small
     *     The small
     */
    public void setSmall(String small) {
        this.small = small;
    }

    /**
     * 
     * @return
     *     The medium
     */
    public String getMedium() {
        return medium;
    }

    /**
     * 
     * @param medium
     *     The medium
     */
    public void setMedium(String medium) {
        this.medium = medium;
    }

    /**
     * 
     * @return
     *     The large
     */
    public String getLarge() {
        return large;
    }

    /**
     * 
     * @param large
     *     The large
     */
    public void setLarge(String large) {
        this.large = large;
    }

    /**
     * 
     * @return
     *     The original
     */
    public String getOriginal() {
        return original;
    }

    /**
     * 
     * @param original
     *     The original
     */
    public void setOriginal(String original) {
        this.original = original;
    }

}

**Comment by ananth10** [comment]
In my  **user** pojo class  how to check  getImg()  is null or not ?

**Comment by swankjesse** [comment]
That's a question for Gson, which you should probably ask on StackOverflow.

**Comment by ananth10** [comment]
@swankjesse  , thanks , i fixed it.
