### ISSUE TITLE
RxJava adapters blocking api overhead?

### ISSUE THREAD

**Issue by llooz** [square/retrofit#2085]
Having an RxJava adapter that generates observable running directly with the Call enqueue method is more efficient than the blocking api on Schedulers.io()?

**Comment by JakeWharton** [comment]
No. It's exactly the same except OkHttp ends up blocking on its own thread pool instead of being on one which you can specify.

If you want this functionality then it's only about 15 lines of a custom CallAdapter to write but we won't be providing such functionality in the first-party adapters.

**Comment by llooz** [comment]
Ok so it will just allow to use the okhttp Dispatcher with its functionality without any benefit regarding thread efficiency

**Comment by JakeWharton** [comment]
Correct!
