### ISSUE TITLE
Can't mock Response.class, it's final

### ISSUE THREAD

**Issue by chriskessel** [square/retrofit#2089]
I'm trying to use Mockito to mock out the Call\<ResponseBody\> object my retrofit2 interface is returning, but I can't mock the Response returned by call.execute() because Response.class is final. There's MockRetrofit, but the examples seem to require quite a lot of code to setup and often involve creating custom mock classes. 

Is it possible to just remove final on Response.class? Jersey used to have a similar final on one their classes (an intermediate object in the .post().entity().etc() chain) and removed it to help mocking.

**Comment by JakeWharton** [comment]
Response is a value type. Why do you need to mock it? Just use the static
factory methods to create your own instance.

**Comment by chriskessel** [comment]
Because I ran into issues with further calls in the mock sequence and that was the start of it. For example, if I set up mocks this way I'm getting a failure trying to read the underlying Stream from the response body because there was no actual underlying http call.
```
java.lang.NullPointerException
	at okhttp3.ResponseBody.bytes(ResponseBody.java:128)
	at okhttp3.ResponseBody.string(ResponseBody.java:154)
```

How do I mock that out with a real Response? Unless I'm mocking every step (call, response, body read) I can't seem to get it to work.
```
        Call<ResponseBody> call = mock(Call.class);
        ResponseBody responseBody = mock(ResponseBody.class);
        Response<ResponseBody> response = Response.success(responseBody);
        when(call.execute()).thenReturn(response);
        when(responseBody.string()).thenReturn("mystring"); /// Fails
```

**Comment by JakeWharton** [comment]
You don't need to mock ResponseBody either. You can create instances with
its static methods.

**Comment by AlexMcConnell** [comment]
> Response is a value type. Why do you need to mock it? Just use the static
> factory methods to create your own instance.

Because I shouldn't have to learn how to use your library in order to backfill unit tests on a legacy application.
