### ISSUE TITLE
About send POST with raw string.

### ISSUE THREAD

**Issue by shichaohui** [square/retrofit#2091]
I think it is very inconvenient to use an entity or Map or RequestBody to send a Post request. Has the author ever thought of using annotations instead of entity or RequestBody? Like @Field @Query

**Comment by JakeWharton** [comment]
You can send a raw string by using and adding the `converters-scalars` artifact which supports all of Java's primitive types, boxed types, and `String`. It will be treated as `text/plain`.

**Comment by shichaohui** [comment]
Thank you for your reply. But this method is still not convenient. I don't want to splice strings. It's easy to make mistakes.
Why not provide an annotation named Raw? Be used like this:
```
@POST("terminal/task/list")
Observable<T> load(
        @Raw("tokenId") String tokenId,
        @Raw("userId") String userId);
```
Finally, send  out this json string. `{"tokenId":"tokenId", "userId":"userId"}`

**Comment by JakeWharton** [comment]
Because Retrofit is serialization format agnostic. Create a model object
and use a JSON converter.
