### ISSUE TITLE
Feature Request: RequestBody Converter even if no @Body param is present

### ISSUE THREAD

**Issue by hzsweers** [square/retrofit#2097]
Currently, if no `@Body` parameter is specified in the service method, then no `Converter` is ever requested and it always forces an empty request body behavior. I'd like to propose still requesting converters even if no body is provided.

We have two use example cases that would benefit from this:

----------

1. We have some server specs that define parameters on methods but expect them to all be blobs within a single body with the param names as keys, like so:

Spec:
```thrift
someEndpoint(A paramA, B paramB);
```

Expected JSON:
```json
{
  "paramA": <serializedInstanceOfA>,
  "paramB": <serializedInstanceOfB>
}
```

Currently we get around in code gen because consumers don't work directly with the service, rather they interact with a `Client` instance that consumes the generated service. The result is that while the client keeps the `someEndpoint(A paramA, B paramB)` API, the actual service just has an awkward `someEndpoint(@Body Map mapBody)` and the client implementation creates the `Map` under the hood to take the burden off consumers.

Ideally, we'd like to be able to write something like this:

```java
someEndpoint(@NestedBodyPart("paramA") A paramA, @NestedBodyPart("paramB") B paramB);
```

And do the request conversion ourselves through a custom converter.

----------

~~2. We also have some endpoints that have weird empty body requirements. Usually an "EmptyBody" implementation would just be something with a content length of 0, but for json request types they actually expect the body to be (groan) `{}`. While we could always require some `SillyEmptyBody` instance, it would be ideal again from an API perspective if we could do something like this:~~

```java
@POST("someEndpoint")
@SillyEmptyBody
someEndpoint();
```

~~And then fill in the weird empty body requirement via custom converter. This is understandable a weaker argument though, but just giving it as another example.~~

**EDIT**: Talked with @swankjesse separately, he pointed out that this is a good candidate for something pushed into an interceptor.

-----------

We're starting to migrate to Retrofit 2 and part of that is with the goal of being able to avoid generating the `Client` façades entirely and just injecting the retrofit-created service, and having this ability would go a long way to enabling that.

**Comment by swankjesse** [comment]
Retrofit is really good if you’ve got a single `T` parameter for the request body. You’re requesting support for mapping _N_ parameters to the request body, where `N` is between 0 and 2.

Doing this in Retrofit risks dramatically complicating it. The workaround of building your own objects for the bodies doesn’t seem too tragic.

**Comment by hzsweers** [comment]
I don't think that's what I was requesting, rather I was just saying if no body parameters are specified, still see if there's a converter factory willing to provide one.

**Comment by swankjesse** [comment]
What would we pass to the `Converter.Factory`?

**Comment by hzsweers** [comment]
You'd have to do a more eager check for missing body pieces on a request that needs a body, but effectively start with the default `ResponseBody` instance [retrofit already creates if none are provided](https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit2/RequestBuilder.java#L206).

**Comment by JakeWharton** [comment]
But what type would we ask the converters for?

**Comment by hzsweers** [comment]
`Void` to be defensive (have to be looking for this) or `Object` to be permissive (everyone gets a chance?)

**Comment by JakeWharton** [comment]
I'm hesitant about adding this. The absence of a body declaration makes our
decision to skip the converters logical and using this mechanism to
materialize non-empty empty bodies sounds like working around poor APIs.
Maybe use a marker header and an interceptor to "fix" the empty body?

On Fri, Nov 25, 2016 at 8:25 PM Zac Sweers <notifications@github.com> wrote:

Void to be defensive (have to be looking for this) or Object to be
permissive (everyone gets a chance?)

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/square/retrofit/issues/2097#issuecomment-263037377>,
or mute
the thread

**Comment by hzsweers** [comment]
Possibly, how would I access the "parts" so-to-speak in an interceptor approach?

**Comment by JakeWharton** [comment]
What parts? I thought the whole point was that there was no body declared.

**Comment by hzsweers** [comment]
Whoops, forgot to reply to this thread :|

Looking at it again, I for some reason thought the converter API gave you app the parameters during conversion, but that's not actually the case. In light of that, I don't think there's a path forward on this. Thanks for humoring me though!
