### ISSUE TITLE
Multipart request to post JSONArray using RequestBody

### ISSUE THREAD

**Issue by Fatehali** [square/retrofit#2098]
Is it possible to post JSONArray using Multipart RequestBody ?

My current issue is : **_### Cannot resolve method 'create(okhttp3.MediaType, org.json.JSONArray)_**

I am using it as:
 **RequestBody jsonArrayList= RequestBody.create(MediaType.parse("text/plain"), jsonArray);**

**@Multipart
@POST("doctor/orderdata")
Call<ResponseBody> addDigitalPrescription(@Part (digitalPrescription) RequestBody digitalPrescription);**

_If not? Than what should I do to post Multipart JSONArray using Retrofit2_

**Comment by JakeWharton** [comment]
You have to convert it to a String or byte[] to use it with RequestBody.
Otherwise you can write a Retrofit Converter.Factory that handles this type
and does the conversion automatically for you by adding it to
Retrofit.Builder with your other converters.
