### ISSUE TITLE
[Feature Request] SubPath Annotation on Interface

### ISSUE THREAD

**Issue by jaumard** [square/retrofit#2100]
Maybe this already exist but I was not able to find how... 
It can be useful to have the ability to add annotation on interfaces to set some subpath on the baseURL.

Something like : 
```
@SubPath("user") //http://mybaseUrl/user
public class User {
  @Get
   .....

   @Post
   ....
   
   @Get("customAction") //http://mybaseUrl/user/customAction
   ....
}
```

I think it's already possible but as I can't find nothing about it, maybe I just imagine it.
Thanks!

**Comment by swankjesse** [comment]
Probably just simpler to specify that in the base URL? You can have multiple Retrofit.Builders if necessary.
