### ISSUE TITLE
[Feature Request] Fastjson

### ISSUE THREAD

**Issue by jjhesk** [square/retrofit#2105]
What kind of issue is this?

 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Are there any plan to get [fastjson](https://github.com/alibaba/fastjson) integrated into retrofit?

**Comment by JakeWharton** [comment]
No. We are not adding any more first-party converters at this time. See https://github.com/square/retrofit/wiki/Converters

**Comment by jjhesk** [comment]
it seems the fastjson convertor has been developed
