### ISSUE TITLE
responds different types

### ISSUE THREAD

**Issue by A7med7ani** [square/retrofit#2108]
how handle different tyoes respons 

{
  "status": 0,
  "count": 0,
  "message": "Login Failed. Incorrect Credentials",
  "items": []
}
-------
{
  "status": 1,
  "count": 6,
  "message": "Successfully Logged In",
  "items": {
    "id": 94,
    "name": "tt",
    "email": "tt@hotmail.com",
    "mobile": "123456",
    "apiKey": "4d0d249403a429a15ff8589cc02e24cd",
    "createdAt": "2016-12-02 16:35:57"
  }
}

**Comment by JakeWharton** [comment]
Retrofit just hands the `ResponseBody` to your installed converter and asks it to deserialize as whatever type you have declared. For complex deserialization you'll need to consult the documentation of your chosen serialization library and figure out how to make it have the behavior you want. Beyond handing the bytes over, Retrofit plays no part in deserialization.
