### ISSUE TITLE
It's throwing 400 error

### ISSUE THREAD

**Issue by maheswaranecemohan** [square/retrofit#2110]
onResponse{"rawResponse":{"body":{"contentLength":-1,"contentType":{"charset":"UTF-8","mediaType":"application/json;charset\u003dUTF-8","subtype":"json","type":"application"}},"code":400,"headers":{"namesAndValues":["Server","Apache-Coyote/1.1","Access-Control-Allow-Credentials","true","Access-Control-Allow-Methods","POST, GET, OPTIONS, DELETE","Access-Control-Max-Age","3600","Access-Control-Allow-Headers","Content-Type, Accept, X-Requested-With, remember-me","Content-Type","application/json;charset\u003dUTF-8","Transfer-Encoding","chunked","Date","Mon, 05 Dec 2016 10:24:02 GMT","Connection","close"]},"message":"Bad Request","networkResponse":{"code":400,"headers":{"namesAndValues":["Server","Apache-Coyote/1.1","Access-Control-Allow-Credentials","true","Access-Control-Allow-Methods","POST, GET, OPTIONS, DELETE","Access-Control-Max-Age","3600","Access-Control-Allow-Headers","Content-Type, Accept, X-Requested-With, remember-me","Content-Type","application/json;charset\u003dUTF-8","Transfer-Encoding","chunked","Date","Mon, 05 Dec 2016 10:24:02 GMT","Connection","close"]},"message":"Bad Request","protocol":"HTTP_1_1","receivedResponseAtMillis":1480933444311,"request":{"cacheControl":{"isPrivate":false,"isPublic":false,"maxAgeSeconds":-1,"maxStaleSeconds":-1,"minFreshSeconds":-1,"mustRevalidate":false,"noCache":false,"noStore":false,"noTransform":false,"onlyIfCached":false,"sMaxAgeSeconds":-1},"headers":{"namesAndValues":["Authorization","Basic YWRtaW46YWRtaW4\u003d","Content-Type","application/json","Content-Length","0","Host","192.168.0.2:8080","Connection","Keep-Alive","Accept-Encoding","gzip","User-Agent","okhttp/3.3.1"]},"method":"POST","tag":{"headers":{"namesAndValues":[]},"method":"POST","url":{"host":"192.168.0.2","password":"","pathSegments":["enicu-service","auth","session",""],"port":8080,"scheme":"http","url":"http://192.168.0.2:8080/enicu-service/auth/session/","username":""}},"url":{"host":"192.168.0.2","password":"","pathSegments":["enicu-service","auth","session",""],"port":8080,"scheme":"http","url":"http://192.168.0.2:8080/enicu-service/auth/session/","username":""}},"sentRequestAtMillis":1480933444148},"protocol":"HTTP_1_1","receivedResponseAtMillis":1480933444311,"request":{"headers":{"namesAndValues":["Authorization","Basic YWRtaW46YWRtaW4\u003d","Content-Type","application/json","Content-Length","0"]},"method":"POST","tag":{"headers":{"namesAndValues":[]},"method":"POST","url":{"host":"192.168.0.2","password":"","pathSegments":["enicu-service","auth","session",""],"port":8080,"scheme":"http","url":"http://192.168.0.2:8080/enicu-service/auth/session/","username":""}},"url":{"host":"192.168.0.2","password":"","pathSegments":["enicu-service","auth","session",""],"port":8080,"scheme":"http","url":"http://192.168.0.2:8080/enicu-service/auth/session/","username":""}},"sentRequestAtMillis":1480933444148}}

**Comment by JakeWharton** [comment]
The 400 comes from your server and you have to handle it.
