### ISSUE TITLE
Upload image with chunk.

### ISSUE THREAD

**Issue by ViramP** [square/retrofit#2111]
Hi,
I'm android developer,I want to upload multiple image at server (around 50 images).
Currently,I'm upload with URLConnection on Chunk.
So i can upload image using retrofit with chink.

**Comment by JakeWharton** [comment]
Retrofit has no control over (and doesn't care about) the mechanism for which the HTTP client uploads the data. The built-in converters all specify a `Content-Length` which means OkHttp will not use chunked encoding. If you write your own converter to go from whatever image type you are using to a `RequestBody` and you do not specify a content length then OkHttp will use chunked encoding as a side-effect. There's no strict control over this from Retrofit though.
