### ISSUE TITLE
progressive feature

### ISSUE THREAD

**Issue by jjhesk** [square/retrofit#2112]
What kind of issue is this?

 - [X] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I have seen that google firebase has the feature of progressive data loading. You have any plans to make that implemented to retrofit as well?

**Comment by JakeWharton** [comment]
Retrofit already streams the response data to the converter. Beyond that, anything progressive has to be implemented by the application layer, not by this library.
