### ISSUE TITLE
Easier support for Hystrix and a like

### ISSUE THREAD

**Issue by edudar** [square/retrofit#2113]
I tried to marry Retrofit and Hystrix together but that appears to be quite a cumbersome process. Ideally, I'd like to have something like this
```
@POST("...")
@HystrixCommand(groupKey="...", commandKey="...")
Observable<SomeObject> get();
```
However Retrofit uses JDK proxies and annotation info is not preserved so AOP stuff that wires together annotations and actual code does not work. For now, I had to create classes that match methods on interfaces and put `@HystrixCommand` into class methods instead. That does not look nice as I have to double the code.

Maybe allowing pluggable proxy (cglib, byte-buddy, etc) solution would be helpful in the long term here.

**Comment by liangGTY** [comment]
hystrix-adapters？ I think this is very good

**Comment by swankjesse** [comment]
It’s not necessarily going to be a good fit because of the way Retrofit returns asynchronous objects. I think Hystrix is going to want to time the network call, not the method call to create an observable, etc.

Probably better to integrate Hystrix as a custom CallAdapter.

**Comment by swankjesse** [comment]
(closing because I don’t think we’re going to get to this. If somebody would like to write a call adapter that hooks up Hystrix, that’d be great!)

**Comment by liangGTY** [comment]
I've written a simple hystrix callAdapter before。

[hystrix callAdapter](https://github.com/liangGTY/retrofit-spring-boot/blob/master/retrofit-core-spring-boot/src/main/java/cn/dysania/retrofit/instrument/hystrix/HystrixCallAdapterFactory.java)
