### ISSUE TITLE
Error:(31, 13) Failed to resolve: com.squareup.retrofit2:converter-gson:latest.version 

### ISSUE THREAD

**Issue by aderbas** [square/retrofit#2117]
Hello, I'm created new Android project for use retrofit. But when I add  in dependencies it gives error in download. `Failed to resolve: com.squareup.retrofit2:converter-gson:latest.version`
```
dependencies {
   compile 'com.squareup.retrofit2:retrofit:2.1.0'
   compile 'com.squareup.retrofit2:converter-gson:latest.version'
}
```
No need to add "convert-gson" dependencies?

**Comment by aderbas** [comment]
Fixed: `compile 'com.squareup.retrofit2:converter-gson:2.1.0'` However in the documentation is: `com.squareup.retrofit2:converter-gson:latest.version`

**Comment by SbyXlmm** [comment]
good

**Comment by varun1233** [comment]
Thanks for the solution

**Comment by hamada147** [comment]
Thanks for the solution.

**Comment by xkadmx** [comment]
I followed your instruction and got 

> ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not find any version that matches com.squareup.retrofit2:converter-gson:latest.version.

instead.

**Comment by powerfuldeveloper** [comment]
just user the same version which the retrofit is:
```
implementation 'com.squareup.retrofit2:retrofit:2.5.0'
implementation 'com.squareup.retrofit2:converter-gson:2.5.0'
```

**Comment by jedidiahasare** [comment]
this is it!
