### ISSUE TITLE
Add sample showing polymorphic converter.

### ISSUE THREAD

**Issue by karlkar** [square/retrofit#2123]
So that the runtime type is serialized and not the declared type.

*Original issue below*

----

I have a very strange problem with Retrofit, in fact it may be a bug of it. I want to send to server a POST request with some data. My data is in a subclass of Request class.

```
public abstract class Request {}
public abstract class Measurement {}

public class StepMeasurement extends Measurement {
    ...
    public int value;
}
public class SendStepsRequest extends Request {
    public List<StepMeasurement> steps;
}
````

example is of course very simplified. I've prepared an interface for sending it:
```

public interface EndpointInterface {

@Headers({"Content-Type: application/json"})
@POST("/patients/{id}/{dataType}")
Call<ResponseBody> postRequest(
       @Path("id") int patientId,
        @Path("dataType") String dataType,
        @Header("X-XSRF-TOKEN") String token,
        @Header("Cookie") String cookie,
        @Body Request req);
}
```

And I have a retrofit ready to go:

```
mEndpointInterface = new Retrofit.Builder()
            .baseUrl(BASE_URL)
            .client(getUnsafeOkHttpClient())
            .addConverterFactory(GsonConverterFactory.create())
            .build().create(EndpointInterface.class);
```

I think that now calling mEndpointInterface.postRequest(1, "steps", "token", "cookie", new SendStepsRequest(5)); should send a JSON looking like that:

> {"steps":[{"value":5}]}

However all that is sent is

> {}

For me unlogical. I guess that Gson doesn't know how to go down in a class hierarchy, so he doesn't know that SendStepsRequest is a subtype of Request. I've already prepared RuntimeTypeAdapterFactory and it started to work then, but that's strange for me. Shouldn't GSON know about inheritance? So I started to experiment.

And now some interesting stuff. I've created a class RequestWrapper:

```
public class RequestWrapper {
    Request mRequest;
}
```

and changed my interface to accept RequestWrapper instead of Request and guess what! The result was:

> {"mRequest":{"steps":[{"value":5}]}}

so he found out how my classes are hierarchized, but couldn't do it without RequestWrapper.

I've also tried a different thing - I've changed my Interface to accept SendStepsRequest objects and changed List< StepMeasurement > to List< Measurement >. What Retrofit send to the server?

> {"steps":[{"value":5}]}

so again, he detected the subtype of Measurement class and used it as he should.

My guess is that there's some bug in Retrofit that prevents proper serialization of objects' of classes passed in interface. What do you think? Maybe I'm doing something wrong?

One more funny thing - same behavior was observed when I've used Jackson instead of Gson.

**Comment by JakeWharton** [comment]
This is not a bug but a design decision of the library. We only look up a converter for the declared type and not the runtime type to save having to do it for every call. I'll repurpose your issue for adding a sample to show how to make a converter polymorphic based on the supplied type not the declared type.

**Comment by ylfzq** [comment]
Just as @JakeWharton said, here is the code in GsonConverterFactory:

```java
public final class GsonConverterFactory extends Converter.Factory {
  // ...

  @Override
  public Converter<?, RequestBody> requestBodyConverter(Type type,
      Annotation[] parameterAnnotations, Annotation[] methodAnnotations, Retrofit retrofit) {
    // you can see here that it uses declared type
    TypeAdapter<?> adapter = gson.getAdapter(TypeToken.get(type));
    return new GsonRequestBodyConverter<>(gson, adapter);
  }
}
```

Note the parameter "type" is the type you declare in your interface. Retrofit uses declare type instead of runtime type. 

Actually we don't need this type in request converter. Since JSON(Gson) only serialize fields, not containing the class type itself. So we don't need TypeAdapter at all. Here is the modified code, it work well in your scene @karlkar :

```java
public final class GsonConverterFactory extends Converter.Factory {
  // ...

  @Override
  public Converter<?, RequestBody> requestBodyConverter(Type type,
      Annotation[] parameterAnnotations, Annotation[] methodAnnotations, Retrofit retrofit) {
    return new GsonRequestBodyConverter<>(gson);
  }
}

final class GsonRequestBodyConverter<T> implements Converter<T, RequestBody> {
  private static final MediaType MEDIA_TYPE = MediaType.parse("application/json; charset=UTF-8");
  private static final Charset UTF_8 = Charset.forName("UTF-8");

  private final Gson gson;

  GsonRequestBodyConverter(Gson gson /* removed parameter TypeAdapter */) {
    this.gson = gson;
  }

  @Override
  public RequestBody convert(T value) throws IOException {
    // just using Writer to output json string
    Buffer buffer = new Buffer();
    Writer writer = new OutputStreamWriter(buffer.outputStream(), UTF_8);
    gson.toJson(value, writer);
    writer.close();
    return RequestBody.create(MEDIA_TYPE, buffer.readByteString());
  }
}
```
But deserialize need type, so only requestBodyConverter need to be changed.

**Comment by julioromano** [comment]
Is this a behavior change from retrofit 1.x ?

I'm asking because during a migration from Retrofit 1 to 2 (both using gson for de/serialization) I started having issues with polymorphic types and found out they are now being serialized as their parent type.

**Comment by JakeWharton** [comment]
Yes it's a behavior change for performance reasons.

**Comment by julioromano** [comment]
Thanks. What is the gist of the performance reasons?

**Comment by JakeWharton** [comment]
99% of the time you serialize the same type so looking up the same adapter
inside Gson or Moshi or Wire or Protobuf over and over is wasteful work. We
now look up the adapter once and reuse it directly.

**Comment by julioromano** [comment]
`Gson.getAdapter()` is backed by a cache so subsequent calls with the same `type` should be reasonably quick.
Are you concerned about the cost of cache misses or the cost of `TypeToken.get()` ?

**Comment by JakeWharton** [comment]
Both. It's wasted work when the type isn't changing.

**Comment by swankjesse** [comment]
No action to take on this.
