### ISSUE TITLE
Request body to server is updated as null Put method 

### ISSUE THREAD

**Issue by prasanthmurugan** [square/retrofit#2124]
Json body is attached correctly in the retrofit but the server request is null in back office so the response is error

**Issue**
12-14 20:11:36.014 23741-30248/D/OkHttp: --> PUT http://url/v1/trips/428 http/1.1
12-14 20:11:36.014 23741-30248/ D/OkHttp: Content-Type: application/json; charset=UTF-8
12-14 20:11:36.014 23741-30248/ D/OkHttp: Content-Length: 157
12-14 20:11:36.014 23741-30248/D/OkHttp: {"Distance":"0.0010570142","EndLatitude":"11.95622502037177","EndLongitude":"79.8267606040814","EndTime":"2016-12-14 19:56:38","MaxSpeed":"3","MinSpeed":"0"}
12-14 20:11:36.014 23741-30248/com.drava.android D/OkHttp: --> END PUT (157-byte body)
12-14 20:11:36.014 23741-30248/com.drava.android E/retrofit: Authorization header is added to the url.... NtC0A9rARDFENR5X84pw36JjDI8Qq8ijXF2lW3lZ
12-14 20:11:36.014 23741-23741/E/SyncHelper: TrackPathObject size :0
12-14 20:11:37.067 23741-30248/ D/OkHttp: <-- 200 OK http://url/v1/trips/428 (1052ms)
12-14 20:11:37.067 23741-30248/ D/OkHttp: Cache-Control: no-store,no-cache,must-revalidate
12-14 20:11:37.067 23741-30248/D/OkHttp: Content-Type: application/json
12-14 20:11:37.067 23741-30248/D/OkHttp: Date: Wed, 14 Dec 2016 14:41:37 GMT
12-14 20:11:37.067 23741-30248/D/OkHttp: Expires: Thu,19 Nov 1981 08:52:00 GMT
12-14 20:11:37.067 23741-30248/ D/OkHttp: Pragma: no-cache
12-14 20:11:37.067 23741-30248/ D/OkHttp: Server: Apache
12-14 20:11:37.067 23741-30248/ D/OkHttp: Set-Cookie: PHPSESSID=5bapa52gbuo5as4tmmjmavdqe5; path=/
12-14 20:11:37.067 23741-30248/D/OkHttp: Content-Length: 74
12-14 20:11:37.068 23741-30248/ D/OkHttp: Connection: Close
12-14 20:11:37.068 23741-30248/D/OkHttp: {"meta":{"code":1000,"errorMessage":"Please check the user's properties"}}
12-14 20:11:37.068 23741-30248/ D/OkHttp: <-- END HTTP (74-byte body)
12-14 20:11:37.068 23741-23741/ E/RetrofitCallback: onSuccess Retrofit callback response... {"meta":{"code":1000,"errorMessage":"Please check the user's properties"}} code ---> 200 isSuccess ---> true

**Correctly works:**

 D/DravaApplication: ---------------------End from 4-----------------------
D/OkHttp: --> PUT http://url/v1/trips/428 http/1.1
12-14 20:18:43.508 23741-30248/ D/OkHttp: Content-Type: application/json; charset=UTF-8
12-14 20:18:43.508 23741-30248/ D/OkHttp: Content-Length: 157
12-14 20:18:43.508 23741-30248/D/OkHttp: {"Distance":"0.0010570142","EndLatitude":"11.95622502037177","EndLongitude":"79.8267606040814","EndTime":"2016-12-14 19:56:38","MaxSpeed":"3","MinSpeed":"0"}
12-14 20:18:43.508 23741-30248/ D/OkHttp: --> END PUT (157-byte body)
12-14 20:18:43.508 23741-30248/ E/retrofit: Authorization header is added to the url.... NtC0A9rARDFENR5X84pw36JjDI8Qq8ijXF2lW3lZ
12-14 20:18:43.510 23741-23741/ E/SyncHelper: TrackPathObject size :0
12-14 20:18:43.603 23741-23741/ D/MapsActivity: onMapReleased
12-14 20:18:43.844 23741-23741/ D/MapsActivity: onMapTouched
12-14 20:18:44.115 23741-30248/ D/OkHttp: <-- 201 Created http://url/v1/trips/428 (606ms)
12-14 20:18:44.115 23741-30248/ D/OkHttp: Cache-Control: no-store, no-cache, must-revalidate
12-14 20:18:44.115 23741-30248/ D/OkHttp: Content-Type: application/json
12-14 20:18:44.115 23741-30248/D/OkHttp: Date: Wed, 14 Dec 2016 14:48:44 GMT
12-14 20:18:44.115 23741-30248/ D/OkHttp: Expires: Thu, 19 Nov 1981 08:52:00 GMT
12-14 20:18:44.115 23741-30248/ D/OkHttp: Pragma: no-cache
12-14 20:18:44.115 23741-30248/D/OkHttp: Server: Apache
12-14 20:18:44.115 23741-30248/ D/OkHttp: Set-Cookie: PHPSESSID=m2jph187jr0ba7trourbisesa2; path=/
12-14 20:18:44.115 23741-30248/ D/OkHttp: Content-Length: 128
12-14 20:18:44.115 23741-30248/ D/OkHttp: Connection: keep-alive
12-14 20:18:44.119 23741-30248/ D/OkHttp: {"meta":{"code":201,"dataPropertyName":"TripDetail"},"TripDetail":{"TripId":428},"notifications":["Trip updated successfully."]}

**Comment by JakeWharton** [comment]
I don't see the difference. Can you express this as a failing test case?
What makes you think Retrofit is causing the problem?

**Comment by prasanthmurugan** [comment]
ya for me too it does seen to be difference !! but in back office of the server log tracking the request is send as null as shown below

Request : -

Response :
{"meta":{"code":1000,"errorMessage":"Please check the user's properties"}}

**Comment by JakeWharton** [comment]
The logs indicate that Retrofit made the request with a body and OkHttp saw
it at least at the point where your logging interceptor is installed.
Perhaps another interceptor or an intermediate proxy is stripping the body,
but it's definitely not Retrofit.

**Comment by prasanthmurugan** [comment]
Solved the issue it was due to Retrofit !!
After changing the put method body to RequestBody object solved my issue .Actually i used the Java model class as the body initials since it cause the null request in the server after changing it to request body solved my problem
Where EndTrip =>Model class

  @PUT(DravaURL.TRIP_END)
    Call<ResponseBody> endTrip(@Path("Tripid") String Tripid, @Body EndTrip endTrip);


**Solution**
 @PUT(DravaURL.TRIP_END)
    Call<ResponseBody> endTrip(@Path("Tripid") String Tripid, @Body RequestBody endTrip);
 String json = new Gson().toJson(endTrip);
   RequestBody requestBody = RequestBody.create(MediaType.parse("application/json; charset=utf-8"), (json));

**Comment by JakeWharton** [comment]
I don't see any evidence that Retrofit was causing a problem there.

**Comment by prasanthmurugan** [comment]
i don't know but after changing it to request body solved my problem

**Comment by developergitch** [comment]
Had a similar issue and followed @prasanthmurugan approach of converting the object to RequestBody then sending the request body and it worked. Before then, while attaching a Java object with @Body i was not receiving the Object in my backend server.
