### ISSUE TITLE
Retrofit now supports grpc?

### ISSUE THREAD

**Issue by GuaiShu** [square/retrofit#2131]
Hello,
Our Android client has been using retrofit as a web framework,but the server project later to use gRPC as RPC framework.So i want to say, Retrofit now supports grpc? Thanks!

**Comment by JakeWharton** [comment]
While the Android client of gRPC is built on OkHttp's core, it uses a much lower-level request/response API than the normal one. It's also responsible for generating it's own high-level interface from a protocol buffer `service` instead if you defining it yourself as an `interface`. gRPC isn't HTTP and Retrofit issues HTTP requests only over OkHttp. Most server-side implementations of gRPC should be able to expose an HTTP "view" of their RPC API thus allowing you to use Retrofit, but you wouldn't actually be using gRPC in that case.
