### ISSUE TITLE
Failed to invoke public okhttp3.RequestBody() with no args

### ISSUE THREAD

**Issue by vishal901** [square/retrofit#2133]
I have pass post body in jsonarray getting this error,

 JSONObject jsonObject = new JSONObject();
        try {

            jsonObject.put( "vendor_id", "83" );
            jsonObject.put( "text", edtComment.getText().toString().trim() );
            jsonObject.put( "phone", edtNumber.getText().toString().trim() );
            jsonObject.put( "alt_phone", "1234567890" );
            jsonObject.put( "email", "vish@gmail.com" );
            jsonObject.put( "alt_email", "abc@gmail.com" );
            jsonObject.put( "city", "mehsana" );
            jsonObject.put( "at_time", "2106-11-11" );

// error this......line
            jsonObject.put( "info_to_be_sent", jsonarray );

            jsonObject.put( "complaint_type", "jhjf" );
        } catch (JSONException e) {
            e.printStackTrace();
        }

please help me....

**Comment by JakeWharton** [comment]
Please provide a full test case if you believe this is a problem with the library.

**Comment by jbm714060** [comment]
h

**Comment by dijiubuzhan** [comment]
maybe you can transfer the jsonarray  to String and try again
