### ISSUE TITLE
can support rxjava2.x.x(io.reactivex.Observable)

### ISSUE THREAD

**Issue by xybCoder** [square/retrofit#2137]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by xybCoder** [comment]
Caused by: java.lang.IllegalArgumentException: Unable to create call adapter for io.reactivex.Observable<com.xx.bean.xx>

**Comment by JakeWharton** [comment]
Support is already on master for the next release. You can use https://github.com/JakeWharton/retrofit2-rxjava2-adapter for now.
