### ISSUE TITLE
RxJava2 Retrofit adapter is not in Maven Central

### ISSUE THREAD

**Issue by Rangenn** [square/retrofit#2139]
Hi,

The Retrofit adapter for RxJava2 does not seem to be present in Maven Central, although its README claims that it should be accessible via

`compile 'com.squareup.retrofit2:adapter-rxjava2:latest.version'`

https://github.com/square/retrofit/tree/master/retrofit-adapters/rxjava2

**Comment by JakeWharton** [comment]
It was just added and will be in the next release.

**Comment by PaulWoitaschek** [comment]
When is the next release scheduled? Because of broken Completable support I can only RxJava 1.10 and because of missing RxJava2 support I cannot use a 2.x version of RxJava

**Comment by JakeWharton** [comment]
The latest RxJava is usable as long as you don't use Completable in your
interface. And even if you want to you can write a delegating CallAdapter
that creates an Observable and then calls toCompletable() on it.
