### ISSUE TITLE
rx.Completable.CompletableSubscribe.CompletableOnSubscribe not find in rxjava 1.2.4

### ISSUE THREAD

**Issue by ab503044120** [square/retrofit#2140]
compile 'com.squareup.retrofit2:adapter-rxjava:2.1.0'

rx.Completable.CompletableSubscribe.CompletableOnSubscribe not find in rxjava 1.2.4

what  is the compile version  of rxjava in your library

**Comment by JakeWharton** [comment]
This is fixed on master and will be in the next release.

**Comment by ab503044120** [comment]
thanks for your quick answer
