### ISSUE TITLE
[Feature Request] Replace part of URL

### ISSUE THREAD

**Issue by kolczak** [square/retrofit#2143]
I started adapting a big project I am working on to use Retrofit. Existing networking structure is very complicated so I am very excited to start using Retrofit. Great job guys!

It all worked great for me till the moment, when I wanted to implement GET query with filtering options.
I need to make a call like that:
```
.../read/something/Books?$filter(substringof('{filter}',Description)+or+substringof('{filter}',Code)+or+substringof('{filter}',Title))
```
and replace {filter} with string that user inputs.

I think the only solution to this is to use @Query annotation like that:
```
@GET("read/something/Books")
Call<ApiResponse<Book>> getFilteredBooks(@Query(value = "$filter", encoded = true) String filter);
```
and then call it like:
```
getFilteredBooks("substringof('"+filter+"',Description) or substringof('"+filter+"',Code) or substringof('"+filter+"',Title)");
```

Filtering part url is always same for any call I make to this API, therefore I wanted to place all filtering part in the @GET url and only replace {filter} with my custom string.
Then any call that future developer makes to this API would look like: `getFilteredIBooks(filter)`.
Is there any other way to achieve that result?

I think the only solution for that would be to create additional Interceptor to replace string in the url. Sounds however as overhead for simple use case.

**Comment by ylfzq** [comment]
I think it's the better way to achieve this:

```java
// define interface like this
@GET("read/something/Books")
Call<ApiResponse<Book>> getFilteredBooks(@QueryMap(encoded = true) MyFilter filter);
```

yes, use `@QueryMap`. And the type `MyFilter` is:

```java
// attention here, your class should extends HashMap(or other subclass of Map)
public class MyFilter extends HashMap<String, Object> {
  public MyFilter(String filter) {
  	put("$filter", "substringof('"+filter+"',Description) or substringof('"+filter+"',Code) or substringof('"+filter+"',Title)");
  }
}
```

after that, you can call your method like:

```java
getFilteredIBooks(new MyFilter(filter))
```

Is it much better?

**Comment by swankjesse** [comment]
No action to take on this.
