### ISSUE TITLE
Why is the return is onFailure？

### ISSUE THREAD

**Issue by DesignQu** [square/retrofit#2144]
There is a login interface.
Account password correctly returned to onResponse.
Password is incorrectly returned to onFailure.
status code is 200.
why?

**Comment by JakeWharton** [comment]
The exception would indicate why.

**Comment by DesignQu** [comment]
01-05 14:43:31.958 32137-3229/com.ld.smb D/OkHttp: --> POST http://xxx/index.php?m=member&c=api&a=do_login http/1.1
01-05 14:43:31.958 32137-3229/com.ld.smb D/OkHttp: Content-Type: application/x-www-form-urlencoded
01-05 14:43:31.958 32137-3229/com.ld.smb D/OkHttp: Content-Length: 38
01-05 14:43:31.958 32137-3229/com.ld.smb D/OkHttp: username=18505126172&password=11111112
01-05 14:43:31.958 32137-3229/com.ld.smb D/OkHttp: --> END POST (38-byte body)
01-05 14:43:32.188 32137-3229/com.ld.smb D/OkHttp: <-- 200 OK http://xxx/index.php?m=member&c=api&a=do_login (220ms)
01-05 14:43:32.188 32137-3229/com.ld.smb D/OkHttp: Server: nginx/1.6.2
01-05 14:43:32.188 32137-3229/com.ld.smb D/OkHttp: Date: Thu, 05 Jan 2017 06:43:31 GMT
01-05 14:43:32.188 32137-3229/com.ld.smb D/OkHttp: Content-Type: text/html; charset=utf-8
01-05 14:43:32.188 32137-3229/com.ld.smb D/OkHttp: Transfer-Encoding: chunked
01-05 14:43:32.188 32137-3229/com.ld.smb D/OkHttp: Connection: keep-alive
01-05 14:43:32.188 32137-3229/com.ld.smb D/OkHttp: X-Powered-By: PHP/5.5.21
01-05 14:43:32.188 32137-3229/com.ld.smb D/OkHttp: Vary: Accept-Encoding
01-05 14:43:32.188 32137-3229/com.ld.smb D/OkHttp: {"code":0,"info":"\u5bc6\u7801\u9519\u8bef","result":-5}
01-05 14:43:32.188 32137-3229/com.ld.smb D/OkHttp: <-- END HTTP (56-byte body)
01-05 14:43:32.188 32137-32137/com.ld.smb E/onFailure: onFailure

This is the log

Will callback to the onFailure method

**Comment by DesignQu** [comment]
Why is the return is onFailure

**Comment by JakeWharton** [comment]
Probably because JSON deserialize fails. The exception passed to onFailure
will indicate why.
