### ISSUE TITLE
Http RoutePlanner

### ISSUE THREAD

**Issue by gautamshrm3** [square/retrofit#2148]
Hi Team,

I need to implement route planner through Retrofit. Please help me 

Route planner exists in DefaultHttpClient.

**Comment by JakeWharton** [comment]
Retrofit is not an HTTP client, it's a high-level abstraction in creating requests for an HTTP client to execute. OkHttp is the recommended client and the one used by default so if you have a feature request for its behavior please file an issue on that project.
