### ISSUE TITLE
Retrofit in Module?

### ISSUE THREAD

**Issue by dhiwakarmani** [square/retrofit#2150]
I am trying to create a library module, where i want to implement Retrofit in it and my app will interact with this Module for Restful calls. Multiple Apps in future. So URL will change, Response class will change. So in the below example FriendResponse will be dynamic. Any reference or example? Thanks.

    Call<FriendResponse> call = service.getAPI().getFriends();
    call.enqueue(new Callback<FriendResponse>() { 
        @Override 
        public void onResponse(Call<FriendResponse> call, Response<FriendResponse> response) {
            System.out.println("whats the call 1: " + response.body().friendLocations.toString());
        } 
 
        @Override 
        public void onFailure(Call<FriendResponse> call, Throwable t) {
            System.out.println("whats the call 2: " + t.getMessage());
        } 
    });

**Comment by JakeWharton** [comment]
StackOverflow is the right place for usage questions, which I see you've already asked there too: http://stackoverflow.com/q/41598819/132047.

**Comment by dhiwakarmani** [comment]
Thanks Jake.
