### ISSUE TITLE
NPE when endpoint returns 204 without entity body

### ISSUE THREAD

**Issue by aitorvs** [square/retrofit#2154]
I am not an expert on HTTP but it is my understanding that it is not mandatory to return entity body with 204 responses. 

I am using Retrofit 2.1.0 and, I am getting an NPE in `retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:191)` when my endpoint returns 204 and no entity body.
Looking at the code it seems it might be a bug.

```
  Response<T> parseResponse(okhttp3.Response rawResponse) throws IOException {
    ResponseBody rawBody = rawResponse.body();

    // Remove the body's source (the only stateful object) so we can pass the response along.
    rawResponse = rawResponse.newBuilder()
        .body(new NoContentResponseBody(rawBody.contentType(), rawBody.contentLength()))
        .build();

    int code = rawResponse.code();
    if (code < 200 || code >= 300) {
      try {
        // Buffer the entire body to avoid future I/O.
        ResponseBody bufferedBody = Utils.buffer(rawBody);
        return Response.error(bufferedBody, rawResponse);
      } finally {
        rawBody.close();
      }
    }

    if (code == 204 || code == 205) {
      return Response.success(null, rawResponse);
    }
```

If there is no entity body, `rawBody` will be `null` and then `new NoContentResponseBody(rawBody.contentType(), rawBody.contentLength()))` will throw NPE. 

Am I missing something?

Thanks in advance.

**Comment by swankjesse** [comment]
It's more likely the body will be empty, not absent. If there is a problem please provide an executable test case.

**Comment by aitorvs** [comment]
Indeed, the body is absent. If I understand properly the [RFC](https://tools.ietf.org/search/rfc2616#section-10.2.5) that is a valid case, is it not? 
In such case, `parseResponse` will get a null `rawBody` and would call `.contentType()` on it throwing NPE like it is throwing on me (I got it from stack trace).

I just want to make sure that absent body on 204 response is in accordance to the standard. If you can confirm that, I will provide executable test case for it.

**Comment by JakeWharton** [comment]
We have tests showing that this works correctly: https://github.com/square/retrofit/blob/47cc621c7736cace218be341f9b480add64c9083/retrofit/src/test/java/retrofit2/CallTest.java#L371-L395. `rawBody` will never be `null` when coming from OkHttp.

**Comment by aitorvs** [comment]
What happens when an interceptor manipulates the response leaving a `null` body? 

In our use case, we encapsulate (and encrypt) all requests through a proxy. For lack of a better way to explain it, it is like if all our requests go through an encrypted pipe. To do that, we use a application `Interceptor` that encrypts and routes the requests, and parses/decrypts the responses.
Now when the decrypted response is 204 with no body, the `Interceptor` returns just that, 204 and `null` body. I guess that happens after OkHttp has ensure that no `null` is bubbled up to `rawBody` and, we are reverting all that so actually Retrofit can face a `null` `rawBody`.

What do you think it would be the proper solution. The RFC seems to be ok with `null` body for 204 responses so in principle our `Interceptor` is not doing anything 'wrong'. 
However we are kind of undoing all the good work OkHttp does ensuring `rawBody` is never `null`. 

I see two possible solutions, ensure Retrofit is OK with `null` `rawBody` or making sure that Retrofit/OkHttp users know that `Interceptor`s shall never surface a response with `null` body (maybe adding some words to the OkHttp documentation).
I am fine with either and I am happy to help if needed.

Does this make sense to you?

**Comment by swankjesse** [comment]
Don’t make interceptors that return responses will null bodies?

**Comment by swankjesse** [comment]
(_empty_ bodies are okay)

**Comment by aitorvs** [comment]
I fully agree with you, returning responses with empty bodies instead of `null` bodies is a good practice, as well as checking for `null`s on a API that explicitly allows for null params to be passed in.
I just tested it, it was the `Interceptor` returning `.body(null)` that made Retrofit throwing NPE.
