### ISSUE TITLE
Failed to invoke public okhttp3.RequestBody() with no args

### ISSUE THREAD

**Issue by LJame** [square/retrofit#2155]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by LJame** [comment]
@POST("home/indexThree")
    Call<RequestBody> getHomeinfo(@Body RequestBody info);

  private static MediaType JSON = MediaType.parse("application/json;charset=utf-8");
 Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(baseUrl)
//                .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                .addConverterFactory(GsonConverterFactory.create())
                .build();
        ResultBean bean=new ResultBean();
        bean.setClientType("ANDROID");
        bean.setCustomerId("");
        bean.setMac( RSASignature.sign(
                AppConfig.CLIENTTYPE,
                AppConfig.SIGN_KEY_S));
        RequestService requestService = retrofit.create(RequestService.class);
        Gson gson=new Gson();
        String s = gson.toJson(bean);
        RequestBody body = RequestBody.create(JSON, result.toString());
        Call<RequestBody> homeinfo = requestService.getHomeinfo(body);
        homeinfo.enqueue(new Callback<RequestBody>() {
            @Override
            public void onResponse(Call<RequestBody> call, Response<RequestBody> response) {
                System.out.println("onResponse>>"+response.body().toString());
            }

            @Override
            public void onFailure(Call<RequestBody> call, Throwable t) {
                System.out.println("onFailure>>"+t.getMessage());
            }
        });

**Comment by LJame** [comment]
What causes it？thx

**Comment by swankjesse** [comment]
This issue tracker is not the place for questions. If you want to ask how to do
something, or to understand why something isn't working the way you expect it to, use Stack
Overflow. https://stackoverflow.com/questions/tagged/retrofit
