### ISSUE TITLE
How to Contribute to retrofit?

### ISSUE THREAD

**Issue by silhan52** [square/retrofit#2157]
Here I want some FACTS about retrofit library,

- After clone the library from Github, how to build in my local environment?
- What IDE should I use?
- After make changes, How to Test with a my Android studio project?

**Comment by swankjesse** [comment]
Please ask usage questions on StackOverflow.

**Comment by ShabanKamell** [comment]
I can't find any answer on Google or Stackoverflow!

**Comment by sagar392** [comment]
Proper documentation is needed for setting up the environment .
