### ISSUE TITLE
Boolean being sent as string

### ISSUE THREAD

**Issue by asdasdfadgs** [square/retrofit#2162]
I have a Retrofit call that involves a boolean parameter:

    @FormUrlEncoded
    @POST("post")
    Call<BasicResponse> post(@Field("isPosting") Boolean isPosting);

And on the server side (Laravel PHP framework), I have the following validation:

    $validator = Validator::make($request->all(), [
        'isPosting' => 'required|boolean'
    ]);

    // If the validation passes...
    if ($isPosting) {
        //
    } else {
        //
    }

The boolean rule accepts `true, false, 0, 1, "0", and "1"`.

However, I noticed that the boolean is being sent as a string (`"true"` and `"false"`, instead of `true` and `false`).

How is this meant to be fixed?

**Comment by swankjesse** [comment]
Not sure what you’d like us to do here. There’s only one type in form encoding and it is strings.
