### ISSUE TITLE
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()

### ISSUE THREAD

**Issue by CodeDogDream** [square/retrofit#2166]
I use Rxjava2 with retrofit .It is right when the lenght of the paramete is short,When I make the length of the parameter longer.It report this error.I have this piece of code;
public void sendRequest(String url, MySubscriber<NetMessage> ss, HashMap<String, String> data) {
        Flowable<NetMessage> mObservable;
        final String[] paths = url.split("/");
        mObservable = myApi.getData(paths[0], paths[1], data);
        mObservable.observeOn(new HandlerScheduler(new Handler(Looper.getMainLooper()))).
                subscribeOn(Schedulers.io())
                .subscribe(ss);
    }
This is my Interface
private interface MyApi {
        @FormUrlEncoded
        @Headers(HttpData.Header)
        @POST("{path1}/{path2}")
        Flowable<NetMessage> getData(@Path("path1") String path1, @Path("path2") String path2, @FieldMap HashMap<String, String> data);
   }

**Comment by JakeWharton** [comment]
Retrofit only creates one `Handler` and it explicitly passes `Looper.getMainLooper()`: https://github.com/square/retrofit/blob/dec2f1a675a77c12bd28f8f9a25a45a9cc31888d/retrofit/src/main/java/retrofit2/Platform.java#L99. This error is coming from your code and not the library.
