### ISSUE TITLE
is it possible to show progress bar (percent) when downloading file in retrofit 2 asynchronously

### ISSUE THREAD

**Issue by bbincybbaby** [square/retrofit#2170]
is it possible to show progress bar (percent) when downloading file in retrofit 2 asynchronously

I already read solution u r provided, but am beginner in this field can u please elaborate it

**Comment by JakeWharton** [comment]
Please ask usage questions on StackOverflow with the 'retrofit' tag. The general strategy is to add `@Streaming` and use `ResponseBody` as your response type and then count the bytes as they go by.
