### ISSUE TITLE
Multipart Request using Retrofit 2 not working

### ISSUE THREAD

**Issue by amitmitra** [square/retrofit#2182]
I am trying to upload an image on the server using Retrofit2 but while executing the code its giving "java.net.SocketTimeoutException: connect timed out".

Previously I was using HttpClient, HttpPost, MultipartEntityBuilder. Previously I was using below code:

     public MultipartEntityBuilder reqEntity = MultipartEntityBuilder.create();
     try {
        HttpClient httpclient = getNewHttpClient();
        HttpPost httppost = new HttpPost(url);

        reqEntity.setMode(HttpMultipartMode.BROWSER_COMPATIBLE);
        Bitmap bitmap = BitmapFactory.decodeFile(filePath);
        if (bitmap != null) {
            ByteArrayOutputStream stream = new ByteArrayOutputStream();
            bitmap.compress(Bitmap.CompressFormat.JPEG, 75, stream);
            byte[] byteArray = stream.toByteArray();
            reqEntity.addBinaryBody("image[pic]", byteArray, ContentType.create("image/jpeg"), new File(filePath).getName());
            reqEntity.addPart("image[test_id]", new StringBody(testid));
            reqEntity.addPart("image[processing_log]", new StringBody(ProcessingLog));
            Dictionary<String, String> headers = GlobalAccess.getAppPref().getAuthHeaders();
            if (headers != null) {
                Enumeration<String> keys = headers.keys();
                while (keys.hasMoreElements()) {
                    String key = keys.nextElement();
                    httppost.addHeader(key, headers.get(key)); 
                }            
            }   

            httppost.setEntity(reqEntity.build());
            HttpResponse response = httpclient.execute(httppost);

            HttpEntity resEntity = response.getEntity();
            if (resEntity != null) {
                responseString = EntityUtils.toString(resEntity);
                System.out.println("PAGE :" + responseString);
            }
        }
    }
    catch (IOException e) {
        e.printStackTrace();

    }
Json Data which is being sent to the server by above request is:

{"image"=>{"pic"=>#, @original_filename="pic-8.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"image[pic]\"; filename=\"pic-8.jpg\"\r\nContent-Type: image/jpeg\r\n">, "test_id"=>"7813", "processing_log"=>"null"}}

Now I am trying to do the same thing using retrofit2 using below code:

           private static final String IMAGEUPLOADURL = "images";
           private FileUploadServiceAPI fileUploadServiceAPI;

         private interface FileUploadServiceAPI{
             @Multipart
             @POST(IMAGEUPLOADURL)
             Observable<ResponseBody> uploadFile(@Part MultipartBody.Part body,
                                        @Part("image[test_id]") RequestBody requestId,
                                        @Part("image[processing_log]") RequestBody requestProcessingLog);

            }

          public SendTestImageService(ServiceGenerator serviceGenerator){
                 fileUploadServiceAPI = serviceGenerator.createService(FileUploadServiceAPI.class);
         }

        public Observable<ResponseBody> uploadFile(File file, String id, String processingLog){
        RequestBody requestFile = RequestBody.create(MediaType.parse("image/jpeg"), file);
       MultipartBody.Part body = MultipartBody.Part.createFormData("image[pic]", file.getName(),      requestFile);
        RequestBody requestId = RequestBody.create(MediaType.parse("text/plain"), id);
        RequestBody requestProcessingLog = RequestBody.create(MediaType.parse("text/plain"),  processingLog);
           return  fileUploadServiceAPI.uploadFile(body, requestId, requestProcessingLog);
       }
But this doesn't seem to be working and giving exception (java.net.SocketTimeoutException: connect timed out) or (java.net.SocketException: Broken pipe)

**Comment by JakeWharton** [comment]
You can set a longer timeout by creating an `OkHttpClient.Builder` and passing whatever values you want to `connectTimeout` and `writeTimeout`. Then call `build()` and pass the resulting client to `client()` on `Retrofit.Builder`.

**Comment by amitmitra** [comment]
@JakeWharton 
Thanks for the help. Issue is resolved. 
Actual reason was on server side. Image Size limit was set to 1MB and I was trying to send 4 MB image. Thats why even after increasing connectTimeout and writeTimeout, I was getting java.net.SocketException: Broken pipe

**Comment by farmazon3000** [comment]
this may be related https://github.com/square/okhttp/issues/1895#issuecomment-611242495
