### ISSUE TITLE
[Feature Request] Modify Call or Request object before execute()

### ISSUE THREAD

**Issue by avatarandrij** [square/retrofit#2187]
I have one URL for first page (e.g http://some.host/resource?filter=1)
and completely different for other pages (e.g http://random-node.some.host/{pid}/cursor/{cursor_id}. It's just example. URL have almost random structure, based on position of node in network )
Request to first URL returns data and second URL. request to second URL returns the same response structure, and link to third URL and so on. 

```
interface Api{
    @GET("resource")
    Call<Resources> getResource(@Query String filter)
}
```
```

Api api = /* retrofit build */
// Get first page
Response<Resources> first = api.getResource("relevant").execute();
// I need something like this for next pages:
Response<Resources> second = api.getResource("doesn`t matter, because url overrriden").setUrl(first.nextPage).execute();
```

**Comment by JakeWharton** [comment]
This is what the `@Url` parameter annotation is for:
```java
interface Api{
    @GET("resource")
    Call<Resources> getResource(@Query String filter);
    @GET
    Call<Resources> getResourceNext(@Url String url);
}
```
Fundamentally these are two different HTTP requests so they require two different method declarations. You can encapsulate it behind your own paging `Call`-like object if you want to expose it as a unified API.
