### ISSUE TITLE
[Question]retrofit + RxAndroid+OKHttp, In a request define interface, How to define the request paramer?

### ISSUE THREAD

**Issue by saragitshare** [square/retrofit#2198]
1 define request  interface
`public interface IChartService {
@POST(URL.UserInfo_URL)
@FormUrlEncoded
Observable<String> getUserData(@Field("loginId") String loginId
  @FieldMap Map<String, Object> params);
}`

In the above interface,
(1) params  data is :
{"requestParams":{"interpolation":"NONE","callerId":"AAAA","period":"MAX"},"tags":{"A":"AAAAA"},"responseParams":
{"user":true,"formulaParse":true,"statistics":false}}

_**(2) params is "Request Paramers".**_
In our  web application had implemented  the API. The Request Paramers in Chrome is below.
![qa](https://cloud.githubusercontent.com/assets/17293753/22920458/1608a4be-f2d0-11e6-941c-0b5447a8dce0.png)

**3 QA:** 
In "@FieldMap Map<String, Object> params",
params deos not work.
What should I use? 
"@FieldMap Map<String, Object> params" -> "? params"

4 Reference:
(1) Android Lib info:
gradle dependencies config:
com.squareup.retrofit:retrofit:1.9.0
com.squareup.okhttp:okhttp:2.6
com.squareup.okhttp:logging-interceptor:2.6
com.squareup.okhttp:okhttp-urlconnection:2.6
(2) Android Studio 2.2
(3) Url:
http://json.parser.online.fr/

**Comment by swankjesse** [comment]
Please use StackOverflow for usage questions.
