### ISSUE TITLE
Is retrofit able to send multipart form data alongside nested json

### ISSUE THREAD

**Issue by zmwas** [square/retrofit#2201]
I am trying to send data that is in this form

```
{
    "id": ,
    "venue": {
        "id": ,
        "name": "",
        "city": "",
        "address": "",
        "rating": null,
        "point": null
    },
    "name": "",
    "time": "",
    "event_pic": null,
    "description": "",
    "event_type": "Movie",
    "invite_only": ,
    "free": ,
    "age_restriction": ,
    "ticket_price": ,
    "user": 
}
```
I have created the api interface like this:
 ```
  @Multipart
    @POST("api/events/")
    Observable<Event> postEvent(
            @Part("venue") RequestBody venue,
            @Part("event_pic") RequestBody image,
            @Part("name") RequestBody name,
            @Part("description") RequestBody description,
            @Part("time") RequestBody date,
            @Part("event_type") RequestBody type,
            @Part("invite_only") RequestBody isInviteOnly,
            @Part("age_restriction") RequestBody isAgeRestricted,
            @Part("free") RequestBody isFree,
            @Part("ticket_price") RequestBody ticketPrice

    );

```

```
        Gson gson = new Gson();

        MediaType json = MediaType.parse("application/json");
        MediaType image = MediaType.parse("image/*");
        MediaType text = MediaType.parse("text/plain");
        String venue_json ="venue:"+ gson.toJson(venue)+"";
        File file = new File(path);


        RequestBody requestBodyVenue = RequestBody.create(json, venue_json);
        RequestBody requestBodyImage = RequestBody.create(image, file);
        RequestBody requestBodyName = RequestBody.create(text, name);
        RequestBody requestBodyDate = RequestBody.create(text, date);
        RequestBody requestBodyDescription = RequestBody.create(text, description);
        RequestBody requestBodyType = RequestBody.create(text, type);
        RequestBody requestBodyAge = RequestBody.create(text, ageRestricted);
        RequestBody requestBodyFree = RequestBody.create(text, free);
        RequestBody requestBodyInviteOnly = RequestBody.create(text, inviteOnly);
        RequestBody requestBodyTicketPrice = RequestBody.create(text, ticketPrice);

        return apiService.postEvent(requestBodyVenue,  requestBodyImage, requestBodyName, requestBodyDescription,
                requestBodyDate, requestBodyType, requestBodyInviteOnly, requestBodyAge, requestBodyFree, requestBodyTicketPrice);
    
```
However it does not send the nested venue json object. Is this supported in retrofit?

**Comment by JakeWharton** [comment]
You need to create an object that represents the entire JSON object and use that as the sole `@Body` argument. Consider looking at http://www.jsonschema2pojo.org/ to create it for you.

A multi-part request is something very different and is usually used for uploading files or submitting complex forms.

For general usage questions please use StackOverflow with the 'retrofit' tag. We monitor it and can respond to these types of questions on there.

**Comment by mwshubham** [comment]
A sample/link/blog for using the same would be helpful for the future visitors. Thanks

**Comment by codetime79** [comment]
good

**Comment by lopamudraMohanty** [comment]
@zmwas  @JakeWharton Is it possible to save simple json string/object to gist using Retrofit ? If yes please share somecode snippet as an example .

**Comment by sraj0605** [comment]
@zmwas : did you find the solution, if so please share me the code sample, I am stuck with the same issue

**Comment by jimmytrivedi** [comment]
Any solution? https://stackoverflow.com/questions/62783444/why-does-multipart-pdf-is-not-able-to-upload-in-api-using-retrofit-2-in-android

**Comment by Narensanju** [comment]
I have a list like
       [{
       Imgstr:"obj as string", 
       Ingfile:file
       },{
       Imgstr:"obj as string", 
       Ingfile:file
       }
        ]

How can I upload them as multipart  x   if it is a single obj I am sending as  multipart body and file

**Comment by sanjeet007** [comment]
{"data": {
    "bookDate": "2021/03/01",
    "bookTime": "4:57 PM",
    "createdBy": {
        "firstName": "SaNjEeT",
        "role": "patient",
        "userId": "603cb8bd7a6f8018d09b2d15",
        "userName": "80055885868"
    },
    "currentlocation": {
        "address": "C 26, C Block, Sector 65, Noida, Uttar Pradesh 201301, India",
        "address1": "Ezimax  Ltd.",
        "address2": "Ezimax",
        "coordinates": [
            28.6104975,
            77.38590529999999
        ],
        "pincode": "201301",
        "type": "Point"
    },
    "emergencyContactNumber": "8004305868",
    "emergencyContactPerson": "SaNjEeT KuMaR",
    "isActive": true,
    "isCancelled": false,
    "isDeleted": false,
    "isPaid": false,
    "patient": {
        "address": "C 26, C Block, Sector 65, vt. Ltd., Ezimax, 201301",
        "addresses": [{
            "latitude": 28.6104975,
            "longitude": 77.38590529999999
        }],
        "email": "sanjeet@gmail.com",
        "firstName": "SaNjEeT",
        "lastName": "KuMaR",
        "mobile": "8003422868",
        "patientId": "603cb8bd7a6f8018d09b2d15"
    },
    "pinCode": "201301",
    "requestBy": {
        "email": "sanjeet@gmail.com",
        "firstName": "SaNjEeT",
        "lastName": "KuMaR",
        "mobile": "80wqq05868",
        "userId": "603cb8bd7a6f8018d09b2d15"
    },
    "serviceName": "Nursing",
    "serviceType": "Health",
    "service_id": "5f57380b2fbbe93ce527553a",
    "subServiceId": "102",
    "subServiceName": "injection"
}}

how to send this object in multipart form data and i have to send multiple images' i with this object
