### ISSUE TITLE
[Question] Does 500 internal server error get routed to onError in a subscriber?

### ISSUE THREAD

**Issue by liuzhen2008** [square/retrofit#2203]
I have a very basic retrofit setup like below.

```
@POST(deleteAll/book)
Observable<Response<Void>> deleteAllBook();

// retrofit.create blah blah blah

bookAPI.deleteAllBook()
.subscribeOn()
.observeOn()
.subscribe(new Subscriber<Response<Void>>() {
   ... onComplete
   ... onError
   ... onNext
})

```
I just ran into a issue where the onError in a subscriber does not get invoked if the server returns a 500 error response code.

Is it the normal behaviour? Or are there any special handling that needs to be done so that all none 2xx responses invokes the onError of a subscriber?

**Comment by JakeWharton** [comment]
By declaring a type of `Observable<Response<Void>>` you're indicating to Retrofit that you want `onNext` to be called with all HTTP responses and only call `onError` when the network or serialization fails. If you want non-200 status codes to call `onError` then you should declare `Observable<Void>`. If you need the information from `Response` but want a 5xx status code to error then you can either write a custom `CallAdapter` for this behavior (which is hard) or just apply a `map` operation that checks the status code and manually throws an `HttpException`.

**Comment by liuzhen2008** [comment]
@JakeWharton Thanks for the quick answer. I just have some more questions....

In my code, i have a couple types..

I have done `Observable<Boolean>` I notice this will call `onError` for 500 status code.

I have also done `Observable<MySimpleJSONModel>` and this does not call `onError`.

Are these all expected? What criteria needs to be met for `onError` to be invoked? Judging by your reply, network and serialization fail will trigger onError. So does that mean MySimpleJSONModel actually serialized properly given my 500 server error response?

I only have these two factories for the retrofit builder.
```
        builder.addConverterFactory(GsonConverterFactory.create());
        builder.addCallAdapterFactory(RxJavaCallAdapterFactory.create());

```

**Comment by JakeWharton** [comment]
Deserialization is not attempted on non-200 responses, only responses with
a 200 status code.
