### ISSUE TITLE
No compatibility between maven version and the examples and the git code

### ISSUE THREAD

**Issue by TonyHaddad91** [square/retrofit#2204]
I'm using Retrofit version 2.1.0
and I'm trying to use Error handling example but it uses a mthod from this class CallAdapter.Factory
which had one param in the version i have but on the get it has 2 params and i had to downgrade to version 2.0.2 in order to make it work

**Comment by NightlyNexus** [comment]
Are you referring to https://github.com/square/retrofit/commit/2a2196a619fd007828bf212aeab9742a6b318264?

The samples in master are based on the code in master.

You can check out the samples back at 2.1.0 here: https://github.com/square/retrofit/tree/fd2f2e24a9e3aae3f7f6a832da3bb6fc22362577/samples/src/main/java/com/example/retrofit

Or, you can use Retrofit 2.2.0's snapshots and use the samples from master.

**Comment by TonyHaddad91** [comment]
ya thats was my issue Thanks
