### ISSUE TITLE
annotation issue

### ISSUE THREAD

**Issue by kesava442** [square/retrofit#2207]
HTTP method annotation is required (e.g., @GET, @POST, etc.).

her i am using retrofit 1.9.0 and 2.1.0 

is there any problem to use both the versions in on project.

is there any conflicts between the two retrofits.

thanks in adv.

**Comment by swankjesse** [comment]
Use em both in the same project. Be careful about imports. Make sure you get around to upgrading everything soon. Living on two versions simultaneously is possible but not pleasant.
