### ISSUE TITLE
"RxJava2 Adapter" jar not found

### ISSUE THREAD

**Issue by kkunsue** [square/retrofit#2209]
- download link is broken
- can't find it in maven

**Comment by Gaket** [comment]
Hi! Maybe you have similar issue I had:
http://stackoverflow.com/questions/41140203/using-rxjava-2-and-retrofit-2-adapter-version-issue/41140375

P.s. I would be glad if it helps and you add you upvote my answer)

**Comment by koala99** [comment]
you should use this one:    compile 'com.jakewharton.retrofit:retrofit2-rxjava2-adapter:1.0.0'

**Comment by JakeWharton** [comment]
Dupe of #2151.
