### ISSUE TITLE
 HTTP method annotation is required (e.g., @GET, @POST, etc.).

### ISSUE THREAD

**Issue by kesava442** [square/retrofit#2211]
hi good morning,

        I am developing a project in android studio and i am facing the issue " HTTP method annotation is required (e.g., @GET, @POST, etc.).".

1) in my project i am using retrofit 1.9.0 and retrofit 2.1.0.
2) the project is having two modules.
3) when it is in debug it was running successfully.
4) while it was in release build it was crashing when i was installed in my mobile and i am getting the issue " HTTP method annotation is required (e.g., @GET, @POST, etc.).".
5) Is there any problem while using two retrofit versions in same project and it is having the two different modules.

can any one suggest me the issue clearly.

thanks in adv.

**Comment by JakeWharton** [comment]
The except message is pretty clear. You don't have an annotation for the HTTP method or you're using the one from the wrong version of Retrofit.

Please provide a self-contained sample or test case demonstrating the problem.

> Is there any problem while using two retrofit versions in same project and it is having the two different modules.

No.

**Comment by ylfzq** [comment]
I think it may be caused by Proguard especially when using proguard-android-optimize.txt

**Comment by ylfzq** [comment]
you can add below in your Proguard rules and retry
```
-keepclasseswithmembers class * {
    @retrofit2.http.* <methods>;
}
```

**Comment by vijayalakshmikk** [comment]
I added this in proguard file but still facing same issue

**Comment by fparkar** [comment]
> I am using implementation 'com.squareup.retrofit:retrofit:1.9.0' in build.gradle
> 
> and while generating proguard warning came so added -dontwarn retrofit.appengine.** in proguard.pro files.
> 
> Debug apk is working fine but release apk which is signed in is getting the above mentioned error. I tried adding
> -keepclasseswithmembers class * {
> @retrofit2.http.* ;
> }
> in proguard.pro file still facing the same problem. Please help ASAP

Did you solve this issue?

**Comment by Dhawalsllp** [comment]
I am phasing same issue and cant resolve using above -keepclasseswithmembers class * {
@retrofit2.http.* ;
} in proguard rule.
 Can anybody help me ASAP?

**Comment by 4dk1998** [comment]
-keepclasseswithmembers class * {
    @retrofit.http.* <methods>;
}

works for me

add in proguard-rules.pro
