### ISSUE TITLE
[Feature Request] @Query using converter instead of toString()

### ISSUE THREAD

**Issue by thebrokenpipe** [square/retrofit#2212]
I'm using service with query parameters of Json type. In every POJO class I need to override toString method and use Gson to parse to Json. Is there any solution to force converter to parse my @Query params?

**Comment by JakeWharton** [comment]
`@Query` uses a string converter to convert an object to a string, not just `toString()`. You can register a converter which matches your object type(s) and instead calls a JSON serializer.

We have a sample that does this: https://github.com/square/retrofit/blob/master/samples/src/main/java/com/example/retrofit/JsonQueryParameters.java
