### ISSUE TITLE
Lint error: 'InvalidPackage': java.lang.invoke in retrofit2.Platform.Java8

### ISSUE THREAD

**Issue by autonomousapps** [square/retrofit#2213]
From my lint report:

> ../../../../.gradle/caches/modules-2/files-2.1/com.squareup.retrofit2/retrofit/2.1.0/2de7cd8b95b7021b1d597f049bcb422055119f2c/retrofit-2.1.0.jar: Invalid package reference in library; not included in Android: java.lang.invoke. Referenced from retrofit2.Platform.Java8.
Priority: 6 / 10
Category: Correctness
Severity: Error
Explanation: Package not included in Android.

Maybe this is due to our project's language level being set to Java 8 (thanks to retrolambda)?

**Comment by JakeWharton** [comment]
No, this is from Retrofit's Java 8 support. Safe to suppress/ignore.

**Comment by autonomousapps** [comment]
Thanks! I did figure out how to suppress it. In case anyone else comes across this, it's quite simple:

In a file named `lint.xml`
```
<?xml version="1.0" encoding="UTF-8"?>
<lint>
    <issue id="InvalidPackage">
        <ignore regexp="retrofit2.Platform.Java8.*"/>
    </issue>
</lint>
```
