### ISSUE TITLE
couldn't get Headers in onFailure method in 2.0

### ISSUE THREAD

**Issue by shan117** [square/retrofit#2215]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by shan117** [comment]
there is no way to get response headers once web service api call fail.
In onFailure method the only exposed entity is Throwable.

**Comment by JakeWharton** [comment]
A failure means there was no response and thus no headers. If the call returned a non-200 status it would go to onResponse.

**Comment by shan117** [comment]
In the same scenario , using Volley, I get status code 200, while in retrofit it goes in onFailure and hence I cant check for network status code,response and response headers.
Actually , this is the scenario when session get expired.
