### ISSUE TITLE
[Feature Request] RxJavaCallAdapterFactory: specify common RxJava logic to be executed with each request

### ISSUE THREAD

**Issue by mohamedkomalo** [square/retrofit#2221]
**Scope**
retrofit2
[RxJavaCallAdapterFactory](https://github.com/square/retrofit/blob/master/retrofit-adapters/rxjava/src/main/java/retrofit2/adapter/rxjava/RxJavaCallAdapterFactory.java)

**Problem**
Need to specify common RxJava logic (ex: retrial mechanisms) to be executed with each request, It is possible to extract common logic in [Transformer](http://blog.danlew.net/2015/03/02/dont-break-the-chain/) and pass this transformer in `compose` for each Observable returned from a retrofit rest interface but there's no way to register this Transformer globally for all urls

This is a generalizaion of createWithScheduler, but instead of taking Scheduler, it will take Transformer instead.

**Solution**
- change RxJavaCallAdapterFactory, ResultCallAdapter and SimpleCallAdapter constructors to take Transformer<Object, Object> instead of Scheduler
- use the Transformer in the adapt function, this will include an unchecked cast
- add a new factory method
`public static <T> RxJavaCallAdapterFactory createWithTransformer(Transformer<T, T> transformer)`

- change the implementation of createWithScheduler to use the transformer supplied
```
    public static RxJavaCallAdapterFactory createWithScheduler(final Scheduler scheduler) {
        if (scheduler == null) throw new NullPointerException("scheduler == null");
        return createWithTransformer(new Transformer<Object, Object>() {
            @Override
            public Observable<Object> call(Observable<Object> objectObservable) {
                return objectObservable.subscribeOn(scheduler);
            }
        });
    }
```

Why not add type parameter to avoid the unchecked cast ?
will add unnecessary complexity as all RxJavaCallAdapterFactory, ResultCallAdapter and SimpleCallAdapter will include the type parameter while the type parameters of the Transformer is already checked in the factory method

Happy to do a pull request or implement it in a a separate module

**Comment by naturalwarren** [comment]
Why not just create your own `RxJavaRetryCallAdapterFactory` that delegates to `RxJavaCallAdapterFactory` using the `Retrofit.nextAdapter()` API?

**Comment by JakeWharton** [comment]
Yep, thanks @naturalwarren. That is the recommended approach for composing new behavior. There's a sample here you can copy and build upon: https://github.com/square/retrofit/blob/master/samples/src/main/java/com/example/retrofit/RxJavaObserveOnMainThread.java

**Comment by mohamedkomalo** [comment]
@naturalwarren 
I didn't know about this delegation capability, thanks for the info

@JakeWharton 
thanks for the sample, while the delegation capability can solve the problem, I find the Transformer approach provides a cleaner way for RxJava users to use.

comparing the two codes

**Using call adapter delegation**

```
  public static void main(String... args) {
    Scheduler observeOn = Schedulers.computation();

    Retrofit retrofit = new Retrofit.Builder()
        .baseUrl("http://example.com")
        .addCallAdapterFactory(new ObserveOnMainCallAdapterFactory(observeOn))
        .addCallAdapterFactory(RxJavaCallAdapterFactory.createWithScheduler(io()))
        .build();
  }

  static final class ObserveOnMainCallAdapterFactory extends CallAdapter.Factory {
    final Scheduler scheduler;

    ObserveOnMainCallAdapterFactory(Scheduler scheduler) {
      this.scheduler = scheduler;
    }

    @Override
    public CallAdapter<?, ?> get(Type returnType, Annotation[] annotations, Retrofit retrofit) {
      if (getRawType(returnType) != Observable.class) {
        return null;
      }

      //noinspection unchecked returnType checked above to be Observable.
      final CallAdapter<Object, Observable<?>> delegate =
          (CallAdapter<Object, Observable<?>>) retrofit.nextCallAdapter(this, returnType,
              annotations);

      return new CallAdapter<Object, Object>() {
        @Override public Object adapt(Call<Object> call) {
          return delegate.adapt(call).observeOn(scheduler);
        }

        @Override public Type responseType() {
          return delegate.responseType();
        }
      };
    }
  }
```

vs 

**taking transformer as a parameter**

```
public static void main(String... args) {
    Scheduler observeOn = Schedulers.computation();
    ObserveOnMainThreadTransformer transformer = new ObserveOnMainThreadTransformer(observeOn );

    Retrofit retrofit = new Retrofit.Builder()
        .baseUrl("http://example.com")
        .addCallAdapterFactory(RxJavaCallAdapterFactory.createWithTransformer(transformer)))
        .build();
  }

class ObserveOnMainThreadTransformer<T> implements Observable.Transformer<T, T> {
    private final Scheduler scheduler;

    ObserveOnMainThreadTransformer(Scheduler scheduler) {
        this.scheduler = scheduler;
    }
    
    @Override
    public Observable<T> call(Observable<T> tObservable) {
        return tObservable.observeOn(scheduler);
    }
}

```

However, the call adapter delegation allowed me to create an adapter that accepts a Transformer and compose this into the produced Observable so this is fine for me.

for anyone interested, here is the gist
https://gist.github.com/mohamedkomalo/8b804e2c9faa4b605f3fb633efe6e493
