### ISSUE TITLE
Is Retrofit aware of Gradle 3.4's incremental compilation?

### ISSUE THREAD

**Issue by EduardDopler** [square/retrofit#2222]
What kind of issue is this?
- [x] Question + Feature Request.

Having read [Gradle's new feature](https://blog.gradle.org/incremental-compiler-avoidance) which speeds up compilation by many times but only if annotations are implemented a special a way, I was wondering whether Retrofit allows Gradle doing those optimizations or whether it leads to recompiling every file where Retrofit annotations are present. (I am no expert in the compilation process.)

**Comment by JakeWharton** [comment]
Retrofit is not an annotation processor so it doesn't care nor effect anything about whatever build system you are using. All its work happens at runtime.
