### ISSUE TITLE
@Body & @Field via POST 

### ISSUE THREAD

**Issue by JulienRaad** [square/retrofit#2223]
Hello guys, 

I need to send a request in this form using POST 
{ "user_id":"x" "search": "xxx", "filter": {"country_code":["_id", "_id"], "city_id":["_id", "_id"], "industry":["_id", "_id"], "talent":["_id", "_id"], "skills":["_id", "_id"] }}

for "filter", i need to use @Body
for "user_id" and "search", i need to use @Field

How is this doable ? is is acceptable ? 
@FormUrlEncoded
@POST("")
Call<LoginResponse> globalUsersSearch(@Header("Authorization") String authorizationToken,
                                          @Field("user_id") String user_id, @Field("input") String searchInput,
                                          @Body("filter") Filter filter);

Thank you in advance

**Comment by JakeWharton** [comment]
You cannot mix `@Body` and `@FormUrlEncoded`. That request is a JSON object and not a form url-encoded request so you only need to make a single Java object representing the JSON and use that for the `@Body` parameter.

There's an example here: https://futurestud.io/tutorials/retrofit-send-objects-in-request-body.

**Comment by mainaviTech** [comment]
Hi Jake,
I got stuck with the same kind of issue. I am using simple web services which looks like test.com/serv.aspx?a=1&b=2&c=3 and its taking an encoded string in its body. I think I should go for @Field and @Body for this but as we cannot mix it so is there any other solution you could suggest to me?

**Comment by mainaviTech** [comment]
Hi Jake,
My requirement has been solved with @Query and @Body as it was related to the appending the parameters to the url and @Query does it superbly the way I want it :)

**Comment by yashgoscale** [comment]
> Hi Jake,
> My requirement has been solved with @query and @Body as it was related to the appending the parameters to the url and @query does it superbly the way I want it :)

Hey It's working fine, you save my day
