### ISSUE TITLE
Uploading File in binary using Multipart (Uploading file to WCF Service)

### ISSUE THREAD

**Issue by soodakshay** [square/retrofit#2224]
Hi All!

I am trying to upload a file via Retrofit 2 in binary using Multipart. The method on the .Net Server is accepting a binary file using multipart and it accept the file as a **Stream**. 
Please find the code that I am trying :

 File file = new File(mFilePath);
            byte[] buff = null;
            try {
                InputStream inputStream = new FileInputStream(file);
                buff = new byte[inputStream.available()];
                while (inputStream.read(buff) != -1) ;
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            }

            RequestBody requestBody = RequestBody.create(MediaType.parse("application/octet-stream"), buff);
            MultipartBody.Part part = MultipartBody.Part.createFormData("fileStream", file.getName(), requestBody);

            Retrofit retrofit = Utils.getInstance().getRetrofit();
            RetrofitApi retrofitApi = retrofit.create(RetrofitApi.class);
            Call<FileUploadResponse> fileUploadResponseCall = retrofitApi.uploadFilee(part);
            fileUploadResponseCall.enqueue(new Callback<FileUploadResponse>() {
                @Override
                public void onResponse(Call<FileUploadResponse> call, Response<FileUploadResponse> response) {
                    Logger.e("OnResponse=>", "onResponse");
                }

                @Override
                public void onFailure(Call<FileUploadResponse> call, Throwable t) {
                    Logger.e("onFailure=>", "onFailure");
                }
            });

    @Multipart
    @POST("TestUpload")
    Call<FileUploadResponse> uploadFilee(@Part MultipartBody.Part part);

I am not able to upload it but using Postman it can be uploaded. Please help.
It returns the following error response :
{"TestUploadResult":{"Message":{"Status":2,"message":"Value cannot be null.\u000d\u000aParameter name: bytes. StackTrace:    at System.IO.File.WriteAllBytes(String path, Byte[] bytes)\u000d\u000a   at iDox.Business.BLLFile.testFupload(Stream fileStream)"},"TempFileGUID":"00000000-0000-0000-0000-000000000000"}}

I am also attaching the Postman screenshot.
<img width="1440" alt="screen shot 2017-02-27 at 11 45 29 pm" src="https://cloud.githubusercontent.com/assets/16735792/23373636/e1b2b2b4-fd46-11e6-9a58-a26188e37be6.png">

Any help would be appreciated.
Thanks

**Comment by ylfzq** [comment]
Your read operation on InputStream is ERROR! Please check it by yourself, it's basic. After that I think you will get the success response. 
I guess your Server has a file check on uploaded file's content.
At last, read the whole file into memory is a bad practice.

**Comment by soodakshay** [comment]
@ylfzq the InputStream is working fine. I have checked this one without using multipart and it works well.

**Comment by ylfzq** [comment]
I mean your byte[] is invalid, you can output the value of this field and check

**Comment by JakeWharton** [comment]
It's not clear what action you want Retrofit to take here. What about the HTTP request is being serialized incorrectly?

**Comment by ApilPokhrel** [comment]
Same problem i want to convert inputstream to multipart
