### ISSUE TITLE
Run onFailure in Signed apk

### ISSUE THREAD

**Issue by mirmousaviii** [square/retrofit#2230]
I have error in build signed apk, and I use dontwarn for pass the build signed apk, But my application in signed mode (release) every time run onFailure from Callback.
Throwable message:
`platform java.util.LinkedHashMap<java.lang.String,a.a.a.j> annotated [] requires explicit JsonAdapter to be registered`

**Comment by JakeWharton** [comment]
Sounds like ProGuard is inlining your use of the `Map` interface to the `LinkedHashMap` concrete implementation but Moshi only supports the `Map` interface. Add a `-keep` rule to prevent it from optimizing your Retrofit interface.

**Comment by JakeWharton** [comment]
You'll have to consult a forum for ProGuard support on how to disable the optimization.
