### ISSUE TITLE
Support default methods on interfaces in Java 9.

### ISSUE THREAD

**Issue by JakeWharton** [square/retrofit#2234]
http://openjdk.5641.n7.nabble.com/Proposal-java-lang-reflect-Proxy-and-default-methods-tp273894p300256.html

**Comment by MONIKA-KUMAR-JETHANI** [comment]
@JakeWharton @swankjesse  Can I work on this?

**Comment by netomi** [comment]
I had the exact same need for my library to correctly handle default methods in dynamic proxies. I extracted the code from spring which solves this in a clean and efficient way:

https://github.com/netomi/uom/blob/master/src/main/java/org/netomi/uom/util/Proxies.java

Contrary to spring, I use the ConcurrentReferenceHashMap from Doug Lea which uses weak references on the keys / values instead on the entries, which makes more sense and results in longer-lived entries. If you would be interested I can create a pull request to include that into retrofit.

Btw. thanks a lot for this library, it gave me a lot of great insights into dynamic proxies.

**Comment by JakeWharton** [comment]
We shipped this a loooong time ago.
