### ISSUE TITLE
@Body converter problem ?

### ISSUE THREAD

**Issue by songsh** [square/retrofit#2235]
i use @Body CompanySearchBean bean,  
the paramter is :
{"isRecommend":0,"sortNumber":0,"limitId":0,"size":10,"userCode":"2b213b2d-c848-4467-8c98-bcac2d068d91","which":1}

how to convert to parameter 
userCode=2b213b2d-c848-4467-8c98-bcac2d068d91&isRecommend=1.1

**Comment by JakeWharton** [comment]
That format is a `@FormUrlEncoded` body for which you can make multiple parameters which are `@Field`s.
```java
@GET("whatever") @FormUrlEncoded
Call<String> endpoint(@Field("userCode") String userCode, @Field("isRecommended") String isRecommended);
```
Please use StackOverflow for usage questions.

**Comment by songsh** [comment]
thank, i dont want  the 
Call<String> endpoint(@Field("userCode") String userCode, @Field("isRecommended") String isRecommended);
i want a converter covert to @body to  Field, how?

**Comment by JakeWharton** [comment]
You'd have to write your own Converter which looked at the fields of the
supplied type and turned them into OkHttp's FormBody type.

**Comment by songsh** [comment]
i solve the problem,
http://www.cnblogs.com/songsh/p/6526989.html
