### ISSUE TITLE
Thread not continuing after enqueuing call

### ISSUE THREAD

**Issue by MrThreepwood** [square/retrofit#2237]
I have a project that uses multiple endpoints in the app, all of them work except the PUT fields request, and I can't see a difference.

`@POST("v1/auth/login")
    Call<ItemWrapper<AuthResponse>> postLogin(@Body Auth auth);

    @GET("v1/company/fields")
    Call<ListWrapper<Field>> getFields(@Query("last-update") String lastSyncTime);

    @PUT("v1/company/fields")
    Call<ListWrapper<Field>> updateFields(@Query("last-update") String lastSyncTime, @Body List<Field> fields);

    @POST("/v1/feedback")
    Call<Response> sendFeedback(@Body Feedback feedback);`

When debugging I hit the breakpoint for this: 
appService.updateFields(lastSync, fieldsToUpdate).enqueue(new SimpleRetrofitCallback<>(callback));

And the thread (main thread) does not continue. No breakpoint is hit inside any of the interceptors, the entire app just hangs. If I do it synchronously the call goes through as expected and things mostly work fine. I am getting no errors, no crashes, no network logs. I have no idea what's going on. I am currently on Retrofit 2.2

***EDIT***
Sorry, found the issue. I was unaware that the initial processing for the request occurs on the same thread. GSON was running out of memory attempting to serialize the objects (after a long time). Not sure why this worked when I did it on the main thread. Probably an issue with Realm (I was attempting to feed realm objects directly to the call rather than copying them from realm).

**Comment by JakeWharton** [comment]
Without a test case or sample to reproduce the behavior it's going to be impossible to know what's going on here.
