### ISSUE TITLE
Question 怎么获取 relativeUrl

### ISSUE THREAD

**Issue by guangit** [square/retrofit#2244]
Request toRequest(Object... args) throws IOException {
    RequestBuilder requestBuilder = new RequestBuilder(httpMethod, baseUrl, relativeUrl, headers,
        contentType, hasBody, isFormEncoded, isMultipart);

    @SuppressWarnings("unchecked") // It is an error to invoke a method with the wrong arg types.
    ParameterHandler<Object>[] handlers = (ParameterHandler<Object>[]) parameterHandlers;

    int argumentCount = args != null ? args.length : 0;
    if (argumentCount != handlers.length) {
      throw new IllegalArgumentException("Argument count (" + argumentCount
          + ") doesn't match expected count (" + handlers.length + ")");
    }

    for (int p = 0; p < argumentCount; p++) {
      handlers[p].apply(requestBuilder, args[p]);
    }

    return requestBuilder.build();
  }

**Comment by JakeWharton** [comment]
Please ask usage questions on StackOverflow with the 'retrofit' tag. It also isn't clear what the question is. Providing more detail like the expected behavior and the actual behavior will help get an answer.

**Comment by Rajanna87** [comment]
Pop up

**Comment by guangit** [comment]
啥意思 @Rajanna87
