### ISSUE TITLE
retrofit2 addHeader() not work

### ISSUE THREAD

**Issue by chanzhao** [square/retrofit#2249]
## when i use retrofit2 ,okhttp3. 

   @POST("chan/Login")
    @Multipart
    Call<ResponseBody> post( @Part MultipartBody.Part file);

##but i use
response .newBuilder()
                    .addHeader("Charsert", "UTF-8")

##is not work

if i use @Headers("Charsert: UTF-8") is work

**Comment by JakeWharton** [comment]
Please provide a failing test case. Bug reports with tests get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
