### ISSUE TITLE
create Custom Call (request) method using retrofit ,error show when proguard is enable 

### ISSUE THREAD

**Issue by pawarlalit29** [square/retrofit#2250]
method working fine when we are not using pro-guard ,after pro-guard enable in app show following error 

java.lang.NullPointerException: Attempt to invoke virtual method 'okhttp3.Request$Builder okhttp3.Request.newBuilder()' on a null object reference

**Comment by JakeWharton** [comment]
Please provide the full stacktrace or a sample that reproduces the problem. Or both.

**Comment by pawarlalit29** [comment]
thanks and sorry, issue was found in okhttp lib
