### ISSUE TITLE
Base url automatically modified

### ISSUE THREAD

**Issue by ramkia613** [square/retrofit#2251]
My base url http://192.168.1.2:8080/myfile/path/

@POST("/module/apiName")
Call<String> .....

But while making request, request url is  http://192.168.1.2:8080/module/apiName <br> but expected url is http://192.168.1.2:8080/myfile/path/module/apiName

**Comment by egor-n** [comment]
You have to add a slash at the start of your path to make it relative:

```java
@POST("/module/apiName")
```

**Comment by ramkia613** [comment]
@egor-n  I already sent like as you told. Modified my question.

**Comment by egor-n** [comment]
My bad, see [this answer](http://stackoverflow.com/a/32356916/1348215).

**Comment by ramkia613** [comment]
@egor-n thank you.
