### ISSUE TITLE
@Body request, the server returns the prompt: the parameter is empty

### ISSUE THREAD

**Issue by jarylan** [square/retrofit#2254]
public interface RetrofitApiService {
      @POST(NetUrlConstant.URL_LOGIN)
       Call<LoginCallBean> login(@Body LoginParam param);
}
As mentioned above, the server prompts the parameters to be empty。
But I used the following way：
public interface RetrofitApiService {
    @FormUrlEncoded
    @POST(NetUrlConstant.URL_LOGIN)
    Call<LoginCallBean> login(@Field("username") String phone, @Field("password") String password);
}
Can return data normally；
My request body：
public class LoginParam implements Serializable{

    public String username;
    public String password;

    public LoginParam(String username, String password) {
        this.username = username;
        this.password = password;
    }

}
What 's wrong ？  Thank you .

**Comment by JakeWharton** [comment]
Please ask usage questions on StackOverflow. If you think there's a bug, a test case or sample app that demonstrates the problem and expected outcome is required.
