### ISSUE TITLE
How about Backend?

### ISSUE THREAD

**Issue by Exerosis** [square/retrofit#2259]
It would be so cool to see a Retrofit backend service method. It would be amazing for developers that want to very quickly create a client-server relationship. Here's an example of what I mean:  https://hastebin.com/ohubifiyav.cs Because of the javarx it's really almost as if you are just calling methods on a local instance. 

It's just a thought, I have no idea how retrofit works as of now so it might be highly incompatible.

**Comment by JakeWharton** [comment]
The annotations and design of the library is entirely that from the client perspective and while the trivial cases map to the same method signature on the server, complex ones do not. Most specifically, there's a lack of request object that lets you get arbitrary headers or URL information that are not specified by the signature.

We have no plans to try and support both sides. JAX-RS is a better option for a similar server-side component. Even better is programmatically generating your client and server interfaces based on a shared schema like gRPC or swagger.
