### ISSUE TITLE
gsonbuilder.registerTypeAdapter is not valid in converter-gson

### ISSUE THREAD

**Issue by dhcn** [square/retrofit#2262]
``` 
        GsonBuilder builder = new GsonBuilder();
        builder.registerTypeAdapter(new TypeToken<List<Review>>(){}.getType(),new Topic.ReviewListDeserializer());
        Gson gson = builder.create();
        Topic topic = new Topic();
        topic.setContent("topic222");
        Review review1 = new Review();
        review1.setContent("re1111");
        topic.getReviews().add(review1);
        Review review2 = new Review();
        review2.setContent("re1112");
        topic.getReviews().add(review2);
        String jsonstr = gson.toJson(topic);
        topic = gson.fromJson(jsonstr,Topic.class);
        Log.e("--->",String.valueOf(topic.getReviews().size()));
``` 
code above is valid
but when i register adpater to gson object used in retrofit conveter factory,it is  invalid.

What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by JakeWharton** [comment]
Please provide a failing test case.

**Comment by dhcn** [comment]
```     GsonBuilder builder = new GsonBuilder();
        builder.excludeFieldsWithModifiers(Modifier.FINAL, Modifier.TRANSIENT, Modifier.STATIC);
        builder.registerTypeAdapter(new TypeToken<List<Review>>(){}.getType(),new Topic.ReviewListDeserializer());//it is not valid in retrofit converter
        Gson gson = builder.create();
```
```
public class Topic {
    private String content;
    private Integer id;
    private ArrayList<Picture> pictures=new ArrayList<>();
    public ArrayList<Review> reviews = new ArrayList<>();

    public ArrayList<Picture> getPictures() {
        return pictures;
    }

    public void setPictures(ArrayList<Picture> pictures) {
        this.pictures = pictures;
    }

    public ArrayList<Review> getReviews() {
        return reviews;
    }

    public void setReviews(ArrayList<Review> reviews) {
        this.reviews = reviews;
    }
}
```
I find that ReviewListDeserializer  is not invoked when that type appears in retrofit context.
but I use gson directly，that Deserializer is valid.



        Retrofit mretrofit = new Retrofit.Builder()
                .baseUrl(restBaseURL)
                .addConverterFactory(GsonConverterFactory.create(gson))
                .client(httpClient)
                .build();
