### ISSUE TITLE
[Question] NoClassDefFoundError: Failed resolution of: Lokhttp3/internal/platform/Platform;

### ISSUE THREAD

**Issue by liuzhen2008** [square/retrofit#2266]
I have a weird situation with my gradle packages.

I recently added a third party jar into my ./lib. The jar itself contains okHttp version 3.4.1.

In my build.gradle, I added this line:
    `compile files('./libs/woogeenconference.jar')`

And this line has been in that file forever.
    `com.squareup.okhttp:okhttp:2.3.0'`

I notice that when I try to run the application, it will give me a dupliateEntry in one of okHttp class file. So I just removed the 2.3.0 import, and replaced all okHttp stuff with the newer version in my app. I also added this in build.gradle:
```
configurations.all {
    exclude module: "okio"
    exclude module: "okhttp"
}

```

After that, the app does build and run. But then I am running in to the issue specified in the title.

And I am totally confused and don't know what to do. (Prior to adding that third party library, everything worked.)

I also attached the file in case you are interested.

**Comment by liuzhen2008** [comment]
[Archive.zip](https://github.com/square/retrofit/files/886873/Archive.zip)

**Comment by JakeWharton** [comment]
Retrofit relies on OkHttp 3 which you are forcing to be excluded and thus it can't be found at runtime. Despite you saying that the jar includes OkHttp 3.4.1 that does not seem to be the case or this would not have happened.

**Comment by liuzhen2008** [comment]
@JakeWharton  But I was able to use objects like OkHttpClient throughout my app? And I see they come from okHttp

**Comment by JakeWharton** [comment]
They come from OkHttp 2.x

**Comment by liuzhen2008** [comment]
![image](https://cloud.githubusercontent.com/assets/2473837/24568984/231837e8-1632-11e7-93c8-14a5d66a431d.png)

**Comment by liuzhen2008** [comment]
Is this not okHttp3?

**Comment by JakeWharton** [comment]
No. OkHttp 3's package name is okhttp3.*. That looks like a pre-release
version that won't be compatible with anything.

**Comment by liuzhen2008** [comment]
@JakeWharton  I see. Good to know. Looks like the 3rd party people screwed up with their okhttp version eh? I can see it is indeed not 3.4.1. It was 3.0.1 my bad.

**Comment by JakeWharton** [comment]
Yes. For one, if they're bundling dependencies they should be jarjar-ing
them into their own 'internal' package so as to not cause conflicts with
other libraries. Or, alternatively, they should publish their library to a
Maven repository where it can depend on OkHttp and other libraries in a
pom.xml file to be automatically downloaded and resolved like a normal
library.

I would go try to yell at the library publisher to correct what they're
doing, especially if you're paying for it.

**Comment by liuzhen2008** [comment]
Thanks. Issue resolved!
