### ISSUE TITLE
java.lang.NoClassDefFoundError: rx.Observable

### ISSUE THREAD

**Issue by AAverin** [square/retrofit#2268]
Hey guys.
Got the following problem: 
```
java.lang.NoClassDefFoundError: rx.Observable
at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
at java.lang.Class.getDexCacheType(Class.java:479)
at java.lang.reflect.ArtMethod.getDexCacheType(ArtMethod.java:236)
at java.lang.reflect.ArtMethod.getReturnType(ArtMethod.java:185)
at java.lang.reflect.Method.getReturnType(Method.java:184)
at java.lang.Class.getDeclaredMethods(Class.java:801)
at java.lang.reflect.Proxy.getMethodsRecursive(Proxy.java:303)
at java.lang.reflect.Proxy.getMethods(Proxy.java:292)
at java.lang.reflect.Proxy.getProxyClass(Proxy.java:165)
at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:232)
at retrofit2.Retrofit.create(Retrofit.java:132)

Caused by: java.lang.ClassNotFoundException: Didn't find class "rx.Observable" on path: DexPathList[ .... ]
```

Happens if I run the app on Android 5.0.1 with
Kotlin 1.1.0 + Retrofit 2.2.0 + RxJava 1.2.0 + Jackson-Converter 2.2.0

The only indication of something similar happening is in Realm library:
https://github.com/realm/realm-java/issues/1963

Solution there is to include RxJava in the project, which is already there in my case.
Might also be somehow related to https://github.com/FasterXML/jackson-databind/issues/1070

I have a jar library compiled with Kotlin with data classes, that are shared between backend and android projects. Backend also uses Jackson. Jackson dependency is not included in library jar. And in Android code no classes extend library classes.

Will be thankful for any clues on where to search for solution.
Also, everything runs fine on Android 6.0.1

**Comment by AAverin** [comment]
Localized the issue to converter-jackson. Switching to converter-gson solves the problem.
Issue is limited to Android 5.X 

The underlying cause might be:
I have a Kotlin compiled jar library with jackson-annotated models. They are shared between backend and android project. Probably, parsing those models on Android 5.X with Jackson causing the problem.

**Comment by artem-zinnatullin** [comment]
I think you have multidex issue, Jackson is much heavier than Gson in terms
of methods count.

**Comment by AAverin** [comment]
@artem-zinnatullin Multidex is enabled and I'm running 5.0, should be fine

**Comment by artem-zinnatullin** [comment]
Some manufacturers still use dalvik on 5.x. Are you sure you use Multidex
support library?

**Comment by AAverin** [comment]
Yes. Tested on Samsung Galaxy S4 and Nexus 5. Stock firmware.
Multidex gets disabled at start due to 5.0

**Comment by artem-zinnatullin** [comment]
Ah, I see ART in stacktrace. Do you use instant run?

**Comment by AAverin** [comment]
By default in latest Android studio.
Will try without it, thanks for the tip.

**Comment by AAverin** [comment]
Ok, runs fine without Instant Run.
@artem-zinnatullin do you think there can be any workaround for the problem with Instant Run enabled?

**Comment by artem-zinnatullin** [comment]
Idk, we don't use it

**Comment by KingWu** [comment]
better solution here
https://realm.io/docs/java/latest/#jackson-databind

**Comment by GitHubMurt** [comment]
Go to https://realm.io/docs/java/latest/#jackson-databind
and create fake Observable class
