### ISSUE TITLE
Order XML Elements SOAP Request

### ISSUE THREAD

**Issue by Laura198610** [square/retrofit#2269]
Hi everyone,

I'm using retrofit with my soap services in my Android App and I have problems with a Header Element in my xml request. The request is something like:
```
<Envelope>
<Header>
<...>
</Header>
<Body>
<..>
</Body>
</Envelope>
```
I have header and body created correct but when I send the request, *body* is sending before *header* and my server is returning me an error because the order its important in this request. I send a request like:
```
<Envelope>
<Body>
<..>
</Body>
<Header>
<...>
</Header>
</Envelope>
```

I've tried to use `@Order` annotation in my class like this:
```
@Root(name = "Envelope")
@Order (elements = {"Header", "Body"})
public class Envelope
```

but it doesn't work.

How can I order my xml elements? Is there any way to do this?

Thanks.

**Comment by JakeWharton** [comment]
This would be a question for the XML serialization library you are using, not Retrofit. Retrofit has no control over how your objects are serialized to XML other than just delegating to some other library to do it.

If you're using the simplexml converter then you can ask on StackOverflow or on the SimpleXML project page (which I think is on SourceForge).

**Comment by vladaman** [comment]
Ordering XML elements do work. Make sure you use SimpleXML framework

```
OkHttpClient httpClient = builder.build();
  Retrofit retrofit2 = new Retrofit.Builder()
  .baseUrl(BASE_URL)
  .addConverterFactory(SimpleXmlConverterFactory.create(getSerializer()))
  .client(httpClient)
  .build();

// will produce sorted XML first with Header, then Body
@Root(name = "Envelope")
@org.simpleframework.xml.Order (elements = {"Header", "Body"})
public class Envelope {

    @Element(name = "Body")
    public Body body;

    @Element(name = "Header")
    public Header header;

}
```
