### ISSUE TITLE
how to use setChunkedStreamingMode(1024) by retrofit???

### ISSUE THREAD

**Issue by jimUpdate** [square/retrofit#2270]
```
HttpURLConnection con = (HttpURLConnection) url.openConnection();
con.setChunkedStreamingMode(1024*2);
```

**Comment by JakeWharton** [comment]
Retrofit is not an HTTP client so it doesn't natively support chunked transfer encoding. For OkHttp, the underlying HTTP client, to send a chunked transfer, the content length of the `RequestBody` needs to be reported as -1. 

I wrote a sample which demonstrates how to do this: https://github.com/square/retrofit/blob/master/samples/src/main/java/com/example/retrofit/ChunkingConverter.java

**Comment by jimUpdate** [comment]
very thankful！
