### ISSUE TITLE
Opencart

### ISSUE THREAD

**Issue by coolhaka** [square/retrofit#2273]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by coolhaka** [comment]
I have an opencart 1.5.6.4 based Ecommerce website and i got a Ecommerce app script from these two sites:-
 http://www.openshop.io 
& 
https://github.com/hiteshsahu/ECommerce-App-Android

Now i want a opencart 1.5.6.4 based api extension to make an app from the above script. Please give me the tutorial about to make an api extension or give me the api extension which you create from retrofit.

**Comment by JakeWharton** [comment]
This issue tracker is for bug reports and feature requests only. I'm not sure the appropriate forum for your question but it is not this one. If you have a specific problem with Retrofit that can be demonstrated with a failing test case or sample then we're able to take a look, but we don't provide general help.
