### ISSUE TITLE
Android wear 2 support

### ISSUE THREAD

**Issue by jaumard** [square/retrofit#2274]
What kind of issue is this?
 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I see under the documentation that now Android Wear can make network calls https://developer.android.com/training/wearables/data-layer/network-access.html, it would be nice if retrofit can be used in wear devices directly. I don't think it's the case actually. 

Thanks :)

**Comment by iNoles** [comment]
I think that is outside of retrofit's scope.

**Comment by JakeWharton** [comment]
How does it fail? Got a full stacktrace?
