### ISSUE TITLE
DELETE request rejects a @Body parameter

### ISSUE THREAD

**Issue by w9jds** [square/retrofit#2278]
The API I am trying to hit has a spec where you pass in a JSON body on a DELETE request so that it removes the sent records. However, when this request goes to fire Retrofit is rejecting it saying that a body isn't allowed. Is there a specific reason for this?

Also, to note. The method type is mandatory and checked.

**Comment by JakeWharton** [comment]
The spec is ambiguous here so we forbid it which I detail here: https://github.com/square/retrofit/issues/330#issuecomment-25179351

You can use `@HttpMethod(method = "DELETE", path = "..", hasBody = true)` to work around this.

**Comment by w9jds** [comment]
Thanks, talking to the API developers now and they will be moving to a path/query system and mark that it is preferred in their specs for future reference.
