### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by guediagael** [square/retrofit#2279]
[Bug Report] Can't directly send a base64 encoded JPEG image into @query or @querymap. Retrofit sends back a 400 bad request. The request should be sent as a parameter, not body.

**Comment by JakeWharton** [comment]
> Retrofit sends back a 400 bad request.

No, that's your server sending back a 400.

If you believe this is a Retrofit problem, please provide a failing test case. Bug reports with tests get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

**Comment by ylfzq** [comment]
@guediagael You might exceed the limit of url length, so the server's framework like ngix forbidden the request
