### ISSUE TITLE
Upload file in IntentService , app freeze UI

### ISSUE THREAD

**Issue by tuananhdtu** [square/retrofit#2280]
Hi

In Activity

`Intent intent = new Intent(UploadRecordingActivity.this, UploadService.class);
        intent.putExtra(UploadService.RECORDING, currentRecording);
        startService(intent);`

In IntentService, onHandleIntent method

` File file = new File(mp3File);
            ProgressRequestBody requestFile = new ProgressRequestBody(file, UploadOldService.this);
            MultipartBody.Part body = MultipartBody.Part.createFormData("uploadedfile", file.getName(), requestFile);
            Call<ResponseBody> response = Server.service.fileUpload(Constants.DEFAULE_UPLOAD_SERVER, body);
            try {
                final String onlineVocalUrl = new String(response.execute().body().bytes());`

When it call fileUpload APi, app freeze UI , i don't interact with my finger in UI.

How to upload file in service but UI not freeze ?
Anybody help?

**Comment by JakeWharton** [comment]
This is a usage question which is generally more appropriate for StackOverflow. GitHub issues are reserved for bug reports with test cases or samples, or new feature requests. You can use the 'retrofit' tag which is monitored by us and many library users. Feel free to link the asked question back here on the issue.
