### ISSUE TITLE
sometimes upload audio file broken

### ISSUE THREAD

**Issue by gewuxy** [square/retrofit#2281]
I use this code to upload audio file (about 500K) ,but it sometimes upload failed caused by file broken.
`

        AudioAttachment attachment = (AudioAttachment)msg.getAttachment();
        String path = attachment.getPath();
        MultipartBody.Part body = null;
        if(TextUtils.isEmpty(path)){
            ToastUtil.showToast(getActivity(),getString(R.string.audio_file_not_exist));
            return false;
        }
        File file = new File(path);
        RequestBody requestFile = RequestBody.create(MediaType.parse("audio/*"), file);
        body = MultipartBody.Part.createFormData("audio_file", file.getName(), requestFile);

        HashMap<String,RequestBody> params = new HashMap<>();
        params.put("lecture_id",RequestBody.create(MediaType.parse("multipart/form-data"), mId + ""));
        params.put("need_encode",RequestBody.create(MediaType.parse("multipart/form-data"), String.valueOf(false)));
        params.put("duration",RequestBody.create(MediaType.parse("multipart/form-data"),attachment.getDuration() + ""));
        params.put("reply_message_id",RequestBody.create(MediaType.parse("multipart/form-data"),msg.getReplyMsgId() + ""));
        params.put("uuid",RequestBody.create(MediaType.parse("multipart/form-data"),msg.getUuid()));
        params.put("ts",RequestBody.create(MediaType.parse("multipart/form-data")
                ,String.valueOf(System.currentTimeMillis())));

        Subscription subscription = ApiService.getInstance().sendAudioMessage(body,params).subscribe(new HttpObserver<IMMessage>() {
            @Override
            protected void onError(ApiException ex) {
                ex.printStackTrace();
                ToastUtil.showToast(getActivity(),ex.getMsg());
                onSendMessageFail(msg);
            }

            @Override
            public void onNext(IMMessage imMessage) {
                onSendMessageSuccess(msg);
            }
        });
        mCompositeSubscription.add(subscription);

       compile ('com.squareup.retrofit2:retrofit:2.1.0'){
            exclude module: 'okhttp'
        }

    compile 'com.squareup.retrofit2:adapter-rxjava:2.1.0'
    compile 'com.squareup.retrofit2:converter-gson:2.1.0'
    compile 'io.reactivex:rxjava:1.0.14'
    compile 'io.reactivex:rxandroid:1.0.1'
`

**Comment by JakeWharton** [comment]
This is a usage question which is generally more appropriate for StackOverflow. GitHub issues are reserved for bug reports with test cases or samples, or new feature requests. You can use the 'retrofit' tag which is monitored by us and many library users. Feel free to link the asked question back here on the issue.
