### ISSUE TITLE
some user cannot be used when network is 4G at retrofit:2.2.0 version but work fine at retrofit:2.1.0

### ISSUE THREAD

**Issue by Z644912187** [square/retrofit#2284]
some user cannot be used when network is 4G at retrofit:2.2.0 version but work fine at retrofit:2.1.0

**Comment by JakeWharton** [comment]
Retrofit knows nothing about networks. It's a high-level wrapper around the OkHttp HTTP client. Any problem you are having with networks not working is at a level far lower than Retrofit and it's a level over which Retrofit has no control.

**Comment by Z644912187** [comment]
I noticed that the problem was due to that retrofit2.1.0 with okhttp3.3.0/okhttp3.4.1 ,but retrofit2.2.0 with okhttp3.6.0. So I have to continue to use retrofit2.1.0.
