### ISSUE TITLE
go to onFailure when I login with incorrect data but my server response when I login with incorrect data

### ISSUE THREAD

**Issue by KimBunhong** [square/retrofit#2288]
go to onFailure when I login with incorrect data but my server response when I login with incorrect data

I have problem when I use retrofit to login to server with post method. It will response prefect when I insert the data that already have in server and the server will response status true but when I insert data that have no in server it will go to onFailure method but server response status false when have no data. Is this problem come from my coding or other? How can I fix it?

**Comment by JakeWharton** [comment]
This is a usage question which is generally more appropriate for StackOverflow. GitHub issues are reserved for bug reports with test cases or samples, or new feature requests. You can use the 'retrofit' tag which is monitored by us and many library users. Feel free to link the asked question back here on the issue.

It sounds like your server response is failing to parse which is propagating to onFailure.
