### ISSUE TITLE
java.net.ProtocolException: expected 688 bytes but received 8192

### ISSUE THREAD

**Issue by Praveen-Pro** [square/retrofit#2291]
I'm getting this exception randomly while uploading file to server

```
--> POST file_url http/1.1
Content-Type: multipart/form-data; boundary=6ffd316b-2cab-4882-a9e9-64ded315ad53
Content-Length: 82607
--6ffd316b-2cab-4882-a9e9-64ded315ad53
Content-Disposition: form-data; name="description"
Content-Transfer-Encoding: binary
Content-Type: multipart/form-data; charset=utf-8
Content-Length: 28
description
--6ffd316b-2cab-4882-a9e9-64ded315ad53
Content-Disposition: form-data; name="file"; filename="file.csv"
Content-Type: text/csv
Content-Length: 81920
File Data //Removed

--6ffd316b-2cab-4882-a9e9-64ded315ad53--
--> END POST (82607-byte body)
<-- HTTP FAILED: java.net.ProtocolException: expected 687 bytes but received 8192
```

**Comment by Praveen-Pro** [comment]
I'm getting this exception randomly while uploading file to server


--> POST file_url http/1.1
 Content-Type: multipart/form-data; boundary=6ffd316b-2cab-4882-a9e9-64ded315ad53
 Content-Length: 82607
 --6ffd316b-2cab-4882-a9e9-64ded315ad53
 Content-Disposition: form-data; name="description"
 Content-Transfer-Encoding: binary
 Content-Type: multipart/form-data; charset=utf-8
 Content-Length: 28
 description
 --6ffd316b-2cab-4882-a9e9-64ded315ad53
 Content-Disposition: form-data; name="file"; filename="file.csv"
 Content-Type: text/csv
 Content-Length: 81920
    File Data //Removed

 --6ffd316b-2cab-4882-a9e9-64ded315ad53--
 --> END POST (82607-byte body)
 <-- HTTP FAILED: java.net.ProtocolException: expected 687 bytes but received 8192

**Comment by naturalwarren** [comment]
That seems like a problem with your server, not with Retrofit. Can you provide a test case that reproduces this problem?

**Comment by JakeWharton** [comment]
This exception comes from OkHttp and not Retrofit. Furthermore, the
exception occurs because the server indicated that it would return only a
few bytes but returned much more. There's nothing Retrofit can do here, and
if you can reproduce it with a test case in OkHttp as a bug we can fix it,
but I suspect it's just your server returning incorrect data and OkHttp
being strict about it.
