### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException Exception thrown on Scheduler.Worker thread. Add `onError` handling.

### ISSUE THREAD

**Issue by seojiju** [square/retrofit#2297]
Hi there.
I am gratefully using your retrofit2 and rxjavacalladapterfactory.
But there is one issue with using
Occasionally, a subscriber can not unsubscribe during network communication.

for example -)
I should call Observable.unsubscribeOn(Schedulers.io()), retrofit will unsubscribe at the end of a http-request.

In RxJavaCallAdapterFactory of retrofit-rxjava-adapter

it actions like this. (It does not work properly.)
`
if (!subscriber.isUnsubscribed()) {
    subscriber.onCompleted();
}
`
But when subscriber is a SafeSubscriber, it'll call unsubscribe finally.

I use retrofit2 2.1.0 and okhttp3 3.6.0 and adapter-rxjava 2.1.0
and http://bytes.babbel.com/en/articles/2016-03-16-retrofit2-rxjava-error-handling.html#
this link error handler

Why is that? Please help me.

**Comment by JakeWharton** [comment]
Can you provide a test case that demonstrates the problem? Otherwise I'm not sure how I can fix the problem without knowing exactly what's going on. There's a bunch of test cases for RxJava 1 and 2 in their respective modules.
