### ISSUE TITLE
Resume API callback when internet is back.

### ISSUE THREAD

**Issue by Mehdi-android** [square/retrofit#2300]
Hello, I want to know if retrofit provides any facility to resume API callback when internet is available back. Actually I am implementing API call and suddenly in middle of call my internet goes off, now when my internet is back then I want to resume my API callbaack and get the results. 

Ty

**Comment by swankjesse** [comment]
Retrofit doesn't track this, and doing so has lots of bad consequences so it's unlikely we’ll ever implement this.
