### ISSUE TITLE
How to send Multipart Request without file. (

### ISSUE THREAD

**Issue by CrazyStoneJy** [square/retrofit#2301]
@Multipart
    @POST("comController/feedBack.do")
    Observable<BaseWrapper> feedback(@QueryMap Map<String, String> map, @Part MultipartBody.Part file);

this request file maybe is null,how to resolve.

**Comment by ylfzq** [comment]
Just pass null to the file parameter, it will be ok. Retrofit will skip all null values besides values in Map.

**Comment by JakeWharton** [comment]
Thanks @ylfzq !

**Comment by CrazyStoneJy** [comment]
@ylfzq I pass file paramter with null, throw RuntimeException(at least send a part),I confused

**Comment by oky2abbas** [comment]
@ylfzq  @JakeWharton
*I do the same but the exception `Multipart body must have at least one part`. It happens to me.*
