### ISSUE TITLE
How to give dynamic query 

### ISSUE THREAD

**Issue by jsroyal** [square/retrofit#2308]
https://api.github.com/search/users?q=location:india+language:python
 for folling result

But How do I give query in dynamic?

public interface Service {
    @GET("/search/users")
    Call<ItemResponse> getItems(
            @Query("q") String location,
            @Query("language") String language
    );
}

I try this way but could not get answer?

**Comment by jsroyal** [comment]
repos Filters users based on the number of repositories they have.
location Filter users by the location indicated in their profile.
language Search for users that have repositories that match a certain language.
created Filter users based on when they joined.
followers Filter users based on the number of followers they have.

More about it. 
![image](https://cloud.githubusercontent.com/assets/10773353/25647169/5054a6be-2fdd-11e7-9d36-a95d212f09af.png)

**Comment by JakeWharton** [comment]
This is a usage question which is generally more appropriate for StackOverflow. GitHub issues are reserved for bug reports with test cases or samples, or new feature requests. You can use the 'retrofit' tag which is monitored by us and many library users. Feel free to link the asked question back here on the issue.

**Comment by jsroyal** [comment]
@JakeWharton I try through the tags 'retrofit' but what I need, I did not get it.Here is clearly define my issue please look once.
It okay to close but please resolved before it

**Comment by JakeWharton** [comment]
If you create a string or an object with a toString of
"language:java+location:india" you can pass that to a "q" query paramter.

**Comment by jsroyal** [comment]
yes that is the alter way but giving according to the [example](https://futurestud.io/tutorials/retrofit-optional-query-parameters) 
How to do standard request?

**Comment by milanmadubasha** [comment]
@get("/search/code")
Call getItems(

);

Sir how can i dynamically do code search ?
