### ISSUE TITLE
Question: GsonResponseBodyConverter UnsupportedCharsetException: utf8mb4

### ISSUE THREAD

**Issue by boyfox** [square/retrofit#2312]
Hi everyone!
I have following problem with parsing response, anybody know how to add support utf8mb4 character encoding/decoding to gson converter in retrofit?

Thanks in advance!

**Comment by swankjesse** [comment]
That isn't a valid charset name. You probably want just UTF-8. (utf8mb4 is what MySQL calls UTF-8.)
