### ISSUE TITLE
Using ApiError

### ISSUE THREAD

**Issue by MahdiPishguy** [square/retrofit#2314]
how can i install `ApiError` to use `ErrorHandler` for  handling retrofit errors?

**Comment by JakeWharton** [comment]
`ErrorHandler` doesn't exist in Retrofit 2.

This is a usage question which is generally more appropriate for StackOverflow. GitHub issues are reserved for bug reports with test cases or samples, or new feature requests. You can use the 'retrofit' tag which is monitored by us and many library users. Feel free to link the asked question back here on the issue.
