### ISSUE TITLE
Server can not receive params

### ISSUE THREAD

**Issue by AndroidKiven** [square/retrofit#2316]
@JakeWharton 
@Multipart 
@POST("direct_v2/threads/broadcast/text/") 
Observable<String> sendTextMsgToOthers(@Part("recipient_users") String recipient_users,
                                       @Part("client_context") String client_context,
                                       @Part("thread_ids") String thread_ids,
                                       @Part("text") String text,
                                       @Header("Content-Type") String boundary)

I don't know why? Server is php and interface is ok!

**Comment by JakeWharton** [comment]
This is a usage question which is generally more appropriate for StackOverflow. GitHub issues are reserved for bug reports with test cases or samples, or new feature requests. You can use the 'retrofit' tag which is monitored by us and many library users. Feel free to link the asked question back here on the issue.
