### ISSUE TITLE
Always getting content-length 0 in response

### ISSUE THREAD

**Issue by harshmalhotra** [square/retrofit#2319]
What kind of issue is this?

 
![screenshot 43](https://cloud.githubusercontent.com/assets/16223713/25887668/a5cb487a-3580-11e7-9e79-747e2fdef1ec.png)

**Comment by JakeWharton** [comment]
I'm not sure why you think this is a Retrofit problem. That log message comes from the OkHttp logging interceptor which is just reporting whatever value your server returns for the header.
