### ISSUE TITLE
Uploading large video file throws OutOfMemoryException

### ISSUE THREAD

**Issue by MichaelReyes** [square/retrofit#2320]
Hello,

Here is my code for uploading videos,

`ServiceGenerator serviceGenerator = new ServiceGenerator(context, Constants.SERVER_URL, HttpLoggingInterceptor.Level.NONE);
        CommandAPI commandAPI = serviceGenerator.createService(CommandAPI.class);

        User user = User.getUserFromSharedPreferences(context);

        RequestBody videoBody = RequestBody.create(MediaType.parse("video/*"), file);
        MultipartBody.Part archiveFile = MultipartBody.Part.createFormData("video", file.getName(), videoBody);

        LocationCoordinates locationCoordinates = LocationCoordinates.getLocationInfoFromSharedPreferences(context);

        String address = Utils.getAddressFromLatLng(context,locationCoordinates.getLatitude(), locationCoordinates.getLongitude());

        EventIntelligence eventIntelligence = EventIntelligence.getEventIntelligenceFromSharedPreferences(context);

        if(address.equalsIgnoreCase(""))
            address = "Address not found.";

        RequestBody accesscode = serviceGenerator.createPartFromString(user.getAccessCode());
        RequestBody accel = serviceGenerator.createPartFromString(String.valueOf(eventIntelligence.getAcceleration()));
        RequestBody alert_battery_level = serviceGenerator.createPartFromString(String.valueOf(eventIntelligence.getBatteryLevel()));
        RequestBody alert_gps_files = serviceGenerator.createPartFromString("");
        RequestBody alert_media_files = serviceGenerator.createPartFromString("");
        RequestBody alert_speed = serviceGenerator.createPartFromString("");
        RequestBody course = serviceGenerator.createPartFromString("");
        RequestBody direction = serviceGenerator.createPartFromString(eventIntelligence.getDirection());
        RequestBody elevation = serviceGenerator.createPartFromString("");
        RequestBody event_id = serviceGenerator.createPartFromString(String.valueOf(user.getEventId() + 1));
        RequestBody lat = serviceGenerator.createPartFromString(String.valueOf(locationCoordinates.getLatitude()));
        RequestBody lng = serviceGenerator.createPartFromString(String.valueOf(locationCoordinates.getLongitude()));
        RequestBody level = serviceGenerator.createPartFromString("");
        RequestBody location_now = serviceGenerator.createPartFromString(address);
        RequestBody online_status = serviceGenerator.createPartFromString("");

        HashMap<String, RequestBody> map = new HashMap<>();
        map.put("accesscode", accesscode);
        map.put("accel", accel);
        map.put("alert_battery_level", alert_battery_level);
        map.put("alert_gps_files", alert_gps_files);
        map.put("alert_media_files", alert_media_files);
        map.put("alert_speed", alert_speed);
        map.put("course", course);
        map.put("direction", direction);
        map.put("elevation", elevation);
        map.put("event_id", event_id);
        map.put("lat", lat);
        map.put("lng", lng);
        map.put("level", level);
        map.put("location_now", location_now);
        map.put("online_status", online_status);

        Call<ResponseBody> call = commandAPI.uploadVideo(archiveFile, map);

        try {
            Response<ResponseBody> response = null;
            response = call.execute();
            ResponseBody responseBody = response.body();

            user.setEventId(user.getEventId() + 1);
            user.save(context);

            Log.d("MIKE", "responseBody: " + new Gson().toJson(responseBody));

        } catch (Exception e) {
            e.printStackTrace();
        }`

` @Multipart
    @POST("upload/video")
    Call<ResponseBody> uploadVideo(
            @Part MultipartBody.Part video,
            @PartMap() Map<String, RequestBody> partMap
    );`

When uploading videos with small file size (e.g. 16Mb) upload is ok. But when uploading videos with large file size (e.g. 80Mb)  call.execute() throws OutOfMemoryException.

Is there a way or work around to upload videos with large file size like 100+Mb? or maybe to chunk files when uloading? Thanks.

**Comment by swankjesse** [comment]
Please use StackOverflow for usage questions.
