### ISSUE TITLE
Allow @QueryParam to be optional.

### ISSUE THREAD

**Issue by manuelq** [square/retrofit#2321]
When using the @QueryParam.  Documentation says: 
"A {@code null} value for the map, as a key, or as a value is not allowed."  

Could it be possible to have this function as the @Query annotation where if the value/map is null the param is not added?

**Comment by JakeWharton** [comment]
Do you mean `@QueryMap`?

There should be no reason to have a null collection. You can pass an empty map if there are no parameters to be added.

There also was a reason to disallow null values in the map, but I'd have to dig it up as i've since forgotten it.

**Comment by manuelq** [comment]
Yup your right.  Just tried this out an empty map works for me.
