### ISSUE TITLE
Possible Bug: Multipart Form Data boundary being changed in MultipartBody.part

### ISSUE THREAD

**Issue by REWmitenko** [square/retrofit#2326]
To be honest, I don't know if this is a bug or if this is WAI.

I have posted the issue in Stackoverflow [here](http://stackoverflow.com/questions/43926941/android-retrofit-2-2-multipart-request-server-not-parsing-data-as-it-is-encoded).

Essentially, I have a MultipartBody.part field inside a @Multipart request that is being encoded with a different boundary token than the boundary defined in the request header. In fact this MultipartBody.part field is encoding all of its header data as if this was part of the request. The server is unable to parse any data sent inside this embedded boundary. 

I have read the [specs](https://tools.ietf.org/html/rfc1867#section-7) and it doesn't look like different boundary tokens are acceptable.

**Comment by JakeWharton** [comment]
Multipart is provided by OkHttp's `MultipartBody`. However, it's not a bug in the library, but instead you have nested multipart bodies. You can visualize this if I add a synthetic indent:
```
Accept-Encoding:gzip
Authorization:Basic cmV3OnJldw==
Connection:Keep-Alive
Content-Length:861
Content-Type:multipart/form-data; boundary=f963340b-1f3d-432a-974c-d13249e26b55
Host:dev.xxxxxxx.com
Request Payload
--f963340b-1f3d-432a-974c-d13249e26b55
    Content-Type: multipart/mixed; boundary=dc925bca-93dd-4c22-9def-e4095d0e95a1
    Content-Length: 278

    --dc925bca-93dd-4c22-9def-e4095d0e95a1
        Content-Disposition: form-data; name="to[0][id]"
        Content-Length: 4

        3145
    --dc925bca-93dd-4c22-9def-e4095d0e95a1
        Content-Disposition: form-data; name="to[0][type]"
        Content-Length: 4

        lead
    --dc925bca-93dd-4c22-9def-e4095d0e95a1--

--f963340b-1f3d-432a-974c-d13249e26b55
    Content-Disposition: form-data; name="message"
    Content-Transfer-Encoding: binary
    Content-Type: application/json; charset=UTF-8
    Content-Length: 5

    "dda"
--f963340b-1f3d-432a-974c-d13249e26b55
    Content-Disposition: form-data; name="subject"
    Content-Transfer-Encoding: binary
    Content-Type: application/json; charset=UTF-8
    Content-Length: 7

    "asdas"
--f963340b-1f3d-432a-974c-d13249e26b55--
```
