### ISSUE TITLE
[Feature] Add request body support with HTTP DELETE

### ISSUE THREAD

**Issue by jiachenning** [square/retrofit#2328]
I use the @FormUrlEncoded with HTTP DELETE, and got message `FormUrlEncoded can only be specified on HTTP methods with request body (e.g., @POST).`

Http document does not forbid nor encourage use request body in HTTP DELETE.

Could retrofit add the HTTP DELETE's request body support in future?

**Comment by JakeWharton** [comment]
The spec is ambiguous here so we forbid it which I detail here: https://github.com/square/retrofit/issues/330#issuecomment-25179351

You can use `@HttpMethod(method = "DELETE", path = "..", hasBody = true)` to work around this.
