### ISSUE TITLE
Add Kotlin Unit Converter

### ISSUE THREAD

**Issue by consp1racy** [square/retrofit#2329]
As per https://medium.com/square-corner-blog/square-open-source-loves-kotlin-c57c21710a17 please add support for `kotlin.Unit` type so consumers don't have to return `Call<Void>` in Kotlin code. Cheers!

**Comment by JakeWharton** [comment]
This is really easy. Can do.

**Comment by JakeWharton** [comment]
Only downside is we have to check for `kotlin.Unit` using its qualified name. This means if you use ProGuard or jarjar to rewrite the Kotlin stdlib it won't work.

The alternative to that is a separate dependency and explicit converter you have to install.

**Comment by consp1racy** [comment]
Dammit, didn't account for rewrites.

Can we slap more things together to a Kotlin artifact to make it worthwhile?

**Comment by JakeWharton** [comment]
Hmm like what?

**Comment by consp1racy** [comment]
Phew...

`retrofit.create<MyService>()` instead of `retrofit.create<MyService>(MyService::class.java)`

that's all I could find right now. I guess other candidates for extension functions could be worth exploring.

**Comment by JakeWharton** [comment]
Yep, good one. I'll think about it more.

**Comment by swankjesse** [comment]
Will it be compiled to `Void` in the classfile?

**Comment by JakeWharton** [comment]
No it stays as Unit. Unlike Void which can only be null, Unit can only be
Unit.INSTANCE.

**Comment by consp1racy** [comment]
`Nothing?` can be `null` but that's counterintuitive to use.

**Comment by JakeWharton** [comment]
BTW this is trivial to add yourself if you don't want to wait for official support:
```kotlin
object UnitConverterFactory : Converter.Factory() {
  override fun responseBodyConverter(type: Type, annotations: Array<out Annotation>,
      retrofit: Retrofit): Converter<ResponseBody, *>? {
    return if (getRawType(type) == Unit::class.java) UnitConverter else null
  }

  private object UnitConverter : Converter<ResponseBody, Unit> {
    override fun convert(value: ResponseBody) {
      value.close()
    }
  }
}
```

**Comment by jaredsburrows** [comment]
@JakeWharton About the proguad comment, it looks like `Class.forName` calls might work: https://www.guardsquare.com/en/proguard/faq:

> Does ProGuard handle Class.forName calls?
> Yes. ProGuard automatically handles constructs like Class.forName("SomeClass") and SomeClass.class. The referenced classes are preserved in the shrinking phase, and the string arguments are properly replaced in the obfuscation phase.
> 
> With variable string arguments, it's generally not possible to determine their possible values. They might be read from a configuration file, for instance. However, ProGuard will note a number of constructs like" "(SomeClass)Class.forName(variable).newInstance()". These might be an indication that the class or interface SomeClass and/or its implementations may need to be preserved. The developer can adapt his configuration accordingly.

Could we leverage `Class.forName` in `retrofit2.Utils.getRawType`? Source of `Unit` here: https://github.com/JetBrains/kotlin/blob/master/core/builtins/src/kotlin/Unit.kt.

**Comment by JakeWharton** [comment]
If coroutines ever hits 1.0 we could eat https://github.com/gildor/kotlin-coroutines-retrofit into a Kotlin module.

**Comment by JakeWharton** [comment]
Actually we probably want to expose `Deferred<T>` in addition to awaiting a `Call<T>`.
