### ISSUE TITLE
Collision with DatabindingComponent

### ISSUE THREAD

**Issue by b22n** [square/retrofit#2333]
Retrofit: 2.2.0~
Databinding: enabled
Gradle: 2.3.1~

There is some issue when using the databinding with Retrofit 2.2.0~.
I don't know the reason but gradle can't find the android.databinding.DataBindingComponent. 
It was fine with 2.1.0.

**Comment by PromanSEW** [comment]
Retrofit: 2.3.0
Databinding: Enabled
Gradle: 2.3.2
All works fine

**Comment by b22n** [comment]
@PromanSEW Have you been tested with the custom component which implements DataBindingComponent?

**Comment by PromanSEW** [comment]
@b22n No. I use layouts with data binding injections and `DataBindingUtil` for binding them only

**Comment by JakeWharton** [comment]
This is unlikely to be a Retrofit problem. You'll have better luck asking on StackOverflow with the 'retrofit' and 'databinding' tags and include _a lot_ more info.
