### ISSUE TITLE
Okhttp client and its interceptors ignored in MockRetrofit

### ISSUE THREAD

**Issue by khafan** [square/retrofit#2340]
I'm trying to test the behavior of an OkHttp' `Interceptor`. I create a `Retrofit` with an OkHttp client and the interceptor and then a mocked instance of my Service API using NetworkBehaviour and MockRetorfit. But when calling methods of mocked Service, the interceptor is being ignored (the intercept method never gets called when debbuggin.)

```Java
private BehaviorDelegate<MyRestApi> delegate;

@Before
public void setup() {
    Retrofit retrofit = new Retrofit.Builder()
        .baseUrl(BacktoryClient.BASE_URL)
        .client(new OkHttpClient.Builder().addInterceptor(new RetryWithRefreshedTokenInterceptor()).build())
        .build();

    NetworkBehavior behavior = NetworkBehavior.create();
    MockRetrofit mockRetrofit = new MockRetrofit.Builder(retrofit)
        .networkBehavior(behavior)
        .build();

    delegate = mockRetrofit.create(MyRestApi.class);
}

@Test
public void testRetryWithRefreshedToken() throws Exception {
    SimpleMock apiMock = new SimpleMock(delegate);
    Response<SomeApiResponse> response = apiMock.someApiCall(<parameters>).execute();
    // assert part
}
```

_THIS SHOULD BE ASKED IN STACKOVERFLOW...._ 
Yeah, I've [asked](http://stackoverflow.com/q/43953069/1660013) it earlier with more info on what I'm trying to achieve and why I don't test the interceptor in isolation.

I'm not even sure its a bug and saw many pages about testing interceptors and mocking retrofit not finding a suitable answer.

If it's not a bug, how can I test an interceptor which uses a retrofit's Service methods internally?

**Comment by JakeWharton** [comment]
MockRetrofit is about stubbing your API before it gets to the HTTP client.
If you want the full HTTP stack you should use something like MockWebServer
in OkHttp to simulate a server and allow customizing the requests and
responses to whatever you'd like.

**Comment by khafan** [comment]
Hmm, I've tried the MockWebServer and think that `Dispatcher` is my thing, but working with MockRetrofit was easier :).
So, I should change my client to a mocked version, and create the service API like I do in production code, right?

----
In case you've didn't read the SO post, the interceptor is a kind of `authenticator` refreshing an expired access-token and persisting that and some other things.

**Comment by khafan** [comment]
I used the `Dispatcher` and everything's good. 

Thanks Jake, I'm closing the issue.

**Comment by rt4914** [comment]
@Alireza-Farahani I am facing the same issue, can you help out to test the Interceptor?
