### ISSUE TITLE
Feature request: I'm gettting string from server with escape(\") or quote(") charcters. How could I remove them before reponse exposes Gson de-serialization?

### ISSUE THREAD

**Issue by mecoFarid** [square/retrofit#2341]
This what I get from server 
```
{
  "result": {
    "jsonResult": "{
      \"waypoints\": [],
      \"routes\": [],
      \"code\": \"Ok\"
    }"
  },
  "targetUrl": null,
  "success": true,
  "error": null,
  "unAuthorizedRequest": false,
  "__abp": true
}

```
And this is how I want my response be before Gson deserialization:

```
{
  "result": {
    "jsonResult": {
      "waypoints": [],
      "routes": [],
      "code": "Ok"
    }
  },
  "targetUrl": null,
  "success": true,
  "error": null,
  "unAuthorizedRequest": false,
  "__abp": true
}
```

Any solution to solve this issue.

**Comment by warnyul** [comment]
This is not valid json. Ask the backend developer to fix it.

**Comment by JakeWharton** [comment]
It is valid, it's just nested.

**Comment by JakeWharton** [comment]
JSON inside of a JSON value.

**Comment by mecoFarid** [comment]
@JakeWharton so any suggestions regarding my question? I mean not custom fnuction but Gson built-in method.

**Comment by JakeWharton** [comment]
Not from Retrofit's side. This is entirely outside of Retrofit's control, we just pass the raw response body over to Gson and let it handle it. You might be able to write a custom type adapter in Gson, but asking somewhere like StackOverflow with the 'gson' tag for that is a much better place.
