### ISSUE TITLE
POST Multipart always failing but the file is uploaded to the server

### ISSUE THREAD

**Issue by darakt** [square/retrofit#2342]
I think that my title is pretty clear, I'm uploaded a photo using retrofit (POST multipart), but strangely I'm always going by the onFailure callback but my file is present on my server and the log show a 200 about the upload.
` RequestBody name = RequestBody.create( MediaType.parse("multipart/form-data"), this.name.getText().toString());
        RequestBody description =
                RequestBody.create(
                        MediaType.parse("multipart/form-data"), this.description.getText().toString());
        RequestBody disp =
                RequestBody.create(
                        MediaType.parse("multipart/form-data"), Integer.toString(this.TorF));

        RequestBody max =
                RequestBody.create(
                        MediaType.parse("multipart/form-data"), this.max.getText().toString());

        RequestBody price =
                RequestBody.create(
                        MediaType.parse("multipart/form-data"), this.price.getText().toString());

        RequestBody id =
                RequestBody.create(
                        MediaType.parse("multipart/form-data"), Integer.toString(chef.getId()));

        File nImg = new File(folderImg, imgName);

        RequestBody requestFile = RequestBody.create(MediaType.parse("multipart/form-data"), nImg);
        MultipartBody.Part body = MultipartBody.Part.createFormData("picture", nImg.getName(), requestFile);

        ApiService apiService = ApiManager.createService(ApiService.class, this.chef.getPseudo(), this.chef.getPassword());
        Call<Dish> call = apiService.upload(id, name, description, disp, max, price, body);
        call.enqueue(new Callback<Dish>() {
            @Override
            public void onResponse(Call<Dish> call, Response<Dish> response) {
                Dish d = response.body();
                Log.d(TAG, "onResponse: smt");
                pd.dismiss();
                AddDish.this.terminate();

            }
            @Override
            public void onFailure(Call<Dish> call, Throwable t) {
                Log.d(TAG, "onFailure: smt");
                pd.dismiss();
                AddDish.this.terminate();

            }
        });`
Any explanations?

**Comment by JakeWharton** [comment]
What's the failure?

**Comment by darakt** [comment]
That was because of network problems...
