### ISSUE TITLE
Memory leak with cache

### ISSUE THREAD

**Issue by mehdipourfar** [square/retrofit#2343]
When I use strict mode, I see a memory leak that I can't trace its source.
The error is as follows:

> 05-23 18:27:46.257 2199-2207/com.mypackage E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
>                                                        java.lang.Throwable: Explicit termination method 'close' not called
>                                                            at dalvik.system.CloseGuard.open(CloseGuard.java:180)
>                                                            at java.io.FileOutputStream.<init>(FileOutputStream.java:89)
>                                                            at okio.Okio.appendingSink(Okio.java:186)
>                                                            at okhttp3.internal.io.FileSystem$1.appendingSink(FileSystem.java:59)
>                                                            at okhttp3.internal.cache.DiskLruCache.newJournalWriter(DiskLruCache.java:315)
>                                                            at okhttp3.internal.cache.DiskLruCache.readJournal(DiskLruCache.java:307)
>                                                            at okhttp3.internal.cache.DiskLruCache.initialize(DiskLruCache.java:228)
>                                                            at okhttp3.internal.cache.DiskLruCache.get(DiskLruCache.java:436)
>                                                            at okhttp3.Cache.get(Cache.java:195)
>                                                            at okhttp3.Cache$1.get(Cache.java:145)
>                                                            at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:54)
>                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
>                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
>                                                            at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
>                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
>                                                            at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
>                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
>                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
>                                                            at com.mypackage.net.RestApiConnection$3.intercept(RestApiConnection.java:131)
>                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
>                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
>                                                            at com.mypackage.net.RestApiConnection$1.intercept(RestApiConnection.java:89)
>                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
>                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
>                                                            at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
>                                                            at okhttp3.RealCall.execute(RealCall.java:69)
>                                                            at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
>                                                            at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:41)
>                                                            at io.reactivex.Observable.subscribe(Observable.java:10700)
>                                                            at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
>                                                            at io.reactivex.Observable.subscribe(Observable.java:10700)
>                                                            at io.reactivex.internal.operators.observable.ObservableSubscribeOn$1.run(ObservableSubscribeOn.java:39)
>                                                            at io.reactivex.Scheduler$1.run(Scheduler.java:138)
>                                                            at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
>                                                            at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
>                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>                                                            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
>                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
>                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
>                                                            at java.lang.Thread.run(Thread.java:818)
> 

I use, retrofit 2.3.0, rxjava2 2.0.6, and gson 2.8.0. And I create a cache file like this and pass it to okhttp client builder:
```
File httpCacheDirectory = AndroidApplication.responsesDir();
int cacheSize = 20 * 1024 * 1024; // 20 MiB
cache = new Cache(httpCacheDirectory, cacheSize);
```
It seems that cache file will not be closed at the time it should.

**Comment by JakeWharton** [comment]
Please provide a test case that reproduces the problem. It's impossible to know what's causing this otherwise. Also you're using custom interceptors and we can't know if they're the cause or not.
