### ISSUE TITLE
Connot Connect to Server using Retrofit + Psiphone

### ISSUE THREAD

**Issue by Mahdihp** [square/retrofit#2347]
Connot Connect to Server using Retrofit + [Psiphone](https://s3.amazonaws.com/0ubz-2q11-gi9y/en.html)

**Comment by JakeWharton** [comment]
There is not enough information to make this report actionable. Retrofit doesn't make connections, it delegates to OkHttp for that by passing a request object that points at the given base URL combined with the declared relative URL.

**Comment by Mahdihp** [comment]
public static final String BASE_URL = "http://de.fetyan.org:3000/";
private static Retrofit retrofit = null;
    public static IService getClient() {

        OkHttpClient okHttpClient = new OkHttpClient().newBuilder()
                .connectTimeout(30, TimeUnit.SECONDS)
                .readTimeout(30, TimeUnit.SECONDS)
                .writeTimeout(30, TimeUnit.SECONDS)
                .build();


        if (retrofit==null) {
            retrofit = new Retrofit.Builder()
                    .client(okHttpClient)
                    .baseUrl(BASE_URL)
                    .addConverterFactory(GsonConverterFactory.create())
                    .build();
        }
        return retrofit.create(IService.class);
    }
