### ISSUE TITLE
Connot Connect to Server using Retrofit + Psiphone

### ISSUE THREAD

**Issue by Mahdihp** [square/retrofit#2348]
Connot Connect to Server using Retrofit + [Psiphone](https://s3.amazonaws.com/0ubz-2q11-gi9y/en.html)

`` public static final String BASE_URL = "http://de.fetyan.org:3000/";
private static Retrofit retrofit = null;
    public static IService getClient() {

        OkHttpClient okHttpClient = new OkHttpClient().newBuilder()
                .connectTimeout(30, TimeUnit.SECONDS)
                .readTimeout(30, TimeUnit.SECONDS)
                .writeTimeout(30, TimeUnit.SECONDS)
                .build();
        if (retrofit==null) {
            retrofit = new Retrofit.Builder()
                    .client(okHttpClient)
                    .baseUrl(BASE_URL)
                    .addConverterFactory(GsonConverterFactory.create())
                    .build();
        }
        return retrofit.create(IService.class);
    } 
//-------------------------------------------------
 @Headers({"Accept: application/json"})
    @FormUrlEncoded
    @POST("pixel/dashboard")
    Call<DashboardResult> dashboard(@Field("token") String token, @Field("Page") int Page);
``

**Comment by JakeWharton** [comment]
There is not enough information to make this report actionable and it's not clear why you think Retrofit is to blame here. Please provide a failing test case if you think it's a bug in the library. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
