### ISSUE TITLE
onFailure gets called even after getting response body

### ISSUE THREAD

**Issue by Harish120896** [square/retrofit#2349]
Hi,
In my code onfailure gets called even after response body arrives can u provide suggestions on how to overcome this problem .Logs are as follows:

05-28 22:55:39.103 27514-28233/com.example.admin.atry D/OkHttp: --> GET http://classfinder.azurewebsites.net/classes/music http/1.1
05-28 22:55:39.103 27514-28233/com.example.admin.atry D/OkHttp: --> END GET
05-28 22:55:39.276 2019-2039/? I/LaunchCheckinHandler: Displayed com.example.admin.atry/.DetailsListActivity,wp,ca,1214
05-28 22:55:39.276 2019-2039/? I/ActivityManager: Displayed com.example.admin.atry/.DetailsListActivity: +1s214ms
05-28 22:55:39.508 3734-3734/? I/cm.log.servpro: [forcestop_listener][D]/  onAccessibilityEvent com.example.admin.atry.DetailsListActivity, mListened = false
05-28 22:55:39.631 3030-3313/? I/NetworkController.MotorolaMobileSignalController(1): MotorolaMobilePhoneStateListener.onSignalStrengthsChanged: Entered: signalStrength=SignalStrength: 9 0 -120 -160 -120 -1 -1 99 2147483647 2147483647 2147483647 2147483647 2147483647 gsm|lte level=3
05-28 22:55:40.054 259-259/? I/SFPerfTracer:      triggers: (rate: 790:30403) (compose: 1:416) (post: 0:2428) (render: 12:3788) (19:246035 frames) (20:283371)
05-28 22:55:40.054 259-259/? D/SFPerfTracer:        layers: (3:11) (FocusedStackFrame (0xb8bf5870): 1:1011)* (DimLayer (0xb8bf7ce8): 0:97)* (DimLayer (0xb8bee388): 0:2)* (StatusBar (0xb8bab898): 2:16085) (NavigationBar (0xb8badd10): 0:1813) (com.android.systemui.ImageWallpaper (0xb8b49e00): 0:180)* (DimLayer (0xb8be7e60): 0:16)* (DimLayer (0xb8b4d6f8): 0:4)* (com.example.admin.atry/com.example.admin.atry.MainActivity (0xb8bff968): 0:159)- (com.example.admin.atry/com.example.admin.atry.DetailsListActivity (0xb8b96ce8): 0:31)- (com.example.admin.atry/com.example.admin.atry.DetailsListActivity (0xb8bdf4f0): 20:58) 
05-28 22:55:40.467 27514-28233/com.example.admin.atry D/OkHttp: <-- 200 OK http://classfinder.azurewebsites.net/classes/music (1364ms)
05-28 22:55:40.467 27514-28233/com.example.admin.atry D/OkHttp: Content-Type: application/json; charset=utf-8
05-28 22:55:40.467 27514-28233/com.example.admin.atry D/OkHttp: ETag: W/"181-Ms/IaCrJspsscut2HcejISheb9M"
05-28 22:55:40.467 27514-28233/com.example.admin.atry D/OkHttp: Vary: Accept-Encoding
05-28 22:55:40.468 27514-28233/com.example.admin.atry D/OkHttp: Server: Microsoft-IIS/8.0
05-28 22:55:40.468 27514-28233/com.example.admin.atry D/OkHttp: X-Powered-By: Express
05-28 22:55:40.468 27514-28233/com.example.admin.atry D/OkHttp: X-Powered-By: ASP.NET
05-28 22:55:40.468 27514-28233/com.example.admin.atry D/OkHttp: Set-Cookie: ARRAffinity=ebb396d4f81beeb5fd4bbc63eb7fd56cdbac52e54150918a54705740949cf93d;Path=/;Domain=classfinder.azurewebsites.net
05-28 22:55:40.468 27514-28233/com.example.admin.atry D/OkHttp: Date: Sun, 28 May 2017 17:25:41 GMT
05-28 22:55:40.471 27514-28233/com.example.admin.atry D/OkHttp: [{"_id":"59218e6b8bf8e8171c6a7e7c","classname":"music","institutename":"Dp","location":"AnnaNagar","contact":9349349349,"__v":0}]
05-28 22:55:40.471 27514-28233/com.example.admin.atry D/OkHttp: <-- END HTTP (385-byte body)

**Comment by JakeWharton** [comment]
With what exception? Please provide a failing test case or executable sample that demonstrates a bug in Retrofit.
