### ISSUE TITLE
Add an Async example with callback to the README

### ISSUE THREAD

**Issue by alfiehanssen** [square/retrofit#235]
As an iOS developer new to Java and Android, Retrofit looks superb. I can get sync requests to work but am having trouble finding any examples of async requests online. Specifically regarding how to create and pass the callback. And where / how the success/fail callbacks happen. I realize this may be basic java stuff, but it would be super helpful if the README contained such an example. (I've looked at the Square blog post introducing Retrofit as well as the Retrofit website and neither show how to create/pass the callback parameter or how the success/fail are called. Thanks!

**Comment by JakeWharton** [comment]
Things are changing wildly with Retrofit 2.0 and all of the documentation is going to be refreshed with the new way of doing sync and async calls.
