### ISSUE TITLE
Interrupted exception when a network call is made multiple times in multithreading environemnt

### ISSUE THREAD

**Issue by shabarishbk** [square/retrofit#2353]
Getting thew below exception 

W/System.err:     at okio.Timeout.throwIfReached(Timeout.java:146)
W/System.err:     at okio.Okio$1.write(Okio.java:75)
W/System.err:     at okio.AsyncTimeout$1.write(AsyncTimeout.java:179)
W/System.err:     at okio.RealBufferedSink.flush(RealBufferedSink.java:216)
W/System.err:     at okhttp3.internal.http1.Http1Codec.finishRequest(Http1Codec.java:166)
W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:64)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at com.facebook.stetho.okhttp3.StethoInterceptor.intercept(StethoInterceptor.java:59)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
W/System.err:     at okhttp3.RealCall.execute(RealCall.java:63)
W/System.err:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
W/System.err:     at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:89)

when my code is executed some 7 or 8 times in succession : 

private List<Repo> getServerRepo() throws Throwable {
        List<Repo> repositories = null;
        retrofit2.Call<Repositories> call = syncApi.listRepositories(getUserUid(), getHeadersForRepository());
        Response<Repositories> repoList;
        try {
            repoList = call.execute();
            repositories = repoList.body().getRepository();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return repositories;
    }

I am using retrofit2.2.0 which uses okhttp 3.8.0 and using simpleXmlConverter for converting XML responses.

Setting up retofit like this : 

new OkHttpClient.Builder().
                addInterceptor(loggingInterceptor)
                //.addInterceptor(new UnzippingInterceptor())
                .addNetworkInterceptor(new StethoInterceptor())
                .connectTimeout(30, TimeUnit.SECONDS)
                .readTimeout(300, TimeUnit.SECONDS)
                .writeTimeout(300,TimeUnit.SECONDS)
                .connectionPool(new ConnectionPool(10, 5, TimeUnit.MINUTES))
                .build();

Retrofit.Builder builder = new Retrofit.Builder();
        builder.baseUrl(baseUrl());
        builder.addConverterFactory(
                new AnnotationTypeConverterFactory(GsonConverterFactory.create(),
                        SimpleXmlConverterFactory.create()));
        return builder.build();

**Comment by JakeWharton** [comment]
Please don't file bugs in multiple projects. This isn't a problem with Retrofit so closing.

**Comment by shabarishbk** [comment]
I am not sure if this is Retrofit or Okhttp issue, so filed it in two places, thanks @JakeWharton  , any insights on the issue ? any help is greatly appreciated.
