### ISSUE TITLE
In Multipart Request, boolean and integer type form data is received as string on server side 

### ISSUE THREAD

**Issue by ankit-agg** [square/retrofit#2358]
My request declaration is - 

   ```
    @Multipart
    @POST("/upload/abc")
    Call<UploadResponse> uploadToServer(@Part("img_file\";filename=\"image") RequestBody file,
                                             @Part("access_token") RequestBody sessionKey,
                                             @Part("is_final") Boolean flag,
                                             @Part("sequence_id") Integer sequenceId,
                                             @Part("entity_id") RequestBody entityId,
                                             @Part("image_type") RequestBody imageType);       

```

I tried 3 approaches to send this 
(1) Boolean.TRUE
(2) true
(3) making 'flag' as RequestBody and sending it as `RequestBody.create(MediaType.parse("text/plain"), Boolean.TRUE.toString());`

In all the three cases, it is always received as string "true" (with double quotes) instead of true on server. Similarly integer type params are received as Strings with double quotes. I am using 'com.squareup.retrofit2:converter-gson:2.1.0' converter. This is only happening in case of Multipart request.

**Comment by JakeWharton** [comment]
Add the converter-scalars dependency and install the scalars converter before the Gson converter. Otherwise all of those elements will be sent as quoted values in JSON.

**Comment by nailbrother** [comment]
Is there a way that I can convert int values to booleans ? I'm receiving JSON that looks like this:

{ "verify": "1", "success": "1" }

My class mamber getVerify() returns always false even if value is 1

**Comment by vijaypalod** [comment]
Can you please tell, how to use converter-scalars while sending boolean  with Multipart

**Comment by JakeWharton** [comment]
Register the converter before any others and it should just work. It'll
send text/plain parts with "true" or "false" (but no quotes).

**Comment by ankit-agg** [comment]
@vijaypalod check this out https://stackoverflow.com/a/47627526/1320616
