### ISSUE TITLE
Unable to get response when code 401,422 Unauthorized

### ISSUE THREAD

**Issue by SumanPahari** [square/retrofit#2361]
Unable to get response when code 401,422 Unauthorized?

I have onResponse and onFailure block when requesting for api. In response block checking response.isSuccessful() when success mean code 200 then i can easily parse the response but when 400,401,422 then i can't able to parse response.when i am trying to get body or errorBody then return `null.

 if (response.isSuccessful())
{
                    Gson gson = new Gson();
                    String json = gson.toJson(response.body());
                    Log.e("isSuccessful2",json);
}
 else {
                   Log.e("isSuccessful1",response.errorBody().toString());
                    Gson gson = new Gson();
                    String json = gson.toJson(response.body());
                    Log.e("isSuccessful2",json);
 }

**Comment by JakeWharton** [comment]
You're calling `body()` instead of `errorBody()` in the `else` which will always be null in an unsuccessful response.

**Comment by SumanPahari** [comment]
yes,i have checked body and errorbody both,return null

**Comment by JakeWharton** [comment]
Can you provide a test case demonstrating the problem?

**Comment by SumanPahari** [comment]
yes, Sorry for late reply.
This is my postman api link : https://www.getpostman.com/collections/ab7ac2b29dc0857607df
If success then status 200 and it is execute 
`if (response.isSuccessful())
{
Gson gson = new Gson();
String json = gson.toJson(response.body());
Log.e("isSuccessful2",json);
}
but when missing any parameter or wrong credentials then status 422 and return some response but unable to execute else block
