### ISSUE TITLE
Null pointer in OkHttpCall.parseResponse(Response rawResponse) 

### ISSUE THREAD

**Issue by Malachiasz** [square/retrofit#2362]
The method assumes that  rawResponse.body() won't return null, but null is actually allowed because okhttp3.Response.Builder.build() asserts that only request, protocol and code are non null:
```
        public Response build() {
            if(this.request == null) {
                throw new IllegalStateException("request == null");
            } else if(this.protocol == null) {
                throw new IllegalStateException("protocol == null");
            } else if(this.code < 0) {
                throw new IllegalStateException("code < 0: " + this.code);
            } else {
                return new Response(this);
            }
        }
```

```
    retrofit2.Response<T> parseResponse(Response rawResponse) throws IOException {
        ResponseBody rawBody = rawResponse.body();
        rawResponse = rawResponse.newBuilder().body(new OkHttpCall.NoContentResponseBody(rawBody.contentType(), rawBody.contentLength())).build();
```

**Comment by JakeWharton** [comment]
Null bodies are only present in cache response, network response, or redirect responses. Never the main response.

**Comment by Malachiasz** [comment]
It can appear in the main response if OkHttp client has Interceptor which intercepts server response and deliver its own:

```
public interface Interceptor {
  Response intercept(Chain chain) throws IOException;

  interface Chain {
    Request request();
    Response proceed(Request request) throws IOException;
    Connection connection();
  }
}

```
As you see here in method intercept(Chain chain) returns Response, which can be created with okhttp3.Response.Builder.build() without a body, thus leading to null pointer exception in retrofit.

**Comment by JakeWharton** [comment]
Responses are required to have a body. If OkHttp allows that then we're
missing a check in OkHttp to forbid this.
