### ISSUE TITLE
Get SocketTimeoutException after changing Retrofit obj

### ISSUE THREAD

**Issue by MarcoGrasselli** [square/retrofit#2370]
Hi everyone!

I've got 2 server where fetch data:
 - SERVER_A: http://213.XXX.XXX.XXX:8280/
 - SERVER_B: http://mobile.foo.it/

I'm using a RestClient class with a static Retrofit object.

Before send a request, I replace the Retrofit object width a new one having the right address (SERVER_A/SERVER_B).

On the same Android activity I have successfull request for SERVER_A and successfull request for SERVER_B until I don't alternate them, but I have SocketTimeoutException if I alternate the requests.

Example:
1- REQUEST_A : successfull
2- REQUEST_A : successfull
3- REQUEST_B : successfull
4- REQUEST_B : successfull
5- REQUEST_A : **SocketTimeoutException**

Going to previous activity (where I do only REQUEST_A)  after the SocketTimeoutException at step 5, I will have always a  SocketTimeoutException!

Thanks for help!

**Comment by digitalbuddha** [comment]
Please use Stackoverflow for questions. 
This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

**Comment by MarcoGrasselli** [comment]
I asked here because I think it's a issue of retrofit library..

**Comment by JakeWharton** [comment]
Retrofit doesn't interact with sockets or timeouts so it has no means of causing or preventing this exception. It creates Request objects and asks OkHttp to return a Response object. So any bug, if there is one, would be in OkHttp or a layer below it.

You're free to report this on OkHttp but without a test case or reproduction steps it will be impossible to diagnose what you're seeing.
