### ISSUE TITLE
Dynamic Endpoint with Post Request

### ISSUE THREAD

**Issue by aliabhas** [square/retrofit#2372]
I am calling an POST Api for example:
www.github.com/user/1122

and some parameters using body parameter .
when i call the API app crashes with Exception as :-
   Caused by: java.lang.IllegalArgumentException: baseUrl must end in /: 

but when i add the "/" in the base url the api path get wrong and throws resource not found exception .
The issue is i have to call the url without the "/" at the end .
and without "/" application crashes what should i have to do 
please help .
thanks

**Comment by JakeWharton** [comment]
The documentation on `baseUrl` should clarify the behavior: http://square.github.io/retrofit/2.x/retrofit/retrofit2/Retrofit.Builder.html#baseUrl-okhttp3.HttpUrl-
