### ISSUE TITLE
encode not work in post method with @FieldMap

### ISSUE THREAD

**Issue by PPTing** [square/retrofit#2374]
I use Retrofit 2.3.0 to post a String(base64 with some char like / ) as the value. So I make it like
```java
    @POST(Api.Url)
    @FormUrlEncoded
    Observable<Response> update(@Field("id") String id,@FieldMap(encoded = true) Map<String, Object> requestParams);
```

but as the result , when I check the value in **Charles**,I found it also post the value with **%2F** and more.
It's a Bug for the ***Retrofit***?

**Comment by swankjesse** [comment]
This is consistent with Firefox and other major browsers.
