### ISSUE TITLE
timeout connection 

### ISSUE THREAD

**Issue by Nardeep** [square/retrofit#2377]
when i send large content length string in POST method then the following error come but when content length short it works correct how to  solve it.
Exception in thread "main" java.net.SocketTimeoutException: timeout

**Comment by JakeWharton** [comment]
Timeouts are normal things to come from sockets. If you're sending something large, considering increasing the timeout on OkHttp.

**Comment by Nardeep** [comment]
After increasing time , error will remain same .I increased the timeout upto 15 minutes.but the same error come after 15 min. why?

**Comment by JakeWharton** [comment]
You haven't provided enough information for anyone to know why let alone
what you're doing.

What I can say with confidence, however, is that it's not a Retrofit
problem. The entire request/response functionality of this library is
delegated to OkHttp. Retrofit doesn't affect timeouts in any way.
