### ISSUE TITLE
why not use CLASS Anotation

### ISSUE THREAD

**Issue by dndxxiangyu** [square/retrofit#2380]
I see the code of Retrofit, and realize that it use RetentionPolicy.RUNTIME. I want to know why not use RetentionPolicy.CLASS instead, because many frames such as ButterKnife , Dagger, xUtils3, EventBus3.

**Comment by JakeWharton** [comment]
Retrofit is not an annotation processor. It uses a runtime proxy and
reflection for parsing the annotations and thus requires them to be present
at runtime.
