### ISSUE TITLE
Java7 proguard has waring

### ISSUE THREAD

**Issue by JackLiaoJH** [square/retrofit#2382]
Warning:retrofit2.Platform$Java8: can't find referenced class java.lang.invoke.MethodHandles$Lookup
Warning:retrofit2.Platform$Java8: can't find referenced class java.lang.invoke.MethodHandle
Warning:retrofit2.Platform$Java8: can't find referenced class java.lang.invoke.MethodHandles
Warning:retrofit2.Platform$Java8: can't find referenced class java.lang.invoke.MethodHandle
Warning:retrofit2.Platform$Java8: can't find referenced class java.lang.invoke.MethodHandles$Lookup
Warning:retrofit2.Platform$Java8: can't find referenced class org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement

**Comment by JackLiaoJH** [comment]
Now ,I add -ignorewarnings in the proguard ,this ok?

**Comment by JakeWharton** [comment]
Yes. This can be ignored.

**Comment by JackLiaoJH** [comment]
thanks
