### ISSUE TITLE
GSON Field Naming Policy not applied 

### ISSUE THREAD

**Issue by FrankSalad** [square/retrofit#2383]
Bug Report:
Attempted to use this strategy for having Retrofit 2 automatically convert dash-cased API responses to camelCased field names:
```
Gson gson = new GsonBuilder().setFieldNamingPolicy(FieldNamingPolicy.LOWER_CASE_WITH_DASHES).create()
Retrofit retrofit = new Retrofit.Builder()
.baseUrl("https://openapi.etsy.com/v2/")
.addConverterFactory(GsonConverterFactory.create(gson))
.build();
```

Unfortunately, any dash-cased fields are not being deserialized properly. I'm getting nulls in those fields in my deserialized objects. I have to manually add `@SerializedName` annotations everywhere. 

I believe this has to do with changes in the way the deserialization works from retro1 to retro2:
In retro 1 deserialization is delegated to Gson: https://github.com/square/retrofit/blob/parent-1.9.0/retrofit/src/main/java/retrofit/converter/GsonConverter.java

But in retro 2 we pull the jsonreader out of the gson and apply the TypeAdapter manually
https://github.com/square/retrofit/blob/master/retrofit-converters/gson/src/main/java/retrofit2/converter/gson/GsonResponseBodyConverter.java

The type adapter has a map of field names to reflected bound fields and it does a simple lookup on every json key. It doesn't apply the dash-case conversion.

**Comment by JakeWharton** [comment]
Sounds like a Gson bug then. The `TypeAdapter` we receive from the `Gson` instance when looking up a type should reflect the field naming policy that is set.

**Comment by eneim** [comment]
@FrankSalad Just to make sure, are you mixing DASH (**-**) with UNDERSCORE (**_**)? I read esty API doc and its response's field are all "lower case with underscores". For example: [https://www.etsy.com/developers/documentation/reference/billcharge](https://www.etsy.com/developers/documentation/reference/billcharge)

**Comment by FrankSalad** [comment]
@eneim I pulled etsy from an example. 

Our backend API uses underscores over the wire and I'm using `FieldNamingPolicy.LOWER_CASE_WITH_UNDERSCORES` when constructing my Gson instance.

**Comment by FrankSalad** [comment]
@JakeWharton Shouldn't this be considered a Retrofit 2 regression? As an end-user, using Retrofit 1, I'm able to have the correct behavior given some configuration. Under Retrofit 2, I am not without rewriting parts of `GsonResponseBodyConverter`.

**Comment by JakeWharton** [comment]
Regressions can only happen within the same major release. Retrofit 2
intentionally changes many behaviors of the library.

That being said, we use a more optimal means of interacting with Gson and
if it doesn't correctly expose the behavior it should on that API then it's
a bug there.

**Comment by FrankSalad** [comment]
Sorry! It was my mistake. This is not broken at all, it totally works. My fields were actually camelCased and I was using the wrong `FieldNamingPolicy` 🙈

![image](https://confessionsofa20somethingklutz.files.wordpress.com/2014/04/sleepy-homer_lurking.gif)
