### ISSUE TITLE
Call.enqueue blocks

### ISSUE THREAD

**Issue by fab1an** [square/retrofit#2387]
In my Android app calls to `enqueue` sometimess block for up to two seconds.

**Comment by swankjesse** [comment]
Executable test case?

**Comment by fab1an** [comment]
Hard to do as I get the error only in production and seldomly. I can try to patch something together.

Is my assumption correct in the first place that `enqueue` should never block like this, no matter how many calls get queued?

**Comment by swankjesse** [comment]
There’s a few `synchronized` blocks that aren’t expected to be contended-upon. And there’s a call to `ExecutorService.enqueue()` that could block if OkHttp’s Dispatcher’s executor service is incorrectly configured.

Please try to provide an executable test case. As-is this isn’t actionable.

**Comment by fab1an** [comment]
Like I said, I will try to provide a test-case. Could you tell me an example of incorrect configurations of the executor-service?

**Comment by JakeWharton** [comment]
One backed by a queue that blocks and is sized to only hold a finite amount
of elements.

**Comment by fab1an** [comment]
I'm setting up the okhttp client with default-settings. Would supplying a `Dispatcher` with raised `maxRequestsPerHost` help with my issue, or doesn't that affect whether `enqueue` blocks?
