### ISSUE TITLE
retrofit 2 onResponse is getting called for no internet connection

### ISSUE THREAD

**Issue by RajuSE** [square/retrofit#2390]
onResponse is getting called for 4-5 times also isSuccess() of Response class is returning true for 4-5 times returning true when there is no internet connection. onError is getting called properly after 4-5 attempts.  

My gradle:
```
compile 'com.google.code.gson:gson:2.4'
    compile 'com.squareup.retrofit:retrofit:2.0.0-beta2'
    compile 'com.squareup.retrofit:converter-gson:2.0.0-beta2'
    compile 'com.squareup.okhttp:okhttp:2.4.0'
```
Code : https://github.com/RajuSE/CodeDagger2

**Comment by Egorand** [comment]
Any specific reason you're using `com.squareup.retrofit:retrofit:2.0.0-beta2` and not `com.squareup.retrofit2:retrofit:2.3.0`?

**Comment by RajuSE** [comment]
Ok I updated to 2.3.0 still problem continues!
https://github.com/RajuSE/CodeDagger2/commit/e51e059a60bb670cd59e32e7c89c29747696266f
refer code to recreate: https://github.com/RajuSE/CodeDagger2

**Comment by RajuSE** [comment]
I've done Workaround by intercepting the request and checking connection by ConnectivityManager **manually**.
Can this issue be taken as enhancement (or feature request).(as there is a lot of boilerplate code required to write)?

Thanks

**Comment by JakeWharton** [comment]
You enabled HTTP caching so it's likely that the response is being served from the cache. You can check this by seeing if `cacheResponse()` is non-null on the `raw()` OkHttp response from Retrofit's `Response` object.
