### ISSUE TITLE
Retrofit URL request problem

### ISSUE THREAD

**Issue by Ibbus93** [square/retrofit#2391]
I'm trying to download data from Facebook export API doing GET request .
I've built a correct URL, I've seen it printing it from the responseBody request and from testing it in Postman. The problem is that the request responses with a code 500. When I debug I can clearly see that the url is changed.

Here's my code:

```
public interface FacebookService {
    @Streaming
    @GET("download")
    Call<ResponseBody> getData(@Query("access_token") String access_token, 
        @Query("id") String id, Query("filename") String filename);
}
```
Method that I use for the request:

```
public FacebookCSV getCSV(@NotNull String access_token, @NotNull String id) {
        FacebookCSV facebookCSV = null;

        final Call<ResponseBody> responseBodyCall = facebookService.getData(access_token, id, "output.gz");

        responseBodyCall.enqueue(new Callback<ResponseBody>() {
            public void onResponse(Call<ResponseBody> call, Response<ResponseBody> response) {
                ResponseBody responseBody = response.body();
                DataInputStream zin = new DataInputStream(responseBody.byteStream()); //responseBody is null
                Scanner sc = new Scanner(zin);
                try {
                    while(sc.hasNextLine()){
                        System.out.println(sc.nextLine());
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
            public void onFailure(Call<ResponseBody> call, Throwable throwable) {
                throwable.printStackTrace();
            }
        });

        System.out.println(responseBodyCall.request().url());

        return facebookCSV;
    }
```

URL that I'm submitting:
https://lookaside.fbsbx.com/analytics/app_events_export/download/?access_token={myAccessToken}&id={myRequestID}&filename=output.gz

URL that response with 500:
https://m.facebook.com/analytics/app_events_export/download/?access_token={myAccessToke}&id={myRequestID}&filename=output.gz

The only different that I've found between the URLs is a little thing into the Access Token. The Access Token is built in this way:
{facebookClientID}**|**{secretKey}
That vertical bar, in the URL response, has been translated to **%7**.

This could be the problem, so the URL response is only a default error response to a bad request. In this way the error 500 could be explained too.

In other queries, anyway, I use the same access token and I didn't find problems like this.

**Comment by swankjesse** [comment]
Please use StackOverflow for usage questions. Please include executable test cases in bug reports.
