### ISSUE TITLE
how to use okhttp  request tag in retrofit

### ISSUE THREAD

**Issue by xushaun** [square/retrofit#2394]
I used okhttp  request with tag for my internet request, Now i decide to use retrofit 
   But i find there isn't any API  in retrofit for me to add a tag which is support by okhttp to request;  
   The request tag is important for me ,and retrofit is  convenient for us，So I want to combine them
   Can you help to add this function in retrofit or tell how i can build  retrofit source code  to satisfy my need

thank you

**Comment by NightlyNexus** [comment]
There's no Retrofit 2 API directly exposed to set the Request tag.

You could make a CallAdapter to do this, though.

**Comment by xushaun** [comment]
I think i should change RequestBuilder source code to add tag

**Comment by JakeWharton** [comment]
What are you using it for?

**Comment by xushaun** [comment]
I used tag to Distinguish between different requst, Before i send http request to server, i will attach extra information to this request with okhttp tag, so I can Distinguish between different requst and response

**Comment by Tamicer** [comment]
@xushaun  you can try   get  request  by Interceptor

**Comment by rahul-a** [comment]
I have a similar requirement of distinguishing requests with tags, but I wouldn't want to use call adapter factory as I'm using rxJava2Call factory already. I could do it in the Call.Factory per se but annotations could make it simpler, otherwise I'd have to map tags to urls.

**Comment by teffi** [comment]
I also came across with the same requirement. I somehow need to identify what request is running on the interceptor so that I can modify some headers accordingly.

**Comment by wjwang0914** [comment]
Why can not add the request tag in Retrofit, the purpose of this design is

**Comment by D330** [comment]
until now there was no support?

**Comment by fkowal** [comment]
```
class Client {
@GET("/url")
@Tag("Authorized") // custom tag that will trigger a Interceptor logic
String somemethod();
```

i'd like to have a fine grained control over OkHttp Interceptors

in the 

class AuthInterceptor implements Interceptor {
Response intercept {
Request req = request()
if (req.tag == "...") { dosomething() }
}
```

**Comment by NightlyNexus** [comment]
@fkowal 
Maybe use a custom header for that?
https://publicobject.com/2016/01/17/sneaking-data-into-an-okhttp-interceptor/

**Comment by fkowal** [comment]
Great idea thx

**Comment by viyski** [comment]
> ```
> I used okhttp  request with tag for my internet request, Now i decide to use retrofit 
> ```
> 
> But i find there isn't any API in retrofit for me to add a tag which is support by okhttp to request;
> The request tag is important for me ,and retrofit is convenient for us，So I want to combine them
> Can you help to add this function in retrofit or tell how i can build retrofit source code to satisfy my need
> 
> thank you

you can use the retrofit @Tag annotation in the request method.

eg: Call<List<User>> userList(@Path("user") String user, @Tag() String value);

**Comment by shahwaiz90** [comment]
https://www.linkedin.com/pulse/how-use-tag-retrofit-ahmad-shahwaiz/
