### ISSUE TITLE
Does retrofit support List<Map<String,String>> int GET method

### ISSUE THREAD

**Issue by pollylove** [square/retrofit#2395]
like this:
@GET("parents/{parent_id}/clazzs/{clazz_id}/xxx.json")
    Call<List<Comment>> getComments(@Path("parent_id") String parentId,
            @Path("clazz_id") String clazzId,
            @Query("comment_updates[]") List<Map<String, String>> dataMap);

this will convert ":" to "=" of map in json
this is error log:unexpected token at '{clazzroom_record_id=254523, last_updated_at=2017-07-06 18:08:29}'

thx~

**Comment by JakeWharton** [comment]
Retrofit will use a string converter to convert each Map to a string output for the URL. So it's supported in that sense, but there's no explicit support for maps inside a query param. If you need custom formatting register your own string converter. For more information you can ask questions on StackOverflow with the 'retrofit' tag and more information about the desired result.

**Comment by pollylove** [comment]
thanks a lot! i resolved it by override the stringConverter of my project
