### ISSUE TITLE
How to send request jsonobject using retrofit

### ISSUE THREAD

**Issue by amitd123** [square/retrofit#2401]
I am using retrofit to call post web service . but i am getting 404 response code. i tried a lot but can't get solution.

My json request is: 

 `{"params":{"email":"bxbhdhzh@hdj.com","password":"hdjdu","firstName":"jdjdj","lastName":"jdjdj"}}`

and response is

`{"userId": "12","message": "successfully register","success": "1"}`

please suggest solution

**Comment by JakeWharton** [comment]
This is a usage question which is generally more appropriate for StackOverflow. GitHub issues are reserved for bug reports with test cases or samples, or new feature requests. You can use the 'retrofit' tag which is monitored by us and many library users. Feel free to link the asked question back here on the issue.
