### ISSUE TITLE
java.io.EOFException

### ISSUE THREAD

**Issue by gongxm0412** [square/retrofit#2405]
java.io.EOFException
07-13 10:43:49.614 8493-8493/com.zhende.zhendebusiness W/System.err:     at okio.RealBufferedSource.require(RealBufferedSource.java:60)
07-13 10:43:49.625 8493-8493/com.zhende.zhendebusiness W/System.err:     at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:294)
07-13 10:43:49.636 8493-8493/com.zhende.zhendebusiness W/System.err:     at okhttp3.internal.http1.Http1Codec$ChunkedSource.readChunkSize(Http1Codec.java:444)
07-13 10:43:49.647 8493-8493/com.zhende.zhendebusiness W/System.err:     at okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:425)
07-13 10:43:49.655 8493-8493/com.zhende.zhendebusiness W/System.err:     at okio.RealBufferedSource.readAll(RealBufferedSource.java:163)
07-13 10:43:49.662 8493-8493/com.zhende.zhendebusiness W/System.err:     at retrofit2.Utils.buffer(Utils.java:303)
07-13 10:43:49.669 8493-8493/com.zhende.zhendebusiness W/System.err:     at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:198)
07-13 10:43:49.676 8493-8493/com.zhende.zhendebusiness W/System.err:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
07-13 10:43:49.687 8493-8493/com.zhende.zhendebusiness W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171)
07-13 10:43:49.697 8493-8493/com.zhende.zhendebusiness W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
07-13 10:43:49.704 8493-8493/com.zhende.zhendebusiness W/System.err:     at rx.Subscriber.setProducer(Subscriber.java:211)
07-13 10:43:49.710 8493-8493/com.zhende.zhendebusiness W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
07-13 10:43:49.715 8493-8493/com.zhende.zhendebusiness W/System.err:     at rx.Subscriber.setProducer(Subscriber.java:205)
07-13 10:43:49.722 8493-8493/com.zhende.zhendebusiness W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
07-13 10:43:49.729 8493-8493/com.zhende.zhendebusiness W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
07-13 10:43:49.735 8493-8493/com.zhende.zhendebusiness W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
07-13 10:43:49.741 8493-8493/com.zhende.zhendebusiness W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
07-13 10:43:49.746 8493-8493/com.zhende.zhendebusiness W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:10151)
07-13 10:43:49.752 8493-8493/com.zhende.zhendebusiness W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
07-13 10:43:49.758 8493-8493/com.zhende.zhendebusiness W/System.err:     at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:228)
07-13 10:43:49.764 8493-8493/com.zhende.zhendebusiness W/System.err:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
07-13 10:43:49.769 8493-8493/com.zhende.zhendebusiness W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
07-13 10:43:49.774 8493-8493/com.zhende.zhendebusiness W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-13 10:43:49.781 8493-8493/com.zhende.zhendebusiness W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
07-13 10:43:49.787 8493-8493/com.zhende.zhendebusiness W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-13 10:43:49.792 8493-8493/com.zhende.zhendebusiness W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-13 10:43:49.795 8493-8493/com.zhende.zhendebusiness W/System.err:     at java.lang.Thread.run(Thread.java:776)

**Comment by JakeWharton** [comment]
This is not a Retrofit problem, and if it were it would require a test case demonstrating the problem. It looks like your server is truncating the response or some lower level of the network stack is failing to delivered the promised bytes.

There's no action for Retrofit to take on this.

**Comment by gongxm0412** [comment]
Thanks
