### ISSUE TITLE
Wrong thread name in case we supply our executors 

### ISSUE THREAD

**Issue by yashasvigirdhar** [square/retrofit#2407]
What kind of issue is this?
- Bug report.

I am using retrofit version 1.9.0.

The issue is that retrofit sets wrong thread name when we supply our own executors using `RestAdaper#setExecutors` method. 

See `RestAdapter#invokeRequest` method.  There are two places where it sets the thread name : 

- `Thread.currentThread().setName(THREAD_PREFIX
              + url.substring(serverUrl.length(), substrEnd));`  

- `Thread.currentThread().setName(IDLE_THREAD_NAME);`.

When I've supplied my http and callback executors to it, I've already configured the thread names in my exectuor configuration. IMO, it should be honouring that here. 

I'll write a test for this after somebody confirms that it's a valid bug.

**Comment by JakeWharton** [comment]
Retrofit 2.x has supplanted 1.x about 18 months ago and there won't be any more development or releases for 1.x. If you need to make changes to 1.x then your best bet is forking the library to release your own version or just embedding the source inside your project.

And it should be noted that there's no thread naming or threading at all really that's explicitly handled inside Retrofit 2.x. We delegate to other libraries for that now.
