### ISSUE TITLE
Lamda support at enqueue method

### ISSUE THREAD

**Issue by kawnayeen** [square/retrofit#2408]
It will be nice if we can pass lamda function at `enqueue()` method.

**Comment by JakeWharton** [comment]
You can write your own version of `Call` that supports this and a `CallAdapter` which wraps the Retrofit `Call` to your custom `Call`.

The biggest limiting factor to putting it in the library is that it requires the SAM types introduced in Java 8 and Retrofit works on Java 7. Maybe in some hypothetical future where Java 8 is required we'll add this, but that won't be for some time as we support the Android platform.
