### ISSUE TITLE
Retrofit how to access raw folder json file

### ISSUE THREAD

**Issue by maheswaranecemohan** [square/retrofit#2409]
Retrofit how to access raw folder json file

**Comment by freeyob** [comment]
https://stackoverflow.com/questions/32518967/how-to-get-a-json-file-from-raw-folder

**Comment by JakeWharton** [comment]
This is a usage question which is generally more appropriate for StackOverflow. GitHub issues are reserved for bug reports with test cases or samples, or new feature requests. You can use the 'retrofit' tag which is monitored by us and many library users. Feel free to link the asked question back here on the issue.
