### ISSUE TITLE
Proguard Error

### ISSUE THREAD

**Issue by Zvirtuey** [square/retrofit#2411]
##compile 'com.google.code.gson:gson:2.8.1'
    compile 'com.squareup.okhttp3:okhttp:3.8.1'
    compile 'com.squareup.okio:okio:1.13.0'
    compile 'com.squareup.retrofit2:retrofit:2.3.0' 

##this is my Proguard Configuration:

##okhttp3
-dontwarn okhttp3.**
-keep class okhttp3.** { *;}
-dontwarn okio.**
-dontwarn javax.annotation.Nullable
-dontwarn javax.annotation.ParametersAreNonnullByDefault
## Okio
-dontwarn com.squareup.**
-dontwarn okio.**
-keep public class org.codehaus.* { *; }
-keep public class java.nio.* { *; }
## Retrofit
-dontnote retrofit2.Platform
-dontwarn retrofit2.Platform$Java8
-keepattributes Signature
-keepattributes Exceptions
-dontwarn retrofit2.**
-keep class retrofit2.** { *; }
-dontwarn javax.annotation.**
-keep class com.google.gson.examples.android.model.** { *; }

## But run the error
07-17 14:19:13.880: E/AndroidRuntime(10253): java.lang.AbstractMethodError: abstract method "void retrofit2.Callback.onResponse(retrofit2.Call, retrofit2.Response)"
07-17 14:19:13.880: E/AndroidRuntime(10253): 	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
07-17 14:19:13.880: E/AndroidRuntime(10253): 	at android.os.Handler.handleCallback(Handler.java:739)
07-17 14:19:13.880: E/AndroidRuntime(10253): 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-17 14:19:13.880: E/AndroidRuntime(10253): 	at android.os.Looper.loop(Looper.java:145)
07-17 14:19:13.880: E/AndroidRuntime(10253): 	at android.app.ActivityThread.main(ActivityThread.java:5942)
07-17 14:19:13.880: E/AndroidRuntime(10253): 	at java.lang.reflect.Method.invoke(Native Method)
07-17 14:19:13.880: E/AndroidRuntime(10253): 	at java.lang.reflect.Method.invoke(Method.java:372)
07-17 14:19:13.880: E/AndroidRuntime(10253): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
07-17 14:19:13.880: E/AndroidRuntime(10253): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

If I don't use Proguard, it's okay，How can i solve it?

**Comment by JakeWharton** [comment]
First of all, those ProGuard rules are ridiculous and pointless. You can just disable ProGuard to get the same effect (keeping everything). You gain nothing by running ProGuard with those rules.

This doesn't seem to be a Retrofit issue but one of ProGuard use. This is a build tool that you are choosing to use and thus should seek assistance with its accurate use in an appropriate forum like StackOverflow with the 'retrofit' and 'proguard' tag or its mailing list. There's no action for us to take here.
