### ISSUE TITLE
Crash in okhttp3

### ISSUE THREAD

**Issue by XiaoqianYuPLN** [square/retrofit#2413]
In our Android production build, it crashes many times, here is the stack:

okhttp3.internal.connection.RouteSelector.next (RouteSelector.java:78)
--
  | okhttp3.internal.connection.StreamAllocation.findConnection (StreamAllocation.java:171)
  | okhttp3.internal.connection.StreamAllocation.findHealthyConnection (StreamAllocation.java:121)
  | okhttp3.internal.connection.StreamAllocation.newStream (StreamAllocation.java:100)
  | okhttp3.internal.connection.ConnectInterceptor.intercept (ConnectInterceptor.java:42)
  | okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:92)
  | okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:67)
  | okhttp3.internal.cache.CacheInterceptor.intercept (CacheInterceptor.java:93)
  | okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:92)
  | okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:67)
  | okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.java:93)
  | okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:92)
  | okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.java:120)
  | okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:92)
  | okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:67)
  | okhttp3.RealCall.getResponseWithInterceptorChain (RealCall.java:185)
  | okhttp3.RealCall$AsyncCall.execute (RealCall.java:135)
  | okhttp3.internal.NamedRunnable.run (NamedRunnable.java:32)
  | java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
  | java.lang.Thread.run (Thread.java:762)

it seems some people have the same issue.

**Comment by JakeWharton** [comment]
This is not a problem with Retrofit but of OkHttp. Ensure you are using the latest version of OkHttp.

**Comment by XiaoqianYuPLN** [comment]
Okhttp3 3.8.0 is provided in retrofit 2.3.0, can I use 3.8.1 explicitly in gradle file? It will override 3.8.0 in retrofit?

**Comment by JakeWharton** [comment]
Yes

**Comment by XiaoqianYuPLN** [comment]
Thank you so much.
