### ISSUE TITLE
Does retrofit support json params int GET method

### ISSUE THREAD

**Issue by brook19** [square/retrofit#2414]
What kind of issue is this?

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by brook19** [comment]
http://192.168.1.114/ds?{"action":"getAction","method":"get","param":{"serviceName":"solr_goods","format":"json","param":{"device_type":"6","user_id":2426733,"product_type":"3"}}}

How to implement this?

**Comment by JakeWharton** [comment]
This is a usage question which is generally more appropriate for StackOverflow. GitHub issues are reserved for bug reports with test cases or samples, or new feature requests. You can use the 'retrofit' tag which is monitored by us and many library users. Feel free to link the asked question back here on the issue.
