### ISSUE TITLE
When to use this lib. ?

### ISSUE THREAD

**Issue by patelakshay13890** [square/retrofit#2420]
In my app RESTful services are called in background threading & in 1 sec i want tom kae 2 to 4 request in one thread…And there may be 3 to 4 such thread running in parallel & making individual REST request…
So in this Situation which lib. should I use ??
Plz help me out..
Thanks…

**Comment by JakeWharton** [comment]
This is a usage question which is generally more appropriate for StackOverflow. GitHub issues are reserved for bug reports with test cases or samples, or new feature requests. You can use the 'retrofit' tag which is monitored by us and many library users. Feel free to link the asked question back here on the issue.
