### ISSUE TITLE
JsonWriter close may occur resource leak in GsonRequestBodyConverter.convert()

### ISSUE THREAD

**Issue by EdwardLee03** [square/retrofit#2421]
See the following source code of 'GsonRequestBodyConverter', the third to fifth statements are may throws IOException. When the `adapter.write(jsonWriter, value)` statement has throw an IOException, `jsonWriter.close()` will not execute, it occurs resource leak problem.

```java
  @Override public RequestBody convert(T value) throws IOException {
    Buffer buffer = new Buffer();
    Writer writer = new OutputStreamWriter(buffer.outputStream(), UTF_8);
    JsonWriter jsonWriter = gson.newJsonWriter(writer); // 3
    adapter.write(jsonWriter, value); // 4
    jsonWriter.close(); // 5
    return RequestBody.create(MEDIA_TYPE, buffer.readByteString());
  }
```

It can use [try-with-resources Statement](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) to fix this problem, because the `gson` module of `retrofit-converters` is use JDK 7.
```java
  @Override public RequestBody convert(T value) throws IOException {
    Buffer buffer = new Buffer();
    Writer writer = new OutputStreamWriter(buffer.outputStream(), UTF_8);
    try (JsonWriter jsonWriter = gson.newJsonWriter(writer)) {
      adapter.write(jsonWriter, value);
    }
    return RequestBody.create(MEDIA_TYPE, buffer.readByteString());
  }
```

**Comment by swankjesse** [comment]
Good to fix on principle. But leaking a JsonWriter that’s backed by an okio.Buffer is no big deal.

**Comment by EdwardLee03** [comment]
OK, very nice. 👍

**Comment by JakeWharton** [comment]
I'd rather fix this with a comment that it's not a leak. Try with resources
is unsuitable as Throwable.addSuppressed is only available on Android API
19+.

**Comment by EdwardLee03** [comment]
@JakeWharton Thanks for reminding! I don't consider Android compatibility issues.
