### ISSUE TITLE
D/onFailure: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 3 path $.

### ISSUE THREAD

**Issue by dilonne** [square/retrofit#2426]
Retrofit produces the above error even though the response from the server matches with the one received by Retrofit. I used postman to check my response from the server and it appears to be the same with the one I received im receiving in android.

**Comment by JakeWharton** [comment]
This error is from Gson, not Retrofit. There's nothing Retrofit can do if there's a disagreement between your data and the declared response model.

**Comment by mannan541** [comment]
Still having the same issue. My response is ok on postman and I have checked 100 times that my model classes are exactly according to my response model. If that is from GSON, then how to fix that bug?

**Comment by dilonne** [comment]
Depending on your issue, you might have to write your own custom GSON convertor
