### ISSUE TITLE
Feature Request: FlatBuffers Converter Support

### ISSUE THREAD

**Issue by vivekkiran** [square/retrofit#2427]
It would be great if Retrofit can support parsing flatbuffers .bin files and map it to java models through a converter.

https://google.github.io/flatbuffers/

**Comment by JakeWharton** [comment]
We are not adding any more first-party converters. Someone is free to make a third party implementation that we'll link to from the wiki though.

**Comment by msgilligan** [comment]
This would be useful. Has anyone made one? Is there any documentation on how to create a converter?
