### ISSUE TITLE
Retrofit - Append dynamic queries after hard coded queries inserted

### ISSUE THREAD

**Issue by yonimm** [square/retrofit#2429]
I need to set queries after hard coded queries inserted.

my API address is :

    myapiaddress/names?q=Yoni&gender=Man&(here i need to enter dynamic queries)
my API call :

`@GET("names")
Call<List<Integer>> searchNames(
    @Query("q") String q,
    @Query("gender") Gender gender);`
how can I do it?

**Comment by JakeWharton** [comment]
`@QueryMap` let you supply dynamic keys and their values.

**Comment by mneckoee** [comment]
Hi, my REST api allows me to have a SQL where clause query:
```
@GET(SERVICES_BASE_URL + "query?f=pjson&geometry=false&where=provinceName%3DN'{provinceName}'")
    Call<ResponsBody> getAllCities(@Path("provinceName") String provinceName, @Query("outFields") Set<String> outFields);
```
but this is illegal:
```java.lang.IllegalArgumentException: URL query string "f=pjson&geometry=false&where=provinceName%3DN'{provinceName}'" must not have replace block.For dynamic query parameters use @Query.```
How can I manage this? I don't want to use this:
```
@GET(SERVICES_BASE_URL + "query?f=pjson&geometry=false")
    Call<ResponsBody> getAllCities(@Query("where") String whereClause, @Query("outFields") Set<String> outFields);
```
Is there any other solution?

**Comment by hadjiprocopis** [comment]
Any solution to the above? What is the recommended way to replace variables inside the URL? Is there any reason why 
```
@GET("http://...xyz/?abc=1&where=X={X}+and+Y={Y}&out=2")
@Query("X") String X
```

Should I construct the ```where``` myself then? If the ```replacement block``` exists why it stops me from replacing ``{X}``` ??? Unless I am missing something, what's the point of using retrofit?
