### ISSUE TITLE
ServiceMethod.parseHeaders() strips 'Content-Type' header, thus not allowing CallFactory impl to Set on delegate

### ISSUE THREAD

**Issue by aaronvargas** [square/retrofit#2430]
In CallFacotry.newCall(Request request) the Request object has been stripped of the Content-Type header. So when I try to construct an, in my case, HttpUrlConnection, I cannot set the Content-Type (since the header is gone) and the server (not in my control) rejects the http call.

The header gets stripped in ServiceMethod.parseHeaders(). Really, parseHeaders(), or something else, should ADD headers for formUrlEncoded or such so that the Request is 'complete' for use in creating the final http delegate.

**Comment by swankjesse** [comment]
You can get the content-type from the RequestBody.
