### ISSUE TITLE
GsonFactory Gradle repository is incorrect in docs.

### ISSUE THREAD

**Issue by techtide** [square/retrofit#2431]
In the official docs, the Gradle repo is incorrect. Instead of:
com.squareup.retrofit2:converter-gson
It should be:
 compile 'com.squareup.retrofit:converter-gson:2.0.0-beta2'
Or any working, stable repository that actually compiles.

techtide

**Comment by JakeWharton** [comment]
This is incorrect. The documentation is accurate and the latest version is 2.3.0
