### ISSUE TITLE
Remove @FormUrlEncoded and @Multipart annotations

### ISSUE THREAD

**Issue by natebrunette** [square/retrofit#2432]
These annotations seem unnecessary as a corresponding `@Field` or `@Part` is required to make non-json requests.

**Comment by JakeWharton** [comment]
While they're not strictly needed since it could be inferred from the parameter annotations, we prefer them as they indicate the body-level format that's provided by the library as opposed to by user-code. So in this way they're somewhat documentary but also an explicit indication of intent.
