### ISSUE TITLE
Parallel HTTP calls fails sometimes

### ISSUE THREAD

**Issue by boyhasnoname** [square/retrofit#2435]
Hi Team,

We have a requirement like passing a token in header in every API calls and the token expire in every 1Hr. 
If the token expires, we make RefreshToken call and firther API calls will go with the updated token.
The scenario fails when the app makes two Api calls parallelly after 1Hr, Since 2 calls ready with the token at a time, first call will go and failed  due to token expired and it will make the RefreshToken api call and responds with new token. Since 2nd call already in queue, it will go with the old token again. Since the token already expired 2nd call will make another RefreskToken call and responds with new tokens. So for every parallel calls after 1Hr, server returns 2 Tokens. I would like to handle this scenario in android. Could you please help me?

Note: Making 2nd Call in onSuccess callback of first service call is not advisable :). That's not the requirement. 
 
Thanks in advance.

**Comment by JakeWharton** [comment]
This is a usage question which is generally more appropriate for StackOverflow. GitHub issues are reserved for bug reports with test cases or samples, or new feature requests. You can use the 'retrofit' tag which is monitored by us and many library users. Feel free to link the asked question back here on the issue.
