### ISSUE TITLE
Response caching for Post Request

### ISSUE THREAD

**Issue by vidhithakrar** [square/retrofit#2436]
We have two requirements in Caching response
1. Caching Post response. For some security concern, we are using Post instead of Get.
2. We need Stale-while-revalidating behavior

Initially, we had thought of using Intercepter to fulfill the above requirements by using cache control headers. But then we felt that it gives a wrong notion that network library is caching the Post response and hence we have thought of adding a layer on top of Retrofit to fulfill the above requirements.

We had two approaches:
1. Have a layer above Retrofit like custom ServiceClient which checks for the cache and then take appropriate actions. The problem in this approach is Retrofit needs Observables/Singles to be created from Service to make the request and hence, the abstraction becomes the callback hell which does not look good. Like,

`ServiceClient.refresh(GitHubClient.class, new ServiceCall{
public Observable service(client){
return client.getXXX()
}
public Observer observer(){
return new Observer(){
}
}
})`

2. We had thought of creating CacheableResponseObservable which can be created by applying CallAdapterFactory and which can provide abstractions like subscribe(CacheControl, Observer). The problem in this approach is we have to write so much logic to have custom observable just because there are some classes which are package private and final. Also, when we combine Observables or when we subscribeOn(scheduler) , it creates new wrapper and gives problems with Observables.

We were thinking of going ahead with 2nd approach as we thought it would be much cleaner to write as we can decorate things, but then we could not achieve it and had to write some logic to make it work. Is there anything wrong in this way of approaching the above requirements?

PS: We have just migrated to Retrofit + Rx and we are newbie here.

**Comment by rameshvoltella** [comment]
i also have same question when i use get methord  caching is happening, and as @vidhithakrar  said we use post for security reason the same response caching not happening and show the following error
504 Unsatisfiable Request (only-if-cached)

i followed https://stackoverflow.com/questions/42927216/retrofitokhttp-http-504-unsatisfiable-request-only-if-cached/42970263

can we cach post request on current version or i try any other way 
@JakeWharton

**Comment by rameshvoltella** [comment]
ok i think this is not possible i just saw issue #2586 anyway thanks

**Comment by swankjesse** [comment]
Probably simplest to do caching in the code that calls Retrofit, instead of inside Retrofit. What you're asking for is specific to your application
