### ISSUE TITLE
Dynamically choose the connectivity channel to perform http call

### ISSUE THREAD

**Issue by ashwinqb** [square/retrofit#2437]
- [ ] Feature Request

In customized version of Android OS if the Device is connected to wifi and it has no internet connectivity it will not try to perform the http call using the cellular data. if this is handld in the library itself it will be helpful. ie. when a http call is triggered the retrofir choose through wifi channel or cellular data the call must perform. In early android versions they supported ConnetivityManager.setPerference().  But now this is deprecated. If this feature is implemented. it will be vey helpful.
I mean to loop through the NetworkInterfaces and check the destinationAddress is reachable or not and then if reachable the call must perform through that interface.

**Comment by JakeWharton** [comment]
Retrofit doesn't make connections so perhaps you want to request this on OkHttp.
