### ISSUE TITLE
Upload multipartbody with progress dialog showing percentage

### ISSUE THREAD

**Issue by senthilbalajiganesan** [square/retrofit#2438]
I'm trying to upload a multipart body with progress dialog showing percentage using retrofit, how can  I find how to get the percentage/bytes uploaded to the server and so that I can update in UI?

**Comment by mopsalarm** [comment]
For this I've implemented `RequestBody.writeTo` to publish the progress while writing the content of the file ot upload to the sink.

**Comment by swankjesse** [comment]
Tracking in OkHttp: https://github.com/square/okhttp/issues/1471
