### ISSUE TITLE
Signal 6, Signal 11, ArrayIndexOutOfBoundsException and InstaRun

### ISSUE THREAD

**Issue by ortonas** [square/retrofit#2441]
Are there any plans on fixing [nearly two year old issue](https://github.com/square/retrofit/issues/1486)? 
I'm currently using Android Studio 3.0 Canary 9 with SDK 26 yet the issue keeps occurring at random points. The one and only solution is to disable InstaRun.

**Comment by JakeWharton** [comment]
Ask Google. There isn't anything to fix for Retrofit.
