### ISSUE TITLE
@QueryMap(encoded = false) always change my map value to encoded.

### ISSUE THREAD

**Issue by yonimm** [square/retrofit#2447]
@QueryMap(encoded = false) always change my map value to encoded. (i know the default is false)
this is my hashmap before i call to retrofit2 :

Map<String, String> parms = new HashMap<>();
parms.put("name","yoni");
parms.put("brand","h&m");

parms.toString() output is :
"name"="yoni","brand"="h&m"
my interface:
@GET("product")
Call<List<Integer>> searchNames(
@QueryMap() Map<String, String> options);

on response this is what i got:
"name"="yoni","brand"="h&m"
https://myApi.com/pepole?name=yoni&brand=h%26m

after searching i found %26 is & on encode.
why is happen?

**Comment by yunlongsoft** [comment]
maybe you must add "\" like this "\&"

**Comment by yunlongsoft** [comment]
maybe you must add "\\" like this "\\&"

**Comment by yonimm** [comment]
@yunlongsoft 
I can't do it because the android studio gives me this error:
Error:(296, 59) error: illegal escape character

**Comment by JakeWharton** [comment]
`&` is not a valid character in a query parameters value so OkHttp's URL encode corrects your mistake. This is expected behavior. The only way an ampersand can appear in a value is when encoded.
