### ISSUE TITLE
send dynamic keys with duplicate keys

### ISSUE THREAD

**Issue by yonimm** [square/retrofit#2448]
I need to send dynamic keys with duplicate keys.

**this is what i need:**
https://myApi.com/pepole?name=yoni&name=albert&brand=nike

all the keys are dynamics (name, brand).

so to do it dynamically i used  @QueryMap for exmpale:
Map<String, String> parms = new HashMap<>();
        parms.put(dynamicKey, dynamicValue);
        parms.put(anotherDynamicKey,anotherDynamicValue);

and this is my interface:
    @GET("pepole")
    Call<List<Integer>> searchPepole(
            @QueryMap Map<String, String> options);

 and is working fine but my problem starts when i have duplicate keys.

so how can i make call with dynamic keys with duplicates keys?

**Comment by FabianTerhorst** [comment]
You can try the ```org.apache.commons.collections.MultiHashMap;```. The HashMap supports only one value / key.

**Comment by JakeWharton** [comment]
Basically what @FabianTerhorst. Supporting something like Guava's `Multimap` requires #626 which we don't have a timeline on.
