### ISSUE TITLE
Throwable:End of input at character 0 of 

### ISSUE THREAD

**Issue by lucklyperson** [square/retrofit#2450]
I want to handler the  responseBody.string() by myself.

responseBody.string():{"code":1,"msg":"","cost":100}

 RetrofitServiceUtil.getRetrofitService().goods_basePrice(map)
                .subscribeOn(Schedulers.io())
                .observeOn(Schedulers.immediate())
                .subscribe(new Subscriber<ResponseBody>() {
                    @Override
                    public void onCompleted() {

                    }

                    @Override
                    public void onError(Throwable e) {

                    }

                    @Override
                    public void onNext(ResponseBody responseBody) {
                        try {
                            LogUtil.log(TAG, "result= " + responseBody.string());
                            JSONObject jsonObject = new JSONObject(responseBody.string());
                            int code = jsonObject.getInt("code");
                            if (code == 1) {
                                String cost = **jsonObject.getString("cost");**
                                tv_price.setText(cost);
                            } else {
                                String msg = jsonObject.getString("msg");
                                Toast.makeText(getActivity(), msg, Toast.LENGTH_SHORT).show();
                            }

                        } catch (IOException | JSONException e) {
                            LogUtil.log(TAG, "e=" + e.getMessage());
                            e.printStackTrace();
                        }
                    }
                });

**Comment by JakeWharton** [comment]
Calling `string()` consumes the body per the [`ResponseBody` documentation][1]:

> ### The response body can be consumed only once.
>
> This class may be used to stream very large responses. For example, it is possible to use this class to read a response that is larger than the entire memory allocated to the current process. It can even stream a response larger than the total storage on the current device, which is a common requirement for video streaming applications.
>
> Because this class does not buffer the full response in memory, the application may not re-read the bytes of the response. Use this one shot to read the entire response into memory with `bytes()` or `string()`. Or stream the response with either `source()`, `byteStream()`, or `charStream()`.

Call it once and re-use the returned `String` instance.

 [1]: https://square.github.io/okhttp/3.x/okhttp/okhttp3/ResponseBody.html
