### ISSUE TITLE
Read Error : Connectionn reset by peer

### ISSUE THREAD

**Issue by rajsuvariya** [square/retrofit#2451]
I am getting the following error

`FAILURE: Read error: ssl=0xb82927f8: I/O error during system call, Connection reset by peer`

What could be the reason for this? Is there anything I can do from mobile app side?

**Comment by JakeWharton** [comment]
You can retry or show an error message, basically. IO failures are a normal part of networking so you'll always have to deal with failures of the physical link between you and the remote server.

**Comment by rajsuvariya** [comment]
Yes I am showing a pupup with retry option and user tried the same for at least 15-20 times but everytime he got the same error

**Comment by rajsuvariya** [comment]
@JakeWharton Lately, I found out that this is happening only with some specific APIs. Other APIs are working totally fine even after getting this error once. Still, it might be the issue of the server or any trouble shooting can be done at mobile app end?

**Comment by JakeWharton** [comment]
I'm not sure. Those types of problems happen at layers much farther down
from Retrofit.
