### ISSUE TITLE
Kotilin: Unable to pass list of enum class element

### ISSUE THREAD

**Issue by antechrestos** [square/retrofit#2457]
Hi,

First of all thanks for your work. Your library is very helpfull for building quickly api client services.

I am currently working on version `"2.2.0"`. I wanted to build the following service in kotlin 1.1 (`List` refers to kotlin collection):

```kotlin

interface MyService{
    @GET("/my/api/path/that/wont/work")
    fun wontWork(
           @Query("enumParameter") enumParameters: List<EnumQueryParameter>?=null)
            : Call<String>
}

// ...
    val httpClientBuilder: OkHttpClient.Builder = OkHttpClient.Builder()
    val retrofit = Retrofit.Builder()
                .baseUrl("http://somewhere.org")
                .client(httpClientBuilder.build())
                .addConverterFactory(JacksonConverterFactory.create(JacksonConfig.objectMapper))
                .build()
    val service = retrofit.create(MyService::class.java)
    service.wontWork(listOf(EnumQueryParameter.one, EnumQueryParameter.two))
```

Running the above code raises me an exception:

```
java.lang.IllegalArgumentException: Parameter type must not include a type variable or wildcard: java.util.List<? extends com.orange.datashare.api.EnumQueryParameter> (parameter #1)
```

From what I understood, retrofit does not accept generic types as it needs to fully know what type of object is up to handle. Yet on that point I am not asking him to handle wild card type (even though enum class is saw as a `Enum<T>`)

What is more surprising is it accepts the following declaration (replacing `List`by `MutableList`)

```kotlin
interface MyService{
    @GET("/my/api/path/that/will/work")
    fun willWork(
            @Query("enumParameter") enumParameters: MutableList<EnumQueryParameter>?=null)
            : Call<String>
}
```

**Comment by JakeWharton** [comment]
You can add `@JvmSuppressWildcard` either inside the angle brackets before the `String` type, or before the `List`. Both should work and remove the wildcard.

**Comment by antechrestos** [comment]
@JakeWharton thank you very much
