### ISSUE TITLE
Retrofit moshi-adapter ignores @Json(name = "abc")

### ISSUE THREAD

**Issue by 540Grunkspin** [square/retrofit#2460]
So the problem seems to be that the name specified in the *Json* annotation gets ignored.

Here is a test i wrote: https://gist.github.com/540Grunkspin/7bc91dfe6053adedf4f809f58535e6ac

My gradle dependencies looks like this

```gradle
implementation 'com.squareup.retrofit2:retrofit:2.3.0'
implementation 'com.squareup.retrofit2:converter-moshi:2.3.0'
implementation 'com.squareup.moshi:moshi:1.5.0'
implementation 'com.squareup.okhttp3:okhttp:3.8.1'
implementation 'com.squareup.retrofit2:adapter-rxjava2:2.3.0'
testImplementation 'com.squareup.okhttp3:mockwebserver:3.8.1'
```

Im using kotlin 1.1.4-2.

Seems to be an issue with moshi 1.5.0 because it works fine with 1.4.0 I'm not really sure if this problem is a moshi problem or a "moshi-converter with the new moshi version" problem.

**Comment by 540Grunkspin** [comment]
Forgot to mention this same test works as expected when written in Java.

**Comment by JakeWharton** [comment]
If you use Moshi 1.5 or newer with Kotlin you have to use the 'moshi-kotlin' artifact as well. There's no other way for Moshi to know how to call constructors such that default values and nullability work correctly.

Retrofit behavior remains unchanged, as it just hands off to Moshi.

**Comment by 540Grunkspin** [comment]
Okay thank you for the fast response!

**Comment by alexandru-calinoiu** [comment]
Did using moshi-kotlin worked?

I have the same issue now and I have the both libraries in my project, moshi and moshi-kotlin

**Comment by alexandru-calinoiu** [comment]
@JakeWharton can you please reopen this issue?

**Comment by JakeWharton** [comment]
It's not a Retrofit issue.
