### ISSUE TITLE
How to use retorfit with Thread class ?

### ISSUE THREAD

**Issue by patelakshay13890** [square/retrofit#2461]
In my case I have to make 2 to 3 retrofit request in the background thread..
Without using RxJava..
So how can I achieve this ?
I have searched a lot but couldn't find appropriate way to achieve this..
Please do help me out of this situation...
Thanks..

**Comment by frankodoom** [comment]
Using retrofits .enque i believe is already asynchronuous

**Comment by patelakshay13890** [comment]
But what I want is repeative call for that

**Comment by JakeWharton** [comment]
Please ask usage questions on StackOverflow. GitHub issues are for bug reports and feature requests only.

That being said, it's not clear what you want beyond `Call.enqueue()` which is already asynchronous or `Call.execute()` which is synchronous (and with which you could bring your own thread).
