### ISSUE TITLE
Setting custom timeout not working

### ISSUE THREAD

**Issue by jablonskipj** [square/retrofit#2468]
Hello,

I have found out that for retrofit version 2.3.0. I have ask question on StackOverflow but no answer was fixing my problem. I am setting custom timeout on OkHttpClient object like:

`OkHttpClient client = new OkHttpClient.Builder()
 .connectTimeout(20, TimeUnit.SECONDS)
.writeTimeout(20, TimeUnit.SECONDS)
.readTimeout(20, TimeUnit.SECONDS)
.build()`

and then I just attach it to retrofit builder like:

` builder.client(client)`

but it has no effect. Request throw `SocketTimeoutException` after 10 seconds. I was also trying to set 0 as timeout, but is was not working too.

Can you take a look at this, because I assume that something is not working correctly.

Best regards,
Patryk

**Comment by JakeWharton** [comment]
Retrofit doesn't do anything with timeouts. If it's not being triggered then that happens at the OkHttp layer.
