### ISSUE TITLE
API Proposal - Retrofit.Builder.converterFactories()

### ISSUE THREAD

**Issue by naturalwarren** [square/retrofit#2471]
I have a `Retrofit` instance that's configured with a bunch of `CallAdapter.Factory` instances. I want to be able to call `newBuilder()` and swap in a new `GsonConverterFactory` built with a new `Gson` instance but `Retrofit.Builder` doesn't expose `List<Converter.Factory>`.

Would a PR be welcomed that adds such an API? Also, would we want a similar API for `List<CallAdapter.Factory>`?

**Comment by baristaze** [comment]
That would be a great addition.

**Comment by vidhithakrar** [comment]
Retrofit.Builder should not expose List<Converter.Factory>. Retrofit already exposes it via converterFactories() method.

**Comment by naturalwarren** [comment]
Once it's exposed as part of a Retrofit instance the list should be immutable and not allow for further configuration though right? As part of a Builder I'd like to modify the list in a similar fashion to how OkHttpClient.Builder let's you access a mutable list of interceptors.

**Comment by JakeWharton** [comment]
Feel free to send a PR to make the list public.

There's a decent amount of subtlety that has to be handled and tested. The
default converters which must be placed first must be moved into the
build() method so they're not exposed in the list. It also needs removed
when copying the existing set into the builder in newBuilder().

**Comment by naturalwarren** [comment]
Sounds good. Thanks!

**Comment by naturalwarren** [comment]
Reopened to track adding a sister API for call adapter factories.
