### ISSUE TITLE
how to handle response with both type: JSON object and JSON array?

### ISSUE THREAD

**Issue by macarthor** [square/retrofit#2472]
hi community,

my server team defines a terrible reponse, which may be a json object like `{key1=value1, key2=value2}`, and may be a json array like `[{key3=value3, key4=value4}, {key3=value3a, key4=value4a}]`

i cannot tell them to change this because this response is used by other like PC and iOS.

so what should i do with this four-letter-word-ing response?

**Comment by JakeWharton** [comment]
You can write a [type adapter / json adapter / whatever Jackson calls it] for your JSON serialization library of choice that checks for an object when you declare a binding to a collection and if it detects it, wraps it in `Collections.singletonList`. How to do this is different for each library, but it involves peeking at the next token and then based on whether it's an object beginning or array beginning either doing the single object deserialization and wrapping or the collection deserialization.

If you need more help doing that, StackOverflow or the mailing list for the JSON serialization library that you are using is the appropriate place, as Retrofit isn't involved at all in deserialization. It just hands the response body to your chosen JSON converter.

**Comment by macarthor** [comment]
@JakeWharton i'll try stackoverflow. many thx for the hint
