### ISSUE TITLE
Add the license to pom.xml so that google oss-licenses can pick it up automatically

### ISSUE THREAD

**Issue by martinbonnin** [square/retrofit#2473]
Google released a plugin that auto-generates the licenses automagically: https://developers.google.com/android/guides/opensource

Somehow though it looks like it's not picking up the retrofit one. Adding it to pom.xml should solve this.

**Comment by JakeWharton** [comment]
PRs welcome!

**Comment by martinbonnin** [comment]
Ok, let me try to see if I understand this xml thing...

**Comment by JakeWharton** [comment]
My guess is that the plugin isn't smart enough to read the parent poms,
which is sad. We declare the license in the root pom because it applies to
the whole repo.

**Comment by martinbonnin** [comment]
PR here: https://github.com/square/retrofit/pull/2475

With this I get an entry for `retrofit`. It feels a bit strange because it also creates entries for `converter-gson` and the likes without any 'retrofit' mention. I don't know if we want to merge it or just wait for the oss-licenses plugin to improve...

**Comment by iNoles** [comment]
Looks like they only added a value from artifactId

**Comment by JakeWharton** [comment]
I've filed this as a bug on the plugin. No action to take.

**Comment by twaddington** [comment]
@JakeWharton can you drop a link to your bug report? I searched issuetracker.google.com but couldn't find it.

**Comment by JakeWharton** [comment]
It's internal. There's no public bug tracker for play services because
Google is dumb.

**Comment by twaddington** [comment]
@JakeWharton ah word, that explains it. Thanks!
