### ISSUE TITLE
Dynamic HeaderMap, Body and Url always returns BadRequestException

### ISSUE THREAD

**Issue by AyoGitNg** [square/retrofit#2478]
` @POST
  fun sendFirebaseNotification(@HeaderMap headers: Map<String, String>?, @Url url: String?, @Body body : String): Call<FCMResponse>`

After hours of debugging with the same 401 badrequestException, I switched to Volley just to test and it works fine. I reverted to retrofit and still gets the same 401 error.

I am not sure if this is really a bug. I hope someone can reproduce it but i decided to report it

**Comment by JakeWharton** [comment]
Are you able to express this in an executable test case such as the one in
the issue template?

**Comment by AyoGitNg** [comment]
`class RetrofitBug {

    @get:Rule
    val server = MockWebServer()

    internal interface Service {
        @GET("/path")
        @Headers("User-Agent: Test Case")
        fun search(@Query("keyword") keyword: String): Call<ResponseBody>

        @POST
        fun dynamicTest(@HeaderMap headers: Map<String, String>?, @Url url: String?, @Body body : String): Call<FCMResponse>
    }

    @Test
    @Throws(Exception::class)
    fun test() {
        val retrofit = Retrofit.Builder()
                .baseUrl(server.url("/"))
                .build()
        val example = retrofit.create(Service::class.java)

        server.enqueue(MockResponse()
                .addHeader("Content-Type", "text/plain")
                .setBody("Hi"))

        val call = example.search("hello")
        val response = call.execute()
        assertEquals("text/plain", response.headers().get("Content-Type"))
        assertEquals("Hi", response.body().string())

        val recordedRequest = server.takeRequest()
        assertEquals("/path?keyword=hello", recordedRequest.path)
        assertEquals("Test Case", recordedRequest.getHeader("User-Agent"))
    }

    @Test
    fun dynamicTest() {
        val gson = Gson()
        val retrofit = Retrofit.Builder()
                .baseUrl(server.url("/"))
                .addConverterFactory(GsonConverterFactory.create(gson))
                .build()
        val example = retrofit.create(Service::class.java)

        server.enqueue(MockResponse()
                .addHeader("Content-Type", "text/plain")
                .setBody("Hi"))

        var header = HashMap<String, String>()
        header.put("Content-Type", "application/json")
        header.put("Authorization", "Some Auth")

        val bodyCreate = makeNotificationModel("test", "test", "test", "New Test Notification")

        val bodyModel = Model("test", bodyCreate)
        val bodyOFMessage = gson.toJson(bodyModel)

        val call = example.dynamicTest(header,"http://demo8481314.mockable.io/testmock",bodyOFMessage)
        val response = call.execute()

        assertEquals("text/plain", response.headers().get("Content-Type"))
        assertEquals("Hi", response.body())

    }
}
`

This didnt work either. I am not sure the test is right because i got SocketTimeoutException from the mock server i guess because i was testing a dynamic url

**Comment by JakeWharton** [comment]
Thanks. I'll try it out soon and see where I can go from there.

**Comment by swankjesse** [comment]
Unclear what action to take.

**Comment by NehaKushwah993** [comment]
same issue here.. this is because some headers get removed if we provide them using @HeaderMap.
I can see that when trying to check them using Interceptor.
