### ISSUE TITLE
Feature Request: Date URL parameters should be formatted using ISO8601Utils

### ISSUE THREAD

**Issue by emmanuelproulx** [square/retrofit#2479]
When serializing and deserialzing JSON (using Gson) dates (Java Date class) are taken care of perfectly. That's because the **Date class is recognized by Gson** and it's formatted and parsed using the class ISO8601Utils.

But when **passing a Date to a Retrofit method**, since it's **not recognized** as any of the supported types, Retrofit uses Object.toString() to format the Date. This is less than ideal. For consistency, Dates in URL parameters should be processed exactly like when serializing.

For this purpose, you should **recognize each instance of the Date class and format it using the ISO8601Utils class.**

**Comment by JakeWharton** [comment]
You can install a string converter that serializes any object type in any format you want. This allows you to achieve the behavior you want while others can have different behavior (maybe they want the `long` value). We've now come to know Gson's built-in Date handling as being a bad idea which is why you won't find it in Moshi–Gson's spiritual successor.

**Comment by emmanuelproulx** [comment]
OK it's good to know there's a workaround but still there should be a solid default implementation for Date serializing. ISO8601 is a good standard for such default.

Can you please expand on the down-side of Gson's Date handling?

**Comment by JakeWharton** [comment]
This isn't a workaround, it's a designed feature which lets you accomplish what you want.

The problem with Gson is that some people want millis and some don't. Some want named timezones and others want offsets. And various servers and client supports various combinations of these things and rejects others. The same would be true here and it would cause a customization and API nightmare trying to figure out how to support it. And besides some will need entirely different formats which means the behavior would have to also be overridable.

**Comment by emmanuelproulx** [comment]
I understand that the user _should_ decide on a format. But right now he _doesn't have to_. So I still think there should be a chosen default date format based on a standard (any standard is better than none) used by both URL parameters and Json serialization.

Right now the default is toString() which is a horrible default because it's not standard, verbose, with spaces, made for humans and not for parsing. Example "Sun Dec 12 13:45:12 CET 2010". Not only that, but it's a inconsistent because it is different from the format used in JSON serialization. At the very least both default formats should be the same and not different.

Alternatively you could force the user to specify a date format.

**Comment by JakeWharton** [comment]
toString is the standard for all types which is nice and simple.
