### ISSUE TITLE
allow retrofit2.Converter to add, remove, or replace request headers

### ISSUE THREAD

**Issue by dawud-tan** [square/retrofit#2480]
allow retrofit2.Converter to add, remove, or replace request headers

**Comment by JakeWharton** [comment]
For what purpose?

**Comment by dawud-tan** [comment]
Sorry for the late response @JakeWharton , what I want to do is to build the equivalent converter for `Content-Type: application/pkcs7-mime; name="smime.p7m"; smime-type=enveloped-data`, as @patriot1burke already did in his code [EnvelopedWriter](https://github.com/resteasy/Resteasy/blob/master/security/resteasy-crypto/src/main/java/org/jboss/resteasy/security/smime/EnvelopedWriter.java).

His implementation implements [MessageBodyWriter](https://github.com/jax-rs/api/blob/master/jaxrs-api/src/main/java/javax/ws/rs/ext/MessageBodyWriter.java#L123
) interface as provided by [JAX-RS API](https://github.com/jax-rs), the interface let the converter (or MessageBodyWriter in JAX-RS API) to modify the http headers. As [RFC 3851](https://tools.ietf.org/html/rfc3851#section-3.2.1) instruct that `Sending agents SHOULD also emit the optional Content-Disposition field [CONTDISP] with the "filename" parameter.` For example: `Content-Disposition: attachment; filename=smime.p7m`

My current workaround is by implementing okhttp3.Interceptor interface, following is my implementation [Pkcs7MimeConverter](https://github.com/dawud-tan/RetrofitSmime/blob/master/app/src/main/java/retrofit2/converter/pkcs7_mime/Pkcs7MimeConverter.java#L84).
