### ISSUE TITLE
Null data returned

### ISSUE THREAD

**Issue by JoyHong** [square/retrofit#2482]
I/OkHttp: --> GET https://interface.meiriyiwen.com/article/day?dev=1&date=20170912 http/1.1
I/OkHttp: --> END GET
I/OkHttp: <-- 200 OK https://interface.meiriyiwen.com/article/day?dev=1&date=20170912 (107ms)
I/OkHttp: Server: nginx
I/OkHttp: Content-Type: application/json
I/OkHttp: Transfer-Encoding: chunked
I/OkHttp: Connection: keep-alive
I/OkHttp: Cache-Control: no-cache, private
I/OkHttp: Date: Fri, 15 Sep 2017 08:19:56 GMT
I/OkHttp: Strict-Transport-Security: max-age=31536000
I/OkHttp: X-Frame-Options: DENY
I/OkHttp: X-Content-Type-Options: nosniff
I/OkHttp: X-XSS-Protection: 1; mode=block
I/OkHttp: X-UA-Compatible: IE=Edge,chrome=1
I/OkHttp: {"data":[]}

But when from web browser, it has data returns.

What's wrong?

**Comment by JakeWharton** [comment]
There's not enough information here to determine where the problem is, if there is one. Can you express it in the form of a failing test case or executable sample?

**Comment by JoyHong** [comment]
RetrofitHelper.java

public class RetrofitHelper {

    private static Apis apis = new Retrofit.Builder()
            .baseUrl(Apis.HOST)
            .client(newOkHttpInstance())
            .addConverterFactory(GsonConverterFactory.create())
            .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
            .build()
            .create(Apis.class);

    private static OkHttpClient newOkHttpInstance() {
        HttpLoggingInterceptor loggingInterceptor = new HttpLoggingInterceptor();
        loggingInterceptor.setLevel(HttpLoggingInterceptor.Level.BODY);
        OkHttpClient.Builder builder = new OkHttpClient.Builder();
        builder.addInterceptor(loggingInterceptor);
        builder.connectTimeout(15, TimeUnit.SECONDS);
        builder.readTimeout(15, TimeUnit.SECONDS);
        builder.writeTimeout(15, TimeUnit.SECONDS);
        builder.retryOnConnectionFailure(false);
        return builder.build();
    }

    public static Observable<Object> fetchTodayArticle() {
        return apis.fetchTodayArticle(1);
    }

}

-------------------------------------------------------------------------
Apis.java

interface Apis {

    String HOST = "https://interface.meiriyiwen.com/article/";

    @GET("today")
    Observable<Object> fetchTodayArticle(@Query("dev") int dev);

}

--------------------------------------------------------------------------

RetrofitHelper.fetchTodayArticle()
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Action1<Object>() {
                    @Override
                    public void call(Object o) {

                    }
                }, new Action1<Throwable>() {
                    @Override
                    public void call(Throwable throwable) {

                    }
                });

**Comment by JoyHong** [comment]
Please help to have a check, thx.

**Comment by JoyHong** [comment]
Dears, any update?

**Comment by caseykulm** [comment]
Can you write this as a failing test with the expected assertion? If you do that it will make it much easier for people to help you.

**Comment by JoyHong** [comment]
@caseykulm 
If you run my sample, you will get the issue.
But if you visit the url via browser, it's ok.
I dont know what's the problem.

**Comment by caseykulm** [comment]
@JoyHong The server wants you to send a User-Agent header, and refuses to give you content if you don't set it. I guessed it at first by seeing,

```
I/OkHttp: X-XSS-Protection: 1; mode=block
I/OkHttp: X-UA-Compatible: IE=Edge,chrome=1
```

and confirmed it by sending with a User-Agent header.

I would recommend following the OkHttp interceptor recipe here they use to globally add a User-Agent header, https://github.com/square/okhttp/wiki/Interceptors#application-interceptors

**Comment by JakeWharton** [comment]
Thanks @caseykulm !

**Comment by JoyHong** [comment]
@caseykulm 
it works, thanks very much!
