### ISSUE TITLE
Support for Paging Library

### ISSUE THREAD

**Issue by geftimov** [square/retrofit#2484]
The new library from Architecture Components is about pagination.
Would retrofit provide a support for it?

https://developer.android.com/topic/libraries/architecture/paging.html

So something like the following could possible:
```
@GET("/articles")
TiledDataSource<Article> getArticles();
```

**Comment by JakeWharton** [comment]
I don't see any way to do this in a general case. Some APIs return pagination info in the headers and some in the body. Some APIs want pagination requests in the URL path and other wants them in the query parameters. Some APIs returns pagination tokens for follow-up requests while others use simple indexing.

If we can't solve 90% of the cases with this integration then I don't want to do it, and it seems to be that way here. If your API supports pagination it should be as simple as creating two endpoints and then wrapping them manually in one of the two `DataSource` implementations.

Beyond just supporting the shape of requests that need to be made, there's no infrastructure set up inside Retrofit for call adapters to modify requests or issue multiple requests. They're simple transformations from Retrofit's `Call<T>` to some other type (in this example `TiledDataSource<T>`). So this restriction also pushes us towards defining multiple endpoints and then wrapping them in a `DataSource` manually.
