### ISSUE TITLE
Response is in errorBody() instead of body()

### ISSUE THREAD

**Issue by liauli** [square/retrofit#2485]
I get strange behaviour from retrofit. most of API I used has at least "status" and "code" response.

![image](https://user-images.githubusercontent.com/16285098/30529658-d73be360-9c69-11e7-9ea2-892cd2705c34.png)

when the "status" is "failed", retrofit will return error "Internal Server Error" and response.body() is null.
but it's actually received the response in errorbody() NOT in body().
Why it's like that? and how I switch the response to body()?

**Comment by JakeWharton** [comment]
Can you provide a failing test case that demonstrates the problem?

**Comment by workingenius** [comment]
I have the same question. Although it is old, let me say something about it.

I think checking http status code has nothing to do with checking http body. They should be "orthogonal".
Even if it is a 400 response, http body should also be deserialized. Anyway I have to do it by myself sometimes, and the code is more complex;

What I suppose would work is something like this:
```java
class ModelClass {
  public int errorCode;
  public int successReturnVal;
}

Response<ModelClass> response = getResponseSomehow();  // A 400 response
final boolean isSuccessful = response.isSuccessful();
final int errorCode = response.body().errorCode();
if (!isSuccessful && errorCode == 1) {
  // xxx
} else if (!isSuccessful && errorCode == 2) {
  // yyy
} else if (!isSuccessful) {
  // default error handing
} else {
  // no error
}
```

Now I have to write like this:
```java
Response<ModelClass> response = getResponseSomehow();  // A 400 response
if (response.isSuccessful()) {
  // no error
} else {
  ResponseBody errorBody0 = response.errorBody();
  if (errorBody0 != null) {
    final String errorBodyString = errorBody0.string();
    ModelClass errorBody = deserializeErrorBodySomehow(errorBodyString, ModelClass.class);
    if (errorBody.errorCode() == 1) {
        // xxx
    } else if (errorBody.errorCode() == 2) {
        // yyy
    } else {
        // default error handing
    }
  } else {
    // blabla
  }
}
```

And this pattern is seen repeated a lot of times in our code.

I just think this design is not "naive".
I just wonder how it came into being, and what part I missed. 
And is it possible to change it?

**Comment by JakeWharton** [comment]
> I think checking http status code has nothing to do with checking http body. They should be "orthogonal".

This is simply untrue. Both 400 and 500 responses can be performed at layers of the stack that have no knowledge of the 200-level response body type. If you speak protos you might get a JSON 400 response. If you speak XML you might get an HTML 500 response.

The current response object is effectively an either type with the declared response body type for success and a generic response body container for non-success. If you would like to deserialize alternate status codes within a custom type and through a custom adapter. 

More info and details on how to build custom adapters here: https://youtu.be/t34AQlblSeE?t=3009

> And is it possible to change it?

No. I don't believe the change is justified, but it is also a massive breaking behavioral change.
