### ISSUE TITLE
retrofit2 in callback view is null

### ISSUE THREAD

**Issue by sk-huang** [square/retrofit#2491]
hello：
    my app has retrofit2 & rxjava2 & butterknife, when i use appcompat-v23-2-daynight theme,  a request ends, in callback， my views is all null.    
   but,  When i replace the retrofit2 with the retrofit1，replace the rxjava2 with the rxjava1.   it is ok

**Comment by JakeWharton** [comment]
If your views are null then the request is either returning before you've bound them or after you've unbound them.

If you can write a failing test case or sample that reproduces the problem we can take a look. But otherwise this is not enough information for an actionable bug report.
