### ISSUE TITLE
Exception on http 201 with empty body

### ISSUE THREAD

**Issue by frankkienl** [square/retrofit#2492]
What kind of issue is this?
 - [X] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. 

Gist with failing test:
https://gist.github.com/frankkienl/374326a003c82b3fe54bd56adf30a293

HTTP status 204 No Content will return an empty body.
HTTP status 201 MAY return an empty body, if the Location-header is present.
And in my case, it does.

204 will correctly handle this empty body, but 201 will try to parse an empty body. Which results in an Exception. (when using enqueue, it will end up in onFailure)

Maybe relevant line of code:
https://github.com/square/retrofit/blob/1ca821af67bfec8e8da0d0e99f2444080be5a041/retrofit/src/main/java/retrofit2/OkHttpCall.java#L207

Steps to reproduce:
- Create a Retrofit instance using the Retrofit.Builder.
- call .addConverterFactory(GsonConverterFactory.create()) on the builder.
(Bug wont happen if you dont use GsonConverter so it seems)
- Make a REST (POST) call that will result in a HTTP 201, with no body.

What happens:
"java.io.EOFException: End of input at line 1 column 1 path $"

What should happen:
No exception

**Comment by JakeWharton** [comment]
Thanks for the test!

So what would you expect the behavior to be in this case?

**Comment by JakeWharton** [comment]
I mean obviously it's not the exception, but do you want a null body?
Something else?

**Comment by frankkienl** [comment]
I would expect same behavior as 204, so not null. But an instance of the response class, that contains no content.

**Comment by frankkienl** [comment]
Found a workaround, 
as the expected body will always be empty, there is no use parsing it, to a specific own class.
Using `ResponseBody` instead of `MyEmptyResponseBody` seems to help prevent the exception.

**Comment by JakeWharton** [comment]
If you'll always get no body then use Void. I thought the problem was that
the body is only empty sometimes.
