### ISSUE TITLE
Backslash in string in POST request 

### ISSUE THREAD

**Issue by MedveDomg** [square/retrofit#2493]
Hello, I'm trying to send post request with @Body parameter and this parameter includes string like "2017\09\22" and when i see log, this string converts to "2017\/09\/22" . I use jackson convert with retrofit.

**Comment by JakeWharton** [comment]
Retrofit doesn't deal with serializing the body. Sounds like something
Jackson is doing. If you can write a failing test case we can take a look,
otherwise there's no way to guess what's going on.
