### ISSUE TITLE
BUG? "@GET @QUERY"

### ISSUE THREAD

**Issue by c3stream** [square/retrofit#2500]
I tried to test it, but I didn't make it well.

This is a problem that never happened before.

Please confirm.

https://gist.github.com/c3stream/45b2abd901744bc14c0833295ea1220b

**Comment by c3stream** [comment]
# Result
/text/plain: text/plain
/Hi: Hi
/path?keyword=hello: /path
/Test Case: Test Case

path is bug? @Query dosen't work.

**Comment by NightlyNexus** [comment]
The query is not part of the path. I think you want RecordedRequest.getRequestUrl().query() to get the query.

**Comment by JakeWharton** [comment]
What he said.

**Comment by c3stream** [comment]
Thanks for watching.
Android Studio 3.0 Canary beta6 make the binaries seem to have been funny.
Android Studio 3.0 Canary beta7 it was fixed!
