### ISSUE TITLE
@QueryMap(encoded = true) Map<String, Object> message);  ERROR ??

### ISSUE THREAD

**Issue by youngonlyforyou** [square/retrofit#2503]
ArrayList<String> list;
list.add("android");
list.add("ios");

Map<String, Object> message = new HashMap<>();
message.put("uid", "me");
message.put("groupIds",list);

@Multipart
        @POST("{specialMode_company}/{specialMode_services}")
        Observable<ResponseBody> faceIdentify(@Path("specialMode_company") String specialMode_company,
                                                    @Path("specialMode_services") String specialMode_services,
                                                    @Part MultipartBody.Part part,
                                                    @QueryMap(encoded = true) Map<String, Object> message);

My friend .. i want know , these code NO Proplem ?

**Comment by youngonlyforyou** [comment]
server 
const formData = {
        uid: uid2,
        groupIds: ["group2", "group3"],
        file: fs.createReadStream(emotion_5),
    };

**Comment by JakeWharton** [comment]
Can you express your problem in a failing test case? It's not clear where you think the problem is.
