### ISSUE TITLE
@QueryMap not encode query which contains '^' to '%5e'

### ISSUE THREAD

**Issue by chardlau** [square/retrofit#2504]
As title.

I wan to send ^ as value of keyword:
http://localhost/v1.0.0/api/activity?pageSize=20&keyword=^&pageNum=1

So I use @QueryMap to collect all params above and send it to '@GET'

I image it should be encoded but it do not.
http://localhost/v1.0.0/api/activity?pageSize=20&keyword=%5e&pageNum=1

Should I do url encode myself before collection?

Below is some information may help.

The latest version of Tomcat seem no support these characters below:

`
if (IS_CONTROL[i] || i > 127 ||
                    i == ' ' || i == '\"' || i == '#' || i == '<' || i == '>' || i == '\\' ||
                    i == '^' || i == '`'  || i == '{' || i == '|' || i == '}') {
        if (!REQUEST_TARGET_ALLOW[i]) {
                IS_NOT_REQUEST_TARGET[i] = true;
        }
}
`

while
 i is target character.
 IS_CONTROL is a list of control characters no printable.
 REQUEST_TARGET_ALLOW seems to be a white list.

REQUEST_TARGET_ALLOW only can configure to pass checking these characters:
`
if (c == '{' || c == '}' || c == '|') {
                    REQUEST_TARGET_ALLOW[c] = true;
                } else {
                    log.warn(sm.getString("httpparser.invalidRequestTargetCharacter",
                            Character.valueOf(c)));
                }

`

**Comment by JakeWharton** [comment]
As you can see on http://tinyurl.com/url-escaping row 37 and columns AC through AF, no major web browser encodes this character. You should file a bug on Tomcat for their broken expectations.
