### ISSUE TITLE
in maven repo v2.3.0 depends on com.squareup.okhttp3 » okhttp 3.8.0  NOT 3.9.0

### ISSUE THREAD

**Issue by DanielCharczynski** [square/retrofit#2505]
Could you update maven repo to use okhttp 3.9.0

https://mvnrepository.com/artifact/com.squareup.retrofit2/retrofit/2.3.0

**Comment by PromanSEW** [comment]
2.4.0 snapshot is already uses 3.9.0
https://github.com/square/retrofit/blob/af406dd527830832c5825db80a3a6071821aac9f/pom.xml#L52
You cannot modify dependencies for already released version, you need to release new version for that.

**Comment by JakeWharton** [comment]
If you want to use OkHttp 3.9.0 you can always depend on it directly.
