### ISSUE TITLE
onFailure() gets called though status code is 401.

### ISSUE THREAD

**Issue by Neha1490** [square/retrofit#2506]
What kind of issue is this?

What I am trying to achieve is - If same user login on some other device (say device B) ,then on the previous device(say device A) its token gets invalid. So if the user tries to continue doing some operation on previous device i.e. device A, then on some api's breakpoint is passed to onFailure method with EOF exception though I am getting status code 401 from backend. One of the api's example is uploading images to server. 
 

**CODE -**
`public static OkHttpClient buildClient(){
			HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
			interceptor.setLevel(HttpLoggingInterceptor.Level.BODY);

			OkHttpClient okHttpClient = new OkHttpClient().newBuilder()
					.addInterceptor(interceptor)
					.connectTimeout(60 * 5, TimeUnit.SECONDS)
					.readTimeout(60 * 5, TimeUnit.SECONDS)
					.writeTimeout(60 * 5, TimeUnit.SECONDS).addInterceptor(new Interceptor() {
						@Override
						public okhttp3.Response intercept(Chain chain) throws IOException {
							if (!auth_token.equalsIgnoreCase("")) {
								Request originalRequest = chain.request();
								Request.Builder builder = originalRequest.newBuilder().header("Authorization", auth_token);
								Request newRequest = builder.build();
								//accesses the server response
								return chain.proceed(newRequest);
							}
							return chain.proceed(chain.request());
						}
					}).build();

			return okHttpClient;
		}

public static Retrofit getClient(String token) {
				
				OkHttpClient httpClient = buildClient();
				auth_token = token;
				retrofit = new Retrofit.Builder()
						.baseUrl(BASE_URL)
						.client(httpClient)
						.addConverterFactory(GsonConverterFactory.create())
						.build();
				
				return retrofit;
		}

**API CALL -**

private void call_addAlbumApi() {
        ApiInterface apiService = ApiClient.getClient("Token " + readPref.getAuthToken()).create(ApiInterface.class);
        MultipartBody.Part[] body = new MultipartBody.Part[selectedImages.size()];
        String[] imagesArray = new String[selectedImages.size()];
        List<MultipartBody.Part> images = new ArrayList<>();

 Call<Result> call = apiService.addAlbum(title, subtitle, body);

 call.enqueue(new Callback<Result>() {
            @Override
            public void onResponse(Call<Result> call, Response<Result> response) {
  if (response.isSuccessful()) {
// get response and do appropraite action
}  else {
                    if(response.code() == 401){
// logout user with relevant msg
}

 @Override
            public void onFailure(Call<Result> call, Throwable t) {
// getting java.io.EOFException  here
}`

What may be the reason of this problem and is it possible to access status code inside onFailure()

**Comment by JakeWharton** [comment]
You haven't provided enough information to determine the cause. In all likelihood, the server sent less bytes than the client was expecting. In this case, the request is failed and you are unable to access any information about it, including the status code.

**Comment by Neha1490** [comment]
Please let me know what else information is required. 

I have implemented logging interceptor also and I am getting status code 401 by interceptor. So according to me I am able to get the status code.

**Comment by JakeWharton** [comment]
The stacktrace should help show you the cause

**Comment by Neha1490** [comment]
In the stacktrace I am getting status code 401 but when I debug the code,its executing the onFailure() part with EOFException. Its not executing onResponse() part.

**Comment by Neha1490** [comment]
Thank you for your response.

There was some middleware problem from backend. It has been solved now.
