### ISSUE TITLE
Proguard Warning: library class retrofit2.BuiltInConverters$StringConverter extends or implements program class retrofit2.Converter

### ISSUE THREAD

**Issue by ncapdevi** [square/retrofit#2512]
`Warning: library class retrofit2.BuiltInConverters$StringConverter extends or implements program class retrofit2.Converter`
The job fails with the following warning:
Warning: there were 1 instances of library classes depending on program classes.
         You must avoid such dependencies, since the program classes will
         be processed, while the library classes will remain unchanged.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#dependency)

On using the Android Studio 3.0 Beta 7

Proguard includes the following
```
-dontwarn okio.**
# Keep Retrofit
# Platform calls Class.forName on types which do not exist on Android to determine platform.
-dontnote retrofit2.Platform
# Platform used when running on Java 8 VMs. Will not be used at runtime.
-dontwarn retrofit2.Platform$Java8
# Retain generic type information for use by reflection by converters and adapters.
-keepattributes Signature
# Retain declared checked exceptions for use by a Proxy instance.
-keepattributes Exceptions
```

If I add  `-dontwarn retrofit2.Converter` the issue goes away and the build completes successfully

**Comment by JakeWharton** [comment]
The `Converter` type is referenced directly by the `Retrofit` type and therefore needs no rule. Perhaps you have some aggressive, non-default optimizations turned on that's trying to flatten hierarchies?

**Comment by ncapdevi** [comment]
Hmm, not sure what that would be. I have `minifyEnabled true` as the only thing in the build.gradle other than that, scanning through my Proguard I don't see any overarching rules. Is it possible it relates to the new `api` vs `implementation` in Gradle?

**Comment by JakeWharton** [comment]
Which ProGuard file from the SDK are you using? The normal one, or the one suffixed with `-optimize`?

**Comment by ncapdevi** [comment]
The normal one, `proguard-android.txt`, with `-dontoptimize`

**Comment by ncapdevi** [comment]
Okay, figured it out. I have a `common` library that my module imports. In that module, I was using 

```
implementation "com.squareup.retrofit2:retrofit:$versions.retrofit2"
implementation "com.squareup.retrofit2:converter-gson:$versions.retrofit2"
```
changing that to 
```
api "com.squareup.retrofit2:retrofit:$versions.retrofit2"
api "com.squareup.retrofit2:converter-gson:$versions.retrofit2"
```

fixes it, which I think makes sense.

**Comment by JakeWharton** [comment]
Maybe. I mean it's definitely not a Retrofit issue so that's always great. But I would think that the entire runtime classpath would have been presented to ProGuard (api + implementation) since it's doing whole-program analysis. Are you using AGP 3.0b7?

**Comment by ncapdevi** [comment]
Yup, indeed I am.  The other curious thing is that it was never an issue in debug builds even though I have `minifyEnabled true` for those builds as well (although I may just be uninformed as to if proguard treats release/debug differently even outside of them having different proguard files). The only difference between my debug/release proguards is that the debug has

```
-dontobfuscate
-useuniqueclassmembernames
-allowaccessmodification

```
