### ISSUE TITLE
addConverterFactory does not call toJSON on my POJO objects as a @Field parameter

### ISSUE THREAD

**Issue by ebbnormal** [square/retrofit#2514]
I am trying to leverage retrofits `addConverterFactory()` functionality when I build my retrofit instance so that I can deserialize JSON into POJOs, and serialize POJOs into JSON. The former works, The latter does not within a `@PUT` request. Here is my `@PUT` request: 

             @FormUrlEncoded
             @PUT("Accounts/me")
             Call<Account> updateAccount(@Field("account") Account account,
                                @Field("password") String password,
                                @Field("newPassword") String newPassword); 

However when I parse the request on the server side the `Account account` is not turned into JSON by GSON. It gets  a string which is the class name of my POJO. 

In Another project we have the following retrofit `@POST` request which has a similar pattern and it properly serializes into JSON: 
 
           
             @FormUrlEncoded
             @POST("Addresses")
              Call<AccountAddress> createAddress(@Field("address") Address address,
                                @Field("isDefault") boolean isDefault);

Here is the definition of the account: 

    `public class Account extends BaseObservable implements Cloneable {
       public int id;
       public int mediaId;
       public  String firstName;
       public  String lastName;
       public String email ="";
       public String password;
       public String addressLine1;
       public String addressLine2;
       public String city;
       public String region;
       public String phone;
       public String gender;
       public String postalCode;
       public boolean isSetUp;
       public String accessToken;

    public String getAccessToken() {
        return accessToken;
    }

    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Bindable
    public int getMediaId() {
        return mediaId;
    }

    public void setMediaId(int mediaId) {
        this.mediaId = mediaId;
    }

    @Bindable
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Bindable
    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Bindable
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
        notifyPropertyChanged(BR.email);
    }

    @Bindable
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
        notifyPropertyChanged(BR.password);
    }

    @Bindable
    public String getAddressLine1() {
        return addressLine1;
    }

    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }

    @Bindable
    public String getAddressLine2() {
        return addressLine2;
    }

    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }

    @Bindable
    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @Bindable
    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    @Bindable
    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Bindable
    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    @Bindable
    public String getPostalCode() {
        return postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    @Bindable
    public boolean isSetUp() {
        return isSetUp;
    }

    public void setSetUp(boolean setUp) {
        isSetUp = setUp;
    }

    @Override
    public Object clone() throws CloneNotSupportedException {
        return super.clone();
    }
   }`
    

And here is where we add the GsonConverterFactory in our building of our retrofit instance: 

` OkHttpClient defaultHttpClient = new OkHttpClient.Builder()
                    .addInterceptor(new Interceptor() {
                        @Override
                        public Response intercept(Interceptor.Chain chain) throws IOException {
                            Request authorisedRequest = chain.request().newBuilder()
                                    .addHeader("Authorization", AccountManager.sharedManager().getAccessToken()).build();
                            return chain.proceed(authorisedRequest);
                        }
                    }).build();
            retrofitInstance = new Retrofit.Builder()
                    .baseUrl(Application.get().getString(R.string.base_url))
                    .addConverterFactory(GsonConverterFactory.create())
                    .client(defaultHttpClient)
                    .build();`

When we call: 

        Gson gson = new GsonBuilder().disableHtmlEscaping().create();
        String accountJson = gson.toJson(account);

explicitly in our Activity and then make the `@Field` parameter for Account a string, it works. I just thought that since we added the ConverterFactory explicitly we wouldn't need to serialize by hand each object.

**Comment by ebbnormal** [comment]
When I override the `toString()` method on the POJO class, and then call the `toJson()` there it serializes correctly.... but why? I can't see this requirement in retrofit nor in GSON. which library calls `toString` implicitly?

**Comment by JakeWharton** [comment]
Per the [docs on `@Field`](http://square.github.io/retrofit/2.x/retrofit/retrofit2/http/Field.html), values are converted using a string converter, not a request body converter like Gson. If you want a JSON-encoded field value, you'll need to register a converter factory which uses Gson when asked to serialized to a string. Retrofit doesn't provide one by default. I believe I've posted one as a comment before, but I'm on mobile and searching for it is hard.

**Comment by ebbnormal** [comment]
@JakeWharton okay that makes way more sense. Forgive me for not looking close enough at the actual Javadoc source. So then performing the `@Override` isn't an anti-pattern for retrofit, but is rather as designed if I am using `@Field`s? Thank you again for your expedient reply and help.

**Comment by JakeWharton** [comment]
Yeah sorry I forgot to mention that. The default string converter just
calls toString on the object. So you can either use a value (or wrapper)
with a toString, or register a string converter that does the custom
conversion that you want.
