### ISSUE TITLE
20% .....rawCall

### ISSUE THREAD

**Issue by youngonlyforyou** [square/retrofit#2516]
ArrayList<String> groups_ThisPersonJoin;
Map<String, Object> message = new LinkedHashMap<>();
message.put("uid", "jack");
message.put("groupIds",groups_ThisPersonJoin);
<img width="741" alt="2017-10-08 9 06 06" src="https://user-images.githubusercontent.com/28915390/31317068-bdefc70a-abff-11e7-92aa-34a7e62d379d.png">
<img width="1140" alt="2017-10-08 9 07 55" src="https://user-images.githubusercontent.com/28915390/31317071-d2c34e9a-abff-11e7-8a3c-f1cc41c87b49.png">

**Comment by JakeWharton** [comment]
It's not clear what you're asking (not that this is the place for questions) or if you're reporting a bug. Please express any bugs as failing test cases or executable samples such that we can reproduce them locally. General questions should be directed to StackOverflow with the 'retrofit' tag.
