### ISSUE TITLE
Add Scala retrofit adapter

### ISSUE THREAD

**Issue by Abrasha** [square/retrofit#2517]
What kind of issue is this?

 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I see that there are plenty of existing adapters. I do like Retrofit and its style, e.g. (copying http clients, declarative style, etc.)

What do you think about adding Scala adapter?

For example, signature of endpoint method will be:

```
public interface GitHub {
   @GET("/repos/{owner}/{repo}")
   Future<Response<Repository>> contributors(@Path("owner") String owner, @Path("repo") String repo);
}
```

**Comment by JakeWharton** [comment]
Is the Future API stable? I quick looks makes it seem like it hasn't
changed much.

Also what's the story with the multiple version thing? I don't want to have
to publish multiple artifacts for different versions of the language.

**Comment by Abrasha** [comment]
Hi @JakeWharton! Thank you for paying attention.

I believe it is stable enough. At least public method that are responsible for instantiating Future (which we actually need in Retrofit, am I right?).

Well.. story with Scala versions is pretty sad for us as Java developers. I can't say exactly if we need to public it for all versions. I can investigate and even write simple example of such adapter if you want.

**Comment by JakeWharton** [comment]
I already have one fully written and tested. I'm trying to research the API
guarantees and distribution questions which are the more important things
here.
