### ISSUE TITLE
[Question] String[] headers in Kotlin

### ISSUE THREAD

**Issue by norman784** [square/retrofit#2518]
I'm wondering how to implement this in Kotlin

```java
@Headers({
    "Accept: application/vnd.github.v3.full+json",
    "User-Agent: Retrofit-Sample-App"
})
```

Regards

**Comment by NightlyNexus** [comment]
Does `arrayOf` not work?
This issue tracker works best for bugs with test cases and feature requests.
StackOverflow has people who can answer usage questions about Kotlin, Retrofit, etc.

**Comment by norman784** [comment]
It doesn't, it complains about requiring String but Array<String> passed. I ended up using an interceptor to setup the headers. 

Thanks

**Comment by JakeWharton** [comment]
`arrayOf` will work. If not it's a Kotlin bug. See https://kotlinlang.org/docs/reference/annotations.html#java-annotations.

**Comment by NightlyNexus** [comment]
Kotlin seems to understand Java arrays in annotations as varargs. (filed as possible bug: https://youtrack.jetbrains.com/issue/KT-20691)

```kotlin
@Headers(
    "Accept: application/vnd.github.v3.full+json",
    "User-Agent: Retrofit-Sample-App"
)
```
(not `arrayOf`)
in Kotlin will work.
