### ISSUE TITLE
How do I write code?

### ISSUE THREAD

**Issue by rmtic** [square/retrofit#2519]
I use retrofit
Hello, a web service accepts this kind of requests below（PHP）:
{
    "bgcolor": "",
    "color_price": "0",
    "design": {
        "1": {
            "height": "557.86px",
           "width": "556.27px"
        }
    }
}
-----------------------------------------
But My Post:
{
    "bgcolor": "",
    "color_price": "0",
    "design":" {
        "1": {
            "height": "557.86px",
           "width": "556.27px"
        }
    }"
}
-----------------------------------------
I want to delete double quotes. It looks like this 
{ ......,
"design":{.......}
}
not looks like this
{ ......,
"design":"{.......}"
}

How do I write code?

**Comment by JakeWharton** [comment]
Retrofit does not do JSON conversion. Libraries like Gson are relied upon for that. If you are having problems with JSON conversion then you should either ask on StackOverflow with the appropriate tag for the library or ask on the library's mailing list, if it has one.

**Comment by rmtic** [comment]
I'm glad you can answer me! My question has been settled.
