### ISSUE TITLE
How to secure the reqest/response of an HTTPS call using Retrofit 1.9.0

### ISSUE THREAD

**Issue by shaikansaar** [square/retrofit#2520]
Hi,

I am using retrofit 1.9.0, and used Packet capture app to check if my https calls are secure.

Here's the usage of rest adapter:

RestAdapter restAdapter = new retrofit.RestAdapter.Builder()
                .setLogLevel(RestAdapter.LogLevel.FULL)
                .setEndpoint(MY_END_POINT)
                .setConverter(new GsonConverter(gson))
                .setErrorHandler(new MyRestErrorHandler())
                .build()

Unfortunately, I could see ALL data in both request and response as it is. It's not encrypted at all. Here's the screenshot for a request.

![cf5br](https://user-images.githubusercontent.com/4800397/31383005-8a042c98-adca-11e7-8340-28303e7a838e.jpg)

How do i make sure the calls are secure?

Thanks

**Comment by JakeWharton** [comment]
Retrofit is not an HTTP client and thus provides no facilities for this. You can use things like certificate pinning with OkHttp as your HTTP client to ensure that you are talking to the server that you expect. This will prevent tools doing packet capture from working.

**Comment by JakeWharton** [comment]
See https://github.com/square/okhttp/wiki/HTTPS

**Comment by ArabAgile** [comment]
I'm facing similar issue @JakeWharton, But I'm not using `OkHttp` at all.

Is it included by default when I'm using `retrofit`, and which version it uses? and how to change it if it's required?
