### ISSUE TITLE
Sending request parameters sometime getting null parameter value

### ISSUE THREAD

**Issue by asamadifateh** [square/retrofit#2522]
Why it is not sending my field parameter to the request received by the server?
It is not like that the parameter value is null but server is not receiving that parameter key. So, is this bug or what? or I have made some mistakes creating request body? It is not happening every time it requests to the server.

**Comment by JakeWharton** [comment]
Please provide a failing test case if you think there is a bug.

**Comment by JakeWharton** [comment]
There's almost no information here to go on to determine what's happening.

**Comment by asamadifateh** [comment]
Is it possible that i can have that request string once it created with parameters and ready connect with server? It prints log by logging addInterceptor but may be saving that full request could help me out. Its frequent so logging in console won't help me. I have to save that request.

Thanks for reply and your kindness

**Comment by JakeWharton** [comment]
Without a failing test case or reproduction sample we have no way of knowing what's going on here. If you can supply one of the two we can take a look. Otherwise there's no action to take here.
