### ISSUE TITLE
how to urlEncode when use @GET

### ISSUE THREAD

**Issue by shuifengYu** [square/retrofit#2523]
I have a GET request with a param "link=https://test.cn/index.html?key1=value1&key2=value2&key3=value3",so the full url is like: 
https://test.com?realkey1=realvalue1&realkey2=realvalue2&link=https://test.cn/index.html?key1=value1&key2=value2&key3=value3,so the server receive the value  of param "link"  is "https://test.cn/index.html?key1=value1",i try to urlEncode before pass the value,but when the request is delivered ,the encoded param "link" is auto decoded,how can i fix the problem?thank you

**Comment by JakeWharton** [comment]
`@Query` values are URL encoded automatically to spec with the behavior of the major browsers. If you are not seeing the results you expect, it's very likely that your server is parsing the URL incorrectly. If you think you found a bug in Retrofit, please provide a failing test case or standalone executable sample that demonstrates the problem.

**Comment by shuifengYu** [comment]
i have found why this happened,here is my code :

    private Request buildWithFormBody(Request request, FormBody originalBody) {
       HashMap<String, String> paramsMap = new HashMap<>();
        for (int i = 0; i < originalBody.size(); i++) {
            paramsMap.put(originalBody.encodedName(i), originalBody.encodedValue(i));
        }
        paramsMap = decorateParams(paramsMap);
        FormBody.Builder builder =new FormBody.Builder();
        for(Map.Entry<String,String> entry:paramsMap.entrySet()){
            builder.add(entry.getKey(),entry.getValue());
        }
        request = request.newBuilder().post(builder.build()).build();
        return request;
    }
    private Request buildParamsWithGET(Request request) {
        HttpUrl httpUrlurl = request.url();
        HashMap<String, String> paramsMap = new HashMap<>();
        Set<String> parameterNames = httpUrlurl.queryParameterNames();
        for (String key : parameterNames) {
            String value = httpUrlurl.queryParameter(key);
            if (TextUtils.isEmpty(value) || value.equalsIgnoreCase("null")) {
                value = "";
            }
            paramsMap.put(key, value);
        }
        paramsMap = decorateParams(paramsMap);
        Request.Builder builder = request.newBuilder();
        String url = Utils.getUrlPath(request.url().toString());
        url = url + "?" + Utils.getUrlParamsFromMap(paramsMap);
        builder.url(url);
        return builder.build();
    }

i added an interceptor to add common params for my request,the two functions are used for GET and POST method,in GET method  String value = httpUrlurl.queryParameter(key); the value returned was not encoded,so after i call the decorateParams(paramsMap) function,the params are all not encoded;also the likely problem is in the POST method,originalBody.encodedValue(i)return the encoded value,and after i call the function decorateParams(paramsMap) and post the new builder again, the params are encoded again,therefor whichever method i choose ,the server can not receive the correct params,is there any simply way to solve this problem? Thank you very much for your reply!

**Comment by shuifengYu** [comment]
in GET method, i can encode the params after i decorating them,but how can i deal with the repetition encode in POST method? so i think is it possible to auto encode the params after all interceptors and the params returned in both GET and POST method in interceptors are all original params?

**Comment by JakeWharton** [comment]
Please provide a failing test case if you believe there is a bug. There isn't the required information to guess what the problem you are facing is.
