### ISSUE TITLE
License information in individual POM files

### ISSUE THREAD

**Issue by jaredsburrows** [square/retrofit#2529]
I wrote this plugin generate a license information based off the POM files from the dependencies: https://github.com/jaredsburrows/gradle-license-plugin.

It fails to find some Square libraries such as Okio, Okhttp and Retrofit:
```
$ gradlew licenseDebugReport

> Task :licenseDebugReport
OkHttp Logging Interceptor dependency does not have a license.
Adapter: RxJava 2 dependency does not have a license.
Converter: Moshi dependency does not have a license.
Retrofit dependency does not have a license.
OkHttp dependency does not have a license.
moshi-adapters dependency does not have a license.
Moshi dependency does not have a license.
Okio dependency does not have a license.
Wrote HTML report to /<>/repo/android-gif-example/build/reports/licenses/licenseDebugReport.html.
Wrote JSON report to /<>/repo/android-gif-example/build/reports/licenses/licenseDebugReport.json.


BUILD SUCCESSFUL in 7s
```

It turns out the "parent" POM files have the license information and child POM files of the project that are the actual artifacts that users download do not have the information. See below.

Parent POM: 
 - https://repo1.maven.org/maven2/com/squareup/retrofit2/parent/2.3.0/parent-2.3.0.pom
 - https://github.com/square/retrofit/blob/master/pom.xml

Individual POM:
 - https://repo1.maven.org/maven2/com/squareup/retrofit2/retrofit/2.3.0/retrofit-2.3.0.pom
 - https://github.com/square/retrofit/blob/master/retrofit/pom.xml 

Would you all please accept a PR to include the correct license information in the actual POM files of the artifacts that clients consume that is in the parent POM?

**Comment by JakeWharton** [comment]
No. Your plugin should traverse parent poms to find necessary info. This is the same issue the Play Services OSS plugin has. See: https://github.com/square/okhttp/pull/3591.

**Comment by jaredsburrows** [comment]
@JakeWharton Thanks for the explanation. I added support for traversing the parent dependencies in my plugin here: https://github.com/jaredsburrows/gradle-license-plugin/pull/20.
