### ISSUE TITLE
Kotlin support using kotlin.serialization

### ISSUE THREAD

**Issue by PaulWoitaschek** [square/retrofit#2530]
With the currently released [kotlinx.serialization](https://github.com/Kotlin/kotlinx.serialization) it might be possible to use that as an adapter for serializing kotlin classes without having to maintain the serialization work yourself.

Is there anything that speaks against this idea?

**Comment by JakeWharton** [comment]
It's not stable.

**Comment by family93** [comment]
commit

**Comment by JakeWharton** [comment]
Until it's a 1.0 we can't look at even potentially adding it. Feel free to create a standalone converter and add it to the wiki for now.
