### ISSUE TITLE
@Path after the question mark

### ISSUE THREAD

**Issue by D330** [square/retrofit#2535]
Hi, perfect library!

I make an application that uses the API of one browser game: Retrofit for requests, Jsoup for parsing. This is a really good idea but I ran into a problem. All game requests have this type of link:

    /user/id/501/?wicket:interface=:10:addFriendLink::ILinkListener::

I wrote so

    @GET("/user/id/{userId}/?wicket:interface=:{session}:addFriendLink::ILinkListener::")
    Call<Document> addFriend(@Path("userId") long userId, @Path("session") int session);

This is very good, but @Path does not work after the question mark. @Query is not suitable in this case because after the question mark there are no key/value pairs: it non-standard link. 

I do not want to write link collectors, it does not look professionally. Also I do not want to use @Url

What can be done? Thank you!

**Comment by swankjesse** [comment]
You’ll want to use a `@Query("wicket:interface")` parameter. When you do, you’ll need to add the `:` prefix and `:addFriendLink::ILinkListener::` suffix manually.

**Comment by D330** [comment]
@swankjesse, no.. it's not very pretty. I will have to transmit this manually, but I would like the links to be collected in one place. Is there really no other way? and why is @Path blocked after the question mark? because of this little thing my code will be awful and unsupported

**Comment by D330** [comment]
@swankjesse, please open the issue again. I think it will be interesting to many people. maybe I can make changes to the source code? or maybe it worked in the version below? for example, in the FastAndroidNetworking library, the addPathParameter method works everywhere.

**Comment by JakeWharton** [comment]
Because after the question mark it is no longer the path component it is
there query component

**Comment by D330** [comment]
@JakeWharton, hello, Jake! Yes, I understand this, but in my case, I need some @QueryPath. I can write such an annotation. can any "hack" be possible?

**Comment by D330** [comment]
@JakeWharton, Eureka! Can I pass a question mark as a path parameter? or can I replace the question mark with some other symbol, for example "¿", and in some place intercept this sign and replace it with "?"

**Comment by D330** [comment]
Yes Yes!! I can write like this:

    @GET("/user/id/{userId}/¿wicket:interface=:{session}:addFriendLink::ILinkListener::")
Call<Document> addFriend(@Path("userId") long userId, @Path("session") int session);

and then, somewhere replace "¿" with "?". if this is possible, then where can I intercept the url and change it?

**Comment by D330** [comment]
I'm away from the computer. but I guess I can do it. I do not know whether there is a method `setUrl`:

    private static class UrlInterceptor implements Interceptor {
        @Override
        public Response intercept(Chain chain) throws IOException {
            Request request = chain.request();
            request.setUrl(request.urlString().replace("¿", "\\?"));
            Response response = chain.proceed(request);
            return response;
        }
    }
