### ISSUE TITLE
why Rxjava adapter uses an old Rxjava version of 1.3.0?

### ISSUE THREAD

**Issue by shijia109** [square/retrofit#2536]
why not use the newest version of Rxjava of 2.1.6?

**Comment by digitalbuddha** [comment]
There are 2 rxjava adapters. One for rxjava1 and one for Rxjava2.  Some want to still be using Rxjava1 is why that one still exists. https://github.com/square/retrofit/tree/master/retrofit-adapters

**Comment by JakeWharton** [comment]
What Mike said!

**Comment by shijia109** [comment]
I am using gradle : compile 'com.squareup.retrofit2:adapter-rxjava:2.3.0' to depend on the lib, so I got a 1.3.0 Rxjava version, what shoud I do to get a Rxjava2 version by using gradle?

**Comment by NightlyNexus** [comment]
`com.squareup.retrofit2:adapter-rxjava2:2.3.0`

[README](https://github.com/square/retrofit/tree/master/retrofit-adapters/rxjava2)
