### ISSUE TITLE
convert int values to booleans

### ISSUE THREAD

**Issue by nailbrother** [square/retrofit#2537]
Retrofil cannot convert int values to booleans correctly, I'm receiving JSON that looks like this:

{ "verify": "1", "success": "1" }

My class member getVerify() returns always false even if value is 1

**Comment by JakeWharton** [comment]
Retrofit doesn't deserialize JSON. Look into configuring your serialization
library instead (like Gson).

**Comment by nailbrother** [comment]
Ah, I see.
Thanks bro.
