### ISSUE TITLE
Uploading large images using retrofit 2

### ISSUE THREAD

**Issue by a3adel** [square/retrofit#2538]
Iam using Retrofit 2.3.0 to upload images to a .Net framework server, 
the uploading of images i working fine .. ubt when i try to upload >5MB images it gives me an error
when i logged the request it doesn't read the full file and gives EOF exception .. and i do have to compress the image with about 50% quality which is not very good
iam using `MultiPart` to upload and this is my code snippet 

        RequestBody requestFile =
                        RequestBody.create(MediaType.parse("image/jpeg"), file);
                MultipartBody.Part body =
                        MultipartBody.Part.createFormData("image", file.getName(), requestFile);
    
    // add another part within the multipart request
                RequestBody fullName =
                        RequestBody.create(
                                MediaType.parse("multipart/form-data"), image.getDescription());
and this is the okHttp log 

                     --------- beginning of main
    10-30 14:25:45.330 11236-11402/com.project.peoject D/OkHttp: �Dwm�1l�n�D�RXZX�1[)$M��l�`��7Q���n�ӟ̊e�L،����=�k���*a�~�g��=�U�ɨ@<�x��/���>� ���R��@��z;c�?��Zʖ7��ۮ�0�*r����#ך�����3�J��F{���v�	��Kk̌�$||
                                                                   
                                                                   read: unexpected EOF!

**Comment by JakeWharton** [comment]
The behavior you are seeing comes from OkHttp, not Retrofit. But even so, I don't see how the client could be at fault. I've used OkHttp to send gigabytes of data, so I expect the network is breaking, the server is rejecting the request mid-stream, or someone is changing the file out underneath the client.

If you can describe the problem as a failing test case or executable sample we can take a look on the OkHttp issue tracker.

**Comment by Bhoomika06** [comment]
Hello Folk, I am facing the same problem while uploading video file (Size: around 6 MB) along with Image file. When I tried to sent only Video, Still got Same Error. If You can suggest anything to me; Please Give Suggestions.

**Comment by ritunagpal** [comment]
Can we compress file before sending to server ?

**Comment by ritunagpal** [comment]
Any update ? @JakeWharton

**Comment by sachinletsgo** [comment]
@JakeWharton .. Less than 6Mb is working fine. But not able to upload more than 6Mb.
Please help

**Comment by vasiledoe** [comment]
Check out timeout limit, because it can finish earlier than file is loaded!

`  OkHttpClient okHttpClient = new OkHttpClient.Builder()
                .connectTimeout(30, TimeUnit.SECONDS)
                .addInterceptor(httpLoggingInterceptor)
                .addInterceptor(new DecriptInterceptor())
                .build();
`

**Comment by parasjain1** [comment]
Was this issue somehow resolved? Even I'm can't upload a collective media size of more than 6 MB. Backend is hosted on a hostgator VPS and written in php.

**Comment by tarunmehta-quovantis** [comment]
Has any one got the solution . i am facing the same problem . even i have increased my time duration limit.
httpClient.readTimeout(240, TimeUnit.SECONDS);
        httpClient.connectTimeout(240, TimeUnit.SECONDS);
        httpClient.writeTimeout(240, TimeUnit.SECONDS);

**Comment by sachinletsgo** [comment]
Yes, There is no issue in the library. My issue is resolved.
Its Server side issue.
You Might check following point to resolve it:-
1. Check how lengthy file can be uploaded to the server.
2. Check server connection time out from the server point of view. 
3. Make sure you have to change the file size on Apache server also. (In my case php filesize of apache server was 5MB)

**Comment by habahbehbassam** [comment]
This case happens when sending larg attachment and backend has fix max size for attachment usually 5 MB,
Should send the attachment via **Chunks** technique, and each chunk should have max size.

Ex -> you have a file with size 20 MB  and backend max size 5 MB:
1. should separate this file to 4 chunks (20/5) 
2. send chunks 
3. after sent those chunks successfully handle success and return callbacks

**Comment by shahidgeek** [comment]
Solution : 
https://github.com/square/retrofit/issues/540#issuecomment-46934042

Happy 👍 💯 🥇
