### ISSUE TITLE
How to send array params with Retrofit when the array's key name not sure

### ISSUE THREAD

**Issue by fenglintianxia6** [square/retrofit#2540]
I am not able to access to stackOverFlow,3Q

I use the server's response as key to request new data where the value is array. So how can I do it.
I have tried @QueryMap Map<String[] List<String>> paramMap   @QueryMap Map<String,List<String>> paramsMap  @QueryMap Map<String,String[]> paramsMap.  They all don't work. plz help me.

**Comment by JakeWharton** [comment]
It's not clear what you're trying to do. What is the exact data that you have and what is the desired URL you want?

**Comment by exp2Tapavicki** [comment]
I think what he meant is example like this.

He probably have dynamic filters or something similar like that. 
Class Filter will look something like this.

```
class Filter {
    String firstProperty;
    String secondProperty;
    Operation operation;
}
enum Operation {
    GreaterThen;
    EqualTo;
    LessThen;
}

```
Now when he forms request he will have List<Filter> available and he needs to map it somehow as array. For example let have object name, object property and index in List<Filter> as part of key. I know this is not best example but it would be look like this. 

```
@Get
url?filter1firstProperty=name&filter1secondProperty=username&filter1operation=EqualTo
    &filter2firstProperty=first_price&filter2secondProperty=second_price&filter2operation=GreaterThen
```

Question is probably how to properly handle Array of some Object as @QueryMap parameters? How to support to fit for different languages in backend?

I don't think my quick and dirty solution above is good. Also I am not aware of any standard for this situation with different programming languages and frameworks even I have wrote rest api in more languages and framework I didn't find any standard for this. It is always language or framework specific. It would be nice that someone set some standard for Get request and query parameters. This is a lot easier if request is @Post and we can just put in @Body HashMap<String, Filter> body or I don't know if this is supported @Body Filter[].
