### ISSUE TITLE
java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 79 column 20 path $.seatlayout[2].u_layout

### ISSUE THREAD

**Issue by PeterDasondhi** [square/retrofit#2541]
java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 79 column 20 path $.seatlayout[2].u_layout

Hello Friends,
  **I am new user in Retrofit 2.0** when i send a request to server in POST method, I am getting this issue.
means if in a response i need to get Array and behalf-of that i am getting null value(" ") or empty string.
Please let me know how to solved this Issue

**Comment by JakeWharton** [comment]
This exception comes from Gson and not Retrofit. Retrofit isn't involved in serialization except handing off to Gson
