### ISSUE TITLE
@Path for @GET request not working

### ISSUE THREAD

**Issue by rpugase** [square/retrofit#2542]
"minSdkVersion" is api 19. In api 19 this not working, but in the api 20-26 is working. 
I have such `@GET` request.
```java
@Headers("Cache-Control: no-cache")
@GET("notifications/from/{atom_date}")
Observable<List<Notification>> getNotifications(@Path("atom_date") String atomDate);
```
And realy request sending (only api 19):
`notifications/from/%7Batom_date%7D`

Retrofit 2.3.0

**Comment by caseykulm** [comment]
Can you write a reproducible instrumented test for this?
