### ISSUE TITLE
IllegalStateException when converting the response to User object defined

### ISSUE THREAD

**Issue by DivyasriBS** [square/retrofit#2543]
I m trying to do Rx java 2 with retrofit 2 and MVP
Using foll dependencies
 compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
    compile 'io.reactivex.rxjava2:rxjava:2.1.0'
    compile 'com.squareup.retrofit2:retrofit:2.3.0'
    compile 'com.squareup.retrofit2:converter-gson:2.3.0'
    compile 'com.squareup.retrofit2:adapter-rxjava2:2.3.0'
    compile 'com.jakewharton.retrofit:retrofit2-rxjava2-adapter:1.0.0'

My Retrofit code looks like
 public RetrofitRequest(String baseUrl){
        okHttpClient = buildClient();
        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(baseUrl)
                .addConverterFactory(GsonConverterFactory.create())
                .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
                .client(okHttpClient)
                .build();

        netApi = retrofit.create(NetworkAPI.class);
    }
 My RX code
observable.compose(SchedulerProvider.applySchedulers()).
                subscribe(new Observer<OAuthTokenVO>() {
                    @Override
                    public void onSubscribe(Disposable d) {

                    }

                    @Override
                    public void onNext(OAuthTokenVO oAuthTokenVO) {
                        Log.i("ON NEXT", oAuthTokenVO.toString());
                    }

                    @Override
                    public void onError(Throwable e) {
                        Log.e("ERR", e.getMessage());
                        e.printStackTrace();
                    }

                    @Override
                    public void onComplete() {

                    }
                });
Error on Response
I/LogUtils-->: response code:200
11-03 10:38:26.655 13262-13318/com.sakha.o3 I/LogUtils-->: Content{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbGxvd2VkU2VydmljZXMiOltdLCJ1c2VyX25hbWUiOiIxMjM0NTY3ODkwIiwic2NvcGUiOlsid3JpdGUiXSwiYXV0aEdlblRpbWUiOjE1MDk2ODU3MDgyNDQsImV4cCI6MTUwOTcyODkwOCwiYXV0aG9yaXRpZXMiOlsiUk9MRV9QUk9EVUNUX0FETUlOIl0sImp0aSI6IjQzMWM5ZjJkLTA1ZWYtNGVmOC05MTI4LWRkNjRlMDY3ZjhkOCIsImNsaWVudF9pZCI6ImNsaWVudElkUGFzc3dvcmQifQ.-klR8KIGscmKODCK61tkDjUB_sORxpSIoqhF0K9rK9Y","token_type":"bearer","refresh_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbGxvd2VkU2VydmljZXMiOltdLCJ1c2VyX25hbWUiOiIxMjM0NTY3ODkwIiwic2NvcGUiOlsid3JpdGUiXSwiYXRpIjoiNDMxYzlmMmQtMDVlZi00ZWY4LTkxMjgtZGQ2NGUwNjdmOGQ4IiwiYXV0aEdlblRpbWUiOjE1MDk2ODU3MDgyNDQsImV4cCI6MTUxMjI3NzcwOCwiYXV0aG9yaXRpZXMiOlsiUk9MRV9QUk9EVUNUX0FETUlOIl0sImp0aSI6ImZkN2RjMDU3LWZhYWQtNDY5Yi05N2I3LTA1YTdlZjFiMmI1NCIsImNsaWVudF9pZCI6ImNsaWVudElkUGFzc3dvcmQifQ.wwkFfRAYs9d3Y_Ebsb0Wvh6hCE39WBmIOxxdO03Q1uw","expires_in":43199,"scope":"write","allowedServices":[],"authGenTime":1509685708244,"jti":"431c9f2d-05ef-4ef8-9128-dd64e067f8d8"}
11-03 10:38:26.658 13262-13262/com.sakha.o3 E/ERR: closed

11-03 10:38:26.658 13262-13262/com.sakha.o3 W/System.err: java.lang.IllegalStateException: closed
11-03 10:38:26.659 13262-13262/com.sakha.o3 W/System.err:     at okio.RealBufferedSource.read(RealBufferedSource.java:43)
11-03 10:38:26.659 13262-13262/com.sakha.o3 W/System.err:     at okio.ForwardingSource.read(ForwardingSource.java:35)
11-03 10:38:26.659 13262-13262/com.sakha.o3 W/System.err:     at retrofit2.OkHttpCall$ExceptionCatchingRequestBody$1.read(OkHttpCall.java:291)
11-03 10:38:26.659 13262-13262/com.sakha.o3 W/System.err:     at okio.RealBufferedSource.request(RealBufferedSource.java:67)
11-03 10:38:26.659 13262-13262/com.sakha.o3 W/System.err:     at okio.RealBufferedSource.rangeEquals(RealBufferedSource.java:408)
11-03 10:38:26.659 13262-13262/com.sakha.o3 W/System.err:     at okio.RealBufferedSource.rangeEquals(RealBufferedSource.java:392)
11-03 10:38:26.660 13262-13262/com.sakha.o3 W/System.err:     at okhttp3.internal.Util.bomAwareCharset(Util.java:431)
11-03 10:38:26.660 13262-13262/com.sakha.o3 W/System.err:     at okhttp3.ResponseBody$BomAwareReader.read(ResponseBody.java:249)
11-03 10:38:26.660 13262-13262/com.sakha.o3 W/System.err:     at com.google.gson.stream.JsonReader.fillBuffer(JsonReader.java:1287)
11-03 10:38:26.660 13262-13262/com.sakha.o3 W/System.err:     at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1325)
11-03 10:38:26.660 13262-13262/com.sakha.o3 W/System.err:     at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:549)
11-03 10:38:26.660 13262-13262/com.sakha.o3 W/System.err:     at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
11-03 10:38:26.660 13262-13262/com.sakha.o3 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:205)
11-03 10:38:26.660 13262-13262/com.sakha.o3 W/System.err:     at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:37)
11-03 10:38:26.661 13262-13262/com.sakha.o3 W/System.err:     at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:25)
11-03 10:38:26.661 13262-13262/com.sakha.o3 W/System.err:     at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:119)
11-03 10:38:26.661 13262-13262/com.sakha.o3 W/System.err:     at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:218)
11-03 10:38:26.661 13262-13262/com.sakha.o3 W/System.err:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
11-03 10:38:26.661 13262-13262/com.sakha.o3 W/System.err:     at com.jakewharton.retrofit2.adapter.rxjava2.CallObservable.subscribeActual(CallObservable.java:41)
11-03 10:38:26.661 13262-13262/com.sakha.o3 W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10842)
11-03 10:38:26.661 13262-13262/com.sakha.o3 W/System.err:     at com.jakewharton.retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
11-03 10:38:26.661 13262-13262/com.sakha.o3 W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10842)
11-03 10:38:26.662 13262-13262/com.sakha.o3 W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
11-03 10:38:26.662 13262-13262/com.sakha.o3 W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
11-03 10:38:26.662 13262-13262/com.sakha.o3 W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
11-03 10:38:26.662 13262-13262/com.sakha.o3 W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
11-03 10:38:26.662 13262-13262/com.sakha.o3 W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-03 10:38:26.662 13262-13262/com.sakha.o3 W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
11-03 10:38:26.662 13262-13262/com.sakha.o3 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
11-03 10:38:26.662 13262-13262/com.sakha.o3 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
11-03 10:38:26.662 13262-13262/com.sakha.o3 W/System.err:     at java.lang.Thread.run(Thread.java:761)

**Comment by caseykulm** [comment]
Btw `com.jakewharton.retrofit:retrofit2-rxjava2-adapter` is deprecated in favor of the official https://github.com/square/retrofit/tree/master/retrofit-adapters/rxjava2

**Comment by JakeWharton** [comment]
My guess is that you have an interceptor that's reading the body. Please provide an executable test case or sample that demonstrates the problem.
