### ISSUE TITLE
Feature Request: Ability to provide iterable parameter handler

### ISSUE THREAD

**Issue by Kindrat** [square/retrofit#2545]
According to current 2.3.0 retrofit2.ServiceMethod - iterables in query params are processed one by one and passed as repeatable key=value sequence to URI.
In my case API I'm working with requires passing collection of query param values as it's defined in spec - repeated key-values - for some keys and concatenating  with comma for other:

`http://api.wolframalpha.com/v2/query?appid=DEMO&input=france&format=image,imagemap&podtitle=Weather+station+information&podtitle=Latest+recorded+weather*`

- format=image,imagemap is using concatenation
- podtitle is repeated sequence

Will it be possible to extend parseParameter method in ServiceMethod to delegate conversion of entire collections, not just single elements, to user-defined converters?

**Comment by Kindrat** [comment]
What I'm doing currently - added new field `boolean rawProcessing()` to `Query` annotation and added additional check in iterable branch in `parseParameterAnnotation`:

<pre>if (Iterable.class.isAssignableFrom(rawParameterType) && !query.rawProcessing()) {
                    if (!(type instanceof ParameterizedType)) {
                        throw parameterError(p, rawParameterType.getSimpleName()
                                + " must include generic type (e.g., "
                                + rawParameterType.getSimpleName()
                                + "<String>)");
                    }
                    ParameterizedType parameterizedType = (ParameterizedType) type;
                    Type iterableType = Utils.getParameterUpperBound(0, parameterizedType);
                    Converter<?, String> converter = retrofit.stringConverter(iterableType, annotations);
                    return new ParameterHandler.Query<>(name, converter, encoded).iterable();
                } else if (rawParameterType.isArray() && !query.rawProcessing()) {
                    Class<?> arrayComponentType = boxIfPrimitive(rawParameterType.getComponentType());
                    Converter<?, String> converter = retrofit.stringConverter(arrayComponentType, annotations);
                    return new ParameterHandler.Query<>(name, converter, encoded).array();
                } else {
                    Converter<?, String> converter = retrofit.stringConverter(type, annotations);
                    return new ParameterHandler.Query<>(name, converter, encoded);
                }</pre>

so when flag is set to true - whole value is passed to converter.

**Comment by Kindrat** [comment]
anyone?

**Comment by JakeWharton** [comment]
We're tracking this as #626. Its an advanced use-case that doesn't come up all that often and it requires a significant amount of surface API to be exposed.

The comma concatenation can be done currently using a custom string converter.
