### ISSUE TITLE
addQueryParameter doesn't work in PHP server

### ISSUE THREAD

**Issue by yangtuhua** [square/retrofit#2547]
HttpUrl.Builder requestTypeBuilder = oldRequest.url()
                .newBuilder()
                .scheme(oldRequest.url().scheme())
                .host(oldRequest.url().host())
                .addQueryParameter("client","android")

I add the public parameter by interceptor ,but it doesn't work in PHP server when it works well in a JAVA Sever.

Is there something wrong in my code?

**Comment by JakeWharton** [comment]
Interceptors are from OkHttp, not Retrofit. If you think there's a problem, a failing test case is the best way to get it resolved so we can see exactly what you're doing and exactly what format you expect the request to be in. There's currently no information to diagnose what is happening.
