### ISSUE TITLE
For real, allow to configure retrofit to allow API interfaces to extend interfaces

### ISSUE THREAD

**Issue by co5dt** [square/retrofit#2548]
Hi there.
Great lib, wouldn't know how to live on without it. Solves all usecases in my apps, but one is still unmet. Just pointing this out so I don't get asked why I even use retrofit. :)

But issue remains: #504 !

This is needed, really. Example:
`TokenHandler jwtHandler = new JWTTokenHandler(context);
        Api api = ApiFactory(jwtHandler).createService(clazz);

        Observable
                .from(entities)
                .flatMap(api::save)
                .doOnNext(entity -> entity.setSynced(true))
                .toList()
                .doOnNext(/*save to db, etc*/)
                .subscribe(entities -> {}, Throwable::printStackTrace);`

Here and there I read JW favors composition over inheritance and that's why we must write this 13 times, given we have 13 endpoints for 13 entities in 13 service interfaces. 

Now I could have a single interface for post requests with 13 methods, each one for a different entity. 

`
 public interface UploadApi {

    @POST("users")
    Observable<User> save(User user);

    @POST("user-groups")
    Observable<UserGroup> save(UserGroup userGroup);

    @POST("user-photos")
    Observable<UserPhoto> save(UserPhoto userPhoto);

    @POST("user-text-notes")
    Observable<UserTextNote> save(UserTextNote userTextNote);

    @POST("user-actions")
    Observable<UserAction> save(UserAction userAction);

    @POST("user-activities")
    Observable<UserActivity> save(UserActivity userActivity);

    @POST("pois")
    Observable<Poi> save(Poi poi);

    @POST("poi-collections")
    Observable<PoiCollection> save(PoiCollection poi);

    // and so on ...
 }
`
I have seen some projects by now and all of them specify their service interfaces around entites (or dto's or whatya wanna call 'em) like so:

`public interface UserApi {

    @GET("users")
    Observable<List<User>> get();

    @GET("users/{id}")
    Observable<User> get(@Path("id") long id);

    @GET("users/{login}")
    Observable<User> get(@Path("login") String login);

    @POST("users")
    Observable<User> save(User user);

    @POST("users")
    Observable<User> save(List<User> user);

    @DELETE("users")
    Observable<User> delete(List<User> user);

    @DELETE("users/{id}")
    Observable<User> delete(@Path("id") long user);

    @GET("account")
    Observable<User> getCurrentUser();
}`

I have read somewhere that a library should not be in the way of things but help you to do something more easily. Please reconsider. 

Anyway, all the best and thanks for this great lib.

**Comment by JakeWharton** [comment]
Dupe #504. Add your use case there.

**Comment by co5dt** [comment]
#504 closed
