### ISSUE TITLE
Response headers does not contain "content-encoding"

### ISSUE THREAD

**Issue by MVLangkilde** [square/retrofit#2553]
Hi,
First of all, thanks for an awesome library. 

I have an issue, I hope you can help me with. I can't seem to access the response header "content-encoding", from the response object in onResponse for a network request:

```
call.enqueue(object :Callback<SomeClass> {

                override fun onResponse(call: Call<SomeClass>?, response: Response<SomeClass>?) {
// response.headers().get("Content-Encoding") = null
                }

                override fun onFailure(call: Call<SomeClass>?, t: Throwable?) {
                    if (t != null) {
                        callback.onFail(t, "")
                    }
                }
            })
```

is the header filtered out by default, through either retrofit or okhttp?

I tested the network request through Postman, which returned: Content-Encoding: gzip

Thanks in advance

**Comment by JakeWharton** [comment]
OkHttp removes the header when it automatically un-gzips the body. You can confirm whether the response was gzip'd or not by checking the header on `raw().networkResponse()`. You will not be able to access the gzip'd body, however.
