### ISSUE TITLE
Okhhtp is caching old request object

### ISSUE THREAD

**Issue by shabarishbk** [square/retrofit#2555]
What kind of issue is this?

 - [ ] I have a implementation where i have one "retry interceptor" which retries for HTTP 503 and and  " authenticator" for http 401, in my observation if "retry interceptor" is invoked with request R1 , and when it retries, it encounters a http 401 , then "authenticator" is kicked in, it calls my API and gets the token and makes the request R2 (R1 with new token), this call is again encountered with 503 when that is retried it is re-tried with R1(old token) which again encounters 401, this is happening till 503 retry counts are exhausted.

**Comment by JakeWharton** [comment]
File a bug on [OkHttp](https://github.com/square/okhttp)? Retrofit has no control over this.
