### ISSUE TITLE
Strange way to get the root of a URL

### ISSUE THREAD

**Issue by Koire** [square/retrofit#2557]
I don't know if this is on purpose or not, but it seems the only way to get the root of your URL is to use a space in your get, i.e.  @Get(" ")
I have a url:
`Retrofit.Builder()
                .baseUrl(" http://www.myapi.com/v1/")
                .client(client)
                .addConverterFactory(MoshiConverterFactory.create())
                .build()`
now I want to go a get to that URL:
`    @GET("")
    fun getRoot(): Call<ApiGetRoot> `

Error: Missing @URL or @Path parameter
` @GET("/")
    fun getRoot(): Call<ApiGetRoot>` 
now it tries to get from "http://www.myurl.com/

` @GET(" ")
    fun getRoot(): Call<ApiGetRoot>` 
this one works

**Comment by JakeWharton** [comment]
The right way to do this would actually be @GET(".") which is a relative
link to the current page.

**Comment by JakeWharton** [comment]
I'm not sure why space works, but that code is inside OkHttp which does the relative URL resolution.
