### ISSUE TITLE
Retrofit 2.2.0 / OkHttp 3.6.0: Query url encoding failed

### ISSUE THREAD

**Issue by antechrestos** [square/retrofit#2558]
Hello,

I seem to resurect an old bug about query parameters. 

My aim is to pass a json object as a string query parameter.

```kotlin
@GET("/somewhere/over/the/rainbow")
    fun getResults(
            @Query("filter") filter: String? = null)
            : Call<List<ObjectResponse>>
```

Calling it like this

```kotlin
val result = client.getResults(filter = """{"metadata"{"source":{"eq":"something:model@instance"}}}""")
                .execute().body()
```

When I run it either with logging interceptor or with a mock server, I get the following call

```
http://my-service/somewhere/over/the/rainbow?filter={%22metadata%22{%22source%22:{%22eq%22:%22something:model@instance%22}}}
```

If we take a look at what is returned from the python lib (or any library for url encoding)

```python
>>> import urllib
>>> urllib.urlencode(dict(filter='{"metadata"{"source":{"eq":"something:model@instance"}}}'))
'filter=%7B%22metadata%22%7B%22source%22%3A%7B%22eq%22%3A%something%model%instance%22%7D%7D%7D'
```

As far as I can see, it seems that caracters such as `{`, `@`, `:`are not encoded.

I currently execute this code with retrofit `2.2.0` with okhttp `3.6.0`.

Thank you by advance

**Comment by JakeWharton** [comment]
Per http://tinyurl.com/url-escaping lines 30, 34, and 40, all major browsers do not encode any of those characters and thus OkHttp does not either.
