### ISSUE TITLE
Allow marker interfaces

### ISSUE THREAD

**Issue by mozinrat** [square/retrofit#2559]
What kind of issue is this?
 - [x] Feature Request
Please allow support for marker interface, is useful for grouping and applying interceptors and provides validation at compile time only.
e.g `public ConnectorFactory(Class<T extends ServiceCategoryA> clazz) {
    aClass = clazz;
  }

  public T create(PropertyResolver env) {
    String baseUrl = env.getProperty("baseUrl");
    OkHttpClient client =
        new OkHttpClient.Builder().addInterceptor(new OkHttpOauthInterceptor(env)).build();
    Retrofit retrofit =
        new Retrofit.Builder()
            .baseUrl(baseUrl)
            .client(client)
            .addConverterFactory(JacksonConverterFactory.create())
            .build();
    return retrofit.create(aClass);
  }`

Now using the marker interface `ServiceCategoryA` I can find on compiletime if this factory can create this service or not

**Comment by NightlyNexus** [comment]
A marker interface on what exactly? Can you give an example of what you want to achieve?

Are you trying to make a custom Converter.Factory? These factories don't know anything about the type of the service interface. It's possible annotations on your service methods will be what you want.
