### ISSUE TITLE
How many enqueue process works in retrofit

### ISSUE THREAD

**Issue by vishal901** [square/retrofit#2560]
- how many enqueue process in retrofit, I'm working on a project in which i'm using retrofit. i just know how many process works. i tried to google searched or retrofit docs but didn't found anything useful.

**Comment by JakeWharton** [comment]
Retrofit's enqueue delegates to OkHttp's enqueue and doesn't know anything about how it's implemented. There's some information about how OkHttp's enqueue works on [its wiki](https://github.com/square/okhttp/wiki/Calls#dispatch) and you can customize how it executes async requests using [its `Dispatcher` type](http://square.github.io/okhttp/3.x/okhttp/okhttp3/Dispatcher.html).
