### ISSUE TITLE
OkHttp receive http code 200,but data not receive 

### ISSUE THREAD

**Issue by tigerface** [square/retrofit#2565]
hi,
I find a situation when set net download rate in 5kb/s. retrofit can receive 200 http code, but not receive data. How can I deal with this ?
please see the net request "http://howto.yilan.tv/video/head".

thank you.

**11-20 16:11:25.449 D/OkHttp  (16557): --> GET http://howto.yilan.tv/video/head?app=howto_a&sid=xiaomimarket&model=HM%202A&brand=Xiaomi&guuid=650750d37ae55f6c9cb746c4064e6cb7&udid=689e0693d35dd15dd15dd15db428ee2a246c29b7a81c959e5fbd2d396bd08bae&ver=1.1.0.11&uuid=e5614eda-4708-414a-bce3-2506d32c1e9f&timestamp=1511165485468 http/1.1**

11-20 16:11:25.449 D/OkHttp  (16557): Connection: close

11-20 16:11:25.449 D/OkHttp  (16557): --> END GET

11-20 16:11:25.489 I/XiaomiFirewall( 1474): firewall pkgName:tv.yilan.howto.app, result:0x0

11-20 16:11:25.779 D/ConnectivityService(  838): getActiveNetworkInfo 

11-20 16:11:25.779 D/ConnectivityService(  838): getNetworkInfo:networkType 1 is connected,apn is "gjb_pc"

11-20 16:11:25.789 D/ConnectivityService(  838): getActiveNetworkInfo 

11-20 16:11:25.789 D/OkHttp  (16557): --> GET http://data.yilan.tv/event/heartbeat?app=howto_a&beatid=3&interval=30&loadid=c1e4b91c-1030-4531-9f11-a99ff8249403&m=c038f3387b5f576c4b9f9554fcd3f669&mac=FC64BA8D5AF3&model=HM%202A&nt=1&rver=2&sid=xiaomimarket&sn=1511165485798&telecom=0&udid=689e0693d35dd15dd15dd15db428ee2a246c29b7a81c959e5fbd2d396bd08bae&uid=0&ver=1.1.0.11&uuid=c1432ee1-63e2-4c53-a49d-c8739f5ba860&timestamp=1511165485804 http/1.1

11-20 16:11:25.789 D/OkHttp  (16557): Cache-Control: 

11-20 16:11:25.789 D/OkHttp  (16557): Connection: close

11-20 16:11:25.789 D/OkHttp  (16557): --> END GET

11-20 16:11:25.789 D/ConnectivityService(  838): getNetworkInfo:networkType 1 is connected,apn is "gjb_pc"

**11-20 16:11:25.909 D/OkHttp  (16557): <-- 200 OK http://howto.yilan.tv/video/head?app=howto_a&sid=xiaomimarket&model=HM%202A&brand=Xiaomi&guuid=650750d37ae55f6c9cb746c4064e6cb7&udid=689e0693d35dd15dd15dd15db428ee2a246c29b7a81c959e5fbd2d396bd08bae&ver=1.1.0.11&uuid=e5614eda-4708-414a-bce3-2506d32c1e9f&timestamp=1511165485468 (450ms)**

11-20 16:11:25.909 D/OkHttp  (16557): Server: nginx/1.13.0

11-20 16:11:25.909 D/OkHttp  (16557): Date: Mon, 20 Nov 2017 08:11:26 GMT

11-20 16:11:25.909 D/OkHttp  (16557): Content-Type: text/html; charset=UTF-8

11-20 16:11:25.909 D/OkHttp  (16557): Transfer-Encoding: chunked

11-20 16:11:25.909 D/OkHttp  (16557): Connection: close

11-20 16:11:25.909 D/OkHttp  (16557): X-Powered-By: PHP/5.6.30

11-20 16:11:25.909 D/OkHttp  (16557): Access-Control-Allow-Origin: *

11-20 16:11:25.909 D/OkHttp  (16557): iscache: 0

11-20 16:11:26.349 D/WifiStateMachine(  838): handleMessage: E msg.what=131155

11-20 16:11:26.349 D/WifiStateMachine(  838): processMsg: ConnectedState

11-20 16:11:26.349 D/WifiStateMachine(  838): processMsg: L2ConnectedState

11-20 16:11:26.349 D/WifiNative-wlan0(  838): doString: SIGNAL_POLL

11-20 16:11:26.349 D/WifiStateMachine(  838): handleMessage: X

11-20 16:11:26.369 I/System.out(16557): [CDS]read byte is 0

11-20 16:11:26.509 I/System.out(16557): [CDS]read byte is 0

11-20 16:11:27.029 D/OkHttp  (16557): <-- 200 OK http://data.yilan.tv/event/heartbeat?app=howto_a&beatid=3&interval=30&loadid=c1e4b91c-1030-4531-9f11-a99ff8249403&m=c038f3387b5f576c4b9f9554fcd3f669&mac=FC64BA8D5AF3&model=HM%202A&nt=1&rver=2&sid=xiaomimarket&sn=1511165485798&telecom=0&udid=689e0693d35dd15dd15dd15db428ee2a246c29b7a81c959e5fbd2d396bd08bae&uid=0&ver=1.1.0.11&uuid=c1432ee1-63e2-4c53-a49d-c8739f5ba860&timestamp=1511165485804 (1234ms)

11-20 16:11:27.029 D/OkHttp  (16557): Date: Mon, 20 Nov 2017 08:11:27 GMT

11-20 16:11:27.029 D/OkHttp  (16557): Content-Type: text/html

11-20 16:11:27.029 D/OkHttp  (16557): Content-Length: 13

11-20 16:11:27.029 D/OkHttp  (16557): Connection: close

11-20 16:11:27.029 D/OkHttp  (16557): This is text!

11-20 16:11:27.029 D/OkHttp  (16557): <-- END HTTP (13-byte body)

11-20 16:11:27.029 I/NSubscriber(16557): report success:event/heartbeat

11-20 16:11:27.029 I/NSubscriber(16557): onCompleted

11-20 16:11:27.369 I/System.out(16557): [CDS]read byte is 0

11-20 16:11:27.519 E/octvm_drv( 1793): common drv: platform_autosave_handle -> not implemented

11-20 16:11:27.519 I/octvm_drv( 1793): gap_jiffies: 3752

11-20 16:11:27.519 I/octvm_drv( 1793): cpu0 state: -1204183152

11-20 16:11:27.519 I/octvm_drv( 1793): cpu2 state: -1204183152

11-20 16:11:27.519 I/octvm_drv( 1793): cpu2 state: -1204183152

11-20 16:11:27.519 I/octvm_drv( 1793): cpu2 state: -1204183152

11-20 16:11:27.529 D/StatusBar.NetworkController(  916): onSignalStrengthsChanged received on slotId :1signalStrength=SignalStrength: 24 99 -120 -160 -120 -1 -1 99 2147483647 2147483647 2147483647 2147483647 2147483647 gsm|lte level=5 cdmdlevel=0 evdolevel=0

11-20 16:11:27.549 D/StatusBar.NetworkController(  916): onSignalStrengthsChanged received on slotId :0signalStrength=SignalStrength: 23 99 -120 -160 -120 -1 -1 99 2147483647 2147483647 2147483647 2147483647 2147483647 gsm|lte level=5 cdmdlevel=0 evdolevel=0

11-20 16:11:27.859 D/skia    (16557): --- SkImageDecoder::Factory returned null

11-20 16:11:27.859 D/skia    (16557): --- SkImageDecoder::Factory returned null

11-20 16:11:29.039 D/WifiStateMachine(  838): handleMessage: E msg.what=131143

11-20 16:11:29.039 D/WifiStateMachine(  838): processMsg: ConnectedState

11-20 16:11:29.039 D/WifiStateMachine(  838): processMsg: L2ConnectedState

11-20 16:11:29.039 D/WifiNative-wlan0(  838): doBoolean: SCAN TYPE=ONLY

11-20 16:11:29.049 D/WifiNative-wlan0(  838):    returned true

11-20 16:11:29.049 D/WifiStateMachine(  838): handleMessage: X

11-20 16:11:29.309 I/System.out(16557): [CDS]read byte is 0

11-20 16:11:29.309 D/skia    (16557): --- decoder->decode returned false

11-20 16:11:29.359 D/WifiStateMachine(  838): handleMessage: E msg.what=131155

11-20 16:11:29.359 D/WifiStateMachine(  838): processMsg: ConnectedState

11-20 16:11:29.359 D/WifiStateMachine(  838): processMsg: L2ConnectedState

11-20 16:11:29.359 D/WifiNative-wlan0(  838): doString: SIGNAL_POLL

11-20 16:11:29.359 D/WifiStateMachine(  838): handleMessage: X

11-20 16:11:29.869 W/Netd    (  147): void NetlinkHandler::notifyInterfaceLinkChanged(const char*, bool) ==> Iface linkstate wlan0 up

11-20 16:11:29.869 D/WifiStateMachine(  838): handleMessage: E msg.what=147461

11-20 16:11:29.869 D/WifiStateMachine(  838): processMsg: ConnectedState

11-20 16:11:29.869 D/WifiP2pService(  838): InactiveState{ when=-5ms what=147461 target=com.android.internal.util.StateMachine$SmHandler }

11-20 16:11:29.879 D/WifiStateMachine(  838): processMsg: L2ConnectedState

11-20 16:11:29.879 D/WifiStateMachine(  838): processMsg: ConnectModeState

11-20 16:11:29.879 D/WifiStateMachine(  838): processMsg: DriverStartedState

11-20 16:11:29.879 D/WifiStateMachine(  838): processMsg: SupplicantStartedState

11-20 16:11:29.879 D/WifiNative-wlan0(  838): doString: BSS RANGE=0- MASK=0x23987

11-20 16:11:29.879 D/WifiP2pService(  838): P2pEnabledState{ when=-7ms what=147461 target=com.android.internal.util.StateMachine$SmHandler }

11-20 16:11:29.879 D/WifiP2pService(  838): DefaultState{ when=-8ms what=147461 target=com.android.internal.util.StateMachine$SmHandler }

11-20 16:11:29.879 D/Tethering(  838): interfaceLinkStateChanged wlan0, true

11-20 16:11:29.889 D/Tethering(  838): interfaceStatusChanged wlan0, true

11-20 16:11:29.899 I/System.out(16557): [CDS]read byte is 0

11-20 16:11:29.899 D/WifiStateMachine(  838): mScanResults size: 17

11-20 16:11:29.919 D/ConnectivityService(  838): getActiveNetworkInfo 

11-20 16:11:29.919 D/ConnectivityService(  838): getNetworkInfo:networkType 1 is connected,apn is "gjb_pc"

11-20 16:11:29.929 D/WifiStateMachine(  838): handleMessage: X

11-20 16:11:29.929 D/WifiStateMachine(  838): handleMessage: E msg.what=131131

11-20 16:11:29.929 D/WifiStateMachine(  838): processMsg: ConnectedState

11-20 16:11:29.929 D/WifiStateMachine(  838): processMsg: L2ConnectedState

11-20 16:11:29.929 D/WifiStateMachine(  838): processMsg: ConnectModeState

11-20 16:11:29.939 D/WifiStateMachine(  838): handleMessage: X

11-20 16:11:29.949 D/ConnectivityService(  838): getFilteredNetworkInfo:  network is blocked 

11-20 16:11:29.969 E/lights  (  838): write_int failed to open /sys/class/leds/key-pad/brightness

11-20 16:11:29.979 W/Settings( 1779): Setting android_id has moved from android.provider.Settings.System to android.provider.Settings.Secure, returning read-only value.

11-20 16:11:30.519 E/octvm_drv( 1793): common drv: platform_autosave_handle -> not implemented

11-20 16:11:30.519 I/octvm_drv( 1793): gap_jiffies: 3836

11-20 16:11:30.519 I/octvm_drv( 1793): cpu0 state: -1204183152

11-20 16:11:30.519 I/octvm_drv( 1793): cpu2 state: -1204183152

11-20 16:11:30.519 I/octvm_drv( 1793): cpu2 state: -1204183152

11-20 16:11:30.519 I/octvm_drv( 1793): cpu2 state: -1204183152

11-20 16:11:31.809 I/System.out(16557): [CDS]read byte is 0

11-20 16:11:32.149 D/skia    (16557): --- SkImageDecoder::Factory returned null

11-20 16:11:32.339 I/System.out(16557): [CDS]read byte is 0

11-20 16:11:32.359 D/WifiStateMachine(  838): handleMessage: E msg.what=131155

11-20 16:11:32.359 D/WifiStateMachine(  838): processMsg: ConnectedState

11-20 16:11:32.369 D/WifiStateMachine(  838): processMsg: L2ConnectedState

11-20 16:11:32.369 D/WifiNative-wlan0(  838): doString: SIGNAL_POLL

11-20 16:11:32.369 D/WifiStateMachine(  838): handleMessage: X

11-20 16:11:32.499 I/System.out(16557): [CDS]read byte is 0

11-20 16:11:32.539 D/StatusBar.NetworkController(  916): onSignalStrengthsChanged received on slotId :0signalStrength=SignalStrength: 23 99 -120 -160 -120 -1 -1 99 2147483647 2147483647 2147483647 2147483647 2147483647 gsm|lte level=5 cdmdlevel=0 evdolevel=0

11-20 16:11:32.569 D/StatusBar.NetworkController(  916): onSignalStrengthsChanged received on slotId :1signalStrength=SignalStrength: 24 99 -120 -160 -120 -1 -1 99 2147483647 2147483647 2147483647 2147483647 2147483647 gsm|lte level=5 cdmdlevel=0 evdolevel=0

11-20 16:11:33.519 E/octvm_drv( 1793): common drv: platform_autosave_handle -> not implemented

11-20 16:11:33.519 I/octvm_drv( 1793): gap_jiffies: 3542

11-20 16:11:33.519 I/octvm_drv( 1793): cpu0 state: -1204183152

11-20 16:11:33.519 I/octvm_drv( 1793): cpu2 state: -1204183152

11-20 16:11:33.519 I/octvm_drv( 1793): cpu2 state: -1204183152

11-20 16:11:33.519 I/octvm_drv( 1793): cpu2 state: -1204183152

11-20 16:11:34.999 I/System.out(16557): [CDS]read byte is 0

11-20 16:11:35.379 D/WifiStateMachine(  838): handleMessage: E msg.what=131155

11-20 16:11:35.379 D/WifiStateMachine(  838): processMsg: ConnectedState

11-20 16:11:35.379 D/WifiStateMachine(  838): processMsg: L2ConnectedState

11-20 16:11:35.379 D/WifiNative-wlan0(  838): doString: SIGNAL_POLL

11-20 16:11:35.879 D/WifiStateMachine(  838): handleMessage: X

11-20 16:11:35.909 I/System.out(16557): [CDS]read byte is 0

11-20 16:11:35.919 E/NSubscriber(16557): >>>>>>>>>>>>>>>>>>>>>>null>>>>>>>>>>>>>>>>>>>>>>>>

11-20 16:11:35.919 E/MainFragment(16557): 精选>>>>>>>>>>>>>>>>>>>>>>收到even >>>>>>>>>RecommendListEvent{data=null, channel=Channel{id='100', channel_name='精选', selected='1'}}

11-20 16:11:35.929 E/MainFragment(16557): >>>>>>>>>>>>>>>>>>>>>>提示错误>>>>>>>>>

**Comment by tigerface** [comment]
the followed wireshark log:

[https://github.com/tigerface/test/blob/master/20171120171506.png](https://github.com/tigerface/test/blob/master/20171120171506.png)

**Comment by JakeWharton** [comment]
Can you write a test case that demonstrates the problem in isolation? It's not clear what's happening nor how Retrofit would be to blame.

**Comment by anubhavmalik** [comment]
Since you are mentioning speed of your connection, try to retrieve your data on a high speed connection.
It's unclear what your use case is . Http 200 code (Success) could depend on how the server back-end is designed and it may or may not be retrofit's problem (most probably isn't) .
