### ISSUE TITLE
Proguard - PersistenceException: Constructor not matched for class

### ISSUE THREAD

**Issue by abbasshah17** [square/retrofit#2568]
I am using retrofit2.0 in my app with simpleframework xml converter library.

The problem is when I run the app without proguard it works fine however when I run proguard I get the following Error in logs.

    E/ERROR: java.lang.RuntimeException: org.simpleframework.xml.core.PersistenceException: Constructor not matched for class A

My proguard-rules.pro (with only relevant lib obfuscation rules).

    #-keepattributes *Annotation*

    -dontwarn retrofit2.**
    -keep class retrofit2.** { *; }

    -dontwarn com.bea.xml.stream.**
    -dontwarn org.simpleframework.xml.stream.**
    -keep class org.simpleframework.xml.**{ *; }
    -keepclassmembers,allowobfuscation class * {
        @org.simpleframework.xml.* <fields>;
        @org.simpleframework.xml.* <init>(...);
    }

So the class A had no constructor (which should work BTW), still I added a **No Argument Constructor**.

**Class A**

    @Root(name = "data",strict = false)
    public class A {
        @Element(name = "baseurl",required = false)
        private String baseURl;
        @Element(name = "country_code")
        private String country_code;

        public A() {
        }
    }

And I am still getting the same **Error**.

**Comment by JakeWharton** [comment]
Retrofit doesn't have any control over this as it's a problem with your chosen serialization library. I would suggest posting either on StackOverflow or seeking help from wherever the Simple Framework project provides (mailing list, issue tracker, etc.). I've never used Simple Framework so we're not in a position to provide assistance for how to ensure your models expose what the library requires in order to work.

**Comment by abbasshah17** [comment]
But I am using a Retrofit Integrated converter (SimpleXMLConverter). Shouldn't there be flawless integration with Retrofit itself?
I already have a question on [SO](https://stackoverflow.com/q/47407587/1889768)

**Comment by JakeWharton** [comment]
The Retrofit integration worked flawlessly. The HTTP body was handed to
Simple Framework to deserialize into the target body type which
subsequently failed interacting with your model.

**Comment by zt-lg** [comment]
@abbasshah17  I also encountered this problem, may I solve it?

**Comment by abbasshah17** [comment]
@zt-lg I've not. :)

**Comment by hazems** [comment]
@abbasshah17 I had the same issue, and I could fix it by having a constructor which maps XML elements to class attributes, so in your case, it can be fixed as follows:
```
public A(@Element(name = "baseurl") String baseurl,
         @Element(name = "country_code") String country_code) {

    this.baseurl = baseurl;
    this.country_code = country_code;
}
```
Good luck

**Comment by abbasshah17** [comment]
@hazems You're right, while I was looking for a solution I tried many different things, among them all elements' constructor. However when using an API, you can never be 100% sure which elements are available and which are not. If you didn't get that then Imagine an API where some response elements like `country_code` are optional, they may be there or they may not depending on different variables. And then I realized that the optional elements (not present) can also work by adding another constructor that matches that particular set of elements. But doing that is just terrible work and besides one tiny change in the API and you'd have to release a new app just to keep it API friendly.

P.S. I do realize now that this is not a retrofit issue and should be fixed by simplexml _people_.
