### ISSUE TITLE
[question] - max size of body request, upload stream

### ISSUE THREAD

**Issue by michaelDnguyen** [square/retrofit#2570]
I have a few questions about retrofit 2 that I did not find on stackoverflow:
1. Max size of body request ?
2. Max size of single upload stream (image)
3. max size of multiupload stream (image)

Thanks so much & best regards,

**Comment by JakeWharton** [comment]
Retrofit imposes none of these nor does OkHttp, the underlying HTTP client.
You'll be limited by OkHttp's timeouts (which you can control), network
connectivity (which you don't control), and any server-side limits (which
you may or may not control).
