### ISSUE TITLE
How can I use Retrofit for this requirement?

### ISSUE THREAD

**Issue by jayleco** [square/retrofit#2571]
My app needs to request multiple domains to get the data, for example:
http://news.abc.com/api/20171122
http://weather.abc.com/20171122
https://video.abc.com/api/page/001
http://image.bde.com/api/
http://user.facebook.com/api/creatat/20171122
https://images.aliyun.net
http://images.qq.net
http://images.amazone.net
https://images.ucloud.net
……
……

How can I use Retrofit for this requirement?
please help me, thanks everyone

**Comment by JakeWharton** [comment]
Either create multiple Retrofit instances for each endpoint or include the host in your annotation with a single Retrofit instance. It really depends on what behavior you want. If you have more questions, please ask on StackOverflow with the 'retrofit' tag.
