### ISSUE TITLE
Could not find any version that matches com.squareup.retrofit2:converter-moshi:latest.version.

### ISSUE THREAD

**Issue by remymumoh** [square/retrofit#2573]
So, i am trying to add com.squareup.retrofit2:converter-moshi:latest to my project and i get hit by this error,  **Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not find any version that matches com.squareup.retrofit2:converter-moshi:latest.version. Open File Show Details** . Am using android stuio 3.0, gradle version 3.0.1, when i revert to gradle version 2.3.0 it works fine please update the library to use version 3.0.1

**Comment by NightlyNexus** [comment]
Replace "latest.version" with the latest version ("2.3.0"). There's no reason this would have changed across Android Gradle plugin versions.

**Comment by remymumoh** [comment]
changing it from latest version to 2.3.0 removed all errors
