### ISSUE TITLE
RxJavaCallAdapterFacorty uses Rx Observable 1.x 

### ISSUE THREAD

**Issue by chemickypes** [square/retrofit#2575]
I want use retrofit 2 and RxJava2 but I see that the imports in `RxJavaCallAdapterFactory` are about version 1 of Rx:

``` java
import java.io.IOException;
import java.lang.annotation.Annotation;
import java.lang.reflect.ParameterizedType;
import java.lang.reflect.Type;
import javax.annotation.Nullable;
import retrofit2.CallAdapter;
import retrofit2.HttpException;
import retrofit2.Response;
import retrofit2.Retrofit;
import rx.Completable;
import rx.Observable;
import rx.Scheduler;
import rx.Single;
```

There is a way, that I'd not see, to use version 2 of Rx?

**Comment by JakeWharton** [comment]
Add adapter-rxjava2 instead of adapter-rxjava for RxJava 2.x.

**Comment by geelaro** [comment]
Add `    compile 'com.squareup.retrofit2:adapter-rxjava:2.3.0' ` to use RxJavaCallAdapterFacorty.
