### ISSUE TITLE
Exception while Initializing Call<ResponseBody> call object

### ISSUE THREAD

**Issue by santoshshikare** [square/retrofit#2581]
I am getting following error while initial-zing Call Object  
com.sun.jdi.InternalException : Unexpected JDWP Error: 103
I have configure retrofit properly and it was working proper but some time it gives above error

**Comment by JakeWharton** [comment]
Please provide the full stacktrace or a sample which reproduces the problem.

JDWP is the debugging protocol so it's unlikely Retrofit is the cause.

**Comment by anudeepreddygopu** [comment]
I am facing the same issue.

**Comment by MayankS13** [comment]
In this case, no stack trace is printed. 
Try to download the file from given link using get method. In my case first, it was working fine after some time it keeps on cashing. While on another device it is working fine. Using nexus 5. 

http://h20195.www2.hp.com/v2/getpdf.aspx/4AA7-0722EEE.pdf

**Comment by swankjesse** [comment]
Executable test case?

**Comment by amanps** [comment]
@santoshshikare Verify that all data types in the adapter model class you're using for this API call match the data types in the response.

**Comment by Sai-Deepthi** [comment]
Is it resolved for anyone? I am still facing the issue on Android M while it is working on Android O.

**Comment by chnouman** [comment]
@Sai-Deepthi  are you debugging the code?

**Comment by chnouman** [comment]
dear while debugging it gives this error this is not a library issue nothing but when you are debugging instead of getting a response we get this JDWP error. You can test your request on postman before using it inside retrofit android.

**Comment by Sai-Deepthi** [comment]
I have tested it on postman which is working perfectly fine. Even in the application, it worked a few times but now a crash is generated.
