### ISSUE TITLE
Retrieve each part of the MultipartBody inside a interceptor when using Retrofit

### ISSUE THREAD

**Issue by lxd1047926543** [square/retrofit#2587]
Hi, I wonder if there are some methods that can retrieve each part of the MultipartBody inside a interceptor when using Retrofit?
Thank you for your time!

**Comment by JakeWharton** [comment]
Retrofit doesn't have interceptors. OkHttp has interceptors and it provides you the RequestBody. You can do an `instanceof` check and then cast if successful to get the individual parts.

**Comment by lxd1047926543** [comment]
Thanks for the replay.
The thing is if I use Retrofit with OkHttp, the RequestBody I get in the interceptors of OkHttp is an instance of  ContentTypeOverridingRequestBody, I have no ideas how to get the private field delegate RequestBody out of it without using reflection.

**Comment by JakeWharton** [comment]
Are you specifying a custom Content-Type header as part of that API's
service method annotations?

**Comment by lxd1047926543** [comment]
No. But doesn't the multipart request hava a Content-Type like multipart/form-data or something else itself?

**Comment by JakeWharton** [comment]
Yes, but that's set on the MultipartBody directly and shouldn't need to be
done with the ContentTypeOverridingRequestBody.

**Comment by lxd1047926543** [comment]
I, uh, double checked my annotations specified on the method, and there was really a Content-Type header. Oops, thanks again(Awkward smile).

**Comment by JakeWharton** [comment]
Oh, glad you solved it!
