### ISSUE TITLE
retrofit have cached HTTP 404 

### ISSUE THREAD

**Issue by fdh19979** [square/retrofit#2593]
- [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

My team used retrofit2.1.0 on an android project.

There is a problem that retrofit may have cached HTTP 404 .

I used the fiddler to capure the request is :
GET https://media-mline.nos-eastchina1.126.net/20171219/1fcbea39ed174ef996541e813a6644fd_thumbnail HTTP/1.1
Host: media-mline.nos-eastchina1.126.net
Connection: Keep-Alive
Accept-Encoding: gzip
User-Agent: okhttp/3.8.1
If-Modified-Since: Tue, 19 Dec 2017 09:24:32 GMT
=======================================
HTTP/1.1 304 Not Modified
Server: openresty/1.11.2.5
Date: Tue, 19 Dec 2017 09:25:39 GMT
Connection: keep-alive
x-nos-request-id: 2f879dec-bcd3-40b0-af64-c892c18bee6e

But the logcat of  android studio is :
12-19 16:58:38.557 10722-12938/com.yiwu.mline D/OkHttp: --> GET https://media-mline.nos-eastchina1.126.net/20171219/1fcbea39ed174ef996541e813a6644fd_thumbnail http/1.1
12-19 16:58:38.557 10722-12938/com.yiwu.mline D/OkHttp: --> END GET
12-19 16:58:38.734 10722-12938/com.yiwu.mline D/OkHttp: <-- 404 Not Found https://media-mline.nos-eastchina1.126.net/20171219/1fcbea39ed174ef996541e813a6644fd_thumbnail (176ms)
12-19 16:58:38.735 10722-12938/com.yiwu.mline D/OkHttp: Content-Type: application/xml;charset=UTF-8
12-19 16:58:38.735 10722-12938/com.yiwu.mline D/OkHttp: Content-Length: 351
12-19 16:58:38.735 10722-12938/com.yiwu.mline D/OkHttp: Connection: keep-alive
12-19 16:58:38.735 10722-12938/com.yiwu.mline D/OkHttp: Server: openresty/1.11.2.5
12-19 16:58:38.735 10722-12938/com.yiwu.mline D/OkHttp: Date: Tue, 19 Dec 2017 08:58:43 GMT
12-19 16:58:38.735 10722-12938/com.yiwu.mline D/OkHttp: x-nos-request-id: 79f7bdc4-ceea-4fba-bd72-24f350e6871a
12-19 16:58:38.735 10722-12938/com.yiwu.mline D/OkHttp: Cache-Control: 
12-19 16:58:38.736 10722-12938/com.yiwu.mline D/OkHttp: <?xml version="1.0" encoding="UTF-8"?>
12-19 16:58:38.737 10722-12938/com.yiwu.mline D/OkHttp: <Error>
12-19 16:58:38.737 10722-12938/com.yiwu.mline D/OkHttp:   <Code>NoSuchKey</Code>
12-19 16:58:38.737 10722-12938/com.yiwu.mline D/OkHttp:   <Message>对象“20171219/1fcbea39ed174ef996541e813a6644fd_thumbnail”不存在，请指定正确的对象</Message>
12-19 16:58:38.737 10722-12938/com.yiwu.mline D/OkHttp:   <Resource>/media-mline/20171219/1fcbea39ed174ef996541e813a6644fd_thumbnail</Resource>
12-19 16:58:38.737 10722-12938/com.yiwu.mline D/OkHttp:   <RequestId>0c796e58-e0f1-4d34-9ec9-75ed3b7e7909</RequestId>
12-19 16:58:38.737 10722-12938/com.yiwu.mline D/OkHttp: </Error>
12-19 16:58:38.737 10722-12938/com.yiwu.mline D/OkHttp: <-- END HTTP (351-byte body)

After I deleted the cache file，it work well

**Comment by JakeWharton** [comment]
Retrofit does not have a cache. If caching is involved it comes from OkHttp. Retrofit will create and execute the request against OkHttp every time you invoke the method. Since this issue doesn't appear to be with the formulation of the request, there's no action to take.

If you believe there's a caching problem with OkHttp. You can file an issue on that project, although without more information it's impossible to know what you are seeing. The OkHttp issue tracker template has a link to a test case sample that you can build a test case which models exactly what you are seeing. OkHttp's cache tests are also a good starting point to building a failing test.

**Comment by fdh19979** [comment]
Thank you very much.
I mix the retrofit and okttp 's features.
I have find the issue in okhttp project , it solved my problem.
In case somebody else also make my mistake to mix retrofit and okhttp , i put the issues link in here
https://github.com/square/okhttp/issues/2909

Once again , thank you for your patient answer .

**Comment by fdh19979** [comment]
Thank you very much.
I mix the retrofit and okttp 's features.
I have find the issue in okhttp project , it solved my problem.
In case somebody else also make my mistake to mix retrofit and okhttp , i put the issues link in here
square/okhttp#2909

Once again , thank you for your patient answer .
@JakeWharton
