### ISSUE TITLE
Retrofit 2 calling same request so many unwanted times in my app

### ISSUE THREAD

**Issue by Eyadoos** [square/retrofit#2594]
I have an android app already uploaded to store and working fine, sometimes when a lot of users open the app at the same time (eg. when sending a notification) our servers are getting overloaded and stops responding for about 10 to 15 minutes. I'm using Retrofit 2 to send requests to our server from the app, I've checked all the app requests there are no places where the request is happening when it shouldn't or needed, finally, I added a logging interceptor to retrofit to track the requests and I was surprised that each request is being called more than ten times for no apparent reason! as you can see in the following image:

![fullscreen_12_21_17__7_22_pm](https://user-images.githubusercontent.com/8078957/34267767-bfe44e52-e686-11e7-9294-fce8cd57586b.png)

This is happening with all requests called from the app for no apparent reason. My service generator for Retrofit 2 is the following:

```
private static OkHttpClient.Builder httpClient
        = new OkHttpClient.Builder().connectTimeout(10000, TimeUnit.SECONDS)
        .readTimeout(10000, TimeUnit.SECONDS).addInterceptor(new FakeInterceptor())
        .addNetworkInterceptor(new StethoInterceptor())
        .retryOnConnectionFailure(false);

private static Gson gson = new GsonBuilder()
            .registerTypeAdapter(Date.class, new DateDeserializer())
            .create();

private static Retrofit.Builder builder =
            new Retrofit.Builder()
                    .baseUrl(API_BASE_URL));



public static <S> S createService(Class<S> serviceClass) {

        HttpLoggingInterceptor logging = new HttpLoggingInterceptor();
        logging.setLevel(HttpLoggingInterceptor.Level.BASIC);
        httpClient.addInterceptor(logging);

        Retrofit retrofit = builder.client(httpClient.build()).build();
        return retrofit.create(serviceClass);
    }
```
I am sure request is only called once from my code but I have no idea why Retrofit is making all these useless and unnecessary requests. What might be the problem? Thanks in advance, any help is much appreciated.

**Comment by JakeWharton** [comment]
My guess would be that you call `createService` many times and thus add the logging interceptor over and over again. Call `createService` once, and re-use the returned instance.

**Comment by Eyadoos** [comment]
@JakeWharton I tried what you said but with no luck, the same issue is happening still.

**Comment by JakeWharton** [comment]
Can you provide a sample or executable test case which demonstrates the
problem?
