### ISSUE TITLE
Conflicting Proguard config recommendations

### ISSUE THREAD

**Issue by stevestock** [square/retrofit#2596]
The Progaurd recommendations at [github.com/square/retrofit#proguard](https://github.com/square/retrofit#proguard):

> If you are using ProGuard you might need to add the following options:
> 
> ```
> -dontwarn okio.**
> -dontwarn javax.annotation.**
> ```

**_versus_**

The Proguard recommendations at [square.github.io/retrofit](http://square.github.io/retrofit/) ([website code](https://github.com/square/retrofit/blob/master/website/index.html#L176-L189)):

> If you are using ProGuard in your project add the following lines to your configuration:
> 
> ```
> # Platform calls Class.forName on types which do not exist on Android to determine platform.
> -dontnote retrofit2.Platform
> # Platform used when running on Java 8 VMs. Will not be used at runtime.
> -dontwarn retrofit2.Platform$Java8
> # Retain generic type information for use by reflection by converters and adapters.
> -keepattributes Signature
> # Retain declared checked exceptions for use by a Proxy instance.
> -keepattributes Exceptions
> ```
> Retrofit uses Okio under the hood, so you may want to look at its ProGuard rules as well.

So also, from [github.com/square/okio#proguard](https://github.com/square/okio#proguard):

> If you are using ProGuard you might need to add the following option:
> 
> `-dontwarn okio.**`

_But retrofit actually uses [OKHttp](http://square.github.io/okhttp/) which includes Okio_, which recommends [github.com/square/okhttp#proguard](https://github.com/square/okhttp#proguard):

> ```
> -dontwarn okhttp3.**
> -dontwarn okio.**
> -dontwarn javax.annotation.**
> # A resource is loaded with a relative path so the package of this class must be preserved.
> -keepnames class okhttp3.internal.publicsuffix.PublicSuffixDatabase
> ```

**_Which is correct?_**

**Comment by JakeWharton** [comment]
The README is correct. Rules for Okio and OkHttp are not included in Retofit's rules and we're not going to track changes to them.

**Comment by stevestock** [comment]
> The README is correct. Rules for Okio and OkHttp are not included in Retofit's rules and we're not going to track changes to them.

Just to clarify, the README is simply:

> ```
> -dontwarn okio.**
> -dontwarn javax.annotation.**
> ```

which is not enough, and causes my builds to fail

**Comment by JakeWharton** [comment]
...with what problem?

**Comment by stevestock** [comment]
@JakeWharton I agree that the website is correct.  Would you accept a pull request to change the README to match the website, and have both reference OKHttp instead of Okio

**Comment by JakeWharton** [comment]
Yep!

**Comment by stevestock** [comment]
I think this fits with #2338, I'll try to get this worked out there
Sorry for the redundant issue!
