### ISSUE TITLE
onError:javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by firojandev** [square/retrofit#2601]
Hello,

when I try to get data from https://websitedomain.com. the following error shown in android

"onError:javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
"

How can I solve this?

**Comment by JakeWharton** [comment]
This exception comes from the HTTP client, not Retrofit, and there's nothing you can configure in Retrofit to avoid this, you have to configure the HTTP client.
