### ISSUE TITLE
retrofit2.adapter.rxjava.HttpException: HTTP 305 Use Proxy

### ISSUE THREAD

**Issue by kagile** [square/retrofit#2603]
I am getting following error from the retrofit.
`retrofit2.adapter.rxjava.HttpException: HTTP 305 Use Proxy`

The same URL works with iOS Http clients.
Is there any solution/guide for this?

**Comment by JakeWharton** [comment]
This is not an exception from Retrofit but from the underlying HTTP client. The 305 status states that you should retry the request using the proxy defined in the `Location` header. If you feel that this should be done automatically by the HTTP client then you can file a feature request on [OkHttp][1].

 [1]: https://github.com/square/okhttp
