### ISSUE TITLE
Post request with @Body parameter

### ISSUE THREAD

**Issue by asaeid** [square/retrofit#2605]
Hi
I want to send post request with Body parameter and and my body contains : 
{"start":timestamp, "end":timestamp, "series":[{"id":"string","type":int}]}
and write my body like this https://futurestud.io/tutorials/retrofit-send-objects-in-request-body
but now the server gives me a bad request message.
and  my rest request: 
@POST("data/chart")
Call<ResultGeneric<ChartResponse*>> getChartData(@Body SeriesInput model);

can you guide me please ?

**Comment by wdeo3601** [comment]
I am having the same problem with my API 19 device today..

**Comment by amirulzin** [comment]
This is more suited to StackOverflow and not exactly a Retrofit issue. 
Also details about the relevant API being called is lacking.
Please make sure:
1. Retrofit is constructed with the proper JSON converters
2. The server API is properly mapped to the actual interface
