### ISSUE TITLE
Add Means of Intercepting and Rewiting Requests and Responses Fully

### ISSUE THREAD

**Issue by JakeWharton** [square/retrofit#261]
This will facilitate signing, changing, replacing, etc. See #197 and #224 for more things it will need to support.

Like dealing with headers in the existing implementation, these have a want of being both global and local to an API method which, while not difficult, clutters the APIs.

Draft:
```java
// Read the content of a request and add a signing header.
@POST("/foo")
@RequestInterceptor(OauthSigningInterceptor.class)
Response doSomething();
```
```java
// Grab child JSON from the response (e.g., {"data": {realdata}}) and use it for deserialization.
@GET("/foo")
@ResponseInterceptor(DeclutterInterceptor.class)
Foo doSomething();
```
```java
// Set global interceptors for adding auth headers, etc.
RestAdapter ra = new RestAdpater.Builder()
    .setGlobalRequestInterceptor(..)
    .setGlobalResponseInterceptor(..)
    .build()
```

**Comment by alatar-** [comment]
+1

**Comment by smaspe** [comment]
> That's an HTTP client interceptor job, not Retrofit's job. You'll be able
to do that with OkHttp 2.2.

Right, but having some information regarding the request, may be via annotations, would be nice, as not all requests need the same kind of authentication (e.g. a request requesting a token vs a request using the token as auth).

This is what looked nice in the `@RequestInterceptor(OauthSigningInterceptor.class)` example, is that each request can specify its mean of authentication (or of whatever).

**Comment by CateyesLin** [comment]
+1
I need to sign request before it really send.

**Comment by JakeWharton** [comment]
Use OkHttp interceptors for that!

**Comment by CateyesLin** [comment]
I need more complete request headers, post body to sign.
The RequestInterceptor.RequestFacade cannot do this.

**Comment by jdreesen** [comment]
Not `retrofit.RequestInterceptor.RequestFacade` but [OkHttp interceptors](https://github.com/square/okhttp/wiki/Interceptors) ;)

**Comment by CateyesLin** [comment]
Oh, Great! I'll take a look.

BTW
There still legacy examples on http://square.github.io/retrofit/.

**Comment by JakeWharton** [comment]
Legacy how? It reflects the released version.

**Comment by CateyesLin** [comment]
Sorry I saw master branch instead of tag 1.9.0

**Comment by JakeWharton** [comment]
Rewriting is for [OkHttp interceptors][1]. For modifying objects coming in and out there #816.

 [1]: https://github.com/square/okhttp/wiki/Interceptors
