### ISSUE TITLE
Strange behavior when uploading big files. I am using retrofit:2.3.0 and to upload files to server. It works normally when files are small but when i try to upload large files like 800MB device is starting to work slowly and freezing sometimes.I have no idea what cause that stuation. pls Help

### ISSUE THREAD

**Issue by mfpolat** [square/retrofit#2611]
What kind of issue is this?

 - [x] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by mfpolat** [comment]
Here is my code.

  @Multipart
    @POST("/user/file/upload/")
    Call<UploadFileResponse> uploadNewFile(@Part MultipartBody.Part file, @Part("name") RequestBody name, @Part("folder_id") int folderid);




   RequestBody fileBody = new ProgressRequestBody(file, this);
        RequestBody fileNameBod = RequestBody.create(MediaType.parse("text/plain"), file.getName());
        MultipartBody.Part prgressPart = MultipartBody.Part.createFormData("file", file.getName(), fileBody);


 public void uploadNewFile(MultipartBody.Part file, RequestBody fileName, int folder_id, final OnSuccessListener onSuccessListener) {
        if (!AppController.getInstance().isNetworkConnected()) {
            handleConnectionError();
            return;
        }

        Call call = getTokenClient().uploadNewFile(file, fileName, folder_id);
        call.enqueue(new Callback<UploadFileResponse>() {
            @Override
            public void onResponse(Call<UploadFileResponse> call, retrofit2.Response<UploadFileResponse> response) {
                if (response.code() == 200) {
                    UploadFileResponse uploadFileResponse = response.body();
                    if (uploadFileResponse.isSuccess()) {
                        onSuccessListener.OnSusccess(response);
                    } else {
                        handleError(response.body());
                    }
                } else {
                    handleServerError(response.code());
                }
            }

            @Override
            public void onFailure(Call<UploadFileResponse> call, Throwable t) {
                handleRetrofitError(call);

            }
        });

    }

**Comment by JakeWharton** [comment]
It's not clear what the problem is or who is here so there's no clear action to take. If you can isolate the cause of the slowness then we can take a look. Also make sure you don't have a logging interceptor being used.
