### ISSUE TITLE
Feature request: Allow use of @Headers annotation at interface level

### ISSUE THREAD

**Issue by Gaibhne** [square/retrofit#2612]
I tend to group related REST routes in the same interface, and often they share the same headers. Specifying headers at the HTTP client level is noisy and not granular enough, so I end up with a lot of copy and pasted code. Being able to place @Headers at the interface level would allow me to reduce code like this:

```
public interface Example {
	@GET
	@Headers("X-Special-Flag: someFlag")
	public Call<String> getThingy();

	@GET
	@Headers("X-Special-Flag: someFlag")
	public Call<Void> doStuff(@Query("stuff") int theStuff);

	@GET
	@Headers("X-Special-Flag: someFlag")
	public Call<List<String>> getAllTheThings();

	@GET
	@Headers("X-Special-Flag: someFlag")
	public Call<Boolean> hasThings();
}
```

to code like this:
```
@Headers("X-Special-Flag: someFlag")
public interface Example {
	@GET
	public Call<String> getThingy();

	@GET
	public Call<Void> doStuff(@Query("stuff") int theStuff);

	@GET
	public Call<List<String>> getAllTheThings();

	@GET
	public Call<Boolean> hasThings();
}
```

Seems much neater.

**Comment by naturalwarren** [comment]
I like this idea and would love to take a crack at implementing it if there's interest.

**Comment by swankjesse** [comment]
Our reluctance on this has been around the possibility that it may require precedence rules. Imagine a header that works for all-but-one method.

Do we build a mechanism to let one header override another? Or do they stack? It gets complicated. Particularly since some headers should not be repeated (Authorization) whereas for others it's okay (Cookie).

**Comment by JakeWharton** [comment]
Prior requests: #329 #1113

**Comment by JakeWharton** [comment]
#1866 there's probably more...
