### ISSUE TITLE
NoClassDefFoundError: retrofit2.adapter.rxjava2.HttpException

### ISSUE THREAD

**Issue by jingpeng** [square/retrofit#2618]
java.lang.NoClassDefFoundError: retrofit2.adapter.rxjava2.HttpException	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(Unknown Source)	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(Unknown Source)	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(Unknown Source)	at a08AUx.a08aux.k.subscribe(Unknown Source)	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(Unknown Source)	at a08AUx.a08aux.k.subscribe(Unknown Source)	at a08AUx.a08aux.a08auX.a08auX.a08Aux.ih$1.run(Unknown Source)	at a08AUx.a08aux.r$1.run(Unknown Source)	at a08AUx.a08aux.a08auX.a08aUX.l.run(Unknown Source)	at a08AUx.a08aux.a08auX.a08aUX.l.call(Unknown Source)	at java.util.concurrent.FutureTask.run(FutureTask.java:237)	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)	at java.lang.Thread.run(Thread.java:818)

We happen to find this crash.

**Comment by swankjesse** [comment]
This looks like a packaging problem. Do you have this class in your binary? Is this crash consistent?

**Comment by jingpeng** [comment]
This possibility of this crash is around 80/2000000, and I am sure this class is in my apk

**Comment by JakeWharton** [comment]
That sounds like a classloader or runtime bug on those devices then. I don't see any action to take here. The class is shipped in the jar correctly and the bytecode obviously works on those other 99.999% of devices so the problem lies waaaaay down the toolchain where Retrofit has no control.

**Comment by jingpeng** [comment]
I thought so, too, thanks
