### ISSUE TITLE
The constructor RxErrorHandlingCallAdapterFactory.RxCallAdapterWrapper(Retrofit, CallAdapter\u003ccapture#10-of ?\u003e) is undefined

### ISSUE THREAD

**Issue by manju115** [square/retrofit#2620]
I have posted this issue on stackoverflow [This](https://stackoverflow.com/questions/48401301/the-constructor-rxerrorhandlingcalladapterfactory-rxcalladapterwrapperretrofit) issue is related to retrofit so thought of posting it here too. I am stuck and need some help.

**Comment by naturalwarren** [comment]
Don't use Jack 🤷‍♂️

**Comment by JakeWharton** [comment]
It doesn't seem to be a Retrofit problem since it is your code that is failing to compile and I don't see what action Retrofit itself could take to fix the problem.

And yes, don't use Jack. It's long dead.

**Comment by manju115** [comment]
I need to support lambda expressions in Android Studio 2.3. Is there a way to do that without using Jack?

**Comment by artem-zinnatullin** [comment]
Use Retrolambda or migrate to Android Gradle Plugin 3 and use Desugar
https://developer.android.com/studio/write/java8-support.html#disable_jack
