### ISSUE TITLE
A link which contains : in it

### ISSUE THREAD

**Issue by Faiyyaz** [square/retrofit#2623]
Hello,

I have an api link https://favqs.com/api/users/:login which contains : in between it. The problem is when i hit the api link i m getting 404 not found.

Please can you let me know how can i use this link.

Thank you

**Comment by JakeWharton** [comment]
This test added to `RequestBuilderTest` passes:
```java
@Test public void colon() {
  class Example {
    @GET("api/users/:login") //
    Call<ResponseBody> login() {
      return null;
    }
  }
  Request request = buildRequest(Example.class);
  assertThat(request.method()).isEqualTo("GET");
  assertThat(request.url().toString()).isEqualTo("http://example.com/api/users/:login");
}
```
If you believe there is a problem with how Retrofit creates requests, please express it in a failing test case so we can see exactly what the input and output should be.

**Comment by Faiyyaz** [comment]
Thanks @JakeWharton 

The :login was just a path variable which needs the username in the url.

Its working awesome now. Thanks for such a quick response & such a great library :)
