### ISSUE TITLE
converter-jaxb-LATEST.jar 404

### ISSUE THREAD

**Issue by ArtemBogush** [square/retrofit#2625]
can't download `converter-jaxb` to use in favor to the deprecated `simplexml`

the following link (which is listed on the [main page of the converter](https://github.com/square/retrofit/tree/master/retrofit-converters/jaxb)) gives 404:
https://repo1.maven.org/maven2/com/squareup/retrofit2/converter-jaxb/LATEST/converter-jaxb-LATEST.jar

Gradle can't resolve the dependency neither in both cases below:

case 1: implementation 'com.squareup.retrofit2:converter-jaxb:2.3.0'
case 2: implementation 'com.squareup.retrofit2:converter-jaxb:2.4.0'

which gives: "**Failed to resolve: com.squareup.retrofit2:converter-jaxb:2.3.0**" (same for 2.4.0)

**Comment by JakeWharton** [comment]
The converter hasn't been released yet, it's only on `master`. It will be available with 2.4.0. You can use the latest SNAPSHOT for now if you want to try it out.
