### ISSUE TITLE
Too many follow-up requests problem

### ISSUE THREAD

**Issue by MetaiR** [square/retrofit#2630]
hello,
I saw this on the issues: [too many follow-up requests](https://github.com/square/retrofit/issues/1561).

so we have this problem too and checked the server.
I posted the situation on [StackOverflow](https://stackoverflow.com/questions/48595358/getting-too-many-follow-up-request-as-response-of-request)

is this a bug in retrofit or okhttp?

**Comment by JakeWharton** [comment]
Nether. This indicates a redirect loop between URLs. Instead of following it endlessly, OkHttp stops after 20 or so. You should correct the misconfiguration of the server.

**Comment by MetaiR** [comment]
it wasn't about the server
we realized that if android gets status code 408, it will show `too many follow up` but this problem doesn't exist on other platforms like a website (wrote by js). we change the returning status code to 410 and it fixed now.
I don't know it's a bug or not but it's too bad that we can't use 408 as a response code for our web service.

**Comment by JakeWharton** [comment]
That behavior is in OkHttp, not Retrofit.
