### ISSUE TITLE
Chunked Transfer Encoding Response

### ISSUE THREAD

**Issue by judemanutd** [square/retrofit#2632]
The app is making a request to an endpoint which is sending back a json string containing data fetched from the database. This data could sometimes get pretty huge, as big as 4mb, the default Transfer-Encoding for the server is chunked so when the data is big enough it splits it into chunks and sends it to the app. The problem is Retrofit doesn't seem to be handling that out of the box and crashes with an EOF error. How can this i let Retrofit or rather OkHttp know that the response could be chunked?

**Comment by JakeWharton** [comment]
If the server includes the Transfer-Encoding: chunked header, as it's required to do, OkHttp will transparently un-chunk it. If this is not the case, please create a failing test case for OkHttp as the responsibility for handling this is in that library.

**Comment by WarrenFaith** [comment]
@JakeWharton would be much appreciated if you could be more specific. What do you mean by "transparently un-chunk"?
So far I try to get retrofit send a response for each chunk it gets but I fail miserably. I always only get one response containing everything.
