### ISSUE TITLE
Retrofit 2.2.0 sending multipart/form-data images and 2 strings

### ISSUE THREAD

**Issue by egmixer** [square/retrofit#2633]
I am trying to upload 2 images & 2 strings the problem is that the request works fine on  post man and when i am tried to log the request this is what i found 

`02-05 13:10:45.141 31485-31690/com.speed.speed D/OkHttp: Content-Type: application/x-www-form-urlencoded
02-05 13:10:45.143 31485-31690/com.speed.speed D/OkHttp: Content-Length: 60820
02-05 13:10:45.143 31485-31690/com.speed.speed D/OkHttp: Accept: application/json
02-05 13:10:45.143 31485-31690/com.speed.speed D/OkHttp: Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImVkYzY3MWQzZWU0YTk1MzMyNTNjNjM1MzMxMzU3ZDdiZTYyZDc4YmJmOWRhMzY1OTkxMjA5NmE2N2U2OGU4Yjg4MjUwNzg0MjIyNzVmOTdiIn0.eyJhdWQiOiIyIiwianRpIjoiZWRjNjcxZDNlZTRhOTUzMzI1M2M2MzUzMzEzNTdkN2JlNjJkNzhiYmY5ZGEzNjU5OTEyMDk2YTY3ZTY4ZThiODgyNTA3ODQyMjI3NWY5N2IiLCJpYXQiOjE1MTc4MjMyMDEsIm5iZiI6MTUxNzgyMzIwMSwiZXhwIjoxNTQ5MzU5MjAxLCJzdWIiOiIxMiIsInNjb3BlcyI6WyIqIl19.FZ6s0BGVtQallneVCrGxJSNwd0i0uzNAV7RrstabumYKr5y_Z8meCAb-MADagV9JfjjpsyljOPaRLMi09ROCMWqz_pHCAiEHTgItpT5mN4NvQrcXjhyoipb9pb8q-LVGl451xlswFEDoZbEDtbETDgoitbkNcD1niITmLA0om3k4NCiPPausTFHnplyzwDV6pChpGYTvMSJmftaePMLrMC4gOByR5Hpo8VUEodkD_7wEP7JI8MXzkHnL0F8Lv-yxARJ4gl9Tw0gC6_a6w_fXkfGtBqiW2Ic48thEKm8wiGORVhlJhtP5-lsbmnS6Buq3hKJw2BaETUVsMzKcoMGHwHA0Ju_M9XbE4wZHVApDU6aenNIsAVAZix1ZiVqYKrKVN20ATzsI-zZNukcFZkWRPhApFnz0hDIDe_LfUJ-Gc90976vxU6_8nEVOqX7-FSPJd-hWw7DZveej3W6YW8aD7sRVgUTSWO_X3GhhCEYpehC_sS7iT1jock24cm78STSikcKJYh4VBxPUibWG7t5fcrjKc5EFxNKO936uI5KT6YHnVsuymIq9dfM_eF-bUBLj-PrMTKE9Pl2sbW8-zB4TBiIQaErR7_4TEh4YpiWQwYibjnuK32EsIy0Fqv3NomoI6zfMGYqgoD6Aw7kDz2O3QVhs4-xYt6Fo0mmxeUd4PZw
02-05 13:10:45.181 31485-31690/com.speed.speed D/OkHttp: --14b7b4a2-a073-4e55-8302-c020807326b3
02-05 13:10:45.181 31485-31690/com.speed.speed D/OkHttp: Content-Disposition: form-data; name="image"; filename="1517829045024.jpg"
02-05 13:10:45.181 31485-31690/com.speed.speed D/OkHttp: Content-Type: multipart/form-data
02-05 13:10:45.181 31485-31690/com.speed.speed D/OkHttp: Content-Length: 30017
02-05 13:10:45.187 31485-31690/com.speed.speed D/OkHttp: --14b7b4a2-a073-4e55-8302-c020807326b3
02-05 13:10:45.187 31485-31690/com.speed.speed D/OkHttp: Content-Disposition: form-data; name="image_id"; filename="1517829045067.jpg"
02-05 13:10:45.187 31485-31690/com.speed.speed D/OkHttp: Content-Type: multipart/form-data
02-05 13:10:45.187 31485-31690/com.speed.speed D/OkHttp: Content-Length: 30017
02-05 13:10:45.192 31485-31690/com.speed.speed D/OkHttp: --14b7b4a2-a073-4e55-8302-c020807326b3
02-05 13:10:45.192 31485-31690/com.speed.speed D/OkHttp: Content-Disposition: form-data; name="name"
02-05 13:10:45.192 31485-31690/com.speed.speed D/OkHttp: Content-Transfer-Encoding: binary
02-05 13:10:45.192 31485-31690/com.speed.speed D/OkHttp: Content-Type: text/plain; charset=utf-8
02-05 13:10:45.192 31485-31690/com.speed.speed D/OkHttp: Content-Length: 10
02-05 13:10:45.192 31485-31690/com.speed.speed D/OkHttp: Atef Etman
02-05 13:10:45.192 31485-31690/com.speed.speed D/OkHttp: --14b7b4a2-a073-4e55-8302-c020807326b3
02-05 13:10:45.192 31485-31690/com.speed.speed D/OkHttp: Content-Disposition: form-data; name="bio"
02-05 13:10:45.192 31485-31690/com.speed.speed D/OkHttp: Content-Transfer-Encoding: binary
02-05 13:10:45.192 31485-31690/com.speed.speed D/OkHttp: Content-Type: text/plain; charset=utf-8
02-05 13:10:45.192 31485-31690/com.speed.speed D/OkHttp: Content-Length: 7
02-05 13:10:45.193 31485-31690/com.speed.speed D/OkHttp: tvyvyby
02-05 13:10:45.193 31485-31690/com.speed.speed D/OkHttp: --14b7b4a2-a073-4e55-8302-
c020807326b3--
02-05 13:10:45.193 31485-31690/com.speed.speed D/OkHttp: --> END POST (60820-byte body)
02-05 13:10:45.208 31485-31491/com.speed.speed I/zygote64: Compiler allocated 7MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
02-05 13:10:46.864 31485-31690/com.speed.speed D/OkHttp: <-- 201 Created  (1671ms)
02-05 13:10:46.864 31485-31690/com.speed.speed D/OkHttp: Date: Mon, 05 Feb 2018 11:10:43 GMT
02-05 13:10:46.865 31485-31690/com.speed.speed D/OkHttp: Server: Apache/2.4.27 (Win64) PHP/7.0.23
02-05 13:10:46.865 31485-31690/com.speed.speed D/OkHttp: Vary: Authorization
02-05 13:10:46.865 31485-31690/com.speed.speed D/OkHttp: X-Powered-By: PHP/7.0.23
02-05 13:10:46.865 31485-31690/com.speed.speed D/OkHttp: Cache-Control: no-cache, private
02-05 13:10:46.865 31485-31690/com.speed.speed D/OkHttp: X-RateLimit-Limit: 60
02-05 13:10:46.865 31485-31690/com.speed.speed D/OkHttp: X-RateLimit-Remaining: 58
02-05 13:10:46.865 31485-31690/com.speed.speed D/OkHttp: Content-Length: 331
02-05 13:10:46.865 31485-31690/com.speed.speed D/OkHttp: Keep-Alive: timeout=5, max=100
02-05 13:10:46.865 31485-31690/com.speed.speed D/OkHttp: Connection: Keep-Alive
02-05 13:10:46.865 31485-31690/com.speed.speed D/OkHttp: Content-Type: application/json
02-05 13:10:46.868 31485-31690/com.speed.speed D/OkHttp: {"status_code":201,"message":"Update process succeed.","data":{"id":12,"name":"dsfkjsdhfj","phone":"00966090705106","image":"133832115a78375613a5a.jpg","image_id":"916892275a78375613c8a.jpg","bio":"sdfsdfsdfsdf","total_score":"0","status":"1","last_seen":null,"created_at":"2018-02-04 16:21:42","updated_at":"2018-02-05 10:52:06"}}
02-05 13:10:46.868 31485-31690/com.speed.speed D/OkHttp: <-- END HTTP (331-byte body)`
 
the response i get it seems to be the last update i've made from postman and there's no update happens from my device ?

here my service:`@Headers({"Content-Type: application/x-www-form-urlencoded",
        "Accept: application/json"})
        @Multipart
        @POST("api/editaccount")
        Call<EditProfileResponse> editProfile(@Part MultipartBody.Part image,
                                              @Part MultipartBody.Part imageId,
                                              @Part("name") RequestBody name,
                                              @Part("bio") RequestBody bio,
                                              @Header("Authorization") String authorization);`

**Comment by etman55** [comment]
@JakeWharton i have the same problem can you help?

**Comment by etman55** [comment]
It worked for me you problem is Content Type header which is application/x-www-form-urlencoded
try to remove that and i think it will work :)
