### ISSUE TITLE
Handle HTTP DELETE/PUT request response body null with HTTP response code 204,205

### ISSUE THREAD

**Issue by drayan85** [square/retrofit#2651]
HTTP DELETE/PUY request response body is empty throwing error;

In The `BodyObservable.class` (`package retrofit2.adapter.rxjava2;`)

Is possible to handle the situation for HTTP response code 204, 205 with Empty body
```
    private static class BodyObserver<R> implements Observer<Response<R>> {
        private final Observer<? super R> observer;
        private boolean terminated;

        BodyObserver(Observer<? super R> observer) {
            this.observer = observer;
        }

        @Override public void onSubscribe(Disposable disposable) {
            observer.onSubscribe(disposable);
        }

        @Override public void onNext(Response<R> response) {
            if (response.isSuccessful()) {
                R body = response.body();
                int code = response.code();
                if (code == 204 || code == 205) {
                    //NO CONTENT - [DELETE]
                    if (body == null){
                        onComplete();
                    }
                    return;
                }
                if (body == null){
                    observer.onError(new RuntimeException("Response Body not allow Null"));
                    return;
                }
                observer.onNext(body);
            } else {
                terminated = true;
                Throwable t = new HttpException(response);
                try {
                    observer.onError(t);
                } catch (Throwable inner) {
                    Exceptions.throwIfFatal(inner);
                    RxJavaPlugins.onError(new CompositeException(t, inner));
                }
            }
        }

        @Override public void onComplete() {
            if (!terminated) {
                observer.onComplete();
            }
        }

        @Override public void onError(Throwable throwable) {
            if (!terminated) {
                observer.onError(throwable);
            } else {
                // This should never happen! onNext handles and forwards errors automatically.
                Throwable broken = new AssertionError(
                        "This should never happen! Report as a bug with the full stacktrace.");
                //noinspection UnnecessaryInitCause Two-arg AssertionError constructor is 1.7+ only.
                broken.initCause(throwable);
                RxJavaPlugins.onError(broken);
            }
        }
    }
```
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by JakeWharton** [comment]
Please see https://github.com/square/retrofit/issues/2242#issuecomment-300850574 for a detailed analysis of a case similar to this. You should use the `Optional` converter (or any other which doesn't produce `null`) in cases where your adapter cannot handle `null`.

**Comment by drayan85** [comment]
Thanks, @JakeWharton  somehow I missed the issue #2242  to refer.
