### ISSUE TITLE
Feature request: reduce boiler plate by supporting javac -parameters

### ISSUE THREAD

**Issue by Gaibhne** [square/retrofit#2654]
A lot of interface definitions look like this:

    @GET("users/{name}/{domain}/{level}")
    Call<User> getUserRanks(@Path("name") String name, @Path("domain") String domain, @Path("level") int level);

Following DRY, it bothers me that the variable name has to be typed out twice (for cases where the names are identical). javac supports embedding parameter names with the `-parameters` flag, so it would be possible to reduce the above to:

    @GET("users/{name}/{domain}/{level}")
    Call<User> getUserRanks(@Path String name, @Path String domain, @Path int level);

or possibly even:

    @GET("users/{name}/{domain}/{level}")
    Call<User> getUserRanks(String name, String domain, int level);

I originally came across this option in the JDBI library, where some more detail can be found: http://jdbi.org/#_compiling_with_parameter_names

**Comment by JakeWharton** [comment]
I looked into this a few years ago back when Java 8 was in EA releases. We
decided not to do anything because it was opt-in and couldn't be supported
on Android.

From a user experience perspective, when you default the annotation value
the IDE doesn't prompt you for it meaning the common case (when a value is
required) is easy to overlook. You don't find out you have a problem until
runtime.

**Comment by raderio** [comment]
> You don't find out you have a problem until runtime.

It is not the same if we have 
```
public interface GitHubService {
  @GET("users/{user}/repos")
  Call<List<Repo>> listRepos(@Path("users") String user);
}
```
?
You will notice this in runtime.

**Comment by JakeWharton** [comment]
Not at all the same. That case is a simple user error. Not an omission of
path name because you weren't forced to include it and didn't know that
java doesn't include parameter names by default.

**Comment by swankjesse** [comment]
No plans for this at the moment.
