### ISSUE TITLE
EOFException: End of input at line 1 column 1 path $

### ISSUE THREAD

**Issue by Kolyall** [square/retrofit#2655]
"com.squareup.retrofit2:retrofit:2.1.0"
"com.squareup.okhttp3:okhttp:3.9.1"

Bug report
The error occurs:
If I work with body of `Response` in `Interceptor`, seems because I read `ResponseBody ` of `Response`, or because of I read it to `string()`, for example add `Interceptor`:
```

public class MyInterceptor implements Interceptor {
 @Override
    public Response intercept(final Chain chain) throws IOException {
        Request original = chain.request();

        Response response = chain.proceed(original);

        ResponseBody body = response.body();
        String bodyString = body != null ? body.string() : null;

      return response ;

}
```

**Comment by JakeWharton** [comment]
Please read the OkHttp docs on ResponseBody. You cannot consume it twice.
