### ISSUE TITLE
RxJava2CallAdapter not propagating request cancel when called on client

### ISSUE THREAD

**Issue by Bxttx** [square/retrofit#2656]
I'm trying to cancel all requests on an OkHttpClient while using it in a Retrofit + RxJava2CallAdapter configuration.
After cancelling the request, wrapped as RxJava Single, I don't receive any event in the stream.
Here's a failing test that reproduces the issue: https://gist.github.com/Bxttx/c6e8b7474464e5e7722ca692b4885c72

I guess there is an unhandled case in `CallExecuteObservable`:
```
@Override protected void subscribeActual(Observer<? super Response<T>> observer) {
    // Since Call is a one-shot type, clone it for each new observer.
    Call<T> call = originalCall.clone();
    observer.onSubscribe(new CallDisposable(call));

    boolean terminated = false;
    try {
      Response<T> response = call.execute();
      if (!call.isCanceled()) {
        observer.onNext(response);
      }
      if (!call.isCanceled()) {
        terminated = true;
        observer.onComplete();
      }
      // <----------- else, throw error when canceled ?
    } catch (Throwable t) {
      Exceptions.throwIfFatal(t);
      if (terminated) {
        RxJavaPlugins.onError(t);
      } else if (!call.isCanceled()) {
        try {
          observer.onError(t);
        } catch (Throwable inner) {
          Exceptions.throwIfFatal(inner);
          RxJavaPlugins.onError(new CompositeException(t, inner));
        }
      }
    }
  }
```

**Comment by JakeWharton** [comment]
The existing code is correct. What needs changed is separating the downstream disposed state and the upstream call canceled state. Upstream cancelation does **not** indicate downstream disposal, but downstream disposal does indicate upstream cancelation.
