### ISSUE TITLE
Synchronous calls silently discard exceptions and never return

### ISSUE THREAD

**Issue by nathan-b** [square/retrofit#2668]
When using Retrofit synchronously (i.e. calling call.execute instead of call.enqueue), any exception encountered by the JSON parser will be silently discarded. No exception will be returned and the call will be blocked indefinitely.

I don't have any sanitized example code, but here's a rough outline:

interface RESTData
* `@GET("url") fun DoSomething(): Call<RESTData>`

class ServerCommunicator
* `fun getRESTData(): Stuff { `
  * `rd: Call<RESTData> = DoSomething()`
  * `try { resp: Response<RESTData> = rd.execute() } catch (Exception e) { Log.e("Bad", e.message)  }`
  * `return resp.body() }`

UI Thread:
* `onCreate() {`
  * `doAsync { var stuff = ServerCommunicator.getRESTData() } }`

If the parser (in my case, Moshi) fails to parse the data and throws an exception, that exception will get caught inside Retrofit's async code and never rethrown. From a developer perspective, the program flow halts at rd.execute() and never proceeds.

Hopefully this is enough description. If not then I can try to produce a toy program that reproduces the issue, but that might take several days before I get the time so I figured I'd give you something now in case you can get traction on it.

**Comment by NightlyNexus** [comment]
https://github.com/square/retrofit/blob/687b3a639d64dfddd549d79a0097614dd1ef2040/retrofit/src/test/java/retrofit2/CallTest.java#L257
shows that this works.

I don't see any obvious causes from your posted code, so a test case or reproducible sample would be great.
