### ISSUE TITLE
How to pass Json body data in @OPTIONS

### ISSUE THREAD

**Issue by alphaDroid89** [square/retrofit#2669]
Hi All,

I want to pass the below Json data to my API service with the @OPTIONS method. 
`{"username":"name","password":"test@user"}`

I tried with 

   ```
@OPTIONS("login/userauth?")
        Observable<Response<ResponseBody>> userLogin(@QueryMap JsonObject mLoginRequestBody);
```

It throws error code 200. Can anyone please help me out to fix this.

Thanks.

**Comment by JakeWharton** [comment]
200 is not an error, it's success.

This is a usage question which is generally more appropriate for StackOverflow. GitHub issues are reserved for bug reports with test cases or samples, or new feature requests. You can use the 'retrofit' tag which is monitored by us and many library users. Feel free to link the asked question back here on the issue.
