### ISSUE TITLE
release apk Error with proguard rules

### ISSUE THREAD

**Issue by akshaynjain** [square/retrofit#2682]
What kind of issue is this?

 - [ ] Question. Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> Job failed, see logs for details

 - [ ] Here is my proguard rules

-assumenosideeffects class android.util.Log {
    public static *** d(...);
    public static *** w(...);
    public static *** v(...);
    public static *** i(...);
}

-keep class com.crashlytics.** { *; }
-dontwarn com.crashlytics.**
-dontwarn com.visiontek.**

-dontwarn org.apache.http.**
-dontwarn org.bouncycastle.**
#-keep class android.support.design.widget.** { *; }
#-keep interface android.support.design.widget.** { *; }
#-dontwarn android.support.design.**

-keep class android.support.v4.** { *; }
-keep interface android.support.v4.** { *; }

-dontwarn android.support.**
-dontwarn android.support.design.**
-keep class android.support.design.** { *; }
-keep interface android.support.design.** { *; }
-keep interface android.support.design.widget.** { *; }
-keep public class android.support.design.R$* { *; }

-keep class com.sec.biometric.** { *; }
-keepclassmembers class com.sec.biometric.** { *; }
-dontwarn com.sec.biometric.**
-keepclassmembers class * {
    @android.webkit.JavascriptInterface <methods>;
}

-keepattributes JavascriptInterface
-keepattributes Signature

-keepattributes *Annotation*

-dontwarn sun.misc.**

-keep class com.google.gson.examples.android.model.** { *; }

-keep class com.google.gson.TypeAdapterFactory
-keep class com.google.gson.JsonSerializer
-keep class com.google.gson.JsonDeserializer
-keep class com.fasterxml.jackson.jackson-databind
-keep class com.fasterxml.jackson.jackson-core
-keep class com.fasterxml.jackson.jackson-annotations
-keep class org.joda.time
-dontwarn org.joda.convert.**
-dontwarn javax.annotation.GuardedBy

**Comment by JakeWharton** [comment]
ProGuard is a build tool, you should seek help either from its forum or a general one like StackOverflow with the 'retrofit' tag. This issue tracker is for bugs and feature requests only.
