### ISSUE TITLE
SocketTimeoutException in background service only

### ISSUE THREAD

**Issue by Riningan** [square/retrofit#2684]
Hello!
I have background service.
He periodically send data to server.
When activity is dead (no in app list)? I catch always exception:
java.net.SocketTimeoutException: failed to connect to m2mtest.nis-glonass.ru/213.87.44.109 (port 443) after 35000ms: isConnected failed: ETIMEDOUT (Connection timed out)
But when I start activity, exception gone and service works fine.
Is any constraints to work in background?

**Comment by Riningan** [comment]
Hello!
I have background service. 
He periodically sent data to server. 
When activity is dead (no in app list)
I always catch this exception
java.net.SocketTimeoutException: failed to connect to xxx.xxx.xx/xxx.xx.xx.xx (port xxx) after 35000ms: isConnected failed: ETIMEDOUT (Connection timed out)
But when I start activity exception is gone.
And service work fine.
Is any constraints to work in background?

**Comment by JakeWharton** [comment]
This isn't a problem with Retrofit. Android imposes all kinds of restrictions for doing work in the background and it likely it preventing you from using the network. You'll need to hold wake locks, use a foreground service, or a mechanism like JobScheduler to prevent this behavior.
