### ISSUE TITLE
retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall@7aa981e

### ISSUE THREAD

**Issue by paveltech** [square/retrofit#2689]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

i am using

    private String authToken;
    public AuthenticationInterceptor(String token) {
        this.authToken = token;
    }

    @Override
    public Response intercept(Chain chain) throws IOException {
        Request original = chain.request();

        Request.Builder builder = original.newBuilder()
                .addHeader("Authorization", authToken)
                .addHeader("Cache-Control", "no-cache");

        Request request = builder.build();
        return chain.proceed(request);
    }
}

But always getting this error
            retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall@7aa981e

**Comment by JakeWharton** [comment]
That is not an error. Please provide a full stacktrace and/or failing test case and/or executable sample.

**Comment by paveltech** [comment]
ok i am giving you everything what ever i done. just check it out. 


my pojo class 


    public class CountryResponce {

    @SerializedName("iso_code")
    @Expose
    private String isoCode;
    @SerializedName("name")
    @Expose
    private String name;

    public String getIsoCode() {
        return isoCode;
    }

    public void setIsoCode(String isoCode) {
        this.isoCode = isoCode;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}


     public class AuthenticationInterceptor implements Interceptor {

        private String authToken;

        public AuthenticationInterceptor(String token) {
           this.authToken = token;
       }

       @Override
       public Response intercept(Chain chain) throws IOException {
           Request original = chain.request();

           Request.Builder builder = original.newBuilder()
                  .addHeader("Authorization", authToken)
                  .addHeader("Cache-Control", "no-cache");

          Request request = builder.build();
          return chain.proceed(request);
    }
}

and my 


      public interface LoginService {
         @GET("/v1/money-transfer/countries")
         Call<CountryResponce> basicLogin();
    }


and my login state 


       public static final String API_BASE_URL = "https://api-pre.mm.transferto.com";

       private static OkHttpClient.Builder httpClient = new OkHttpClient.Builder();

    private static Retrofit.Builder builder =
            new Retrofit.Builder()
                    .baseUrl(API_BASE_URL)
                    .addConverterFactory(GsonConverterFactory.create());

    private static Retrofit retrofit = builder.build();


    public static <S> S createService(
            Class<S> serviceClass, String username, String password) {
        if (!TextUtils.isEmpty(username)
                && !TextUtils.isEmpty(password)) {
            String authToken = Credentials.basic(username, password);
            Log.d("authToken" , ""+authToken);
            return createService(serviceClass, authToken);
        }

        return createService(serviceClass, null);
    }

    public static <S> S createService(
            Class<S> serviceClass, final String authToken) {
        if (!TextUtils.isEmpty(authToken)) {
            AuthenticationInterceptor interceptor =
                    new AuthenticationInterceptor(authToken);

            if (!httpClient.interceptors().contains(interceptor)) {
                httpClient.addInterceptor(interceptor);

                builder.client(httpClient.build());
                retrofit = builder.build();
            }
        }

         return retrofit.create(serviceClass);
        }
     }


and my final call.


              final LoginService loginService = ServiceGenerator.createService(LoginService.class , "a89fd8a6-3ea4-575b-a535-5c7607497cdc" , "5585c839-8045-51bb-99e2-d848f7c75826");
             Call<CountryResponce> call = loginService.basicLogin();
               Log.d("url" , ""+call.request().url().toString());
              call.enqueue(new Callback<CountryResponce>() {
                @Override
               public void onResponse(Call<CountryResponce> call, Response<CountryResponce> response) {

                if (response.isSuccessful()){
                    // do something
                    Toast.makeText(MainActivity.this, "Yes", Toast.LENGTH_SHORT).show();
                    String name  = response.body().getName();
                    Log.d("apicall" , ""+name);
                }
                else {
                    Toast.makeText(MainActivity.this, "Not successful", Toast.LENGTH_SHORT).show();
                }
            }

            @Override
            public void onFailure(Call<CountryResponce> call, Throwable t) {
                Log.d("error" , ""+call);
            }
        });


what's wrong with this when i call api from postman or browser everything is ok but from app getting nothing. can you check it @JakeWharton

**Comment by JakeWharton** [comment]
```
        @Override
        public void onFailure(Call<CountryResponce> call, Throwable t) {
            Log.d("error" , ""+call);
        }
```
You should be logging `t` which will indicate the problem.

**Comment by paveltech** [comment]
ya i got it and this is retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall@7aa981e

that's why i need a solution.

**Comment by JakeWharton** [comment]
No. That's from logging the call object and not the exception.

**Comment by paveltech** [comment]
so why not my code doesn't work

**Comment by Apsaliya** [comment]
```
         @Override
         public void onFailure(Call<CountryResponce> call, Throwable t) {
           t.printStackTrace();
        }
```
Log your error like this and provide full stacktrace and ask the question here : https://stackoverflow.com/questions/tagged/retrofit

**Comment by milan400** [comment]
retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall@7bcde23  comes at logcat what to do

**Comment by mahdiba97** [comment]
As from error you are receiving, server returns object while you're expecting a string.

**Comment by phucbv98x3** [comment]
thanks
