### ISSUE TITLE
Headers parameter annotation for okhttp3.Headers

### ISSUE THREAD

**Issue by NightlyNexus** [square/retrofit#2696]
There's no way to do `@HeaderMap Map<String, List<String>> headers` as a parameter right now. (Maybe that should be allowed? I can open a separate issue or PR later.)

How about a way to pass in okhttp3.Headers? (even easier to implement with https://github.com/square/okhttp/issues/3923)

I'm not sure what the annotation name would be. There's already the method annotation `@Headers`.

**Comment by JakeWharton** [comment]
Probably just re-use the `@HeaderMap` annotation even though it's a bit weird. The semantics are at least the same.

PR welcome.
