### ISSUE TITLE
`@HeaderMap Map<String, List<String>>` for parameters.

### ISSUE THREAD

**Issue by NightlyNexus** [square/retrofit#2697]
Opening this to track possible feature. I'd prefer just `okhttp3.Headers` from #2696, as that's my use case.

**Comment by JakeWharton** [comment]
Dupe #1324

**Comment by NightlyNexus** [comment]
Yeah, I saw that.
It's trickier for query parameters because it's ambiguous whether you have a list parameter or you have a list of parameters.

For headers, you don't have to feed them into any string converter or anything, so you can just handle it depending on the type.

**Comment by NightlyNexus** [comment]
Oops, I'm wrong. Header values are put through the string converter. Never mind, totally a duplicate.

**Comment by JakeWharton** [comment]
Are you sure? I'm pretty sure they go through the converters.
