### ISSUE TITLE
Using SimpleXMLConverterFactory requires special rule in proguard

### ISSUE THREAD

**Issue by zishanj** [square/retrofit#2703]
While using `SimpleXMLConverterFactory` I receive following error and my app crashes. I have to add this rule in `proguard` to overcome this issue:

`-keep class org.simpleframework.xml.** { *; }`

May be you can update your documentation to mention above rule also. Here is the error log:

> Non-fatal Exception: java.lang.RuntimeException: java.lang.NoSuchMethodException: <init> [interface org.b.a.b.ag, interface org.b.a.d, class org.b.a.e.i]
>        at retrofit2.converter.simplexml.SimpleXmlResponseBodyConverter.convert(Unknown Source)
>        at retrofit2.converter.simplexml.SimpleXmlResponseBodyConverter.convert(Unknown Source)
>        at retrofit2.ServiceMethod.toRequest(Unknown Source)
>        at retrofit2.OkHttpCall.enqueue(Unknown Source)
>        at retrofit2.OkHttpCall.enqueue(Unknown Source)
>        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(Unknown Source)
>        at io.reactivex.Observable.timer(Unknown Source)
>        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(Unknown Source)
>        at io.reactivex.Observable.timer(Unknown Source)
>        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(Unknown Source)
>        at io.reactivex.Single.create(Unknown Source)
>        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(Unknown Source)
>        at io.reactivex.Scheduler$DisposeTask.run(Unknown Source)
>        at io.reactivex.internal.schedulers.ScheduledRunnable.run(Unknown Source)
>        at io.reactivex.internal.schedulers.ScheduledRunnable.call(Unknown Source)
>        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
>        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
>        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
>        at java.lang.Thread.run(Thread.java:761)

> Caused by java.lang.NoSuchMethodException: <init> [interface org.b.a.b.ag, interface org.b.a.d, class org.b.a.e.i]
>        at java.lang.Class.getConstructor0(Class.java:2204)
>        at java.lang.Class.getConstructor(Class.java:1683)
>        at org.simpleframework.xml.core.LabelExtractor$LabelBuilder.getConstructor(Unknown Source)
>        at org.simpleframework.xml.core.LabelExtractor$LabelBuilder.getConstructor(Unknown Source)
>        at org.simpleframework.xml.core.LabelExtractor.getList(Unknown Source)
>        at org.simpleframework.xml.core.LabelExtractor.getLabel(Unknown Source)
>        at org.simpleframework.xml.core.LabelExtractor.getSingle(Unknown Source)
>        at org.simpleframework.xml.core.LabelExtractor.getLabels(Unknown Source)
>        at org.simpleframework.xml.core.LabelExtractor.getLabel(Unknown Source)
>        at org.simpleframework.xml.core.LabelExtractor.getLabel(Unknown Source)
>        at org.simpleframework.xml.core.Support.replace(Unknown Source)
>        at org.simpleframework.xml.core.StructureBuilder.process(Unknown Source)
>        at org.simpleframework.xml.core.StructureBuilder.assemble(Unknown Source)
>        at org.simpleframework.xml.core.ObjectScanner.getType(Unknown Source)
>        at org.simpleframework.xml.core.ObjectScanner.getSignature(Unknown Source)
>        at org.simpleframework.xml.core.ObjectScanner.(Unknown Source)
>        at org.simpleframework.xml.core.ScannerFactory.getInstance(Unknown Source)
>        at org.simpleframework.xml.core.Support.getMethods(Unknown Source)
>        at org.simpleframework.xml.core.Source.getScanner(Unknown Source)
>        at org.simpleframework.xml.core.Source.getSchema(Unknown Source)
>        at org.simpleframework.xml.core.Composite.read(Unknown Source)
>        at org.simpleframework.xml.core.Composite.read(Unknown Source)
>        at org.simpleframework.xml.core.Traverser.read(Unknown Source)
>        at org.simpleframework.xml.core.Persister.read(Unknown Source)
>        at org.simpleframework.xml.core.Persister.read(Unknown Source)
>        at org.simpleframework.xml.core.Persister.read(Unknown Source)
>        at org.simpleframework.xml.core.Persister.read(Unknown Source)
>        at retrofit2.converter.simplexml.SimpleXmlResponseBodyConverter.convert(Unknown Source)
>        at retrofit2.converter.simplexml.SimpleXmlResponseBodyConverter.convert(Unknown Source)
>        at retrofit2.ServiceMethod.toRequest(Unknown Source)
>        at retrofit2.OkHttpCall.enqueue(Unknown Source)
>        at retrofit2.OkHttpCall.enqueue(Unknown Source)
>        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(Unknown Source)
>        at io.reactivex.Observable.timer(Unknown Source)
>        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(Unknown Source)
>        at io.reactivex.Observable.timer(Unknown Source)
>        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(Unknown Source)
>        at io.reactivex.Single.create(Unknown Source)
>        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(Unknown Source)
>        at io.reactivex.Scheduler$DisposeTask.run(Unknown Source)
>        at io.reactivex.internal.schedulers.ScheduledRunnable.run(Unknown Source)
>        at io.reactivex.internal.schedulers.ScheduledRunnable.call(Unknown Source)
>        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
>        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
>        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
>        at java.lang.Thread.run(Thread.java:761)

**Comment by JakeWharton** [comment]
This is a problem of interaction between the Simple XML framework and your code. It is not a problem of interaction between the Simple XML converter and Retrofit. We don't maintain ProGuard rules for the serialization libraries as they can be very nuanced based on how you're using them and what you have enabled in ProGuard.

Also that rule is, frankly, crazy. There should never be a need for such an overly-keepy rule, and you should try to write one that is far more specific and retains the minimal amount necessary rather than the entirety of the library.
