### ISSUE TITLE
[JAXBConverter] Didn't find class "com.sun.xml.internal.bind.v2.ContextFactory"

### ISSUE THREAD

**Issue by NoMaillard** [square/retrofit#2705]
Hi,

I'm using the new JAXBConverter, but i can't make any requests :disappointed: 
i get an exception : `Didn't find class "com.sun.xml.internal.bind.v2.ContextFactory"`
 Here's how i setup my retrofit 
```kt
val retrofit = Retrofit.Builder()
                .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
                .addConverterFactory(JaxbConverterFactory.create())
                .baseUrl(BuildConfig.MGPT_URL)
                .build()

            return retrofit.create(MGPTApi::class.java)
```

i've tried with `.addConverterFactory(JaxbConverterFactory.create(JAXBContext.newInstance(MGPTApi::class.java)))`

but the result is the same

any clue on what to do ?

seems like i have a missing package, but i'm not sure how to find which one or how to fix it...

**Comment by myleswh** [comment]
Hey, 
Is this on Android? If so JAXB isn't supported. 

https://github.com/square/retrofit/issues/2702#issuecomment-374252966
https://github.com/square/retrofit/pull/2704/files

**Comment by NoMaillard** [comment]
Ah crap... 

thanks for the info !
