### ISSUE TITLE
Please provide a message for this AssertionError

### ISSUE THREAD

**Issue by rupinderjeet** [square/retrofit#2710]
The `onFailure()` method provides a `Throwable` with null message. It is very hard to trace this issue because the JIT compiler will optimize away stack traces in certain exceptions if they happen enough. The JVM flag `-XX:-OmitStackTraceInFastThrow` prevents this behavior and provides stack-traces for such exceptions [as mentioned here](https://stackoverflow.com/a/2070568/3682535).
 
https://github.com/square/retrofit/blob/522592bb11fc8aa1ee491c3e7a1fe55675c372cd/retrofit/src/main/java/retrofit2/RequestBuilder.java#L90-L93

Once the error was visible, it was very easy to trace. Please add a message to suggest user to place `@Path` parameters before `@Query`/`@QueryMap` parameters.

Also, is there any preference in usage order of `@HeaderMap` and `@Path`?

**Comment by JakeWharton** [comment]
Triggering this is a bug. Please provide reproduction steps.

**Comment by rupinderjeet** [comment]
```
@GET("products/{product_id}/similar")
Call<ArrayResponse<SimilarProduct>> fetchSimilarProducts(
    @HeaderMap Map<String, String> headerMap,
    @QueryMap Map<String, Object> paginationMap,
    @Path("product_id") String productId
);
```

Now, if I don't send Pagination QueryMap on the first call to this endpoint, our server API will give me 10 items (the first page). So, paginationMap is empty, and then, not included in Url:

    --> https://xxxxxx.xx/products/1/similar

But, if I want to fetch the second page, I need to send paginationMap. And Url becomes:

    --> https://xxxxxx.xx/products/1/similar?page=2

Retrofit doesn't call this second Url. And, as I mentioned throws the `AssertionError()` silently(?), which is mostly not visible, because `throwable`'s message is null.

I hope you will be able to understand this, I have done a poor job of explaining.

**Comment by JakeWharton** [comment]
Thanks. I'll try to reproduce and see what the underlying cause is.

**Comment by rupinderjeet** [comment]
```
@GET("products/{product_id}/similar")
Call<ArrayResponse<SimilarProduct>> fetchSimilarProducts(
    @HeaderMap Map<String, String> headerMap,
    @Path("product_id") String productId,
    @QueryMap Map<String, Object> paginationMap
);
```

Writing it like this solves it. Thank you for Retrofit.
