### ISSUE TITLE
Retrofit 2.4.0 adding new line character at the end of header string

### ISSUE THREAD

**Issue by naseemrafique** [square/retrofit#2712]
I am using Retrofit v2.4.0, It is adding a new line character in headers which fails my call.

"Authorization: Base dXNlcm5hbWU6cGFzc3dvcmQ=\n"

I have tried static and dynamic headers also interceptors but the result is same.

What is solution for this?

**Comment by JakeWharton** [comment]
Please provide a failing test case or executable sample that demonstrates the problem.

**Comment by naseemrafique** [comment]
@JakeWharton 

It's a simple case of adding Headers in the call. Whenever I try adding header it returns 400 and if I remove headers it return 200 and proper response. After digging into the headers in the request i found out that there is a special character of new line as follows.

"Authorization: Base dXNlcm5hbWU6cGFzc3dvcmQ=\n"

**Comment by JakeWharton** [comment]
Well we have tests that show that we aren't adding newlines so without a failing test case or executable sample I have no way of knowing whether or not your input data contains a trailing newline which I strongly suspect is the underlying cause.

**Comment by naseemrafique** [comment]
@Headers({
            "Authorization: Basic YWRtaW46YWRtaW4xMjM=",
            "Content-Type: application/json"
    })
    @POST("/_search")
    Call<Response> apiCall(@Body PostBody obj, @Query("q") String keyword);

That's how I am providing header.and there are no trailing newline.

**Comment by naseemrafique** [comment]
also this way as well 

@post("/_search")
Call apiCall(@header("Authorization") String authToken, @Body PostBody obj, @query("q") String keyword);

Please see attached screen shots where I have inspected the value. also there is code snippet of the library.


![image](https://user-images.githubusercontent.com/10273459/37870090-09ade6fc-2fe7-11e8-91cf-5e5c427bee00.png)
![image](https://user-images.githubusercontent.com/10273459/37870113-4bdd2556-2fe7-11e8-9187-2363097ac29e.png)

**Comment by vanniktech** [comment]
\n is the trailing whitespace

**Comment by naseemrafique** [comment]
@vanniktech 
yes and if you see the toString method, it is from Headers.java class in Retrofit. Is this causing the real problem?

**Comment by JakeWharton** [comment]
There is no Headers.java in Retrofit. That's from OkHttp and it's debugging output, not what's put on the wire.

**Comment by naseemrafique** [comment]
@JakeWharton 

I am just making a basic authentication token and passing in header field let me know how to pass header in retrofit header if i am doing wrong in above code.

Thakns,

**Comment by naseemrafique** [comment]
@JakeWharton 

Retrofit is using okhttp3 library to manage headers i think I have debugged the code and it is going through okhttp3 library, I have created the following sample please look into it.

[RetroFitTest.zip](https://github.com/square/retrofit/files/1845778/RetroFitTest.zip)

**Comment by naseemrafique** [comment]
any body here???

**Comment by JakeWharton** [comment]
This is not a support forum and Retrofit is not a paid product that
guarantees support. We will look at this potential bug when we have free
time.

**Comment by naseemrafique** [comment]
Well that's rude of you man...

**Comment by JakeWharton** [comment]
I apologize that this software which is entirely open source and provided
to you for no charge that has been worked on by people in their spare time
which promises no support nor provides an SLA of any kind hasn't met your
level of satisfaction and where you were asked for an executable sample or
failing test case such that we could easily reproduce the exact conditions
that you were seeing to quickly diagnose the problem but where you instead
repeatedly commented to draw attention to your issue with neither of those
things and inadequate time periods between them didn't produce the desired
result for you. We remain here to assist you in the future, however.

**Comment by drybly88** [comment]
I have the same problem. Any ideas?

**Comment by SergeyMilewski** [comment]
The same for me.
It happened with the body, I guess cause problem "=" this symbol
