### ISSUE TITLE
Storing data while downloading using retrofit2 and RxJava2

### ISSUE THREAD

**Issue by ParadiseHell** [square/retrofit#2713]
I wanna download a file using Retrofit2 and RxJava2, but it seems that I can only store the file data when I finish downloading.
So I add an interceptor to the OKHttp Client which I can listen to the progress. But it's just the downloading progress, I still cannot store data while downloading except the progress turns to 100.
If the file is small, it's Okay, but if the file is large, I don't think it's a good idea to store data after finishing downloading.
So is there a way to store data while downloading? I have tried to find for a long time in Google but there was nothing mentioned.

**Comment by JakeWharton** [comment]
Use `ResponseBody` as the type and annotate the method as `@Streaming`. This will let your provide progress and stream the data directly to a file with no intermediate buffering.
