### ISSUE TITLE
Facilitate trace propagation with RxJava2

### ISSUE THREAD

**Issue by adriancole** [square/retrofit#2716]
What kind of issue is this?
 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I'm trying to help get tracing working for retrofit. For example, continuing an incoming trace during an retrofit outbound request (including but not limited to SLF4J propagation).

I looked at similar tech https://github.com/akaita/RxJava2Debug and assembly hooks look quite good for this. I started testing and noticed everything works nicely, except when the result type is Observable. That's because observable types are returned as-is:

```java
final class RxJava2CallAdapter<R> implements CallAdapter<R, Object> {
 --snip--
    if (isCompletable) {
      return observable.ignoreElements(); // .ignoreElements indirectly calls RxJavaPlugins.onAssembly
    }
    return observable; // returned with no hooks
  }
```

I understand that a custom adapter could do this, but wondering if we could make it default to use the hook on plain observable.

ex.
```java
final class RxJava2CallAdapter<R> implements CallAdapter<R, Object> {
 --snip--
    if (isCompletable) {
      return observable.ignoreElements();
    }
    return RxJavaPlugins.onAssembly(observable);
  }
```

Open to other ideas to make this drop-in

**Comment by JakeWharton** [comment]
Seems fine to me. PR?

**Comment by artem-zinnatullin** [comment]
👍 

Whenever custom Observable type is instantiated, it should go through `RxJavaPlugins.onAssembly()`

**Comment by adriancole** [comment]
https://github.com/square/retrofit/pull/2721 thx for the quick consideration folks!
