### ISSUE TITLE
java.net.ProtocolException: Expected ':status' header not present

### ISSUE THREAD

**Issue by pinvisible** [square/retrofit#2718]
My app is published and was working fine till today morning.
But suddenly now, it is giving error like,

OkHttp: <-- HTTP FAILED: java.net.ProtocolException: Expected ':status' header not present

i am using below gradel configs..

    compile 'com.squareup.retrofit2:retrofit:2.1.0'
    compile 'com.google.code.gson:gson:2.6.2'
    compile 'com.squareup.retrofit2:converter-gson:2.1.0'
    compile 'com.squareup.okhttp3:logging-interceptor:3.3.1'

is there anything that can be done to prevent republishing app by updating these libraries?

**Comment by JakeWharton** [comment]
This exception comes from OkHttp and not Retrofit so there's nothing this library can do. That being said, your dependencies are easily 1 or 2 years out of date. Please update to the latest and if the problem persists, file a bug with a reproduction case or executable sample on OkHttp.

**Comment by hiteshcla00** [comment]
i am also getting this error but when i update dependencies . then getting this all errors below link
https://stackoverflow.com/questions/50447511/android-when-updating-retrofit-2-9-1-and-okhttp-3-x-x-the-json-converter-library

https://stackoverflow.com/questions/50453522/error-when-trying-to-upgrade-retrofit-library
