### ISSUE TITLE
Bug parsing @Json(name="2")

### ISSUE THREAD

**Issue by Z-13** [square/retrofit#2723]
```
data class MyDataResponse(
	@Json(name="2")
	val content: MyContent
)
```
This code is working good for version 2.3.0 and **content = null** if version 2.4.0!
Why is it so?

**Comment by JakeWharton** [comment]
The dependency on Moshi was probably upgraded and you're getting newer behavior of Moshi. You can either force your build system to use a lower version (which I would not recommend) or consult the Moshi [change log](https://github.com/square/moshi/blob/master/CHANGELOG.md) for any changes it might have made. This isn't a Retrofit bug, though, as Retrofit doesn't know anything about this annotation.
