### ISSUE TITLE
Excess whitespace character - java.net.ProtocolException: Unexpected status line: ' HTTP/1.1 200 OK'

### ISSUE THREAD

**Issue by KursX** [square/retrofit#2724]
```
protected OkHttpClient getHttpClient() {
    OkHttpClient.Builder builder = new OkHttpClient.Builder()
            .addInterceptor(new Cookies())
            .addInterceptor(new Headers());
    return builder.build();
}

protected Retrofit getRetrofit() {
    return new Retrofit.Builder()
            .baseUrl(getBaseUrl())
            .client(getHttpClient())
            .addConverterFactory(GsonConverterFactory.create())
            .build();
}

public interface ApiFiles {
    @GET("api/files/images/{name}")
    Call<ResponseBody> image(@Path("name") String name);
}
```
Bottom code code works correctly but produce memory leak.
After a large number of requests, an exception is thrown
android.system.ErrnoException: connect failed: EMFILE (Too many open files)

```
//works correctly but creates a memory leak after a large number of requests
getRetrofit().create(ApiFiles.class).image("name.jpg").execute();
getRetrofit().create(ApiFiles.class).image("name.jpg").execute(); 
getRetrofit().create(ApiFiles.class).image("name.jpg").execute();
```
This code produce java.net.ProtocolException: Unexpected status line: " HTTP/1.1 200 OK" on second call. 
Extra space at the beginning of the status line

```
ApiFiles call = getRetrofit().create(ApiFiles.class);
call.image("name.jpg").execute();
//next line throws java.net.ProtocolException
call.image("name.jpg").execute();
call.image("name.jpg").execute();

```
Without retrofit everything works correctly

```
//works correctly
OkHttpClient client = getHttpClient();
client.newCall(new Request.Builder().url(getBaseUrl() + "api/files/images/name.jpg").build()).execute();
client.newCall(new Request.Builder().url(getBaseUrl() + "api/files/images/name.jpg").build()).execute();
```

The server receives identical requests and gives identical answers.

If I add "Connection: close" header, everything gets fine

But the server needs to process sequential queries in one close, and this header will increase the load on the server

I think, this is some sort of okhttp problem, when sending requests to the server that does not close the connection after the first request, because after requests to the server that close the connection, such an exception does not thrown.

How to get rid of ProtocolException when using retrofit?

I prepared an android project in which you can repeat and test the problem. Write if necessary

**Comment by droidlomg** [comment]
I think you should only build on ApiFiles instance,  you do not need to create an instance every time you send a request.

**Comment by KursX** [comment]
droidlomg, I'm doing this. The problem is not this
```
ApiFiles call = getRetrofit().create(ApiFiles.class);
call.image("name.jpg").execute();
//next line throws java.net.ProtocolException
call.image("name.jpg").execute();
call.image("name.jpg").execute();
```

**Comment by droidlomg** [comment]
KursX , I haven‘t met this situation yet, but if as you say "If I add "Connection: close" header, everything gets fine" , My sugguestion is: add an interceptor, add header "Connection: close" after you 've get a response. It may be possible to solve the problem temporarily.

**Comment by KursX** [comment]
droidlomg, I can not do this, since I have a large number of consecutive requests when I synchronize data. And the server keeps the connection. If it is interrupted after each request, the server load is unreasonably increased. Now it's easier for me to copy the sources of the retrovit and clean up the extra space manually)
Ideally, I would like the developers of the library to clean up the buffer after processing the request, because I'm sure that the problem is this, but I still can not find where it should be done in order to offer a solution

**Comment by 672009095** [comment]
me to,
i found this issue a week ago after update Android studio, im not sure about this fix, but suddenly work after adding
`.registerTypeAdapterFactory(new YOUR TYPE ADAPTER)`
i put that on gson builder, then use it on converter factory on retrofit builder.
in your code:
```
protected Retrofit getRetrofit() {
return new Retrofit.Builder()
            .baseUrl(getBaseUrl())
            .client(getHttpClient())
            .addConverterFactory(GsonConverterFactory.create())
            .build();
}
```
change into

```
protected Retrofit getRetrofit() {
Gson gson = new GsonBuilder()
                .setLenient()
                .registerTypeAdapterFactory(new ItemTypeAdapterFactory())
                .create();
return new Retrofit.Builder()
            .baseUrl(getBaseUrl())
            .client(getHttpClient())
            .addConverterFactory(GsonConverterFactory.create(gson))
            .build();
}
```

and also check your build tools version,  i use "27.0.3"
i hope this help u
grats!

**Comment by JakeWharton** [comment]
You should not be creating a new instance of your API, Retrofit, and OkHttp constantly. Create a single instance of each and re-use it everywhere. These objects are expensive to create and hold on to resources like sockets and files that you should not rely on the garbage collector to clean up. Adding `Connection: close` just pushes the problem farther out but eventually it will crash the very same way.

**Comment by KursX** [comment]
@JakeWharton , When re-used, an error occurs (java.net.ProtocolException). The problem is precisely this. I do not create a new instance of Retrofit constantly.

```
ApiFiles call = getRetrofit().create(ApiFiles.class);
call.image("name.jpg").execute();
//next line throws java.net.ProtocolException
call.image("name.jpg").execute();
call.image("name.jpg").execute();
```

I noticed that in Retrofit2, unlike OkHttp3, with multiple requests, the response is read from the same Buffer. After the first request, the buffer size is one byte greater than the Content-Length. Because of this, after reading the entire response, there is a byte in the buffer, which is most likely a space. When reading the response to the second request in the same buffer, this space goes to the beginning. There is status line In the beginning. Since the heder is truncated by the \n character, this space is at the top of the status line and throws ProtocolException. It seems to me necessary to clear this buffer after processing of request, or before new request.

**Comment by KursX** [comment]
@JakeWharton, you can repeat this problem yourself

```
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        new Thread(new Runnable() {
            public void run() {
                try {
                    ApiFiles call = getRetrofit().create(ApiFiles.class);
                    call.image("name.jpg").execute();
                    //next line throws java.net.ProtocolException: Unexpected status line:  HTTP/1.1 404 Not Found
                    call.image("name.jpg").execute();
                    call.image("name.jpg").execute();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }).start();

    }

    protected OkHttpClient getHttpClient() {
        OkHttpClient.Builder builder = new OkHttpClient.Builder()
                .addInterceptor(new Interceptor() {
                    public Response intercept(@NonNull Chain chain) throws IOException {
                        Request.Builder builder = chain.request().newBuilder();
                        builder.addHeader("Cookie", "secret_key=80fcfad39216a97f94bb;device_uid=353627079535681;version=android-debug;user_id=79;");
                        return chain.proceed(builder.build());
                    }
                })
                .addInterceptor(new Interceptor() {
                    public Response intercept(@NonNull Chain chain) throws IOException {
                        Request original = chain.request();
                        Request.Builder requestBuilder = original.newBuilder()
                                .header("Timezone", TimeZone.getDefault().getID())
                                .header("Date", getDate())
                                .header("User-Agent", "Android WiseRep Launcher");
                        Request request = requestBuilder.build();
                        return chain.proceed(request);
                    }

                    private String getDate() {
                        return new SimpleDateFormat("EEE, dd MMM yyyy HH:mm:ss Z", Locale.US).format(new Date());
                    }
                });
        return builder.build();
    }

    protected Retrofit getRetrofit() {
        return new Retrofit.Builder().baseUrl(getBaseUrl()).client(getHttpClient()).build();
    }

    public String getBaseUrl() {
        return "https://api.dev1.wise-rep.com/";
    }

    public interface ApiFiles {
        @GET("api/files/slides/videos/covers/{name}")
        Call<ResponseBody> image(@Path("name") String name);
    }
}
```
