### ISSUE TITLE
Internal server Error 500 when calling post method

### ISSUE THREAD

**Issue by vigneshhR** [square/retrofit#2726]
**Login Request:**

`public class LoginRequest {
    @SerializedName("userName")
    @Expose
    public String  username;
    @SerializedName("password")
    @Expose
    public String  password;
      public LoginRequest(String username, String password) {
        this.username = username;
        this.password = password;    
    }
}'

**LoginResponse:**

'public class LoginResponse {
    @SerializedName("UserID")
    @Expose
    public Integer UserID;
    @SerializedName("UserRoleID")
    @Expose
    public Integer UserRoleID; }
public LoginResponse(int userID, int userRoleID) {
        UserID = userID;
        UserRoleID = userRoleID;
}'

**ApiCall**

'public interface LoginApiCall {
@POST("GetUserAuthentication")
 Call<LoginResponse> getDetails(@Body LoginRequest loginRequest ); }'

**Activity**
'Retrofit retrofit = new Retrofit.Builder()
                .baseUrl("url")
                .addConverterFactory(GsonConverterFactory.create())
                .build();
        loginApiCall = retrofit.create(LoginApiCall.class);
        Call<LoginResponse> loginResponseCall = null;
        LoginRequest loginRequest = new LoginRequest(mUsername, mPassword);
        loginResponseCall = loginApiCall.getDetails(loginRequest);'

I get 500 internal server message in response and how to add "application/json" content type in that.

**Comment by JakeWharton** [comment]
The Gson converter you've installed will specify that content type by default.

This is a usage question which is generally more appropriate for StackOverflow. GitHub issues are reserved for bug reports with test cases or samples, or new feature requests. You can use the 'retrofit' tag which is monitored by us and many library users. Feel free to link the asked question back here on the issue.
