### ISSUE TITLE
ErrorHandlingAdapter callback not show toast notification or dialog

### ISSUE THREAD

**Issue by kecoli2** [square/retrofit#2727]
Hi 
I use ErrorHandlingAdapter but on return callback method not show toast notification or dialog 
exception 

I used example ErrorHandlingAdapterFactory 
(https://github.com/square/retrofit/blob/master/samples/src/main/java/com/example/retrofit/ErrorHandlingAdapter.java)

What should I do

java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
at android.os.Handler.(Handler.java:200)
at android.os.Handler.(Handler.java:114)
at android.widget.Toast$TN$2.(Toast.java:343)
at android.widget.Toast$TN.(Toast.java:343)
at android.widget.Toast.(Toast.java:103)
at android.widget.Toast.makeText(Toast.java:262)
at com.example.zzapp.MainActivity$2.onPictureTaken(MainActivity.java:129)
at com.wonderkiln.camerakit.CameraView$CameraListenerMiddleWare.onPictureTaken(CameraView.java:524)
at com.wonderkiln.camerakit.Camera1$3$1.onStillProcessed(Camera1.java:308)
at com.wonderkiln.camerakit.ProcessStillTask.run(ProcessStillTask.java:47)
at java.lang.Thread.run(Thread.java:760)

**Comment by JakeWharton** [comment]
I don't see Retrofit in that stack trace. It very clearly looks like a camera callback that occurs on a background thread and not the main thread.

**Comment by kecoli2** [comment]
So sorry ı am wrong trace paste
I use ErrorHandlingAdapter  callback methot name is "success" 
I want to use dialog notification or toast notification in success method  but OkHttpCall.java class in onResponse method catch.
Just I use only Call<T> class no problem

04-05 16:49:02.194 12015-13534/com.univera.android W/System.err: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
04-05 16:49:02.198 12015-13534/com.univera.android W/System.err:     at android.os.Handler.<init>(Handler.java:200)
04-05 16:49:02.201 12015-13534/com.univera.android W/System.err:     at android.os.Handler.<init>(Handler.java:114)
04-05 16:49:02.203 12015-13534/com.univera.android W/System.err:     at android.app.Dialog.<init>(Dialog.java:151)
04-05 16:49:02.205 12015-13534/com.univera.android W/System.err:     at android.app.Dialog.<init>(Dialog.java:199)
04-05 16:49:02.208 12015-13534/com.univera.android W/System.err:     at com.afollestad.materialdialogs.DialogBase.<init>(DialogBase.java:18)
04-05 16:49:02.210 12015-13534/com.univera.android W/System.err:     at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.java:87)
04-05 16:49:02.212 12015-13534/com.univera.android W/System.err:     at com.afollestad.materialdialogs.MaterialDialog$Builder.build(MaterialDialog.java:2183)
04-05 16:49:02.215 12015-13534/com.univera.android W/System.err:     at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:2188)
04-05 16:49:02.217 12015-13534/com.univera.android W/System.err:     at com.univera.android.MainPagePanoramaMobile$11$1.onsuccess(MainPagePanoramaMobile.java:1139)
04-05 16:49:02.220 12015-13534/com.univera.android W/System.err:     at com.univera.service.univeraOnlineApi.ApiErrorHandlingAdapter$ApiCallAdapter$2.onResponse(ApiErrorHandlingAdapter.java:140)
04-05 16:49:02.222 12015-13534/com.univera.android W/System.err:     at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:123)
04-05 16:49:02.224 12015-13534/com.univera.android W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
04-05 16:49:02.225 12015-13534/com.univera.android W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
04-05 16:49:02.226 12015-13534/com.univera.android W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
04-05 16:49:02.228 12015-13534/com.univera.android W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
04-05 16:49:02.229 12015-13534/com.univera.android W/System.err:     at java.lang.Thread.run(Thread.java:762)

**Comment by JakeWharton** [comment]
This is the same underlying problem. The callbacks happen on a background thread and you're trying to interact with the UI which can only be done on the main thread. Change your implementation to invoke the callbacks on the main thread or post to the main thread from within the callback.
