### ISSUE TITLE
Avoid Retrofit model class redundancy

### ISSUE THREAD

**Issue by mtariquekhan** [square/retrofit#2729]
Let's say I have three parameters in my model class which I want to send in retrofit request
1. String a
2. String b
3. boolean c 

in my first request I need all three parameters so it looks fine but when If in my request, I want 1 and 2 parameters then my third parameter becomes false by default in the request payload which I don't want. How can I avoid this ?

**Comment by JakeWharton** [comment]
This sounds like something that occurs with `@Body` and JSON which Retrofit has no control over. That behavior is entirely up to your chosen serialization library. You should consult its documentation or StackOverflow for assistance.

But likely the answer is to use a Boolean not boolean.
