### ISSUE TITLE
SimpleXmlConverterFactory deprecated without replacement for Android

### ISSUE THREAD

**Issue by hameno** [square/retrofit#2733]
I just noticed after upgrading to 2.4 on my Android project that the SimpleXmlConverterFactory is now deprecated and it suggests using JAXB while on the JAXBConverter page it says it does not support Android. This means, that there is now no "supported" XML converter for Android.
I would suggest rethinking the deprecation of the SimpleXmlConverterFactory.

**Comment by JakeWharton** [comment]
Deprecated doesn't mean non-functional. You're free to continue using it.

It was deprecated because Simple XML is a dead library with CVEs. If you'd like an alternative that works on Android consider https://github.com/Tickaroo/tikxml.

**Comment by hameno** [comment]
Good to know, will look into switching. Thanks :)

**Comment by VikiVignesh026** [comment]
Is there any example implementation for Tickaroo In android. We followed their documentation, but we end up in a issue saying "No TypeAdapter found" on using it with retrofit.

**Comment by lukechi1219** [comment]
@VikiVignesh026 
Does your pojo has inner class? I also encountered "No TypeAdapter found" when trying TikXml, then I found TikXml's AutoValueTypeAdapterCodeGenerator didn't handle inner class well. After I change inner classes to separate classes, TikXml works well for me.

Following is my code adding tikXmlConverterFactory into Retrofit.Builder.

new Retrofit.Builder()
                .addConverterFactory(tikXmlConverterFactory)
                .addCallAdapterFactory(rxJava2CallAdapterFactory)
                .client(okHttpClientForXml)
                .baseUrl(baseUrl)
                .build();

https://github.com/lukechi1219/HelloDagger/blob/master/app/src/main/java/com/lukechi/android/hellodagger/factory/CustomRetrofitFactory.java

**Comment by sbeve72** [comment]
Can Jackson be used in place of it?

**Comment by durgeshrjkumar** [comment]
does tikxml works with pojo classes generated by jaxb compiler?

**Comment by newmanw** [comment]
https://github.com/Tickaroo/tikxml seems dead as well.   Last release 5 years ago w/ many issues and PRs outstanding.  Is this still the "recommended" xml parser when using retrofit on Android?

**Comment by georrge1994** [comment]
Any updates? Some backend still continue to use it and we still don't have a nice shoot solution
