### ISSUE TITLE
Feature Request: Create Retrofit on custom process for network binding

### ISSUE THREAD

**Issue by felislynx-silae** [square/retrofit#2738]
Hi, i'm developing application on Android Things. 

Raspberry Pi3 have both LAN and WiFi, so in theory i'm able to use LAN to communicate with Network1 and WiFi to communicate with Network2.
Since Android doesn't provide easy way to connect to both LAN and WiFi (only one network is binded to main process), I've found that i could use this method from ConnectivityManager: connectivitymanager.bindProcessToNetwork(network2); to achieve that.

This would bind current process to specific network. Retrofit is running on default android process. So i would love to see a feature where i could choose on which process Retrofit is created and by that, bind it with specific network.

**Comment by JakeWharton** [comment]
Retrofit runs inside _your_ process so it's not clear why you cannot call this method yourself.

Also Retrofit doesn't make network connections, that's OkHttp. Retrofit is just a fancy of way to create an HTTP request and ask it to be executed using your preferred asynchronous library of choice.

**Comment by felislynx-silae** [comment]
In android "your process" would be default application process. Which means, calling bind results in switching whole application into specific network. Where i would like to be able to call over LAN and WiFi. So when i call retrofit.create(), i wanted to choose which process is chosen for this call. If you think, that i should go and ask OkHttp, because this feature is on their side, then i will :).

**Comment by JakeWharton** [comment]
All work is done in the calling process. If you want a separate process to make network calls you'll have to manage that yourself with something like a service and a named process.

**Comment by AafaaqAli** [comment]
@JakeWharton really helpful feedback, thanks :)
