### ISSUE TITLE
@QueryMap can not process null values for keys

### ISSUE THREAD

**Issue by genxlogics** [square/retrofit#2741]
Hi,
I am using retrofit2 : 2.3.0
I am passing a HashMap as below which include null values for two params. i am getting error as "java.lang.IllegalArgumentException: Query map contained null value for key &#39;client_number&#39;.

both "passport" and "client_number" are null values.

`HashMap<String, String> ids = new HashMap<>();
            ids.put("rsa_id_value", id);
            ids.put("passport_number", passport);
            ids.put("client_number", clientNumber);
            Response<List<QuoteEligibility>> response = mstiService.getEligibility(ids).execute();`

interface defined as 

`@GET("personal/eligibility")
    Call<List<QuoteEligibility>> getEligibility(@QueryMap(encoded = true) Map<String,String> options);`

**Comment by NightlyNexus** [comment]
What would be your expected behavior? Add the name without a value to the query string?

**Comment by NightlyNexus** [comment]
which seems a reasonable request to me.

**Comment by genxlogics** [comment]
i would expected retrofit to not process any key which has a null/empty
value.

**Comment by genxlogics** [comment]
According to Retrofit documentation, QueryMap will not process the keys for which values are null.
@JakeWharton ,
please help !!

**Comment by genxlogics** [comment]
this is what ParameterHandler.java has regarding the QueryMap.
`T entryValue = entry.getValue();
        if (entryValue == null) {
          throw new IllegalArgumentException(
              "Query map contained null value for key '" + entryKey + "'.");
        }`
seems that null values can not be bypassed.

however as per retrofit book +

How to Use QueryMap
The @QueryMap annotation expects a standard Java Map implementation with key-value-pairs of type String. Each key which has a non-null value will be mapped and you can dynamically add your desired query parameters.
1 public interface TaskService() {
2     @GET("tasks")
3     Call<List<Task>> getTasks(
4         @QueryMap Map<String, String> options
5     );
6 }
If you want to request the tasks for Marcus from page 2, you only need to add the map entries for page and owner. There’s no need to worry about the other available options (taskId, order).
The resulting url with the assumed example (page 2 of Marcus):
1 tasks?page=2&owner=Marcus


@NightlyNexus @da3mon @eventualbuddha @codebutler @JakeWharton 

any idea how to get through this?

**Comment by daleiyinsi** [comment]
I also met this problem

**Comment by genxlogics** [comment]
@NightlyNexus @JakeWharton 
Is there anybody looking at it? Can I add this fix?
This issue is causing me to add a lot of work around.

To allow an empty QueryMap so that no query-params are added in the URL and URL appears without any query parameter.
There are few rest apis i am using which allow query-parameters to be absent at all..

Say I have two query params to list my acticity for a given period (from and to)
the api I use looks like this http://host/users/1212121/activities?from=2018&to=2019

now they return last month data if no query is provided so the URL we pass to them appears as

http://host/users/1212121/activities

using QueryMap is causing issues for me when my Map is empty.

possible solution to is to add a flexibility through @QueryMap annotation property to allow empty map
something like that
@GET("userscore/{clientNumber}/fitness_assessment")
	Call<List<Activity>> getUserActivities(@Path("clientNumber") String clientNumber, @QueryMap(nullAllowed=true) Map<String, String> options) ;

so, validation can be bypassed if nullAllowed=true

Can I patch this fix?

**Comment by swankjesse** [comment]
I think our current behavior is least surprising. If our documentation doesn't agree with the code I'd like to change the documentation.

If you want to include a query parameter, put a value in the map?

**Comment by genxlogics** [comment]
Hi @swankjesse ,
my issue is that the rest call that I make through Retrofit allows no query parameter.
Now, I have two options to make this dynamic call where query parameter may be present or may all be absent, yielding into a URI without query params (/activities)
As of now,
my work around is to add one more  GET /activities so that I can make the call when there is no query parameter.
I was hoping something like

<pre><code>
  &#64;GET("/friends")
 Call&lt;ResponseBody&gt; friends(@QueryMap(nullAllowed=true,) Map&lt;String, String&gt; filters);
 </code></pre>
So,
Calling with {@code foo.list(new HashMap<>())} yields
 * {@code /friends}.

**Comment by JakeWharton** [comment]
An empty collection is very different than one containing null. What you
wrote should already work.
