### ISSUE TITLE
If Rxjava cancels the subscription before sending the request if it can't find DNS, then immediately enter or request again. The second subscription will be blocked.

### ISSUE THREAD

**Issue by HaiChecker** [square/retrofit#2743]
If Rxjava cancels the subscription before sending the request if it can't find DNS, then immediately enter or request again. The second subscription will be blocked.

**Comment by JakeWharton** [comment]
Retrofit doesn't know anything about DNS. It asks for the request to be executed and then cancels it if you cancel. So this either needs a test case proving that it's an Retrofit issue (which is unlikely) or the problem lies at a lower layer (like OkHttp).
