### ISSUE TITLE
Call is enqueued not invoked

### ISSUE THREAD

**Issue by zenglian** [square/retrofit#2745]
- [x] Bug report. 

In below code, the callback is not invoked if the last line is commented out. If the last line is uncommented, then callback is executed.

execute() below is working fine with logs.

Shall I explicitly make another invoke for enqueue() as the method name implies is enqueued only?

```
        RequestBody body = RequestBody.create(MediaType.parse("application/octet-stream"), new File(fileName));
        Call<DataResult> call = service.uploadData("yyy", body);
        call.enqueue(new Callback<DataResult>() {
            @Override
            public void onResponse(Call<DataResult> call, Response<DataResult> response) {
                System.out.println(response.body());
            }

            @Override
            public void onFailure(Call<DataResult> call, Throwable throwable) {
                throwable.printStackTrace();
            }
        });
        //service.uploadData("yyy", body).execute().body();

```

**Comment by JakeWharton** [comment]
If you are running this code in something like a main method you'll have to either block the calling thread with a sleep or a count-down latch to wait for the background thread to deliver a result.

**Comment by zenglian** [comment]
it's called in a test. 
something like `call.join()` will help.

**Comment by JakeWharton** [comment]
I don't think that is our responsibility to provide, and I'm even more worried about its use outside of a test environment to block a thread when the consumer of Retrofit doesn't understand what's happening.
