### ISSUE TITLE
Excess whitespace character - java.net.ProtocolException

### ISSUE THREAD

**Issue by KursX** [square/retrofit#2748]
I noticed that in Retrofit2, unlike OkHttp3, with multiple requests, the response is read from the same Buffer. After the first request, the buffer size is one byte greater than the Content-Length. Because of this, after reading the entire response, there is a byte in the buffer, which is most likely a whitespace. When reading the response to the second request in the same buffer, this whitespace goes to the beginning. There is status line In the beginning. Since the header is truncated by the \n character, this space is at the top of the status line and throws ProtocolException. It seems to me necessary to clear this buffer after processing of request, or before new request.

You may try it. Maybe I'm doing something wrong?

```
public class MainActivity extends AppCompatActivity {

    private OkHttpClient httpClient;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        new Thread(new Runnable() {

            public void run() {
                try {
                    //works correctly
                    OkHttpClient client = getHttpClient();
                    client.newCall(new Request.Builder().url(getBaseUrl() + "api/files/slides/videos/covers/name.jpg").build()).execute();
                    client.newCall(new Request.Builder().url(getBaseUrl() + "api/files/slides/videos/covers/name.jpg").build()).execute();


                    ApiFiles call = getRetrofit().create(ApiFiles.class);
                    call.image("name.jpg").execute();
                    //next line throws java.net.ProtocolException: Unexpected status line: ' HTTP/1.1 500 Internal Server Error'
                    call.image("name.jpg").execute();
                    call.image("name.jpg").execute();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }).start();
    }

    public String getBaseUrl() {
        return "https://api.dev1.wise-rep.com/";
    }

    protected Retrofit getRetrofit() {
        return new Retrofit.Builder()
                .baseUrl(getBaseUrl())
                .client(getHttpClient())
                .build();
    }

    public OkHttpClient getHttpClient() {
        return new OkHttpClient.Builder().build();
    }

    public interface ApiFiles {
        @GET("api/files/slides/videos/covers/{name}")
        Call<ResponseBody> image(@Path("name") String name);
    }
}
```

**Comment by JakeWharton** [comment]
I cannot reproduce with this test:
```java
public final class CallTest {
  @Rule public final MockWebServer server = new MockWebServer();

  interface Service {
    @GET("/") Call<String> getString();
  }

  @Test public void whevs() throws IOException {
    server.enqueue(new MockResponse()
        .setResponseCode(500)
        .setBody("{\"exception\":{},\"request\":{},\"message\":\"Incorrect secret key\",\"status\":\"error\"}"));
    server.enqueue(new MockResponse()
        .setResponseCode(500)
        .setBody("{\"exception\":{},\"request\":{},\"message\":\"Incorrect secret key\",\"status\":\"error\"}"));
    server.enqueue(new MockResponse()
        .setResponseCode(500)
        .setBody("{\"exception\":{},\"request\":{},\"message\":\"Incorrect secret key\",\"status\":\"error\"}"));

    Retrofit retrofit = new Retrofit.Builder()
        .baseUrl(server.url("/"))
        .addConverterFactory(new ToStringConverterFactory())
        .build();
    Service example = retrofit.create(Service.class);

    assertEquals(500, example.getString().execute().code());
    assertEquals(500, example.getString().execute().code());
    assertEquals(500, example.getString().execute().code());
  }
```
If you can provide a failing test case I'm happy to take a look but unless I can reproduce the behavior

**Comment by JakeWharton** [comment]
MockWebServer is a real server. If I can't reproduce it with MockWebServer
then I can't write a test to prevent regression, assuming it's actually a
bug and not a broken web server.

**Comment by KursX** [comment]
@JakeWharton 
java.net.ProtocolException: Unexpected status line: ' HTTP/1.1 500 Internal Server Error'
Here, from somewhere, a whitespace is taken, which should not be.
The problem in the whitespace before the HTTP in status line, and not in the response code
When using okhttp everything works fine, so this is not a server problem

**Comment by JakeWharton** [comment]
The server reports a content length of 79:

![screen shot 2018-05-02 at 10 08 04 am](https://user-images.githubusercontent.com/66577/39527941-c20250a4-4df0-11e8-905f-5286d60a7d84.png)

But sends 80:

![screen shot 2018-05-02 at 10 07 43 am](https://user-images.githubusercontent.com/66577/39527954-cc15dfb6-4df0-11e8-8de1-c94a1b625655.png)

Note the trailing whitespace.

**Comment by KursX** [comment]
@JakeWharton, could it be right to clear the buffer after processing the response, that extra characters were not used for the following queries?
Okhttp creates new buffer for each response, but Retrofit is not

**Comment by KursX** [comment]
@JakeWharton, last question. Why in the code of my question in repeated calls through okhttp the problem does not repeat? Only when using Retrofit
Thank you

**Comment by JakeWharton** [comment]
You aren't consuming the response body before executing the next call so
OkHttp is forced to open a new connection. Close the response body (which
consumes it in its entirety) before executing the next call and you'll see
the same behavior.
