### ISSUE TITLE
 Unable to create call adapter for interface retrofit2.Call for method Interface.Login

### ISSUE THREAD

**Issue by 143Deepu** [square/retrofit#2755]
Interface:

`   @FormUrlEncoded
    @POST
    Call Login(@Field("method") String method,@Field("email") String username, @Field("password") String password);
`
ApiClient:

`    HttpLoggingInterceptor  interceptor=new HttpLoggingInterceptor();
        interceptor.setLevel(HttpLoggingInterceptor.Level.BODY);
        OkHttpClient client=new  OkHttpClient.Builder().addInterceptor(interceptor).build();
        retrofit =new Retrofit.Builder()
            .baseUrl("http://api.hallohours.in/api/login/")
                .addConverterFactory(GsonConverterFactory.create())
                .client(client)
                .build();
        return retrofit;`

Main_Acticity:

`  email = User_email.getText().toString();
                password = User_password.getText().toString();

                try {

                    Interface service = ApiClient.getClient().create(Interface.class);
                    Call call = service.Login("POST",email, password);
                    call.enqueue(new Callback() {
                        @Override
                        public void onResponse(Call call, Response response) {
                            if (response.isSuccessful()) {
                                ResObj resObj= (ResObj) response.body();
                                assert resObj != null;
                                if (resObj.getMessage().equals(true)){
                                    Intent intent = new Intent(MainActivity.this, MainPg.class);
                                    startActivity(intent);

                                }
                            } else {
                                Toast.makeText(MainActivity.this, "The Email or password is incorrect", Toast.LENGTH_SHORT).show();
                            }

                        }

                        @Override
                        public void onFailure(Call call, Throwable t) {
                            Toast.makeText(getApplicationContext(),"Faild!!!!!!",Toast.LENGTH_LONG).show();

                        }
                    });
                } catch (Exception e) {

                    Toast.makeText(getApplicationContext(),"Error!!!!", Toast.LENGTH_LONG).show();
//                    Log.e("TAG", toString(e));
//                    Log.e("MYAPP", "exception: " + e.getMessage());
//                    Log.e("MYAPP", "exception: " + e.toString());
                    Log.e("TAG","exception",e);

                }

            }
        });
`

Error:
1. java.lang.IllegalArgumentException: Unable to create call adapter for interface retrofit2.Call
        for method Interface.Login
2.     Caused by: java.lang.IllegalArgumentException: Call return type must be parameterized as Call<Foo> or Call<? extends Foo>

**Comment by roufalnewage** [comment]
### 

> [`_****_`](

- 

@ # @

- [ ] 

1. url

)
