### ISSUE TITLE
Android Studio builded failed if adding proguard options in README.md

### ISSUE THREAD

**Issue by HenryChao24** [square/retrofit#2756]
Android Studio builded failed if adding following proguard options:
`-keepclassmembernames,allowobfuscation interface * {
    @retrofit2.http.* <methods>;
}`

No modifier should be added following keepclassmembernames as the manual writes below:
[https://www.guardsquare.com/en/proguard/manual/usage#keepclassmembernames](url)

**Comment by JakeWharton** [comment]
Yeah I think it's supposed to be `-keepclassmembers,allowobfuscation`.

Here's the message from Eric Lafortune:
```
-keepclassmembers,allowshrinking,allowobfuscation interface * {
    @retrofit2.http.** <methods>;
}
```

**Comment by HenryChao24** [comment]
@technoir42 Thanks. 
It's a workaround below.
`-keepclassmembers,allowshrinking,allowobfuscation interface * {
    @retrofit2.http.** <methods>;
}`
