### ISSUE TITLE
How to send file along with Java Object using @Multipart

### ISSUE THREAD

**Issue by Vijaykumarj** [square/retrofit#2760]
I want upload a file along with Java object using Multipart.  In this java object have more than 10 members.
Any one guide to me, how i can achieve this one.

**Comment by AtulSandilya** [comment]
I have the same issue , i am trying to pass a RequestBody of java model and a image file , 
i can not use i tried using @part it is asking a key , i can not send that , i tried it with @PartMap but getting the error hash validation failed , and for using hashmap i am doing recursion process , first creating json string and then encryption and then converting to hashmap , please help if there is any simple possible way to do it

**Comment by JakeWharton** [comment]
@Vijaykumarj Sounds like you want two `@Part`s, one which is a `MultipartBody.Part` for a file and the other which is a JSON model type that goes through a converter.

Is this not working?

**Comment by TwinsOd** [comment]
I have the same issue, I want to send a difficult object, but this impossible
