### ISSUE TITLE
Getting two different response code for single Request.

### ISSUE THREAD

**Issue by The-RobinHood** [square/retrofit#2761]
When I make request call it first comes inside  _intercept_ where I get response code **403** and then it comes into _network request response_ where I receive response code **401**, why there two different response code for single API call? and does API get call twice?

**RestClient.java**
    

    public class RestClient {
    public static int LANGUAGE_CODE_ENGLISH = 1033;
    public static int LANGUAGE_CODE_SWEDISH = 1053;
    public static String ENGLISH = "eng";
    public static String SWEDISH = "swe";
    private int langauge_code;

    public static int DEFAULT_TIMEOUT = 0; // 60 seconds

    private static final String TAG = RestClient.class.getSimpleName();

    private static RestClient restClient;
    private Retrofit retrofit;

    public static RestClient getInstance() {
        if (restClient == null) {
            restClient = new RestClient();
        }
        return restClient;
    }

    public ApiInterface getApiInterface() {
        return getRetrofitInstance().create(ApiInterface.class);
    }

    private Retrofit getRetrofitInstance() {
        if (retrofit == null) {
            Gson gson = new GsonBuilder()
                    .registerTypeAdapter(Date.class, new JsonDeserializer<Date>() {
                        public Date deserialize(JsonElement json, Type type, JsonDeserializationContext context) throws JsonParseException {
                            return new Date(json.getAsJsonPrimitive().getAsLong());
                        }
                    })
                    .setPrettyPrinting()
                    .create();

            retrofit = new Retrofit.Builder()
                    .baseUrl(HpcConstants.WS_URL)
                    .addConverterFactory(GsonConverterFactory.create(gson))
                    .client(getHeader())
                    .build();
        }
        return retrofit;
    }

    public OkHttpClient getHeader() {
        final AppPreferences appPreferences = new AppPreferences(MyApplication.getAppInstance());

        /**for localization**/
        String lang = Locale.getDefault().getISO3Language();
        if (lang.equalsIgnoreCase(SWEDISH)) {
            langauge_code = LANGUAGE_CODE_SWEDISH;
        } else {
            langauge_code = LANGUAGE_CODE_ENGLISH;
        }

        HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
        interceptor.setLevel(HttpLoggingInterceptor.Level.BODY);
        OkHttpClient okClient = new OkHttpClient.Builder()
                .readTimeout(DEFAULT_TIMEOUT, TimeUnit.MILLISECONDS)
                .connectTimeout(DEFAULT_TIMEOUT, TimeUnit.MILLISECONDS)
                .writeTimeout(DEFAULT_TIMEOUT, TimeUnit.MILLISECONDS)
                .addInterceptor(interceptor)
                .addInterceptor(
                        new Interceptor() {
                            @Override
                            public Response intercept(Interceptor.Chain chain) throws IOException {
                                Request request;
                                Request original = chain.request();
                                okhttp3.Response response = chain.proceed(original);
                                **Here I received response code 403** 

                                // Request customization: add request headers

                                Request.Builder requestBuilder = original.newBuilder();
                                if (!TextUtils.isEmpty(appPreferences.getSessionKey())) {
                                    requestBuilder.addHeader(RequestParameters.AUTHORIZATION, appPreferences.getSessionKey());
                                    requestBuilder.addHeader(RequestParameters.LANGUAGE_ID, String.valueOf(langauge_code));
                                }

                                request = requestBuilder.build();
                                return chain.proceed(request);
                            }
                        })
                .build();
        return okClient;
        }
    }

**Netwrok Request Call**

                        
           public void activityLogRequest(int ActivityId, int itemId, int itemType) {
        if (Utils.isNetworkAvailable(BaseActivity.this)) {
            Call<ActionModel> call = 
             RestClient.getInstance(BaseActivity.this).getApiInterface().activityLogWS(new 
             ActivityLogRequest(ActivityId, itemId, itemType));
            call.enqueue(new Callback<ActionModel>() {
                @Override
                public void onResponse(@NonNull Call<ActionModel> call, @NonNull 
                Response<ActionModel> response) {
                    Log.e(TAG, "onResponse: ");
                  **Here I'm getting response code 401** 
                    if (response.isSuccessful()) {
                        ActionModel result = response.body();
                        if (result != null) {
                            Log.e(TAG, "onResponse: " + result.data);
                        }
                    } else {
                        try {
                            if (!TextUtils.isEmpty(response.errorBody().string())) {
                                String error = response.errorBody().string();
                                Log.e(TAG, "onResponse: error=" + error);
                            }
                        } catch (IOException e) {
                            e.printStackTrace();
                        }
                    }

                }

                @Override
                public void onFailure(@NonNull Call<ActionModel> call, @NonNull Throwable t) {
                    Log.e(TAG, "onFailure: " + t.getMessage());
                }
            });
        } else {
            Log.e(TAG, "no_internet");
        }
    }`

**Comment by JakeWharton** [comment]
These response codes come from your server. Retrofit doesn't control or affect this aside from sending the requests in the form you dictate. You'll have to consult your server team or the API documentation to discern the underlying cause.

**Comment by The-RobinHood** [comment]
I consult with the server team and they are claiming that API has been called twice from my end, whats your view? does my code is okay?

**Comment by The-RobinHood** [comment]
Grab the issue! Its chain.proceed() which called Api implicitly 2nd time.
