### ISSUE TITLE
SimpleXML Converter - Lint Problems when generating Signed apk (release)

### ISSUE THREAD

**Issue by ioannisa** [square/retrofit#2763]
Hi, I noticed something when using the SimpleXML Converter library...

1. Create an empty project
2. Add **implementation 'com.squareup.retrofit2:converter-simplexml:2.4.0'** dependency.
3. Generate a Signed APK (release)

Outcome: Lint Problem

When using this library in a project, Lint will produce DuplicatePlatformClasses Error when you attempt to build a signed-release apk:

This error can be located at your android project in the following path/file:
app/build/reports/lint-results-release-fatal.html

(This error occurs only with "release" signed apk, and not (obviously) with "debug" signed apk generation)

The only solution is to ask Lint to exclude only the DuplicatePlatformClasses errors from its checks like that

```
lintOptions {
    disable 'DuplicatePlatformClasses'
}
```

P.S. Error doesn't occur if min-sdk is set to 23

**Comment by JakeWharton** [comment]
This is a problem with the simple XML library and not the converter itself which contains no duplicate platform classes. My best guess would be that the library contains transitive dependencies which are bundled into the Android platform which you can exclude. I would seek assistance from the Simple XML library directly or on StackOverflow where those familiar with the library will be able to assist. Retrofit only has an integration (which is actually deprecated) and we aren't well versed in the library.
