### ISSUE TITLE
How to post object parameters ? 

### ISSUE THREAD

**Issue by ismailtosun** [square/retrofit#2764]
My parameters look like this : 
```
Request
{
                "ProcName" :"BR_SP_BRN_GET_STORE_ACTIVE_SHIPMENTS",
                "Parameters": [
    {
      "Name": "StoreCode",
      "Value": "B201"
    }
  ]
}

```

**Comment by dangets** [comment]
Check out this gist showing basic usage of Retrofit with json body
https://gist.github.com/dangets/66dd7bed4b5babaa8cc6d6b7336ba76a

That example uses Moshi and retrofit converter-moshi, but there are converters for gson or jackson if you are already using other serializers.

**Comment by JakeWharton** [comment]
This is a usage question which is generally more appropriate for StackOverflow. GitHub issues are reserved for bug reports with test cases or samples, or new feature requests. You can use the 'retrofit' tag which is monitored by us and many library users. Feel free to link the asked question back here on the issue.
