### ISSUE TITLE
Cannot access class 'retrofit2.Retrofit'. Check your module classpath for missing or conflicting dependencies,use retrofit2 with kotlin 

### ISSUE THREAD

**Issue by zaxcler** [square/retrofit#2766]
i'm use retrofit2 with kotlin,here is the problem

Cannot access class 'retrofit2.Retrofit'. Check your module classpath for missing or conflicting dependencies

here is my dependencies tree

debug
debugCompileClasspath - Dependencies for compilation
+--- com.android.databinding:adapters:3.1.2@aar
+--- com.android.databinding:library:3.1.2@aar
+--- com.android.databinding:baseLibrary:3.1.2@jar
+--- com.android.support:appcompat-v7:26.1.0@aar
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.2.31@jar
+--- com.squareup.retrofit2:adapter-rxjava2:2.3.0@jar
+--- com.squareup.retrofit2:converter-gson:2.3.0@jar
+--- com.squareup.retrofit2:retrofit:2.3.0@jar
+--- com.squareup.okhttp3:logging-interceptor:3.9.0@jar
+--- io.reactivex.rxjava2:rxandroid:2.0.1@aar
+--- io.reactivex.rxjava2:rxkotlin:2.1.0@jar
+--- com.orhanobut:logger:1.15@aar
+--- com.scwang.smartrefresh:SmartRefreshLayout:1.0.4-7@aar
+--- com.android.support:recyclerview-v7:26.1.0@aar
+--- com.orhanobut:hawk:2.0.1@aar
+--- com.contrarywind:Android-PickerView:3.2.7@aar
+--- com.tbruyelle.rxpermissions2:rxpermissions:0.9.5@aar
+--- com.facebook.stetho:stetho-okhttp3:1.5.0@aar
+--- com.facebook.stetho:stetho:1.5.0@aar
+--- com.android.support:support-v4:26.1.0@aar
+--- com.android.support:support-fragment:26.1.0@aar
+--- com.android.support:support-core-utils:26.1.0@aar
+--- com.android.support:animated-vector-drawable:26.1.0@aar
+--- com.android.support:support-vector-drawable:26.1.0@aar
+--- com.android.support:support-core-ui:26.1.0@aar
+--- com.android.support:support-media-compat:26.1.0@aar
+--- com.android.support:support-compat:26.1.0@aar
+--- android.arch.lifecycle:runtime:1.0.3@aar
+--- android.arch.lifecycle:common:1.0.3@jar
+--- android.arch.core:common:1.0.0@jar
+--- com.android.support:support-annotations:26.1.0@jar
+--- org.jetbrains.kotlin:kotlin-stdlib:1.2.31@jar
+--- com.squareup.okhttp3:okhttp:3.9.0@jar
+--- io.reactivex.rxjava2:rxjava:2.1.0@jar
+--- com.google.code.gson:gson:2.7@jar
+--- com.facebook.conceal:conceal:1.1.3@aar
+--- commons-cli:commons-cli:1.2@jar
+--- com.google.code.findbugs:jsr305:2.0.1@jar
+--- com.squareup.okio:okio:1.13.0@jar
+--- org.reactivestreams:reactive-streams:1.0.0@jar
\--- org.jetbrains:annotations:13.0@jar

**Comment by JakeWharton** [comment]
This is a build system or IDE problem and not a problem with Retrofit. That class is inside the Retrofit jar so I'm not sure what to tell you. You might have better luck on StackOverflow with a much more detailed description of your build system setup and any relevant IDE configuration.

**Comment by zaxcler** [comment]
thanks
