### ISSUE TITLE
I need [{},{},{}] instead of ["{}","{}","{}"]

### ISSUE THREAD

**Issue by Whatgbc** [square/retrofit#2768]
@FormUrlEncoded
    @POST(url)
    Observable<Object> getOrderDetailData(@FieldMap Map<String,String> map,@Field("data[]") List<DetailEntity> list);

and log shows "data" is ["{t.tostring}","{t.tostring}","{t.tostring}"], I don't need quotation, what should I  do

**Comment by JakeWharton** [comment]
Please provide a failing test case that includes the expected body format. There's a link to get you started in the issue template. It sounds like you want JSON and not form encoding.

**Comment by Whatgbc** [comment]
em..php server is different than others.
