### ISSUE TITLE
baseUrl must end with slash "/" however need to call index.php?/api....

### ISSUE THREAD

**Issue by hanasaki** [square/retrofit#2770]
working with retrofit to call the testrail API's   however getting an error that the base url must end with a slash.
TestRail api and docs below.   Notice where the "?" is.

http://docs.gurock.com/testrail-api2/reference-tests
GET index.php?/api/v2/get_tests/:run_id

**Comment by JakeWharton** [comment]
Add a `/` to the end of http://docs.gurock.com/testrail-api2/reference-tests to make http://docs.gurock.com/testrail-api2/reference-tests/.

**Comment by hanasaki** [comment]
the docs URL is the URL for the doc... provided for your reference.
The issue is with the GET url give .......index.php?/api/v2/get_tests/5

**Comment by hanasaki** [comment]
the docs URL is the URL for the doc... provided for your reference.
The issue is with the GET url give .......index.php?/api/v2/get_tests/5

see the "?" with no preceding "/"  ????  and the server will only take 
it this way

**Comment by JakeWharton** [comment]
That's the relative URL not the base URL. It is not required to start with a slash (although it can if you want it to be an absolute URL _relative_ to the base URL).

Did you read the [base URL docs][1]?

 [1]: http://square.github.io/retrofit/2.x/retrofit/retrofit2/Retrofit.Builder.html#baseUrl-okhttp3.HttpUrl-

**Comment by hanasaki** [comment]
so how can retrofit be used to call API's like
GET http://myhost/index.php?/api/v2/get_tests/{run_id}

The server requires no slash before the ? (which is valid URL syntax)  and retrofit requires the slash.

**Comment by JakeWharton** [comment]
The base URL is `http://myhost/` and the relative URL is `index.php?/api/v2/get_tests/{run_id}`.

**Comment by hanasaki** [comment]
So in this case, the {run_id} becomes a dynamic part of the "query" since it is after the "?".  @query or @querymap are appended after a "?" that retrofit/okhttp adds are done so with key=value.  This URL pattern requires JUST the run_id substitution in the query portion.   How can this be accomplished?

**Comment by JakeWharton** [comment]
True. That would be unsupported then. You can use the relative URL for the portion after the `?` and then use an OkHttp interceptor to rewrite the URL to prepend the `index.php?` portion. Otherwise, Retrofit doesn't support this case aside from normal query parameter manipulation.

**Comment by jaydipumaretiya** [comment]
Can you give an example of this? How I can use that one with the `index.php?`.
