### ISSUE TITLE
MTProto Proxy

### ISSUE THREAD

**Issue by LegendaryCoders** [square/retrofit#2775]
Hi . Tnx for this great lib.
Can i add MTProto Proxy in OkHttpClientBuilder Like Telegram ? How?
And How Can i find a proxy auto?

How Can i check the proxy is available ?

**Comment by JakeWharton** [comment]
This is a usage question which is generally more appropriate for StackOverflow. GitHub issues are reserved for bug reports with test cases or samples, or new feature requests. You can use the 'retrofit' tag which is monitored by us and many library users. Feel free to link the asked question back here on the issue.
