### ISSUE TITLE
The enqueue call is made on a background thread and after that onResponse is not triggered. but okHttp shows the request is completed successfully.

### ISSUE THREAD

**Issue by dimpybadra** [square/retrofit#2780]
The enqueue call is made on a background thread and after that onResponse is not triggered.
but okHttp shows the request is completed successfully.
public static void gettabData(final NetworkOperationListener<OpShiftModel[]> listener) {

        Call<OpShiftModel[]> tabCall = opShiftService.getTabData(getAuthHeader());
        tabCall.enqueue(new Callback<OpShiftModel[]>() {

            @Override
            public void onResponse(Call<OpShiftModel[]> call, Response<OpShiftModel[]> response) {
                try {
                    listener.onSuccess(response.body());
                } catch (NullPointerException e) {
                    onFailure(call, e);
                }
            }

            @Override
            public void onFailure(Call<OpShiftModel[]> call, Throwable throwable) {

            }
        });}
http request is successfull.

**Comment by swankjesse** [comment]
This bug report isn't actionable. Please provide an executable test case.

**Comment by afunnyrainman** [comment]
I met the problem, too.  
I found the reason because I encapsulated it
public abstract class BaseRxObser<T> implements Observer<T> {
    static CompositeDisposable compositeDisposable = new CompositeDisposable();

    @Override
    public void onError(Throwable t) {
            ExceptionEngine.handleException(t);
    }

    @Override
    public void onComplete() {

    }

    @Override
    public void onSubscribe(Disposable d) {
        compositeDisposable.add(d);
    }

    @Override
    public void onNext(T t) {
    }
}
No problem after the cancellation。Excuse me, this is why, how to solve it
