### ISSUE TITLE
Why does ExceptionCatchingRequestBody extend ResponseBody?

### ISSUE THREAD

**Issue by tanglie1993** [square/retrofit#2781]
The inner class ExceptionCatchingRequestBody  in  retrofit/retrofit/src/main/java/retrofit2/OkHttpCall.java extends ResponseBody. I don't understand why it is named ExceptionCatchingRequestBody instead of ExceptionCatchingResponseBody.  Is it a bug?

**Comment by JakeWharton** [comment]
It's not a bug. Just a erroneous internal name. PR welcome.
