### ISSUE TITLE
(enhancement request) Using gsonFactory for generic types is not supported

### ISSUE THREAD

**Issue by pedro-teran-mojix-com** [square/retrofit#2785]
**Introduction**
as it is known GSON doesn't support generic types by default so if for example I want to deserialize
something like 
```
public class  FooResponse <T> {
    @SerializedName("total")
    private int total;
    @SerializedName("results")
    ArrayList<T> results;
}
```
and we use a class 
```
public class Food {
    @SerializedName("name")
    private String name;
    @SerializedName("quantity")
    private String quantity;
}
```
and we call json    
`FooResponse<Food> response = gson.fromJson(rawData, FooResponse.class);
`
it will fail. miserably. but furtunatly there are some work arround on gson like for example calling it like this:
``FooResponse<Food> response = gson.fromJson(rawPerson, new TypeToken<FooResponse<Food>>(){}.getType())`

**issue in retrofit**

using GsonConverterFactory.create(new GsonBuilder().
....
.create()));

there is no way to support generic types using gson. since there is no way to tell gson the type of the response. as gson  injected in retrofit build time.

** Expected behaviour ** 

to have an alternative GsonFactory or  an optional parameter to define that we are using t types. or at least a way to deserialize this requests. using gson. with some more boiler plate code.

**Comment by JakeWharton** [comment]
Retrofit's Gson converter uses `Type` not `Class` when looking up adapters from Gson so this should work fine. The request will be for a `ParameterizedType` of `FooResponse` with a single parameter of `Food`.

Please providing a failing test case that demonstrates the problem.
