### ISSUE TITLE
Kotlin's Ktor support as http client?

### ISSUE THREAD

**Issue by epool** [square/retrofit#2792]
Is in the plans/roadmap of retrofit add support for different http clients than okhttp? I'm not sure if it's already possible but I'm curios if could be possible to use [Ktor](http://ktor.io/clients/http-client.html) as a Retrofit's client.

**Comment by JakeWharton** [comment]
Ktor is not a client. It's a client abstraction:

> you just have to instantiate an HttpClient instance, specifying an engine, for example Apache, Jetty or CIO

I don't see any reason to add support for an abstraction when Retrofit is already an abstraction.

Alternate HTTP clients can already be used by implementing OkHttp's `Call.Factory` and using its `Request`, `Response`, and other types as the model to convert to/from.
