### ISSUE TITLE
Fatal exception in request

### ISSUE THREAD

**Issue by Jparrgam** [square/retrofit#2793]
Hi, in my app retrofit generated this error

`Caused by okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL        at okhttp3.internal.http2.Http2Stream$FramingSource.checkNotClosed(Http2Stream.java:436)        at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:338)        at okhttp3.internal.http2.Http2Codec$StreamFinishingSource.read(Http2Codec.java:210)        at okio.RealBufferedSource.request(RealBufferedSource.java:68)        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:241)        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)        at okhttp3.RealCall.execute(RealCall.java:77)        at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)        at com.jakewharton.retrofit2.adapter.rxjava2.CallObservable.subscribeActual(CallObservable.java:41)        at io.reactivex.Observable.subscribe(Observable.java:12005)        at io.reactivex.internal.operators.flowable.FlowableFromObservable.subscribeActual(FlowableFromObservable.java:29)        at io.reactivex.Flowable.subscribe(Flowable.java:14291)        at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest.subscribeActual(FlowableOnBackpressureLatest.java:32)        at io.reactivex.Flowable.subscribe(Flowable.java:14291)        at io.reactivex.internal.operators.flowable.FlowableObserveOn.subscribeActual(FlowableObserveOn.java:56)        at io.reactivex.Flowable.subscribe(Flowable.java:14291)        at io.reactivex.Flowable.subscribe(Flowable.java:14237)        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)        at java.util.concurrent.FutureTask.run(FutureTask.java:237)        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)        at java.lang.Thread.run(Thread.java:776)`

**Comment by JakeWharton** [comment]
This is a normal IOException that OkHttp is throwing because the server sent a cancel to stop a stream. Your application should be resilient to IOExceptions which indicate transport failure.

**Comment by Jparrgam** [comment]
@JakeWharton you have a example to control this IOExceptions?

**Comment by JakeWharton** [comment]
All IOExceptions are transport problems with the network. How you handle that is subjective to your app.
