### ISSUE TITLE
Throwable = SSlHandShapeException

### ISSUE THREAD

**Issue by mohammadaminha** [square/retrofit#2794]
I'm using 2.4.0 version and I'm getting SSlHandShapeException on android O
I Used self sign certificate
It works on androids lower than O 
This is my code 
`
public static OkHttpClient.Builder getBuilder(Context context) {

//        OkHttpClient okHttpClient = new OkHttpClient.Builder()
//                .build();
        OkHttpClient okHttpClient = SelfSigningClientBuilder.createClient(context);

        OkHttpClient.Builder httpClient = okHttpClient.newBuilder();

        ConnectionSpec spec = new ConnectionSpec.Builder(ConnectionSpec.MODERN_TLS)
                .tlsVersions(TlsVersion.TLS_1_0)
                .cipherSuites(
                        CipherSuite.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
                        CipherSuite.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
                        CipherSuite.TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,
                        CipherSuite.TLS_DHE_RSA_WITH_AES_128_CBC_SHA).build();

        TrustManagerFactory trustManagerFactory = null;
        try {
            trustManagerFactory = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        }
        try {
            trustManagerFactory.init((KeyStore) null);
        } catch (KeyStoreException e) {
            e.printStackTrace();
        }
        TrustManager[] trustManagers = trustManagerFactory.getTrustManagers();
        if (trustManagers.length != 1 || !(trustManagers[0] instanceof X509TrustManager)) {
            throw new IllegalStateException("Unexpected default trust managers:" + Arrays.toString(trustManagers));
        }
        X509TrustManager trustManager = (X509TrustManager) trustManagers[0];
        SSLContext sslContext = null;
        try {
            sslContext = SSLContext.getInstance("SSL");
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        }
        try {
            sslContext.init(null, new TrustManager[] { trustManager }, null);
        } catch (KeyManagementException e) {
            e.printStackTrace();
        }

        httpClient.connectTimeout(15, TimeUnit.SECONDS)
                .writeTimeout(15, TimeUnit.SECONDS)
                .readTimeout(15, TimeUnit.SECONDS)
                .connectionSpecs(Collections.singletonList(spec))
                .sslSocketFactory(okHttpClient.sslSocketFactory(), trustManager)
                .protocols(Collections.singletonList(Protocol.HTTP_1_1))
        ;

        //httpClient.sslSocketFactory(SelfSigningClientBuilder.createClient(activity).sslSocketFactory());
        httpClient.hostnameVerifier(new HostnameVerifier() {

            @Override
            public boolean verify(String hostname, SSLSession session) {
                return true;
            }
        });

        return httpClient;
    }
`
Please give me an answer to solve this.

**Comment by JakeWharton** [comment]
This problem occurs at a layer much lower than Retrofit and as such we are not equipped to help. You'll have better luck on StackOverflow since this is a general problem not specific to any library but your use of the platform APIs.
