### ISSUE TITLE
How to pause/resume downloading with retrofit2

### ISSUE THREAD

**Issue by LegendaryCoders** [square/retrofit#2800]
hello.
How to pause/resume downloading with retrofit2 ? 
@JakeWharton  can u help ?

**Comment by JakeWharton** [comment]
There is no built-in pause or resume. If your server supports range requests you can break the connection at any time during a streaming download and then send a range header in a follow-up request.

**Comment by UniqueJoy** [comment]
> There is no built-in pause or resume. If your server supports range requests you can break the connection at any time during a streaming download and then send a range header in a follow-up request.

how to do that "send a range header in a follow-up request" ?
