### ISSUE TITLE
Adding Content-Type in interceptor is not working

### ISSUE THREAD

**Issue by taibui-rogue** [square/retrofit#2801]
I created a simple interceptor
`public class AuthorizationInterceptor implements Interceptor {`
`    @Override`
`    public Response intercept(Chain chain) throws IOException {`
`        Request original = chain.request();`
`        Request request = original.newBuilder()`
`                .header("Authorization", "no need authorization")`
`                .header("Content-Type", "application/json")`
`                .build();`
`        return chain.proceed(request);`
`    }`
`}`

The log showed that the Authorization header was added successfully, but the Content-Type wasn't:

`06-17 11:22:55.510 22929-23677/ D/___retrofit: --> POST http://.../users`
`    Content-Type: text/plain; charset=UTF-8`
`    Content-Length: 242`
`    Authorization: no need authorization`
`    --> END POST`
`06-17 11:23:05.560 22929-23677/ D/___retrofit: <-- HTTP FAILED: java.net.SocketTimeoutException: timeout`

Please let me know if I missed something

**Comment by LegendaryCoders** [comment]
This is the Last Interceptor u aded?
You can Send Request With okhttp3.RequestBody then u can set media type

Example :
@POST
Call<ResponseBody> PostBosy(@Url String Url,@Body RequestBody body)


ApiService.PostBody("Url",Body)

Body : You can send RequestBody with String and set Json MediaType..

**Comment by taibui-rogue** [comment]
The last interceptor was just the HttpLoggingInterceptor from squareup and I think it has nothing to do with the header. The app I'm working on works only with content-type application/json, putting @Headers("Content-Type: application/json") in service interface works but I just don't want to do that for every times, you know.

**Comment by JakeWharton** [comment]
Retrofit doesn't influence the interaction of your OkHttp interceptors so there's really no action to take here. Your best bet would be posting on StackOverflow with the 'okhttp' tag and more information about your setup and the problem. In general, headers added by an interceptor are seen by later ones unless overwritten or removed by those later ones.
