### ISSUE TITLE
can't receive the post parameters in url

### ISSUE THREAD

**Issue by Leytton** [square/retrofit#2804]
the server received the `access_token` parameter in $_POST ,but `type` in $_GET
```
@FormUrlEncoded 
@POST("login/app?type=facebook")
Observable<BaseDataResult> loginByFaceBook(
        @Field("access_token") String access_token
);
```

**Comment by JakeWharton** [comment]
That's because `type` is a query parameter in the URL and not a form field value that is included in the body. If you want it to be a form field you need to supply it as a `@Field` and a parameter. There are no mechanisms built-in for constant field values on form-url encoded requests.

**Comment by Leytton** [comment]
Thinks a lot,better if it supports constant field in url query :)

**Comment by JakeWharton** [comment]
It's tracked by #951
