### ISSUE TITLE
Callback is not triggered

### ISSUE THREAD

**Issue by viper619** [square/retrofit#2809]
I'm making a service call from onCreate method of a MainActivity and neither onResponse nor onFailure method is getting called. But when I trigger the same method using onClick command from other components it is working fine.
Is there any issue with calling the retrofit client from onCreate method or something else is the issue?

Please help.

**Comment by kovac777** [comment]
Can you show your`s MainActivity code?

**Comment by JakeWharton** [comment]
This is a usage question which is generally more appropriate for StackOverflow. GitHub issues are reserved for bug reports with test cases or samples, or new feature requests. You can use the 'retrofit' tag which is monitored by us and many library users. Feel free to link the asked question back here on the issue.
