### ISSUE TITLE
Manage digest authentication with Retrofit

### ISSUE THREAD

**Issue by grena** [square/retrofit#281]
Hi everyone,

Do somebody have any idea on how to implement a digest authentication solution with Retrofit ? When the server answers with a **401 Unauthorized** responses, the `Callback` object calls its `failure()` method..

Is it possible with retrofit ? Thanks in advance.

**Comment by Prashant6001** [comment]
Retrofit error: 401 Unauthorized. Previously it was working fine for me but now i am geting this error.
