### ISSUE TITLE
How to pass multiple images using retrofit

### ISSUE THREAD

**Issue by srohith900** [square/retrofit#2811]
Tried to pass multiple images using bytearray format. But it will take more time, how to handle this problem?

**Comment by JakeWharton** [comment]
This is a usage question which is generally more appropriate for StackOverflow. GitHub issues are reserved for bug reports with test cases or samples, or new feature requests. You can use the 'retrofit' tag which is monitored by us and many library users. Feel free to link the asked question back here on the issue.
