### ISSUE TITLE
PATCH method support

### ISSUE THREAD

**Issue by marijnvdwerf** [square/retrofit#282]
The `PATCH` method can be used to only edit some properties of a resource, instead of overwriting it as `PUT` does. Unfortunately, Retrofit doesn't offer support for `PATCH` requests. Are there any plans of adding this request method?

**Comment by pdichone** [comment]
Hey @kapso, do you mind to share how to get PATCH to work in Android Studio?  I am new to retrofit, so any help will be highly appreciated.

Thanks!

**Comment by SandroMachado** [comment]
@pdichone You just need to add the gradle the following dependences:

    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'com.squareup.okhttp:okhttp:2.0.0'
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.0.0'

And the patch will start working.

**Comment by ahmadalibaloch** [comment]
As of March 2016, with Retrofit `2.0.0-beta4` I am using PATCH successfully without any further libraries inclusion as mentioned in the answers here.

**Comment by masterlittle** [comment]
Could someone give an example of using a PATCH request? I am sending data to server but I am receiving 400 error in response. The server is seeing some weird characters as input and not decipherable data.

**Comment by ahmadalibaloch** [comment]
Client Interface in Android is here

` @PATCH("employeeJobs/{id}")
    Call<EmployeeJob> UpdateEmpJob(@Body HashMap empJob, @Path("id") int id);`

Where my `empJob` HashMap has as many properties of empJob entity as I want.

Corresponding .Net WebApi generic controller which is inherited by all other controllers has this `PATCH` method.

        [Route("{id:int}")]
        [HttpPatch]
        public IHttpActionResult Patch(int id, Delta<T> ent)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);

            T origEnt = dbSet.Single(p => p.Id == id);

            if (origEnt == null) return NotFound();

            try
            {
                ent.Patch(origEnt);
                db.SaveChanges();

                return Ok(origEnt);
            }
            catch (Exception e)
            {
                while (e.InnerException != null) e = e.InnerException;
                return BadRequest(e.Message);
            }
        }
`
