### ISSUE TITLE
I want to retrieve method annotations on interceptor.

### ISSUE THREAD

**Issue by missmess** [square/retrofit#2832]
I cannot retrieve method and parameter annotations on OkHttp interceptor, I'd like to use
annotations to modify request url, header or other configurations.
Or can author supply a new feature like interceptor but can obtain the method annotations
and add a method like addXxxFactory.

**Comment by JakeWharton** [comment]
This is not possible, unfortunately. OkHttp does not know about Retrofit to know that a request is being executed by a method declaration and not normal OkHttp interaction. From the other side, Retrofit doesn't actually know that OkHttp is the HTTP client that is executing the request. It only uses OkHttp's model for Request/Response and doesn't actually know about OkHttpClient or interceptors.

The easiest way to pass information to an interceptor is with a header that you then strip. So your method would have something like `@Headers("Custom-Thing: value")` which you would then read in the interceptor and then remove the header.

**Comment by swankjesse** [comment]
Another option: we could add metadata to `retrofit2.Call`: the `java.lang.reflect.Method` and its parameters. And then we could use deluxe tags to tell the okhttp3.Request about its `retrofit2.Call`.

**Comment by mhmdcs** [comment]
For future googlers, as of Retrofit 2.6.0 you can retrieve annotations inside Interceptor.

```
class myInterceptor: Interceptor {

override fun intercept(chain: Interceptor.Chain): Response {
        val request = chain.request()
        val annotation = request.getAnnotation(MyAnnotation::class.java)
        if (annotation != null) {
          /// do whatever you want to do with your annotation metadata
             }
       }
}
```
Use this extension function.
``` fun <T : Annotation> Request.getAnnotation(annotationClass: Class<T>): T? {
    return this.tag(Invocation::class.java)?.method()?.getAnnotation(annotationClass)
}
```
