### ISSUE TITLE
Missed Proguard rule to not remove the Retrofit annotations

### ISSUE THREAD

**Issue by magnumrocha** [square/retrofit#2833]
Hey guys,

During my project releasing, I've got some Issue with Proguard regarding the Retrofit2 rules that were not set to NOT remove the Retrofit Annotations.

After some research, I've found this:
https://raw.githubusercontent.com/square/retrofit/master/retrofit/src/main/resources/META-INF/proguard/retrofit2.pro

The rule below solved my problem:

````
# Retain service method parameters when optimizing.
-keepclassmembers,allowshrinking,allowobfuscation interface * {
    @retrofit2.http.* <methods>;
}
````

I think this rule is very important to be in Retrofit documentation.

Cheers,
Magnum

**Comment by JakeWharton** [comment]
The documentation points to that file now. Perhaps at the time of filing it did not though.
