### ISSUE TITLE
retrofit2. response body is null

### ISSUE THREAD

**Issue by mahmoudAhmedZaher** [square/retrofit#2834]
Endpoint works fine in postman and I get Response{protocol=http/1.1, code=200, message=OK, url=http://192.168.1.249/api/v1/user/1} in the response but no data related to the user.

**Comment by JakeWharton** [comment]
This is not enough information for an actionable report. If you think there's a bug in Retrofit please supply a failing test case or executable sample. The issue template contained an example of this.

**Comment by mahmoudAhmedZaher** [comment]
ok i will explain in more details, attache photo for each step , i have an end point i have developed it with laravel framework , it return json response in postman but when using retrofit the response body is null , code = 200, message=ok .

sample of returned json in postman : 
![11](https://user-images.githubusercontent.com/7596450/43364310-fdc08e5a-9317-11e8-8819-dd59e4b51de8.PNG)

===========
API interface, json parsing, API client

![16](https://user-images.githubusercontent.com/7596450/43364476-13915b26-931b-11e8-8232-70264ac6af4c.PNG)
![18](https://user-images.githubusercontent.com/7596450/43364477-13de80c2-931b-11e8-8e27-3d7fdd8288fc.PNG)
![12](https://user-images.githubusercontent.com/7596450/43364478-141ed55a-931b-11e8-9eb8-9ad41699dd04.PNG)
![15](https://user-images.githubusercontent.com/7596450/43364479-145cd54e-931b-11e8-92dc-7423b12e5eaf.PNG)

==========
API calling -java code- and response in debugger
![13](https://user-images.githubusercontent.com/7596450/43364490-4c116900-931b-11e8-93fc-a26462843364.PNG)
![14](https://user-images.githubusercontent.com/7596450/43364491-4c603422-931b-11e8-9a98-f94dcb5ec7ae.PNG)
