### ISSUE TITLE
How to add custom annotations

### ISSUE THREAD

**Issue by luoxianchao** [square/retrofit#2838]
eg:
public interface Api{
  @GET("/test/api")
  @myanotation(key="demo")
 Call<List<User>> getUsers(@Query('name') String name);
}
like this method,it has a myanotation how can I create?

**Comment by JakeWharton** [comment]
Custom annotations can be read in both converter factories and call adapter factories. What are you trying to do?

**Comment by PoonamGargAgarwal** [comment]
@JakeWharton I would like to add @ApplicationPAth Annotation . Reason is I would like to generate swagger documentation in format on json/yml from it. The application Path defines base url for it.

**Comment by waqasakram117** [comment]
@JakeWharton Please look at this
  
         @GET("/api/v1/home-screen/")
        @RequiredSignedIn
        fun fetchHomeData(@Query("lat") lat:Double, @Query("lng")lng:Double ):Observable<HomeResponse>

And this is my factory


      class TokenInjectorFactory: CallAdapter.Factory() {


    override fun get(
        returnType: Type,
        annotations: Array<Annotation>,
        retrofit: Retrofit
    ): CallAdapter<*, *>? {

        annotations.forEach {

            when(it.annotationClass){
                RequiredSignedIn::class -> {
                    // I want to do something here
                    return null
                }

                UnSigned::class ->{
                   //I want to do something here
                    return null
                }

                SignedOrUnsigned::class -> {
                  // I want to do something here
                    return null
                }

            }
        }

      throw IllegalAccessException("must provide Signedin or Signedout Annotation to your methods")
    }
 
It called only once when the first request made (fetchHomeData called) if I tried same request this factory method never called.
