### ISSUE TITLE
How to set http type dynamic

### ISSUE THREAD

**Issue by firelion0725** [square/retrofit#2839]
I have a dynamic http api, the path , http type and params all from our server.
So, I don't know how to set HTTP TYPE (eg: GET\POST) dynamic.
I want to use @HTTP but method ="" But how to change it with param.
I need HELP!!!

如何动态设置请求的HTTP 类型， 所有的东西都是动态获取的 http类型 也是 但我找不到如何设置的方法
求助！！！

**Comment by JakeWharton** [comment]
This is not supported. If your API is that dynamic its semantics aren't going to map well to methods on an interface which represent remote calls. You're better off just using OkHttp directly which allows you to control all aspects of the HTTP request dynamically.

**Comment by firelion0725** [comment]
I‘m ready to use OKHTTP for this API.  Thank you.
