### ISSUE TITLE
occur java.net.ConnectException

### ISSUE THREAD

**Issue by lckj686** [square/retrofit#2840]
I use retrofit:2.3.0 in my android app，today a device prompts for a network exception。
By tracking is “java.net.ConnectException”，but others devices not has this exception。And in the same app on others devices donot has this exception。In the same device, others app donot has this exception。
Can't solve the problem, ask for help

**Comment by JakeWharton** [comment]
All subtypes of `IOException` indicate a problem with the transport–the network you are talking over.  Especially on mobile platforms, the network comes and goes and you should always plan for failures at any time.

**Comment by SynergyTeletech** [comment]
I am getting same issue
