### ISSUE TITLE
retrofit2.adapter.rxjava2.HttpException HTTP 500 Server Error

### ISSUE THREAD

**Issue by RuanJH** [square/retrofit#2842]
io.reactivex.exceptions.OnErrorNotImplementedException:HTTP 500 Server Error

io.reactivex.exceptions.OnErrorNotImplementedException:HTTP 500 Server Error
--
2 io.reactivex.internal.functions.Functions$m.a(Functions.java:704)
3 ......
4 Caused by:
5 retrofit2.adapter.rxjava2.HttpException:HTTP 500 Server Error
6 retrofit2.adapter.rxjava2.a$a.a(BodyObservable.java:54)
7 retrofit2.adapter.rxjava2.a$a.onNext(BodyObservable.java:37)
8 retrofit2.adapter.rxjava2.c.a(CallExecuteObservable.java:43)
9 io.reactivex.r.subscribe(Observable.java:11040)
10 retrofit2.adapter.rxjava2.a.a(BodyObservable.java:34)
11 io.reactivex.r.subscribe(Observable.java:11040)
12 io.reactivex.internal.operators.observable.ObservableSubscribeOn$a.run(ObservableSubscribeOn.java:96)
13 io.reactivex.x$a.run(Scheduler.java:463)
14 io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
15 io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
16 java.util.concurrent.FutureTask.run(FutureTask.java:266)
17 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
18 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
19 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
20 java.lang.Thread.run(Thread.java:764)

**Comment by JakeWharton** [comment]
An HTTP 500 is an error from your server and OnErrorNotImplementedException means you didn't implement an error callback when subscribing.
