### ISSUE TITLE
Generating swagger documentation from retrofit . 

### ISSUE THREAD

**Issue by PoonamGargAgarwal** [square/retrofit#2843]
I would like to add @ApplicationPAth Annotation . Reason is I would like to generate swagger documentation in format on json/yml from it. The application Path defines base url for it.

**Comment by JakeWharton** [comment]
Retrofit is a client. Swagger is a documentation tool for server APIs. Usually you would generate the client from the server definitions. I don't understand what this annotation is for or what Retrofit would do with it.

**Comment by PoonamGargAgarwal** [comment]
@JakeWharton  I would like to generate swagger document from already defined api in retrofit. I know swagger is documentation tool for Server API . From Swagger documentation - we can build retrofit client.  From Retrofit Client , How can we generate swagger documentation . ? @ApplicationPath annotation is being used in JAx-RS

**Comment by JakeWharton** [comment]
I have no idea how you can do that, but it doesn't sound like a feature request for Retrofit itself. Swagger is an external tool and you should consult what they provide or build something to process the annotations of Retrofit.
