### ISSUE TITLE
QueryMap not encoding square brackets for keys

### ISSUE THREAD

**Issue by maraisf** [square/retrofit#2848]
- [ ] Feature Request. Currently we have urls that use square brackets for the query param keys.

eg. `https://my_domain.com/browse?grid=6&min_discount=1&size[0]=2058&size[1]=2060&size[2]=1924&ss=sli`

We use them in `@QueryMap Map<String, String> filters`.
When using the unencoded square brackets in the keys the following error is thrown.

`java.lang.IllegalArgumentException: Query map contained null value for key 'size[0]'.
        at retrofit2.ParameterHandler$QueryMap.apply(ParameterHandler.java:161)
        at retrofit2.ParameterHandler$QueryMap.apply(ParameterHandler.java:139)
        at retrofit2.ServiceMethod.toCall(ServiceMethod.java:110)
        at retrofit2.OkHttpCall.createRawCall(OkHttpCall.java:184)
        at retrofit2.OkHttpCall.enqueue(OkHttpCall.java:95)
        at retrofit2.adapter.rxjava2.CallEnqueueObservable.subscribeActual(CallEnqueueObservable.java:40)`

I have added a method to encode the keys for the map before we send it to retrofit to make the request:

```
  public Map<String, String> urlEncodeMapKeys(Map<String, String> map) {
        Map<String, String> mapNew = new LinkedHashMap<>();
        for (Map.Entry<String, String> entry : map.entrySet()) {
            String encodedKey = null;
            String unencodedKey = entry.getKey();

            try {
                encodedKey = URLEncoder.encode(unencodedKey, "UTF-8");
            } catch (UnsupportedEncodingException e) {
                e.printStackTrace();
            }

            if (encodedKey != null) {
                mapNew.put(encodedKey, entry.getValue());
            } else {
                mapNew.put(unencodedKey, entry.getValue());
            }
        }
        return mapNew;
    }
```

Would it be possible to add encoding for these @QueryMap keys in retrofit? 🤔

**Comment by swankjesse** [comment]
I think encoding is not the problem here. The exception is because you have a null value in the map.

**Comment by maraisf** [comment]
Hi thanks for the response, you are correct. 
When the map enters here -> `@Override void apply(RequestBuilder builder, @Nullable Map<String, T> value)` all the sizes are listed as null, using the following url `https://my_domain.com/browse?grid=6&min_discount=1&size[0]=2058&size[1]=2060&size[2]=1924&ss=sli`

![screen shot 2018-08-10 at 11 15 23](https://user-images.githubusercontent.com/33288437/43949753-bd435850-9c8e-11e8-8b33-d4aec26b1c46.png)

All the other non-bracket values are shown correctly. 🤔

**Comment by maraisf** [comment]
Im thinking its trying to read the size[0] as an object instead of a string in this case as it is a string key?

**Comment by JakeWharton** [comment]
The values in the map are null as Jesse said and those are not allowed because it's unclear what the intent is (omit pair, omit value, or literal "null").

**Comment by maraisf** [comment]
How would I go about making a request that includes these map values? Is there an option or intent I can set in order for the correct size values to be used?

eg. `https://my_domain.com/browse?grid=6&min_discount=1&size[0]=2058&size[1]=2060&size[2]=1924&ss=sli`
