### ISSUE TITLE
Proxy's InvocationHandler invoke change an argument to null when working with Kotlin

### ISSUE THREAD

**Issue by biaomingzhong** [square/retrofit#2850]
What kind of issue is this?

 - [x] Bug report. 

I am using `Retrofit 2.4.0` with `Kotlin 1.2.30` on Android.  My Project's huge with **5 dexes** in Release Apk. 

It only happens on `Android 6.0.1` devices. One of the followings:

- Normal. Everything works fine.
- `@Get` methods losing a `@Query`  argument. 
- Crash with ANR when requesting losing an argument. 

The method's input is right, I had logged out all my passing arguments. And none of them is `null`. 

So I dug deeper. I built a new `retrofit 2.4.0` Jar by adding an `android.util.Log` in `Retrofit.java`

In those `Android 6.0.1` devices, one of the `args` turns into `null` causing the problem.

```java
public <T> T create(final Class<T> service) {
    Utils.validateServiceInterface(service);
    if (validateEagerly) {
      eagerlyValidateMethods(service);
    }
    return (T) Proxy.newProxyInstance(service.getClassLoader(), new Class<?>[] { service },
        new InvocationHandler() {
          private final Platform platform = Platform.get();

          @Override public Object invoke(Object proxy, Method method, @Nullable Object[] args)
              throws Throwable {
            android.util.Log.e("Retrofit", "invoke args is " + Arrays.toString(args));
            // If the method is a method from Object then defer to normal invocation.
            if (method.getDeclaringClass() == Object.class) {
              return method.invoke(this, args);
            }
            if (platform.isDefaultMethod(method)) {
              return platform.invokeDefaultMethod(method, service, proxy, args);
            }
            ServiceMethod<Object, Object> serviceMethod =
                (ServiceMethod<Object, Object>) loadServiceMethod(method);
            OkHttpCall<Object> okHttpCall = new OkHttpCall<>(serviceMethod, args);
            return serviceMethod.adapt(okHttpCall);
          }
        });
  }
```

This is very Strange. 😭

Please Help me figure out how to solve this.

**Comment by JakeWharton** [comment]
Does it happen in debug APKs? I suspect ProGuard or R8 is causing the problem. It's impossible to know without a sample that reproduces the problem.

**Comment by nicai1900** [comment]
I Have the same problem on 6.0.1

ErrorLog:

`java.lang.IncompatibleClassChangeError

Class 'java.lang.VirtualMachineError' does not implement interface 'java.lang.Class' in call to 'byte byte.()' (declaration of 'java.lang.Throwable' appears in /system/framework/core-libart.jar)`

My code


`interface ApiService {

    @GET
    fun getUserInfo(@Url url: String): Observable<UserModel>

}`

When I  call getUserInfo  method,  the app ANR and then crash

**Comment by nicai1900** [comment]
I have the same problem  only on Android 6.0 or 6.0.1

Crash Log:

`java.lang.IncompatibleClassChangeError

Class 'java.lang.VirtualMachineError' does not implement interface 'java.util.concurrent.locks.Condition' in call to 'void java.util.concurrent.locks.Condition.signal()' (declaration of 'java.lang.Throwable' appears in /system/framework/core-libart.jar)`

**Comment by JakeWharton** [comment]
Nothing indicates that to be the same problem.

**Comment by nicai1900** [comment]
> Nothing indicates that to be the same problem.

I will try to write a demo that reproduces the problem.

**Comment by nicai1900** [comment]
> What kind of issue is this?
> 
> * [x]  Bug report.
> 
> I am using `Retrofit 2.4.0` with `Kotlin 1.2.30` on Android. My Project's huge with **5 dexes** in Release Apk.
> 
> It only happens on `Android 6.0.1` devices. One of the followings:
> 
> * Normal. Everything works fine.
> * `@Get` methods losing a `@Query`  argument.
> * Crash with ANR when requesting losing an argument.
> 
> The method's input is right, I had logged out all my passing arguments. And none of them is `null`.
> 
> So I dug deeper. I built a new `retrofit 2.4.0` Jar by adding an `android.util.Log` in `Retrofit.java`
> 
> In those `Android 6.0.1` devices, one of the `args` turns into `null` causing the problem.
> 
> ```java
> public <T> T create(final Class<T> service) {
>     Utils.validateServiceInterface(service);
>     if (validateEagerly) {
>       eagerlyValidateMethods(service);
>     }
>     return (T) Proxy.newProxyInstance(service.getClassLoader(), new Class<?>[] { service },
>         new InvocationHandler() {
>           private final Platform platform = Platform.get();
> 
>           @Override public Object invoke(Object proxy, Method method, @Nullable Object[] args)
>               throws Throwable {
>             android.util.Log.e("Retrofit", "invoke args is " + Arrays.toString(args));
>             // If the method is a method from Object then defer to normal invocation.
>             if (method.getDeclaringClass() == Object.class) {
>               return method.invoke(this, args);
>             }
>             if (platform.isDefaultMethod(method)) {
>               return platform.invokeDefaultMethod(method, service, proxy, args);
>             }
>             ServiceMethod<Object, Object> serviceMethod =
>                 (ServiceMethod<Object, Object>) loadServiceMethod(method);
>             OkHttpCall<Object> okHttpCall = new OkHttpCall<>(serviceMethod, args);
>             return serviceMethod.adapt(okHttpCall);
>           }
>         });
>   }
> ```
> 
> This is very Strange. 😭
> 
> Please Help me figure out how to solve this.

这个问题现在找到原因了吗？

**Comment by biaomingzhong** [comment]
没，应该是特定系统的 bug，所以我做了特殊的中转，判断是 6.0.1 用一个 java 类 proxy 了 interface，而不是直接 kotlin 调用 interface 接口

**Comment by nicai1900** [comment]
@biaomingzhong  能贴一份 中转实现类的代码吗？

**Comment by nicai1900** [comment]
@biaomingzhong Could you upload your Proguard config here?
