### ISSUE TITLE
Optional class fields not working

### ISSUE THREAD

**Issue by chronvas** [square/retrofit#2851]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

----

Optionals in fields crashes in deserialization
The entire object can be Optional, but fields inside it cause crashes, either with JsonSyntaxException or with "Failed to invoke com.google.common.base.Optional() with no args" exception message.

To reproduce I've created these tests https://gist.github.com/chronvas/9c060ace6cac4ad8915fd187978b4328

I know this will probably be considered as a language limitation and not a library bug, but IMO this needs to exist even in closed bugs since I suspect that it would save lots of time for other people.
A few answers can be found here https://stackoverflow.com/questions/31922866/why-should-java-8s-optional-not-be-used-in-arguments

The obvious solution would be a retrofit specific Optional all together, alongside with a Converter Factory for that, but probably it's not that great of a solution. Any other solutions?

**Comment by NightlyNexus** [comment]
did you install a converter factory for Optional?
There are existing ones in the converters artifacts.

**Comment by chronvas** [comment]
I tried with Guava optional converter factory, see the gist at line 34
https://gist.github.com/chronvas/9c060ace6cac4ad8915fd187978b4328#file-retrofitoptionalbug-java-L34

**Comment by NightlyNexus** [comment]
from your gist:
```
interface Service2 {
  @GET("/path")
  Call<Optional<Settings2>> getSettings();
}

class Settings2 {
  Optional<Integer> alias;

  Settings2() {
  }

  Settings2(Optional<Integer> alias) {
    this.alias = alias;
  }
}
```

Retrofit will look up the converter for the method's call adapter's response type (`Optional<Settings2>`). The Optional  converter will delegate to the next converter for the Optional's argument type (`Settings2`). You'd need a Gson adapter for Optional to change how the `alias` field is understood; the Retrofit Optional converter doesn't know anything about that field.

**Comment by chronvas** [comment]
Ok I think I got how this works now. As I understand it the optional converter works for the base object and then it delegates down the rest of the deserialization, in this case to the Gson converter. When the Gson converter finishes, the optional converter just wraps the gson converter result with optional. 
In case that this object has fields that the gson converter can not convert, the gson converter does not look for other converters for "help" continuing.

Interesting thing is that if I change the order of adding converters, all of the tests fail. Reading the docs for the guava optional converter I can assume that this is ment by design, but should the order matter in the first place?

A Gson adapter for guava's optional does not exist at the moment afaik, does this mean that this bug turns into feature request? -tnx for your help!

**Comment by JakeWharton** [comment]
A feature request for Gson perhaps in some extras artifact (since it doesn't depend on Guava). Retrofit doesn't participate in the configuration of your chosen serializer. I think your immediate course of action is to write the 10-or-so lines of code to create the `TypeAdapterFactory` for Guava's `Optional<T>` for Gson yourself. Whether you choose to pursue publicizing that elsewhere or trying to land it into Gson (I am also a Gson committer but we're not eager to add new things) is up to you.

Closing since no action for Retrofit to take.
