### ISSUE TITLE
Retrofit2, 0-byte body in POST request [while proguard enabled]

### ISSUE THREAD

**Issue by redblackion** [square/retrofit#2852]
I am using retrofit2, and when running the app in release mode with proguard enabled I am not able to send post request body:

I got this log:
```
D/OkHttp: --> POST http:url
    Content-Type: application/json
    Content-Length: 0
    --> END POST (0-byte body)
```

but if I run the app in debug mode with no proguard the POST request works normally!

I have added proguard rules of retrofit:

```
# Platform calls Class.forName on types which do not exist on Android to determine platform.
-dontnote retrofit2.Platform
# Platform used when running on Java 8 VMs. Will not be used at runtime.
-dontwarn retrofit2.Platform$Java8
# Retain generic type information for use by reflection by converters and adapters.
-keepattributes Signature
# Retain declared checked exceptions for use by a Proxy instance.
-keepattributes Exceptions
-dontwarn okio.**
```
ALso I am working with raw Json and using the lib:

`com.squareup.retrofit2:converter-scalars:2.3.0`

Any idea how this happens?

**Comment by JakeWharton** [comment]
Nope. Can you provide a sample project that demonstrates the issue?

**Comment by MartinLi2015** [comment]
yeah,I meet the same problem;
@Filemap   not support JSON str params
