### ISSUE TITLE
setting okhttpclient, responsecode is 200,but Has been the callback  onFailure

### ISSUE THREAD

**Issue by luXiuKun** [square/retrofit#2855]
if (mRetrofitService == null){
            mRetrofitService = new Retrofit.Builder()
                    .client(getOkHttpClient())
                    .baseUrl(HttpRequestUrl.BASE_IP)
                    .addConverterFactory(FastJsonConverterFactory.create())
                    .addConverterFactory(ScalarsConverterFactory.create())
                    .build();
        }

        return mRetrofitService;

 File cache = new File(CommonApplication.getApplication().getCacheDir(), "cache");
        int cacheSize = 10 * 1024 * 1024;
        OkHttpClient.Builder builder = new OkHttpClient.Builder()
                .addNetworkInterceptor(new RetrofitInterceptor.CommonNoNetCache(CommonApplication.getContext()))
                .cache(new Cache(cache,cacheSize))
                .addInterceptor(new RetrofitInterceptor.HeaderInterceptor())
                .connectTimeout(DEFAULT_TIMEOUT, TimeUnit.SECONDS)
                .writeTimeout(DEFAULT_TIMEOUT, TimeUnit.SECONDS)
               .connectionPool(new ConnectionPool(8, 10, TimeUnit.SECONDS));

        if (!BuildConfig.ISONLINE){
            builder.addInterceptor(new RetrofitInterceptor.LoggingInterceptor());
        }

        OkHttpClient okHttpClient = builder.build();
        return okHttpClient;

**Comment by luXiuKun** [comment]
OkHttpClient.Builder builder = new OkHttpClient.Builder()
 OkHttpClient okHttpClient = builder.build();

set this ,  result is the same

**Comment by NightlyNexus** [comment]
Lots of things can cause retrofit2.Callback.onFailure to be called despite successfully getting the HTTP headers back with a successful response code. Details will be in the Throwable parameter. Check that. A likely case is failure in converting the ResponseBody to the declared response type.

**Comment by luXiuKun** [comment]
I found the reason, use own custom Logger intercept , return response

   @Override
        public Response intercept(@NonNull Chain chain) throws IOException {
            Request request = chain.request();
            HttpUrl requestUrl = request.url();
            Headers headers = request.headers();

            if (request.method().equals("POST")){

                RequestBody requestBody= request.body();
                Buffer buffer = new Buffer();
                requestBody.writeTo(buffer);
                Charset charset = Charset.forName("UTF-8");

                String paramsStr = buffer.readString(charset);
                Log.e(TAG,"requestParams ---->" + paramsStr);
           }
            Log.e(TAG,"headers ---->" + headers);
            Log.e(TAG,"requestUrl ---->" + requestUrl);

            Response response = chain.proceed(chain.request());
            String content = response.body().string();
            Log.e(TAG,"response ---->" + content);

            Log.e(TAG,"responseCode ---->" + response.code());

            return response;
        }

if  return chain.proceed(chain.request()) ,callback onResponse ,  but two requests ,  now I  used libs implementation 'com.squareup.okhttp3:logging-interceptor:3.11.0'   no problem

**Comment by NightlyNexus** [comment]
the question is resolved. the interceptor posted above was consuming the response body (`response.body().string()`).
