### ISSUE TITLE
[Question]  When we are dealing with an http or https request, sometimes we will encounter that the returned object is determined according to your request parameters,

### ISSUE THREAD

**Issue by yuqiyich** [square/retrofit#2863]
When we are dealing with an http or https request, sometimes we will encounter that the returned object is determined according to your request parameters, but retrofit does not handle this problem very well temporarily. and I have modified retrofit before, adding an annotation to put the return Class Type, when your request parameter changes, then change the annotation  value to match the return class type，then get the value of this annotation in the converter step, let the converter convert it to the value of our annotated parameter, so that the parameter determines the type returned. above is how I handle different response class type，so I help adding this feature  into retrofit.

**Comment by JakeWharton** [comment]
I don't see what the difference is between changing the type in an annotation and changing the type of the body through the normal mechanism.

**Comment by yuqiyich** [comment]
thank u very much,yes,I get it,there is small difference between changing the type in an annotation and changing the type of the body through the normal mechanism, I can handle different return type  through the normal mechanism.
