### ISSUE TITLE
@Path parameters may not be used with @Url

### ISSUE THREAD

**Issue by zhupengxiang** [square/retrofit#2869]
![qq 20180824172913](https://user-images.githubusercontent.com/17894209/44577276-3e457200-a7c3-11e8-9807-6aef3c463a1f.png)

**Comment by JakeWharton** [comment]
We cannot know whether the path will have a template for this path parameter or not so it is disallowed. If you control the path, you can perform any replacement inside of it before calling Retrofit.

**Comment by Bajranghudda** [comment]
@JakeWharton Is there any solution for this, I am also facing same issue - 
java.lang.IllegalArgumentException: @Path can only be used with relative url on @GET (parameter #2)

**Comment by chanjungkim** [comment]
Is this resolved issue? I still get this error.

**Comment by joenjogu** [comment]
@chanjungkim based off of @JakeWharton's comment, it's not an issue to begin with.
If you had a `@Path` param let's say for a `@GET(endpoint/{param})`  and you use a `@Url` Retrofit has no way of knowing whether the path will have a template for this path parameter.
Instead, at your call site for the endpoint, if you called `fun endpoint(url, param)` just remove the param and append it to the url like so `val url = "https://example.com/endpoint/$param"`
