### ISSUE TITLE
@Query Param contain '|'，will encode Error

### ISSUE THREAD

**Issue by wxmclub** [square/retrofit#2876]
when keyword=abc|def，contain char '|'

this will failed：
```java
@GET(value = "/search")
Call<Result> search(@Query("kw") String keyword);
```

this will success：
```keyword = URLEncoder.encode(keyword, "utf-8")```
```java
@GET(value = "/search")
Call<Result> search(@Query(value = "kw", encoded = true) String keyword);
```

**Comment by wxmclub** [comment]
1.  Request.url = "search?kw=abc|def", so failed, char '|' is not encoded.
2. Request.url = "search?kw=abc%7Cdef", so success. URLEncoder.encode will encode char '|'.

**Comment by JakeWharton** [comment]
Query parameters are encoded by OkHttp, not Retrofit. That being said, I don't see `|` in the set that is required to be encoded so I don't see a problem here.

**Comment by wxmclub** [comment]
Thanks, update OkHttp to v3.10.0 can solve this problem.
