### ISSUE TITLE
FR: AAR to wrap Jar with proguard.txt

### ISSUE THREAD

**Issue by PaulRashidi** [square/retrofit#2880]
Feature Request. Start by telling us what problem you’re trying to solve:

Developers using Retrofit in their Android Apps have a poor experience with Proguard if they forget to add the Proguard directives from the README (and the OK* transitive dependencies). 

Just wondering if it makes sense to create an AAR Maven targets that wrap the JAR targets and includes the proguard.txt file with the directives that are required to use the library.

Anecdotally, it seems like a handful of developers I've spoke with end up disabling Proguard rather than working through the issue.

**Comment by JakeWharton** [comment]
The ProGuard configuration is now embedded in the jar and will be picked up by R8 but not ProGuard. R8 is enabled by default in AGP 3.3 alpha 05 or newer but I'm not sure if it'll stay enabled for AGP 3.3 final. I would encourage you (and everyone) to start testing out R8 to make sure it works on your apps and as a bonus you'll get the rules for libraries like Retrofit, OkHttp, and Okio automatically as they are now embedded in the jar.
