### ISSUE TITLE
Where I can handle custom annotation for convert response?

### ISSUE THREAD

**Issue by MisterGitHubber** [square/retrofit#2881]
I use Retrofit for just html response and I want tag each API method his annotation `@Parser`:

    @Retention(RetentionPolicy.RUNTIME)
    @Target(ElementType.METHOD)
    public @interface Parser {
        Class<? extends IParser> parserClass();
    }

Here my `IParser`:

    public interface IParser<T> {
        T parse(String html);
    }

For example the `ProfileParser`:

    public class ProfileParser implements IParser<Profile> {
        @Override
        public Profile parse(String html) {
            Document doc = Jsoup.parse(htm);
            String nick = doc.select(......);
            // other data
            return new Profile(nick, ...);
        }
    }

I want tag like this:

    public interface GameAPI {
        @Parser(parserClass = ProfileParser.class)
        @GET("/user/{userId}")
        Call<Profile> getProfile(@Path("userId") long userId);
    }

Where I can handle the `@Parser` annotation and how I can set him? How I can make it?

**Comment by NightlyNexus** [comment]
when implementing a Converter.Factory, you can get the method annotations.
something like this:
```java
@Override public Converter<ResponseBody, ?> responseBodyConverter(Type type, Annotation[] annotations, Retrofit retrofit) {
  Parser parserAnnotation = findParserAnnotation(annotations);
  IParser<?> parser = newInstance(parserAnnotation.parserClass());
  return new IParserConverter(parser);
}
```

**Comment by MisterGitHubber** [comment]
@NightlyNexus, `Converter.Factory` for each method?

**Comment by MisterGitHubber** [comment]
@NightlyNexus I create the Factory

**Comment by MisterGitHubber** [comment]
```
class HtmlConverterFactory : Converter.Factory() {
    override fun responseBodyConverter(type: Type,
                                       annotations: Array<Annotation>,
                                       retrofit: Retrofit): Converter<ResponseBody, *>? {
        val parserAnnotation = annotations.firstOrNull { it.annotationClass == Parser::class }
                ?: throw IllegalArgumentException("Each api method must have @Parser annotation")

        val parser = (parserAnnotation as Parser).value.javaObjectType.newInstance()
        return HtmlConverter(parser)
    }
}
```

**Comment by MisterGitHubber** [comment]
But I don't know how complete this with type problem. `return HtmlConverter(parser)` has error

**Comment by MisterGitHubber** [comment]
And here my Converter class. `as T` is unchecked cast

```
class HtmlConverter<T>(private val parser: IParser<*>) : Converter<ResponseBody, T> {

    override fun convert(response: ResponseBody): T {
        val htmlDocument = Jsoup.parse(response.string())
        return parser.parse(htmlDocument) as T
    }
    
}
```

**Comment by MisterGitHubber** [comment]
@NightlyNexus, thanks! I finished writing this converter: https://gist.github.com/MisterGitHubber/632e61b51083647aca99b0a8512de1d1#file-net_retrofit_htmlconverterfactory-kt.

but did not have time to test. later I'll write it or not
