### ISSUE TITLE
Retrofit 2 to support ->  Restrictions on non-SDK interfaces on Android Pie

### ISSUE THREAD

**Issue by KevinLeigh** [square/retrofit#2889]
As of Android Pie, there is restrictions for using non-SDK interfaces. Please see documentation here -> https://developer.android.com/about/versions/pie/restrictions-non-sdk-interfaces

Will Retrofit2 be updated to fully support `Restrictions on non-SDK`?

**Comment by JakeWharton** [comment]
It doesn't violate any.

**Comment by KevinLeigh** [comment]
@JakeWharton Thank you for the response Jake,

Please let me know if the following dark greylist falls under non-SDK restriction or not for Retrofit2  ->

```
#819: Reflection dark greylist Ljava/util/concurrent/locks/AbstractQueuedSynchronizer;->HEAD potential use(s):
       Lcom/google/android/gms/internal/ads/zzafs;->zza(Landroid/content/Context;Lcom/google/android/gms/internal/ads/zzafl;)Lorg/json/JSONObject;
       Lcom/google/android/gms/internal/ads/zzagf;->zzop()Lcom/google/android/gms/internal/ads/zzanz;
       Lcom/google/android/gms/internal/ads/zzas;->zza(Lcom/google/android/gms/internal/ads/zzr;Ljava/util/Map;)Lcom/google/android/gms/internal/ads/zzaq;
       Lcom/google/android/gms/internal/firebase-perf/zzc;->zzb(Ljava/lang/String;)Lcom/google/android/gms/internal/firebase-perf/zzc;
       Lio/fabric/sdk/android/services/network/HttpRequest;->head(Ljava/lang/CharSequence;)Lio/fabric/sdk/android/services/network/HttpRequest;
       Lio/fabric/sdk/android/services/network/HttpRequest;->head(Ljava/net/URL;)Lio/fabric/sdk/android/services/network/HttpRequest;
       Lokhttp3/Request$Builder;->head()Lokhttp3/Request$Builder;
       Lokhttp3/internal/http/HttpHeaders;->hasBody(Lokhttp3/Response;)Z
       Lokhttp3/internal/http/HttpMethod;->permitsRequestBody(Ljava/lang/String;)Z
       Lretrofit2/ServiceMethod$Builder;->parseMethodAnnotation(Ljava/lang/annotation/Annotation;)V
       Lokhttp3/internal/http/RetryAndFollowUpInterceptor;->followUpRequest(Lokhttp3/Response;Lokhttp3/Route;)Lokhttp3/Request;
```

Specifically referring to this line in dump above ->
`Lretrofit2/ServiceMethod$Builder;->parseMethodAnnotation(Ljava/lang/annotation/Annotation;)V`

**Comment by JakeWharton** [comment]
That method does no reflection and uses no Android APIs

**Comment by KevinLeigh** [comment]
Thank you for the quick response, much appreciated :). I hear what you saying, Veridex gives a lot of false positives, next time I will look at the library source code before raising issue.

**Comment by JakeWharton** [comment]
Yeah it seems to be using a similar technique to ProGuard where it assumes a simple name match might be reflection-based usage which tend to throw a lot of false positives.
