### ISSUE TITLE
Empty io.reactivex.Maybe

### ISSUE THREAD

**Issue by abersnaze** [square/retrofit#2891]
What kind of issue is this?
 - [X] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Using the RxJava 2 call adaptor and `Maybe<R>` return type. I've used the code below to map what I think are some common situations that I wish were part of the default adaptor. As it currently is implemented it seems like the Maybe is never empty.

Could the `RxJava2CallAdapterFactory` take a `java.util.function.Predicate<Call<R>>` to let me choose which calls are mapped `Maybe.empty()`?

`maybe = maybe.onErrorResumeNext(this::mapSomeErrorsToEmpty);`

```
        public <R> Maybe<R> mapSomeErrorsToEmpty(Throwable err) {
            if (err instanceof HttpException) {
                HttpException httpErr = (HttpException) err;
                if (httpErr.code() == 404)
                    return Maybe.empty();
            }
            if (err instanceof JsonMappingException && "No content to map due to end-of-input"
                    .equals(((JsonProcessingException) err).getOriginalMessage())) {
                return Maybe.empty();
            }
            return Maybe.error(err);
        }
```

**Comment by JakeWharton** [comment]
I don't think it makes sense to have any support for this in the library. For applying application-layer concern around the shape of the return types you can use a delegating call adapter. We have one in the `samples/` which shows you how to delegate to the built-in adapter to create an `Observable` and then mix-in the behavior of applying `observeOn`: https://github.com/square/retrofit/blob/61dc1be80098699482afb1f553f8c63134ccb18f/samples/src/main/java/com/example/retrofit/RxJavaObserveOnMainThread.java#L65-L68. You can do the same trick here. Delegate to get the original `Maybe` and then apply your application-layer shaping to produce a `Maybe` with the behavior you want.
