### ISSUE TITLE
Android Retrofit/OkHtp Use `8.8.8.8` programatically for DNS lookup?

### ISSUE THREAD

**Issue by sudhanshugaur4** [square/retrofit#2901]
I am trying to add Google DNS lookup which is '8.8.8.8.' in my android app, I am using Retrofit with OkHttp.

Is it possible programmatically?

I saw this post but wasn't able to add it https://garage.easytaxi.com/tag/dns-android-okhttp/

**Comment by JakeWharton** [comment]
This is a usage question which is generally more appropriate for StackOverflow. GitHub issues are reserved for bug reports with test cases or samples, or new feature requests. You can use the 'retrofit' tag which is monitored by us and many library users. Feel free to link the asked question back here on the issue.
