### ISSUE TITLE
Why I can not debug Proxy.newProxyInstance method?

### ISSUE THREAD

**Issue by CoXier** [square/retrofit#2907]
What kind of issue is this?

 - [x] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I am using Retrofit on Android.

I define a service `GitHubService`.

    public interface GithubService {
    
        @GET("users/{user}")
        Call<ResponseBody> fetchUserInfo(@Path("user") String user);
    
    }

Then I create service.

        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl("http://api.github.com")
                .build();

        GithubService service = retrofit.create(GithubService.class);
        Call<ResponseBody> call = service.fetchUserInfo("coxier");
        call.enqueue(...);
As you see, I use above code to get user info of github. And above code works well for me. Now I want to know how Retofit works so I read source code.The code below is `Retrofit#create`. After reading, I still don't know its magic then I decide to debug Retroft.

    public <T> T create(final Class<T> service) {
      ...
      return (T) Proxy.newProxyInstance(...,
          new InvocationHandler() {
            ...
            @Override public Object invoke(..)
                throws Throwable {
       
              if (method.getDeclaringClass() == Object.class) {
                return method.invoke(this, args);
              }
              ...
              return loadServiceMethod(method).invoke(args != null ? args : emptyArgs);
            }
          });
    }

I debug at `if(method.getDeclaringClass() == Object.class)` line ,however it crashes. I don't know why it crashes.

**Comment by JakeWharton** [comment]
I don't know why debugging doesn't work but I can't see a way that Retrofit is somehow causing it. I'm able to put a breakpoint inside the invocation handler and have it work in my app.

What exception is thrown in the crash?

**Comment by CoXier** [comment]
> I don't know why debugging doesn't work but I can't see a way that Retrofit is somehow causing it. I'm able to put a breakpoint inside the invocation handler and have it work in my app.
> 
> What exception is thrown in the crash?

It's very strange. I did not find any crash log.

**Comment by CoXier** [comment]
> I don't know why debugging doesn't work but I can't see a way that Retrofit is somehow causing it. I'm able to put a breakpoint inside the invocation handler and have it work in my app.
> 
> What exception is thrown in the crash?

I tested several devices.

* Nexus 6P Android 8.0 : crash when debug
* Xiaomi 6 Android 8.1: crash when debug
* OnePlus 3 Android 8.0: crash when debug
* Samsung Android 5.0: works well when debug

It may crash above Android 8.0. I do not know why. Can Jake have a look at it?

**Comment by CoXier** [comment]
So I think this issue should not be closed.

**Comment by JakeWharton** [comment]
It's not clear what change could be made by Retrofit to facilitate this. Proxy is a JDK class and if debugging fails to work inside the invocation handler that would be a limitation of the Android VM.

**Comment by swankjesse** [comment]
This is a bug in your VM.

**Comment by koush** [comment]
Just a heads up:
I'm running into this too. This is not a Retrofit issue, but an issue with debugging InvocationHandler targets and/or proxy objects. If the "proxy" object is in the is in the current frame (doesn't matter where), the process crashes with:

```
12-25 11:32:41.294  9617  9617 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12-25 11:32:41.294  9617  9617 F DEBUG   : Build fingerprint: 'NVIDIA/darcy/darcy:8.0.0/OPR6.170623.010/3507953_1364.6545:user/release-keys'
12-25 11:32:41.294  9617  9617 F DEBUG   : Revision: '0'
12-25 11:32:41.294  9617  9617 F DEBUG   : ABI: 'arm64'
12-25 11:32:41.294  9617  9617 F DEBUG   : pid: 9503, tid: 9510, name: JDWP  >>> com.koushikdutta.scrypted <<<
12-25 11:32:41.294  9617  9617 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x14
12-25 11:32:41.294  9617  9617 F DEBUG   : Cause: null pointer dereference
12-25 11:32:41.294  9617  9617 F DEBUG   :     x0   0000000000000000  x1   0000002359825400  x2   0000000000014667  x3   0000002367a231cc
12-25 11:32:41.294  9617  9617 F DEBUG   :     x4   0000000000000000  x5   0000000000000000  x6   000000234b053000  x7   00000000047716d0
12-25 11:32:41.294  9617  9617 F DEBUG   :     x8   000000000000ffff  x9   000000000000ffff  x10  0000000000000000  x11  0000002367a23048
12-25 11:32:41.294  9617  9617 F DEBUG   :     x12  0000000000000000  x13  0000000000000000  x14  000000235ddb5027  x15  0000000000000000
12-25 11:32:41.294  9617  9617 F DEBUG   :     x16  0000000000000014  x17  000000234d2cc718  x18  00000023505859b5  x19  000000234f8b1320
12-25 11:32:41.294  9617  9617 F DEBUG   :     x20  0000002367a23054  x21  0000000070a89b38  x22  0000002359858010  x23  0000000000000043
12-25 11:32:41.294  9617  9617 F DEBUG   :     x24  0000002367a231cc  x25  00000023501fbb78  x26  0000000000000020  x27  000000234fefb07c
12-25 11:32:41.294  9617  9617 F DEBUG   :     x28  000000000000004d  x29  0000002367a23030  x30  000000234fda9c8c
12-25 11:32:41.294  9617  9617 F DEBUG   :     sp   0000002367a22fd0  pc   000000234fda9c94  pstate 0000000060000000
12-25 11:32:41.299  9617  9617 F DEBUG   : 
12-25 11:32:41.299  9617  9617 F DEBUG   : backtrace:
12-25 11:32:41.299  9617  9617 F DEBUG   :     #00 pc 0000000000192c94  /system/lib64/libart.so (_ZN3art11annotations23GetSourceDebugExtensionENS_6HandleINS_6mirror5ClassEEE+92)
12-25 11:32:41.299  9617  9617 F DEBUG   :     #01 pc 00000000001648ec  /system/lib64/libart.so (_ZN3art3Dbg23GetSourceDebugExtensionEmPNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE+292)
12-25 11:32:41.299  9617  9617 F DEBUG   :     #02 pc 00000000002e40b0  /system/lib64/libart.so (_ZN3art4JDWPL23RT_SourceDebugExtensionEPNS0_9JdwpStateEPNS0_7RequestEPNS0_9ExpandBufE+52)
12-25 11:32:41.299  9617  9617 F DEBUG   :     #03 pc 00000000002e25c8  /system/lib64/libart.so (_ZN3art4JDWP9JdwpState14ProcessRequestEPNS0_7RequestEPNS0_9ExpandBufEPb+732)
12-25 11:32:41.299  9617  9617 F DEBUG   :     #04 pc 00000000002e9158  /system/lib64/libart.so (_ZN3art4JDWP9JdwpState12HandlePacketEv+164)
12-25 11:32:41.299  9617  9617 F DEBUG   :     #05 pc 000000000051447c  /system/lib64/libart.so (_ZN3art4JDWP12JdwpAdbState15ProcessIncomingEv+912)
12-25 11:32:41.299  9617  9617 F DEBUG   :     #06 pc 00000000002e94a0  /system/lib64/libart.so (_ZN3art4JDWP9JdwpState3RunEv+444)
12-25 11:32:41.299  9617  9617 F DEBUG   :     #07 pc 00000000002e8b7c  /system/lib64/libart.so (_ZN3art4JDWPL15StartJdwpThreadEPv+40)
12-25 11:32:41.299  9617  9617 F DEBUG   :     #08 pc 0000000000065f88  /system/lib64/libc.so (_ZL15__pthread_startPv+36)
12-25 11:32:41.299  9617  9617 F DEBUG   :     #09 pc 000000000001ed24  /system/lib64/libc.so (__start_thread+68)
```
