### ISSUE TITLE
PUT requests are converting to GET

### ISSUE THREAD

**Issue by sachinartoo** [square/retrofit#2908]
I am making a `PUT` request but in response it says `GET` request and of course `404` code as target api supports only `PUT`. Please refer following attached snapshot.

I have tried with Postman and other api clients, api works fine. But not with retrofit.

Debugger snapshot of response returned by dagger PUT call:

Call (request):
![request_1](https://user-images.githubusercontent.com/36504516/46068013-cd182680-c195-11e8-92ce-96936d89480e.png)

Response: 
![response_2](https://user-images.githubusercontent.com/36504516/46068168-2ed89080-c196-11e8-8ea6-23c4294dbb8b.png)

**Comment by swankjesse** [comment]
We really need executable test cases on bug reports like this. There's nothing actionable here.

BTW, this issue probably should be reported against OkHttp unless there's something Retrofit is doing that's problematic.

**Comment by sachinartoo** [comment]
Its on OkHttp issue, because at the end i am using OkHttp now for put calls. When in do it thought retrofit it converts `PUT` request to `GET`.

Question: Which kind of test case you want? I can not expose our api access_token for a live test request. Could you be more specific?

**Comment by sachinartoo** [comment]
I have attached a test case. I hope it helps you reproduce issue. Let me know if you need something else.

```
import org.junit.Rule;
import org.junit.Test;

import okhttp3.ResponseBody;
import okhttp3.mockwebserver.MockResponse;
import okhttp3.mockwebserver.MockWebServer;
import retrofit2.Call;
import retrofit2.Response;
import retrofit2.Retrofit;
import retrofit2.http.Body;
import retrofit2.http.Headers;
import retrofit2.http.PUT;
import retrofit2.http.Query;

import static org.junit.Assert.assertEquals;

public final class RetrofitPutBugTest {
    @Rule public final MockWebServer server = new MockWebServer();

    interface Service {
        @PUT("entities/108400000051")
        @Headers("User-Agent: Test Case")
        Call<ResponseBody> put(@Query("access_token") String token, @Body String body);
    }

    // This should happen, when a put request is made.
    @Test public void test_Should_be_test_case_scenario() throws Exception {
        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(server.url("/"))
                .build();
        Service example = retrofit.create(Service.class);

        server.enqueue(new MockResponse()
                .setResponseCode(200)
                .addHeader("Content-Type", "application/json")
                .setBody("{}"));

        Call<ResponseBody> call = example.put("sample-access-token",
                "{Some json data}");

        Response<ResponseBody> response = call.execute();
        ResponseBody responseBody = response.body();
        assertEquals(200, response.code());
        assertEquals("{}", responseBody.string());
    }

    // This is happening in my case. When a PUT request is made it returns 404 code.
    @Test public void test_Actual_test_case_scenario() throws Exception {
        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(server.url("/"))
                .build();
        Service example = retrofit.create(Service.class);

        server.enqueue(new MockResponse()
                .setResponseCode(400)
                .addHeader("Content-Type", "application/json"));

        Call<ResponseBody> call = example.put("sample-access-token",
                "{Some json data}");

        Response<ResponseBody> response = call.execute();
        ResponseBody responseBody = response.body();
        assertEquals(400, response.code());
    }
}
```

**Comment by swankjesse** [comment]
Unclear what the bug in OkHttp/Retrofit is here. What behavior were you expecting?

**Comment by sachinartoo** [comment]
Please check attached images in first comments.
In request image, you can see its `PUT` request. But its response represents it as `GET` request.

**Comment by swankjesse** [comment]
But that behavior isn’t represented in your test case. Could you figure out what the difference is between your environment and the test, and add it to the test?

**Comment by sachinartoo** [comment]
I tried doing it. MockResponse does not allow me to do that. 
Is it possible that i can add `METHOD` (GET, PUT) in MockResponse object? If yes, Please direct me to some links  that i can refer.

**Comment by swankjesse** [comment]
Is your server redirecting the request?
