### ISSUE TITLE
Support complex object for service request path param

### ISSUE THREAD

**Issue by foresthuo** [square/retrofit#291]
I created a service as below, it use date as the path param
@GET("/programs/date/{date}")
public void findByDate(@Path("date") Date date, Callback<List<Program>> callback);

Retrofit will auto convert the request to link:
http://localhost:8080/itv/services/programs/date/Thu+Aug+01+13%3A32%3A09+GMT%2B0800+2013

but my expect is:
http://localhost:8080/itv/services/programs/date/2013-08-01 13:03:09

I checked the code in RequestBuilder and find that it use URLEncoder.encode(String.valueOf(value), "UTF-8"); to format the date, 

How can I specify the date format?

**Comment by rolfw** [comment]
For anyone having the same issue: this is now possible by registering a custom `Converter.Factory`. See example on SO: http://stackoverflow.com/a/42459356/741217

**Comment by cypressious** [comment]
Is there a way to decompose a complex object into more than one query parameter? Using `&` in the `toString()` result isn't possible as it will be encoded, even when using `@Query(..., encoded = true)`

**Comment by NightlyNexus** [comment]
@cypressious with `@QueryMap`? and you may want to subscribe to this: https://github.com/square/retrofit/issues/626
