### ISSUE TITLE
How to repeat network request by click the "retry button" with RxJava2.

### ISSUE THREAD

**Issue by nEdAy** [square/retrofit#2910]
The Call() can only be called once, but can be cloned. Can call the newly cloned call.

But with RxJava2 return a Observable, I don't know what to do? Observable functions without "clone()".

I want to call "observableClone.subscribe(subscriber)" everywhere(E.g on an dialog button click ),but got an error!

"It is not allowed to subscribe with a(n) " + consumer + " multiple times. "
                + "Please create a fresh instance of " + consumer + " and subscribe that to the target source instead.";

```
 public RecoveryErrorDialogFragment showRecoveryErrorDialog(Observable observable, BaseSubscriber subscriber) {
        final RecoveryErrorDialogFragment errorDialog = RecoveryErrorDialogFragment.newInstance();
        errorDialog.setAfterRecoveryErrorDialogAction(new RecoveryErrorDialogFragment.AfterRecoveryErrorDialogAction() {
            @Override
            public void afterErrorRetryAction() {
                **observable.subscribe(subscriber);**
            }

            @Override
            public void afterErrorCancelAction() {

            }
        });
}
```

**Comment by JakeWharton** [comment]
The call is cloned for each new subscriber: https://github.com/square/retrofit/blob/61dc1be80098699482afb1f553f8c63134ccb18f/retrofit-adapters/rxjava2/src/main/java/retrofit2/adapter/rxjava2/CallEnqueueObservable.java#L36-L37

All you should have to do is call `subscribe` twice. I just wrote tests for all Rx types which validate they can be subscribed to multiple times: #2912.
