### ISSUE TITLE
Open RxJava2CallAdapter for subclassing

### ISSUE THREAD

**Issue by jeffdgr8** [square/retrofit#2913]
I'd like to create a custom `RxJava2CallAdapterFactory` which creates a `RxJava2CallAdapter` subclass whose behavior is to create a synchronous `Observable` when an HTTP service is called on a background thread and an asynchronous `Observable` when called on the main thread. But since the `RxJava2CallAdapter` class is package private and final, I am unable to subclass to add this functionality.

I'd have to copy and duplicate a lot of code from the `retrofit2.adapter.rxjava2` package to achieve this currently. I'm not sure this use case warrants an addition to the retrofit base code, but this would be another option.

**Comment by swankjesse** [comment]
Inheritance is too difficult to reason about in code like this. Consider delegation?

**Comment by adriancole** [comment]
could this be done with assembly hooks?

we used this approach to add tracing for example
https://github.com/openzipkin/brave/tree/master/context/rxjava2

**Comment by jeffdgr8** [comment]
Delegation works pretty well. Thanks for the idea @swankjesse.

```
class RxJava2AsyncOnMainCallAdapterFactory: CallAdapter.Factory() {

    private val syncFactory = RxJava2CallAdapterFactory.create()
    private val asyncFactory = RxJava2CallAdapterFactory.createAsync()

    override fun get(returnType: Type, annotations: Array<Annotation>, retrofit: Retrofit): CallAdapter<*, *>? {
        return if (Looper.myLooper() == Looper.getMainLooper()) {
            RxJava2AsyncCallAdapter(asyncFactory.get(returnType, annotations, retrofit)!!)
        } else {
            syncFactory.get(returnType, annotations, retrofit)
        }
    }

    class RxJava2AsyncCallAdapter<R>(private val asyncDelegate: CallAdapter<R, *>): CallAdapter<R, Any> {

        override fun adapt(call: Call<R>): Any {
            return with(asyncDelegate.adapt(call)) {
                when (this) {
                    is Flowable<*> -> observeOn(AndroidSchedulers.mainThread())
                    is Single<*> -> observeOn(AndroidSchedulers.mainThread())
                    is Maybe<*> -> observeOn(AndroidSchedulers.mainThread())
                    is Completable -> observeOn(AndroidSchedulers.mainThread())
                    is Observable<*> -> observeOn(AndroidSchedulers.mainThread())
                    else -> this
                }
            }
        }

        override fun responseType(): Type {
            return asyncDelegate.responseType()
        }
    }
}
```

@adriancole I'll have to look into how those assembly hooks work. Thanks for the input.
