### ISSUE TITLE
How send javaBean data to server? ( there are many files in this JavaBean )

### ISSUE THREAD

**Issue by 297179121** [square/retrofit#2917]
It is my JavaBean data:
![image](https://user-images.githubusercontent.com/3394927/46706429-f8efdd80-cc66-11e8-94d1-eb73efdbd4ae.png)
![image](https://user-images.githubusercontent.com/3394927/46706438-04430900-cc67-11e8-814a-5845373d88bc.png)

I use @body 
![image](https://user-images.githubusercontent.com/3394927/46706456-276db880-cc67-11e8-8d39-20e1f8835d16.png)

My service is springboot
![image](https://user-images.githubusercontent.com/3394927/46706489-44a28700-cc67-11e8-9981-3263dc60ebaf.png)

I want to send data with JavaBean, but I failure, please Help me! thank you everybody

**Comment by JakeWharton** [comment]
This is a usage question which is generally more appropriate for StackOverflow. GitHub issues are reserved for bug reports with test cases or samples, or new feature requests. You can use the 'retrofit' tag which is monitored by us and many library users. Feel free to link the asked question back here on the issue. In general, you need to choose a serialization format and a library to perform that serialization. Common ones are JSON and protocol buffers which each have a few different libraries you can choose from.
