### ISSUE TITLE
Proguard issue:Note: the configuration keeps the entry point...

### ISSUE THREAD

**Issue by CoXier** [square/retrofit#2918]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I am using `Retrofit 2.4.0`. When I proguard my app , there are some `Notes`.

> Note: the configuration keeps the entry point 'retrofit2.HttpException { HttpException(retrofit2.Response); }', but not the descriptor class 'retrofit2.Response'
Note: the configuration keeps the entry point 'retrofit2.adapter.rxjava2.HttpException { HttpException(retrofit2.Response); }', but not the descriptor class 'retrofit2.Response'

I use [proguard rules](https://github.com/square/retrofit/blob/master/retrofit/src/main/resources/META-INF/proguard/retrofit2.pro). And `ProGuard, version 4.7`

**Comment by JakeWharton** [comment]
Our rules don't mark subtypes of exceptions as explicitly kept. Those are coming from elsewhere and the fact that it's keeping all subtypes is very worrying.

I would recommend posting on StackOverflow with your entire set of rules to figure out how to eliminate the problematic one. You can also use -whyareyoukeeping to narrow down the reasoning.

This warning will not occur with only the rules we provide, so there's no action to take on our part.
