### ISSUE TITLE
Unrecognized token exception from server

### ISSUE THREAD

**Issue by suarezu** [square/retrofit#2920]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I created a JacksonService
`mJacksonService = new Retrofit.Builder()
                .baseUrl("http://" + ip + ":" + port + "/")
                .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
                .addConverterFactory(JacksonConverterFactory.create())
                .build()
                .create(JacksonService.class);`

and the service definition:
`private interface JacksonService {
        @FormUrlEncoded
        @POST("alarm/searchPersonAlarmList")
        Observable<String> taskHistory(
                @HeaderMap Map<String, String> headers,
                @Field("confidence") Integer confidence,
                @Field("startTime") Long startTime,
                @Field("endTime") Long endTime,
                @Field("pageNumber") Integer pageNumber,
                @Field("pageSize") Integer pageSize,
                @Field("refresh") Double refresh,
                @Field("sort") String sort,
                @Field("sortBy") String sortBy
        );
    }`

when calling taskHistory(...) the first parameter **confidence** is reported exception from the server:
`Failed to read HTTP message: org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Unrecognized token 'confidence': was expecting ('true', 'false' or 'null'); nested exception is com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'confidence': was expecting ('true', 'false' or 'null')
 at [Source: java.io.PushbackInputStream@792a1443; line: 1, column: 12]`

I have searched all the issues and explored the internet, but found no solution to this problem. need badly a fix to it.

**Comment by JakeWharton** [comment]
You are sending a form url-encoded request and your server is trying to parse it as JSON. You need to use the same serialization format on the client as you do on the server so either the client needs to send JSON or the server needs to parse the request as being form url-encoded.

**Comment by suarezu** [comment]
could you show an jackson example? sorry I cant get it through by defining this method in the JacksonService:
`@POST("alarm/searchPersonAlarmList")
        Observable<String> taskHistory2(
                @HeaderMap Map<String, String> headers,
                @Body TaskHistoryParams params);`

and the param as follows:
` private class TaskHistoryParams {
        @JsonProperty
        public int confidence;
        @JsonProperty
        public long startTime;
        @JsonProperty
        public long endTime;
        @JsonProperty
        public int pageNumber;
        @JsonProperty
        public int pageSize;
        @JsonProperty
        public double refresh;
        @JsonProperty
        public String sort;
        @JsonProperty
        public String sortBy;
    }`
