### ISSUE TITLE
Retrofit2.Call ArrayIndexOutOfBoundsException gradle plugin 3.2.0

### ISSUE THREAD

**Issue by palrahul** [square/retrofit#2921]
We are seeing a crash  on Android 6.0 and possibly 6.1 because of this issue. Was using gradle:3.2.0
Have checked previous closed issues with similar trace and was wondering if the gradle toolchain is again broken or could this be some other issue.

Stack trace:
```
10-10 21:49:40.657 18171-18171/com.publisher.test A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 18171 (.publisher.test)
10-10 21:49:39.510 18171-18171/com.publisher.test A/art: art/runtime/thread.cc:1329] Throwing new exception 'length=304; index=1366' with unexpected pending exception: java.lang.ArrayIndexOutOfBoundsException: length=304; index=1366
    art/runtime/thread.cc:1329]   at retrofit2.Call com.vungle.warren.VungleApiClient.reportNew() (VungleApiClient.java:529)
    art/runtime/thread.cc:1329]   at void com.vungle.warren.Vungle$2.onResponse(retrofit2.Call, retrofit2.Response) (Vungle.java:385)
    art/runtime/thread.cc:1329]   at void com.vungle.warren.VungleApiClient$3.onResponse(retrofit2.Call, retrofit2.Response) (VungleApiClient.java:475)
    art/runtime/thread.cc:1329]   at void retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run() (ExecutorCallAdapterFactory.java:70)
    art/runtime/thread.cc:1329]   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:739)
    art/runtime/thread.cc:1329]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95)
    art/runtime/thread.cc:1329]   at void android.os.Looper.loop() (Looper.java:148)
    art/runtime/thread.cc:1329]   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:5527)
    art/runtime/thread.cc:1329]   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
    art/runtime/thread.cc:1329]   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:730)
    art/runtime/thread.cc:1329]   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:620)
```

Code invoking the trace above:
Api interface:
          @Headers(value = {"Content-Type: application/json", "Vungle-Version: 5.2.0"})
	@GET("{new}")
	Call<JsonObject> reportNew(@Header("User-Agent") String ua, @Path(value = "new", encoded = true) String path, @QueryMap Map<String, String> query);

VungleApiClient.java:529:   api.reportNew(HEADER_UA, newEndpoint, query);
Vungle.java:385 :                 vungleApiClient.reportNew().enqueue(cb); 
VungleApiClient.java:475:   callback.onResponse(call, response);

**Comment by JakeWharton** [comment]
We have no control over the toolchain you use or what it does to our code. And, most importantly, the crash originates from your code and not from inside Retrofit itself. If you think D8 has regressed, I would file an issue at https://issuetracker.google.com/issues/new?component=317603 with your APK or classes.dex attached and as much information as possible about the crash. They are much better suited to deal with this than us. As with the original exception, there's nothing we can even really do here.
