### ISSUE TITLE
Retrofit change base url

### ISSUE THREAD

**Issue by Jparrgam** [square/retrofit#2922]
Hello,
Retrofit is making me a url change, it is eliminating a path on the base

this is my base url 
`public static final String backend_url = "https://api.coink.com/qa/";`

in runtime execute base url 
`https://api.coink.com/`

my configuration is this: 

`@Provides @Singleton fun provideRetrofit(): Retrofit {
       val retrofit =  Retrofit.Builder()
                .addConverterFactory(CoinkEncryptConverterFactory.create(providesGson()))
                .addConverterFactory(GsonConverterFactory.create(providesGson()))
                .baseUrl(BuildConfig.backend_url)
                .client(okHttpClient())
                .build()
        return retrofit
    }`

**Comment by JakeWharton** [comment]
Are you specifying a relative URL or an absolute URL on the service method? Please read the documentation for base URL which describes the behavior: http://square.github.io/retrofit/2.x/retrofit/retrofit2/Retrofit.Builder.html#baseUrl-okhttp3.HttpUrl-
