### ISSUE TITLE
response is ok in android all version but null in android pie.

### ISSUE THREAD

**Issue by techhuntdevelopers** [square/retrofit#2924]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by techhuntdevelopers** [comment]
how to fix this issue

**Comment by JakeWharton** [comment]
You haven't supplied any information to even begin diagnosing a problem. Please read the issue template. At minimum we need a _ton_ more information. And without a test case or executable sample it will likely be impossible to know what is going on.
