### ISSUE TITLE
Encapsulate different json part into one field using retrofit android

### ISSUE THREAD

**Issue by rahul4452** [square/retrofit#2936]
I'm trying to make a Post request using retrofit. i'm able to send name,image, language_id,relation_id, but i don't understand one thing how to encapsulate that into user

`{       
“user” :{ 
        “name” : “helo”,
        “image” : “”,
language_id” : 1,
“relation_id”: 2
} 
}`

I'm new in android and stuck in this for two days if anyone know plzz help
Thanks in advance

**Comment by JakeWharton** [comment]
Retrofit doesn't deal with the body serialization. That is delegated to the serialization library of your choice. In this case you'll want to see help with Moshi, Gson, or Jackson on how to model your Java types to produce the desired JSON.
