### ISSUE TITLE
CompletableFutureCallAdapterFactory.java should be public.

### ISSUE THREAD

**Issue by sregan** [square/retrofit#2941]
Support to return CompletableFuture was added to retrofit so you don't have to use the new deprecated Java8CallAdapterFactory.java.  However the CompletableFutureCallAdapterFactory.class is currently package private.  I assume this should be public so that it can be added to the Retrofit call adapters.

**Comment by JakeWharton** [comment]
You can add the `RxJava2CallAdapter`. Is there anything that doesn't provide?

**Comment by sregan** [comment]
While RxJava would work, its features are not really necessary for our use cases.  What is the direction for CompletableFuture/Retrofit?  Is support for the feature intentionally deprecated with support of RxJava moving forward (If so, it should probably be documented as such on the existing CompletableFuture adapter(s)).

**Comment by JakeWharton** [comment]
I'm not sure why I replied that. The call adapter factory is added automatically, no? Those PRs to move it were merged without my review but they're still on my backlog to review prior to release.

**Comment by sregan** [comment]
OK.  Yes, it does look like it is added automatically.

**Comment by JakeWharton** [comment]
This will be released shortly
