### ISSUE TITLE
ObjectMapper setTimeZone not working

### ISSUE THREAD

**Issue by KingWu** [square/retrofit#2942]
i use jackson to convert this json
{"startDate":"2018-11-30T00:00:00.000Z"}

i want to set time zone to be UTC. 

try to use the following code
`ObjectMapper mapper = new ObjectMapper();
mapper.setTimeZone(TimeZone.getTimeZone("UTC"));`

But, not working. It still use the device's default timezone.

Try to call this
TimeZone.setDefault(TimeZone.getTimeZone("UTC"));

Then it is okay.
But, why?

**Comment by swankjesse** [comment]
Report to Jackson? This is unlikely to be caused by Retrofit.
