### ISSUE TITLE
Content-Type not changing

### ISSUE THREAD

**Issue by sagarmaiyad** [square/retrofit#2943]
I am requesting post request with formurlencoded. In which i am setting authorization and content-type is application/x-www-form-urlencoded.
but when i am checking log i can see that my content-type is still showing text/plain;charset=UTF-8.

Below is my code to request:

@FormUrlEncoded
    @POST("/api/private/card/list")
    Call<CardListResponse> cardList(@HeaderMap Map<String, String> headers, @Field("pager") String pager);

Where headers are:

Authorization: *****
Content-Type: application/x-www-form-urlencoded

**Comment by ketanMuttha** [comment]
I am also trying the same thing..  If we do this way, Content-Type is not getting added in the header. I think, we might need to use interceptor to fix this.

**Comment by JakeWharton** [comment]
I wrote some tests for this in #2964. If you think something isn't working, please write a failing test using those as a starting point.
