### ISSUE TITLE
Problem with gradle 4.6

### ISSUE THREAD

**Issue by MHKalantarian** [square/retrofit#2947]
I'm using latest gradle  `classpath 'com.android.tools.build:gradle:3.2.1'` & Retrofit 2.4.0
and I'm getting JavaSocketTimeout using Retrofit but with manual requests and postman its fine. Anyway to fix this?

**Comment by PromanSEW** [comment]
Latest Gradle is 4.10.2

**Comment by MHKalantarian** [comment]
Can you post me the gradle distribution url?

**Comment by JakeWharton** [comment]
It's not clear why you think this is a Retrofit problem. Socket timeouts come from a layer far below Retrofit and it has no control over them. If you want to increase the socket timeout, you can create an `OkHttpClient` instance with the desired timeouts and pass it to your `Retrofit.Builder`. Without more information, this sounds like normal network connectivity problems.
