### ISSUE TITLE
The call is cloned for each new subscriber: https://github.com/square/retrofit/blob/61dc1be80098699482afb1f553f8c63134ccb18f/retrofit-adapters/rxjava2/src/main/java/retrofit2/adapter/rxjava2/CallEnqueueObservable.java#L36-L37

### ISSUE THREAD

**Issue by nEdAy** [square/retrofit#2951]
All you should have to do is call `subscribe` twice. I just wrote tests for all Rx types which validate they can be subscribed to multiple times: #2912.

_Originally posted by @JakeWharton in https://github.com/square/retrofit/issues/2910#issuecomment-425458865_

Thanks Reply,

But I can't subscribe twice using 'extends DisposableObserver'.

the error logs as follows：

"It is not allowed to subscribe with a(n) " + consumer + " multiple times. Please create a fresh instance of " + consumer + " and subscribe that to the target source instead."

at EndConsumerHelper.setOnce(this.upstream, disposable, getClass())

And I want to use the same RecordingObserver instance(extends DisposableObserver) , as follows：
`

RecordingObserver<String> observer1 = observerRule.create();
observable.subscribe(observer1);
observer1.assertValue("Hi").assertComplete();
**observable.subscribe(observer1);**
observer1.assertValue("Hey").assertComplete();
`

The above error will occur in this test case.
I think it should be the problem I am using. So how do you subscribe to the same observer instance, or if the observer can clone a new instance?

**Comment by JakeWharton** [comment]
You cannot use the same observer twice. This contract is enforced by RxJava, not Retrofit. You'll need to call `create()` again to get a new instance.
