### ISSUE TITLE
Support okhttp3.Call.timeout()

### ISSUE THREAD

**Issue by adelnizamutdinov** [square/retrofit#2966]
https://github.com/square/okhttp/blob/c273b3be385383842e44d25d6b7ca137ff6b1076/okhttp/src/main/java/okhttp3/Call.java#L84-L91

I have one endpoint in the retrofit `interface` that needs an increased timeout. Currently I have to create a modified `OkHttpClient`, and then create an additional `interface` with an endpoint that needs the increased timeout.

It would be great to have annotation for that

**Comment by JakeWharton** [comment]
You don't actually have to do what you described to get per-service timeouts. There's two ways this can be done currently:

 1. Add a `@Headers` annotation with a synthetic header that specifies the timeout value on the service method. Read and strip the header in an interceptor. Update the timeout on the `chain` based on the header value before calling `chain.proceed`.

 2. Add a custom `@Timeout` annotation on the service method. In an interceptor, read the `Invocation.class` tag instance from the `Call` object and adjust the timeout on the `chain` before calling `chain.proceed`.

I'm not sure if we want to add static (i.e., annotation-based) and/or dynamic (i.e., parameter-based) timeouts. I'll have to think about it! And additional use cases are welcome.

**Comment by JakeWharton** [comment]
Suggestion 2 didn't work above, but this should: https://github.com/square/retrofit/issues/2982#issuecomment-456608496

**Comment by xchengDroid** [comment]
I think we can do like this.
```java
    @Retention(RetentionPolicy.RUNTIME)
    @Target(ElementType.METHOD)
    public @interface Timeout {
        int value();

        TimeUnit unit();
    }

    public interface ApiService {
        @Timeout(value = 100, unit = TimeUnit.MILLISECONDS)
        @GET("something")
        retrofit2.Call<String> getSomething();
    }

public class CallFactoryProxy implements Call.Factory {

    protected final Call.Factory delegate;

    public CallFactoryProxy(Call.Factory delegate) {
        Utils.checkNotNull(delegate, "delegate==null");
        this.delegate = delegate;
    }

    @Override
    public Call newCall(Request request) {
        Call call = delegate.newCall(request);
        Invocation tag = request.tag(Invocation.class);
        Method method = tag.method();
        Timeout timeout = method.getAnnotation(Timeout.class);
        if (timeout != null) {
            call.timeout().timeout(timeout.value(), timeout.unit());
        }
        return call;
    }
}
      // create retrofit
       OkHttpClient client = new OkHttpClient.Builder()
                .build();
        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl("https://xxxxx.com/")
                .callFactory(new CallFactoryProxy(client))
                .addConverterFactory(GsonConverterFactory.create())
                .build();

```

**Comment by xchengDroid** [comment]
or  dynamic  you can use @Header or @Tag and parse it from `newCall(Request request)`
