### ISSUE TITLE
Retrofit 2.0 API Spec (Working Draft)

### ISSUE THREAD

**Issue by JakeWharton** [square/retrofit#297]
This is a living spec for what will be v2 of Retrofit.
 
## Goals

 * Broaden the scope of how you can process successful responses and handle the results of various exceptions throughout the stack. Currently there's a mix of exceptions, wrapped types, and callbacks depending on the usage of synchronous or asynchronous API declarations.
 * Unify API declaration so that both synchronous and asynchronous consumption of a resource does not change its declaration.
 * Introduce better request and response interceptors which allow for both tweaks to existing requests or full on replacement (e.g., for signing purposes).
 * Allow simple request retry and cancel support without the need to talk to the `RestAdapter` or generated interface instance.
 * Completely decouple interface declaration parsing from request invocation and processing and expose the shim layer between the two as a extension-based system for customization. This will be used to (hopefully) facilitate RxJava integration as an extensions rather than being baked into the core of the library itself

### Annotation Processors

An annotation processor will be embedded inside the core artifact for compile-time verification of REST API interface declarations.

A second annotation processor will be provided as a separate artifact for full code generation of a class implementation of each API interface.

The `RestAdapter` will always do a read-through cached lookup for the generated classes since it has no knowledge of whether the code-gen processor was used and we don't want to place the burden on the caller either.

### Request Object

All interface declarations will be required to return an object through which all interaction will occur. The behavior of this object will be similar to a `Future` and will be generic typed (`T`) for the success response type (ref: #231).
```java
@GET("/foo")
Call<Foo> getFoo();
```

Callers can synchronously call `.execute()` which will return type `T`. Exceptions will be thrown for any error, network error, unsuccessful response, or unsuccessful deserialization of the response body. While these exceptions will likely extend from the same supertype, it's unclear as to whether that supertype should be checked or unchecked.
```java
interface Api {
  @GET("/{user}/tweets")
  Call<List<Tweet>> listTweets(@Path("user") String username);
}
```
```java
List<Tweet> tweets = api.listTweets("JakeWharton").execute();
```

Callers can also supply callbacks to this object for asynchronous notification of the response. The traditional `Callback<T>` of the current version of Retrofit will be available. One change will be that the error object passed to `failure` will not be the same exception as would be thrown in synchronous execution but rather something a bit more transparent to the underlying cause.
```java
interface Api {
  @GET("/{user}/tweets")
  Call<List<Tweet>> listTweets(@Path("user") String username);
}
```
```java
Call<List<Tweet>> c = api.listTweets("JakeWharton");
c.execute(new Callback<List<Tweet>>() {
  @Override public void success(List<Tweet> response) { }
  // ...
}
```

TODO describe error handling
```java
public abstract class ResponseCallback<T> {
  public abstract void success(T response);

  public void networkError(IOException e) {
    error(ErrorType.NETWORK, -1, e);
  }
  public void processingError(Exception e) {
    error(ErrorType.PROCESSING, -1, e);
  }
  public void httpError(int status, ...) {
    error(ErrorType.HTTP, status, e);
  }
  public void error(ErrorType errorType, int status, Exception e) {
    throw new RuntimeException(.., e);
  }

  public enum ErrorType { NETWORK, PROCESSING, HTTP }
}
```

The call object is also an obvious place for handling the retry and cancelation of requests. Both are a simple, no-args method on the object which can only be called at appropriate times.

 * `cancel()` is a no-op after the response has been received. In all other cases the method will set any callbacks to `null` (thus freeing strong references to the enclosing class if declared anonymously) and render the request object dead. All future interactions with the request object will throw an exception. If the request is waiting in the executor its `Future` will be cancelled so that it is never invoked. 

 * `retry()` will re-submit the request onto the backing executor without passing through any of the mutating pipeline described above. Retrying a request is only available after a network error or 5XX response. Attempting to retry a request that is currently in flight, after a non-5XX response, after an unexpected error, or after calling `cancel()` will throw an exception.

### Extension System

In order to facilitate libraries which offer semantics on both synchronous and asynchronous operations without requiring a wrapper, we will introduce a system which we will tentatively refer to as extensions. An extension instance will be registered with the `RestAdapter` and associate itself as handling an explicit interface method return type.

By default, Retrofit will install its own extension which handles the aforementioned `Call` type for both synchronous and asynchronous request execution.

The current (albeit experimentally denoted) RxJava integration will also be provided as an opt-in extension. This extension will register itself as handling the `Observable` type which will allow the declaration of interfaces which return this type.
```java
interface FooService {
  @GET("/foos")
  Observable<Foo> getFoo();
}
```

### And more...

TODO!

**Comment by sockeqwe** [comment]
A nice feature in 2.0 (or a later 2.x release) would be to **allow stale data ** on async calls. I guess it's more a okhttp thing.

```java
public @interface Get {
   public void staleData() default false;
    ...
}
```
If data has been found in cache (incl. expired) the success callback will be called with the (possibly expired) data. If the data from cache is expired, then the real http call will be executed and the success callback will be called for a second time (first time was with the expired data from cache). The main purpose is to display "old" data while loading fresh data. It would also help to implement something like "getting old data instead of no data if no network connection is available". 


Btw. I would like to help coding (once the specifications are clear) if a helping hand is needed.

**Comment by JakeWharton** [comment]
You can do that already.

@Header("Cache-Control: max-age=" Integer.MAX_VALUE)

**Comment by Jackponer** [comment]
I'm new in this area, I thank you for this information

**Comment by cy6erGn0m** [comment]
What about websocket support? Is there way to handle continuous websocket response via RxJava/Callback?

**Comment by laaptu** [comment]
Any release date for V 2.0. I am new to Retrofit and should I wait for V 2.0 to release or should I work with the current version V 1.9. I want `cancel` mechanism of V 2.0  to cancel the request.

**Comment by YuriHeupa** [comment]
Any updates about the v2.0 ? I really need the `cancel` feature, just because of this i'm not using more the nice retrofit :(

**Comment by JakeWharton** [comment]
No updates.

**Comment by sockeqwe** [comment]
Regarding RxJava: is there a reason why not using RxJava Schedulers instead of OkHttp async threading? Would be nice to be able to specify `subscribeOn()`  manually (i.E. for unit testing)

**Comment by JakeWharton** [comment]
OkHttp knows about transport which is much more important. Things like SPDY
and HTTP/2 and even connection reuse on normal HTTP are devalued by not
using its threading.

**Comment by mwajeeh** [comment]
@YuriHeupa I know you are asking for a proper cancel mechanism, I am waiting for it too. But for now this works perfectly for me, I am sure you might be doing something similar, if not, have a look at this. Just extend from this `NetworkingFragment`.


	public class NetworkingFragment extends BaseFragment {
		protected final CallbacksManager callbacksManager = new CallbacksManager();

		@Override
		public void onResume() {
			super.onResume();
			callbacksManager.resumeAll();
		}

		@Override
		public void onDestroyView() {
			callbacksManager.pauseAll();
			super.onDestroyView();
		}

		@Override
		public void onDestroy() {
			callbacksManager.cancelAll();
			super.onDestroy();
		}

		protected Service apiFor(CallbacksManager.CancelableCallback<?> callback) {
			callbacksManager.addCallback(callback);
              // return your retrofit API
			return Api.getService();
		}
	}

CallBackManager:

	public class CallbacksManager {
		private final Set<CancelableCallback> callbacks = new HashSet<>();

		public void cancelAll() {
			for (CancelableCallback callback : callbacks) {
				// false to avoid java.util.ConcurrentModificationException alternatively we can use
				// iterator
				callback.cancel(false);
			}
			callbacks.clear();
		}

		public void resumeAll() {
			final Iterator<CancelableCallback> iterator = callbacks.iterator();
			while (iterator.hasNext()) {
				boolean remove = iterator.next().resume();
				if (remove) {
					iterator.remove();
				}
			}
		}

		public void pauseAll() {
			for (CancelableCallback callback : callbacks) {
				callback.pause();
			}
		}

		public void addCallback(CancelableCallback<?> callback) {
			callbacks.add(callback);
		}

		private void removeCallback(CancelableCallback<?> callback) {
			callbacks.remove(callback);
		}

		public abstract class CancelableCallback<T> implements Callback<T> {
			private boolean canceled;
			private boolean paused;

			private T pendingT;
			private Response pendingResponse;
			private RetrofitError pendingError;

			public CancelableCallback() {
				this.canceled = false;
			}

			public void pause() {
				paused = true;
			}

			public boolean resume() {
				paused = false;
				// if callback was cancelled then no need to post pending results
				if (canceled) {
					return true;
				}
				if (pendingError != null) {
					onFailure(pendingError);
					// to make sure not to post it again
					pendingError = null;
					return true;
				} else if (pendingT != null) {
					onSuccess(pendingT, pendingResponse);
					// to make sure not to post it again
					pendingT = null;
					pendingResponse = null;
					return true;
				}
				return false;
			}

			public void cancel(boolean remove) {
				canceled = true;
				if (remove) {
					removeCallback(this);
				}
			}

			@Override
			public void success(T t, Response response) {
				if (canceled) {
					return;
				}
				if (paused) {
					pendingT = t;
					pendingResponse = response;
					return;
				}
				onSuccess(t, response);
				removeCallback(this);
			}

			@Override
			public void failure(RetrofitError error) {
				if (canceled) {
					return;
				}
				if (paused) {
					pendingError = error;
					return;
				}
				onFailure(error);
				removeCallback(this);
			}

			protected abstract void onSuccess(T t, Response response);

			protected abstract void onFailure(RetrofitError error);
		}
	}

Usage:

	private void fetchUser(String id) {
        final CallbacksManager.CancelableCallback<User> callback = callbacksManager.new CancelableCallback<User>() {
            @Override
            protected void onSuccess(User user, Response response) {
            }

            @Override
            protected void onFailure(RetrofitError error) {
            }
        };
		// this is only drawback of this approach, you need to pass your callback to your service interface as well as to 
		// Networking fragment for life cycle handling
        apiFor(callback).getData(id, callback);
    }

**Comment by ricechen** [comment]
@mwajeeh
thank you so much, you save my time.

**Comment by JakeWharton** [comment]
Most of this was done in #845. For everything else there's separate issues tracking it.

**Comment by Tooto** [comment]
when i can gat this with graddle?

**Comment by YuriHeupa** [comment]
@Tooto You can get the 2.0 snapshot from the Sonatype's snapshots repository, just add the following to your gradle file:
 
>repositories {
>    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
>}

And declare this on your dependencies:
>compile 'com.squareup.retrofit:retrofit:2.0.0-SNAPSHOT'

**Comment by jdreesen** [comment]
But be aware that the 2.0 API is far from stable and moving fast at the moment ;)

**Comment by felipecsl** [comment]
is there a separate issue for tracking the error handling implementation?

**Comment by JakeWharton** [comment]
Error handlers can be implemented as CallAdapters. There will be an example.

**Comment by stephanenicolas** [comment]
@jdreesen @JakeWharton @YuriHeupa, can the source code of 2.0 preview be seen somewhere ?
Even if it's just experimental..and moving fast.

**Comment by JakeWharton** [comment]
master

**Comment by stephanenicolas** [comment]
Wow :) Cool. Thx. Eager to try that.

**Comment by changyuheng** [comment]
See Also: [yongjhih/retrofit](https://github.com/yongjhih/retrofit)

**Comment by JakeWharton** [comment]
You cite Dagger 2. Google approached us about them spearheading Dagger 2
and we participated in both the design and development of it. You offered
no such interaction and instead eschewed the obvious work being done in
this repo to make some attempt to claim the version 2 of the same name with
a hero feature almost no one is asking for but retains all of the poor API
decisions of our version 1. Your efforts would have been appreciated on
this project instead of silently off in a fork. Unless you change the name,
do not link that project here again.

**Comment by yongjhih** [comment]
Sorry. No offense, it's just a experimental project. The naming/building were just following Google Dagger 2 without bad intention. You can found the description that is almost copied.

I thought introduce it after some projects tested it.
I do not seek appreciation. I'd like to make a right thing for development.
It is at your disposal. What name do you suppose? Or just remove it.

**Comment by DASAR** [comment]
Finally we have Canceling in Retrofit. That's awesome. How to cancel all currently ongoing requests?

**Comment by cooperkong** [comment]
Error handlers can be implemented as CallAdapters. There will be an example.

Where can I find such an example?
Cheers,

**Comment by liuxue0905** [comment]
[Converter!!!]It's better:
1 Can add Default Converter
2 Can handle Simple Retrun Type / Or supply Simple Converter:Like String,byte,Integer,Stream
3 Can Register Multi Converter for different Return Type

**Comment by samskiter** [comment]
Hi, I'm a little confused about where error handlers are but I've just been thinking about them in the context of autogenerated code. Would it be perhaps possible to define all the possible (known) paths of success (only one) and error (potentially a few) at compile time? Like defining a subclass of a responseCallback with the errorTypes I want to handle (400, 404, etc) annotated? so something like:

```
public interface Callback<T> {

  /** Successful HTTP response. */
  void success(T t, Response response);

  /**
   * Unsuccessful HTTP response due to network failure, non-2XX status code, or unexpected
   * exception.
   */
  void failure(RetrofitError error);
}
```

```
public interface UsersGetEndpointCallback extends Callback<User> {
  @HTTP(400)
  void failure400(My400BodyErrorType error);
}
```

I've not fully thought through how this would be connected up, but it would offer really good compile time guarantees that I've handled the error cases I care about.

**Comment by JakeWharton** [comment]
You don't need to generate that, just use an abstract class for your
callback, override onSuccess and onFailure, and call the more specific
abstract methods.

**Comment by samskiter** [comment]
Sure, I mean that it creates a more type-safe way to ensure errors are handled. I can't use the endpoint unless I handle the errors in a callback object and I get the deserialization of error bodies for free too, reducing boilerplace. Otherwise I end up documenting it:
```
/*
  Returns 400 is the user object is not get initialized. Body will be the standard JSON error object
  Returns 403 is the user is not authorized.
 */
@GET("/users/{user}")
void getUser(@Path("user") String user, Callback<User> cb);
```
And then handling the error, checking the errortype, deserializing the json.

When I say autogenerated, I mean from things like RAML or Swagger. These allow error cases to be defined just as thoroughly as success cases.

**Comment by ArslanAli7** [comment]
Hi Jack i am facing an issue when i try to run the app for the first time on a new device the first request doesn't execute,i have to send the request again to get the response,i am using retrofit version: retrofit:2.0.0-beta2,and in my code i am send a post request on success of which i am executing the get request,i am not using a custom version of okhttp,i am using the version which is build with retrofit already,i have tested on emulator as well android nexus 6 device.i am using methods like Call.eneque for async processing of request and i am calling these methods on button click without any use of asynctasks...,should i switch back to the previous version or there is issue with my code.waiting for your  response, keep up the good work!

**Comment by TobiasReich** [comment]
Hey there,
I really like using Retrofit for my network calls. Still I'm wondering if there is a good way of repeating a call only several times in case there is an error?
The idea is to try the same call for example only 3 times before trying other solutions. The clone method does not allow me to add any further values to it like an int "retriesLeft" or such things.
So is there a good way of solving this issue?
Thanks!

**Comment by swankjesse** [comment]
Consider using an OkHttp application interceptor.
https://github.com/square/okhttp/wiki/Interceptors

**Comment by sockeqwe** [comment]
> Consider using an OkHttp application interceptor.
> https://github.com/square/okhttp/wiki/Interceptors

this

OR

if your are using Retrofit + RxJava you could use [retry](http://reactivex.io/documentation/operators/retry.html) or [retryWhen](http://reactivex.io/RxJava/javadoc/rx/Observable.html#retryWhen(rx.functions.Func1)) operator
