### ISSUE TITLE
Download failed, url @Path encoded while server didn't support decode via http GET!

### ISSUE THREAD

**Issue by 1step2hell** [square/retrofit#2974]
# Bug
I developered a SNS share library, if a imageUrl will be shared,
download it with retrofit firstly and save it to local storage, then share it.
Most of the time, it works well.
But for some particular imageUrls, there is something wrong:
* Download failed, http 400 bad request.
* Download successed, but cannot be decode to bitmap.

As a contrast, I write another download method with OkHttp directly, it works well all the time.

Here is my retrofit download code:
```
public static void downloadByRetrofit(String imageUrl, final String dstPath) {
        String baseUrl = "";
        String path = "";
        try {
            URL url = new URL(imageUrl);
            baseUrl = url.getProtocol() + "://" + url.getAuthority() + "/";
            path = url.getPath();
        } catch (MalformedURLException e) {
            return;
        }
        OkHttpClient client = new OkHttpClient.Builder()
                .readTimeout(20000, TimeUnit.MILLISECONDS)
                .writeTimeout(20000, TimeUnit.MILLISECONDS)
                .addNetworkInterceptor(new HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.BODY))
                .build();
        new Retrofit.Builder()
                .baseUrl(baseUrl)
                .client(client)
                .build()
                .create(ServiceApi.class)
                .requestByRetrofit(path)
                .enqueue(new Callback<ResponseBody>() {
                    @Override
                    public void onResponse(Call<ResponseBody> call, Response<ResponseBody> response) {
                        saveRetrofitFile(response, dstPath);
                    }

                    @Override
                    public void onFailure(Call<ResponseBody> call, Throwable t) {
                        Log.e(TAG, "downloadByRetrofit onFailure:" + t.getMessage());
                    }
                });
    }

interface ServiceApi {
    @GET("{path}")
    Call<ResponseBody> requestByRetrofit(@Path("path") String path);
}

```

And the OkHttp log:

1. Download test imageUrl="https://www.baidu.com/img/bd_logo1.png";
```
D/OkHttp: --> GET https://www.baidu.com/%2Fimg%2Fbd_logo1.png http/1.1
D/OkHttp: Host: www.baidu.com
D/OkHttp: Connection: Keep-Alive
D/OkHttp: Accept-Encoding: gzip
D/OkHttp: User-Agent: okhttp/3.12.0
D/OkHttp: --> END GET
D/OkHttp: <-- 302 Found https://www.baidu.com/%2Fimg%2Fbd_logo1.png (55ms)
D/OkHttp: Cache-Control: max-age=86400
D/OkHttp: Connection: Keep-Alive
D/OkHttp: Content-Length: 222
D/OkHttp: Content-Type: text/html; charset=iso-8859-1
D/OkHttp: Date: Thu, 22 Nov 2018 01:40:48 GMT
D/OkHttp: Expires: Fri, 23 Nov 2018 01:40:48 GMT
D/OkHttp: Location: https://www.baidu.com/search/error.html
D/OkHttp: Server: Apache
```
As we see, the origin imageUrl `https://www.baidu.com/img/bd_logo1.png`
has been encoded to `https://www.baidu.com/%2Fimg%2Fbd_logo1.png`.
But the backend of BAIDU server didn't do the decode action, the encoded url cannot be founded.
Http 302, the backend redirect it to `https://www.baidu.com/search/error.html`.
At last, the download is still success, but I got the error url downloaded, it cannot be convert to bitmap.

2. Download test imageUrl="http://inews.gtimg.com/newsapp_bt/0/876781763/1000";
```
D/OkHttp: --> GET http://inews.gtimg.com/%2Fnewsapp_bt%2F0%2F876781763%2F1000 http/1.1
D/OkHttp: Host: inews.gtimg.com
D/OkHttp: Connection: Keep-Alive
D/OkHttp: Accept-Encoding: gzip
D/OkHttp: User-Agent: okhttp/3.12.0
D/OkHttp: --> END GET
D/OkHttp: <-- 400 Bad Request http://inews.gtimg.com/%2Fnewsapp_bt%2F0%2F876781763%2F1000 (54ms)
D/OkHttp: Server: ImgHttp3.0.0
D/OkHttp: Connection: keep-alive
D/OkHttp: Date: Thu, 22 Nov 2018 01:46:27 GMT
D/OkHttp: Last-Modified: Thu, 22 Nov 2018 01:40:00 GMT
D/OkHttp: Content-Type: text/plain
D/OkHttp: Content-Length: 0
D/OkHttp: X-ErrNo: -104
D/OkHttp: X-RtFlag: 1
D/OkHttp: Access-Control-Expose-Headers: X-Client-Ip
D/OkHttp: Access-Control-Expose-Headers: X-Server-Ip
D/OkHttp: Access-Control-Expose-Headers: X-Upstream-Ip
D/OkHttp: X-Client-Ip: 171.223.206.218
D/OkHttp: X-Server-Ip: 118.112.11.173
D/OkHttp: X-Upstream-Ip: 183.36.108.166:80
D/OkHttp: Keep-Alive: timeout=30
D/OkHttp: X-Cache-Lookup: Hit From Upstream
D/OkHttp: <-- END HTTP (0-byte body)
```
Same action this time, the original imageUrl has been encoded, and the server still didn't decode.
The difference is that this server didn't do redirection, it returns http 400 bad request.
The download failed, I got nothing.

You can found code here: [Gist](https://gist.github.com/1step2hell/8678598ce105d2e228dae9adf3bfe2e9), or just download [android sample](https://github.com/1step2hell/RetrofitUrlEncodeBug) and run it directly.
Please note that the test imageUrls are located in China, you might use a VPN because of the [GFW](https://en.wikipedia.org/wiki/Great_Firewall).

# Reason
I spend some time to figure it out, this bug occurs with two conditions:
1. the server didn't do the url decode-action while http GET request.
2. url was built by replacing @Path, and contains '/' or '%'.

The url meet condition 2 will be encoded in `RequestBuilder`(source code of Retrofit):
```
    private static String canonicalizeForPath(String input, boolean alreadyEncoded) {
        int codePoint;
        for (int i = 0, limit = input.length(); i < limit; i += Character.charCount(codePoint)) {
            codePoint = input.codePointAt(i);
            if (codePoint < 0x20 || codePoint >= 0x7f
                    || PATH_SEGMENT_ALWAYS_ENCODE_SET.indexOf(codePoint) != -1
                    || (!alreadyEncoded && (codePoint == '/' || codePoint == '%'))) {
                // Slow path: the character at i requires encoding!
                Buffer out = new Buffer();
                out.writeUtf8(input, 0, i);
                canonicalizeForPath(out, input, i, limit, alreadyEncoded);
                return out.readUtf8();
            }
        }

        // Fast path: no characters required encoding.
        return input;
    }
```
the encoded url will not be decode in server which meet condition 1, and two kind of response might be return:
* some servers could not find the corresponding url, return http 400 bad request directly.
* anothers redirect to the default error page and the error page was downloaded successfully.
  [Issue#2489](https://github.com/square/retrofit/issues/2489),  [Issue#1689](https://github.com/square/retrofit/issues/1689) and  [Issue#1946](https://github.com/square/retrofit/issues/1946) might be the same reason, because of the wrong url was downloaded.

# Solution
According to the analysis, there are three solutions:
1.  For the server, make it support decode-action while http GET request.
    Unfortunately I found a lot of servers didn't support it.
    eg. The test logo image "https://www.baidu.com/img/bd_logo1.png" belongs to BAIDU which is the biggest search website in China.
2.  For developers, set encoded=true through @Path
    ```
    //  @GET("{path}")
    //  Call<ResponseBody> requestByRetrofit(@Path("path") String path);

    @GET("{path}")
    Call<ResponseBody> requestByRetrofit(@Path(value="path",encoded=true) String path);
    ```
    It's hard to do this for people who didn't know this issue.
    The download might be success, but the result is totally wrong, people will spent a lot of time to dig this out.
3.  For Retrofit, modify method `canonicalizeForPath` in `RequestBuilder`:
    ```
    /**
     * remove modifier static,
     * don't encoded '/' and '%' if it's a http GET request.
     */
    private String canonicalizeForPath(String input, boolean alreadyEncoded) {
        int codePoint;
        for (int i = 0, limit = input.length(); i < limit; i += Character.charCount(codePoint)) {
            codePoint = input.codePointAt(i);
            if (codePoint < 0x20 || codePoint >= 0x7f
                    || PATH_SEGMENT_ALWAYS_ENCODE_SET.indexOf(codePoint) != -1
                    || (!alreadyEncoded && !"GET".equals(method) && (codePoint == '/' || codePoint == '%'))) {
                // Slow path: the character at i requires encoding!
                Buffer out = new Buffer();
                out.writeUtf8(input, 0, i);
                canonicalizeForPath(out, input, i, limit, alreadyEncoded);
                return out.readUtf8();
            }
        }

        // Fast path: no characters required encoding.
        return input;
    }
    ```
    This change fix this issue, but I'm not sure doing this could not importing other bugs.
    Or maybe you guys could find another better way.

**Comment by JakeWharton** [comment]
From your examples you need to be using `@Url` and not `@Path` as you seem to want to supply an entire relative URL and not a single path statement. 

That being said, there's no reason to use Retrofit here. You're not leveraging any of its features and it will actually make the download slower since the entire response body will be buffered in memory before being written out to the filesystem. If you use OkHttp directly you can stream the bytes directly to the filesystem.

**Comment by 1step2hell** [comment]
@JakeWharton Thank you.
The reason I used Retrofit is that I want to keep network request same in whole App, I do replace it with OkHttp later.
Also I try @Url, it works. I never used it before , it seems I misunderstanding @Path.
Again thanks.
