### ISSUE TITLE
JetifyTransform fails

### ISSUE THREAD

**Issue by naz-mul** [square/retrofit#2979]
10:53:48 > Transform converter-gson.jar (com.squareup.retrofit2:converter-gson:2.4.0) with JetifyTransform
10:53:48 ERROR: [TAG] Failed to resolve variable '${project.groupId}'
10:53:48 ERROR: [TAG] Failed to resolve variable '${project.version}'

**Comment by JakeWharton** [comment]
Please file a bug at b.android.com/new. Jetifier is an Android toolchain component and we have no control over its behavior.
