### ISSUE TITLE
Retrofit first request takes exact timeout to process

### ISSUE THREAD

**Issue by bolds07** [square/retrofit#2980]
What kind of issue is this?
 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

I'm using Retrofit and OkHttpClient to build a Rest API on Android.

Some time ago, i had noticed the very first request made by the api always take way longer to process than all others... At begining i didn't care because it was an acceptable time.

But suddenly the request time jumped to 60 SECONDS

All this time is waste client side, since I'm monitoring the server i see that the processing time takes less than 1 seconds...

I was wondering what change I made that could cause such high impact, then I realized that i changed the connection timeout of OkHttp.

I had changed the value from 10 seconds to 60 seconds just for testings...

I made some experiments setting the connectTimeout to many others values and ALWAYS the first request takes the time sighly above the timeout

Does anyone know what may cause this weird behavior? how to solve it?

PS. I needed to test the api on a desktop and this problem didnt occur, i mean it is only happening on android devices [i tried several] what is the cause?

here is an example
	```
OkHttpClient.Builder httpClientBuilder = new OkHttpClient.Builder();
 
	  httpClientBuilder.readTimeout(READ_TIMEOUT, TimeUnit.MILLISECONDS);
		httpClientBuilder.writeTimeout(WRITE_TIMEOUT, TimeUnit.MILLISECONDS);
		httpClientBuilder.connectTimeout(CONNECT_TIMEOUT, TimeUnit.MILLISECONDS);
		httpClientBuilder.retryOnConnectionFailure(true);
		httpClientBuilder.connectionPool(DEFAULT_CONNECTION_POOL);
		httpClientBuilder.followRedirects(false);
		
		this.service = new Retrofit.Builder().baseUrl(Constants.API_URL).addConverterFactory(GsonConverterFactory.create(set.getGson())).client(httpClientBuilder.build()).build().create(IService.class);
		//everything normal until here
		
		this.service.foo();//this method will take CONNECT_TIMEOUT plus some millis to process
		this.service.foo();//now this method will take only some millis to process
```

just to be clear the problem is 100% client side, im monitoring both sides and i'm sure server isn't taking any time to process and respond

also i tried to debug the inner code of retrofit and okhttp and seems when it is looking for a connection in the pool for the first time it really takes longer... i'm not sure i properly understood the code

**Comment by niwoshijie** [comment]
I have the same problem, especially with HTTPS

**Comment by JakeWharton** [comment]
Does the same behavior happen when making requests with `OkHttpClient` directly instead of through Retrofit?

**Comment by tusharvasudev** [comment]
I am facing the same issue... first call is slow then all the calls are fast... have both android and ios apps consuming the webservice, only facing this issue in android in which is using retrofit.

**Comment by warcello** [comment]
I'm also experiencing this issue.
It looks like it easily reproducible on API 22. Just need to turn Airplane mode ON and OFF and then make a request. 
In my case, it always takes about 2mins. On API 26 and 28 it's slightly faster but also happens.
I cannot reproduce it on API 19.

The issue does not exist when using OkHttpClient directly in my case.

I guess it can be connected to this issue: #2977

**Comment by knutigro** [comment]
I have the same problem.

**Comment by JakeWharton** [comment]
By virtue of the content of the initial issue, the fact that adjusting the connect timeout on OkHttp is also the length of time reflected on how long the initial call takes, this is an issue with OkHttp and its connections rather than with Retrofit. Retrofit just asks OkHttp to perform a request on its behalf, it has no knowledge of timeouts or how to speak HTTP at all.

If you can reliably reproduce, please file a bug on OkHttp.

**Comment by latifimehrdad** [comment]
I have the same problem.

**Comment by vishnusukumar14** [comment]
i have the same problem
