### ISSUE TITLE
Get String Response Bug

### ISSUE THREAD

**Issue by Lee-Wang-Jing** [square/retrofit#2984]
When I add  GsonConverterFactory first，then add ScalarsConverterFactory，I can't receive String  onResponse Callback！

When I add  ScalarsConverterFactoryfirst，then add GsonConverterFactory ，I can receive String onResponse Callback！

I use 2.4.0 version and 2.5.0 version ，has reappeared

**Comment by JakeWharton** [comment]
This is documented behavior of the JSON converters: https://github.com/square/retrofit/blob/master/retrofit-converters/gson/src/main/java/retrofit2/converter/gson/GsonConverterFactory.java#L31-L34

They match all types and thus must be last in the chain.
