### ISSUE TITLE
Append parameter to dynamic url

### ISSUE THREAD

**Issue by Asendo316** [square/retrofit#2985]
I'm still beginner on retrofit API for android, im trying to pass a variable into my dynamic url but it adds extra characters to it these characters are "&=".

This is what the endpoint im trying to consume looks like:

https://www.example.com/api/index.php?/Playlists/getTracks/00978d67f6933af10ec8bd8045f089a4/0673CC13-476A-4786-BF27-13ADD9C44261/9392

where "9232" is the id i am trying to pass. However when i use the retrofit library this is what my generated Url looks like:

https://www.example.com/api/index.php?/Playlists/getTracks/00978d67f6933af10ec8bd8045f089a4/0673CC13-476A-4786-BF27-13ADD9C44261/&=9392

Notice the **&=** being attached to the Id im sending

`// Method that receives id and calls the retrofit API
private void getPlaylist(String id) {
    /*Create handle for the RetrofitInstance interface*/
    GetPlaylistRetrofitInterface playlistService = PlaylistClientInstance.getRetrofitInstance().create(GetPlaylistRetrofitInterface.class);

    Call<List<Playlists>> call = playlistService.getPlaylist(id);
    Log.d("URL", "getPlaylist: " + call.request().url());
    call.enqueue(new Callback<List<Playlists>>() {
        @Override
        public void onResponse(Call<List<Playlists>> call, Response<List<Playlists>> response) {
            myProgressBar.setVisibility(View.GONE);
            populatePlayList(response.body());
        }

        @Override
        public void onFailure(Call<List<Playlists>> call, Throwable throwable) {
            myProgressBar.setVisibility(View.GONE);
            Log.d("onFailure", "onFailure: " + throwable);
            Toast.makeText(getActivity(), throwable.getMessage(), Toast.LENGTH_LONG).show();
        }
    });
}`

And this is the interface where i am receiving the url id and attaching it to the endpoint

`public interface GetPlaylistRetrofitInterface {
    @GET("index.php?/Playlists/getTracks/00978d67f6933af10ec8bd8045f089a4/0673CC13-476A-4786-BF27-13ADD9C44261/")
    Call<List<Playlists>> getPlaylist(@Query(value = "") String id);
}`

I have tried using @Path in my interface 

`public interface GetPlaylistRetrofitInterface {
    @GET("index.php?/Playlists/getTracks/00978d67f6933af10ec8bd8045f089a4/0673CC13-476A-4786-BF27-13ADD9C44261/{id}")
    Call<List<Playlists>> getPlaylist(@Path("id") String id);
}`

However it made my app crash with this error:

` java.lang.RuntimeException: Unable to start activity ComponentInfo{com.demoapp.HomeActivity}:
 java.lang.IllegalArgumentException: URL query string "/Playlists/getTracks/00978d67f6933af10ec8bd8045f089a4/0673CC13-476A-4786-BF27-13ADD9C44261/{id}" must not have replace block. For dynamic query parameters use @Query.
            for method GetPlaylistRetrofitInterface.getPlaylist
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
            at android.app.ActivityThread.-wrap11(Unknown Source:0)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
            at android.os.Handler.dispatchMessage(Handler.java:106)
            at android.os.Looper.loop(Looper.java:164)
            at android.app.ActivityThread.main(ActivityThread.java:6494)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

Thanks in Advance

**Comment by JakeWharton** [comment]
This is working as intended as far as Retrofit is concerned because everything after `?` is the query part of the URL. When you add a parameter to the query part they're separated by `&` and the name and value split with `=`.

There's all kinds of ways to work around this. In order to use Retrofit's request creation assistance you can either deploy a URL rewriter to the server so that you can use normal request paths and have them rewritten to all go to `index.php` as an implementation detail or you can use an OkHttp interceptor to rewrite a normal request path to go to `index.php`. Otherwise you can manually manipulate the URL before passing it to the `@Url` parameter and don't actually use Retrofit for creating the request URL.

But as it stands now, Retrofit doesn't offer any way to build the URL as desired because of the use of the query part of the URL for path information.
