### ISSUE TITLE
Please help: post params&json body what can i do?

### ISSUE THREAD

**Issue by litoo** [square/retrofit#2988]
I want to post web request like this https://xx.com/square/retrofit/issues/new?paramone=one&paramtwo=two also with a jsonbody,but i cant use @Filed(FormUrlEncoded)&@Body together . what can i do? please

**Comment by JakeWharton** [comment]
This is a usage question which is generally more appropriate for StackOverflow. GitHub issues are reserved for bug reports with test cases or samples, or new feature requests. You can use the 'retrofit' tag which is monitored by us and many library users. Feel free to link the asked question back here on the issue.

**Comment by litoo** [comment]
Oh,I'm sorry. I will link the asked question back
