### ISSUE TITLE
Retrofit 2.5 Android build error: Task transformClassesWithAndroidGradleClassShrinkerForRelease failed

### ISSUE THREAD

**Issue by alixwar** [square/retrofit#2992]
My project (pure Java, no Kotlin) used Retrofit2 2.3 (not yet tried 2.4) but when upgrading to 2.5 the project does not build and I see the following in the build log:

``` 
> Task :submodule1:mergeReleaseConsumerProguardFiles
> Task :submodule2:mergeReleaseConsumerProguardFiles
> Task :submodule3:mergeReleaseConsumerProguardFiles
> Task :submodule4:mergeReleaseConsumerProguardFiles
> Task :submodule5:mergeReleaseConsumerProguardFiles
retrofit2/BuiltInConverters$UnitResponseBodyConverter references unknown class: kotlin/Unit
retrofit2/-KotlinExtensions references unknown class: kotlin/jvm/internal/Intrinsics

> Task :app:transformClassesWithAndroidGradleClassShrinkerForRelease
retrofit2/BuiltInConverters references unknown class: kotlin/Unit
retrofit2/-KotlinExtensions references unknown class: kotlin/Metadata

> Task :application:transformClassesWithAndroidGradleClassShrinkerForRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':application:transformClassesWithAndroidGradleClassShrinkerForRelease'.
> Warnings found during shrinking, please use -dontwarn or -ignorewarnings to suppress them.
```

My config:
Multi-module Gradle (Android) project
One of the submodules uses Retrofit2. 
```
    buildTypes {
        release {
            minifyEnabled true
            useProguard false
...
```
Android Gradle Plugin: 3.2.1

**Comment by alixwar** [comment]
My problem was more generic than this. But it seems that the ProGuard configuration must be changed in 2.5. Will re-open if this is still an issue

**Comment by 2862339302** [comment]
proguard-rules.pro

# Guarded by a NoClassDefFoundError try/catch and only used when on the classpath.
-dontwarn kotlin.Unit

# Top-level functions that can only be used by Kotlin.
-dontwarn retrofit2.-KotlinExtensions

**Comment by JakeWharton** [comment]
Looks like you need `-dontwarn kotlin.**`. I'm not going to update the rules until #2886 lands and I'm not sure we'll even be able to cover all the types referenced without such a ridiculous wildcard.
