### ISSUE TITLE
GsonConverterFactory does not escape HTML characters.. what Gson normally does!

### ISSUE THREAD

**Issue by Wanjuuuuu** [square/retrofit#3001]
Hi, I'm recently working on my project with Retrofit and Gson.

I found an issue in GsonConverterFactory class.

Gson encodes HTML escape characters in a different way as default.

e.g. "=" -> "\u003"

To disable this setting,

`Gson gson = new GsonBuilder().disableHTMLEscaping().create(); `

is necessary.

I used GsonConverterFactory to parse request body.

```
Retrofit.Builder retrofitBuilder = new Retrofit.Builder()
				.baseUrl(UrlDetails.getUrl())
				.addConverterFactory(GsonConverterFactory.create());
```

And my request body included some String type data which are URLs with escape characters.

I checked GsonConverterFactory code, and it was just using a normal gson without disabling setting.

```
  public static GsonConverterFactory create() {
    return create(new Gson());
  }
```

However, the escape characters of sended request body was not encoded.

I checked it with tcp dump from my device.

Since I wanted to encode them in an original way, I tried to create converter with an already-made gson.

```
Gson gson = new GsonBuilder().create(); 

Retrofit.Builder retrofitBuilder = new Retrofit.Builder()
				.baseUrl(UrlDetails.getUrl())
				.addConverterFactory(GsonConverterFactory.create(gson));
```

However, it didn't encode HTML escapes...

It means,

```
  @SuppressWarnings("ConstantConditions") // Guarding public API nullability.
  public static GsonConverterFactory create(Gson gson) {
    if (gson == null) throw new NullPointerException("gson == null");
    return new GsonConverterFactory(gson);
  }
```

made-gson wasn't used to convert body.

Could you tell the reason why GsonConverterFactory works strangely?

**Comment by JakeWharton** [comment]
This is a Gson bug. Please file a bug on the Gson project. It's likely because we manually look up the adapter and call `newJsonWriter` instead of just calling `fromJson`.

**Comment by sshock** [comment]
Upstream issue: https://github.com/google/gson/issues/1452
