### ISSUE TITLE
json document was not fully consumed 

### ISSUE THREAD

**Issue by ShakeelAhmed210** [square/retrofit#3004]
Hello, I am using retrofit2. 
Here is my retrofit client

  private static Gson gson = new GsonBuilder()
            .setLenient()
            .create();

    public static Retrofit getClient() {
        if (retrofit == null) {
            retrofit = new Retrofit.Builder()
                    .baseUrl(BASE_URL_V1)
                    .addConverterFactory(GsonConverterFactory.create(gson))
                    .build();
        }
        return retrofit;
    }

It is working fine on API 21 and all higher versions. But it is giving the error on API level 19 "json document was not fully consumed". I am using retrofit2 version 2.4.0 and converter-gson:2.4.0. I have searched on StackOverflow and found an answer https://stackoverflow.com/questions/42386250/android-retrofit-2-0-json-document-was-not-fully-consumed  but this solution is not working. I don't know why it's not working on API 19. Can anyone please help.

**Comment by JakeWharton** [comment]
There's not enough information here to diagnose the problem, but it's unlikely to be in Retrofit itself.

This exception occurs when Gson does not fully consume the response body which usually indicates a bug in a custom type adapter. Without an example response body, your JSON model objects, and the custom type adapters its impossible to know where the problem lies.

**Comment by MortezaNedaei** [comment]
This appeared for me when I wanted to receive a string response from retrofit without any model class; and it fixed by this retrofit library :
implementation 'com.squareup.retrofit2:converter-scalars:2.5.0'

**Comment by ramakrishnajoshi** [comment]
Originally answered here : https://stackoverflow.com/a/59298779/8956093

Looks like the API response is not a valid JSON. To map the response, map it String class and then convert it to model.

**For parsing JSON response, we use GsonConverterFactory.**

**For parsing JSONP or String or invalid JSON response, we should use ScalarConverterFactory.**

If you use say flatMap to call JSON API followed by JSONP API then use both GsonConverterFactory(needed for JSON) and ScalarConverterFactory(needed for JSONP).

Make sure you have below dependencies in your gradle : 

    implementation 'com.squareup.retrofit2:converter-gson:2.5.0'
    //For serialising JSONP add converter-scalars
    implementation 'com.squareup.retrofit2:converter-scalars:2.1.0'
    //An Adapter for adapting RxJava 2.x types.
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.2.0'

Add converterFactories to retrofit and use setLenient() while building Gson to get rid of error `JSON document was not fully consumed.`

    val gson = GsonBuilder()
                .setLenient()
                .create()

    val retrofit = Retrofit.Builder()
                .baseUrl("http://api.flickr.com/")
                .client(builder.build())
                .addConverterFactory(ScalarsConverterFactory.create()) //important
                .addConverterFactory(GsonConverterFactory.create(gson))
                .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
                .build()

    @GET("end-point/to/some/jsonp/url")
    fun getJsonpData() : Observable<String>

Use **converters** to convert JSONP to get JSON by removing prefix and suffix present in JSONP.
And then convert the string to your data model via

    SomeDataModel model = Gson().fromJson<SomeDataModel>(jsonResponse,
                SomeDataModel::class.java)

**Comment by afj95** [comment]
I got this problem when my API was response string and i solved it by make the API response Void not string

**Comment by NehaKushwah993** [comment]
Also I found out that order also needs to be same 

            .addConverterFactory(ScalarsConverterFactory.create()) //important
            .addConverterFactory(GsonConverterFactory.create(gson))

It wont work if GSON is on top like following :


            .addConverterFactory(GsonConverterFactory.create(gson))
            .addConverterFactory(ScalarsConverterFactory.create()) //important

**Comment by Grandolf49** [comment]
> Also I found out that order also needs to be same
> 
> ```
>         .addConverterFactory(ScalarsConverterFactory.create()) //important
>         .addConverterFactory(GsonConverterFactory.create(gson))
> ```
> 
> It wont work if GSON is on top like following :
> 
> ```
>         .addConverterFactory(GsonConverterFactory.create(gson))
>         .addConverterFactory(ScalarsConverterFactory.create()) //important
> ```

Thanks @NehaKushwah993 This worked for me. Just by putting `ScalarsConverterFactory` above GsonFactory solved the Issue!

**Comment by afj95** [comment]
> This appeared for me when I wanted to receive a string response from retrofit without any model class; and it fixed by this retrofit library :
> implementation 'com.squareup.retrofit2:converter-scalars:2.5.0'
> 
> ```
>         Retrofit retrofit = new Retrofit.Builder()
>                 .baseUrl(BASE_URL)
>                 .client(okHttpClient)
>                 **.addConverterFactory(ScalarsConverterFactory.create())**
>                 .addConverterFactory(GsonConverterFactory.create())
>                 .build();
> ```

Thank yoooouuuuuu it worked for me

**Comment by chenGit1763113879QQ** [comment]
When ERROR


`Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $,com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $`

I set 


` .addConverterFactory(GsonConverterFactory.create(new GsonBuilder().setLenient().create()))`

then ERROR


`JSON document was not fully consumed.,com.google.gson.JsonIOException: JSON document was not fully consumed.`


A built-in iterator that will iterate through all the converters if not found; But gsonconvert matches a lot

Putting the converter ScalarsConverterFactory first can solve this problem temporarily

 ```
       .addConverterFactory(ScalarsConverterFactory.create()) //important
        .addConverterFactory(GsonConverterFactory.create(gson))

```

you can see 

https://github.com/square/retrofit/blob/6b6984e9dd683bff6cdb5931694e1b8efc3533ae/retrofit-converters/gson/src/main/java/retrofit2/converter/gson/GsonResponseBodyConverter.java#L38

Is this the stream not closing or is it the reason? Or change it to something like this

```
try (??? InputStream()) {
// ...
}
```

**Comment by 1dina** [comment]
> This appeared for me when I wanted to receive a string response from retrofit without any model class; and it fixed by this retrofit library : implementation 'com.squareup.retrofit2:converter-scalars:2.5.0'
> 
> ```
>         Retrofit retrofit = new Retrofit.Builder()
>                 .baseUrl(BASE_URL)
>                 .client(okHttpClient)
>                 **.addConverterFactory(ScalarsConverterFactory.create())**
>                 .addConverterFactory(GsonConverterFactory.create())
>                 .build();
> ```

you saved my life!
