### ISSUE TITLE
Dependency conflicts on com.squareup.okio:okio.jar, causing unexpected hehaviors

### ISSUE THREAD

**Issue by HelloCoCooo** [square/retrofit#3018]
Hi, there are multiple versions of **com.squareup.okio:okio:jar** in **retrofit-parent-2.5.0**. As shown in the following dependency tree, according to Maven's “nearest wins” strategy, only **com.squareup.okio:okio:jar:1.13.0** can be loaded, and **com.squareup.okio:okio:jar:1.15.0** will be shadowed.

As **com.squareup.okio:okio:jar:1.15.0** is missing during the build process, method **retrofit2.converter.moshi.MoshiConverterFactory: retrofit2.Converter responseBodyConverter(java.lang.reflect.Type,java.lang.'annotation'.Annotation[],retrofit2.Retrofit)** actually references method **okio.RealBufferedSource: int select(okio.Options)** in the unexpected version **com.squareup.okio:okio:jar:1.13.0**  via the following invocation path:

`<retrofit2.converter.moshi.MoshiConverterFactory: retrofit2.Converter responseBodyConverter(java.lang.reflect.Type,java.lang.'annotation'.Annotation[],retrofit2.Retrofit)> C:\Users\Flipped\Desktop\project\moshi\.\target\classes
<com.squareup.moshi.Moshi: com.squareup.moshi.JsonAdapter adapter(java.lang.reflect.Type,java.util.Set)> C:\Users\Flipped\.m2\repository\com\squareup\moshi\moshi\1.5.0\moshi-1.5.0.jar
<com.squareup.moshi.Moshi$Builder$2: com.squareup.moshi.JsonAdapter create(java.lang.reflect.Type,java.util.Set,com.squareup.moshi.Moshi)> C:\Users\Flipped\.m2\repository\com\squareup\moshi\moshi\1.5.0\moshi-1.5.0.jar
<com.squareup.moshi.Util: boolean isAnnotationPresent(java.util.Set,java.lang.Class)> C:\Users\Flipped\.m2\repository\com\squareup\moshi\moshi\1.5.0\moshi-1.5.0.jar
<okhttp3.Cache$2: boolean hasNext()> C:\Users\Flipped\.m2\repository\com\squareup\okhttp3\okhttp\3.12.0\okhttp-3.12.0.jar
<okio.RealBufferedSource: java.lang.String readUtf8LineStrict()> C:\Users\Flipped\.m2\repository\com\squareup\okio\okio\1.13.0\okio-1.13.0.jar
<okio.RealBufferedSource: java.lang.String readUtf8LineStrict(long)> C:\Users\Flipped\.m2\repository\com\squareup\okio\okio\1.13.0\okio-1.13.0.jar
<okio.RealBufferedSource: boolean request(long)> C:\Users\Flipped\.m2\repository\com\squareup\okio\okio\1.13.0\okio-1.13.0.jar
<okhttp3.internal.cache.CacheInterceptor$1: long read(okio.Buffer,long)> C:\Users\Flipped\.m2\repository\com\squareup\okhttp3\okhttp\3.12.0\okhttp-3.12.0.jar
<okhttp3.Cache$CacheRequestImpl: void abort()> C:\Users\Flipped\.m2\repository\com\squareup\okhttp3\okhttp\3.12.0\okhttp-3.12.0.jar
<okhttp3.internal.cache.DiskLruCache$Editor: void abort()> C:\Users\Flipped\.m2\repository\com\squareup\okhttp3\okhttp\3.12.0\okhttp-3.12.0.jar
<okhttp3.internal.cache.DiskLruCache: void completeEdit(okhttp3.internal.cache.DiskLruCache$Editor,boolean)> C:\Users\Flipped\.m2\repository\com\squareup\okhttp3\okhttp\3.12.0\okhttp-3.12.0.jar
<okhttp3.internal.NamedRunnable: void run()> C:\Users\Flipped\.m2\repository\com\squareup\okhttp3\okhttp\3.12.0\okhttp-3.12.0.jar
<okhttp3.RealCall$AsyncCall: void execute()> C:\Users\Flipped\.m2\repository\com\squareup\okhttp3\okhttp\3.12.0\okhttp-3.12.0.jar
<retrofit2.OkHttpCall$1: void onResponse(okhttp3.Call,okhttp3.Response)> C:\Users\Flipped\.m2\repository\com\squareup\retrofit2\retrofit\2.5.0\retrofit-2.5.0.jar
<retrofit2.OkHttpCall: retrofit2.Response parseResponse(okhttp3.Response)> C:\Users\Flipped\.m2\repository\com\squareup\retrofit2\retrofit\2.5.0\retrofit-2.5.0.jar
<retrofit2.converter.moshi.MoshiResponseBodyConverter: java.lang.Object convert(java.lang.Object)> C:\Users\Flipped\Desktop\project\moshi\.\target\classes
<retrofit2.converter.moshi.MoshiResponseBodyConverter: java.lang.Object convert(okhttp3.ResponseBody)> C:\Users\Flipped\Desktop\project\moshi\.\target\classes
<com.squareup.moshi.ClassJsonAdapter: java.lang.Object fromJson(com.squareup.moshi.JsonReader)> C:\Users\Flipped\.m2\repository\com\squareup\moshi\moshi\1.5.0\moshi-1.5.0.jar
<com.squareup.moshi.JsonUtf8Reader: int selectName(com.squareup.moshi.JsonReader$Options)> C:\Users\Flipped\.m2\repository\com\squareup\moshi\moshi\1.5.0\moshi-1.5.0.jar
<okio.RealBufferedSource: int select(okio.Options)>
`

By further analyzing, the expected callee **okio.RealBufferedSource: int select(okio.Options)**  in shadowed version **com.squareup.okio:okio:jar:1.15.0**, have different implementations from the actual callees with the same signatures (same method names, same paremeters) included in the unexpected (but actual loaded) version **com.squareup.okio:okio:jar:1.13.0**, which leads to different behaviors.

**Solution:**
Use the newer version com.squareup.okio:okio:jar:1.15.0 to keep the version consistency.

Dependency tree----
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ converter-moshi ---
[INFO] com.squareup.retrofit2:converter-moshi:jar:2.5.0
[INFO] +- com.squareup.retrofit2:retrofit:jar:2.5.0:compile
[INFO] |  \- com.squareup.okhttp3:okhttp:jar:3.12.0:compile
[INFO] |     \- **(com.squareup.okio:okio:jar:1.15.0:compile - omitted for conflict with 1.13.0)**
[INFO] +- com.squareup.moshi:moshi:jar:1.5.0:compile
[INFO] |  \- **com.squareup.okio:okio:jar:1.13.0:compile**
[INFO] +- com.google.code.findbugs:jsr305:jar:3.0.2:provided
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- com.squareup.okhttp3:mockwebserver:jar:3.12.0:test
[INFO] |  +- (com.squareup.okhttp3:okhttp:jar:3.12.0:test - omitted for duplicate)
[INFO] |  \- (junit:junit:jar:4.12:test - omitted for duplicate)
[INFO] \- org.assertj:assertj-core:jar:1.7.0:test

Best regards,
Coco

**Comment by HelloCoCooo** [comment]
Code snippet of **okio.RealBufferedSource: int select(okio.Options)** in **com.squareup.okio:okio:jar:1.13.0**:

**Comment by HelloCoCooo** [comment]
May I pull a request?

**Comment by JakeWharton** [comment]
Sure.
