### ISSUE TITLE
Attempt to invoke virtual method 'retrofit2.Converter retrofit2.Converter$Factory.stringConverter(java.lang.reflect.Type, java.lang.annotation.Annotation[], retrofit2.Retrofit)' on a null object reference

### ISSUE THREAD

**Issue by ginderAtWindsribe** [square/retrofit#3023]
Dependencies:  
    implementation 'com.squareup.retrofit2:retrofit:2.5.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.5.0'
    implementation 'com.squareup.retrofit2:converter-scalars:2.5.0'
    implementation 'android.arch.persistence.room:rxjava2:1.1.1'
 
Retrofit Builder:
mRetrofitBuilder.baseUrl(url)
                .addConverterFactory(GsonConverterFactory.create())
                .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
                .addConverterFactory(ScalarsConverterFactory.create())
                .client(mHttpClientBuilder.build())
                .build().create(WindApiInterface.class);

Log: 

retrofit2.Retrofit.stringConverter (Retrofit.java:362)
retrofit2.RequestFactory$Builder.parseParameterAnnotation (RequestFactory.java:460)
retrofit2.RequestFactory$Builder.parseParameter (RequestFactory.java:295)
retrofit2.RequestFactory$Builder.build (RequestFactory.java:182)
retrofit2.RequestFactory.parseAnnotations (RequestFactory.java:65)
retrofit2.ServiceMethod.parseAnnotations (ServiceMethod.java:25)
retrofit2.Retrofit.loadServiceMethod (Retrofit.java:168)
retrofit2.Retrofit$1.invoke (Retrofit.java:147)
java.lang.reflect.Proxy.invoke (Proxy.java:913)
$Proxy4.getSession (Unknown Source)
com.windscribe.vpn.apimodel.ApiCallManager.getSessionGeneric (ApiCallManager.java:1211)
com.windscribe.vpn.windscribe.WindscribePresenterImpl.onStart (WindscribePresenterImpl.java:488)
com.windscribe.vpn.windscribe.WindscribeActivity.onStart (WindscribeActivity.java:681)
android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1339)
android.app.Activity.performStart (Activity.java:7403)
android.app.Activity.performRestart (Activity.java:7477)
android.app.ActivityThread.handleWindowVisibility (ActivityThread.java:4918)
android.app.ActivityThread.-wrap30 (Unknown Source)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2033)
android.os.Handler.dispatchMessage (Handler.java:108)
android.os.Looper.loop (Looper.java:166)
android.app.ActivityThread.main (ActivityThread.java:7529)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:245)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:921)

Issue:

Attempt to invoke virtual method 'retrofit2.Converter retrofit2.Converter$Factory.stringConverter(java.lang.reflect.Type, java.lang.annotation.Annotation[], retrofit2.Retrofit)' on a null object reference

App crashes when parsing results. All results are Json responses. It does not happen all times. During testing error was not reproducible . Thousands of crashes are gets reported every day.   Please help.

**Comment by JakeWharton** [comment]
Are you doing anything with `Retrofit.Builder.converterFactories()`. I struggle to see how `null` could make it inside the collection otherwise.

**Comment by JakeWharton** [comment]
Or if you have an example project that demonstrates this that would be immensely helpful.

**Comment by ginderAtWindsribe** [comment]
This is the call we make. 


 return mWindApiFactory.createApi(NetworkKeyConstants.API_ENDPOINT)
                .getMyIP(queryMap)
                .onErrorResumeNext(new Function<Throwable, SingleSource<ResponseBody>>() {
                    @Override
                    public SingleSource<ResponseBody> apply(final Throwable throwable) {
                        if (!(throwable instanceof HttpException)) {
                            
                            return mWindApiFactory.createApi(backupApiEndPoint.get(0)).getMyIP(queryMap);
                        } else {
                            return Single.fromCallable(new Callable<ResponseBody>() {
                                @Override
                                public ResponseBody call() {
                                    return ((HttpException) throwable).response().errorBody();
                                }
                            });
                        }
                    }
                })
                .onErrorResumeNext(new Function<Throwable, SingleSource<ResponseBody>>() {
                    @Override
                    public SingleSource<ResponseBody> apply(final Throwable throwable) {
                        if (!(throwable instanceof HttpException)) {
                            
                            return mWindApiFactory.createApi(backupApiEndPoint.get(1)).getMyIP(queryMap);
                        } else {
                            return Single.fromCallable(new Callable<ResponseBody>() {
                                @Override
                                public ResponseBody call() {
                                    return ((HttpException) throwable).response().errorBody();
                                }
                            });
                        }
                    }
                })
                .onErrorResumeNext(new Function<Throwable, SingleSource<ResponseBody>>() {
                    @Override
                    public SingleSource<ResponseBody> apply(final Throwable throwable) {
                        if (!(throwable instanceof HttpException)) {
                            
                            return mWindApiFactory.createApi(backupApiEndPoint.get(2)).getMyIP(queryMap);
                        } else {
                            return Single.fromCallable(new Callable<ResponseBody>() {
                                @Override
                                public ResponseBody call() {
                                    return ((HttpException) throwable).response().errorBody();
                                }
                            });
                        }
                    }
                })
                .onErrorResumeNext(new Function<Throwable, SingleSource<ResponseBody>>() {
                    @Override
                    public SingleSource<ResponseBody> apply(final Throwable throwable) {
                        if (!(throwable instanceof HttpException)) {
                           
                            if (accessIp1 != null) {
                                return mWindCustomFactory.createCustomCertApi("https://" + accessIp1).getMyIP(queryMap);
                            } else {
                                apiManagerLog.info(fTAG + "No access ip in storage, getting access IPs and retrying...");
                                return getAccessIp(queryMap)
                                        .flatMap(new Function<GenericResponseClass<AccessIpResponse, ApiErrorResponse>, SingleSource<ResponseBody>>() {
                                            @Override
                                            public SingleSource<ResponseBody> apply(GenericResponseClass<AccessIpResponse, ApiErrorResponse> accessIpResponse) {
                                                if (accessIpResponse.getDataClass() != null) {
                                                    
                                                    return mWindCustomFactory.createCustomCertApi("https://" + accessIpResponse.getDataClass().getHosts().get(0)).getMyIP(queryMap)
                                                            .onErrorResumeNext(mWindCustomFactory.createCustomCertApi("https://" + accessIpResponse.getDataClass()
                                                                    .getHosts().get(1)).getMyIP(queryMap));

                                                } else if (accessIpResponse.getErrorClass() != null) {
                                                    apiManagerLog.debug(fTAG + " Server returned error response. Response: " + accessIpResponse.getErrorClass().toString());
                                                    return null;
                                                } else {
                                                    apiManagerLog.debug(fTAG + " Unknown Error.");
                                                    return null;
                                                }
                                            }
                                        });
                            }
                        } else {
                            return Single.fromCallable(new Callable<ResponseBody>() {
                                @Override
                                public ResponseBody call() {
                                    return ((HttpException) throwable).response().errorBody();
                                }
                            });
                        }
                    }
                })
                .onErrorResumeNext(new Function<Throwable, SingleSource<ResponseBody>>() {
                    @Override
                    public SingleSource<ResponseBody> apply(final Throwable throwable) {
                        if (!(throwable instanceof HttpException)) {
                            apiManagerLog.info(fTAG + "Failed to get IP using access ip 1. " + throwable.getLocalizedMessage());

                            apiManagerLog.info(fTAG + "Trying access ip endpoint 2: " + accessIp2);
                            if (accessIp2 != null) {
                                return mWindCustomFactory.createCustomCertApi("https://" + accessIp2).getMyIP(queryMap);
                            } else {
                                apiManagerLog.debug("Access IP 2 is null, getting access ip 2 from storage & retrying...");
                                return mWindCustomFactory.createCustomCertApi("https://" + mPrefHelper.getAccessIp(PreferencesKeyConstants.ACCESS_API_IP_2)).getMyIP(queryMap);
                            }
                        } else {
                            return Single.fromCallable(new Callable<ResponseBody>() {
                                @Override
                                public ResponseBody call() {
                                    return ((HttpException) throwable).response().errorBody();
                                }
                            });
                        }
                    }
                })
                .flatMap(new Function<ResponseBody, SingleSource<GenericResponseClass<GetMyIpResponse, ApiErrorResponse>>>() {
                    @Override
                    public SingleSource<GenericResponseClass<GetMyIpResponse, ApiErrorResponse>> apply(final ResponseBody responseBody) throws Exception {
                        //If the response is successful
                        final String responseDataString = responseBody.string(); //Stream closed here
                        return Single.fromCallable(new Callable<GenericResponseClass<GetMyIpResponse, ApiErrorResponse>>() {
                            @Override
                            public GenericResponseClass<GetMyIpResponse, ApiErrorResponse> call() {
                                return new GenericResponseClass<>
                                        (Single.fromCallable(new Callable<GetMyIpResponse>() {
                                            @Override
                                            public GetMyIpResponse call() throws Exception {
                                                return JsonResponseConverter
                                                        .getResponseClass(new JSONObject(responseDataString), GetMyIpResponse.class);
                                            }
                                        }).blockingGet(), null);
                            }
                        }).onErrorReturn(new Function<Throwable, GenericResponseClass<GetMyIpResponse, ApiErrorResponse>>() {
                            @Override
                            public GenericResponseClass<GetMyIpResponse, ApiErrorResponse> apply(Throwable throwable) {
                                if (throwable instanceof RuntimeException && throwable.getCause() instanceof JSONException) {
                                    return new GenericResponseClass<>
                                            (null, Single.fromCallable(new Callable<ApiErrorResponse>() {
                                                @Override
                                                public ApiErrorResponse call() throws Exception {
                                                    return JsonResponseConverter
                                                            .getErrorClass(new JSONObject(responseDataString));
                                                }
                                            }).blockingGet());
                                } else {
                                    apiManagerLog.debug(fTAG+WindError.getInstance().convertThrowableToString(throwable));
                                    return new GenericResponseClass<>(null,null);
                                }
                            }
                        });
                    }
                });

**Comment by JakeWharton** [comment]
I don't see any manipulation of the converter list there such that a null could be introduced. Can't really help without more information to reproduce. Thus far this seems impossible without manipulating the converter list manually.

**Comment by jzlun** [comment]
How did you solve  @ginderAtWindsribe

**Comment by jzlun** [comment]
How did you solve it @ginderAtWindsribe

**Comment by matheusmayron8** [comment]
How did you solve it @ginderAtWindsribe
