### ISSUE TITLE
Jackson-databind 2.9.4 is under security threat

### ISSUE THREAD

**Issue by pavankumarvvijapur** [square/retrofit#3027]
Security flaw. 
Converter: Jackson uses 2.9.4 Jackson Databind which is having security risk. Please find details about the same in the image attached. 

Fix: Upgrade to 2.9.5 or higher Jackson Databind
![screen shot 2019-02-14 at 11 35 47 am](https://user-images.githubusercontent.com/23289872/52766313-cd359780-304c-11e9-8224-21050ca4c5e9.png)

**Comment by JakeWharton** [comment]
Dupe of #2991 and already updated on master. See my comment there as well as to why it hasn't been released.
