### ISSUE TITLE
Upload File to Server along with other data using Retrofit 2.3.0 @MultiPart Android

### ISSUE THREAD

**Issue by Neeraj1108Yadav** [square/retrofit#3033]
Hello Coders

I am creating a new issue, as I am struggling in uploading the image from Android application along with data. The error that I am getting Error Code: 400 Bad Request.

I referred many links for the solution but none of them worked for me:
https://github.com/square/retrofit/issues/1063
https://stackoverflow.com/questions/34562950/post-multipart-form-data-using-retrofit-2-0-including-image

Below I attached the image of my source code:

**Highlighted one is the Retrofit library version that I am using in my code:** 
![lib](https://user-images.githubusercontent.com/34931349/53029615-49860b80-348f-11e9-97cb-8b2e5d20a3bf.JPG)

**Below is the inetrface from I am calling my api:**
![interface](https://user-images.githubusercontent.com/34931349/53029724-7fc38b00-348f-11e9-9860-cfb7cf37c77e.JPG)

This is my source code. It looks very beginner type, but I want to show everything so I written it like that:
![code](https://user-images.githubusercontent.com/34931349/53029809-a681c180-348f-11e9-8d01-3a825194a5d8.JPG)

**This is where I am creating my File:**
![file](https://user-images.githubusercontent.com/34931349/53029912-da5ce700-348f-11e9-8569-bc11c02449d0.JPG)

**Below is the error that I am getting:**
![error1](https://user-images.githubusercontent.com/34931349/53029997-07a99500-3490-11e9-8447-d7180f56aa2c.JPG)

I am stuck here I don't what to do, I kept digging it to resolve issue since last 3 days.

Now If I replace the **hard coded String** with value of all **editText.getText.toString** then the Response I get is in **Succcess**. This is another thing that I am not able to understand, that why it is happening this way.

Please help me to resolve this issue.

**Comment by msayanece** [comment]
Try this...

Use
`RequestBody.create(MediaType.parse("text/plain"), textData)`
for simple text data and 
`MultipartBody.Part.createFormData("file",  path, imageBody)`
for your image data (file)

**Comment by msayanece** [comment]
And use 
`instituteRegister(@Part MultipartBody.Part body, @Part("text") RequestBody text)`

**Comment by Neeraj1108Yadav** [comment]
@msayanece Thanks your suggestion helped me.

**Comment by remonmmitsoft** [comment]
![Capture3](https://user-images.githubusercontent.com/90492379/134331046-dba60289-8947-4b4f-abd4-e879fcb074ad.PNG)
![Capture](https://user-images.githubusercontent.com/90492379/134331051-125eb377-6da0-44b5-a115-92dbd8fa1127.PNG)
![Capture2](https://user-images.githubusercontent.com/90492379/134331055-653ec064-1dc3-46dd-850a-c370ae62cde0.PNG)


Can't triggered into response.isSuccessful()??

**Comment by MRRanjit** [comment]
Hi @remonmmitsoft 

Please use above solution. It will definitely work for you.

RequestBody.create(MediaType.parse(**"text/plain"**), textData) in place of **multipart-part/form-data**.

**Comment by mrc00** [comment]
I'm having the same problem, I've done it the way it is in the example but without success

**Comment by SiddiquiUbaid** [comment]
Helpful discussion
