### ISSUE TITLE
Ability to add custom adapter for suspend methods

### ISSUE THREAD

**Issue by matejdro** [square/retrofit#3037]
As discussed in #2886:

Seemingly best way to handle server errors in Retrofit right now is to add custom adapter that intercepts all requests and then parses error body  (similarly to how [official retrofit2 sample](https://github.com/square/retrofit/blob/master/samples/src/main/java/com/example/retrofit/ErrorHandlingAdapter.java) intercepts exceptions). For example, errors can be easily handled by installing modified version of https://github.com/JakeWharton/retrofit2-kotlin-coroutines-adapter that parses and throws any server errors before creating Deferred instances.

However, with the new official coroutine support with `suspend` modifier, there is no way to attach any kind of adapter. Only way of parsing server exceptions is using `suspend Response<T>` everywhere (instead of just `suspend T`) and then manually parsing error body after every call to the retrofit methods, which is cumbersome.

@nenick has created fork of retrofit with that feature here: https://github.com/nenick/retrofit/tree/suspend-calladapter . Maybe something like that could be adopted into central Retrofit?

**Comment by nenick** [comment]
I need to find some time, then I can try to rewrite the fork based on the latest adjustments. First some feedback from the maintainers would be great.

**Comment by schatzdesigns** [comment]
Has this been solved? Still cannot catch server errors using the suspend functions

**Comment by matejdro** [comment]
Yes, you can use the adapter that @JakeWharton added in #3040, although there does not appear to be any documentation about it.
