### ISSUE TITLE
Does the object serviceMethodCache in Retrofit cause memory leak?

### ISSUE THREAD

**Issue by yifei8** [square/retrofit#3041]
I found a risk of memory leaks in object serviceMethodCache of class Retrofit. Can anyone explain to me if I understand it wrong?

**Comment by JakeWharton** [comment]
It's not static so the only way for it to leak would be for you to leak the Retrofit object which would leak everything it refers to. So I'm not really seeing a leak. You didn't really explain why you think it's a leak so it's hard to figure out whether that addresses your concern or not.

**Comment by yifei8** [comment]
I agree with this point you said which the Retrofit object would leak everything it refers to.  
So I recommend using the LRU algorithm for caching.

**Comment by JakeWharton** [comment]
But why? Do you have an actual problem or are you just speculating?

**Comment by yifei8** [comment]
No, I haven’t encountered any problems yet.  If I find the problem and then feedback in the future,.
You can ignore this problem now. Thank you for your reply.

**Comment by JakeWharton** [comment]
For the access patterns of the library, especially on mobile, caching the data from all endpoints is going to be advantageous. Users wanting LRU behavior can create multiple Retrofit instances and allow them to be GC'd.
