### ISSUE TITLE
Caused by java.lang.IllegalArgumentException: Could not locate call adapter for io.reactivex.Single Tried: * retrofit2.CompletableFutureCallAdapterFactory

### ISSUE THREAD

**Issue by vikrama** [square/retrofit#3046]
I have been seeing this issue creep up over a long time in Crashlytics.

```
Caused by java.lang.IllegalArgumentException: 
Could not locate call adapter for io.reactivex.Single<APIResponseClass>.
  Tried:
   * retrofit2.CompletableFutureCallAdapterFactory
   * retrofit2.ExecutorCallAdapterFactory
       at retrofit2.Retrofit.nextCallAdapter(Retrofit.java:239)
       at retrofit2.Retrofit.callAdapter(Retrofit.java:203)
       at retrofit2.HttpServiceMethod.createCallAdapter(HttpServiceMethod.java:58)
```

I see a similar issue https://github.com/square/retrofit/issues/2028 which was closed with a solution to use the RxJava2CallAdapterFactory. I'm already using it as below:

```
builder.addCallAdapterFactory(RxJava2CallAdapterFactory.create());
retrofit = builder.build();
```

This is the service I have:
```
interface MyService {

    @GET("endpoint")
    fun getSomething(@Query("var1") var1: String,
                      @Query("var2") var2: String?): Single<APIResponseClass>
}
```

The fact that I'm seeing this error in Crashlytics only for 7.x.x+ (API 24+) devices and that https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit2/CompletableFutureCallAdapterFactory.java#L25 gets added only for API 24+, I can see the direct co-relation.
```
// Only added when CompletableFuture is available (Java 8+ / Android API 24+).
@IgnoreJRERequirement 
final class CompletableFutureCallAdapterFactory extends CallAdapter.Factory {
```

I even tried with these proguard rules just to see if it makes a difference. 
```
-dontwarn okio.**
-dontwarn retrofit2.**
-keep class retrofit2.** { *; }
-keepattributes Signature
-keepattributes Exceptions

-keepclasseswithmembers class * {
    @retrofit2.http.* <methods>;
}
```

Am I missing something here or is this a bug with Retrofit + Java 8?

**Comment by JakeWharton** [comment]
The exception message indicates that the RxJava adapter is not registered. Are you sure you're using the correct `Retrofit` instance to create that service?

**Comment by vikrama** [comment]
Makes sense. I can see one edge case in the codebase where the retrofit instance is being nulled out and a new one created. I'll add some Crashlytics log and try to isolate that population. Thx.
