### ISSUE TITLE
Error interceptor body for request @stream

### ISSUE THREAD

**Issue by charleston10** [square/retrofit#3052]
How to ignoring an interceptor for @Stream

I'm have any requests `application/json` and the retrofit works normal

When I use a request as data stream (@stream) occur an error `java.io.EOFException: source exhausted prematurely`

The other calls normally occur and work, just the service that happens the error

```@Provides
    @Named("UserAgentInterceptor")
    @Singleton
    fun provideUserAgentInterceptor(): Interceptor {
        return Interceptor { chain ->
            val requestBuilder = chain.request().newBuilder()
            requestBuilder.addHeader("User-Agent", userAgent())
            chain.proceed(requestBuilder.build())
        }
    }
```
```
@GET("/v1/foo")
    @Streaming
    Observable<ResponseBody> fetchFoo();
```

How can I solve?

**Comment by JakeWharton** [comment]
The interceptor doesn't affect that. My guess is you're trying to read the body twice.

That being said, if you really want to do this, you can look up the Retrofit method on the OkHttp `Call` using `Invocation.class`. This will give you a reference to the `Method` on which you can do `hasAnnotation(Streaming.class)`.

**Comment by charleston10** [comment]
I checked in calmly and saw that it was Encode's problem, and added the GZIP

This answer helped me.
https://github.com/square/okhttp/issues/2132#issuecomment-169500736
