### ISSUE TITLE
You have to create your own annotation for a DELETE with a body. Retrofit (as per the HTTP spec) does not allow it.

### ISSUE THREAD

**Issue by MuhammadjonDeveloper** [square/retrofit#3057]
You have to create your own annotation for a DELETE with a body. Retrofit (as per the HTTP spec) does not allow it.

_Originally posted by @JakeWharton in https://github.com/square/retrofit/issues/533#issuecomment-46994436_

**Comment by JakeWharton** [comment]
Is there a bug or feature request here?
