### ISSUE TITLE
java.lang.NoSuchMethodError: okhttp3.HttpUrl.get(Ljava/lang/String;)Lokhttp3/HttpUrl;

### ISSUE THREAD

**Issue by zijinwangchao** [square/retrofit#3058]
when I set baseUrl，I got a problem :
java.lang.NoSuchMethodError: okhttp3.HttpUrl.get(Ljava/lang/String;)Lokhttp3/HttpUrl;

This problem only happened when I used version 2.5 , if I uesd 2.4 ,it is OK.

I have solved this problem , the okhttp  version mismatch the retrofit version, when I used both the newest version , this problem is solved

**Comment by swankjesse** [comment]
Use OkHttp 3.12.2 or newer.

**Comment by JakeWharton** [comment]
And the pom declares a dependency on that version so if it wasn't present you like have a misconfiguration on the side of your build system which we can't control.

**Comment by Zach-Dean-Attractions-io** [comment]
Hi,

Currently my project is using:

- implementation 'com.squareup.okhttp3:okhttp:4.8.0'
- implementation 'com.squareup.okhttp3:logging-interceptor:3.9.0'
- implementation 'com.squareup.retrofit2:retrofit:2.3.0'
- implementation 'com.squareup.retrofit2:converter-gson:2.3.0'

I tried to move the retrofit & gson converter library to version 2.6.0 or 2.9.0, however I then get the error:

```
java.lang.NoSuchMethodError: No static method get(Ljava/lang/String;)Lokhttp3/HttpUrl; in class Lokhttp3/HttpUrl; or its super classes (declaration of 'okhttp3.HttpUrl' appears in 
        at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:506
```

I tried upgrading all of the libraries to their latest versions, but I still get the same error. Any ideas on where I'm going wrong?

- implementation 'com.squareup.okhttp3:okhttp:4.9.2'
- implementation 'com.squareup.okhttp3:logging-interceptor:4.9.2'
- implementation 'com.squareup.retrofit2:retrofit:2.9.0'
- implementation 'com.squareup.retrofit2:converter-gson:2.9.0'

**Comment by maheritdev** [comment]
I tried all of these solutions but with no benefits unfortunately.
