### ISSUE TITLE
Is serviceMethodCache necessary? 

### ISSUE THREAD

**Issue by guangmomo** [square/retrofit#3059]
Is serviceMethodCache necessary? Many requests may be requested once and will not be requested again.

**Comment by JakeWharton** [comment]
Sure but is that the common case? All usage patterns I've seen indicate otherwise. You're also free to let the interface instance get garbage collected and re-create it when you need it. I'm not sure what's actionable here.

**Comment by guangmomo** [comment]
Thank you, the situation is exactly what you said, this is rarely the case.

**Comment by guangmomo** [comment]
> Sure but is that the common case? All usage patterns I've seen indicate otherwise. You're also free to let the interface instance get garbage collected and re-create it when you need it. I'm not sure what's actionable here.

Thank you, the situation is exactly what you said, this is rarely the case.
