### ISSUE TITLE
[Feature request] first class support for suspend functions

### ISSUE THREAD

**Issue by Ethan1983** [square/retrofit#3060]
In current implementation, CoroutineCallAdapterFactory can be used to call network APIs from a suspend context. However, the client side usage needs an await() on the deferred. This feature request is just to support suspend function out of the box.

    Current: fun getRepos(): Deferred<List<Repo>>

    New: suspend fun getRepos(): List<Repo>

**Comment by JakeWharton** [comment]
See #2886. Will be in the next release.

**Comment by Ethan1983** [comment]
Cool, thanks for the change.
