### ISSUE TITLE
can you tell me why need to box arrayComponentType?

### ISSUE THREAD

**Issue by xchengDroid** [square/retrofit#3061]
`  Class<?> arrayComponentType = boxIfPrimitive(rawParameterType.getComponentType());
          Converter<?, String> converter =
              retrofit.stringConverter(arrayComponentType, annotations);
          return new ParameterHandler.Query<>(name, converter, encoded).array();`

**Comment by JakeWharton** [comment]
`StringConverter` is a generic type which requires boxed types. Instead of looking one up for `int.class` and invoking it with an `Integer.class`, we always used the boxed types.

**Comment by xchengDroid** [comment]
@JakeWharton You are my idol！  I know that, but in the  last else  case , you have not box it ，that's my question.
![image](https://user-images.githubusercontent.com/29690403/55370767-3191b500-552e-11e9-8ee4-f26406170dfe.png)

**Comment by JakeWharton** [comment]
I'm not sure then. Maybe just an oversight? I'd have to dig through the history. That code is probably 4-5 years old at this point.

**Comment by xchengDroid** [comment]
Thank you for your answer ,  good night!
