### ISSUE TITLE
retrofit.baseUrl() is returning different value from what is set in the Builder().

### ISSUE THREAD

**Issue by Raj-Varun** [square/retrofit#3063]
**This is the class which is instantiating retrofit**

    public class ApiClient {

    private static Retrofit retrofit;

    public static Retrofit getRetrofitInstance() {

        if (retrofit == null) {

            final OkHttpClient client = setTokenToHeader();

            retrofit = new retrofit2.Retrofit.Builder()
                    .client(client)
                    //.baseUrl("http://192.168.1.3:3000/")
                    .baseUrl(BuildConfig.BASE_URL)
                    .addConverterFactory(GsonConverterFactory.create())
                    .build();
        }
        return retrofit;
    }

    private static OkHttpClient setTokenToHeader() {

        return new OkHttpClient.Builder().addInterceptor(new Interceptor() {

            @NonNull
            @Override
            public Response intercept(@NonNull Chain chain) throws IOException {

                Request newRequest = chain.request()
                        .newBuilder()
                        .addHeader("Authorization", "Bearer " + UserInfo.getToken())
                        .build();
                return chain.proceed(newRequest);
            }
        }).build();
    }
    }

**This is the method which is requesting data from server**

     private void login() {

        final Retrofit retrofit = ApiClient.getRetrofitInstance();
        retrofit.baseUrl()  **// It is  http:///192.168.1.5:3000/**

        final userApiInterface apiInterface = retrofit.create(userApiInterface.class);
        // Body
        final User loginUser = new User();
        loginUser.setUserEmail(Email.getText().toString());
        loginUser.setPassword(Password.getText().toString());
        final Call<User> call = apiInterface.Login(loginUser);

        call.enqueue(new Callback<User>() {

            @Override
            public void onResponse(@NonNull Call<User> call, @NonNull Response<User> response) {
                handleLoginResponse(response);
            }

            @Override
            public void onFailure(@NonNull Call<User> call, @NonNull Throwable t) {
                customToast.internalError();
                Log.e("Retrofit error: ", String.valueOf(t));
                // java.net.SocketTimeoutException: failed to connect to /192.168.1.5 (port 3000) after 10000ms
               // This is thrown here
            }
        });
    }

When I'm calling "retrofit.baseUrl()" it is returning a different url.

**Comment by JakeWharton** [comment]
Can you express this with a failing test case? I have no idea what `BuildConfig.BASE_URL` is set to.

**Comment by Raj-Varun** [comment]
Hey @JakeWharton , I assure you the value of `BuildConfig.BASE_URL` is the same as "http://192.168.1.3:3000/".

**Comment by JakeWharton** [comment]
We have tests which validate the supplied base URL is what's returned from the created `Retrofit` instance: https://github.com/square/retrofit/blob/master/retrofit/src/test/java/retrofit2/RetrofitTest.java#L736-L750

If you can express your problem in a failing test case or executable sample we can diagnose what's happening, but with no way to reproduce it's unclear what you're seeing.

**Comment by jacksonkyle** [comment]
@JakeWharton I am using the latest Retrofit and encountered the same issue. This issue should be revisited.
