### ISSUE TITLE
 @FieldMap Map<String, String> maps   , value null in the map,throw exception  FiledMap {@code null} value for the map, as a key, or as a value is not allowed. 

### ISSUE THREAD

**Issue by lyjSmile** [square/retrofit#3068]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by JakeWharton** [comment]
It's not clear what you're asking. Yes, null values are not allowed.

**Comment by lyjSmile** [comment]
Is there a way to allow Map key-value pairs to be Null?

**Comment by JakeWharton** [comment]
Not currently. Why do you maps contain these entries? What do you expect in the body?

**Comment by lyjSmile** [comment]
The parameter might be Null when accessed, but I don't want to filter the Map key-value pair every time

**Comment by JakeWharton** [comment]
It's not clear _why_ your maps contains a null entry though. Nor what behavior you expect when Retrofit sees it. Do we ignore it? Write "null" as a literal?

**Comment by lyjSmile** [comment]
I wish I could configure myself to allow the body parameter to be null
