### ISSUE TITLE
Using Retrofit in JavaEE

### ISSUE THREAD

**Issue by genxlogics** [square/retrofit#3073]
What kind of issue is this?

 - [x] Feature Request. In order to use Retrofit in Java EE environment where we would expect client proxies to be managed by CDI in order to user the ee and cdi feature, I have created a CDI extension which process all your Retrofit interfaces and create beans for them so that you can do something like

```
@ApplicationScoped
public class ServiceCaller {
@Inject
private RetrofitTestClient client;
.....
```

Retrofit interface will look like this,

```
@Retrofit(url="", connectTimeout="",readTimeout="",...all other necessary properties)
public interface RetrofittestClient {
all your methods here
....
}
```

@JakeWharton , @codebutler , @loganj 
what is your opinion??

**Comment by genxlogics** [comment]
@swankjesse ,

**Comment by genxlogics** [comment]
may be we can call it a retrofit-ee adapter.

**Comment by swankjesse** [comment]
Sounds good. Please create this as a standalone project.
