### ISSUE TITLE
Retrofit Questions

### ISSUE THREAD

**Issue by halimpuckjava** [square/retrofit#3074]
hi, i using retrofit 2.5.0

1.
OkHttpClient.Builder().connectionTimeout(....) not work but with intercepor (Interceptor { .. connectionTimeout = .... ) it work fine, so whats difference between connectiontimeout in OkHttpClient & Interceptor ??

2. how in can cancel (shutdow) retrofit thread service

3. localdatetime serialize (diserialize) with exception when using jackson, so to fix that 

4. add logging feature in retrofit bulder

**Comment by JakeWharton** [comment]
1. This is a question about OkHttp, not Retrofit. I would suggest asking on StackOverflow with the 'okhttp' tag.
2. Retrofit doesn't have a thread pool. You can read "Shutdown isn't necessary" from [the documentation on `OkHttpClient`](https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.html) for how OkHttp deals with this.
3. This is a Jackson question. You can ask on stackOverflow with the 'jackson' tag.
4. You can use OkHttp's `HttpLoggingInterceptor' for logging: https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor#readme

**Comment by halimpuckjava** [comment]
thanks
