### ISSUE TITLE
Retrofit + Dagger2 + Authentificator

### ISSUE THREAD

**Issue by selmanon** [square/retrofit#3076]
I'm working on a sample project that have 2 webservice calls, the first is for getting the list of cars and the second for refreshing the token. To be able to retrieve the cars a valid token must be used.

To implement this I used the Authenticator interface.

In my architecture I'm using Dagger2 for dependency injection, but when I try to avoid having 2 OkHttp instances (one for the Api service and the other for the Authenticator) I got a circular dependency issue that could be solved by a bunch of solutions.

IMO this issue of having 2 OkHttp instances could be fixed Retrofit side or maybe there is a proper solution Retrofit side without having recourse to those solutions :
[1. How to solve circular dependency?](https://softwareengineering.stackexchange.com/a/306496/85187)
[2. Gloal setter](https://stackoverflow.com/a/43929302/3672184)

**Comment by fawaad** [comment]
Retrofit and OkHttp are unaware/indifferent of what you use as a DI layer. I'm not sure I see a reason why retrofit/okhttp would need to do anything here. Perhaps your question/issue would be better directed to StackOverflow.

**Comment by selmanon** [comment]
@fawaad my question is regarding Retrofit design issue IMHO .. so I don't think that SO is needed in this case.

**Comment by fawaad** [comment]
I may have misunderstood, but I don't actually see any questions here. Can you provide example code of what you are referring to and the errors you are getting? Based on the links you provided, it appears that those circular dependencies are user initiated and not a library problem.

**Comment by selmanon** [comment]
@fawaad I updated my question/request. my question was about avoiding to have 2 OkHttp instances while using `Authenticator` for sure there is some solutions but not clean IMO.

**Comment by JakeWharton** [comment]
I'm not seeing how this is related to Retrofit.

OkHttpClient instances are cheap when you use `newBuilder()`.
```java
var baseClient = new OkHttpClient();
var tokenAuthenticator = createTokenAuthenticator(baseClient);
var authClient = baseClient.newBuilder()
    .authenticator(tokenAuthenticator)
    .build()
var authRetrofit = new Retrofit.Builder()
    .baseUrl(..)
    .client(authClient)
    .build()
var myService = authRetrofit.create(MyService.class);
```

If this is truly a feature request then a concrete proposal is needed. The problem is far too abstract and nebulous as you've described it.
