### ISSUE TITLE
Error into Retrofit 2.5.0 or OkHttp for Huawei Honor 9 Lite LLD-L31

### ISSUE THREAD

**Issue by Vedkh** [square/retrofit#3077]
I have the IllegalArgumentException with the client's Huawei Honor 9 Lite LLD-L31 device, with installed application beta-version (signed app from the Google Play Store, beta test). It works fine for Android 6 and 7.1, MTK chipsets, same as for all SDK emulators. But not for Huawei Honor 9 Lite LLD-L31 device. Unfortunately, I cannot provide a test source code here. Only the next information from the Firebase Crashlytics:

FatalException: java.lang.IllegalArgumentException
Expected URL scheme 'http' or 'https' but no colon was found
okhttp3.HttpUrl$Builder.parse (HttpUrl.java:1332)
okhttp3.HttpUrl.get (HttpUrl.java:917)
retrofit2.Retrofit$Builder.baseUrl (Retrofit.java:458)

After Retrofit downgrade to the 2.4.0 version issue has not been found and everything works perfectly. So seems this error is into Retrofit or OkHttp. 
(I duplicated it also into OkHttp. ([https://github.com/square/okhttp/issues/4918])

**Comment by JakeWharton** [comment]
Why can't you provide test code? How are we supposed to know what you're doing in order to reproduce the failure and verify any fix?

**Comment by Vedkh** [comment]
I am very sorry for delay with answer, very busy with the current order. I will create test code example, in 1-2 days as full code example, nothing special in it. But issue was found only for the specified Huawei customer device. On all my devices (sadly no Huawei) it works perfectly (same works perfectly everywhere after retrofit downgrade without code changes).

**Comment by swankjesse** [comment]
Consider reporting the problem to Huawei?

**Comment by Vedkh** [comment]
I am unsure that is Huawei's bug, because after Retrofit downgrade to 2.4.0 everything works. So error happens somewhere into Retrofit's call stack. Not exactly into Retrofit code, can be into another used libraries.

**Comment by swankjesse** [comment]
If this is a bug report it should include an executable test case.
