### ISSUE TITLE
Upload binary file as application/octet-stream?

### ISSUE THREAD

**Issue by wishy-viewlift** [square/retrofit#3078]
I have to upload image file as binary with PUT request
This is my service 

`@PUT
    Call<String> putUserProfileImage(@Url String url,
                                           @Body RequestBody file);`

This is my calling method

       `   InputStream in = new FileInputStream(new File(profileImage.getPath()));
        byte[] buf;
        buf = new byte[in.available()];
        while (in.read(buf) != -1);
        RequestBody requestBody = RequestBody
                .create(MediaType.parse("application/octet-stream"), buf);

        appCMSUserIdentityRest.putUserProfileImage(url, requestBody).enqueue(new Callback<String>() {
            @Override
            public void onResponse(Call<String> call, Response<String> response) {
                Observable.just(response.body())
                        .onErrorResumeNext(throwable -> Observable.empty())
                        .subscribe(userIdentityAction);
            }

            @Override
            public void onFailure(Call<String> call, Throwable t) {
                Observable.just((String) null)
                        .onErrorResumeNext(throwable -> Observable.empty())
                        .subscribe(userIdentityAction);
            }
        });`

I keep getting bad request in error

**Comment by JakeWharton** [comment]
A bad request error is a disagreement between you and your server as to the format they expect and unlikely a Retrofit bug. If it's a Retrofit bug you can write a test case with the interface and expected HTTP request format that doesn't involve a server. Without this, it's impossible to know what you are experiencing or what your server expects. StackOverflow with the 'retrofit' is usually a better place to ask usage questions about how to create a request in a particular format which matches your server's expectations.
