### ISSUE TITLE
Maybe not support Android things in Raspberry Pi 3 Model B 

### ISSUE THREAD

**Issue by yeyupiaoling** [square/retrofit#3085]
Maybe not support Android things in Raspberry Pi 3 Model B .

My device is Raspberry Pi 3 Model B,
OS is Android things 1.0.13
Android 8.1

**Comment by JakeWharton** [comment]
There is no information here which indicates _why_ you think this device in unsupported. Retrofit works on Android 8.1 on other devices, so there's no reason why this should be any different. Please provide the failing stacktrace at minimum, or more ideally a failing test case or reproducing sample of some sort.

**Comment by yeyupiaoling** [comment]
@JakeWharton Just this log:
```
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x68 in tid 5920 (CameraBackgroun), pid 5894 (upiaoling.robot)
```

I found the wrong place. This error is the result of okhttp3.
