### ISSUE TITLE
Fatal Exception: java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by ravigbw** [square/retrofit#3086]
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 12 byte allocation with 0 free bytes and 3GB until OOM
       at java.util.HashMap.values(HashMap.java:703)
       at okhttp3.internal.http2.Http2Connection.close(Http2Connection.java:455)
       at okhttp3.internal.http2.Http2Connection$ReaderRunnable.execute(Http2Connection.java:617)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.lang.Thread.run(Thread.java:818)

**Comment by JakeWharton** [comment]
Why do you think Retrofit is the cause of this?

**Comment by ravigbw** [comment]
Recently after moving from volley to retrofit ,we start facing this crashes ,any help would be highly appreciated .
Not able to get fixed for this crashes after doing stackoverflow ,then finally after loosing hope and helpless ,i decided to  ask for help here .

**Comment by JakeWharton** [comment]
My best guess is that you're creating a new `Retrofit` instance for every call and eventually you just exhaust the memory. The stacktrace that accompanies an OOM is never the underlying problem. For all we know you're allocating memory and leaking it elsewhere and OkHttp just happened to draw the short straw which finally trigger the crash. Unless you can demonstrate the leak is inside Retrofit, there's no action to take here.

**Comment by ravigbw** [comment]
**My best guess is that you're creating a new Retrofit instance for every call**
No sir ,We are following singleton pattern .
We checked Leaks after integrated memory Leak ,but no Leaks have been found for retrofit

**Comment by rayworks** [comment]
@ravigbw 
You may also need to take a look on [Crashes on OutOfMemoryError, while there are 257 "OkHttp ConnectionPool" threads](https://github.com/square/okhttp/issues/2846).
