### ISSUE TITLE
android

### ISSUE THREAD

**Issue by ranafaisi** [square/retrofit#3087]
04-30 03:02:06.359 1340-1629/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 51235842 , only wrote 51235432
04-30 03:02:06.359 1340-1629/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 51235438 , only wrote 51235432
04-30 03:02:06.384 1340-1629/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 51236542 , only wrote 51236093
04-30 03:02:06.582 1340-1629/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 51244808 , only wrote 51244025
04-30 03:02:06.582 1340-1629/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 51244032 , only wrote 51244025
04-30 03:02:06.597 1340-1629/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 51244695 , only wrote 51244686
04-30 03:02:06.647 16357-16377/com.application.ranafaixalrajpoot.ustadgpk D/EGL_emulation: eglMakeCurrent: 0xae4947e0: ver 3 0 (tinfo 0xb2bbd160)
04-30 03:02:06.649 16357-16377/com.application.ranafaixalrajpoot.ustadgpk D/EGL_emulation: eglMakeCurrent: 0xae4947e0: ver 3 0 (tinfo 0xb2bbd160)
04-30 03:02:06.793 1340-1629/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 51253339 , only wrote 51253279
04-30 03:02:06.793 1340-1629/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 51253284 , only wrote 51253279
04-30 03:02:06.809 1340-1629/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 51253982 , only wrote 51253940
04-30 03:02:06.993 1340-1629/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 51262064 , only wrote 51261872
04-30 03:02:07.006 16357-16357/com.application.ranafaixalrajpoot.ustadgpk I/Choreographer: Skipped 43 frames!  The application may be doing too much work on its main thread.
04-30 03:02:07.055 16357-16377/com.application.ranafaixalrajpoot.ustadgpk D/EGL_emulation: eglMakeCurrent: 0xae4947e0: ver 3 0 (tinfo 0xb2bbd160)
04-30 03:02:07.112 1340-1629/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 51267100 , only wrote 51266499
04-30 03:02:07.326 1340-1629/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 51275943 , only wrote 51275753
04-30 03:02:07.326 1340-1629/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 51275759 , only wrote 51275753
04-30 03:02:07.533 1340-1629/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 51284857 , only wrote 51284346
04-30 03:02:07.705 16357-16357/com.application.ranafaixalrajpoot.ustadgpk I/Choreographer: Skipped 40 frames!  The application may be doing too much work on its main thread.
04-30 03:02:07.773 1643-1664/system_process I/ActivityManager: Displayed com.application.ranafaixalrajpoot.ustadgpk/.user_sign_up: +1s719ms
04-30 03:02:07.925 1340-1629/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 51301666 , only wrote 51300871
04-30 03:02:07.929 16357-16377/com.application.ranafaixalrajpoot.ustadgpk E/Surface: getSlotFromBufferLocked: unknown buffer: 0xae569dc0
04-30 03:02:08.346 1229-1229/? W/SurfaceFlinger: couldn't log to binary event log: overflow.
04-30 03:02:08.376 1340-1629/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 51320754 , only wrote 51320701
04-30 03:02:08.377 1340-1629/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 51320714 , only wrote 51320701
04-30 03:02:08.402 1340-1629/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 51321819 , only wrote 51321362
04-30 03:02:09.092 1340-1630/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 51381320 , only wrote 51351768
04-30 03:02:59.929 1229-1320/? D/hwcomposer: hw_composer sent 223 syncs in 60s

**Comment by JakeWharton** [comment]
I don't see anything related to Retrofit or evidenced as being the result of using Retrofit.

**Comment by ranafaisi** [comment]
this error is happening again and again why?

**Comment by JakeWharton** [comment]
You haven't shown an error

**Comment by ranafaisi** [comment]
W/audio_hw_generic: Not supplying enough data to HAL, expected position 51381320 , only wrote 51351768
This is the error

**Comment by JakeWharton** [comment]
That doesn't come from Retrofit
