### ISSUE TITLE
http://square.github.io/retrofit/ 打不开了

### ISSUE THREAD

**Issue by a120476536** [square/retrofit#3092]
http://square.github.io/retrofit/  打不开了

**Comment by lijinghuatongxue** [comment]
你也是个人才

**Comment by xchengDroid** [comment]
很秀

**Comment by JakeWharton** [comment]
I'm not sure how to help. GitHub controls the hosting, not us. Do all GitHub pages not work? Or only Retrofit? You can check out the repository and the website is browsable in the `website/` directory as well.
