### ISSUE TITLE
Json response data missing

### ISSUE THREAD

**Issue by poldiepolds** [square/retrofit#3093]
Im having a problem displayin all the json response.
Some of my json data are missing.

Here is my json response.

{"data":[{
         "loan_id":"LO-FD-1903544",
	 "loan_type":"Loan more than 1 month delay",
	 "municipality":"City",
	 "province":"Buhi",
	 "barangay":"Cobo",
	 "customer_id":"CX-FD-1903326",
	 "first_name":"Daniel",
	 "last_name":"Dela Cruz",
	 "middle_name":"Trast",
	 "name_extension":"",
	 "contact_no":"00524310514",
	 "thumbnail":"hulugan\/img\/customers\/CX-FD-1903326\/10001903326000015492519213900001.jpg",
	 "photo":"hulugan\/img\/customers\/CX-FD-1903326\/10001903326000015492519213900000.jpg",
	 "street_no":"p-2",
	 "street":null,
	 "i.status":"Completed"
 }

Then when try to display it in logcat some of them are missin.

Response: Received information[
{"barangay":"Cobo",
"municipality":"City",
"photo":"hulugan/img/customers/CX-FD-1903326/10001903326000015492519213900000.jpg",
"province":"Buhi",
"thumbnail":"hulugan/img/customers/CX-FD-1903326/10001903326000015492519213900001.jpg"},

**Comment by JakeWharton** [comment]
Retrofit doesn't deal in JSON. It hands the response body to your chosen converter. If the data is being deserialized incorrectly, it is between your HTTP response data and the type you are using to define the shape of JSON. I would suggest asking on StackOverflow with the object definition and the tag of the serialization library you are using (e.g., 'gson').
