### ISSUE TITLE
@QueryMap keys must be of type String: K (parameter #1)

### ISSUE THREAD

**Issue by umasankar-ts** [square/retrofit#3095]
**Log**
java.lang.IllegalArgumentException: @QueryMap keys must be of type String: K (parameter #1)
        for method ApiService.updateDevice

**ApiService interface:**
@GET("update_device")
    Call<ResponseBody> updateDevice(@QueryMap HashMap<String, String> hashMap);

**Issue**
Works **fine with Debug build**, issue raises only on **Release Build**

**Comment by JakeWharton** [comment]
Sounds like your generic signatures are being removed by a shrinking tool.
Consult it's documentation for retaining generic signatures. If you're
using proguard you need `-keepattributes Signature`.

**Comment by BianconeroIle** [comment]
In my case the moment i added -keepattributes Signature i got the issues. 

This is what i have.. 
`#Proguard rules for retrofit for proguard - R8 has them included
# EnclosingMethod is required to use InnerClasses.
-keepattributes Signature, InnerClasses, EnclosingMethod

# Retrofit does reflection on method and parameter annotations.
-keepattributes RuntimeVisibleAnnotations, RuntimeVisibleParameterAnnotations

# Retain service method parameters when optimizing.
-keepclassmembers,allowshrinking,allowobfuscation interface * {
    @retrofit2.http.* <methods>;
}

# Ignore annotation used for build tooling.
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement

# Ignore JSR 305 annotations for embedding nullability information.
-dontwarn javax.annotation.**

# Guarded by a NoClassDefFoundError try/catch and only used when on the classpath.
-dontwarn kotlin.Unit

# Top-level functions that can only be used by Kotlin.
-dontwarn retrofit2.KotlinExtensions
-dontwarn retrofit2.KotlinExtensions$*

#Proguard rules for okhttp3 - R8 has them included

# A resource is loaded with a relative path so the package of this class must be preserved.
-keepnames class okhttp3.internal.publicsuffix.PublicSuffixDatabase

# Animal Sniffer compileOnly dependency to ensure APIs are compatible with older versions of Java.
-dontwarn org.codehaus.mojo.animal_sniffer.*

# OkHttp platform used only on JVM and when Conscrypt dependency is available.
-dontwarn okhttp3.internal.platform.ConscryptPlatform` 

and this is what i get 
`Fatal Exception: java.lang.IllegalArgumentException
@QueryMap keys must be of type String: K (parameter #1) for method n.i
retrofit2.Utils.methodError
`

**Comment by natansalda** [comment]
@angeleskilija where you able to resolve this? I have the same problem
