### ISSUE TITLE
Connection time out issue on Samsung Devices

### ISSUE THREAD

**Issue by ishwarverma39** [square/retrofit#3096]
**SocketTimeoutException on Samsung Devices?** 
 Hi team, some of our customers/users are facing connection time out error on Samsung Devices, Samsung Galaxy Note8 and Note9 with Android OS version 9.

**We are using retrofit lib version is 2.4.0**
`implementation 'com.squareup.retrofit2:retrofit:2.4.0'
  implementation 'com.squareup.retrofit2:converter-gson:2.4.0'`

**Please also find the OkHttp initialization as mentioned below**
`private Retrofit getRetrofit(String baseUrl) {
        OkHttpClient.Builder okHttpClientBuilder = new OkHttpClient.Builder();
        okHttpClientBuilder.readTimeout(BlueSkyConstants.TIME_OUT_DURATION, TimeUnit.SECONDS);
        okHttpClientBuilder.connectTimeout(BlueSkyConstants.TIME_OUT_DURATION, TimeUnit.SECONDS);
        okHttpClientBuilder.writeTimeout(BlueSkyConstants.TIME_OUT_DURATION, TimeUnit.SECONDS);
        OkHttpClient client = okHttpClientBuilder.build();
        return new Retrofit.Builder()
                .baseUrl(baseUrl)
                .addConverterFactory(GsonConverterFactory.create())
                .client(client)
                .build();
    }`

**Please help us to resolve the issue, thanks in advance**

**Comment by ruieduardosoares** [comment]
> **SocketTimeoutException on Samsung Devices?**
> Hi team, some of our customers/users are facing connection time out error on Samsung Devices, Samsung Galaxy Note8 and Note9 with Android OS version 9.
> 
> **We are using retrofit lib version is 2.4.0**
> `implementation 'com.squareup.retrofit2:retrofit:2.4.0' implementation 'com.squareup.retrofit2:converter-gson:2.4.0'`
> 
> **Please also find the OkHttp initialization as mentioned below**
> `private Retrofit getRetrofit(String baseUrl) { OkHttpClient.Builder okHttpClientBuilder = new OkHttpClient.Builder(); okHttpClientBuilder.readTimeout(BlueSkyConstants.TIME_OUT_DURATION, TimeUnit.SECONDS); okHttpClientBuilder.connectTimeout(BlueSkyConstants.TIME_OUT_DURATION, TimeUnit.SECONDS); okHttpClientBuilder.writeTimeout(BlueSkyConstants.TIME_OUT_DURATION, TimeUnit.SECONDS); OkHttpClient client = okHttpClientBuilder.build(); return new Retrofit.Builder() .baseUrl(baseUrl) .addConverterFactory(GsonConverterFactory.create()) .client(client) .build(); }`
> 
> **Please help us to resolve the issue, thanks in advance**

Check this issue https://github.com/square/okhttp/issues/3146

**Comment by JakeWharton** [comment]
Retrofit doesn't deal in sockets or connections so I'm going to close in favor of the OkHttp issue. We don't affect this behavior at all.
