### ISSUE TITLE
Retrofit @Headers cannot apply two headers

### ISSUE THREAD

**Issue by CoXier** [square/retrofit#3099]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I want to add two headers for an api interface and I am using Retrofit.

Here is my code.

    @Headers({
            "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
            "Content-Type: application/json"
            })
    @POST("web/shrink")
    Call<TinyResponse> uploadUrl(@Body String url);

As you see, `User-Agent` and `Content-Type` are needed. However when I debug, I find that there is `User-Agent` in Request class. Then I swap these headers position, `Content-Type` left.

What's wrong with my code? Thanks in advance!

**Comment by oladipo** [comment]
Did you fix this eventually?
