### ISSUE TITLE
org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject

### ISSUE THREAD

**Issue by asamadifateh** [square/retrofit#3103]
This issue arises only in Nokia 6 (7.1.1 ) while calling API using Retrofit 2.5.0. Please help me to resolve this issue. No other devices having such an issue.

**Comment by JakeWharton** [comment]
Seems like a captive Wi-Fi portal or something is returning HTML instead of your JSON. Retrofit can't do anything about this. It's just passing the response to your converter. You'll have to deal with this on your own.
