### ISSUE TITLE
Retrofit library throwing NullPointerExceptioninterceptor

### ISSUE THREAD

**Issue by harshmittal29** [square/retrofit#3104]
We have retrofit library version 2.5.0 in our app.
We recently update our apps to gradle 3.4.1 and we started getting lot of crashes. Here is the crash logs : 

```
> Fatal Exception: java.lang.NullPointerExceptioninterceptor d.g.c.b.d@3d32616 returned null Raw Text
> --
>   | okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:157)
>   | okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:121)
>   | okhttp3.RealCall.getResponseWithInterceptorChain (RealCall.java:254)
>   | okhttp3.RealCall$AsyncCall.execute (RealCall.java:200)
>   | okhttp3.internal.NamedRunnable.run (NamedRunnable.java:32)
>   | java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
> 
> 
```

**Comment by JakeWharton** [comment]
The exception message tells you the problem. Your interceptor, `d.g.c.b.d`, is returning null which is not allowed by OkHttp. Deobfuscate the stacktrace to find the offending class and change it to either throw exceptions or return a valid `Response`.

**Comment by harshmittal29** [comment]
Looking deep inside my code, I found the issue and fixed it. Thanks for your inputs Jake.
