### ISSUE TITLE
Gradle 3.4.1 not able to parse the response into Object

### ISSUE THREAD

**Issue by harshmittal29** [square/retrofit#3106]
I just updated my Gradle to 3.4.1.
I am having an API call inside one of my module.
I am using the module inside the app : 
`implementation com.mindvalley.module_login:Module_Login:$rootConfiguration.loginLibraryVersion`

Now when I generate a signed build with ProGuard, the object is null, meaning retrofit is not able to parse the object.

P.S. : This works fine with debug mode or if I run the app with Gradle version 3.3.2

My Retrofit Proguard file : 
```
-dontwarn retrofit2.**
-keep class retrofit2.** { *; }
-keepattributes Signature
-keepattributes Exceptions

-keepclasseswithmembers class * {
    @retrofit2.http.* <methods>;
}


-keepattributes Signature, InnerClasses, EnclosingMethod

-keepattributes RuntimeVisibleAnnotations, RuntimeVisibleParameterAnnotations
-keepclassmembers,allowshrinking,allowobfuscation interface * {
    @retrofit2.http.* <methods>;
}

-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement

-dontwarn javax.annotation.**

-dontwarn kotlin.Unit

-dontwarn retrofit2.KotlinExtensions

-if interface * { @retrofit2.http.* <methods>; }
-keep,allowobfuscation interface <1>


-dontwarn org.codehaus.mojo.**
-keepattributes *Annotation*

-keepattributes RuntimeVisibleAnnotations
-keepattributes RuntimeInvisibleAnnotations
-keepattributes RuntimeVisibleParameterAnnotations
-keepattributes RuntimeInvisibleParameterAnnotations

-keepattributes EnclosingMethod

-keepclasseswithmembers class * {
    @retrofit2.* <methods>;
}

-keepclasseswithmembers interface * {
    @retrofit2.* <methods>;
}

```

My OkHttp proguard file : 

```
-keepattributes Signature
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-dontwarn okhttp3.**

-dontwarn javax.annotation.**
-keepnames class okhttp3.internal.publicsuffix.PublicSuffixDatabase

-dontwarn org.codehaus.mojo.animal_sniffer.*

-dontwarn okhttp3.internal.platform.ConscryptPlatform

-dontwarn org.codehaus.mojo.animal_sniffer.*
```

My GSON proguard file : 

```
-keepattributes Signature
-keepattributes EnclosingMethod

-keep class sun.misc.Unsafe { *; }
-keep class com.google.gson.stream.** { *; }
-dontwarn com.google.gson.internal.UnsafeAllocator

-keepattributes Signature

-keepattributes *Annotation*

-dontwarn sun.misc.**
-keep class com.google.gson.examples.android.model.** { <fields>; }

-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

-keepclassmembers,allowobfuscation class * {
  @com.google.gson.annotations.SerializedName <fields>;
}
```

**Comment by harshmittal29** [comment]
Also it works fine if I disable R8 and useProguard from build.gradle but it fails when R8 is enabled.

**Comment by ipereziriarte** [comment]
AFAIK, retrofit and proguard latest releases include the proguard configuration, so you don't need to add any extra config yourself.

Check the [embedded proguard rule](https://github.com/square/retrofit/blob/master/retrofit/src/main/resources/META-INF/proguard/retrofit2.pro)

**Comment by DroidNinja** [comment]
Happening with me too. Is there any solution to this?
-Gradle:3.4.1
Minify enabled
Result: Crashing while parsing

- Working fine with debug build

**Comment by harshmittal29** [comment]
In gradle 3.4.1, by default R8 is enabled. So in case you want to use proguard, you need to disable R8 and enable proguard in build.gradle.
https://stackoverflow.com/questions/56032152/class-no-longer-obfuscated-after-upgrading-to-android-gradle-plugin-3-4-0/56032248#56032248.

Using proguard works fine for me.
But if I enable R8, it fails again.

**Comment by JakeWharton** [comment]
It's not clear this is a problem with Retrofit. It seems like your model objects and chosen converter likely need rules in place that Retrofit cannot provide and as a result we aren't suited to assist here. I would suggest posting to StackOverflow with the 'gson' and 'r8' tags, and potentially creating a sample which reproduces the problem for the post.

I've been using R8 for almost a year in my personal projects which use Retrofit with a variety of converters some of which required rules (usually reflection-based ones) and some of which did not (codegen-based ones.

Unless there is a problem with the rules embedded in Retrofit which are specific to how optimizers handle the service interfaces, this isn't something Retrofit is responsible for.

**Comment by DroidNinja** [comment]
Thanks @JakeWharton . There was problem with gson rules.

**Comment by harshmittal29** [comment]
Thanks @JakeWharton. The problem was solved when I added my data models used in a separate library module in GSON proguard something like this :
-keep class com.google.gson.examples.android.model.** { <fields>; }

**Comment by asugomez** [comment]
Hi, I'm having the same problem I think, could you tell me how did you solve it? what did you add to your code and where?
Thanks :)
