### ISSUE TITLE
Jackson converter issue with java 8 date & time 

### ISSUE THREAD

**Issue by halimpuckjava** [square/retrofit#3107]
hi

i use JACKSON as converter , so when passed data contains (LocalTime or LocalDate or LocalDateTime) as body to server an BAD_REQUEST invoke with response, i sugggest to add method for more flexibility when use JacksonConverterFactory to register modules like jackson-datatype (serialize date & time with java8)

**Comment by JakeWharton** [comment]
The `JacksonConverterFactory` already accepts an `ObjectMapper` which you can configure any way you like. We have an example of doing so in our tests to ensure it works: https://github.com/square/retrofit/blob/81a6193a7b3f2b1bf25e78adc2638681b0514fe8/retrofit-converters/jackson/src/test/java/retrofit2/converter/jackson/JacksonConverterFactoryTest.java#L114-L128

**Comment by halimpuckjava** [comment]
thanks,

i forgot the second constructor or JacksonConverterFactory (accept instance of ObjectMapper)
