### ISSUE TITLE
Building with Gradle

### ISSUE THREAD

**Issue by jaredsburrows** [square/retrofit#3111]
Okio was converted from maven to gradle here: https://github.com/square/okio/commit/8fda82f88627a377a010e5a838cdfea20af61c61

OkHttp was converted from maven to gradle:
https://github.com/square/okhttp/commit/dc1e870d24914a26c97a52e8151355d37162799a

@JakeWharton @swankjesse would you accept a PR build retrofit via Gradle?

**Comment by JakeWharton** [comment]
No. There's no reason to switch. Those projects all had motivations which required the change.

See also: #1929, #1169
