### ISSUE TITLE
Detect Client Timeout from Server

### ISSUE THREAD

**Issue by mobileonekh** [square/retrofit#3112]
Hi,
Sometimes our server needs a long time to process before it can response to client app, so we have a scenario where the app is timeout but the server is unable to detect it and commit its task so the result is "work is success at server while the app is timeout".

Is there any solution for the server to detect that the client side is already timeout.

Thanks;

**Comment by JakeWharton** [comment]
No, a server has no way of detecting this. In HTTP/2 you might be able to detect it provided the client on the server exposes it, but you'd still be performing a race. If the two events occur at the same time, the notification will never reach the server and the client will never see the response.
