### ISSUE TITLE
Docker container missing SNAT on massive request

### ISSUE THREAD

**Issue by msartor92** [square/retrofit#3116]
Hi all,

I've introduced retrofit2 into a java application that made massive http request to some endpoint and run into a Docker container.

Dockerfile example:
`FROM openjdk:8-jre-alpine

COPY  "./FlinkHTTPTest.jar" "/tmp/FlinkHTTPTest.jar"

ENV jar_file=FlinkHTTPTest.jar
ENTRYPOINT exec java $JAVA_OPTS -jar /tmp/$jar_file
`
Initially apps work well but after few second I see on the host TCP packet exiting with source IP of the container. 
The expected behavior is that host NAT source IP of each packet coming from Docker container with host IP so the other host that recive request could respond through it.

Instead with this bug other host recive request and respond to docker ip that is not exposed to all VM so that packet generate an alert in the firewall.

The host ARP table is correct in fact ping and telnet command works fine.

I've used Retrofit with okHttp implementation. 
Anyone with same problem?

**Comment by JakeWharton** [comment]
Retrofit doesn't operate at a layer that can affect this in any way. The very highest level that controls this would be in OkHttp. I would suggest perhaps asking on StackOverflow, or if you think it's a bug in OkHttp creating a reproducing test case and opening an issue on that project.
