### ISSUE TITLE
Missing Moshi converter for retrofit2.Call when using suspend keyword

### ISSUE THREAD

**Issue by PhilipSA** [square/retrofit#3122]
```
@GET("$API_PATH{packageId}?langCode=en")
fun get(@Path("packageId") packageId: String) : Call<ApiResponse<GlobalAppConfigPackageDto>>
```

This snippet works as normal. But after updating to 2.6.0 and adding the new suspend keyword:

```
@GET("$API_PATH{packageId}?langCode=en")
suspend fun get(@Path("packageId") packageId: String) : Call<ApiResponse<GlobalAppConfigPackageDto>>
```

I get exception:

```
java.lang.IllegalArgumentException: Unable to create converter for retrofit2.Call<com.sdk.api.ApiResponse<com.sdk.api.models.global.GlobalAppConfigPackageDto>>
        for method GlobalAppConfigApi.get
        at retrofit2.Utils.methodError(Utils.java:52)
        at retrofit2.HttpServiceMethod.createResponseConverter(HttpServiceMethod.java:115)
        at retrofit2.HttpServiceMethod.parseAnnotations(HttpServiceMethod.java:82)
```

I am using the MoshiConverterFactory that uses the same version as Retrofit:

`api("com.squareup.retrofit2:converter-moshi:${Versions.retrofitVersion}")`

Is the suspend keyword not compatible with Call<>? It works just fine with Response<> for example.

**Comment by JakeWharton** [comment]
Remove `Call`:
```kotlin
@GET("$API_PATH{packageId}?langCode=en")
suspend fun get(@Path("packageId") packageId: String): ApiResponse<GlobalAppConfigPackageDto>
```

**Comment by PhilipSA** [comment]
I am using `void enqueue(Callback<T> callback);` in `Call` to handle error cases like when the server is down for example. If i use your example i would simply get null and not any exceptions of what went wrong right?

**Comment by JakeWharton** [comment]
You would get an IOException or HttpException depending on whether the
failure was network-related or HTTP-related.

**Comment by ziglee** [comment]
But replacing `Call` with `Response` means that now you can't obtain informations about the `Request` anymore.
How to obtain info about `Request` in that case, @JakeWharton ?
