### ISSUE TITLE
Moshi @Json annotation has problem after upgrade to 2.6.0

### ISSUE THREAD

**Issue by biothunder** [square/retrofit#3124]
After upgrade to 2.6.0, response data is ok but cannot convert to data class with using MoshiConverterFactory, all properties get null value after converted.
If Retrofit.Builder change to use GsonConverterFactory and change use @Json annotation to @SerializedName in data class, it works perfectly.

source:

data class BikeData(
    @Json(name = "data")
    val data: Bike
)
data class Bike(...)

@GET("bikes?")
    suspend fun getBikeAsync(
        @Query("frame_number") frameNumber: String
): BikeData

suspend fun getBikeAsync(frameNumber: String): BikeData

**Comment by dkorobtsov** [comment]
@biothunder tried updating Retrofit to 2.6.0, works just fine with Moshi - both Java and Kotlin classes.
Just in case, data classes in kotlin look like:
`data class BikeData(@field:Json(name = "data") val data: Bike?)`

Btw, @JSON does not look like valid Moshi annotation. Should not it be @Json instead?

**Comment by biothunder** [comment]
It's works perfectly now!! Thank you.
