### ISSUE TITLE
NullPointerException for R8 on multi-classes responses

### ISSUE THREAD

**Issue by mkaflowski** [square/retrofit#3125]
I get that errors after obfuscating:
Fatal Exception: java.lang.NullPointerException
throw with null exception
radiofm.apis.models.lastfm.Track.getAlbum (Track.java:3)
radiofm.apis.LastFmRetrofitHandler$1.onResponse (LastFmRetrofitHandler.java:53)
retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$1.run (DefaultCallAdapterFactory.java:83)

The result of response should be object of Example class (Call<Example>).
```
    public class Example {

    @SerializedName("track")
    @Expose
    private Track track;

    public Track getTrack() {
        return track;
    }

    public void setTrack(Track track) {
        this.track = track;
    }
    
}
```

I think that there is a problem when classes used in interfaces has subclasses. For example I get response as object of Album class and that object include field of class Track.

**Comment by JakeWharton** [comment]
Retrofit is not involved in this. It passes the type you declare to the chosen converter (which looks like Gson) and the bytestream of the HTTP response. What happens next is out of Retrofit's control. Crafting rules for each serializer isn't specific to Retrofit and you'll need to consult Gson's documentation, mailing lists, or StackOverflow with the 'gson' tag for appropriate rules.
