### ISSUE TITLE
How to use "@Tag"

### ISSUE THREAD

**Issue by zhaowenliang** [square/retrofit#3127]
`@Tag parameter annotation for setting tags on the underlying OkHttp Request object. These can be read in CallAdapters or OkHttp Interceptors for tracing, analytics, varying behavior, and more.`
How to user "@Tag" in Interceptors? Can I have a Demo ?

**Comment by zhaowenliang** [comment]
How to use "@tag" in Interceptors?

**Comment by JakeWharton** [comment]
The request object allows you to read tags by type: https://square.github.io/okhttp/3.x/okhttp/okhttp3/Request.html#tag-java.lang.Class-

Whatever instance you pass through `@Tag` can be queried on the request object in an interceptor by the argument type.

Here's the test for the feature: https://github.com/square/retrofit/blob/master/retrofit/src/test/java/retrofit2/RequestFactoryTest.java#L2947-L2956

**Comment by zhaowenliang** [comment]
thank you!
