### ISSUE TITLE
How calculate network bandwidth 

### ISSUE THREAD

**Issue by MukFlex** [square/retrofit#3129]
I have implement two type of view for products listing in my app.
1- Grid View -> Showing products images in grid view.
2- Player View -> Showing product video in vertical listing.

When internet is slow then I have to show product in gridview(images) otherwise in playerview.
For this, I have to calculate bandwidth.

I have added GsonConverterFactory while building the Retrofit instance.  I am able to get  time of send request and response time. 

But when I try to get content length, it returns -1 and  also exception.
**Note -**  Server not provide the 'Content-Length' in header.

Exception -   Cannot read raw response body of a converted body.
For the line response.raw().body()?.string()?.length

       Retrofit provideRetrofit(Gson gson, OkHttpClient okHttpClient) {
        Retrofit retrofit = new Retrofit.Builder()
            .addConverterFactory(GsonConverterFactory.create(gson))
            .baseUrl(SERVER_URL)
            .client(okHttpClient)
            .build();
         return retrofit;
       }

Few libraries provide the bandwidth-
https://amitshekhar.me/Fast-Android-Networking/connection_quality.html
https://medium.com/@mohitkumar0571/fast-android-networking-vs-retrofit-vs-volley-32ca4a0e4030

How I get Either content length with conversion factory or network bandwidth using retrofit.

**Comment by JakeWharton** [comment]
This is a usage question which is generally more appropriate for StackOverflow. GitHub issues are reserved for bug reports with test cases or samples, or new feature requests. You can use the 'retrofit' tag which is monitored by us and many library users. Feel free to link the asked question back here on the issue.
