### ISSUE TITLE
[Suggestion]  Move ObjectReader creation to convert method of Jackson converter

### ISSUE THREAD

**Issue by Dimezis** [square/retrofit#3130]
I'm using Retrofit 2.6.0 with Jackson converter and RxJava2CallAdapter.

I noticed that `ObjectMapper.readerFor(javaType)` is a very expensive call and can take around 50ms on an average Android device. It's done in the `JacksonConverterFactory` and in most of the cases takes place on the main thread.

I made a fork of Jackson converter and moved reader creation to `convert` method of `JacksonRequestBodyConverter` and `JacksonResponsetBodyConverter`, because `convert` is usually called on the background thread.

It significantly reduced the time to call a retrofit service method, to something like ~8ms, so the main thread has much less load now.

I'm wondering, is there any reason it wasn't done before? Does this solution have any flaws?
If not, I can make a PR with this change.

**Comment by swankjesse** [comment]
Does `ObjectMapper.readerFor(javaType)` ever fail? Ie. will Jackson throw if it cannot create a reader for a specific type?

**Comment by Dimezis** [comment]
Seems like not. It ends up with calling `ObjectReader._prefetchRootDeserializer`, which says it's not throwing any exceptions:

```
/**
* Method called to locate deserializer ahead of time, if permitted
* by configuration. Method also is NOT to throw an exception if
* access fails.
*/
protected JsonDeserializer<Object> _prefetchRootDeserializer(JavaType valueType)
```

**Comment by swankjesse** [comment]
For example, what happens if I have conflicting annotations in my Jackson configuration?

**Comment by Dimezis** [comment]
At this point - nothing. Jackson won't be able to create a `JsonDeserializer` for this type, but will throw only during actual serialization/deserialization.

**Comment by swankjesse** [comment]
Would be worthwhile offering both eager and lazy options. Going from always eager to always lazy means errors aren't surfaced until you use an API, which could be problematic.

**Comment by Dimezis** [comment]
Actually, the behavior on 2.6.0 is the same, exactly because `ObjectReader._prefetchRootDeserializer` doesn't throw an exception. 
So in these terms, lazy call of `ObjectMapper.readerFor(javaType)` doesn't change the behavior.

**Comment by JakeWharton** [comment]
This behavior is an intentional architecture change from 1.x. The types never change, and so the call adapter and converters are resolved once instead of for each invocation.

Now that we target Java 8 we could possibly something like `asLazy()` to all converter factories and call adapter factories to provide such behavior.

**Comment by JakeWharton** [comment]
Actually for call adapters we still always have to do it synchronously

**Comment by JakeWharton** [comment]
No plans to change this with 2.x series.
