### ISSUE TITLE
when we got exact "timeout"

### ISSUE THREAD

**Issue by ISAIFI** [square/retrofit#3134]
Hi Guys,

I got a SocketTimeoutException in Failure method, in failure method when i call t.getMessage(). it return exact "timeout"
Code below : 

@Override
public void onFailure(Call<ResponseModel> call, Throwable t) {
       String message =  t.getMessage();
}

That message give exact "timeout". In which senario that message we getting.

**Comment by JakeWharton** [comment]
This happens when the connection timeout, read timeout, or write timeout triggers in OkHttp. These values are set on the OkHttpClient. This is an expected error when network connectivity is flaky and should be considered a normal thing to happen in any application.
