### ISSUE TITLE
How to send body on GET Request?

### ISSUE THREAD

**Issue by JavohirYakubov** [square/retrofit#3135]
How to send body on GET Request?

**Comment by ISAIFI** [comment]
@JavohirYakubov We can't send body by using GET method, if you want to send body you can implement POST method

**Comment by JavohirYakubov** [comment]
> @JavohirYakubov We can't send body by using GET method, if you want to send body you can implement POST method

but I can this on PostMan

**Comment by ISAIFI** [comment]
@JavohirYakubov, It is not possible also by postman b'coz postman disable the option of body.

**Comment by JakeWharton** [comment]
OkHttp, the HTTP client which backs Retrofit, disallows a body to be sent with a GET request, per the HTTP spec.
