### ISSUE TITLE
ThreadContextElement doesn't work with suspend functions

### ISSUE THREAD

**Issue by Dkhusainov** [square/retrofit#3137]
retrofit: 2.6.0

In the current implementation of suspend functions `ThreadContextElement` doesn't work them, because the call is enqueued on OkHttp thread pool, ignoring `coroutineContext`

gist with test:
https://gist.github.com/Dkhusainov/e3a74c14f1465ee39e4888cc3f9cc44c

**Comment by JakeWharton** [comment]
This is similar to the behavior as if you wrapped OkHttp or Retrofit's `Call` in `suspendCoroutine` since the threading model is entirely an implementation detail of OkHttp and not Retrofit. I'm not sure there's much we can do here...

**Comment by Dkhusainov** [comment]
You can change the implementation from `enqueue` to `execute` and it will "just work". 
Calling this function inside `suspend fun <T : Any> Call<T>.await(): T {}` passes the test.

```
private suspend fun <T> Call<T>.executeAsync(): Response<T> {
  val call = this
  return suspendCancellableCoroutine { continuation ->

    continuation.invokeOnCancellation { call.cancel() }

    CoroutineScope(continuation.context).launch {
      val result = runCatching(call::execute)
      continuation.resumeWith(result)
    }
  }
}
```

**Comment by JakeWharton** [comment]
We cannot use execute which is mostly a legacy API at this point.

**Comment by Dkhusainov** [comment]
So there is no way for you to fix the issue? Maybe some workaround or options in future versions?

**Comment by JakeWharton** [comment]
I haven't looked into it but it seems unlikely unless OkHttp starts caring
about this explicitly in its handling of threads. Provided we have access
to the whole map we could put it as a request tag, but you'd have to query
it out of the request instead of having it exposed like a thread local.
Don't know. Would have to spend time playing with it.
