### ISSUE TITLE
parsing rest of a url using @Path annotation 

### ISSUE THREAD

**Issue by DarkDeveloper-Plant** [square/retrofit#3139]
There is a confusing problem in this code below:
this is a client interface:
`@HTTP(method = "POST", path = "{url}", hasBody = true)
Call<HtmlModel> getJson(@Body JsonObject code, @Path("url") String secUrl);`

and this is when I use it:
`Call<HtmlModel> listCall = dataClient.getJson(data(code), secUrl);
`
problem is on secUrl variable. When I run something like this is response of that:
`Response{protocol=http/1.1, code=400, message=Bad Request, url=http://exampleDomain.com/%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00rest_of_url.txt}`

and when I parse "rest_of_url.txt" instead of secUrl, it works fine.
note: secUrl = "rest_of_url.txt"

**Comment by JakeWharton** [comment]
Please provide a failing test case or executable sample that demonstrates the problem. As it stands, it looks like there's just a bunch of 0x00 bytes prepended to the string.

**Comment by DarkDeveloper-Plant** [comment]
excuse me I found the solution:I was working with chars so little mistake caused this mess.
