### ISSUE TITLE
Retrofit issue with Coroutine

### ISSUE THREAD

**Issue by halimpuckjava** [square/retrofit#3152]
hi

i use retrofit 2.6.0, with kotlin coroutines 1.2.1, 

1.  so when use Flow an exception appear:

```
@GET("/") suspend fun fetch(): Flow<User>

Exception in thread "main" com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `kotlinx.coroutines.flow.Flow`
``` 

2. i have this case
```
GET("/{id}") suspend fun loadBy(@Path("id") id: Int): User? 
```  
if suppose that the back-end return NotFoundException(......) in failure, so the front-end (client) have an exception of can't cast NotFoundException to User instance (font-end suppose receive a null instance of User in failure) so its possible to use Result<User> instead of User? nullable type however when try to use it i see kotlin not allow Result as return type  

3. even if try to use Result<User> instead of User?, an other exception appear: 
```
Exception in thread "main" com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `kotlin.Result` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
```

**Comment by JakeWharton** [comment]
Flow is not a supported type. Simply remove it and just return User.

If you absolutely need Flow for some reason, you'll want to remove the `suspend` modifier and then register a custom call adapter which supports Flow.

**Comment by vkmdnytr** [comment]
Hi ,
I methinks Corrutines 1.3.40  is not yet published. You can 1.3.40 M
https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-coroutines-android

https://github.com/Kotlin/kotlinx.coroutines

Halim Dev <notifications@github.com>, 7 Tem 2019 Paz, 14:22 tarihinde şunu
yazdı:

**Comment by halimpuckjava** [comment]
thanks

but how about (3) point when returning nullable object on diff format from backend side (ex:  User? vs NotFoundException) ??

**Comment by JakeWharton** [comment]
Can you reproduce that in a failing test case? I don't see that behavior.

**Comment by halimpuckjava** [comment]
backend-side (developed with NESTJS)

```
@Entity()
export class User {
    @PrimaryGeneratedColumn('increment') id: number
    @Column({type: 'varchar', length: 20}) name: string
    @CreateDateColumn() createAt?: Date
}

export class UserController {
  constructor(private readonly userRepository: Repository<User>) {}

  @Get(':id')
  findById(@Param('id') id: number): Observable<any> {
     return from(this.userRepository.findOneOrFail(id)).pipe(catchError(err => of(new NotFoundException(`user [id:${id}] not found`))))
  
}
```

in front-end (retrofit client): 
```
@GET("/{id}") suspend fun findById(@Path("id") id: Int): User?
```
so when client send request to server to find user by id it expect to return user or null if not found, but in server side when user by id not found server return an exception of [NotFoundException] and send it to client, so when client receive response (NotFoundException in failure) it can't cast it to User nullable instance and throw an exception of casting  error

**Comment by atonamy** [comment]
@JakeWharton any link where explains how to register a custom call adapter for Retrofit which supports Coroutines Flow?

**Comment by JakeWharton** [comment]
You would have to build it yourself. Retrofit only supports `suspend` functions for coroutines, not Flow.
