### ISSUE TITLE
400异常

### ISSUE THREAD

**Issue by yuanmaio** [square/retrofit#3154]
07-09 19:17:38.474 7387-7387/com.yt.lantianstore W/System.err: retrofit2.adapter.rxjava2.HttpException: HTTP 400 Bad Request
07-09 19:17:38.474 7387-7387/com.yt.lantianstore W/System.err:     at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:54)
07-09 19:17:38.474 7387-7387/com.yt.lantianstore W/System.err:     at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
07-09 19:17:38.474 7387-7387/com.yt.lantianstore W/System.err:     at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:43)
07-09 19:17:38.474 7387-7387/com.yt.lantianstore W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:11194)
07-09 19:17:38.474 7387-7387/com.yt.lantianstore W/System.err:     at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
07-09 19:17:38.474 7387-7387/com.yt.lantianstore W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:11194)
07-09 19:17:38.475 7387-7387/com.yt.lantianstore W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
07-09 19:17:38.475 7387-7387/com.yt.lantianstore W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:463)
07-09 19:17:38.475 7387-7387/com.yt.lantianstore W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
07-09 19:17:38.475 7387-7387/com.yt.lantianstore W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
07-09 19:17:38.475 7387-7387/com.yt.lantianstore W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-09 19:17:38.475 7387-7387/com.yt.lantianstore W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
07-09 19:17:38.475 7387-7387/com.yt.lantianstore W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
07-09 19:17:38.475 7387-7387/com.yt.lantianstore W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
07-09 19:17:38.475 7387-7387/com.yt.lantianstore W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
07-09 19:17:38.475 7387-7387/com.yt.lantianstore W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by JakeWharton** [comment]
An HTTP 400 was returned by your server. This is just relaying that information.
