### ISSUE TITLE
Parameterized typealias fails the build (moshi-converter)

### ISSUE THREAD

**Issue by e16din** [square/retrofit#3161]
Hello!

I use a moshi-converter and type aliases for response type:
```
typealias ApiResponse<T> = Response<BaseResponse<T>>
typealias ApiResponseList<T> = ApiResponse<ArrayList<T>>
```

And when I do request like this:
```
 @GET("v1/map/")
    suspend fun loadMap(
        // ...
    ): ApiResponseList<MyData>
```

I see the exception "IllegalArgumentException: Unable to create converter for ..." in best way or nothing at all in logcat.
 
I tried it in versions 2.4.0, 2.6.0, 2.7.0-SNAPSHOT.

**Comment by e16din** [comment]
I found a quick fix:
`typealias ApiResponseList<T> = ApiResponse<MutableList<T>>`

**Comment by JakeWharton** [comment]
This doesn't seem related to Retrofit. We just pass the type information along to Moshi.

**Comment by e16din** [comment]
Ok, I just pass the type information along to Moshi Converter. 
Moshi Converter is a part of Retrofit. 
This seem related to Retrofit.
