### ISSUE TITLE
Create POST method with form-data?

### ISSUE THREAD

**Issue by khattab93** [square/retrofit#3165]
I have this body in postman which is a form-data and I want to create a post method with it.
  
![Screen Shot 2019-07-14 at 1 57 31 AM](https://user-images.githubusercontent.com/7592299/61177645-d0708780-a5da-11e9-9b21-2e79fe16ae27.png)

I tried these solutions:
http://stackoverflow.com/questions/29680158/how-to-send-multipart-form-data-with-retrofit
http://stackoverflow.com/questions/37814857/retrofit-2-with-only-form-data
https://gist.github.com/esantiago1/493cd1e2b8597f02c75e8a8a510e7ccb

Could you help me please?

**Comment by halimpuckjava** [comment]
hey
try this code
```
@POST("url")
suspend fun postFormData(@Query("user_number") userNumber: String, @Query("user_password") userPassword: String) : ResultType
```

**Comment by JakeWharton** [comment]
This is a usage question which is generally more appropriate for StackOverflow. GitHub issues are reserved for bug reports with test cases or samples, or new feature requests. You can use the 'retrofit' tag which is monitored by us and many library users. Feel free to link the asked question back here on the issue.
