### ISSUE TITLE
Progress bar for byte[] content

### ISSUE THREAD

**Issue by selvarajmca18** [square/retrofit#3167]
Is there any way to show progress bar when uploading file in byte[] content?

**Comment by JakeWharton** [comment]
If you subclass `RequestBody` you can monitor the progress of how fast bytes are being pushed into the sink. There's a sample in OkHttp for a ResponseBody (https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/Progress.java), but creating a version for RequestBody would be similar. Please ask a question on StackOverflow with the 'retrofit' or 'okhttp' tag if you need further help implementing this.
