### ISSUE TITLE
Retrofit does not throw HttpException when HTTP status code is 500

### ISSUE THREAD

**Issue by JiongBull** [square/retrofit#3168]
In my Interceptor(only one), when response http code is 500,  it won't throw a HttpException.

![](https://user-images.githubusercontent.com/4413502/61355325-b36fd900-a8a6-11e9-8aa5-7e19edde895a.png)

```
var response = chain.proceed(newRequest)
```

How to fix it?
```
var response = chain.proceed(newRequest)
 if (!response.isSuccessful) {
    throw ApiException() // or other exception (HttpException)
}
```

#3036

**Comment by swankjesse** [comment]
This is working as designed.

If this is a bug report please add a failing test case. Otherwise please use StackOverflow.
