### ISSUE TITLE
retrofit2.6 use coroutines will crash when app off-line start

### ISSUE THREAD

**Issue by Lailaizb** [square/retrofit#3171]
how handle this exception.
maybe is unknowHostException.
if use call.enqueue(callback), the callback call handle this exception, but i use suspend, it don't handle exception.
help me

**Comment by JakeWharton** [comment]
Coroutines use normal try/catch blocks to handle exceptions. You can also use standard library functions like `runCatching` if you like.

**Comment by lulululbj** [comment]
> how handle this exception.
> maybe is unknowHostException.
> if use call.enqueue(callback), the callback call handle this exception, but i use suspend, it don't handle exception.
> help me

I met this question too. Have you solved it ?

**Comment by Lailaizb** [comment]
> > how handle this exception.
> > maybe is unknowHostException.
> > if use call.enqueue(callback), the callback call handle this exception, but i use suspend, it don't handle exception.
> > help me
> 
> I met this question too. Have you solved it ?

i used mvvm, it crashes when the network is disconnected, so before I request the BaseViewModel, I decide whether there is a network or not.

**Comment by schatzdesigns** [comment]
Has this issue been solved yet? Am also experiencing the app crashing when offline, or when Socket times out. How do I runCatching?

**Comment by fatihergin** [comment]
> > > how handle this exception.
> > > maybe is unknowHostException.
> > > if use call.enqueue(callback), the callback call handle this exception, but i use suspend, it don't handle exception.
> > > help me
> > 
> > 
> > I met this question too. Have you solved it ?
> 
> i used mvvm, it crashes when the network is disconnected, so before I request the BaseViewModel, I decide whether there is a network or not.

Checking the network status can't guarantee to catch the unknown host exceptions. Unknown host exception is thrown when there is no known server with that address.


> Has this issue been solved yet? Am also experiencing the app crashing when offline, or when Socket times out. How do I runCatching?

I used a workaround by creating an error handling interceptor based on [this Okhttp issue](https://github.com/square/okhttp/issues/4380#issuecomment-437170098)  to solve this issue because it looks like an OkHttp issue more than Retrofit. 
Of course it works if your http client is OkHttp.

**Comment by EmmanuelAmet** [comment]
> Has this issue been solved yet? Am also experiencing the app crashing when offline, or when Socket times out. How do I runCatching?

Well, one way you can solve the issue of Socket  time out is by increasing the call callTimeout, by default it's 10 seconds, so after the 10 seconds if a connection is not established between your application and the server, then the app will be crush.
