### ISSUE TITLE
@POST with @Field not working

### ISSUE THREAD

**Issue by mythio** [square/retrofit#3174]
[BUG]
Retrofit Version : 2.6.0

I tried to create a post request and the response was empty object.
The body of the data to be posted is
```json
{
"language_id" : 1
}
```

```java
@POST("doctors/")
@FormUrlEncoded
Single<DoctorsResponse> getDoctors(
        @Field("language_id") String languageId
);
```
So I tried to do it with @Body and it worked fine
```java
@POST("doctors/")
Single<DoctorsResponse> get(
        @Body Lang land
);
```
Is there something I did wrongly or Is this some bug?

**Comment by JakeWharton** [comment]
Please provide a failing test case or executable sample that demonstrates the problem.

**Comment by mythio** [comment]
@JakeWharton actually it needed to be a `@Query` instead of `@Field`. My bad.
