### ISSUE TITLE
GSON converter factory not working on samsung galaxy s9 phones

### ISSUE THREAD

**Issue by dreamcatcha** [square/retrofit#3176]
What kind of issue is this?

serialization of objects

I test on a Sony Xperia premium and send of serialized object follow the rules of the converter:

    new Builder()
                .baseUrl(API_BASE_URL)
                .addConverterFactory(GsonConverterFactory.create(getGson()));

    public static Gson getGson() {

        return new GsonBuilder()
                .setDateFormat(GSON_DATE_FORMAT)
                .setFieldNamingPolicy(FieldNamingPolicy.LOWER_CASE_WITH_UNDERSCORES)
                .registerTypeAdapter(Long.class, new LongTypeAdapter())
                .setLongSerializationPolicy( LongSerializationPolicy.STRING )
                .create();
    }

and they reach the api as they should like so:

    {
        client_id: '07cffbe0-6df9-4b08-a524-f19b265c17be',
        country: 'xxxx',
        email: 'xxxx',
        first_name: 'xxxx',
        last_name: 'xxxx',
        ....
    }

but on a Samsung Galaxy S9 I get:

    {
        a: '07cffbe0-6df9-4b08-a524-f19b265c17be',
        b: 'xxxx',
        c: 'xxxx',
        d: 'xxxx',
        e: 'xxxx',
        ....
    }

Why would the serialization change?

**Comment by JakeWharton** [comment]
Retrofit does not affect this behavior nor is in a position to control it. The Gson converter just calls Gson APIs. You would presumably get the same behavior from invoking Gson directly, and thus this isn't a Retrofit issue. You're merely using Retrofit to use Gson. Please seek help in a forum more appropriate for Gson such as StackOverflow with the 'gson' tag or on Gson's mailing list or issue tracker.

**Comment by dreamcatcha** [comment]
Sorry mate, it was a completely noob mistake and had nothing to do with retrofit
