### ISSUE TITLE
Add a way to cancel a pending/running request

### ISSUE THREAD

**Issue by romainpiel** [square/retrofit#318]
Currently there is no way to cancel a running request (not that I know of). I've tried multiple things:
- cancelling the task at the executor level (doing a `Future.cancel()`). But I can't see any way to do this.
- cancelling the task from the client itself. OkHttp has a `cancel()` but it only affect enqueued requests. From what I understand, Retrofit only uses the `HttpURLConnection` from the `OkHttpClient` when configured.

What I would suggest is to add an annotation `@TaskId` to the request receiving a String.

``` java
public interface MyService {

     @TaskId("get_users")
     @GET("/users")
     void users(Callback<Users> onComplete);

}
```

This value would then be used to do something like:

``` java
myService.cancel("get_users");
```

when we want to cancel the task.

**Comment by wh5355** [comment]
@zevektor I think this way is also good!
