### ISSUE TITLE
RXJAVA2 - can i return a HOT observable?

### ISSUE THREAD

**Issue by macarthor** [square/retrofit#3180]
hi community,

i have some network APIs for those client does not care about if they succeed or fail.

while rxjava2 adapter only returns observables that must be subscribed to execute the real okhttp call. but i don't need any subscriber to receive the result of success or failure.

so i wonder how can i get the okhttp call executed without subscribing within the rxjava2 adapter scope, or some other methods.

**Comment by xiaojinzi123** [comment]
First of all, a network is cold observable certainly. And your basic question is how to ignore signal and error. Here are some code for you

- you can use Completeable and ignore error
- you can use Single or Observable and ignore error

```java
interface Api {
		Single<xxx> test();
}

api.test()
    // will ignore signal
		.ignoreElement()
    // will ignore error
    .onErrorComplete()
    .subscribe();

```

or 

```java
interface Api {
		Observable<xxx> test();
}

api.test()
  	// will ignore signal
		.ignoreElement()
  	// will ignore error
    .onErrorComplete()
    .subscribe();
```

**Comment by JakeWharton** [comment]
Retrofit does not naturally support hot observables. If you need to ignore the result of a request, you can simply subscribe with an empty subscriber. If you truly want a hot observable, you can use a technique like [this sample][1] which adds a call to `observeOn` and rewrite it to add something like `.publish().autoConnect(0)` (or whatever hot-making operator you want).

 [1]: https://github.com/square/retrofit/blob/8c93b59dbc57841959f5237cb141ce0b3c18b778/samples/src/main/java/com/example/retrofit/RxJavaObserveOnMainThread.java
