### ISSUE TITLE
Retrofit holding/retaining VM when using suspending functions

### ISSUE THREAD

**Issue by Gloix** [square/retrofit#3194]
Bug: When querying an API through suspending method calls in Retrofit 2.6.1 the VM won't stop even though all coroutines are done executing.

Here's a sample project: https://github.com/Gloix/RetrofitVMExecutionRetainerExample

**Comment by JakeWharton** [comment]
This comes from OkHttp use of a thread pool for connection management. Retrofit doesn't have any threads.

See the "Shutdown isn't necessary" section of https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.html. This also means you have to explicitly pass in an OkHttpClient to `Retrofit.Builder.client` when creating your `Retrofit` instance.
