### ISSUE TITLE
Requirements documentation mismatch on website and README.md

### ISSUE THREAD

**Issue by spiderhands** [square/retrofit#3196]
On the website (https://square.github.io/retrofit/#download) 

> Retrofit requires at minimum Java 7 or Android 2.3.

On the github (https://github.com/square/retrofit#download)

> Retrofit requires at minimum Java 8+ or Android API 21+.

Which one is correct?

**Comment by JakeWharton** [comment]
Both are correct. The website reflects the released version. `master` reflects the in-development version. If you browse the code for the latest tag, you'll see that it matches the website.

**Comment by MarcelReiter** [comment]
If i'm not mistaken this issue should be opened again due to version updates?
