### ISSUE TITLE
Retrofit 2.6.1 Here's a error occured when I  invoke the method named baseUrl of Retrofit's Builder

### ISSUE THREAD

**Issue by JPMonty** [square/retrofit#3197]
` Retrofit retrofit = new Retrofit.Builder(
                .baseUrl("http://www..baidu.com/")
                .build();
`

### **when i execute the code on above, an exception is thrown immediately.**

`java.lang.NoSuchMethodError: okhttp3.HttpUrl.get(Ljava/lang/String;)Lokhttp3/HttpUrl;
	at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:470)
`

**Comment by JPMonty** [comment]
I found that bug could be resolved if  I  degraded  version to 2.4.0.

**Comment by JakeWharton** [comment]
Retrofit 2.6.1 depends on OkHttp 3.12 which has that method: https://static.javadoc.io/com.squareup.okhttp3/okhttp/3.12.0/okhttp3/HttpUrl.html#get-java.lang.String-

Your build system or your build system configuration is likely lowering the version of OkHttp to a version which did not contain that method. You will need to find and correct that.
