### ISSUE TITLE
Retrofit POST request not working with Androi build tools 3.5.0

### ISSUE THREAD

**Issue by coomar2841** [square/retrofit#3204]
I updated by build tools from 3.4.1 to 3.5.0. And suddenly, all Retrofit POST requests started sending empty JSON body requests. These are the versions that I am using.

    implementation 'com.squareup.retrofit2:retrofit:2.5.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.5.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.12.0'

Took 2 hours to figure out this was the issue. As soon as I update the tools version, I see this behaviour. Not sure, if it's a Retrofit issue or build tools issue.

**Comment by coomar2841** [comment]
Sorry. It seems to be some other problem.

**Comment by nick2425** [comment]
We've also just observed this issue, did you work out a fix?

**Comment by nick2425** [comment]
This looks promising:
https://stackoverflow.com/a/57883405/1568082
