### ISSUE TITLE
Bug report: Sending duplicate headers when setting a header on interceptor and on the interface declaration via @Header

### ISSUE THREAD

**Issue by ColtonIdle** [square/retrofit#3208]
I'm setting a header `APP: WEB` via an interceptor so it's on every call. Works great, but there is one call that I want to override the interceptor header and so I set it via `@Headers("APP: ANDROID")` but now my network request has two headers with the same name. Let me know if you want me to send over a project with a repro.

**Comment by JakeWharton** [comment]
Sounds like your interceptor needs to check for the presence of the header before unconditionally adding it. This isn't a problem with Retrofit.

**Comment by ColtonIdle** [comment]
@JakeWharton I thought the direct @Header annotation takes precedence. Similar to how styles work in android. Guess my head was stuck thinking in that format. This makes sense too. Thanks for clarifying.

**Comment by JakeWharton** [comment]
Retrofit doesn't know anything about your interceptors. It creates the
request object with either 0 or 1 App header and sends it over to OkHttp.
