### ISSUE TITLE
 NullPointerException after publishing app to play store

### ISSUE THREAD

**Issue by WeslleyBriito** [square/retrofit#3210]
After the app was published in the store I had the following error:

 java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at br.com.www.app5m.querocuidador.inicio.auth.LoginActivity.b(:2)
        at c.a.b.a.a.f.i.m.a(:5)
        at l.n.run()
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6349)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

It's my request:

public interface WebService {

@POST("user/register/login")
Call<List<User>> u_login(@Body User u);

}

public class WSUser {

    private Context context;
    private AuthUser authUser;
    private Useful useful;
    private Preferences preferences;

    public WSUser(Context context, AuthUser authUser) {
        this.context = context;
        this.authUser = authUser;
        this.useful = new Useful(context);
        this.preferences = new Preferences(context);
    }

public void loginUser(User user) {
        //useful.openLoading("Aguarde...");
        WebService service = useful.getRetrofit(false).create(WebService.class);

        Call<List<User>> param = service.u_login(user);
        param.enqueue(new Callback<List<User>>() {
        @Override
        public void onResponse(@NonNull Call<List<User>> call, @NonNull final 
                Response<List<User>> response) {
                //useful.closeLoading();
                if (response.isSuccessful())
                    authUser.getAuth(response.body() != null ? response.body().get(0) : null, "login");
                else
                    authUser.getError("Unexpected error.");
            }

            @Override
            public void onFailure(@NonNull Call<List<User>> call, @NonNull Throwable t) {
                //useful.closeLoading();
                Toast.makeText(context,"Could not contact server.", Toast.LENGTH_SHORT).show();
            }
        });

    }

}
When I run the apk directly on my phone it works well, but when put in the store it happens, does anyone have any idea what it might be?

**Comment by JakeWharton** [comment]
It's not clear why you think Retrofit is to blame, but without a deobfuscated stacktrace it's impossible to discern even the slightest idea as to the real cause.
