### ISSUE TITLE
why is the RxJava2CallAdapter.java marked error?

### ISSUE THREAD

**Issue by JakeRain** [square/retrofit#3212]

**Comment by JakeRain** [comment]
75  if (isFlowable) {
76      return observable.toFlowable(BackpressureStrategy.LATEST);
77    }

**Comment by JakeWharton** [comment]
I'm not sure what you're asking but that API is defined here: http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html#toFlowable-io.reactivex.BackpressureStrategy-
