### ISSUE TITLE
Error while generating signed APK V2.6.2

### ISSUE THREAD

**Issue by krishnameena** [square/retrofit#3214]
Unknown option '-if' in line 46 of file 

Following rules I have added

`# Retrofit does reflection on generic parameters. InnerClasses is required to use Signature and
# EnclosingMethod is required to use InnerClasses.
-keepattributes Signature, InnerClasses, EnclosingMethod

# Retrofit does reflection on method and parameter annotations.
-keepattributes RuntimeVisibleAnnotations, RuntimeVisibleParameterAnnotations

# Retain service method parameters when optimizing.
-keepclassmembers,allowshrinking,allowobfuscation interface * {
    @retrofit2.http.* <methods>;
}

# Ignore annotation used for build tooling.
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement

# Ignore JSR 305 annotations for embedding nullability information.
-dontwarn javax.annotation.**

# Guarded by a NoClassDefFoundError try/catch and only used when on the classpath.
-dontwarn kotlin.Unit

# Top-level functions that can only be used by Kotlin.
-dontwarn retrofit2.KotlinExtensions
-dontwarn retrofit2.KotlinExtensions$*

# With R8 full mode, it sees no subtypes of Retrofit interfaces since they are created with a Proxy
# and replaces all potential values with null. Explicitly keeping the interfaces prevents this.
-if interface * { @retrofit2.http.* <methods>; }
-keep,allowobfuscation interface <1>`

**Comment by JakeWharton** [comment]
You have to be using ProGuard 6 or newer for `-if` support. I think this corresponds to AGP 3.1 or 3.2.

**Comment by krishnameena** [comment]
I am using proguard v 6.0.3

**Comment by JakeWharton** [comment]
Are you specifying that explicitly? Or is that in the output of the Gradle
buildEnvironment task?

**Comment by krishnameena** [comment]
Its  is that in the output of the Gradle
buildEnvironment task

**Comment by JakeWharton** [comment]
The [ProGuard change log](https://www.guardsquare.com/en/products/proguard/manual/versions) details that `-if` was introduced in 6.0 so I'm not sure what to tell you. Can you reach out to their support?
