### ISSUE TITLE
Connect to file url without response body

### ISSUE THREAD

**Issue by VeiZhang** [square/retrofit#3218]
Hello, there is a situation.
I want to download a file, but before that, I want to check whether the file url is valid.
Then I create a request to connect the file url, but the response body return file stream, the file stream affect response speed and it is not necessory.
```
@GET
Observable<Response<ResponseBody>> connect(@Url String url);
```
**Please give me a help how to connect file url without the file stream, I just want to get the header and http code.**

**Comment by VeiZhang** [comment]
I used `@HEAD`, but the server refused to connect.

**Comment by VeiZhang** [comment]
```
@GET
Observable<Response<Void>> connect(@Url String url);
```
Maybe it is ok? I am not sure, but it is fast return.

**Comment by JakeWharton** [comment]
This is a usage question which is generally more appropriate for StackOverflow. GitHub issues are reserved for bug reports with test cases or samples, or new feature requests. You can use the 'retrofit' tag which is monitored by us and many library users. Feel free to link the asked question back here on the issue.
