### ISSUE TITLE
java.io.EOFException: End of input at line 1 column 1 path $

### ISSUE THREAD

**Issue by Morons** [square/retrofit#3229]
I launch this request with retrofit_version = '2.6.2'
My data actually get saved on my Server (API) Side but I still get this error

My Retrofit Request
Request{method=POST, url=http://poseidon.mail.com:8080/api/networkers/, tags={class retrofit2.Invocation=za.co.zone.marketingapp.data.network.api.MarketingApiService.upsertNetworkerAsync() [NetworkerData(id=null, name=Steve, lastName=Jobs, phone=1081010810, email=steve.jobs@gmail.com, timestamp=2019-10-15T10:32:27.641, addressId=null, networkerSettings=null, networkerSecurity=NetworkerSecurity(username=steve, password=password, active=true, roles=[USER, API], permissions=[USER, API]))]}}

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: za.co.zone.marketingapp, PID: 27127
    java.io.EOFException: End of input at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1397)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:550)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:426)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:207)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:39)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:121)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
I/Process: Sending signal. PID: 27127 SIG: 9
Process 27127 terminated.

**Comment by Morons** [comment]
Setting some debugging points to capture the true request to simulate the POST with Postman I got the following results confirming that the request is valid and the returning data is actually perfect
I copied the JSON value directly from the debugger and pasted it into Postman - set the POST URL and executed with perfect result!
![RetrofitBug1](https://user-images.githubusercontent.com/22202038/66835713-51d01100-ef60-11e9-8fc2-c784683b7f98.JPG)
![RetrofitBug2](https://user-images.githubusercontent.com/22202038/66835734-598fb580-ef60-11e9-9374-62678828e44d.JPG)

**Comment by JakeWharton** [comment]
This usually happens when you inadvertantly consume the body in an interceptor. Do you have any interceptors? Can you express the problem in a failing test case or executable sample?

**Comment by Morons** [comment]
This is my API I guess the addInterceptor(requestInterceptor) is a good starting point?
addInterceptor(connectivityInterceptor)  handles the event of no internet connections

This exact API works for the @GET request perfectly! but failes on the @POST
Thanx so far @JakeWharton 
```
interface MarketingApiService {
	
	@GET(value = PROGRESS_URL)
	fun getProgressAsync(): Deferred<ProgressResponse>
	
	@GET(value = "$PROGRESS_URL/{ID}")
	fun getProgressSelfAsync(@Path(value = "ID") ID: String): Deferred<ProgressEntry>
	
	@POST(value = PROGRESS_URL)
	fun upsertProgressEntryAsync(@Body progressData: ProgressData): Deferred<ProgressEntry>
	
	companion object {
		operator fun invoke(
			connectivityInterceptor: ConnectivityInterceptor // injecting interface (Kodein)
		): MarketingApiService {
			
			val requestInterceptor = Interceptor { chain ->
				
				val url = chain.request()
					.url()
					.newBuilder()
					.build()
				val request = chain.request()
					.newBuilder()
					.url(url)
					.build()
				
				return@Interceptor chain.proceed(request)
			}
			
			val okHttpClient = OkHttpClient.Builder()
				.addInterceptor(requestInterceptor)
				.addInterceptor(connectivityInterceptor) // injected interface via Kodein
				.build()
			
			return Builder()
				.client(okHttpClient)
				.baseUrl(BASE_URL)
//				.addConverterFactory(nullOnEmptyConverterFactory)
				.addCallAdapterFactory(CoroutineCallAdapterFactory())
				.addConverterFactory(GsonConverterFactory.create())
				.build()
				.create(MarketingApiService::class.java)
		}
	}
}
```
and the interceptor
```
class ConnectivityInterceptorImpl(
	context: Context
) : ConnectivityInterceptor {
	
	private val appContext = context.applicationContext
	
	override fun intercept(chain: Interceptor.Chain): Response {
		if (!isOnline())
			throw NoConnectivityException()
		return chain.proceed(chain.request())
	}
	
	private fun isOnline(): Boolean {
		val connectivityManager = appContext.getSystemService(Context.CONNECTIVITY_SERVICE)
				as ConnectivityManager
		
		val networkInfo = connectivityManager.activeNetworkInfo
		return networkInfo !== null && networkInfo.isConnected
	}
}
```

**Comment by anandrex5** [comment]
I have been facing the same issue for such days and I checked this solution [Link](https://stackoverflow.com/a/55455017/18099730) -
    
You can get this error when you are expecting an object in the response, but the API doesn't return anything other than result codes (200,...). Options: - Check that the API returns a ServerResponse. - If you don't need it to return anything, use Observable<Response<Void>> instead of Observable<ServerResponse>
    
    
    this is my old working face with this issue Log : AddTaskError - End of input at line 1 column 1 - 
    
       @POST("/Api/AddUpdateTask")
            fun addUpdateTask(
                @Header("Content-Type") contentType: String?,
                @Header("SessionId") session: String?,
                @Body requestBody: RequestBody
            ): Call<JsonObject>
    
    and this is my method -
    private fun addTaskApi() {
            try {
                customProgress?.show("")
            } catch (e: BadTokenException) {
                e.printStackTrace()
            }
    
            val showObserId = JSONArray().apply {
                if (!observerid.isNullOrEmpty()) {
                    observerid!!.split(",").forEach {
                        put(it)
                    }
                }
            }
    
            val showUserId = JSONArray().apply {
                if (!assignId.isNullOrEmpty()) {
                    assignId!!.split(",").forEach {
                        put(it)
                    }
                }
            }
    
            if (!Utils.isNetworkAvailable(this@AddTask)) {
                Toast.makeText(applicationContext, "Internet not available", Toast.LENGTH_LONG).show()
            } else {
                try {
                    val apiClient = RetroApi.client?.create(APIClient::class.java) ?: return
                    val postdata = JSONObject().apply {
                        put("TaskId", 0)
                        put("TaskLeadId", chooseLeadId)
                        put("TaskTitle", etTaskName!!.text.toString())
                        put("TaskDescription", Html.toHtml(etTaskDescription!!.text))
                        put("TaskCreatedBy", 0)
                        put("TaskAssignTo", showUserId)
                        put("TaskObserver", showObserId)
                        put("TaskStartDate", tvStartdate!!.text.toString())
                        put("TaskEndDate", tvEndDate!!.text.toString())
                        put("TaskCreatedDate", tvStartdate!!.text.toString())
                        put("TaskModifiedDate", tvStartdate!!.text.toString())
                        put("TaskStatus", 0)
                        put("IsTaskActive", activeValue)
                        put("IsDeleted", isDeleted)
                        put("TaskCompanyId", 0)
                        put("TaskPriority", leadPriorityId)
                    }
                    Log.d("request_edit_addtask", postdata.toString())
                    val requestBody =
                        postdata.toString().toRequestBody("application/json".toMediaTypeOrNull())
                    val call = apiClient.addUpdateTask(
                        "application/json",
                        sharedManager!!.sessionID,
                        requestBody
                    )
                    call.enqueue(object : Callback<JsonObject> {
                        override fun onResponse(
                            call: Call<JsonObject>,
                            response: Response<JsonObject>
                        ) {
                            customProgress?.hide()
                            if (response.isSuccessful) {
                                val responseBody = response.body()
                                Log.d(
                                    "addTaskApiResponseBody",
                                    responseBody?.toString() ?: "Empty response body"
                                )
                                if (responseBody != null) {
                                    processResponseAddTask()
                                } else {
                                    Log.e("Error", "Empty or null response body")
                                    runOnUiThread {
                                        Toast.makeText(
                                            this@AddTask,
                                            "Empty or null response body",
                                            Toast.LENGTH_SHORT
                                        ).show()
                                    }
                                }
                            } else {
                                val errorBody = response.errorBody()?.string()
                                Log.e("Error_Response", errorBody ?: "Empty error response body")
                                if (response.code() == 401) {
                                    Toast.makeText(
                                        this@AddTask,
                                        "Unauthorized request",
                                        Toast.LENGTH_SHORT
                                    ).show()
                                    LogOutApi(this@AddTask)
                                } else {
                                    runOnUiThread {
                                        Toast.makeText(
                                            this@AddTask,
                                            "Error: ${response.message()}",
                                            Toast.LENGTH_SHORT
                                        ).show()
                                    }
                                }
                            }
                        }
    
                        override fun onFailure(call: Call<JsonObject>, t: Throwable) {
                            customProgress?.hide()
                            t.printStackTrace()
                            Log.e("AddTaskError", "API call failed: ${t.message}")
                        }
                    })
                } catch (e: Exception) {
                    e.printStackTrace()
                }
            }
        }
    
    Solution is -  
    
    @POST("/Api/AddUpdateTask")
        fun addUpdateTask(
            @Header("Content-Type") contentType: String?,
            @Header("SessionId") session: String?,
            @Body requestBody: RequestBody
        ): Call<Void>   //Change this 
    
    
and this part -
    
     call.enqueue(object : Callback<Void> {
                    override fun onResponse(call: Call<Void>, response: Response<Void>) {
                        customProgress?.hide()
                        if (response.isSuccessful) {
                            Log.d("SuccessfulResponse", "Response body: ${response.body()?.toString()}")
                            Log.d("SuccessfulResponse", "Response code: ${response.code()}")
                            processResponseAddTask()
                        } else {
                            val errorCode = response.code()
                            Log.e("AddTaskErrorResponse", "API call failed with error code: $errorCode")
                            val errorBody = response.errorBody()?.string()
                            Log.e("Error_Response", errorBody ?: "Empty error response body")
                            runOnUiThread {
                                Toast.makeText(
                                    this@AddTask,
                                    "Error: ${response.message()}",
                                    Toast.LENGTH_SHORT
                                ).show()
                            }
                        }
                    }

                    override fun onFailure(call: Call<Void>, t: Throwable) {
                        customProgress?.hide()
                        t.printStackTrace()
                        Log.e("AddTaskError", "API call failed: ${t.message}")
                    }
                })

for me its working fine.
