### ISSUE TITLE
Warning in proguard rules

### ISSUE THREAD

**Issue by henningBunk** [square/retrofit#3234]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Hi there,  
with Android Studio 4 we have highlighting for proguard rules. With [these](https://github.com/square/retrofit/blob/master/retrofit/src/main/resources/META-INF/proguard/retrofit2.pro) rules I get the following warning: 

    colon, comma, left paranthesis or semicolon expexted, got '$'

for line 24. Are the rules correct or is the Android Studio warning at fault?

Cheers!

**Comment by hqzxzwb** [comment]
This rule is meant for proguard. R8 does not use `dontwarn`. `dontwarn`s should be safely ignored by R8 but clearly it is not. So I assume this is an R8 bug.  If you are using R8, it's safe to just delete that line.

**Comment by JakeWharton** [comment]
Please file a bug against Android studio. The dollar sign is a perfectly valid character to appear in a qualified class name.

**Comment by legd** [comment]
I’m having this same issue after upgrading to android studio 4, can someone please tell me where can I find the solution?  I'm stuck with this issue and I couldn't find any solution

**Comment by hqzxzwb** [comment]
> I’m having this same issue after upgrading to android studio 4, can someone please tell me where can I find the solution? I'm stuck with this issue and I couldn't find any solution

@legd Just remove the rules from your project. Retrofit packages the rules under META-INF/proguard. R8 uses these rules automatically.

**Comment by Abhimanyu14** [comment]
Filed an issue in Android Studio issue tracker,
https://issuetracker.google.com/issues/195621744
