### ISSUE TITLE
 retrofit  need java8 and android 21+ on version 2.6.2?

### ISSUE THREAD

**Issue by xchengDroid** [square/retrofit#3237]
What kind of issue is this?

 - [x] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Did retrofit 2.6.2  not run on  java7 or android 21-?

**Comment by PromanSEW** [comment]
2.6.2 does not need Java 8

**Comment by xchengDroid** [comment]
@PromanSEW  thank you, readme show require java8 and android Api21+

**Comment by JakeWharton** [comment]
The readme reflects the code on master. If you want to see the readme for a particular version you can browse to the corresponding tag on GitHub.
