### ISSUE TITLE
java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/reflect/Method;ILjava/lang/String;Lretrofit2/Converter;Z)V in class Lretrofit2/ParameterHandler$Path

### ISSUE THREAD

**Issue by ronjunevaldoz** [square/retrofit#3239]
What kind of issue is this?
I'm having this kind of error when calling method from interface, I'm really stuck on this part

```
def retrofit_version = '2.6.2'
def okhttp_version = '3.12.0'
def koin_version = '2.0.1'
def coroutine_version = '1.3.2'
def room_version = '2.2.1'
```
```
interface MainService {
    @GET("api/user/{uid}")
    suspend fun getUser(@Path("uid") uid: String): UserResponse
}
```

```
 GlobalScope.launch {
   runCatching {
                mainService.getUser(uid)
    }.onSuccess {
                usersDao.insertUser(it.data)
    }
                .onFailure(::handleFailure)
    }
```

`java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/reflect/Method;ILjava/lang/String;Lretrofit2/Converter;Z)V in class Lretrofit2/ParameterHandler$Path; or its super classes (declaration of 'retrofit2.ParameterHandler$Path' appears in /data/data/com.ronscript.bountytips/app_working/vungle.dex)`

**Comment by JakeWharton** [comment]
This is likely the result of post-processing and not a Retrofit issue. Are you using R8, ProGuard, or DexGuard?
