### ISSUE TITLE
Receiving incomplete response from retrofit

### ISSUE THREAD

**Issue by kaushikburkule** [square/retrofit#3241]
I am using retrofit version 2.6.1 for making http request over the network. The JSON i am expecting is 42466 character long. However i am receiving only 4073 character and API are working fine on web broswer and postman.

So i added custom okhttp client and increses timeout but it does not help me. Then i tried adding logging interceptor and i found that okhttp is receiving the reponse what i wanted in interceptor logs but in chunks.

At last i assigned http client and interceptor to retrofit builder. So i think using post request will help me rather than get and tried taking all the response in string format to check the reponse

But it also did not get to conclusion after that i thought http response will have size limit and used reader to access the json from url by following way.

I also added this `.addConverterFactory(ScalarsConverterFactory.create())` in case to check response but issue persist the same
 
Also asked in stackverflow : [https://stackoverflow.com/q/58615323/7639056](url)

**Comment by kaushikburkule** [comment]
Checkout the link given stackoverflow link for answer.

**Comment by joimxjtuse** [comment]
i think you'd better check HTTP Header : "Content-Length" to ensure server response the right length.
