### ISSUE TITLE
Implementation details about Response.java

### ISSUE THREAD

**Issue by hellos1923** [square/retrofit#3242]
What kind of issue is this?

 - [x] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Hi, why did you set "http://localhost/" as URL in the class Response.java? What does it mean "synthetic successful response" in that context? I am trying to understand the implementation of your APIs. Thank you for making it available!

**Comment by JakeWharton** [comment]
OkHttp requires that we set a URL and since the responses are fake that seemed like an easy value to use. Maybe we should use `example.com` instead? I don't know.
