### ISSUE TITLE
Why HEAD request must return Void as responseType?

### ISSUE THREAD

**Issue by zqturtle** [square/retrofit#3244]
I just want to send a HEAD request and get the response headers's CONTENT_LENGTH.  For example: get video size
@HEAD("videoUrl")  
Observable<ResponseHeader> getVideoSize();
However the response type must be void. 
// TODO support Unit for Kotlin?
    if (requestFactory.httpMethod.equals("HEAD") && !Void.class.equals(responseType)) {
      throw methodError(method, "HEAD method must use Void as response type.");
    }

**Comment by JakeWharton** [comment]
Because there is no body. What are you suggesting?

**Comment by zqturtle** [comment]
I want to get the response header but don't download it, since the response body may be large. Use HEAD request can't get the response header.

**Comment by JakeWharton** [comment]
Ah, I see. You can use `Response<Void>` as the type to access all of the information of the response aside from just the body. This works with _any_ type of request, not just HEAD.

**Comment by zqturtle** [comment]
just like this demo:
ExecutorService cachedThreadPool = Executors.newCachedThreadPool();
        cachedThreadPool.execute(new Runnable() {
            @Override
            public void run() {
                HttpURLConnection urlConnection = null;
                int responseLength;
                try {
                    URL url = new URL(videoUrl);
                    urlConnection = (HttpURLConnection) url.openConnection();
                    urlConnection.setRequestMethod("HEAD");
                    urlConnection.setConnectTimeout(500);
                    urlConnection.connect();
                    responseLength = urlConnection.getContentLength();

                } catch (Exception e) {
                    //ignore
                } finally {
                    if (urlConnection != null) {
                        urlConnection.disconnect();
                    }
                }
              //handler send responseLength
            }
        });

**Comment by zqturtle** [comment]
ok, thank you
