### ISSUE TITLE
[Bug report] Link in document die

### ISSUE THREAD

**Issue by thaycacac** [square/retrofit#3245]
This link [Sonatype's snapshots repository](https://oss.sonatype.org/content/repositories/snapshots/) in document die

![Screen Shot 2019-11-11 at 23 04 23](https://user-images.githubusercontent.com/29374426/68601786-a327dd80-04d7-11ea-8259-94f0c0d0c73f.png)

**Comment by JakeWharton** [comment]
The link is actually still correct, they just removed the ability to browse
it. But it's the URL that you would put into a maven { url '' } block in
Gradle or a <repository> tag in Maven.
