### ISSUE TITLE
[Feature] Suspend function CallAdapter to not require wrapping return type in Call

### ISSUE THREAD

**Issue by tinder-aaronweaver** [square/retrofit#3246]
Currently, https://github.com/square/retrofit/pull/3040 has added the ability to use call adapters for suspend functions within Retrofit 2.6.X, but it requires call adapters to specifically return the `Call` type 

Example: `CallAdapter<T, MyResponseWrapper<T>>` 

The above call adapter will fail when the return type for a retrofit api method marked as a suspend function is `MyResponseWrapper<T>`, as it is attempting to cast your response type to `Call<MyResponseWrapper<T>>`

The current workaround is to simply make your call adapter wrap the ultimate return type to `Call<...>`. My expectation of call adapters, however, has always been that re-wrapping them to the `Call` type is unnecessary. 

Making this align with previous implementations would allow for call adapters to remain consistent even with the introduction of suspend functions.

Related Issue: https://github.com/square/retrofit/issues/3193
Related Stackoverflow Post w/ Workaround: https://stackoverflow.com/questions/57625272/retrofit-2-6-0-custom-coroutines-calladapterfactory

**Comment by JakeWharton** [comment]
The easiest way to reconcile your mental model is to think of the `suspend` modifier as automatically calling `enqueue` on a `Call`. Thus, the thing you actually need to return is still a `Call` that can be asynchronously executed.

> My expectation of call adapters, however, has always been that re-wrapping them to the `Call` type is unnecessary.

This is not correct. Call adapters have always had the ability to return `Call` to intercept the built-in `Call` behavior. For example, if you were doing JSON-RPC and wanted to unwrap the response envelope you might do
```kotlin
@JsonRpc
@POST("whatever/url/")
fun whatever(): Call<ResponseType>
```
and use a `CallAdapter` to internally delegate with a response type of `Envelope<ResponseType>` and then take the resulting `Call<Envelope<ResponseType>>` and wrap it in an envelope-unwrapping instance which produces the returned `Call<ResponseType>`.

Historically, the mechanism for call adapters only handled the synchronous case where you call the function and are immediately returned an encapsulation of the HTTP request. `suspend` works differently as it actually triggers the request and does not conceptually return until it is complete. While conceptually synchronous, it is fundamentally asynchronous and `CallAdapter<T, ResponseType>` cannot model that. That is a synchronous function. So we need a way to change it to behave asynchronously. Thus, `CallAdapter<T, Call<ResponseType>>` is a synchronous function that produces a lazy HTTP request that can then be triggered with a listener producing the asynchronous behavior.
