### ISSUE TITLE
onFailure doesn't get called when losing network connection

### ISSUE THREAD

**Issue by JKorsten** [square/retrofit#3248]
Hey,

I'm using Retrofit and OkHttp to get data from a server and to download files from a server. The happy flow works as intended. But when something goes wrong (I pull out the network cable so my system loses connection) I would expect to get a onFailure to which I could respond. But I don't get anything.

I've followed this tutorial to implement it and I've made minor changes: https://futurestud.io/tutorials/retrofit-2-how-to-download-files-from-server

My timeouts are:
`httpClientBuilder.connectTimeout(5, TimeUnit.SECONDS);
httpClientBuilder.writeTimeout(0, TimeUnit.SECONDS);
httpClientBuilder.readTimeout(5, TimeUnit.SECONDS);
httpClientBuilder.callTimeout(5, TimeUnit.SECONDS);`

Now I would expect to have a onfailure when the network is lost but I don't get anything.
What am I doing wrong?

Kind regards,

JKorsten

**Comment by swankjesse** [comment]
Could you provide an executable test case? MockWebServer has “pull the plug” features if you look at SocketPolicy.

**Comment by JKorsten** [comment]
Hello swankjesse,

The sourcecode I have is exactly the same as the link I've provided. When I'm downloading a bigger file and I pull out the lan cable (this is my losing connection way of reproducing)  I don't get a callback.

I'll look at mockwebserver.

**Comment by JakeWharton** [comment]
Most of the built-in tests for Retrofit itself use MockWebServer
