### ISSUE TITLE
404 respons with jio network..

### ISSUE THREAD

**Issue by hirenpatel868** [square/retrofit#3251]
Integrated retrofit in android application for api calls.application works fine with wifi or other telephone operators expect jio. when try to call api using jio mobile data its respond with httpCode 404

**Comment by JakeWharton** [comment]
It's hard to see how Retrofit could have anything to do with this. A 404 means the server received your request and chose to reject it, and the fact it does so only on some networks is far, far outside of Retrofit's control.
