### ISSUE TITLE
use javadoc.io for javadoc hosting?

### ISSUE THREAD

**Issue by maxcellent** [square/retrofit#3256]
Not sure how javadoc is managed currently. But I assume there will be some manual work invovled. So hope this could save some effort on every release.

Basically https://javadoc.io/doc/com.squareup.retrofit2/retrofit will always point to the latest version published to JCenter / Central Maven. 

Or you can add a badge with versions always up to date:

`
[![javadoc](https://javadoc.io/badge2/com.squareup.retrofit2/retrofit/javadoc.svg)](https://javadoc.io/doc/com.squareup.retrofit2/retrofit)
`

[![javadoc](https://javadoc.io/badge2/com.squareup.retrofit2/retrofit/javadoc.svg)](https://javadoc.io/doc/com.squareup.retrofit2/retrofit)

Disclaimer: I creates javadoc.io

**Comment by swankjesse** [comment]
Neat service! But I don’t understand your business model so I fear you or your successors may eventually monetize with ads or tracking. We like hosting on GitHub and would prefer for you to take down your mirror as it competes with the official one we host.

**Comment by maxcellent** [comment]
It's my personal project created 5 years ago, and I noticed more and more popular libraries (like mockito / gson) are using it recently, so I thought maybe I should actively approach more projects as this could help for wider group.

I haven't thought of monetizing myself. It's not yet open sourced only because the code need to be well refactored to remove all my personal details (like personal AWS tokens etc)
