### ISSUE TITLE
Better documentation would be helpful

### ISSUE THREAD

**Issue by jilvin** [square/retrofit#3257]
Wonderful work with the library. Kudos!

The present documentation available on the website(not Javadoc) seems inadequate. I was wondering if we could improve the documentation with more sections including but not limited to standard usage on Android and others.

**Comment by swankjesse** [comment]
We’ll continue to work on our own documentation. In the interim there's lots of great third-party documentation.

https://duckduckgo.com/?q=retrofit+android

**Comment by jilvin** [comment]
Third party documentation sometimes seems inadequate particularly towards standard practices to be followed. Appreciate the work with the library. Glad to hear that work on official documentation is in progress.

Towards a better future. Cheers.
