### ISSUE TITLE
I expect to get interface class annotations when customize Converter

### ISSUE THREAD

**Issue by chentianming11** [square/retrofit#3258]
In order to achieve more features, I need use class annotations in customized Converter.
![image](https://user-images.githubusercontent.com/30620547/69613174-1569f780-106c-11ea-9291-be4889ece0f6.png)

**Comment by JakeWharton** [comment]
Do you have a specific use case? What about when you are merely a part in a multipart request?

**Comment by chentianming11** [comment]
What you said makes sense, using the method annotation is  more suitable.
