### ISSUE TITLE
Not compatible with coroutines kotlinx-coroutines-rx2

### ISSUE THREAD

**Issue by CarsonRedeye** [square/retrofit#3260]
See reproduction here https://github.com/Kotlin/kotlinx.coroutines/issues/1671.
I'm not sure in which library the bug is, or if I'm just using it wrong.

**Comment by JakeWharton** [comment]
I'm already following that bug! 😀

**Comment by CarsonRedeye** [comment]
Wow you're onto it haha!

**Comment by CarsonRedeye** [comment]
Seems like it was a coroutines problem
