### ISSUE TITLE
@path annotation always do url encode

### ISSUE THREAD

**Issue by lizhaode** [square/retrofit#3264]
What kind of issue is this?

 - [x] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

the interface code like this

```groovy
@GET('/{sub_url}')
Call<ResponseBody> anySubUrl(@Path(value = 'sub_url', encoded = true) String subUrl)
```

the url is dynamic get from other, but the base url is the same. So I write this code

but I found that, variable `String subUrl` always url encode , even though I don't want and given `encoded = true`

**Comment by JakeWharton** [comment]
If you violate the rules of what a path is allowed to contain, those characters will be encoded, yes. If you have a dynamic URL, you should likely be using `@Url` instead of `@Path` which will work like an `<a href="">` would.

https://square.github.io/retrofit/2.x/retrofit/retrofit2/http/Url.html
