### ISSUE TITLE
Response body returning weird values 

### ISSUE THREAD

**Issue by Innovolved** [square/retrofit#3271]
I'm calling an api & getting weird values returned with key values being totally mixed up. 
On postman I'm getting the correct values returned but with retrofit it's not correct. 

Postman :
"companyLogo": "CompanyLogo/EZYCOMP_8923_2016_08_17.jpg",

Retrofit :
companyLog
2019-12-28 21:11:03.443 22368-22405/net.myapp.mvvm D/OkHttp: o

I tried adding a custom converter but it does not work 

  return Retrofit.Builder()
                .client(okkHttpclient)
                .baseUrl(apiConstants.URL)               
                .addConverterFactory(HtmlGsonConverter())
                .addConverterFactory(GsonConverterFactory.create(gson))
                .build()

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

**Comment by JakeWharton** [comment]
It's not at all clear what's happening here or even what you're doing. Postman does not process the response body and Retrofit does so while they receive the same data they might not print the same value. As stated in the issue template, without a failing test case or executable sample it's impossible to know what's happening here or what's to blame.
