### ISSUE TITLE
com.android.builder.dexing.DexArchiveBuilderException protobuf-java-3.10.0.jar

### ISSUE THREAD

**Issue by karthi2007** [square/retrofit#3273]
What kind of issue is this?

 - [x] Bug report. Build exception in android

While using protobuf-converter, android build execution throws 

`com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process com.google.protobuf/protobuf-java/3.10.0/410b61dd0088aab4caa05739558d43df248958c9/protobuf-java-3.10.0.jar`

and fails to build.

This is more specific to android and occurs as reported here [issue link](https://github.com/protocolbuffers/protobuf/issues/6718)

**Comment by JakeWharton** [comment]
Retrofit has no control over this. The problem is with the protobuf library, as noted in the issue that you link.
