### ISSUE TITLE
Parameter type must not include a type variable or wildcard: java.util.Map<java.lang.String, ?>

### ISSUE THREAD

**Issue by jikun2008** [square/retrofit#3275]
@POST("/driver/login")
    suspend fun login(@Body param:Map<String,Any>): Result<String>

ex:
 `   {
                var param= mapOf(
                    "password" to "123123",
                "phone" to "123456789")
                service.login(param)
            }`

 use Map<String,Any>   when use it case Throwable
 throwabel is  < java.lang.IllegalArgumentException: Parameter type must not include a type variable or wildcard: java.util.Map<java.lang.String, ?> (parameter #1) >

**Comment by JakeWharton** [comment]
For now you should be able to add @JvmSuppressWildcard to the parameter to
work around the issue. I'll see about relaxing the restrictions.

**Comment by acefalobi** [comment]
*`@JvmSuppressWildcards`

**Comment by hackaprende** [comment]
The error is still present on version `com.squareup.retrofit2:retrofit:2.11.0`

The solution is still the same, adding
`@JvmSuppressWildcards`

Just below the 
@GET or @POST or any http method, example:

 ```
@POST(MY_URL)
@JvmSuppressWildcards
 suspend fun makeRequest(@Body myList: List<MyModel>): MyResponse
```
