### ISSUE TITLE
Inconsistent behaviour between 204 and 200 with null body

### ISSUE THREAD

**Issue by MiSikora** [square/retrofit#3278]
When I declare an interface with i.e. `suspend fun foo(): Unit` function the results for `204` and `200` with a `null` body do not behave in the same way. The first one fails with an NPE while the latter succeeds.

```kotlin
class NullBodyTest {
  @get:Rule val server = MockWebServer()
  private val service: Service = Retrofit.Builder()
    .client(OkHttpClient())
    .baseUrl(server.url("/"))
    .addConverterFactory(AlwaysNullConverterFactory)
    .build()
    .create()

  @Test(expected = Test.None::class)
  fun `Unit for 200 with null body`() = runBlocking {
    server.enqueue(MockResponse().setResponseCode(200))
    service.call()
  }

  @Test(expected = Test.None::class)
  fun `Unit for 204 with null body`() = runBlocking {
    server.enqueue(MockResponse().setResponseCode(204))
    service.call()
  }

  private interface Service {
    @GET("/") suspend fun call(): Unit
  }

  object AlwaysNullConverterFactory : Factory() {
    override fun responseBodyConverter(
      type: Type,
      annotations: Array<Annotation>,
      retrofit: Retrofit
    ): Converter<ResponseBody, *>? {
      return Converter<ResponseBody, Any?> { null }
    }
  }
}
```

The body is never delegated to the converters so the "short circuiting" converters like `VoidResponseBodyConverter` and `UnitResponseBodyConverter` have no chance to close the response. I think it should either fail or pass both tests. I would prefer if it passed both cases because if I understand it correctly `Unit` represents more or less "I don't care as long as it does not fail".

https://github.com/square/retrofit/blob/7110c196825031690235c4f331a05fc4a93f6a4f/retrofit/src/main/java/retrofit2/OkHttpCall.java#L218-L221

https://github.com/square/retrofit/blob/7110c196825031690235c4f331a05fc4a93f6a4f/retrofit/src/main/java/retrofit2/BuiltInConverters.java#L70-L77

**Comment by JakeWharton** [comment]
Thanks for the detailed and comprehensive report! This unfortunate interaction is tracked by #2867. Now that the library targets Java 8, we might be able to solve it with a default method on `Converter`, I just haven't had time to look into it.

**Comment by MiSikora** [comment]
Great! Right now we delegate to our own converter as we use sealed classes for responses butI'm glad to know that it can be fixed in the library.
