### ISSUE TITLE
Could not find class 'java.lang.invoke.MethodHandles$Lookup', referenced from method retrofit2.Platform.invokeDefaultMethod

### ISSUE THREAD

**Issue by saleh-gholamian** [square/retrofit#3281]
When I added MultiDex to the Android project, In lower versions of Android like the 4.2 I get the following error
```
E/dalvikvm: Could not find class 'java.lang.invoke.MethodHandles$Lookup', referenced from method retrofit2.Platform.invokeDefaultMethod
```
Here's how I added Multiplex

My gradle module:
``` 
defaultConfig {
    multiDexEnabled = true
    // other code
}

dependencies {
    implementation 'com.android.support:multidex:1.0.3'

    implementation 'com.squareup.okhttp3:okhttp:1.12.7'

    implementation 'com.squareup.retrofit2:retrofit:2.7.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.7.0'
    // other code
}

```

My application class:
```
public class BaseApplication extends MultiDexApplication {
 // other code
}
```

My Manifest:
```
<application
    android:name=".BaseApplication">
    <!-- other code -->
</application>
```

My retrofit clinte:
```
public class ApiClient {

    private static final String BASE_URL = BaseApplication.API_URL;
    private static Retrofit retrofit = null;

    public static Retrofit getClient() {

        if (retrofit == null) {
            retrofit = new Retrofit.Builder()
                    .baseUrl(BASE_URL)
                    .client(getOkHttpClient())
                    .addConverterFactory(GsonConverterFactory.create())
                    .build();
        }
        return retrofit;
    }

    public static OkHttpClient getOkHttpClient() {

        return new OkHttpClient.Builder()
                .readTimeout(20, TimeUnit.SECONDS)
                .connectTimeout(20, TimeUnit.SECONDS)
                .addInterceptor(new Interceptor() {
                                    @Override
                                    public Response intercept(@NonNull Interceptor.Chain chain) throws IOException {
                                        Request original = chain.request();
                                        Request request = original.newBuilder()
                                                .method(original.method(), original.body())
                                                .build();

                                        return chain.proceed(request);
                                    }
                                }
                ).build();
    }
}
```

**Some of the solutions I found in search were:**

 - Use retrofit version 2.2.0 or below

 - Disable Multiplex and resize the project to the point that it does not need to be multiplexed

But I don't want to use these methods because I always want to use the latest version of retrofit, also cannot reduce the project size

**Comment by kerimovscreations** [comment]
It's a bug I think after v2.7.0. Even v2.7.1 is not succeeded in my small project

**Comment by kerimovscreations** [comment]
I suggest you downgrade the version to v.2.6.3. In addition, if your project's minSdk version is 21 and higher, you don't need to setup multidex support library (https://developer.android.com/studio/build/multidex#mdex-gradle)

**Comment by JakeWharton** [comment]
2.7.0 and newer require Java 8 and a relatively new version of AGP such as Android Gradle plugin 3.4.0 or newer. Can you please provide a sample project that exhibits this behavior, or at least provide more information about your build?

**Comment by kerimovscreations** [comment]
It was solved with Java 8 configuration now. Thanks for your tips. In case of anyone wants to enable Java 8 in the project, here is the snippet from build.gradle (app) :
`{android:
...
   compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}`

**Comment by cogman** [comment]
FYI, this issue is a problem with Java 14.  The private constructor "Lookup(Class<?> lookupClass, int allowedModes)" method was removed.  There is now a constructor of "private Lookup(Class<?> lookupClass, Class<?> prevLookupClass, int allowedModes)"

**Comment by cogman** [comment]
A work around for if the platform is on Java 9+ is this
http://mail.openjdk.java.net/pipermail/jigsaw-dev/2017-January/010741.html

There may need to be some reflection skull skulduggery to sniff for the Java 9 method.  I'll see if I can't craft something up.
