### ISSUE TITLE
How to handle/Parse following json on Retrofit2?

### ISSUE THREAD

**Issue by attaullahpro** [square/retrofit#3282]
How to handle/parse this json on Retrofit2?
```
[
   [
      "106639",
      "jonni",
      "assistant director",
      "1"
   ],
   [
      "106639",
      "maikel",
      "operator and publisher",
      "1"
   ]
]
```
[**json link** ](http://udb.gov.pk/dev/result_json.php?search1=1&search=تانِیث&posi=offline&pn=1)
**code**
```
public interface ApiService {
//    dev/result_json.php?search1=1&search=تانِیث&posi=offline&pn=1
    @GET("/dev/result_json.php")
    Call<String> getWordList(
            @Query("search1") String search1,
            @Query("search") String search,
            @Query("posi") String posi,
            @Query("pn") String pn);
}
```
**and this**
```
public class RetroClient { 
    private static final String BASE_URL = "http://udb.gov.pk/";
    private static Retrofit retrofit = null;

    public static Retrofit getClient() {
        if (retrofit == null) {
            Gson gson = new GsonBuilder()
                    .excludeFieldsWithoutExposeAnnotation()
                    .create();
            retrofit = new Retrofit.Builder()
                    .baseUrl(BASE_URL)
                    .addConverterFactory(GsonConverterFactory.create(gson))
                    .build();
        }
        return retrofit;
    }

    public static ApiService getApiService() {
        return getClient().create(ApiService.class);
    }
}
```
**and call**
```
ApiService apiService = RetroClient.getApiService();
        Call<String> call = apiService.getWordList("0", "تانِیث", "offline", "1");
        call.enqueue(new Callback<String>() {
            @Override
            public void onResponse(Call<String> call, Response<String> response) {
                if (response.body() != null) {
                    Log.e("TAG", "response 33: " + new Gson().toJson(response.body()));
                } 
            }

            @Override
            public void onFailure(Call<String> call, Throwable t) {
                Log.e("TAG", "response : x"   );
            }
        });
```
I ask already in stackoverflow but no answer
https://stackoverflow.com/questions/59704608/

**Comment by JakeWharton** [comment]
StackOverflow is the right place for this question because it isn't specific to Retrofit. Retrofit just passes the data to Gson and then hands you back whatever Gson returns. Decoding JSON and dealing with mapping that to an object is entirely an interaction with Gson.

**Comment by attaullahpro** [comment]
> 
> 
> StackOverflow is the right place for this question because it isn't specific to Retrofit. Retrofit just passes the data to Gson and then hands you back whatever Gson returns. Decoding JSON and dealing with mapping that to an object is entirely an interaction with Gson.

but i does not resturn any thing any goes to onfail method thats why?

**Comment by joimxjtuse** [comment]
> How to handle/parse this json on Retrofit2?
> 
> ```
> [
>    [
>       "106639",
>       "jonni",
>       "assistant director",
>       "1"
>    ],
>    [
>       "106639",
>       "maikel",
>       "operator and publisher",
>       "1"
>    ]
> ]
> ```
> 
> I ask already in stackoverflow but no answer
> https://stackoverflow.com/questions/59704608/

retrofit only parse this request/response by Converter.Factory, like GsonConverterFactory,  without focusing on the specific parsing, i think you should debug GsonResponseBodyConverter.convert() to find the root cause.
