### ISSUE TITLE
Limit retry count for authentication challenge

### ISSUE THREAD

**Issue by i-schuetz** [square/retrofit#3283]
I'd like to be able to limit the retry count in `Authenticator` to 3. At the moment it appears to be 20. I don't see anything to do this and didn't get an answer in [StackOverflow](https://stackoverflow.com/questions/59680324/limit-retry-count-of-authenticator), so assuming it's not possible at the moment.

**Comment by JakeWharton** [comment]
Authenticator is a feature of OkHttp, not Retrofit. We have no control over the number of times it is invoked.

**Comment by biwin** [comment]
See [this answer](https://stackoverflow.com/questions/59680324/limit-retry-count-of-authenticator) on StackOverflow
