### ISSUE TITLE
Invoke-customs are only supported starting with Android O (--min-api 26)

### ISSUE THREAD

**Issue by zishanj** [square/retrofit#3288]
Compiling with 2.7.1 gives me this error in Android Studio 3.5.3:
`Invoke-customs are only supported starting with Android O (--min-api 26)`
I have also enabled Java 1.8 but it still gives this error. I have changed the version to 2.6.4 and it works.

**Comment by JakeWharton** [comment]
Are you _sure_ you've correctly enabled Java 8 support? Are you using a relatively modern version of the Android Gradle plugin? This error indicates a misconfiguration or really old version of AGP.

**Comment by zishanj** [comment]
Actually it was due to my `retrolambda` plugin which I was using in older version of Android Studio. I have removed this plugin now and it works like a charm.

**Comment by JakeWharton** [comment]
Great. Thanks for following up.

**Comment by Kshitij09** [comment]
> Are you _sure_ you've correctly enabled Java 8 support? Are you using a relatively modern version of the Android Gradle plugin? This error indicates a misconfiguration or really old version of AGP.

As mentioned by @JakeWharton, the solution is to enable java-8 support for your project. Putting the required code for future reference:
```gradle
android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```
borrowed from [stackoverflow](https://stackoverflow.com/a/50198499)
