### ISSUE TITLE
Update dependencies com.squareup.okhttp3 to 3.12.8

### ISSUE THREAD

**Issue by biancaarno8** [square/retrofit#3294]
Hi, i am using retrofit version 2.6.4 and i have a bug with one of your dependencies: the library 'com.squareup.okhttp3' with version 3.12.0  is old and has bugs that all of my users are experiencing. (i.e. SocketTimeoutException : https://github.com/square/okhttp/issues/3146 )
Are you going to update the library to version 3.12.8 by making a separate branch for support with older devices? I need to support old devices.

**Comment by PromanSEW** [comment]
Add dependency manually

**Comment by biancaarno8** [comment]
@PromanSEW  thank you for your reply. I tried to add dependency manually, and when i run my project to emulator, i found this error:
- I/dalvikvm: Could not find method java.time.Duration.toMillis, referenced from method okhttp3.OkHttpClient$Builder.callTimeout
- I/dalvikvm: Could not find method java.time.Duration.toMillis, referenced from method okhttp3.OkHttpClient$Builder.connectTimeout
- I/dalvikvm: Could not find method java.time.Duration.toMillis, referenced from method okhttp3.OkHttpClient$Builder.pingInterval
- I/dalvikvm: Could not find method java.time.Duration.toMillis, referenced from method okhttp3.OkHttpClient$Builder.readTimeout
- I/dalvikvm: Could not find method java.time.Duration.toMillis, referenced from method okhttp3.OkHttpClient$Builder.writeTimeout
It's normal?

**Comment by PromanSEW** [comment]
@biancaarno8 you try to use the latest OkHttp which do not support API < 24
The latest versions for pre-24 are Retrofit 2.6.4 and OkHttp 3.12.8
I use these versions and all works fine

**Comment by biancaarno8** [comment]
Yes, i use these versions, and are only warnings.
Thank you for your time.
Have a nace day!
