### ISSUE TITLE
 retrofit does not recognize my access provider.

### ISSUE THREAD

**Issue by nimondo** [square/retrofit#3296]
What kind of issue is this?

 - [ ]  I get this error HTTP FAILED: java.net.UnknownHostException: Unable to resolve host "moov": No address associated with hostname. Moov is my 3G access provider.
When I use Wifi network there is no problem.

**Comment by JakeWharton** [comment]
This exception comes from deep within the networking stack. You are trying to connect to a URL whose host is just `moov` (e.g., `http://moov/api/path`). This is likely not what you want and instead you want a proper domain. This might be coming from your specified base URL or a `@Url` annotation parameter value.
