### ISSUE TITLE
First-party RxJava 3 adapter

### ISSUE THREAD

**Issue by JakeWharton** [square/retrofit#3297]
![](https://media.giphy.com/media/GV3aYiEP8qbao/giphy.gif)

**Comment by pavankumarvvijapur** [comment]
This will be a nice to have. Any ETA ? @JakeWharton

**Comment by JakeWharton** [comment]
This library is built entirely on volunteer time so there are no ETAs.

**Comment by provJoshMieczkowski** [comment]
@JakeWharton ^ pr is ready for a review when someone has a second <3

**Comment by provJoshMieczkowski** [comment]
https://github.com/square/retrofit/pull/3315
Any updates on when this guy is going to be merged in?

**Comment by zhupengxiang** [comment]
have any plan to update RxBinding for RxJava3?

**Comment by AdamSHurwitz** [comment]
See my comment in [#3315](https://github.com/square/retrofit/pull/3315#issuecomment-626222628) for RxJava3 Retrofit adapter.

`implementation "com.github.akarnokd:rxjava3-retrofit-adapter:3.0.0"`
