### ISSUE TITLE
Needed logging the request and response body of protobuf

### ISSUE THREAD

**Issue by Morteza-Rastgoo** [square/retrofit#3312]
What kind of issue is this?

 - [√ ] Feature Request.

I need to log my response and requests of protobuf. I couldn't find any solution. Any Idea how to do this?

**Comment by ctlove0523** [comment]
OkHTTP's [Interceptors](https://square.github.io/okhttp/interceptors/) helpful?

**Comment by JakeWharton** [comment]
Object-form logging covered by #378. Serialized form covered by OkHttp interceptors and, optionally, OkHttp's first-party logging-interceptor artifact.
