### ISSUE TITLE
ETag cache not working

### ISSUE THREAD

**Issue by victorlsn** [square/retrofit#3317]
I'm trying to get cache working - including the use of ETags, but so far I've had no success.

This is my OkHttpClient Builder:
`val cache = Cache(
	directory = app.cacheDir,
	maxSize = 10L * 1024L * 1024L
)
return OkHttpClient.Builder()
	.cache(cache)
	.addNetworkInterceptor(rxOAuthManager.provideAuthInterceptor())
	.addInterceptor(httpLoggingInterceptor)
	.addInterceptor(
		ConnectivityInterceptor(
			app,
			connectivityChecker
		)
	)`

And here's a sample response from my server:
2020-02-24 17:17:23.937 15661-16048/de.tafmobile.android.payu.local D/OkHttp: <-- 200 http://192.168.120.67:8000/restapi/product/v1/catalog (6ms)
2020-02-24 17:17:23.937 15661-16048/de.tafmobile.android.payu.local D/OkHttp: Date: Mon, 24 Feb 2020 16:05:01 GMT
2020-02-24 17:17:23.937 15661-16048/de.tafmobile.android.payu.local D/OkHttp: X-Content-Type-Options: nosniff
2020-02-24 17:17:23.937 15661-16048/de.tafmobile.android.payu.local D/OkHttp: X-XSS-Protection: 1; mode=block
2020-02-24 17:17:23.937 15661-16048/de.tafmobile.android.payu.local D/OkHttp: X-Frame-Options: DENY
2020-02-24 17:17:23.937 15661-16048/de.tafmobile.android.payu.local D/OkHttp: ETag: "0eff0ea3a1471aaa7e8fd2b895db52eb7"
2020-02-24 17:17:23.937 15661-16048/de.tafmobile.android.payu.local D/OkHttp: Cache-Control: max-age=24898, must-revalidate, private

I can get ETag working if I manually save the ETag and send it through a @Header parameter in the request, but I reckon Retrofit usually manages ETag and some other caching automatically, right?

Thanks in advance!

**Comment by JakeWharton** [comment]
Retrofit knows nothing about OkHttp's cache and does not manage it in any way. We only use OkHttp to model requests and responses. The mechanisms of its internals like caching are completely opaque to Retrofit and it isn't in a position to control them.

If you think there's a bug in OkHttp's behavior you should isolate it into a test case with MockWebServer where you can script both the client and server behavior to ensure everyone is seeing the same behavior and is clear on what the expectations are and then create an issue on OkHttp. If this is just a general usage question about OkHttp's behavior with regard to ETags then I would recommend posting on StackOverflow with the 'okhttp' tag.

**Comment by AndroidDeveloperLB** [comment]
@JakeWharton How come there is this article about it:
https://medium.com/android-news/reducing-your-networking-footprint-with-okhttp-etags-and-if-modified-since-b598b8dd81a1
?

I think it says it could cache the responses headers, no? And then if it hasn't changed, you can check if HttpURLConnection.HTTP_NOT_MODIFIED is received.

Sadly though, for some reason it doesn't work for me:

```
interface FileDownloadService {
    @GET
    @Streaming
    fun downloadFile(@Url fileUrl: String): Call<ResponseBody>
}
```

@WorkerThread
fun test(context: App, url: String) {
    Log.d("AppLog", "test")
    val cacheSizeBytes = 1024L * 1024L * 2L
    val builder = OkHttpClient().newBuilder()
    builder.cache(Cache(context.cacheDir, cacheSizeBytes))
    val client: OkHttpClient = builder.build()
    val retrofitBuilder = Retrofit.Builder()
    retrofitBuilder.baseUrl("https://s3.amazonaws.com").client(client)
    val retrofit = retrofitBuilder.build()
    val service = retrofit.create(FileDownloadService::class.java)
    val response = service.downloadFile(url).execute()
    Log.d("AppLog", "isSuccessful?${response.isSuccessful} ${response.code()} ${response.raw().code} ${response.headers()["Last-Modified"]}")
}
```

This has multiple issues:
1. On emulator, it keeps getting response code 200 (instead of `HttpURLConnection.HTTP_NOT_MODIFIED`) and takes a long time (4 seconds)
2. On device, I keep getting `UnknownHostException: Unable to resolve host "s3.amazonaws.com": No address associated with hostname` . 

Is there any sample out there to show how it's done properly?
