### ISSUE TITLE
Is there a way to add methods ignored by the Retrofit proxy?

### ISSUE THREAD

**Issue by christophehenry** [square/retrofit#3319]
What kind of issue is this?

 - [x] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I'd like to define getters and setters in my Retrofit interface so that a class that would inherit from it can also expose some internal data. For instance (in Kotlin):

```kotlin
interface IAPI {
    var account: Account

    // Retrofit stuff here
}

class API(override var account: Account): IAPI by getAPI(account) {}
```

It does not seem to be possible. When I do this, I get 

```
java.lang.IllegalArgumentException: HTTP method annotation is required (e.g., @GET, @POST, etc.).
```

Is there a annotation to tell Retrofit to ignore the call and pass it to the implementing class?

**Comment by JakeWharton** [comment]
No, there is no way to do this. It would get extremely complicated and likely would have no type safety whatsoever if attempted.

If you need to do this, your best bet is to use multiple interfaces:
```kotlin
interface AccountApi : AccountHttpApi {
  var account: Account
}
interface AccountHttpApi {
  // Retrofit stuff here
}
class API(override var account: Account): AccountApi, AccountHttpApi by getApi(account)
```

Otherwise I would suggest separating the concerns and keeping your local state and HTTP API as two different things.

**Comment by christophehenry** [comment]
Ok, thank you.
