### ISSUE TITLE
Question: Call throws "empty string" in error everytime.

### ISSUE THREAD

**Issue by prathamk22** [square/retrofit#3326]
I am sending an api call to the server which is working great in the POSTMAN, but when I send the same API call through retrofit, it throws "empty string". What does that mean?

**Comment by JakeWharton** [comment]
There is not enough information here to discern a cause. If you believe there's a bug in Retrofit please create a failing test case using the sample in the issue template. You can also supply a sample which runs against a real endpoint and demonstrates the problem. Without that, we have no idea what you're doing, what you expect, and what's happening.

If you just have a question on how to configure Retrofit to deliver a particular request, posting on StackOverflow more information in the 'retrofit' tag is recommended.
