### ISSUE TITLE
Question BuiltInConverters.checkForKotlinUnit NoClassDefFoundError don't catch

### ISSUE THREAD

**Issue by qq8803128** [square/retrofit#3327]
i'm a android game sdk developer, we always decompile an parent apk file to an android studio project,but this time,we meet an problem by use dex2jar.jar to convert dex file to jar file
***the base retrofit2 BuiltInConverters.checkForKotlinUnit code***
```java
 @Nullable
    public Converter<ResponseBody, ?> responseBodyConverter(Type type, Annotation[] annotations, Retrofit retrofit) {
        if (type == ResponseBody.class) {
            return (Converter)(Utils.isAnnotationPresent(annotations, Streaming.class) ? BuiltInConverters.StreamingResponseBodyConverter.INSTANCE : BuiltInConverters.BufferingResponseBodyConverter.INSTANCE);
        } else if (type == Void.class) {
            return BuiltInConverters.VoidResponseBodyConverter.INSTANCE;
        } else {
            if (this.checkForKotlinUnit) {
                try {
                    if (type == Unit.class) {
                        return BuiltInConverters.UnitResponseBodyConverter.INSTANCE;
                    }
                } catch (NoClassDefFoundError var5) {
                    this.checkForKotlinUnit = false;
                }
            }

            return null;
        }
    }
```
***the dex2jar convert  retrofit2 BuiltInConverters.checkForKotlinUnit code***
```java
@Nullable
    public Converter<ResponseBody, ?> responseBodyConverter(Type var1, Annotation[] var2, Retrofit var3) {
        if (var1 == ResponseBody.class) {
            Object var6;
            if (Utils.isAnnotationPresent(var2, Streaming.class)) {
                var6 = BuiltInConverters.StreamingResponseBodyConverter.INSTANCE;
            } else {
                var6 = BuiltInConverters.BufferingResponseBodyConverter.INSTANCE;
            }

            return (Converter)var6;
        } else if (var1 == Void.class) {
            return BuiltInConverters.VoidResponseBodyConverter.INSTANCE;
        } else {
            if (this.checkForKotlinUnit && var1 == Unit.class) {
                try {
                    BuiltInConverters.UnitResponseBodyConverter var5 = BuiltInConverters.UnitResponseBodyConverter.INSTANCE;
                    return var5;
                } catch (NoClassDefFoundError var4) {
                    this.checkForKotlinUnit = false;
                }
            }

            return null;
        }
```
the NoClassDefFoundError can't catch ，how to fix it

**Comment by JakeWharton** [comment]
This seems like a dex2jar bug. If you're actually recompiling the decompiled code I would recommend using Smali which can ensure that the semantics are correctly preserved by using a language that more accurately models Dalvik bytecode. I don't see any action to take here on Retrofit's side. Our code correctly puts the conditional inside the try.

**Comment by qq8803128** [comment]
> This seems like a dex2jar bug. If you're actually recompiling the decompiled code I would recommend using Smali which can ensure that the semantics are correctly preserved by using a language that more accurately models Dalvik bytecode. I don't see any action to take here on Retrofit's side. Our code correctly puts the conditional inside the try.

thanks ,but the android stdio project can't include the smali file into project

**Comment by qq8803128** [comment]
> This seems like a dex2jar bug. If you're actually recompiling the decompiled code I would recommend using Smali which can ensure that the semantics are correctly preserved by using a language that more accurately models Dalvik bytecode. I don't see any action to take here on Retrofit's side. Our code correctly puts the conditional inside the try.

our team use dex2jar for convert classes.dex file in parent apk file to jar file,with this way,our team can compile('xxx.jar') in android studio project,but if only convert to smali file,we don't know how to use them in android studio project
