### ISSUE TITLE
Configurable base url

### ISSUE THREAD

**Issue by coroutineDispatcher** [square/retrofit#3333]
Hi, 

I was hoping to get it as a feature because the way it is it doesn't fit pretty well in our code.
Since it's mandatory to define a base url (and I do agree with the arguments on the other cases) we have cases when the url is configurable on Runtime. Of course that we are using `@Url` annotation but yet, the builder of the `Retrofit` instance needs the base url defined. Is there sth that could be considered to come as a feature later? Like making the base url optional?

**Comment by JakeWharton** [comment]
If the base URL changes why not just recreate the `Retrofit` instance and any of the service instances?

**Comment by JakeWharton** [comment]
Or you can use an OkHttp interceptor to rewrite the base URL to whatever the latest value is.

**Comment by JakeWharton** [comment]
Going to preemptively close because we have no plans to include this. Let me know if those solutions work for you.

**Comment by coroutineDispatcher** [comment]
Yes, fine for me. Thnx
