### ISSUE TITLE
Header Authorization not working with Yelp Api

### ISSUE THREAD

**Issue by SriwanKm** [square/retrofit#3335]
What kind of issue is this?

 - [x ] Bug report

I have tried adding a Header for Yelp Api: 
Authorization: Bearer {apiKey} 

It works in postman and from curl and from Intellij http file but not in retrofit. I tried every way of adding header including annotations, interceptors and following a bunch of tutorials but none of them seem to work. I think something is wrong with this library (or could be improved) since it shouldn't be this hard to do something that is quite easy in postman, curl, or intellij's built-in http files.

**Comment by JakeWharton** [comment]
Please provide a failing test case or executable sample. You have provided no information as to what your Retrofit service declaration looks like, what the server expects, or what is actually being sent.

**Comment by mutunenthaby** [comment]
African customary Healer botanist arranged in South Africa and significant Marriage counselor and diviner Call/Whatsapp +27670093205 or Email mamawata85@gmail.com

• Bringing back lost darlings in a 72 hours 

• Divorce or Court issues 

• Financial issues and DEBTS 

• Preventing your accessory from undermining you 

• Making your accessory love just you 

• Get a separation settlement quickly from your ex-accessory 

• Removal of misfortune 

• Buy a house or vehicle of your dream 

• I help understudies with completing their tests/interviews 

• I help those searching for work 

• Speed up money ensure spell delayed, payments, pension and incident stores 

• Unfinished occupations by various masters if not satisfied come to me. 

• Win business tenders and understandings 

• Do you need to recover your lost property 

• Promotion busy working and better pay. 

• Do you should be protected from awful spirits terrible dreams? 

• Are you a priest, administrator, botanist who needs to get more powers? 

• Why you can't keep money or sweethearts? 

• Why you have a lot of adversaries? 

• Why you are fired routinely on jobs?
