### ISSUE TITLE
response errorBody deserialization results in java.io.EOFException: End of input

### ISSUE THREAD

**Issue by r0mi** [square/retrofit#3337]
Retrofit 2.7.2
okhttp:4.4.0

The following sample is not working:
retrofit/samples/src/main/java/com/example/retrofit/DeserializeErrorBody.java

Response errorBody conversion results in java.io.EOFException: End of input

**Comment by JakeWharton** [comment]
It's working fine for me.

![Screen Shot 2020-03-18 at 12 28 38 PM](https://user-images.githubusercontent.com/66577/76983565-03aaa980-6914-11ea-9d72-643a339137cd.png)

**Comment by r0mi** [comment]
Totally my mistake.
I added a single log line before the converter code to log out the errorBody as a string. Seems that this consumed the errorBody and caused the issue. Removing the log line made it work.
Sorry for wasting your time 😫
