### ISSUE TITLE
Illegal reflective access

### ISSUE THREAD

**Issue by MoshDev** [square/retrofit#3341]
I've a sample project using Spring Boot and Retrofit 

I'm using:
Spring boot  2.2.5.RELEASE
Retrofit 2.8.0
OkHttp 4.4.1
Kotlin 1.3.61
Jdk 11

Retrofit fails to make any request and i receive this warning in the logs:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by retrofit2.Platform (file:/Users/mersan/.gradle/caches/modules-2/files-2.1/com.squareup.retrofit2/retrofit/2.8.0/53fa357bd7538d2c4872bddf33654f113cf6652b/retrofit-2.8.0.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by JakeWharton** [comment]
The reflection works around a bug in the JDK which was fixed in 14 but it's only used for default methods. As it's only a warning, it's not preventing your call from working.

Please provide a failing test case or reproducing sample.

**Comment by MoshDev** [comment]
After checking the logs, i found the request was failing for another reason along with this warning printed.

**Comment by marlonlom** [comment]
Greetings,

This is a related issue.

I'm using:
- Android Studio 4.2
- Retrofit 2.9.0
- Kotlin 1.5.10
- Jdk 1.8.0_292

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by retrofit2.Platform (file:/home/marlonlom/.gradle/caches/modules-2/files-2.1/com.squareup.retrofit2/retrofit/2.9.0/d8fdfbd5da952141a665a403348b74538efc05ff/retrofit-2.9.0.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by MihaelBercic** [comment]
Has this been resolved yet?

> Greetings,
> 
> This is a related issue.
> 
> I'm using:
> 
> * Android Studio 4.2
> * Retrofit 2.9.0
> * Kotlin 1.5.10
> * Jdk 1.8.0_292
> 
> ```
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by retrofit2.Platform (file:/home/marlonlom/.gradle/caches/modules-2/files-2.1/com.squareup.retrofit2/retrofit/2.9.0/d8fdfbd5da952141a665a403348b74538efc05ff/retrofit-2.9.0.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
> WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> ```
