### ISSUE TITLE
response?.raw()?.close() throwing    java.lang.IllegalStateException: Cannot read raw response body of a converted body.

### ISSUE THREAD

**Issue by Charuwaka** [square/retrofit#3350]
When i am trying to close body

 @GET("api/dummy/users")
    suspend fun getusers(): Response<users>

val response=api.instance().getusers()
try
{

}finally
{
response.raw().close() // here throwing exception as below
}

 response?.body().toString() -> will this close body ? 

java.lang.IllegalStateException: Cannot read raw response body of a converted body.
        at retrofit2.OkHttpCall$NoContentResponseBody.source(OkHttpCall.java:274)
        at okhttp3.ResponseBody.close(ResponseBody.kt:192)
        at okhttp3.Response.close(Response.kt:302)

**Comment by JakeWharton** [comment]
Retrofit closes the body on your behalf in all cases except when using the `@Streaming` annotation with the `ResponseBody` return type. You can safely remove your `finally` block.

Calling `ResponseBody.string()` will close the body automatically, but `ResponseBody.toString()` will not.
