### ISSUE TITLE
Is there a size limit for uploading images using @part List< multipartbody. Part> Part?

### ISSUE THREAD

**Issue by AndroidLMY** [square/retrofit#3352]
Is there a size limit for uploading images using @part List< multipartbody. Part> Part?, I can't call the server's interface when it's over 4MB in use

**Comment by JakeWharton** [comment]
Retrofit itself imposes no limits but your server absolutely might. In this case you'll usually see the upload closed prematurely (producing some kind of `IOException`) or you'll get a 4xx HTTP error in response.

**Comment by AndroidLMY** [comment]
Thank you



 
---Original---
