### ISSUE TITLE
Minimum required information needs to be updated

### ISSUE THREAD

**Issue by FunCoder0676** [square/retrofit#3357]
Minimum required information needs to be updated on the https://square.github.io/retrofit/

[https://github.com/square/retrofit](https://github.com/square/retrofit)   show **Retrofit requires at minimum Java 8+ or Android API 21+.**

but [https://square.github.io/retrofit/](https://square.github.io/retrofit/)  show previous content **Retrofit requires at minimum Java 7 or Android 2.3.**

**Comment by JakeWharton** [comment]
Thanks.

fdbaf2c37c807e5064960231817300c9e7646eb0

**Comment by JakeWharton** [comment]
And fef7115dbec1163e32d1cbdb2417d3ea52478b27
