### ISSUE TITLE
MoshiConverterFactory should have a nullsafe option

### ISSUE THREAD

**Issue by vmtrue** [square/retrofit#3359]

**Comment by JakeWharton** [comment]
What does this mean?

**Comment by vmtrue** [comment]
@JakeWharton `JsonAdapter` has the ability to deserialize "null" by calling `nullSafe()`.

Example

```
String dateJson = "\"2018-11-26T11:04:19.342668Z\"";
String nullDateJson = "null";

// Hypothetical IsoDateDapter, doesn't support null by default
JsonAdapter<Date> adapter = new IsoDateDapter();

Date date = adapter.fromJson(dateJson);
System.out.println(date); // Mon Nov 26 12:04:19 CET 2018

Date nullDate = adapter.fromJson(nullDateJson);
// Exception, com.squareup.moshi.JsonDataException: Expected a string but was NULL at path $

Date nullDate = adapter.nullSafe().fromJson(nullDateJson);
System.out.println(nullDate); // null
```

But there is no way to make adapters inside `MoshiConverterFactory` nullsafe. It would be great to have 
such ability like It implemented with `lenient`, `serializeNulls` etc.

**Comment by JakeWharton** [comment]
You can call `nullSafe()` when you register the adapter with your `Moshi.Builder` though, right?

Can you express this in a failing test case so that it's clear what behavior you're seeing?

**Comment by vmtrue** [comment]
Yes, you are right. I decorated KotlinJsonAdapterFactory and called `nullSafe()` for each adapter.

I've been confused by `MoshiConverterFactory` with `lenient` and `serializeNulls` and thought that `nullSafe` should have be in `MoshiConverterFactory` too.

Thanks for help
