### ISSUE TITLE
Call factory does not create calls on a background thread

### ISSUE THREAD

**Issue by MiSikora** [square/retrofit#3363]
What kind of issue is this?

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

Articles like [the one](https://www.zacsweers.dev/dagger-party-tricks-deferred-okhttp-init/) by @ZacSweers or [the post](https://www.reddit.com/r/androiddev/comments/dsibh4/dagger_party_tricks_deferred_okhttp_initialization/f6qhzxm/) from @JakeWharton on Reddit describe/confirm a recipe for lazy creation of the `OkHttpClient` on a background thread. We noticed in our apps that this does not happen. I'm not sure if something is messed up in our setup but even the minimal examples that I try to reproduce do not yield an expected result. I wrote a test that I think should pass. Is my thinking horribly wrong here?

```java
@Test public void callFactoryDoesNotCreateCallsOnMainThread() throws InterruptedException {
  final Thread mainThread = Thread.currentThread();
  final CountDownLatch latch = new CountDownLatch(1);
  final AtomicBoolean calledOnMain = new AtomicBoolean();
  okhttp3.Call.Factory callFactory = request -> {
    if (mainThread == Thread.currentThread()) calledOnMain.set(true);
    return new OkHttpClient().newCall(request);
  };
  Retrofit retrofit = new Retrofit.Builder()
      .baseUrl(server.url("/"))
      .callFactory(callFactory)
      .build();

  server.enqueue(new MockResponse());

  CallMethod service = retrofit.create(CallMethod.class);
  service.getResponseBody().enqueue(new Callback<ResponseBody>() {
    @Override public void onResponse(Call<ResponseBody> call, Response<ResponseBody> response) {
      latch.countDown();
    }

    @Override public void onFailure(Call<ResponseBody> call, Throwable t) { t.printStackTrace(); }
  });

  latch.await();
  assertFalse(calledOnMain.get());
}
```

**Comment by ZacSweers** [comment]
Your snippet is incomplete - what's the code for `CallMethod`?

It depends on what CallAdapter you are using. The post example there is using coroutines. The RxJava call adapter will also make the request on whatever `subscribeOn()` scheduler is used or whatever scheduler the call adapter was created with.

**Comment by MiSikora** [comment]
Hey, thanks for such a quick response. Call method is just an interface defined it this repository.

https://github.com/square/retrofit/blob/f288fef3c150db09b8deb4b72707dd430e8239f5/retrofit/src/test/java/retrofit2/RetrofitTest.java#L67-L82

But when I played around with it coroutines also do not do this. Does this require an additional `CallAdapter.Factory` to ensure that calls will be created in the background since the `suspend` support is now built-in and does not require external adapter from like this one https://github.com/JakeWharton/retrofit2-kotlin-coroutines-adapter.

**Comment by ZacSweers** [comment]
> But when I played around with it coroutines also do not do this

Unless you paste your exact snippet, can't really say. That linked code is java code, which inherently can't be suspend functions. It also returns `Call` directly, which would incur a different [call adapter](https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit2/DefaultCallAdapterFactory.java).

**Comment by MiSikora** [comment]
Ok, something is wrong with my setup. I'll close this issue, analyse further and post on SO if I get stuck.

**Comment by MiSikora** [comment]
Sorry for bothering you but just to be sure. Should this also fail due to lack of custom call adapter?

```kotlin
@get:Rule val server = MockWebServer()

interface Service {
  @GET("/") suspend fun call()
}

@Test fun callTest() = runBlocking {
  val mainThread = Thread.currentThread()
  val calledOnMain = AtomicBoolean()

  val callFactory = object : Call.Factory {
    override fun newCall(request: Request): Call {
      calledOnMain.set(mainThread === Thread.currentThread())
      return OkHttpClient().newCall(request)
    }
  }
  val service = Retrofit.Builder()
    .baseUrl(server.url("/"))
    .callFactory(callFactory)
    .build()
    .create<Service>()

  server.enqueue(MockResponse())

  service.call()

  assertFalse(calledOnMain.get())
}
```

**Comment by ZacSweers** [comment]
That should work as described in that blog post in my experience

**Comment by MiSikora** [comment]
I would thought so as well but it doesn't. I'll dig around more and reopen or ask on SO if I get stuck.

**Comment by ZacSweers** [comment]
I have an update to my experience: coroutines support does call `newCall` on the calling thread and not a background one. Yes you'd need to add an extra step to ensure the newCall() is done on a different thread
