### ISSUE TITLE
A problem when use JacksonConverterFactory

### ISSUE THREAD

**Issue by ctlove0523** [square/retrofit#3372]
problem：
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "app_id" 

can modify `JacksonConverterFactory`'s private final field `mapper` like this：
~~~
mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
~~~

**Comment by JakeWharton** [comment]
Create a mapper, configure this setting, and pass it into the factory through the static method which accepts a mapper.

**Comment by ctlove0523** [comment]
@JakeWharton yes I understand
