### ISSUE TITLE
Retrofit JacksonConverter and JacksonVersion

### ISSUE THREAD

**Issue by aeroxr1** [square/retrofit#3375]
Hi !
I'm wondering if could be problems if in the same Android project I import JacksonConverter 2.8.1 and the last 2.11.0 JacksonVersion.

**Comment by JakeWharton** [comment]
We do not track the latest versions of libraries regularly. If you need a newer version of a library like Jackson, you should specify an explicit dependency on Jackson as well as the Jackson converter. As long as their major version is the same it should work fine.
