### ISSUE TITLE
OkHttp logs the response, but callback not called

### ISSUE THREAD

**Issue by patilvishwanath** [square/retrofit#3378]
The response is getting logged, I have added HttpLoggingInterceptor.
But the same I not receiving in onResponse Method of Enqueue call.
I have debugged, it skips the enqueue block. 
Please find below code.

Retrofit Builder code :   

```
Retrofit retrofit = new Retrofit.Builder()
                .baseUrl("http://instapreps.com/api/")
               // .baseUrl("http://dummy.restapiexample.com/api/")
                .addConverterFactory(GsonConverterFactory.create())
                .client(client)
                .build();
```

EndPoint :  
```
@GET("subjects/2/time_tables")
Call<TimeTable> getTimeTable();
```

EnqueueCall : 

    private void enqueuCal(Call<TimeTable> responseBodyCall, boolean b, IRetrofitTask callback) {
        responseBodyCall.enqueue(new Callback<TimeTable>() {
            @Override
            public void onResponse(Call<TimeTable> call, Response<TimeTable> response) {
                if(response.isSuccessful()) {
                    TimeTable resource = response.body();

                    LogUtils.Verbose("resource", resource.getData().size() +""+resource.getData().get(0).getDay());

                }else{
                    LogUtils.Verbose("resource", "fail");
                }

            }

            @Override
            public void onFailure(Call<TimeTable> call, Throwable t) {
                callback.onFailed("061", "Something Went wrong");
            }
        });
    }

My Response : 

`{"success":true,"message":"OK","data":[{"day":"Monday","classes":[{"start_at":"05:41 AM","end_at":"06:41 AM","subject":"Mathematics","class_link":"https://join.skype.com/RjqbpL5gLucq\""}]},{"day":"Tuesday","classes":[{"start_at":"05:41 AM","end_at":"06:41 AM","subject":"Mathematics","class_link":"https://join.skype.com/RjqbpL5gLucq\""}]},{"day":"Wednesday","classes":[{"start_at":"05:41 AM","end_at":"06:41 AM","subject":"Mathematics","class_link":"https://join.skype.com/RjqbpL5gLucq\""}]},{"day":"Thursday","classes":[{"start_at":"05:41 AM","end_at":"06:41 AM","subject":"Mathematics","class_link":"https://join.skype.com/RjqbpL5gLucq\""}]},{"day":"Friday","classes":[{"start_at":"05:41 AM","end_at":"06:41 AM","subject":"Mathematics","class_link":"https://join.skype.com/RjqbpL5gLucq\""}]},{"day":"Satuarday","classes":[{"start_at":"05:41 AM","end_at":"06:41 AM","subject":"Mathematics","class_link":"https://join.skype.com/RjqbpL5gLucq\""}]},{"day":"Sunday","classes":[{"start_at":"05:41 AM","end_at":"06:41 AM","subject":"Mathematics","class_link":"https://join.skype.com/RjqbpL5gLucq\""}]}],"meta":{},"errors":[]}`

**Comment by ctlove0523** [comment]
I run the same code,but get response every times and call back method called every times. OkHttp version 4.4.1,HttpLoggingInterceptor version 4.6.0

**Comment by JakeWharton** [comment]
Please provide a failing test case or executable sample that demonstrates the issue. There's no way to know what's going on in your setup without it.

**Comment by patilvishwanath** [comment]
Getting this exception, after updating Retrofit and OkHttp Gradle file dependency to latest version. 

java.lang.NoClassDefFoundError: Failed resolution of: Lorg/conscrypt/ConscryptHostnameVerifier.


Finally solved this error, after adding this dependency
implementation 'org.conscrypt:conscrypt-android:2.2.1'

**Comment by JakeWharton** [comment]
You should not need that dependency, for what it's worth. That is, unless you want an unbundled conscript.

**Comment by KDisEDDY** [comment]
I have the same problem with this issue, here is the log:
