### ISSUE TITLE
Platform detection fails in Android Studio 4.1 Canary 8

### ISSUE THREAD

**Issue by yigit** [square/retrofit#3389]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I have an IntelliJ plugin that started crashing in AndroidStudio Canary 4.1.
full exception:
https://github.com/yigit/ArtifactFinder/issues/16

Seems like in 4.1, `Class.forName("android.os.Build") does not fail anymore and then eventually causes a different exception:
https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit2/Platform.java#L43

```
java.lang.UnsatisfiedLinkError: android.os.SystemProperties.native_get(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
	at android.os.SystemProperties.native_get(Native Method)
	at android.os.SystemProperties.get(SystemProperties.java:129)
	at android.os._Original_Build.getString(Build.java:1265)
	at android.os._Original_Build.<clinit>(Build.java:51)
	at android.os._Original_Build$VERSION.<clinit>(Build.java:229)
	at android.os.Build$VERSION.<clinit>(Build.java:21)
	at retrofit2.Platform.findPlatform(Platform.java:43)
```

I'm not sure why that class is available in studio but seems like detecting android platform based on the existence of that class is no more appropriate.

**Comment by yigit** [comment]
Also, seems like this error surfaced before but I was not seeing it until 4.1.
https://github.com/Microsoft/azure-tools-for-java/issues/363

**Comment by JakeWharton** [comment]
😬 

Presumably this is for layoutlib support? Sucks that it's not isolated into a classloader.

Related: #2102.

**Comment by yigit** [comment]
bug on studio:
https://issuetracker.google.com/issues/156312959

This also seems to effect okhttp :( If there is some workaround, I would appreciate but i couldn't find since it runs on class initialization.
