### ISSUE TITLE
RFC 5988 - Web Linking support

### ISSUE THREAD

**Issue by niqo01** [square/retrofit#339]
Are there any discussion to support the [RFC 5988 - Web Linking](http://tools.ietf.org/html/rfc5988) in retrofit?
I think it would require specifying an all URL.

A concrete example would be to support [Gihub API pagination](http://developer.github.com/v3/#pagination)

**Comment by hastebrot** [comment]
As far as I understand, the main requirement to implement a service API that uses pagination with Retrofit is to be able to retrieve the `Response`'s headers.

Previously this was possible by adding `Callback` as method parameter to every method that uses pagination in the service API interface. Now, with redesigned API in 2.0 (#297) which requires every method to return a `Call` which contains a `Response` this is greatly unified.

I'm looking forward to provide some examples of a Github API service with pagination, that uses `RetrofitMock` for testing.
