### ISSUE TITLE
Exclude sensitive information from body

### ISSUE THREAD

**Issue by raderio** [square/retrofit#3401]
We need a way to hide(replace with "****") some sensitive information from the body.

Is there something similar to `redactHeader` from `HttpLoggingInterceptor` but for the body properties?

This will not be supported in okhttp https://github.com/square/okhttp/issues/6085#event-3367771637

**Comment by ctlove0523** [comment]
Anonymize sensitive information from response body is more personalise,different system has different request,so you can writer you own interceptor to do what you want .

**Comment by JakeWharton** [comment]
The body is controlled by your chosen converter which is backed by a third-party serialization library like Jackson, Gson, Moshi, etc. If you want to redact or remove properties of your model from the serialized form you need to configure the serialization library to do so based on the type or an annotation.

Retofit plays no part in creating the body contents so it cannot help here.
