### ISSUE TITLE
Issue with Retrofit @GET with Authorization Header compiled on Android Studio 4.0

### ISSUE THREAD

**Issue by kenshin171** [square/retrofit#3409]
I am not sure if this is a Retrofit issue or an Android studio 4.0 Stable R8 issue.
When compiling my application with Android Studio 4.0 which has R8 of the below version
`2.0.74 (build 685ad9374465eb129da58ec98866fb293828285e from go/r8bot (luci-r8-ci-xenial-11-58q1))`

Any Retrofit GET calls with an `Authorization` header seems to hang forever. POST calls with `Authorization` header seems to be ok.
However calls with non-authorization headers seems to work for all HTTP method calls.
I attached a HttpLoggingInterceptor and below would be the sequence of events.

```
--> GET https://someApiBackendapi.com/v1/path?param1=parm1value
header1: 20200531T090135Z
host: someApiBackendapi.com
Authorization: <redacted authorization data>
--> END GET
```
After which no callbacks or errors will be returned at all no matter how long i wait, not even the read timeouts, connection timeout or write timeouts will be of use.

below is the sample of my retrofit service.

```
val client = OkHttpClient.Builder()
                .retryOnConnectionFailure(true)
                .followRedirects(false)
                .followSslRedirects(false)
                .certificatePinner(certPinner)
                .connectTimeout(10, TimeUnit.SECONDS)
                .readTimeout(readTimeout, TimeUnit.SECONDS)
                .writeTimeout(readTimeout, TimeUnit.SECONDS)
                .addInterceptor(signingInterceptor)
                .addInterceptor(httpLoggingInterceptor)
                .retryOnConnectionFailure(true)
                .build()

val restAdapter = Retrofit.Builder()
                .client(client)
                .baseUrl("https://somebaseurl.com")
                .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
                .addConverterFactory(ScalarsConverterFactory.create())
                .addConverterFactory(MoshiConverterFactory.create())
                .build()

val service = restAdapter.create(myRetrofitService::class.java)
```

### Scenarios working as expected
- I have tried setting minify to `false` and *everything works as expected* on Android Studio 4.0.
- I have also tried compiling the apk with Android Studio 3.6.3 and *everything works as expected* as well. The R8 verision here is `1.6.82`.

### Scenarios not working as expected
- I have tried toggling `android.enableR8.fullMode` in gradle.properties, no working.
- I have added all the r8 rules as per [retrofit rules](https://github.com/square/retrofit/blob/master/retrofit/src/main/resources/META-INF/proguard/retrofit2.pro) , [okio rules](https://github.com/square/okio/blob/master/okio/src/jvmMain/resources/META-INF/proguard/okio.pro) and as per stated [here](https://square.github.io/okhttp/r8_proguard/) okhttp rules are prebundled for r8.

    retroFit2Version = '2.9.0'
    okHttpBomVersion = '4.7.2'
    okioVersion = '2.6.0'

What kind of issue is this?

 - [x] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [X] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by swankjesse** [comment]
Latest versions of OkHttp, Okio, and Retrofit? Can you create an executable test case that reproduces this problem?

**Comment by kenshin171** [comment]
yes latest versions of okio, okhttp and retrofit. This seems like an R8 issue, maybe i can try to create a sample project?

**Comment by kenshin171** [comment]
### Update
i cannot seem to reproduce this with my sample project, however downgrading r8 version manually seems to fix the issue. `classpath 'com.android.tools:r8:1.6.82'`. 

 it seems that only selective retrofit calls i make are getting stuck, i cannot seem to determine a pattern and contrary to my initial believe, not only @GET calls suffer from this symtome.

**Comment by kenshin171** [comment]
### Update 2

My apologies, this issue is not with retrofit, it was with a config in r8 rules which behaved differently with the latest version of r8. full context can be seen here. https://issuetracker.google.com/issues/158018192#comment3. 

And again my apologies
