### ISSUE TITLE
 MediaType.parse java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by Vangaorth** [square/retrofit#3412]
In a Java Android project using Android Studio 4.0, with gradle plugin 4.0.0 and proguard enabled (with proper rules), calling

`MediaType mediaType = MediaType.parse("application/octet-stream");`

makes the application (built with the release configuration) crash with the following exception

`The method 'f.a0 f.a0$a.b(java.lang.String)' was expected to be of type virtual but instead was found to be of type static (declaration of 'd.a.a.c.h.p0' appears in /data/app/my.app.packageid.dev-1L1taSMlTPHQ0cbe1kpruQ==/base.apk)
       at okhttp3.MediaType.parse(MediaType.java:6)`

This does not happen when downgrading to gradle 3.6.3 (com.android.tools.build:gradle:3.6.3). Every version from 2.8.1 to latest 2.9.0 seems to be affected by it

**Comment by swankjesse** [comment]
Please report this bug to the AGP maintainers. There's nothing we can do unfortunately.
