### ISSUE TITLE
Getting empty string in onFailure message

### ISSUE THREAD

**Issue by KulkarniKaustubh** [square/retrofit#3413]
What kind of issue is this?

 I am not able to establish connection with the json api link.

Here is the retrofit calling code:
```
val retrofit: Retrofit =
            Retrofit.Builder()
                .baseUrl("https://api.covid19india.org/")
                .addConverterFactory(GsonConverterFactory.create())
                .build()

        ind_api = retrofit.create(indiaApi::class.java)
        call = ind_api?.getFullData()

@SuppressLint("SetTextI18n")
    override fun onPostExecute(result: Void?) {
        super.onPostExecute(result)

        call?.enqueue(object : Callback<AllData> {
            override fun onFailure(call: Call<AllData>, t: Throwable) {
                Log.e(TAG, "ERROR : " + t.message)
                indiaLoading.visibility = View.GONE
                indiaText.text = "No internet. Please retry."
            }

            override fun onResponse(call: Call<AllData>, response: Response<AllData>) {
                allData = response.body()
                indiaLoading.visibility = View.GONE
                indiaText.text = allData?.toString()
            }

        })
```
Here is my interface:
```
package com.androiddevs.confused.ui

import retrofit2.Call
import retrofit2.http.GET

public interface indiaApi {
    @GET("data.json")
    fun getFullData() : Call<AllData>
}
```

**Comment by KulkarniKaustubh** [comment]
The log message:
```
2020-06-05 15:12:18.065 27862-27862/com.mine.coronaapp E/ContentValues: ERROR : empty String
```

**Comment by ctlove0523** [comment]
> The log message:
> 
> ```
> 2020-06-05 15:12:18.065 27862-27862/com.mine.coronaapp E/ContentValues: ERROR : empty String
> ```
What return from server when the request failed?

**Comment by JakeWharton** [comment]
That value "empty String" is coming from the exception. Which is presumably coming from some Gson adapter. Without a failing test case or executable sample it's impossible to know. As far as I can tell I don't see anything that Retrofit is doing wrong here. The issue template contained a test case template that you can use. I would suggest capturing the raw JSON from the API you are hitting, enqueuing it with MockWebServer, and then hitting it with your Retrofit service. This will remove the network and backend server from the equation and let you debug what's going on.

**Comment by SahilGargCrownStack** [comment]
I'm facing the same issue. The request successfully executed in Postman but using retrofit it always goes in onFailure and give 'empty string' error message

**Comment by SahilGargCrownStack** [comment]
@JakeWharton please help us out
