### ISSUE TITLE
null pointer exception: On getting Array of String from Retrofit Pojo

### ISSUE THREAD

**Issue by irfan-429** [square/retrofit#3418]
What kind of issue is this?

 - [x] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by JakeWharton** [comment]
"Array of string from Retrofit pojo" sounds like you're accessing a field or property from the body object Retrofit returned to you. However, that type was populated by your chosen serialization library from the contents of the HTTP response body. Retrofit has no influence over its behavior.

Also, there's no information here to even begin to diagnose what's going on in the first place so I'm basically making a wild guess anyway.
