### ISSUE TITLE
Allow the converters to accept a custom MediaType

### ISSUE THREAD

**Issue by Nilzor** [square/retrofit#3428]
Feature request:

I have a use case where the server [1] only accepts a non-standard `Content-Type` header, goverened by the `MediaType` set by the Retrofit converter. Even though the content is JSON, it will reject the query with a `415` response if `Content-Type=application/json`. Both the Jackson-converter and Gson-converter have [hard-coded MediaType](https://github.com/square/retrofit/blob/master/retrofit-converters/jackson/src/main/java/retrofit2/converter/jackson/JacksonRequestBodyConverter.java#L25)

You could argue that the server is wrong, but I don't own the server and have little to no power to change it. There might also be more servers like it. 

Overriding the `Content-Type` through interceptors doesn't work - it seems the MediaType one set with `okhttp3.RequestBody.create(MEDIA_TYPE, bytes);` trumps any interceptor's attempt to override the `Content-Type`.

I suppose it's a rather simple thing to implement (I could do it), but does it belong in Retrofit?

[1] It's the [AppDynamics Analytics Event API](https://docs.appdynamics.com/display/PRO45/Analytics+Events+API). The `Content-Type` it requires is `application/vnd.appd.events+json;v=2`

**Comment by JakeWharton** [comment]
We'll never get 'em all to update.

Maybe we add a default method to the factory which lets you override? `withRequestMediaType` or something?

**Comment by swankjesse** [comment]
You can do it in an interceptor. Replace the request body with one that forwards everything to the original request body, except the media type.

Alternately you could do a converter that wraps the Moshi or Gson converter and forwards everything except the media type.

**Comment by Nilzor** [comment]
You are right @swankjesse it could be solved by replacing the `RequestBody` object! I created this Interceptor-RequestBody-pair that will do the job:

https://gist.github.com/Nilzor/dc4a493355226bfbf86c24feb467d1a6

Tested and works.

I guess this is a better solution than what I hinted at first @JakeWharton so I am closing the issue.
