### ISSUE TITLE
Retrofit bug : java.lang.NoSuchMethodError: No static method metafactory

### ISSUE THREAD

**Issue by thomaslprr** [square/retrofit#3429]
Hello, 
I can't use Retrofit.

When I try to request the API here is the error: 
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.dev.gpstracker, PID: 18447
    java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.runtime/javalib/core-oj.jar)
        at okhttp3.internal.Util.<clinit>(Util.java:87)
        at okhttp3.internal.Util.skipLeadingAsciiWhitespace(Util.java:321)
        at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1313)
        at okhttp3.HttpUrl.get(HttpUrl.java:917)
        at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:506)
        at fr.dev.gpstracker.MainActivity$3$1.onClick(MainActivity.java:173)
        at android.view.View.performClick(View.java:7125)
`

**MainActivity.java**

```
Retrofit retrofit = new Retrofit.Builder()
                                            .baseUrl("https://api-adresse.data.gouv.fr/")
                                            .addConverterFactory(GsonConverterFactory.create())
                                            .build();

                                    ApiAdresseGouv apiAdresseGouv = retrofit.create(ApiAdresseGouv.class);
                                    Call<List<Adresse>> appelApi = apiAdresseGouv.getAdresse(2.37,48.357);

                                    appelApi.enqueue(new Callback<List<Adresse>>() {
        ........


```

**ApiAdresseGouv.java**
`
    @GET("reverse/")
    Call<List<Adresse>> getAdresse(@Query("lon") double longitude, @Query("lat") double latitude);
`

**Context**
Mac os - Android Studio

Thanks in advance

**Comment by swankjesse** [comment]
Solution is here:
https://stackoverflow.com/questions/59448845/no-static-method-metafactory

**Comment by thomaslprr** [comment]
I have already see this solution but the problem is :
`ERROR: Could not find method kotlinOptions() for arguments [build_bgkz3etaeesijop74g1ed2d2y$_run_closure1$_closure6@2df1fcc5] on object of type com.android.build.gradle.internal.dsl.BaseAppModuleExtension.
`

because of : 
```
kotlinOptions {
        jvmTarget = "1.8"
    }
```
And I don't know how to solve it

**Comment by thomaslprr** [comment]
Ok now it's ok.
I've improved the response on StackOverFlow to make it even more complete for the next ones.
Thanks anyway 😄
