### ISSUE TITLE
base path for a set of api - prefix handling

### ISSUE THREAD

**Issue by maifeeulasad** [square/retrofit#3432]
What kind of issue is this?

 -  Feature Request. 
I will say it is a feature request cause for a week I couldn't get any solution. 
**How to add base path for a set of requests ?**

Imagine I have two set of APIs:
 - auth
   - signin (`/auth/signin`)
   - signup (`/auth/signup`)
 - info
   - user (`/info/user`)
   - edit (`/info/edit`)

For the first set one of the way to handle this is creating a class like this : 
```
//@RequestMapping("./auth")    <<<--- how I want to write
public interface AuthService {
    //@POST("./signup")               <<<--- how I want to write
    @POST("./auth/signup")
    Call<SignupResponse> signup(@Body SignupRequest signupRequest);

    //@POST("./signin")                <<<--- how I want to write
    @POST("./auth/signin")
    Call<SigninResponse> signin(@Body SigninRequest signinRequest);
}
```

I guess you already got this what I meant to say, like Spring Boot has `RequestMapping` annotation. Won't it be great to have such nice thing in retrofit ?

*If you guys start development under this issue. You can assign me. I want to work on this. Thank you.*

**Comment by JakeWharton** [comment]
We don't have any plans to support annotations on the type.

You can read more about our reasoning here: https://github.com/square/retrofit/pull/1138#issuecomment-162137881
