### ISSUE TITLE
Fatal Exception: java.net.ConnectException Failed to connect to www.ekincare.com/3.6.16.227:443 okhttp3.internal.connection.RealConnection.connectSocket

### ISSUE THREAD

**Issue by PhalugunaRao** [square/retrofit#3433]
okhttp3.internal.platform.Platform.connectSocket (Platform.kt:120)
okhttp3.internal.connection.RealConnection.connectSocket (RealConnection.kt:283)
okhttp3.internal.connection.RealConnection.connect (RealConnection.kt:195)
okhttp3.internal.connection.ExchangeFinder.findConnection (ExchangeFinder.kt:249)
okhttp3.internal.connection.ExchangeFinder.findHealthyConnection (ExchangeFinder.kt:108)
okhttp3.internal.connection.ExchangeFinder.find (ExchangeFinder.kt:76)
okhttp3.internal.connection.RealCall.initExchange$okhttp (RealCall.kt:245)
okhttp3.internal.connection.ConnectInterceptor.intercept (ConnectInterceptor.kt:32)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:100)
okhttp3.internal.cache.CacheInterceptor.intercept (CacheInterceptor.kt:96)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:100)
okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.kt:83)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:100)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.kt:76)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:100)
com.ekincare.network.retrofit.RetrofitHandler$Companion$get_HTTPClient$1.intercept (RetrofitHandler.kt:80)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:100)
okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp (RealCall.kt:197)
okhttp3.internal.connection.RealCall$AsyncCall.run (RealCall.kt:502)

**Comment by JakeWharton** [comment]
This is a normal failure that occurs when the network is not available.

**Comment by asimc2** [comment]
> okhttp3.internal.platform.Platform.connectSocket (Platform.kt:120)
> okhttp3.internal.connection.RealConnection.connectSocket (RealConnection.kt:283)
> okhttp3.internal.connection.RealConnection.connect (RealConnection.kt:195)
> okhttp3.internal.connection.ExchangeFinder.findConnection (ExchangeFinder.kt:249)
> okhttp3.internal.connection.ExchangeFinder.findHealthyConnection (ExchangeFinder.kt:108)
> okhttp3.internal.connection.ExchangeFinder.find (ExchangeFinder.kt:76)
> okhttp3.internal.connection.RealCall.initExchange$okhttp (RealCall.kt:245)
> okhttp3.internal.connection.ConnectInterceptor.intercept (ConnectInterceptor.kt:32)
> okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:100)
> okhttp3.internal.cache.CacheInterceptor.intercept (CacheInterceptor.kt:96)
> okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:100)
> okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.kt:83)
> okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:100)
> okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.kt:76)
> okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:100)
> com.ekincare.network.retrofit.RetrofitHandler$Companion$get_HTTPClient$1.intercept (RetrofitHandler.kt:80)
> okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:100)
> okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp (RealCall.kt:197)
> okhttp3.internal.connection.RealCall$AsyncCall.run (RealCall.kt:502)

Hi @PhalugunaRao 
did you find any solution of that issue?
