### ISSUE TITLE
OkHttp Version in retrofit cause NoClassFound if used with logging-interceptor

### ISSUE THREAD

**Issue by yoavgeva** [square/retrofit#3435]
I am using this versions of the libraries
 ` <dependency>
           <groupId>com.squareup.okhttp3</groupId>
           <artifactId>logging-interceptor</artifactId>
           <version>4.7.2</version>
       </dependency>
       <dependency>
           <groupId>com.squareup.retrofit2</groupId>
           <artifactId>retrofit</artifactId>
           <version>2.9.0</version>
           </dependency>`

I get NoClassFound for kotlin/jvm/internal/intrinsics 

I fixed by excluding OkHttp from Retrofit, I suggest updating the OkHttp version

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [*] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by swankjesse** [comment]
Just make sure the OkHttp and logging interceptor versions are the same. You can accomplish this with a Gradle platform.

```
dependencies {
   api(platform("com.squareup.okhttp3:okhttp-bom:4.7.2"))
   api("com.squareup.okhttp3:okhttp")              // No version!
   api("com.squareup.okhttp3:logging-interceptor") // No version!
}

```

**Comment by yoavgeva** [comment]
@swankjesse I understand you can do it, but it's a hack, there is a need to update okhttp version in the retrofit library.

**Comment by JakeWharton** [comment]
We have never tracked OkHttp releases. You should assume the dependency will be slightly out of date but always functional.
