### ISSUE TITLE
java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.runtime/javalib/core-oj.jar)

### ISSUE THREAD

**Issue by sandeepPalagati** [square/retrofit#3438]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by sandeepPalagati** [comment]
Iam facing the issue while using the retrofit for android, And iam using gradle plugin 4.0.0 and also i am writing in java.can you guys help me with this?

**Comment by sandeepPalagati** [comment]
Retrofit retrofit=new Retrofit.Builder().
                baseUrl("https://jsonplaceholder.typiecode.com/")
                .addConverterFactory(GsonConverterFactory.create())
                .build();

**Comment by JakeWharton** [comment]
You must enable Java 8 language support on your project: https://developer.android.com/studio/write/java8-support#supported_features

**Comment by sandeepPalagati** [comment]
But Iam using gradle plugin 4.0.0 and according to the documentation by
google this version has java8 enabled

**Comment by JakeWharton** [comment]
It is not enabled by default. You need to set it manually in `compileOptions`
