### ISSUE TITLE
Convert POKO to form request.

### ISSUE THREAD

**Issue by gilgamesharcadia** [square/retrofit#3442]
Feature Request:

It would be nice a way to convert a POKO to a form request.

```kotlin
// The POKO (class or data class)
data class Foo(
    val a: String,
    val b: String
)

// Current way of sending the params
@FormUrlEncoded
@POST("url")
suspend fun foo(
    @Field("a") a: String,
    @Field("b") b: String
): Response<Any>

// Proposed way of sending the params without redefining them.
@FormUrlEncoded
@POST("url")
suspend fun foo(@FormBody() foo: Foo): Response<Any>
```

The why: I think is pretty common in OOP to have a request class per service so every time an API expects params instead of a JSON you have to redefine those params in the service and in the class. You could say don't create a class but then every change on the service will mean changes in more than one layer of code needlessly.

Thanks for your time.

**Comment by JakeWharton** [comment]
The easiest way to do this is with a default method:
```kotlin
data class Foo(
    val a: String,
    val b: String
)

// Current way of sending the params
@FormUrlEncoded
@POST("url")
suspend fun foo(
    @Field("a") a: String,
    @Field("b") b: String
): Response<Any>

suspend fun foo(foo: Foo) = foo(foo.a, foo.b)
```

We have no plans to support object binding for form or multipart requests. #626 tracks the ability for a single parameter to set multiple parts of a request.
