### ISSUE TITLE
On Android, converter-protobuf requires API 26 - even with Java 8 target

### ISSUE THREAD

**Issue by stoyicker** [square/retrofit#3445]
What kind of issue is this?

 - [x] Bug report. https://github.com/stoyicker/converter-protobuf-bug Android Studio template with dependencies removed and min api 25 with converter-protobuf 2.9.0. I've verified that 2.8.1 also has the problem.

**Comment by hualong-shen** [comment]
Same issue. It seems that the converter uses protobuf java 3.10.0 internally which requires min API 26. https://github.com/protocolbuffers/protobuf/issues/6718
