### ISSUE TITLE
SSL/TLS Connection issue 

### ISSUE THREAD

**Issue by mohsen2986** [square/retrofit#3447]
As per the docs in Android for SSLSocket and SSLContext, TLS v1.1 and v1.2 protocols are supported in API level 16+ but some 
android developer solve this by using custom SSLAdapter!! is it better to solve this problem by adding that custom adapter to retrofit with  OkHttpClient?

**Comment by JakeWharton** [comment]
Retrofit has no visibility into this as it operates at a level much farther down the stack. So, in general, we are not in a position to provide guidance here.
