### ISSUE TITLE
Make reflective call to Lookup lazy on first default method invocation

### ISSUE THREAD

**Issue by Dragas** [square/retrofit#3448]
After moving my project to fully support JPMS (JDK11), and retrofit has become unusable due to the following error:
```
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make private java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int) accessible: module java.base does not "opens java.lang.invoke" to module retrofit2
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
	at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:189)
	at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:182)
	at retrofit2@2.9.0/retrofit2.Platform.<init>(Platform.java:59)
	at retrofit2@2.9.0/retrofit2.Platform.findPlatform(Platform.java:44)
	at retrofit2@2.9.0/retrofit2.Platform.<clinit>(Platform.java:35)
	... 11 more
```
It seems that retrofit deeply depends on Java's Lookup class and making its constructor visible to itself. The issue becomes apparent, when using the JPMS. A workaround for this is to add `--add-opens java.base/java.lang.invoke=retrofit2` but it would be nice if there wasn't such need to expose the base module's packages myself. Perhaps add a call to `Module#addOpen(String, Module)` when initializing retrofit's class?

**Comment by JakeWharton** [comment]
If you can move to JDK 14 or newer this reflective call is no longer required. I suspect we'll probably make it lazy rather than eager, but I don't see us adding a call to `Module` (unless that also was done with reflection).

**Comment by JakeWharton** [comment]
#3444 was the motivation for making it lazy. This is yet another reason!

The reflection is only needed when your service interfaces have default methods (on pre-14).

**Comment by Dragas** [comment]
I doubt reflectively calling `Module` class will solve the issue, considering `open` declaration in module definition is what permits reflective operations against module exposing those classes. See: https://hg.openjdk.java.net/jdk/jdk11/file/1ddf9a99e4ad/src/java.base/share/classes/module-info.java, which does not contain an `open` declaration on `java.lang` package.

**Comment by JakeWharton** [comment]
I can't reflectively invoke public API? That's pretty nonsensical on the JDKs part. But since this isn't a problem with JDK 14 any more I'm inclined to make the reflective lookup on `Lookup` lazy on first use and if you are using default methods on pre-14 in the module system then you'll just have to live with opening up java.base until you can upgrade to 14 or newer.

**Comment by Dragas** [comment]
Fair enough.

**Comment by robertvazan** [comment]
@JakeWharton You can definitely access all public APIs via reflection even with strong module encapsulation.

**Comment by nienienienie** [comment]
true :)

> If you can move to JDK 14 or newer this reflective call is no longer required. 

I had JDK 11 and warning was there.

Then I moved to JDK 17 and it's gone.

**Comment by JakeWharton** [comment]
This happened, at some point. The lookup is now lazy.

https://github.com/square/retrofit/blob/e34aee654b04f48b1936d8df41436cf3a7707d9a/retrofit/src/main/java/retrofit2/DefaultMethodSupport.java#L36-L37
