### ISSUE TITLE
JavaEE/JakartaEE Json-B Converter

### ISSUE THREAD

**Issue by cchacin** [square/retrofit#3455]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Hello **retrofit2** community,

There is not converter yet AFAIK for the (JavaEE/JakartaEE Json Binding (Json-B) API)[http://json-b.net/], I created a simple (not polished yet) implementation for it in this repository: [jsonb-retrofit-converter](https://github.com/cchacin/jsonb-retrofit-converter/tree/master/src/main/java/retrofit2/converter/jsonb)

The intention of this issue is to discuss if it makes sense to create a Pull Request adding the converter in this repository.

Thanks!

**Comment by JakeWharton** [comment]
We are not accepting any new first-party converters at this time. There is a list of third-party converters available on the wiki here: https://github.com/square/retrofit/wiki/Converters. Please add yours!

**Comment by cchacin** [comment]
Added https://github.com/square/retrofit/wiki/Converters

Thanks!
