### ISSUE TITLE
Introduce a way to have custom error handling adapter with suspend functions

### ISSUE THREAD

**Issue by mnayef95** [square/retrofit#3461]
When using Retrofit with normal `Call<>` it's easy to custom the `Call<>` to be something like `MyCall<>` and in the adapter, we can handle the errors and return our custom error instead of `HttpException` as appearing in this [example](https://github.com/square/retrofit/blob/master/samples/src/main/java/com/example/retrofit/ErrorHandlingAdapter.java).

But when it comes to coroutines suspend functions we don't have a way to do that thing

**Comment by MiSikora** [comment]
You can write your own adapter for a custom class. For example, in one of my projects we use this class.

```kotlin
sealed class NetworkResponse<out T> {
  data class Success<out T>(
    val statusCode: Int,
    val headers: Map<String, List<String>>,
    val value: T,
  ) : NetworkResponse<T>()

  sealed class Failure : NetworkResponse<Nothing>() {
    data class Http(
      val statusCode: Int,
      val headers: Map<String, List<String>>,
      val rawBody: ResponseBody?,
    ) : Failure()

    data class Fatal(
      val throwable: Throwable,
    ) : Failure()
  }
}
```

You need to write a factory that creates `CallAdapter<T, Call<NetworkResponse<T>>>` adapters. Then you'll be able to use something like `suspend fun foo(): NetworkResponse<Foo>`.

**Comment by mnayef95** [comment]
@MiSikora Could you please share an example of the `CallAdapter` ?

**Comment by JakeWharton** [comment]
There is an example here: https://github.com/square/retrofit/blob/576f23dae73814b23787322d8f663c4421af8939/retrofit/src/test/java/retrofit2/KotlinSuspendTest.kt#L237-L279. It doesn't change the type, but merely duplicates the response body.
