### ISSUE TITLE
Retrofit crashes on android API 23 (Marshmallow)

### ISSUE THREAD

**Issue by SnoopyCodeX** [square/retrofit#3472]
My app crashes as soon as I add retrofit as gradle dependency. My device's API level is 23 which is Marshmallow.

**Comment by JakeWharton** [comment]
You haven't provided any information. How are we supposed to determine what is happening? At minimum you need a full stack trace. Better would be a failing test case or reproducing sample.

**Comment by SnoopyCodeX** [comment]
> You haven't provided any information. How are we supposed to determine what is happening? At minimum you need a full stack trace. Better would be a failing test case or reproducing sample.

Hi sir, my logcat does not show anything after my app crashes.

If I remove retrofit in build.gradle (app level build.gradle), my app does not crash.

But as soon as I place back retrofit in my build.gradle (just the repo, did not implemented the code yet in my java files), my app crashes.

I don't know why and my logcat does not show anything.
