### ISSUE TITLE
Retrofit keeps firing GET requests until the server stops it with "too many requests" message.

### ISSUE THREAD

**Issue by AhnnsetAPPL** [square/retrofit#3482]
Hi there, 

I am using Retrofit with RxJava2 Adapter and OkHttp client, here is my setup:

`object ApiFactory {

    fun makeApiService(isDebug: Boolean): ApiService {
        val okHttpClient = makeOkHttpClient(
            makeLoggingInterceptor(isDebug)
        )
        return makeApiService(okHttpClient, Gson())
    }

    private fun makeApiService(okHttpClient: OkHttpClient, gson: Gson): ApiService {
        val retrofit = Retrofit.Builder()
            .baseUrl("https://depanage.digitnumlab.net/api/")
            .client(okHttpClient)
            .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
            .addConverterFactory(GsonConverterFactory.create(gson))
            .build()
        return retrofit.create(ApiService::class.java)
    }

    private fun makeOkHttpClient(httpLoggingInterceptor: HttpLoggingInterceptor): OkHttpClient {
        return OkHttpClient.Builder()
            .addInterceptor(httpLoggingInterceptor)
            .connectTimeout(120, TimeUnit.SECONDS)
            .readTimeout(120, TimeUnit.SECONDS)
            .build()
    }

    private fun makeLoggingInterceptor(isDebug: Boolean): HttpLoggingInterceptor {
        val logging = HttpLoggingInterceptor()
        logging.level = if (isDebug) {
            HttpLoggingInterceptor.Level.BODY
        } else {
            HttpLoggingInterceptor.Level.NONE
        }
        return logging
    }
}`

I am also using dagger 2 to inject it as a dependency

`@Module
abstract class RemoteModule {

    @Binds
    abstract fun bindServicesRemoteRepository(remote: ServicesRemoteRepositoryImpl)
            : ServicesRemoteRepository

    @Binds
    abstract fun bindAuthRemoteRepository(remote: AuthRemoteRepositoryImpl)
            : AuthRemoteRepository

    @Module
    companion object {

        @JvmStatic
        @Singleton
        @Provides
        fun provideApibService(): ApiService {
            return ApiFactory.makeApiService(BuildConfig.DEBUG)
        }
    }
}`

The issue is despite using RxJava Single<T> for the call and using @Singleton annotation, Retrofit won't stop making GET request until the server responds with "Too many requests".

`interface ApiService {

    @GET("categories")
    fun fetchCategories(
        @Header("Authorization") authHeader: String
    ): Single<CategoryResp>

    @GET("subcategories")
    fun fetchSubCategories(
        @Header("Authorization") authHeader: String
    ): Single<SubCategoryResp>
}`

Please can anyone help me out ?

**Comment by JakeWharton** [comment]
Retrofit does not retry calls. OkHttp follows redirects but does not retry calls arbitrarily. Can you provide a failing test case that demonstrates the behavior?

**Comment by AhnnsetAPPL** [comment]
Sorry Jake, It was my mistake, I used LiveData to trigger the GET request, I moved the function to the init block in my viewModel, it's all good now.
