### ISSUE TITLE
Link to Jackson seems to be dead

### ISSUE THREAD

**Issue by h4n23s** [square/retrofit#3483]
Hi there, the link to Jackson on your website seems to be dead.

It could be replaced with a link to their [GitHub repository](https://github.com/FasterXML/jackson) or a capture of the [internet archive](http://web.archive.org/web/20170831135541/http://wiki.fasterxml.com/JacksonHome).

Thanks.

**Comment by JakeWharton** [comment]
Hmm which link are you referring to?

Also if you want to send a PR that'd be swell! Linking to the repo seems good.

**Comment by h4n23s** [comment]
I'm referring to http://wiki.fasterxml.com/JacksonHome (see "Converters") on https://square.github.io/retrofit/.
