### ISSUE TITLE
Content-Type set in interceptor is overwritten, maybe by ConverterFactory default 

### ISSUE THREAD

**Issue by matecode** [square/retrofit#3485]
- [X] Bug report.

I think its a bug, maybe not, we will see ;) If I set the Content-Type header with chain interceptor, it will be overwritten to a default. I guess it is the ConverterFactory, but i'm not sure. 

I wrote a test to show whats happening. In interceptor I set `.addHeader("Content-Type", "application/vnd.x.api.v1+json")` which is also logged by HttPLoggingInterceptor, but the request received by the MockServer has `Content-Type: application/json; charset=UTF-8`

If anything is unclear fell free to ask.

```

open class RetrofitBug {
    internal interface Service {
        @POST("/path")
        fun post(@Body body:PostBody): Call<ResponseBody?>
    }

    data class PostBody(val value: String)

    @Test
    @Throws(Exception::class)
    fun test() {
        val server = MockWebServer()
        val retrofit = Retrofit.Builder()
            .addConverterFactory(
                GsonConverterFactory.create(
                    GsonBuilder()
                        .create()
                )
            )
            .client(
                OkHttpClient().newBuilder()
                    .addInterceptor { chain ->
                        val newRequest = chain.request().newBuilder()
                            .addHeader("Content-Type", "application/vnd.x.api.v1+json")
                            .build()
                        chain.proceed(newRequest)
                    }
                    .addInterceptor(HttpLoggingInterceptor { message -> println(message) }.apply {
                        level = HttpLoggingInterceptor.Level.BODY
                    })
                    .build()
            )
            .baseUrl(server.url("/"))
            .build()
        val example = retrofit.create(
            Service::class.java
        )
        server.enqueue(
            MockResponse()
                .addHeader("Content-Type", "text/plain")
                .setBody("Hi")
        )
        val call = example.post(PostBody("Test"))
        val response = call.execute()
        val recordedRequest = server.takeRequest()
        assertEquals("application/vnd.x.api.v1+json", recordedRequest.getHeader("Content-Type"));
        server.shutdown()
    }
}
```

**Comment by waqasakram117** [comment]
Use this ` .header("Content-Type", "application/vnd.x.api.v1+json")` instead of 
` .addHeader("Content-Type", "application/vnd.x.api.v1+json")` because .addHeader use for adding multiple headers like cookies etc but .header will replace(if already header exists) or add new one.

**Comment by JakeWharton** [comment]
That's right. Also if you use `getHeaders` on the MockWebServer validation you'll get a list with two values for both headers which also would have helped indicate the problem.

**Comment by matecode** [comment]
Thx for your answer @waqasakram117 , but using `.header("Content-Type", "application/vnd.x.api.v1+json")`does not change anything. The request still uses the header `Content-Type: application/json; charset=UTF-8`

@JakeWharton also thx for your answer. if i use `headers`on RecordedRequest i can see the following list which also points out that not the Content-Type Headers come along which i set before:
```
Content-Type: application/json; charset=UTF-8
Content-Length: 16
Host: localhost:49434
Connection: Keep-Alive
Accept-Encoding: gzip
User-Agent: okhttp/4.9.0
```

So it is still like somewhat is overwriting the header on a later step, **after** I set it at the interceptor.
I'm sorry to see you closing this issue so fast. Maybe it worth reopening it again?

**Comment by waqasakram117** [comment]
@matecode use **addNetworkInterceptor** not **addInterceptor** [these](https://square.github.io/okhttp/interceptors/) are different and it will work.

**Comment by matecode** [comment]
@waqasakram117  thank you for pointing out that!
