### ISSUE TITLE
how to deal with IP changes（ The application does not restart）

### ISSUE THREAD

**Issue by fanqGithub** [square/retrofit#3488]
Questions：

The IP of the Android machine is switched, and the API Service network request created by the singleton method times out

**Comment by JakeWharton** [comment]
Connections happen way, way below Retrofit such that we have no control over it. The highest level that this could be handled is inside OkHttp. I'm not sure how to test this or whether it's meant to be handled, but I do know that Retrofit cannot do anything about it.
