### ISSUE TITLE
Add Kotlinx.serialization support

### ISSUE THREAD

**Issue by XhstormR** [square/retrofit#3495]
https://github.com/Kotlin/kotlinx.serialization/releases/tag/v1.0.0

As the release said, it is now a stable version.

**Comment by JakeWharton** [comment]
Parts of it are stable, yes, but the parts that are required for building a converter are still experimental.

For now you can use the unbundled version here: https://github.com/JakeWharton/retrofit2-kotlinx-serialization-converter/

**Comment by JakeWharton** [comment]
Additionally, the design of Retrofit is such that we shouldn't have to ship first-party converters for everything out of this repo. The code in the one I linked is exactly the same as what would be bundled into a converter here.
