### ISSUE TITLE
[Feature Request] Support adapter for Kotlin Coroutine Flow

### ISSUE THREAD

**Issue by PatilShreyas** [square/retrofit#3497]
## Feature Request

It would be great if it supports Kotlin Coroutine [`Flow<T>`](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-flow/) adapter for getting a response in the stream.

**For example:**

```kotlin
interface FeedApi {
    @GET("/")
    fun getPosts(): Flow<List<Post>>
}
```

If this is available then it will be easy to use and it'll be easy to map network response to the app's data model and for many `Flow` specific operations as well.

**Comment by JakeWharton** [comment]
HTTP requests return a single response, not a stream of responses, and so only `suspend fun` is supported.
```kotlin
interface FeedApi {
    @GET("/")
    suspend fun getPosts(): List<Post>
}
```
If you need to emit this as a flow you can do something like
```
flow {
  emit(getPosts())
}
```
We won't be supporting `Flow` out of the box, and if we had the chance to do the RxJava adapters over again we probably wouldn't support their `Observable` either (`Single` is the natural type to use).

**Comment by PatilShreyas** [comment]
Thanks!

**Comment by Goooler** [comment]
This is useful for #1029.

**Comment by MukjepScarlet** [comment]
> This is useful for [#1029](https://github.com/square/retrofit/issues/1029).

see #4462
