### ISSUE TITLE
Empty responses after gradle and gradle plugin update to 4.1.1 and 6.5

### ISSUE THREAD

**Issue by ChrisMpitzios** [square/retrofit#3503]
After the aforementioned update responses received are empty only in release builds. We bumped from:
3.6.3 -> 4.1.1
5.6.4 -> 6.5
If we set disable minify to false then things get back to normal, so maybe there is something missing in proguard rules?
(dont know how to simulate it through a failing test)

**Comment by JakeWharton** [comment]
Can you reproduce it in a standalone sample project that we could look at? Otherwise there's really no information here to go on.

**Comment by ChrisMpitzios** [comment]
I will try to reproduce it in a standalone project otherwise i will post our gradle(s) files and proguard files (if they can help) thanks

**Comment by AndroidDeveloperLB** [comment]
@JakeWharton I might have a similar issue. Not sure if it's the same here. Reported still as a new one:
https://github.com/square/retrofit/issues/3534
