### ISSUE TITLE
First request takes as long as the connectTimeout

### ISSUE THREAD

**Issue by houmie** [square/retrofit#3504]
I may have found a bug. The first request takes as long as the connectTimeout (5 seconds). Any subsequent calls go then really fast.  Why is the first call waiting until the timeout exceeds before it succeeds?

This is independent from API. Because when I change `.connectTimeout(5, TimeUnit.SECONDS)` to 10 seconds. Then the first call takes 10 seconds.  And if I lower it to 1 second, then it takes 1 second the first time around. 

I even tried to disable proxy ```.proxy(Proxy.NO_PROXY)```.

I'm at this point unsure if this is a Retrofit or okHttpsClient issue. 

```
import okhttp3.OkHttpClient
import retrofit2.Call
import retrofit2.Retrofit
import retrofit2.converter.moshi.MoshiConverterFactory
import java.util.concurrent.TimeUnit

object ApiService {
    private val SERVICE : ApiInterface

    init {
        val okHttpClient = OkHttpClient().newBuilder()
            .connectTimeout(5, TimeUnit.SECONDS)
            .readTimeout(1, TimeUnit.SECONDS)
            .writeTimeout(1, TimeUnit.SECONDS)
            .build()
        val retrofit = Retrofit.Builder()
            .baseUrl(Config.BASE_URL)
            .client(okHttpClient)
            .addConverterFactory(MoshiConverterFactory.create())
            .build()
        SERVICE = retrofit.create(ApiInterface::class.java)
    }

    fun getServerStatus() : Call<Map<String, ServerJson>> = SERVICE.getServers()

}
```

**Comment by JakeWharton** [comment]
Let's not duplicate efforts into investigating. Closing in favor of https://github.com/square/okhttp/issues/6486
