### ISSUE TITLE
retrofit loading issue

### ISSUE THREAD

**Issue by abservetechTech** [square/retrofit#3506]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by abservetechTech** [comment]
when retrofit api request send to backend , but that request is not received to backend  .
our retrofit client console shows that the request sent to the backend, 
i am using latest retrofit client gradle below
   implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'com.google.code.gson:gson:2.8.5'

i dont know what is the issue , same code working fine two week age right now i am facing this kind of issue

**Comment by JakeWharton** [comment]
There is not enough information here to make this report actionable. If you believe the problem is Retrofit then we need a test case or executable sample to reproduce the behavior.
