### ISSUE TITLE
EOFException issue: okio.RealBufferedSource.require(RealBufferedSource.kt:201)

### ISSUE THREAD

**Issue by JMCMARQUES** [square/retrofit#3507]
Hello,

I've made some successful requests using Postman (for test and to verify the sent/received Objects).
However, when using Retrofit to send out the same requests, I get always the EOFException.

I found an issue here https://github.com/square/retrofit/issues/2405, that could be similar, however, since the endpoint works fine on Postman, I didn't consider it to be the same case.

I added the issue on stackoverflow previously: 
       https://stackoverflow.com/questions/65288288/retrofit2-java-io-eofexception-even-when-postman-works-fine
However there has been no feedback there.

Since the request works on Postman, it can be my code or some issue on retrofit side.

As a header, the only item that I really need to add is the bearer token which is passed correctly in the interceptor.
I added log interceptor to try and obtain additional information, seems that the requests get the success code 200.
I've tried to use Observable instead of Call and the end result is the same.

Thank you in advance,
JM

**Comment by JakeWharton** [comment]
Please provide a test case or executable sample that reproduces the problem. Otherwise it's impossible to know what factors are contributing to this behavior.
