### ISSUE TITLE
Update retrofit2 2.9.0

### ISSUE THREAD

**Issue by Arcangel1994** [square/retrofit#3509]
Update the retrofit Library to 

    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'

I had an error with retrofit and okhttp3

![Captura de Pantalla 2021-01-08 a la(s) 15 06 30 2](https://user-images.githubusercontent.com/24682559/104064326-62068880-51c3-11eb-8c5c-21008f59f003.png)

**Comment by Arcangel1994** [comment]
I think it's because of this part of the coding.

okHttpClient = OkHttpClient().newBuilder()
            .connectTimeout(60, TimeUnit.SECONDS)
            .readTimeout(60, TimeUnit.SECONDS)
            .writeTimeout(60, TimeUnit.SECONDS)
            .addInterceptor { chain ->
                val newRequest = chain.request().newBuilder()
                    .addHeader("Authorization",  "123")
                    .build()
                chain.proceed(newRequest)
            }
            .build();

        retrofit = Retrofit.Builder()
            .baseUrl("https//")
            .client(okHttpClient!!)
            .addConverterFactory(GsonConverterFactory.create())
            .build()

**Comment by JakeWharton** [comment]
TLS happens at a layer far, far below Retrofit and is not something Retrofit explicitly has control over. You would see the same exception if you made a direct request with OkHttp, as the stacktrace indicates, and thus we aren't really in a position to help with whatever this problem is at the Retrofit layer.

**Comment by SaisudhakarBhaskaruni** [comment]
does anyone know how to solve this error
 implementation 'com.squareup.retrofit2:retrofit:2.9.0'
implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
