### ISSUE TITLE
Request: add "JsonBodyParam" annotation, similar to "@Body"

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [square/retrofit#3522]
What kind of issue is this?
 - [ V] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I have to work with a server that each function in the interface I create has a Json as a body.
This means that for each, instead of something like that:

```kt
interface SomeInterface {
           @POST("first_launch") fun sendFirstLaunch(
            @Path("referral_code") referralCode: String?,
            @Path("referral_source") referralSource: String?): Call<BaseDCResponse>
}
```

I have to create a class that will hold those parameters, as such:

```kt
interface SomeInterface {
    class SendFirstLaunchRequest(@Path("referral_code") val referralCode: String?,
        @Path("referral_source") val referralSource: String?)

    @POST("first_launch") fun sendFirstLaunch(
        @Body body: SendFirstLaunchRequest): Call<BaseDCResponse>
}
```

Can you please offer a way to avoid the creation of the classes, one for each case we have @Body ? 
Maybe in the above case, it could be:

```kt
interface SomeInterface {
           @POST("first_launch") fun sendFirstLaunch(
            @JsonBodyParam("referral_code") referralCode: String?,
            @JsonBodyParam("referral_source") referralSource: String?): Call<BaseDCResponse>
}
```

Or something?

**Comment by JakeWharton** [comment]
Retrofit is agnostic to serialization formats so there is no way to have this work. The library passes the `@Body` instance and its type to the chosen converter which is responsible for turning it into a `RequestBody`. Retrofit does not participate in this process at all.

You could potentially implement this if we add support for #2890, but I wouldn't hold my breath for it.

The class is the right way to go and is pretty standard practice.

**Comment by AndroidDeveloperLB** [comment]
You are right.
Is it possible though for me to make a customized annotation, like on the link you've provided, that I could still put it the way I've shown?
Do you think it's a lot of time?
I never developed anything that is based on annotations...
Could Retrofit allow us to parse the annotations that it doesn't support, and let us choose what to do with them (changing the body in this case) ?

**Comment by JakeWharton** [comment]
That is what the linked issue is for, and it is not currently implemented.

**Comment by AndroidDeveloperLB** [comment]
@JakeWharton OK sorry for that. I'm not an expert in Retrofit and thus wasn't sure I understood well what's written there. 
Do you think that theoretically it's possible?
Please do consider this though. Could be nice.

**Comment by JakeWharton** [comment]
Sure, it would be possible for someone to write support for that if we implemented that linked issue. Retrofit itself will never ship something like that, though, because it's far too specific and inflexible in the general case. It's a perfect thing for a mixin library, not the core.

**Comment by AndroidDeveloperLB** [comment]
@JakeWharton Will a general solution be possible, or just a sample of how it's done, so that others could do it too based on their requirements?

**Comment by JakeWharton** [comment]
I'm not sure what you're asking. Like I said, the linked issue is not implemented and we currently have no plans to implement it meaning you cannot build something like this today.

**Comment by AndroidDeveloperLB** [comment]
I mean that there are 2 ways to handle it:
1. Providing just what I wrote, of a Json as a body.
2. Providing a general solution, that will allow developers to have what they need. This might be that they could create an annotation, for example, that Retrofit will be able to handle.
