### ISSUE TITLE
SSL handshake aborted, Connection reset by peer

### ISSUE THREAD

**Issue by rashel007** [square/retrofit#3526]
I am using retrofit version  2.6.0 and getting this issue while making network call in pre lollipop device. Previously using 2.5.0 which working fine.

`02-27 01:29:00.326 3513-3513/com.obhai W/System.err: javax.net.ssl.SSLException: SSL handshake aborted: ssl=0xb9aa24c0: I/O error during system call, Connection reset by peer
02-27 01:29:00.326 3513-3513/com.obhai W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
02-27 01:29:00.326 3513-3513/com.obhai W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:405)
02-27 01:29:00.326 3513-3513/com.obhai W/System.err:     at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:319)
02-27 01:29:00.326 3513-3513/com.obhai W/System.err:     at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:283)
02-27 01:29:00.326 3513-3513/com.obhai W/System.err:     at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:168)
02-27 01:29:00.326 3513-3513/com.obhai W/System.err:     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
02-27 01:29:00.326 3513-3513/com.obhai W/System.err:     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
02-27 01:29:00.326 3513-3513/com.obhai W/System.err:     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
02-27 01:29:00.326 3513-3513/com.obhai W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
02-27 01:29:00.326 3513-3513/com.obhai W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
02-27 01:29:00.326 3513-3513/com.obhai W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
02-27 01:29:00.326 3513-3513/com.obhai W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
02-27 01:29:00.326 3513-3513/com.obhai W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
02-27 01:29:00.326 3513-3513/com.obhai W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
02-27 01:29:00.326 3513-3513/com.obhai W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
02-27 01:29:00.326 3513-3513/com.obhai W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
02-27 01:29:00.336 3513-3513/com.obhai W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
02-27 01:29:00.336 3513-3513/com.obhai W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
02-27 01:29:00.336 3513-3513/com.obhai W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
02-27 01:29:00.336 3513-3513/com.obhai W/System.err:     at com.ihsanbal.logging.LoggingInterceptor.intercept(LoggingInterceptor.java:99)
02-27 01:29:00.336 3513-3513/com.obhai W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
02-27 01:29:00.336 3513-3513/com.obhai W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
02-27 01:29:00.336 3513-3513/com.obhai W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
02-27 01:29:00.336 3513-3513/com.obhai W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
02-27 01:29:00.336 3513-3513/com.obhai W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
02-27 01:29:00.336 3513-3513/com.obhai W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-27 01:29:00.336 3513-3513/com.obhai W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-27 01:29:00.336 3513-3513/com.obhai W/System.err:     at java.lang.Thread.run(Thread.java:841)`

**Comment by JakeWharton** [comment]
This happens at a layer far below Retrofit. We do not affect this in any way. It's more likely OkHttp, or how it talks to the platform. You can use the `dependencies` task to see how the OkHttp transitive dependency is changing when you change the Retrofit version.

Put another way, you can stay on Retrofit 2.5 and manually upgrade OkHttp and you should see the same change in behavior. This is because Retrofit isn't the cause–we merely ask OkHttp to perform a request on our behalf.
