### ISSUE TITLE
The request body did not contain the specified number of bytes. Got 0, expected 1,101 

### ISSUE THREAD

**Issue by abpatel97** [square/retrofit#3531]
i am sending string body in retrofit but getting timeout excption everytime
i scrap request using scrapper then i got below line:
The request body did not contain the specified number of bytes. Got 0, expected 1,101

What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by JakeWharton** [comment]
Can you express the problem as a reproducing example or a failing test case? You haven't provided any information to accurately understand what you are doing such that an attempt can be made to figure out how to resolve it.
