### ISSUE TITLE
Possible issue with requests/responses when using with obfuscation of Android-library

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [square/retrofit#3534]
What kind of issue is this?
 - [ V] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

I actually don't know if it's a bug or a question, but it seems similar to this:
https://github.com/square/retrofit/issues/3503

I have made an Android-library module that I was required to obfuscate. It has some classes in requests and responses as Json inside.

Example:

gradle files:

```
    ext.kotlin_version = "1.4.31"
...
    classpath 'com.android.tools.build:gradle:4.1.2'
...
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
```

```kt
internal interface SomeInterface{
    @POST("register")
    fun register(@Body request: RegisterRequest): Call<RegisterResponse>
}
```

```kt
@Keep
internal class DCRegisterUserResponse : BaseDCResponse() {
    @SerializedName("response_token") val responseToken: String = ""
}
```

```kt
@Keep
internal class RegisterRequest(
    @SerializedName("request_token") val requestToken: String)
```

Note that the fields are not always just strings. They can be simple objects too that I use with SerializedName for their fields.

Without the annotation of "@Keep" (which I got this solution here: https://stackoverflow.com/a/63824377/878126 ) , it fails to have the proper request and/or response.
Only with it, it works fine. I already tried to use "data class" and "var" instead of "val", thinking those might help.

Is it a valid solution to use this annotation? Is there a better way?
I ask because I've noticed that the obfuscation completely ignores these classes, so it's not just the server value for these fields that stays the same, but also the class name, fields and functions that stay exactly the same.

I didn't see this mentioned on the Retrofit docs. In fact I saw that it says it handles Proguard rules automatically anyway.

**Comment by AndroidDeveloperLB** [comment]
I think the best way to handle it is as such:

https://stackoverflow.com/a/66670232/878126

No idea though how this could be fixed on library level. Maybe have an annotation like "@Keep" that will keep the class and its stuff, but still change the names (obfuscate)

**Comment by AndroidDeveloperLB** [comment]
For now I've put all of these special classes into the same package name, and used the Proguard rule I wrote (`-keep,allowobfuscation class com.your_library.rest_objects.** { *; }`) .

If anyone can tell me of a better solution, please do. If possible to document this, please consider adding it somewhere to the docs. If there is a way for the library to somehow do it automatically, please consider doing it (though I think it might not be possible, sadly).

**Comment by JakeWharton** [comment]
This seems to be a question about Gson and how it handles binding to JSON when obfuscating your models. Retrofit is not involved in that. If the Java field is renamed then you have to use an annotation to specify the real name.

**Comment by AndroidDeveloperLB** [comment]
@JakeWharton So you say that maybe it was enough for Proguard rules to be applied only for the classes with Gson in them?
Does Retrofit take care of the rest, of its own classes?

**Comment by JakeWharton** [comment]
Retrofit takes care of only the contents of the service interface. For serialization and deserialization of the request and response body, that is up to your chosen serialization library which, in this case, appears to be Gson. It will need its own rules if they don't ship any within the library.

**Comment by Endeavour233** [comment]
> For now I've put all of these special classes into the same package name, and used the Proguard rule I wrote (`-keep,allowobfuscation class com.your_library.rest_objects.** { *; }`) .
> 
> If anyone can tell me of a better solution, please do. If possible to document this, please consider adding it somewhere to the docs. If there is a way for the library to somehow do it automatically, please consider doing it (though I think it might not be possible, sadly).

I think it's because annotation `@Serializedname` does not work well with R8(according to the second and the third highly voted answers of this discussion https://stackoverflow.com/questions/56142150/fatal-exception-java-lang-nullpointerexception-in-release-build/56149162#56149162). And personally, I prefer the solution mentioned there: add `-keepclassmembers,allowobfuscation class * {
    @com.google.gson.annotations.SerializedName <fields>;
  }
-keep,allowobfuscation @interface com.google.gson.annotations.SerializedName` to proguard-rules

**Comment by AndroidDeveloperLB** [comment]
@Endeavour233 This is a bit different from what you wrote.
There it says:

```
# Prevent R8 from leaving Data object members always null
-keepclassmembers,allowobfuscation class * {
  @com.google.gson.annotations.SerializedName <fields>;
}
```

And you wrote:

```
-keepclassmembers,allowobfuscation class * { @com.google.gson.annotations.SerializedName <fields>; }
-keep,allowobfuscation @interface com.google.gson.annotations.SerializedName
```

Perhaps you refer to this:

https://stackoverflow.com/a/57904190/878126

**Comment by Endeavour233** [comment]
> @Endeavour233 This is a bit different from what you wrote. There it says:
> 
> ```
> # Prevent R8 from leaving Data object members always null
> -keepclassmembers,allowobfuscation class * {
>   @com.google.gson.annotations.SerializedName <fields>;
> }
> ```
> 
> And you wrote:
> 
> ```
> -keepclassmembers,allowobfuscation class * { @com.google.gson.annotations.SerializedName <fields>; }
> -keep,allowobfuscation @interface com.google.gson.annotations.SerializedName
> ```
> 
> Perhaps you refer to this:
> 
> https://stackoverflow.com/a/57904190/878126

yes! and I think the answer (which was 10 voted) below the one I referred to is also quite helpful.

**Comment by AndroidDeveloperLB** [comment]
@Endeavour233 So you suggest the bit longer one, with the link I've put, right?

I still think such a thing should be mentioned somewhere officially. 
It's not nice to find such things only on StackOverflow....

**Comment by Endeavour233** [comment]
> @Endeavour233 So you suggest the bit longer one, with the link I've put, right?
> 
> I still think such a thing should be mentioned somewhere officially. It's not nice to find such things only on StackOverflow....

yes, to be on the safe side, I prefer the longer one , which has an extra rule to keep the annotation `@Serializedname` except for those fields annotated by `@Serializedname`. (And to be honest, I know little about obfuscation. I just want to be as safe as possible (-;) As for your suggestion that this should be mentioned officially. I think since `GsonConverterFactory` is not a built-in or default ConverterFactory of `retrofit` and the cause of this issue is the incompatibility between R8 and Gson, not mentioning this officially in `retrofit` documentations is reasonable. (Though, I'll pretty appreciate it if it's mentioned, because we typically use `retrofit` with `GsonConverterFactory`)
