### ISSUE TITLE
Bump Jackson version to at least 2.12 to support serialization and de-serialization of records

### ISSUE THREAD

**Issue by DavidTheProgrammer** [square/retrofit#3546]
What kind of issue is this?

 - [ ] Question.
-  [ ] Bug report.
- [x] Feature Request.

I'm using java `records` for requests to external services and unfortunately the version of Jackson in the library does not support record serialization. The functionality was added in the Jackson library and the discussion can be found on [this thread](https://github.com/FasterXML/jackson-future-ideas/issues/46#issuecomment-678634274). Can we update the lib so we can use the convertor natively to serialize and de-serialize records.

**Comment by JakeWharton** [comment]
You can add a direct dependency on the version of Jackson you need. Your build system will correctly only resolve the newer one.

You're free to send a PR to update Retrofit's version, but we do not make releases for version bumps.

**Comment by JakeWharton** [comment]
Closing since there's no action to take on our side

**Comment by DavidTheProgrammer** [comment]
> You can add a direct dependency on the version of Jackson you need. Your build system will correctly only resolve the newer one.
> 
> You're free to send a PR to update Retrofit's version, but we do not make releases for version bumps.

Thanks so much for this. I'm super new Java, I wasn't sure how the build would resolve the dependencies. Turns out just adding the version I want to my `build.gradle` works perfectly! Apologies for the no-op issue and thank you for the guidance.
