### ISSUE TITLE
after OkHttpClient.Builder.build()  is executed ,can I add/remove  a intercept ?

### ISSUE THREAD

**Issue by onunix** [square/retrofit#3560]
after OkHttpClient.Builder.build()  is executed ,can I add/remove  a intercept ?

 httpClientBuilder = new OkHttpClient.Builder();       
httpClientBuilder.addInterceptor(getHttpLoggingInterceptor());
httpClientBuilder.build()

then user press a button,and I want to add another intercept or remove a intercept. I don't want to destroy httpClientBuilder or  new another httpClientBuilder  ,   how can I  I add/remove  a intercept ?

**Comment by JakeWharton** [comment]
No, you cannot. But you can implement your conditional logic inside of an interceptor that is always available to choose whether to apply some behavior or not.
