### ISSUE TITLE
Support kotlin.Nothing in place of java.lang.Void as type parameter for Call objects whose response is to be ignored

### ISSUE THREAD

**Issue by stoyicker** [square/retrofit#3561]
What kind of issue is this?

 - [x] Feature Request.

As of 2.9.0, declaring an interface with a method returning a `Call<Void>` will work as expected, but a `Call<Nothing>` (obviously with the Kotlin stdlib in the classpath) will cause the following exception:

```
java.lang.IllegalArgumentException: Unable to create call adapter for interface retrofit2.Call for method YourInterface.yourMethod at 

retrofit2.Utils.methodError(Utils.java:54) at

retrofit2.HttpServiceMethod.createCallAdapter(HttpServiceMethod.java:116) at 

retrofit2.HttpServiceMethod.parseAnnotations(HttpServiceMethod.java:67) at 

retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:39) at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:202) at 

retrofit2.Retrofit.validateServiceInterface(Retrofit.java:189) at 

retrofit2.Retrofit.create(Retrofit.java:141)
```

While I understand that the Kotlin "equivalent" to Java's `Void` is `Unit`, I believe using `Nothing` for the type of the body of a response that never has a body fits the documentation for `Nothing` perfectly and hence I'd expect this case to work.

**Comment by JakeWharton** [comment]
`Nothing` is not a real type so Kotlin will use a raw type (i.e., `Call` without a type parameter). We could treat that as meaning the same as `Call<Nothing>`, but it also means that in Java you could write a bare `Call` and Retrofit would still work (whereas today it correctly throws an exception.

Is supporting `Unit` enough here?

**Comment by stoyicker** [comment]
Yeah I'd say it is. That makes sense, thanks
