### ISSUE TITLE
Use refreshVersions?

### ISSUE THREAD

**Issue by jmfayard** [square/retrofit#3565]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.
       
----

Hello, I'm the author of refreshVersions, a Gradle plugin whose mission is to make adding and updating dependencies faster, more convenient and less error-prone

See [https://jmfayard.github.io/refreshVersions/](https://jmfayard.github.io/refreshVersions/)

I'm currently working on improving how we migrate existing projects, and to test that it works on real world, I prefer to try migrating existing open-source projects.
Would you be interested in having a pull request adding refreshVersions to retrofit?

**Comment by JakeWharton** [comment]
I think that if we were going to migrate to something the obvious choice is Gradle's version catalogs rather than a third-party solution. Is there a reason to prefer your tool?

Also I'm pretty sure dependabot works today on the string-based solution that we use which is another reason to not migrate.

I think the general problem is we don't really need a tool like this. Our dependencies are generally kept to a minimum unless a CVE or feature requires a bump. And we simply don't track that many in the first place.

**Comment by jmfayard** [comment]
> I think the general problem is we don't really need a tool like this. Our dependencies are generally kept to a minimum 

That's good!

> I think that if we were going to migrate to something the obvious choice is Gradle's version catalogs rather than a third-party solution. Is there a reason to prefer your tool?

Actually they work well together. 
The versions catalog provide typesafe accessors (like the buildSrc but better)
RefreshVersions take care of managing dependency versions and finding available updates (like Ben Manes's versions plugin but better)
I have added (but not release yet) a task called `refreshVersionsCatalog` that generates automatically a versions catalog file for an existing file so that it doesn't have to be written manually
