### ISSUE TITLE
Call not available for import

### ISSUE THREAD

**Issue by GaneshShetty951** [square/retrofit#3570]
I have imported retrofit2 to my App. But still, I can't import Call<>. If I try to write import statement manually also retrofit2.Call is showing errors.

```import 'com.spuareup.retrofit2:retrofit:2.9.0'```

**Comment by JakeWharton** [comment]
Do you have a sample project where I can reproduce this and see what's going on?

**Comment by JakeWharton** [comment]
Try invalidate caches and restart in the IDE
