### ISSUE TITLE
TypeToken not found

### ISSUE THREAD

**Issue by Softkeydel** [square/retrofit#3571]
`import com.google.gson.reflect.TypeToken`

 not found in com.squareup.retrofit2:converter-gson:2.7.1 
Without adding com.google.code.gson:gson:2.8.6 is it possible to access TypeToken

Please help

**Comment by JakeWharton** [comment]
Gson is a transitive dependency of converter-gson as can be seen in its pom: https://search.maven.org/artifact/com.squareup.retrofit2/converter-gson/2.9.0/jar

Adding one to your build system should add both. You should not need to specify both in order to have access to `TypeToken` or any other Gson type.

I'm not really sure what to tell you beyond that... if you have a minimal sample project that reproduces the problem I can take a look.

**Comment by Softkeydel** [comment]
@JakeWharton 
I'm consuming json data like
`{
  "status": "1",
  "message": "all feedback",
  "data": [
    {
      "id": "10",
      "job_id": "124",
      "service_provider_id": "7",
      "service_id": "10",
      "user_id": "8",
      "rating": "3",
      "feedback": "[{\"checked\":true,\"created_at\":\"2021-05-15 13:57:39\",\"id\":\"5\",\"question\":\"test3_3\",\"rating\":\"3\",\"updated_at\":\"2021-05-15 13:57:39\"}]",
      "comment": "Good",
      "created_at": "2021-06-06 08:52:41",
      "updated_at": "2021-06-06 08:52:41",
      "user_full_name": "Customer",
      "user_image": "6fc934bb259e34bc1bcdbecfaa78694c.png",
      "user_phone_no": "8145268350"
    },
    {
      "id": "9",
      "job_id": "119",
      "service_provider_id": "7",
      "service_id": "10",
      "user_id": "8",
      "rating": "1",
      "feedback": "[{\"checked\":true,\"created_at\":\"2021-05-15 13:56:40\",\"id\":\"2\",\"question\":\"test1_2\",\"rating\":\"1\",\"updated_at\":\"2021-05-15 13:56:40\"}]",
      "comment": "Good",
      "created_at": "2021-06-06 06:43:13",
      "updated_at": "2021-06-06 06:43:13",
      "user_full_name": "Customer",
      "user_image": "6fc934bb259e34bc1bcdbecfaa78694c.png",
      "user_phone_no": "8145268350"
    },
    {
      "id": "8",
      "job_id": "118",
      "service_provider_id": "7",
      "service_id": "10",
      "user_id": "8",
      "rating": "2",
      "feedback": "[{\"checked\":true,\"created_at\":\"2021-05-15 13:58:00\",\"id\":\"6\",\"question\":\"test3_1\",\"rating\":\"2\",\"updated_at\":\"2021-05-15 13:58:00\"}]",
      "comment": "Good",
      "created_at": "2021-06-05 18:13:40",
      "updated_at": "2021-06-05 18:13:40",
      "user_full_name": "Customer",
      "user_image": "6fc934bb259e34bc1bcdbecfaa78694c.png",
      "user_phone_no": "8145268350"
    },
    {
      "id": "7",
      "job_id": "108",
      "service_provider_id": "7",
      "service_id": "10",
      "user_id": "8",
      "rating": "1",
      "feedback": "[{\"checked\":true,\"created_at\":\"2021-05-15 13:56:14\",\"id\":\"1\",\"question\":\"test1_1\",\"rating\":\"1\",\"updated_at\":\"2021-05-15 13:56:14\"}]",
      "comment": "Good",
      "created_at": "2021-06-05 18:11:29",
      "updated_at": "2021-06-05 18:11:29",
      "user_full_name": "Customer",
      "user_image": "6fc934bb259e34bc1bcdbecfaa78694c.png",
      "user_phone_no": "8145268350"
    }
  ]
}`

I need to convert the feedback as a list of objects
my pojo is

`public class FeedbackInfo  {

    @SerializedName("id")
    @Expose
    private String id;
    @SerializedName("job_id")
    @Expose
    private String jobId;
    @SerializedName("service_provider_id")
    @Expose
    private String serviceProviderId;
    @SerializedName("service_id")
    @Expose
    private String serviceId;
    @SerializedName("user_id")
    @Expose
    private String userId;
    @SerializedName("rating")
    @Expose
    private String rating;
    @SerializedName("feedback")
    @Expose
    private String feedback;
    @SerializedName("comment")
    @Expose
    private String comment;
    @SerializedName("created_at")
    @Expose
    private String createdAt;
    @SerializedName("updated_at")
    @Expose
    private String updatedAt;
    @SerializedName("user_full_name")
    @Expose
    private String userFullName;
    @SerializedName("user_image")
    @Expose
    private String userImage;
    @SerializedName("user_phone_no")
    @Expose
    private String userPhoneNo;


    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getJobId() {
        return jobId;
    }

    public void setJobId(String jobId) {
        this.jobId = jobId;
    }

    public String getServiceProviderId() {
        return serviceProviderId;
    }

    public void setServiceProviderId(String serviceProviderId) {
        this.serviceProviderId = serviceProviderId;
    }

    public String getServiceId() {
        return serviceId;
    }

    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getRating() {
        return rating;
    }

    public void setRating(String rating) {
        this.rating = rating;
    }

    public List<Feedback> getFeedback() {
        Type type = new TypeToken<List<Feedback>>(){}.getType();
        List<Feedback> feedbacks = new Gson().fromJson(this.feedback,type);
        return feedbacks;
    }

    public void setFeedback(String feedback) {
        this.feedback = feedback;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    public String getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }

    public String getUserFullName() {
        return userFullName;
    }

    public void setUserFullName(String userFullName) {
        this.userFullName = userFullName;
    }

    public String getUserImage() {
        return userImage;
    }

    public void setUserImage(String userImage) {
        this.userImage = userImage;
    }

    public String getUserPhoneNo() {
        return userPhoneNo;
    }

    public void setUserPhoneNo(String userPhoneNo) {
        this.userPhoneNo = userPhoneNo;
    }


}
`

**Comment by JakeWharton** [comment]
That is not what I offered to help with.

**Comment by Softkeydel** [comment]
@JakeWharton 
could you please tell me what kinda sample project you want?

is there any possible solution without using jar?

**Comment by JakeWharton** [comment]
If you are using jars then you have to obtain all the transitive dependencies such as Gson yourself. If you are using a build system like Gradle or Maven (as everyone should) then your build system will transitively pull the Gson dependency.

If you have a sample project that shows somehow that a dependency on our Gson converter is not automatically pulling the transitive dependency in your build system I would be interested in looking at it. Otherwise it sounds like you have general Java build questions and general Gson usage questions which are more appropriate for places like StackOverflow and are not specific to the use of Retrofit.
