### ISSUE TITLE
retrofit返回<!DOCTYPE html>

### ISSUE THREAD

**Issue by ldmgithub** [square/retrofit#3573]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

网络从有网络到网络请求超时之后再到有网络之后请求不到服务器，但是返回以下内容

<!DOCTYPE html>
<html id="html">
<head><meta name="csrf_token" content="PXqnrwd0LSv49ZhSgZUhaPWG90m6pwzQ">
<meta name="csrf_token" content="1GWGTyofidc0RH1ndqxp1KluEud1Eh9Z">

<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<meta name="format-detection" content="telephone=no"/>
<meta http-equiv='Pragma' content='no-cache'/>
<meta http-equiv="Cache-Control" content="no-cache, must-revalidate"/>
<meta name="description" content="emui webui 6.0"/>
<meta name="author" content="emui webui 6.0"/>
<link

**Comment by JakeWharton** [comment]
As far as I can tell, you're asking about receiving that content. It's possible there's a captive portal that returns HTML for all requests. Ultimately there's nothing Retrofit can do here. If you made the same HTTP requests with raw OkHttp you'd see the same behavior.

**Comment by ldmgithub** [comment]
ok，thanks
