### ISSUE TITLE
Add a link to kotlin examples to the Website.

### ISSUE THREAD

**Issue by gyrraf** [square/retrofit#3575]
What kind of issue is this?

 - [ ] Feature Request.

For someone looking at the Website there is no way to know that retrofit supports kotlins `suspend` keyword.

**Comment by mrlem** [comment]
This is now documented on the [main page](https://square.github.io/retrofit/), with a straight-forward example, in section "API declaration / Kotlin support:
```kotlin
@GET("users")
suspend fun getUser(): Response<User>
```

So I guess this issue could be closed.
