### ISSUE TITLE
V2.10 is overdue for release

### ISSUE THREAD

**Issue by clydebarrow** [square/retrofit#3585]
The last stable release was 2.9.0 which is now over a year old. 2.10 has changes I rely on, so I'm having to use the 2.10.0-SNAPSHOT which has the potential for things to break unexpectedly, since it can change without notice.

Is there a timeframe for releasing 2.10.0?

**Comment by JakeWharton** [comment]
What changes do you rely on?

**Comment by clydebarrow** [comment]
#3424

**Comment by JakeWharton** [comment]
I'm going to try and land a few changes to do a release soon. Keep in mind RoboVM support is best-effort and not official.

**Comment by clydebarrow** [comment]
Sure, and that best effort is much appreciated.

**Comment by Dkhusainov** [comment]
Also #3563, since Retrofit + AGP 7.0 + `android.enableR8.fullMode` is broken now.
https://issuetracker.google.com/issues/188703877

**Comment by JakeWharton** [comment]
Yep, more and more things are landing, but there's a few more to get to. Going to close since we don't track releases as issues.
