### ISSUE TITLE
Avoiding deadlocks within okhttp interceptors/authenticator when using retrofit with coroutines adapter

### ISSUE THREAD

**Issue by ursusursus** [square/retrofit#3587]
Hi,
I used retrofit+okhttp+rxjava, now migrated to coroutines. These have implicit support and from what I know the coroutine adapter is hardcoded to use okhttp's thread dispatcher (not the caller context, as it was possible with rxjava; the async boolean parameter)

What happens now is that, there are cases where requests need to be initiated from within okhttp's interceptors/authenticator; which are ran on okhttp's threads

From what I gather, that threadpool is limited, therefore calling new request when the thread pool is maxed out, will lead to deadlock

(Just for clarification, the pseudo-codey situation is this)

```
fun OkhttpAuthenticator.authenticate() {
	...
	synchronized(this) {
		runBlocking { retrofitService.suspendingRefreshTokens() }<--- 
		...
	}
}
```

What is the recommended solution for this?

Having the auth calls declared as synchronous in retrofit?
Drive auth layers via a custom (separate) dispatcher?
Make dispatcher smart enought not to hop from okhttp thread to okhttp thread?
Is there option to not use okhttp's threadpools as it was in rxjava?

I know this might be out of retrofit scope, but I believe many implementations in the wild have this issue

**Comment by ywett02** [comment]
Hey!
I understand that the issue is already closed but I've run into the same issue recently. Were you able to figure out any solution?

**Comment by ursusursus** [comment]
For the calls which needed be called from within okhttp thread I kept them blocking, i.e. no threading applied.
Then for convenience I wrapped it with this

```
/** Due to the fact that native retrofit coroutines support
 * runs request on OkHttp thread pool, which is hard limited.
 * Refreshing tokens happens from within a Authenticator,
 * which is already run on OkHttp thread, thus resulting in
 * OkHttp thread requesting to spawn another OkHttp thread,
 * which leads to deadlock.
 * Workaround was either run all such requests synchronously,
 * or, as here, simply run them on IO dispatcher, which is
 * unbounded.*/
private suspend fun <T> Call<T>.suspendExecute(): Response<T> {
    return withContext(dispatcherProvider.io) {
        suspendCancellableCoroutine { continuation ->
            continuation.invokeOnCancellation {
                cancel()
            }

            try {
                val response: Response<T> = execute()
                continuation.resume(response)
            } catch (ex: Exception) {
                continuation.resumeWithException(ex)
            }
        }
    }
}
```

(btw nazdar)

**Comment by ywett02** [comment]
Thanks (dakujem!) for the inside! 🙏 

I would like to know where and why the potential deadlock happens. If I am not wrong, the thread pool is unbounded, so there should be enough capacity. 🤔 

What I found was that we exceeded `maxRequestsPerHost` number in `okhttp3.Dispatcher.promoteAndExecute()`. Therefore, I guess, the refresh token request was just thrown away and the authenticator was just waiting forever for the response.
```
if (asyncCall.callsPerHost.get() >= this.maxRequestsPerHost) continue // Host max capacity.
```

**Comment by ursusursus** [comment]
I found the okhttp threadpool to be hard limited

**Comment by ywett02** [comment]
I deduced it from seeing the following in logs:
![image](https://user-images.githubusercontent.com/14801604/148427324-274fb561-1826-48a0-8213-77c0eae87dde.png)

Anyway, I am not any okhttp or threads expert. Maybe I was not looking at the correct place.

**Comment by ywett02** [comment]
Increasing `maxRequestsPerHost` did not help. Apparently, it was not a problem.

**Comment by nikhilbansal97** [comment]
@ursusursus How does the `suspendExecute()` function implementation solve the issue? It is essentially a `suspend` function that executes the Retrofit call in an unbounded IO dispatcher. To call it from `Authenticator.authenticate()`, are you using `runBlocking`? If yes, that would still block the OkHttp thread, right? Or am I missing something here?

From what I understood, the implementation of `Authenticator.authenticate()` function should be `synchronized(this)` and inside it, we can call the non-suspending Retrofit interface call that returns `Call<T>`. That way, even if multiple concurrent requests get 401 and try to refresh, only 1 thread will refresh token and others will wait and will eventually retry with new token.

Ref: [Handling Token Expiration in Retrofit: Automatic Token Refresh with OkHttp](https://www.droidcon.com/2025/02/27/handling-token-expiration-in-retrofit-automatic-token-refresh-with-okhttp/)
