### ISSUE TITLE
Why does retrofit not allow sending images to a server without saving the image as a file locally?

### ISSUE THREAD

**Issue by iAmJuan550** [square/retrofit#3592]
What kind of issue is this?

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I want to send an image to a flask server. However, it seems I always have to save it locally to my device before doing that. Why don't you guys allow us to convert a bitmap to a byte array and just send that to the server?

**Comment by JakeWharton** [comment]
You are free to send a byte array by using `RequestBody` and supplying its content type. Retrofit does not care or enforce where your data comes from.
