### ISSUE TITLE
v2.9.0, retrofit2/http package (with annotations) is empty

### ISSUE THREAD

**Issue by ardovic** [square/retrofit#3594]
Using com.squareup.retrofit2:retrofit:2.9.0 in Android Studio project with gradle: 7.0.0, kotlin: 1.5.10

retrofit2/http package in external libraries is empty, resulting in non resolved annotations GET, POST, Body etc.

Project builds and I'm able to launch the app.

Does not happen on v2.8.2 or lower.

**Comment by JakeWharton** [comment]
Maybe try invalidate caches and restart? If it builds on the command line then it's not specifically a problem with Retrofit since otherwise the build would fail.

**Comment by CakeWalker1337** [comment]
Actually I have the same issue:( invalidate caches and restart doesn't work, but decreasing the version from 2.9.0 to 2.8.2 works fine. No idea what's going on, but I rechecked all project settings and didn't see anything suspicious.
