### ISSUE TITLE
The version 2.9.0 is one year old so when would expected next release?

### ISSUE THREAD

**Issue by tyagi-bhoopesh** [square/retrofit#3611]
One of my android project, I am using retrofit 2.9.0 dependency. It was release in May 2020 and its one year old release now. In our contract of project , we don't need more than one year of any dependency. Please let me know when would you like to release of retrofit?

**Comment by JakeWharton** [comment]
We will release when it's ready. A time-based policy is unwise.

**Comment by tyagi-bhoopesh** [comment]
@JakeWharton If you don't release next version then we will loose the retrofit in our project, it means that we have to remove your retrofit and try other alternates of retrofit dependency.

**Comment by JakeWharton** [comment]
If that's what your policy demands then that is what you have to do. We do not release based on time.

**Comment by jylin** [comment]
The released version of retrofit is now more than a year old, and there are other concerns like dependencies it uses being out of date too (subject to potential security vulnerabilities or bugs). For example, the OkHttp version that's included still comes with the non-daemon threads bug (though that's easy to fix by adding an explicit dependency on OkHttp), which causes the process to not shutdown on exit.

Any chance we could get a release soon to rollup and release all the changes that have been accumulated as well as pull in updated dependencies?
