### ISSUE TITLE
Missing documentation and samples for Kotlin coroutines

### ISSUE THREAD

**Issue by bartek-wesolowski** [square/retrofit#3627]
There is no documentation and samples showing how to use Retrofit with Kotlin coroutines. In particular, there should be information regarding:
- the dispatcher used with Retrofit calls and whether you should explicitly change it to Dispatchers.IO
- exception handling - what exceptions can be thrown and when; how to handle HTTP status codes

**Comment by JakeWharton** [comment]
Dupe of #3263
