### ISSUE TITLE
[Feature Request] Is there anyway I can Build the url before making the call? Should be added as a new functionality if not already available.

### ISSUE THREAD

**Issue by shahwaiz90** [square/retrofit#3628]
What kind of issue is this?

 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.
 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

**Comment by shahwaiz90** [comment]
updated label

**Comment by JakeWharton** [comment]
If you are using Retrofit's `Call` you can get the backing OkHttp `Request` which has the URL available. If you are using any of the adapters the URL is not exposed in any way.

**Comment by shahwaiz90** [comment]
yes you are right. but i have to use retrofit2.Response<> in order to get the errorBody and less boiler plate code. 
Means, without call can't use url object, ok thank you!

i added a stackoverflow question here as well, if you like to see the answer i posted.

https://stackoverflow.com/questions/68997554/in-retrofit-can-i-get-the-endpoint-uri-with-all-dynamic-values-query-params-bef/68998550#68998550
