### ISSUE TITLE
isSuccessful is not trigger

### ISSUE THREAD

**Issue by remonmmitsoft** [square/retrofit#3631]
![Capture](https://user-images.githubusercontent.com/90492379/133965350-c2847337-2e41-4b22-99b0-327b136e6111.PNG)
![Capture2](https://user-images.githubusercontent.com/90492379/133965403-f93ca94c-9cbb-4479-a994-217d7b0b2653.PNG)
![Capture3](https://user-images.githubusercontent.com/90492379/133965406-ae651916-97d1-48ae-843e-e378074456ff.PNG)

**Comment by JakeWharton** [comment]
Can you express this as a failing test case or executable sample? As is I have no way to reproduce what you are seeing.

**Comment by otnieldocs** [comment]
can you check if `Withdraw_response` object maps the right attribute from your response?
