### ISSUE TITLE
Make timeout configurable per method.

### ISSUE THREAD

**Issue by kazuki-ma** [square/retrofit#3639]
What kind of issue is this?

 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

----

There is common case that we want set short timeout for GET API and long timeout for (specific) POST API.

Now, retrofit don't have timeout mechanism and only way is set OkHttp's timeout.
But setting individual timeout per method is impossible by this way.

**Comment by MiSikora** [comment]
You can access request method type in an interceptor and set a timeout on a `Chain` object – https://square.github.io/okhttp/4.x/okhttp/okhttp3/-interceptor/-chain.

Or if you need a more granular mechanism you can create a custom annotation like `Timeout` and access it with reflection from `Invocation` in an interceptor to get the value. Code below should give you an idea on how to approach it.

https://github.com/square/retrofit/blob/061149190fd523ff63619652038cdfadd2674d54/samples/src/main/java/com/example/retrofit/InvocationMetrics.java#L46-L67

**Comment by kazuki-ma** [comment]
Oh.. That's my shame and thank you for your information.
I'm checked Retrofit builder method many times but OkHttpClient.Builder has it... Thank you!

**Comment by kazuki-ma** [comment]
Let me close the issue. I hope this information is meaningful to other Retrofit users.

Thank you again.
