### ISSUE TITLE
Static headers using interceptor and dynamic headers issue

### ISSUE THREAD

**Issue by ishaileshmishra** [square/retrofit#3641]
Question. This issue is with my dynamic header.
 
- Step 1: I have added an interceptor with having few static headers.
- Step 2: On the other hand, want to send few more headers dynamically using @header/@HeaderMap
   
   When the request completes, I check request headers like below and found that only static headers are available in the request 

checking using: 
```
`System.out.println(response.raw().request().headers());`
```

**where I can see the static headers but not the dynamic headers.**

below is the code for Interceptor to set static headers:

    public class AuthInterceptor implements Interceptor {
    
        public AuthInterceptor() {
        }
    
        protected String authtoken;
    
        public AuthInterceptor(String authtoken) {
            defaultHeader();
            this.authtoken = authtoken;
        }
    
        public void setAuthtoken(String authtoken) {
            this.authtoken = authtoken;
        }
    
        private Headers.Builder defaultHeader() {
            final String xUserAgent = Util.SDK_NAME + "/" + Util.SDK_VERSION;
            return new Headers.Builder()
                    .add("X-User-Agent", xUserAgent)
                    .add("User-Agent", Util.defaultUserAgent())
                    .add("Content-Type", "application/json");
        }
    
        public Headers.Builder addHeader(@NotNull String key, @NotNull String value) {
            defaultHeader().add(key, value);
            return defaultHeader();
        }
    
        @NotNull
        @Override
        public Response intercept(Chain chain) throws IOException {
            Request.Builder request = chain.request().newBuilder()
                    .headers(defaultHeader().build());
    
            if (this.authtoken != null) {
                request.addHeader("authtoken", this.authtoken);
            }
            return chain.proceed(request.build());
        }
    
    
    }

And Sending dynamic headers like below.
    
        @POST("stacks")
        Call<ResponseBody> create(
                @Header("organization_uid") String orgUid,
                @Body RequestBody body);

**Comment by angusholder** [comment]
This line:

    .headers(defaultHeader().build());

deletes all the existing headers in the request and replaces them with those from `defaultHeader()`, so your "organization_uid" header gets deleted.

Use `Request.Builder.header(String, String)` instead. If you only want to add the headers if they don't already exist, you can check if they exist in the request object like `chain.request().header("User-Agent") != null`

**Comment by ishaileshmishra** [comment]
Thanks, @angusholder. worked nicely
