### ISSUE TITLE
Upload Image to Server using Multipart and Request Body in Android using Kotlin

### ISSUE THREAD

**Issue by Neeraj1108Yadav** [square/retrofit#3642]
I am stuck in between a strange issue of uploading image file to server. Although I did upload file several times before, but this time I don't understand what is the issue.

I get the file path of respective file but **RequestBody** returns **null**. Below I mentioned what library I'm using.

I am using **Kotlin**, **MultiPart** and RequestBody for file upload.

```
implementation  'com.squareup.retrofit2:retrofit:2.9.0'
implementation  'com.squareup.retrofit2:converter-gson:2.9.0'
implementation  'com.squareup.okhttp3:logging-interceptor:4.9.1'

val file =  MultipartBody.Part.createFormData("key",fileName,userImage)

@Multipart
    @POST("hosiery/v1/users/register")
    suspend fun register1(@Header("Authorization") token:String, @Part("username") companyName: RequestBody,
                          @Part("email") email: RequestBody, @Part("owner_name") ownerName: RequestBody,
                          @Part("address") address: RequestBody, @Part("client_id") id: RequestBody,
                          @Part file: MultipartBody.Part?
    ) : Response<SuccessModel>

```

Below is my code which I wrote for file upload. In which you can see **GalleryCameraUtility.getImageRequestBody(imageFile) returns null for file.**

File path from mobile device **/storage/emulated/0/DCIM/Screenshots/test_image.jpg**

```
fun addNewCompany(companyName: String, email: String,imageFile: File, ownerName: String, address: String){

        val companyNameBody: RequestBody = companyName.toRequestBody("text/plain".toMediaType())
        val emailBody: RequestBody = email.toRequestBody("text/plain".toMediaType())
        val fileData: RequestBody? = GalleryCameraUtility.getImageRequestBody(imageFile)
        val ownerNameBody: RequestBody = ownerName.toRequestBody("text/plain".toMediaType())
        val addressBody: RequestBody = address.toRequestBody("text/plain".toMediaType())
        val userIdBody: RequestBody = PreferenceHelper.readUserIdPref(Constants.USER_ID).toString()
            .toRequestBody("text/plain".toMediaType())

        addCompanyRepo.addNewCompanyApi(companyNameBody, emailBody, fileData, ownerNameBody, addressBody, userIdBody)
    }


class GalleryCameraUtility {
    companion object{

        fun getImageRequestBody(sourceFile: File) : RequestBody? {
            var requestBody: RequestBody? = null
            Thread {
                val mimeType = getMimeType(sourceFile);
                if (mimeType == null) {
                    Log.e("file error", "Not able to get mime type")
                    return@Thread
                }
                try {
                    requestBody = sourceFile.path.toRequestBody("multipart/form-data".toMediaTypeOrNull())
                } catch (ex: Exception) {
                    ex.printStackTrace()
                    Log.e("File upload", "failed")
                }
            }.start()

            return requestBody;
        }

        // url = file path or whatever suitable URL you want.
        private fun getMimeType(file: File): String? {
            var type: String? = null
            val extension = MimeTypeMap.getFileExtensionFromUrl(file.path)
            if (extension != null) {
                type = MimeTypeMap.getSingleton().getMimeTypeFromExtension(extension)
            }
            return type
        }
    }
}
```

I spent so many hours on this but not able to find solution. Please help me out on this.

**Comment by faizazharr** [comment]
Me too. I followed the statement but it is still 400, it's well on swift ios but not in Kotlin

**Comment by BukT0p** [comment]
It's strange why you use issues in github instead of SO or some other dev resource, to solve this particular problem it's better to use MultipartBody.
Your API call would look like:
```
@POST("/api/user/edit")
suspend fun updateUserDetails(@Body body: MultipartBody): UserDTO
```
and to construct that body you should call it like:
```
val multipartBody = MultipartBody.Builder()
            .setType(MultipartBody.FORM)
            .addFormDataPart("firstName", fName)
            .addFormDataPart("avatarUrl", avatarFileName, avatarRequestBody)
            .build()

val userDTO = yourApi.updateUserDetails(multipartBody)
```
Also there could be other problems with your code like you should use FileProvider, etc.

**Comment by JakeWharton** [comment]
```
        fun getImageRequestBody(sourceFile: File) : RequestBody? {
            var requestBody: RequestBody? = null
            Thread {
                val mimeType = getMimeType(sourceFile);
                if (mimeType == null) {
                    Log.e("file error", "Not able to get mime type")
                    return@Thread
                }
                try {
                    requestBody = sourceFile.path.toRequestBody("multipart/form-data".toMediaTypeOrNull())
                } catch (ex: Exception) {
                    ex.printStackTrace()
                    Log.e("File upload", "failed")
                }
            }.start()

            return requestBody;
        }
```
This is a race and will 99.9% of the time result in `null` being returned from this function. The same thread which is creating the `RequestBody` should perform the network call, or at least you need a happens-before relationship to ensure the variable is initialized before performing the network call in a separate thread.

**Comment by Kundanswa** [comment]
I spent whole day but not solve path problem

**Comment by sihalohoapry** [comment]
> I spent whole day but not solve path problem

are you solved this problem?

**Comment by sihalohoapry** [comment]
> I am stuck in between a strange issue of uploading image file to server. Although I did upload file several times before, but this time I don't understand what is the issue.
> 
> I get the file path of respective file but **RequestBody** returns **null**. Below I mentioned what library I'm using.
> 
> I am using **Kotlin**, **MultiPart** and RequestBody for file upload.
> 
> ```
> implementation  'com.squareup.retrofit2:retrofit:2.9.0'
> implementation  'com.squareup.retrofit2:converter-gson:2.9.0'
> implementation  'com.squareup.okhttp3:logging-interceptor:4.9.1'
> 
> val file =  MultipartBody.Part.createFormData("key",fileName,userImage)
> 
> @Multipart
>     @POST("hosiery/v1/users/register")
>     suspend fun register1(@Header("Authorization") token:String, @Part("username") companyName: RequestBody,
>                           @Part("email") email: RequestBody, @Part("owner_name") ownerName: RequestBody,
>                           @Part("address") address: RequestBody, @Part("client_id") id: RequestBody,
>                           @Part file: MultipartBody.Part?
>     ) : Response<SuccessModel>
> ```
> 
> Below is my code which I wrote for file upload. In which you can see **GalleryCameraUtility.getImageRequestBody(imageFile) returns null for file.**
> 
> File path from mobile device **/storage/emulated/0/DCIM/Screenshots/test_image.jpg**
> 
> ```
> fun addNewCompany(companyName: String, email: String,imageFile: File, ownerName: String, address: String){
> 
>         val companyNameBody: RequestBody = companyName.toRequestBody("text/plain".toMediaType())
>         val emailBody: RequestBody = email.toRequestBody("text/plain".toMediaType())
>         val fileData: RequestBody? = GalleryCameraUtility.getImageRequestBody(imageFile)
>         val ownerNameBody: RequestBody = ownerName.toRequestBody("text/plain".toMediaType())
>         val addressBody: RequestBody = address.toRequestBody("text/plain".toMediaType())
>         val userIdBody: RequestBody = PreferenceHelper.readUserIdPref(Constants.USER_ID).toString()
>             .toRequestBody("text/plain".toMediaType())
> 
>         addCompanyRepo.addNewCompanyApi(companyNameBody, emailBody, fileData, ownerNameBody, addressBody, userIdBody)
>     }
> 
> 
> class GalleryCameraUtility {
>     companion object{
> 
>         fun getImageRequestBody(sourceFile: File) : RequestBody? {
>             var requestBody: RequestBody? = null
>             Thread {
>                 val mimeType = getMimeType(sourceFile);
>                 if (mimeType == null) {
>                     Log.e("file error", "Not able to get mime type")
>                     return@Thread
>                 }
>                 try {
>                     requestBody = sourceFile.path.toRequestBody("multipart/form-data".toMediaTypeOrNull())
>                 } catch (ex: Exception) {
>                     ex.printStackTrace()
>                     Log.e("File upload", "failed")
>                 }
>             }.start()
> 
>             return requestBody;
>         }
> 
>         // url = file path or whatever suitable URL you want.
>         private fun getMimeType(file: File): String? {
>             var type: String? = null
>             val extension = MimeTypeMap.getFileExtensionFromUrl(file.path)
>             if (extension != null) {
>                 type = MimeTypeMap.getSingleton().getMimeTypeFromExtension(extension)
>             }
>             return type
>         }
>     }
> }
> ```
> 
> I spent so many hours on this but not able to find solution. Please help me out on this.

how you fix this problem sir?
