### ISSUE TITLE
Why do not encode ‘+’  in path?

### ISSUE THREAD

**Issue by liujingxing** [square/retrofit#3653]
What kind of issue is this?

 - [x] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

## retrofit-v2.9.0

the api docs
https://github.com/square/retrofit/blob/7158698314daa138e993fac6a590ed19d78a8599/retrofit/src/main/java/retrofit2/http/Path.java#L48

```java
 @GET("/user/{name}")
 Call<ResponseBody> encoded(@Path("name") String name);

 @GET("/user/{name}")
 Call<ResponseBody> notEncoded(@Path(value="name", encoded=true) String name);
 
Calling foo.encoded("John+Doe") yields /user/John%2BDoe
whereas foo.notEncoded("John+Doe") yields /user/John+Doe.
```

https://github.com/square/retrofit/blob/fbf1225e28e2094bec35f587b8933748b705d167/retrofit/src/main/java/retrofit2/RequestBuilder.java#L133

```java
  private static String canonicalizeForPath(String input, boolean alreadyEncoded) {
    int codePoint;
    for (int i = 0, limit = input.length(); i < limit; i += Character.charCount(codePoint)) {
      codePoint = input.codePointAt(i);
      if (codePoint < 0x20
          || codePoint >= 0x7f
          || PATH_SEGMENT_ALWAYS_ENCODE_SET.indexOf(codePoint) != -1
          || (!alreadyEncoded && (codePoint == '/' || codePoint == '%'))) {
        // Slow path: the character at i requires encoding!
        Buffer out = new Buffer();
        out.writeUtf8(input, 0, i);
        canonicalizeForPath(out, input, i, limit, alreadyEncoded);
        return out.readUtf8();
      }
    }

    // Fast path: no characters required encoding.
    return input;
  }
```
The canonicalizeForPath method do not encode '+'

**Comment by JakeWharton** [comment]
What does OkHttp do?

**Comment by JakeWharton** [comment]
I wrote this test:
```java
  @Test public void whatever() {
    HttpUrl a = HttpUrl.get("https://example.com")
      .newBuilder()
      .addPathSegment("a+b")
      .build();
    assertThat(a.toString()).isEqualTo("https://example.com/a+b");

    HttpUrl b = HttpUrl.get("https://example.com")
      .newBuilder()
      .addEncodedPathSegment("a+b")
      .build();
    assertThat(b.toString()).isEqualTo("https://example.com/a+b");
  }
```
It passes with OkHttp 3.14.9, 4.12.0, and 5.0.0-alpha12.

**Comment by Zhuinden** [comment]
Interestingly, I did just run into the issue that `+` in a path parameter is not URL-encoded if you say `encoded = false`, had to use `encoded = true` and URL encode it manually.

Wildly enough, the `@Path` parameter was in generated code that did not support this, so I just had to copy the whole generated code and make edits to that. Not ideal, but at least the `+` is URL encoded now.
