### ISSUE TITLE
I got onFailure response even though got a 200 status code

### ISSUE THREAD

**Issue by zzzsound** [square/retrofit#3655]
Hi, im getting onFailure response but the status code im having is 200
![Screenshot 2021-11-08 190223](https://user-images.githubusercontent.com/93919393/140738680-71ca94a0-4b80-4601-be8b-389717b0f28c.png)

**Comment by JakeWharton** [comment]
With what exception?

**Comment by zzzsound** [comment]
> exception

Sorry I dont entirely understand wdym by what exception.

**Comment by JakeWharton** [comment]
`onFailure` is called with an exception which indicates what the problem is.

**Comment by zzzsound** [comment]
> `onFailure` is called with an exception which indicates what the problem is.

I didnt use any exception just simple onResponse and onFailure. The data i got back from the api in the Log is like what I want but at the end still have onFailure response. Sorry Im a bit new.

![Screenshot 2021-11-08 213006](https://user-images.githubusercontent.com/93919393/140760446-a9399ea6-3060-4d17-8332-8b6aea714ff9.png)

**Comment by JakeWharton** [comment]
Print the `Throwable` that is passed to `onFailure` as `t`. You can call `printStackTrace` and then paste the whole thing here.

**Comment by zzzsound** [comment]
> printStackTrace
Thank you so much. I got it running now.
