### ISSUE TITLE
Better docs

### ISSUE THREAD

**Issue by CamilYed** [square/retrofit#3659]
Hi. 
Where Can I find more detailed documentation about `@Streaming` annotation?

**Comment by JakeWharton** [comment]
The only docs are on the annotation itself: https://square.github.io/retrofit/2.x/retrofit/retrofit2/http/Streaming.html

**Comment by ryanholden8** [comment]
+ 1 for better docs. The [current docs](https://square.github.io/retrofit/) doesn't mention the @Body annotation even exists. Had to use StackOverflow and some poorly written blog posts to figure out how to send a JSON payload in a POST API. 

The current docs could benefit from briefly mentioning the different annotations.

**Comment by JakeWharton** [comment]
Would love to write better docs but simply put no one is being paid to work on such things. Perhaps we'll overhaul this for 3.x, if such a thing every happens.
