### ISSUE TITLE
response error body string conversion confusion

### ISSUE THREAD

**Issue by SaurabhS120** [square/retrofit#3660]
to convert server response to string you can call the 'toString()' method
eg.
(code in kotlin)
response.body().toString()

but to convert errorbody to string we have to call 'string()' method
response.errorBody()!!.string()

if you forget this you will end up spending a huge amount of time on this error

**Comment by JakeWharton** [comment]
`toString()` on the body object is not guaranteed to return a full representation. What it does is implementation detail of whatever type you have chosen for your body–we do not control it.

The `ResponseBody` type that `errorBody()` returns has a meaningful `toString()`, it's just not the full content. Retrofit does not control this type, it comes from OkHttp and we cannot change its behavior.

There's not really anything we can do here.
