### ISSUE TITLE
Expose scalar converter internals for extension

### ISSUE THREAD

**Issue by Dragas** [square/retrofit#3664]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Currently I have an issue where I must use multiple types of converters conditionally in the same retrofit instance (suppose scalars and  jackson). I have figured out that `Converter.Factory` interface permits obtaining all the annotations that a particular method in interface would have (either per argument, or entire method) for requests and for responses. As a result, I came up with the following converter factory

```java
public class ConditionalScalarConverterFactory extends ScalarsConverterFactory {
    public static ConditionalScalarConverterFactory create() {
        return new ConditionalScalarConverterFactory();
    }

    private ConditionalScalarConverterFactory() {
    }


    @Override
    public Converter<ResponseBody, ?> responseBodyConverter(
            Type type, Annotation[] annotations, Retrofit retrofit) {
        for (Annotation methodAnnotation : annotations) {
            if (methodAnnotation.annotationType().equals(ScalarResponse.class)) {
                return super.responseBodyConverter(type, annotations, retrofit);
            }
        }
        return null;
    }
}
```

Assume `ScalarResponse` is a marker interface.

Such factory permits conditionally override which converter factory would be selected for method in retrofit interface provided that it has the necessary marker annotation. If a method would not contain the marker interface, then retrofit will select next one in the installed converter factory order.

Currently this is not achievable because scalars module does not expose its internals (classes are final, and most are package private). As a workaround user can copy over the module to his codebase, but that would mean keeping track of the changes that would be made to the scalars converter. 

As a result I request to expose internals of scalars converter module for extension. See #3663

**Comment by JakeWharton** [comment]
The pattern to use here to extend the functionality is composition via delegation, not inheritance.

Consider this very small tweak to your code snippet:
```diff
-public class ConditionalScalarConverterFactory extends ScalarsConverterFactory {
+public class ConditionalScalarConverterFactory implements Converter.Factory {
     public static ConditionalScalarConverterFactory create() {
         return new ConditionalScalarConverterFactory();
     }

     private ConditionalScalarConverterFactory() {
     }

+  private final ScalarsConverterFactory delegate = ScalarsConverterFactory.create()

     @Override
     public Converter<ResponseBody, ?> responseBodyConverter(
             Type type, Annotation[] annotations, Retrofit retrofit) {
         for (Annotation methodAnnotation : annotations) {
             if (methodAnnotation.annotationType().equals(ScalarResponse.class)) {
-                return super.responseBodyConverter(type, annotations, retrofit);
+                return delegate.responseBodyConverter(type, annotations, retrofit);
             }
         }
         return null;
     }
 }
```

A more complex example can be found here: https://github.com/square/retrofit/blob/515bfc977fbc567919a595206749256f5a8b4620/samples/src/main/java/com/example/retrofit/JsonAndXmlConverters.java

**Comment by Dragas** [comment]
Ah right. Forgot about delegation.
