### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by onexuan** [square/retrofit#3665]
I try to use this jdk https://github.com/Tencent/TencentKona-11/releases/tag/kona11.0.13 or https://developer.ibm.com/languages/java/semeru-runtimes/downloads

retrofit-2.9.0 
spring 2.3.8.RELEASE
but get this issue

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by retrofit2.Platform to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by tarasok** [comment]
I have same issue, Java 11, retrofit 2.9.0.

**Comment by thevery** [comment]
https://github.com/square/retrofit/issues/3557#issuecomment-839756515

**Comment by fadzlitown** [comment]
Super annoying. I'm getting the same issue. I can't find any workaround

**Comment by JakeWharton** [comment]
Tracked by #3448
