### ISSUE TITLE
Upgrading to targetSdkVersion 31

### ISSUE THREAD

**Issue by mariuspena** [square/retrofit#3667]
Bug

If I upgrade compileSdkVersion and targetSdkVersion to 31 I get a 
Manifest merger failed : android:exported needs to be explicitly specified for <activity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

If I downgrade compileSdkVersion and targetSdkVersion to 30 I get a successful build, look into the AndroidManifest - the merged one and see an activity android:name = com.squareup.leakcanary.internal.DisplayLeakActivity that does not have the exported attribute (required by API 31)

Do you have any ideas of what I should do ?

thank you

**Comment by JakeWharton** [comment]
File a bug on LeakCanary: https://github.com/square/leakcanary. This has nothing to do with Retrofit.

**Comment by mariuspena** [comment]
yes my bad!
