### ISSUE TITLE
Unable to access headers in Converter

### ISSUE THREAD

**Issue by zyxist** [square/retrofit#3676]
I'm trying to write a converter for Apache Avro types. Our solution requires sending additional headers with Avro schema version corresponding to the given Avro class. I reached the point when I'm able to convert the Avro object into a binary representation, but then I'm not able to attach the necessary header in the converter:

```kotlin
    override fun convert(value: Any): RequestBody? {
        val result = converter.toAvro(value)
        // result.schemaVersion() - how to send it here?
        return result.data().toRequestBody(AvroMediaType.AVRO_MEDIA_TYPE_VALUE.toMediaType())
    }
```

I tried to use OkHttp interceptors, but they don't seem to see the original parameter type of service interface method, and even if - I'd have to call the conversion twice to get the schema version which is not what I need.

How can I workaround the issue and is it possible to make necessary improvements to `RequestBody` type? It looks like a blocker and I think there are many more protocols/use cases, where the ability to send headers would be necessary.

**Comment by JakeWharton** [comment]
There is no workaround at present unfortunately. `RequestBody` is from OkHttp, not Retrofit, so we cannot change it.

This use case is tracked by #2987 for future API breaking changes in Retrofit.
