### ISSUE TITLE
PEN Test Issue : Insecure Random and Hashing Identified

### ISSUE THREAD

**Issue by krishnapatait** [square/retrofit#3694]
We have run the PEN test using the [ mobsf tool ](https://mobsf.github.io/docs/#/running) and for the retrofit library we found that on the following observation.

![Retrofit Error](https://user-images.githubusercontent.com/85921615/154234432-8bb53bb5-a130-41e4-82b2-413f26172e02.png)

Can you please provide feedback and fix this issue.

**Comment by JakeWharton** [comment]
This function is not used for cryptography. Moreover, this artifact is not used in production as it's a testing dependency.
