### ISSUE TITLE
'okhttp3.Response' is not a valid response body type.

### ISSUE THREAD

**Issue by shaburov** [square/retrofit#3698]
Why can't I get a raw response using retrofit?

```
    @GET("/api/service/live")
    Response liveCheck();
```

I implemented `retrofit2.CallAdapter.Factory` and a converter specifically for getting a raw response, however I got an exception.

```
IllegalArgumentException: 'okhttp3.Response' is not a valid response body type. Did you mean ResponseBody?
    for method JavaTypeAdapterFactoryClient.returnRawResponseType
```

What is the reason for this limitation?
And what problem does this exception solve?
![image](https://user-images.githubusercontent.com/15269131/155509265-6a538194-1506-471d-aff3-fa2502b4619c.png)

**Comment by tomridder** [comment]
u can just use okhttp instead of retrofit in order to get Response return type

**Comment by stevep99** [comment]
Yes, this restriction is highly inconvenient in a case where you want to be able to get a particular response header. 
We shouldn't need to have to resort to using okhttp when the rest of our API is using Retrofit.

**Comment by JakeWharton** [comment]
Have you looked around the Retrofit API? OkHttp is _everywhere_.

**Comment by stevep99** [comment]
So, I have figured out, I'll post it here in case it helps any of the others who have upvoted this ticket.

If your API is returning let's say a User object, then you can have your method return
`Response<User>`
Here, `Response` is retrofit.Response, _not_ okhttp3.Response.

If you just want to get the raw body content, you can also set your return type to:
`Response<ResponseBody>`
where Response is the the retrofit one, and ResponseBody is the okttp3 one.

I think the guidance in error message ("Did you mean ResponseBody?") took OP - and myself - down a wrong alley, as ResponseBody doesn't provide headers. What you actually need to do is just wrap your object inside retrofit Response, and you can then access the headers and status code etc.

**Comment by JakeWharton** [comment]
Indeed. Also, notably, you can access the full `okhttp3.Response` via `retrofit2.Response.raw()` API. Now this instance will have the body removed (lest we have to buffer/duplicate in-memory), but that combined with using `retrofit2.Response<ResponseBody>` as the return type effectively gives you the original `okhttp3.Response`.

I don't think there's a huge advantage to allowing `Call<okhttp3.Response>` which would yield the fairly confusing `retrofit2.Response<okhttp3.Response>`.
