### ISSUE TITLE
[Bug] The response body is discarded when a 204/205 status is received

### ISSUE THREAD

**Issue by shaburov** [square/retrofit#3699]
The client must make a request and return a real response from the server. The server response for any client implementation must be **IMMUTABLE**, but the client implementation introduces changes by discarding the body.

The `retrofit2.OkHttpCall.parseResponse()` method ignores the response body from the server if a 204/205 status is received.
![image](https://user-images.githubusercontent.com/15269131/155511742-b77e2a7e-9063-4f17-a24f-2563147348ff.png)

**RFC 7231**
[6](https://datatracker.ietf.org/doc/html/rfc7231#section-6).  Response Status Codes
...
HTTP status codes are extensible.  HTTP **clients are not required** to understand the meaning of all registered status codes, though such understanding is obviously desirable.  However, a client **MUST understand** the class of any status code, as indicated **by the first digit**, and treat an unrecognized status code as being equivalent to the x00 status code of that class, with the exception that a recipient MUST NOT cache a response with an unrecognized status code.
...

I'm using your client for API testing and couldn't catch the error when on status 204 the response body was not empty (JSON was received). Retrofit did not return the actual response body. I haven't been able to verify that the response body is indeed empty. I couldn't catch the error.

**Comment by JakeWharton** [comment]
Per https://datatracker.ietf.org/doc/html/rfc7231#section-6.3.5

> A 204 response is terminated by the first empty line after the header fields because it cannot contain a message body.

And https://datatracker.ietf.org/doc/html/rfc7231#section-6.3.6

> Since the 205 status code implies that no additional content will be provided, a server MUST NOT generate a payload in a 205 response.  In other words, a server MUST do one of the following for a 205 response: a) indicate a zero-length body for the response by including a Content-Length header field with a value of 0; b) indicate a zero-length payload for the response by including a Transfer-Encoding header field with a value of chunked and a message body consisting of a single chunk of zero-length; or, c) close the connection immediately after sending the blank line terminating the header section.

If you have a non-conforming server which sends a body for these status codes, I would suggest dropping down to OkHttp which is less opinionated about such things (although still quite opinionated).
