### ISSUE TITLE
Observer with observeOn on Schedulers.currentThread is not called on currentThread

### ISSUE THREAD

**Issue by Sagaris** [square/retrofit#370]
I'm new to RxJava so forgive me if I made the wrong assumption. 
I assumed from the RxJava documentation that the Observer is called from the thread which is set by the observeOn call of an Observable. 

In my case I set the Schedulers as follows:
.subscribeOn(Schedulers.threadPoolForIO()).observeOn(Schedulers.currentThread())

So I was expecting that the onNext is called from the current thread but it appears that onNext is called from the "Retrofit-Idle" thread instead.

It seems that the observeOn is completely ignored. 
Is this as designed or is this an error?

**Comment by bhargavms** [comment]
@loganj what if you are on JVM and therefore do not have access to `AndroidThreads.mainThread()` ?

**Comment by guelo** [comment]
To answer the JVM question, you need an Executor that executes the runnables back on the calling thread. One solution is posting to a BlockingQueue that's being consumed on the caller's thread. Something like this (kotlin),

```kotlin		
		val tasks = LinkedBlockingQueue<Runnable>()

		Observable.fromCallable {"Hello" }
				.subscribeOn(Schedulers.io())
				.observeOn(Schedulers.from(Executor { runnable -> tasks.add(runnable) }))
				.subscribe { println("Back on the original thread:  " + Thread.currentThread().name) }
		
		tasks.take().run()
```

**Comment by bhargavms** [comment]
@guelo so that just basically blocks the calling thread until, `tasks.take()` returns which is when the `observable` emits.

**Comment by guelo** [comment]
Correct. You need some kind of strategy to allow the thread to cede control and execute work asynchronously posted from another thread. In UI and game code that's usually provided for you as an event loop, which is what AndroidSchedulers.mainThread() hooks into. If you're doing your own asynchronous callbacks you have to come up with your own strategy.
