### ISSUE TITLE
Retrofit socket timeout exception due to <mluc> tag while uploading file using multipart

### ISSUE THREAD

**Issue by Poonam4789** [square/retrofit#3701]
While uploading file using multipart using retrofit 2.9.0,it convert file to binary and adds mluc tag along with that , because of this tag api is blocking at our server because it has firewall and and does not allows mluc tags , can anyone help me resolve this issue .
why this tag is added by retrofit ?

Logs:
upload_document
--21e712b2-520c-4844-9cb8-219d9a77d1cc
Content-Disposition: form-data; name="file"; filename="1644842874898_croppedImg.jpg"
Content-Type: multipart/form-data
Content-Length: 45195

......JFIF.............(ICC_PROFILE...............mntrRGB XYZ ............acsp.......................................-................................................... desc.......trXYZ...d....gXYZ...x....bXYZ........rTRC.......(gTRC.......(bTRC.......(wtpt........cprt.....**..< mluc** ............enUS...X.....s.R.G.B................................................................................XYZ ......o...8.....XYZ ......b.........XYZ ......$.........para..........ff......
Y......
[........XYZ ............... **-mluc** ............enUS... .....G.o.o.g.l.e. .I.n.c... .2.0.1.6...C...............
.

...............%...#... , #&')*)..-0-(0%()(...C....
.

**Comment by JakeWharton** [comment]
Retrofit does not affect the body of HTTP requests in any way. It passes along whatever your chosen converter supplies or it uses helpers like `FormBody` or `MultipartBody` from OkHttp which are responsible for encoding those formats.

Please provide a failing test case or executable sample that reproduces the issue.
