### ISSUE TITLE
 retrofit support load balancing feature

### ISSUE THREAD

**Issue by melin** [square/retrofit#3708]
Does retrofit have built-in load balancing features? Does not rely on nginx for load balancing. Can reduce deployment dependencies
GRPC client has load balancing feature.

**Comment by JakeWharton** [comment]
Retrofit is a fancy way to build HTTP requests but OkHttp is the library which executes those requests. If you want load balancing, OkHttp is the layer that is best suited to implement it. You could accomplish it with an interceptor that rewrites the domain/base URL in whatever fashion you want to distribute the load based on whatever policy you want. At Retrofit's layer, however, we do not have or plan to add any type of support for this.

**Comment by melin** [comment]
Retrofit depends on okhttp, does retrofit expose okhttp interceptor?

**Comment by JakeWharton** [comment]
OkHttp is an API dependency. You have it's full API available.
