### ISSUE TITLE
Warning from Android Studio

### ISSUE THREAD

**Issue by DocMeaningless** [square/retrofit#3709]
Hello!
https://developer.android.com/courses/pathways/android-basics-kotlin-unit-4-pathway-2#codelab-https://developer.android.com/codelabs/android-basics-kotlin-test-network-request
By following this linked tutorial for Kotlin made by Google i found a new warning when i try execute the unit test for the API.
The first image is the code that create the warning.
![retrofit_2](https://user-images.githubusercontent.com/11209676/159271922-a12d18c4-3939-491b-a3c1-695007d2e883.png)
The second image is the warning.
![retrofit_1](https://user-images.githubusercontent.com/11209676/159271912-4b0d46ae-e3b3-429a-b905-7cb4e7b00d53.png)
I think that you can reproduce the warning by following the tutorial.
The info of Android Studio tha was used are:
Android Studio Bumblebee | 2021.1.1 Patch 2
Build #AI-211.7628.21.2111.8193401, built on February 17, 2022
Runtime version: 11.0.11+9-b60-7590822 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8
Registry: external.system.auto.import.disabled=true, debugger.watches.in.variables=false
Non-Bundled Plugins: idea.plugin.protoeditor (2.3.1), Dart (211.7808), wu.seal.tool.jsontokotlin (3.7.2), com.thoughtworks.gauge (211.6693.111), org.jetbrains.kotlin (211-1.6.10-release-923-AS7442.40), io.flutter (65.2.2), org.intellij.plugins.markdown (211.7142.37)

Have a nice day.

**Comment by JakeWharton** [comment]
Thanks. Making this required reflective lookup lazy is tracked by #3448. On JDK 17 and newer we do not use reflection for this functionality.
