### ISSUE TITLE
@Streaming method does not return from execute() until full content has been downloaded

### ISSUE THREAD

**Issue by tzugen** [square/retrofit#3718]
I have declared a Streaming API endpoint:
```
@Streaming
    @GET("stream.view")
    fun stream(
        @Query("id") id: String,
    ): Call<ResponseBody>
```

I call it using execute():

```
API.stream(song.id, maxBitrate, offset = songOffset)
                .execute()`
```

This call returns a mediafile, usually an mp3. Unfortunately even though it is marked as @Streaming, execute() returns only when the complete file has been received. I would suggest to have a way to get a InputStream of the body once the headers have been received.

**Comment by JakeWharton** [comment]
We have a test which proves that `execute().body()` returns before the full response body has been read from the socket: https://github.com/square/retrofit/blob/1490e6b1f90c616e2283b098a2c8e51a88cc97c2/retrofit/src/test/java/retrofit2/CallTest.java#L587-L609. If the response was fully buffered in that test, the exception would be thrown from the `execute()` function and not later by `string()` which reads the actual body stream.

**Comment by tzugen** [comment]
I have created a test with a real url, and you are right, in the test it works:
https://github.com/tzugen/retrofit/commit/23c0081b5ad14ed37adae25e02cf730d21cb82e3

Do you have an idea why it would behave completely differently in our app?

https://github.com/ultrasonic/ultrasonic/blob/e77b5abd3e12c17b455e71ff397f343d04fac214/core/subsonic-api/src/main/kotlin/org/moire/ultrasonic/api/subsonic/SubsonicAPIClient.kt#L86-L100

Here is where we call it:

https://github.com/ultrasonic/ultrasonic/blob/a98c9e2ffd92df32cb927f4b4e657ce9ba762ac7/ultrasonic/src/main/kotlin/org/moire/ultrasonic/playback/APIDataSource.kt#L143-L149

The timestamp of the logging calls are sometimes 40 seconds apart

**Comment by JakeWharton** [comment]
Do you have an OkHttp interceptor which somehow reads the whole body?

**Comment by tzugen** [comment]
Yes, that was it: A logging interceptor set to Level.Body!

Thank you :)
