### ISSUE TITLE
Retrofit 1.3.0 doesn't work after obfuscation using ProGuard

### ISSUE THREAD

**Issue by tshevchuk** [square/retrofit#372]
I have used following configuration for obfuscation:
###### 

-keep class com.google.gson.*\* { _; }
-keep class com.google.inject._\* { _; }
-keep class org.apache.http._\* { _; }
-keep class org.apache.james.mime4j._\* { _; }
-keep class javax.inject._\* { _; }
-keep class retrofit._\* { public protected private _; }
-keep class com._\* {
  public protected private _;
}
-dontwarn rx._*
###### 

It crashed during call to network service with the following exception:
01-08 16:24:45.642: E/AndroidRuntime(12713): FATAL EXCEPTION: main
01-08 16:24:45.642: E/AndroidRuntime(12713): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.testobfuscation/com.example.testobfuscation.MainActivity}: java.lang.IllegalArgumentException: Last parameter of getPuzzleComments must be of type Callback<X> or Callback<? super X>. Found: interface retrofit.Callback
01-08 16:24:45.642: E/AndroidRuntime(12713):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2049)
01-08 16:24:45.642: E/AndroidRuntime(12713):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2083)
01-08 16:24:45.642: E/AndroidRuntime(12713):    at android.app.ActivityThread.access$600(ActivityThread.java:134)
01-08 16:24:45.642: E/AndroidRuntime(12713):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1233)
01-08 16:24:45.642: E/AndroidRuntime(12713):    at android.os.Handler.dispatchMessage(Handler.java:99)
01-08 16:24:45.642: E/AndroidRuntime(12713):    at android.os.Looper.loop(Looper.java:137)
01-08 16:24:45.642: E/AndroidRuntime(12713):    at android.app.ActivityThread.main(ActivityThread.java:4697)
01-08 16:24:45.642: E/AndroidRuntime(12713):    at java.lang.reflect.Method.invokeNative(Native Method)
01-08 16:24:45.642: E/AndroidRuntime(12713):    at java.lang.reflect.Method.invoke(Method.java:511)
01-08 16:24:45.642: E/AndroidRuntime(12713):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
01-08 16:24:45.642: E/AndroidRuntime(12713):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
01-08 16:24:45.642: E/AndroidRuntime(12713):    at dalvik.system.NativeStart.main(Native Method)
01-08 16:24:45.642: E/AndroidRuntime(12713): Caused by: java.lang.IllegalArgumentException: Last parameter of getPuzzleComments must be of type Callback<X> or Callback<? super X>. Found: interface retrofit.Callback
01-08 16:24:45.642: E/AndroidRuntime(12713):    at retrofit.RestMethodInfo.parseResponseType(Unknown Source)
01-08 16:24:45.642: E/AndroidRuntime(12713):    at retrofit.RestMethodInfo.<init>(Unknown Source)
01-08 16:24:45.642: E/AndroidRuntime(12713):    at retrofit.RestAdapter.getMethodInfo(Unknown Source)
01-08 16:24:45.642: E/AndroidRuntime(12713):    at retrofit.RestAdapter$RestHandler.invoke(Unknown Source)
01-08 16:24:45.642: E/AndroidRuntime(12713):    at $Proxy0.getPuzzleComments(Native Method)
01-08 16:24:45.642: E/AndroidRuntime(12713):    at com.example.testobfuscation.MainActivity.onCreate(Unknown Source)
01-08 16:24:45.642: E/AndroidRuntime(12713):    at android.app.Activity.performCreate(Activity.java:4539)
01-08 16:24:45.642: E/AndroidRuntime(12713):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
01-08 16:24:45.642: E/AndroidRuntime(12713):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2013)
01-08 16:24:45.642: E/AndroidRuntime(12713):    ... 11 more

**Comment by XandrMaster** [comment]
Cool, I have fixed also. Thanks.

**Comment by nobuoka** [comment]
Thanks, this issue is helpful for me.

I think Markdown parser removed asterisks from tshevchuk's code. I have fixed the problem with following ProGuard configuration:

```
-keep class com.google.gson.** { *; }
-keep class com.google.inject.** { *; }
-keep class org.apache.http.** { *; }
-keep class org.apache.james.mime4j.** { *; }
-keep class javax.inject.** { *; }
-keep class retrofit.** { *; }
-dontwarn rx.**
-keep class com.example.testobfuscation.** { *; }
-keepattributes Signature
-keep class sun.misc.Unsafe { *; }
```
