### ISSUE TITLE
uncatch exception with suspend 

### ISSUE THREAD

**Issue by jianning0925** [square/retrofit#3724]
hellow, there is a uncatch  exception . eg: Httpexception  500.  this is my code :
```
suspend inline fun <T> ApiCall(crossinline call: suspend CoroutineScope.() -> ResponseResult<T>): ResponseResult<T> {
    return withContext(Dispatchers.IO) {
        val res: ResponseResult<T>
        try {
            res = call()
        } catch (e: Throwable) {
        
            e.printStackTrace()
            return@withContext ApiException.build(e).toResponse<T>()
        }
    
        return@withContext res
    }

```

and i see the issues a long time ,for  [https://github.com/Kotlin/kotlinx.coroutines/issues/1474](1474) 
[https://github.com/square/retrofit/issues/3128](3128)  

I still don't know how to fix it  in the lastrelease

**Comment by JakeWharton** [comment]
I'm not quite sure what this is stating. Is it a question or a problem?

We really need an executable test case to demonstrate what you're seeing and what you expect the behavior to be. If you can provide one, I'll happily re-open and take a look.
