### ISSUE TITLE
[BUG] Response code is wrong

### ISSUE THREAD

**Issue by wayne900204** [square/retrofit#3729]
# Response Code Bug
https://stackoverflow.com/questions/72099494/android-retrofit2-okhttp3-responsebody-wrong

# My expectation
In android, response code is 403.
But in fact the response code should be 302.

**Comment by JakeWharton** [comment]
OkHttp follows redirects automatically. You can disable it for on the builder: https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/-builder/follow-redirects/.
