### ISSUE TITLE
Add Service instance to `Invocation`

### ISSUE THREAD

**Issue by efemoney** [square/retrofit#3730]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Since Retrofit supports service interface hierarchies, the `method()` & `arguments()` of the `Invocation` are no more sufficient to distinguish the invocation. A method might be declared in a super class with Retrofit annotations but the subclass is the interface which gets created.

```kt
interface Super {
  @GET("/super") fun getSuper()
}

// This interface gets instantiated via Retrofit.create(Sub::class)
interface Sub: Super {
  fun getSuperFallback(error: Throwable) { ... }
}
```

The primary use case right now is to be able to support/implement Resilience4j's CircuitBreaker fallback mechanism but there are [other library use cases](https://github.com/LianjiaTech/retrofit-spring-boot-starter/issues/109) and it might open the door to many others.

**Comment by JakeWharton** [comment]
Are you asking for the actual instance or just the service class?

**Comment by JakeWharton** [comment]
This is really easy to add, but I just want to make sure I understand completely what you want so I can try to balance it with any and all other options we have.

So are you basically would unsafe cast back to the `Sub` type in order to call this fallback function?

**Comment by efemoney** [comment]
In my case, it would be called via reflection on the instance, but some other integration would require an unsafe cast, yes.

**Comment by efemoney** [comment]
soft bump ⬆️ @JakeWharton 😅

**Comment by efemoney** [comment]
Just ran into another use case for this! This time for distinguishing the correct "api" subclass.
