### ISSUE TITLE
在使用协程时返回值可为空

### ISSUE THREAD

**Issue by KFCboy** [square/retrofit#3731]
在我使用协程时，我希望能在接口返回空值时能获取到空值，但是我在实际运行过程中无法获取，同时报错

`Response from XXX was null but response body type was declared as non-null `

然后再查看源码时发现，[HttpServiceMethod](https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit2/HttpServiceMethod.java)中，没有调用awaitNullable的逻辑，希望能够加上这个

**Comment by wonsuc** [comment]
Use english dude.

**Comment by moten-07** [comment]
你可以这么做
@POST(URL)
suspend fun base():Bean?

**Comment by xiaojinzi123** [comment]
> 你可以这么做 @post(URL) suspend fun base():Bean?

没用的 yuan'ma源码中的 continuationBodyNullable 是写死的 false
![image](https://user-images.githubusercontent.com/12975743/202117752-f19c8623-ae08-4752-b0ed-6c8b063a7e0a.png)

**Comment by Goooler** [comment]
Duplicate of #3075

**Comment by Goooler** [comment]
这个问题可以关了，关注那个就好
