### ISSUE TITLE
Cancel multiple Retrofit API calls at once

### ISSUE THREAD

**Issue by waseem786** [square/retrofit#3734]
Hi, 

Past few days I am searching for a Retrofit2 feature. 
Is there any option or way to cancel multiple API calls at once, requested from a client? 

For example, I have to call 5 APIs in a sequence, and while the app calls those 5 APIs, the user can do other actions in the app. 
In case, if the user has called another API, I have to prioritize the last called API and hold or terminate the previous 5 API calls. 
Right now what happens is, that the user called API will be in the queue till the previous APIs completes. 

I have found that Retrofit2 has a method called 'cancel()', but it works only for one API, not working for multiple API calls.

I am using version - 2.9.0 in my android app

**Comment by JakeWharton** [comment]
We do not provide a way to aggregate `Call` instances to cancel in a batch, but you could write such an object yourself. Unfortunately this quickly spirals into building a bunch of promise-like combinators like `then` which we don't want to be responsible for and would defer to other libraries.

Other libraries like kotlinx.coroutines and its `CoroutineScope` or RxJava and its `CompositeDisposable` allow aggregating operations and canceling them as a unit (as well as providing the aforementioned combinators for all kinds of sequencing operations).
