### ISSUE TITLE
@GET with Json Request Body

### ISSUE THREAD

**Issue by Morons** [square/retrofit#3735]
BUG

I have searched but it seem like there is No Way to send a @GET with an @Body using Retrofit!
```java
OkHttpClient client = new OkHttpClient().newBuilder()
  .build();
Request request = new Request.Builder()
  .url("http://localhost:8080/api/post/get")
  .method("GET", null)
  .addHeader("Content-Type", "application/json")
  .build();
Response response = client.newCall(request).execute();
```
This works BUT not with Retrofit! on Android and Kotlin I get 
` java.lang.IllegalArgumentException: Non-body HTTP method cannot contain @Body.` 

**My Api** Ommited the `Authorization` for brevity
```kotlin
	@GET("/api/post/get")
	@Headers("Content-Type:application/json")
	suspend fun getPostForFollows(@Body getPageRequest: GetPageRequest): List<Post>
``` 
**My Di** - Using Hilt
```kotlin
	@Provides
	@Singleton
	fun providePostApi(httpClient: OkHttpClient): PostApi {
		return Retrofit.Builder()
			.baseUrl(BASE_URL)
			.addConverterFactory(GsonConverterFactory.create())
			.build()
			.create(PostApi::class.java)
	}
```
PostmanRuntime/7.29.0 also succeed!
This works well with Retrofit and @Query or @Path **BUT** why?

**Comment by JakeWharton** [comment]
You can use `@HTTP("GET", hasBody = true)` for this. Here's its docs: https://square.github.io/retrofit/2.x/retrofit/retrofit2/http/HTTP.html

We will not be allowing a body with the `@GET` annotation as it is forbidden by the spec. We also don't control the behavior of OkHttp which may prevent you from sending the request.

**Comment by PanosHatz** [comment]
> You can use `@HTTP("GET", hasBody = true)` for this. Here's its docs: https://square.github.io/retrofit/2.x/retrofit/retrofit2/http/HTTP.html
> 
> We will not be allowing a body with the `@GET` annotation as it is forbidden by the spec. We also don't control the behavior of OkHttp which may prevent you from sending the request.

Can I find an example of this anywhere? I don't seem to be able to make it work. Do we need two classes RequestBody and ResponseBody where the first sets the body variables and the other has the getters?
