### ISSUE TITLE
HTTP FAILED: java.io.IOException: unexpected end of stream on

### ISSUE THREAD

**Issue by rituapplocum** [square/retrofit#3737]
HTTP FAILED: java.io.IOException: unexpected end of stream on GET request 
getting the above exception randomly for every GET request

**Comment by JakeWharton** [comment]
The server is closing your connection. Or your phone is losing network. Or your server has its route broken.

IOExceptions are perfectly normal, expected outcomes when the transport (the things which marshals bytes from you to the server and back) fails. You should expect this exception to _always_ occur and handle it appropriately.
