### ISSUE TITLE
Upgrade Moshi to 1.12.0 from 1.8.0

### ISSUE THREAD

**Issue by kiskunk** [square/retrofit#3738]
Upgrade Moshi to 1.12.0 from 1.8.0

**Comment by JakeWharton** [comment]
Anyone is welcome to send a PR for this.

However, things to keep in mind:
- We never make releases solely for dependency bumps.
- We generally track a lower-than-latest version for each converter's serialization library.
- You should always specify an explicit dependency on the serialization library you use and bump that version regularly.
