### ISSUE TITLE
java.net.UnknownHostException, Caused by: android.system.GaiException:

### ISSUE THREAD

**Issue by TieuNhi95** [square/retrofit#3739]
Coroutine: 1.3.9
retrofit: 2.9.0
gson: 2.9.0
logging-interceptor: 4.9.3

Crash log on play console, the amount of crashes is a lot, please tell me how to solve it!
`java.net.UnknownHostException: at java.net.Inet6AddressImpl.lookupHostByName (Inet6AddressImpl.java:156) at java.net.Inet6AddressImpl.lookupAllHostAddr (Inet6AddressImpl.java:103) at java.net.InetAddress.getAllByName (InetAddress.java:1152) at okhttp3.Dns$Companion$DnsSystem.lookup (Dns.kt:49) at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress (RouteSelector.kt:164) at okhttp3.internal.connection.RouteSelector.nextProxy (RouteSelector.kt:129) at okhttp3.internal.connection.RouteSelector.next (RouteSelector.kt:71) at okhttp3.internal.connection.ExchangeFinder.findConnection (ExchangeFinder.kt:205) at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection (ExchangeFinder.kt:106) at okhttp3.internal.connection.ExchangeFinder.find (ExchangeFinder.kt:74) at okhttp3.internal.connection.RealCall.initExchange$okhttp (RealCall.kt:255) at okhttp3.internal.connection.ConnectInterceptor.intercept (ConnectInterceptor.kt:32) at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109) at okhttp3.internal.cache.CacheInterceptor.intercept (CacheInterceptor.kt:95) at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109) at okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.kt:83) at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109) at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.kt:76) at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109) at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp (RealCall.kt:201) at okhttp3.internal.connection.RealCall$AsyncCall.run (RealCall.kt:517) at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641) at java.lang.Thread.run (Thread.java:919) Caused by: android.system.GaiException: at libcore.io.Linux.android_getaddrinfo (Native Method) at libcore.io.ForwardingOs.android_getaddrinfo (ForwardingOs.java:74) at libcore.io.BlockGuardOs.android_getaddrinfo (BlockGuardOs.java:200) at libcore.io.ForwardingOs.android_getaddrinfo (ForwardingOs.java:74) at java.net.Inet6AddressImpl.lookupHostByName (Inet6AddressImpl.java:135) at java.net.Inet6AddressImpl.lookupAllHostAddr (Inet6AddressImpl.java:103) at java.net.InetAddress.getAllByName (InetAddress.java:1152) at okhttp3.Dns$Companion$DnsSystem.lookup (Dns.kt:49) at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress (RouteSelector.kt:164) at okhttp3.internal.connection.RouteSelector.nextProxy (RouteSelector.kt:129) at okhttp3.internal.connection.RouteSelector.next (RouteSelector.kt:71) at okhttp3.internal.connection.ExchangeFinder.findConnection (ExchangeFinder.kt:205) at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection (ExchangeFinder.kt:106) at okhttp3.internal.connection.ExchangeFinder.find (ExchangeFinder.kt:74) at okhttp3.internal.connection.RealCall.initExchange$okhttp (RealCall.kt:255) at okhttp3.internal.connection.ConnectInterceptor.intercept (ConnectInterceptor.kt:32) at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109) at okhttp3.internal.cache.CacheInterceptor.intercept (CacheInterceptor.kt:95) at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109) at okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.kt:83) at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109) at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.kt:76) at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109) at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp (RealCall.kt:201) at okhttp3.internal.connection.RealCall$AsyncCall.run (RealCall.kt:517) at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641) at java.lang.Thread.run (Thread.java:919)`

**Comment by JakeWharton** [comment]
This is a normal exception that you can expect on mobile networks. All calls can fail at any time with an IOException or any subtype. It just means DNS is currently working.

**Comment by TieuNhi95** [comment]
@JakeWharton 
I have caught the exception by this way, is it wrong?

` private val exceptionHandler = CoroutineExceptionHandler { _, throwable ->
Timber.tag(TAG).e("error: ${throwable.message}")
handleError(throwable)
}
val coroutineContextIO = Dispatchers.IO + exceptionHandler

private fun getDomain() {
    viewModelScope.launch(coroutineContextIO) {
  
            val jsonString = ObjectDevice(
                client = Constants.CLIENT,
                platform = Constants.PLATFORM_ANDROID,
                appVersion = BuildConfig.VERSION_CODE,
                device = Build.DEVICE
            )
            val asyncTwo = async {
                apiInterface.getDomain(jsonString.toRequestBodyEncrypted(gson))
            }

            val response = asyncTwo.await()

            val data = gson.fromJson(
                response.string().decrypt(),
                ResponseGetDomain::class.java
            )
            saveDomainInfo(data)
            checkLogin()

  
    }
}`
