### ISSUE TITLE
[Feature Request] Original path without args

### ISSUE THREAD

**Issue by pvarry** [square/retrofit#3740]
Hello,

I'm trying to implement a performance monitoring on the API I'm using, for that I added a `Interceptor` and log every request with the URL. But all request appears multiples times, each time with a different parameter in the path or in query.

I would to know if there is a possibility to get the original path setup in `@GET("products/{id}")` without replacing the `id` in a `Interceptor` ?
If not, it's possible to add this ?

Thanks

**Comment by JakeWharton** [comment]
This is possible, yes, but it requires a bit of effort.

First, get the [Retrofit `Invocation`](https://square.github.io/retrofit/2.x/retrofit/retrofit2/Invocation.html) from the OkHttp interceptor chain.
```java
Request request = chain.request();
Invocation invocation = request.tag(Invocation.class);
if (invocation != null) {
  // TODO
}
```

The `Invocation` will give you the `Method`.
```java
Method method = invocation.method();
```

Then with the method you can look up the HTTP annotation.
```java
GET get = method.getAnnotation(GET.class);
```

From there you can get the relative URL.
```java
String relativeUrl = get.value();
```
