### ISSUE TITLE
I hope you can provide an instant messaging library based on retrofit to facilitate app developers to quickly develop an instant messaging function

### ISSUE THREAD

**Issue by BraveHL** [square/retrofit#3741]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I hope you can provide an instant messaging library based on retrofit to facilitate app developers to quickly develop an instant messaging function, because it is very difficult for developers, especially app developers, to develop an instant messaging function, so if you have a relatively mature and stable open source library, this is very good for developers. Thank you very much.

**Comment by JakeWharton** [comment]
This is entirely out of scope for an HTTP client abstraction to include.
