### ISSUE TITLE
Is there really no updates about @QueryObject?

### ISSUE THREAD

**Issue by leosanqing** [square/retrofit#3746]
Its been 3 and a half years since the last comment. Is there really no updates about @QueryObject?

_Originally posted by @MadRatSRP in https://github.com/square/retrofit/issues/2293#issuecomment-683286832_

This feature should be used by a lot of people

In Spring or Openfeign, we can put multiple Params in one object and then make a Get request

If you can only use Map for requests with multiple parameters, it will be very troublesome to maintain

**Comment by JakeWharton** [comment]
My comment on that issue is still the current state of things.
