### ISSUE TITLE
support kotlin suspend nullable body

### ISSUE THREAD

**Issue by LDLZH** [square/retrofit#3756]
since 2.8.0 , retrofit accept a nullable response type, but not for suspend body
when  use Response as return type like below,
@GET("/get")
suspend fun get(): Response<Data?>
response.body() could return null

but for this usage, retrofit throw exception: Response from ** was null but response body type was declared as non-null
@GET("/get")
suspend fun get(): Data?
so why not support kotlin suspend nullable body?

**Comment by JakeWharton** [comment]
This is tracked by #3075. It's not supported because we're not going to inflict a massive dependency for parsing Kotlin metadata onto our Java consumers.

**Comment by goodwan** [comment]
@JakeWharton can you please consider adding something like @NullableResponse annotation instead of linking metadata jar? we will manually decorate cases like suspend fun getSomeStuff(...): T?
