### ISSUE TITLE
Where are the snapshots located?

### ISSUE THREAD

**Issue by KrishnaST** [square/retrofit#3772]
Could not find snapshots anywhere. 

[old ticket ](https://github.com/square/retrofit/issues/1103) refers to 
https://oss.sonatype.org/content/repositories/snapshots/com/squareup/retrofit/retrofit/2.0.0-SNAPSHOT/ 

but no latest snapshot available.

**Comment by JakeWharton** [comment]
The new snapshot URL is https://s01.oss.sonatype.org/content/repositories/snapshots/. It's linked in the README. Your `groupId` is incorrect, however, it should be `com.squareup.retrofit2` which means `com/squareup/retrofit2/`.

**Comment by JakeWharton** [comment]
The snapshot version is currently 2.10.0-SNAPSHOT as well. Generally you never navigate through the folder structure yourself. Add that URL to your build system, change the version to the snapshot version, and let your build system download all the snapshot artifacts.

**Comment by KrishnaST** [comment]
Thanks
