### ISSUE TITLE
If the type is primitive or String.class, you can directly return null; Compatible with other converters

### ISSUE THREAD

**Issue by chenGit1763113879QQ** [square/retrofit#3784]
https://github.com/square/retrofit/blob/6b6984e9dd683bff6cdb5931694e1b8efc3533ae/retrofit-converters/gson/src/main/java/retrofit2/converter/gson/GsonConverterFactory.java#L65

**Comment by JakeWharton** [comment]
The Gson converter will handle `String` if the body's JSON is a top-level string such as `"hello"`. Similarly, `2` is valid JSON and you can bind that to `Integer` or `Long`.

**Comment by chenGit1763113879QQ** [comment]
related issues
 json document was not fully consumed #3004    [https://github.com/square/retrofit/issues/3004]
