### ISSUE TITLE
HEAD method doens't support Kotlin Unit

### ISSUE THREAD

**Issue by scorpeeon** [square/retrofit#3787]
I'm using retrofit 2.9.0, when I'm trying to use a HEAD method with Unit return type:

```
@HEAD("/some/api")
suspend fun someApi(): Response<Unit>
```

I get an exception:
`java.lang.IllegalArgumentException: HEAD method must use Void as response type.`

Checking the stacktrace, it seems to be coming from HttpServiceMethod.java:81

A few lines before this line there's even a comment to support Kotlin's Unit:
`// TODO support Unit for Kotlin?`

I'm just wondering is there a specific reason this was not addressed yet? It's not critical, but needless to say Kotlin is not very good friends with Java's Void.

**Comment by JakeWharton** [comment]
This was tracked by #2888 and was fixed by #3702. It has not been released yet, unfortunately.
