### ISSUE TITLE
java.lang.NoSuchMethodError: No interface method in class or its super classes 

### ISSUE THREAD

**Issue by sarimmehdi** [square/retrofit#3789]
Pretty simple code:

```
interface someApi {

    @POST("/login")
    suspend fun getUserToken(@Body tokenRequest: UserAuthenticationRequest): TokenRequestResponse
}
```
Both UserAuthenticationRequest and TokenRequestResponse are data classes in Kotlin

This is how the Retrofit instance is created:

```
val logger = HttpLoggingInterceptor()
logger.setLevel(HttpLoggingInterceptor.Level.BASIC)
val okHttpClient = OkHttpClient
    .Builder()
    .addInterceptor(logger)
    .build()

return Retrofit.Builder()
    .baseUrl(someApi.BASE_URL)
    .addConverterFactory(MoshiConverterFactory.create())
    .client(okHttpClient)
    .build()
    .create(MicrodronesApi::class.java)
```
The error happens on this line:

`val userToken = api.getUserToken(userAuthenticationRequest)`

Java 8 features are already enabled:

```
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}
kotlinOptions {
    jvmTarget = '1.8'
}
```
I honestly no clue what's going on. Is it because I am using @Body incorrectly? Is it because of Moshi? The HttpsLoggingInterceptor?

**Comment by JakeWharton** [comment]
Please include the full stack trace of the exception.

**Comment by sarimmehdi** [comment]
Problem was solved by adding internet permissions
