### ISSUE TITLE
Retrofit does not release its resources.

### ISSUE THREAD

**Issue by VirajShirwalkar** [square/retrofit#3802]
Hi there,
I have been using retrofit for a while and realize that when i had to do more than 10 api calls on one screen via retrofit multiple times then android does not get time to release some memory (Garbage Collection). It went OOM. 
Please try the sequence as follows,

1. Consider You have more than 10 api calls on one screen of different end points. (Multiple times calling. 10 x n )
2. You have to update values from response in sqlite. (Update or Insert)
3. All api calls are either parallel or sequential.
4. Notice on logcat that, at a point, android start releasing memory for sake of api calls to be executed completely.
5. Goes OOM with releasing memory and either closes the app or fallback to previous screen.

[Note: Please consider that dbHelper has single instance and all cursors inside the responses are closed after query called each time.]
[Note: Tried with call.enqueue() and call.execute()]
[Note: Used Android Studio Dolphin with Java 11 + latest version of this library]

**Why Retrofit does not release its resources after all process is done inside the response everytime?**

**Comment by JakeWharton** [comment]
Can you provide an executable sample application that demonstrates the problem? It's impossible to know what you're doing and what you're seeing with such an abstract description. What specific resources are you talking about? Retrofit doesn't really maintain any resources, OkHttp is responsible for the entire HTTP layer and we treat it very closely like a pure function from request to response. We do stream the responses to converters, unless you are using `@Streaming` we try/finally to close those. So without more information, there's not much actionable response we can make here.

**Comment by VirajShirwalkar** [comment]
Thanks for reply.
I hope you are right.
I cannot share original api and all but sharing a scenario.
[ApiTestActivity.txt](https://github.com/square/retrofit/files/10416830/ApiTestActivity.txt)
[MyDB.txt](https://github.com/square/retrofit/files/10416831/MyDB.txt)
[MyDbHelper.txt](https://github.com/square/retrofit/files/10416832/MyDbHelper.txt)

Please convert from txt to java and add to your sample project.
Try the scenario. It will take some time but atleast give detail info of what is happening.
**[Note: After each bitmap variable added to table, i have tried to set variable null and same with contentValues variable.
Tried with some other objects too. But OOM appears.]**
**[Note: largeHeap is there. only doubt remain on the retrofit objects]**

Please take time and let us know the outcome.
Thanks.

**Comment by VirajShirwalkar** [comment]
Hmmm. A new retrofit instance.
I tried with single variable of Call, Api, ContentValues as a class level and before calling next api, set values to null. But it does not reflect as i thought.
I will try this solution and it will take some time and will update here asap.
Thanks.

**Comment by MrExplode** [comment]
I might have stumbled upon the same behaviour.
Consider the following test:
```java
var client = new OkHttpClient();
var req = new Request.Builder().url("https://google.com").build();
try (Response res = client.newCall(req).execute()) {
    System.out.println(res.body().string());
} catch (IOException e) {
    e.printStackTrace();
}
```

When using the transitive okhttp dependency from the [latest retrofit version](https://mvnrepository.com/artifact/com.squareup.retrofit2/retrofit/2.9.0) this example hangs (not just the plain okhttp request, the retrofit wrapped requests too)
![thread19](https://cdn.sunstorm.rocks/img/25ieq8.png/q2r9)
![thread21](https://cdn.sunstorm.rocks/img/1rmkjh.png/tctov7)

However, this doesn't happen when the [latest okhttp version](https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp/4.10.0) is explicitly added to the dependencies.

**Comment by JakeWharton** [comment]
Thanks. We are stuck on an old OkHttp for now because we aren't going to ship OkHttp's Kotlin dependency to our users (yet!), but we will eventually. For now, all we can do is recommend that you keep your OkHttp version up-to-date. This is good practice in general as Retrofit does not release solely to bump its dependencies.

With no further information from OP, there's no action to take.
