### ISSUE TITLE
FollowUp:21 Error 

### ISSUE THREAD

**Issue by usantos** [square/retrofit#3849]
When leaving the app in the background for many hours, about 4 hours, when returning to the foreground, it gives the following error: follow-up:21.

Even having configured it not to retry silently.

------
.retryOnConnectionFailure(false)
                .cache(null)
                .followRedirects(false)
                .followSslRedirects(false)

Libs:

    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'com.google.code.gson:gson:2.10'
    implementation 'com.squareup.okhttp3:okhttp-bom:4.10.0'
    implementation 'com.squareup.okhttp3:okhttp'
    implementation 'com.squareup.okhttp3:logging-interceptor'

**Comment by JakeWharton** [comment]
There's no information here to be able to diagnose any kind of a problem.

In general, Retrofit is a high-level abstraction on top of OkHttp and we don't have any knowledge or control of how requests are executed nor the enclosing context such as an application. Retrofit isn't an Android library, after all.

Without significantly more details it's not possible to understand what is going on to even start trying to identify what you're seeing let alone the underlying cause.
