### ISSUE TITLE
 the baseUrl of HTTP protocol requests is dynamic

### ISSUE THREAD

**Issue by sunnykandy** [square/retrofit#3877]
In certain scenarios, the baseUrl of HTTP protocol requests is dynamic, eg https://5095551.xxx.com , https://283819111.xxx.com 。 Due to changes in business rules, I do not want to create more Retrofit object instances. Hope to provide us with an answer. Thank you very much！

**Comment by JakeWharton** [comment]
You can use `@Url` to supply a full URL to an endpoint: https://square.github.io/retrofit/2.x/retrofit/retrofit2/http/Url.html

**Comment by sunnykandy** [comment]
Although this is possible, I need to concatenate the URL addresses at all calls. 

 I suggest this would be better. 

`
  @GET("/user/info")
  Call<JsonObject> user(@BasicUrl String baseUrl, @Header("Authorization") String name);
`

**Comment by sunnykandy** [comment]
> You can use `@Url` to supply a full URL to an endpoint: https://square.github.io/retrofit/2.x/retrofit/retrofit2/http/Url.html

Although this is possible, I need to concatenate the URL addresses at all calls.

I suggest this would be better.

@GET("/user/info") Call<JsonObject> user(@BasicUrl String baseUrl, @Header("Authorization") String name);
