### ISSUE TITLE
Missing proguard rules for R8/AGP8, please make a 2.9.1 release including the retrofit.pro R8 full mode rules

### ISSUE THREAD

**Issue by avianey** [square/retrofit#3880]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

After upgrading to AGP 8, release build are crashing on :

```
java.lang.IllegalArgumentException: Call return type must be parameterized as Call<Foo> or Call<? extends Foo>
                                                                                                    	at oe.i.a(SourceFile:43)
                                                                                                    	at oe.d0.d(SourceFile:36)
                                                                                                    	at oe.d0.a(Unknown Source:1)
                                                                                                    	at oe.m.d(SourceFile:1)
```

from R8 mapping :

```
retrofit2.DefaultCallAdapterFactory -> oe.i:
# {"id":"sourceFile","fileName":"DefaultCallAdapterFactory.java"}
    java.util.concurrent.Executor callbackExecutor -> a
    1:3:void <init>(java.util.concurrent.Executor):31:31 -> <init>
    4:6:void <init>(java.util.concurrent.Executor):32:32 -> <init>
```

This happens with :
-     implementation 'com.squareup.retrofit2:retrofit:2.7.2'
-     implementation 'com.squareup.retrofit2:retrofit:2.9.0'

Looking at the repo I saw that the https://github.com/square/retrofit/blob/master/retrofit/src/main/resources/META-INF/proguard/retrofit2.pro contains more rules than the one that are include in the retrofit jar. So I tried to add the content of https://github.com/square/retrofit/blob/master/retrofit/src/main/resources/META-INF/proguard/retrofit2.pro to my proguard.pro file and it solves the problem.

Is it possible to release a 2.9.1 version that includes the missing rules, especially the R8 full mode ones ?

**Comment by mhswtf** [comment]
I also just ran into this issue. 
For anyone else, until the issue is fixed, if you are using a non-default call adapter factory, you must also add the rules from it. 
For example, I am using the rxjava2 call adapter factory, so I needed to add the rules here:
https://github.com/square/retrofit/blob/master/retrofit-adapters/rxjava2/src/main/resources/META-INF/proguard/retrofit2-rxjava2-adapter.pro

**Comment by mirekkukla** [comment]
I'm likewise seeing proguard-rule related failures in full mode after migrating to gradle 8, albeit with a slightly different exception. Details and current workaround here: https://github.com/square/retrofit/issues/3005#issuecomment-1523948650

**Comment by MianoMen1** [comment]
```kotlin

```

**Comment by Goooler** [comment]
See https://github.com/square/retrofit/issues/3751#issuecomment-1192043644.

**Comment by DarkAbhi** [comment]
> What kind of issue is this?
> 
> * [ ]  Question. This issue tracker is not the place for questions. If you want to ask how to do
>   something, or to understand why something isn't working the way you expect it to, use Stack
>   Overflow. https://stackoverflow.com/questions/tagged/retrofit
> * [x]  Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
>   get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
> * [ ]  Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
>   already exists! Don’t send pull requests to implement new features without first getting our
>   support. Sometimes we leave features out on purpose to keep the project small.
> 
> After upgrading to AGP 8, release build are crashing on :
> 
> ```
> java.lang.IllegalArgumentException: Call return type must be parameterized as Call<Foo> or Call<? extends Foo>
>                                                                                                     	at oe.i.a(SourceFile:43)
>                                                                                                     	at oe.d0.d(SourceFile:36)
>                                                                                                     	at oe.d0.a(Unknown Source:1)
>                                                                                                     	at oe.m.d(SourceFile:1)
> ```
> 
> from R8 mapping :
> 
> ```
> retrofit2.DefaultCallAdapterFactory -> oe.i:
> # {"id":"sourceFile","fileName":"DefaultCallAdapterFactory.java"}
>     java.util.concurrent.Executor callbackExecutor -> a
>     1:3:void <init>(java.util.concurrent.Executor):31:31 -> <init>
>     4:6:void <init>(java.util.concurrent.Executor):32:32 -> <init>
> ```
> 
> This happens with :
> 
> * ```
>   implementation 'com.squareup.retrofit2:retrofit:2.7.2'
>   ```
> * ```
>   implementation 'com.squareup.retrofit2:retrofit:2.9.0'
>   ```
> 
> Looking at the repo I saw that the https://github.com/square/retrofit/blob/master/retrofit/src/main/resources/META-INF/proguard/retrofit2.pro contains more rules than the one that are include in the retrofit jar. So I tried to add the content of https://github.com/square/retrofit/blob/master/retrofit/src/main/resources/META-INF/proguard/retrofit2.pro to my proguard.pro file and it solves the problem.
> 
> Is it possible to release a 2.9.1 version that includes the missing rules, especially the R8 full mode ones ?

Did you add all the content in https://github.com/square/retrofit/blob/master/retrofit/src/main/resources/META-INF/proguard/retrofit2.pro ? I added the one's which mentioned R8 full, it didn't fix my issue.

**Comment by MianoMen1** [comment]
> 

Fg

**Comment by ubuntudroid** [comment]
The only additional rule you need to add should be the one added in commit 59d302a.

**Comment by SwordWang0228** [comment]
+1

**Comment by kanglongba** [comment]
> > What kind of issue is this?
> > 
> > * [ ]   Question. This issue tracker is not the place for questions. If you want to ask how to do
> >   something, or to understand why something isn't working the way you expect it to, use Stack
> >   Overflow. https://stackoverflow.com/questions/tagged/retrofit
> > * [x]   Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
> >   get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
> > * [ ]   Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
> >   already exists! Don’t send pull requests to implement new features without first getting our
> >   support. Sometimes we leave features out on purpose to keep the project small.
> > 
> > After upgrading to AGP 8, release build are crashing on :
> > ```
> > java.lang.IllegalArgumentException: Call return type must be parameterized as Call<Foo> or Call<? extends Foo>
> >                                                                                                     	at oe.i.a(SourceFile:43)
> >                                                                                                     	at oe.d0.d(SourceFile:36)
> >                                                                                                     	at oe.d0.a(Unknown Source:1)
> >                                                                                                     	at oe.m.d(SourceFile:1)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > from R8 mapping :
> > ```
> > retrofit2.DefaultCallAdapterFactory -> oe.i:
> > # {"id":"sourceFile","fileName":"DefaultCallAdapterFactory.java"}
> >     java.util.concurrent.Executor callbackExecutor -> a
> >     1:3:void <init>(java.util.concurrent.Executor):31:31 -> <init>
> >     4:6:void <init>(java.util.concurrent.Executor):32:32 -> <init>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This happens with :
> > 
> > * ```
> >   implementation 'com.squareup.retrofit2:retrofit:2.7.2'
> >   ```
> > * ```
> >   implementation 'com.squareup.retrofit2:retrofit:2.9.0'
> >   ```
> > 
> > Looking at the repo I saw that the https://github.com/square/retrofit/blob/master/retrofit/src/main/resources/META-INF/proguard/retrofit2.pro contains more rules than the one that are include in the retrofit jar. So I tried to add the content of https://github.com/square/retrofit/blob/master/retrofit/src/main/resources/META-INF/proguard/retrofit2.pro to my proguard.pro file and it solves the problem.
> > Is it possible to release a 2.9.1 version that includes the missing rules, especially the R8 full mode ones ?
> 
> Did you add all the content in https://github.com/square/retrofit/blob/master/retrofit/src/main/resources/META-INF/proguard/retrofit2.pro ? I added the one's which mentioned R8 full, it didn't fix my issue.

I update my gradle from 7.x to 8.0.2， then I encounter same issue. 
I added retrofit2.pro to my proguard-rules.pro, it fixed my issue.

**Comment by alicedomingueslok** [comment]
Hey, just an FYI

I'm a Support Engineer at Lokalise and we distribute an Android SDK runtime that is Retrofit dependent. If used with AGP 8 our app crashes in runtime.
We need to manually circumvent it using the proposed workaround of appending the missing Proguard rules to `.../proguard/retrofit2.pro`.

We are working tight with our clients experiencing such problems and looking into implementing such manual fix in our SDK runtime, so a manual intervention is not required.

**Comment by Goooler** [comment]
For ones who need this support, you can try out my fork, use `io.github.goooler.retrofit2:retrofit:2.10.0`, check https://github.com/Goooler/retrofit/releases/tag/2.10.0

**Comment by JakeWharton** [comment]
There will not be a 2.9.1. At some point there will be a 2.10.0, though.

**Comment by ubuntudroid** [comment]
@JakeWharton why not keep the issue open for 2.10.0 then? 👀

**Comment by JakeWharton** [comment]
Issues are closed when the fix lands into the repo as there is no longer any action to take on them.

**Comment by ubuntudroid** [comment]
Got it, I merely thought there was still some additional work or documentation planned on this topic as this issue was kept open for quite some time now even after the related change landed in trunk. 👍 Glad to hear that there are plans for a 2.10.0.

**Comment by JakeWharton** [comment]
Hopefully within a week! But maybe two...

**Comment by Funambol-Android-Developers** [comment]
@JakeWharton any news about the upcoming 2.10.0 release?

**Comment by JakeWharton** [comment]
No. Still planned.
