### ISSUE TITLE
Gradle bug fixed: "Setting JVM toolchain does not affect JavaCompile targetCompatibility value"

### ISSUE THREAD

**Issue by gardner** [square/retrofit#3890]
This Gradle issue has been resolved: https://issuetracker.google.com/issues/260059413
Please evaluate if this workaround can / should be removed from: https://github.com/square/retrofit/blob/59d302aedce5edae4806efac57b630d4fe8c27db/build.gradle#L118-L122

Please see [f62a2ec](https://android.googlesource.com/platform/tools/base/+/f62a2ec38b1cccada9a9534cb1d2fa9a10650b9d) for more information on the Gradle change.

**Comment by JakeWharton** [comment]
Thanks for the heads up. We have to jump to Gradle 8 then AGP 8 and then once AGP 8.1 is stable I'll try removing it.

**Comment by tspence1000** [comment]
Have a nice day

**Comment by JakeWharton** [comment]
Removed!
