### ISSUE TITLE
Reflective access report

### ISSUE THREAD

**Issue by mzattera** [square/retrofit#3900]
I have warning messages suggesting to report the below when using retrofit 2.9.0 in my application:

Can provide more info if  required.

```console
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by retrofit2.Platform (file:/D:/.m2/repository/com/squareup/retrofit2/retrofit/2.9.0/retrofit-2.9.0.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by nikam14** [comment]
@mzattera try using grovvy 3.x.

**Comment by adityajha1903** [comment]
Hey @mzattera, can u please tell me how you solved this issue?

**Comment by mzattera** [comment]
I didn't. It is still there.

**Comment by mzattera** [comment]
OK, it seems this appears when using JRE 11 but NOT when I use JRE 17.

Can therefore probably be closed.

**Comment by JakeWharton** [comment]
Very Bad™ reflection is the only solution for invoking default methods on Java 8 through Java 13. Java 14 allowed a normal lookup to succeed so we use that on 14 & 15. Java 16 added a proper public API for invoking default methods so we use that on 16 and newer.
