### ISSUE TITLE
retrofit I periodically get the error No address associated with hostname

### ISSUE THREAD

**Issue by Lyagaev** [square/retrofit#3915]
0

I periodically receive complaints from users that the application is working, they sent records on which it is clear that the Internet is available but the application does not receive data, added error logging for which I see that the error is "Unable to resolve host "site.ru": No address associated with hostname" I managed to catch such an error by turning off and on the mobile Internet and at some point the Internet is on and there is no access to it from the application, although if you open this URL from the same device in the browser, then it all works. Closing and opening the application does not help, it helps to either wait 5 minutes or close the application, turn off and turn on the Internet and open the application again.

I've looked at many threads on the forum but haven't been able to find an answer on how to fix this.

code retrofit

```
object NetworkService {
    const val BASE_URL_API = "https://sait.ru/"       
    private var mInstance: NetworkService = NetworkService
    private var mContext: Context? = null

    val gson = GsonBuilder().setDateFormat("yyyy-MM-dd'T'HH:mm:ss").create()
    private var mRetrofit: Retrofit = Retrofit.Builder()
        .baseUrl(BASE_URL_API)
        .addConverterFactory(GsonConverterFactory.create(gson))
        .callFactory(getOkHTTPClient())
        .build()
    fun getInstanceRetrofit(): NetworkService {
        return mInstance
    }

    fun getOkHTTPClient(): OkHttpClient {
        val client = OkHttpClient.Builder()
            .connectTimeout(10, TimeUnit.SECONDS)
            .addInterceptor(object : Interceptor {
                override fun intercept(chain: Interceptor.Chain): Response {
                    val request = chain.request()
                    val response: Response
                    try {
                        response = chain.proceed(request)
                    } catch (e: IOException) {
                        setError(e , request.url)
                        throw IOException("Network error", e)
                    }
                    return response
                }
            })
        return client.build()
    }

     fun setError(t: IOException, url: HttpUrl) {
         val db = Room.databaseBuilder(
             mContext!!,
             AppDatabase::class.java, "database-file-name.db"
         ).build()

         val current = LocalDateTime.now()
         var logError = Log(0, current.toString() + url.toString() + t.message, 0)

         GlobalScope.launch(Dispatchers.IO) {
             db.logDao().insert(logError)
         }
    }

    fun getJSONApi1(context: Context): NetworkAPI {
        mContext = context
        return mRetrofit.create(NetworkAPI::class.java)
    }

}
```
call

```
NetworkService.getInstanceRetrofit().getJSONApi(applicationContext)
            .login(login, password, pin, fcmToken).enqueue(object: Callback<Token> {
                override fun onResponse(call: Call<Token>, response: Response<Token>) {
                    if(response.isSuccessful && response.code() == 200){
                        // ....
                    }
                }

                override fun onFailure(call: Call<Token>, t: Throwable) {
                    textError!!.visibility = View.VISIBLE
                    textError!!.text = "Ошибка соединения с интернетом"
                }
            })
```
I tried to recreate mInstance when I got an error, this helped to some extent, now you don’t need to reconnect the Internet, but the request may not start working on the first try

```
object NetworkService {
    const val BASE_URL_API = "https://site.ru/"       
    private var mInstance: NetworkService? = null
    private var mContext: Context? = null

    val gson = GsonBuilder().setDateFormat("yyyy-MM-dd'T'HH:mm:ss").create()
    private var mRetrofit: Retrofit = Retrofit.Builder()
        .baseUrl(BASE_URL_API)
        .addConverterFactory(GsonConverterFactory.create(gson))
        .callFactory(getOkHTTPClient())
        .build()
    fun getInstanceRetrofit(): NetworkService {
        if (mInstance == null)
        {
            mInstance = NetworkService
        }
        return mInstance!!
    }

    fun getOkHTTPClient(): OkHttpClient {
        val client = OkHttpClient.Builder()
            .connectTimeout(10, TimeUnit.SECONDS)
            .addInterceptor(object : Interceptor {
                override fun intercept(chain: Interceptor.Chain): Response {
                    val request = chain.request()
                    val response: Response
                    try {
                        response = chain.proceed(request)
                    } catch (e: IOException) {
                        setError(e , request.url)
                        mInstance = null
                        throw IOException("Network error", e)
                    }
                    return response
                }
            })
        return client.build()
    }

     fun setError(t: IOException, url: HttpUrl) {
         val db = Room.databaseBuilder(
             mContext!!,
             AppDatabase::class.java, "database-file-name.db"
         ).build()

         val current = LocalDateTime.now()
         var logError = Log(0, current.toString() + url.toString() + t.message, 0)

         GlobalScope.launch(Dispatchers.IO) {
             db.logDao().insert(logError)
         }
    }

    fun getJSONApi(context: Context): NetworkAPI {
        mContext = context
        return mRetrofit.create(NetworkAPI::class.java)
    }
}
```

**Comment by shriharsha-bhagwat** [comment]
@Lyagaev Do we have any updates here? I am also facing a similar issue at the moment.

**Comment by JakeWharton** [comment]
Retrofit does not participate in any layer of the HTTP stack where it's in a position to affect this in any way. Retrofits job is to take your declarative function and turn it into an OkHttp request. Similarly, once OkHttp receives a response, Retrofit deserializes the body into your desired type. Any behavior of the actual HTTP client, such as the inability to resolve a domain name, is something that only OkHttp controls (and often may be beneath OkHttp, such as in the system DNS resolver). You should see the same behavior if you were to issue requests directly to OkHttp further emphasizing that Retrofit has no ability to affect change here.

**Comment by akardas16** [comment]
this is really annoying issue. We have got feedback from some users and they said app is staying in splash screen. After some debugging, all requests are "unable to resolve host ... No address associated with hostname" I have added ktor and it is working while retrofit gives error
<img width="926" alt="Screenshot_at_Nov_25_13-20-30" src="https://github.com/square/retrofit/assets/28716129/cf6911dc-5ef4-4ff7-9f48-072f0332dbf3">

**Comment by akardas16** [comment]
this is really annoying issue. We have got feedback from some users and they said app is staying in splash screen. After some debugging, all requests are "unable to resolve host ... No address associated with hostname" I have added ktor and it is working while retrofit gives error
<img width="926" alt="Screenshot_at_Nov_25_13-20-30" src="https://github.com/square/retrofit/assets/28716129/a9d1fd43-4150-4a80-9f9e-12363cbac24c">

**Comment by varuntribe** [comment]
We are also facing the same issue. They started randomly, I believe something has changed in last few Android OS updates, which is causing some sort of incompatibility issue with retrofit now. I might have to dig it a little more to get to the root of it. Also, really surprised to see RetroFit hasn't received any updates in last 3 years, we are still on 2.9.0.

**Comment by akardas16** [comment]
> We are also facing the same issue. They started randomly, I believe something has changed in last few Android OS updates, which is causing some sort of incompatibility issue with retrofit now. I might have to dig it a little more to get to the root of it. Also, really surprised to see RetroFit hasn't received any updates in last 3 years, we are still on 2.9.0.

I think times to move to Ktor. it is Kotlin official network library.

**Comment by varuntribe** [comment]
> > We are also facing the same issue. They started randomly, I believe something has changed in last few Android OS updates, which is causing some sort of incompatibility issue with retrofit now. I might have to dig it a little more to get to the root of it. Also, really surprised to see RetroFit hasn't received any updates in last 3 years, we are still on 2.9.0.
> 
> I think times to move to Ktor. it is Kotlin official network library.

I agree, I think it's time.

**Comment by JakeWharton** [comment]
Retrofit does not execute requests. OkHttp executes requests. OkHttp is also an engine behind ktor because ktor also does not execute requests. Both libraries make it easy to craft requests for actual engines to execute. And finally, the behavior here is specific to the execution of requests and not their creation. All of that to say, Retrofit cannot affect the behavior you are seeing in any way, and moving to ktor with OkHttp very well might exhibit the same exact behavior.

**Comment by akardas16** [comment]
> Retrofit does not execute requests. OkHttp executes requests. OkHttp is also an engine behind ktor because ktor also does not execute requests. Both libraries make it easy to craft requests for actual engines to execute. And finally, the behavior here is specific to the execution of requests and not their creation. All of that to say, Retrofit cannot affect the behavior you are seeing in any way, and moving to ktor with OkHttp very well might exhibit the same exact behavior.

I have tried with Ktor **Android** engine and while retrofit gives the issue, Ktor is working well.

**Comment by JakeWharton** [comment]
Feel free to file an issue against OkHttp then. Retrofit plays no part in any of this behavior.

**Comment by varuntribe** [comment]
Thanks @JakeWharton , I will report the issue to OkHttp as well.

**Comment by akardas16** [comment]
> Thanks @JakeWharton , I will report the issue to OkHttp as well.

https://github.com/square/okhttp/issues/7677 I think this is related issue

**Comment by Areeb786123** [comment]
facing same issue
