### ISSUE TITLE
HTTP FAILED: java.lang.NullPointerException

### ISSUE THREAD

**Issue by rushitD2** [square/retrofit#3925]
Hello, Hope you are doing well.

I am using interceptor to passing header into the request. But getting error "HTTP FAILED: java.lang.NullPointerException" So can you please let me know what is reason for it? Without interceptor API response is getting but when I add interceptor above mentioned error is getting. So can you please guide me for this?

Here is version of retrofit
```
implementation 'com.squareup.retrofit2:retrofit:2.9.0'
implementation 'com.squareup.okhttp3:okhttp:4.9.1'
implementation 'com.squareup.okhttp3:okhttp-urlconnection:3.12.1'
implementation 'com.squareup.okhttp3:logging-interceptor:4.9.1'
```

Here is some part of code
```
val interceptor = HttpLoggingInterceptor()
interceptor.setLevel(HttpLoggingInterceptor.Level.BODY)
httpClient.addInterceptor(interceptor)
httpClient.addInterceptor(Interceptor { chain ->
                val preferenceManagerClass =
                    PreferenceManagerClass(TwanApplication.getContext())

                var token = ""

                if (!preferenceManagerClass.getValueString(Constant.AUTHORIZATION)
                        .isNullOrEmpty()
                ) {
                    httpClient.addInterceptor(interceptor)
                    token = preferenceManagerClass.getValueString(Constant.AUTHORIZATION)!!
                }
                val original = chain.request()
                val requestBuilder = original.newBuilder()
                    .addHeader(
                        "Authorization", "Bearer $token"
                    )
                Log.e("Authorization", "Authorization:====>   Bearer $token")

                val request = requestBuilder.build()
                val response = chain.proceed(request)

                if (response.code == 401) {
                    //logout code
                }
                response

            })
```

And here is the error which getting
`I/okhttp.OkHttpClient: <-- HTTP FAILED: java.lang.NullPointerException`

**Comment by JakeWharton** [comment]
Best guess is that your interceptor code is crashing, but the full stack trace would be needed to know. If the exception is being logged by OkHttp logging it occurs at a layer beneath Retrofit and therefore there is nothing that Retrofit can do to really affect the behavior.

**Comment by rushitD2** [comment]
Here is full stack trace of API calling, Please check

```
I/okhttp.OkHttpClient: Content-Type: application/json; charset=UTF-8
I/okhttp.OkHttpClient: Content-Length: 100
I/okhttp.OkHttpClient: {"mailto:email":"abc@gmail.com","password":"999999999","device_token":"test","device_type":"A"}
I/okhttp.OkHttpClient: --> END POST (100-byte body)
I/okhttp.OkHttpClient: <-- HTTP FAILED: java.lang.NullPointerException
I/DecorView: [INFO] isPopOver=false, config=false
I/DecorView: updateCaptionType >> DecorView@a41442f[], isFloating=true, isApplication=true, hasWindowDecorCaption=false, hasWindowControllerCallback=false
D/DecorView: setCaptionType = 0, this = DecorView@a41442f[]
D/InputTransport: Input channel constructed: 'cddc43c', fd=105
I/ViewRootImpl@f2a6741[LoginActivity]: setView = com.android.internal.policy.DecorView@a41442f TM=true
I/ViewRootImpl@f2a6741[LoginActivity]: dispatchDetachedFromWindow
D/InputTransport: Input channel destroyed: 'cddc43c', fd=105
I/SurfaceControl: nativeRelease nativeObject s[503262816928]
I/SurfaceControl: nativeRelease nativeObject e[503262816928]
I/SurfaceControl: nativeRelease nativeObject s[503256153600]
I/SurfaceControl: nativeRelease nativeObject e[503256153600]
I/SurfaceControl: nativeRelease nativeObject s[503262817024]
I/SurfaceControl: nativeRelease nativeObject e[503262817024]
I/SurfaceControl: nativeRelease nativeObject s[503412999296]
I/SurfaceControl: nativeRelease nativeObject e[503412999296]
I/ViewRootImpl@eb6b998[LoginActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager: prepareNavigationBarInfo() DecorView@3a6bfa[LoginActivity]
D/InputMethodManager: getNavigationBarColor() -855310
I/ViewRootImpl@eb6b998[LoginActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
```

**Comment by JakeWharton** [comment]
Those are the surrounding logs. Without the stacktrace from the `NullPointerException` it's going to be impossible to know what's going on.

Really seems like OkHttp's logger should dump the whole stack by default regardless of your logging level.

**Comment by rushitD2** [comment]
Can you please let me know how can I can whole stacktrace? Actually I have shared you entire log what I am getting. Do I need to do something different?

**Comment by behzodhalil** [comment]
@rushitD2 You can add the filter option `-is:stacktrace` for your logcat.

**Comment by JakeWharton** [comment]
The "HTTP FAILED" message comes from here: https://github.com/square/okhttp/blob/5d8e2d373185d0870336e4f8111686395e2a5cdf/okhttp-logging-interceptor/src/main/kotlin/okhttp3/logging/HttpLoggingInterceptor.kt#L233-L238

It indicates that your interceptor is throwing an exception, as expected. The exception is rethrown and so it should be going _somewhere_. If it is neither being logged nor crashing your application then that's a fairly significant OkHttp problem.

Please file a bug on OkHttp at https://github.com/square/okhttp/issues/new/choose since it seems to be swallowing exceptions and making debugging impossible.

For now, if you simply want to get unblocked, wrap your entire interceptor in a `try`/`catch` and log the full stacktrace of the exception yourself. This will show you the problem with your interceptor code and allow you to move forward with fixing it in the mean time.
