### ISSUE TITLE
Apply @Path to base url as well

### ISSUE THREAD

**Issue by bogdan-pechounov** [square/retrofit#3973]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [x ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I would like to have a dynamic base url to change the language code `"https://{languageCode}.wikipedia.org/w/"` (user can change the language). For now, I simply overwrite the base url `@GET("${BASE_URL}api.php?action=query&format=json&list=random&rnnamespace=0&rnlimit=5")` so that `@Path` works.

```
import com.uzential.speedreadingendless.api.wikipedia.responses.RandomArticleResponse
import retrofit2.http.GET
import retrofit2.http.Path

const val BASE_URL = "https://{lang}.wikipedia.org/w/"

interface WikipediaApi {

    @GET("${BASE_URL}api.php?action=query&format=json&list=random&rnnamespace=0&rnlimit=5")
    suspend fun getRandomArticles(
        @Path("lang") lang: String = "ru"
    ): RandomArticleResponse
}
```
Otherwise, I would get a `IllegalArgumentException`.
```
java.lang.IllegalArgumentException: URL "api.php?action=query&format=json&list=random&rnnamespace=0&rnlimit=5" does not contain "{lang}". (parameter #1)
		for method WikipediaApi.getRandomArticles
	at retrofit2.Utils.methodError(Utils.java:54)
	at retrofit2.Utils.methodError(Utils.java:43)
	at retrofit2.Utils.parameterError(Utils.java:64)
	at retrofit2.RequestFactory$Builder.validatePathName(RequestFactory.java:829)
	at retrofit2.RequestFactory$Builder.parseParameterAnnotation(RequestFactory.java:416)
	at retrofit2.RequestFactory$Builder.parseParameter(RequestFactory.java:325)
	at retrofit2.RequestFactory$Builder.build(RequestFactory.java:206)
	at retrofit2.RequestFactory.parseAnnotations(RequestFactory.java:67)
	at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:26)
	at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:202)
	at retrofit2.Retrofit$1.invoke(Retrofit.java:160)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
...
```

**Comment by ritikverma2000** [comment]
Hi @bogdan-pechounov would like to work on this issue.

**Comment by Goooler** [comment]
Which version you are using, I can't repro this with `2.9.0`

```kt
interface WikipediaApi {

  @GET("${BASE_URL}api.php?action=query&format=json&list=random&rnnamespace=0&rnlimit=5")
  suspend fun getRandomArticles(
    @Path("lang") lang: String = "en",
  ): Map<String, Any>

  companion object {
    private const val BASE_URL = "https://{lang}.wikipedia.org/w/"
  }
}
```

**Comment by bogdan-pechounov** [comment]
@Goooler I am using "com.squareup.retrofit2:retrofit:2.9.0". The issue happens when I don't overwrite the base url in the `@GET` request. It's just a minor inconvenience. 

```
@Module
@InstallIn(SingletonComponent::class)
object ApiModule {

    @Singleton
    @Provides
    fun provideWikipediaApi(): WikipediaApi = Retrofit.Builder()
        .addConverterFactory(GsonConverterFactory.create())
        .baseUrl(BASE_URL) // needs to be overwritten
        .build()
        .create(WikipediaApi::class.java)
}
```

```
interface WikipediaApi {

    @GET("api.php?action=query&format=json&generator=random&grnlimit=1&grnnamespace=0&prop=info")
    suspend fun getRandomArticleInfo(
        @Path("lang") lang: String
    ): RandomArticleInfoResponse
}
```

**Comment by Goooler** [comment]
You should override `baseUrl`, that's the right access.
