### ISSUE TITLE
There's no artifact asociated with converter-kotlinx-serialization in Maven Central

### ISSUE THREAD

**Issue by yamin8000** [square/retrofit#4003]
According to [repo's doc](https://github.com/square/retrofit/tree/master/retrofit-converters/kotlinx-serialization) kotlinx-serialization can be added with this artifact name: `com.squareup.retrofit2:converter-kotlinx-serialization`, however, there's no artifact with that name in Maven Central.
https://central.sonatype.com/artifact/com.squareup.retrofit2/converter-kotlinx-serialization
What am I missing here?

**Comment by JakeWharton** [comment]
It has just been merged but not released. GitHub does not let us differentiate between the released code and our integration branch. There should be a release in the next 6 to 8 weeks that will contain this artifact.

**Comment by JakeWharton** [comment]
For now, https://github.com/JakeWharton/retrofit2-kotlinx-serialization-converter still works great.

**Comment by yamin8000** [comment]
> For now, https://github.com/JakeWharton/retrofit2-kotlinx-serialization-converter still works great.

Thanks.
