### ISSUE TITLE
Is Retrofit supported on API level 17 for API calling?

### ISSUE THREAD

**Issue by HirenBharodiya** [square/retrofit#4010]
I'm currently working on a project that targets API level 17, and I'm considering using Retrofit for API calls. However, I couldn't find clear information about whether Retrofit supports API level 17. Could you please clarify whether Retrofit is compatible with API level 17 or if there are any specific considerations I should be aware of?

Thanks!

**Comment by JakeWharton** [comment]
We do not support anything below 21. However, it still might work, we simply don't actively support it. You'll just have to try. Retrofit itself doesn't really have any API restrictions, but OkHttp which is the HTTP client beneath it only supports API 21 and newer.
