### ISSUE TITLE
Upgrading OkHTTP to 5.0.0

### ISSUE THREAD

**Issue by UKMIITB** [square/retrofit#4020]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [X] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.
       
       
       https://square.github.io/okhttp/changelogs/changelog/
       OkHTTP 5.0 is on its way. And currently the latest retrofit is dependent on retrofit 3.14.9
       
       When can we expect updating the dependency

**Comment by JakeWharton** [comment]
OkHttp 5.x is not stable and therefore can't be used.

OkHttp 4.x is written in Kotlin and we're not ready to inflict the Kotlin stdlib dependency on our consumers at this time.

The general plan is:
- Release 2.10 and other 2.x's with the changes on master.
- Release 3.0 as binary and behavioral compatible with 2.x but rewritten in Kotlin with OkHttp 4.x (or 5.x) as a dependency.
- Release 4.0 with breaking changes (following our breaking policy) as Kotlin multiplatform and depending on OkHttp 5.x's multiplatform abstraction.
   - #3181 

Retrofit 2.10 will be released within a month or so. There is no timeline for anything else at this time.
