### ISSUE TITLE
converter-kotlinx-serialization artifact is missing

### ISSUE THREAD

**Issue by curioussabhi** [square/retrofit#4026]
There doesn't seem to be an artifact for `converter-kotlinx-serialization`, even though the repository contains code for it: https://github.com/square/retrofit/tree/master/retrofit-converters/kotlinx-serialization

0 results found at https://central.sonatype.com/search?q=g:com.squareup.retrofit2%20a:converter-kotlinx-serialization&smo=true

**Comment by JakeWharton** [comment]
It has not been released yet. It will be included in the next release, 2.10.

**Comment by JakeWharton** [comment]
You can use https://github.com/JakeWharton/retrofit2-kotlinx-serialization-converter/ for now
