### ISSUE TITLE
How to hide sensitive information from response header?

### ISSUE THREAD

**Issue by P01ARPITJ** [square/retrofit#4034]
Hello Team, 
I am using Retrofit library for Api calls. now i am getting some values in headers response like server details, tokens etc.
is there any way to hide the values from response header.
I thought to add interceptor but i think its work for header request call, not for response.

**Comment by JakeWharton** [comment]
Hide from whom?

**Comment by P01ARPITJ** [comment]
Hi @JakeWharton, Thanks for immediate response. 
Actually, I am calling Api and getting success response with body and headers. 
Now headers contain some sensitive information's so i want to hide those values.
 
like in logs :

2024-01-18 16:32:36.803 6625-6934/com.**********.debugD/OkHttp: server_value: "test123445"

so i want to hide this value or change with blank strings.
