### ISSUE TITLE
[Bug?] When the http request executes finished. The coroutine scope still alive.

### ISSUE THREAD

**Issue by PeanutMelonSeedBigAlmond** [square/retrofit#4073]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I'm not sure this is a problem or not. When I using retrofit with coroutines, the http request execute finished and the so-called main coroutine scope does not exit immediately. Instead, it exited and my application finished about 2 mins later.

Here are my code.

```kotlin
fun main() = runBlocking {
    println(Client.test())
}

interface Api {
    @GET("/get")
    suspend fun test(): String
}

object Client {
    private val service = Retrofit.Builder()
        .baseUrl("https://httpbin.org")
        .addConverterFactory(ScalarsConverterFactory.create())
        .build()
        .create(Api::class.java)

    suspend fun test() = withContext(Dispatchers.IO) { service.test() }
}
```

Is a JVM application, not Android. My dependencies version are below:

```kotlin
implementation("com.squareup.okhttp3:okhttp:5.0.0-alpha.12")
implementation("com.squareup.retrofit2:converter-scalars:2.9.0")
implementation("com.squareup.retrofit2:retrofit:2.9.0")
implementation("com.squareup.okio:okio:3.7.0")
```

**Comment by JakeWharton** [comment]
It has nothing to do with the coroutine scope. `runBlocking` will successfully exit, but the main thread will stay active because OkHttp is holding onto connections.

See "Shutdown Isn't Necessary" on https://square.github.io/okhttp/5.x/okhttp/okhttp3/-ok-http-client/index.html as to how you can eagerly shut down an `OkHttpClient`'s resources to allow the program to exit normally.
