### ISSUE TITLE
Feature Request - Upgrade to okhttp3 version 4.x.y

### ISSUE THREAD

**Issue by rolandhaas** [square/retrofit#4074]
Feature Request
Retrofit uses major 3 version of okhttp3. This version is from the year 2020 and has - according to https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp/3.14.9 - some vulnerabilities.

Using retrofit causes some dependency conflicts when using the latest version of okhttp

It would be nice to upgrade to major 4 (currently 4.12.0). Is there a reason for not upgrading? Should the renovate coniguration also be adjusted to have minor/major upgrades?

**Comment by JakeWharton** [comment]
OkHttp 4.x is written in Kotlin and we are not ready to force that dependency onto our users.

See plan here https://github.com/square/retrofit/issues/4020#issuecomment-1870586604
