### ISSUE TITLE
Security issue: Information Exposure

### ISSUE THREAD

**Issue by Duna** [square/retrofit#4083]
SNYK is exposing new security issue for Retrofit 2.9.0. 
Moreover we do not see any release since 2020. 
Some security issues needs to be addressed in the next release.

Here it is the issue: https://security.snyk.io/vuln/SNYK-JAVA-COMSQUAREUPOKHTTP3-2958044

**Comment by JakeWharton** [comment]
You can bump the OkHttp dependency in your project. We will not be bumping it at this time. The plan is here https://github.com/square/retrofit/issues/4020#issuecomment-1870586604.
