### ISSUE TITLE
Getting message as empty when response is not successful

### ISSUE THREAD

**Issue by Akshaya-Amar** [square/retrofit#4096]
https://api.spoonacular.com/recipes/random?number=99

Issue - Message is always empty when the response is not successful. 

Steps to reproduce - 
suspend fun getRecipes(): Response<List<Recipe>> {
        try {
            val response = apiService.getRecipes("99")
            if (response.isSuccessful) {
                response.body()?.let { data ->
                    if (data.recipes.isNullOrEmpty().not()) {
                        return Response.Success(data = data.recipes!!)
                    } else {
                        return Response.Error(message = "Empty Data")
                    }
                } ?: run {
                    return Response.Error(message = "Empty Data")
                }
            } else {
                return Response.Error(message = response.message()) // message is empty when response is not successful
            }
        } catch (exception: Exception) {
            return Response.Error(message = exception.message)
        }
    }

**Comment by JakeWharton** [comment]
`Response.message()` returns the HTTP status message.

According to `curl` that API does not include one, only a status code:
```
$ curl -I https://api.spoonacular.com/recipes/random?number=99
HTTP/2 401
date: Wed, 13 Mar 2024 13:05:42 GMT
content-type: text/html;charset=utf-8
allow-control-allow-origin: *
access-control-allow-origin: *
access-control-allow-headers: Authorization, UserId, Hash, Name, Password, Accept, Accept-Language, x-api-key, Content-Language, Content-Type, Cache-Control, Origin, X-Requested-With
access-control-allow-methods: GET, HEAD, POST, OPTIONS, DELETE, PUT
allow-control-allow-methods: GET, HEAD, POST, OPTIONS, DELETE, PUT
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=xrW3iM%2FxjO9X1pgJuNu2i0wNoLvQ6bKe7u%2BViCdhclgkxO5sakPYHRNCHiZeBJUzGK2o9noViImRzP%2FEzFROEF12Rv0Am%2FakOvWdJ2DuRMFVxreczUD7jV0tvqujAUFLcda4FI0%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 863c3caeb9c307d3-IAD
alt-svc: h3=":443"; ma=86400
```

If you want to extract the message from the JSON body you will need to deserialize the `Response.errorBody()`. Here's a sample that showcases how to do that: https://github.com/square/retrofit/blob/trunk/samples/src/main/java/com/example/retrofit/DeserializeErrorBody.java
