### ISSUE TITLE
Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.5.1.

### ISSUE THREAD

**Issue by fparkarenet** [square/retrofit#4111]
I am getting issue as below.

.gradle/caches/transforms-3/b85d3ca1d1a3ee19e6a335126cc9759f/transformed/jetified-retrofit-2.10.0.jar!/META-INF/retrofit.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.5.1.

Below is what I have

    implementation 'com.squareup.okhttp:okhttp:2.7.5'
    implementation 'com.jakewharton.retrofit:retrofit2-rxjava2-adapter:1.0.0'
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2+'
    implementation "com.squareup.retrofit2:retrofit:2.4.0"
    implementation "com.squareup.retrofit2:converter-gson:2.4.0"
    implementation 'com.squareup.okhttp3:logging-interceptor:3.11.0'

Any idea why I am getting this error all of sudden.

Note : It was working fine till morning of 19 Mar 2024. From afternoon I start getting these errors.

<hr>

Even I tried with below but still same issue persists

    implementation "com.squareup.retrofit2:retrofit:2.10.0"

**Comment by JakeWharton** [comment]
You are using a wildcard for the `adapter-rxjava2` artifact. If you want to use an old version, specify the version exactly like you do with the other artifacts to avoid pulling in the latest.

**Comment by fparkarenet** [comment]
Below is what I updated

In project build.gradle made below changes

buildscript {
    ext.kotlin_version = "1.9.0"
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

In app, build.gradle

implementation "com.squareup.retrofit2:retrofit:2.10.0"
