### ISSUE TITLE
Exception on api calling with Okhttp

### ISSUE THREAD

**Issue by pankajtalaviya97** [square/retrofit#4118]
Fatal Exception: java.lang.IllegalStateException
closed
        okio.RealBufferedSource.request (RealBufferedSource.kt:206)
        okhttp3.logging.HttpLoggingInterceptor.intercept (**HttpLoggingInterceptor.kt:248**)
        okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
        okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp (RealCall.kt:201)
        okhttp3.internal.connection.RealCall$AsyncCall.run (RealCall.kt:517)
        java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1145)

**Comment by JakeWharton** [comment]
Your issue has almost no information and as such it is impossible to diagnose the problem. There is no Retrofit in the stack trace so Retrofit is unlikely to be the cause. There is no versioning information so we don't even know what versions of OkHttp you are using. We have no way of knowing how you made the request and how your client is configured and whether that contributes.

If you are using the latest stable OkHttp (4.12.0) and have tried the latest alpha as well (5.0.0-alpha.12) and the problem still persists, I would suggest filing a bug on the OkHttp repo: https://github.com/square/okhttp/issues/new/choose
