### ISSUE TITLE
[THANK YOU] Jake Wharton - you are the Godfather of the Android! 

### ISSUE THREAD

**Issue by cj-marius-duna** [square/retrofit#4127]
Not much of a problem.

We'd like to express our gratitude to Jake for his contributions to open source, as he serves as a wellspring of inspiration that guides us along the correct path!

**Comment by pess0a** [comment]
But he said that okhttp and retrofit doesn't have prevision for multiplataform so these libs will be dead soon

**Comment by JakeWharton** [comment]
@cj-marius-duna Thanks. There's a lot of people at Square and Cash App who help make these libraries happen, though. And, of course, numerous contributions from those in the community as well which have been instrumental in their success.
