### ISSUE TITLE
Jackson dependency version breaks Android 21+ minimum contract

### ISSUE THREAD

**Issue by kmayoral** [square/retrofit#4150]
The main [README](https://github.com/square/retrofit?tab=readme-ov-file#download) states:
> Retrofit requires at minimum Java 8+ or Android API 21+.

However, I noticed that the Jackson dependency version defined here:
https://github.com/square/retrofit/blob/15b162eccdc417caa08f28ff6d8f9b6ff57ac1ae/gradle/libs.versions.toml#L23

impacts the actual minimum runtime Android OS version supported as defined in the jackson-databind compatibility readme [here](https://github.com/FasterXML/jackson-databind?tab=readme-ov-file#compatibility):

```
Android
List is incomplete due to compatibility checker addition being done for Jackson 2.13.

2.13: Android SDK 24+
2.14: Android SDK 26+
2.15: Android SDK 26+
2.16: Android SDK 26+
```

So it seems that the release specific minimum Android API versions should be documented as:
- Retrofit 2.9.0 (using jackson-databind 2.13.x) - Android SDK 24+
- Retrofit 2.10.0 (using jackson-databind 2.14+) - Android SDK 26+
- Retrofit 2.11.0 (using jackson-databind 2.17.1 currently) - Android SDK 26+

For my purposes, I'll be reverting back to Retrofit `2.9.0` for now since I have a min sdk 24+ requirement in my app but I'm unsure if the resolution in this codebase should be to simply update the readme or revert the jackson version upgrades to `2.12.x` (or maybe `2.13.x` if retrofit wants to update to min sdk 24+ as well). Looking more at the latest jackson-databind [releases](https://github.com/FasterXML/jackson-databind/tags), I do see that version `2.12.7.2` was released 3 weeks ago and `2.13.5` was last released in January of 2023, so it seems that they do appear to be partially supporting older minor release versions along with the newer releases....

**Comment by JakeWharton** [comment]
There's no reason to downgrade Retrofit. You can force the Jackson version to be older in your build for compatibility with lower API levels. Also note that statement in the README is really just about the core of Retrofit. We don't control the compatibility of serialization libraries. We merely provide convenience bridges to using them.

Please see https://github.com/square/retrofit/issues/4131#issuecomment-2077300121 for more info on why we have to use newer versions of Jackson.

**Comment by kmayoral** [comment]
Ah, of course, great point about just forcing the version of Jackson on my end! Thanks for the quick response, closing this for now.
