### ISSUE TITLE
Does adding ProGuard rules for Okio still require in 2.11.0?

### ISSUE THREAD

**Issue by ArcherEmiya05** [square/retrofit#4171]
Upon reading and navigating in `README.md`, the link for Okio's ProGuard rules does not or no longer exist? Does it mean we no longer need it? Which version of AGP makes it optional?

**Comment by JakeWharton** [comment]
You haven't needed to copy rules manually in like 5 years now for Android. It's only for non-Android usage that you would have to copy the rules.
