### ISSUE TITLE
GsonConverterFactory not able to access in Android release build

### ISSUE THREAD

**Issue by TippuFisal** [square/retrofit#4182]
While creating a release build in Android Studio, I am getting the error 'Unresolved reference: GsonConverterFactory' or Gson. How can I resolve this issue?

Use Case:

I can run the app successfully
I can Take generated signed debug build
Not Able to take generated signed release build its shows an above error.

Libraries files i added:

[versions]
retrofit = "2.9.0"
okhttp = "4.12.0"
googleGson = "2.10.1"

[libraries]
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
google-gson = { module = "com.google.code.gson:gson", version.ref = "googleGson" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

**Comment by JakeWharton** [comment]
Without a sample that demonstrates the problem it's going to be impossible to discern the underlying cause, but it's something in your build setup and not specific to Retrofit itself.

Best I can guess without seeing anything is to say clean your IDE caches and ensure your dependencies are not added to variant-specific configurations (like `debugImplementation`).

**Comment by TippuFisal** [comment]
I mentioned my library files which are included in build configuration and i did not add any debug implementation, i believe the implementation is correct as I follow the official document.

Kindly assist me with solutions or the root cause.

**Comment by TippuFisal** [comment]
Issue resolved, thanks for assisting me, I added in **debugImplementation**.

Thanks team
