### ISSUE TITLE
[Feature Request]Header support in Converter

### ISSUE THREAD

**Issue by ZAsheesh** [square/retrofit#4193]
I'm working on building a comprehensive page performance framework, and as part of this, I'm developing a sub-framework for network performance. One challenge I'm facing is linking the parsing time to a specific request. Although I have a request ID to identify requests, the lack of access to headers in the Converter is preventing me from making this connection. Is it possible to add support for headers in the Converter?

**Comment by JakeWharton** [comment]
Not without doing a breaking API change. This is tracked by #2987.
