### ISSUE TITLE
Retrofit  Kotlin examples

### ISSUE THREAD

**Issue by Amir-yazdanmanesh** [square/retrofit#4205]
Why doesn't Retrofit have any Kotlin examples? Can I write some sample examples and submit a PR?

**Comment by shubhamdevgupta** [comment]
yes you can , just create  request and response class for the api and create a pr

**Comment by JakeWharton** [comment]
There are no Kotlin examples for the same reason there are no Scala or Clojure examples: Retrofit is fundamentally a Java library. Aside from `suspend fun` support, all of the features are the same in Java as they are in Kotlin, and users can trivially convert the Java examples into whichever JVM language they want. The only example I'd accept a PR for in Kotlin would be for showing off `suspend fun`.
