### ISSUE TITLE
Return an EnumConverter for GsonConverterFactory#stringConverter

### ISSUE THREAD

**Issue by tisonkun** [square/retrofit#4278]
> Here is my implementation that maybe helpful:
> 
> 
> ```java
> private static final class EnumConverterFactory extends Converter.Factory {
>     private EnumConverterFactory() {}
> 
>     @Override
>     public Converter<?, String> stringConverter(
>             @NotNull Type type, Annotation @NotNull [] annotations, @NotNull Retrofit retrofit) {
>         if (getRawType(type).isEnum()) {
>             return new EnumConverter();
>         }
>         return null;
>     }
> 
>     private static final class EnumConverter implements Converter<Enum<?>, String> {
>         @Override
>         public String convert(@NotNull Enum<?> o) {
>             try {
>                 final Field f = o.getClass().getField(o.name());
>                 final SerializedName name = f.getAnnotation(SerializedName.class);
>                 if (name != null) {
>                     return name.value();
>                 }
>             } catch (Exception ignored) {
>                 // passthrough
>             }
>             return o.name();
>         }
>     }
> }
> ```
> 
> I suppose it's possible to add in `com.squareup.retrofit2:converter-gson`. Either as the return value of `GsonConverterFactory#stringConverter `, or a new `GsonEnumConverterFactory`. 

 _Originally posted by @tisonkun in [#711](https://github.com/square/retrofit/issues/711#issuecomment-2561728376)_

**Comment by JakeWharton** [comment]
This is a bit too niche for inclusion in the main converter. Plus adding it has the potential to break existing users. I will point future travelers to your implementation, though, if they need such a thing.
