### ISSUE TITLE
Observable is not respecting subscribeOn

### ISSUE THREAD

**Issue by doapp-grady** [square/retrofit#430]
In an Android app, I am using retrofit's observables. I am running into an issue where the observable is not respecting my observeOn. Here is what I am hoping my code would look like: 

@GET("/foo.gz")
public Observable<Foo> getFoo();
...

RestAdapter restAdapter = new RestAdapter.Builder()
  .setServer("http://fooprovider.com")
  .build();
FooApi apiManager = restAdapter.create(FooApi.class);
apiManager.getFoo()
  .subscribeOn(Schedulers.newThread())
  .observeOn(AndroidSchedulers.mainThread())
  .subscribe(new SettingsObserver(this));

Right now I believe I have a few options to get network off the main thread. I can wrap this in a callable which executes on a different thread. I can have my Api return Foo and build my own Observable. Or I can pass in an httpExecutor and callbackExecutor to my restAdapter. 

I feel like none of those solutions look as clean as my sample code.

**Comment by briandilley** [comment]
@JakeWharton is this still true of retrofit 2?

**Comment by briandilley** [comment]
I think i see in `RxJavaCallAdapterFactory` where we can specify the default scheduler... i assume that's what i should use then.

**Comment by JakeWharton** [comment]
2 is synchronous by default

**Comment by briandilley** [comment]
Ok, so then i need to call `subscribeOn(Schedulers.io())` to make sure the network call happens on the IO thread.  And the code in `master` has a way to set a default scheduler for `RxJavaCallAdapterFactory` via: `RxJavaCallAdapterFactory.create(Schedulers.io())`

**Comment by JakeWharton** [comment]
Yep! You got it.

**Comment by lukaszkalnik** [comment]
Just to clarify: is it enough to just set default scheduler in my `Retrofit` object by calling `RxJavaCallAdapterFactory.create(Schedulers.io())` (making the call asynchronous) or should I also later call `subscribeOn(Schedulers.io())` when subscribing to the created Retrofit `Observable`?

Do these calls effectively duplicate each other's behavior in this case?

My goal is simply to make an async network call and report the result back to the main thread.

**Comment by JakeWharton** [comment]
> Do these calls effectively duplicate each other's behavior in this case?

yes
