### ISSUE TITLE
Multipart data uploading progress bar

### ISSUE THREAD

**Issue by egor-n** [square/retrofit#431]
Is there a way to show an uploading progress bar while making a `@Multipart` request?

**Comment by philipgiuliani** [comment]
Thanks for the solution on StackOverflow! Works fine.

**Comment by davicdsalves** [comment]
I'm glad it worked for you @philipgiuliani. Maybe it could be an official solution?

**Comment by DavidMihola** [comment]
I tried this and observed that while it took only a few seconds for writeTo() to go through all of a 4MB image file I only received a response from our server about a minute later:

06-11 21:42:50.005  17539-21710/com.our.app.dev D/Retrofit﹕ ---> END HTTP (4121330-byte body)
06-11 21:42:50.105  17539-21710/com.our.app.dev D/dalvikvm﹕ GC_FOR_ALLOC freed 15882K, 28% free 58773K/80988K, paused 42ms, total 42ms
06-11 21:43:39.635  17539-21710/com.our.app.dev D/Retrofit﹕ <--- HTTP 200 http://app.dev.our-server.com/webservice/api/Image/upload (49634ms)

The effect of course is that the progress bar fills very quickly but then it takes a long time for the actual response to arrive.

Is that because writeTo writes to some kind of buffered stream and therefore the time that writeTo takes does not really reflect the time it takes the data over the net? Or is that because our server itself took so long to process the image?

I am sorry I have to ask, but I don't know Retrofit's internals well enough to know what's going on here...

**Comment by davicdsalves** [comment]
@DavidMihola i saw it happening as well, it just takes more seconds to write the last bytes.
To fix that just change the order of the listener
Instead of 
```
            this.listener.transferred(total);
            out.write(buffer, 0, read);
```
Use
```
            out.write(buffer, 0, read);
            this.listener.transferred(total);
```
That should give you a better feedback when the upload finishes.

**Comment by DavidMihola** [comment]
@davicdsalves That makes sense, thank you!

I still have the feeling that the actual sending of the request takes somewhat longer than the feedback seems to indicate but I haven't had the time to actually watch it with Wireshark or something...

**Comment by duckinferno** [comment]
@DavidMihola Chances are you have the log level set to include the body.  In order to log the body, it essentially goes through the whole rigamarole of writing the request, but to your device's memory rather than the network.  You thus may be seeing the logging output rather than the actual transmission?  Try using a lower log level

**Comment by androiddev-smartside** [comment]
@davicdsalves thanks for your solution, however when uploading image from a camera, I don't have a File object, so I use TypedByteArray( mimeString, bytesFromCamera)  instead.
I peaked into  the TypedBytedArray source but couldn't understand how I could integrate your solution.

**Comment by philipgiuliani** [comment]
@androiddev-smartside checkout this one!

ProgressiveTypedByteArray:
https://github.com/OneDrive/onedrive-explorer-android/blob/master/app/src/main/java/com/microsoft/onedrive/apiexplorer/ProgressiveTypedByteArray.java

ProgressListener:
https://github.com/OneDrive/onedrive-explorer-android/blob/master/app/src/main/java/com/microsoft/onedrive/apiexplorer/ProgressListener.java

You can easily create your own one. Just copy the **ProgressiveTypedByteArray** from the lib and adapt it to have a ProgressListener.

**Comment by androiddev-smartside** [comment]
@philipgiuliani  wow, all of a sudden I love Microsoft OneDrive, who could tell!   Thanks, that one seems to work fine so far.

**Comment by DavidMihola** [comment]
@duckinferno Yes, that was indeed the case - I set the log level to BASIC and now the updates align a lot better with my subjective feeling of the upload (I still haven't checked the actual transfer with Wireshark but now after the 100% it takes only one or two seconds for the response to arrive, so I think that should be OK).

**Comment by davicdsalves** [comment]
I'm amazed that this is still a hot topic and often I get an upvote on SO. I'm not following retrofit development anymore, but it doesn't have an official solution for this on the last versions?

**Comment by JakeWharton** [comment]
Retrofit 2 uses OkHttp and progress for OkHttp can be found @ https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/com/squareup/okhttp/recipes/Progress.java

**Comment by DavidMihola** [comment]
@davicdsalves @JakeWharton Thank you for pointing out that Retrofit 2 can do this out of the box. I just thought that I should confirm @duckinferno's solution - better late than never.

**Comment by shahinfasihi** [comment]
hi, this link can be very helpful
https://gist.github.com/eduardb/dd2dc530afd37108e1ac
after all
i use this and try to explain it simply (if i am wrong fix me ,tnx ;)  )
first get this class 
https://gist.github.com/shahinfasihi/b9f33883aa0b506acfa1
and after that copy these Lines in your AsyncTask doInBackground Method 
https://gist.github.com/shahinfasihi/67f9b1f44dddf57f64c5
i am using these hope to work fine for you

**Comment by priyochatterjee08** [comment]
@JakeWharton 
https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/com/squareup/okhttp/recipes/Progress.java..... This link does not exist.

**Comment by JakeWharton** [comment]
`Progress.java` under https://github.com/square/okhttp/blob/master/samples/guide

**Comment by alexnavarro** [comment]
@JakeWharton  It's not an Android example. Can you have any Android example? Thanks

**Comment by davicdsalves** [comment]
What you mean? This work on Android too:
https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/Progress.java

**Comment by alexnavarro** [comment]
I saw this example and I got quite confused because I'm using retrofit and I need intrercept RequestBody. In the example the ResponseBody was interceped. Can you understand me?

**Comment by TakeoffAndroid** [comment]
In v2.0 you can show the progress bar by simply using the request body from the call object. Please find the code that I have used after a long struggle

RequestBody  requestBody = call.request().body();

            long fileLength = requestBody.contentLength();
            byte[] buffer = new byte[2048];
            FileInputStream in = new FileInputStream(filePath);
            long uploaded = 0;

            try {
                int read;
                Handler handler = new Handler(Looper.getMainLooper());
                while ((read = in.read(buffer)) != -1) {

                    // update progress on UI thread for 5 seconds
                    handler.postDelayed(new ProgressUpdater(uploaded, fileLength,callbacks),5000);

                    uploaded += read;
//                    sink.write(buffer, 0, read);
                }
            } finally {
                in.close();
            }

  private static class ProgressUpdater implements Runnable {
        private long mUploaded;
        private long mTotal;
        private HTTPLibraryFileUploadCallbacks mCallbacks;

        public ProgressUpdater(long uploaded, long total, HTTPLibraryFileUploadCallbacks callbacks) {
            mUploaded = uploaded;
            mTotal = total;
            mCallbacks = callbacks;
        }

        @Override
        public void run() {
            mCallbacks.onFileUploadProgress((int)(100 * mUploaded / mTotal));
        }
    }

**Comment by kulsjoshi** [comment]
@TakeoffAndroid Do you have any kind of demo with your code?

**Comment by luca992** [comment]
@TakeoffAndroid Pretty sure the only thing you are tracking is the progress of a while loop reading a file 2048 bytes at a time... not the data that is actually being uploaded

**Comment by shubham1g5** [comment]
Anyone have any idea about how to get Progress in case I have a multipart request that uploads a dynamic number of files to the server. I am migrating to Retrofit/OkHTTP from Apache HTTP client and was earlier achieving this by extending the MultipartEntity  and tracking transferred bytes. Though I can't do the same with it's OkHTTP's equivalent MultipartBody as it's declared as a final class. Are there any workarounds I can implement for my case ? (Relevant SO Question - https://stackoverflow.com/q/45019438/3811963)

**Comment by nb312** [comment]
There are solutions for making the progress in this link 👍 https://gist.github.com/eduardb/dd2dc530afd37108e1ac

**Comment by joshuapinter** [comment]
For those landing here that are still stuck on Retrofit 1.x, here's an easy, working solution that we ended up using: https://stackoverflow.com/a/24772058/293280. 

It involves creating a `ProgressListener` interface, a modified `TypedFile` and just using the listener when uploading the modified `TypedFile`.

It took a while to track this down so hopefully this helps others still running on version 1.x.
