### ISSUE TITLE
Read Response Header data

### ISSUE THREAD

**Issue by BugsBunnyBR** [square/retrofit#444]
Hi, Is it possible to read headers in the response direclty in my object? 
Like:
```Java
@POST("/users/login")
User login(String username, String password);
```
with the user having a field "token" or "cookies" in his fields?

or should I use the Response object to read the headers?
Like:
```Java
@POST("/users/login")
Response login(String username, String password);
```
Thanks folks.

**Comment by IgorGanapolsky** [comment]
@mipreamble What do you call getBodyAs() method on?

**Comment by mipreamble** [comment]
@IgorGanapolsky This method is used to convert the Response you get from Retrofit into a Java Object.
Retrofit 2.0 should resolve provide an API for this.
