### ISSUE TITLE
Using semicolon as query parameter separator

### ISSUE THREAD

**Issue by xiangdev** [square/retrofit#450]
Hi, I am trying to access a REST api using semicolon as query param separator.

 /api/1.0/channels;provider=0;detail=full;region=0;begin=1395635000;end=1395645000

AFAIK, retrofit uses '&' instead of ';' as query param separator if I do stuff like:

``` Java
@GET("/channels")
void channels(@Query("provider") String provider, 
        @Query("detail") String detail, 
        @Query("region") String region, 
        @Query("begin") long begin, 
        @Query("end") long end, 
        Callback<Channels> cb);
```

The request sent by retrofit would be:

/api/1.0/channels?provider=0&detail=full&region=0&begin=1395635000&end=1395645000

Is there a config switch to use ';' in this case?

P.S. The use of ';' is actually legit:
http://www.w3.org/TR/html401/appendix/notes.html#h-B.2.2

> We recommend that HTTP server implementors, and in particular, CGI implementors support the use of ";" in place of "&" to save authors the trouble of escaping "&" characters in this manner.

**Comment by meinuser** [comment]
i have a similar problem. but we need dynamic query parameters where one consists of three values separated by semicolon e.g. http://www.url.com/index.php?location=3.2225;24.44444;2&secondParam=123&thirdParam=456...
Is there a possibility to tell retrofit (or okhttp) not to escape some characters?
thanks in advance!
