### ISSUE TITLE
retrofit.RetrofitError: java.net.ProtocolException: unexpected end of stream

### ISSUE THREAD

**Issue by leodufer** [square/retrofit#456]
//In post FormUrlEncode

public interface AlumnoInterface {
	@FormUrlEncoded
	@POST("/service")
	void loginAlumno(@Field("cedula") String cedula,
					 @Field("password") String password,
					 Callback<Alumno> callback);
}

**Comment by JakeWharton** [comment]
> Perhaps it's just an issue with the embedded http client in retrofit?

There is no embedded client. You are seeing the HTTP client of the Android OS.

Moving forward we support only OkHttp which means this won't be an issue. Furthermore we can't really fix shipped, old versions of Android even if we wanted to.
