### ISSUE TITLE
DELETE with Body in Retrofit 1.5.0

### ISSUE THREAD

**Issue by cesards** [square/retrofit#458]
Hi,

First of all, I know that including body in DELETE request is bad, but I'm working for a customer with a legacy API, so I can't avoid it.

I'm getting this error (and the app stops):

```
Non-body HTTP method cannot contain @Body or @TypedOutput.
```

I've been having look to other responses:

https://github.com/square/retrofit/issues/330
https://github.com/square/retrofit/issues/426

But neither of them worked for me with Retrofit 1.4.1

If I use my custom DELETE annotation:

```
@Documented
@Target(METHOD)
@Retention(RUNTIME)
@RestMethod(value = "DELETEWITHBODY", hasBody = true)
public @interface DELETEWITHBODY {
  String value();
}
```

I get the next error (and the app doesn't stop):

```
Expected one of [OPTIONS, GET, HEAD, POST, PUT, DELETE, TRACE, PATCH] but was DELETEWITHBODY
```

Is there any kind of dirty solution for now?

Thanks in advance!

**Comment by farmazon3000** [comment]
>HTTP spec says there shouldn't be one

I can't it, can somebody help which it's said?

**Comment by darshanz** [comment]
There is nothing in the specs that strictly prevent us from implementing DELETE with body. Retrofit should be flexible too.

**Comment by 0xbaadf00d** [comment]
The response is on the HTTP 1.1 RFC (http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.7)

A successful response SHOULD be 200 (OK) __if the response includes an entity describing the status, 202 (Accepted)__ if the action has not yet been enacted, or 204 (No Content) if the action has been enacted but the response does not include an entity.


The DELETE method could return a message but isn't mandatory

**Comment by Zhuinden** [comment]
```
@Documented
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
@RestMethod(value = "DELETE", hasBody = true)
public @interface RetrofitDeleteWithBody {
    String value();
}
```

This worked for me, just use it like a normal DELETE except it actually works with a body!
Retrofit 1.9.

**Comment by rchampa** [comment]
I'm using 
```
compile 'com.google.code.gson:gson:2.5'
compile 'com.squareup.retrofit2:retrofit:2.0.2'
compile 'com.squareup.retrofit2:converter-gson:2.0.2'
compile 'com.squareup.okhttp3:okhttp:3.0.1'
```

But cannot find symbol `RestMethod`

**Comment by kherembourg** [comment]
With Retrofit 2 the solution is to use the HTTP interface instead of DELETE.
So replace : 
```
@DELETE("my/path")
```
By
```
@HTTP(method = "DELETE", path = "/my/path", hasBody = true)
```

I would like to create my own interface DELETE_BODY but I didn't find how yet since like you said RestMethod is not available anymore.

**Comment by PiaDeveloperBr** [comment]
Delete method is not working. In my case I use:
@DELETE("/Stories/{storyid}")
 Call<DeleteStoryResponse> deleteStory(@Path("storyid") int storyId);

But its not working :( Please Help me out...  !!

**Comment by liuguangmao** [comment]
Try this， https://stackoverflow.com/a/41142089/4486048
