### ISSUE TITLE
Confusing error message with calls to a malformed Retrofit Service

### ISSUE THREAD

**Issue by yogurtearl** [square/retrofit#473]
When a service interface is not well formed you may get the wrong error message.

For example, you might get 

```
java.lang.IllegalArgumentException: TestService.foo: Only one HTTP method is allowed. Found: GET and GET.
```

When the real problem is:

```
java.lang.IllegalArgumentException: TestService.foo: @Field parameters can only be used with form encoding. (parameter #1)
```

I think this is happening because retrofit.RestMethodInfo#init is throwing with an exception and leaving the shared instance in a weird state.

retrofit.RestMethodInfo#requestMethod gets set to a non-null value but retrofit.RestMethodInfo#loaded is still false. 

I think you need not run init again if threw an exception on another thread and make sure the first error is reported.

**Comment by sadeqzadeh** [comment]
@yogurtearl  Thanks for mentioning the real error message. I was confused. For me the real error was dropping the `@Body ` annotation before one of the parameters in my REST interface.
