### ISSUE TITLE
Malformed IPv6 address

### ISSUE THREAD

**Issue by Tarquinio** [square/retrofit#479]
Hello,
because of an annoying android bug (https://code.google.com/p/android/issues/detail?id=12724) retrofit crashes when i use endpoints like this: "http://192.168.2.108:8080/app_dev.php". 

Maybe this is a fix: http://stackoverflow.com/questions/6811482/use-url-on-android-throws-ioexception-malformed-ipv6-address ?

Greets

**Comment by JakeWharton** [comment]
This will be solved by https://github.com/square/okhttp/issues/1486. No action to take by Retrofit.
