### ISSUE TITLE
RxSupport should not set Scheduling on the Observable

### ISSUE THREAD

**Issue by christopherperry** [square/retrofit#480]
I've already had deadlock because of this, and had to manually set the executors to the current thread, but it should be that way by default.

Relevant to the discussion is [this section from Intro to Rx](http://www.introtorx.com/Content/v1.0.10621.0/15_SchedulingAndThreading.html#LockUps):

> We do not magically avoid classic concurrency problems simply by adopting Rx. Rx will however make it easier to get it right, provided you follow these two simple rules.
  1. **Only the final subscriber should be setting the scheduling**
  2. Avoid using blocking calls: e.g. First, Last and Single

> The last example came unstuck with one simple problem; the service was dictating the scheduling paradigm when, really, it had no business doing so. Before we had a clear idea of where we should be doing the scheduling in my first Rx project, we had all sorts of layers adding 'helpful' scheduling code. What it ended up creating was a threading nightmare. When we removed all the scheduling code and then confined it it in a single layer (at least in the Silverlight client), most of our concurrency problems went away. I recommend you do the same.

**Comment by JakeWharton** [comment]
#721 removed default scheduling. Many more changes will be made, but this issue is resolved and won't be back.
