### ISSUE TITLE
OkHttp v2 API Support

### ISSUE THREAD

**Issue by JakeWharton** [square/retrofit#497]
Preemptively creating this issue.

**Comment by JakeWharton** [comment]
This happened with 1.9.0.

**Comment by izmajlowiczl** [comment]
I'm experiencing the same problem on versions 2.1.0 and 2.2.0 only on Android 5. Any ideas?

**Comment by vineet425** [comment]
I'm integrate a module Cordova which used okhttp package src code, when i use picasso in main project it always give 

 java.lang.NoSuchMethodError: No virtual method setWriteTimeout(JLjava/util/concurrent/TimeUnit;)V in class Lcom/squareup/okhttp/OkHttpClient; or its super classes (declaration of 'com.squareup.okhttp.OkHttpClient' appears in /data/app/com.firstrain.debug-1/base.apk)
            at com.squareup.picasso.OkHttpDownloader.defaultOkHttpClient(OkHttpDownloader.java:34)
            at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:76)
            at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:55)
            at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:45)
            at com.squareup.picasso.Utils$OkHttpLoaderCreator.create(Utils.java:424)
            at com.squareup.picasso.Utils.createDefaultDownloader(Utils.java:250)
            at com.squareup.picasso.Picasso$Builder.build(Picasso.java:832)
            at com.squareup.picasso.Picasso.with(Picasso.java:662)

**Comment by artem-zinnatullin** [comment]
Looks like Cordova uses old version of OkHttp, try to manually add OkHttp
as a dependency.

вт, 22 Сен 2015, 16:44, vineet425 <notifications@github.com>:

> I'm integrate a module Cordova which used okhttp package src code, when i
> use picasso in main project it always give
>
> java.lang.NoSuchMethodError: No virtual method
> setWriteTimeout(JLjava/util/concurrent/TimeUnit;)V in class
> Lcom/squareup/okhttp/OkHttpClient; or its super classes (declaration of
> 'com.squareup.okhttp.OkHttpClient' appears in
> /data/app/com.firstrain.debug-1/base.apk)
> at
> com.squareup.picasso.OkHttpDownloader.defaultOkHttpClient(OkHttpDownloader.java:34)
> at com.squareup.picasso.OkHttpDownloader.(OkHttpDownloader.java:76)
> at com.squareup.picasso.OkHttpDownloader.(OkHttpDownloader.java:55)
> at com.squareup.picasso.OkHttpDownloader.(OkHttpDownloader.java:45)
> at com.squareup.picasso.Utils$OkHttpLoaderCreator.create(Utils.java:424)
> at com.squareup.picasso.Utils.createDefaultDownloader(Utils.java:250)
> at com.squareup.picasso.Picasso$Builder.build(Picasso.java:832)
> at com.squareup.picasso.Picasso.with(Picasso.java:662)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/square/retrofit/issues/497#issuecomment-142293289>.
>
-- 

@artem_zin
