### ISSUE TITLE
Retrofit: Sending POST request to server and getting result in JSONObject in android

### ISSUE THREAD

**Issue by niteshkhatri** [square/retrofit#500]
I am Retrofit to call APIs. I am sending a post request to API but in the callback I am getting empty JSON like this {}.

Below is the code for RetrofitService

```
@POST("/com/searchusers.php")
void getUser(@Body JSONObject searchstring, Callback<JSONObject> callBack);
```

where searchstring JSON is like this {"search":"nitesh"}. In response I am supposed to get the detail of user "nitesh".

Below is the code for sending POST request

```
RetrofitService mRetrofitService = app.getRetrofitService();
mRetrofitService.getUser(user, new Callback<JSONObject>() {

    @Override
    public void success(JSONObject result, Response arg1) {
        System.out.println("success, result: " + result);
    }

    @Override
    public void failure(RetrofitError error) {
        System.out.println("failure, error: " + error);
    }
});
```

I am getting this output success, result: {}

Expected output is success, result: {"name":"nitesh",....rest of the details}

Note: I tried using Response instead of JSONObject like this 

```
CallBack<Response>
```

 and then I converted the raw response into String and I got the expected result. But the problem is its in String, I want the response in JSONObject.

How can I get the exact result using this

```
CallBack<JSONObject>
```

**Comment by sudhanshugaur4** [comment]
Use GSON as new Gson().toJson(login) where login is the object defined in Callback Like this api.getLocation(new Callback<Login>()  {
                @Override
                public void success(Login login, Response response) {
                    
                }

                @Override
                public void failure(RetrofitError retrofitError) {
                   
                }
            });
