### ISSUE TITLE
Update SimpleXML retrofit converter doc

### ISSUE THREAD

**Issue by nicolasjafelle** [square/retrofit#507]
Needs to update or clarify somewhere that simpleXML converter library needs to exclude some jars, in this way:

compile ('com.squareup.retrofit:converter-simplexml:1.5.1') {
        exclude module: 'stax'
        exclude module: 'stax-api'
        exclude module: 'xpp3'
    }

**Comment by dante8300** [comment]
Why are complicating so much  just put this and you can be on your way...

configurations {
    compile.exclude group: 'stax'
    compile.exclude group: 'xpp3'
}
