### ISSUE TITLE
Mock Client implementation

### ISSUE THREAD

**Issue by ccmtaylor** [square/retrofit#528]
Hi,

inspired by the answers to [a question on StackOverflow](http://stackoverflow.com/questions/17544751/square-retrofit-server-mock-for-testing), I wrote [retromock](https://github.com/ccmtaylor/retromock/), a mock implementation of `retrofit.client.Client` and a couple of associated hamcrest matchers that let you specify a mock API endpoint for testing with a fluent API reminiscent of [wiremock](http://wiremock.org/stubbing.html) or [rest-driver](https://github.com/rest-driver/rest-driver/wiki), but without forcing you to start up a web server for your tests.

As of now, I'm still working on adding functionality, tests and documentation, but you can find a sketch of how to use the library in [this test](https://github.com/ccmtaylor/retromock/blob/master/src/test/java/retromock/MockClientTest.java).

Would you be interested in including this in retrofit itself? I couldn't find a mailing list or forum for retrofit-related discussion, so if I should submit this somewhere else, please let me know.

**Comment by JakeWharton** [comment]
`Client` has died. OkHttp is now used directly for v2. The right thing to do is either mock the interface, script OkHttp via an interceptor, or use MockWebServer.
