### ISSUE TITLE
Can not add http header "Content-Type:application/json" on 1.6.0

### ISSUE THREAD

**Issue by NeoLSN** [square/retrofit#533]
Can not add http header "Content-Type:application/json" on 1.6.0, but it works on 1.5.1

**Comment by emreaktrk** [comment]
I had the same issue and resolved by investigate backend. It was only accepts url encoded so i added to @FormUrlEncoded annotation to method and avoid using @Body annotation as parameters. You may need to use @Field instead.

If anyone have problem like this give it a try. Maybe it solves your problem ;)
