### ISSUE TITLE
OutOfMemory while sending big file

### ISSUE THREAD

**Issue by sportwtany** [square/retrofit#540]
When I send big file (about 50 Mb) by multipart, Retrofit catch OutOfMemoryError.
How I can send big files by Retrofit?

**Comment by RohitJPatil** [comment]
how do i handle that error in failure???

**Comment by manmohansoni** [comment]
Same issue I am also facing. In my case my app is feching huge json data from the server.

**Comment by swankjesse** [comment]
@manmohansoni please ask on StackOverflow. This tracker is for bug reports and feature requests only.

**Comment by manmohansoni** [comment]
@swankjesse if in a request, response request is large and retrofit gets crashed due to out of memory. I think it is a bug. Please let me know, any solution you have for it. The issue was not coming with small responses.

**Comment by artem-zinnatullin** [comment]
You're probably converting response to object in memory, if so — it's not a
bug of Retrofit, it does what you said it to do.

You can try to switch to reading InputStream from response and consume by
small chunks to avoid OOM.

**Comment by manmohansoni** [comment]
@artem-zinnatullin thanks Artem. This is quit right reply, now i got the direction to move. Thanks a lot and let me try to another way to fix OOM.

**Comment by artem-zinnatullin** [comment]
Sure, np.

Another direction you can try to go into is switch to pagination requests
if possible, usually if backend can reply with some huge response backend
developers also add pagination to the API, like: `&limit=10&lastId=value`

**Comment by ralphgabrielle** [comment]
This helps, kindly set your interceptor level to none
 `interceptor.setLevel(HttpLoggingInterceptor.Level.NONE);`

**Comment by joshuapinter** [comment]
@ralphgabrielle That's what @JakeWharton was saying here: https://github.com/square/retrofit/issues/540#issuecomment-46934042.
