### ISSUE TITLE
How to handle dynamic json with POJO !

### ISSUE THREAD

**Issue by LOG-TAG** [square/retrofit#548]
Sorry it's not a bug , I need help for dynamic json handling via pojo!

I'm using Retrofit, but unfortunately REST api dev built dynamic api, thinking of how to convert my POJO to handle dynamic json ( JSON Prefix type changes to Object in success condition and the same prefix changes to String in failed condition!) since the Object {} type changes to String type built in GSON parser making error!

For more info ref SO: https://stackoverflow.com/questions/24279245/how-to-handle-dynamic-json-in-retrofit

**Comment by bhagyasri** [comment]
I have used Retrofit 2 for API calls in my app. I have difficulty to parse Retrofit error response "response.errorBody()". Because some times I am getting responseMessage as object and some times as string or json array. How to rectify this to parse dynamic error response from API?
