### ISSUE TITLE
Add support for multipart response

### ISSUE THREAD

**Issue by francisoud** [square/retrofit#562]
As describe in this stackoverflow question(1), support for multipart response in retrofit would be useful for my project.
[1] http://stackoverflow.com/questions/24534688/is-it-possible-to-consume-http-response-with-content-type-multipart-mixed-wi

**Comment by JakeWharton** [comment]
I think multipart responses are simply too esoteric for inclusion in the core library and the pluggable converter mechanism was designed so that you could plug your own in if you wanted to use something else.
