### ISSUE TITLE
Allow streaming of Response 

### ISSUE THREAD

**Issue by jvanzyl** [square/retrofit#568]
Doesn't appear to be a way to stream a Response directly to disk. Maybe this is not in Retrofit's wheelhouse, but I have a call that retrieves Zip files that are large and with a normal sized heap Retrofit OOMEs as it spools everything into memory first before making it available to userspace.

**Comment by initialjie** [comment]
Hi, could Retrofit ignore ```HttpLoggingInterceptor``` when using ```@Streaming```?
I found it can not be achieved.

**Comment by JakeWharton** [comment]
N. They don't know about each other.

**Comment by tentypwtk** [comment]
@initialjie 
Have you found any solutions to avoid logging of streaming? I added the following as a workaround:

`HttpLoggingInterceptor logging = new HttpLoggingInterceptor(new HttpLoggingInterceptor.Logger() {
            boolean skipBody = false;
            @Override public void log(String message) {
                if( message.contains("Content-type: application/pdf") )
                    skipBody = true;
                if( message.length() > 5000 && skipBody ) {
                    skipBody = false;
                    return;
                }

                Timber.tag("OkHttp").d(message);
            }
        });`

**Comment by initialjie** [comment]
@tentypwtk 
Sorry for replying it just now.
Thanks for your suggestion!
Whether it is a wonderfully solution for just  a few particular assumption(If)?

**Comment by kagile** [comment]
How can we do this in OkHttp same as @Streaming without using Retrofit?

**Comment by swankjesse** [comment]
OkHttp is always streaming.
