### ISSUE TITLE
Retrying requests manually

### ISSUE THREAD

**Issue by tonnyavery** [square/retrofit#572]
Hi guys.
I'm wondering if there is some way to manually retry asyncronous requests sent via retorfit?
I'm writing a game with a large user base, and right now we are using another network library. The main problem is that game is sometimes played on 3G network, and sometimes random requests fail. For that case, I would like to implement some manual retry logic to make sure user experience is on the level.
I'm read to re-write the core of our game to retrofit, but before I start I need to make sure that retrying requests will be possible. Right now I don't see any handle for async request that might give me ability to retry it, or maybe save in my own wrapper around retrrofit and resend manually

**Comment by gurappa** [comment]
@JakeWharton when the V2.o will be available ? I am really looking for a way to do Cancel ongoing request and Retry stuff. Our Android application is not progressing without these. I have been trying to do with RxJava but facing some problems. I have used UrlConnectionClient as my client while building RestAdapter and async way using Callbak. Please let me know if there is way I can do on my own to manually cancel and retry. I am confused between many links and docs on this.

**Comment by JakeWharton** [comment]
No timeline. Probably 2 monthsish.

**Comment by gurappa** [comment]
@JakeWharton Thanks for clarity !
Is there a way I can do CANCEL and RETRY if I change my code to Synchronous requests ?

**Comment by PankajSavaliyaGit** [comment]
is there is any retry policy for using retrofit because sometime i have to recall and after trying 3-4 times it will provide response. I have checked to backend for my service response everting is perfect.
Always first time calling of service it will return retrofitError is Null.
