### ISSUE TITLE
Why custom annotations instead of JAX-RS (JSR-311) ones?

### ISSUE THREAD

**Issue by simon-heinen** [square/retrofit#573]
What was the design decision not to use the JAX-RS (JSR-311) annotations and instead create custom ones? 

I would like to share the REST interfaces between my backend and Android frontend to not write them twice but this isn't possible due to the custom annotations or am I wrong?

**Comment by daniphp** [comment]
@simon-heinen did you find a way to reuse the interfaces?

**Comment by simon-heinen** [comment]
No but there are some possible ways: What you can do is create a version of retrofit where you modify the parser that it accepts both retrofit annotations and jax rs annotations which might be the best way or you add the retrofit annotations to your jax rs interfaces on the server side (which I wouldn't recommend;)
