### ISSUE TITLE
Provide method to intercept responses as well as requests

### ISSUE THREAD

**Issue by moswald** [square/retrofit#585]
I have to grab a header value from the server's response and return it in the _next_ request. Since this value changes on every request, having all requests return a `Request` object isn't much better than rolling my own service.

**Comment by JakeWharton** [comment]
This can be done with [OkHttp interceptors][1] with version 1.9.0.

 [1]: https://github.com/square/okhttp/wiki/Interceptors

**Comment by JakeWharton** [comment]
FYI this probably isn't going to happen because it will be impossible to be OkHttp's interceptors. I would _highly_ recommend them for this.

**Comment by JakeWharton** [comment]
OkHttp interceptors are the way to go. Retrofit is getting dumber and OkHttp has gotten a lot smarter.

**Comment by doneill** [comment]
Thanks @JakeWharton OkHTTP interceptors it is, thanks for the update.
