### ISSUE TITLE
Success callback supplied with null response object

### ISSUE THREAD

**Issue by berkankisaoglu** [square/retrofit#591]
I have an api call like the one below: 

```
@POST("/some/random_path")
public void doSomething(@Body SomeRequest someRequest, Callback<BaseResponse<SomeResponse>> callback);
```

I don't quite understand why some of the success callbacks are supplied with `null` response object. 
What I expected was to receive at least an instance of `BaseResponse` with `SomeResponse` type (In worst case I would expect to get an instance with no mapping/all fields are `null`). 

I wasn't able to reproduce it myself, It is quite intermittent. But for the ones who crashed due to this reason, I can see that the response code is 200. 

> D/d ---> HTTP POST http://example.com/some/random_path
> D/d <--- HTTP 200 http://example.com/some/random_path

Is there any specific case that calls success callback with null object instead of throwing an exception and calling failure callback? 

ps. It is not specific to one api call, or a specific method.

**Comment by moonandroid** [comment]
I also faced same issue with 2.0.2

private static Retrofit retrofit = null;
 public static Retrofit getLogin() {
        HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
        interceptor.setLevel(HttpLoggingInterceptor.Level.BODY);
        OkHttpClient okHttpClient = new OkHttpClient.Builder().addInterceptor(interceptor).build();

        if (retrofit==null) {
            retrofit = new Retrofit.Builder()
                    .baseUrl(MAIN_URL)
                    .addConverterFactory(GsonConverterFactory.create())
                    .client(okHttpClient)
                    .build();
        }
        return retrofit;
    }

---------------------------------------------------------------------------------
 @FormUrlEncoded
    @POST("login.php")
    Call<User> loginUser(@Field("login_type") String login_type, @Field("email") String email,
                         @Field("password") String password, @Field("deviceID") String deviceID,
                         @Field("push_token") String push_token, @Field("push_token") String platform);
-------------------------------------------------------------------------------------------

 ApiInterface apiService =
                ApiClient.getLogin().create(ApiInterface.class);

        Call<User> call = apiService.loginUser("Rider","test@test.com","Test123@",
                "ddddddddddddddd",
                "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "android");

        call.enqueue(new Callback<User>() {
            @Override
            public void onResponse(Call<User> call, Response<User> response) {
                int statusCode = response.code();
                Log.e("Tag","onResponse response "+response.isSuccessful());
                Log.e("Tag","onResponse" +response.body().toString());
# /Here getting null.....................
            }

            @Override
            public void onFailure(Call<User> call, Throwable t) {
                Log.e("Tag","onResponse onFailure" );
            }
        });
