### ISSUE TITLE
javax.net.ssl.SSLException / Retrofit 1.6.1 / OkHTTP 2.0 / Okio 1.0.1

### ISSUE THREAD

**Issue by rwmorey71** [square/retrofit#592]
Seeing this error on Android 4.4.4

D/Retrofit(5084): javax.net.ssl.SSLException: Read error: ssl=0x76abde80: I/O error during system call, Connection reset by peer
D/Retrofit(5084):   at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
D/Retrofit(5084):   at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:689)
D/Retrofit(5084):   at okio.Okio$2.read(Okio.java:136)

Apparently later versions of Conscrypt fix this error. Will Retrofit be updated any time soon to use the latest Conscrypt code?

Rich

**Comment by cah-ericmaxwell** [comment]
@rwmorey71 , did you ever find a solution to this?  We are experiencing the same exception with the exact same libraries on Android 4.4.4.  I realize this isn't a Retrofit issue, but can't seem to find a solution anywhere..   The problem goes away on other Android versions such as 5.0.2

**Comment by rwmorey71** [comment]
Hi --

I believe we did. I will look through the code and try to figure out how we fixed it. We have moved to the latest version of Retrofit and changed around some of the code because a change in Retrofit so that fixed code may have been removed. Either way I'll let you know if I have the solution or not.

Rich

**Comment by cah-ericmaxwell** [comment]
Awesome, thanks for the quick response Rich!

**Comment by rwmorey71** [comment]
Hi --

I was not able to find the code where we might have fixed this issue. There were three different projects I was working on back when I wrote this. I no longer have access to the source code of one of the three but I could not find anything in the other two.

I would suggest updating to the latest version of Retrofit and see if the issue goes away.

Sorry I can't be of more help.

Rich

**Comment by cah-ericmaxwell** [comment]
Oh, that's okay.  Thanks for trying!

**Comment by GokhanArik** [comment]
@JakeWharton Any advice on debugging this issue? Do you think there is something wrong with our SSL Factory? I understand it is not related to the Retrofit, but maybe you might give us some advice.

**Comment by JakeWharton** [comment]
No. I have no idea how to deal with this.

**Comment by GokhanArik** [comment]
Thanks Jake

**Comment by siwangqishiq** [comment]
@JakeWharton I have found this problem on okhttp 2.0.0     log:-->  
at com.android.org.conscrypt.NativeCrypto.SSL_read(NativeCrypto.java)
       at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:811)
       at okio.Okio$2.read(Okio.java:136)
       at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
       at okio.RealBufferedSource.indexOf(RealBufferedSource.java:206)
       at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:153)
       at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:189)
       at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:101)
       at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:676)
       at com.squareup.okhttp.Call.getResponse(Call.java:205)
       at com.squareup.okhttp.Call.execute(Call.java:80)

Any advice on debugging this issue?

**Comment by swankjesse** [comment]
Please upgrade to the latest release. It’s possible that your issue has since been fixed.
