### ISSUE TITLE
VM doesn't immediately stop when using Callback

### ISSUE THREAD

**Issue by TheHolyWaffle** [square/retrofit#598]
When I issue a GET request without the Callback parameter the VM immediately ends.

When I issue the same GET request but this time with the Callback parameter and after the result arrives it takes the VM a good 1-2 minutes before it stops.

I'm running this on my windows 7 (Java 7) desktop, default executors and OkHttp client.

**Comment by JakeWharton** [comment]
OkHttp owns the treading model now so there's no action to take. Bottom line, both options here suck: the VM stays alive for some timeout or the VM exits immediately without waiting for the response.
