### ISSUE TITLE
@POST, Must have either a return type or Callback as last argument.

### ISSUE THREAD

**Issue by pankai** [square/retrofit#603]
My service interface is like:

```
@POST("/posts/new")
void newPost(@Body Post post);
```

I got this exception when calling it:

```
java.lang.IllegalArgumentException: PostService.newPost: Must have either a return type or Callback as last argument.
```

My questions are. Why does POST need a return type? Can we do without it? Will having a return type force the server to return an object back, which will cause users' data usage?

**Comment by adi1133** [comment]
How is this situation handled in retrofit 2 ?
