### ISSUE TITLE
Comma separated parameter possible?

### ISSUE THREAD

**Issue by artworkad** [square/retrofit#611]
E.g.

```
http://maps.google.com/maps/api/staticmap?center=37.4223662,-122.0839445&zoom=15&size=200x200&sensor=false
```

Is this center param possible with retrofit? How?

**Comment by MuhammedRefaat** [comment]
@JakeWharton Sorry but I didn't get your answer, for me when sending it as it is it gets unicoded to its Hex value (%2C), which somehow is not accepted at the server side. 
So how shall I send it.

**Comment by kihaki** [comment]
> @JakeWharton Sorry but I didn't get your answer, for me when sending it as it is it gets unicoded to its Hex value (%2C), which somehow is not accepted at the server side.
> So how shall I send it.

You can set the encoded parameter to true and then it will accept the values without encoding them, e.g. `@Query("page_numbers", encoded = true) pageNumbers: String`

**Comment by MuhammedRefaat** [comment]
> > Sorry but I didn't get your answer, for me when sending it as it is it gets unicoded to its Hex value (%2C), which somehow is not accepted at the server side.
> > So how shall I send it.
> 
> @MuhammedRefaat You can set the encoded parameter to true and then it will accept the values without encoding them, e.g. `@Query("page_numbers", encoded = true) pageNumbers: String`

I believe I was doing that and still it's getting encoded, need to double-check.
