### ISSUE TITLE
Support HystrixRequestContext When Using Observable

### ISSUE THREAD

**Issue by mrcritical** [square/retrofit#647]
Currently the RxSupport doesn't allow me to copy the HystrixRequestContext onto the Executor thread used by RetroFit. So now any commands executed in my Hystrix-enabled HTTP client fail. I cannot see a way to copy the context to the executor thread. This isn't an issue when using the none Observable version, where an Executor is not used.

Can there be support added to access the thread, in some way, to allow putting the HystrixRequestContext onto to that thread? Hystrix does this by using a CallableWrapper.

**Comment by tcompart** [comment]
Is there any chance that Hystrix could by easily coupled except the hack above?!
