### ISSUE TITLE
Document that request Interceptors run on main thread

### ISSUE THREAD

**Issue by runningcode** [square/retrofit#651]
For some reason I assumed that request interceptors ran in the background thread, but in fact they run on the main thread. It would be nice if this were documented.

This is the code I used to test this:
```
@Override
public void intercept(RequestFacade request) {
	if (Looper.getMainLooper() == Looper.myLooper()) {
		Log.i("INTERCEPTOR", "running on ui thread");
	}
}
```
Also it is worth mentioning that this was an RxJava Observable request, perhaps it takes a different code path than the normal request interceptor.

**Comment by jnlopar** [comment]
I've found putting .subscribeOn(Schedulers.io()) right after the call to get the observable causes it to get called on an io thread. Still confusing.

**Comment by runningcode** [comment]
it seems that this issue was fixed, thanks!

**Comment by jnlopar** [comment]
Do you have a reference to the fix?
