### ISSUE TITLE
request: break mime functionality into its own jar

### ISSUE THREAD

**Issue by jgangemi** [square/retrofit#652]
hello -

i am very interested in using the mime parsing offered in retrofit but i don't need the other portions. would you consider splitting the functionality out into its own jar?

thank!

**Comment by JakeWharton** [comment]
I'm assuming you mean `TypedInput` and `TypedOutput`? I actually plan to kill these and replace them with something based on [Okio][1].

I would recommend you copy them out yourself.

 [1]: http://github.com/square/okio
