### ISSUE TITLE
How to retry request api (fail , timeout, error)

### ISSUE THREAD

**Issue by Poonjaroen** [square/retrofit#670]
hi, how to coding retry request api (fail , timeout, error)

**Comment by jondwillis** [comment]
One slightly naive method would be to retry periodically. For me, this looks like:

    
                .retryWhen(attempts -> {
                    return attempts.switchMap(o -> {
                        return Observable.timer(3, TimeUnit.SECONDS);
                    });
                })

excuse the shitty variable names. this was quickly adapted from something similar to:

https://stackoverflow.com/questions/22066481/rxjava-can-i-use-retry-but-with-delay
