### ISSUE TITLE
JAX-RS Compatibility

### ISSUE THREAD

**Issue by nobeh** [square/retrofit#671]
I understand that one focus of this nice library is aimed at Android. 

I am interested to know what where the design decisions/concerns to have 

```java
@GET("/api/users/{id}"
public User getUser(@Path("id") String id);
```

rather than having JAX-RS spec API and then:

```java
@GET
@Path("/api/users/{id}")
public User getUser(@PathParam("id") String id);
```

Thanks. And, any plans to support the spec?

**Comment by JakeWharton** [comment]
With 2.0 we're going to move even farther away from the ability to share making this impossible. I admire your desire to do this. I spent a good two days evaluating compatibility back in 2012 but deemed it impossible then and as we are focusing even more on client-specific behavior with 2.0 I simply don't think we can ever really do this.

What I would recommend doing is using an alternative format for representing your API endpoints and generating both the Retrofit service interface and the JAX-RS one for server side.

For example, we use protocol buffers:
```proto
service FooService {
  // @url /bar
  // @method POST
  rpc BarResponse bar(BarRequest);
  // @url /baz
  // @method POST
  rpc BazResponse baz(BazRequest);
```
which generate types and becomes:
```java
interface FooService {
  @POST("/bar")
  BarResponse bar(BarRequest body);

  @POST("/baz")
  BazResponse baz(BazRequest body);
}
```
