### ISSUE TITLE
Retrofit parsing doesn't work

### ISSUE THREAD

**Issue by richard-chiang** [square/retrofit#680]
Hello.
I am currently learning how to use Retrofit because I have heard of many good reviews about it, particularly the ease of using it. I have looked up many tutorials and copied the exact coding and classes. They all crashes my Android App. (I'm using Android Studio <-- also new to this). To my surprise, this also include your sample. My current project is on 

https://github.com/deadanger/BusPlzStop/tree/master/BusSTOP/app/src

What I am trying to do is simply have Retrofit with Simple to parse XML data given from 

http://api.translink.ca/rttiapi/v1/buses?apikey=faYApdPzIJThbIF16yCP&routeNo=099

I have tried using Android API 18, 20, 21 thinking that it may be due to API version but none of them worked.
I have tried your sample to parse your json source which also doesn't work

Any methods I tried, the error all has to do with 
<MyClass> mClass = <Interface>.getXML();

In my case busList = apiService.getBus(apikey, 99);   in the MapsActivity class
where busList is of type Buses 
           apiService is my interface with @GET 

Can I please have someone who had success with Retrofit check where I'm doing wrong?

In my MapsActivity class
        public  Buses getBuses(int routeNo) {
            Log.i("Step", "start doInBackground");
            Buses busList;
            RestAdapter restAdapter = new RestAdapter.Builder()
                    .setEndpoint("http://api.translink.ca/rttiapi/v1")
                    .setConverter(new SimpleXmlConverter())
                    .setLogLevel(RestAdapter.LogLevel.FULL)
                    .build();
            ApiService apiService = restAdapter.create(ApiService.class);

```
        try {
            busList = apiService.getBus(apikey, 99);
            return busList;
        } catch (RetrofitError e) {
            System.out.println(e.getResponse().getStatus());
        }
            return new Buses();
    }
```

My ApiService Interface..
public interface ApiService {

```
@GET("/buses")
public Buses getBus(@Query("apikey") String api, @Query("routeNo") int busNo);
```

}

My Buses Class
@Root(name = "Buses")
public class Buses implements Iterable<Bus>{

   @ElementList(name = "Bus",inline = true)
    public List<Bus> bus;

```
@Override
public Iterator<Bus> iterator() {
    return bus.iterator();
}
```

}

My Bus Class
@Root(name = "Bus")
public class Bus {
   @Element(name = "VehicleNo")
    public int vehicleNo;

   @Element(name = "RouteNo")
    public int routeNo;

```
@Element(name = "Direction")
public String direction;

@Element(name = "Destination")
public String destination;

@Element(name = "Latitude")
public double latitude;

@Element(name = "Longitude")
public double longitude;

@Element(name = "RecordedTime")
public String recordedTime;
```

}

Update:
I tried Callback method with failure

public void failure(RetrofitError error) {
                    Log.e("failure", String.valueOf(error.getMessage().contains("authentication")));
                    Log.e("failure", String.valueOf(error.getResponse().getStatus()));
                    Log.e("failure", String.valueOf(error.getResponse().getBody()));
                }

Output: 

{12-17 13:27:42.947    1908-1908/com.example.chiang.busstop E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.example.chiang.busstop, PID: 1908
    java.lang.NullPointerException: Attempt to invoke virtual method 'int retrofit.client.Response.getStatus()' on a null object reference
            at com.example.chiang.busstop.MapsActivity$Data$1.failure(MapsActivity.java:89)
            at retrofit.CallbackRunnable$2.run(CallbackRunnable.java:53)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
12-17 13:34:34.719    2375-2375/com.example.chiang.busstop E/failure﹕ false
12-17 13:34:34.719    2375-2375/com.example.chiang.busstop E/failure﹕ 200
12-17 13:34:34.719    2375-2375/com.example.chiang.busstop E/failure﹕ null}

When I entered the url I inputted on google chrome.

I get a long snippet below. (not a complete list) It clearly has information.
but Retrofit returns null for the body

http://api.translink.ca/rttiapi/v1/buses?apikey=faYApdPzIJThbIF16yCP&routeNo=099
<?xml version="1.0" encoding="UTF-8"?>
<Buses xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
   <Bus>
      <VehicleNo>8013</VehicleNo>
      <TripId>6331261</TripId>
      <RouteNo>099</RouteNo>
      <Direction>WEST</Direction>
      <Destination>UBC B-LINE</Destination>
      <Pattern>WB1</Pattern>
      <Latitude>49.262317</Latitude>
      <Longitude>-123.068933</Longitude>
      <RecordedTime>01:42:11 pm</RecordedTime>
      <RouteMap>
         <Href>http://nb.translink.ca/geodata/099.kmz</Href>
      </RouteMap>
   </Bus>
   <Bus>
      <VehicleNo>8016</VehicleNo>
      <TripId>6331260</TripId>
      <RouteNo>099</RouteNo>
      <Direction>WEST</Direction>
      <Destination>UBC B-LINE</Destination>
      <Pattern>WB1</Pattern>
      <Latitude>49.264083</Latitude>
      <Longitude>-123.167900</Longitude>
      <RecordedTime>01:43:10 pm</RecordedTime>
      <RouteMap>
         <Href>http://nb.translink.ca/geodata/099.kmz</Href>
      </RouteMap>
   </Bus>

**Comment by beydogan** [comment]
@richard-chiang do you have any solutions for this?
