### ISSUE TITLE
Passing array of values which have the same parameter name in Multipart request

### ISSUE THREAD

**Issue by skonb** [square/retrofit#685]
I want to send multipart POST request exactly like GET request as below
`param[]=1&param[]=2&param[]=3,....`
currently I think have to construct MultipartTypedOutput to send arbitrary number of values of the same name. For example,
```java
 MultipartTypedOutput body = new MultipartTypedOutput();
 for (String value : values) {
        body.addPart("param[]", new TypedString(value));
  }
```
Please correct me if I am in wrong direction.

So I wonder if it is good for Retrofit to have an annotation for this pattern, something like @PartArray,
and the concept is implemented [here](https://github.com/skonb/retrofit/commit/21a40a85ad6c8177062651f43303541a6ec81bab) WITHOUT any tests...

Usage is,
```java
   @Multipart
   @POST("/")
   Observable sendSomething(@PartArray("params[]") List<String> params, @Part("image") TypedFile image);
```

If it is worth considering, I will write tests for this.
Thank you.

**Comment by Bajranghudda1** [comment]
Yes can send an array or list also like this...

 	RequestBody rb;
        LinkedHashMap<String, RequestBody> mp= new LinkedHashMap<>();
        for(int i=0;i<itemBeam.getItems_info().size();i++)
        {
                   rb=RequestBody.create(MediaType.parse("text/plain"), itemBeam.getItems_info().get(i).getItem_bar_code());
            mp.put("item_bar_code["+i+"]", rb);

            rb=RequestBody.create(MediaType.parse("text/plain"),itemBeam.getItems_info().get(i).getItem_type());
            mp.put("item_type["+i+"]",rb);

            rb=RequestBody.create(MediaType.parse("text/plain"),itemBeam.getItems_info().get(i).getCna_number());
            mp.put("cna_number["+i+"]",rb);

            rb=RequestBody.create(MediaType.parse("text/plain"),itemBeam.getItems_info().get(i).getTime());
            mp.put("times["+i+"]",rb);
        }
        
Now pass your map in the callback function ....

 getVerty("11221", mp, "Bajrang Hudda");

And change your interface like this.....
        @Multipart
        @POST("vertical")
        Call <ApiCallingModel> getVerty(
					 @PartMap() Map<String, RequestBody> phot,
			);

That's it.....
now your request will be like....
{"status":"1","message":{"nfc_tag_id":"U-123456-123-12/346","time":"2015-12-17 10:04:29","resident_at_home":"Y","item_bar_code":["MC140517193S","9804456119139","CN04G4817161653H01AV","SP40D71289"],"item_type":["O","O","O","SP"],"cna_number":["","","",""],"times":["2015-12-17 10:04:33","2015-12-17 10:04:38","2015-12-17 10:04:46","2015-12-17 10:04:53"]}}
