### ISSUE TITLE
About gson paser

### ISSUE THREAD

**Issue by ted66** [square/retrofit#687]
Now i using 
    void getkillerList(
            @Query("allianceid") String allianceid,
            @Query("type") String type,
            Callback<Map<String,GsonPromoteKillerChild>> 
The correct JSON format:
{
  "1": {
    "is_bought": "0",
    "killerIsStable": "0",
    "nickname": "tcc",
    "pic": "p_valosz790523_52f0d394639ef.jpg",
    "promotion": "nba",
    "sale_price": "0",
    "sellid": null,
    "userid": "valosz790523",
    "winpercentage": "0"
  },
  "2": {
    "is_bought": "0",
    "killerIsStable": "0",
    "nickname": "aab",
    "pic": "p_mw625_539668889b6db.jpeg",
    "promotion": "cba",
    "sale_price": "0",
    "sellid": null,
    "userid": "mw625",
    "winpercentage": "0"
  }}

But somtimes have error the JSON format is:

{
  "error": "0201",
  "description": "api not exist",
  "type": 2
}

 It will run failure function

I wish handle corrent callback and error callback

How could i fix it?

**Comment by JakeWharton** [comment]
I don't understand the question. Are you asking how to read the JSON error from a `RetrofitError` object in the failure callback?

**Comment by ted66** [comment]
Now it's ok
I fixed result,thx
