### ISSUE TITLE
Posting JSON object body with a null property value

### ISSUE THREAD

**Issue by eralpkaraduman** [square/retrofit#688]
{"foo":{"bar":null}}

I'm trying to post such json with "bar": being null;
But retrofit ignores null properties in java object passed to @Body 

gson .serializeNulls() couldn't save me because I have 2 other properties on the object I pass to @Body shouldn't be serialized as json null's. 
https://sites.google.com/site/gson/gson-user-guide#TOC-Null-Object-Support

What's the most practical and "clean / less-hacky" way to serialize single property value as json null when it's java null using Retrofit? Is it providing a custom gson serializer, would it be overkill?

Thanks.

**Comment by Juan266** [comment]
eralpkaraduman Could you resolve your problem with null property value ?. I am dealing with the same issue without success so far.

**Comment by lmorda** [comment]
public class RetrofitAdapterBuilder extends RestAdapter.Builder {
    public RetrofitAdapterBuilder(RetrofitInterceptor retrofitInterceptor) {
        this.setConverter(new GsonConverter(new GsonBuilder().serializeNulls().create()))
...

**Comment by mplzgta** [comment]
or change
    new Retrofit.Builder().addConverterFactory(GsonConverterFactory.create())

to
  new Retrofit.Builder().addConverterFactory(GsonConverterFactory.create(new GsonBuilder().serializeNulls().create()))

**Comment by masterravi** [comment]
@mplzgta ,
Thats what I looking for .
Thanks

**Comment by FabrizioAlmeidaFerreira** [comment]
mplzgta you are the man, you save my ass... sorry for vocabulary but, that is happen to me, only this handle work for me tks.

**Comment by mecoFarid** [comment]
@mplzgta I am using Retrofit. Tested Gson converter outside Retrift context and conversion was as intended (fields with null values were serialized to JSON), but when using it in Retrofit's GET request they don't get serialized (fields with null value gets omitted in conversion). What could be the possible problem?

**Comment by SergeyBurlaka** [comment]
> GsonConverterFactory.create(new GsonBuilder().serializeNulls().create()))

finally fouhnd solution

**Comment by arpitjoshi08** [comment]
can i use both factory object :

```
addConverterFactory(new Retrofit.Builder().addConverterFactory(GsonConverterFactory.create())
addConverterFactory(new Retrofit.Builder().addConverterFactory(GsonConverterFactory.create(new GsonBuilder().serializeNulls().create())))
```

according to my need i use both pattern but issue is that only one working which is written on top, how could i resolved this

**Comment by Sarowal-1734** [comment]
> 

Did you find the solution?

**Comment by hotellinawebmaster** [comment]
The solution is having only 1 line of the above two:

`addConverterFactory(new Retrofit.Builder().addConverterFactory(GsonConverterFactory.create())
addConverterFactory(new Retrofit.Builder().addConverterFactory(GsonConverterFactory.create(new GsonBuilder().serializeNulls().create())))`

In Kotlin below I was able to add a custom gson converter that has many options:

`package ***************

import com.example.retrofitsample.deserializers.InstantDateDeserializer
import com.google.gson.Gson
import com.google.gson.GsonBuilder
import kotlinx.datetime.Instant
import okhttp3.OkHttpClient
import okhttp3.logging.HttpLoggingInterceptor
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory

object RetrofitClient {

    fun getInstance(): Retrofit {
        var mHttpLoggingInterceptor = HttpLoggingInterceptor()
            .setLevel(HttpLoggingInterceptor.Level.BODY)

        var mOkHttpClient = OkHttpClient
            .Builder()
            .addInterceptor(mHttpLoggingInterceptor)
            .build()

        val gson: Gson = GsonBuilder()
            .registerTypeAdapter(Instant::class.java, InstantDateDeserializer())
            .serializeNulls()
            .create()

        var retrofit: Retrofit = retrofit2.Retrofit.Builder()
            .baseUrl("https://www.souvenirscout.com/rest-api/code-test/")
            //.addConverterFactory(GsonConverterFactory.create())   // this was the default one only
            .addConverterFactory(GsonConverterFactory.create(gson))
            //.addConverterFactory(GsonConverterFactory.create(GsonBuilder().serializeNulls().create()))

            .client(mOkHttpClient)
            .build()

        return retrofit
    }

}`


So above I added a custom serializer .registerTypeAdapter(Instant::class.java, InstantDateDeserializer()) and also  .serializeNulls() to the same and unique gson object.
After that I added the gson object just built, only once.

The original code in Kotlin, without the .registerTypeAdapter(Instant::class.java, InstantDateDeserializer()) and with no  .serializeNulls would be the following:

`val gson: Gson = GsonBuilder()
             .create()`

>
