### ISSUE TITLE
Getting Response body empty if i am on Log level NONE in Sucees callback

### ISSUE THREAD

**Issue by abhirb1** [square/retrofit#695]
I am getting response body as empty if i am on Log level NONE in Success callback.
I think this shouldn't happen right, because i usually turn off logs if my app is in release mode liek this

restAdapter.setLogLevel(BuildConfig.DEBUG ? RestAdapter.LogLevel.FULL : RestAdapter
                        .LogLevel.NONE);

And in success callback (if my app is in release build variant) -:

          Callback callback = new Callback<MyParser>() {
            @Override
            public void success(MyParser parser, Response response) {
                     // I get .readInputStream(response) empty here but response.getUrl() is not empty
                    //,only body is empty dont understand why
            }

            @Override
            public void failure(RetrofitError error) {
            }
        };

I guess, you are not setting Response object's body if app is in release mode.I used workaround like
i set log level to always FULL now and got it work but this shouldn't happen.

Now i changed it to which is workaround i think,Correct me if i am not  -:

restAdapter.setLogLevel(LogLevel.FULL);

**Comment by JakeWharton** [comment]
You should not be reading the body of the request. The fact that we do not set it to `null` every single time is a bug. This has already been fixed for 2.0 but I doubt it will be fixed for the current 1.x versions. You should assume that the response `getBody()` will never have useful information in it.
