### ISSUE TITLE
Switching between multiple endpoints.

### ISSUE THREAD

**Issue by amalChandran** [square/retrofit#697]
This is not a bug as such. I would like to know how to create a RestAdapter that can switch between two endpoints. Currently in my app, the RestAdapter is created in the Application class(singleton). I am looking for a way to have different endpoints without actually creating multiple RestAdapter.

**Comment by JakeWharton** [comment]
`Endpoint` is called for every request. If you want to switch on an algorithm you can implement your own (e.g., to do round-robin). Other than that, a single `RestAdapter` is tied to an `Endpoint`, you cannot control it on a per-method basis or anything.

**Comment by maddie** [comment]
Is it possible to do the same on Retrofit 2?

**Comment by JakeWharton** [comment]
Yes. `Endpoint` has been renamed `BaseUrl`.

**Comment by maddie** [comment]
Got it. Thanks a lot!
