### ISSUE TITLE
Calling retrofit function inside a ScheduledThreadPoolExecutor runnable

### ISSUE THREAD

**Issue by somghosh** [square/retrofit#703]
I have the following code to poll for the unread count of notification from server via retrofit (+ okhttp+gson) every 5 seconds or so

It seems that the retrofit function is not executing in this manner. If I simply remove the retrofit call the scheduled task executes after every 5 seconds. (I verified from logcat) However, with the Retrofit call (both async and sync without using callback but with a return type), I see the first log message just once, and then nothing whatsoever after it (and also no retrofit logcat debug messages).

The retrofit function works separately, as I have made standalone calls to it from the UI thread (and using callback arguments)

	public class App extends Application  {

    		
		private ScheduledExecutorService scheduleTaskExecutor;
		// some more code
	
	
		@Override
		public void onCreate() {
			super.onCreate();

			//region Set up the periodic notification count listener task

			scheduleTaskExecutor= Executors.newScheduledThreadPool(2);
			scheduleTaskExecutor.scheduleAtFixedRate(new PeriodicNotifCountFetchTask(), 0, 5, TimeUnit.SECONDS);
			
			//endregion
		}
		
		
		class PeriodicNotifCountFetchTask implements Runnable {

			@Override
			public void run() {
				Log.d("XXX", "Requesting Notification count from server ...");
				EMRestClient.getmEMRestService().getNotificationCount(new Callback<NotificationCount>() {
					@Override
					public void success(NotificationCount response, Response unused) {
						
						int unreadNotifCount = response.getCount();
						
						Log.d("XXX", "Successfully fetched notification count, unread = " + response.getCount());
						if (unreadNotifCount>0){
							// call listener to repaint menu
							for (NewNotificationListener x :notifListeners){
								x.onNewNotificationReceived(response.getCount());    
							}
						}
					}

					@Override
					public void failure(RetrofitError error) {
						Log.d("XXX", "Failed to fetch notification count from server");
					}
				});

			}
		}
		
	
	}

**Comment by JakeWharton** [comment]
Wrap the runnable in try/catch and look for an exception? Without more information I can't really figure out what is happening here.
