### ISSUE TITLE
Add callback for onPreExecute

### ISSUE THREAD

**Issue by xckevin** [square/retrofit#704]
As you know,  we always use `AsyncTask` to start a background task, which has `onPreExeceute`, `onPostExecute` and `onProgressUpdated`. But retrofit don't have callback for `onPreExecute`.
Now if I don't wanna modify source code, I must add ext proxy:

    static class KoalaProxy<T> implements InvocationHandler {
        
        private T t;
        
        public KoalaProxy(T t) {
            this.t = t;
        }
        
        public T bind(Class<T> clazz) {
            return (T) Proxy.newProxyInstance(clazz.getClassLoader(), new Class[]{clazz}, this);
        }

        @Override
        public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {
            if(args != null && args.length > 0) {
                String url = getUrlForMethod(method);
                if(url != null) {
                    for(Object arg : args) {
                        if(arg instanceof KoalaCallback) {
                            ((KoalaCallback)arg).onPreExecute(url);
                        }
                    }
                }
            }
            return method.invoke(t, args);
        }
    }

**Comment by JakeWharton** [comment]
Retrofit does not need a pre-execute callback because unlike AsyncTask, making a call into a Retrofit API immediately begins execution in the background (no call to `.execute()`). Simple do your pre-execute tasks before calling.

**Comment by cuizaixi** [comment]
I wann have a pre-execute callback for add a loading dialog
