### ISSUE TITLE
Converter not used on `@Form` args

### ISSUE THREAD

**Issue by marshallpierce** [square/retrofit#705]
In RequestBuilder#setArguments, Converter#toBody is only used on `@Part`, `@PartMap`, and `@Body` params. It would be nice to have a similar opportunity to control the serialization of form params; right now it just always calls `toString()`. In my case, I'd like to pass a pojo whose serialized representation is a form param without having to do the serialization effectively manually in every case.

**Comment by JakeWharton** [comment]
You want JSON formatted values in your form URL encoded body?

**Comment by marshallpierce** [comment]
Well, not JSON, but yes. What can I say but "legacy".

**Comment by JakeWharton** [comment]
This isn't something we're going to change with 1.x but it can be looked at for 2.x which is starting work soon.

**Comment by samskiter** [comment]
:+1: just found myself looking for exactly this. An error will need to be thrown for objects with depth > 1

**Comment by samskiter** [comment]
:+1: just found myself looking for exactly this. @FormMap on GSON convertible objects would be great :)

**Comment by samskiter** [comment]
@marshallpierce Hey I realised you can manage this with a custom converter, but only if you want this behaviour over your whole service. (we do). 

You have to remove the `@FormUrlEncoded` mark from your endpoint, then mark your object param as `@Body` for this to work...

Anyway, here's the converter for your enjoyment: https://gist.github.com/samskiter/822c78795f46df2571f9

**Comment by chakrit** [comment]
+1 for this. We use form-url-encoding for all inputs. Is there a 2.x branch where we can test this? I see there's a `okhttp-two` branch but not sure if that's just upgrading okhttp.

**Comment by JakeWharton** [comment]
We have decided not to support this. For one, it's flat out strange, as I've already said. But, there's also technical limitations. What does a protocol buffer or another binary format inside of form URL encoding body look like? Additionally, most servers should parse a multipart form-data request as form fields and our multipart support does allow serialization of parts using the supplied converter.

**Comment by samskiter** [comment]
So before this gets too far out of memory, I think it's worth saying that this isn't *that* strange - form arguments might be quite large and it's nice to manage those in an object. One of the main benefits of retrofit after all is to aid with serializing/deserializing objects from rest calls and avoid boilerplate marshalling.

What if we were to specify a form as an interface? so that the method names were `getFormkey()`. Implementing this in an object might look like:

```java
class FormArgs implements MyForm
{
    public String getFormKey()
    {
        return "blah";
    }
}
```

passing this object to a retrofit method might result in a URL like:

`http://www.mybase.url/myendpoint?formKey=blah`

**Comment by JakeWharton** [comment]
That's a query param not a form-encoded body. It follow the same principle, though, of using strings as values since they end up in the URL where something like a protocol buffer wouldn't work. You can also pass a map using `@QueryMap` for multiple values.

**Comment by talios** [comment]
Just commenting on this - I have a scenario where we have a domain specific `Password` type, that we want to pass into a retrofit method, but we want to provide a custom formatter for how this is set in the request fields.  Is there a way of handling that?
