### ISSUE TITLE
Retrofit error reporting API, where is it?

### ISSUE THREAD

**Issue by chjan** [square/retrofit#706]
We are using the Spotify web api that uses Retrofit, which is again using OkHttp and okio. We did the simple tutorial available in the readme of that api. The error was done not to include the okio.jar library in the build. Actually, the build process did not request it, which is a bit odd. The missing jar was not discovered during build, but produces a runtime error report as follows: Retrofit.error: okio.Buffer. Spotify web api receives this error through an "error" callback, and this is all information received.

This error was incomprehensible to me for a long working day, but as it seems, it is just a retrofit wrapping of a ClassNotFoundException reported by standard Java, the latter being trivial and would have pointed me to the missing okio.jar within minutes, had I seen it.

I would like to study the error reporting system of Retrofit in more detail. Can somebody please point me to this. I tried the Javadoc, but could not find anything. 

I am a bit confused as to why Retrofit is hiding away standard Java error reporting api as this is an effective one. Is there a tutorial that could enhance my understanding in this regard ?

**Comment by JakeWharton** [comment]
https://square.github.io/javadoc/

**Comment by JakeWharton** [comment]
As I told you on Okio, the underlying exception is in the caused by throwable, standard to every java exception.

**Comment by chjan** [comment]
Not working: https://square.github.io/javadoc/

**Comment by chjan** [comment]
Please explain in a bit more detail where I can observe this throwable. The okioxxx.jar is not reported missing during build, however it is necessary for the Spotify Web API to work. Then, the Android Debug monitor is used with no filters whatsoever in the Logcat. Everything else comes through there. 

Why do I not see the claimed exception reported in logCat?

**Comment by JakeWharton** [comment]
Did you e.printStackTrace()?
