### ISSUE TITLE
Okio exception not reported in logCat

### ISSUE THREAD

**Issue by chjan** [square/retrofit#707]
Ref to the #706 that was closed: Please explain in a bit more detail where I can observe this throwable. The okioxxx.jar is not reported missing during build, however it is necessary for the Spotify Web API to work. Isn't that a bit strange? Then, during runtime, the Android Debug monitor is used with no filters whatsoever in the Logcat. Everything else comes through there.

Why do I not see the claimed exception reported in logCat?

**Comment by f2prateek** [comment]
The missing dependencies should be documented on the Spotify API which requires OkHttp (which indeed does document it's dependency on Okio), not by Retrofit, which is agnostic of the underlying networking client used. The issue is probably that the Spotify API is distributing a lean JAR, without any transitive dependencies.

`RetrofitError` is a subclass of `RuntimeException`, so you can simply call the `getCause` method to retrieve the underlying error, which would likely return the underlying ClassNotFoundException.

```java
new Callback<Foo>() {
    @Override
    public void success(Foo foo, Response response) {
    }

    @Override
    public void failure(RetrofitError error) {
        Log.d("RetrofitError", error.toString());
        Log.d("Cause", error.getCause().toString()); // do some null checks
    }
});
```

**Comment by chjan** [comment]
Thanks, fog lifted somewhat, but it would be a good thing if exceptions were passed to the log system. This retrofit error clearly diminishes the whole intent of the Java RunTimeException system. 

I shall investigate your lean Jar theory over at Spotify Web api.

**Comment by f2prateek** [comment]
It's a common practice to wrap and rethrow exceptions, and very useful in this case. This way you can quickly inspect things like what response did the request failed for. If all Retrofit did was rethrow the exception as is, you'd lose the ability to inspect this extra information easily.

**Comment by chjan** [comment]
ok, but IMHO there is a theory vs practice element present in this case as the error report is both incomprehensible and seemingly non-related to the actual error.

**Comment by chjan** [comment]
Tried your trick without the null checks: Log.d("Cause", error.getCause().toString());

The results tells me I am (as a user of the Spotify Web API), far too long into the jungle of Retrofit where I do not want to be. Someone should take a look at this error reporting system:

![image](https://cloud.githubusercontent.com/assets/69140/5774763/a5a9659c-9d71-11e4-8ea1-3461ebd418bc.png)
