### ISSUE TITLE
Weird problems when using SimpleXML's @Commit sometimes

### ISSUE THREAD

**Issue by Fyren** [square/retrofit#708]
I'm using Retrofit 1.9.0 with async callbacks.  It seems like if I use SimpleXML's commit annotation in some of my classes, Retrofit never calls back after performing the REST call.  I don't have a reduced test case, but my structure is something like the following:

```java
class Member {
  @Commit
  public void commit() { } //causes breakage?
}

class Base {
  @Commit
  public void commit() { } //works fine?
}

class Derived extends Base {
  @ElementList
  List<Member> members;
}

class Result {
  @Element
  Derived derived;
}
```

With the commit-annotated function in Member, Retrofit never calls either success or failure on my Callback<Result>.  If I set logging to full, I see the request and response bodies with the expected contents/headers.  Both commit functions do get called.

If I comment out commit() in Member, then everything works as expected.  Retrofit calls either success or failure.  Also, commit() in Base still gets called.

Did I miss something in the Retrofit docs regarding this?  Is this expected?  If so, can I do anything about it?

**Comment by JakeWharton** [comment]
I have never used the Simple XML converter so I really can't help too much here. I just read the docs and `@Commit` is a crazy but interesting feature. Are you sure the `failure` callback isn't being invoked?

**Comment by Fyren** [comment]
That was a quick response, heh.  I'm logging something before starting the REST call, then something in both success and failure.  It looks like in some cases, it actually never calls either success or failure and in some cases, my Result is full of empties and nulls.  I can't figure out what's different between the two cases.

In my actual code, if I just comment out the one commit(), everything always works fine.

**Comment by JakeWharton** [comment]
Can you turn on Retrofit's logging? Call `.setLogLevel(LogLevel.FULL)` and watch the logs. See if it prints an error.

**Comment by Fyren** [comment]
Argh, yeah, I suck.  My fault.  My logging in failure was screwed up.  Retrofit's logging on full doesn't show the exception during conversion, so I didn't notice my logging (or my code causing the original exception) was bad.  I'm not sure if full logging should show it or not, but in any case, the original issue is definitely my fault.
