### ISSUE TITLE
Allow a service method to return ConnectableObservable<>

### ISSUE THREAD

**Issue by yogurtearl** [square/retrofit#710]
If a service method returns ConnectableObservable, then the server request would not be sent until the connect() method was called.

This allows you to detach the subscription from the sending of the request.

This would allow you to subscribe multiple observers and then connect().
IMO, it is more clear to have to call connect, than to remember that an HTTP call is a side effect of subscribe sometimes. 

The client code has to be aware of this special type of Observable with side effects, otherwise they might make more server requests than intended.

You can, of course, call .publish() on the Observables returned by the current version of Retrofit to turn them into ConnectableObservables, but you may forgot to do that in some places.

Calling subscribe to initiate a server call can obfuscate what is actually causing the server call for someone unfamiliar with Retrofit.

In fact, maybe for Retrofit 2 returning a plain Observable should be dis-allowed and ConnectableObservable could be the only option.

**Comment by jacobtabak** [comment]
I think this change would really clear up some confusion about when to subscribe and unsubscribe to/from observables relative to the activity lifecycle.

For example, if you had an activity that made 2 different network requests, you could subscribe all of the observables using a CompositeSubscription in `onCreate()` or `onResume()` and then unsubscribe from them at `onDestroy()` or `onPause()`

For example:

```
public class TestActivity extends Activity {
  @Inject MyService mService;
  private CompositeSubscription mSubscription = new CompositeSubscription();
  private ConnectableObservable<Response> mEmployeesObservable;
  private ConnectableObservable<Response> mCustomersObservable;

  interface MyService {
    public ConnectableObservable<Response> getEmployees();
    public ConnectableObservable<Response> getCustomers();
  }

  @Override protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    mEmployeesObservable = mService.getEmployees();
    mCustomersObservable = mService.getCustomers();
    mSubscription.add(mEmployeesObservable.subscribe(...));
    mSubscription.add(mCustomersObservable.subscribe(...));
  }

  @OnClick(R.id.employee_button)
  void onEmployeesClicked() {
    mEmployeesObservable.connect();
  }
  
  @OnClick(R.id.customer_button)
  void onCustomersClicked() {
    mCustomersObservable.connect();
  }

  @Override protected void onDestroy() {
    mSubscription.clear();
  }
}
```

@yogurtearl also makes a good point about how you'd be able to to subscribe multiple observables to the same network request, which has been much more complicated in the past - sometimes involving a separate PublishSubject.

**Comment by jacobtabak** [comment]
There has been some informal discussion about how Retrofit will handle network error conditions in 2.0, specifically, the `onError()` method will **not** be called in the case of a network error; rather, the return types will be wrapped in a Response<T> object.

`onComplete()` is similarly destructive - once it's called, all future subscribers will immediately receive their completion callbacks.  

In my opinion, `ConnectableObservables` should not enter a completed state after a successful response.  Re-connecting to an existing observable should make another network request, and any subscribers should have their onNext() method called.

@JakeWharton did you have plans to change the way onComplete() works for normal observables in 2.0?

**Comment by JakeWharton** [comment]
> `onComplete()` is similarly destructive - once it's called, all future subscribers will immediately receive their completion callbacks.

You are referring to a `ConnectableObservable` only here, right? I've never used one.

**Comment by yogurtearl** [comment]
As a note, one use case for ConnectableObservable from: 
http://www.introtorx.com/Content/v1.0.10621.0/14_HotAndColdObservables.html#PublishAndConnect

" In a financial trading application, if you wanted to consume a price stream for a certain asset in more than one place, you would want to try to reuse a single, common stream and avoid making another subscription to the server providing that data. "

**Comment by JakeWharton** [comment]
I understand the use case. Although the one you quoted doesn't sound much like HTTP.

**Comment by jondwillis** [comment]
One idea is to just call publish() on the Service's resulting observable. Now, you'd have to share that Connectable Observable instead of Retrofit doing it for you.

**Comment by chakrit** [comment]
Just wanted to add that if you have 2 serial network operations (for example, one API call depending on another first succeeding) then the ability to use something like `Observable.concat` to serialize the calls doesn't work, because the second call might've already been fired even before the first succeed: 

**Example:**

```java
Observable.concat(
    tokenApi.get(userId), // <- this call may modifies result from userApi.
    userApi.get(userId)
)
```

I _think_ having retrofit generates `ConnectableObservable` would actually solves my use case nicely as well. I could be wrong though since I'm not familiar with this publish/connect thing. :/

**Comment by chakrit** [comment]
That maybe just me but I think this should even be the default behavior, not the other way around. Since this allows you to manipulate the resulting observable before the actual HTTP call took place (on subscription).

**Comment by JakeWharton** [comment]
If you have two serial calls flatMap the second onto the first.
