### ISSUE TITLE
Add support for @Query/@Field enums with @SerializedName (or other annotation)

### ISSUE THREAD

**Issue by jacobtabak** [square/retrofit#711]
In the interest of clean, maintainable code, we've opted to use `Enum`s to represent some strings that can potentially contain spaces or non-alphanumeric characters.  Example:

```
enum CustomValues {
  @SerializedName("custom.value.one") CUSTOM_VALUE_ONE,
  @SerializedName("custom.value.two") CUSTOM_VALUE_TWO
}
```

When these values are requested from the server, they're run through the `GsonConverter` and mapped to the correct enum values.

However, if we want to send any of these values back up in a `@Query` or `@Field` parameter, the value is only encoded with `.toString()`; it is encoded as "CUSTOM_VALUE_ONE" rather than "custom.value.one".

Here's a link to the source of Gson's [`EnumTypeAdapter`](https://code.google.com/p/google-gson/source/browse/trunk/gson/src/main/java/com/google/gson/internal/bind/TypeAdapters.java#717).  I think it would make a lot of sense in Retrofit 2.0 to respect the `@SerializedName` annotation on `Enum`s if the `Converter` is a `GsonConverter`.

Here is my implementation of `.toString()` on `Enum` to achieve the desired result:

```
  @Override public String toString() {
    try {
      Annotation[] annotations = getClass().getField(name()).getAnnotations();
      for (Annotation annotation : annotations) {
        if (annotation.annotationType() == SerializedName.class) {
          return ((SerializedName)annotation).value();
        }
      }
    } catch (NoSuchFieldException e) {
      throw new RuntimeException(e);
    }
    return super.toString();
  }
```

**Comment by JakeWharton** [comment]
I don't really want to special case Gson in the core which is completely agnostic to content type. We don't even use Gson with Retrofit, for example.

An alternative would just be to specify the string in the enum constructor, return it from `toString`, and register a custom adapter via `@JsonAdapter` or on the `Gson` instance.

**Comment by jacobtabak** [comment]
I agree that it's not an ideal scenario, but if gson is the default converter, and a required dependency, it makes sense the serialization and deserialization should work the same way.  The current behavior is inconsistent and confusing, especially if you've written and tested all of the deserialization code only to be disappointed when you realize you have to hack something together to get the values to serialize correctly.

Supporting boilerplate-free custom serialization on enums will lead to some really clean & maintainable client code.  It's the type of code that I want to show my friends and say "hey, look how awesome Retrofit is!"  I think `@SerializedName` on enum values is a poorly documented gson feature and if it were fully supported people would use it a lot more.

But I'll just leave these 2c here :)

**Comment by JakeWharton** [comment]
> if gson is the default converter, and a required dependency

It's a default dependency, but it is by no means required. We exclude it and pull in other converters. It only exists so that Retrofit works "out of the box" since JSON is what most people want.

JSON is a content type. So is multipart and form URL-encoded. They are all peers. The only overlap is multipart which is a hierarchical content type (it can have other bodies in each part). Building on your example, Retrofit only uses the converter when you have a JSON content type as the top-level body or a multipart part. The use of the converter (or the semantics of a converter) are not present in headers, query params, path params, or form values. This was done for consistency with the semantics of the content types as they're defined in the HTTP spec.

If I wanted to have the same behavior as you desire without Gson on the classpath how would I do it?

**Comment by JakeWharton** [comment]
Or to even stick with GSON, what if I'm a Jackson user which can do the same thing with enum values but using a different annotation?

**Comment by jacobtabak** [comment]
> If I wanted to have the same behavior as you desire without Gson on the classpath how would I do it?

You'd write some code, but who wants to do that?

> what if I'm a Jackson user which can do the same thing with enum values but using a different annotation?

If Jackson has a similar annotation it would be nice it it was supported as well.  Maybe there's a converter-agnostic way to do it?

**Comment by JakeWharton** [comment]
The converter-agnostic way is just an annotation provided by Retrofit which I don't know if I'm too keen on.

**Comment by bsberry** [comment]
This would be nice, but I see the point about not wanting the Gson dependency.

**Comment by jacobtabak** [comment]
It could be accomplished without the dependency by checking the classpath.
But it's a slippery slope because if we add this functionality for gson,
then the code will eventually become littered with converter-specific
logic.

**Comment by adriancole** [comment]
I'm not sure there's a way out of this without introducing a
parameter-specific extraction annotation or an argument pre-processor (ex.
can mutate args around the invocation proxy call). Both of which add
significant weight to the internals.

**Comment by JakeWharton** [comment]
`toString` was chosen because it's global to every object and it allows objects to define their own representation. Without going through the pain of implementing a mechanism for registering object representation mappers (a la Gson's type adapter, and which i'm not remotely excited about doing) I'm not sure how to proceed here.

**Comment by JakeWharton** [comment]
An argument pre-processor and deserialized post-processor is being considered.

Bottom line: we can't support anything like this issue describes as a first-party mechanism. Closing.

**Comment by tisonkun** [comment]
If this won't be implemented in retrofit2 core, is it possible to implement this in `com.squareup.retrofit2:converter-gson`, that implement `stringConverter` for `GsonConverterFactory`?

**Comment by tisonkun** [comment]
Here is my implementation that maybe helpful:


```java
private static final class EnumConverterFactory extends Converter.Factory {
    private EnumConverterFactory() {}

    @Override
    public Converter<?, String> stringConverter(
            @NotNull Type type, Annotation @NotNull [] annotations, @NotNull Retrofit retrofit) {
        if (getRawType(type).isEnum()) {
            return new EnumConverter();
        }
        return null;
    }

    private static final class EnumConverter implements Converter<Enum<?>, String> {
        @Override
        public String convert(@NotNull Enum<?> o) {
            try {
                final Field f = o.getClass().getField(o.name());
                final SerializedName name = f.getAnnotation(SerializedName.class);
                if (name != null) {
                    return name.value();
                }
            } catch (Exception ignored) {
                // passthrough
            }
            return o.name();
        }
    }
}
```

I suppose it's possible to add in `com.squareup.retrofit2:converter-gson`. Either as the return value of `GsonConverterFactory#stringConverter `, or a new `GsonEnumConverterFactory`.
