### ISSUE TITLE
Single api call at once

### ISSUE THREAD

**Issue by kroobroeck** [square/retrofit#714]
Hi, I was wondering if I could do the following with retrofit...only one call can be executed at once. The second call can be called during execution of the first call, then the second one is queued en executed when the first call return or timed out.

If I can do this with retrofit, could someone point me in the right direction...

**Comment by JakeWharton** [comment]
You can pass `Executors.singleThreadExecutor()` as the first parameter to `RestAdapter.Builder`'s `setExecutors` method. This will allow only a single background job to be running at once, thus creating the behavior you desire.
