### ISSUE TITLE
RestAdapter crashes when logging null arguments

### ISSUE THREAD

**Issue by bsegall** [square/retrofit#716]
If you set `RestAdapter`'s logging level to HEADER_AND_ARGS or greater, and pass in null arguments  to your service calls you get a crash in `logAndReplaceRequest`:

    @GET
    void sampleFunction( @Field("test") String test );
    ...
    myService.sampleFunction( null );

...

    for (int i = 0; i < args.length; i++) {
      log.log("#" + i + ": " + args[i].toString());
    }

Why am I passing in null arguments? Because it suits my purposes (avoids sending arguments to the server in certain cases) and it seems to be supported and handled gracefully by RequestBuilder.setArguments:

    } else if (annotationType == Field.class) {
      String name = ((Field) annotation).value();
      if (value != null) { // Skip null values.

**Comment by JakeWharton** [comment]
Logging is being completely redone so I'm folding this into #378.
