### ISSUE TITLE
Add support for a ResponseInterceptor

### ISSUE THREAD

**Issue by alecio** [square/retrofit#719]
In my current project, we had to deal with some specific response headers that could come on any of the endpoints from our backend. We wanted then to create a 'generic' structure to handle it instead of providing a 'Callback'  to every individual call. Ideally we wanted something that would behave like the RequestInterceptor does with each request, but for the responses. So what we needed was something like a 'ResponseInterceptor'.

On the absence of such 'ResponseInterceptor' in the default Retrofit implementation, we've came up with the following solution described on the following stackoverflow post:
http://stackoverflow.com/questions/27230418/is-there-a-responseinterceptor-as-its-counterpart-requestinterceptor-compone

It would be nice if this could be applicable for future releases, so other users can take advangage from it.

Thanks!

**Comment by jdreesen** [comment]
This is already scheduled for 2.0 (#261)

**Comment by JakeWharton** [comment]
What he said. Also, OkHttp has interceptors which allow common handling of response headers if you don't want to wait.
