### ISSUE TITLE
Retrofit returns 400 error Bad request when Mobile data connection on, and works fine on Wi-Fi

### ISSUE THREAD

**Issue by bajalovic** [square/retrofit#720]
I am having a strange issue over here. My `PATCH` and `POST` Retrofit methods return 400 error, even before coming to server side, when mobile data connection is on. When I turn WI-Fi on, everything works fine.

           restAdapter = makeDefaultBuilder(baseURL).setRequestInterceptor(new RequestInterceptor() {
                @Override
                public void intercept(RequestFacade request) {
                   // setup headers
                }
            }).build();

where `makeDefaultBuilder` is:

    private RestAdapter.Builder makeDefaultBuilder(String baseURL) {
        OkHttpClient okHttpClient = new OkHttpClient();
        okHttpClient.setReadTimeout(READ_TIMEOUT, TimeUnit.SECONDS);
        okHttpClient.setConnectTimeout(CONNECT_TIMEOUT, TimeUnit.SECONDS);

        return new RestAdapter.Builder()
                .setLogLevel(RestAdapter.LogLevel.BASIC)
                .setEndpoint(baseURL)
                .setClient(new OkClient(okHttpClient))
                .setErrorHandler(new APIErrorHandler(context));
    }

Here is the log:

    01-28 10:26:15.919    9769-9796/com.example D/Retrofit﹕ ---> HTTP PATCH     http://example.com/api/v1/endpoint
    01-28 10:26:15.919    9769-9796/com.example D/Retrofit﹕ Cache-Control: no-cache
    01-28 10:26:15.919    9769-9796/com.example D/Retrofit﹕ Content-Type: application/json; charset=UTF-8
    01-28 10:26:15.919    9769-9796/com.example D/Retrofit﹕ Content-Length: 245
    01-28 10:26:15.920    9769-9796/com.example D/Retrofit﹕ {"settings":{"settings_1":true,"settings_2":true}}
    01-28 10:26:15.920    9769-9796/com.example D/Retrofit﹕ ---> END HTTP (245-byte body)
    01-28 10:26:17.023    9769-9796/com.example D/Retrofit﹕ <--- HTTP 400 http://example.com/api/v1/endpoint (1103ms)
    01-28 10:26:17.023    9769-9796/com.example D/Retrofit﹕ : HTTP/1.0 400 Bad request
    01-28 10:26:17.023    9769-9796/com.example D/Retrofit﹕ Connection: close
    01-28 10:26:17.023    9769-9796/com.example D/Retrofit﹕ Content-Type: text/plain
    01-28 10:26:17.023    9769-9796/com.example D/Retrofit﹕ Date: Wed Jan 28 09:26:17 2015
    01-28 10:26:17.023    9769-9796/com.example D/Retrofit﹕ OkHttp-Received-Millis: 1422437177022
    01-28 10:26:17.024    9769-9796/com.example D/Retrofit﹕ OkHttp-Response-Source: NETWORK 400
    01-28 10:26:17.024    9769-9796/com.example D/Retrofit﹕ OkHttp-Selected-Protocol: http/1.0
    01-28 10:26:17.024    9769-9796/com.example D/Retrofit﹕ OkHttp-Sent-Millis: 1422437176962
    01-28 10:26:17.024    9769-9796/com.example D/Retrofit﹕ Server:
    01-28 10:26:17.024    9769-9796/com.example D/Retrofit﹕ Request could not be understood( Status: 400 )
    01-28 10:26:17.024    9769-9796/com.example D/Retrofit﹕ <--- END HTTP (46-byte body)
    01-28 10:26:17.025    9769-9796/com.example E/APIErrorHandler﹕ Endpoint Error. StatusCode: 400, Error: API Changed Something, response: Request could not be understood( Status: 400 )

This request never make to server side. I tried setting headers `Cache-control: no-cache`, setting `.setCache(null)` on `OkHttpClient` (I had a thought that maybe request is cached).

When I try this request using `Postman`, or from terminal using `curl` everything is ok, and I do get response back.

I also tried to wrap a client in new class, and to check connectivity issues before making requests (thinking maybe there is no connectivity because it's on mobile data connection) but this did not help either.

Any more ideas? Thanks in advance.

**Comment by JakeWharton** [comment]
The response is definitely coming from across the network as evidenced by the `OkHttp-Response-Source` header and the fact that there's a body.

Perhaps it's a proxy server run by the cellular network that is intercepting your request and returning this response.

**Comment by JakeWharton** [comment]
I'm closing because this is definitely not a problem with Retrofit. As to what to do, I have no idea. You could try using a HTTPS URL and certificate pinning in the HTTP client to ensure that you only talk to the real server.

**Comment by bajalovic** [comment]
Hi @JakeWharton I created a new android app, and added Retrofit by following basic sample from your website. Here is the source code: https://github.com/bajalovic/TestRetrofit

I create a sample Rails app, hosted it on Heroku, and just one PATCH action: http://secret-lake-7090.herokuapp.com/welcome/update

And here are the two responses, first when I am on data connection, and second one when I am on the wifi:

    02-02 22:06:06.508  21242-21314/com.esseworks.testretrofit D/Retrofit﹕ ---> HTTP PATCH http://secret-lake-7090.herokuapp.com/welcome/update.json
    02-02 22:06:06.508  21242-21314/com.esseworks.testretrofit D/Retrofit﹕ Content-Type: application/json; charset=UTF-8
    02-02 22:06:06.508  21242-21314/com.esseworks.testretrofit D/Retrofit﹕ Content-Length: 38
    02-02 22:06:06.509  21242-21314/com.esseworks.testretrofit D/Retrofit﹕ {"params":{"p2":"world","p1":"hello"}}
    02-02 22:06:06.509  21242-21314/com.esseworks.testretrofit D/Retrofit﹕ ---> END HTTP (38-byte body)
    02-02 22:06:07.640  21242-21314/com.esseworks.testretrofit D/Retrofit﹕ <--- HTTP 400 http://secret-lake-7090.herokuapp.com/welcome/update.json (1130ms)
    02-02 22:06:07.640  21242-21314/com.esseworks.testretrofit D/Retrofit﹕ : HTTP/1.0 400 Bad request
    02-02 22:06:07.640  21242-21314/com.esseworks.testretrofit D/Retrofit﹕ Connection: close
    02-02 22:06:07.640  21242-21314/com.esseworks.testretrofit D/Retrofit﹕ Content-Type: text/plain
    02-02 22:06:07.640  21242-21314/com.esseworks.testretrofit D/Retrofit﹕ Date: Mon Feb  2 21:06:08 2015
    02-02 22:06:07.640  21242-21314/com.esseworks.testretrofit D/Retrofit﹕ Server:
    02-02 22:06:07.640  21242-21314/com.esseworks.testretrofit D/Retrofit﹕ X-Android-Received-Millis: 1422911167638
    02-02 22:06:07.641  21242-21314/com.esseworks.testretrofit D/Retrofit﹕ X-Android-Response-Source: NETWORK 400
    02-02 22:06:07.641  21242-21314/com.esseworks.testretrofit D/Retrofit﹕ X-Android-Sent-Millis: 1422911167579
    02-02 22:06:07.641  21242-21314/com.esseworks.testretrofit D/Retrofit﹕ Request could not be understood( Status: 400 )
    02-02 22:06:07.641  21242-21314/com.esseworks.testretrofit D/Retrofit﹕ <--- END HTTP (46-byte body)


    02-02 22:18:50.545  21242-23293/com.esseworks.testretrofit D/Retrofit﹕ ---> HTTP PATCH http://secret-lake-7090.herokuapp.com/welcome/update.json
    02-02 22:18:50.545  21242-23293/com.esseworks.testretrofit D/Retrofit﹕ Content-Type: application/json; charset=UTF-8
    02-02 22:18:50.545  21242-23293/com.esseworks.testretrofit D/Retrofit﹕ Content-Length: 38
    02-02 22:18:50.545  21242-23293/com.esseworks.testretrofit D/Retrofit﹕ {"params":{"p2":"world","p1":"hello"}}
    02-02 22:18:50.545  21242-23293/com.esseworks.testretrofit D/Retrofit﹕ ---> END HTTP (38-byte body)
    02-02 22:18:51.005  21242-23293/com.esseworks.testretrofit D/Retrofit﹕ <--- HTTP 200 http://secret-lake-7090.herokuapp.com/welcome/update.json (460ms)
    02-02 22:18:51.005  21242-23293/com.esseworks.testretrofit D/Retrofit﹕ : HTTP/1.1 200 OK
    02-02 22:18:51.006  21242-23293/com.esseworks.testretrofit D/Retrofit﹕ Cache-Control: max-age=0, private, must-revalidate
    02-02 22:18:51.006  21242-23293/com.esseworks.testretrofit D/Retrofit﹕ Connection: keep-alive
    02-02 22:18:51.006  21242-23293/com.esseworks.testretrofit D/Retrofit﹕ Content-Length: 155
    02-02 22:18:51.006  21242-23293/com.esseworks.testretrofit D/Retrofit﹕ Content-Type: application/json; charset=utf-8
    02-02 22:18:51.006  21242-23293/com.esseworks.testretrofit D/Retrofit﹕ Date: Mon, 02 Feb 2015 21:18:51 GMT
    02-02 22:18:51.006  21242-23293/com.esseworks.testretrofit D/Retrofit﹕ Etag: "7e4b82007afa8c178343553a2ee90c04"
    02-02 22:18:51.006  21242-23293/com.esseworks.testretrofit D/Retrofit﹕ Server: WEBrick/1.3.1 (Ruby/2.0.0/2014-11-13)
    02-02 22:18:51.006  21242-23293/com.esseworks.testretrofit D/Retrofit﹕ Via: 1.1 vegur
    02-02 22:18:51.006  21242-23293/com.esseworks.testretrofit D/Retrofit﹕ X-Android-Received-Millis: 1422911931005
    02-02 22:18:51.006  21242-23293/com.esseworks.testretrofit D/Retrofit﹕ X-Android-Response-Source: NETWORK 200
    02-02 22:18:51.006  21242-23293/com.esseworks.testretrofit D/Retrofit﹕ X-Android-Sent-Millis: 1422911930786
    02-02 22:18:51.006  21242-23293/com.esseworks.testretrofit D/Retrofit﹕ X-Content-Type-Options: nosniff
    02-02 22:18:51.006  21242-23293/com.esseworks.testretrofit D/Retrofit﹕ X-Frame-Options: SAMEORIGIN
    02-02 22:18:51.006  21242-23293/com.esseworks.testretrofit D/Retrofit﹕ X-Request-Id: 0581c425-83b5-4ed4-8366-42743f54d292
    02-02 22:18:51.006  21242-23293/com.esseworks.testretrofit D/Retrofit﹕ X-Runtime: 0.031767
    02-02 22:18:51.006  21242-23293/com.esseworks.testretrofit D/Retrofit﹕ X-Xss-Protection: 1; mode=block
    02-02 22:18:51.007  21242-23293/com.esseworks.testretrofit D/Retrofit﹕ {"params":{"params":{"p2":"world","p1":"hello"},"controller":"welcome","action":"update","format":"json","welcome":{"params":{"p2":"world","p1":"hello"}}}}
    02-02 22:18:51.008  21242-23293/com.esseworks.testretrofit D/Retrofit﹕ <--- END HTTP (155-byte body)

**Comment by bajalovic** [comment]
A little update. I just added new route for PUT, everything else is the same. It seems that there is no problem with Network 400 error when the request is PUT. On PATCH I still get 400 error.

**Comment by matt-thinair** [comment]
The first PATCH request is using HTTP 1.0, PATCH was introduced in HTTP 1.1 and thus is not understood using HTTP 1.0

**Comment by SayoojDev** [comment]
I am also facing the same issue. 
My configuration : 
```
compile 'com.squareup.retrofit:retrofit:1.9.0'
compile 'com.squareup.okhttp:okhttp-urlconnection:2.0.0'
compile 'com.squareup.okhttp:okhttp:2.3.0'
```

Issue Log : 

08-16 18:36:47.635 13771-14231/tv.accedo.airtel.wynk D/Retrofit: ---> HTTP POST http://54.251.164.80:8080/wynk/v2/account/login?service=video
08-16 18:36:47.635 13771-14231/tv.accedo.airtel.wynk D/Retrofit: x-bsy-did: 5cd0876802a60413
08-16 18:36:47.635 13771-14231/tv.accedo.airtel.wynk D/Retrofit: x-app-version: 0.0.1
08-16 18:36:47.635 13771-14231/tv.accedo.airtel.wynk D/Retrofit: x-bsy-imei: 353968070096673
08-16 18:36:47.635 13771-14231/tv.accedo.airtel.wynk D/Retrofit: x-bsy-imsi: 404950113948835
08-16 18:36:47.635 13771-14231/tv.accedo.airtel.wynk D/Retrofit: x-bsy-location : 
08-16 18:36:47.635 13771-14231/tv.accedo.airtel.wynk D/Retrofit: x-bsy-network: 3g
08-16 18:36:47.635 13771-14231/tv.accedo.airtel.wynk D/Retrofit: Content-Type: application/json
08-16 18:36:47.635 13771-14231/tv.accedo.airtel.wynk D/Retrofit: Content-Length: 156
08-16 18:36:47.635 13771-14231/tv.accedo.airtel.wynk D/Retrofit: {"osVersion":"6.0.1","name":"","deviceKey":"APADdd8231gg","deviceId":"5cd0876802a60413","appVersion":"0.0.1","os":"Android","deviceType":"Samsung SM-T815Y"}
08-16 18:36:47.635 13771-14231/tv.accedo.airtel.wynk D/Retrofit: ---> END HTTP (156-byte body)
08-16 18:36:47.835 13771-14231/tv.accedo.airtel.wynk D/Retrofit: <--- HTTP 400 http://54.251.164.80:8080/wynk/v2/account/login?service=video (197ms)
08-16 18:36:47.835 13771-14231/tv.accedo.airtel.wynk D/Retrofit: Cache-Control: no-cache
08-16 18:36:47.835 13771-14231/tv.accedo.airtel.wynk D/Retrofit: Connection: close
08-16 18:36:47.835 13771-14231/tv.accedo.airtel.wynk D/Retrofit: Content-Type: text/html
08-16 18:36:47.835 13771-14231/tv.accedo.airtel.wynk D/Retrofit: OkHttp-Selected-Protocol: http/1.0
08-16 18:36:47.835 13771-14231/tv.accedo.airtel.wynk D/Retrofit: OkHttp-Sent-Millis: 1471352807730
08-16 18:36:47.835 13771-14231/tv.accedo.airtel.wynk D/Retrofit: OkHttp-Received-Millis: 1471352807833
08-16 18:36:47.835 13771-14231/tv.accedo.airtel.wynk D/Retrofit: <html><body><h1>400 Bad request</h1>
                                                                 Your browser sent an invalid request.
                                                                 </body></html>
08-16 18:36:47.835 13771-14231/tv.accedo.airtel.wynk D/Retrofit: <--- END HTTP (90-byte body)

**Comment by SayoojDev** [comment]
An Update : When I connected Charles to my device the response is correct.

```
HTTP/1.1 200 OK
ct: application/json; charset=UTF-8
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 1728000
Access-Control-Allow-Headers: X-Requested-With
Content-Encoding: gzip
Connection: close

```

Also see in error log please see

**## OkHttp-Selected-Protocol: http/1.0**

is okHttp support 1.0

**Comment by Yemjee** [comment]
i too had similar problem. i solved it by editing the 'Mobile networks' settings provided by the network. for this go to ur mobile setting and search for 'Mobile networks' somewhere with in 'Mobile data' section. Now you will see fields like name,apn,proxy , port...etc... just edit two fields ie proxy field with the ip address of your server, and port field with your port and save the changes and try... hope that works.. :)

**Comment by iwebnetid** [comment]
Maybe they using token to login .. try this [](https://futurestud.io/tutorials/retrofit-token-authentication-on-android)

**Comment by iwebnetid** [comment]
https://futurestud.io/tutorials/retrofit-token-authentication-on-android
