### ISSUE TITLE
Could @QueryMap handle object as parameter? 

### ISSUE THREAD

**Issue by ptitvinou** [square/retrofit#722]
Hi there!

Not entirely sure this is the right place to write this ticket as this is marked  as issues and I am asking for an evolution.

I'd like to know if there is a way to extend the @QueryMap annotation to handle Object as the Map value in order to send Objects for GET methods?

As of now, @QueryMap converts the Object into a String according to the documentation. Because you can't use the @Body annotation for GET requests (which is, from what I understood, doable with HTTP/1.1 specs), there is now way that I can see to send my object in my request.

Am I missing something here?

**Comment by JakeWharton** [comment]
This is not only extremely uncommon but is generally considered bad practice. As such, Retrofit will not natively support it. See also: http://stackoverflow.com/a/15656884/132047

You can create your own HTTP method annotation which allows a body for GET but there's no guarantees the underlying HTTP client will allow it:
```java
@Target(METHOD)
@Retention(RUNTIME)
@RestMethod(value = "GET", hasBody = true)
public @interface GET_WITH_BODY {
  String value();
}
```
