### ISSUE TITLE
Could RequestInterceptor provide information about the request itself?

### ISSUE THREAD

**Issue by juliomarcos** [square/retrofit#723]
I'm building a RequestInterceptor like these

return new RequestInterceptor() {
            @Override
            public void intercept(RequestFacade request) {
                final String cookies = simpleCookieStore.retriveFormattedCookies(getHostFromEndPoint());
                if (cookies.length() > 0) {
                    request.addHeader("Cookie", cookies);
                }
            }
        };

But I also need to access some request headers. Is it possible?

**Comment by JakeWharton** [comment]
This is not possible. The interceptors in Retrofit run while the request is being built. You can use [OkHttp's interceptors][1] to do this, though.

 [1]: https://github.com/square/okhttp/wiki/Interceptors
