### ISSUE TITLE
How to Handle Responses without a Body

### ISSUE THREAD

**Issue by VinyWenkz** [square/retrofit#734]
Hello,

My expected response is only http code 200 without any body. I always get Callback failure even if I am using Callback \<Void\> or Callback \<Object\>.

The error I get is retrofit.converter.ConversionException: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4 path $.

How should I handle the null response?

Thanks

**Comment by jacobtabak** [comment]
Try Callback<Response>.  StackOverflow may be more appropriate for this type of question.

**Comment by JakeWharton** [comment]
Yes, use that.

Your response also clearly does have a body of some sort or Gson wouldn't be trying to parse it.
