### ISSUE TITLE
Add the possibility of using Observables for request interception?

### ISSUE THREAD

**Issue by jnlopar** [square/retrofit#737]
In my app I use Observables from retrofit, and I have a request interceptor to add things like the auth token. The problem is that the auth token method is blocking, and must be run off the main thread. This requires a subscribeOn call on the returned observable all the time (and usually nasty blowups at runtime if I forget), since as mentioned in #651, it seems that interceptors default to the main thread (or maybe whatever the calling thread is.)

If it were possible to set an Observable interceptor, which could return a header/query map, we could easily define in one place subscribe/observe threads for these calls, as well as make it a lot easier to manage potentially blocking operations like grabbing an auth token.

**Comment by JakeWharton** [comment]
Another approach to have this work today is by adding the header in an [OkHttp interceptor][1].

 [1]: https://github.com/square/okhttp/wiki/Interceptors

**Comment by jnlopar** [comment]
That looks pretty useful. However, it looks like it's OkHttp-only (which we're using right now, but may not be always the case), and it also seems to push the blocking calls back a level without the nice control that Rx Observables provide. Still, it's a definite improvement, I'll look more into these. :)

**Comment by JakeWharton** [comment]
Retrofit 2 is built on OkHttp so interceptors are the best approach here. Retrofit's interceptor has been removed. Another possible way to do this is passing the value through as a method parameter that you can lookup on a BG thread.
```java
interface Service {
  @POST("/")
  Whatever addData(@Body Data data, @Header("Authorization") String auth);
}
```
```java
Observable.just(data)
    .observeOn(computation())
    .flatMap(data -> {
        String auth = lookupAuth();
        return service.addData(data, auth);
    })
    .observeOn(mainThread())
    .subscribe(updateUi());
```
