### ISSUE TITLE
Problem with relative PUT annotation

### ISSUE THREAD

**Issue by Kondra007** [square/retrofit#740]
Hello, guys.
I have a nasty problem, hope to see a solution. 
I'm working with one Cloud Storage, when uploading files:
1) I make GET request to /upload/... and **I get a link to upload** (https://www.example.com/...)
2) I need to make put request with that link. The problem is that link isn't relative path, but @ PUT annotation requires relative.

Is there any way to solve this problem?

P.S. I guess it's somehow similar to #498

**Comment by casidiablo** [comment]
Well, then make it relative. Just remove the scheme, host and port information from that link. And add a PUT method that receives the path:

```java
public interface Foo {
        @PUT("/{path}")
        String foo(@Path(value = "path", encode = false) String thePath);
}
```

**Comment by Kondra007** [comment]
@casidiablo Could you please explain your answer?
I'll give and example to make sure we understand each other.
1) I have baseURL = "http://example.com"
Make GET request @ GET("/upload") and recieve a link to upload ("https://mysite.com/file/123456");

2) I need to make PUT request not relative to example.com, but to https://mysite.com/file/123456
However, path must start with "/".

**Comment by JakeWharton** [comment]
This is the same as #333.

**Comment by casidiablo** [comment]
@Kondra007 yup... all that is covered in my previous answer.

**Comment by Kondra007** [comment]
@casidiablo maybe I understood you wrong, because your way didn't work for me :(
However, I've managed to solve this:
https://github.com/square/retrofit/issues/333#issuecomment-73320733
