### ISSUE TITLE
Improves documentation with retrofit-mock

### ISSUE THREAD

**Issue by GerardPaligot** [square/retrofit#748]
Hi,

Currently, I'm working on an android application which use retrofit and I would like to test my application with retrofit-mock and robolectric. There hasn't really a problem about that but to find the documentation of retrofit-mock, I must to read the javadoc in the source code.

Can we improve the current documentation/website (or create a new one) to show the documentation of retrofit-mock too?

Thanks in advance!

**Comment by JakeWharton** [comment]
Sure. Also, see https://github.com/JakeWharton/u2020 for a comprehensive example.

**Comment by JakeWharton** [comment]
There's now a sample, [`SimpleMockService`][1]. More will be added over time, but u2020 is a great source here.

 [1]: https://github.com/square/retrofit/blob/master/samples/src/main/java/com/example/retrofit/SimpleMockService.java
