### ISSUE TITLE
using post method gets IllegalStateException

### ISSUE THREAD

**Issue by sajadshokri** [square/retrofit#758]
I'm using retrofit library as Rest client, and wonder how exactly should i use it to post something?

I'm using it as follow:

```
@FormUrlEncoded
@POST("/edit")
void postFoFt(@Field("FO") String fo,@Field("FT") boolean ft ,Callback<SimpleCB> cb); 
```

and i receive an error:

    com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

and the same error while using `@FieldMap`

**Comment by JakeWharton** [comment]
Looks like your server isn't returning JSON, hence the error message from Gson. Log the response and see what you are getting.

This isn't a problem with Retrofit nor even Gson. There's hundreds of questions like this on StackOverflow. Basically, you are expecting a JSON object but that's not what's in the HTTP response.

**Comment by sajadshokri** [comment]
OK

you are right.
i just want to see the response of server, if it sends OK (200) or not. what should i do?

**Comment by JakeWharton** [comment]
You can use `retrofit.client.Response` as the type for `Callback`, this will prevent Gson from trying to convert the response.
