### ISSUE TITLE
Downloading files via HTTPS links ?

### ISSUE THREAD

**Issue by SuperHich** [square/retrofit#759]
Hello,

Does RETROFIT permit downloading files via HTTPS requests ?
If yes, is there an exple ?

Thanks in advance...

**Comment by JakeWharton** [comment]
Yes. Just use "https" as the scheme when you are creating your `Endpoint` or passing a string to `RestAdapter.Builder`'s `setEndpoint` method. The HTTP client is responsible for all of that, Retrofit just eliminates the boilerplate around creating requests.

Please direct general questions to StackOverflow with the 'retrofit' tag as they'll be much better served by that community (which also includes the developers of this project).
