### ISSUE TITLE
Documentation / Sample Application

### ISSUE THREAD

**Issue by geniushkg** [square/retrofit#760]
I am newbie and cant understand hoe to implement use retrofit , there are lots of tutorials on web but none of them expain clearly or give sample code

Hence please give simple sample code or explaination /documentation

**Comment by sohayb** [comment]
Did you check [website?!](http://square.github.io/retrofit/)
I think it has all the explanations and sample code you need, but no full application sample though.
Good luck :)

**Comment by geniushkg** [comment]
@sohayb   , yeah seen website but cant get exactly as per my understanding and scenario for android
 refer below  
------------------------------------------------------------
1) API.java - (contains interface code , API declaration)
2) Model.java - (conatins POJO for coresponding json schema / constructor)
3) Main activity.java - (contains Restadapte builer / Service)

--------------------------------------------------------------------------------------
Is this corect way , to implement network call on main ui thread , I followed the 
http://inaka.net/blog/2014/10/10/android-retrofit-rest-client/  , tutorial and got data (partialy) but

Just guide me direction to correctly implement rest client using Retrofit

Thanks :+1:

**Comment by sohayb** [comment]
For me, I separated the communication in a separate class containing the RestAdapter and made it available through a singleton, in its constructor I configured the RestAdapter. The network call methods are in that class like MyRestService.getInstance().getStores(), or it can be with a callback.

**Comment by geniushkg** [comment]
thanks :+1:
