### ISSUE TITLE
api_key along with all api requests

### ISSUE THREAD

**Issue by Fshamri** [square/retrofit#761]
Hi,
I am using retrofit to call my api service but my Api rules are as follows:
- api_key must be sent along with all requests.
- api_key must be sent as application/x-www-form-urlencoded only. ( not as headers)

How can I achieve this using retrofit
Thanks

**Comment by CCMDevel** [comment]
You have to add the `@FormUrlEncoded` tag. Then, set your fields accordingly in your API interface.

    public interface PiksApi {    
        @FormUrlEncoded
        @POST("/something")
        void postSomething(@Field("api_key") String api_key, /* other fields */ , Callback<PostResponse> callback);

The above example is for a post with a body of application/x-www-form-urlencoded data. If you have to add information in another way (i.e. params, query), you have to do so in your retrofit API interface.

**Comment by JakeWharton** [comment]
Yep, do what @CCMDevel said.

Sending the API key in a form URL-encoded body is strange. Most APIs use either a header, query param, or include it in the URL, all of which can be added centrally using a request interceptor. We do not allow altering the body of the request in the interceptor, however, so it will not work in this specific case.
