### ISSUE TITLE
Supply default RequestBody converters for primitives?

### ISSUE THREAD

**Issue by b22n** [square/retrofit#763]
Retrofit 1.9.0 / OkHttp 2.2.0
Using default GsonConverter
```
@Multipart
@PUT("/xxxx")
void method (
   @Part("idx") long idx,
   @Part("image") TypedFile image
);
```
Request Header:
Content-Type: multipart/form-data; boundary=9bf70ec9-6823-4209-ac75-933a931b8baf
Content-Length: 673890
--9bf70ec9-6823-4209-ac75-933a931b8baf
    Content-Disposition: form-data; name="idx"
    <b>Content-Type: application/json; charset=UTF-8</b>
    Content-Length: 3
    Content-Transfer-Encoding: binary
   <b> 244</b>

Expectation: the body param should be encoded in json format or Content-Type should be the 'text/plain'.

**Comment by JakeWharton** [comment]
`long` is a primitive, so it has no structure in JSON format. If the object was not a primitive you would see the normal JSON structure. You can achieve `text/plain` easily by using a `String` instead for the parameter type instead.

**Comment by b22n** [comment]
the wrapper class Long is also encoded with plain text.
and I think, if primitive types have no structure in JSON format, the Content-Type header shouldn't be the 'application/json'.

**Comment by JakeWharton** [comment]
Maybe for 2.0.

**Comment by sigod** [comment]
I just want to point out that `244` is a valid JSON.

**Comment by JakeWharton** [comment]
It isn't.

**Comment by sigod** [comment]
Yes, it is.

> Early versions of JSON (such as specified by RFC 4627) required that a valid JSON "document" must consist of only an object or an array type—though they could contain other types within them. This restriction was removed starting with RFC 7158, so that a JSON document may consist entirely of any possible JSON typed value.

**Comment by JakeWharton** [comment]
@sigod Ew, that's dumb. Thankfully it's not Retrofit's problem but the serialization library being used.

Renamed this issue to correctly reflect what it's asking for.
