### ISSUE TITLE
PUT Request fails on android Lollipop 

### ISSUE THREAD

**Issue by visheshvvs** [square/retrofit#764]
Following the REST API,  I encounter an error while using the PUT method through retrofit call. The error occurs only in Lollipop version of android whereas it works fine on the other O.S. as tested thoroughly . I am sending data in the body of the request and while debugging it , it shows that the body has been successfully sent but the server does not receive it .  The error occurs randomly as it may or may not work . What could be the possible reason and solution?

**Comment by JakeWharton** [comment]
There's no information to go on here (stacktrace, error message, repro code), and I see you've posted on StackOverflow so I'll defer to there: http://stackoverflow.com/q/28778407/132047.

In general, Retrofit only takes part in the creation and execution of the request. The actual application of HTTP semantics on the socket is the job of the underlying HTTP client. And if the request fails only on certain versions of Android, it's going to be at that level.

Anyway, hope someone answers on StackOverflow. You might try adding code and a stacktrace.
