### ISSUE TITLE
No response body for POST request with 4xx error code, only when using HttpURLConnection

### ISSUE THREAD

**Issue by bubbleguuum** [square/retrofit#767]
Using retrofit  1.9.0.
If making a POST request using HttpURLConnection that results in a 4xx http error with a response body, Retrofit does not see the response body (getBody() == null).
It works using OkHttp.

**Comment by JakeWharton** [comment]
I cannot reproduce this.

We use the error stream if the response is 400 or greater which is where HttpURLConnection puts the error body: https://github.com/square/retrofit/blob/2f4caa6f5df8e7f47a881266bbfc723f537b0b47/retrofit/src/main/java/retrofit/client/UrlConnectionClient.java#L88-L92

As a bonus: version 2 will build directly on OkHttp so this won't be a problem in practice anymore.
