### ISSUE TITLE
dns bug or proxy bug

### ISSUE THREAD

**Issue by geniushkg** [square/retrofit#768]
When I am trying to call api.github.com , retrofit converts it to some 192.30.xx.xx Ip , I think this is a bug, 

I have my complete source code uploaded at 
___________________________________________________________________________
: https://github.com/geniushkg/Android-Retrofit-callback-async-sample
___________________________________________________________________________

PLease just once compile on your machine and run , you'l see on logcat , what I am saying

My logcat is like this
_____________________________________________________________________________
failed to connect to api.github.com/192.30.252.139 (port 80): connect failed: ECONNREFUSED (Connection refused)
03-03 23:59:43.720  13691-13691/in.ist.android_retrofit_callback_async_sample E/retrofit﹕ http://api.github.com/repos/square/retrofit/contributors
03-03 23:59:43.720  13691-13691/in.ist.android_retrofit_callback_async_sample E/retrofit﹕ retrofit.RetrofitError: failed to connect to api.github.com/192.30.252.139 (port 80): connect failed: ECONNREFUSED (Connection refused)
______________________________________________________________________________

**Comment by JakeWharton** [comment]
This has nothing to do with Retrofit. DNS resolution and connection of the socket happens by Java. Either your DNS setup, network config, or GitHub is blocking you from connecting.

**Comment by geniushkg** [comment]
I dont know exactly now how to solve the error , anyways have you faced simmilar problem ? 
or if possible give some direction 

Thank you :+1:  , 
Jake your a legend Not because you closed this issue in 3mins but you are really hardworking
hatsoff

**Comment by JakeWharton** [comment]
I get the same IP for resolving `api.github.com` so the problem is that a firewall or GitHub itself is blocking your access for some reason. I really can't know more without actually being there. Try running a `traceroute` perhaps?
