### ISSUE TITLE
Receive empty json objects

### ISSUE THREAD

**Issue by MadScientistUA** [square/retrofit#769]
When i download json array List<JSONObject> it returns right number of exist json objects, but all of them are empty.
```
List<JSONObject> arr = projects.result(accountDB.getCompany(),accountDB.getToken());
            Log.wtf("","projects list: " + arr.toString());
            for(int i = 0; i < arr.size(); i++){
                list.add(new ProjectHelper(arr.get(i)).getProject());
                Log.wtf("", "jsonObj: "+arr.get(i).toString());
            }
```
Log here
```
projects list: [{}, {}]
jsonObj: {}
jsonObj: {}
```

**Comment by JakeWharton** [comment]
Don't use `JSONObject`, that's a terrible, awful, horrible JSON API that nobody should use nor should even exist.

You'll want to look at the [Gson documentation](https://sites.google.com/site/gson/gson-user-guide) for how to create objects that can be deserialized.
