### ISSUE TITLE
Doing requests with the same cookie setted before

### ISSUE THREAD

**Issue by KeizerDev** [square/retrofit#770]
Hi,

I'm using a api where I have to auth myself to open a specific page.
Not that awesome but how do is use the cookie I've use before?
My code now:
(Interface)
```
    @POST("/sessie")
    void setSessie(@Body User user, Callback<List<String>> callBack);
```
This is working propably. When I set the log level on full I get something like this:

**Comment by JakeWharton** [comment]
Cookies are just headers. You can either have the HTTP client manage them, use [a `@Header` annotation][1], or use [a `RequestInterceptor`][2] to add them to every request.

Please direct future questions to StackOverflow with the 'retrofit' tag.

 [1]: http://square.github.io/retrofit/javadoc/retrofit/client/Header.html
 [2]: http://square.github.io/retrofit/javadoc/retrofit/RequestInterceptor.html

**Comment by KeizerDev** [comment]
Sorry, I posted that too early and sorry I posted here.
This is my full question, I had clicked on the submit button too early by accident. (Tab + space...)

Thanks for your fast answer!
