### ISSUE TITLE
Not able to make network request in pre lollipop devices

### ISSUE THREAD

**Issue by makk909** [square/retrofit#772]
I don't know what the problem is but everytime when i try to make a network request in pre lollipop devices, am getting TypeNotPresentException followed by ClassNotFoundException and NoClassDefFound error for my pojo classes, although they are working fine in android lollipop devices.
So Help me suggesting whether it is a problem with the latest gradle dependency of Retofit or something else.

**Comment by sohayb** [comment]
Are you facing this in a signed application package after applying proguard on it?

**Comment by makk909** [comment]
Problem is coming in both signed and debugged apk.

**Comment by sohayb** [comment]
For pojo objects in your signed package, please make sure you keep your serialized classes in the proguard configuration file like this ````-keep class com.your.models.package.** { *; }````.
And regarding Retrofit configuration, make sure to add these:
````
-keep class retrofit.** { *; }
-keepclasseswithmembers class * {
    @retrofit.http.* <methods>;
}
````
Hope this helps

**Comment by makk909** [comment]
Sorry I have seen this answer somewhere but i am not getting where  to write these lines in my gradle file inside build types??

**Comment by frodberserk** [comment]
@sohayb I don't know how that will help in debug apk as proguard will run only in release apk.

**Comment by sohayb** [comment]
@makk909 you should write them in your proguard configuration file (maybe named proguard-rules.pro or something in your main app module)
@frodberserk you're basically right, but I think that maybe the proguard is running for the debug (some misconfiguration in the build.gradle file), because these kind of errors are very rare to happen in debug mode with android studio and gradle dependencies.

**Comment by JakeWharton** [comment]
Please ask this on StackOverflow with the 'retrofit' tag. This is a configuration problem, not a bug in the library. Others might have this problem and StackOverflow is the right place for archival and search as well as simply getting the right people looking at the problem.
