### ISSUE TITLE
JSON key with dash

### ISSUE THREAD

**Issue by jestillore** [square/retrofit#777]
How will I handle a JSON key with dash/hypen?
Below is the sample response.
```
"request": {
    "authenticate-login": {
        "response": {
            "status": 1,
            "msg": "User Authorized!"
        }
    }
}
```

**Comment by HoracioFilho** [comment]
@jestillore I think is better you ask that question in StackOverflow, you will get answers more quickly :D.

**Comment by jestillore** [comment]
hahaha ok. i will.
thanks buddy.

**Comment by JakeWharton** [comment]
This is also a Gson question, not a Retrofit one.

Short answer: Use `@SerializedName`.
