### ISSUE TITLE
JSON string as query format

### ISSUE THREAD

**Issue by csabatini** [square/retrofit#780]
I am trying to use a rest API that exposes my MySQL database with Flask-Restless. Flask-Restless documentation is [here](https://flask-restless.readthedocs.org/en/latest/searchformat.html#query-format), the query format is a JSON string:

    /api/person?q={"filters":[{"name":"id","op":"eq","val":1}]}

and there's cases I'd like to use multiple filters 

    /api/person?q={"filters":[{...},{...}]}

Is this possible with Retrofit or will only the query format ?key1=value1&key2=value2 work and I'm a fringe case? The QueryMap produces that format for me and I'm not allowed to replace inside the query with @Path

**Comment by JakeWharton** [comment]
You data is in the format "?key1=value" except you have a complex value with an arbitrary serialization mechanism that is known to the application layer. Retrofit will happily accept a JSON string as a query value. Specify either a `@QueryMap` or simply a `@Query` with `encodeValue = false` (unless you want URL-encoding) and pass the JSON-encoded string as your value.

As I already mentioned, the fact that the query value is a JSON-encoded string is an application-level detail which means you code is responsible for creating the JSON string with whatever means you choose (by hand, Gson, `org.json.*`, etc.).

**Comment by csabatini** [comment]
That makes sense - thanks!
