### ISSUE TITLE
SimpleXMLConverter.java is inconsistent

### ISSUE THREAD

**Issue by bopbi** [square/retrofit#783]
it seems the SimpleXMLConverter not consistent with the Converter interface that are on package retrofit.converter

IMO based on the commit message, i think the SimpleXMLConverter is more update compared with the interface itself

**Comment by JakeWharton** [comment]
Both `master` and the 1.9.0 releases have passing builds. Please paste that stacktrace or compilation failure you are seeing.

I'm closing for now because I don't believe it's a problem.

**Comment by bopbi** [comment]
when i try to create a custom converter, the class look like on this gist https://gist.github.com/bopbi/9f85f227234102085675

the toBody and fromBody function return value or param is different with the master SimpleXMLConverter

i am using the compile 'com.squareup.retrofit:retrofit:1.9.0'

what do you think?
