### ISSUE TITLE
Google cloud endpoints authorization

### ISSUE THREAD

**Issue by alchemistgo87** [square/retrofit#785]
Is there a way to set googleaccountcredential in the restadapter for authorization of goolge cloud endpoints api.

**Comment by JakeWharton** [comment]
I have never used Google Cloud Endpoints so no idea. Please ask questions on StackOverflow with the 'retrofit' tag. If there's a concrete feature request or bug around this then you're welcome to file, but general usage and integrations are better served (and archived) on StackOverflow.
