### ISSUE TITLE
Allow to specify filename as optional parameter to TypedByteArray

### ISSUE THREAD

**Issue by jonnor** [square/retrofit#787]
I would expect to be able to use `new TypedByteArray(type, bytes, "myfilename.foo")` to upload a file multi-part using RetroFit from an in-memory file instead of a `File` object.

Right now one needs to subclass using work-around described here: https://github.com/square/retrofit/issues/178#issuecomment-34470409

**Comment by rgrinberg** [comment]
+1. I've been bitten by this as well

**Comment by pepijntb** [comment]
+1. Also bitten.

**Comment by achuinard** [comment]
Yea, I never understood why you couldn't use a TypedByteArray in a multipart file upload. Had the API allowed it, probably would have just figured it out. I'm now using the subclass hack.

**Comment by tai2** [comment]
:+1:

**Comment by JakeWharton** [comment]
`TypedByteArray` is gone from v2. There's a whole new model of building data with content type and length information from OkHttp. For filename, this is something new and it's being tracked by #1140.
