### ISSUE TITLE
How to handle disk cache with Retrofit

### ISSUE THREAD

**Issue by Folyd** [square/retrofit#791]
Retrofit is awesome thought! But i didn't know how to cache my data with Retrofit. 
I can handle well disk cache with my data  if i use AsyncTask,but i don't know how to do it wit Retrofit.

Please help me.Thanks !

**Comment by JakeWharton** [comment]
Retrofit does no caching. It's job is to apply HTTP semantics onto interfaces and create the appropriate requests on the underlying HTTP client. Disk caching is a feature best implemented in the HTTP client. You can use [OkHttp][1] with Retrofit which has a modern, smart disk cache.

 [1]: https://square.github.io/okhttp
