### ISSUE TITLE
"Content-Type: application/json" should not specify charset

### ISSUE THREAD

**Issue by renaudcerrato** [square/retrofit#794]
Using Retrofit+JacksonConverter: when posting JSON content, `Content-Type` is illegally specifying a charset (`Content-Type: application/json; charset=UTF-8`).

Unfortunately, according to RFC, it seems that [it should not specify a charset](http://stackoverflow.com/questions/13096259/can-charset-parameter-be-used-with-application-json-content-type-in-http-1-1). 

That behavior caused my webservice to return a 0-byte body:

```
    @POST("/oauth/bridge/facebook")
    public Observable<User> login(@Body FacebookCredential info);
```

```
---> HTTP POST http://*****/oauth/bridge/facebook
Accept: application/json
Content-Type: application/json; charset=UTF-8
Content-Length: 316 {"id":"10205307586101984","token":"***"}
---> END HTTP (316-byte body)
<--- HTTP 200 http://*****/oauth/bridge/facebook (1995ms)
Server: nginx/1.6.2
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: no-cache
Date: Wed, 25 Mar 2015 17:18:57 GMT
OkHttp-Selected-Protocol: http/1.1
OkHttp-Sent-Millis: 1427303934267
OkHttp-Received-Millis: 1427303936195
<--- END HTTP (0-byte body)
```

As a workaround, I forced the `Content-Type` through `@Headers` annotations, and it worked as it should.

**Comment by JakeWharton** [comment]
According to [RFC 7159](http://tools.ietf.org/html/rfc7159):

> No "charset" parameter is defined for this registration. Adding one really has no effect on compliant recipients.

So it sounds like your server is misbehaving as well.

**Comment by nono240** [comment]
I agree.

**Comment by swankjesse** [comment]
My preference is to always explicitly specify UTF-8.

For consumers, explicitly specifying it permits some optimizations: you can avoid a potentially-awkward charset detection, or a potentially-broken charset assumption.

**Comment by JakeWharton** [comment]
No action to take here.
