### ISSUE TITLE
Retrofit website needs updating for version 1.9.0 (requiring OkHttp 2.0+)

### ISSUE THREAD

**Issue by pjdelport** [square/retrofit#795]
According to the changelog, Retrofit 1.9.0 requires OkHttp 2.0+, and no longer needs the `okhttp-urlconnection` shim.

However, the [website](http://square.github.io/retrofit/) still talks about using OkHttp 1.6.0 or newer, and including the `okhttp-urlconnection` shim.

**Comment by JakeWharton** [comment]
Thanks.

79a2a501b5964bd831bd3c4b9554d35fb2e584c2
