### ISSUE TITLE
@FormUrlEncoded not supported ?

### ISSUE THREAD

**Issue by jimxj** [square/retrofit#806]
I have a method in a service
```
  @FormUrlEncoded
  @POST("/formParamTest")
  void formParamTest(
          @Field("input") Double input,
          retrofit.Callback<Double> callback
  );
```
Got following exception when calling the method 
```
java.lang.UnsupportedOperationException: Form URL encoding shall return!
at retrofit.MethodInfo.parseMethodAnnotations(MethodInfo.java:147)
at retrofit.MethodInfo.<init>(MethodInfo.java:96)
```
Checked the code, it seems it always throws a exception when FormUrlEncoded is enabled.
```
else if (annotationType == FormUrlEncoded.class) {
        if (requestType != RequestType.SIMPLE) {
          throw methodError("Only one encoding annotation is allowed.");
        }
        throw new UnsupportedOperationException("Form URL encoding shall return!");
        //requestType = RequestType.FORM_URL_ENCODED;
      } 
```

**Comment by JakeWharton** [comment]
Don't use the latest snapshot unless you are prepared to deal with a lot of breaking changes and spurious failures. A lot of churn is happening.

The exception and its message are intentional for now.

**Comment by jimxj** [comment]
Are you working on bringing form parameter back ? I can fix it send a PR.

**Comment by JakeWharton** [comment]
The fix is non-trivial which is why it's currently disabled altogether. It
will come back before release.

**Comment by jimxj** [comment]
OK. Then I just keep my temporary in my own branch.

Thanks!
