### ISSUE TITLE
Feature request: Add null check for parameters

### ISSUE THREAD

**Issue by jimxj** [square/retrofit#808]
It's nice to have some validation for parameter in client to save the round trip to server and get a error back. 

The most basic validation could be null check. A annotation like @NotNull could be added to the parameter to enforce the validation.

Later, validations like string length, number range or even regex could be considered.

**Comment by JakeWharton** [comment]
Validation is an application-level concern. Retrofit's job is simply mapping a declarative way of specifying requests and responses to an underlying HTTP client. The scope of this validation knows no bounds (as you alluded to with other validations) which is a very scary thing from a project maintainers perspective.

We can leave this open for others to comment on, but I don't foresee effort being done on this any time soon.

**Comment by JakeWharton** [comment]
#816
