### ISSUE TITLE
Adding Observable support to legacy async style methods

### ISSUE THREAD

**Issue by z0lope0z** [square/retrofit#809]
Hi! There's a library that uses retrofit's async-style method
```
@GET("/user/{id}/photo")
void getUserPhoto(@Path("id") int id, Callback<Photo> cb);
```
I'd like to be able to add Observable support along side this method but this will produce compilation conflicts (same method name, params)
```
@GET("/user/{id}/photo")
void getUserPhoto(@Path("id") int id, Callback<Photo> cb);
@GET("/user/{id}/photo")
Observable<Photo> getUserPhoto(@Path("id") int id);
```
:boom: compile error!

What would be the best way to go about this? change the method name to "getUserPhotoObs"?
```
@GET("/user/{id}/photo")
Observable<Photo> getUserPhotoObs(@Path("id") int id);
```

**Comment by mattprecious** [comment]
One of those methods takes a `Callback` and one does not. That should compile just fine.

**Comment by JakeWharton** [comment]
The parameters are different, this will compile.

**Comment by z0lope0z** [comment]
Oops! I think what I meant was for synchronous methods wherein the difference between the two methods is the return type:
```
@GET("/user/{id}/photo")
Photo getUserPhoto(@Path("id") int id);
@GET("/user/{id}/photo")
Observable<Photo> getUserPhoto(@Path("id") int id);
```
I guess there are times wherein I want to be able to make a blocking call instead of using an observable. Although toBlocking() exists, I read somewhere that I shouldn't be using it for production code. But then again, why would I want a blocking call in production? Implementation aside, it'd be great if I could have both options (especially for legacy code wherein i can't delete blocking method to have observable method) and I was wondering about the best way to have them both or is making the method name different the only real choice I have?

**Comment by JakeWharton** [comment]
You can rename the method, but there's nothing wrong with calling `toBlocking().first()` if you actually want blocking behavior. That's the whole reason why it exists. `Observable` pushes the choice of threading models on the caller rather than into the library.

**Comment by z0lope0z** [comment]
Okay copy! But i swear i read somewhere that it was only meant for debugging/testing. Thanks! :D
