### ISSUE TITLE
Argument pre-processor, deserialized post-processor.

### ISSUE THREAD

**Issue by JakeWharton** [square/retrofit#816]
Consumers of the library want things that we cannot provide or simply will never provide. Examples are: validation of `@Nullable` or other arbitrary annotations for parameters, supporting non-body conversion of third-party library types (e.g., `Multimap`) or with custom rules (e.g., `@SerializedName` on enum constants), and custom handling of response data.

Supporting this isn't certain, and unlike to be in 2.0, but it would be a re-usable extension point which potentially would solve a lot of future cases. Perhaps this could obviate the half-assed `RequestInterceptor` that we have now.

**Comment by baoti** [comment]
LGTM
