### ISSUE TITLE
MultipartConverter

### ISSUE THREAD

**Issue by johnjohndoe** [square/retrofit#819]
Please have a look at this [Stackoverflow question](http://stackoverflow.com/questions/29680158/how-to-send-multipart-form-data-with-retrofit) and [this Gist](https://gist.github.com/plastiv/08538a095d2d35acab05) linked in the comments. You might be interested in adding a generic `MultipartConverter` to the repository ...

**Comment by JakeWharton** [comment]
I don't think this is of enough quality to warrant inclusion directly. You can already used `MultipartTypedOutput` as a `@Body` param to create multipart in a similar fashion.

My problems with the gist are that it's asymmetric: serialization in multipart only goes one direction. Plus it puts multipart as an odd special case whereas something like form encoding is not.

The serialization mechanisms we currently have are fleshed out full projects that each individually deal with the semantics and implications of their respective format. I do not want to take on the burden of figuring out all the details and nuances of something like this as part of Retrofit. Now, if there was a third-party library that dealt with all these things in relation to Retrofit then that might be interesting to provide a first-party converter for. Without that, however, I don't think this makes sense.

Also I think demand for something like this is really, really low that the cost of adding it would be far too high for the return.
