### ISSUE TITLE
Call Observable RestService use the same subscriber many times

### ISSUE THREAD

**Issue by sxyzgit** [square/retrofit#822]
Hello,
When I call Observable RestService use the same subscriber many times, it exec only the first time.
Like this:
```
interface RestService {
    @GET("/path/to/get")
    Observable<Result> getResultRx(@Query("id") int id);
}
Subscriber mSubscriber;
void test() {
    RestAdapter.create(RestService.class).getResultRx(id).subscribe(mSubscriber);
}
```
But
```
void test() {
    RestAdapter.create(RestService.class).getResultRx(id).subscribe(new Subscriber(){...});
}
```
Not

I read the source at `retrofit.RxSupport` found it call `subscriber.onCompleted()` after `subscriber.onNext(wrapper.responseBody)` immediately in `getRunnable(...)` method.

So it cause the problem above, is there any other methods can resolve this?
Thanks!

**Comment by JakeWharton** [comment]
Can you write a complete test case so that I can reproduce this? I don't quite understand the behavior that you say you are seeing. I believe that if there is a problem here that it might be an RxJava bug.
