### ISSUE TITLE
TypedByteArray and ProgressBar

### ISSUE THREAD

**Issue by DoctorB** [square/retrofit#823]
Hi there, any chance to link a progress bar using only the TypedByteArray class that working directly with the BufferedSink and not with the body OutputStream?
Do I have to implement my own Client, is it the only way?

Thanks in advance

**Comment by JakeWharton** [comment]
Yes, or an [OkHttp interceptor][1]. Retrofit v2 will remove the `Typed*` abstractions in favor of just using OkHttp's `RequestBody` and `BufferedSink` directly so that will make things even easier.

[1]: https://github.com/square/okhttp/wiki/Interceptors
