### ISSUE TITLE
Does Retrofit work with Java 6 with okhttp integration?

### ISSUE THREAD

**Issue by xhh** [square/retrofit#826]
The [home page](https://square.github.io/retrofit/) says "Retrofit requires at minimum Java 6 or Android 2.3", and "Retrofit will automatically use OkHttp (version 2.0 or newer) when it is present", but [okhttp requires Java 7](https://github.com/square/okhttp/issues/528#issuecomment-96622594). So will Retrofit really support Java 6?

**Comment by JakeWharton** [comment]
Yes. Older versions of OkHttp, `java.net.HttpURLConnection`, and Apache HTTP client will work just fine.

**Comment by simonlinj** [comment]
I need a version of retrofit to support Java 6, which version of Retrofit should I use??  The current latest retrofit requires at minimum java 7. which was the latest version to support Java 6?

Currently its compiling with the latest version,  but havent tested in run time yet...  any ideas?? Thanks!

**Comment by sinatragunda** [comment]
Anyone found a solution to this ?
