### ISSUE TITLE
please help  504 Gateway Time-out thanks!

### ISSUE THREAD

**Issue by Weststreet** [square/retrofit#829]
HTTP 504 https://api.weibo.com/2/friendships/followers.json?trim_status=0&access_token=2.00aT7apB06XASO4947c90a16gKTyfC&uid=1233135754&cursor=300 (6039ms)
Server: nginx/1.6.1
 Date: Fri, 01 May 2015 12:29:25 GMT
 Content-Type: text/html;charset=ISO-8859-1
Transfer-Encoding: chunked
 Connection: keep-alive
 Set-Cookie: JSESSIONID=E3DFA94523EF03A059F5FCF7036BE76D; Path=/; HttpOnly
 Vary: Accept-Encoding
 OkHttp-Selected-Protocol: http/1.1
 OkHttp-Sent-Millis: 1430483359055
 OkHttp-Received-Millis: 1430483365095
 Sorry, that page doesnât exist!
 <--- END HTTP (34-byte body)
 status=504
 504 Gateway Time-out

**Comment by JakeWharton** [comment]
This is a non-200 HTTP response from the remote server (or a proxy between you and the remote server), not a Retrofit bug. Your application needs to handle the case where the remote resource you fetch is not available.

**Comment by lilised** [comment]
but it works by httpurl connection only retrofit respone 504 gateway time out
