### ISSUE TITLE
When using Rx Observables .subscribeOn() does not control the thread that the rest call runs on. 

### ISSUE THREAD

**Issue by kungfurorykelly** [square/retrofit#830]
When using Rx Observables .subscribeOn does not control the thread that the rest call runs on. 
If I want to control the thread rx operators run on. I can't because calls use the Retrofit provided thread pool. 

i.e
```
    IRestCall{
        @GET("/stores")
   	Observable<List<Store>> getStores();
   }

   getRestClient()
   . getStores()
   .map(stores -> {
       // runs on retrofit thread not the thread specified below
   }).subscribeOn(Schedulers.newThread());
```

I think this is because of line 234 in RestAdapter.java

```
call.enqueue(new com.squareup.okhttp.Callback() {
```

should be 

```
call.execute()
```

**Comment by JakeWharton** [comment]
We delegate threading to OkHttp in an effort to more efficiently make requests and read responses. This is especially true when using HTTP/2 or SPDY3 as transports. The synchronous version requires wasting a thread both in OkHttp and Retrofit as well as reducing overall throughput.

`subscribeOn` merely dictates the thread on which the request is prepared and enqueued. `observeOn` dictates on which thread the responses are observed. On which thread the actual HTTP request is executed is an implementation detail of OkHttp's `Dispatcher`.
