### ISSUE TITLE
Root node name in post request

### ISSUE THREAD

**Issue by jonathanrz** [square/retrofit#832]
Hi,

Rails expects that the params in a post request inits with a root node with the name of the model. Ex: "user" => { "name" => "John Doe" }

If I annotate the post request param with a @Body, Retrofit sends the serialized model in the root of the request. To overcome this, I need to define the param as an Map where the key is the model name and the value is the model itself, in that way retrofit sends the params as expected by rails.

Would be awesome if I could specify in the param their root node name, something like @Body @Root("user")

**Comment by JakeWharton** [comment]
Retrofit is neither JSON-specific nor would we cater to a single server technology in our API. Also having worked with Rails backends, I'm not sure that this is a requirement of all users so much as something that's specific to your backend (i.e., we never had this problem).

The way that I would do this is with your own `@Root` annotation that you can put on your model objects. Then create a `TypeAdapterFactory` which looks for the annotation and adds the envelope. Here's a quick version:
```java
@Retention(RUNTIME)
@Target(TYPE)
@interface Root {
  String value();
}
```
```java
class RootedTypeAdapterFactory implements TypeAdapterFactory {
  @Override public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
    Root root = type.getRawType().getAnnotation(Root.class);
    if (root == null) {
      return null;
    }
    final String rootValue = root.value();
    final TypeAdapter<T> delegate = gson.getDelegateAdapter(this, type);
    return new TypeAdapter<T>() {
      @Override public void write(JsonWriter out, T value) throws IOException {
        out.beginObject();
        out.name(rootValue);
        delegate.write(out, value);
        out.endObject();
      }

      @Override public T read(JsonReader in) throws IOException {
        return delegate.read(in); // Note: not unwrapping the envelope!
      }
    };
  }
}
```
```java
@Root("user")
class User {
  public final String name;

  User(String name) {
    this.name = name;
  }
}
```
Then just register that type adapter factory with a `Gson` instance and pass it to a `GsonConverter` which you finally pass to a `RestAdapter.Builder`!

Here's an example of it working:
```java
Gson gson = new GsonBuilder()
    .registerTypeAdapterFactory(new RootedTypeAdapterFactory())
    .create();

User user = new User("John Doe");
System.out.println(gson.toJson(user));
```
```
{"user":{"name":"John Doe"}}
```

**Comment by jonathanrz** [comment]
@JakeWharton thanks for your reply and the example code, solved my issue.
