### ISSUE TITLE
Optional RxJava support in wrapper using Retrofit

### ISSUE THREAD

**Issue by athornz** [square/retrofit#834]
While this is not a direct issue with Retrofit (I think), I would love some help.

I've implemented a wrapper using retrofit, which I will publish for use in other apps. I'd my wrapper to have optional RxJava support, like Retrofit does. 

But it seems that by declaring methods in the api that return Observables, I am making RxJava support compulsory for any app that uses my wrapper (Whenever a Retrofit service is called, I get a class not found exception).

Is there a way around this?

**Comment by JakeWharton** [comment]
I would just follow the same pattern as Retrofit does:

 * Use a `Class.forName` lookup to determine if the library is present: https://github.com/square/retrofit/blob/3eab762a81abb4a4650aa8423a58e095f1da441a/retrofit/src/main/java/retrofit/Platform.java#L77-L84
 * Put everything deal with RxJava in a separate class: https://github.com/square/retrofit/blob/3eab762a81abb4a4650aa8423a58e095f1da441a/retrofit/src/main/java/retrofit/RxSupport.java
 * Only load that class when support is available: https://github.com/square/retrofit/blob/3eab762a81abb4a4650aa8423a58e095f1da441a/retrofit/src/main/java/retrofit/RestAdapter.java#L224-L226

Closing the issue but feel free to ask more questions about it if you have any.

**Comment by athornz** [comment]
Awesome thanks for the reply. I had tried something similar but I think the issue was I didnt create a separate class for the rx version of the api. I'll give it another go.
