### ISSUE TITLE
Best way to create custom onError events depending on api response?

### ISSUE THREAD

**Issue by GNima** [square/retrofit#836]
I'm working with an API that has the following json response format:

```
{
"code":0,
"message":"OK",
"data":{....}}
```
Using Rx, I would like to raise custom exceptions resulting in `onError` for subscribers depending on the code value. We have things like if code = 200 it means user not found, so I want to throw a new UserNotFoundException for example.

What's the best approach to achieve this?

**Comment by JakeWharton** [comment]
This is a usage question not a bug or feature and thus belongs on StackOverflow with the 'retrofit' tag. And you've already posted it: http://stackoverflow.com/questions/30154133/rxjava-and-retrofit-raising-custom-exceptions-depending-on-server-response
