### ISSUE TITLE
Send post request with params

### ISSUE THREAD

**Issue by fiftycy** [square/retrofit#840]
am trying unsuccessfully to consume an API on Android  but while using POSTMAN i can see the expected results.

[POSTMAN SETTING]

* The api url (base+controller)

* HTTP Method set to POST

* Clicked the from-data or x-www-form-urlencoded

* Then i pass the two params on the key/value fields.

[ANDROID SETTING]
``` Android
@POST("/GetDetailWithMonth&Code")
void getLandingPageReport(@Query("code") String code,
                          @Query("monthact") String monthact,
                          Callback<LandingPageReport> cb);

@FormUrlEncoded
@POST("/GetDetailWithMonth&Code")
void getLandingPageReport(@Field("code") String code,
                          @Field("monthact") String monthact,
                          Callback<LandingPageReport> cb);
```
None of this options works. But am getting {} as result.

**Comment by adi1133** [comment]
Please post on stackoverflow, this is not an issue with retrofit.

**Comment by JakeWharton** [comment]
Indeed. Usage questions should go on StackOverflow with the 'retrofit' tag. Feel free to link the question here, but there's much more visibility over there.

**Comment by fiftycy** [comment]
Well, sr if i shouldn't write it here. I considered that something is going wrong because it should work like I write it in the second method. I've added to my question the StackOverflow link.
