### ISSUE TITLE
encrypt params

### ISSUE THREAD

**Issue by Azzssss** [square/retrofit#841]
I want to use retrofit in my project，but my project need handle the parameters. It change parameters to json, them encrypt the json as a parameter, like  this : requestParams.put("params",Security.encrypt(json)). How can I handle this in a elegant way?

**Comment by Azzssss** [comment]
Or should I revise the source code so I can handle it in an elegant way?

**Comment by jdreesen** [comment]
You should ask this on stackoverflow as it is not a retrofit issue ;)

**Comment by JakeWharton** [comment]
Agree. StackOverflow + 'gson' tag. This is a Gson question, you just happen to be using Retrofit which calls Gson for you.
