### ISSUE TITLE
Retrofit and google-http-java-client

### ISSUE THREAD

**Issue by juliocotta** [square/retrofit#842]
Is there any known implementation of a Client using google-http-java-client?

**Comment by JakeWharton** [comment]
Not that I know of, no. I can't imagine it would be too hard to write one if the client is reasonable in its API. Does Google force you to use that client for something?

**Comment by juliocotta** [comment]
Ohh, Ok. I don't have any specific need to use that client, I just thought it would be nice to see how it would work.

**Comment by JakeWharton** [comment]
There's no plans to support this as a first party HTTP client out of the box so I'm going to close.
