### ISSUE TITLE
Handling Collection of Polymorphic objects

### ISSUE THREAD

**Issue by alchemistgo87** [square/retrofit#843]
If I have to retrieve a list of say Animal objects and I have inherited classes of Animal (say Cat, Dog etc). How would I retrieve such a list of animals in Callback maintaining all the data of polymorphic objects?

**Comment by jdreesen** [comment]
This is not a retrofit issue, so this is the wrong place to ask, stackoverflow would be better. 
Also, it depends on the data converter you use, e.g. Gson for JSON data.

**Comment by alchemistgo87** [comment]
Thanks for the Reply. But need to ask one thing:
Cant' the Callback provided by Retrofit have some functionality where we can describe which polymorphic objects are expected?

**Comment by alchemistgo87** [comment]
I am using the default Retrofit converter.

**Comment by jdreesen** [comment]
> Cant' the Callback provided by Retrofit have some functionality where we can describe which polymorphic objects are expected?

As Retrofit itself has nothing to do with the serialization/deserialization of your data and it largely depends on your data structure, I don't think this would be possible or even desired.

> I am using the default Retrofit converter.

As the default converter is Gson, maybe you should have a look at its [documentation](https://sites.google.com/site/gson/gson-user-guide). I think you would have to implement your own serializer/type adapter for this.

**Comment by alchemistgo87** [comment]
All right then, I will implement custom serializer. Thanks for the help jdreesen.
