### ISSUE TITLE
Unclear how RetroFit keeps reference to Callbacks used for async calls

### ISSUE THREAD

**Issue by snowpong** [square/retrofit#846]
I can't find documentation anywhere specifying how RetroFit keeps it's reference to Callbacks given for async calls.

Is it a proper reference or a weak reference of some sort?

I want to know if it's safe to pass a new Callback<SomeClass>() {....} where RetroFit is the only one keeping a reference to the instance.

**Comment by JakeWharton** [comment]
It is a strong reference. We are only in the habit of documenting when it's weak. What you describe should be safe!

**Comment by snowpong** [comment]
Excellent. Thanks.
