### ISSUE TITLE
retrofit.RetrofitError: 413 FULL head

### ISSUE THREAD

**Issue by zhongbaitu** [square/retrofit#847]
I turn a bitmap to base64 and post it to server.

And I catch an error : 
retrofit.RetrofitError: 413 FULL head

How can i fix it ? it is a bug? or ?

thanks for help.

and my code 
***
		@Headers("param-type:key-value")
	    @POST("/image/uploadIcon")
		UploadIconResponse uploadIcon(@Query("userId") long userId, @Query("token") String token, @Query("image") String image);
***

**Comment by JakeWharton** [comment]
This is your server returning an HTTP error. You need to handle this case.

According to [the HTTP RFC][1]

> ### 413 Request Entity Too Large
>
>The server is refusing to process a request because the request entity is larger than the server is willing or able to process. The server MAY close the connection to prevent the client from continuing the request.
>
> If the condition is temporary, the server SHOULD include a Retry- After header field to indicate that it is temporary and after what time the client MAY try again.

 [1]: http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html
