### ISSUE TITLE
Log headers added directly into OkHttp

### ISSUE THREAD

**Issue by juliocotta** [square/retrofit#860]
Hi, I would like to know if retrofit would be able to log (using LogLevel) the custom headers added into OkHttpClient.interceptors.add(new Interceptor() {//...add header}) .
I used to use the retrofit RestAdapter.Builder.setRequestInterceptor method to add headers and they were in the log output.
Thanks.

**Comment by JakeWharton** [comment]
It cannot. Those headers are added after Retrofit calls the HTTP client and it has no way of knowing what they are. If you want those to be logged, use another OkHttp interceptor added after the one which adds the headers to do your own logging.
