### ISSUE TITLE
Posting array as multipart in retrofit

### ISSUE THREAD

**Issue by absaruddin** [square/retrofit#864]
{ 
            "checksum"      : "747d23f4333f05c60d57f83ab3648e2e",
            "userId"        : 1,
            "reqType"       : "Medical Devices",
            "reqFormType"   : "General Request",
            "requestFields"  : [
                                    {
                                        "fieldName" : "xxx",
                                        "fieldValue" : "s3343"
                                    }
                                ],
            "timestamp" : 1403477427
        }

I need to send this as multipart request basically my problem is in sending requestFields[] as multipart as i cant send this to the server as multipart.

Any help will be appreciated as i am stuck in it.
Thanks in advance

**Comment by JakeWharton** [comment]
Usage questions are much better served on StackOverflow. Many more people will see it and the search and archiving of questions is superior to GitHub. Please ask there and feel free to link to the question here when you do.
