### ISSUE TITLE
Add headers based on the request ?

### ISSUE THREAD

**Issue by adnan-SM** [square/retrofit#865]
So I see that there is a global interceptor which I can use to add headers to every request, but is there some way I can decide whether or not add headers to a particular request based on a parameter I pass in ?  

Ex :  I have 10 API calls out of which only 8 need a AccessToken Header, currently I can either set the header globally to all the 10 API requests or manually add headers before each API request. What I am looking at is if we could somehow pass a parameter(probably boolean) with each request which decides whether or not to add headers. So in the interface I create I setup something like -

```java
@GET("/api/getDummyContent")
public void getContent(Callback<String> callback, boolean shouldAddHeader); 
```

Now if we could somehow get access to shouldAddHeader variable in the global interceptor like - 

```java
if(shouldAddHeader) { 
      requestFacade.addHeader("HeaderName", "HeaderValue");
}
 ```

Any way I can do this already ?

**Comment by steffandroid** [comment]
Cleanest way I can think of to do this is to define two separate services, one for the eight requests which need headers and one for the remaining two. Add the interceptor to the former.

**Comment by zhakid** [comment]
@steffandroid +1

**Comment by adnan-SM** [comment]
@steffandroid That's what i thought of as well but just wanted to confirm if there is anything better before taking that route. Thanks for the clarification.

@zhakid  That's interesting, I could give that a try I guess.

Thanks
