### ISSUE TITLE
way to add comman feild to the param without having to add it in every call 

### ISSUE THREAD

**Issue by amansatija** [square/retrofit#866]
I pass an api key in every  call which i wish to hide in the apiclient is there a way i can harcode a param while defining the api call in the api client  or is there a way by which i can pass comman set of params which get added by default to every call  i make , ??

**Comment by jimxj** [comment]
I think you can add a request Interceptor to to that in okhttp client.

**Comment by JakeWharton** [comment]
You can set a [`RequestInterceptor`][1] on the `RestAdapter.Builder` which is called for every request or you can use an [OkHttp interceptor][2].

 [1]: http://square.github.io/retrofit/javadoc/retrofit/RequestInterceptor.html
 [2]: https://github.com/square/okhttp/wiki/Interceptors
