### ISSUE TITLE
Singleton approach for initializing RestAdapter and Api interfaces

### ISSUE THREAD

**Issue by laaptu** [square/retrofit#867]
This is not a bug or issue, but simply an implementation validation. So far looking at various `github` project implementing `Retrofit`, they are focusing on `singleton` approach. Using all those resources, I have made a simple [gist](https://gist.github.com/laaptu/feb3cae85f07c0c5fe3e). Is this a valid way for singleton approach for initializing `RestAdapter` and api interfaces.

Using `Retrofit 1.9.0`

Thanks in advance.

**Comment by JakeWharton** [comment]
Yes it should be a singleton (or at least lived in a managed lifetime). Doing so allows re-use of connections, threads, annotation parsing, and more. And yes, your approach works fine as an implementation of the singleton pattern.

**Comment by laaptu** [comment]
@JakeWharton :+1:  Thanks.
