### ISSUE TITLE
Documentation outdated for Xml example

### ISSUE THREAD

**Issue by praveendath92** [square/retrofit#869]
Documentation still points to xml example using ```SimpleXMLConverter``` which is not available in the current releases. It should be ```SimpleXmlConverter```

Gradle dependency:
```compile 'com.mobprofs:retrofit-simplexmlconverter:1.1'```

**Comment by PavelSynek** [comment]
`SimpleXMLConverter` from `com.squareup.retrofit:converter-simplexml:1.9.0` works for me.

**Comment by praveendath92** [comment]
My bad. I didn't add the dependency. Presumed it ships with retrofit.

It would be nice to see this in the tutorial.

**Comment by JakeWharton** [comment]
What tutorial?

**Comment by praveendath92** [comment]
```CONTENT FORMAT AGNOSTIC``` section of [this][1] and [simplexml Readme][2]

Just saying, from a retro beginner perspective.

[1]: http://square.github.io/retrofit/
[2]: https://github.com/square/retrofit/tree/master/retrofit-converters/simplexml

**Comment by praveendath92** [comment]
I can send a pull request by mentioning ```com.squareup.retrofit:converter-simplexml:1.9.0``` at those places.

**Comment by JakeWharton** [comment]
This section has now been removed from the website. Much more detailed converter documentation is coming as part of the efforts towards v2.0.
