### ISSUE TITLE
401 unauthorize

### ISSUE THREAD

**Issue by dhrumit123** [square/retrofit#894]
When the server returns with the 401 status, the RetrofitError response object is null, and the networkError flag is set to true, making it impossible for the app to check error.getResponse().getStatus().
I Have also try adding WWW-authenticate flag server side . But still its not working. 
I need to logout when server throws 401 unauthorize error . How to make this work?

**Comment by JakeWharton** [comment]
I do not see this behavior.
```java
public final class Main {
  public static void main(String... args) throws IOException {
    MockWebServer server = new MockWebServer();
    server.start();
    server.enqueue(new MockResponse().setResponseCode(401).setBody("Nope"));

    RestAdapter ra = new RestAdapter.Builder()
        .setEndpoint(server.getUrl("/").toString())
        .setLogLevel(RestAdapter.LogLevel.FULL)
        .build();
    Service service = ra.create(Service.class);

    try {
      service.strings();
    } catch (RetrofitError e) {
      System.out.println("Network error: " + e.isNetworkError());
      System.out.println("Error kind: " + e.getKind());
      System.out.println("Response: " + e.getResponse());
      System.out.println("Code: " + e.getResponse().getStatus());
      System.out.println("Body: " + e.getBodyAs(String.class));
    }

    server.shutdown();
  }

  interface Service {
    @GET("/") List<String> strings();
  }
}
```
```
---> HTTP GET http://localhost:64434/
---> END HTTP (no body)
<--- HTTP 401 http://localhost:64434/ (255ms)
Content-Length: 4
OkHttp-Selected-Protocol: http/1.1
OkHttp-Sent-Millis: 1433948430424
OkHttp-Received-Millis: 1433948430430

Nope
<--- END HTTP (4-byte body)
Network error: false
Error kind: HTTP
Response: retrofit.client.Response@5f2050f6
Code: 401
Body: Nope
```
Please provide a test case similar to above.

**Comment by LordRaydenMK** [comment]
I had a similar problem. In my case the problem turned out to be a custom error handler.

	public class MyErrorHandler implements ErrorHandler {
		@Override
		public Throwable handleError(RetrofitError cause) {
			Response response = cause.getResponse();
			if(response != null) {
				if (response.getStatus() == 401) {
					return new UnauthorizedException(cause);
				} else if(response.getStatus() == 404) {
					return new NotFoundException(cause);
				}
			}
			return cause;
		}
	}

Bug or feature?
