### ISSUE TITLE
 Service methods cannot return void.

### ISSUE THREAD

**Issue by banxi1988** [square/retrofit#895]
error message is:
> Caused by: java.lang.IllegalArgumentException: V2exService.listTopicByScope: Service methods cannot return void.

and my code is

```Java
public interface V2exService {
    @GET("/topics/{scope}.json")
    void listTopicByScope(@Path("scope") String scope, Callback<List<Topic>> cb);
}
```

it's works well in previous snapshot version.
and I think I was using the async form,Type info can be inferred from Callback instance.

**Comment by JakeWharton** [comment]
The API is changing dramatically. Do not rely on a snapshot if you cannot tolerate constant breakage.
