### ISSUE TITLE
Retrofit drops context path from endpoint url

### ISSUE THREAD

**Issue by unguiculus** [square/retrofit#907]
I'm currently checking out Retrofit with the new Moshi converter. 

Retrofit 2.0.0-SNAPSHOT
OkHttp 2.4.0
Okio 1.4.0
Moshi 0.9.0

Say, I have the following service:

```Java
public interface MyService {
  @POST("/")
  Call<MyResult> post(@Body MyRequest request);
}
```

The request is executed as follows:

```Java
Retrofit retrofit = new Retrofit.Builder()
    .endpoint("http://localhost:8778/mycontext/")
    .converter(new MoshiConverter())
    .build();

Call<MyResult> call = retrofit.create(MyService.class).post(new MyRequest());
Response<MyResult> response = call.execute();
```

The result is a `404` because the context (`/mycontext`) is dropped from the URL and the post goes to `http://localhost:8778/`. This happens in https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit/RequestBuilder.java#L333 when [encodedPath(String)](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java#L731) is called. Shouldn't [addEncodedPathSegment(String)](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java#L691) be called instead?

**Comment by swankjesse** [comment]
Maybe we should trim/forbid the leading slash on the relative path? If we treat the whole thing as a relative URL there are interesting consequences. For example, this works:
```
  @POST("https://host/path/{parameter}")
```
And this:
```
  @POST("../path/{parameter}")
```
Though looking at it, I think I'm convincing myself that what we have in retrofit 1.x is simpler. Maybe just require a trailing shash in the endpoint and forbid it in the annotation?

**Comment by gustavohenke** [comment]
So, this issue has been fixed in #927.
But how is the fix supposed to work? I'm new to Android/Retrofit world.

- Base URL is `http://server.com/api`
- API interface has `@GET("/user")`
- Result: the request goes to `http://server.com/user`.

I'm considering using an interceptor to rewrite the URL (if that's even possible...).

I'm using Retrofit `2.0.0-beta1`.

**Comment by JakeWharton** [comment]
Add trailing slash to base URL, remove leading slash from relative URL.

**Comment by gustavohenke** [comment]
OK, thank you! I was using a Builder to create that URL, so I added an empty path segment.
