### ISSUE TITLE
method PATCH must have a reqest body.

### ISSUE THREAD

**Issue by kimtaegyeong** [square/retrofit#910]
@PATCH("/users/{user_id}/")
     void patchUserName(
         @Body UserNameChangeRequest body,
         @Path("user_id") String user_id,
         Callback<Object> callback
     );

RetrofitError.getCause() = java.lang.IllegalArgumentException: method PATCH must have a request body

I write "@Body", so why this error has occurred?

**Comment by felipecsl** [comment]
That can happen if your body is `null`. 
This is a change on [OkHttp 2.4.0-RC1](https://github.com/square/okhttp/blob/master/CHANGELOG.md):

```
Request.Builder no longer accepts null if a request body is required. Passing null will now fail for request methods that require a body. Instead use an empty body such as this one:

    RequestBody.create(null, new byte[0]);
```

**Comment by kimtaegyeong** [comment]
i solve this problem.
    
    okhttp:2.4.0
    retrofit:1.9.0

add GsonConverter 

    RestAdapter restAdapter = new RestAdapter.Builder()
                    .setEndpoint(url)
                    .setClient(new OkClient(new OkHttpClient()))
                    .setConverter(new GsonConverter(new Gson()))

Thanks you :)

**Comment by JakeWharton** [comment]
This was already fixed on `master` by https://github.com/square/retrofit/pull/875.

For now, just add `@Body String body` and pass an empty string `""`.
