### ISSUE TITLE
Add support to define Scheduler used for RxJava (to support AppEngine)

### ISSUE THREAD

**Issue by ZakTaccardi** [square/retrofit#916]
Threads in AppEngine have to be created in a specific way, or a security exception occurs. These two posts detail how to use RxJava in Google App Engine - achieved by overriding Schedulers.io()/computation()/newThread(). 

https://github.com/ReactiveX/RxJava/issues/2918
http://stackoverflow.com/questions/23701504/google-appengine-and-rx-java

However, for v1.90 [Platform.Base.defaultHttpExecutor()](https://github.com/square/retrofit/blob/parent-1.9.0/retrofit/src/main/java/retrofit/Platform.java) does not use the `Schedulers.newThread()` interface, but manually creates a new thread. This causes a security exception in AppEngine.

Is there any way to tell Retrofit to use a specific `Rx.Scheduler`, either in the latest stable version or the in-development one?

Thanks!

**Comment by JakeWharton** [comment]
You can specify a custom background executor by calling `setExecutors` on the `RestAdapter.Builder` and using an executor that works on AppEngine as the first argument. You can pass `null` as the second argument to have callbacks run synchronously (or pass something else if you want callbacks on a different executor). The observable implementation uses whatever background executor has been configured.

For v2 we're moving away from handling the threading of HTTP requests and pushing them into OkHttp. This allows things like SPDY and HTTP/2 (as well as future enhancements) to be done more efficiently. I'm not sure the implications this will have on AppEngine, but it likely will mean that Retrofit won't there. I'll look into it in the future, but the above should fix the problem
