### ISSUE TITLE
Supporting mock network calls

### ISSUE THREAD

**Issue by dsdebastiani** [square/retrofit#917]
I have been searching a solution to mock some network methods calls in my ServiceInterface. I found this lib: https://github.com/orhanobut/wasp#user-content-mocking, which uses Volley. But it do not support upload files methods, so it is not useful for me.

Could Retrofit support same feature? Using annotations to identify the methods that returns a static response.

**Comment by JakeWharton** [comment]
Retrofit service definitions are interfaces. You can just implement the interface on a class to create a mock version. By using the `MockRestAdapter` from the 'retrofit-mock` module you can create artificial delay around that interface which simulates a network call.

Here's a sample which does both of those things: https://github.com/square/retrofit/blob/parent-1.9.0/retrofit-samples/mock-github-client/src/main/java/com/example/retrofit/GitHubClient.java.
