### ISSUE TITLE
Generic use

### ISSUE THREAD

**Issue by GurpreetSinghGnim** [square/retrofit#919]
Hi,

If want to hit more that one service at a time and check accordingly which is called on basis on UniqueId. How can we implement such functionality. Please help me out.

Regards
Gurpreet.

**Comment by JakeWharton** [comment]
GitHub issues are not a support forum for usage–only bugs and feature requests. Please try StackOverflow for usage questions with the 'retrofit' tag. Not only will more people see it, but it's a better place for search and archival of questions.
