### ISSUE TITLE
Why MainThreadExecutor as default on android?

### ISSUE THREAD

**Issue by black-snow** [square/retrofit#922]
Why is `MainThreadExecutor` the `defaultCallbackExecutor` on android? Isn't the android developer's foremost duty to get things off the UI-thread?

Since `Platform` and `RestAdapter.IDLE_THREAD_NAME` aren't available outside the retrofit package I had to do some dirty hacks to use `RestAdapter.Builder.setExecutors()`. I wanted to keep the default httpExecutor but get the callbacks off the main thread.

**Comment by JakeWharton** [comment]
The assumption is that you take the HTTP response and update the UI with its data–something that can only be done on the UI thread. If you use the RxJava Observable mechanism you can observe responses on any thread. All this stuff is changing in Retrofit 2, and it can't be changed in v1 without breaking a ton of apps.

**Comment by black-snow** [comment]
Thanks for the intel. Is there a release schedule for 2.0?
