### ISSUE TITLE
Not possible to ganerate header value based on request type and URL

### ISSUE THREAD

**Issue by outlying** [square/retrofit#923]
Problem is I need to generate header value based on request url, value is created like that:

    String hashSource = post.getMethod() + "|" + post.getURI() + "|" + publicKey + "|" + timestamp;

I started with RequestInterceptor but it's not designed to use/read request data, only add some extra.

Is there a way to do this and if not, would it be convenient to add this to Retrofit ?

**Comment by outlying** [comment]
I figured out that Client would be a best place to add this kind of logic, feels like overshot but you may easily create decorator class for that matter.

**Comment by JakeWharton** [comment]
You can also use an OkHttp interceptor.
