### ISSUE TITLE
Specific methods on SSL only

### ISSUE THREAD

**Issue by ivanviragine** [square/retrofit#932]
Is it possible to select some methods of an interface to run on HTTPS/SSL and some other methods on HTTP? I have a REST endpoint that has some sensitive data that needs to be on SSL, however, some other methods shouldn't, as they're retrieving only public data.

**Comment by artem-zinnatullin** [comment]
I see two solutions:

1. Build two RestAdapters with different endpoints (http and https). Also, you can wrap them into one via custom implementation of REST interface which will select proper endpoint for request.
2. You can replace http -> https per request via OkHttp "application" interceptor https://github.com/square/okhttp/wiki/Interceptors

P.S. SSL is not only about securing private data, it hides what content user receives/sends, speed of data loading can be critical, but I'd prefer SSL for everything as user.

**Comment by ivanviragine** [comment]
Thanks for the answer!

I got this solution 1, but found that I've ended up repeating too much code. Assuming http as default and using https via annotation seems like a cleaner way to do this. Also, the endpoint URL can be broken into peaces.
I'll take a look at solution 2.

The problem about securing all methods is speed... otherwise I would go for SSL all the way...

**Comment by artem-zinnatullin** [comment]
I am not sure that it'll work, but you can try to set endpoint in RestAdapter as empty string (really not sure, that Retrofit will allow it) and set full paths for the queries in the annotations and use http/https where required.

**Comment by ivanviragine** [comment]
I'll try this, but my idea was to use the endpoint, ie, as "google.com", then, @GET("/search"), it'll use as default "http://google.com/search" (default is always HTTP). If I add these annotations to another method, say, @HTTPS @GET("/login") (or @SSL), it'll use "https://google.com/login".
That way, the annotation will be used in a built in interceptor.

**Comment by artem-zinnatullin** [comment]
I understand, but it breaks concept of setting endpoint/BaseUrl as separate entity, because your annotated REST interface in fact is specification, which can be used for different endpoints (http/https) and probably, http/https should not be part of such specification.

But let's see what @swankjesse and @JakeWharton will say.

**Comment by JakeWharton** [comment]
You can put a [full URL in the annotation][1] with the version on `master`. That's the best you're going to get. The use case of switching schemes is rare and does not deserve an annotation. The alternative of using two service interfaces with two `RestAdapter` instances and two endpoints is also reasonable.

 [1]: https://github.com/square/retrofit/blob/fd76d5c2442d8171b682a9c65b1f778c82bb9b76/retrofit/src/test/java/retrofit/RequestBuilderTest.java#L883-L896

**Comment by ivanviragine** [comment]
Ok! Thanks!
