### ISSUE TITLE
Fix sample

### ISSUE THREAD

**Issue by maxml** [square/retrofit#933]
Your sample is nothing! I can't understand, how I can work with

**Comment by JakeWharton** [comment]
There's a website, tests, and two samples. If you have a specific problem that can be addressed we can, but such an open ended question is not appropriate for GitHub issues.

**Comment by maxml** [comment]
Please, update your samples with GET - and POST-requests. I can't start it with 1.9.0 version, they don't work. This is the reason I start Github issue
