### ISSUE TITLE
Calculate digest of raw payload before processing response

### ISSUE THREAD

**Issue by andrejvanderzee** [square/retrofit#934]
Hi,

I am looking for a way to calculate the digest (for example a 64bit encoded MD5 hash) of the raw payload before actually processing the response (i.e. parse the JSON, update database, etc). I want to be able to check if the payload actually changed from the previous call to the same endpoint. If it did not change, I want to abort processing the response immediately in order to safe battery on Android.

How can this be achieved by Retrofit?

Cheers,
Andrej

**Comment by JakeWharton** [comment]
It cannot. You'll need to use [OkHttp interceptors][1].

 [1]: https://github.com/square/okhttp/wiki/Interceptors
