### ISSUE TITLE
Retrofit class cannot be resolved

### ISSUE THREAD

**Issue by uNight** [square/retrofit#937]
Hi,
Recently I've added retrofit dependency to my project (also tried clean new project). Problem is that retrofit.Retrofit class cannot be resolved. I've checked retrofit-1.9.0.jar in graddle folder, downloaded same from maven, jcenter, your website - result is the same, all of them are missing Retrofit.class, Response.class... So what am I missing?

**Comment by JakeWharton** [comment]
Use `RestAdapter` instead. I didn't mean to deploy the website. Will revert.

**Comment by JakeWharton** [comment]
Fixed
