### ISSUE TITLE
RetrofitError.httpError Crash with null converter

### ISSUE THREAD

**Issue by danielgomezrico** [square/retrofit#940]
RetrofitError.httpError not have `@NonNull` for converter but if you pass a null it crash.

**Comment by JakeWharton** [comment]
All of the parameters to the factory methods for `RetrofitError` are required. Not checking for `null` eagerly is just an oversight.

Work is being done on v2.0 on `master` and `RetrofitError` has been removed so there's no action to take here. We don't expect to have another 1.9 release but instead will soon have a beta of 2.0.

**Comment by danielgomezrico** [comment]
I'm waiting that 2.0 release! thanks
