### ISSUE TITLE
Custom call adapter and reuse of default implementation classes

### ISSUE THREAD

**Issue by stephanenicolas** [square/retrofit#946]
Hi Retrofit team,

I am trying retrofit 2.0, and the embryo of API is nice, for now it solves pretty well the signature de-duplication problem (having to provide a sync / async service signature).

In our app, we would like to generalize an error management process. I mean that most of our endpoints can return an http error code and some JSON to provide details about the failure. 

Actually, I would think that a pretty nice place to do it would be to get a custom `Call`object whose execute method could throw exceptions, the exceptions wrapping the returned error JSON.

However, to achieve this, it would be nice to be able to extend default implementations of `Call` like `ExecutorCallbackCall`. I could delegate most cases to it with a decorator pattern, and handle special error cases in it. 

Is that the suggested best practice to create a common error management entity ? If so, could you make the default implementations classes public ?

Keep up the good work,
 S.

**Comment by JakeWharton** [comment]
You can already do this with a `CallAdapter.Factory`. There's examples of how `Observable` and `ListenableFuture` adaptations, but error handling would be done the same way.

**Comment by stephanenicolas** [comment]
Yeah, I got that. But then, do you mind making `ExecutorCallbackCall ` and its factory public so that they can be extended ?

**Comment by JakeWharton** [comment]
If it was public it would be a final type. Extending is not a suitable
approach, but delegation could work.

**Comment by stephanenicolas** [comment]
Thx I came up with this idea a few minute ago. I will try it soon and give
you some feedback (if you are interested).

2015-07-07 14:16 GMT-07:00 Jake Wharton <notifications@github.com>:

**Comment by xk009** [comment]
I want to know your idea to deal common error process。should you give me tips. thank you!

**Comment by xk009** [comment]
> Thx I came up with this idea a few minute ago. I will try it soon and give
> you some feedback (if you are interested).
I want to know your idea to deal common error process。should you give me tips. thank you!

**Comment by swankjesse** [comment]
`nextAdapter` FTW !
