### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by ikhthiandor** [square/retrofit#947]
I want to use [Sourcegraph](https://sourcegraph.com) for retrofit code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/square/retrofit. (It should only take 30 seconds.)

Thank you!

**Comment by JakeWharton** [comment]
There's a ton of these tools, and I don't see why it should require access to the repository. We get requests to enable all kinds of things from review systems to code coverage to cloud-based IDEs. Since this isn't a tool we use I don't see why I should give it access.
