### ISSUE TITLE
Retrofit doesn't trigger Subscriber onError when using custom ErrorHandler

### ISSUE THREAD

**Issue by ziem** [square/retrofit#952]
I'm using Retrofit 1.9.0, RxJava 1.0.10, RxAndroid 0.24.0 and OkHttp 2.4.0. When I'm setting custom ErrorHandler RxJava Subscriber `onError` method isn't triggered. Why? Is it possible to change this behaviour?

Output with ErrorHandler:
https://gist.github.com/ziem/b535959ad78bf68f8db5

Otuput without ErrorHandler:
https://gist.github.com/ziem/e716378d48acc09bf451 (`onError` is triggered)

More details: http://stackoverflow.com/questions/31073526/retrofit-doesnt-trigger-onerror-when-using-custom-errorhandler

**Comment by JakeWharton** [comment]
Can you write a test against 1.9.0 that demonstrates the behavior? I feel like [this test][1] proves that it does work.

 [1]: https://github.com/square/retrofit/blob/parent-1.9.0/retrofit/src/test/java/retrofit/ErrorHandlerTest.java#L89-L106

**Comment by tomxor** [comment]
Not sure how related this is but in case a runtime exception is thrown from within `handleError()` then `onError()` will not be invoked. @ziem can you double check that's not the case with your `handleError()` implementation?

**Comment by ziem** [comment]
@tomxor -![Facepalm](https://camo.githubusercontent.com/805ee37e1f5abcbbadcebbf6e5f1db89fa49efc0/687474703a2f2f6d793335307a2e636f6d2f666f72756d2f696d616765732f736d696c6965732f6661636570616c6d34323535303938372e676966), thanks :+1:. I removed this line from the code listing:

    Timber.e("Error: %s, %d", cause.getMessage(), cause.getResponse().getStatus());

`getResponse()` was causing `NullPointerException`... I overlooked it because there wasn't any log in logcat. Thanks for help.
