### ISSUE TITLE
LogLevel other than FULL causes java.lang.ClassCastException

### ISSUE THREAD

**Issue by Hedgehog-IT** [square/retrofit#953]
when I set my LogLevel to anything else than FULL get error
```
java.lang.ClassCastException: retrofit.client.OkClient$2 cannot be cast to retrofit.mime.TypedByteArray
```
in line
```
String str = new String(((TypedByteArray) response.getBody()).getBytes());
```

**Comment by JakeWharton** [comment]
What version? Can you write a simple test that we can run? There's tests for logging which show levels other than `FULL` working: https://github.com/square/retrofit/blob/parent-1.9.0/retrofit/src/test/java/retrofit/RestAdapterTest.java#L140-L231

**Comment by khafan** [comment]
I encountered the same problem. When setting LOG_LEVEL_BASIC
![loglevel_basic](https://cloud.githubusercontent.com/assets/2133782/9026234/134d2720-393d-11e5-9dc7-e0fc496bcfe9.png)
but on LOG_LEVEL_FULL 
![loglevel_full](https://cloud.githubusercontent.com/assets/2133782/9026235/2a9f4afc-393d-11e5-9cb1-468f8d9a7323.png)

Regarding this issue what way you suggest to getting the response body as string?

**Comment by radodr** [comment]
Hi,
I have the same problem with non-debug version of my code with LOG_LEVEL_NONE. I have to make separate Logger with empty output:

Gson gson = new GsonBuilder().setDateFormat("d.m.yyyy")						.setFieldNamingPolicy(FieldNamingPolicy.LOWER_CASE_WITH_UNDERSCORES)
.create();
RestAdapter.Builder restAdapterBuilder = new RestAdapter.Builder()
						.setErrorHandler(new ErrorRetrofitHandlerException())
						.setClient(new OkClient(new OkHttpClient()))
						.setConverter(new GsonConverter(gson))
						.setEndpoint(BuildConfig.SERVER_URL)
						.setRequestInterceptor(new RequestInterceptor() {
							@Override
							public void intercept(RequestFacade request) {
								request.addHeader("Accept", "text/html");
								request.addHeader("User-Agent", ParfemPlusAdapter.class.getSimpleName());
							}
						});
				if (BuildConfig.DEBUG) {
					restAdapterBuilder
							.setLogLevel(RestAdapter.LogLevel.FULL)
							.setLog(new AndroidLog("PPlus REST:"));
				} else {
					RestAdapter.Log fooLog = new RestAdapter.Log() {
						@Override public void log(String message) {
						}
					};
restAdapterBuilder
							.setLog(fooLog)
							.setLogLevel(RestAdapter.LogLevel.FULL);
				}
				service = restAdapterBuilder
						.build()
						.create(ParfemPlusService.class);

I use these versions:
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'com.squareup.okhttp:okhttp:2.3.0'

I saw test cases, but I don't understand why in my code it works different.

**Comment by cortexdesign** [comment]
Same issue!
I need the response body for custom offline cache, but when i leave the log level as default, I got an TypeCastException.
 String bodyString = new String(((TypedByteArray) response.getBody()).getBytes());

**Comment by bagintz** [comment]
We are also having this issue when setting the log level to NONE

**Comment by shliama** [comment]
Same issue with release build & log level NONE.

**Comment by sacot41** [comment]
same issue in release build with log level NONE.

**Comment by naman14** [comment]
Same issue with log level basic, please look into this

**Comment by gbIxaHue** [comment]
only with log lelve FULL i got normal work without exception in 1.9.0
java.lang.ClassCastException: retrofit.client.OkClient$2 cannot be cast to retrofit.mime.TypedByteArray

restApi.getUserfiles(url).getBody()).getBytes()

fix this issue plz

**Comment by fernandospr** [comment]
Same issue here using:

compile 'com.squareup.okhttp:okhttp:2.4.0'
compile 'com.squareup.retrofit:retrofit:1.9.0'

when using LogLevel.NONE works ok, with LogLevel.FULL a class cast exception happens.

**Comment by lagurohit** [comment]
restAdapterBuilder = new RestAdapter.Builder()
		.setLogLevel(LogLevel.NONE)	
		.setClient(client)
		.setRequestInterceptor(objRequestInterceptor)
		.setEndpoint(strEndPoint)
		.build();

Same error

**Comment by MiguelCatalan** [comment]
Same here when using LogLevel.NONE
