### ISSUE TITLE
Response interceptor?

### ISSUE THREAD

**Issue by hbmartin** [square/retrofit#956]
Hello, thanks for this fantastic library!

Is there a way to request the ability to set a response interceptor? Analogous to the request interceptor, I would like be able to do some processing on the response before passing it along. In particular, I want to extract my object array from a metadata wrapper object.

Thanks.

**Comment by troyjperales** [comment]
There is not a ResponseInterceptor, but if you are using Gson for serialization, you can implement a ```TypeAdapter``` that achieves what you would like. See https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/TypeAdapter.html.

You can register the ```TypeAdapter``` with your ```GsonBuilder``` before setting it as the ```retrofit.converter.Converter```.
```
GsonBuilder gsonBuilder = new GsonBuilder();
gsonBuilder.registerTypeAdapter(SomeClass.class, new MetadataWrapperTypeAdapter());
Gson gson = gsonBuilder.create();

RestAdapter adapter = new RestAdapter.Builder()
    .setConverter(new GsonConverter(gson))
    ...
    .build();
```
 If you aren't using Gson, something similar can be achieved for other serialization alternatives.

**Comment by JakeWharton** [comment]
Having the converter to do this (or Converter.Factory in v2) is the right way. There's more info and example code on https://github.com/square/retrofit/issues/1076.
