### ISSUE TITLE
RequestInterceptor for Post Parameters

### ISSUE THREAD

**Issue by FabianTerhorst** [square/retrofit#957]
Hello,

is there any way to add post parameters in the RequestInterceptor so that i dont have to add @Field() more then needed on every api post.

**Comment by radzio** [comment]
+1

**Comment by NAYOSO** [comment]
Do you mean the OkHttp Interceptor? Because I think Retrofit already have it's RequestInterceptor removed at #839

**Comment by JakeWharton** [comment]
We're not going to support this for two reasons:
 * The content type of a request body is not always url-encoded so having that API would require a much larger API to query information about the request. But,
 * `RequestInterceptor` has been removed in v2.0 in favor of [OkHttp's interceptors][1]. Interceptors have full access to all information about a request and allow you to do things like prepend a set of constant form fields onto the body.

 [1]: https://github.com/square/okhttp/wiki/Interceptors

**Comment by FabianTerhorst** [comment]
@JakeWharton how can i add new parameters without override the old. 
```
 client.interceptors().add(new Interceptor() {
            @Override
            public Response intercept(Chain chain) throws IOException {
                Request request = chain.request();
                Request.Builder requestBuilder = request.newBuilder();
                RequestBody requestBody = new FormEncodingBuilder()
                        .add("...", "...")
                        .add("...","...")
                        .add("...", "...")
                        .add("...", "....")
                        .build();
                Request newRequest = requestBuilder
                        .post(requestBody)
                        .build();
                return chain.proceed(newRequest);
            }
        });
```

**Comment by Filipews** [comment]
Even though this is old, for anyone whos stumbles upon this, I guess you could use:
```
@Override
public Response intercept(Chain chain) throws IOException {
	Request request = chain.request();
	Builder formBuilder = getNewBuilder((FormBody)request.body());
	chain.proceed(request.newBuilder().post(formBuilder.build()).build());
}

FormBody.Builder getNewBuilder(FormBody body) {
	final FormBody.Builder builder = new FormBody.Builder();

	for (int i = 0; i < body.size(); i++) {
		builder.add(body.name(i), body.value(i));
	}

	//Add new parameters
	builder.add("ParamName", "ParamValue");
	return builder;
}
```
