### ISSUE TITLE
Additional parameter annotations not ignored.

### ISSUE THREAD

**Issue by hastebrot** [square/retrofit#959]
Hey, I'm using Retrofit 2.0.0-SNAPSHOT.

My REST service interface is written in Kotlin and Kotlin seems to always add an extends-wildcard to generics.

Retrofit complains with

>Exception in thread "main" java.lang.IllegalArgumentException: Method return type must not include a type variable or wildcard: retrofit.Call&lt;java.util.List&lt;? extends retrofit.Repo>>

My Kotlin code is

~~~kotlin
interface GitHubService {
    @GET("/users/{user}/repos?per_page=1")
    fun listRepos(@Path("user") user: String,
                  @Query("page") page: Int): Call<List<Repo>>

    @GET("/users/{user}/repos?per_page=1")
    fun listRepos(@Path("user") user: String,
                  @Query("page") page: Int,
                  callback: Callback<List<Repo>>)
}
~~~

I wonder whether the check for the wildcards is necessary.

**Comment by swankjesse** [comment]
That's completely broken. a `Call<List<? extends Repo>>` is definitely not the same thing as a `Call<List<Repo>>`. The former `List` cannot receive a call to `add()` of anything but null; the latter can.

Is there a Kotlin bug for this?

**Comment by hastebrot** [comment]
I've found this: https://youtrack.jetbrains.com/issue/KT-5792

**Comment by hastebrot** [comment]
I guess this is unrelated and the new Retrofit API requires me to explicitely define a `Converter`.

**Comment by swankjesse** [comment]
Yup.

**Comment by JakeWharton** [comment]
Right. We no longer use any converter as a default. You can add a dependency to `converter-gson` and just do `.converterFactory(GsonConverterFactory.create())` when you create the Retrofit instance.

As to the Kotlin stuff, I guess this will just serve as a recommended practice.

**Comment by hastebrot** [comment]
Already got it, thanks! I use `compile "com.squareup.retrofit:converter-moshi:2.0.0-SNAPSHOT"` and `.converterFactory(MoshiConverterFactory.create())`.

Another error is

>Exception in thread "main" java.lang.IllegalArgumentException: Multiple Retrofit annotations found, only one allowed. (parameter #1) for method GitHubService.listRepos

for this interface

~~~kotlin
interface GitHubService {
    @GET("/users/{user}/repos?per_page=1")
    fun listRepos(@Path("user") user: String,
                  @Query("page") page: Int): Call<MutableList<Repo>>
}
~~~

Sorry for posting this unrelated error. But I don't understand the error message, found no solution in the changeset that introduced this error check and it even complains with only a single Retrofit annotation.

**Comment by JakeWharton** [comment]
It somehow sees two annotations on a single parameter. I'll have to try it tomorrow unless you can run `javap -c` on the class file and post it.

**Comment by hastebrot** [comment]
`javap -c GitHubService.class`:

~~~
Compiled from "retrobug.kt"
public interface retrobug.GitHubService {
  public static final kotlin.reflect.KClass $kotlinClass;

  static {};
    Code:
       0: ldc           #2                  // class retrobug/GitHubService
       2: invokestatic  #38                 // Method kotlin/jvm/internal/Reflection.createKotlinClass:(Ljava/lang/Class;)Lkotlin/reflect/KClass;
       5: putstatic     #40                 // Field $kotlinClass:Lkotlin/reflect/KClass;
       8: return

  public abstract retrofit.Call<java.util.List<retrobug.Repo>> listRepos(java.lang.String, int);
}
~~~

`javap -c GitHubService$$TImpl.class`:

~~~
Compiled from "retrobug.kt"
public final class retrobug.GitHubService$$TImpl {
}
~~~

**Comment by hastebrot** [comment]
It definately worked with the same interface in Kotlin (minus the usage of `Call`) and Retrofit 1.9.0.

**Comment by hastebrot** [comment]
I adapted the `SimpleService` sample [1] to Kotlin and set to I set a breakpoint to a line in `RequestFactoryParser#parseParameters()` [2].

![retrofit-bug-01](https://cloud.githubusercontent.com/assets/496255/8691233/1768e636-2ac0-11e5-8a94-bcea656eb543.png)

Seems that the `IllegalArgumentException` is due to the additional Kotlin annotation `
@JetValueParameter`.

[1] https://github.com/square/retrofit/blob/904bf94b7c/samples/src/main/java/com/example/retrofit/SimpleService.java#L25
[2] https://github.com/square/retrofit/blob/bf02efdf30/retrofit/src/main/java/retrofit/RequestFactoryParser.java#L208

-----

~~~kotlin
import retrofit.Call
import retrofit.MoshiConverterFactory
import retrofit.Retrofit
import retrofit.http.GET
import retrofit.http.Path

data class Contributor(val login: String,
                       val contributions: Int)

interface GitHubService {
    @GET("/repos/{owner}/{repo}/contributors")
    fun contributors(@Path("owner") owner: String,
                     @Path("repo") repo: String): Call<MutableList<Contributor>>
}

fun main(args: Array<String>) {
    val retrofit = Retrofit.Builder()
        .baseUrl("https://api.github.com")
        .converterFactory(MoshiConverterFactory.create())
        .build()

    val service = retrofit.create(javaClass<GitHubService>())

    val response = service.contributors("square", "retrofit").execute()
    response.body().forEach { println(it) }
}
~~~

**Comment by JakeWharton** [comment]
Looks like a simple bug. We should be ignoring annotations we don't recognize.

**Comment by hastebrot** [comment]
Updated to the newest snapshot. Everything works fine.

Small note: I got an error that "service methods cannot return void". Obviously the approach with `Callback` as method argument is superseded by `Call` that also allows `Callback` using `enqueue()`. This seems to be a great API change in order to improve testability.
