### ISSUE TITLE
Default Callback Executor for Retrofit 2.0

### ISSUE THREAD

**Issue by alexmprog** [square/retrofit#962]
Hello, guys

I have one question about default callback executor.
For example I have 3 different BaseUrl  like "myservice.com","myservice1.com","myservice2.com". I also have 3 api services -  Service1API, Service2API,Service3API .

For using this services I created 3 Retrofit object with Default CallbackExecutor.

```
static class MainThreadExecutor implements Executor {
      private final Handler handler = new Handler(Looper.getMainLooper());

      @Override public void execute(Runnable r) {
        handler.post(r);
      }

      @Override public String toString() {
        return "MainThreadExecutor";
      }
    }
```

If I correctly understand this Executor works in UI thread - it mean that all callbacks will be run in UI thread.

In my case it mean that for 3 different Retrofit object will use only 1 UI Thread with Handler.
But I can add custom Executor for my Retrofit objects like this:
```
private static final int CPU_COUNT = Runtime.getRuntime().availableProcessors();
    private static final int CORE_POOL_SIZE = CPU_COUNT + 1;

    public static final Executor THREAD_POOL_EXECUTOR
            = Executors.newFixedThreadPool(CORE_POOL_SIZE);

private static final Retrofit RETROFIT_MAIN = new Retrofit.Builder().baseUrl
            (sMainBaseUrl).client(generateNewOkClient(sMainBaseUrl.getUrl()))
      .converterFactory(GsonConverterFactory.create(gsonBuilder)).callbackExecutor(THREAD_POOL_EXECUTOR).build();
```

In this case all callbacks won't be run in UI Thread.
I only want  check my logic - did I correctly understand how does Default CallbackExecutor work?

**Comment by JakeWharton** [comment]
You have understood this correctly!

We know documentation is lacking as we've been focused on feature development but it will be improved in the coming weeks.
