### ISSUE TITLE
Dynamic request Parameters for Multipart

### ISSUE THREAD

**Issue by nishantgshah** [square/retrofit#964]
I want to add multipart support with multiple images (Part name ("profilePic") will be decided dynamically). It will accept maximum 6 images. SimplePhotoRequestImpl class is working with single images. When I am trying to add multiple images with MultiplePhotoRequestImpl class, it is not working. I am passing parameter name of Part as a key in QueryMap.

        
public interface SimplePhotoRequestImpl {
        
        @Multipart
        @POST("/xyz/abc/update")
        void doRequest(@Part("profilePic") TypedFile photo,
                       @Part("parameters") TypedString in, Callback<Response> callback);
}

           
public interface MultiplePhotoRequestImpl {

        @Multipart
        @POST("/xyz/abc/update")
        void doRequest(@QueryMap Map<String, TypedFile> photos,
                       @Part("parameters") TypedString in, Callback<Response> callback);
    }

**Comment by JakeWharton** [comment]
`@QueryMap` is for the URL's query parameters. You can use `@PartMap` if the names are different. Unfortunately we didn't support passing an iterable object like `List` in the current released version, but that's already been fixed on `master` and will be present in the next release.
