### ISSUE TITLE
OutOfMemory when LogLevel.FULL if uploading large files

### ISSUE THREAD

**Issue by brunovinicius** [square/retrofit#965]
RestAdapter class, line 444
log.log(new String(bodyBytes, bodyCharset));

Raises OOM error if uploading large files. 
This line is essentially forcing twice the file size into the memory at the same time.

**Comment by JakeWharton** [comment]
Don't use FULL on binary files let alone ones of great size. There's nothing we can really do here...

Logging is currently being overhauled for v2.0 which is being tracked by #378.

**Comment by brunovinicius** [comment]
I see your point, but I kinda disagree. I think you should really be eager error checking for potential output larger than an pre-defined threshold. Just dont log body past 2mb or something like that. Just truncate the output and append a "Body was truncated, x bytes ignored" message. Than later you could let us define what is the threshold, maybe... "There's nothing we can do" is not really accurate. 

Anyways I hope #378 is tackling such problems. Thanks!
