### ISSUE TITLE
Different intercepters for Service interfaces on Retrofit 2.0

### ISSUE THREAD

**Issue by baoti** [square/retrofit#966]
Can I use different intercepters for two api instances, but sharing same OkHttpClient?

For example:

...

    public AccountAuthenticator(Context context) {
        super(context);
        passwordInterceptor = new PasswordInterceptor();
        OkHttpClient client = new OkHttpClient();
        client.interceptors().add(passwordInterceptor);
        this.api = new Retrofit.Builder()
                .baseUrl(GitHubApi.API_URL)
                .client(client)
                .callAdapterFactory(ObservableCallAdapterFactory.create())
                .converterFactory(GsonConverterFactory.create())
                .build()
                .create(GitHubApi.class);
    }

    public GitHubSource(GitHubTokenInterceptor interceptor) {
        this.tokenInterceptor = interceptor;
        OkHttpClient client = new OkHttpClient();
        client.interceptors().add(interceptor);
        api = new Retrofit.Builder()
                .baseUrl(GitHubApi.API_URL)
                .client(client)
                .callAdapterFactory(ObservableCallAdapterFactory.create())
                .converterFactory(GsonConverterFactory.create())
                .build()
                .create(GitHubApi.class);
    }
...

For retrofit 1.9.1, I known I can do it.

**Comment by JakeWharton** [comment]
You can `.clone()` the `OkHttpClient` which creates a shallow copy.
```java
OkHttpClient sharedClient = new OkHttpClient();

OkHttpClient accountClient = sharedClient.clone();
accountClient.interceptors().add(accountInterceptor);
Retrofit accountRetrofit = new Retrofit.Builder()
    // ...
    .client(accountClient);
    .build();
AccountService accountService = accountRetrofit.create(AccountService.class);

OkHttpClient gitHubClient = sharedClient.clone();
gitHubClient.interceptors().add(gitHubInterceptor);
Retrofit gitHubRetrofit = new Retrofit.Builder()
    // ...
    .client(gitHubClient);
    .build();
GitHubService gitHubService = gitHubRetrofit.create(GitHubService.class);
```

**Comment by baoti** [comment]
:+1: Looks nice. Thanks very much!
