### ISSUE TITLE
PUT request with a body?

### ISSUE THREAD

**Issue by lfdversluis** [square/retrofit#967]
I'm trying to perform [this PUT request](https://github.com/justintv/Twitch-API/blob/master/v3_resources/channels.md#put-channelschannel).

I got the following lines defined:

```
@PUT("/channels/{channel}")
    void updateChannel(
            @Query("oauth_token") String OAuthToken,
            @Path("channel") String channel,
            @Body TypedJSONString body,
            Callback<TwitchChannel> cb
    );
```

Where ``TypedJSONString`` is just a ``TypedString`` that returns ``"application/json"`` as mime type.

However, this returns ``retrofit.RetrofitError: 400 Bad Request``. Why?

**Comment by danielgomezrico** [comment]
@lfdversluis  As a suggestion... you can use http://cellist.patr0n.us/ or http://www.charlesproxy.com/ as proxy to see what´s going to the server and what it response.

**Comment by JakeWharton** [comment]
Ah HTTP 400 response means that it reaches your server and the server rejects the request. This means that either your request is not in the format the server expects or the server has a bug. Either way, this isn't a problem with Retrofit itself, just a problem between you and your remote server.
