### ISSUE TITLE
Support rx.Single from RxJava?

### ISSUE THREAD

**Issue by plastiv** [square/retrofit#969]
With `rx.Single` released as experimented type of `Observable` do you see the value in supporting it as a return type for network requests?
https://github.com/ReactiveX/RxJava/blob/1.x/CHANGES.md#rxsingle
https://github.com/ReactiveX/RxJava/issues/1594#issuecomment-101300655

Quote from there:
```
A Single will always behave in one of 3 ways:

1) respond with an error
2) never respond
3) respond with a success

An Observable on the other hand may:

1) response with an error
2) never respond
3) respond successfully with no data and terminate
4) respond successfully with a single value and terminate
5) respond successfully with multiple values and terminate
7) respond successfully with one or more values and never terminate (waiting for more data)
```

**Comment by JakeWharton** [comment]
We are aware and it may be added. It's experimental nature adds a level of
volatility that if we choose to add it as the API may change in a
backwards-incompatible way.

**Comment by svenjacobs** [comment]
+1 for `Single` :)
