### ISSUE TITLE
How to upload a image by using multipart

### ISSUE THREAD

**Issue by wenjiang** [square/retrofit#970]
if i want to upload a image,how to do

**Comment by wenjiang** [comment]
@JackDanger

**Comment by wenjiang** [comment]
@alexxv

**Comment by JakeWharton** [comment]
Specify a `TypedInput` parameter, create a `TypedFile` or `TypedByteArray`, pass it as the argument.

GitHub is for bugs and feature requests. For usage please ask questions on StackOverflow with the 'retrofit' tag. It's a much better community and location for interactive problem solving and archival of solutions.
