### ISSUE TITLE
When using a profiler getResponse on failure error.getResponse returns null

### ISSUE THREAD

**Issue by eduardocucharro** [square/retrofit#971]
Hello guys, I'm new to android and retrofit but when I use a profiler with Crashlytics on my adapter for some reason the error.getResponse over failure event returns null, is this a bug? See my code below:

public static Profiler createCrashlyticsProfiler() {
        return new Profiler() {
            @Override
            public Object beforeCall() {
                return null;
            }

@Override
public void afterCall(RequestInformation requestInfo, long elapsedTime, int statusCode, Object beforeCallData) {
                if (Fabric.isInitialized() && statusCode != 200) {
                    Crashlytics.setInt("statusCode", statusCode);
                    Crashlytics.setString("method", requestInfo.getMethod());
                    Crashlytics.setString("baseUrl", requestInfo.getBaseUrl());
                    Crashlytics.setString("path", requestInfo.getRelativePath());
                    Crashlytics.getInstance().crash();
                }
            }
        };
    }

 RestAdapter restAdapter = new RestAdapter.Builder()
                .setLogLevel(RestAdapter.LogLevel.FULL)
                .setEndpoint(DSUrl.getSubscriptionAPIUrl())
                .setErrorHandler(new SubmitPaymentErrorHandler())
                .setRequestInterceptor(requestInterceptor)
                .setProfiler(createCrashlyticsProfiler())
                .setConverter(new GsonConverter(gson))
                .build();

**Comment by JakeWharton** [comment]
If `beforeCall` or `afterCall` throw an exception then the `Response` will not be passed along. That's the only way that this could happen, something in your `afterCall` is throwing an exception.

The `Profiler` type is gone in Retrofit v2, and instead we emphasize using [OkHttp interceptors][1] which are much more powerful. If you're already using OkHttp with Retrofit v1 I would suggest migrating to them.

 [1]: https://github.com/square/okhttp/wiki/Interceptors

**Comment by eduardocucharro** [comment]
Thank you  Jake.
