### ISSUE TITLE
PUT call body getting lost

### ISSUE THREAD

**Issue by wasaig** [square/retrofit#972]
In some PUT calls, request body is getting lost and not reaching server. 
I can see the body contents in logs but its not reaching server.
I am using Android 4.2 and Retrofit v1.9, OkHttp v2.0

**Comment by JakeWharton** [comment]
There is no information available here to diagnose a problem, if any. Consider using something like Charles Proxy to determine what is being sent across the wire (Retrofit's logs are a best-guess, not the actual bytes sent across the wire). You'll also want to provide information like your interface declaration and any other information such as how you are configuring your RestAdapter.

But that said, GitHub issues are for bugs and feature requests only. Usage problems are best served on StackOverflow which is a much more active, searchable, and correctly archived community. We monitor the 'retrofit' tag and answer questions all the time.

**Comment by goonerDroid** [comment]
This issue still persists in V2.1.0!
