### ISSUE TITLE
NTLM authentication

### ISSUE THREAD

**Issue by kiotto** [square/retrofit#973]
Hello,

This library supports authentication NTLM?

I began a search and found no information about it

Thank You,

Best regards

Kiotto

**Comment by JakeWharton** [comment]
No. Authentication must be handled at the application level above Retrofit or using something like OkHttp's [interceptors][1] or [authenticator][2].

 [1]: https://github.com/square/okhttp/wiki/Interceptors
 [2]: http://square.github.io/okhttp/javadoc/com/squareup/okhttp/Authenticator.html
