### ISSUE TITLE
Website still shows old documentation with RestAdapter.Builder()

### ISSUE THREAD

**Issue by shauvik** [square/retrofit#975]
Please push website to gh-pages
http://square.github.io/retrofit/

Diff: http://www.diffnow.com/?report=r4z81

**Comment by JakeWharton** [comment]
The website shows the latest release.

**Comment by shauvik** [comment]
@JakeWharton Are you sure? 

Your commit 30f317 seems to have reverted the changes back to the older version. 
https://github.com/square/retrofit/commits/gh-pages

On http://square.github.io/retrofit/ I still see the RestAdapter class instead of Retrofit.
