### ISSUE TITLE
Where is `TypedFile` in 2.0.0?

### ISSUE THREAD

**Issue by baoti** [square/retrofit#982]
Can you add a sample for uploading a file on retrofit 2.0.0?
Thanks!

**Comment by JakeWharton** [comment]
Use RequestBody

**Comment by baoti** [comment]
Ah, the doc of `Part.java` says:

```
 * <p>
 * <pre>
 * &#64;Multipart
 * &#64;POST("/")
 * void example(&#64;Part("description") String description,
 *              &#64;Part("image") TypedFile image,
 *              ...
 * );
 * </pre>
 * <p>
```

**Comment by JakeWharton** [comment]
There's a _ton_ of outdated documentation on `master`. The code is changing too fast to warrant constantly keeping it up-to-date. In a month or so we'll go through and ensure things are correct. If you are using the latest snapshots your best bet is to look at the tests for how to do things like this.

**Comment by Dcodechef** [comment]
@JakeWharton   
Is this correct to create request body for wav file?
RequestBody body = RequestBody.create(MediaType.parse("audio/*"), file);
        return body;
I am getting unsupported Media format

**Comment by sudeeps-r** [comment]
@JakeWharton 

Am getting nullpointer exception while creating the requestbody object, please check the attached log 
----------------------------------------------------------------------
 RequestBody file=RequestBody.create(MediaType.parse("image/*"),new File(userAction.imagePath));

-------------------------------------------------------------------
java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.nio.charset.Charset)' on a null object reference
                                                                          at com.squareup.okhttp.RequestBody.create(RequestBody.java:55) 
---------------------------------

**Comment by SufianBabri** [comment]
@sudeeps-r  please create a new issue and mention which library and version you're using.
