### ISSUE TITLE
Retrofit and Centralized Error Handling

### ISSUE THREAD

**Issue by mahmoud-elnaggar** [square/retrofit#983]
each request to server may return error_code I want to handle these error in one place when I was useing AsyncTask I had a BaseAsyncTask like that

    public abstract class BaseAsyncTask<Params, Progress, Result> extends AsyncTask<Params,         Progress, Result> {

    protected Context context;
    private ProgressDialog progressDialog;
    private Result result;

    protected BaseAsyncTask(Context context, ProgressDialog progressDialog) {
        this.context = context;
        this.progressDialog = progressDialog;
    }

    @Override
    protected void onPreExecute() {
        super.onPreExecute();
    }

    @Override
    protected void onPostExecute(Result result) {
        super.onPostExecute(result);
        HttpResponse<ErrorResponse> response = (HttpResponse<ErrorResponse>) result;
     if(response.getData().getErrorCode() != -1) {
                handleErrors(response.getData());
        }else 
            onResult(result);

    }

    private void handleErrors(ErrorResponse errorResponse) {
    }
     public abstract void onResult(Result result);
    }
but using retrofit each request has its error handling callback

         git.getFeed(user,new Callback<gitmodel>() {
         @Override
         public void success(gitmodel gitmodel, Response response) {
         }
         @Override
          public void failure(RetrofitError error) {

                    }
                });
            }
        });
How I can handle all errors in one place ??
Sorry guys I have already written this question to SO but I didn't get any answer till now so I hope to get help here

**Comment by k-nar** [comment]
why not use the exact same pattern as your BaseAsyncTask but with Callback 

public abstract class BaseCallback<T> implements Callback<T>
{
 public abstract void onResult(T model);
 @Override
      public void failure(RetrofitError error) {
               handleErrors(error);  
       }
 @Override
     public void success(T model, Response response) {
           onResult(model)
     }
  private void handleErrors(ErrorResponse errorResponse) {
}
}

**Comment by mahmoud-elnaggar** [comment]
Yes ,you are right I have to integrate my pattern with Callback
