### ISSUE TITLE
Read parameters from response URL

### ISSUE THREAD

**Issue by cooperkong** [square/retrofit#984]
Hi, 
thanks for the great library. I have a question here and it may seems silly to ask.
The library works fine overall until the point when I'm trying to read several parameters from the return URL. For exapmle on the web browser:
1. type "http://foobar.com/"
2. Hit enter
3. it becomes "http://foobar2.com/abc=123"
Now the question is how do I get that "abc=123" value from retrofit response. Thanks heaps!

**Comment by JakeWharton** [comment]
You can get the URL by using `Response` as a type instead of `User` (or whatever). Then just call `getUrl()` on it.

The next version wraps response types in a parameterized `Response` object which will always carry response url, headers, etc. information along with the converted type.

**Comment by cooperkong** [comment]
That's weird . Because what I get from getUrl() is the request URL(http://foobar.com in my example) in the Response object not the actual modified url.
Cheers,

**Comment by JakeWharton** [comment]
If the server is issuing a 301 or 302 redirect then it's the underlying HTTP client's job to follow that redirect before returning to Retrofit. What does the status code say?

**Comment by cooperkong** [comment]
Hi Jake,
From the Retrofit log, it's printing 200 OK only.
---> HTTP GET http://....
D/Retrofit﹕ ---> END HTTP
D/Retrofit﹕ <--- HTTP 200 http://.....
D/Retrofit﹕ Content-Type: text/html; charset=utf-8
...

**Comment by JakeWharton** [comment]
Then I'm not sure what you are seeing in your browser. Perhaps the website is doing redirects based on the `User-Agent` of the browser or something.
