### ISSUE TITLE
How to SET/GET custom HTTP REQUEST / RESPONSE Headers

### ISSUE THREAD

**Issue by waqary705** [square/retrofit#992]
I want to send custom header to server and also want to receive custom header from Server  . for example server send me status code 404 but i want its status text "NOT FOUND" in header???

**Comment by JakeWharton** [comment]
Use `@Headers` on the method for static headers, `@Header` on a method parameter, or a `RequestInterceptor` on the `RestAdapter` for adding to every request.

Usage questions are best asked on StackOverflow with the 'retrofit' tag. These issues are for feature requests and bug reports only.
