### ISSUE TITLE
Any way to download file as .zip with retrofit callback

### ISSUE THREAD

**Issue by NorbertSzydlowski** [square/retrofit#993]
Is any way to download file as .zip with retrofic callback?

I try 
 void downloadDatabase(@Path("dbName") String databaseName, Callback<Response> callback);

but it was return java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING

**Comment by JakeWharton** [comment]
That exception is from Gson which is trying to parse your database (I guess) as a JSON object. Perhaps you are using the wrong `Response` type? Try `ResponseCallback` to ensure it correct detects that it should not deserialize the data.

Usage questions like this are great for StackOverflow under the 'retrofit' tag where they are seen and can be answered by a much larger audience than the few who manage these issues.
