### ISSUE TITLE
Hnadshake Failed ECONNRESET (Connection reset by peer)

### ISSUE THREAD

**Issue by sohilmemon** [square/retrofit#994]
I am using retrofit for a simple "soundCloud" api call and it gives me error.

Api: http://api.soundcloud.com/tracks?cliend_id=44c0d423bb154343e1936bbc4528ba65&q=blood+on+my+hands

**Comment by JakeWharton** [comment]
This is a normal exception that occurs when talking over a network. The server disconnected from your connection for some reason.

**Comment by sohilmemon** [comment]
The problem is when I download something it's working fine, but when I call the retrofit function, I get stuck and getting this error.

**Comment by JakeWharton** [comment]
This is a transport error, not a Retrofit error. The low-level socket is
throwing the exception. If you sent the HTTP request manually the same way
Retrofit does you would see the same thing.
