### ISSUE TITLE
Append value to header in RequestFacade

### ISSUE THREAD

**Issue by MGaetan89** [square/retrofit#995]
`RequestFacade` allows us to add various data to our request.

In my app, I am setting a custom header with `requestFacade.addHeader("X-NAME", "Value")`. My problem is that I may set this header multiple time for a single request. Retrofit supports this by setting the header multiple times.
I know that the specifications allow this, if the value are comma-separated. However, in my case, each value is separated with a `&` and I can not change the server behaviour.

What I would like is appending the header to the existing one. Something like `requestFacade.appendHeader("X-NAME", "Value")`. Unless there is already a way to do this?

**Comment by caseykulm** [comment]
So you want something like `X-NAME: Value1 & Value2 & etc` for a header?

**Comment by MGaetan89** [comment]
Yes, exactly.
But I am not calling `addHeader()` in the same part of my application (some headers can be added by external developers with callbacks).

**Comment by caseykulm** [comment]
`requestFacade.appendHeader("X-NAME", combinedValue)` can still work for you. You will just need to manage generating that `combinedValue` string. Have the external developers be able to add an array of strings rather than being able to set the value itself.

**Comment by MGaetan89** [comment]
That's what I thought. I just wanted to make sure that there is nothing in Retrofit that handles that automatically.
Thanks for your answers

**Comment by JakeWharton** [comment]
You can use an [OkHttp interceptor][1] for this. It allows reading the value and conditionally appending. Retrofit is moving to push more things into OkHttp and as such the interceptor functionality has been removed for v2.

 [1]: https://github.com/square/okhttp/wiki/Interceptors
