### ISSUE TITLE
Enums serialisation in @Part parameters

### ISSUE THREAD

**Issue by alex-shpak** [square/retrofit#996]
Hi guys. In my service I have
```
@Multipart
@POST("/images/")
void postImage(@Part("file") TypedOutput image, @Part("image_type") Image.ImageType type, Callback<Image> cb);
```
Where `Image.ImageType` is enum
```
public enum ImageType {
    attachment, cover, avatar
}
```
Unfortunately enums serializing using `Converter.toBody(object)` which converting it as JSON string, what is correct according to the [docs](http://square.github.io/retrofit/javadoc/retrofit/http/Part.html)

Converting as JSON string means that `GSON` adding leading and trailing quotes to the value, 
So, is there possibility or workaround to serialize enums as `toString()` value?

I can't use `TypeAdapter` in `GSON` for enums because it will break serialization in other places.
And I would like to avoid calling `Image.ImageType.attachment.name()` each time.

Such usage of enums works okay for `@Query` and `@Field` since it using `String.valueOf()`

**Comment by JakeWharton** [comment]
This is covered by #626 targeted for v2.

**Comment by JakeWharton** [comment]
Actually, you can handle this in v2 with a custom `Converter.Factory` that handles instances of `Enum<?>` and calls either `.name()` or `.toString()`.
```java
public final class EnumConverterFactory implements Converter.Factory {
  private static final MediaType PLAIN = MediaType.parse("text/plain");
  
  @Override public Converter<?> get(Type type, Annotation[] annotations) {
    if (!(type instanceof Class<?>)) {
      return null;
    }
    Class<?> cls = (Class<?>) type;
    if (!Enum.class.isAssignableFrom(cls)) {
      return null;
    }
    return new Converter<Enum<?>>() {
      @Override public Enum<?> fromBody(ResponseBody body) throws IOException {
        throw new UnsupportedOperationException();
      }

      @Override public RequestBody toBody(Enum<?> value) {
        return RequestBody.create(PLAIN, value.name());
      }
    };
  }
}
```
